### PR TITLE
[Emhancement] BufferedReader in HelpMoudle need be closed automaticly

### PR DESCRIPTION
**Pull request by xuzifu666**
Fixes #issue

## What type of PR is this:
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4

### CODE REVIEW

**Comment by imay** [comment]
HelpModule is not needed anymore, could you please remove it?

**Comment by xuzifu666** [comment]
> HelpModule is not needed anymore, could you please remove it?

OK，got it~ @imay

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 3 / 3 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/HelpModule.java|3|3|100.00%|[]|

**Comment by xuzifu666** [comment]
refactor it need change much files， need consider more detail，close it firstly.

**Pull request closed without merging**
