### PR TITLE
[Doc] Fix typo of `Aggregate table` in docs TOC

### PR DESCRIPTION
**Pull request by bowenliang123**
## What type of PR is this:
- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [x] Doc
- [ ] Tool

## Which issues of this PR fixes:

Fixes #

## Problem Summary(Required):

- fix the typo in docs TOC, `Aggragete table` should be `Aggregate table`

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 3.0
  - [x] 2.5
  - [x] 2.4
  - [x] 2.3

### CODE REVIEW

**Review by imay — APPROVED** [review]

**Comment by imay** [comment]
@bowenliang123 could you sign the CLA and sign-off this commit?

**Comment by bowenliang123** [comment]
Sure. Leave me a sec to follow the instructions.

**Comment by imay** [comment]
@bowenliang123 Thank you for your contribution.

**Review by imay — APPROVED** [review]

**Comment by imay** [comment]
@mergify backport branch-3.0

**Comment by imay** [comment]
@mergify backport branch-2.5

**Comment by imay** [comment]
@mergify backport branch-2.4

**Comment by imay** [comment]
@mergify backport branch-2.3

**Comment by imay** [comment]
@mergify backport branch-2.2

**Comment by imay** [comment]
> Thanks for the help and impressively rapid response. Consider backporting this doc fix to all the release versions for both 3.x and 2.x. as well, since this is a crucial concept to understand and use Starrocks's table model.
> 
> And also, what's the update frequency, when will this fix be applied to the docs on Starrocks (https://docs.starrocks.io/)?

I have cherry-picked it for all branches, all documents will be built every day.

**Comment by bowenliang123** [comment]
Roger. Good to know that, thanks.

**Pull request merged**
