### PR TITLE
[BugFix] Fix es log return null.

### PR DESCRIPTION
**Pull request by Smith-Cruise**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Fix es log return null, so we can easily trace the bug.

### CODE REVIEW

**Review by imay — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 0 / 3 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/external/elasticsearch/EsRepository.java|0|2|00.00%|[80, 81]|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|0|1|00.00%|[2415]|

**Review by DorianZheng — APPROVED** [review]
LGTM

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by DorianZheng** [comment]
run starrocks_admit_test

**Pull request merged**
