### PR TITLE
[BugFix] diff lambda arg from normal slot

### LINKED ISSUE #31158: [array] select array NPE
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
```
create database array_filter_test_9acf51ee_52c7_11ee_ace6_00163e0e489a;
use array_filter_test_9acf51ee_52c7_11ee_ace6_00163e0e489a;
 CREATE TABLE `array_sort_null` ( c1 int NOT NULL, c2 array<date>, c3 array<datetime>, c4 array<char(20)>, c5 array<varchar(20)>, c6 array<boolean>, c7 array<tinyint>, c8 array<smallint>, c9 array<int>, c10 array<bigint>, c11 array<largeint>, c12 array<float>, c13 array<double> ) DUPLICATE KEY(c1) DISTRIBUTED BY HASH(c1) buckets 1 PROPERTIES ("replication_num" = "3");
insert into array_filter_test_9acf51ee_52c7_11ee_ace6_00163e0e489a.array_sort_null (c1, c2, c3, c4, c5, c6, c7, c8, c9, c10, c11, c12, c13)values (1, ['2022-01-02', '2012-01-01', '2011-01-04'], ['2012-01-04 01:01:01', '2012-01-03 01:01:01', '2013-01-01 01:01:01'], ['22', '33', '11'], ['222feds', '中文', null], [False, True, False], [2, 1, 3], [22, 11, 33], [null, null, null], [null, 12345, null], [3333, null, 1111], [11.2, 11.1, -10.1], [11.11, null, 4.44]);
```

2. SELECT  '....'
```
mysql> select c5 from array_sort_null order by array_filter(x -> year(x),c2)[1] nulls last limit 1;
ERROR 1064 (HY000): Unknown error
```

### Expected behavior (Required)
success

### Real behavior (Required)
NPE

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
main-1e55429

### PR DESCRIPTION
**Pull request by fzhedu**
Fixes https://github.com/StarRocks/starrocks/issues/31158

diff lambda arguments from normal slot to avoid crash.

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.2
  - [x] 3.1
  - [x] 3.0
  - [ ] 2.5

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:disappointed: **fail** : 3 / 4 (75.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/analysis/SlotRef.java|2|3|66.67%|[433]|
|:large_blue_circle:|com/starrocks/sql/plan/ScalarOperatorToExpr.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:disappointed: **fail** : 4 / 6 (66.67%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/analysis/SlotRef.java|3|5|60.00%|[433, 447]|
|:large_blue_circle:|com/starrocks/sql/plan/ScalarOperatorToExpr.java|1|1|100.00%|[]|

**Comment by kangkaisen** [comment]
please add issue for this PR

**Review by Seaven — DISMISSED** [review]

**Review by packy92 — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:disappointed: **fail** : 3 / 4 (75.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/analysis/SlotRef.java|2|3|66.67%|[433]|
|:large_blue_circle:|com/starrocks/sql/plan/ScalarOperatorToExpr.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 4 / 4 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/analysis/SlotRef.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/plan/ScalarOperatorToExpr.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by Seaven — APPROVED** [review]

**Review by packy92 — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.2

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Pull request merged**
