### PR TITLE
[BugFix] Fix FE sonar bugs

### PR DESCRIPTION
**Pull request by Seaven**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Review by kangkaisen — DISMISSED** [review]

**Review by liuyehcf — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by HangyuanLiu — DISMISSED** [review]

**Comment by Seaven** [comment]
run starrocks_fe_unittest

**Comment by Seaven** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 78 / 99 (78.79%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/load/ExportMgr.java|0|1|00.00%|[124]|
|:large_blue_circle:|com/starrocks/backup/RestoreJob.java|0|1|00.00%|[674]|
|:large_blue_circle:|com/starrocks/common/io/FastByteArrayInputStream.java|0|1|00.00%|[71]|
|:large_blue_circle:|com/starrocks/analysis/Analyzer.java|0|1|00.00%|[262]|
|:large_blue_circle:|com/starrocks/qe/ShowExecutor.java|19|32|59.38%|[453, 581, 587, 588, 589, 591, 850, 938, 1113, 1405, 1456, 1474, 1620]|
|:large_blue_circle:|com/starrocks/sql/common/MetaUtils.java|2|3|66.67%|[34]|
|:large_blue_circle:|com/starrocks/load/streamload/StreamLoadManager.java|2|3|66.67%|[425]|
|:large_blue_circle:|com/starrocks/sql/analyzer/QueryAnalyzer.java|6|8|75.00%|[256, 257]|
|:large_blue_circle:|com/starrocks/journal/bdbje/BDBEnvironment.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/backup/RepositoryMgr.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/load/loadv2/SparkLoadJob.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/statistics/ColumnHistogramStatsCacheLoader.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/mysql/MysqlChannel.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/tree/DefaultPredicateSelectivityEstimator.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/common/Config.java|5|5|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/tree/PreAggregateTurnOnRule.java|10|10|100.00%|[]|
|:large_blue_circle:|com/starrocks/journal/bdbje/BDBJEJournal.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/common/util/DynamicPartitionUtil.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/journal/bdbje/BDBJournalCursor.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/staros/BDBJEJournalSystem.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/transaction/TransactionState.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/statistic/StatisticsMetaManager.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/statistics/ExpressionStatisticCalculator.java|7|7|100.00%|[]|
|:large_blue_circle:|com/starrocks/load/loadv2/LoadJobScheduler.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/journal/JournalTask.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/transaction/UpdateDbUsedDataQuotaDaemon.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/load/loadv2/LoadEtlChecker.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/statistics/ColumnBasicStatsCacheLoader.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/system/HeartbeatMgr.java|1|1|100.00%|[]|

**Review by kangkaisen — APPROVED** [review]

**Review by HangyuanLiu — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
