### PR TITLE
[BugFix] Fix npe when executing queryDictSync

### PR DESCRIPTION
**Pull request by stephen-shelby**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #
related with https://github.com/StarRocks/starrocks/issues/6970
## Problem Summary(Required) ：

image

### CODE REVIEW

**Comment by stephen-shelby** [comment]
run starrocks_fe_unittest

**Comment by stephen-shelby** [comment]
run starrocks_fe_unittest

**Comment by kangkaisen** [comment]
run starrocks_fe_unittest

**Review by HangyuanLiu — APPROVED** [review]

**Comment by stdpain** [comment]
run starrocks_fe_unittest

**Review by Seaven — APPROVED** [review]

**Comment by stephen-shelby** [comment]
@Mergifyio backport branch-2.3

**Comment by stephen-shelby** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 0 / 1 (00.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/statistic/StatisticExecutor.java|0|1|00.00%|

**Comment by stephen-shelby** [comment]
run starrocks_clang-tidy

**Comment by stephen-shelby** [comment]
run starrocks_clang-format

**Pull request merged**
