### PR TITLE
[BugFix] Make decimal-typed ArithmeticExpr analyzing idempotent

### PR DESCRIPTION
**Pull request by satanson**
When analyzing a decimal ArithmeticExpr, CastExpr is interpolated, so analyzing a decimal ArithmeticExpr multiple times give different result, which can cause  that the query contains duplicate aggregation function applying to decimal ArithmeticExpr fails to parse. the query looks like the one as follows:
```
-- c0: decimal(24, 2);
-- c1: decimal(25 ,5);
select c0, sum(c1/(1+c2)), sum(c1/(1+c2)) from t0 group by c0;
```
First analyzing is that SelectAnalyzer.analyze invoke SelectAnalyzer.analyzeSelect to get output exprs, then collect aggregations from output exprs, only one aggregation is collected since the two are duplicate.
Second analyzing  that SelectAnalyzer.analyzeAggregations analyze collected aggregation again, then try to substitute this aggregation with ColumnRefOperator in output exprs(QueryTransform.plan invokes project() after invoking aggregate()), but because the collected aggregation is analyzed twice, it is different from another aggregation in output exprs.

We should make decimal ArithmeticExpr analyzing idempotent,  so CastExpr intepolation is moved to ImplicitCastRule.

## What type of PR is this
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.0
  - [x] 2.5
  - [x] 2.4
  - [x] 2.3

### CODE REVIEW

**Review by Seaven — DISMISSED** [review]

**Review by caneGuy — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 26 / 26 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/analysis/ArithmeticExpr.java|16|16|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rewrite/scalar/ImplicitCastRule.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/ExpressionAnalyzer.java|6|6|100.00%|[]|

**Review by kangkaisen — APPROVED** [review]

**Review by miomiocat — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.4

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.3

**Pull request merged**
