### PR TITLE
[Enhancement] update error reason when throw runtime error in local exchange

### PR DESCRIPTION
**Pull request by fzhedu**
update error reason when throw runtime error in local exchange

## What type of PR is this:
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [x] 3.0
  - [x] 2.5
  - [x] 2.4

### CODE REVIEW

**Review by Seaven — DISMISSED** [review]

**Review by ZiheLiu — DISMISSED** [review]

**Review by kangkaisen — APPROVED** [review]

**Comment by fzhedu** [comment]
close it as https://github.com/StarRocks/starrocks/pull/26086

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.4

**Pull request closed without merging**
