### PR TITLE
[BugFix] Materialized views do not support automatic cooling down

### LINKED ISSUE #19596: Materialized views do not support automatic cooling down
### Steps to reproduce the behavior (Required)
1. CREATE TABLE like this:
```
CREATE TABLE tbl1
(
k1 date,
k2 int,
v1 int sum
)
PARTITION BY RANGE(k1)
(
    PARTITION p1 values less than('2023-02-01'),
    PARTITION p2 values less than('2023-03-01')
)
DISTRIBUTED BY HASH(k2) BUCKETS 3
PROPERTIES('replication_num' = '1');
```
2. CREATE MATERIALIZED VIEW  like this:
```
CREATE MATERIALIZED VIEW mv1
PARTITION BY k1
distributed by hash(k2)
REFRESH ASYNC
PROPERTIES(
'replication_num' = '1',
"storage_medium" = "SSD",
"storage_cooldown_time" = "2023-03-16 09:53:00"
)
as select k1, k2 from tbl1;
```
3. execute `show partitions from mv1;` after time `2023-03-16 09:55:00`

### Expected behavior (Required)
partition storage medium use hdd.

### Real behavior (Required)
partition storage medium use ssd.
```

+-------------+---------------+----------------+---------------------+--------------------+--------+--------------+----------------------------------------------------------------------------+-----------------+---------+----------------+---------------+---------------------+--------------------------+----------+------------+----------+
| PartitionId | PartitionName | VisibleVersion | VisibleVersionTime  | VisibleVersionHash | State  | PartitionKey | Range                                                                      | DistributionKey | Buckets | ReplicationNum | StorageMedium | CooldownTime        | LastConsistencyCheckTime | DataSize | IsInMemory | RowCount |
+-------------+---------------+----------------+---------------------+--------------------+--------+--------------+----------------------------------------------------------------------------+-----------------+---------+----------------+---------------+---------------------+--------------------------+----------+------------+----------+
| 11035       | p1            | 1              | 2023-03-16 09:51:40 | 0                  | NORMAL | k1           | [types: [DATE]; keys: [0000-01-01]; ..types: [DATE]; keys: [2023-02-01]; ) | k2              | 2       | 1              | SSD           | 2023-03-16 09:53:00 | NULL                     | 0B       | false      | 0        |
| 11040       | p2            | 1              | 2023-03-16 09:51:40 | 0                  | NORMAL | k1           | [types: [DATE]; keys: [2023-02-01]; ..types: [DATE]; keys: [2023-03-01]; ) | k2              | 2       | 1              | SSD           | 2023-03-16 09:53:00 | NULL                     | 0B       | false      | 0        |
+-------------+---------------+----------------+---------------------+--------------------+--------+--------------+----------------------------------------------------------------------------+-----------------+---------+----------------+---------------+---------------------+--------------------------+----------+------------+----------+
2 rows in set (0.01 sec)
```

### StarRocks version (Required)
 - UNKNOWN 356ab9b

### PR DESCRIPTION
**Pull request by blackstar-baba**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #19596 

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 3.0
  - [x] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|1|1|100.00%|[]|

**Review by Astralidea — APPROVED** [review]

**Review by murphyatwork — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by Astralidea** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
