### PR TITLE
[BugFix] data error after reload persistent index

### LINKED ISSUE #12513: [Bug] persistentindex may be inconsistent after reload
```
I1025 23:34:17.631394 19638 publish_version.cpp:109] Publish txn success tablet:1208221 version:4205 partition:1206478 txn_id: 2790947 rowset:02000000000c45bb744b99dbe502e1e120eee5efbe01d699
I1025 23:34:18.052182  9937 tablet_updates.cpp:1028] apply_rowset_commit finish. tablet:1208221 version:4205 txn_id: 2790947 total del/row:0/46640008 0% rowset:4155 #seg:1 #op(upsert:10984 del:0) #del:0+0=0 #dv:1 duration:420ms(0/0/420/0/0)
I1025 23:35:40.852489 11257 task_worker_pool.cpp:238] success to submit task. type=CHECK_CONSISTENCY, signature=[1208221], task_count_in_queue=17
I1025 23:35:40.857470 19667 engine_checksum_task.cpp:48] begin to process compute checksum.tablet_id=1208221, schema_hash=899250008, version=4205
I1025 23:35:40.857477 19667 task_worker_pool.cpp:1018] check consistency success. status:OK, signature:1208221, checksum:0
I1025 23:35:42.423712 19737 tablet_manager.cpp:622] Found the best tablet to compact. compaction_type=update tablet_id=1208221 highest_score=161153103
I1025 23:35:42.423733 19737 tablet_updates.cpp:1742] update compaction start tablet:1208221 version:4205 score:161153104 pick:6/valid:6/all:105 4150,4151,4152,4153,4154,4155 #rows:66181->66181 bytes:6.31 MB->6.31 MB(estimate)
I1025 23:35:42.541230 19737 rowset_merger.cpp:236] compaction merge finished. tablet=1208221 #key=1 algorithm=VERTICAL_COMPACTION column_group_size=5 input(entry=6 rows=66181 del=0 actual=66181 bytes=6.31 MB) output(rows=66181 chunk=18 bytes=6.03 MB) duration: 117ms
I1025 23:35:42.554492 19737 tablet_updates.cpp:1259] commit compaction tablet:1208221 version:4205.1 rowset:4156 #seg:1 #row:66181 size:6.03 MB #pending:0 state_memory:517.04 KB
I1025 23:35:42.554756 10460 tablet_updates.cpp:1287] apply_compaction_commit start tablet:1208221 version:4205.1 rowset:4156
I1025 23:35:42.573256 10460 tablet_updates.cpp:1447] apply_compaction_commit finish tablet:1208221 version:4205.1 total del/row:0/46640008 0% rowset:4156 #row:66181 #del:0 #delvec:1 duration:18ms(0/16/2)
I1025 23:37:12.086856 19700 tablet_updates.cpp:1569] remove_expired_versions tablet:1208221 #version:217 [4003 4205.1@216 4205.1] #pending:0 time:1666710432 min_readable_version:4003 deletes: #version:24 #rowset:15 #delvec:0
I1025 23:37:12.088217 19700 tablet_updates.cpp:2599] _remove_unused_rowsets remove 15 rowsets, tablet:1208221
I1025 23:40:15.753974 19700 tablet_updates.cpp:1569] remove_expired_versions tablet:1208221 #version:191 [4027 4205.1@190 4205.1] #pending:0 time:1666710615 min_readable_version:4027 deletes: #version:26 #rowset:33 #delvec:0
I1025 23:40:15.757539 19700 tablet_updates.cpp:2599] _remove_unused_rowsets remove 33 rowsets, tablet:1208221
I1025 23:43:19.525024 19700 tablet_updates.cpp:1569] remove_expired_versions tablet:1208221 #version:167 [4050 4205.1@166 4205.1] #pending:0 time:1666710799 min_readable_version:4050 deletes: #version:24 #rowset:16 #delvec:0
I1025 23:43:19.526437 19700 tablet_updates.cpp:2599] _remove_unused_rowsets remove 16 rowsets, tablet:1208221
I1025 23:46:23.309231 19700 tablet_updates.cpp:1569] remove_expired_versions tablet:1208221 #version:143 [4073 4205.1@142 4205.1] #pending:0 time:1666710983 min_readable_version:4073 deletes: #version:24 #rowset:17 #delvec:0
I1025 23:46:23.310997 19700 tablet_updates.cpp:2599] _remove_unused_rowsets remove 17 rowsets, tablet:1208221
I1025 23:49:27.030565 19700 tablet_updates.cpp:1569] remove_expired_versions tablet:1208221 #version:120 [4094 4205.1@119 4205.1] #pending:0 time:1666711167 min_readable_version:4094 deletes: #version:23 #rowset:32 #delvec:0
I1025 23:49:27.033957 19700 tablet_updates.cpp:2599] _remove_unused_rowsets remove 32 rowsets, tablet:1208221
I1025 23:52:30.978726 19700 tablet_updates.cpp:1569] remove_expired_versions tablet:1208221 #version:96 [4117 4205.1@95 4205.1] #pending:0 time:1666711350 min_readable_version:4117 deletes: #version:24 #rowset:17 #delvec:0
I1025 23:52:30.980481 19700 tablet_updates.cpp:2599] _remove_unused_rowsets remove 17 rowsets, tablet:1208221
I1025 23:55:35.112809 19700 tablet_updates.cpp:1569] remove_expired_versions tablet:1208221 #version:70 [4141 4205.1@69 4205.1] #pending:0 time:1666711535 min_readable_version:4141 deletes: #version:26 #rowset:32 #delvec:0
I1025 23:55:35.124881 19700 tablet_updates.cpp:2599] _remove_unused_rowsets remove 32 rowsets, tablet:1208221
I1025 23:58:39.416501 19700 tablet_updates.cpp:1569] remove_expired_versions tablet:1208221 #version:48 [4162 4205.1@47 4205.1] #pending:0 time:1666711719 min_readable_version:4162 deletes: #version:22 #rowset:16 #delvec:0
I1025 23:58:39.424757 19700 tablet_updates.cpp:2599] _remove_unused_rowsets remove 16 rowsets, tablet:1208221
I1026 00:01:43.671509 19700 tablet_updates.cpp:1569] remove_expired_versions tablet:1208221 #version:22 [4186 4205.1@21 4205.1] #pending:0 time:1666711903 min_readable_version:4186 deletes: #version:26 #rowset:34 #delvec:0
I1026 00:01:43.689500 19700 tablet_updates.cpp:2599] _remove_unused_rowsets remove 34 rowsets, tablet:1208221
I1026 00:04:48.378939 19700 tablet_updates.cpp:1569] remove_expired_versions tablet:1208221 #version:1 [4205.1 4205.1@0 4205.1] #pending:0 time:1666712088 min_readable_version:4205 deletes: #version:21 #rowset:23 #delvec:0
I1026 00:04:48.391265 19700 tablet_updates.cpp:2599] _remove_unused_rowsets remove 23 rowsets, tablet:1208221
I1026 12:06:12.854524 19775 data_dir.cpp:504] collect garbage dir path: /home/disk3/starrocks_stability/be-e49248c8-a454-4703-95fe-c2234b4e740f/data/27/1208221/899250008/020000000008a2e88846bbbad1934dd9137dedda4bc5b5b7_0.dat
I1026 12:06:12.857723 19775 data_dir.cpp:504] collect garbage dir path: /home/disk3/starrocks_stability/be-e49248c8-a454-4703-95fe-c2234b4e740f/data/27/1208221/899250008/02000000000fd41d8846bbbad1934dd9137dedda4bc5b5b7_0.dat
I1026 13:25:43.418897 19236 persistent_index.cpp:2507] load persistent index tablet:1208221 version:4205.1 size: 46640008 l0_size: 455180 l0_capacity:524287 #shard: 1024 l1_size:45486663 memory: 8912879 status: OK time:327ms
I1026 13:25:43.419029 19236 txn_manager.cpp:210] Commit txn successfully.  tablet: 1208221, txn_id: 2804381, rowsetid: 020000000016d1ee744b99dbe502e1e120eee5efbe01d699 #segment:1 #delfile:0
I1026 13:25:45.293522 19641 tablet_updates.cpp:512] commit rowset tablet:1208221 version:4206 txn_id: 2804381 020000000016d1ee744b99dbe502e1e120eee5efbe01d699 rowset:4157 #seg:1 #delfile:0 #row:10862 size:1.04 MB #pending:0
I1026 13:25:45.293568 19641 publish_version.cpp:109] Publish txn success tablet:1208221 version:4206 partition:1206478 txn_id: 2804381 rowset:020000000016d1ee744b99dbe502e1e120eee5efbe01d699
I1026 13:25:45.644793  4132 tablet_updates.cpp:1028] apply_rowset_commit finish. tablet:1208221 version:4206 txn_id: 2804381 total del/row:0/46650870 0% rowset:4157 #seg:1 #op(upsert:10862 del:0) #del:0+0=0 #dv:1 duration:352ms(0/0/351/0/1)
I1026 13:25:47.170415  4000 txn_manager.cpp:210] Commit txn successfully.  tablet: 1208221, txn_id: 2804388, rowsetid: 020000000016d25d744b99dbe502e1e120eee5efbe01d699 #segment:1 #delfile:0
I1026 13:25:47.898437 19636 tablet_updates.cpp:512] commit rowset tablet:1208221 version:4207 txn_id: 2804388 020000000016d25d744b99dbe502e1e120eee5efbe01d699 rowset:4158 #seg:1 #delfile:0 #row:10698 size:1.02 MB #pending:0
I1026 13:25:47.899268 19636 publish_version.cpp:109] Publish txn success tablet:1208221 version:4207 partition:1206478 txn_id: 2804388 rowset:020000000016d25d744b99dbe502e1e120eee5efbe01d699
I1026 13:25:48.256179  4216 tablet_updates.cpp:1028] apply_rowset_commit finish. tablet:1208221 version:4207 txn_id: 2804388 total del/row:0/46661568 0% rowset:4158 #seg:1 #op(upsert:10698 del:0) #del:0+0=0 #dv:1 duration:356ms(0/0/356/0/0)
I1026 13:25:50.018442 19737 tablet_manager.cpp:622] Found the best tablet to compact. compaction_type=update tablet_id=1208221 highest_score=58631767
I1026 13:25:50.018476 19737 tablet_updates.cpp:1742] update compaction start tablet:1208221 version:4207 score:58631768 pick:3/valid:3/all:102 4156,4157,4158 #rows:87741->87741 bytes:8.08 MB->8.08 MB(estimate)
I1026 13:25:50.223315 19737 rowset_merger.cpp:236] compaction merge finished. tablet=1208221 #key=1 algorithm=VERTICAL_COMPACTION column_group_size=5 input(entry=3 rows=87741 del=0 actual=87741 bytes=8.08 MB) output(rows=87741 chunk=23 bytes=7.93 MB) duration: 204ms
I1026 13:25:50.241887 19737 tablet_updates.cpp:1259] commit compaction tablet:1208221 version:4207.1 rowset:4159 #seg:1 #row:87741 size:7.93 MB #pending:0 state_memory:685.48 KB
I1026 13:25:50.241982  4254 tablet_updates.cpp:1287] apply_compaction_commit start tablet:1208221 version:4207.1 rowset:4159
I1026 13:25:50.541035  4254 tablet_updates.cpp:1447] apply_compaction_commit finish tablet:1208221 version:4207.1 total del/row:66181/46661568 0% rowset:4159 #row:87741 #del:66181 #delvec:1 duration:299ms(0/295/4)
E1026 13:25:50.541064  4254 tablet_updates.cpp:1456] actual row size changed after compaction 46661568 -> 46595387tablet:1208221 #version:4 [4205.1 4207.1@3 4207.1] pending: rowsets:100

```

version: branch-2.4 500abb6

### PR DESCRIPTION
**Pull request by sevev**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes https://github.com/StarRocks/starrocks/issues/12513

## Problem Summary(Required) ：

We should take care of calling `emplace_back` after initializing the capacity of the vector because this may not be your expected behavior. And the first `n` elements are null but not the data we want, that is why cause the inconsistent of persistent index.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Review by Linkerist — DISMISSED** [review]

**Comment by trueeyu** [comment]
Add test case

**Review by decster — DISMISSED** [review]

**Comment by sevev** [comment]
> Add test case

done.

**Comment by sevev** [comment]
> Add test case

done.

**Comment by wanpengfei-git** [comment]
starrocks_be_unittest succeeded.

**Review by decster — APPROVED** [review]

**Review by chaoyli — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by sevev** [comment]
@mergify backport branch-2.4

**Pull request merged**
