### PR TITLE
[Feature]Consider external catalog when checking privilege

### PR DESCRIPTION
**Pull request by caneGuy**
## What type of PR is this：
- [ ] bug
- [x] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

Related with #5062 
DLA New Framework add catalog level. We support hive connector in this milestone. In this pr we skip check privilege for tables and dbs in some limited operation.

1. Table privilege checker in PrivilegeChecker
2. Show databases from catalog

### CODE REVIEW

**Review by DorianZheng — DISMISSED** [review]
LGTM

**Review by stephen-shelby — DISMISSED** [review]
LGTM

**Comment by DorianZheng** [comment]
@HangyuanLiu PTAL

**Review by HangyuanLiu — DISMISSED** [review]

**Review by stephen-shelby — APPROVED** [review]
LGTM

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 19 / 21 (90.48%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/ShowExecutor.java|3|4|75.00%|
|:large_blue_circle:|com/starrocks/sql/analyzer/PrivilegeChecker.java|15|16|93.75%|
|:large_blue_circle:|com/starrocks/analysis/DropTableStmt.java|1|1|100.00%|

**Review by dirtysalt — APPROVED** [review]

**Review by imay — APPROVED** [review]

**Pull request merged**
