### PR TITLE
[Enhancement] add min/max predicates to scan node, which is quite critical information

### PR DESCRIPTION
**Pull request by dirtysalt**
## What type of PR is this：
- [ ] bug
- [ ] feature
- [x] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

This PR is to output `min/max predicates` in explain output. It's because this piece of information is very critical to scanner, without that we won't be able to do file-level/group-level filtering.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Review by kangkaisen — APPROVED** [review]

**Comment by dirtysalt** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 0 / 27 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/planner/HudiScanNode.java|0|6|00.00%|[70, 71, 72, 109, 110, 111]|
|:large_blue_circle:|com/starrocks/planner/IcebergScanNode.java|0|15|00.00%|[77, 203, 212, 213, 214, 233, 242, 243, 244, 284, 285, 288, 293, 296, 297]|
|:large_blue_circle:|com/starrocks/planner/HdfsScanNode.java|0|6|00.00%|[83, 84, 85, 122, 123, 124]|

**Review by caneGuy — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by dirtysalt** [comment]
run starrocks_admit_test

**Comment by dirtysalt** [comment]
run starrocks_admit_test

**Pull request merged**
