### PR TITLE
[Refactor] check status of functions

### LINKED ISSUE #27471: [Proposal] make sure each returned Status is handled explicitly
Status is not handled properly in many places in our code. It is easy to find such problems through error injection, such as #27033 , #27160 , and #26291.
Once this type of error occurs, it may lead to errors in subsequent data processing, and it is difficult to troubleshoot when problems occur.
So I propose to add the nodiscard keyword to Status to ensure that each returned Status can be clearly processed, otherwise a warning will be generated when compiling

https://github.com/StarRocks/starrocks/pull/27411 is the work I am doing, but there are a lot of changes, and it needs to be gradually split into multiple PRs.

### PR DESCRIPTION
**Pull request by liuyehcf**
Fixes #27471

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [x] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 2 / 4 (50.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/exec/sorting/merge_column.cpp|2|4|50.00%|[120, 134]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 5 / 13 (38.46%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/exec/pipeline/sort/sort_context.cpp|0|1|00.00%|[62]|
|:large_blue_circle:|src/exec/pipeline/sort/local_partition_topn_context.cpp|0|2|00.00%|[71, 74]|
|:large_blue_circle:|src/exec/sorting/merge_column.cpp|4|9|44.44%|[120, 134, 156, 171, 179]|
|:large_blue_circle:|src/exec/sorting/merge_cascade.cpp|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 5 / 13 (38.46%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/exec/pipeline/sort/sort_context.cpp|0|1|00.00%|[62]|
|:large_blue_circle:|src/exec/pipeline/sort/local_partition_topn_context.cpp|0|2|00.00%|[71, 74]|
|:large_blue_circle:|src/exec/sorting/merge_column.cpp|4|9|44.44%|[120, 134, 156, 171, 179]|
|:large_blue_circle:|src/exec/sorting/merge_cascade.cpp|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 5 / 13 (38.46%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/exec/pipeline/sort/sort_context.cpp|0|1|00.00%|[62]|
|:large_blue_circle:|src/exec/pipeline/sort/local_partition_topn_context.cpp|0|2|00.00%|[71, 74]|
|:large_blue_circle:|src/exec/sorting/merge_column.cpp|4|9|44.44%|[120, 134, 156, 171, 179]|
|:large_blue_circle:|src/exec/sorting/merge_cascade.cpp|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 5 / 13 (38.46%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/exec/pipeline/sort/sort_context.cpp|0|1|00.00%|[62]|
|:large_blue_circle:|src/exec/pipeline/sort/local_partition_topn_context.cpp|0|2|00.00%|[71, 74]|
|:large_blue_circle:|src/exec/sorting/merge_column.cpp|4|9|44.44%|[120, 134, 156, 171, 179]|
|:large_blue_circle:|src/exec/sorting/merge_cascade.cpp|1|1|100.00%|[]|

**Review by fzhedu — APPROVED** [review]

**Review by murphyatwork — APPROVED** [review]

**Pull request merged**
