### PR TITLE
[BugFix] fix be crash when schema change

### LINKED ISSUE #16998: [Bug] be crash when schema change
### Steps to reproduce the behavior (Required)
When concurrent run data loading and schema change, BE may crash at:
```
 0x57baa51 starrocks::vectorized::SchemaChangeHandler::_convert_historical_rowsets()
*** SIGSEGV (@0x40) received by PID 13522 (TID 0x7fc2bb3a0700) from PID 64; stack trace: ***
    @          0x6a6b792 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7fc3fd261630 (unknown)
    @          0x57baa51 starrocks::vectorized::SchemaChangeHandler::_convert_historical_rowsets()
    @          0x57bd560 starrocks::vectorized::SchemaChangeHandler::_do_process_alter_tablet_v2_normal()
    @          0x57be888 starrocks::vectorized::SchemaChangeHandler::_do_process_alter_tablet_v2()
    @          0x57bed8a starrocks::vectorized::SchemaChangeHandler::process_alter_tablet_v2()
    @          0x55dde96 starrocks::EngineAlterTabletTask::execute()
    @          0x53faeee starrocks::StorageEngine::execute_task()
    @          0x3a4171e starrocks::run_alter_tablet_task()
    @          0x5b4c405 starrocks::ThreadPool::dispatch_thread()
    @          0x5b4712a starrocks::Thread::supervise_thread()
    @     0x7fc3fd259ea5 start_thread
    @     0x7fc3f293f9fd __clone
    @                0x0 (unknown)
```

Because in `_convert_historical_rowsets`, assume that `sc_params.rowset_readers` and `sc_params.rowsets_to_change` have same valid items. If don't, crash will happen.

### StarRocks version (Required)
 - 2.5.0

### PR DESCRIPTION
**Pull request by luohaha**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #16998

## Problem Summary(Required) ：

When concurrent run data loading and schema change, BE may crash at:
```
 0x57baa51 starrocks::vectorized::SchemaChangeHandler::_convert_historical_rowsets()
*** SIGSEGV (@0x40) received by PID 13522 (TID 0x7fc2bb3a0700) from PID 64; stack trace: ***
    @          0x6a6b792 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7fc3fd261630 (unknown)
    @          0x57baa51 starrocks::vectorized::SchemaChangeHandler::_convert_historical_rowsets()
    @          0x57bd560 starrocks::vectorized::SchemaChangeHandler::_do_process_alter_tablet_v2_normal()
    @          0x57be888 starrocks::vectorized::SchemaChangeHandler::_do_process_alter_tablet_v2()
    @          0x57bed8a starrocks::vectorized::SchemaChangeHandler::process_alter_tablet_v2()
    @          0x55dde96 starrocks::EngineAlterTabletTask::execute()
    @          0x53faeee starrocks::StorageEngine::execute_task()
    @          0x3a4171e starrocks::run_alter_tablet_task()
    @          0x5b4c405 starrocks::ThreadPool::dispatch_thread()
    @          0x5b4712a starrocks::Thread::supervise_thread()
    @     0x7fc3fd259ea5 start_thread
    @     0x7fc3f293f9fd __clone
    @                0x0 (unknown)
```

Because in `_convert_historical_rowsets`, assume that `sc_params.rowset_readers` and `sc_params.rowsets_to_change` have same valid items. If don't, crash will happen.

So I add checking code when geneate `rowsets_to_change`, when `base_tablet->get_rowset_by_version` can't find rowset by version, print all helpful message to check what happen and just return error to prevent BE from crash. Still need find out in which situation, version from `capture_consistent_versions` by max version can't find rowset by `get_rowset_by_version`.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Review by trueeyu — APPROVED** [review]

**Review by decster — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by luohaha** [comment]
run starrocks_clang-format

**Comment by luohaha** [comment]
run starrocks_fe_unittest

**Comment by luohaha** [comment]
https://github.com/Mergifyio backport branch-2.5

**Pull request merged**
