### PR TITLE
[Merge Join]fix merge join repeat generate fragement error

### PR DESCRIPTION
**Pull request by zddr**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/plan/PlanFragmentBuilder.java|1|1|100.00%|

**Comment by zddr** [comment]
run starrocks_fe_unittest

**Comment by zddr** [comment]
run starrocks_fe_unittest

**Comment by zddr** [comment]
run starrocks_fe_unittest

**Comment by zddr** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 10 / 10 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/plan/PlanFragmentBuilder.java|10|10|100.00%|

**Comment by zddr** [comment]
@trueeyu

**Comment by zddr** [comment]
PTAL

**Review by trueeyu — APPROVED** [review]

**Review by Seaven — APPROVED** [review]

**Pull request merged**
