### PR TITLE
[BugFix] optimize single table without predicate mv rewrite

### LINKED ISSUE #14265: [materialized view]rewrite not worked when create mv without predicate
### Steps to reproduce the behavior (Required)
```
CREATE TABLE `duplicate_table_with_null_partition` (
                    `k1` date,
                    `k2` datetime,
                    `k3` char(20),
                    `k4` varchar(20),
                    `k5` boolean,
                    `k6` tinyint,
                    `k7` smallint,
                    `k8` int,
                    `k9` bigint,
                    `k10` largeint,
                    `k11` float,
                    `k12` double,
                    `k13` decimal(27,9),
                    `k14` array<int>,
                    `k15` json
                    ) ENGINE=OLAP
                    DUPLICATE KEY(`k1`, `k2`, `k3`, `k4`, `k5`)
                    COMMENT "OLAP"
                    PARTITION BY RANGE(`k1`)
                    (
                    PARTITION `p202006` VALUES LESS THAN ("2020-07-01"),
                    PARTITION `p202007` VALUES LESS THAN ("2020-08-01"),
                    PARTITION `p202008` VALUES LESS THAN ("2020-09-01")
                    )
                    DISTRIBUTED BY HASH(`k1`, `k2`, `k3`, `k4`, `k5`) BUCKETS 3
                    PROPERTIES (
                    "replication_num" = "3",
                    "storage_format" = "v2"
                    );
INSERT INTO duplicate_table_with_null_partition VALUES
                ("2020-06-23","2020-06-23 00:00:00","beijing","haidian",-1,-128,-32768,-2147483648,-9223372036854775808,-18446744073709551616,-3.1,-3.14,-3.141,[1,1,1],parse_json('{"a": 1, "b": true}')),
                ("2020-07-23","2020-07-23 00:00:00","shanghai","pudong",0,0,0,0,0,0,-3.1,-3.14,-3.141,[2,2,2],parse_json('{"a": 1, "b": true}')),
                ("2020-07-23","2020-07-24 00:00:00","shanghai1","pudong1",1,1,1,1,1,1,-3.2,-3.44,-3.441,[3,3,3],parse_json('{"a": 1, "b": true}')),
                ("2020-08-23","2020-08-23 00:00:00","xian","zhonglou",1,127,32767,2147483647,9223372036854775807,18446744073709551615,-3.1,-3.14,-3.141,[3,3,3],parse_json('{"a": 1, "b": true}')),
                (NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
CREATE MATERIALIZED VIEW mv3
                         PARTITION BY k1
                         DISTRIBUTED BY HASH(k1) BUCKETS 10
                         REFRESH ASYNC
                         AS SELECT k1, k14, k15
                         FROM duplicate_table_with_null_partition;
explain SELECT k1, k14, k15 FROM duplicate_table_with_null_partition;
```

### Expected behavior (Required)
`TABLE: mv3`
### Real behavior (Required)
`TABLE: duplicate_table_with_null_partition`
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
+----------------------------+
| current_version()          |
+----------------------------+
| BRANCH-2.5-RELEASE 4de5647 |
+----------------------------+
```

### PR DESCRIPTION
**Pull request by ABingHuang**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #14265 

## Problem Summary(Required) ：

optimize single table rewrite, enable single table rewrite without predicate
## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Review by Seaven — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 4 / 4 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/Binder.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/OptExpressionDuplicator.java|2|2|100.00%|[]|

**Comment by ABingHuang** [comment]
run starrocks_admit_test

**Review by kangkaisen — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
