### PR TITLE
[Enhancement] enable SQLDigest, but not over than slow query time, sh…

### PR DESCRIPTION
**Pull request by wangjie-fourth**
## Why I'm doing:
see[42539](https://github.com/StarRocks/starrocks/issues/42539)

## What I'm doing:

Fixes #issue

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Comment by imay** [comment]
@wangjie-fourth can you sign the CLA and sign-off this PR by `git commit -s`

**Comment by wangjie-fourth** [comment]
> @wangjie-fourth can you sign the CLA and sign-off this PR by `git commit -s`

@imay done

**Comment by wangjie-fourth** [comment]
@imay hi, this pr is block now. can you help with it?

**Review by imay — DISMISSED** [review]

**Comment by wangjie-fourth** [comment]
@Youngwb hi, can you help review this

**Review by kangkaisen — DISMISSED** [review]

**Review by packy92 — DISMISSED** [review]

**Comment by packy92** [comment]
@wangjie-fourth  could you rebase this branch? The thirdparty Info need this.

**Comment by wangjie-fourth** [comment]
> @wangjie-fourth could you rebase this branch? The thirdparty Info need this.

hi, are you meaning to rebase this commit on main branch?

**Review by packy92 — APPROVED** [review]

**Review by kangkaisen — APPROVED** [review]

**Pull request merged**
