### PR TITLE
[Feature] Support substring_index function

### LINKED ISSUE #12532: starrocks don't support substring_index which mysql did
starrocks-client：
```
mysql> select substring_index(substring_index('name(10)', '(', -1), ')', `1)；`
ERROR 1064 (HY000): No matching function with signature: substring_index(varchar(-1), varchar(-1), tinyint(4)).
```

### PR DESCRIPTION
**Pull request by leoyy0316**
Fixes #12532

## What type of PR is this:
- [ ] BugFix
- [x] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/parser/SyntaxSugars.java|1|1|100.00%|[]|

**Comment by leoyy0316** [comment]
> Can you add some sql test for this newly added function?

@imay  done

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by imay — DISMISSED** [review]

**Comment by Seaven** [comment]
sorry, I think `substring_index` isn't same as`split_part`

refs: https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_substring-index

`substring_index` should return:
```
mysql> SELECT SUBSTRING_INDEX('www.mysql.com', '.', 2);
        -> 'www.mysql'
mysql> SELECT SUBSTRING_INDEX('www.mysql.com', '.', -2);
        -> 'mysql.com'
```

but `split_part` will return:
```
MySQL td> SELECT split_part('www.mysql.com', '.', 2);
+-------------------------------------+
| split_part('www.mysql.com', '.', 2) |
+-------------------------------------+
| mysql                               |
+-------------------------------------+
1 row in set
Time: 0.021s
MySQL td> SELECT split_part('www.mysql.com', '.', -2);
+--------------------------------------+
| split_part('www.mysql.com', '.', -2) |
+--------------------------------------+
| mysql                                |
+--------------------------------------+
1 row in set
Time: 0.019s
```

**Comment by leoyy0316** [comment]
> https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_substring-index

@Seaven oh, sorry,  will try to modify this logic later, thanks

**Comment by leoyy0316** [comment]
> sorry, I think `substring_index` isn't same as`split_part`
> 
> refs: https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_substring-index
> 
> `substring_index` should return:
> 
> ```
> mysql> SELECT SUBSTRING_INDEX('www.mysql.com', '.', 2);
>         -> 'www.mysql'
> mysql> SELECT SUBSTRING_INDEX('www.mysql.com', '.', -2);
>         -> 'mysql.com'
> ```
> 
> but `split_part` will return:
> 
> ```
> MySQL td> SELECT split_part('www.mysql.com', '.', 2);
> +-------------------------------------+
> | split_part('www.mysql.com', '.', 2) |
> +-------------------------------------+
> | mysql                               |
> +-------------------------------------+
> 1 row in set
> Time: 0.021s
> MySQL td> SELECT split_part('www.mysql.com', '.', -2);
> +--------------------------------------+
> | split_part('www.mysql.com', '.', -2) |
> +--------------------------------------+
> | mysql                                |
> +--------------------------------------+
> 1 row in set
> Time: 0.019s
> ```

@Seaven  done, pls review it, thanks

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by Seaven — APPROVED** [review]

**Pull request merged**
