### PR TITLE
[Tool] Force file relative path in BE's debug symbol

### LINKED ISSUE #46034: [BE][Build] Strip root directory, use relative path for source code file path
## Enhancement

Current CMAKE system will preserve the entire absolute path to source file, feeding into compiler, this leads to build server absolute path embedded in be binary debug info.

for example:
```
E0517 02:07:07.776870  1982 vacuum.cpp:454] Internal error: starlet err grpc.GetShard(shardId=17816) error: Deadline Exceeded
/build/starrocks/be/src/storage/protobuf_file.cpp:154 value_or_err_L154
/build/starrocks/be/src/storage/lake/tablet_manager.cpp:227 file.load(metadata.get(), fill_cache)
/build/starrocks/be/src/storage/lake/tablet_manager.cpp:245 value_or_err_L245
/build/starrocks/be/src/storage/lake/vacuum.cpp:364 collect_files_to_vacuum(tablet_mgr, root_dir, tablet_id, grace_timestamp, min_retain_version, &datafile_deleter, &metafile_deleter, vacuumed_file_size)
/build/starrocks/be/src/storage/lake/vacuum.cpp:442 vacuum_tablet_metadata(tablet_mgr, root_loc, tablet_ids, min_retain_version, grace_timestamp, &vacuumed_files, &vacuumed_file_size)
```

Expect the prefix will be removed, only the path showing there only starts from `starrocks/` root dir or `starrocks/be/` be source root dir.

### PR DESCRIPTION
**Pull request by kevincai**
* add -ffile-prefix-map to convert absolute path to relative path
* fix gensrc_dir, use a symbolic link to be/src/gen_cpp/ directory
* apply -ffile-prefix-map to `.c` file as well

## What I'm doing:

Fixes #46034

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [x] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.3
  - [x] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Review by imay — DISMISSED** [review]

**Review by imay — DISMISSED** [review]

**Comment by kevincai** [comment]
example output after the change

```
Thread 1 (Thread 0x7f7a7cb3b080 (LWP 4050003) "starrocks_be"):
#0  0x00007f7a7a51c9fd in nanosleep () from /lib64/libc.so.6
#1  0x00007f7a7a51c894 in sleep () from /lib64/libc.so.6
#2  0x0000000009d82272 in starrocks::start_be (paths=..., as_cn=as_cn@entry=false) at be/src/service/service_be/starrocks_be.cpp:284
#3  0x00000000055b7e28 in main (argc=<optimized out>, argv=<optimized out>) at be/src/service/starrocks_main.cpp:250


Thread 59 (Thread 0x7f7a5984d700 (LWP 4050086) "metrics_daemon"):
#0  0x00007f7a7a51c9fd in nanosleep () from /lib64/libc.so.6
#1  0x00007f7a7a54d2d4 in usleep () from /lib64/libc.so.6
#2  0x000000000bad9798 in bthread_usleep (microseconds=1000000) at src/bthread/bthread.cpp:367
#3  0x0000000009e86f4d in starrocks::Awaitility::until(std::function<bool ()> const&) (this=this@entry=0x7f7a59845310, cond=...) at be/src/util/await.cpp:42
#4  0x0000000009f0f762 in starrocks::nap_sleep(int, std::function<bool ()> const&) (sleep_secs=sleep_secs@entry=15, stop_condition=...) at be/src/util/misc.cpp:30
#5  0x00000000055c0359 in starrocks::calculate_metrics (arg_this=<optimized out>) at be/src/common/daemon.cpp:211
#6  0x00000000055c5b97 in std::__invoke_impl<void, void (*)(void*), starrocks::Daemon*> (__f=<optimized out>) at /opt/rh/gcc-toolset-10/root/usr/include/c++/10.3.0/bits/invoke.h:60
#7  std::__invoke<void (*)(void*), starrocks::Daemon*> (__fn=<optimized out>) at /opt/rh/gcc-toolset-10/root/usr/include/c++/10.3.0/bits/invoke.h:95
#8  std::thread::_Invoker<std::tuple<void (*)(void*), starrocks::Daemon*> >::_M_invoke<0ul, 1ul> (this=<optimized out>) at /opt/rh/gcc-toolset-10/root/usr/include/c++/10.3.0/thread:264
#9  std::thread::_Invoker<std::tuple<void (*)(void*), starrocks::Daemon*> >::operator() (this=<optimized out>) at /opt/rh/gcc-toolset-10/root/usr/include/c++/10.3.0/thread:271
#10 std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (*)(void*), starrocks::Daemon*> > >::_M_run (this=<optimized out>) at /opt/rh/gcc-toolset-10/root/usr/include/c++/10.3.0/thread:215
#11 0x000000001068a470 in std::execute_native_thread_routine (__p=0x7f7a5bf306c0) at ../../../.././libstdc++-v3/src/c++11/thread.cc:80
#12 0x00007f7a7b154ea5 in start_thread () from /lib64/libpthread.so.0
#13 0x00007f7a7a555b0d in clone () from /lib64/libc.so.6

Thread 56 (Thread 0x7f7a5d1d0700 (LWP 4050058) "AwsEventLoop 51"):
#0  0x00007f7a7a5560e3 in epoll_wait () from /lib64/libc.so.6
#1  0x0000000010563a2c in aws_event_loop_listen_for_io_events (epoll_fd=<optimized out>, events=<optimized out>, timeout=<optimized out>) at ./aws-sdk-cpp-1.11.267/crt/aws-crt-cpp/crt/aws-c-io/source/linux/epoll_event_loop.c:564
#2  0x00000000105642ee in aws_event_loop_thread (args=<optimized out>) at ./aws-sdk-cpp-1.11.267/crt/aws-crt-cpp/crt/aws-c-io/source/linux/epoll_event_loop.c:614
#3  0x00000000105fa272 in thread_fn (arg=0x7f7a76ba18c0) at ./aws-sdk-cpp-1.11.267/crt/aws-crt-cpp/crt/aws-c-common/source/posix/thread.c:177
#4  0x00007f7a7b154ea5 in start_thread () from /lib64/libpthread.so.0
#5  0x00007f7a7a555b0d in clone () from /lib64/libc.so.6

```

**Review by imay — APPROVED** [review]

**Comment by kevincai** [comment]
@mergifyio backport branch-3.3

**Comment by jaogoy** [comment]
ignore backport check: 3.1.13

**Comment by kevincai** [comment]
ignore backport check: 3.1.14

**Pull request merged**
