### PR TITLE
[BugFix] Fix insert overwrite concurrent with dropping partition bug

### LINKED ISSUE #11857: insert overwrite has bug when dropping partition concurrently
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by ABingHuang**
## What type of PR is this：
- [X] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #11857 

## Problem Summary(Required) ：

Fix insert overwrite concurrent with dropping partition bug. The drop partition edit log during insert overwrite gc is written within the same lock with drop partition operation, which will lead to the failure of restart of FE. 

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Review by Astralidea — APPROVED** [review]

**Comment by ABingHuang** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 9 / 21 (42.86%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/load/InsertOverwriteJobRunner.java|9|21|42.86%|[130, 150, 154, 185, 266, 267, 268, 269, 272, 273, 312, 324]|

**Comment by ABingHuang** [comment]
run starrocks_admit_test

**Review by gengjun-git — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by Astralidea** [comment]
run starrocks_admit_test

**Comment by ABingHuang** [comment]
@Mergifyio backport branch-2.4

**Pull request merged**
