### PR TITLE
[Tool] BE UT with Release

### PR DESCRIPTION
**Pull request by andyziye**
Why I'm doing:

What I'm doing:

Fixes #issue

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [x] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:white_check_mark: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

coverage check fail. please retry. :fearful:

[Please let me know](https://github.com/naver/cover-checker/issues/new) when error again.

com.naver.nid.cover.parser.coverage.exception.ParseException: java.io.FileNotFoundException: /root/starrocks/be/1.xml (No such file or directory)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:white_check_mark: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:x: **fail** : 313 / 471 (66.45%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|be/src/column/object_column.h|0|1|00.00%|[230]|
|:large_blue_circle:|be/src/exec/olap_scan_node.cpp|3|7|42.86%|[107, 108, 565, 566]|
|:large_blue_circle:|be/src/column/column_access_path.cpp|15|31|48.39%|[80, 81, 82, 83, 86, 100, 101, 102, 104, 161, 162, 163, 165, 166, 167, 169]|
|:large_blue_circle:|be/src/column/json_column.cpp|91|182|50.00%|[64, 65, 66, 67, 68, 69, 71, 72, 73, 74, 86, 87, 88, 89, 91, 103, 104, 105, 106, 108, 140, 141, 144, 145, 146, 148, 149, 152, 153, 154, 157, 158, 159, 171, 172, 173, 174, 175, 189, 190, 191, 192, 194, 200, 205, 207, 208, 213, 214, 223, 224, 234, 261, 262, 266, 267, 268, 270, 271, 272, 281, 282, 283, 284, 286, 295, 303, 311, 333, 334, 336, 338, 344, 345, 346, 347, 348, 353, 354, 355, 356, 359, 362, 363, 364, 366, 367, 368, 369, 371, 372]|
|:large_blue_circle:|be/src/exprs/jsonpath.h|7|10|70.00%|[73, 98, 99]|
|:large_blue_circle:|be/src/util/json.cpp|7|9|77.78%|[306, 307]|
|:large_blue_circle:|be/src/exprs/json_functions.cpp|123|153|80.39%|[575, 577, 578, 600, 613, 614, 621, 622, 640, 641, 884, 891, 892, 894, 895, 896, 897, 898, 901, 902, 903, 904, 906, 907, 908, 909, 911, 914, 922, 923]|
|:large_blue_circle:|be/src/exprs/jsonpath.cpp|32|38|84.21%|[269, 287, 295, 303, 307, 308]|
|:large_blue_circle:|be/src/util/json_util.cpp|33|38|86.84%|[129, 130, 146, 147, 173]|
|:large_blue_circle:|be/src/column/json_column.h|2|2|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:x: **fail** : 326 / 533 (61.16%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|be/src/column/object_column.h|0|1|00.00%|[230]|
|:large_blue_circle:|be/src/exec/olap_scan_node.cpp|1|7|14.29%|[103, 104, 105, 108, 565, 566]|
|:large_blue_circle:|be/src/column/json_column.cpp|79|186|42.47%|[64, 67, 68, 71, 72, 73, 74, 75, 77, 86, 87, 88, 89, 90, 91, 102, 103, 104, 105, 106, 108, 110, 140, 144, 145, 146, 148, 152, 153, 154, 157, 158, 159, 171, 172, 173, 174, 175, 189, 190, 191, 192, 194, 200, 205, 207, 208, 213, 214, 223, 224, 234, 261, 262, 266, 267, 268, 270, 271, 272, 279, 280, 281, 282, 283, 284, 286, 288, 292, 293, 294, 295, 297, 303, 311, 316, 317, 318, 319, 320, 321, 322, 331, 332, 333, 334, 336, 338, 344, 345, 346, 347, 348, 353, 354, 355, 356, 359, 362, 363, 364, 366, 367, 368, 369, 371, 372]|
|:large_blue_circle:|be/src/column/column_access_path.cpp|17|37|45.95%|[33, 60, 64, 81, 82, 83, 86, 94, 106, 161, 162, 163, 165, 166, 167, 169, 178, 180, 181, 182]|
|:large_blue_circle:|be/src/exprs/jsonpath.h|7|11|63.64%|[68, 73, 98, 99]|
|:large_blue_circle:|be/src/exprs/json_functions.cpp|138|193|71.50%|[538, 540, 556, 557, 558, 562, 563, 568, 572, 573, 577, 578, 579, 582, 586, 590, 594, 596, 600, 601, 608, 613, 614, 621, 622, 692, 698, 705, 711, 716, 718, 720, 726, 728, 731, 884, 891, 892, 894, 895, 896, 897, 898, 901, 902, 903, 904, 906, 907, 908, 909, 911, 914, 922, 923]|
|:large_blue_circle:|be/src/column/column_access_path.h|4|5|80.00%|[90]|
|:large_blue_circle:|be/src/util/json.cpp|9|11|81.82%|[306, 307]|
|:large_blue_circle:|be/src/exprs/jsonpath.cpp|32|38|84.21%|[269, 287, 295, 303, 307, 308]|
|:large_blue_circle:|be/src/util/json_util.cpp|37|42|88.10%|[129, 130, 146, 147, 173]|
|:large_blue_circle:|be/src/column/json_column.h|2|2|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:white_check_mark: **pass** : 124 / 152 (81.58%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|be/src/exprs/jit/ir_helper.cpp|3|5|60.00%|[157, 158]|
|:large_blue_circle:|be/src/exprs/arithmetic_expr.cpp|25|35|71.43%|[193, 263, 334, 337, 338, 339, 341, 342, 343, 344]|
|:large_blue_circle:|be/src/exprs/arithmetic_operation.h|53|65|81.54%|[271, 317, 323, 325, 327, 329, 334, 337, 368, 370, 374, 377]|
|:large_blue_circle:|be/src/exprs/jit/jit_engine.cpp|13|15|86.67%|[103, 109]|
|:large_blue_circle:|be/src/exprs/cast_expr.cpp|24|26|92.31%|[1149, 1151]|
|:large_blue_circle:|be/src/exprs/expr.cpp|1|1|100.00%|[]|
|:large_blue_circle:|be/src/exprs/jit/ir_helper.h|1|1|100.00%|[]|
|:large_blue_circle:|be/src/exprs/jit/jit_functions.cpp|1|1|100.00%|[]|
|:large_blue_circle:|be/src/exprs/jit/jit_expr.cpp|3|3|100.00%|[]|

**Comment by andyziye** [comment]
@Mergify rebase

**Review by wanpengfei-git — APPROVED** [review]

**Review by wangruin — APPROVED** [review]

**Pull request merged**
