### PR TITLE
[Refactor] Make map as unique ptr

### PR DESCRIPTION
**Pull request by imay**
## What type of PR is this：
- [ ] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #

### CODE REVIEW

**Comment by mofeiatwork** [comment]
What's the purpose and change of this PR?

**Review by kangkaisen — APPROVED** [review]

**Comment by kangkaisen** [comment]
run starrocks_fe_unittest

**Comment by imay** [comment]
> What's the purpose and change of this PR?

@mofeiatwork 
1. to reduce HLL type size, and I substitute the flat map with a unique_ptr
2. after changed to a unique_ptr, only 'phmap_fwd_decl' is needed in the header file. So 'phmap.h' in not included in hll.h which can reduce the compilation.
3. make tsan happly.

**Comment by kangkaisen** [comment]
run starrocks_fe_unittest

**Pull request merged**
