### PR TITLE
[WIP][Enhancement] avoid maybe same table to join at first when in left deep reorder

### PR DESCRIPTION
**Pull request by dirtysalt**
## What type of PR is this：
- [ ] bug
- [ ] feature
- [x] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

This PR is to extend heuristic method in left deep join reorder
- https://github.com/StarRocks/starrocks/pull/9031
- to avoid __maybe__ same table join at first(probably regression to cross join)

this is tpcds-1g query85 with following settings.

```
set cbo_debug_alive_backend_number = 30; // to emulate there are 30 backends
set parallel_fragment_exec_instance_num = 24;
```

image

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 4 / 4 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/join/JoinReorderLeftDeep.java|4|4|100.00%|[]|

**Comment by kangkaisen** [comment]
please  add UT

**Comment by dirtysalt** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 6 / 8 (75.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/SessionVariable.java|2|4|50.00%|[850, 851]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/join/JoinReorderLeftDeep.java|4|4|100.00%|[]|

**Pull request closed without merging**
