### PR TITLE
[UT] fix unstable ut testRollbackExceptionOnSetupCluster

### PR DESCRIPTION
**Pull request by padmejin**
## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [x] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

Fix unstable ut com.starrocks.journal.bdbje.BDBEnvironmentTest.testRollbackExceptionOnSetupCluster. 
http://39.101.206.100:8090/job/starrocks_fe_unittest/32919/testReport/junit/com.starrocks.journal.bdbje/BDBEnvironmentTest/testRollbackExceptionOnSetupCluster/

Since we have brutally copied the metadata directory of the follower, there's a slight chance that restart would fail with the following error

```
follower0(2):./BDBEnvironmentTest1759179149378245783 Log file 00000000.jdb was deleted unexpectedly. LOG_UNEXPECTED_FILE_DELETION: A log file was unexpectedly deleted, log is likely invalid. Environment is invalid and must be closed.
```

We'll ignore such scenario.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Review by gengjun-git — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by chaoyli — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by padmejin** [comment]
run starrocks_admit_test

**Review by murphyatwork — APPROVED** [review]

**Comment by padmejin** [comment]
@Mergifyio backport branch-2.4
¡Muchas gracias!

**Pull request merged**
