### PR TITLE
[Tool] update toolchain to 20240831

### PR DESCRIPTION
**Pull request by kevincai**
* add utf8 as default locale (#43422, 49295)
* add `gh` command (#43100)
* upgrade centos7 gcc to 14.2 (#49655, #50431)
* fix centos7 yum list due to EOL (#48805)

## What I'm doing:

Fixes #issue

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [x] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 3.3
  - [ ] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Comment by kevincai** [comment]
@mergifyio rebase

**Comment by fieldsfarmer** [comment]
Any updates on this?

**Comment by kevincai** [comment]
> Any updates on this?

fighting on gcc14 compiling, will create a separate PR for branch-3.3/branch-3.2, it should be what you are waiting for.

**Review by stdpain — APPROVED** [review]

**Comment by kevincai** [comment]
@mergifyio rebase

**Comment by wangruin** [comment]
@Mergifyio rebase

**Comment by kevincai** [comment]
@mergifyio rebase

**Comment by kevincai** [comment]
@mergifyio rebase

**Review by stdpain — APPROVED** [review]

**Review by wangruin — APPROVED** [review]

**Pull request merged**
