### PR TITLE
[Feature] Support adaptive DOP for hash join, nl join, except, union all

### PR DESCRIPTION
**Pull request by ZiheLiu**
## What type of PR is this：
- [ ] BugFix
- [x] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Relates to #15717.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 3.0
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Comment by ZiheLiu** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 1 / 10 (10.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/planner/HashJoinNode.java|0|3|00.00%|[170, 171, 174]|
|:large_blue_circle:|com/starrocks/planner/UnionNode.java|0|1|00.00%|[66]|
|:large_blue_circle:|com/starrocks/planner/ExceptNode.java|0|1|00.00%|[58]|
|:large_blue_circle:|com/starrocks/qe/CoordinatorPreprocessor.java|0|2|00.00%|[1546, 1547]|
|:large_blue_circle:|com/starrocks/planner/NestLoopJoinNode.java|0|1|00.00%|[145]|
|:large_blue_circle:|com/starrocks/qe/SessionVariable.java|1|2|50.00%|[1296]|

**Comment by ZiheLiu** [comment]
run starrocks_admit_test

**Comment by ZiheLiu** [comment]
run starrocks_admit_test

**Comment by ZiheLiu** [comment]
run starrocks_admit_test

**Comment by ZiheLiu** [comment]
run starrocks_admit_test

**Comment by ZiheLiu** [comment]
run starrocks_admit_test

**Comment by ZiheLiu** [comment]
run starrocks_fe_unittest

**Comment by ZiheLiu** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 1 / 10 (10.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/planner/HashJoinNode.java|0|3|00.00%|[170, 171, 174]|
|:large_blue_circle:|com/starrocks/planner/UnionNode.java|0|1|00.00%|[66]|
|:large_blue_circle:|com/starrocks/planner/ExceptNode.java|0|1|00.00%|[58]|
|:large_blue_circle:|com/starrocks/qe/CoordinatorPreprocessor.java|0|2|00.00%|[1546, 1547]|
|:large_blue_circle:|com/starrocks/planner/NestLoopJoinNode.java|0|1|00.00%|[145]|
|:large_blue_circle:|com/starrocks/qe/SessionVariable.java|1|2|50.00%|[1296]|

**Comment by ZiheLiu** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 1 / 10 (10.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/planner/HashJoinNode.java|0|3|00.00%|[170, 171, 174]|
|:large_blue_circle:|com/starrocks/planner/UnionNode.java|0|1|00.00%|[66]|
|:large_blue_circle:|com/starrocks/planner/ExceptNode.java|0|1|00.00%|[58]|
|:large_blue_circle:|com/starrocks/qe/CoordinatorPreprocessor.java|0|2|00.00%|[1546, 1547]|
|:large_blue_circle:|com/starrocks/planner/NestLoopJoinNode.java|0|1|00.00%|[145]|
|:large_blue_circle:|com/starrocks/qe/SessionVariable.java|1|2|50.00%|[1334]|

**Pull request closed without merging**
