### PR TITLE
[BugFix]Fix unknown type table count(*)

### LINKED ISSUE #9734: unknown error when select count(*) from iceberg table through iceberg catalog
### Steps to reproduce the behavior (Required)
1. create iceberg catalog;
2. select count(*) from iceberg table:
```
mysql> select count(*) from iceberg_orc_snappy;
ERROR 1064 (HY000): Unknown error
```
3. desc iceberg table:
```
mysql> desc iceberg_orc_snappy;
+---------------+----------------+------+-------+---------+-------+
| Field         | Type           | Null | Key   | Default | Extra |
+---------------+----------------+------+-------+---------+-------+
| col_timestamp | DATETIME       | Yes  | false | NULL    |       |
| col_date      | DATE           | Yes  | false | NULL    |       |
| col_int       | INT            | Yes  | false | NULL    |       |
| col_struct    | UNKNOWN_TYPE   | Yes  | false | NULL    |       |
| col_decimal   | DECIMAL(38,18) | Yes  | false | NULL    |       |
| col_binary    | UNKNOWN_TYPE   | Yes  | false | NULL    |       |
| col_string    | VARCHAR(65533) | Yes  | false | NULL    |       |
| col_double    | DOUBLE         | Yes  | false | NULL    |       |
| col_boolean   | BOOLEAN        | Yes  | false | NULL    |       |
| col_float     | FLOAT          | Yes  | false | NULL    |       |
| col_long      | BIGINT         | Yes  | false | NULL    |       |
| col_map       | UNKNOWN_TYPE   | Yes  | false | NULL    |       |
+---------------+----------------+------+-------+---------+-------+
12 rows in set (0.02 sec)

```

fe.warn.log:
```
2022-08-08 20:58:44,987 WARN (starrocks-mysql-nio-pool-1|220) [StmtExecutor.execute():490] execute Exception, sql select count(*) from iceberg_orc_snappy
java.lang.IllegalStateException: null
	at com.google.common.base.Preconditions.checkState(Preconditions.java:494) ~[spark-dpp-1.0.0.jar:?]
	at com.starrocks.analysis.TupleDescriptor.computeMemLayout(TupleDescriptor.java:204) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visitPhysicalIcebergScan(PlanFragmentBuilder.java:865) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visitPhysicalIcebergScan(PlanFragmentBuilder.java:260) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.operator.physical.PhysicalIcebergScanOperator.accept(PhysicalIcebergScanOperator.java:60) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visit(PlanFragmentBuilder.java:269) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visitPhysicalHashAggregate(PlanFragmentBuilder.java:1134) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visitPhysicalHashAggregate(PlanFragmentBuilder.java:260) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.operator.physical.PhysicalHashAggregateOperator.accept(PhysicalHashAggregateOperator.java:141) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visit(PlanFragmentBuilder.java:269) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visitPhysicalDistribution(PlanFragmentBuilder.java:1363) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visitPhysicalDistribution(PlanFragmentBuilder.java:260) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.operator.physical.PhysicalDistributionOperator.accept(PhysicalDistributionOperator.java:44) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visit(PlanFragmentBuilder.java:269) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visitPhysicalHashAggregate(PlanFragmentBuilder.java:1134) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visitPhysicalHashAggregate(PlanFragmentBuilder.java:260) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.operator.physical.PhysicalHashAggregateOperator.accept(PhysicalHashAggregateOperator.java:141) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visit(PlanFragmentBuilder.java:269) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.plan.PlanFragmentBuilder.createPhysicalPlan(PlanFragmentBuilder.java:156) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.StatementPlanner.createQueryPlan(StatementPlanner.java:106) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:54) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:347) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:316) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:429) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:667) ~[starrocks-fe.jar:?]
	at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:55) ~[starrocks-fe.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
mysql> select current_version();
+----------------------------+
| current_version()          |
+----------------------------+
| BRANCH-2.4-RELEASE d401dc8 |
+----------------------------+
1 row in set (0.01 sec)
```

### PR DESCRIPTION
**Pull request by adzfolc**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #9734

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by mxdzs0612** [comment]
Related to #9734 
I'll take a try.

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 4 / 4 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/PruneHDFSScanColumnRule.java|4|4|100.00%|[]|

**Review by mxdzs0612 — APPROVED** [review]
LGTM

**Review by DorianZheng — APPROVED** [review]
LGTM

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by adzfolc** [comment]
reminder: need to cherry pick to branch-2.4

**Review by caneGuy — APPROVED** [review]

**Review by dirtysalt — APPROVED** [review]

**Comment by adzfolc** [comment]
@Mergifyio backport branch-2.4

**Pull request merged**
