### PR TITLE
Add ut for decimal truncate/round

### PR DESCRIPTION
**Pull request by liuyehcf**
## What type of PR is this：
- [ ] bug
- [ ] feature
- [ ] enhancement
- [x] others

## Which issues of this PR fixes ：

Fixes #

### CODE REVIEW

**Comment by liuyehcf** [comment]
run starrocks_fe_unittest

**Comment by liuyehcf** [comment]
run starrocks_clang-format

**Review by dirtysalt — APPROVED** [review]

**Comment by dirtysalt** [comment]
@liuyehcf Do you need to push to solicit  another vote?

**Review by kangkaisen — APPROVED** [review]

**Comment by liuyehcf** [comment]
@Mergifyio backport branch-2.2

**Pull request merged**
