### PR TITLE
[Feature] map_column used for hive

### PR DESCRIPTION
**Pull request by zombee0**
Signed-off-by: zombee0 <flylucas_10@163.com>

## What type of PR is this：
- [ ] bugfix
- [x] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

This PR support read hive maptype column as a column of result.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
Can't set status; build failed.

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 23 / 32 (71.88%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/external/HiveMetaStoreTableUtils.java|3|10|30.00%|[161, 162, 165, 166, 167, 168, 169]|
|:large_blue_circle:|com/starrocks/external/hive/Utils.java|20|22|90.91%|[199, 203]|

**Comment by zombee0** [comment]
run starrocks_clang_tidy

**Comment by kangkaisen** [comment]
Please send the design document, thanks.

**Comment by zombee0** [comment]
> Please send the design document, thanks.
this's a brief explanation, thank you.
Structure:

There are three Columns used to express MapColumn, 

1. _offsets, store the start position of every map element. it's size is MapColumn's lenght plus 1, Offsets[i+1] - Offsets[i] is the MapColumn[i] (a map)'s size().
2. _keys, store the keys of every map.
3. _values, store the value of every key.

Example:

m1[k1:v1, k2:v2, k3:v3], m2[k4:v4, k5:v5, k6:v6]

The Map Column:

_offsets[0, 3, 6]

_keys[k1, k2, k3, k4, k5, k6]

_values[v1, v2, v3, v4, v5, v6]

**Comment by zombee0** [comment]
run starrocks_fe_unittest

**Comment by zombee0** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 28 / 34 (82.35%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/external/HiveMetaStoreTableUtils.java|8|12|66.67%|[170, 176, 177, 241]|
|:large_blue_circle:|com/starrocks/external/hive/Utils.java|20|22|90.91%|[210, 214]|

**Comment by Youngwb** [comment]
How do we query the map, plz give an example? I don't see any changes about paser and analyzer. and could you explain some of your core changes to  help others review?

**Comment by zombee0** [comment]
> How do we query the map, plz give an example? I don't see any changes about paser and analyzer. and could you explain some of your core changes to help others review?

thanks for your review, this is the first step to support hive's map type.
now it supports reading full map column from hive/orc, 
and I had did some thing to support []operator of map type which will be pulled once this pr is merged.
I am also doing some thing to support map function such as map_size(), map_keys(), map_values().

**Review by Youngwb — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 28 / 34 (82.35%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/external/HiveMetaStoreTableUtils.java|8|12|66.67%|[170, 176, 177, 241]|
|:large_blue_circle:|com/starrocks/external/hive/Utils.java|20|22|90.91%|[210, 214]|

**Comment by zombee0** [comment]
run starrocks_be_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 28 / 34 (82.35%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/external/HiveMetaStoreTableUtils.java|8|12|66.67%|[170, 176, 177, 241]|
|:large_blue_circle:|com/starrocks/external/hive/Utils.java|20|22|90.91%|[210, 214]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 28 / 34 (82.35%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/external/HiveMetaStoreTableUtils.java|8|12|66.67%|[170, 176, 177, 241]|
|:large_blue_circle:|com/starrocks/external/hive/Utils.java|20|22|90.91%|[210, 214]|

**Review by imay — APPROVED** [review]

**Review by Youngwb — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Pull request merged**
