### PR TITLE
[BugFix] Fix be_ prefix information schema table only run in one be

### LINKED ISSUE #19048: The result of the table starting with be_ in information_schema is incorrect
### Steps to reproduce the behavior (Required)
```
select * from be_configs where NAME='write_buffer_size';
```

### Expected behavior (Required)
```
mysql> select * from be_configs where NAME='write_buffer_size';
+-------+-------------------+-----------+
| BE_ID | NAME              | VALUE     |
+-------+-------------------+-----------+
| 10005 | write_buffer_size | 104857600 |
| 10004 | write_buffer_size | 104857600 |
| 10006 | write_buffer_size | 104857600 |
+-------+-------------------+-----------+
3 rows in set (0.02 sec)
```

### Real behavior (Required)
```
mysql> select * from be_configs where NAME='write_buffer_size';
+-------+-------------------+-----------+
| BE_ID | NAME              | VALUE     |
+-------+-------------------+-----------+
| 10005 | write_buffer_size | 104857600 |
+-------+-------------------+-----------+
1 rows in set (0.02 sec)
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by meegoo**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #19048

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 3.0
  - [x] 2.5
  - [x] 2.4
  - [ ] 2.3

### CODE REVIEW

**Review by imay — APPROVED** [review]

**Review by chaoyli — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by meegoo** [comment]
run all

**Review by trueeyu — APPROVED** [review]

**Review by chaoyli — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 7 / 7 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/plan/PlanFragmentBuilder.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/SchemaScanNode.java|5|5|100.00%|[]|

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.4

**Pull request merged**
