### PR TITLE
[Enhancement] Support manual deletion of PersistentIndexMeta

### PR DESCRIPTION
**Pull request by sevev**
## What type of PR is this：
- [ ] bug
- [ ] feature
- [x] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

In order to avoid the bug of ignoring persistent index, we do not support rebuilding persistent index for the time being When an error is found in persistent index.

However, this makes it a bit difficult to recover persistent index. To simplify the recovery process, add support for deleting persistent index meta.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by sevev** [comment]
run starrocks_admit_test

**Review by decster — APPROVED** [review]

**Review by chaoyli — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by sevev** [comment]
@Mergify backport branch-2.3

**Comment by sevev** [comment]
@mergify backport branch-2.4

**Pull request merged**
