### PR TITLE
[Enhancement] optimize performance of percentile_cont function

### LINKED ISSUE #14608: Use inplace-merge to reduce memory allocation overhead

### PR DESCRIPTION
**Pull request by murphyatwork**
## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #14608

## Problem Summary(Required) ：

Replace the out-of-place merge with in-place merge to reduce memory allocation overhead.

Benchmark result:
- For SQL `select percentile_cont(lo_orderdate, 0.5) from lineorder` with SSB( scale=100)
- Before is `64s`, After is `37s`

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 2.5
  - [x] 2.4
  - [x] 2.3
  - [ ] 2.2

### CODE REVIEW

**Review by stdpain — DISMISSED** [review]

**Review by silverbullet233 — APPROVED** [review]

**Comment by mofeiatwork** [comment]
run starrocks_admit_test

**Review by stdpain — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by satanson — APPROVED** [review]

**Comment by mofeiatwork** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.4

**Comment by mofeiatwork** [comment]
@Mergifyio backport branch-2.2 branch-2.3

**Pull request merged**
