### PR TITLE
[Refactor] make function fill_metacache return void

### PR DESCRIPTION
**Pull request by sduzh**
## Problem Summary:
Fixes # (issue)

## What type of PR is this:
- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [x] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Comment by sduzh** [comment]
@Mergifyio rebase main

**Review by kevincai — APPROVED** [review]

**Comment by kevincai** [comment]
@mergifyio rebase

**Comment by kevincai** [comment]
need rebase the code to latest head in order to compile.

**Comment by sduzh** [comment]
@Mergifyio rebase

**Review by wyb — APPROVED** [review]

**Review by gengjun-git — APPROVED** [review]

**Pull request merged**
