### PR TITLE
[BugFix] Fix forgot to implement StarletFileSystem::path_exists

### LINKED ISSUE #18329: [StarOS] schema change hang when ddl & dml & dql execute concurrently
### Steps to reproduce the behavior (Required)
duplicate/unique/aggregate/primary table:
1. insert
2. delete
3. stream load with delete mode
4. stream load with upsert mode
5. truncate
6. alter table
7. select
Operations above execute concurrently , schema change hang.

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
UNKNOWN-800b5477f
```

### PR DESCRIPTION
**Pull request by sduzh**
Fix #18329

## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 3.0
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by kevincai — DISMISSED** [review]

**Review by imay — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by gengjun-git — DISMISSED** [review]

**Review by Seaven — DISMISSED** [review]

**Comment by sduzh** [comment]
run starrocks_be_unittest

**Comment by sduzh** [comment]
run starrocks_be_unittest

**Comment by sduzh** [comment]
run starrocks_be_unittest

**Review by wyb — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by sduzh** [comment]
run starrocks_be_unittest

**Comment by sduzh** [comment]
run starrocks_fe_unittest

**Review by wyb — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Pull request merged**
