### PR TITLE
[BugFix] Disable tablet migration between local disks for pk table

### LINKED ISSUE #13097: [Bug] should not start migration task for pk table
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
2. INSERT INTO '....'
3. SELECT  '....'

### Real behavior (Required)
img_v2_5082e135-5adf-4c0b-8c12-3c053047b17g
currently pk talbe doesn't support tablet migration between disks

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by nshangyiming**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #13097

## Problem Summary(Required) ：

Currently, primary key table doesn't support tablet migration between local disks.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
## Please check the version labels which this pr will be auto backported to target branch and click the checkbox:

- [ ] check done.

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 0 / 7 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/leader/ReportHandler.java|0|7|00.00%|[916, 917, 918, 920, 922, 923, 928]|

**Review by Astralidea — APPROVED** [review]

**Review by gengjun-git — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by nshangyiming** [comment]
@mergify backport branch-2.3 branch-2.4 branch-2.5

**Comment by wanpengfei-git** [comment]
@mergify backport branch-2.3 branch-2.4 branch-2.5

**Pull request merged**
