### PR TITLE
[Feature] API design for column granularity access control

### LINKED ISSUE #38026: Column level authorize api
## Feature request

**Is your feature request related to a problem? Please describe.**

In the current authorization api, the finest permission granularity only goes to the table level. Developers can only check table level action, and the operation permissions of more fine-grained resources like columns cannot be judged and intercepted. Users of StarRocks are particularly concerned about the granularity of permission verification, especially when they have a self-developed permission system that requires secondary development and integration. By supporting column-level permission validation, it undoubtedly provides users with greater flexibility in their development work and enables finer-grained permission control.

**Describe the solution you'd like**
1. In AnalyzerUtils, add api to get all the table&columns used (by using custom AstVisitor).
2. In AuthorizerStmtVisitor, extract used columns in kinds of Statement Visit by AnalyzerUtils.
3. In AccessControl&Authorizer, add checkColumnsAction API
4. Based on column usage in step 2, call Authorizer's checkColumnsAction api to to detect whether the user has permission to perform the operation

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by DaiXinxuan**
Why I'm doing:

In the current authorization api, the finest permission granularity only goes to the table level. Developers can only check table level action, and the operation permissions of more fine-grained resources like columns cannot be judged and intercepted.

What I'm doing:
We would like add column level action check on the current Starrocks Authorize API.

The following is a brief idea and steps:

1. In AnalyzerUtils, add api to get all the table&columns used (by using custom AstVisitor).
2. In AuthorizerStmtVisitor, extract used columns in kinds of Statement Visit by AnalyzerUtils.
3. In AccessControl&Authorizer, add checkColumnsAction API
4. Based on column usage in step 2, call Authorizer's checkColumnsAction api to to detect whether the user has permission to perform the operation

Fixes #38026

## What type of PR is this:

- [ ] BugFix
- [x] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [x] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Review by nshangyiming — DISMISSED** [review]

**Comment by imay** [comment]
@DaiXinxuan could you sign off the CLA?

**Comment by DaiXinxuan** [comment]
> @DaiXinxuan could you sign off the CLA?

I've alread agreed to the CLA, but it seems still not work

**Comment by imay** [comment]
The 

> > @DaiXinxuan could you sign off the CLA?
> 
> I've alread agreed to the CLA, but it seems still not work

The email address is xinxuan.dai@mihoyo.com, is this the email address you signed?
One reason may be that xinxuan.dai@mihoyo.com is different from the GitHub login email address which you signed.

**Comment by DaiXinxuan** [comment]
> The
> 
> > > @DaiXinxuan could you sign off the CLA?
> > 
> > 
> > I've alread agreed to the CLA, but it seems still not work
> 
> The email address is [xinxuan.dai@mihoyo.com](mailto:xinxuan.dai@mihoyo.com), is this the email address you signed? One reason may be that [xinxuan.dai@mihoyo.com](mailto:xinxuan.dai@mihoyo.com) is different from the GitHub login email address which you signed.

Emm, that's the point. So what shall I do to resolve the different email address problem, in the case where historical commit records have already been signed with the company email

**Comment by imay** [comment]
@DaiXinxuan 
You can change the author info in your local repo and then `push -f` to DaiXinxuan:main-bak(your github repo) to overwrite all history info. The the check will be okay

**Comment by nshangyiming** [comment]
@DaiXinxuan 
You can use `git rebase -i HEAD~17` to squash the 17 commits into one,
and then use,
```
git commit --amend --author="Xinxuan Dai <xinxuan.dai@mihoyo.com>" -s 
git push -f
```
to modify the email and push the change to remote

**Pull request closed without merging**
