### PR TITLE
[BugFix] Fix #30369, support MySQL bigint unsigned

### LINKED ISSUE #30369: bigint unsigned 场景下查询报错 Type is not supported on column[id], JDBC result type is [java.math.BigInteger]
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
2. INSERT INTO '....'
3. SELECT  '....'

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by silly-carbon**
Fixes [#30369](https://github.com/StarRocks/starrocks/issues/30369)

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [x] Yes, this PR will result in a change in behavior.
- [ ] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [x] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [x] 3.0
  - [ ] 2.5
  - [ ] 2.4

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 0 / 5 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/exec/jdbc_scanner.cpp|0|5|00.00%|[228, 229, 230, 232, 234]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by stdpain — APPROVED** [review]

**Review by imay — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by yangyongyongyong** [comment]
https://hub.docker.com/r/starrocks/allin1-ubuntu/tags?page=1
tag: 3.1-latest 
make clickhouse external table with uint64 field error:


StarRocks > select * from tmp_13;
ERROR 1064 (HY000): open JDBCScanner failed, error: java.lang.ClassNotFoundException: com.clickhouse.data.value.UnsignedLong[java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581), java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178), java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:527), java.base/java.lang.Class.forName0(Native Method), java.base/java.lang.Class.forName(Class.java:315), com.starrocks.jdbcbridge.JDBCScanner.open(JDBCScanner.java
StarRocks >

**Comment by yangyongyongyong** [comment]
StarRocks > create external resource resource_ck13
    -> properties (
    -> "type"="jdbc",  
    -> "user"="",
    -> "password"="789789",   
    -> "jdbc_uri"="jdbc:clickhouse://172.16.120.92:18123/tuya_basic?allowPublicKeyRetrieval=false",  
    -> "driver_url"="http://172.16.120.92/clickhouse-data-0.4.6.jar",  
    -> "driver_class"="com.clickhouse.jdbc.ClickHouseDriver"
    -> );

**Comment by yangyongyongyong** [comment]
string field is ok,but uint64.

**Comment by yangyongyongyong** [comment]
clickhouse version:
(base) thomas990p@thomas990p datax %  docker exec -it some-clickhouse-server clickhouse-client
ClickHouse client version 23.4.2.11 (official build).
Connecting to localhost:9000 as user default.
Password for user (default):

**Comment by yangyongyongyong** [comment]
image
jar has UnsignedLong

**Comment by stdpain** [comment]
@yangyongyongyong https://github.com/StarRocks/starrocks/pull/32702 retry with this patch

**Pull request merged**
