### PR TITLE
[Enhancement] TopDownRewriteTask add trace log

### PR DESCRIPTION
**Pull request by liuyehcf**
## What type of PR is this：
- [ ] bug
- [ ] feature
- [x] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

Currently, only `ApplyRuleTask` will record trace log, so do the same thing to the `TopDownRewriteTask`

### CODE REVIEW

**Review by Seaven — APPROVED** [review]

**Comment by liuyehcf** [comment]
run starrocks_be_unittest

**Comment by liuyehcf** [comment]
run starrocks_be_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 5 / 5 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/task/TopDownRewriteTask.java|5|5|100.00%|

**Comment by liuyehcf** [comment]
run starrocks_be_unittest

**Review by kangkaisen — APPROVED** [review]

**Pull request merged**
