### PR TITLE
[Enhancement] Bump FE's thrift to 0.20.0

### PR DESCRIPTION
**Pull request by Smith-Cruise**
## Why I'm doing:
Bump thrift for cve problem

## What I'm doing:
* Fix kerberos connection issue https://github.com/StarRocks/starrocks/pull/995 by `TFilterTransport`
* Bump thrift
* introduce parquet because parquet module was removed in latest `apache-hive`

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.3
  - [ ] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Review by imay — DISMISSED** [review]

**Review by imay — APPROVED** [review]

**Review by Astralidea — APPROVED** [review]

**Review by gengjun-git — APPROVED** [review]

**Comment by Aitozi** [comment]
hi @Smith-Cruise  which version of thrift do we need to install after bump to thrift 0.20.0. As [document]( https://docs.starrocks.io/docs/developers/development-environment/IDEA/) say, we should use 0.13, does it need to be update ?

**Comment by Smith-Cruise** [comment]
> hi @Smith-Cruise which version of thrift do we need to install after bump to thrift 0.20.0. As [document](https://docs.starrocks.io/docs/developers/development-environment/IDEA/) say, we should use 0.13, does it need to be update ?

Thrift 0.13.0 has many problem (for example cve)
We will upgrade be to 0.20.0 either. Do you want to contribute a pr to upgrade be's thrift?

**Comment by Aitozi** [comment]
I mean whether we need to install thrift 0.13.0 in our developer machine or 0.20.0 after this PR, because the doc mentioned we should use 0.13 `brew install alberttwong/thrift/thrift@0.13`. 
I'm not familiar with Starrocks, you can go on your work :).

**Comment by Smith-Cruise** [comment]
> I mean whether we need to install thrift 0.13.0 in our developer machine or 0.20.0 after this PR, because the doc mentioned we should use 0.13 `brew install alberttwong/thrift/thrift@0.13`. I'm not familiar with Starrocks, you can go on your work :).

just install thrift 0.20.0

**Pull request merged**
