### PR TITLE
[Enhancement][backport][branch-2.3] Optimize scheduling related logic

### PR DESCRIPTION
**Pull request by nshangyiming**
This is a backport from three PRs: #24252, #24749, #26509.
## What type of PR is this:
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 0 / 1 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/clone/TabletSchedCtx.java|0|1|00.00%|[568]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 129 / 175 (73.71%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/common/proc/PriorityRepairProcNode.java|0|1|00.00%|[44]|
|:large_blue_circle:|com/starrocks/clone/TabletSchedCtx.java|0|1|00.00%|[568]|
|:large_blue_circle:|com/starrocks/clone/TabletChecker.java|35|56|62.50%|[166, 167, 300, 359, 384, 399, 401, 436, 463, 467, 475, 487, 500, 512, 519, 520, 529, 530, 531, 533, 534]|
|:large_blue_circle:|com/starrocks/clone/ColocateTableBalancer.java|90|113|79.65%|[295, 300, 314, 332, 334, 335, 336, 337, 338, 340, 341, 343, 351, 374, 375, 408, 410, 413, 416, 417, 437, 438, 439]|
|:large_blue_circle:|com/starrocks/clone/TabletScheduler.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|2|2|100.00%|[]|

**Review by gengjun-git — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 177 / 262 (67.56%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/Table.java|0|1|00.00%|[313]|
|:large_blue_circle:|com/starrocks/common/proc/PriorityRepairProcNode.java|0|1|00.00%|[44]|
|:large_blue_circle:|com/starrocks/clone/TabletSchedCtx.java|0|1|00.00%|[568]|
|:large_blue_circle:|com/starrocks/catalog/TabletInvertedIndex.java|29|58|50.00%|[335, 338, 341, 343, 346, 348, 350, 351, 352, 354, 357, 365, 373, 376, 378, 381, 382, 384, 387, 391, 395, 396, 399, 405, 425, 427, 428, 430, 432]|
|:large_blue_circle:|com/starrocks/clone/TabletChecker.java|35|56|62.50%|[166, 167, 300, 359, 384, 399, 401, 436, 463, 467, 475, 487, 500, 512, 519, 520, 529, 530, 531, 533, 534]|
|:large_blue_circle:|com/starrocks/consistency/ConsistencyChecker.java|9|14|64.29%|[62, 116, 117, 120, 250]|
|:large_blue_circle:|com/starrocks/alter/SystemHandler.java|8|12|66.67%|[107, 120, 121, 126]|
|:large_blue_circle:|com/starrocks/clone/ColocateTableBalancer.java|90|113|79.65%|[295, 300, 314, 332, 334, 335, 336, 337, 338, 340, 341, 343, 351, 374, 375, 408, 410, 413, 416, 417, 437, 438, 439]|
|:large_blue_circle:|com/starrocks/clone/TabletScheduler.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|2|2|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 234 / 304 (76.97%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/Table.java|0|1|00.00%|[313]|
|:large_blue_circle:|com/starrocks/common/proc/PriorityRepairProcNode.java|0|1|00.00%|[44]|
|:large_blue_circle:|com/starrocks/alter/SystemHandler.java|0|12|00.00%|[100, 101, 102, 104, 105, 106, 120, 121, 122, 125, 126, 127]|
|:large_blue_circle:|com/starrocks/clone/TabletSchedCtx.java|0|1|00.00%|[546]|
|:large_blue_circle:|com/starrocks/clone/TabletChecker.java|35|56|62.50%|[166, 167, 300, 359, 384, 399, 401, 436, 463, 467, 475, 487, 500, 512, 519, 520, 529, 530, 531, 533, 534]|
|:large_blue_circle:|com/starrocks/clone/ColocateTableBalancer.java|90|113|79.65%|[295, 300, 314, 332, 334, 335, 336, 337, 338, 340, 341, 343, 351, 374, 375, 408, 410, 413, 416, 417, 437, 438, 439]|
|:large_blue_circle:|com/starrocks/consistency/ConsistencyChecker.java|11|13|84.62%|[182, 342]|
|:large_blue_circle:|com/starrocks/catalog/TabletInvertedIndex.java|89|98|90.82%|[373, 375, 390, 413, 434, 513, 514, 553, 813]|
|:large_blue_circle:|com/starrocks/clone/TabletScheduler.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/TabletMeta.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 222 / 305 (72.79%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/Table.java|0|1|00.00%|[313]|
|:large_blue_circle:|com/starrocks/common/proc/PriorityRepairProcNode.java|0|1|00.00%|[44]|
|:large_blue_circle:|com/starrocks/alter/SystemHandler.java|0|12|00.00%|[100, 101, 102, 104, 105, 106, 120, 121, 122, 125, 126, 127]|
|:large_blue_circle:|com/starrocks/clone/TabletSchedCtx.java|0|1|00.00%|[546]|
|:large_blue_circle:|com/starrocks/catalog/TabletMeta.java|1|4|25.00%|[147, 151, 152]|
|:large_blue_circle:|com/starrocks/clone/TabletChecker.java|35|56|62.50%|[166, 167, 300, 359, 384, 399, 401, 436, 463, 467, 475, 487, 500, 512, 519, 520, 529, 530, 531, 533, 534]|
|:large_blue_circle:|com/starrocks/clone/ColocateTableBalancer.java|90|113|79.65%|[295, 300, 314, 332, 334, 335, 336, 337, 338, 340, 341, 343, 351, 374, 375, 408, 410, 413, 416, 417, 437, 438, 439]|
|:large_blue_circle:|com/starrocks/catalog/TabletInvertedIndex.java|79|98|80.61%|[309, 310, 312, 314, 315, 316, 373, 375, 390, 410, 411, 412, 414, 425, 435, 514, 515, 554, 814]|
|:large_blue_circle:|com/starrocks/consistency/ConsistencyChecker.java|11|13|84.62%|[179, 339]|
|:large_blue_circle:|com/starrocks/clone/TabletScheduler.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/common/Config.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|1|1|100.00%|[]|

**Review by gengjun-git — APPROVED** [review]

**Pull request merged**
