### PR TITLE
[SR SQL Planner Summer Camp] Support modify table properties in new parser

### PR DESCRIPTION
**Pull request by xlwh**
## What type of PR is this：
- [ ] bug
- [x] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #7938

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 38 / 63 (60.32%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/ast/AstVisitor.java|0|1|00.00%|
|:large_blue_circle:|com/starrocks/sql/analyzer/AlterTableStatementAnalyzer.java|28|50|56.00%|
|:large_blue_circle:|com/starrocks/analysis/ModifyTablePropertiesClause.java|4|6|66.67%|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|6|6|100.00%|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 41 / 63 (65.08%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/ast/AstVisitor.java|0|1|00.00%|
|:large_blue_circle:|com/starrocks/sql/analyzer/AlterTableStatementAnalyzer.java|31|50|62.00%|
|:large_blue_circle:|com/starrocks/analysis/ModifyTablePropertiesClause.java|4|6|66.67%|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|6|6|100.00%|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 41 / 63 (65.08%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/ast/AstVisitor.java|0|1|00.00%|
|:large_blue_circle:|com/starrocks/sql/analyzer/AlterTableStatementAnalyzer.java|31|50|62.00%|
|:large_blue_circle:|com/starrocks/analysis/ModifyTablePropertiesClause.java|4|6|66.67%|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|6|6|100.00%|

**Comment by xlwh** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 41 / 63 (65.08%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/ast/AstVisitor.java|0|1|00.00%|
|:large_blue_circle:|com/starrocks/sql/analyzer/AlterTableStatementAnalyzer.java|31|50|62.00%|
|:large_blue_circle:|com/starrocks/analysis/ModifyTablePropertiesClause.java|4|6|66.67%|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|6|6|100.00%|

**Review by HangyuanLiu — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 41 / 63 (65.08%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/ast/AstVisitor.java|0|1|00.00%|[437]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AlterTableStatementAnalyzer.java|31|50|62.00%|[91, 96, 100, 102, 103, 106, 107, 109, 112, 115, 121, 129, 130, 136, 137, 145, 146, 153, 155]|
|:large_blue_circle:|com/starrocks/analysis/ModifyTablePropertiesClause.java|4|6|66.67%|[49, 63]|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|6|6|100.00%|[]|

**Comment by xlwh** [comment]
run starrocks_admit_test

**Pull request merged**
