### PR TITLE
[Refactor][Enhancement] DataStreamRecvr::SenderQueue phase 1: introduce a lock-free queue

### PR DESCRIPTION
**Pull request by silverbullet233**
## What type of PR is this：
- [ ] bug
- [ ] feature
- [x] enhancement
- [x] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by silverbullet233** [comment]
run starrocks_admit_test

**Review by murphyatwork — APPROVED** [review]

**Comment by satanson** [comment]
@silverbullet233
1. Have test proven performance improvement of introducing this lock-free queue?
2. Only lock-free queue is adopted? would blocking queue  be used in our code base?
3. this code shoud be put into third_party or directly introduced? @imay @kangkaisen

**Comment by silverbullet233** [comment]
> @silverbullet233
> 
> 1. Have test proven performance improvement of introducing this lock-free queue?
> 2. Only lock-free queue is adopted? would blocking queue  be used in our code base?
> 3. this code shoud be put into third_party or directly introduced? @imay @kangkaisen

@satanson 
1. From the public benchmark information(https://moodycamel.com/blog/2014/a-fast-general-purpose-lock-free-queue-for-c++.htm#benchmarks and https://github.com/Qihoo360/evpp/blob/master/docs/benchmark_lockfree_vs_mutex_cn.md), it has good performance.
2. Now I only use lock-free queue in PipelineSenderQueue, blocking queue is not used yet, but I think it can be used in some scenarios, such as thread pool…
3. This library has only three header files, so I put it directly in the code, just like phmap

**Review by satanson — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by silverbullet233** [comment]
https://github.com/Mergifyio backport branch-2.4

**Pull request merged**
