### PR TITLE
[BugFix] Fix ClassCastException when query from information_schema.load_tracking_logs with job_id

### LINKED ISSUE #20481: Failed to query from information_schema.load_tracking_logs  with job_id predicate
This issue is related to #19264 . When follow the demo in that PR, an error was threw out.

### Steps to reproduce the behavior (Required)

select tracking_log from information_schema.load_tracking_logs where job_id = 14023;

### Expected behavior (Required)
+-----------------------------------------------------------------------------------------------+
| tracking_log                                                                                  |
+-----------------------------------------------------------------------------------------------+
| Error: The row is out of partition ranges. Please add a new partition.. Row: [2022-01-14, 2]
 |
+-----------------------------------------------------------------------------------------------+
### Real behavior (Required)
ERROR 1064 (HY000): java.lang.Long cannot be cast to java.lang.String

And the error stack trace in fe.warn.log likes this:

```sh
2023-03-28 12:52:23,024 WARN (starrocks-mysql-nio-pool-1|167) [StmtExecutor.execute():562] execute Exception, sql select tracking_log from information_schema.load_tracking_logs where job_id=14023
java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.String
        at com.starrocks.sql.optimizer.operator.scalar.ConstantOperator.getVarchar(ConstantOperator.java:294) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visitPhysicalSchemaScan(PlanFragmentBuilder.java:1140) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visitPhysicalSchemaScan(PlanFragmentBuilder.java:343) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.operator.physical.PhysicalSchemaScanOperator.accept(PhysicalSchemaScanOperator.java:46) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visit(PlanFragmentBuilder.java:360) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.translate(PlanFragmentBuilder.java:354) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.plan.PlanFragmentBuilder.createPhysicalPlan(PlanFragmentBuilder.java:202) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.createQueryPlan(StatementPlanner.java:152) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.planQuery(StatementPlanner.java:113) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:91) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:55) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:396) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:358) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:472) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:738) ~[starrocks-fe.jar:?]
        at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:69) ~[starrocks-fe.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_352]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_352]
```

### StarRocks version (Required)

- build from main branch

### PR DESCRIPTION
**Pull request by wxl24life**
## What type of PR is this：
- BugFix

## Which issues of this PR fixes ：

Fixes #20481 

## Problem Summary(Required) ：

That same error occurs when query information_schema.loads and information_schema.load_tracking_logs.

The switch-case statement seems a typo-error, losing "break" statement in last PR.

Have tested it in our test environment.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
-  bugfix for the main branch

### CODE REVIEW

**Comment by imay** [comment]
Thanks for your contribution.Could you sign off and sign the CLA?
You can sign off by ‘git commit -s’

**Comment by imay** [comment]
DCO doesn't pass because you didn't sign-off the commit.
You need to do it by executing the command 'git commit -s'.
Then push it to the repo

**Comment by wxl24life** [comment]
> DCO doesn't pass because you didn't sign-off the commit. You need to do it by executing the command 'git commit -s'. Then push it to the repo

Thanks, I have Signed-off

**Comment by wxl24life** [comment]
@decster @meegoo this pr related to information_schema, may i have your time to review it? thanks

**Review by imay — APPROVED** [review]

**Comment by imay** [comment]
@mergify backport branch-3.0

**Pull request merged**
