### PR TITLE
[BugFix] Append null to nullable numeric column

### LINKED ISSUE #32656: Check failed: !SIMD::contain_nonzero(_null_column->get_data(), 0) in ASAN builds
### Steps to reproduce the behavior (Required)
1. unzip 
[bug.zip](https://github.com/StarRocks/starrocks/files/12885205/bug.zip)
2. edit bug.sh, changing the `<asan-image>` to a valid image built with ASAN
3. run bug.sh

### Expected behavior (Required)
shouldn't crash

### Real behavior (Required)
```
*** Check failure stack trace: ***
test_new_delete_type_mismatch ASAN (build a143fd7)
query_id:00000000-0000-0000-0000-000000000000, fragment_instance:00000000-0000-0000-0000-000000000000
tracker:process consumption: 0
tracker:query_pool consumption: 0
tracker:load consumption: 0
tracker:metadata consumption: 13573
tracker:tablet_metadata consumption: 7086
tracker:rowset_metadata consumption: 1424
tracker:segment_metadata consumption: 1215
tracker:column_metadata consumption: 3848
tracker:tablet_schema consumption: 2446
tracker:segment_zonemap consumption: 904
tracker:short_key_index consumption: 0
tracker:column_zonemap_index consumption: 1568
tracker:ordinal_index consumption: 984
tracker:bitmap_index consumption: 0
tracker:bloom_filter_index consumption: 0
tracker:compaction consumption: 0
tracker:schema_change consumption: 0
tracker:column_pool consumption: 0
tracker:page_cache consumption: 0
tracker:update consumption: 66
tracker:chunk_allocator consumption: 0
tracker:clone consumption: 0
tracker:consistency consumption: 0
*** Aborted at 1697052458 (unix time) try "date -d @1697052458" if you are using GNU date ***
PC: @     0x7fcdf5684a7c pthread_kill
*** SIGABRT (@0x5f5) received by PID 1525 (TID 0x7fcdc7e31640) from PID 1525; stack trace: ***
    @         0x1c5564ea google::(anonymous namespace)::FailureSignalHandler()
    @     0x7fcdf5630520 (unknown)
    @     0x7fcdf5684a7c pthread_kill
    @     0x7fcdf5630476 raise
    @     0x7fcdf56167f3 abort
    @          0xfc11a4c starrocks::failure_function()
    @         0x1c544951 google::LogMessage::Fail()
    @         0x1c546faf google::LogMessage::SendToLog()
    @         0x1c544490 google::LogMessage::Flush()
    @         0x1c54761d google::LogMessageFatal::~LogMessageFatal()
    @         0x103e1bf6 starrocks::NullableColumn::check_or_die()
    @         0x103f0d74 starrocks::ArrayColumn::check_or_die()
    @         0x103e1c74 starrocks::NullableColumn::check_or_die()
    @         0x103eebeb starrocks::AdaptiveNullableColumn::check_or_die()
    @          0xff77835 starrocks::Chunk::check_or_die()
    @          0xff7275a starrocks::Chunk::update_column_by_index()
    @         0x11cd390d starrocks::JsonScanner::_materialize_src_chunk_adaptive_nullable_column()
    @         0x11cceeea starrocks::JsonScanner::get_next()
    @         0x11b364ff starrocks::connector::FileDataSource::get_next()
    @         0x11df3152 starrocks::ConnectorScanner::get_next()
    @         0x11dec19c starrocks::ConnectorScanNode::_scanner_thread()
    @         0x11deaec0 _ZZN9starrocks17ConnectorScanNode15_submit_scannerEPNS_16ConnectorScannerEbENKUlvE_clEv
    @         0x11def51a _ZSt13__invoke_implIvRZN9starrocks17ConnectorScanNode15_submit_scannerEPNS0_16ConnectorScannerEbEUlvE_JEET_St14__invoke_otherOT0_DpOT1_
    @         0x11def3ac _ZSt10__invoke_rIvRZN9starrocks17ConnectorScanNode15_submit_scannerEPNS0_16ConnectorScannerEbEUlvE_JEENSt9enable_ifIX16is_invocable_r_vIT_T0_DpT1_EES7_E4typeEOS8_DpOS9_
    @         0x11def20d _ZNSt17_Function_handlerIFvvEZN9starrocks17ConnectorScanNode15_submit_scannerEPNS1_16ConnectorScannerEbEUlvE_E9_M_invokeERKSt9_Any_data
    @          0xfafe7d8 std::function<>::operator()()
    @         0x18b5aa4e starrocks::PriorityThreadPool::work_thread()
    @         0x18b8cc47 std::__invoke_impl<>()
    @         0x18b8ca7f std::__invoke<>()
    @         0x18b8ca13 _ZNKSt12_Mem_fn_baseIMN9starrocks18PriorityThreadPoolEFviELb1EEclIJRPS1_RiEEEDTcl8__invokedtdefpT6_M_pmfspcl7forwardIT_Efp_EEEDpOS9_
    @         0x18b8c980 std::__invoke_impl<>()
    @         0x18b8c8c3 _ZSt10__invoke_rIvRSt7_Mem_fnIMN9starrocks18PriorityThreadPoolEFviEEJRPS2_RiEENSt9enable_ifIX16is_invocable_r_vIT_T0_DpT1_EESB_E4typeEOSC_DpOSD_
```

### StarRocks version (Required)
 3.1

### PR DESCRIPTION
**Pull request by rickif**
Fixes  https://github.com/StarRocks/starrocks/issues/32656
The  `add_nullable_numeric_column` dose not set `_has_null` of nullable column when a null value is appended.
This PR fixes this issue.

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.2
  - [x] 3.1
  - [x] 3.0
  - [x] 2.5

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:heart_eyes: **pass** : 3 / 3 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/formats/json/nullable_column.cpp|3|3|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by meegoo — APPROVED** [review]

**Review by chaoyli — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.2

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
