### PR TITLE
[Feature]Add parameter to set whether trino dialect is downgraded

### LINKED ISSUE #52702: Add parameter to set whether trino dialect is downgraded
- [x] https://github.com/StarRocks/starrocks/pull/52660

## Feature request

**Is your feature request related to a problem? Please describe.**

set sql_dialect = 'trino';
select json_extract(json, '$.store.book')  --正常
select date_sub(current_date, interval 14 day) --正常
但是
select json_extract(json, '$.store.book') , date_sub(current_date, interval 14 day)  -- 不正常
原因是 json_extract符合trino语法，date_sub(current_date, interval 14 day) 符合SR语法，所以两个单独查询没问题，但是联合查时会有异常，会带来困惑

**Describe the solution you'd like**

新增参数，支持配置是否允许从Trino降级到StarRocks方言
**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by renzhimin7**
## Why I'm doing:
```
set sql_dialect = 'trino';
select json_extract(json, '$.store.book')  --正常
select date_sub(current_date, interval 14 day) --正常
但是
select json_extract(json, '$.store.book') , date_sub(current_date, interval 14 day)  -- 不正常
原因是 json_extract符合trino语法，date_sub(current_date, interval 14 day) 符合SR语法，所以两个单独查询没问题，但是联合查时会有异常，会带来困惑
```

## What I'm doing:
Fixes #52702 

## What type of PR is this:

- [ ] BugFix
- [x] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [x] Yes, this PR will result in a change in behavior.
- [ ] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [x] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
- [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 3.3
  - [ ] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Comment by miomiocat** [comment]
@wangsimo0 Can you help review this requirement

**Review by miomiocat — DISMISSED** [review]

**Comment by wangsimo0** [comment]
Thanks for your contributing!
In the beginning, I'm just thinking about the scalability of this parameter, and it seems fine. So I just recorded some thoughts here:  
In the future, starrocks may support different kinds of SQL dialects. For example spark, hive, impala, and so on. And some users may need to downgrade the SQL in a different order. For example, trino->spark->hive. 
StarRocks' default behavior will always be the sql_dialect -> starrocks dialect. And in the future maybe we can provide a parameter like something like `sql_dialect_downgrade_order?` and it will be still affected by the `ENABLE_DIALECT_DOWNGRADE` parameter, which still makes sense. 
So I think this parameter LGTM

**Comment by wangsimo0** [comment]
pls add related doc, thx in advance

**Review by Seaven — DISMISSED** [review]

**Comment by renzhimin7** [comment]
rebase main

**Review by trueeyu — APPROVED** [review]

**Review by Seaven — APPROVED** [review]

**Comment by wangsimo0** [comment]
ignore backport check: 3.3.7

**Pull request merged**
