### PR TITLE
[Enhancement] Support alter materialized view properties

### LINKED ISSUE #12969: Properties on materialized view tables should support modifiability
## Enhancement
Many times when creating a materialized view, the attribute design may not be correct. At this time, users may need to adjust the parameters to suit their own needs, which requires that some attributes of the materialized view need to be modified.

### PR DESCRIPTION
**Pull request by Astralidea**
## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #12969

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [x] This pr will affect users' behaviors
- [x] This pr needs user documentation (for new or modified features or behaviors)
- [ ] I have added documentation for my new feature or new function

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 7 / 71 (09.86%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/TableProperty.java|0|5|00.00%|[127, 128, 136, 137, 138]|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|0|2|00.00%|[2823, 2824]|
|:large_blue_circle:|com/starrocks/common/util/PropertyAnalyzer.java|0|2|00.00%|[198, 206]|
|:large_blue_circle:|com/starrocks/persist/EditLog.java|0|6|00.00%|[285, 286, 287, 288, 1540, 1541]|
|:large_blue_circle:|com/starrocks/journal/JournalEntity.java|0|3|00.00%|[286, 287, 288]|
|:large_blue_circle:|com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java|0|10|00.00%|[572, 573, 574, 575, 576, 578, 579, 580, 582, 583]|
|:large_blue_circle:|com/starrocks/alter/Alter.java|1|36|02.78%|[258, 260, 261, 262, 263, 274, 275, 276, 277, 278, 279, 281, 282, 284, 285, 286, 287, 288, 289, 290, 291, 413, 414, 415, 417, 418, 420, 421, 422, 423, 424, 426, 427, 430, 432]|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|3|4|75.00%|[1197]|
|:large_blue_circle:|com/starrocks/sql/ast/AlterMaterializedViewStmt.java|3|3|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 7 / 71 (09.86%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/TableProperty.java|0|5|00.00%|[130, 131, 142, 143, 144]|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|0|2|00.00%|[2831, 2832]|
|:large_blue_circle:|com/starrocks/common/util/PropertyAnalyzer.java|0|2|00.00%|[200, 208]|
|:large_blue_circle:|com/starrocks/persist/EditLog.java|0|6|00.00%|[285, 286, 287, 288, 1545, 1546]|
|:large_blue_circle:|com/starrocks/journal/JournalEntity.java|0|3|00.00%|[286, 287, 288]|
|:large_blue_circle:|com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java|0|10|00.00%|[572, 573, 574, 575, 576, 578, 579, 580, 582, 583]|
|:large_blue_circle:|com/starrocks/alter/Alter.java|1|36|02.78%|[258, 260, 261, 262, 263, 274, 275, 276, 277, 278, 279, 281, 282, 284, 285, 286, 287, 288, 289, 290, 291, 413, 414, 415, 417, 418, 420, 421, 422, 423, 424, 426, 427, 430, 432]|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|3|4|75.00%|[1197]|
|:large_blue_circle:|com/starrocks/sql/ast/AlterMaterializedViewStmt.java|3|3|100.00%|[]|

**Review by ABingHuang — APPROVED** [review]
LGTM

**Review by meegoo — APPROVED** [review]

**Comment by Astralidea** [comment]
run starrocks_admit_test

**Review by gengjun-git — APPROVED** [review]

**Pull request merged**
