### PR TITLE
[Refactor] Add nodiscard and check status return

### PR DESCRIPTION
**Pull request by ABingHuang**
## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [x] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Review by kangkaisen — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 4 / 11 (36.36%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/exec/pipeline/nljoin/nljoin_context.cpp|0|1|00.00%|[258]|
|:large_blue_circle:|src/exec/olap_scan_prepare.cpp|0|1|00.00%|[382]|
|:large_blue_circle:|src/exec/pipeline/set/intersect_output_source_operator.h|0|1|00.00%|[45]|
|:large_blue_circle:|src/exec/schema_scan_node.cpp|0|1|00.00%|[281]|
|:large_blue_circle:|src/exec/data_sink.h|0|1|00.00%|[75]|
|:large_blue_circle:|src/exec/file_scan_node.cpp|0|1|00.00%|[177]|
|:large_blue_circle:|src/exec/union_node.cpp|0|1|00.00%|[230]|
|:large_blue_circle:|src/runtime/external_scan_context_mgr.cpp|2|2|100.00%|[]|
|:large_blue_circle:|src/exec/exec_node.cpp|1|1|100.00%|[]|
|:large_blue_circle:|src/exec/pipeline/context_with_dependency.h|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 3 / 11 (27.27%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/exec/pipeline/nljoin/nljoin_context.cpp|0|1|00.00%|[258]|
|:large_blue_circle:|src/exec/olap_scan_prepare.cpp|0|1|00.00%|[382]|
|:large_blue_circle:|src/exec/pipeline/set/intersect_output_source_operator.h|0|1|00.00%|[45]|
|:large_blue_circle:|src/exec/schema_scan_node.cpp|0|1|00.00%|[281]|
|:large_blue_circle:|src/exec/data_sink.h|0|1|00.00%|[75]|
|:large_blue_circle:|src/exec/file_scan_node.cpp|0|1|00.00%|[177]|
|:large_blue_circle:|src/exec/union_node.cpp|0|1|00.00%|[230]|
|:large_blue_circle:|src/exec/olap_scan_node.cpp|0|1|00.00%|[222]|
|:large_blue_circle:|src/runtime/external_scan_context_mgr.cpp|1|1|100.00%|[]|
|:large_blue_circle:|src/exec/exec_node.cpp|1|1|100.00%|[]|
|:large_blue_circle:|src/exec/pipeline/context_with_dependency.h|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 3 / 11 (27.27%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/exec/pipeline/nljoin/nljoin_context.cpp|0|1|00.00%|[258]|
|:large_blue_circle:|src/exec/olap_scan_prepare.cpp|0|1|00.00%|[382]|
|:large_blue_circle:|src/exec/pipeline/set/intersect_output_source_operator.h|0|1|00.00%|[45]|
|:large_blue_circle:|src/exec/schema_scan_node.cpp|0|1|00.00%|[281]|
|:large_blue_circle:|src/exec/data_sink.h|0|1|00.00%|[75]|
|:large_blue_circle:|src/exec/file_scan_node.cpp|0|1|00.00%|[177]|
|:large_blue_circle:|src/exec/union_node.cpp|0|1|00.00%|[230]|
|:large_blue_circle:|src/exec/olap_scan_node.cpp|0|1|00.00%|[222]|
|:large_blue_circle:|src/runtime/external_scan_context_mgr.cpp|1|1|100.00%|[]|
|:large_blue_circle:|src/exec/exec_node.cpp|1|1|100.00%|[]|
|:large_blue_circle:|src/exec/pipeline/context_with_dependency.h|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 3 / 11 (27.27%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/exec/pipeline/nljoin/nljoin_context.cpp|0|1|00.00%|[258]|
|:large_blue_circle:|src/exec/olap_scan_prepare.cpp|0|1|00.00%|[382]|
|:large_blue_circle:|src/exec/pipeline/set/intersect_output_source_operator.h|0|1|00.00%|[45]|
|:large_blue_circle:|src/exec/schema_scan_node.cpp|0|1|00.00%|[281]|
|:large_blue_circle:|src/exec/data_sink.h|0|1|00.00%|[75]|
|:large_blue_circle:|src/exec/file_scan_node.cpp|0|1|00.00%|[177]|
|:large_blue_circle:|src/exec/union_node.cpp|0|1|00.00%|[230]|
|:large_blue_circle:|src/exec/olap_scan_node.cpp|0|1|00.00%|[222]|
|:large_blue_circle:|src/runtime/external_scan_context_mgr.cpp|1|1|100.00%|[]|
|:large_blue_circle:|src/exec/exec_node.cpp|1|1|100.00%|[]|
|:large_blue_circle:|src/exec/pipeline/context_with_dependency.h|1|1|100.00%|[]|

**Review by silverbullet233 — APPROVED** [review]

**Review by Astralidea — APPROVED** [review]

**Pull request merged**
