### PR TITLE
[Bugfix] Retry when fail to start a local bdb cluster in UT

### PR DESCRIPTION
**Pull request by padmejin**
Tried to fix the root cause but failed. Now just bypass it.

## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by padmejin** [comment]
run starrocks_admit_test

**Review by murphyatwork — APPROVED** [review]

**Review by imay — APPROVED** [review]

**Comment by padmejin** [comment]
@Mergifyio backport branch-2.4

**Comment by padmejin** [comment]
@Mergifyio backport branch-2.4 otra vez

**Comment by padmejin** [comment]
@Mergifyio backport branch-2.4
Por favor!

**Pull request merged**
