### PR TITLE
[BugFix] Fix ES concurreny bug.

### PR DESCRIPTION
**Pull request by Smith-Cruise**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 5 / 11 (45.45%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/external/elasticsearch/EsRepository.java|0|6|00.00%|[63, 64, 70, 71, 82, 84]|
|:large_blue_circle:|com/starrocks/external/elasticsearch/MappingPhase.java|5|5|100.00%|[]|

**Review by imay — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 0 / 13 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/external/elasticsearch/EsRepository.java|0|13|00.00%|[65, 66, 67, 75, 76, 77, 83, 84, 85, 86, 89, 93, 95]|

**Review by imay — DISMISSED** [review]

**Comment by Smith-Cruise** [comment]
@DorianZheng @imay PTAL

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 0 / 12 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/external/elasticsearch/EsRepository.java|0|12|00.00%|[65, 66, 67, 74, 75, 81, 82, 83, 84, 87, 91, 93]|

**Review by imay — APPROVED** [review]

**Review by DorianZheng — APPROVED** [review]
LGTM

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by Smith-Cruise** [comment]
@Mergifyio backport branch-2.4 branch-2.3 branch-2.2

**Pull request merged**
