### PR TITLE
Issue/#9851 make mv inactive after base table rename

### LINKED ISSUE #9851: [sync materialized view]refresh failed after rename base table
### Steps to reproduce the behavior (Required)
```
CREATE TABLE `t1` (
                                    `k1` date,
                                    `k2` int,
                                    `k3` int
                                ) ENGINE=OLAP
                                DUPLICATE KEY(`k1`)
                                COMMENT "OLAP"
                                PARTITION BY RANGE (k1) (
                                START ("2020-10-01") END ("2022-03-04") EVERY (INTERVAL 15 day)
                                )
                                DISTRIBUTED BY HASH(`k1`) BUCKETS 3;
CREATE MATERIALIZED VIEW mv1
                             PARTITION BY k1
                             DISTRIBUTED BY HASH(k1) BUCKETS 10
                             REFRESH ASYNC
                             AS SELECT k1, k2
                             FROM t1;
ALTER TABLE t1 RENAME t2;
INSERT INTO t2 VALUES ("2020-10-10",1,1);
```

### Expected behavior (Required)
`refresh ok`
### Real behavior (Required)
```
2022-08-10 20:55:33,535 WARN (pool-21-thread-2|230) [TaskRunExecutor.lambda$executeTaskRun$0():42] failed to execute TaskRun.
java.lang.NullPointerException: null
	at com.starrocks.scheduler.MvTaskRunProcessor.processSyncBasePartition(MvTaskRunProcessor.java:198) ~[starrocks-fe.jar:?]
	at com.starrocks.scheduler.MvTaskRunProcessor.processTaskRun(MvTaskRunProcessor.java:147) ~[starrocks-fe.jar:?]
	at com.starrocks.scheduler.TaskRun.executeTaskRun(TaskRun.java:106) ~[starrocks-fe.jar:?]
	at com.starrocks.scheduler.TaskRunExecutor.lambda$executeTaskRun$0(TaskRunExecutor.java:35) ~[starrocks-fe.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_252]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_252]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
```
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
+----------------------------+
| current_version()          |
+----------------------------+
| BRANCH-2.4-RELEASE 7708b12 |
+----------------------------+

### PR DESCRIPTION
**Pull request by ABingHuang**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #9851 

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Review by Astralidea — DISMISSED** [review]

**Review by kangkaisen — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by ABingHuang** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 7 / 9 (77.78%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|7|9|77.78%|[3462, 3520]|

**Comment by ABingHuang** [comment]
run starrocks_admit_test

**Review by Astralidea — APPROVED** [review]

**Review by gengjun-git — APPROVED** [review]

**Comment by Astralidea** [comment]
@Mergifyio backport branch-2.4

**Pull request merged**
