### PR TITLE
[Enhancement] Add diagnostic info for tablet syncer

### PR DESCRIPTION
**Pull request by nshangyiming**
## What type of PR is this：
- [ ] bug
- [ ] feature
- [x] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

1.  Add diagnostic info for the tablet syncer so we know how to optimize it next time.
2. Log former owner info when calling DB lock; this will give us some ideas about the thread holding DB lock for a long time.
3. Add `-XX:+PrintConcurrentLocks` to JAVA_OPTS by default to help debug deadlock.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by nshangyiming** [comment]
run starrocks_fe_unittest

**Comment by nshangyiming** [comment]
run starrocks_fe_unittest

**Review by gengjun-git — DISMISSED** [review]

**Review by decster — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by nshangyiming** [comment]
run starrocks_fe_unittest

**Comment by chaoyli** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 6 / 27 (22.22%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/ExternalOlapTable.java|0|9|00.00%|[314, 406, 442, 445, 503, 527, 530, 531, 532]|
|:large_blue_circle:|com/starrocks/catalog/Database.java|6|18|33.33%|[120, 121, 123, 124, 125, 126, 134, 135, 136, 143, 157, 162]|

**Review by gengjun-git — APPROVED** [review]

**Review by decster — APPROVED** [review]

**Pull request merged**
