### PR TITLE
[Bugfix] Catch exception in handleFieldList when showing tables with an unselectable Iceberg table

### PR DESCRIPTION
**Pull request by mxdzs0612**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

Currently, FE will do handleFieldList() in every request if `use database` command is executed. However, some kinds of Iceberg table maybe fail to load, see #9936, after which MySQL client will report "ERROR 2006 (HY000): MySQL server has gone away" whatever SQL user sends. User has to restart a MySQL client to do normal queries, which does not meet expectations.

Now that we can't determine what MySQL client sends, I catch all StarRocksIcebergException and print warning in handleFieldList() to make the client work fine with, say, `show tables` command in this case.

Should be merged after #9936.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by mxdzs0612** [comment]
run starrocks_fe_unittest

**Comment by mxdzs0612** [comment]
run starrocks_fe_unittest

**Comment by mxdzs0612** [comment]
run starrocks_fe_unittest

**Comment by mxdzs0612** [comment]
run starrocks_fe_unittest

**Comment by mxdzs0612** [comment]
run starrocks_fe_unittest

**Comment by mxdzs0612** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 0 / 2 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/ConnectProcessor.java|0|2|00.00%|[402, 403]|

**Review by stephen-shelby — APPROVED** [review]
LGTM

**Review by imay — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by mxdzs0612** [comment]
@Mergifyio backport branch-2.4

**Pull request merged**
