### PR TITLE
[Feature] Implement HiveConnectorInternalMgr

### PR DESCRIPTION
**Pull request by stephen-shelby**
## What type of PR is this：
- [ ] BugFix
- [x] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #
https://github.com/StarRocks/starrocks/issues/11349

## Problem Summary(Required) ：

HiveConnectorInternalMgr is used to control life cycle of IHiveMetastore and RemoteFileIO

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by stephen-shelby** [comment]
run starrocks_admit_test

**Comment by stephen-shelby** [comment]
run starrocks_fe_unittest

**Comment by stephen-shelby** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 1 / 45 (02.22%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/connector/hive/HiveConnectorInternalMgr.java|0|43|00.00%|[38, 39, 40, 41, 42, 43, 46, 47, 48, 50, 53, 54, 56, 57, 59, 63, 64, 67, 68, 70, 71, 72, 75, 76, 77, 79, 84, 85, 87, 88, 90, 91, 92, 95, 96, 97, 98, 101, 105, 106, 107, 108, 109]|
|:large_blue_circle:|com/starrocks/external/hive/CachingHiveMetastore.java|0|1|00.00%|[67]|
|:large_blue_circle:|com/starrocks/external/CachingRemoteFileIO.java|1|1|100.00%|[]|

**Review by Astralidea — APPROVED** [review]

**Review by gengjun-git — APPROVED** [review]

**Pull request merged**
