### PR TITLE
[BugFix] Fix bug show table status from missing information

### LINKED ISSUE #24279: the result is missing from show table status
### Steps to reproduce the behavior (Required)
`show table status from <db>` 

### Expected behavior (Required)
expect all information is complete but now most of the output is `NULL`
image

### Real behavior (Required)
All information should be consistent with the table `information_schema.tables` like `UPDATE_TIME` or `CREATE_TIME`

image

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by Astralidea**
Fixes #24279

## What type of PR is this:
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.0
  - [x] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 21 / 22 (95.45%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/ShowExecutor.java|19|20|95.00%|[906]|
|:large_blue_circle:|com/starrocks/common/util/DateUtils.java|2|2|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 21 / 22 (95.45%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/ShowExecutor.java|19|20|95.00%|[906]|
|:large_blue_circle:|com/starrocks/common/util/DateUtils.java|2|2|100.00%|[]|

**Review by gengjun-git — APPROVED** [review]

**Review by miomiocat — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
