### PR TITLE
[Enhancement] support unpack subfield expression push down

### PR DESCRIPTION
**Pull request by Seaven**
Fixes #issue

1. support push down subfiled expression to scan node
2. refactor `SubfieldAccessPathComputer` -> `PushDownSubfieldRule`

before:
1. we compute subfield access path by top-down, and don't rewrite whole logical tree

after:
1. we push down subfield expression by top-down, and rewrite whole logical tree
2. compute subfield access path only match `project-scan`
3. remove prune subfiled on `Map is NULL`, support `Map is NULL` rewrite to `MAP_SIZE(map) is NULL`

example before: 
```
MySQL test> set cbo_prune_subfield=false;
Query OK, 0 rows affected
Time: 0.002s
MySQL test> explain select s1.s1, s1.s4.e from sc3 join td.t0 on sc3.v1 = t0.v1;
+--------------------------------------------+
| Explain String                             |
+--------------------------------------------+
| PLAN FRAGMENT 0                            |
|  OUTPUT EXPRS:10: s1.s1 | 11: s1.s4.e      |
|      .........                             |
|                                            |
|   4:Project                                |
|   |  <slot 10> : 6: s1.s1                  |
|   |  <slot 11> : 6: s1.s4.e                |
|   |                                        |
|   3:HASH JOIN                              |
|   |  join op: INNER JOIN (BUCKET_SHUFFLE)  |
|   |  colocate: false, reason:              |
|   |  equal join conjunct: 1: v1 = 7: v1    |
|   |                                        |
|   |----2:EXCHANGE                          |
|   |                                        |
|   0:OlapScanNode                           |
|      TABLE: sc3                            |
|      .........                             |

|                                            |
| PLAN FRAGMENT 2                            |
|  OUTPUT EXPRS:                             |
|   PARTITION: RANDOM                        |
|                                            |
|   STREAM DATA SINK                         |
|     EXCHANGE ID: 02                        |
|     BUCKET_SHUFFLE_HASH_PARTITIONED: 7: v1 |
|                                            |
|   1:OlapScanNode                           |
|      TABLE: t0                             |
|      .........                             |
+--------------------------------------------+
```

after:
```
MySQL test> set cbo_prune_subfield=true;
Query OK, 0 rows affected
Time: 0.004s
MySQL test> explain select s1.s1, s1.s4.e from sc3 join td.t0 on sc3.v1 = t0.v1;
+--------------------------------------------+
| Explain String                             |
+--------------------------------------------+
| PLAN FRAGMENT 0                            |
|  OUTPUT EXPRS:10: s1.s1 | 11: s1.s4.e      |
|      .........                             |
|                                            |
|   5:Project                                |
|   |  <slot 10> : 12: expr                  |
|   |  <slot 11> : 13: expr                  |
|   |                                        |
|   4:HASH JOIN                              |
|   |  join op: INNER JOIN (BUCKET_SHUFFLE)  |
|   |  colocate: false, reason:              |
|   |  equal join conjunct: 1: v1 = 7: v1    |
|   |                                        |
|   |----3:EXCHANGE                          |
|   |                                        |
|   1:Project                                |
|   |  <slot 1> : 1: v1                      |
|   |  <slot 12> : 6: s1.s1                  |
|   |  <slot 13> : 6: s1.s4.e                |
|   |                                        |
|   0:OlapScanNode                           |
|      TABLE: sc3                            |
|      .........                             |
|                                            |
| PLAN FRAGMENT 2                            |
|  OUTPUT EXPRS:                             |
|   PARTITION: RANDOM                        |
|                                            |
|   STREAM DATA SINK                         |
|     EXCHANGE ID: 03                        |
|     BUCKET_SHUFFLE_HASH_PARTITIONED: 7: v1 |
|                                            |
|   2:OlapScanNode                           |
|      TABLE: t0                             |
|      .........                             |
+--------------------------------------------+
61 rows in set
Time: 0.019s
MySQL test>
```

## What type of PR is this:
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 283 / 343 (82.51%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/logical/LogicalWindowOperator.java|0|1|00.00%|[147]|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/scalar/MultiInPredicateOperator.java|0|4|00.00%|[42, 43, 44, 45]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rewrite/BaseScalarOperatorShuttle.java|4|27|14.81%|[81, 82, 229, 230, 231, 232, 234, 240, 241, 242, 243, 245, 251, 252, 253, 254, 256, 265, 273, 274, 275, 276, 278]|
|:large_blue_circle:|com/starrocks/sql/optimizer/transformer/SqlToScalarOperatorTranslator.java|2|3|66.67%|[543]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/tree/prunesubfield/PushDownSubfieldRule.java|220|251|87.65%|[103, 105, 107, 108, 110, 113, 114, 115, 119, 120, 121, 235, 236, 237, 243, 244, 245, 246, 363, 370, 376, 377, 378, 379, 416, 447, 448, 465, 489, 497, 505]|
|:large_blue_circle:|com/starrocks/sql/optimizer/Optimizer.java|7|7|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/scalar/MapOperator.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/OperatorBuilderFactory.java|6|6|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/scalar/LambdaFunctionOperator.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/pattern/Pattern.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/RuleType.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/tree/prunesubfield/PruneSubfieldRule.java|32|32|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rewrite/ReplaceColumnRefRewriter.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/PruneProjectColumnsRule.java|3|3|100.00%|[]|

**Review by fzhedu — COMMENTED** [review]
1. 
```
Map is NULL rewrite to MAP_SIZE(map) is NULL
```
how about ARRAY and Struct?
2.
add some tests for lambda functions?

3. json also needs to prune subfields?
4.  can array[1,3][1]>1 be pushed down to storeage?

**Comment by Seaven** [comment]
> ```
> Map is NULL rewrite to MAP_SIZE(map) is NULL
> ```
> 
> how about ARRAY and Struct? 2. add some tests for lambda functions?
> 
> 3. json also needs to prune subfields?
> 4. can array[1,3][1]>1 be pushed down to storeage?

1. ARRAY -> ARRAY_LENGTH(array), can't rewrite struct, it's a correctness question
2. doesn't support lambda function now, and I think this has nonthing to do with lambda if you're talk about lambda's children
3. BE doesn't support now, depend on flat-json
4. yeah, but it's support by previous PR, this PR just push down subfield expressions, predicate push down is supported by `PredicatePushDownRule` , not here.

this PR for: the unread-column don't need append default value on storage, and will implement it in next PR

**Review by kangkaisen — APPROVED** [review]

**Review by fzhedu — APPROVED** [review]
LGTM

**Review by liuyehcf — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 41 / 42 (97.62%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/transformer/SqlToScalarOperatorTranslator.java|2|3|66.67%|[543]|
|:large_blue_circle:|com/starrocks/sql/optimizer/Optimizer.java|7|7|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/scalar/SubfieldOperator.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/OperatorBuilderFactory.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/scalar/LambdaFunctionOperator.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rewrite/BaseScalarOperatorShuttle.java|8|8|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/logical/LogicalWindowOperator.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/pattern/Pattern.java|5|5|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/scalar/MultiInPredicateOperator.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/RuleType.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/tree/prunesubfield/PruneSubfieldRule.java|6|6|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rewrite/ReplaceColumnRefRewriter.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/PruneProjectColumnsRule.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Comment by wannte** [comment]
Hi, @Seaven He 

I’m working on using Starrocks, but my query has exception, but I cannot handle the issue.

The errors are comes from this pr, Could you help me to handle following query?

```
// query
WITH A AS (
  SELECT
    'a' as event_key,
    'x' as property_key
),
B AS (
  SELECT
    'a' as event_key,
    map { 'x' :1 } as props
)
SELECT
  *
FROM
  A
  JOIN B ON A.event_key = B.event_key
WHERE
  props [property_key] = 1
```

error logs are following.

```
java.lang.IllegalStateException: null
	at com.google.common.base.Preconditions.checkState(Preconditions.java:496) ~[spark-dpp-1.0.0.jar:?]
	at com.starrocks.sql.optimizer.OptExpression.getOutputColumns(OptExpression.java:135) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.rule.tree.prunesubfield.PushDownSubfieldRule$PushDowner.generatePushDownProject(PushDownSubfieldRule.java:157) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.rule.tree.prunesubfield.PushDownSubfieldRule$PushDowner.visitLogicalJoin(PushDownSubfieldRule.java:292) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.rule.tree.prunesubfield.PushDownSubfieldRule$PushDowner.visitLogicalJoin(PushDownSubfieldRule.java:86) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.operator.logical.LogicalJoinOperator.accept(LogicalJoinOperator.java:205) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.rule.tree.prunesubfield.PushDownSubfieldRule$PushDowner.visitChildren(PushDownSubfieldRule.java:132) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.rule.tree.prunesubfield.PushDownSubfieldRule$PushDowner.visitLogicalProject(PushDownSubfieldRule.java:226) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.rule.tree.prunesubfield.PushDownSubfieldRule$PushDowner.visitLogicalProject(PushDownSubfieldRule.java:86) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.operator.logical.LogicalProjectOperator.accept(LogicalProjectOperator.java:103) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.rule.tree.prunesubfield.PushDownSubfieldRule$PushDowner.visitChildren(PushDownSubfieldRule.java:132) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.rule.tree.prunesubfield.PushDownSubfieldRule$PushDowner.visit(PushDownSubfieldRule.java:146) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.rule.tree.prunesubfield.PushDownSubfieldRule$PushDowner.visit(PushDownSubfieldRule.java:86) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.OptExpressionVisitor.visitLogicalTreeAnchor(OptExpressionVisitor.java:99) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.operator.logical.LogicalTreeAnchorOperator.accept(LogicalTreeAnchorOperator.java:52) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.rule.tree.prunesubfield.PushDownSubfieldRule.rewrite(PushDownSubfieldRule.java:59) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.Optimizer.pruneSubfield(Optimizer.java:619) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.Optimizer.logicalRuleRewrite(Optimizer.java:385) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.Optimizer.rewriteAndValidatePlan(Optimizer.java:572) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.Optimizer.optimizeByCost(Optimizer.java:195) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.Optimizer.optimize(Optimizer.java:142) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.StatementPlanner.createQueryPlanWithReTry(StatementPlanner.java:249) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:128) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:87) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:486) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:394) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:588) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:872) ~[starrocks-fe.jar:?]
	at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:69) ~[starrocks-fe.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
```

**Pull request merged**
