### PR TITLE
[Refactor] Multi State Manager support serialized and deserialized with JSON format 

### PR DESCRIPTION
**Pull request by HangyuanLiu**
Fixes #issue

## What type of PR is this:
- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [x] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 31 / 170 (18.24%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/load/routineload/RoutineLoadJob.java|0|1|00.00%|[817]|
|:large_blue_circle:|com/starrocks/service/FrontendServiceImpl.java|0|5|00.00%|[1089, 1194, 1355, 1456, 1928]|
|:large_blue_circle:|com/starrocks/http/rest/TransactionLoadAction.java|0|6|00.00%|[235, 244, 259, 265, 273, 281]|
|:large_blue_circle:|com/starrocks/common/proc/CompactionsProcNode.java|0|1|00.00%|[39]|
|:large_blue_circle:|com/starrocks/server/CatalogMgr.java|0|20|00.00%|[394, 395, 396, 398, 399, 401, 402, 403, 404, 406, 407, 410, 412, 413, 414, 415, 417, 418, 420, 422]|
|:large_blue_circle:|com/starrocks/load/routineload/KafkaTaskInfo.java|0|1|00.00%|[200]|
|:large_blue_circle:|com/starrocks/transaction/LakeTableTxnLogApplier.java|0|1|00.00%|[52]|
|:large_blue_circle:|com/starrocks/common/proc/PartitionsProcDir.java|0|1|00.00%|[392]|
|:large_blue_circle:|com/starrocks/common/proc/StreamLoadsProcDir.java|0|1|00.00%|[63]|
|:large_blue_circle:|com/starrocks/catalog/GlobalFunctionMgr.java|0|16|00.00%|[180, 182, 183, 184, 185, 186, 187, 189, 190, 193, 195, 196, 197, 198, 201, 203]|
|:large_blue_circle:|com/starrocks/persist/EditLog.java|0|5|00.00%|[662, 905, 910, 981, 986]|
|:large_blue_circle:|com/starrocks/common/proc/StreamLoadsLabelProcDir.java|0|1|00.00%|[43]|
|:large_blue_circle:|com/starrocks/load/streamload/StreamLoadMgr.java|2|23|08.70%|[527, 544, 545, 546, 547, 548, 549, 551, 552, 555, 556, 558, 559, 560, 561, 563, 564, 565, 568, 571, 573]|
|:large_blue_circle:|com/starrocks/scheduler/mv/MaterializedViewMgr.java|3|20|15.00%|[298, 299, 300, 301, 302, 303, 305, 306, 309, 311, 312, 313, 315, 316, 317, 320, 322]|
|:large_blue_circle:|com/starrocks/load/InsertOverwriteJobMgr.java|3|14|21.43%|[257, 258, 259, 260, 263, 265, 266, 267, 268, 270, 272]|
|:large_blue_circle:|com/starrocks/lake/compaction/CompactionMgr.java|3|13|23.08%|[178, 188, 189, 190, 191, 194, 196, 197, 199, 201]|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|8|26|30.77%|[608, 1428, 1429, 1430, 1431, 1432, 1433, 1507, 1727, 1735, 1756, 1757, 1762, 1763, 1879, 1881, 1883, 2159]|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|2|5|40.00%|[2763, 3046, 3134]|
|:large_blue_circle:|com/starrocks/sql/plan/PlanFragmentBuilder.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/scheduler/mv/MVJobExecutor.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/qe/StmtExecutor.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/alter/AlterJobMgr.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/load/streamload/StreamLoadTask.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/alter/SchemaChangeHandler.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/alter/MaterializedViewHandler.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/qe/ShowExecutor.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 31 / 170 (18.24%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/load/routineload/RoutineLoadJob.java|0|1|00.00%|[817]|
|:large_blue_circle:|com/starrocks/service/FrontendServiceImpl.java|0|5|00.00%|[1089, 1194, 1355, 1456, 1928]|
|:large_blue_circle:|com/starrocks/http/rest/TransactionLoadAction.java|0|6|00.00%|[235, 244, 259, 265, 273, 281]|
|:large_blue_circle:|com/starrocks/common/proc/CompactionsProcNode.java|0|1|00.00%|[39]|
|:large_blue_circle:|com/starrocks/server/CatalogMgr.java|0|20|00.00%|[394, 395, 396, 398, 399, 401, 402, 403, 404, 406, 407, 410, 412, 413, 414, 415, 417, 418, 420, 422]|
|:large_blue_circle:|com/starrocks/load/routineload/KafkaTaskInfo.java|0|1|00.00%|[200]|
|:large_blue_circle:|com/starrocks/transaction/LakeTableTxnLogApplier.java|0|1|00.00%|[52]|
|:large_blue_circle:|com/starrocks/common/proc/PartitionsProcDir.java|0|1|00.00%|[392]|
|:large_blue_circle:|com/starrocks/common/proc/StreamLoadsProcDir.java|0|1|00.00%|[63]|
|:large_blue_circle:|com/starrocks/catalog/GlobalFunctionMgr.java|0|16|00.00%|[180, 182, 183, 184, 185, 186, 187, 189, 190, 193, 195, 196, 197, 198, 201, 203]|
|:large_blue_circle:|com/starrocks/persist/EditLog.java|0|5|00.00%|[662, 905, 910, 981, 986]|
|:large_blue_circle:|com/starrocks/common/proc/StreamLoadsLabelProcDir.java|0|1|00.00%|[43]|
|:large_blue_circle:|com/starrocks/load/streamload/StreamLoadMgr.java|2|23|08.70%|[527, 544, 545, 546, 547, 548, 549, 551, 552, 555, 556, 558, 559, 560, 561, 563, 564, 565, 568, 571, 573]|
|:large_blue_circle:|com/starrocks/scheduler/mv/MaterializedViewMgr.java|3|20|15.00%|[298, 299, 300, 301, 302, 303, 305, 306, 309, 311, 312, 313, 315, 316, 317, 320, 322]|
|:large_blue_circle:|com/starrocks/load/InsertOverwriteJobMgr.java|3|14|21.43%|[257, 258, 259, 260, 263, 265, 266, 267, 268, 270, 272]|
|:large_blue_circle:|com/starrocks/lake/compaction/CompactionMgr.java|3|13|23.08%|[178, 188, 189, 190, 191, 194, 196, 197, 199, 201]|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|8|26|30.77%|[608, 1428, 1429, 1430, 1431, 1432, 1433, 1507, 1727, 1735, 1756, 1757, 1762, 1763, 1879, 1881, 1883, 2159]|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|2|5|40.00%|[2763, 3046, 3134]|
|:large_blue_circle:|com/starrocks/sql/plan/PlanFragmentBuilder.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/scheduler/mv/MVJobExecutor.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/qe/StmtExecutor.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/alter/AlterJobMgr.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/load/streamload/StreamLoadTask.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/alter/SchemaChangeHandler.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/alter/MaterializedViewHandler.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/qe/ShowExecutor.java|1|1|100.00%|[]|

**Review by nshangyiming — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 31 / 170 (18.24%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/load/routineload/RoutineLoadJob.java|0|1|00.00%|[817]|
|:large_blue_circle:|com/starrocks/service/FrontendServiceImpl.java|0|5|00.00%|[1089, 1194, 1355, 1456, 1928]|
|:large_blue_circle:|com/starrocks/http/rest/TransactionLoadAction.java|0|6|00.00%|[235, 244, 259, 265, 273, 281]|
|:large_blue_circle:|com/starrocks/common/proc/CompactionsProcNode.java|0|1|00.00%|[39]|
|:large_blue_circle:|com/starrocks/server/CatalogMgr.java|0|20|00.00%|[394, 395, 396, 398, 399, 401, 402, 403, 404, 406, 407, 410, 412, 413, 414, 415, 417, 418, 420, 422]|
|:large_blue_circle:|com/starrocks/load/routineload/KafkaTaskInfo.java|0|1|00.00%|[200]|
|:large_blue_circle:|com/starrocks/transaction/LakeTableTxnLogApplier.java|0|1|00.00%|[52]|
|:large_blue_circle:|com/starrocks/common/proc/PartitionsProcDir.java|0|1|00.00%|[392]|
|:large_blue_circle:|com/starrocks/common/proc/StreamLoadsProcDir.java|0|1|00.00%|[63]|
|:large_blue_circle:|com/starrocks/catalog/GlobalFunctionMgr.java|0|16|00.00%|[180, 182, 183, 184, 185, 186, 187, 189, 190, 193, 195, 196, 197, 198, 201, 203]|
|:large_blue_circle:|com/starrocks/persist/EditLog.java|0|5|00.00%|[662, 907, 912, 983, 988]|
|:large_blue_circle:|com/starrocks/common/proc/StreamLoadsLabelProcDir.java|0|1|00.00%|[43]|
|:large_blue_circle:|com/starrocks/load/streamload/StreamLoadMgr.java|2|23|08.70%|[527, 544, 545, 546, 547, 548, 549, 551, 552, 555, 556, 558, 559, 560, 561, 563, 564, 565, 568, 571, 573]|
|:large_blue_circle:|com/starrocks/scheduler/mv/MaterializedViewMgr.java|3|20|15.00%|[298, 299, 300, 301, 302, 303, 305, 306, 309, 311, 312, 313, 315, 316, 317, 320, 322]|
|:large_blue_circle:|com/starrocks/load/InsertOverwriteJobMgr.java|3|14|21.43%|[257, 258, 259, 260, 263, 265, 266, 267, 268, 270, 272]|
|:large_blue_circle:|com/starrocks/lake/compaction/CompactionMgr.java|3|13|23.08%|[178, 188, 189, 190, 191, 194, 196, 197, 199, 201]|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|8|26|30.77%|[608, 1429, 1430, 1431, 1432, 1433, 1434, 1507, 1727, 1735, 1756, 1757, 1762, 1763, 1879, 1881, 1883, 2159]|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|2|5|40.00%|[2763, 3046, 3134]|
|:large_blue_circle:|com/starrocks/sql/plan/PlanFragmentBuilder.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/scheduler/mv/MVJobExecutor.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/qe/StmtExecutor.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/alter/AlterJobMgr.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/load/streamload/StreamLoadTask.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/alter/SchemaChangeHandler.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/alter/MaterializedViewHandler.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/qe/ShowExecutor.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 31 / 170 (18.24%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/load/routineload/RoutineLoadJob.java|0|1|00.00%|[817]|
|:large_blue_circle:|com/starrocks/service/FrontendServiceImpl.java|0|5|00.00%|[1089, 1194, 1355, 1456, 1928]|
|:large_blue_circle:|com/starrocks/http/rest/TransactionLoadAction.java|0|6|00.00%|[235, 244, 259, 265, 273, 281]|
|:large_blue_circle:|com/starrocks/common/proc/CompactionsProcNode.java|0|1|00.00%|[39]|
|:large_blue_circle:|com/starrocks/server/CatalogMgr.java|0|20|00.00%|[394, 395, 396, 398, 399, 401, 402, 403, 404, 406, 407, 410, 412, 413, 414, 415, 417, 418, 420, 422]|
|:large_blue_circle:|com/starrocks/load/routineload/KafkaTaskInfo.java|0|1|00.00%|[200]|
|:large_blue_circle:|com/starrocks/transaction/LakeTableTxnLogApplier.java|0|1|00.00%|[52]|
|:large_blue_circle:|com/starrocks/common/proc/PartitionsProcDir.java|0|1|00.00%|[392]|
|:large_blue_circle:|com/starrocks/common/proc/StreamLoadsProcDir.java|0|1|00.00%|[63]|
|:large_blue_circle:|com/starrocks/catalog/GlobalFunctionMgr.java|0|16|00.00%|[180, 182, 183, 184, 185, 186, 187, 189, 190, 193, 195, 196, 197, 198, 201, 203]|
|:large_blue_circle:|com/starrocks/persist/EditLog.java|0|5|00.00%|[662, 907, 912, 983, 988]|
|:large_blue_circle:|com/starrocks/common/proc/StreamLoadsLabelProcDir.java|0|1|00.00%|[43]|
|:large_blue_circle:|com/starrocks/load/streamload/StreamLoadMgr.java|2|23|08.70%|[527, 544, 545, 546, 547, 548, 549, 551, 552, 555, 556, 558, 559, 560, 561, 563, 564, 565, 568, 571, 573]|
|:large_blue_circle:|com/starrocks/scheduler/mv/MaterializedViewMgr.java|3|20|15.00%|[298, 299, 300, 301, 302, 303, 305, 306, 309, 311, 312, 313, 315, 316, 317, 320, 322]|
|:large_blue_circle:|com/starrocks/load/InsertOverwriteJobMgr.java|3|14|21.43%|[257, 258, 259, 260, 263, 265, 266, 267, 268, 270, 272]|
|:large_blue_circle:|com/starrocks/lake/compaction/CompactionMgr.java|3|13|23.08%|[178, 188, 189, 190, 191, 194, 196, 197, 199, 201]|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|8|26|30.77%|[608, 1429, 1430, 1431, 1432, 1433, 1434, 1507, 1727, 1735, 1756, 1757, 1762, 1763, 1879, 1881, 1883, 2159]|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|2|5|40.00%|[2763, 3046, 3134]|
|:large_blue_circle:|com/starrocks/sql/plan/PlanFragmentBuilder.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/scheduler/mv/MVJobExecutor.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/qe/StmtExecutor.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/alter/AlterJobMgr.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/load/streamload/StreamLoadTask.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/alter/SchemaChangeHandler.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/alter/MaterializedViewHandler.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/qe/ShowExecutor.java|1|1|100.00%|[]|

**Review by gengjun-git — APPROVED** [review]

**Review by Astralidea — APPROVED** [review]

**Pull request merged**
