### PR TITLE
[BugFix] fix incorrect memory metrics of jemalloc

### LINKED ISSUE #12349: starrocks_be_jemalloc_allocated_bytes is not  exact
### Steps to reproduce the behavior (Required)

1. first.
 curl -XGET -s http://172.26.194.122:8138/metrics | grep "^starrocks_be_.*_mem_bytes\|^starrocks_be_tcmalloc_bytes_in_use" | sort -n -k 2
starrocks_be_bitmap_index_mem_bytes 0
starrocks_be_bloom_filter_index_mem_bytes 0
starrocks_be_clone_mem_bytes 0
starrocks_be_compaction_mem_bytes 0
starrocks_be_consistency_mem_bytes 0
starrocks_be_load_mem_bytes 0
starrocks_be_query_mem_bytes 0
starrocks_be_schema_change_mem_bytes 0
starrocks_be_update_mem_bytes 0
starrocks_be_segment_zonemap_mem_bytes 28574
starrocks_be_short_key_index_mem_bytes 74988
starrocks_be_ordinal_index_mem_bytes 92808
starrocks_be_segment_metadata_mem_bytes 115658
starrocks_be_column_zonemap_index_mem_bytes 165148
starrocks_be_column_metadata_mem_bytes 301300
starrocks_be_tablet_schema_mem_bytes 492496
starrocks_be_rowset_metadata_mem_bytes 970534
starrocks_be_tablet_metadata_mem_bytes 1391056
starrocks_be_metadata_mem_bytes 2778548
starrocks_be_chunk_allocator_mem_bytes 12701688
starrocks_be_column_pool_mem_bytes 2393137416
starrocks_be_storage_page_cache_mem_bytes 16579690400
starrocks_be_process_mem_bytes 19341446672

2. second
curl -XGET -s http://172.26.194.122:8138/metrics | grep "jemalloc"
\# TYPE starrocks_be_jemalloc_active_bytes gauge
starrocks_be_jemalloc_active_bytes 164335616
\# TYPE starrocks_be_jemalloc_allocated_bytes gauge
**starrocks_be_jemalloc_allocated_bytes** 155397952
\# TYPE starrocks_be_jemalloc_metadata_bytes gauge
starrocks_be_jemalloc_metadata_bytes 34126016
\# TYPE starrocks_be_jemalloc_metadata_thp gauge
starrocks_be_jemalloc_metadata_thp 0
\# TYPE starrocks_be_jemalloc_resident_bytes gauge
starrocks_be_jemalloc_resident_bytes 218787840
\# TYPE starrocks_be_jemalloc_retained_bytes gauge
starrocks_be_jemalloc_retained_bytes 292823040

### Real behavior (Required)
starrocks_be_jemalloc_allocated_bytes is not right

### StarRocks version (Required)
2.4.0-1017 RELEASE (build ee26555)
Built on 2022-10-17 10:15:43 by StarRocks@docker

### PR DESCRIPTION
**Pull request by silverbullet233**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #12349

## Problem Summary(Required) ：

1. fix a stupid bug that would cause the value of jemalloc_retained_bytes incorrect.
2. update the statistics cached by mallctl before get them, otherwise we won't get the latest results

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
starrocks_be_unittest succeeded.

**Comment by silverbullet233** [comment]
run starrocks_admit_test

**Comment by silverbullet233** [comment]
run starrocks_admit_test

**Review by satanson — APPROVED** [review]

**Review by stdpain — APPROVED** [review]

**Comment by silverbullet233** [comment]
@mergify backport branch-2.4

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
starrocks_be_unittest succeeded.

**Review by kangkaisen — APPROVED** [review]

**Comment by silverbullet233** [comment]
run starrocks_admit_test

**Pull request merged**
