### PR TITLE
[Feature] Support bitwise shift functions

### LINKED ISSUE #13221: [function] need to support bitwise shift function
## Feature request
1. bit_shiftleft: Arithmetic shift left
```
SELECT bit_shiftleft(2, 1);
 4
```

2. bit_shfitright: Arithmetic  shift right
```
SELECT bit_shfitright(4, 1);
 2
```

3. bit_shiftright_logic: logic shift right
```
SELECT bit_shiftright_logic(4, 1);
 2
```

### PR DESCRIPTION
**Pull request by sparklezzz**
## What type of PR is this：
- [ ] BugFix
- [x] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ： 

Fixes #13221

## Problem Summary(Required) ：

NEW FUNCTIONS:
1. `BIT_SHIFT_LEFT(value, shift)`: perform bitwise left shift.
2. `BIT_SHIFT_RIGHT(value, shift)`: perform bitwise right shift arithmetic.
3. `BIT_SHIFT_RIGHT_LOGICAL(value, shift)`: perform bitwise right shift logical.

In above three functions, the type of first operator is within TINYINT, SMALLINT, INT, BIGINT, LARGEINT, and the type of second operator is BIGINT.

Test sql:

```sql
CREATE TABLE IF NOT EXISTS `shift_test` (
  `c1` TINYINT,
  `c2` SMALLINT,
  `c3` INT,
  `c4` BIGINT,
  `c5` LARGEINT
)
ENGINE = OLAP
DUPLICATE KEY(`c1`)
DISTRIBUTED BY HASH(`c1`) BUCKETS 1
PROPERTIES (
  "replication_num" = "1" 
)
;

INSERT INTO `shift_test` VALUES (11, 2222, 33333333, 444444444, 5555555555555);
INSERT INTO `shift_test` VALUES (-11, -2222, -33333333, -444444444, -5555555555555);

SELECT BIT_SHIFT_LEFT(11, 3),  BIT_SHIFT_LEFT(2222, 3),  BIT_SHIFT_LEFT(33333333, 3),  BIT_SHIFT_LEFT(444444444, 3),  BIT_SHIFT_LEFT(5555555555555, 3);
SELECT BIT_SHIFT_LEFT(-11, 3),  BIT_SHIFT_LEFT(-2222, 3),  BIT_SHIFT_LEFT(-33333333, 3),  BIT_SHIFT_LEFT(-444444444, 3),  BIT_SHIFT_LEFT(-5555555555555, 3);

SELECT BIT_SHIFT_RIGHT(11, 3),  BIT_SHIFT_RIGHT(2222, 3),  BIT_SHIFT_RIGHT(33333333, 3),  BIT_SHIFT_RIGHT(444444444, 3),  BIT_SHIFT_RIGHT(5555555555555, 3);
SELECT BIT_SHIFT_RIGHT(-11, 3),  BIT_SHIFT_RIGHT(-2222, 3),  BIT_SHIFT_RIGHT(-33333333, 3),  BIT_SHIFT_RIGHT(-444444444, 3),  BIT_SHIFT_RIGHT(-5555555555555, 3);

SELECT BIT_SHIFT_RIGHT_LOGICAL(11, 3),  BIT_SHIFT_RIGHT_LOGICAL(2222, 3),  BIT_SHIFT_RIGHT_LOGICAL(33333333, 3),  BIT_SHIFT_RIGHT_LOGICAL(444444444, 3),  BIT_SHIFT_RIGHT_LOGICAL(5555555555555, 3);
SELECT BIT_SHIFT_RIGHT_LOGICAL(-11, 3),  BIT_SHIFT_RIGHT_LOGICAL(-2222, 3),  BIT_SHIFT_RIGHT_LOGICAL(-33333333, 3),  BIT_SHIFT_RIGHT_LOGICAL(-444444444, 3),  BIT_SHIFT_RIGHT_LOGICAL(-5555555555555, 3);


SELECT `c1`, BIT_SHIFT_LEFT(`c1`, 3) FROM `shift_test`;
SELECT `c1`, BIT_SHIFT_RIGHT(`c1`, 3) FROM `shift_test`;
SELECT `c1`, BIT_SHIFT_RIGHT_LOGICAL(`c1`, 3) FROM `shift_test`;

SELECT `c2`, BIT_SHIFT_LEFT(`c2`, 3) FROM `shift_test`;
SELECT `c2`, BIT_SHIFT_RIGHT(`c2`, 3) FROM `shift_test`;
SELECT `c2`, BIT_SHIFT_RIGHT_LOGICAL(`c2`, 3) FROM `shift_test`;

SELECT `c3`, BIT_SHIFT_LEFT(`c3`, 3) FROM `shift_test`;
SELECT `c3`, BIT_SHIFT_RIGHT(`c3`, 3) FROM `shift_test`;
SELECT `c3`, BIT_SHIFT_RIGHT_LOGICAL(`c3`, 3) FROM `shift_test`;

SELECT `c4`, BIT_SHIFT_LEFT(`c4`, 3) FROM `shift_test`;
SELECT `c4`, BIT_SHIFT_RIGHT(`c4`, 3) FROM `shift_test`;
SELECT `c4`, BIT_SHIFT_RIGHT_LOGICAL(`c4`, 3) FROM `shift_test`;

SELECT `c5`, BIT_SHIFT_LEFT(`c5`, 3) FROM `shift_test`;
SELECT `c5`, BIT_SHIFT_RIGHT(`c5`, 3) FROM `shift_test`;
SELECT `c5`, BIT_SHIFT_RIGHT_LOGICAL(`c5`, 3) FROM `shift_test`;

SELECT BIT_SHIFT_LEFT(`c1`, `c1`), BIT_SHIFT_LEFT(`c2`, `c1`), BIT_SHIFT_LEFT(`c3`, `c1`), BIT_SHIFT_LEFT(`c4`, `c1`), BIT_SHIFT_LEFT(`c5`, `c1`) FROM `shift_test`;

SELECT BIT_SHIFT_RIGHT(`c1`, `c1`), BIT_SHIFT_RIGHT(`c2`, `c1`), BIT_SHIFT_RIGHT(`c3`, `c1`), BIT_SHIFT_RIGHT(`c4`, `c1`), BIT_SHIFT_RIGHT(`c5`, `c1`) FROM `shift_test`;

SELECT BIT_SHIFT_RIGHT_LOGICAL(`c1`, `c1`), BIT_SHIFT_RIGHT_LOGICAL(`c2`, `c1`), BIT_SHIFT_RIGHT_LOGICAL(`c3`, `c1`), BIT_SHIFT_RIGHT_LOGICAL(`c4`, `c1`), BIT_SHIFT_RIGHT_LOGICAL(`c5`, `c1`) FROM `shift_test`;
```

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Comment by mofeiatwork** [comment]
Please rebase the code with branch main, recently we have applied some refactor over the `PrimitiveType`.

**Review by stdpain — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 46 / 78 (58.97%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/plan/ScalarOperatorToExpr.java|0|12|00.00%|[429, 431, 432, 433, 435, 437, 438, 439, 441, 443, 444, 445]|
|:large_blue_circle:|com/starrocks/sql/analyzer/ExpressionAnalyzer.java|0|2|00.00%|[500, 501]|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|2|5|40.00%|[4348, 4349, 4350]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rewrite/ScalarOperatorFunctions.java|28|43|65.12%|[776, 779, 784, 785, 789, 790, 792, 793, 795, 796, 798, 799, 800, 801, 802]|
|:large_blue_circle:|com/starrocks/analysis/ArithmeticExpr.java|16|16|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 64 / 67 (95.52%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|2|5|40.00%|[4348, 4349, 4350]|
|:large_blue_circle:|com/starrocks/analysis/ArithmeticExpr.java|16|16|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/plan/ScalarOperatorToExpr.java|12|12|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rewrite/ScalarOperatorFunctions.java|32|32|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/ExpressionAnalyzer.java|2|2|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 65 / 65 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/ArithmeticExpr.java|16|16|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/plan/ScalarOperatorToExpr.java|12|12|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rewrite/ScalarOperatorFunctions.java|32|32|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/ExpressionAnalyzer.java|2|2|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 65 / 65 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/ArithmeticExpr.java|16|16|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/plan/ScalarOperatorToExpr.java|12|12|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rewrite/ScalarOperatorFunctions.java|32|32|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/ExpressionAnalyzer.java|2|2|100.00%|[]|

**Comment by mofeiatwork** [comment]
run starrocks_admit_test

**Review by murphyatwork — APPROVED** [review]

**Review by imay — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by kateshaowanjou** [comment]
Congratulations on your first merged PR to StarRocks! 🎉 @sparklezzz

**Pull request merged**
