### PR TITLE
[Cherry-pick][Feature] support show create external catalog and support mask cloud credential in show create catalog and show create file table

### PR DESCRIPTION
**Pull request by leoyy0316**
…ud credential in show create catalog and show create file table

## What type of PR is this：
- [ ] BugFix
- [x] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #  cherry-pick from #16509 and #19126

## Problem Summary(Required) ：

support show create external catalog and support mask cloud credential in show create catalog and show create file table
## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Comment by leoyy0316** [comment]
run starrocks_fe_unittest

**Comment by leoyy0316** [comment]
run starrocks_fe_unittest

**Comment by leoyy0316** [comment]
run starrocks_fe_unittest

**Comment by leoyy0316** [comment]
run starrocks_fe_unittest

**Review by stephen-shelby — APPROVED** [review]

**Pull request merged**
