### PR TITLE
Fix Fe UT

### PR DESCRIPTION
**Pull request by Youngwb**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] others

## Which issues of this PR fixes ：

Fixes #

### CODE REVIEW

**Review by stdpain — APPROVED** [review]

**Review by murphyatwork — APPROVED** [review]

**Review by kangkaisen — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by Youngwb** [comment]
@Mergifyio backport branch-2.2

**Comment by stdpain** [comment]
https://github.com/Mergifyio backport branch-2.0

**Comment by stdpain** [comment]
@Mergifyio backport branch-2.0

**Pull request merged**
