### PR TITLE
Fix the problem of truncate_decimal

### PR DESCRIPTION
**Pull request by liuyehcf**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] others

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

* Mistakenly pass `ConstColumn` as data column of `NullableColumn`
* Refactor test cases

### CODE REVIEW

**Comment by liuyehcf** [comment]
run starrocks_be_unittest_coverage

**Review by kangkaisen — DISMISSED** [review]

**Comment by kangkaisen** [comment]
run starrocks_be_unittest

**Review by silverbullet233 — DISMISSED** [review]

**Review by murphyatwork — DISMISSED** [review]

**Review by satanson — DISMISSED** [review]

**Review by ZiheLiu — DISMISSED** [review]

**Comment by kangkaisen** [comment]
starrocks_be_unittest

**Comment by liuyehcf** [comment]
run starrocks_be_unittest

**Comment by liuyehcf** [comment]
starrocks_be_unittest

**Review by kangkaisen — APPROVED** [review]

**Review by ZiheLiu — APPROVED** [review]

**Review by satanson — APPROVED** [review]

**Pull request merged**
