### PR TITLE
[Bugfix] Fix the problem of hash distribution

### LINKED ISSUE #9558: The query contains the 'left Join' operation and 'ROW_number' operation, and the results are inconsistent after multiple executions.
### Steps to reproduce the behavior (Required)

```sql
CREATE TABLE `tmp_info` (
  `var_id` int(11) NOT NULL COMMENT "var",
  `var_name` varchar(65533) NOT NULL COMMENT "var",
  `interface_id` varchar(65533) NULL COMMENT "var",
  `update_time` datetime NOT NULL COMMENT "var"
) ENGINE=OLAP 
UNIQUE KEY(`var_id`)
COMMENT "var"
DISTRIBUTED BY HASH(`var_id`) BUCKETS 3 
PROPERTIES (
"replication_num" = "3",
"in_memory" = "false",
"storage_format" = "DEFAULT",
"enable_persistent_index" = "false"
);
```

```sql
insert into tmp_info values 
(12963,'var','var','2022-08-04 11:23:39.280048'),
(12997,'var','var','2022-08-04 11:23:39.292017');
```

```sql
SELECT a.*, b.var_name AS varname
FROM ( 
    select 12963 as var_id 
    union 
    select 12997 as var_id
) a
left outer JOIN (
    select
        var_id,
        var_name,
        update_time,
        interface_id
    from (
        SELECT 
            ROW_NUMBER() over(PARTITION by var_id order by update_time, var_name) as rk,
            var_id,
            var_name,
            update_time,
            interface_id
        FROM tmp_info
    ) t1
    where t1.rk = 1 
) b
ON a.var_id = b.var_id;
```

### Expected behavior (Required)
图片

### Real behavior (Required)
The above query is repeated several times in a row, yielding several different results:
图片
图片
图片
图片

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 
图片

The results of 'show variables'
图片

图片

图片

### PR DESCRIPTION
**Pull request by liuyehcf**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #9558

## Problem Summary(Required) ：

When outputProperty is not satisfied with the requiredProperty, enforcedProperty is calculated, and we should set the enforcedProperty as the final output property.

## Other

A little refactor to simplify the branch condition

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 7 / 7 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/plan/PlanFragmentBuilder.java|7|7|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 8 / 8 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/plan/PlanFragmentBuilder.java|7|7|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/task/EnforceAndCostTask.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 8 / 8 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/plan/PlanFragmentBuilder.java|7|7|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/task/EnforceAndCostTask.java|1|1|100.00%|[]|

**Comment by liuyehcf** [comment]
run starrocks_admit_test

**Comment by liuyehcf** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 8 / 8 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/plan/PlanFragmentBuilder.java|7|7|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/task/EnforceAndCostTask.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 8 / 8 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/plan/PlanFragmentBuilder.java|7|7|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/task/EnforceAndCostTask.java|1|1|100.00%|[]|

**Comment by liuyehcf** [comment]
run starrocks_admit_test

**Review by Seaven — APPROVED** [review]

**Review by Youngwb — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by liuyehcf** [comment]
@Mergifyio backport branch-2.3

**Comment by liuyehcf** [comment]
@Mergifyio backport branch-2.4

**Pull request merged**
