### PR TITLE
[BugFix] fix jdbc mysql unsigned type

### LINKED ISSUE #29361: MySQL External Catalog type mismatch for unsigned int (10)
#### Description

We have a table in MySQL. Here's what it looks like - 

```
mysql> describe table;
+--------------+------------------+------+-----+---------+----------------+
| Field        | Type             | Null | Key | Default | Extra          |
+--------------+------------------+------+-----+---------+----------------+
| id           | int(11)          | NO   | PRI | NULL    | auto_increment |
...
| attempts     | int(10) unsigned | YES  |     | NULL    |                |
+--------------+------------------+------+-----+---------+----------------+
15 rows in set (0.01 sec)
```

This table has been added as an External Catalog in StarRocks. 

When we try to access this through StarRocks, we get the following error - 

```
mysql> describe external_catalog.db.table;
+--------------+--------------+------+-------+---------+-------+
| Field        | Type         | Null | Key   | Default | Extra |
+--------------+--------------+------+-------+---------+-------+
| id           | INT          | No   | false | NULL    |       |
...
| attempts     | INT          | Yes  | false | NULL    |       |
+--------------+--------------+------+-------+---------+-------+
15 rows in set (0.08 sec)

mysql> select * from external_catalog.db.table;
ERROR 1064 (HY000): Type mismatches on column[attempts], JDBC result type is Long, please set the type to bigint
```

### StarRocks version (Required)

```
mysql> select current_version();
+-------------------+
| current_version() |
+-------------------+
| 3.1.0-1778465dbb  |
+-------------------+
1 row in set (0.06 sec)
```

### PR DESCRIPTION
**Pull request by dirtysalt**
Fixes #29361

Since StarRocks does not have unsigned type, so when dealing with Mysql unsigned type, we have to upgrade it to a larger scaled type.

## What type of PR is this:
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4

### CODE REVIEW

**Review by kangkaisen — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 13 / 13 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/connector/jdbc/MysqlSchemaResolver.java|13|13|100.00%|[]|

**Review by Youngwb — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 13 / 13 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/connector/jdbc/MysqlSchemaResolver.java|13|13|100.00%|[]|

**Comment by dirtysalt** [comment]
@mergify backport branch-3.1

**Comment by dirtysalt** [comment]
@mergify backport branch-3.0

**Pull request merged**
