### PR TITLE
[SR SQL Planner Summer Camp] destroy (Add backup syntax parsing function)

### PR DESCRIPTION
**Pull request by melt-code**
## What type of PR is this：
- [ ] bug
- [x] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #7951 

## Problem Summary(Required) ：

Add backup syntax parsing function.

### CODE REVIEW

**Comment by melt-code** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 62 / 92 (67.39%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/ast/AstVisitor.java|0|1|00.00%|[317]|
|:large_blue_circle:|com/starrocks/analysis/BackupStmt.java|1|3|33.33%|[96, 98]|
|:large_blue_circle:|com/starrocks/sql/analyzer/BackupStmtAnalyzer.java|33|52|63.46%|[26, 42, 48, 52, 60, 65, 71, 82, 86, 87, 90, 91, 92, 93, 94, 95, 97, 107, 108]|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|25|33|75.76%|[568, 1954, 1961, 1962, 1963, 1964, 1965, 3129]|
|:large_blue_circle:|com/starrocks/sql/analyzer/Analyzer.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/common/ErrorCode.java|1|1|100.00%|[]|

**Comment by melt-code** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 77 / 92 (83.70%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/ast/AstVisitor.java|0|1|00.00%|[317]|
|:large_blue_circle:|com/starrocks/analysis/BackupStmt.java|1|3|33.33%|[96, 98]|
|:large_blue_circle:|com/starrocks/sql/analyzer/BackupStmtAnalyzer.java|41|52|78.85%|[26, 42, 48, 60, 65, 71, 82, 87, 97, 107, 108]|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|32|33|96.97%|[568]|
|:large_blue_circle:|com/starrocks/sql/analyzer/Analyzer.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/common/ErrorCode.java|1|1|100.00%|[]|

**Comment by melt-code** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 75 / 89 (84.27%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/ast/AstVisitor.java|0|1|00.00%|[371]|
|:large_blue_circle:|com/starrocks/analysis/BackupStmt.java|1|3|33.33%|[96, 98]|
|:large_blue_circle:|com/starrocks/sql/analyzer/BackupStmtAnalyzer.java|41|52|78.85%|[26, 42, 48, 60, 65, 71, 82, 87, 97, 107, 108]|
|:large_blue_circle:|com/starrocks/sql/analyzer/Analyzer.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|30|30|100.00%|[]|
|:large_blue_circle:|com/starrocks/common/ErrorCode.java|1|1|100.00%|[]|

**Comment by melt-code** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 75 / 89 (84.27%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/ast/AstVisitor.java|0|1|00.00%|[367]|
|:large_blue_circle:|com/starrocks/analysis/BackupStmt.java|1|3|33.33%|[96, 98]|
|:large_blue_circle:|com/starrocks/sql/analyzer/BackupStmtAnalyzer.java|41|52|78.85%|[26, 42, 48, 60, 65, 71, 82, 87, 97, 107, 108]|
|:large_blue_circle:|com/starrocks/sql/analyzer/Analyzer.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|30|30|100.00%|[]|
|:large_blue_circle:|com/starrocks/common/ErrorCode.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 78 / 92 (84.78%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/ast/AstVisitor.java|0|1|00.00%|[367]|
|:large_blue_circle:|com/starrocks/analysis/BackupStmt.java|1|3|33.33%|[96, 98]|
|:large_blue_circle:|com/starrocks/sql/analyzer/BackupStmtAnalyzer.java|41|52|78.85%|[26, 42, 48, 60, 65, 71, 82, 87, 97, 107, 108]|
|:large_blue_circle:|com/starrocks/sql/analyzer/Analyzer.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|33|33|100.00%|[]|
|:large_blue_circle:|com/starrocks/common/ErrorCode.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 78 / 92 (84.78%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/ast/AstVisitor.java|0|1|00.00%|[367]|
|:large_blue_circle:|com/starrocks/analysis/BackupStmt.java|1|3|33.33%|[96, 98]|
|:large_blue_circle:|com/starrocks/sql/analyzer/BackupStmtAnalyzer.java|41|52|78.85%|[26, 42, 48, 60, 65, 71, 82, 87, 97, 107, 108]|
|:large_blue_circle:|com/starrocks/sql/analyzer/Analyzer.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|33|33|100.00%|[]|
|:large_blue_circle:|com/starrocks/common/ErrorCode.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 78 / 92 (84.78%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/ast/AstVisitor.java|0|1|00.00%|[367]|
|:large_blue_circle:|com/starrocks/analysis/BackupStmt.java|1|3|33.33%|[96, 98]|
|:large_blue_circle:|com/starrocks/sql/analyzer/BackupStmtAnalyzer.java|41|52|78.85%|[26, 42, 48, 60, 65, 71, 82, 87, 97, 107, 108]|
|:large_blue_circle:|com/starrocks/sql/analyzer/Analyzer.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|33|33|100.00%|[]|
|:large_blue_circle:|com/starrocks/common/ErrorCode.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 168 / 243 (69.14%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/ast/AstVisitor.java|0|1|00.00%|[367]|
|:large_blue_circle:|com/starrocks/planner/EsScanNode.java|0|22|00.00%|[242, 247, 248, 249, 250, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 265, 266, 267, 268, 270, 271, 272]|
|:large_blue_circle:|com/starrocks/analysis/BackupStmt.java|1|3|33.33%|[96, 98]|
|:large_blue_circle:|com/starrocks/common/io/FastByteArrayOutputStream.java|2|3|66.67%|[102]|
|:large_blue_circle:|com/starrocks/external/elasticsearch/QueryConverter.java|70|104|67.31%|[37, 41, 49, 50, 52, 54, 57, 58, 59, 60, 61, 62, 63, 75, 83, 90, 93, 105, 106, 107, 124, 145, 146, 147, 179, 185, 189, 197, 208, 211, 215, 217, 219, 228]|
|:large_blue_circle:|com/starrocks/sql/analyzer/BackupStmtAnalyzer.java|41|52|78.85%|[26, 42, 48, 60, 65, 71, 82, 87, 97, 107, 108]|
|:large_blue_circle:|com/starrocks/external/elasticsearch/QueryBuilders.java|18|22|81.82%|[60, 61, 487, 488]|
|:large_blue_circle:|com/starrocks/sql/analyzer/Analyzer.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|33|33|100.00%|[]|
|:large_blue_circle:|com/starrocks/common/ErrorCode.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 168 / 243 (69.14%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/ast/AstVisitor.java|0|1|00.00%|[367]|
|:large_blue_circle:|com/starrocks/planner/EsScanNode.java|0|22|00.00%|[242, 247, 248, 249, 250, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 265, 266, 267, 268, 270, 271, 272]|
|:large_blue_circle:|com/starrocks/analysis/BackupStmt.java|1|3|33.33%|[96, 98]|
|:large_blue_circle:|com/starrocks/common/io/FastByteArrayOutputStream.java|2|3|66.67%|[102]|
|:large_blue_circle:|com/starrocks/external/elasticsearch/QueryConverter.java|70|104|67.31%|[37, 41, 49, 50, 52, 54, 57, 58, 59, 60, 61, 62, 63, 75, 83, 90, 93, 105, 106, 107, 124, 145, 146, 147, 179, 185, 189, 197, 208, 211, 215, 217, 219, 228]|
|:large_blue_circle:|com/starrocks/sql/analyzer/BackupStmtAnalyzer.java|41|52|78.85%|[26, 42, 48, 60, 65, 71, 82, 87, 97, 107, 108]|
|:large_blue_circle:|com/starrocks/external/elasticsearch/QueryBuilders.java|18|22|81.82%|[60, 61, 487, 488]|
|:large_blue_circle:|com/starrocks/sql/analyzer/Analyzer.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|33|33|100.00%|[]|
|:large_blue_circle:|com/starrocks/common/ErrorCode.java|1|1|100.00%|[]|

**Pull request closed without merging**
