### PR TITLE
[Enhancement] Improve regexp replace use hyperscan for constant pattern

### PR DESCRIPTION
**Pull request by Pslydhh**
## What type of PR is this：
- [ ] bug
- [ ] feature
- [x] enhancement
- [ ] refactor
- [ ] others

## Problem Summary(Required) ：

Because switching between greedy and non-greedy semantics is a no-op in Hyperscan, so we must test every match for pattern with wildcard, that maybe causing performance degradation.
This improve performance for regexp_replace with pattern without wildcard through hyperscan.

## Checklist:
The count of test_all_type_select0_regexp is 4000000, and there are 2000000 lines for id_varchar = 'foaaoxyaabarbaaa'/'foaaoxyaabarbaaaaaaaaaaaa'. 
And we execute following sql to compare with hyperscan and re2:
```
select sum(re) from (select length(regexp_replace(id_varchar, A, B)) as re from test_all_type_select0_regexp) t;
```
use hyperscan for 
- "aaa", "KK": PushTotalTime: ```1s409ms```
- "ba", "KK": PushTotalTime: ```677.183ms```
- "aoxyaaba", "KK": PushTotalTime: ```476.525ms```

use Re2 for 
- "aaa", "KK": PushTotalTime: ```2s935ms(2.08 * hyperscan)```
- "ba", "KK": PushTotalTime: ```2s38ms(3 * hyperscan)```
- "aoxyaaba", "KK": PushTotalTime: ```1s504ms(3.15 * hyperscan)```

### CODE REVIEW

**Review by murphyatwork — DISMISSED** [review]

**Review by satanson — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by mofeiatwork** [comment]
run starrocks_fe_unittest

**Comment by mofeiatwork** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by Seaven — APPROVED** [review]

**Review by satanson — APPROVED** [review]

**Pull request merged**
