### PR TITLE
Replace multiple ifndef define endif header guards with pragma once

### PR DESCRIPTION
**Pull request by tr29038**

### CODE REVIEW

**Comment by imay** [comment]
@tr29038 Thanks for your contribution. Please sign the CLA.

**Comment by tr29038** [comment]
> @tr29038 Thanks for your contribution. Please sign the CLA.

Hey, I've agreed to it and signed it.  I'm getting the message: "You have signed the CLA already but the status is still pending? Let us recheck it."

**Comment by imay** [comment]
@tr29038 
I checked the CLA list. I saw that there was signed name tr29038.
However I saw that the author of this commit is `mastmartelli`.
I think you'd better to change the git-config's user to equal with the name and email which you filled in CLA assigment.
Then push force to this PR and then this CLA check will pass.

**Comment by tr29038** [comment]
> @tr29038 I checked the CLA list. I saw that there was signed name tr29038. However I saw that the author of this commit is `mastmartelli`. I think you'd better to change the git-config's user to equal with the name and email which you filled in CLA assigment. Then push force to this PR and then this CLA check will pass.

Forcing a push was not working for whatever reason.  I went ahead and did a pragma replacement for another file so I could pull request again, this time with the appropriate username and email.

I apologize for the mess this pull request has developed.

**Comment by imay** [comment]
> Forcing a push was not working for whatever reason. I went ahead and did a pragma replacement for another file so I could pull request again, this time with the appropriate username and email.
> 
> I apologize for the mess this pull request has developed.

@tr29038 You did great, needn't to apologize. Maybe you can create a new branch in you local repo, do the same change, push it to another remote branch. Then create a new pull request based on the new branch.

**Pull request closed without merging**
