### PR TITLE
[Enhancement] raise `JournalInconsistentException` instead of `System.exit()` in `EditLog.loadJournal`

### LINKED ISSUE #11227: Remove system.exit in EditLog.loadJournal
## Enhancement

We have added a configuration for skipping certain journals by their ids. But we can't get the journal id if an exception is raised in `EditLog.loadJournal()` because it rudely exits the process on error. We should raise an exception and quit the process all in one function.

```
2022-09-14 17:29:02,383 ERROR (stateChangeExecutor|71) [EditLog.loadJournal():953] Operation Type 10096
com.starrocks.sql.common.DmlException: replace partitions failed
        at com.starrocks.load.InsertOverwriteJobRunner.doCommit(InsertOverwriteJobRunner.java:264) ~[starrocks-fe.jar:?]
        at com.starrocks.load.InsertOverwriteJobRunner.replayStateChange(InsertOverwriteJobRunner.java:154) ~[starrocks-fe.jar:?]
        at com.starrocks.load.InsertOverwriteJobManager.replayInsertOverwriteStateChange(InsertOverwriteJobManager.java:143) ~[starrocks-fe.jar:?]
        at com.starrocks.persist.EditLog.loadJournal(EditLog.java:926) [starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.replayJournalInner(GlobalStateMgr.java:1710) [starrocks-fe.jar:?]
```

### PR DESCRIPTION
**Pull request by padmejin**
## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #11227

## Problem Summary(Required) ：

Raise `JournalInconsistentException` instead of calling `System.exit()` when fatal error occurs in `EditLog.loadJournal()` and the process must terminate itself. All `JournalInconsistentException` will be caught and handled in  `GlobalStateMgr.replayJournalInner`, including printing the id of the current journal. Thus, if a journal cannot be loaded by `EditLog.loadJournal()`, we can find the journal id and skip it.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 0 / 9 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/persist/EditLog.java|0|9|00.00%|[405, 479, 490, 492, 495, 497, 894, 895, 896]|

**Review by gengjun-git — APPROVED** [review]

**Comment by Astralidea** [comment]
run starrocks_fe_unittest

**Review by Astralidea — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by padmejin** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 0 / 9 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/persist/EditLog.java|0|9|00.00%|[405, 479, 490, 492, 495, 497, 894, 895, 896]|

**Comment by padmejin** [comment]
@Mergifyio backport branch-2.4

**Pull request merged**
