### PR TITLE
[Enhancement] Remove check of staros config

### LINKED ISSUE #26049: [storage volume] fe start failed when s3 info not in congfig file
### Steps to reproduce the behavior (Required)
`2023-06-27 20:40:20,006 ERROR (UNKNOWN 172.26.95.102_9010_1687827465061(-1)|1) [StarMgrServer.initialize():141] The configuration item "aws_s3_path = " is invalid, s3 bucket is empty.`

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
`branch-3.1-36de4d8`

### PR DESCRIPTION
**Pull request by TszKitLo40**
Fixes #26049 

## What type of PR is this:
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by kevincai — COMMENTED** [review]
since these configurations is still take effect if the user configures in fe.conf, need define the criteria when is taken as `the user is not configured with the storage info`, when is taken as `the user still configures storage info`.

When the configures still take effects, the check should not be removed during the configuration load.

**Comment by kevincai** [comment]
can close this PR.

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Pull request closed without merging**
