### PR TITLE
[Enhancement] add session variable tablet_internal_parallel_mode

### PR DESCRIPTION
**Pull request by ZiheLiu**
## What type of PR is this：
- [ ] bugfix
- [ ] feature
- [x] enhancement
- [ ] refactor
- [ ] others

## Problem Summary(Required) ：

Add a session variables `tablet_internal_parallel_mode` to make it possible to split tablet forcefully, which is useful for test.

The optional value are `auto` and `force_split`.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by ZiheLiu** [comment]
run starrocks_admit_test

**Comment by ZiheLiu** [comment]
run starrocks_admit_test

**Comment by ZiheLiu** [comment]
run starrocks_admit_test

**Comment by ZiheLiu** [comment]
run starrocks_admit_test

**Comment by ZiheLiu** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 8 / 10 (80.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/analysis/SetVar.java|5|7|71.43%|[213, 214]|
|:large_blue_circle:|com/starrocks/qe/SessionVariable.java|3|3|100.00%|[]|

**Comment by ZiheLiu** [comment]
@Mergifyio backport  branch-2.4

**Review by kangkaisen — APPROVED** [review]

**Review by satanson — APPROVED** [review]

**Pull request merged**
