### PR TITLE
[BugFix] fix desc rollup column name

### PR DESCRIPTION
**Pull request by murphyatwork**
Fixes #issue

Create MV: 
```sql
create materialized view mv111 
as 
select 
  event_id, 
  sum(cast(request_id as bigint)) as sum 
from tbl 
group by event_id
```

Before:
```sql
MySQL root@127.1:hehe> desc mv111
+----------------------------+----------------+------+-------+---------+-------+
| Field                      | Type           | Null | Key   | Default | Extra |
+----------------------------+----------------+------+-------+---------+-------+
| event_id                   | varchar(65533) | YES  | true  | <null>  |       |
| CAST(request_id AS BIGINT) | bigint         | YES  | false | <null>  | SUM   |
+----------------------------+----------------+------+-------+---------+-------+
```

After: 
```sql
MySQL root@127.1:hehe> desc mv111
+----------+----------------+------+-------+---------+-------+
| Field    | Type           | Null | Key   | Default | Extra |
+----------+----------------+------+-------+---------+-------+
| event_id | varchar(65533) | YES  | true  | <null>  |       |
| mv_sum   | bigint         | YES  | false | <null>  | SUM   |
+----------+----------------+------+-------+---------+-------+
```

## What type of PR is this:
- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [x] 3.0
  - [x] 2.5
  - [ ] 2.4

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/ShowStmtAnalyzer.java|2|2|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/ShowStmtAnalyzer.java|2|2|100.00%|[]|

**Review by kangkaisen — APPROVED** [review]

**Review by Seaven — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
