### PR TITLE
[BugFix] Fix correlated scalar non-aggregate subquery unknown error when correlated predicate has expression

### LINKED ISSUE #9616: [sqlancer] query return unknow error
### Steps to reproduce the behavior (Required)
```
DROP DATABASE IF EXISTS h1;
CREATE DATABASE h1;
USE h1;
admin set frontend config ("enable_decimal_v3" = "true");
CREATE TABLE t0 (c_0_0 DATETIME NOT NULL ,c_0_1 LARGEINT NULL ,c_0_2 DATETIME NULL ,c_0_3 SMALLINT NOT NULL ,c_0_4 DECIMAL(12, 9)  NULL ,c_0_5 SMALLINT NULL ,c_0_6 DATE NULL ,c_0_7 DECIMAL(15, 13)  NOT NULL ,c_0_8 BOOLEAN NULL ,c_0_9 DATETIME NULL ,c_0_10 CHAR(11) NULL ,c_0_11 DATE REPLACE NOT NULL ,c_0_12 DECIMAL(1, 0)  MIN NULL ) AGGREGATE KEY (c_0_0,c_0_1,c_0_2,c_0_3,c_0_4,c_0_5,c_0_6,c_0_7,c_0_8,c_0_9,c_0_10) PARTITION BY RANGE(c_0_0) (START ("2010-01-01") END ("2022-12-31") EVERY (INTERVAL 163 day)) DISTRIBUTED BY HASH (c_0_8,c_0_10,c_0_1,c_0_7,c_0_3,c_0_0,c_0_6,c_0_4,c_0_9) BUCKETS 3 properties("replication_num"="3") ;
CREATE TABLE t1 (c_1_0 DECIMAL(12, 3)  NULL ,c_1_1 LARGEINT NULL ) UNIQUE KEY (c_1_0) DISTRIBUTED BY HASH (c_1_0) BUCKETS 3 properties("replication_num"="3") ;
CREATE TABLE IF NOT EXISTS t2 (c_2_0 DATE NOT NULL ,c_2_1 BOOLEAN NOT NULL ,c_2_2 INT NOT NULL ,c_2_3 VARCHAR(1) NOT NULL ) DUPLICATE KEY (c_2_0) PARTITION BY RANGE(c_2_0) (START ("2010-01-01") END ("2022-12-31") EVERY (INTERVAL 131 day)) DISTRIBUTED BY HASH (c_2_0) BUCKETS 3 properties("replication_num"="3") ;
INSERT INTO t1 VALUES (NULL, 1181819718), (192518.186, 1366490557);
INSERT INTO t0 VALUES ('2010-01-06 08:00:14', -449595975, '2010-01-08 08:00:14', 11, 1.33E-7, 11, NULL, 1.0E-12, false, '2010-01-22 08:00:14', '', '2010-01-08', 2), ('2010-01-09 08:00:14', 522133925, '2010-01-20 08:00:14', 11, 7.95E-7, 15, '2010-01-14', 7.6E-12, true, '2010-01-08 08:00:14', 'D', '2010-01-24', NULL);
INSERT INTO t2 VALUES ('2010-01-19', false, 13, ''), ('2010-01-28', true, 30, ''), ('2010-01-15', true, 24, '');
INSERT INTO t1 VALUES (104554.189, 1366490557), (440874.187, 2111793048);
INSERT INTO t1 VALUES (400479.284, 1366490557), (327539.119, 522133925);
INSERT INTO t0 VALUES ('2010-01-05 08:00:14', 1366490557, '2010-01-10 08:00:14', 3, 2.97E-7, 2, '2010-01-20', 4.2E-12, false, '2009-12-31 08:00:14', 'X', '2010-01-30', 8), ('2010-01-14 08:00:14', 522133925, '2010-01-18 08:00:14', 5, 5.25E-7, 10, NULL, 6.9E-12, false, '2010-01-20 08:00:14', '', '2010-01-23', 3), ('2010-01-17 08:00:14', -841557183, '2010-01-10 08:00:14', 4, NULL, 5, '2010-01-23', 2.0E-12, true, '2010-01-25 08:00:14', 'fGtQp', '2010-01-02', 0);
INSERT INTO t2 VALUES ('2010-01-03', true, 26, '');
INSERT INTO t1 VALUES (320602.481, -241162046), (230457.118, -573349461), (799724.570, -449595975);
INSERT INTO t2 VALUES ('2010-01-10', false, 29, ''), ('2010-01-05', false, 29, '');
INSERT INTO t1 VALUES (428413.424, -573349461), (881574.041, -449595975), (NULL, 1967772903);
INSERT INTO t0 VALUES ('2009-12-31 08:00:14', 734729395, '2010-01-23 08:00:14', 11, 8.46E-7, 12, NULL, 1.6E-12, true, '2010-01-30 08:00:14', '', '2010-01-09', 8), ('2010-01-19 08:00:14', 550485201, '2010-01-08 08:00:14', 3, 2.02E-7, 10, '2010-01-26', 4.9E-12, true, '2010-01-18 08:00:14', 'tt', '2010-01-31', 1);
INSERT INTO t1 VALUES (375182.393, -1950535687), (920521.494, 1926204868);
INSERT INTO t1 VALUES (329538.984, 1000307960), (460623.180, 1181819718), (389572.179, 734729395);
INSERT INTO t2 VALUES ('2010-01-09', true, 6, '');
SELECT t1_16.c_1_0 FROM t2 AS t2_17,  (SELECT t0_15.c_0_0, t0_15.c_0_1, t0_15.c_0_2, t0_15.c_0_3, t0_15.c_0_4, t0_15.c_0_5, t0_15.c_0_6, t0_15.c_0_7, t0_15.c_0_8, t0_15.c_0_9, t0_15.c_0_10, t0_15.c_0_11, t0_15.c_0_12 FROM t0 AS t0_15 WHERE  ( (SELECT t2_17.c_2_0 FROM t2 AS t2_17 WHERE (t0_15.c_0_1) IN (284082749) )  ) >= ( (SELECT t0_15.c_0_10 FROM t0 AS t0_15 WHERE true)  ) ) subt0 RIGHT ANTI JOIN t1 AS t1_16 ON subt0.c_0_10 = t1_16.c_1_0 AND subt0.c_0_10 > t1_16.c_1_0 GROUP BY ["u2", "", "", "wY", "FJ6", "XzPhBSI", "7jE", "3", "ive72a", "a", "Dr"], t1_16.c_1_0, ((((((((((791394355)/(-1159455313)))*(((NULL)+(-1532114392)))))-(-1234124688)))/(-388518788)))/(((-2067663923)+(1211547653)))), t1_16.c_1_0 ORDER BY t1_16.c_1_0, t1_16.c_1_0 ASC;


```

```
fe.log:
2022-08-04 23:00:04,308 WARN (starrocks-mysql-nio-pool-6|260) [StmtExecutor.execute():490] execute Exception, sql SELECT t1_16.c_1_0 FROM t2 AS t2_17,  (SELECT t0_15.c_0_0, t0_15
.c_0_1, t0_15.c_0_2, t0_15.c_0_3, t0_15.c_0_4, t0_15.c_0_5, t0_15.c_0_6, t0_15.c_0_7, t0_15.c_0_8, t0_15.c_0_9, t0_15.c_0_10, t0_15.c_0_11, t0_15.c_0_12 FROM t0 AS t0_15 WHERE  (
 (SELECT t2_17.c_2_0 FROM t2 AS t2_17 WHERE (t0_15.c_0_1) IN (284082749) )  ) >= ( (SELECT t0_15.c_0_10 FROM t0 AS t0_15 WHERE true)  ) ) subt0 RIGHT ANTI JOIN t1 AS t1_16 ON sub
t0.c_0_10 = t1_16.c_1_0 AND subt0.c_0_10 > t1_16.c_1_0 GROUP BY ["u2", "", "", "wY", "FJ6", "XzPhBSI", "7jE", "3", "ive72a", "a", "Dr"], t1_16.c_1_0, ((((((((((791394355)/(-11594
55313)))*(((NULL)+(-1532114392)))))-(-1234124688)))/(-388518788)))/(((-2067663923)+(1211547653)))), t1_16.c_1_0 ORDER BY t1_16.c_1_0, t1_16.c_1_0 ASC;
java.lang.IllegalStateException: null
        at com.google.common.base.Preconditions.checkState(Preconditions.java:494) ~[spark-dpp-1.0.0.jar:?]
        at com.starrocks.sql.optimizer.statistics.Statistics.getColumnStatistic(Statistics.java:56) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.computeGroupByStatistics(StatisticsCalculator.java:694) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.computeAggregateNode(StatisticsCalculator.java:674) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.visitLogicalAggregation(StatisticsCalculator.java:658) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.visitLogicalAggregation(StatisticsCalculator.java:137) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.operator.logical.LogicalAggregationOperator.accept(LogicalAggregationOperator.java:132) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.estimatorStats(StatisticsCalculator.java:153) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.task.DeriveStatsTask.execute(DeriveStatsTask.java:76) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.task.SeriallyTaskScheduler.executeTasks(SeriallyTaskScheduler.java:42) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.memoOptimize(Optimizer.java:166) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.optimize(Optimizer.java:105) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.createQueryPlan(StatementPlanner.java:89) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:54) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:347) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:316) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:429) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:667) ~[starrocks-fe.jar:?]
        at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:55) ~[starrocks-fe.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_272]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_272]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_272]

```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - mysql> select current_version();
+----------------------+
| current_version()    |
+----------------------+
| MAIN-RELEASE 4c3388d |
+----------------------+

### PR DESCRIPTION
**Pull request by Youngwb**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #9616 

## Problem Summary(Required) ：

```
SELECT * FROM t0
WHERE t0.v2 > (
      SELECT t1.v2 FROM t1
      WHERE t0.v1 = t1.v1 +1 
);
```
correlated predicate has expression, we need add project node

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Review by kangkaisen — APPROVED** [review]

**Review by Seaven — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by liuyehcf — APPROVED** [review]

**Comment by Youngwb** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 7 / 7 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/ScalarApply2JoinRule.java|7|7|100.00%|[]|

**Comment by Youngwb** [comment]
@Mergifyio backport branch-2.4

**Pull request merged**
