### PR TITLE
[BugFix] Fix cancel export use error accept function bug

### PR DESCRIPTION
**Pull request by HangyuanLiu**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

introduced by #11805 

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Review by murphyatwork — DISMISSED** [review]

**Comment by kangkaisen** [comment]
need UT

**Review by Seaven — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 3 / 6 (50.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/ast/AstVisitor.java|0|3|00.00%|[627, 631, 635]|
|:large_blue_circle:|com/starrocks/analysis/ExportStmt.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/ShowExportStmt.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/CancelExportStmt.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by kangkaisen — APPROVED** [review]

**Review by murphyatwork — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 3 / 6 (50.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/ast/AstVisitor.java|0|3|00.00%|[627, 631, 635]|
|:large_blue_circle:|com/starrocks/analysis/ExportStmt.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/ShowExportStmt.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/CancelExportStmt.java|1|1|100.00%|[]|

**Pull request merged**
