### PR TITLE
[BugFix] Fix scalar subquery with const expression bug

### LINKED ISSUE #5898: query result error in norec mode
### Steps to reproduce the behavior (Required)
```
DROP DATABASE IF EXISTS n6;
CREATE DATABASE n6;
USE n6;
admin set frontend config ("enable_decimal_v3" = "true");
CREATE TABLE IF NOT EXISTS t0 (c_0_0 DATETIME NULL ,c_0_1 DECIMAL(34, 17)  NOT NULL ,c_0_2 FLOAT NULL ,c_0_3 DOUBLE NOT NULL ,c_0_4 ARRAY<STRING> NULL ,c_0_5 DOUBLE NULL ,c_0_6 BOOLEAN NULL ) UNIQUE KEY (c_0_0,c_0_1) PARTITION BY RANGE(c_0_0) (START ("2010-01-01") END ("2021-12-31") EVERY (INTERVAL 97 day)) DISTRIBUTED BY HASH (c_0_0) BUCKETS 3 properties("replication_num"="3") ;
CREATE TABLE IF NOT EXISTS t1 (c_1_0 TINYINT NOT NULL,c_1_1 DECIMAL(2, 0)  NOT NULL) PRIMARY KEY (c_1_0) DISTRIBUTED BY HASH (c_1_0) BUCKETS 3 properties("replication_num"="3") ;
INSERT INTO t1 VALUES (2, 18), (0, 45);
INSERT INTO t1 VALUES (1, 19), (6, 81);
INSERT INTO t0 VALUES (NULL, 0.69370053928189223, 0.4614500821816787, 0.4614500821816787, ["Xg", "LYPbnk1", "4MOwi9r0", "oB1x", "", "L", "Hr"], 0.4423626111906842, false);
INSERT INTO t0 VALUES ("2010-01-14 08:00:14", 0.50689415907503388, 0.4423626111906842, 0.4423626111906842, ["5", "", "2BtKE7t", "", "", "l", "u", "", "", "7WC", "A", "W4"], NULL, NULL), ("2010-01-14 08:00:14", 0.82266639109866315, 0.0015372076037593052, 0.8764240014536524, ["4W6PN", "", "vFaW7", "", "L", "KtW", "V", "YvnzsJ5", "", "hw", "U1", "ep6jtj"], NULL, false), ("2010-01-26 08:00:14", 0.31960701663613339, 0.6106679772333098, 0.3460395637932474, ["", "0bSuL", "ga9", "s", "55"], 0.5389959256251637, false);
INSERT INTO t1 VALUES (3, 85);
INSERT INTO t1 VALUES (5, 89);
INSERT INTO t1 VALUES (5, 61), (5, 32);
INSERT INTO t0 VALUES ("2010-01-16 08:00:14", 0.67386138830733123, 0.352692865083718, 0.9674184237318098, ["Qk92x", "8rSt", "2tKyatSuh"], 0.2912415087281731, false), ("2010-01-18 08:00:14", 0.00470460418440111, 0.0015372076037593052, 0.6636552752397267, ["x", "GPb0xZbvZ", "", "", "II", "Xv", "r", "d", "UJNyQlD", "3qGF"], 0.4423626111906842, false), ("2009-12-31 08:00:14", 0.30908710011853691, 0.7181740490944297, 0.7181740490944297, ["G"], 0.7019483664128373, true);
INSERT INTO t0 VALUES ("2010-01-19 08:00:14", 0.67475154023333958, 0.352692865083718, 0.0015372076037593052, ["", "cp4ec", "fWKr0K7mT", "C", "KT", "Y", "frx", "IwXrka", "Qexw", "0", "Dbh"], 0.9391522525752316, true), ("2010-01-06 08:00:14", 0.82282015226458264, 0.6106679772333098, 0.7518603505395748, ["9Ilg", "", "NfJg", "o62", "", "zy"], 0.5523275911380171, false);
INSERT INTO t0 VALUES ("2010-01-20 08:00:14", 0.83304580168498241, 0.5389959256251637, 0.9046434262202716, ["rM", "IP"], 0.907364649454345, true), ("2009-12-31 08:00:14", 0.27644613585927093, 0.9046434262202716, 0.352692865083718, ["LDyCIMvoU", "1"], 0.13828262350159837, false), ("2010-01-29 08:00:14", 0.68093288033646049, 0.0015372076037593052, 0.8000189867920818, ["", "CZ", "iEPNorb", "Y", "XLy5mj", "S", "7VPev", "BBfM4N", "mEWbX9b"], 0.5958666142808337, false);
INSERT INTO t0 VALUES ("2010-01-25 08:00:14", 0.82054044842532693, 0.8000189867920818, 0.16921883711137442, ["0ol", "lRW", "", "D", "aL", "0Z", "D3BG", "QT", "L", "1XGX", "zsQ"], 0.32355506518148813, true), (NULL, 0.01024942101516603, 0.9782671331825502, 0.13828262350159837, ["vw5YuG", "e2", "7", "eW0eIxfE", "", "gan", "h", "", "7UTNlFy7s"], 0.8048167555076611, NULL);
INSERT INTO t1 VALUES (6, 50), (7, 50);
INSERT INTO t1 VALUES (4, 18), (2, 28);
INSERT INTO t0 VALUES ("2010-01-17 08:00:14", 0.94021129282846211, NULL, 0.45945812771862193, ["5", "kCX", "u", "R", "qpTI", "5Otz54ZQ", "WJ014xet"], 0.8048167555076611, true), ("2010-01-27 08:00:14", 0.74992202739091449, 0.352692865083718, 0.4423626111906842, ["R7kc0LD", "P2b6"], 0.8335780545967256, NULL);
INSERT INTO t1 VALUES (7, 48);
INSERT INTO t1 VALUES (6, 33), (0, 46);
INSERT INTO t0 VALUES ("2010-01-30 08:00:14", 0.20972852195131033, NULL, 0.37577086853948904, ["HFLEB2", "", "O", "HQN"], NULL, true), ("2010-01-28 08:00:14", 0.00844108001080150, 0.31636803178727646, 0.310467259728863, ["XKMntOSx", "9TmJN54i", "fx", "", "B5Ku", "A30rc", "", "HQi29", "D"], NULL, false);
INSERT INTO t0 VALUES ("2010-01-03 08:00:14", 0.20614434653423895, 0.15729966691571873, 0.9056794062255811, ["", "B", "4jZ", "", "", "", "", "TF", "k", "", ""], 0.22439342448409838, false), ("2010-01-07 08:00:14", 0.10799868925205173, 0.7679101677950338, 0.15729966691571873, ["", "A", "RBKxVmtHd", "e", "uM2", "uS5YspDru", "3", "PS", "NV", "", "", "", "mVxZ2iav"], 0.47498189227613274, false), ("2010-01-05 08:00:14", 0.55078722874179152, 0.13601919342479452, 0.7792504938770375, ["iG", "", "fiVvUId", "C", "", "", "Zs", "kglQBC7"], 0.17085630861909806, true), ("2010-01-01 08:00:14", 0.51637924996384696, NULL, 0.16921883711137442, ["KZ", "", "LmAjpsjZE", "", ""], 0.7119418473479668, true);
INSERT INTO t0 VALUES ("2010-01-24 08:00:14", 0.20636009739364537, 0.8506737275670782, 0.6959734562863799, ["r6u9ywN"], NULL, true), ("2010-01-29 08:00:14", 0.59427084349424318, 0.8235605884441284, 0.0015372076037593052, [], 0.13828262350159837, false);
INSERT INTO t0 VALUES ("2010-01-09 08:00:14", 0.93609375247879677, 0.35509294633892585, 0.9674184237318098, ["9", "vosWg", "t", "H", "NCy7X", "DYNAUg", "9", "wywyGibT"], 0.27612078606713875, false), ("2010-01-15 08:00:14", 0.63820395434719614, 0.22439342448409838, 0.7119418473479668, ["64kH", "", "nu", "gZfKn1E", "", "8", "2", "P", "D1Lb", "", "dtJros", "4K5", "ygEL6NLR", "", "W"], 0.4820165238384321, false);
INSERT INTO t1 VALUES (4, 77), (2, 13), (5, 44);
INSERT INTO t0 VALUES (NULL, 0.39801898041857573, NULL, 0.310467259728863, ["kz5xQJXPn", "f6"], NULL, true), ("2010-01-24 08:00:14", 0.57696085164547493, NULL, 0.6925531497971364, ["", "d", "rhcVjijjJ", "H53zA", "", "", "5IJm", "3NOC1", "eavu", "cL", "dZorBUD", "G8iiE"], 0.8203605024694536, true);
INSERT INTO t1 VALUES (7, 22), (0, 5);

mysql> SELECT COUNT(*) FROM t0 AS t0_55 WHERE  ( (SELECT t0_55.c_0_2 FROM t0 AS t0_55, t1 AS t1_56 WHERE false)  ) != ( 0.08341552272184505 ) ;
+----------+
| count(*) |
+----------+
|       17 |
+----------+
1 row in set (0.07 sec)

mysql> SELECT SUM(count) FROM (SELECT CAST((CAST( ( (SELECT t0_55.c_0_2 FROM t0 AS t0_55, t1 AS t1_56 WHERE false)  ) != ( 0.08341552272184505 )  AS BOOLEAN) = true) AND (CAST( ( (SELECT t0_55.c_0_2 FROM t0 AS t0_55, t1 AS t1_56 WHERE false)  ) != ( 0.08341552272184505 )  AS BOOLEAN) IS NOT NULL) AS INT) as count FROM t0 ) t;
+------------+
| sum(count) |
+------------+
|          0 |
+------------+

```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - mysql> select current_version();
+-------------------------+
| current_version()       |
+-------------------------+
| BRANCH-2.2-ASAN baf786d |
+-------------------------+
- cluster: sqlancer_01_asan

### LINKED ISSUE #5941: [sqlancer]Wrong result in norec mode.
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
```
CREATE TABLE IF NOT EXISTS t0 (c_0_0 DATETIME NOT NULL,c_0_1 DATETIME NOT NULL,c_0_2 BOOLEAN NOT NULL,c_0_3 BOOLEAN NOT NULL,c_0_4 INT NOT NULL,c_0_5 SMALLINT NOT NULL,c_0_6 SMALLINT NOT NULL,c_0_7 DATE NOT NULL,c_0_8 FLOAT NOT NULL, INDEX index1_c_0_1(`c_0_1`) USING BITMAP, INDEX index1_c_0_6(`c_0_6`) USING BITMAP) PRIMARY KEY (c_0_0,c_0_1,c_0_2,c_0_3,c_0_4,c_0_5,c_0_6,c_0_7) PARTITION BY RANGE(c_0_1) (START ("2010-01-01") END ("2021-12-31") EVERY (INTERVAL 168 day)) DISTRIBUTED BY HASH (c_0_1,c_0_3) BUCKETS 3 properties("replication_num"="3") ;
CREATE TABLE IF NOT EXISTS t1 (c_1_0 DATETIME NOT NULL ,c_1_1 DATETIME NOT NULL ,c_1_2 LARGEINT NOT NULL ,c_1_3 DATE NULL ,c_1_4 BOOLEAN NULL ,c_1_5 DATE REPLACE_IF_NOT_NULL NULL ,c_1_6 PERCENTILE PERCENTILE_UNION NULL ,c_1_7 DOUBLE MIN NULL ,c_1_8 DOUBLE REPLACE_IF_NOT_NULL NULL ,c_1_9 DATETIME REPLACE NOT NULL ,c_1_10 HLL HLL_UNION NULL ,c_1_11 BOOLEAN REPLACE NOT NULL ,c_1_12 LARGEINT SUM NULL ,c_1_13 BOOLEAN REPLACE NULL ) AGGREGATE KEY (c_1_0,c_1_1,c_1_2,c_1_3,c_1_4) PARTITION BY RANGE(c_1_0) (START ("2010-01-01") END ("2021-12-31") EVERY (INTERVAL 219 day)) DISTRIBUTED BY HASH (c_1_2,c_1_3,c_1_0,c_1_1,c_1_4) BUCKETS 3 properties("replication_num"="3") ;
CREATE TABLE IF NOT EXISTS t2 (c_2_0 DATETIME NOT NULL,c_2_1 VARCHAR(21) NOT NULL) PRIMARY KEY (c_2_0) PARTITION BY RANGE(c_2_0) (START ("2010-01-01") END ("2021-12-31") EVERY (INTERVAL 112 day)) DISTRIBUTED BY HASH (c_2_0) BUCKETS 3 properties("replication_num"="3") ;
```
2. INSERT INTO '....'
```
INSERT INTO t1 VALUES ("2010-01-19 08:00:14", "2010-01-26 08:00:14", -1588917820, "2010-01-20", false, "2010-01-24", percentile_hash("1931433544"), 0.1065402128320806, NULL, "2010-01-08 08:00:14", hll_hash("byTFgnE"), false, -173599758, true);
INSERT INTO t2 VALUES ("2010-01-28 08:00:14", "");
INSERT INTO t1 VALUES ("2010-01-21 08:00:14", "2010-01-14 08:00:14", -332508514, "2010-01-03", false, "2010-01-24", percentile_hash("-785196854"), 0.44947141064102436, 0.44947141064102436, "2010-01-09 08:00:14", hll_hash("wUL"), true, -173599758, true);
INSERT INTO t0 VALUES ("2010-01-21 08:00:14", "2010-01-25 08:00:14", true, false, 20, 2, 9, "2010-01-04", 0.2861244274976371), ("2010-01-18 08:00:14", "2010-01-30 08:00:14", true, false, 16, 6, 8, "2010-01-08", -3.32508514E8);
INSERT INTO t2 VALUES ("2010-01-11 08:00:14", "Q"), ("2010-01-03 08:00:14", "E9r");
INSERT INTO t0 VALUES ("2010-01-01 08:00:14", "2010-01-22 08:00:14", true, true, 10, 15, 4, "2010-01-23", 0.31647669465263883);
TRUNCATE TABLE t0;
INSERT INTO t2 VALUES ("2010-01-17 08:00:14", "A9v"), ("2010-01-22 08:00:14", "");
INSERT INTO t2 VALUES ("2009-12-31 08:00:14", "9MhCxFxJ"), ("2010-01-03 08:00:14", "");
INSERT INTO t2 VALUES ("2010-01-15 08:00:14", "t1tLBp"), ("2010-01-17 08:00:14", ""), ("2010-01-17 08:00:14", "SN");
INSERT INTO t1 VALUES ("2010-01-03 08:00:14", "2010-01-10 08:00:14", 1977974798, "2010-01-06", false, "2010-01-28", percentile_hash("512537623"), -3.32508514E8, 0.08584695899772532, "2009-12-31 08:00:14", hll_hash(""), true, -332508514, true);
INSERT INTO t2 VALUES ("2010-01-18 08:00:14", "Q0Zd");
INSERT INTO t0 VALUES ("2010-01-20 08:00:14", "2010-01-27 08:00:14", false, false, 2, 14, 9, "2010-01-25", 0.6595753842332469);
INSERT INTO t1 VALUES ("2010-01-09 08:00:14", "2010-01-10 08:00:14", 1977974798, "2010-01-20", false, "2010-01-23", percentile_hash("1931433544"), 0.6865104655269632, 0.44947141064102436, "2010-01-25 08:00:14", hll_hash("kEw"), false, 1048211598, true), ("2010-01-06 08:00:14", "2010-01-09 08:00:14", -598473096, "2010-01-04", false, "2010-01-25", percentile_hash("-598473096"), 0.9821648854153061, -7.85196854E8, "2010-01-06 08:00:14", hll_hash(""), true, 398826314, true), ("2010-01-06 08:00:14", "2010-01-08 08:00:14", 1714317612, "2010-01-23", false, "2010-01-10", percentile_hash("-598473096"), 0.1887389893144772, 0.8839027169722962, "2010-01-05 08:00:14", hll_hash("U"), true, 217387726, false);
INSERT INTO t0 VALUES ("2010-01-30 08:00:14", "2010-01-28 08:00:14", false, true, 4, 2, 5, "2010-01-16", 0.6464817192569825), ("2010-01-16 08:00:14", "2010-01-07 08:00:14", true, true, 8, 14, 1, "2010-01-15", 0.8940819923221665);
```
3. SELECT  '....'

### Real behavior (Required)
```
mysql> SELECT COUNT(*) FROM  t2 AS t2_72 RIGHT JOIN t0 AS t0_70 ON t2_72.c_2_1 = t0_70.c_0_0 AND CAST("1969-12-23 15:59:21" AS STRING )  <= t0_70.c_0_0 WHERE  ( (SELECT t1_71.c_1_0 FROM t1 AS t1_71, t0 AS t0_70 WHERE (CAST(((((929497746)*(652283684)))-(((((-1280292463)-(-1625868276)))+(CASE  WHEN false THEN -1809603169  WHEN false THEN -487415762 END)))) AS FLOAT ) )  BETWEEN (0.05088248537140294) AND (GET_JSON_DOUBLE("", "y") ) )  ) < ( CASE  WHEN true THEN "1970-01-06 14:02:50" ELSE "1969-12-10 07:42:54" END ) ;
+----------+
| count(*) |
+----------+
|        3 |
+----------+
1 row in set (0.02 sec)

mysql> SELECT SUM(count) FROM (SELECT CAST((CAST( ( (SELECT t1_71.c_1_0 FROM t1 AS t1_71, t0 AS t0_70 WHERE (CAST(((((929497746)*(652283684)))-(((((-1280292463)-(-1625868276)))+(CASE  WHEN false THEN -1809603169  WHEN false THEN -487415762 END)))) AS FLOAT ) )  BETWEEN (0.05088248537140294) AND (GET_JSON_DOUBLE("", "y") ) )  ) < ( CASE  WHEN true THEN "1970-01-06 14:02:50" ELSE "1969-12-10 07:42:54" END )  AS BOOLEAN) = true) AND (CAST( ( (SELECT t1_71.c_1_0 FROM t1 AS t1_71, t0 AS t0_70 WHERE (CAST(((((929497746)*(652283684)))-(((((-1280292463)-(-1625868276)))+(CASE  WHEN false THEN -1809603169  WHEN false THEN -487415762 END)))) AS FLOAT ) )  BETWEEN (0.05088248537140294) AND (GET_JSON_DOUBLE("", "y") ) )  ) < ( CASE  WHEN true THEN "1970-01-06 14:02:50" ELSE "1969-12-10 07:42:54" END )  AS BOOLEAN) IS NOT NULL) AS INT) as count FROM   t2 AS t2_72 RIGHT JOIN t0 AS t0_70 ON t2_72.c_2_1 = t0_70.c_0_0 AND CAST("1969-12-23 15:59:21" AS STRING )  <= t0_70.c_0_0) t;
+------------+
| sum(count) |
+------------+
|          0 |
+------------+
1 row in set (0.04 sec)
```
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - BRANCH-2.2-RELEASE 4ad057e
 - sqlancer_branch_release

### PR DESCRIPTION
**Pull request by Seaven**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] others

## Which issues of this PR fixes ：

Fixes #5898 #5947 #5950 #5949 #5942 #5940

## Problem Summary(Required) ：

`AssertOneRowNode` will fill `NULL` value if children output is empty, it's will cause expression evalution error, we can't push down predicate on `AssertOneRowNode`

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 21 / 21 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/PruneAssertOneRowRule.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/logical/LogicalAssertOneRowOperator.java|5|5|100.00%|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/logical/LogicalFilterOperator.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/PushDownPredicateAssertOneRow.java|14|14|100.00%|

**Review by liuyehcf — DISMISSED** [review]

**Review by kangkaisen — DISMISSED** [review]

**Comment by Seaven** [comment]
@mergify backport branch-2.2

**Review by Youngwb — DISMISSED** [review]

**Review by liuyehcf — DISMISSED** [review]

**Comment by Seaven** [comment]
run ORCA

**Comment by Seaven** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 22 / 22 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/PruneAssertOneRowRule.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/logical/LogicalAssertOneRowOperator.java|5|5|100.00%|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/logical/LogicalFilterOperator.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/RuleType.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/PushDownPredicateAssertOneRow.java|14|14|100.00%|

**Review by HangyuanLiu — COMMENTED** [review]
Predicates should not be pushed below assertOneNode, such as SQL: select * from t0 where 0 < (select v7 from t2); if t2 contains multiple rows, an error should be reported, and the push-down of redundant predicates may lead to loss of error information

**Comment by Seaven** [comment]
> Predicates should not be pushed below assertOneNode, such as SQL: select * from t0 where 0 < (select v7 from t2); if t2 contains multiple rows, an error should be reported, and the push-down of redundant predicates may lead to loss of error information

You are right

**Comment by Seaven** [comment]
run starrocks_fe_unittest

**Comment by Seaven** [comment]
run starrocks_fe_unittest

**Review by HangyuanLiu — APPROVED** [review]

**Review by kangkaisen — APPROVED** [review]

**Comment by Seaven** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 3 / 3 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/PruneAssertOneRowRule.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/logical/LogicalAssertOneRowOperator.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/logical/LogicalFilterOperator.java|1|1|100.00%|

**Comment by Youngwb** [comment]
@Mergifyio backport branch-2.2

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 3 / 3 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/PruneAssertOneRowRule.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/logical/LogicalAssertOneRowOperator.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/logical/LogicalFilterOperator.java|1|1|100.00%|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 3 / 3 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/PruneAssertOneRowRule.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/logical/LogicalAssertOneRowOperator.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/logical/LogicalFilterOperator.java|1|1|100.00%|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 3 / 3 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/PruneAssertOneRowRule.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/logical/LogicalAssertOneRowOperator.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/logical/LogicalFilterOperator.java|1|1|100.00%|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 3 / 3 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/PruneAssertOneRowRule.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/logical/LogicalAssertOneRowOperator.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/logical/LogicalFilterOperator.java|1|1|100.00%|

**Comment by HangyuanLiu** [comment]
#5975

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 3 / 3 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/PruneAssertOneRowRule.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/logical/LogicalAssertOneRowOperator.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/logical/LogicalFilterOperator.java|1|1|100.00%|

**Pull request merged**
