### PR TITLE
Update date_trunc.md

### PR DESCRIPTION
**Pull request by evelynzhaojie**
rewrite this function

## What type of PR is this：
- [ ] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by evelynzhaojie** [comment]
@mergify backport branch-2.3

**Review by amber-create — APPROVED** [review]

**Review by EsoragotoSpirit — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by evelynzhaojie** [comment]
@mergify backport branch-2.2

**Comment by evelynzhaojie** [comment]
@mergify backport branch-2.1

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Pull request merged**
