### PR TITLE
[Enhancement] Add a configuration item to control data checksum for block cache

### PR DESCRIPTION
**Pull request by GavinMar**
## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

Add a configuration item `block_cache_checksum_enable` to expose the checksum switch for block cache, which enable/disable data checksum when read/write. 

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Review by dirtysalt — DISMISSED** [review]

**Comment by GavinMar** [comment]
run starrocks_be_unittest

**Comment by GavinMar** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
starrocks_be_unittest succeeded.

**Review by dirtysalt — APPROVED** [review]

**Review by gengjun-git — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Pull request merged**
