### PR TITLE
[Enhancement] Add standard unit of time check for batch build partition

### LINKED ISSUE #17320: Create partitions in batches by adding bounds checks by default
## Enhancement
Most of it should be that users don't pay attention (even including not paying attention to whether the week starts on Sunday or Monday).
so,
1. The default check must be complete (the week must be the whole week, the month must be the whole month, etc.), and a parameter that can be forced to not check the whole week/month is allowed to be incomplete.
2. Keep the rules and results of dynamic partition creation and batch partition creation consistent.
3. The error message should be clearly informed, including the open interval on the right side of the partition, such as 22-02-01, 22-03-01 for the month.
4. When there is an error in the week, add the explanation of start_day_of_week information, so that users can quickly know the reason.

### PR DESCRIPTION
**Pull request by Astralidea**
Signed-off-by: Astralidea <astralidea@163.com>

## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #17320

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [x] This pr will affect users' behaviors
- [x] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 39 / 45 (86.67%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/ast/MultiRangePartitionDesc.java|34|40|85.00%|[192, 199, 206, 214, 222, 226]|
|:large_blue_circle:|com/starrocks/common/Config.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/RangePartitionDesc.java|4|4|100.00%|[]|

**Comment by Astralidea** [comment]
run starrocks_admit_test

**Comment by Astralidea** [comment]
run starrocks_admit_test

**Comment by Astralidea** [comment]
run starrocks_admit_test

**Comment by Astralidea** [comment]
run starrocks_admit_test

**Review by gengjun-git — APPROVED** [review]

**Review by ABingHuang — APPROVED** [review]
LGTM

**Pull request merged**
