### PR TITLE
[BugFix] Fix datediff compute expression stats encounter DateTimeException

### PR DESCRIPTION
**Pull request by Youngwb**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes # https://github.com/StarRocks/StarRocksBenchmark/issues/163

## Problem Summary(Required) ：

Utils.getDatetimeFromLong can not deal with -inf/inf, wiil throw DateTimeException

### CODE REVIEW

**Review by kangkaisen — DISMISSED** [review]

**Comment by Youngwb** [comment]
run starrocks_fe_unittest

**Review by imay — APPROVED** [review]

**Review by kangkaisen — APPROVED** [review]

**Comment by Youngwb** [comment]
run starrocks_fe_unittest

**Comment by Youngwb** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Pull request merged**
