### PR TITLE
[BugFix][Cherry-pick]Fix bug view inferred nullable is wrong

### LINKED ISSUE #15649: Whether the View is nullabe or not is incorrectly inferred
### Steps to reproduce the behavior (Required)
1. CREATE TABLE `site_access` (
  `event_day` date NULL COMMENT "",
  `site_id` int(11) NULL DEFAULT "10" COMMENT "",
  `city_code` varchar(100) NULL COMMENT "",
  `user_name` varchar(32) NULL DEFAULT "" COMMENT "",
  `pv` bigint(20) NULL DEFAULT "0" COMMENT ""
) ENGINE=OLAP 
DUPLICATE KEY(`event_day`, `site_id`, `city_code`, `user_name`)
COMMENT "OLAP"
PARTITION BY RANGE(`event_day`)
(PARTITION p20200321 VALUES [("0000-01-01"), ("2020-03-22")),
PARTITION p20200322 VALUES [("2020-03-22"), ("2020-03-23")),
PARTITION p20200323 VALUES [("2020-03-23"), ("2020-03-24")),
PARTITION p20200324 VALUES [("2020-03-24"), ("2020-03-25")))
DISTRIBUTED BY HASH(`event_day`, `site_id`) BUCKETS 32 
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"storage_format" = "DEFAULT",
"enable_persistent_index" = "false",
"compression" = "LZ4"
);
2.create view test as select * from site_access;
3.desc test

### Expected behavior (Required)
```
+-----------+--------------+------+-------+---------+-------+
| Field     | Type         | Null | Key   | Default | Extra |
+-----------+--------------+------+-------+---------+-------+
| event_day | DATE         | Yes  | false | NULL    |       |
| site_id   | INT          | Yes  | false | NULL    |       |
| city_code | VARCHAR(100) | Yes  | false | NULL    |       |
| user_name | VARCHAR(32)  | Yes  | false | NULL    |       |
| pv        | BIGINT       | Yes  | false | NULL    |       |
+-----------+--------------+------+-------+---------+-------+
```
### Real behavior (Required)
```
+-----------+--------------+------+-------+---------+-------+
| Field     | Type         | Null | Key   | Default | Extra |
+-----------+--------------+------+-------+---------+-------+
| event_day | DATE         | No   | false | NULL    |       |
| site_id   | INT          | No   | false | NULL    |       |
| city_code | VARCHAR(100) | No   | false | NULL    |       |
| user_name | VARCHAR(32)  | No   | false | NULL    |       |
| pv        | BIGINT       | No   | false | NULL    |       |
+-----------+--------------+------+-------+---------+-------+
```
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
main,2.5

### PR DESCRIPTION
**Pull request by Astralidea**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #15649

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Review by wanpengfei-git — APPROVED** [review]

**Review by murphyatwork — APPROVED** [review]

**Comment by Astralidea** [comment]
run starrocks_fe_unittest

**Comment by Astralidea** [comment]
run starrocks_fe_unittest

**Comment by Astralidea** [comment]
run starrocks_fe_unittest

**Comment by Astralidea** [comment]
run starrocks_fe_unittest

**Pull request merged**
