### PR TITLE
[Tool] add health check for minio and zeppelin containers in starrocks-stack-compose

### PR DESCRIPTION
**Pull request by dengliu**
…s-stack-compose

## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [X] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [X] Tool

## Which issues of this PR fixes ：
add health check for minio and zeppelin containers in starrocks-stack-compose
Fixes

## Problem Summary(Required) ：
ditto

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
- [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [X] I have checked the version labels which the pr will be auto backported to target branch
  - [X] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Review by imay — APPROVED** [review]

**Comment by dengliu** [comment]
https://github.com/Mergifyio backport branch-2.5

**Comment by dengliu** [comment]
https://github.com/Mergifyio backport branch-2.5

**Comment by dengliu** [comment]
https://github.com/Mergifyio backport branch-2.5

**Comment by chaoyli** [comment]
@mergify backport branch-2.5

**Pull request merged**
