### PR TITLE
[BugFix] Normalize scan limit to be rounded up to chunk_size

### LINKED ISSUE #18405: Weired behaviour for query_scan_row_limit for the query with large limit
### Steps to reproduce the behavior (Required)
```sql
CREATE TABLE `t0` (
    `k1` int(11) NULL COMMENT "",
    `c1` int(11) NULL COMMENT ""
) ENGINE=OLAP
DUPLICATE KEY(`k1`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`k1`) BUCKETS 12;

insert into t0 select * from t0;
insert into t0 select * from t0;
insert into t0 select * from t0;
insert into t0 select * from t0;
insert into t0 select * from t0;
insert into t0 select * from t0;
insert into t0 select * from t0;
insert into t0 select * from t0;
insert into t0 select * from t0;
insert into t0 select * from t0;

CREATE RESOURCE GROUP test_resource_group_3d91d4a4_b36f_11ed_abf7_00163e04d4c2_rg1
TO
    (user='root', query_type in ('select'), db='test_resource_group_3d91d4a4_b36f_11ed_abf7_00163e04d4c2')
WITH (
    'cpu_core_limit' = '10',
    'mem_limit' = '0.99',
    'big_query_scan_rows_limit' = '4099'
);

set enable_resource_group = true;
set pipeline_dop = 1;
select * from t0 where k1 >=0 limit 4097;

```
### Expected behavior (Required)
Return results normally.

### Real behavior (Required)
```
(1064, 'exceed big query scan_rows limit: current is 32768 but limit is 4099')
```

### PR DESCRIPTION
**Pull request by ZiheLiu**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #18405

## Problem Summary(Required) ：

`big_query_scan_rows_limit` respects the `limit` in query, and set the scan rows limit to `limit * DOP * io_parallelism`.

However, a chunk source may scan `chunk_size` (4096 by default) rows at a time.

Assume that `DOP` is 1, `io_parallelism` is 1, `big_query_scan_rows_limit` is 4098. As for `select * from t0 limit 4097`:
- scan_row_limit = 4098
- The second time invocation of `ChunkSource::read` will read 4096 rows, and the total read rows is 8192, which is greater than 4098.
Therefore, normalize `limit` to be rounded up to `chunk_size`.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 3.0
  - [x] 2.5
  - [x] 2.4
  - [x] 2.3

### CODE REVIEW

**Review by murphyatwork — APPROVED** [review]

**Review by satanson — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.4

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.3

**Pull request merged**
