### PR TITLE
[Enhancement] Schedule VERSION_INCOMPLETE task imediately

### LINKED ISSUE #9587: Don't delay VERSION_INCOMPLETE repair task
## Enhancement
Currently we delay some time(`Config.tablet_sched_repair_delay_factor_second`) based on priority before actually schedule a repair task to avoid unnecessay clone in situations like BE temporarily restart, but for VERSION_INCOMPLETE task, there is no need to wait because we don't clone new replica and extra delay can cause missing version problem when doing incremental clone.

### PR DESCRIPTION
**Pull request by nshangyiming**
## What type of PR is this：
- [ ] bug
- [ ] feature
- [x] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #9587

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 0 / 3 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/clone/TabletChecker.java|0|1|00.00%|[310]|
|:large_blue_circle:|com/starrocks/catalog/LocalTablet.java|0|1|00.00%|[643]|
|:large_blue_circle:|com/starrocks/clone/ColocateTableBalancer.java|0|1|00.00%|[235]|

**Review by decster — APPROVED** [review]

**Review by chaoyli — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by nshangyiming** [comment]
@mergify cherry-pick branch-2.4

**Comment by nshangyiming** [comment]
@mergify backport branch-2.4

**Pull request merged**
