### PR TITLE
[Refactor] rename the materialized column API to Generated Column

### PR DESCRIPTION
**Pull request by srlch**
Fixes #issue

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [x] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:disappointed: **fail** : 79 / 128 (61.72%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/AlterTableClauseVisitor.java|7|21|33.33%|[286, 312, 323, 401, 405, 429, 440, 458, 459, 462, 491, 523, 549, 560]|
|:large_blue_circle:|com/starrocks/sql/ast/AddColumnsClause.java|1|3|33.33%|[32, 36]|
|:large_blue_circle:|com/starrocks/alter/SchemaChangeJobV2.java|5|14|35.71%|[516, 522, 528, 549, 550, 551, 591, 593, 604]|
|:large_blue_circle:|com/starrocks/alter/SchemaChangeHandler.java|4|11|36.36%|[180, 188, 331, 334, 416, 420, 446]|
|:large_blue_circle:|com/starrocks/load/Load.java|7|13|53.85%|[185, 242, 323, 324, 449, 675]|
|:large_blue_circle:|com/starrocks/sql/analyzer/UpdateAnalyzer.java|3|5|60.00%|[136, 151]|
|:large_blue_circle:|com/starrocks/sql/InsertPlanner.java|4|6|66.67%|[425, 478]|
|:large_blue_circle:|com/starrocks/sql/ast/ColumnDef.java|5|7|71.43%|[213, 496]|
|:large_blue_circle:|com/starrocks/catalog/Column.java|7|9|77.78%|[473, 507]|
|:large_blue_circle:|com/starrocks/sql/analyzer/CreateTableAnalyzer.java|14|17|82.35%|[430, 436, 446]|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|13|13|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/OlapTable.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/InsertAnalyzer.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/QueryAnalyzer.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/UpdatePlanner.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/task/AlterReplicaTask.java|2|2|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 23 / 31 (74.19%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/storage/schema_change_utils.h|0|1|00.00%|[49]|
|:large_blue_circle:|src/storage/tablet_updates.cpp|1|3|33.33%|[3420, 3421]|
|:large_blue_circle:|src/storage/schema_change.cpp|11|16|68.75%|[360, 361, 457, 483, 484]|
|:large_blue_circle:|src/storage/schema_change_utils.cpp|11|11|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:disappointed: **fail** : 81 / 129 (62.79%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/AlterTableClauseVisitor.java|7|21|33.33%|[286, 312, 323, 401, 405, 429, 440, 458, 459, 462, 491, 523, 549, 560]|
|:large_blue_circle:|com/starrocks/sql/ast/AddColumnsClause.java|1|3|33.33%|[32, 36]|
|:large_blue_circle:|com/starrocks/alter/SchemaChangeJobV2.java|5|14|35.71%|[516, 522, 528, 549, 550, 551, 591, 593, 604]|
|:large_blue_circle:|com/starrocks/alter/SchemaChangeHandler.java|4|11|36.36%|[180, 188, 331, 334, 416, 420, 446]|
|:large_blue_circle:|com/starrocks/load/Load.java|7|13|53.85%|[185, 242, 323, 324, 449, 675]|
|:large_blue_circle:|com/starrocks/sql/analyzer/UpdateAnalyzer.java|3|5|60.00%|[136, 151]|
|:large_blue_circle:|com/starrocks/sql/InsertPlanner.java|4|6|66.67%|[425, 478]|
|:large_blue_circle:|com/starrocks/sql/ast/ColumnDef.java|5|7|71.43%|[213, 496]|
|:large_blue_circle:|com/starrocks/sql/analyzer/CreateTableAnalyzer.java|14|17|82.35%|[430, 436, 446]|
|:large_blue_circle:|com/starrocks/catalog/Column.java|9|10|90.00%|[499]|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|13|13|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/OlapTable.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/InsertAnalyzer.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/QueryAnalyzer.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/UpdatePlanner.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/task/AlterReplicaTask.java|2|2|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 23 / 31 (74.19%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/storage/schema_change_utils.h|0|1|00.00%|[49]|
|:large_blue_circle:|src/storage/tablet_updates.cpp|1|3|33.33%|[3420, 3421]|
|:large_blue_circle:|src/storage/schema_change.cpp|11|16|68.75%|[360, 361, 457, 483, 484]|
|:large_blue_circle:|src/storage/schema_change_utils.cpp|11|11|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:disappointed: **fail** : 81 / 129 (62.79%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/AlterTableClauseVisitor.java|7|21|33.33%|[286, 312, 323, 401, 405, 429, 440, 458, 459, 462, 491, 523, 549, 560]|
|:large_blue_circle:|com/starrocks/sql/ast/AddColumnsClause.java|1|3|33.33%|[32, 36]|
|:large_blue_circle:|com/starrocks/alter/SchemaChangeJobV2.java|5|14|35.71%|[516, 522, 528, 549, 550, 551, 591, 593, 604]|
|:large_blue_circle:|com/starrocks/alter/SchemaChangeHandler.java|4|11|36.36%|[180, 188, 331, 334, 416, 420, 446]|
|:large_blue_circle:|com/starrocks/load/Load.java|7|13|53.85%|[185, 242, 323, 324, 449, 675]|
|:large_blue_circle:|com/starrocks/sql/analyzer/UpdateAnalyzer.java|3|5|60.00%|[136, 151]|
|:large_blue_circle:|com/starrocks/sql/InsertPlanner.java|4|6|66.67%|[425, 478]|
|:large_blue_circle:|com/starrocks/sql/ast/ColumnDef.java|5|7|71.43%|[213, 496]|
|:large_blue_circle:|com/starrocks/sql/analyzer/CreateTableAnalyzer.java|14|17|82.35%|[430, 436, 446]|
|:large_blue_circle:|com/starrocks/catalog/Column.java|9|10|90.00%|[499]|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|13|13|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/OlapTable.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/InsertAnalyzer.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/QueryAnalyzer.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/UpdatePlanner.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/task/AlterReplicaTask.java|2|2|100.00%|[]|

**Review by chaoyli — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:disappointed: **fail** : 80 / 149 (53.69%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/AlterTableClauseVisitor.java|10|38|26.32%|[286, 299, 312, 322, 323, 332, 345, 346, 363, 402, 405, 416, 429, 439, 440, 449, 459, 466, 467, 469, 492, 523, 536, 549, 559, 560, 569, 588]|
|:large_blue_circle:|com/starrocks/sql/ast/AddColumnsClause.java|1|3|33.33%|[32, 36]|
|:large_blue_circle:|com/starrocks/alter/SchemaChangeJobV2.java|6|18|33.33%|[517, 523, 549, 550, 551, 558, 591, 593, 604, 615, 616, 617]|
|:large_blue_circle:|com/starrocks/alter/SchemaChangeHandler.java|4|11|36.36%|[180, 188, 331, 334, 416, 420, 446]|
|:large_blue_circle:|com/starrocks/sql/analyzer/UpdateAnalyzer.java|3|5|60.00%|[136, 151]|
|:large_blue_circle:|com/starrocks/load/Load.java|8|13|61.54%|[185, 242, 324, 449, 675]|
|:large_blue_circle:|com/starrocks/catalog/Column.java|12|18|66.67%|[467, 470, 500, 610, 676, 697]|
|:large_blue_circle:|com/starrocks/sql/InsertPlanner.java|4|6|66.67%|[425, 478]|
|:large_blue_circle:|com/starrocks/sql/ast/ColumnDef.java|5|7|71.43%|[213, 496]|
|:large_blue_circle:|com/starrocks/sql/analyzer/CreateTableAnalyzer.java|14|17|82.35%|[430, 436, 446]|
|:large_blue_circle:|com/starrocks/catalog/OlapTable.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/InsertAnalyzer.java|5|5|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/QueryAnalyzer.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/UpdatePlanner.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/task/AlterReplicaTask.java|2|2|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 26 / 34 (76.47%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/storage/schema_change_utils.h|0|1|00.00%|[49]|
|:large_blue_circle:|src/storage/tablet_updates.cpp|1|3|33.33%|[3420, 3421]|
|:large_blue_circle:|src/storage/schema_change.cpp|11|16|68.75%|[360, 361, 457, 483, 484]|
|:large_blue_circle:|src/storage/schema_change_utils.cpp|14|14|100.00%|[]|

**Pull request merged**
