### PR TITLE
[BugFix] Fix ORC's SearchArgument not followed with case sensitive behavior

### PR DESCRIPTION
**Pull request by Smith-Cruise**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

Fix orc SearchArgument not follow with case sensitive behavior.

For example, we have an orc file's schema as `struct<a int, b int>`, and the SlotDescriptor's name is `A` and `B`.

In `OrcChunkReader`, we use non case sensitive by default, but our SearchArgument has not followed it. So if the user run query: `select * from tbl where A=5`,  it will throw an error message in `OrcRowReaderFilter::filterMinMax()`.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Comment by Smith-Cruise** [comment]
@dirtysalt @DorianZheng PTAL

**Review by Youngwb — APPROVED** [review]

**Review by stephen-shelby — APPROVED** [review]

**Comment by Smith-Cruise** [comment]
run starrocks_admit_test

**Comment by Smith-Cruise** [comment]
@Mergify backport branch-3.0

**Comment by Smith-Cruise** [comment]
@mergify backport branch-2.5

**Pull request merged**
