### PR TITLE
[Feature][Cherry-pick][Branch-2.2] Make ES supports custom timezone.

### PR DESCRIPTION
**Pull request by Smith-Cruise**
## What type of PR is this：
- [x] BugFix
- [x] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Backport #12662
## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Review by wanpengfei-git — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
starrocks_be_unittest succeeded.

**Comment by wanpengfei-git** [comment]
starrocks_be_unittest succeeded.

**Review by dirtysalt — APPROVED** [review]

**Comment by Smith-Cruise** [comment]
@imay PTAL

**Review by imay — APPROVED** [review]

**Comment by imay** [comment]
@Smith-Cruise if 2.2 is merged, 2.3 2.4 also need this patch too.

**Pull request merged**
