### PR TITLE
Fix the problem of rewriten null_flag of nullable column (#3292)

### PR DESCRIPTION
**Pull request by liuyehcf**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] others

cherry-pick pr-3292 to branch-2.1

### CODE REVIEW

**Comment by liuyehcf** [comment]
run starrocks_be_unittest

**Comment by liuyehcf** [comment]
run starrocks_be_unittest

**Comment by kangkaisen** [comment]
run starrocks_be_unittest

**Comment by kangkaisen** [comment]
run starrocks_be_unittest

**Pull request merged**
