### PR TITLE
[BugFix] Fix missing hack NULL_TYPE for field child_type

### LINKED ISSUE #14288: [BugFix] Be crash on wrong type
### Steps to reproduce the behavior (Required)

```sql
WITH cte_1 AS (
  SELECT null v1
)
SELECT  
  CASE 
    WHEN a.v1 = b.v1 THEN 1 
    ELSE -1 
  END IS_OK
FROM cte_1 a, cte_1 b
```

### Expected behavior (Required)

The right answer

### Real behavior (Required)

Crash

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

+-------------------+
| current_version() |
+-------------------+
| UNKNOWN 44fd7efb8 |
+-------------------+

### PR DESCRIPTION
**Pull request by liuyehcf**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #14288

## Problem Summary(Required) ：

By design, be cannot see this specific type `NULL_TYPE`, so it need to be hacked in fe, by replacing it with a null literal of boolean type. And here is the problem, it forgot to hack another field `child_type` which will be checked in be that causing be to crash. 

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 1 / 2 (50.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/analysis/Expr.java|1|2|50.00%|[760]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 1 / 2 (50.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/analysis/Expr.java|1|2|50.00%|[760]|

**Review by trueeyu — DISMISSED** [review]

**Review by Seaven — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/analysis/Expr.java|2|2|100.00%|[]|

**Review by Seaven — APPROVED** [review]

**Review by kangkaisen — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by liuyehcf** [comment]
@Mergifyio backport branch-2.5

**Comment by liuyehcf** [comment]
All cherry-picks
* 2.2 https://github.com/StarRocks/starrocks/pull/14415
* 2.3 https://github.com/StarRocks/starrocks/pull/14414
* 2.4 https://github.com/StarRocks/starrocks/pull/14413
* 2.5 https://github.com/StarRocks/starrocks/pull/14405

**Pull request merged**
