### PR TITLE
[BugFix] percentile_cont in force_streaming mode cause be's crash

### PR DESCRIPTION
**Pull request by satanson**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #
https://github.com/StarRocks/starrocks/issues/11262
## Problem Summary(Required) ：

PercentileContAggregateFunction's method convert_to_serialize_format is implemented incorrectly, this functions is called and causes BE's crash when streaming_preaggregation_mode = 'force_streaming'.  There are two errors as follows:
1. Forget to update offsets of BinaryColumn when append an to BinaryColumn;
2. In convert_to_serialize_format function, we must serialize row-by-row instead of sequeeze many rows into a row, since the columns in Chunk must be equal-size.
## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 2.5
  - [x] 2.4
  - [x] 2.3
  - [x] 2.2

### CODE REVIEW

**Review by imay — DISMISSED** [review]

**Review by imay — APPROVED** [review]

**Review by kangkaisen — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.4

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.2

**Pull request merged**
