### PR TITLE
[BugFix] fix union rewrite bug for mv with tll

### LINKED ISSUE #14489: union rewrite for materialized view with ttl failed
### Steps to reproduce the behavior (Required)
1. CREATE TABLE
admin set frontend config ("enable_experimental_mv" = "true");
set enable_materialized_view_rewrite = true;

CREATE TABLE `test_base_part` (
  `c1` int(11) NULL COMMENT "",
  `c2` bigint(20) NULL COMMENT "",
  `c3` bigint(20) NULL COMMENT "",
  `c4` bigint(20) NULL COMMENT ""
) ENGINE=OLAP
DUPLICATE KEY(`c1`, `c2`, `c3`)
COMMENT "OLAP"
PARTITION BY RANGE(`c3`)
(PARTITION p1 VALUES [("-9223372036854775808"), ("100")),
PARTITION p2 VALUES [("100"), ("200")),
PARTITION p3 VALUES [("200"), ("1000")),
PARTITION p4 VALUES [("1000"), ("2000")),
PARTITION p5 VALUES [("2000"), ("3000")))
DISTRIBUTED BY HASH(`c1`) BUCKETS 6
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"storage_format" = "DEFAULT",
"enable_persistent_index" = "false",
"compression" = "LZ4"
);

CREATE MATERIALIZED VIEW `test_mv4`
COMMENT "MATERIALIZED_VIEW"
PARTITION BY (`c3`)
DISTRIBUTED BY HASH(`c1`) BUCKETS 6
REFRESH MANUAL
PROPERTIES (
"replication_num" = "1",
"storage_medium" = "HDD",
"partition_ttl_number" = "3"
)
AS SELECT `test_base_part`.`c1`, `test_base_part`.`c3`, sum(`test_base_part`.`c2`) AS `c2`
FROM `mvdb`.`test_base_part`
GROUP BY `test_base_part`.`c1`, `test_base_part`.`c3`;

3. refresh materialized view test_mv4
4. wait ttl_number takes effect.
5. explain select sum(c2) from test_base_part;

### Expected behavior (Required)
the query plan should be union of mv and part of base table

+-------------------------------------------------------------------------------------------+
| PLAN FRAGMENT 0                                                                           |
|  OUTPUT EXPRS:5: sum                                                                      |
|   PARTITION: UNPARTITIONED                                                                |
|                                                                                           |
|   RESULT SINK                                                                             |
|                                                                                           |
|   15:Project                                                                              |
|   |  <slot 5> : 17: sum                                                                   |
|   |                                                                                       |
|   14:AGGREGATE (merge finalize)                                                           |
|   |  output: sum(17: sum)                                                                 |
|   |  group by:                                                                            |
|   |                                                                                       |
|   13:EXCHANGE                                                                             |
|                                                                                           |
| PLAN FRAGMENT 1                                                                           |
|  OUTPUT EXPRS:                                                                            |
|   PARTITION: RANDOM                                                                       |
|                                                                                           |
|   STREAM DATA SINK                                                                        |
|     EXCHANGE ID: 13                                                                       |
|     UNPARTITIONED                                                                         |
|                                                                                           |
|   12:AGGREGATE (update serialize)                                                         |
|   |  output: sum(16: sum)                                                                 |
|   |  group by:                                                                            |
|   |                                                                                       |
|   0:UNION                                                                                 |
|   |                                                                                       |
|   |----11:EXCHANGE                                                                        |
|   |                                                                                       |
|   5:EXCHANGE                                                                              |
|                                                                                           |
| PLAN FRAGMENT 2                                                                           |
|  OUTPUT EXPRS:                                                                            |
|   PARTITION: UNPARTITIONED                                                                |
|                                                                                           |
|   STREAM DATA SINK                                                                        |
|     EXCHANGE ID: 11                                                                       |
|     RANDOM                                                                                |
|                                                                                           |
|   10:Project                                                                              |
|   |  <slot 15> : 9: sum                                                                   |
|   |                                                                                       |
|   9:AGGREGATE (merge finalize)                                                            |
|   |  output: sum(9: sum)                                                                  |
|   |  group by:                                                                            |
|   |                                                                                       |
|   8:EXCHANGE                                                                              |
|                                                                                           |
| PLAN FRAGMENT 3                                                                           |
|  OUTPUT EXPRS:                                                                            |
|   PARTITION: RANDOM                                                                       |
|                                                                                           |
|   STREAM DATA SINK                                                                        |
|     EXCHANGE ID: 08                                                                       |
|     UNPARTITIONED                                                                         |
|                                                                                           |
|   7:AGGREGATE (update serialize)                                                          |
|   |  output: sum(8: c2)                                                                   |
|   |  group by:                                                                            |
|   |                                                                                       |
|   6:OlapScanNode                                                                          |
|      TABLE: test_mv4                                                                      |
|      PREAGGREGATION: ON                                                                   |
|      partitions=3/3                                                                       |
|      rollup: test_mv4                                                                     |
|      tabletRatio=18/18                                                                    |
|      tabletList=243700,243702,243704,243706,243708,243710,243712,243714,243716,243718 ... |
|      cardinality=3                                                                        |
|      avgRowSize=3.0                                                                       |
|      numNodes=0                                                                           |
|                                                                                           |
| PLAN FRAGMENT 4                                                                           |
|  OUTPUT EXPRS:                                                                            |
|   PARTITION: UNPARTITIONED                                                                |
|                                                                                           |
|   STREAM DATA SINK                                                                        |
|     EXCHANGE ID: 05                                                                       |
|     RANDOM                                                                                |
|                                                                                           |
|   4:AGGREGATE (merge finalize)                                                            |
|   |  output: sum(14: sum)                                                                 |
|   |  group by:                                                                            |
|   |                                                                                       |
|   3:EXCHANGE                                                                              |
|                                                                                           |
| PLAN FRAGMENT 5                                                                           |
|  OUTPUT EXPRS:                                                                            |
|   PARTITION: RANDOM                                                                       |
|                                                                                           |
|   STREAM DATA SINK                                                                        |
|     EXCHANGE ID: 03                                                                       |
|     UNPARTITIONED                                                                         |
|                                                                                           |
|   2:AGGREGATE (update serialize)                                                          |
|   |  output: sum(10: c2)                                                                  |
|   |  group by:                                                                            |
|   |                                                                                       |
|   1:OlapScanNode                                                                          |
|      TABLE: test_base_part                                                                |
|      PREAGGREGATION: ON                                                                   |
|      PREDICATES: (12: c3 < 200) OR (12: c3 >= 3000)                                       |
|      partitions=5/5                                                                       |
|      rollup: test_base_part                                                               |
|      tabletRatio=30/30                                                                    |
|      tabletList=220050,220052,220054,220056,220058,220060,220062,220064,220066,220068 ... |
|      cardinality=4                                                                        |
|      avgRowSize=2.0                                                                       |
|      numNodes=0                                                                           |

### Real behavior (Required)
the query plan do not contain mv
| PLAN FRAGMENT 0                                                                           |
|  OUTPUT EXPRS:5: sum                                                                      |
|   PARTITION: UNPARTITIONED                                                                |
|                                                                                           |
|   RESULT SINK                                                                             |
|                                                                                           |
|   3:AGGREGATE (merge finalize)                                                            |
|   |  output: sum(5: sum)                                                                  |
|   |  group by:                                                                            |
|   |                                                                                       |
|   2:EXCHANGE                                                                              |
|                                                                                           |
| PLAN FRAGMENT 1                                                                           |
|  OUTPUT EXPRS:                                                                            |
|   PARTITION: RANDOM                                                                       |
|                                                                                           |
|   STREAM DATA SINK                                                                        |
|     EXCHANGE ID: 02                                                                       |
|     UNPARTITIONED                                                                         |
|                                                                                           |
|   1:AGGREGATE (update serialize)                                                          |
|   |  output: sum(2: c2)                                                                   |
|   |  group by:                                                                            |
|   |                                                                                       |
|   0:OlapScanNode                                                                          |
|      TABLE: test_base_part                                                                |
|      PREAGGREGATION: ON                                                                   |
|      partitions=5/5                                                                       |
|      rollup: test_base_part                                                               |
|      tabletRatio=30/30                                                                    |
|      tabletList=220050,220052,220054,220056,220058,220060,220062,220064,220066,220068 ... |
|      cardinality=5                                                                        |
|      avgRowSize=1.0                                                                       |
|      numNodes=0                                                                           |
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by ABingHuang**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #14489 

## Problem Summary(Required) ：

fix union rewrite bug for mv with tll
## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Comment by ABingHuang** [comment]
run starrocks_admit_test

**Review by kangkaisen — DISMISSED** [review]

**Review by murphyatwork — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by Youngwb — DISMISSED** [review]

**Comment by ABingHuang** [comment]
run starrocks_fe_unittest

**Comment by ABingHuang** [comment]
run starrocks_fe_unittest

**Comment by ABingHuang** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 13 / 13 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/MaterializedViewOptimizer.java|13|13|100.00%|[]|

**Review by kangkaisen — APPROVED** [review]

**Review by murphyatwork — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
