### PR TITLE
[BugFix] aggregate query statistic from all executor nodes

### LINKED ISSUE #9673: ScanRows in audit log of pipeline engine is wrong
### Steps to reproduce the behavior (Required)
1. Use a cluster with **3 BEs**.
2. Create tables and run the query.
```sql
create d0;
use d0;

CREATE TABLE `t1` (
  `c1` int(11) NOT NULL,
  `c2` int(11) NOT NULL
) ENGINE=OLAP
DUPLICATE KEY(`c1`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`c1`) BUCKETS 12
PROPERTIES (
"replication_num" = "1"
);

insert into t1 values (1,1), (2,2), (3,3), (4,4), (5,5), (6,6), (7, 7), (8,8), (9,9);

set enable_pipeline_engine=true;
select * from t1;
```

### Expected behavior (Required)
The `ScanRows` of query result in audit log is 9.

### Real behavior (Required)
The `ScanRows` of query result in audit log only shows the number of scan rows in one BE, including 2, 3, 4.

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

81db90ddbca723a5fb03f0f51c8d8447ba39ba4a

### PR DESCRIPTION
**Pull request by murphyatwork**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #9673

## Problem Summary(Required) ：

Aggregate query-statistic from multiple executor nodes.
- Collect local statistic at `QueryContext`
- Transmit statistic to other nodes through `transmit_chunk` and `transmit_data` RPC
- Statistic received from remote notes are maintained at `QueryStatisticsRecvr`
- Before send statistic to other nodes(excluding final sink node), aggregate local statistic and received statistics
- Since all statistics is transmitted in delta, and finally it could be aggregated exactly once

Concurrency:
- Local statistic in QueryContext is maintained through atomic integers, and accessed by pipeline executors
- Received statistics is protected a big lock, accessed by both `DataStreamRecv` and `ExchangeSinkOperator`

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by mofeiatwork** [comment]
@Mergifyio backport branch-2.3 branch-2.4

**Comment by mofeiatwork** [comment]
run starrocks_admit_test

**Comment by mofeiatwork** [comment]
run starrocks_admit_test

**Comment by mofeiatwork** [comment]
@Mergifyio rebase

**Comment by mofeiatwork** [comment]
run starrocks_admit_test

**Comment by mofeiatwork** [comment]
run starrocks_admit_test

**Comment by mofeiatwork** [comment]
run starrocks_admit_test

**Comment by kangkaisen** [comment]
did we do the full performance test?

**Review by stdpain — APPROVED** [review]

**Review by satanson — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by silverbullet233 — APPROVED** [review]

**Pull request merged**
