### PR TITLE
[Enhancement] Column iterator uses its own file to read data

### PR DESCRIPTION
**Pull request by wyb**
## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

We introduce buffer in starlet s3/hdfs file to prefetch some remote data to improve read efficiency for lake table. However, currently all column iterators of a segment use a shared file, which will cause buffer invalidation, so we need to create a separate file for each column iterator.

Test result of buffer:

```
data: 
ssb lineorder 6kw
bucket 1
oss

select count(lo_orderkey) from lineorder;
buffer size     io time
0               15s327ms
128K            1s910ms
256K            1s295ms
512K            995ms
1M              788ms

select count(lo_orderkey), count(lo_linenumber) from lineorder;
buffer size     io time
0               29s897ms
128K            2s901ms
256K            2s214ms
512K            1s629ms
1M              1s17ms

select count(lo_orderkey), count(lo_linenumber), count(lo_custkey), count(lo_partkey) from lineorder;
buffer size     io time
0               70s
128K            18s813ms
256K            14s152ms
512K            11s949ms
1M              8s592ms
```

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 3.0
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Review by imay — APPROVED** [review]

**Comment by sduzh** [comment]
If there are multiple columns or multiple concurrent queries, is this patch likely to cause out of control memory usage?

**Comment by wyb** [comment]
> If there are multiple columns or multiple concurrent queries, is this patch likely to cause out of control memory usage?

maybe, optimize later

**Comment by sduzh** [comment]
If you want to reduce small IO requests, maybe we can implement a new PageCacheFileSystem that can provide file page cache like the OS.

**Comment by wyb** [comment]
> Maybe we can implement a new PageCacheFileSystem that can provide file page cache like the OS to reduce small IO requests, which can limit the memory usage.

I think page cache will take up more memory, and it is best used to only cache hot data, which is better for small queries.

**Review by dirtysalt — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Pull request merged**
