### PR TITLE
[BugFix] Fix double/float/date cast to string in FE

### LINKED ISSUE #27240: [Bug][Behavior Change] The result of constant double/decimal cast to string change
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
2. INSERT INTO '....'
3. SELECT  '....'

### FIX PR
https://github.com/StarRocks/starrocks/pull/27070
https://github.com/StarRocks/starrocks/pull/27235

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - 2.4, 2.5, 3.0, 3.1

### PR DESCRIPTION
**Pull request by Seaven**
Fixes #27240

1. keep same cast logical as BE on double/float type

before:
```
MySQL td> select cast(cast(1.00 as double) as string);
+------------------------------------------------+
| CAST((CAST(1.00 AS DOUBLE)) AS VARCHAR(65533)) |
+------------------------------------------------+
| 1.0                                            |
+------------------------------------------------+
1 row in set
```

after
```
MySQL td> select cast(cast(1.00 as double) as string);
+------------------------------------------------+
| CAST((CAST(1.00 AS DOUBLE)) AS VARCHAR(65533)) |
+------------------------------------------------+
| 1                                              |
+------------------------------------------------+
1 row in set
```

3. support `cast('2020-05-01T13:45:57' as datetime)` on FE
4. move the cast logical of DateLiteral to DateUtils

Note: the double cast change will take `insert` logical change, like:
```
MySQL td>   insert into ds1 select  4, cast(4.00 as double), 4.0;
Query OK, 1 row affected
MySQL td>   insert into ds1 values (5, cast(5.00 as double), 5.0);
Query OK, 1 row affected
MySQL td> select * from ds1;
+----+-----+-----+
| v1 | v2  | v3  |
+----+-----+-----+
| 4  | 4   | 4.0 |
| 5  | 5.0 | 5.0 |
+----+-----+-----+
2 rows in set
MySQL td> select * from dd1; -- (int, double ,decimal(27, 9))
+----+-----+-------------+
| v1 | v2  | v3          |
+----+-----+-------------+
| 2  | 2.0 | 2.000000000 |
| 1  | 1.0 | 1.000000000 |
+----+-----+-------------+
2 rows in set
MySQL td>   insert into ds1 select * from dd1;
Query OK, 2 rows affected
MySQL td> select * from ds1;
+----+-----+-------------+
| v1 | v2  | v3          |
+----+-----+-------------+
| 2  | 2   | 2.000000000 |
| 1  | 1   | 1.000000000 |
| 4  | 4   | 4.0         |
| 5  | 5.0 | 5.0         |
+----+-----+-------------+
4 rows in set
Time: 0.017s
MySQL td>
```

## What type of PR is this:
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [x] 3.0
  - [x] 2.5
  - [x] 2.4

### CODE REVIEW

**Review by kangkaisen — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 69 / 70 (98.57%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/scalar/ConstantOperator.java|8|9|88.89%|[190]|
|:large_blue_circle:|com/starrocks/common/util/DateUtils.java|49|49|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/DateLiteral.java|6|6|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rewrite/ScalarOperatorFunctions.java|6|6|100.00%|[]|

**Review by packy92 — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.4

**Pull request merged**
