### PR TITLE
[Feature] support resource statements in new RBAC privilege framework

### PR DESCRIPTION
**Pull request by padmejin**
## What type of PR is this：
- [ ] BugFix
- [x] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

* Add a new type of privilege object to represent privileges on resources.
* PrivilegeCheckerV2 support `create resource`, `drop resource`, `alter resource` statements.
* support upgrading the privilege of usage on resource to current version.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
- [ ] I have added documentation for my new feature or new function

### CODE REVIEW

**Comment by padmejin** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 61 / 84 (72.62%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/privilege/ResourcePEntryObject.java|21|38|55.26%|[17, 30, 42, 58, 63, 64, 66, 68, 69, 70, 72, 75, 76, 78, 89, 92, 100]|
|:large_blue_circle:|com/starrocks/sql/analyzer/PrivilegeCheckerV2.java|8|11|72.73%|[176, 185, 194]|
|:large_blue_circle:|com/starrocks/privilege/PrivilegeManager.java|8|11|72.73%|[586, 587, 588]|
|:large_blue_circle:|com/starrocks/privilege/PrivilegeType.java|15|15|100.00%|[]|
|:large_blue_circle:|com/starrocks/privilege/DefaultAuthorizationProvider.java|7|7|100.00%|[]|
|:large_blue_circle:|com/starrocks/persist/gson/GsonUtils.java|2|2|100.00%|[]|

**Comment by padmejin** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 69 / 84 (82.14%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/PrivilegeCheckerV2.java|8|11|72.73%|[176, 185, 194]|
|:large_blue_circle:|com/starrocks/privilege/PrivilegeManager.java|8|11|72.73%|[586, 587, 588]|
|:large_blue_circle:|com/starrocks/privilege/ResourcePEntryObject.java|29|38|76.32%|[42, 64, 69, 70, 72, 76, 89, 92, 100]|
|:large_blue_circle:|com/starrocks/privilege/PrivilegeType.java|15|15|100.00%|[]|
|:large_blue_circle:|com/starrocks/privilege/DefaultAuthorizationProvider.java|7|7|100.00%|[]|
|:large_blue_circle:|com/starrocks/persist/gson/GsonUtils.java|2|2|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 71 / 84 (84.52%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/PrivilegeCheckerV2.java|8|11|72.73%|[176, 185, 194]|
|:large_blue_circle:|com/starrocks/privilege/PrivilegeManager.java|8|11|72.73%|[586, 587, 588]|
|:large_blue_circle:|com/starrocks/privilege/ResourcePEntryObject.java|31|38|81.58%|[42, 64, 70, 76, 89, 92, 100]|
|:large_blue_circle:|com/starrocks/privilege/PrivilegeType.java|15|15|100.00%|[]|
|:large_blue_circle:|com/starrocks/privilege/DefaultAuthorizationProvider.java|7|7|100.00%|[]|
|:large_blue_circle:|com/starrocks/persist/gson/GsonUtils.java|2|2|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 106 / 119 (89.08%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/PrivilegeCheckerV2.java|8|11|72.73%|[176, 185, 194]|
|:large_blue_circle:|com/starrocks/privilege/PrivilegeManager.java|8|11|72.73%|[586, 587, 588]|
|:large_blue_circle:|com/starrocks/privilege/ResourcePEntryObject.java|32|38|84.21%|[42, 64, 76, 89, 92, 100]|
|:large_blue_circle:|com/starrocks/mysql/privilege/AuthUpgrader.java|34|35|97.14%|[464]|
|:large_blue_circle:|com/starrocks/privilege/PrivilegeType.java|15|15|100.00%|[]|
|:large_blue_circle:|com/starrocks/privilege/DefaultAuthorizationProvider.java|7|7|100.00%|[]|
|:large_blue_circle:|com/starrocks/persist/gson/GsonUtils.java|2|2|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 106 / 119 (89.08%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/PrivilegeCheckerV2.java|8|11|72.73%|[176, 185, 194]|
|:large_blue_circle:|com/starrocks/privilege/PrivilegeManager.java|8|11|72.73%|[586, 587, 588]|
|:large_blue_circle:|com/starrocks/privilege/ResourcePEntryObject.java|32|38|84.21%|[42, 64, 76, 89, 92, 100]|
|:large_blue_circle:|com/starrocks/mysql/privilege/AuthUpgrader.java|34|35|97.14%|[464]|
|:large_blue_circle:|com/starrocks/privilege/PrivilegeType.java|15|15|100.00%|[]|
|:large_blue_circle:|com/starrocks/privilege/DefaultAuthorizationProvider.java|7|7|100.00%|[]|
|:large_blue_circle:|com/starrocks/persist/gson/GsonUtils.java|2|2|100.00%|[]|

**Comment by padmejin** [comment]
run starrocks_admit_test

**Comment by padmejin** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 112 / 125 (89.60%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/PrivilegeCheckerV2.java|8|11|72.73%|[176, 185, 194]|
|:large_blue_circle:|com/starrocks/privilege/PrivilegeManager.java|14|17|82.35%|[613, 614, 615]|
|:large_blue_circle:|com/starrocks/privilege/ResourcePEntryObject.java|32|38|84.21%|[42, 64, 76, 89, 92, 100]|
|:large_blue_circle:|com/starrocks/mysql/privilege/AuthUpgrader.java|34|35|97.14%|[464]|
|:large_blue_circle:|com/starrocks/privilege/PrivilegeType.java|15|15|100.00%|[]|
|:large_blue_circle:|com/starrocks/privilege/DefaultAuthorizationProvider.java|7|7|100.00%|[]|
|:large_blue_circle:|com/starrocks/persist/gson/GsonUtils.java|2|2|100.00%|[]|

**Review by nshangyiming — APPROVED** [review]

**Review by gengjun-git — APPROVED** [review]

**Review by meegoo — APPROVED** [review]

**Pull request merged**
