### PR TITLE
[BugFix] Set default AWS region when user not specific region explictily

### PR DESCRIPTION
**Pull request by Smith-Cruise**
Fix `"Unable to find a region via the region provider chain."` problem.
Refer to the same problem in https://issues.apache.org/jira/browse/HADOOP-17771

In iceberg s3, if a user is not using aws services, and he only configures `aws.s3.endpoint` to access files in Minio using `s3://` protocol, sr will throw the below exception:
```bash
software.amazon.awssdk.core.exception.SdkClientException: Unable to load region from any of the providers in the chain software.amazon.awssdk.regions.providers.DefaultAwsRegionProviderChain@13f10a6b: 
[software.amazon.awssdk.regions.providers.SystemSettingsRegionProvider@240eb9d5: Unable to load region from system settings. Region must be specified either via environment variable (AWS_REGION) or  system property (aws.region).
, software.amazon.awssdk.regions.providers.AwsProfileRegionProvider@7856ae5a: No region provided in profile: default, software.amazon.awssdk.regions.providers.InstanceProfileRegionProvider@d656d66: Unable to contact EC2 metadata service.] 
```

So we need to set a default region here.

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.2
  - [x] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by letian-jiang — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:disappointed: **fail** : 8 / 18 (44.44%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/connector/hive/glue/metastore/AWSGlueClientFactory.java|0|1|00.00%|[93]|
|:large_blue_circle:|com/starrocks/connector/iceberg/IcebergAwsClientFactory.java|0|2|00.00%|[98, 109]|
|:large_blue_circle:|com/starrocks/credential/aws/AWSCloudCredential.java|6|13|46.15%|[136, 137, 138, 139, 141, 192, 201]|
|:large_blue_circle:|com/starrocks/credential/aws/AWSCloudConfigurationProvider.java|2|2|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by dirtysalt — APPROVED** [review]

**Review by Youngwb — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.2

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Pull request merged**
