### PR TITLE
[BugFix] Fix segment size in metadata cache (#31978)

### PR DESCRIPTION
**Pull request by wyb**
Fixes #issue

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:heart_eyes: **pass** : 37 / 44 (84.09%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/storage/rowset/column_reader.h|0|1|00.00%|[158]|
|:large_blue_circle:|src/storage/rowset/zone_map_index.h|0|1|00.00%|[101]|
|:large_blue_circle:|src/storage/lake/tablet_manager.cpp|12|17|70.59%|[278, 279, 539, 678, 958]|
|:large_blue_circle:|src/storage/rowset/ordinal_page_index.cpp|1|1|100.00%|[]|
|:large_blue_circle:|src/storage/tablet_schema.h|1|1|100.00%|[]|
|:large_blue_circle:|src/storage/rowset/segment.cpp|5|5|100.00%|[]|
|:large_blue_circle:|src/storage/rowset/zone_map_index.cpp|3|3|100.00%|[]|
|:large_blue_circle:|src/storage/rowset/bloom_filter_index_reader.h|2|2|100.00%|[]|
|:large_blue_circle:|src/storage/rowset/column_reader.cpp|3|3|100.00%|[]|
|:large_blue_circle:|src/storage/rowset/segment.h|2|2|100.00%|[]|
|:large_blue_circle:|src/storage/rowset/ordinal_page_index.h|2|2|100.00%|[]|
|:large_blue_circle:|src/storage/rowset/bitmap_index_reader.h|1|1|100.00%|[]|
|:large_blue_circle:|src/storage/rowset/bitmap_index_reader.cpp|1|1|100.00%|[]|
|:large_blue_circle:|src/storage/rowset/bloom_filter_index_reader.cpp|2|2|100.00%|[]|
|:large_blue_circle:|src/storage/lake/tablet.cpp|1|1|100.00%|[]|
|:large_blue_circle:|src/storage/lake/tablet_manager.h|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:heart_eyes: **pass** : 37 / 44 (84.09%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/storage/rowset/column_reader.h|0|1|00.00%|[158]|
|:large_blue_circle:|src/storage/rowset/zone_map_index.h|0|1|00.00%|[101]|
|:large_blue_circle:|src/storage/lake/tablet_manager.cpp|12|17|70.59%|[278, 279, 539, 678, 958]|
|:large_blue_circle:|src/storage/rowset/ordinal_page_index.cpp|1|1|100.00%|[]|
|:large_blue_circle:|src/storage/tablet_schema.h|1|1|100.00%|[]|
|:large_blue_circle:|src/storage/rowset/segment.cpp|5|5|100.00%|[]|
|:large_blue_circle:|src/storage/rowset/zone_map_index.cpp|3|3|100.00%|[]|
|:large_blue_circle:|src/storage/rowset/bloom_filter_index_reader.h|2|2|100.00%|[]|
|:large_blue_circle:|src/storage/rowset/column_reader.cpp|3|3|100.00%|[]|
|:large_blue_circle:|src/storage/rowset/segment.h|2|2|100.00%|[]|
|:large_blue_circle:|src/storage/rowset/ordinal_page_index.h|2|2|100.00%|[]|
|:large_blue_circle:|src/storage/rowset/bitmap_index_reader.h|1|1|100.00%|[]|
|:large_blue_circle:|src/storage/rowset/bitmap_index_reader.cpp|1|1|100.00%|[]|
|:large_blue_circle:|src/storage/rowset/bloom_filter_index_reader.cpp|2|2|100.00%|[]|
|:large_blue_circle:|src/storage/lake/tablet.cpp|1|1|100.00%|[]|
|:large_blue_circle:|src/storage/lake/tablet_manager.h|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:heart_eyes: **pass** : 37 / 44 (84.09%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/storage/rowset/column_reader.h|0|1|00.00%|[158]|
|:large_blue_circle:|src/storage/rowset/zone_map_index.h|0|1|00.00%|[101]|
|:large_blue_circle:|src/storage/lake/tablet_manager.cpp|12|17|70.59%|[278, 279, 539, 678, 958]|
|:large_blue_circle:|src/storage/rowset/ordinal_page_index.cpp|1|1|100.00%|[]|
|:large_blue_circle:|src/storage/tablet_schema.h|1|1|100.00%|[]|
|:large_blue_circle:|src/storage/rowset/segment.cpp|5|5|100.00%|[]|
|:large_blue_circle:|src/storage/rowset/zone_map_index.cpp|3|3|100.00%|[]|
|:large_blue_circle:|src/storage/rowset/bloom_filter_index_reader.h|2|2|100.00%|[]|
|:large_blue_circle:|src/storage/rowset/column_reader.cpp|3|3|100.00%|[]|
|:large_blue_circle:|src/storage/rowset/segment.h|2|2|100.00%|[]|
|:large_blue_circle:|src/storage/rowset/ordinal_page_index.h|2|2|100.00%|[]|
|:large_blue_circle:|src/storage/rowset/bitmap_index_reader.h|1|1|100.00%|[]|
|:large_blue_circle:|src/storage/rowset/bitmap_index_reader.cpp|1|1|100.00%|[]|
|:large_blue_circle:|src/storage/rowset/bloom_filter_index_reader.cpp|2|2|100.00%|[]|
|:large_blue_circle:|src/storage/lake/tablet.cpp|1|1|100.00%|[]|
|:large_blue_circle:|src/storage/lake/tablet_manager.h|1|1|100.00%|[]|

**Review by sduzh — APPROVED** [review]

**Pull request merged**
