### PR TITLE
[Refactor] Remove alter statement parser / analyzer deprecated code

### PR DESCRIPTION
**Pull request by HangyuanLiu**
## What type of PR is this：
- [ ] bugfix
- [ ] feature
- [ ] enhancement
- [x] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 347 / 436 (79.59%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/ast/AlterLoadErrorUrlClause.java|0|4|00.00%|[19, 20, 21, 25]|
|:large_blue_circle:|com/starrocks/sql/ast/RollupRenameClause.java|0|1|00.00%|[78]|
|:large_blue_circle:|com/starrocks/sql/ast/AddComputeNodeClause.java|0|2|00.00%|[9, 10]|
|:large_blue_circle:|com/starrocks/sql/ast/DropComputeNodeClause.java|0|2|00.00%|[10, 11]|
|:large_blue_circle:|com/starrocks/sql/ast/DropRollupClause.java|0|1|00.00%|[74]|
|:large_blue_circle:|com/starrocks/sql/ast/AstVisitor.java|7|22|31.82%|[140, 144, 148, 156, 160, 164, 168, 186, 214, 223, 227, 231, 235, 610, 614]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AlterTableStatementAnalyzer.java|18|36|50.00%|[355, 359, 377, 381, 384, 385, 394, 395, 403, 404, 405, 406, 407, 413, 414, 415, 416, 417]|
|:large_blue_circle:|com/starrocks/sql/ast/DecommissionBackendClause.java|3|5|60.00%|[20, 21]|
|:large_blue_circle:|com/starrocks/sql/ast/DropIndexClause.java|4|6|66.67%|[17, 27]|
|:large_blue_circle:|com/starrocks/sql/ast/AlterClause.java|4|6|66.67%|[21, 29]|
|:large_blue_circle:|com/starrocks/sql/ast/AlterTableClause.java|3|4|75.00%|[18]|
|:large_blue_circle:|com/starrocks/sql/ast/CreateIndexClause.java|7|9|77.78%|[22, 40]|
|:large_blue_circle:|com/starrocks/sql/ast/ColumnRenameClause.java|8|10|80.00%|[31, 41]|
|:large_blue_circle:|com/starrocks/sql/ast/AlterTableStmt.java|8|10|80.00%|[21, 22]|
|:large_blue_circle:|com/starrocks/sql/ast/DropColumnClause.java|5|6|83.33%|[29]|
|:large_blue_circle:|com/starrocks/sql/ast/AddColumnsClause.java|5|6|83.33%|[31]|
|:large_blue_circle:|com/starrocks/sql/ast/ReorderColumnsClause.java|5|6|83.33%|[30]|
|:large_blue_circle:|com/starrocks/sql/ast/FrontendClause.java|11|13|84.62%|[28, 45]|
|:large_blue_circle:|com/starrocks/sql/ast/TableRenameClause.java|6|7|85.71%|[27]|
|:large_blue_circle:|com/starrocks/sql/ast/DropPartitionClause.java|12|14|85.71%|[44, 49]|
|:large_blue_circle:|com/starrocks/sql/ast/BackendClause.java|7|8|87.50%|[34]|
|:large_blue_circle:|com/starrocks/sql/ast/ModifyColumnClause.java|7|8|87.50%|[38]|
|:large_blue_circle:|com/starrocks/sql/ast/AddColumnClause.java|7|8|87.50%|[39]|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|152|171|88.89%|[719, 720, 721, 722, 723, 724, 1285, 1297, 1338, 1339, 1340, 1345, 1346, 1347, 1366, 1489, 1490, 1491, 1557]|
|:large_blue_circle:|com/starrocks/sql/ast/PartitionRenameClause.java|8|9|88.89%|[31]|
|:large_blue_circle:|com/starrocks/sql/ast/ModifyTablePropertiesClause.java|9|10|90.00%|[38]|
|:large_blue_circle:|com/starrocks/sql/ast/AddPartitionClause.java|12|13|92.31%|[57]|
|:large_blue_circle:|com/starrocks/sql/ast/DropFollowerClause.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/AlterSystemStmt.java|6|6|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/AddFollowerClause.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/DropBackendClause.java|9|9|100.00%|[]|
|:large_blue_circle:|com/starrocks/system/SystemInfoService.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/DropObserverClause.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/AddBackendClause.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/AddObserverClause.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/AlterTableColumnClause.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/StatementPlanner.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/PrivilegeChecker.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/ReplacePartitionClause.java|6|6|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/AddRollupClause.java|1|1|100.00%|[]|

**Comment by HangyuanLiu** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 357 / 442 (80.77%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/ast/AlterLoadErrorUrlClause.java|0|4|00.00%|[19, 20, 21, 25]|
|:large_blue_circle:|com/starrocks/sql/ast/RollupRenameClause.java|0|1|00.00%|[78]|
|:large_blue_circle:|com/starrocks/sql/ast/AddComputeNodeClause.java|0|2|00.00%|[9, 10]|
|:large_blue_circle:|com/starrocks/sql/ast/DropComputeNodeClause.java|0|2|00.00%|[10, 11]|
|:large_blue_circle:|com/starrocks/sql/ast/DropRollupClause.java|0|1|00.00%|[74]|
|:large_blue_circle:|com/starrocks/sql/ast/AstVisitor.java|11|22|50.00%|[148, 152, 164, 172, 218, 227, 231, 235, 239, 636, 640]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AlterTableStatementAnalyzer.java|18|36|50.00%|[355, 359, 377, 381, 384, 385, 394, 395, 403, 404, 405, 406, 407, 413, 414, 415, 416, 417]|
|:large_blue_circle:|com/starrocks/sql/ast/DecommissionBackendClause.java|3|5|60.00%|[20, 21]|
|:large_blue_circle:|com/starrocks/sql/ast/DropIndexClause.java|4|6|66.67%|[17, 27]|
|:large_blue_circle:|com/starrocks/sql/ast/AlterClause.java|4|6|66.67%|[21, 29]|
|:large_blue_circle:|com/starrocks/sql/ast/AlterTableClause.java|3|4|75.00%|[18]|
|:large_blue_circle:|com/starrocks/sql/ast/CreateIndexClause.java|7|9|77.78%|[22, 40]|
|:large_blue_circle:|com/starrocks/sql/ast/ColumnRenameClause.java|8|10|80.00%|[31, 41]|
|:large_blue_circle:|com/starrocks/sql/ast/AlterTableStmt.java|8|10|80.00%|[21, 22]|
|:large_blue_circle:|com/starrocks/sql/ast/DropColumnClause.java|5|6|83.33%|[29]|
|:large_blue_circle:|com/starrocks/sql/ast/AddColumnsClause.java|5|6|83.33%|[31]|
|:large_blue_circle:|com/starrocks/sql/ast/ReorderColumnsClause.java|5|6|83.33%|[30]|
|:large_blue_circle:|com/starrocks/sql/ast/FrontendClause.java|11|13|84.62%|[28, 45]|
|:large_blue_circle:|com/starrocks/sql/ast/TableRenameClause.java|6|7|85.71%|[27]|
|:large_blue_circle:|com/starrocks/sql/ast/DropPartitionClause.java|12|14|85.71%|[44, 49]|
|:large_blue_circle:|com/starrocks/sql/ast/BackendClause.java|7|8|87.50%|[34]|
|:large_blue_circle:|com/starrocks/sql/ast/ModifyColumnClause.java|7|8|87.50%|[38]|
|:large_blue_circle:|com/starrocks/sql/ast/AddColumnClause.java|7|8|87.50%|[39]|
|:large_blue_circle:|com/starrocks/sql/ast/PartitionRenameClause.java|8|9|88.89%|[31]|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|160|179|89.39%|[724, 725, 726, 727, 728, 729, 1324, 1336, 1377, 1378, 1379, 1384, 1385, 1386, 1405, 1528, 1529, 1530, 1596]|
|:large_blue_circle:|com/starrocks/sql/ast/ModifyTablePropertiesClause.java|9|10|90.00%|[38]|
|:large_blue_circle:|com/starrocks/sql/ast/AddPartitionClause.java|12|13|92.31%|[57]|
|:large_blue_circle:|com/starrocks/sql/ast/DropFollowerClause.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/AlterSystemStmt.java|6|6|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/AddFollowerClause.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/DropBackendClause.java|9|9|100.00%|[]|
|:large_blue_circle:|com/starrocks/system/SystemInfoService.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/DropObserverClause.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/AddBackendClause.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/AddObserverClause.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/AlterTableColumnClause.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/StatementPlanner.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/PrivilegeChecker.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/ReplacePartitionClause.java|6|6|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/AddRollupClause.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 367 / 442 (83.03%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/ast/AlterLoadErrorUrlClause.java|0|4|00.00%|[19, 20, 21, 25]|
|:large_blue_circle:|com/starrocks/sql/ast/RollupRenameClause.java|0|1|00.00%|[78]|
|:large_blue_circle:|com/starrocks/sql/ast/AddComputeNodeClause.java|0|2|00.00%|[9, 10]|
|:large_blue_circle:|com/starrocks/sql/ast/DropComputeNodeClause.java|0|2|00.00%|[10, 11]|
|:large_blue_circle:|com/starrocks/sql/ast/AstVisitor.java|11|22|50.00%|[148, 152, 164, 172, 218, 227, 231, 235, 239, 636, 640]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AlterTableStatementAnalyzer.java|21|36|58.33%|[355, 359, 377, 381, 384, 385, 394, 395, 404, 405, 413, 414, 415, 416, 417]|
|:large_blue_circle:|com/starrocks/sql/ast/DecommissionBackendClause.java|3|5|60.00%|[20, 21]|
|:large_blue_circle:|com/starrocks/sql/ast/DropIndexClause.java|4|6|66.67%|[17, 27]|
|:large_blue_circle:|com/starrocks/sql/ast/AlterClause.java|4|6|66.67%|[21, 29]|
|:large_blue_circle:|com/starrocks/sql/ast/AlterTableClause.java|3|4|75.00%|[18]|
|:large_blue_circle:|com/starrocks/sql/ast/CreateIndexClause.java|7|9|77.78%|[22, 40]|
|:large_blue_circle:|com/starrocks/sql/ast/ColumnRenameClause.java|8|10|80.00%|[31, 41]|
|:large_blue_circle:|com/starrocks/sql/ast/AlterTableStmt.java|8|10|80.00%|[21, 22]|
|:large_blue_circle:|com/starrocks/sql/ast/DropColumnClause.java|5|6|83.33%|[29]|
|:large_blue_circle:|com/starrocks/sql/ast/AddColumnsClause.java|5|6|83.33%|[31]|
|:large_blue_circle:|com/starrocks/sql/ast/ReorderColumnsClause.java|5|6|83.33%|[30]|
|:large_blue_circle:|com/starrocks/sql/ast/FrontendClause.java|11|13|84.62%|[28, 45]|
|:large_blue_circle:|com/starrocks/sql/ast/TableRenameClause.java|6|7|85.71%|[27]|
|:large_blue_circle:|com/starrocks/sql/ast/DropPartitionClause.java|12|14|85.71%|[44, 49]|
|:large_blue_circle:|com/starrocks/sql/ast/BackendClause.java|7|8|87.50%|[34]|
|:large_blue_circle:|com/starrocks/sql/ast/ModifyColumnClause.java|7|8|87.50%|[38]|
|:large_blue_circle:|com/starrocks/sql/ast/AddColumnClause.java|7|8|87.50%|[39]|
|:large_blue_circle:|com/starrocks/sql/ast/PartitionRenameClause.java|8|9|88.89%|[31]|
|:large_blue_circle:|com/starrocks/sql/ast/ModifyTablePropertiesClause.java|9|10|90.00%|[38]|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|166|179|92.74%|[1324, 1336, 1377, 1378, 1379, 1384, 1385, 1386, 1405, 1528, 1529, 1530, 1596]|
|:large_blue_circle:|com/starrocks/sql/ast/AddPartitionClause.java|12|13|92.31%|[57]|
|:large_blue_circle:|com/starrocks/sql/ast/DropFollowerClause.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/AlterSystemStmt.java|6|6|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/AddFollowerClause.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/DropBackendClause.java|9|9|100.00%|[]|
|:large_blue_circle:|com/starrocks/system/SystemInfoService.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/DropObserverClause.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/AddBackendClause.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/AddObserverClause.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/AlterTableColumnClause.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/StatementPlanner.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/PrivilegeChecker.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/ReplacePartitionClause.java|6|6|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/AddRollupClause.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/DropRollupClause.java|1|1|100.00%|[]|

**Review by kangkaisen — APPROVED** [review]

**Review by Seaven — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by Youngwb — APPROVED** [review]

**Pull request merged**
