### PR TITLE
[Enhancement] External olap table support temp partition (#28389)

### PR DESCRIPTION
**Pull request by xiangguangyxg**
Fixes #issue

## What type of PR is this:
- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4

### CODE REVIEW

**Review by sduzh — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 8 / 9 (88.89%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/ExternalOlapTable.java|3|4|75.00%|[493]|
|:large_blue_circle:|com/starrocks/leader/LeaderImpl.java|5|5|100.00%|[]|

**Review by wyb — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 9 / 10 (90.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/ExternalOlapTable.java|3|4|75.00%|[493]|
|:large_blue_circle:|com/starrocks/leader/LeaderImpl.java|6|6|100.00%|[]|

**Review by sduzh — APPROVED** [review]

**Comment by xiangguangyxg** [comment]
run CI PIPELINE - BRANCH / FE UT (pull_request)

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 9 / 10 (90.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/ExternalOlapTable.java|3|4|75.00%|[493]|
|:large_blue_circle:|com/starrocks/leader/LeaderImpl.java|6|6|100.00%|[]|

**Pull request merged**
