### PR TITLE
[BugFix] Notify CoordinatorMonitor for metadata aliveStatus

### PR DESCRIPTION
**Pull request by ZiheLiu**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Problem Summary(Required) ：

From version 2.5, the FE leader syncs alive status of BE by a new filed `HeartbeatResponse.AliveStatus` metadata.

However, this new sync logic doesn't notify CoordinatorMonitor.

This modification is already in the branch-2.2/2.3/2.4 (#12954, #12955, #12958).

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

### CODE REVIEW

**Review by murphyatwork — APPROVED** [review]

**Comment by ZiheLiu** [comment]
run starrocks_fe_unittest

**Comment by ZiheLiu** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 9 / 9 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/system/ComputeNode.java|9|9|100.00%|[]|

**Comment by ZiheLiu** [comment]
run starrocks_admit_test

**Review by satanson — APPROVED** [review]

**Pull request merged**
