### PR TITLE
[BugFix] Add read lock to RoutineLoadManager to avoid log out of order

### LINKED ISSUE #5620: FE start failed with replay routine load job failed
### Steps to reproduce the behavior (Required)
create lots of routine load job on broken kafka env.

### Expected behavior (Required)
FE restart successfully.

### Real behavior (Required)
FE restart failed.

### StarRocks version (Required)
 - all

### PR DESCRIPTION
**Pull request by padmejin**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #5620

## Problem Summary(Required) ：

Add a read lock in RoutineLoadManager to protect idToRoutineLoadJob and dbToNameToRoutineLoadJob.

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 47 / 73 (64.38%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/load/routineload/RoutineLoadManager.java|47|73|64.38%|

**Comment by imay** [comment]
Could you explain why the bug will be be fixed after your changes

**Review by gengjun-git — APPROVED** [review]

**Comment by padmejin** [comment]
> Could you explain why the bug will be be fixed after your changes

https://github.com/StarRocks/starrocks/issues/5620

I have added more description in the issue above.

**Comment by imay** [comment]
> > Could you explain why the bug will be be fixed after your changes
> 
> 
> 
> https://github.com/StarRocks/starrocks/issues/5620
> 
> 
> 
> I have added more description in the issue above.

Great detailed explanation. I know the background now. I think the better way to fix it is that write the log first and apply secondly. And we can refactor this meta operation later.

**Comment by padmejin** [comment]
> > > Could you explain why the bug will be be fixed after your changes
> > 
> > 
> > #5620
> > I have added more description in the issue above.
> 
> Great detailed explanation. I know the background now. I think the better way to fix it is that write the log first and apply secondly. And we can refactor this meta operation later. And it is dangerous that someone move the log operation out of this object lock protection. Then you fix here will fail to avoid the problem. So I think we need a better way if we want a more stable product. Have you thought about the idea I mentioned above?

1. Adding a read lock is the most obvious way to me. It's always safer to ensure a data structure is only put to use after the whole modification is finished. Without a read lock, there is even a chance that the two inner data structures become mismatched.
2. There are a few lines of code between adding the new job to the map and writing the journal. If an exception occurs in these lines, there's no way to erase the journal.
3. I would like to change the order of writing the journal soon, but I think we should organize a discussion before committing since it's a huge change. People who modify this code later may not know we have written the journal first, leading to severe consequences such as adding some logic that could fail after the journal is written.

**Review by chaoyli — APPROVED** [review]

**Comment by padmejin** [comment]
@Mergifyio backport branch-2.3

**Comment by padmejin** [comment]
@Mergifyio backport branch-2.2 branch-2.1 branch-2.0

**Pull request merged**
