### PR TITLE
[BugFix] Fix column overflow in RowsetUpdateState and CompactionState

### LINKED ISSUE #33247: actual row size changed after compaction
### Real behavior (Required)
```
mysql> select * from users_10010_v4_high_v2 where user_id =892391026; ERROR 1064 (HY000): get_applied_rowsets failed, tablet updates is in error state: tablet:18849 actual row size changed after compaction 215171486 -> 186981271tablet:18849 #version:3 [1 2.1@2 2.1] #pending:0 backend:[10.201.2.188](http://10.201.2.188/)
```
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by decster**
Fixes #33247

When the compaction output file is too large and contains many rows, the resulting buffer containing all encoded pk in this segment file may be huge and overflow. This PR fixes this by changing `BinaryColumn<uint32>` to `BinaryColumn<int64>`, adding some checks for overflow, and refactoring some compaction memory logs.

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.2
  - [x] 3.1
  - [x] 3.0
  - [x] 2.5

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 8 / 18 (44.44%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/storage/rowset_update_state.cpp|0|1|00.00%|[208]|
|:large_blue_circle:|src/storage/update_compaction_state.cpp|2|6|33.33%|[130, 131, 132, 138]|
|:large_blue_circle:|src/storage/primary_key_encoder.cpp|3|8|37.50%|[336, 337, 338, 339, 340]|
|:large_blue_circle:|src/column/binary_column.cpp|3|3|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 9 / 19 (47.37%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/storage/rowset_update_state.cpp|0|1|00.00%|[208]|
|:large_blue_circle:|src/storage/update_compaction_state.cpp|2|6|33.33%|[130, 131, 132, 138]|
|:large_blue_circle:|src/storage/primary_key_encoder.cpp|4|9|44.44%|[336, 337, 338, 339, 340]|
|:large_blue_circle:|src/column/binary_column.cpp|3|3|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 91 / 154 (59.09%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/storage/update_compaction_state.cpp|1|7|14.29%|[130, 131, 132, 138, 139, 140]|
|:large_blue_circle:|src/storage/primary_key_encoder.cpp|86|143|60.14%|[336, 337, 339, 516, 517, 518, 519, 520, 521, 522, 525, 528, 529, 530, 531, 532, 534, 535, 538, 571, 572, 573, 574, 575, 576, 577, 578, 580, 653, 654, 655, 656, 657, 671, 672, 673, 674, 675, 677, 678, 679, 680, 681, 689, 690, 691, 692, 693, 695, 696, 697, 698, 699, 701, 702, 719, 720]|
|:large_blue_circle:|src/storage/lake/update_compaction_state.cpp|1|1|100.00%|[]|
|:large_blue_circle:|src/column/binary_column.cpp|1|1|100.00%|[]|
|:large_blue_circle:|src/storage/lake/rowset_update_state.cpp|1|1|100.00%|[]|
|:large_blue_circle:|src/storage/rowset_update_state.cpp|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 91 / 154 (59.09%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/storage/update_compaction_state.cpp|1|7|14.29%|[130, 131, 132, 138, 139, 140]|
|:large_blue_circle:|src/storage/primary_key_encoder.cpp|86|143|60.14%|[336, 337, 339, 516, 517, 518, 519, 520, 521, 522, 525, 528, 529, 530, 531, 532, 534, 535, 538, 571, 572, 573, 574, 575, 576, 577, 578, 580, 653, 654, 655, 656, 657, 671, 672, 673, 674, 675, 677, 678, 679, 680, 681, 689, 690, 691, 692, 693, 695, 696, 697, 698, 699, 701, 702, 719, 720]|
|:large_blue_circle:|src/storage/lake/update_compaction_state.cpp|1|1|100.00%|[]|
|:large_blue_circle:|src/column/binary_column.cpp|1|1|100.00%|[]|
|:large_blue_circle:|src/storage/lake/rowset_update_state.cpp|1|1|100.00%|[]|
|:large_blue_circle:|src/storage/rowset_update_state.cpp|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 91 / 154 (59.09%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/storage/update_compaction_state.cpp|1|7|14.29%|[130, 131, 132, 138, 139, 140]|
|:large_blue_circle:|src/storage/primary_key_encoder.cpp|86|143|60.14%|[336, 337, 339, 516, 517, 518, 519, 520, 521, 522, 525, 528, 529, 530, 531, 532, 534, 535, 538, 571, 572, 573, 574, 575, 576, 577, 578, 580, 653, 654, 655, 656, 657, 671, 672, 673, 674, 675, 677, 678, 679, 680, 681, 689, 690, 691, 692, 693, 695, 696, 697, 698, 699, 701, 702, 719, 720]|
|:large_blue_circle:|src/storage/lake/update_compaction_state.cpp|1|1|100.00%|[]|
|:large_blue_circle:|src/column/binary_column.cpp|1|1|100.00%|[]|
|:large_blue_circle:|src/storage/lake/rowset_update_state.cpp|1|1|100.00%|[]|
|:large_blue_circle:|src/storage/rowset_update_state.cpp|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 109 / 172 (63.37%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/storage/update_compaction_state.cpp|1|7|14.29%|[130, 131, 132, 138, 139, 140]|
|:large_blue_circle:|src/storage/primary_key_encoder.cpp|86|143|60.14%|[336, 337, 339, 516, 517, 518, 519, 520, 521, 522, 525, 528, 529, 530, 531, 532, 534, 535, 538, 571, 572, 573, 574, 575, 576, 577, 578, 580, 653, 654, 655, 656, 657, 671, 672, 673, 674, 675, 677, 678, 679, 680, 681, 689, 690, 691, 692, 693, 695, 696, 697, 698, 699, 701, 702, 719, 720]|
|:large_blue_circle:|src/storage/lake/update_compaction_state.cpp|1|1|100.00%|[]|
|:large_blue_circle:|src/column/binary_column.cpp|1|1|100.00%|[]|
|:large_blue_circle:|src/storage/tablet_updates.cpp|13|13|100.00%|[]|
|:large_blue_circle:|src/storage/lake/rowset_update_state.cpp|1|1|100.00%|[]|
|:large_blue_circle:|src/storage/rowset_update_state.cpp|1|1|100.00%|[]|
|:large_blue_circle:|src/storage/persistent_index.cpp|5|5|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 109 / 172 (63.37%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/storage/update_compaction_state.cpp|1|7|14.29%|[130, 131, 132, 138, 139, 140]|
|:large_blue_circle:|src/storage/primary_key_encoder.cpp|86|143|60.14%|[336, 337, 339, 516, 517, 518, 519, 520, 521, 522, 525, 528, 529, 530, 531, 532, 534, 535, 538, 571, 572, 573, 574, 575, 576, 577, 578, 580, 653, 654, 655, 656, 657, 671, 672, 673, 674, 675, 677, 678, 679, 680, 681, 689, 690, 691, 692, 693, 695, 696, 697, 698, 699, 701, 702, 719, 720]|
|:large_blue_circle:|src/storage/lake/update_compaction_state.cpp|1|1|100.00%|[]|
|:large_blue_circle:|src/column/binary_column.cpp|1|1|100.00%|[]|
|:large_blue_circle:|src/storage/tablet_updates.cpp|13|13|100.00%|[]|
|:large_blue_circle:|src/storage/lake/rowset_update_state.cpp|1|1|100.00%|[]|
|:large_blue_circle:|src/storage/rowset_update_state.cpp|1|1|100.00%|[]|
|:large_blue_circle:|src/storage/persistent_index.cpp|5|5|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 98 / 166 (59.04%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|be/src/storage/update_compaction_state.cpp|1|7|14.29%|[130, 131, 132, 138, 139, 140]|
|:large_blue_circle:|be/src/storage/primary_key_encoder.cpp|89|151|58.94%|[516, 517, 518, 519, 520, 521, 522, 525, 528, 529, 530, 531, 532, 534, 535, 538, 571, 572, 573, 574, 575, 576, 577, 578, 580, 652, 653, 654, 655, 656, 657, 658, 664, 670, 671, 672, 673, 674, 675, 676, 677, 678, 679, 680, 681, 682, 689, 690, 691, 692, 693, 694, 695, 696, 697, 698, 699, 700, 701, 702, 719, 720]|
|:large_blue_circle:|be/src/storage/persistent_index.cpp|2|2|100.00%|[]|
|:large_blue_circle:|be/src/storage/lake/rowset_update_state.cpp|1|1|100.00%|[]|
|:large_blue_circle:|be/src/storage/lake/update_compaction_state.cpp|1|1|100.00%|[]|
|:large_blue_circle:|be/src/storage/primary_index.cpp|2|2|100.00%|[]|
|:large_blue_circle:|be/src/column/binary_column.cpp|1|1|100.00%|[]|
|:large_blue_circle:|be/src/storage/rowset_update_state.cpp|1|1|100.00%|[]|

**Review by chaoyli — APPROVED** [review]

**Review by luohaha — APPROVED** [review]

**Review by sevev — APPROVED** [review]

**Comment by luohaha** [comment]
https://github.com/Mergifyio backport branch-3.1-cs

**Pull request merged**
