### PR TITLE
[BugFix] Decimal cast to string on FE

### LINKED ISSUE #27240: [Bug][Behavior Change] The result of constant double/decimal cast to string change
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
2. INSERT INTO '....'
3. SELECT  '....'

### FIX PR
https://github.com/StarRocks/starrocks/pull/27070
https://github.com/StarRocks/starrocks/pull/27235

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - 2.4, 2.5, 3.0, 3.1

### PR DESCRIPTION
**Pull request by Seaven**
Fixes #27240

Fix decimal cast to string will lose zero on FE, it's different with BE
like:
```
MySQL td>  insert into ds1 values (7, cast(7.00 as double), cast(7.0 as decimal(27, 9)));
Query OK, 1 row affected
Time: 0.269s
MySQL td>  insert into ds1 select  8, cast(8.00 as double), cast(8.0 as decimal(27, 9));
Query OK, 1 row affected
Time: 0.048s
MySQL td> select * from dd1; -- (int, double, decimal(27,9))
+----+-----+-------------+
| v1 | v2  | v3          |
+----+-----+-------------+
| 2  | 2.0 | 2.000000000 |
| 1  | 1.0 | 1.000000000 |
+----+-----+-------------+
2 rows in set
Time: 0.022s
MySQL td> insert into ds1 select * from dd1;
Query OK, 2 rows affected
Time: 2.825s
MySQL td>
MySQL td> select * from ds1;
+----+-----+-------------+
| v1 | v2  | v3          |
+----+-----+-------------+
| 2  | 2   | 2.000000000 |
| 1  | 1   | 1.000000000 |
| 7  | 7.0 | 7.0         |
| 8  | 8   | 8.000000000 |
+----+-----+-------------+
4 rows in set
Time: 0.024s
MySQL td>

```

## What type of PR is this:
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [x] 3.0
  - [x] 2.5
  - [ ] 2.4

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 5 / 5 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/scalar/ConstantOperator.java|5|5|100.00%|[]|

**Review by packy92 — APPROVED** [review]

**Review by kangkaisen — APPROVED** [review]

**Review by liuyehcf — APPROVED** [review]

**Comment by Seaven** [comment]
@mergify rebase

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 5 / 5 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/scalar/ConstantOperator.java|5|5|100.00%|[]|

**Pull request merged**
