### PR TITLE
[BugFix] ALTER MATERIALIZED VIEW statement will change

### LINKED ISSUE #11632: ALTER MATERIALIZED VIEW statement will change
### Steps to reproduce the behavior (Required)
1.
CREATE TABLE goods(
    item_id1          INT,
    item_name         STRING,
    price             FLOAT
) DISTRIBUTED BY HASH(item_id1)
PROPERTIES (
 "replication_num" = "1"
);

CREATE TABLE order_list(
    order_id          INT,
    client_id         INT,
    item_id2          INT,
    order_date        DATE
) DISTRIBUTED BY HASH(order_id)
PROPERTIES (
 "replication_num" = "1"
);

2.
CREATE MATERIALIZED VIEW order_mv
DISTRIBUTED BY HASH(`order_id`) BUCKETS 12
REFRESH ASYNC START('2022-09-26 11:03:00') EVERY (interval 1 day)
AS SELECT
    order_list.order_id,
    sum(goods.price) as total
FROM order_list INNER JOIN goods ON goods.item_id1 = order_list.item_id2
GROUP BY order_id;

3.
图片

4.
ALTER MATERIALIZED VIEW order_mv REFRESH ASYNC EVERY(INTERVAL 2 DAY);

5.
MySQL [test]> show create table order_mv;
CREATE MATERIALIZED VIEW order_mv
DISTRIBUTED BY HASH(order_id) BUCKETS 12
REFRESH ASYNC START('2022-09-26 11:09:23') EVERY (interval 2 day)
AS SELECT
order_list.order_id,
sum(goods.price) as total
FROM order_list INNER JOIN goods ON goods.item_id1 = order_list.item_id2
GROUP BY order_id;

### Expected behavior (Required)
MySQL [test]> show create table order_mv;
CREATE MATERIALIZED VIEW order_mv
DISTRIBUTED BY HASH(order_id) BUCKETS 12
REFRESH ASYNC START('2022-09-26 11:03:00') EVERY (interval 2 day)
AS SELECT
order_list.order_id,
sum(goods.price) as total
FROM order_list INNER JOIN goods ON goods.item_id1 = order_list.item_id2
GROUP BY order_id;

### Real behavior (Required)
MySQL [test]> show create table order_mv;
CREATE MATERIALIZED VIEW order_mv
DISTRIBUTED BY HASH(order_id) BUCKETS 12
REFRESH ASYNC START('2022-09-26 11:09:23') EVERY (interval 2 day)
AS SELECT
order_list.order_id,
sum(goods.price) as total
FROM order_list INNER JOIN goods ON goods.item_id1 = order_list.item_id2
GROUP BY order_id;

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - 2.4

### PR DESCRIPTION
**Pull request by blackstar-baba**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #11632

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by blackstar-baba** [comment]
we don't need set next schedule time, if start time less than current time when creating mv, task will run once immediately.

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 8 / 10 (80.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/alter/Alter.java|2|3|66.67%|[295]|
|:large_blue_circle:|com/starrocks/scheduler/TaskBuilder.java|6|7|85.71%|[87]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 27 / 29 (93.10%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/alter/Alter.java|2|3|66.67%|[295]|
|:large_blue_circle:|com/starrocks/scheduler/TaskBuilder.java|9|10|90.00%|[87]|
|:large_blue_circle:|com/starrocks/common/util/TimeUtils.java|16|16|100.00%|[]|

**Comment by wanpengfei-git** [comment]
starrocks_be_unittest succeeded.

**Comment by wanpengfei-git** [comment]
starrocks_be_unittest succeeded.

**Comment by blackstar-baba** [comment]
redirect to new pr：https://github.com/StarRocks/starrocks/pull/12590

**Pull request closed without merging**
