### PR TITLE
[Feature] Add CachingMetastoreConf and CachingRemoteFileConf classes

### PR DESCRIPTION
**Pull request by stephen-shelby**
## What type of PR is this：
- [ ] BugFix
- [x] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #
https://github.com/StarRocks/starrocks/issues/11349

## Problem Summary(Required) ：

Add some config classes to construct HiveMetastoreOperations and RemoteFileOperations

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by stephen-shelby** [comment]
run starrocks_fe_unittest

**Comment by stephen-shelby** [comment]
run starrocks_fe_unittest

**Comment by stephen-shelby** [comment]
run starrocks_fe_unittest

**Comment by stephen-shelby** [comment]
run starrocks_fe_unittest

**Review by gengjun-git — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 3 / 34 (08.82%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/external/hive/CachingHiveMetastoreConf.java|0|16|00.00%|[12, 13, 14, 18, 19, 20, 21, 22, 23, 25, 28, 32, 36, 40, 44, 48]|
|:large_blue_circle:|com/starrocks/external/CachingRemoteFileConf.java|0|15|00.00%|[13, 14, 16, 17, 18, 19, 20, 21, 22, 23, 26, 30, 34, 38, 42]|
|:large_blue_circle:|com/starrocks/common/Config.java|3|3|100.00%|[]|

**Pull request merged**
