### PR TITLE
[BugFix] fix mv rewrite bug with partition prune

### LINKED ISSUE #14641: mv rewrite failed because of partition prune
### Steps to reproduce the behavior (Required)
1. CREATE TABLE

CREATE TABLE `test_base_part` (
  `c1` int(11) NULL COMMENT "",
  `c2` bigint(20) NULL COMMENT "",
  `c3` bigint(20) NULL COMMENT "",
  `c4` bigint(20) NULL COMMENT ""
) ENGINE=OLAP
DUPLICATE KEY(`c1`, `c2`, `c3`)
COMMENT "OLAP"
PARTITION BY RANGE(`c3`)
(PARTITION p1 VALUES [("-9223372036854775808"), ("100")),
PARTITION p2 VALUES [("100"), ("200")),
PARTITION p3 VALUES [("200"), ("1000")),
PARTITION p4 VALUES [("1000"), ("2000")),
PARTITION p5 VALUES [("2000"), ("3000")))
DISTRIBUTED BY HASH(`c1`) BUCKETS 6
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"storage_format" = "DEFAULT",
"enable_persistent_index" = "false",
"compression" = "LZ4"
);

create materialized view partial_mv_6
partition by c3
distributed by hash(c1) as
select c1, c3, c2 from test_base_part where c3 < 2000;

2. query
select c1, c3, c2 from test_base_part where c3 < 1000;

### Expected behavior (Required)
select c1, c3, c2 from partial_mv_6 where c3 < 1000;

### Real behavior (Required)

the rewritten result is 
select c1, c3, c2 from partial_mv_6
union
select c1, c3, c2 from test_base_part.where c3 >= 2000;

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by ABingHuang**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #14641

## Problem Summary(Required) ：

fix mv rewrite bug with partition prune
## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 77 / 87 (88.51%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/MvUtils.java|43|50|86.00%|[403, 409, 417, 418, 419, 421, 422]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java|32|35|91.43%|[492, 511, 523]|
|:large_blue_circle:|com/starrocks/sql/optimizer/MaterializedViewOptimizer.java|2|2|100.00%|[]|

**Comment by ABingHuang** [comment]
run starrocks_admit_test

**Review by kangkaisen — APPROVED** [review]

**Review by Youngwb — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
