### PR TITLE
[BugFix] report error when partition id not found

### PR DESCRIPTION
**Pull request by dirtysalt**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

There is no specific issue relatd. However in some test cases, I find this bug does happen. 

The root cause of this bug is plan inconsistency, we have to fix it from FE side.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 2.5
  - [x] 2.4
  - [x] 2.3
  - [x] 2.2

### CODE REVIEW

**Review by DorianZheng — APPROVED** [review]

**Review by stdpain — APPROVED** [review]

**Review by satanson — APPROVED** [review]

**Comment by dirtysalt** [comment]
@MergifyIO backport branch-2.5

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by dirtysalt** [comment]
@MergifyIO backport branch-2.4

**Comment by dirtysalt** [comment]
@MergifyIO backport branch-2.3

**Comment by dirtysalt** [comment]
@MergifyIO backport branch-2.2

**Pull request merged**
