### PR TITLE
[BugFix] Fix materialized view refresh error when base table partition value has MAXVALUE

### LINKED ISSUE #12735: [Materialized View] Refresh error when base table partition has MAXVLAUE
### Steps to reproduce the behavior (Required)
1.  create table 
```
CREATE TABLE `lineitem_par_maxvalue` (
  `l_orderkey` int(11) NOT NULL COMMENT "",
  `l_partkey` int(11) NOT NULL COMMENT "",
  `l_suppkey` int(11) NOT NULL COMMENT "",
  `l_linenumber` int(11) NOT NULL COMMENT "",
  `l_quantity` decimal64(15, 2) NOT NULL COMMENT "",
  `l_extendedprice` decimal64(15, 2) NOT NULL COMMENT "",
  `l_discount` decimal64(15, 2) NOT NULL COMMENT "",
  `l_tax` decimal64(15, 2) NOT NULL COMMENT "",
  `l_returnflag` char(1) NOT NULL COMMENT "",
  `l_linestatus` char(1) NOT NULL COMMENT "",
  `l_shipdate` date NOT NULL COMMENT "",
  `l_commitdate` date NOT NULL COMMENT "",
  `l_receiptdate` date NOT NULL COMMENT "",
  `l_shipinstruct` char(25) NOT NULL COMMENT "",
  `l_shipmode` char(10) NOT NULL COMMENT "",
  `l_comment` varchar(44) NOT NULL COMMENT ""
) ENGINE=OLAP
DUPLICATE KEY(`l_orderkey`)
COMMENT "OLAP"
PARTITION BY RANGE(`l_shipdate`)
(PARTITION p1992 VALUES [('1992-01-01'), ('1993-01-01')),
PARTITION p1993 VALUES [('1993-01-01'), ('1994-01-01')),
PARTITION p1994 VALUES [('1994-01-01'), ('1995-01-01')),
PARTITION p1995 VALUES [('1995-01-01'), ('1996-01-01')),
PARTITION p1996 VALUES [('1996-01-01'), ('1997-01-01')),
PARTITION p1997 VALUES [('1997-01-01'), ('1998-01-01')),
PARTITION p1998 VALUES [('1998-01-01'), (MAXVALUE)))
DISTRIBUTED BY HASH(`l_orderkey`) BUCKETS 48
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"storage_format" = "DEFAULT",
"enable_persistent_index" = "false",
"compression" = "LZ4"
);
```

2. create mv
```
CREATE MATERIALIZED VIEW `lineitem_par_maxvalue_mv`
COMMENT "MATERIALIZED_VIEW"
PARTITION BY (date_trunc('month', `l_shipdate`))
DISTRIBUTED BY HASH(`l_orderkey`) BUCKETS 10
REFRESH MANUAL
PROPERTIES (
"replication_num" = "1",
"storage_medium" = "HDD"
)
AS SELECT `lineitem_par_maxvalue`.`l_shipdate`, `lineitem_par_maxvalue`.`l_orderkey`
FROM `lineitem_par_maxvalue`;
```

3. refresh
```
refresh materialized view lineitem_par_maxvalue_mv;
```

### Expected behavior (Required)
refresh nomal

### Real behavior (Required)
image

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by Youngwb**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #12735 

## Problem Summary(Required) ：

materialized view need to special handling MAXVALUE  partition value

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 10 / 12 (83.33%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/common/SyncPartitionUtils.java|10|12|83.33%|[93, 94]|

**Comment by wanpengfei-git** [comment]
starrocks_be_unittest succeeded.

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 10 / 12 (83.33%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/common/SyncPartitionUtils.java|10|12|83.33%|[99, 100]|

**Review by Astralidea — APPROVED** [review]

**Review by gengjun-git — APPROVED** [review]

**Comment by Youngwb** [comment]
run starrocks_admit_test

**Comment by Youngwb** [comment]
@Mergify backport branch-2.4

**Pull request merged**
