### PR TITLE
[Enhancement] Memory pool for orc reader to detect bad alloc

### PR DESCRIPTION
**Pull request by letian-jiang**
ORC default memory pool returns nullptr on failure. ORC reader does not check whether the malloc is successful or not.

This PR provides a memory pool that throws `std::bad_alloc` on malloc failure. The exception would be handled by the caller.

## What type of PR is this:
- [x] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [x] 3.0
  - [ ] 2.5
  - [ ] 2.4

### CODE REVIEW

**Comment by DorianZheng** [comment]
let our malloc to catch the null pointer

**Comment by trueeyu** [comment]
Malloc will not return nullptr on Version of 2.4+, if `is_catched` not set, This maybe not the real reason

**Review by trueeyu — APPROVED** [review]

**Comment by trueeyu** [comment]
```
W0530 15:38:41.147928 2800253 mem_hook.cpp:266] large memory alloc: 15739939247947692663 bytes, stack:
    @          0x4f6e1ab  malloc
    @          0x6ec1248  orc::DataBuffer<>::reserve()
    @          0x6ec0e92  orc::DataBuffer<>::resize()
    @          0x6eb4d44  orc::StringDirectColumnReader::next()
    @          0x6eb2688  orc::StructColumnReader::next()
    @          0x6e839cb  orc::RowReaderImpl::next()
    @          0x462cdbe  starrocks::OrcChunkReader::read_next()
    @          0x56c7c17  starrocks::HdfsOrcScanner::do_get_next()
    @          0x56bf2ba  starrocks::HdfsScanner::get_next()
    @          0x562d187  starrocks::connector::HiveDataSource::get_next()
    @          0x30ff1dd  starrocks::pipeline::ConnectorChunkSource::_read_chunk()
    @          0x33a49ec  starrocks::pipeline::ChunkSource::buffer_next_batch_chunks_blocking()
    @          0x30fc761  _ZZN9starrocks8pipeline12ScanOperator18_trigger_next_scanEPNS_12RuntimeStateEiENKUlvE_clEv
    @          0x3103cbe  starrocks::workgroup::ScanExecutor::worker_thread()
    @          0x506b022  starrocks::ThreadPool::dispatch_thread()
    @          0x5065b1a  starrocks::Thread::supervise_thread()
    @     0x7fc2979a31ca  start_thread
    @     0x7fc296e80e73  __GI___clone
    @              (nil)  (unknown)
```

**Review by dirtysalt — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by letian-jiang** [comment]
https://github.com/Mergifyio backport branch-2.5

**Pull request merged**
