### PR TITLE
[BugFix] Fix bug copyWithGson with list partition

### LINKED ISSUE #17534: List partition meta problem
### Steps to reproduce the behavior (Required)
1. CREATE TABLE t_recharge_detail(
    id bigint not null ,
    user_id  bigint not null ,
    recharge_money decimal(32,2) , 
    province varchar(20) not null,
    dt varchar(20) not null
) ENGINE=OLAP
DUPLICATE KEY(id)
PARTITION BY LIST (dt,province) (
   PARTITION p1 VALUES IN (("2022-04-01", "beijing")),
   PARTITION p2 VALUES IN (("2022-04-01", "shanghai"))
)
DISTRIBUTED BY HASH(`id`) BUCKETS 10 
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false"
);
2.select * from t_recharge_detail;

### Expected behavior (Required)
Success.
### Real behavior (Required)
2023-02-08 14:12:33,921 WARN (starrocks-mysql-nio-pool-0|150) [DeepCopy.copyWithGson():104] failed to copy object.
com.google.gson.JsonParseException: cannot deserialize class com.starrocks.catalog.PartitionInfo because it does not define a field named clazz
	at com.starrocks.persist.gson.RuntimeTypeAdapterFactory$1.read(RuntimeTypeAdapterFactory.java:371) ~[classes/:?]
	at com.google.gson.TypeAdapter$1.read(TypeAdapter.java:199) ~[gson-2.8.9.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131) ~[gson-2.8.9.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222) ~[gson-2.8.9.jar:?]
	at com.starrocks.persist.gson.GsonUtils$ProcessHookTypeAdapterFactory$1.read(GsonUtils.java:535) ~[classes/:?]
	at com.google.gson.Gson.fromJson(Gson.java:963) ~[gson-2.8.9.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:928) ~[gson-2.8.9.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:877) ~[gson-2.8.9.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:848) ~[gson-2.8.9.jar:?]
	at com.starrocks.common.io.DeepCopy.copyWithGson(DeepCopy.java:102) ~[classes/:?]
	at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.resolveTableRef(QueryAnalyzer.java:282) ~[classes/:?]
	at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.visitSelect(QueryAnalyzer.java:184) ~[classes/:?]
	at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.visitSelect(QueryAnalyzer.java:101) ~[classes/:?]
	at com.starrocks.sql.ast.SelectRelation.accept(SelectRelation.java:225) ~[classes/:?]
	at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.process(QueryAnalyzer.java:106) ~[classes/:?]
	at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.visitQueryRelation(QueryAnalyzer.java:124) ~[classes/:?]
	at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.visitQueryStatement(QueryAnalyzer.java:118) ~[classes/:?]
	at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.visitQueryStatement(QueryAnalyzer.java:101) ~[classes/:?]
	at com.starrocks.sql.ast.QueryStatement.accept(QueryStatement.java:48) ~[classes/:?]
	at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.process(QueryAnalyzer.java:106) ~[classes/:?]
	at com.starrocks.sql.analyzer.QueryAnalyzer.analyze(QueryAnalyzer.java:94) ~[classes/:?]
	at com.starrocks.sql.analyzer.Analyzer$AnalyzerVisitor.visitQueryStatement(Analyzer.java:344) ~[classes/:?]
	at com.starrocks.sql.analyzer.Analyzer$AnalyzerVisitor.visitQueryStatement(Analyzer.java:134) ~[classes/:?]
	at com.starrocks.sql.ast.QueryStatement.accept(QueryStatement.java:48) ~[classes/:?]
	at com.starrocks.sql.ast.AstVisitor.visit(AstVisitor.java:55) ~[classes/:?]
	at com.starrocks.sql.analyzer.Analyzer$AnalyzerVisitor.analyze(Analyzer.java:136) ~[classes/:?]
	at com.starrocks.sql.analyzer.Analyzer.analyze(Analyzer.java:131) ~[classes/:?]
	at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:70) ~[classes/:?]
	at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:50) ~[classes/:?]
	at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:391) ~[classes/:?]
	at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:337) ~[classes/:?]
	at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:454) ~[classes/:?]
	at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:712) ~[classes/:?]
	at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:68) ~[classes/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_202]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_202]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
2023-02-08 14:12:33,928 WARN (starrocks-mysql-nio-pool-0|150) [StmtExecutor.execute():542] execute Exception, sql select * from t_recharge_detail
java.lang.NullPointerException: null
	at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.visitTable(QueryAnalyzer.java:314) ~[classes/:?]
	at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.visitTable(QueryAnalyzer.java:101) ~[classes/:?]
	at com.starrocks.sql.ast.TableRelation.accept(TableRelation.java:136) ~[classes/:?]
	at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.process(QueryAnalyzer.java:106) ~[classes/:?]
	at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.visitSelect(QueryAnalyzer.java:189) ~[classes/:?]
	at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.visitSelect(QueryAnalyzer.java:101) ~[classes/:?]
	at com.starrocks.sql.ast.SelectRelation.accept(SelectRelation.java:225) ~[classes/:?]
	at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.process(QueryAnalyzer.java:106) ~[classes/:?]
	at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.visitQueryRelation(QueryAnalyzer.java:124) ~[classes/:?]
	at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.visitQueryStatement(QueryAnalyzer.java:118) ~[classes/:?]
	at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.visitQueryStatement(QueryAnalyzer.java:101) ~[classes/:?]
	at com.starrocks.sql.ast.QueryStatement.accept(QueryStatement.java:48) ~[classes/:?]
	at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.process(QueryAnalyzer.java:106) ~[classes/:?]
	at com.starrocks.sql.analyzer.QueryAnalyzer.analyze(QueryAnalyzer.java:94) ~[classes/:?]
	at com.starrocks.sql.analyzer.Analyzer$AnalyzerVisitor.visitQueryStatement(Analyzer.java:344) ~[classes/:?]
	at com.starrocks.sql.analyzer.Analyzer$AnalyzerVisitor.visitQueryStatement(Analyzer.java:134) ~[classes/:?]
	at com.starrocks.sql.ast.QueryStatement.accept(QueryStatement.java:48) ~[classes/:?]
	at com.starrocks.sql.ast.AstVisitor.visit(AstVisitor.java:55) ~[classes/:?]
	at com.starrocks.sql.analyzer.Analyzer$AnalyzerVisitor.analyze(Analyzer.java:136) ~[classes/:?]
	at com.starrocks.sql.analyzer.Analyzer.analyze(Analyzer.java:131) ~[classes/:?]
	at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:70) ~[classes/:?]
	at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:50) ~[classes/:?]
	at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:391) ~[classes/:?]
	at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:337) ~[classes/:?]
	at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:454) ~[classes/:?]
	at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:712) ~[classes/:?]
	at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:68) ~[classes/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_202]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_202]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
main

### PR DESCRIPTION
**Pull request by Astralidea**
Signed-off-by: Astralidea <astralidea@163.com>

## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #17534

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/persist/gson/GsonUtils.java|1|1|100.00%|[]|

**Review by ABingHuang — APPROVED** [review]
LGTM

**Review by gengjun-git — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by Astralidea** [comment]
run starrocks_admit_test

**Pull request merged**
