### PR TITLE
[BugFix] Not showing password on show create JDBC catalog

### LINKED ISSUE #27976: When displaying the specific information of resource and catalog, the sensitive password information is not hidden
### Steps to reproduce the behavior (Required)
SHOW CREATE CATALOG  
SHOW RESOURCES

### Expected behavior (Required)
When displaying the specific information of resource and catalog, the sensitive password information is not hidden
### Real behavior (Required)
the sensitive password information is  hidden
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
SR3.X

### PR DESCRIPTION
**Pull request by letian-jiang**
Fixes #27976

## What type of PR is this:
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [x] 3.0
  - [x] 2.5
  - [ ] 2.4

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 3 / 3 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/credential/CloudCredentialUtil.java|3|3|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/credential/CloudCredentialUtil.java|1|1|100.00%|[]|

**Review by Smith-Cruise — APPROVED** [review]

**Review by stephen-shelby — APPROVED** [review]

**Review by DorianZheng — APPROVED** [review]
LGTM

**Review by dirtysalt — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
