### PR TITLE
[Refactor] Remove LakeServiceClient

### PR DESCRIPTION
**Pull request by sduzh**
LakeServiceClient was mainly designed to retry on errors, but the brpc-java lib can retry itself now.

## What type of PR is this：
- [ ] bug
- [ ] feature
- [ ] enhancement
- [x] refactor
- [ ] others

### CODE REVIEW

**Comment by sduzh** [comment]
run starrocks_admit_test

**Comment by sduzh** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 16 / 38 (42.11%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/lake/compaction/CompactionDispatchDaemon.java|0|5|00.00%|[123, 150, 151, 152, 153]|
|:large_blue_circle:|com/starrocks/transaction/LakeTableTxnStateListener.java|0|3|00.00%|[149, 150, 151]|
|:large_blue_circle:|com/starrocks/lake/DeleteLakeTableTask.java|0|1|00.00%|[63]|
|:large_blue_circle:|com/starrocks/transaction/PublishVersionDaemon.java|0|3|00.00%|[342, 343, 346]|
|:large_blue_circle:|com/starrocks/rpc/BrpcProxy.java|3|7|42.86%|[38, 42, 50, 76]|
|:large_blue_circle:|com/starrocks/rpc/BackendServiceClient.java|4|8|50.00%|[85, 163, 197, 211]|
|:large_blue_circle:|com/starrocks/lake/ShardDeleter.java|2|3|66.67%|[83]|
|:large_blue_circle:|com/starrocks/catalog/TabletStatMgr.java|4|5|80.00%|[260]|
|:large_blue_circle:|com/starrocks/lake/delete/LakeDeleteJob.java|3|3|100.00%|[]|

**Review by imay — APPROVED** [review]

**Review by wyb — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Pull request merged**
