### PR TITLE
[Refactor] Support RoutineLoadAlter Statement in new Parser and Analyzer

### LINKED ISSUE #7949: New Parser and Analyzer support RoutineLoad-related statements （Challenging）
# Required work and output

1.  Use antlr4 to complete parse statements. The generated statement must follow the original data structure, and should be compatible with the old statement.
    
2.  In the original syntax file  **sql_parser.cup**, the new syntax needs to be compatible with the syntax of the old version, using the syntax file sql_parser.cup of the old version as the reference standard.
    
3.  Remove the logic of analytic functions in the statement and move the relevant logic to the new Analyzer framework. The new Analyzer is in the SQL/Analyzer directory.
    
4.  If the code related to Privilege Check exists in the original analyzer, move the code related to privilege control into PrivilegeChecker.
    
5.  When submitting the PR, please make sure there is unit test coverage for related changes.
    

# Tasks

 - [ ] AlterRoutineLoadStmt
 - [ ] PauseRoutineLoadStmt
 - [ ] StopRoutineLoadStmt
 - [ ] CreateRoutineLoadStmt
 - [ ] ResumeRoutineLoadStmt
 - [ ] ShowRoutineLoadStmt
 - [ ] ShowRoutineLoadTaskStmt

# How to participate?

1.  Pick an issue you are interested in, click the issue link and leave a comment under the issue to sign up.  **One person can only choose one issue and the first person who picks the issue will be assigned.**
    
2.  **After the issue is assigned, you should complete the task in 14 days.** If you are unable to complete it within the specified time, the task will be withdrawn and assigned to others.
    
3.  Participants are required to produce two pieces of content (forms including but not limited to mind maps, study notes, blogs, and tutorials) in the course of the activity, each of which should be at least 200 words.
    
4.  Got questions? Join our  [Slack channel](https://join.slack.com/t/starrocks/shared_invite/zt-192zeqlc7-9MAvqAXNcveW_l5Pqr8r2g)  and find channel:  **#sql-planner**.
    

# Before you start

1.  Read  [Contributing.md](https://github.com/StarRocks/starrocks/blob/main/CONTRIBUTING.md)  carefully to understand how to submit a pull request and how to configure BE and FE development environment.
    
2.  Sign the  [Contributor License Agreement](https://cla-assistant.io/StarRocks/starrocks)  before you make a pull request.
    
3.  To learn more about StarRocks, please refer to  [StarRocks documentation](https://github.com/StarRocks/docs/blob/main/TOC.md).
    

# Pull request requirements

1.  Create a pull request (PR) after you complete the task.
* PR title format: [SR SQL Planner Summer Camp] + PR title
2. After submitting PR, you can comment under the pinned Issue [SR SQL Planner Summer Camp].
* Comment format: "I have finished Issue #" + PR link

### PR DESCRIPTION
**Pull request by shshenhua**
## Which issues of this PR fixes ：

Fixes https://github.com/StarRocks/starrocks/issues/7949

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by ABingHuang** [comment]
there are some others code in this pr. maybe there is a problem when you rebase the master code.
you should check and fix it.

**Review by ABingHuang — CHANGES_REQUESTED** [review]
there are some problems in code rebase.
this pr contain many others' code.

**Comment by shshenhua** [comment]
hi ABingHuang，maybe main branch has problem code
following steps:
1. git checkout  main
2. git pull origin main
3. git checkout routineload_alter
4. git rebase main
5. git pull origin routineload_alter 

please tell me how can I solve this problem，thank you
@ABingHuang

**Comment by ABingHuang** [comment]
there are dependency with pr #9981. better to merge #9981 first and then rebase it.

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 76 / 86 (88.37%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/Analyzer.java|0|2|00.00%|[494, 495]|
|:large_blue_circle:|com/starrocks/sql/ast/AstVisitor.java|0|1|00.00%|[368]|
|:large_blue_circle:|com/starrocks/analysis/AlterRoutineLoadStmt.java|5|7|71.43%|[217, 222]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AlterRoutineLoadAnalyzer.java|19|24|79.17%|[21, 22, 31, 32, 33]|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|52|52|100.00%|[]|

**Comment by shshenhua** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 78 / 88 (88.64%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/Analyzer.java|0|2|00.00%|[503, 504]|
|:large_blue_circle:|com/starrocks/sql/ast/AstVisitor.java|0|1|00.00%|[364]|
|:large_blue_circle:|com/starrocks/analysis/AlterRoutineLoadStmt.java|5|7|71.43%|[217, 222]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AlterRoutineLoadAnalyzer.java|19|24|79.17%|[21, 22, 31, 32, 33]|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|54|54|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 81 / 91 (89.01%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/Analyzer.java|0|2|00.00%|[503, 504]|
|:large_blue_circle:|com/starrocks/sql/ast/AstVisitor.java|0|1|00.00%|[364]|
|:large_blue_circle:|com/starrocks/analysis/AlterRoutineLoadStmt.java|5|7|71.43%|[217, 222]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AlterRoutineLoadAnalyzer.java|19|24|79.17%|[21, 22, 31, 32, 33]|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|57|57|100.00%|[]|

**Comment by shshenhua** [comment]
run starrocks_fe_unittest

**Comment by shshenhua** [comment]
run starrocks_fe_unittest

**Comment by shshenhua** [comment]
run starrocks_fe_unittest

**Comment by shshenhua** [comment]
run starrocks_fe_unittest

**Comment by shshenhua** [comment]
run starrocks_fe_unittest

**Comment by shshenhua** [comment]
run starrocks_fe_unittest

**Comment by shshenhua** [comment]
run starrocks_fe_unittest

**Comment by shshenhua** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 83 / 94 (88.30%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/Analyzer.java|0|2|00.00%|[504, 505]|
|:large_blue_circle:|com/starrocks/sql/ast/AstVisitor.java|0|1|00.00%|[365]|
|:large_blue_circle:|com/starrocks/analysis/AlterRoutineLoadStmt.java|5|7|71.43%|[217, 222]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AlterRoutineLoadAnalyzer.java|19|24|79.17%|[21, 22, 31, 32, 33]|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|59|60|98.33%|[4751]|

**Comment by HangyuanLiu** [comment]
run starrocks_admit_test

**Review by kangkaisen — APPROVED** [review]

**Review by HangyuanLiu — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Pull request merged**
