### PR TITLE
[WIP] Test be ut

### PR DESCRIPTION
**Pull request by wangruin**
this will close soon

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wangruin** [comment]
run starrocks_be_unittest image

**Comment by wangruin** [comment]
run starrocks_be_unittest image

**Comment by wangruin** [comment]
run starrocks_be_unittest image

**Comment by wangruin** [comment]
run starrocks_be_unittest image

**Comment by wangruin** [comment]
run starrocks_be_unittest image

**Comment by wangruin** [comment]
run starrocks_be_unittest image

**Comment by wangruin** [comment]
run starrocks_be_unittest

**Comment by wangruin** [comment]
run starrocks_be_unittest

**Comment by wangruin** [comment]
run starrocks_fe_unittest

**Comment by wangruin** [comment]
run starrocks_fe_unittest

**Comment by wangruin** [comment]
run starrocks_fe_unittest

**Pull request closed without merging**
