### PR TITLE
[BugFix] refactor cloud native pk table publish & fix local persistent index usage (backport #30504)

### PR DESCRIPTION
**Pull request by luohaha**
Backport #30504

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:heart_eyes: **pass** : 48 / 58 (82.76%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/storage/lake/meta_file.cpp|0|1|00.00%|[199]|
|:large_blue_circle:|src/storage/lake/lake_local_persistent_index.cpp|0|3|00.00%|[32, 33, 35]|
|:large_blue_circle:|src/storage/lake/update_manager.cpp|32|37|86.49%|[64, 65, 66, 67, 104]|
|:large_blue_circle:|src/storage/lake/txn_log_applier.cpp|16|17|94.12%|[117]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:heart_eyes: **pass** : 48 / 58 (82.76%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/storage/lake/meta_file.cpp|0|1|00.00%|[199]|
|:large_blue_circle:|src/storage/lake/lake_local_persistent_index.cpp|0|3|00.00%|[32, 33, 35]|
|:large_blue_circle:|src/storage/lake/update_manager.cpp|32|37|86.49%|[64, 65, 66, 67, 104]|
|:large_blue_circle:|src/storage/lake/txn_log_applier.cpp|16|17|94.12%|[117]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:heart_eyes: **pass** : 48 / 58 (82.76%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/storage/lake/meta_file.cpp|0|1|00.00%|[199]|
|:large_blue_circle:|src/storage/lake/lake_local_persistent_index.cpp|0|3|00.00%|[32, 33, 35]|
|:large_blue_circle:|src/storage/lake/update_manager.cpp|32|37|86.49%|[64, 65, 66, 67, 104]|
|:large_blue_circle:|src/storage/lake/txn_log_applier.cpp|16|17|94.12%|[117]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:heart_eyes: **pass** : 48 / 58 (82.76%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/storage/lake/meta_file.cpp|0|1|00.00%|[199]|
|:large_blue_circle:|src/storage/lake/lake_local_persistent_index.cpp|0|3|00.00%|[32, 33, 35]|
|:large_blue_circle:|src/storage/lake/update_manager.cpp|32|37|86.49%|[64, 65, 66, 67, 104]|
|:large_blue_circle:|src/storage/lake/txn_log_applier.cpp|16|17|94.12%|[117]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:heart_eyes: **pass** : 48 / 58 (82.76%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/storage/lake/meta_file.cpp|0|1|00.00%|[199]|
|:large_blue_circle:|src/storage/lake/lake_local_persistent_index.cpp|0|3|00.00%|[32, 33, 35]|
|:large_blue_circle:|src/storage/lake/update_manager.cpp|32|37|86.49%|[64, 65, 66, 67, 104]|
|:large_blue_circle:|src/storage/lake/txn_log_applier.cpp|16|17|94.12%|[117]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:heart_eyes: **pass** : 48 / 58 (82.76%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/storage/lake/meta_file.cpp|0|1|00.00%|[199]|
|:large_blue_circle:|src/storage/lake/lake_local_persistent_index.cpp|0|3|00.00%|[32, 33, 35]|
|:large_blue_circle:|src/storage/lake/update_manager.cpp|32|37|86.49%|[64, 65, 66, 67, 104]|
|:large_blue_circle:|src/storage/lake/txn_log_applier.cpp|16|17|94.12%|[117]|

**Review by wyb — APPROVED** [review]

**Pull request merged**
