### PR TITLE
[BugFix] fix ArrayIndexOutOfBoundsException in HiveScanner

### PR DESCRIPTION
**Pull request by zhangyifan27**
Fixes the java exception error when reading hive RCFilie, the detail error message is
```
java.io.IOException: Failed to get the next off-heap table chunk of hive.
        at com.starrocks.hive.reader.HiveScanner.getNext(HiveScanner.java:241)
        at com.starrocks.jni.connector.ConnectorScanner.getNextOffHeapChunk(ConnectorScanner.java:101)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 10 out of bounds for length 10
        at org.apache.hadoop.hive.serde2.columnar.BytesRefArrayWritable.unCheckedGet(BytesRefArrayWritable.java:104)
        at org.apache.hadoop.hive.ql.io.RCFile$Reader.getCurrentRow(RCFile.java:1939)
        at org.apache.hadoop.hive.ql.io.RCFileRecordReader.next(RCFileRecordReader.java:149)
        at org.apache.hadoop.hive.ql.io.RCFileRecordReader.next(RCFileRecordReader.java:44)
        at com.starrocks.hive.reader.HiveScanner.getNext(HiveScanner.java:223)
```

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Comment by dirtysalt** [comment]
Can you reproduce this case in UT? 

To be honest, I don't quite get why this change fix problem.

**Comment by zhangyifan27** [comment]
I can reproduce it in the test environment. 
1. Create a hive external catalog on StarRocks.
2. Query the tpch.lineitem RCFile table generated by Hive.

These SQLs should fail without this fix:
```
select count(1) from lineitem group by l_shipdate;
select count(1) from lineitem where l_shipdate <= '1998-09-02';
```
Remove the `where` or `group by` clause，they did not fail.

**Comment by before-Sunrise** [comment]
I got it! org.apache.hadoop.hive.ql.io.RCFile has one method  getCurrentRow(), in getCurrentRow(), if rowFetched is false, which means this is the first time to call  getCurrentRow, it will set reader's value( which is BytesRefArrayWritable)'s capacity according to number of columns reader want. But this only happens on the first time.So if we call createValue in HiveScanner.getNext(), the second time this value's capacity will not be reset, and default capacity is 10, which cause arrayIndexoutofbound exception.

**Comment by before-Sunrise** [comment]
LGTM

**Review by before-Sunrise — APPROVED** [review]

**Review by kangkaisen — APPROVED** [review]

**Review by dirtysalt — APPROVED** [review]

**Pull request merged**
