### PR TITLE
[Bugfix] fix external catalog support Hive MATERIALIZED_VIEW table

### LINKED ISSUE #9384: [bug] External Catalog Do not support Hive MATERIALIZED_VIEW table
### Steps to reproduce the behavior (Required)
image

image

### Expected behavior (Required)
image

### Real behavior (Required)
image

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - main, 2.3

### PR DESCRIPTION
**Pull request by feihengye**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #9384

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by imay** [comment]
@feihengye thanks for your contribution, can you sign our CLA?

**Comment by feihengye** [comment]
> @feihengye thanks for your contribution, can you sign our CLA?

ok

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by stephen-shelby — APPROVED** [review]
LGTM

**Pull request merged**
