### PR TITLE
[BugFix] fix jni-reader for struct type when writing nulls to off heap

### PR DESCRIPTION
**Pull request by 839224346**
## Why I'm doing:
Current JNI-Reader writes incorrect number of null values to off heap when it comes to struct type. It results into wrong result and sometimes crashes BE.

## What I'm doing:
Remove the part of code that writes duplicate null values to the root struct column.

Fixes #issue

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
- [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Comment by dirtysalt** [comment]
@839224346 thanks for fixing that.

do you have any ut to cover that? or how can you reproduce that?  

UT can be added to `hudi-reader` or `hive-reader` to cover that path.

**Comment by dirtysalt** [comment]
is this the case like 
> c: struct { a int, b string} .

and two rows: 
c0 = struct { 10, "hello"}
c1 = struct { null, "world"}

**Comment by 839224346** [comment]
> is this the case like
> 
> > c: struct { a int, b string} .
> 
> and two rows: c0 = struct { 10, "hello"} c1 = struct { null, "world"}

I've added 9 more rows to make the error more obvious. 
The data looks like this
image
Before fix
image
After fix
image


It seems more difficult to trigger a Segmentation fault like the one we met in Prod env though.

**Review by dirtysalt — APPROVED** [review]

**Review by stephen-shelby — APPROVED** [review]

**Comment by 839224346** [comment]
BE crashes after result is returned. Will look into it.

**Comment by 839224346** [comment]
> BE crashes after result is returned. Will look into it.

Turns out, it was the map type that causes crash. Keep working on it.

**Pull request merged**
