### PR TITLE
[BugFix] Fix query use jsonTye between-and decimalV3Type failed

### LINKED ISSUE #16056: Query json type with between-and faild
### Steps to reproduce the behavior (Required)
1. SELECT  '....'
```
MySQL [dps_data_center_stream]> select parse_json('1') between 0.5 and 0.9;
ERROR 1064 (HY000): between predicate type json with type unknown type: INVALID_TYPE is invalid.
```

### Expected behavior (Required)
return 1
### Real behavior (Required)
report error
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
main

### PR DESCRIPTION
**Pull request by mchades**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #16056 

## Problem Summary(Required) ：

support jsonType implicit cast to double when meet decimalV3Type
## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by murphyatwork — APPROVED** [review]

**Comment by mofeiatwork** [comment]
run starrocks_admit_test

**Review by imay — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Pull request merged**
