### PR TITLE
[BugFix] Fix materialized view parser percentile cast error bug

### LINKED ISSUE #6329: insert failed after create MATERIALIZED VIEW and restart cluster
### Steps to reproduce the behavior (Required)
1.
```
CREATE TABLE `t100` (
  `k1` date NULL COMMENT "",
  `k2` datetime NULL COMMENT "",
  `k3` char(20) NULL COMMENT "",
  `k4` varchar(20) NULL COMMENT "",
  `k5` boolean NULL COMMENT "",
  `k6` tinyint(4) NULL COMMENT "",
  `k7` smallint(6) NULL COMMENT "",
  `k8` int(11) NULL COMMENT "",
  `k9` bigint(20) NULL COMMENT "",
  `k10` largeint(40) NULL COMMENT "",
  `k11` float NULL COMMENT "",
  `k12` double NULL COMMENT "",
  `k13` decimal128(27, 9) NULL COMMENT ""
) ENGINE=OLAP
DUPLICATE KEY(`k1`, `k2`, `k3`, `k4`, `k5`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`k1`, `k2`, `k3`) BUCKETS 3
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"storage_format" = "V2",
"enable_persistent_index" = "false"
);
CREATE MATERIALIZED VIEW mv_function1
                     AS SELECT
                       k1,
                       MAX(k2),
                       MIN(k3),
                       COUNT(t100.k4),
                       SUM(k6),
                       PERCENTILE_UNION(percentile_hash(t100.k7)),
                       HLL_UNION(hll_hash(CAST(`k8` AS VARCHAR))),
                       BITMAP_UNION(to_bitmap(CAST(`k9` AS VARCHAR))),
                       MAX(DISTINCT k12),
                       MIN(DISTINCT k13)
                     FROM t100 GROUP BY k1;
```
2.wait create mv finished
3.restart cluster
4.
`insert into t100 values ('2020-10-22','2020-10-23 12:12:12','k3','k4',0,1,2,3,4,5,1.1,1.12,2.889);`
### Expected behavior (Required)
`query ok`
### Real behavior (Required)
`ERROR 1064 (HY000): Invalid type cast from smallint(6) to varchar(-1) in sql `k7``
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
+----------------------+
| current_version()    |
+----------------------+
| MAIN-RELEASE f4eb1f6 |
+----------------------+
```

### PR DESCRIPTION
**Pull request by HangyuanLiu**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #6329

### CODE REVIEW

**Review by kangkaisen — APPROVED** [review]

**Comment by HangyuanLiu** [comment]
run starrocks_fe_unittest

**Review by Seaven — APPROVED** [review]

**Comment by Seaven** [comment]
starrocks_fe_unittest

**Comment by Seaven** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/ExpressionAnalyzer.java|1|1|100.00%|

**Pull request merged**
