### PR TITLE
[BugFix] HANDLE_FILED catch exception when getting an external table fails.

### PR DESCRIPTION
**Pull request by stephen-shelby**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

if a hive table exists in the db under a iceberg catalog. An exception will be thrown, and subsequent queries will keep coming back with the exception.
image

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 0 / 7 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/connector/exception/StarRocksConnectorException.java|0|3|00.00%|[43, 44, 46]|
|:large_blue_circle:|com/starrocks/qe/ConnectProcessor.java|0|3|00.00%|[420, 421, 422]|
|:large_blue_circle:|com/starrocks/connector/iceberg/hive/HiveTableOperations.java|0|1|00.00%|[124]|

**Comment by stephen-shelby** [comment]
run starrocks_admit_test

**Review by DorianZheng — APPROVED** [review]

**Comment by stephen-shelby** [comment]
run starrocks_admit_test

**Review by Youngwb — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by gengjun-git — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
