### PR TITLE
[BugFix] Report error when creating table with unknown properties

### PR DESCRIPTION
**Pull request by wyb**
1. unpartitioned table properties 
create table t1 (k1 int)
distributed by hash(k1) properties ("wrong_key" = "value");

2. partition properties 
create table t1 (k1 int)
partition by range(k1) (partition p1 values less than("10") ("wrong_key" = "value")) 
distributed by hash(k1);

report `Unknown properties: {wrong_key=value}`

## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 3.0
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Comment by wyb** [comment]
run starrocks_admit_test

**Comment by wyb** [comment]
run all

**Comment by wyb** [comment]
run starrocks_admit_test

**Comment by wyb** [comment]
run starrocks_fe_unittest

**Comment by wyb** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 63 / 67 (94.03%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/AlterTableStatementAnalyzer.java|1|2|50.00%|[238]|
|:large_blue_circle:|com/starrocks/sql/ast/SingleItemListPartitionDesc.java|18|21|85.71%|[168, 169, 170]|
|:large_blue_circle:|com/starrocks/sql/ast/MultiItemListPartitionDesc.java|21|21|100.00%|[]|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/MultiRangePartitionDesc.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/SingleRangePartitionDesc.java|20|20|100.00%|[]|

**Comment by wyb** [comment]
run starrocks_admit_test

**Review by sduzh — DISMISSED** [review]

**Comment by wyb** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 71 / 75 (94.67%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/AlterTableStatementAnalyzer.java|1|2|50.00%|[238]|
|:large_blue_circle:|com/starrocks/sql/ast/SingleItemListPartitionDesc.java|21|24|87.50%|[168, 169, 170]|
|:large_blue_circle:|com/starrocks/sql/ast/MultiItemListPartitionDesc.java|24|24|100.00%|[]|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/MultiRangePartitionDesc.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/SingleRangePartitionDesc.java|22|22|100.00%|[]|

**Review by sduzh — APPROVED** [review]

**Review by Astralidea — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wyb** [comment]
@Mergifyio backport branch-3.0

**Pull request merged**
