### PR TITLE
[BugFix] Support symbol "&&" as logical AND

### LINKED ISSUE #11819: [Bug] &&  operator not Unsupported in 2.3.2-dbc89ae
### Steps to reproduce the behavior (Required)
case to reproduce:

CREATE TABLE t1 (
id bigint(20) NOT NULL COMMENT "",
column1 varchar(20) NULL COMMENT ""
) ENGINE=OLAP
PRIMARY KEY(id)
COMMENT "test"
DISTRIBUTED BY HASH(id) BUCKETS 1
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"storage_format" = "DEFAULT",
"enable_persistent_index" = "false"
);

insert into t1
select 1,"a"
union
select 2,"b"
union
select 3,"c"
union
select 4,"d"
;

 SELECT * from t1 where id=1 && column1='a';

### Expected behavior (Required)
2.1.12 works fine with && operator
mysql> SELECT * from t1 where id=1 && column1='a';
+------+---------+
| id   | column1 |
+------+---------+
|    1 | a       |
+------+---------+

### Real behavior (Required)
[1064] [42000]: Unexpected exception: Unsupported operator: &&

### StarRocks version (Required)
 - 2.3.2-dbc89ae

### PR DESCRIPTION
**Pull request by HangyuanLiu**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #11819

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

### CODE REVIEW

**Comment by HangyuanLiu** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|1|1|100.00%|[]|

**Review by Seaven — DISMISSED** [review]

**Review by murphyatwork — DISMISSED** [review]

**Comment by HangyuanLiu** [comment]
run starrocks_admit_test

**Comment by mofeiatwork** [comment]
@Mergifyio rebase

**Comment by mofeiatwork** [comment]
run starrocks_admit_test

**Comment by HangyuanLiu** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|1|1|100.00%|[]|

**Review by murphyatwork — APPROVED** [review]

**Review by Seaven — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Pull request merged**
