### PR TITLE
[BugFix] Fix AutovacuumDaemon throws NPE after FE starts

### LINKED ISSUE #26158: AutovacuumDaemon throws NPE after FE starts
```
java.lang.NullPointerException
        at com.starrocks.lake.Utils.chooseBackend(Utils.java:57)
        at com.starrocks.lake.Utils.chooseNode(Utils.java:70)
        at com.starrocks.lake.vacuum.AutovacuumDaemon.vacuumPartitionImpl(AutovacuumDaemon.java:140)
        at com.starrocks.lake.vacuum.AutovacuumDaemon.vacuumPartition(AutovacuumDaemon.java:113)
        at com.starrocks.lake.vacuum.AutovacuumDaemon.lambda$vacuumTable$3(AutovacuumDaemon.java:106)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
java.lang.NullPointerException
        at com.starrocks.lake.Utils.chooseBackend(Utils.java:57)
        at com.starrocks.lake.Utils.chooseNode(Utils.java:70)
        at com.starrocks.lake.vacuum.AutovacuumDaemon.vacuumPartitionImpl(AutovacuumDaemon.java:140)
        at com.starrocks.lake.vacuum.AutovacuumDaemon.vacuumPartition(AutovacuumDaemon.java:113)
        at com.starrocks.lake.vacuum.AutovacuumDaemon.lambda$vacuumTable$3(AutovacuumDaemon.java:106)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[2023-06-28 20:41:49] leader finished to replay journal, can write now.
```

The null pointer exception no longer appears after FE has replay all the journals.

### PR DESCRIPTION
**Pull request by sduzh**
Fix #26158

Fixes #issue

## What type of PR is this:
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4

### CODE REVIEW

**Review by gengjun-git — APPROVED** [review]

**Review by wyb — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by kevincai — APPROVED** [review]

**Comment by sduzh** [comment]
@Mergifyio rebase

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Pull request merged**
