### PR TITLE
[Enhancement] Support statistics collect immediately when CreateAnalyzeStmt and some code refactoring

### PR DESCRIPTION
**Pull request by HangyuanLiu**
## What type of PR is this：
- [ ] bug
- [ ] feature
- [x] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 33 / 214 (15.42%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/statistic/StatsConstants.java|0|1|00.00%|
|:large_blue_circle:|com/starrocks/statistic/StatisticSQLBuilder.java|0|1|00.00%|
|:large_blue_circle:|com/starrocks/statistic/StatisticAutoCollector.java|0|11|00.00%|
|:large_blue_circle:|com/starrocks/statistic/SampleStatisticsCollectJob.java|0|3|00.00%|
|:large_blue_circle:|com/starrocks/statistic/StatisticExecutor.java|0|20|00.00%|
|:large_blue_circle:|com/starrocks/statistic/StatisticsCollectJobFactory.java|0|67|00.00%|
|:large_blue_circle:|com/starrocks/statistic/StatisticsMetaManager.java|0|16|00.00%|
|:large_blue_circle:|com/starrocks/execution/CreateAnalyzeJobExecutor.java|0|12|00.00%|
|:large_blue_circle:|com/starrocks/statistic/AnalyzeManager.java|0|8|00.00%|
|:large_blue_circle:|com/starrocks/statistic/TableCollectJob.java|0|1|00.00%|
|:large_blue_circle:|com/starrocks/statistic/HistogramStatisticsCollectJob.java|0|4|00.00%|
|:large_blue_circle:|com/starrocks/statistic/AnalyzeJob.java|1|21|04.76%|
|:large_blue_circle:|com/starrocks/qe/StmtExecutor.java|1|13|07.69%|
|:large_blue_circle:|com/starrocks/statistic/StatisticsCollectJob.java|4|8|50.00%|
|:large_blue_circle:|com/starrocks/sql/analyzer/AnalyzeStmtAnalyzer.java|8|9|88.89%|
|:large_blue_circle:|com/starrocks/sql/ast/CreateAnalyzeJobStmt.java|2|2|100.00%|
|:large_blue_circle:|com/starrocks/statistic/StatisticUtils.java|4|4|100.00%|
|:large_blue_circle:|com/starrocks/sql/analyzer/PrivilegeChecker.java|5|5|100.00%|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/join/JoinOrder.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/statistic/FullStatisticsCollectJob.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/sql/ast/ShowAnalyzeJobStmt.java|3|3|100.00%|
|:large_blue_circle:|com/starrocks/sql/optimizer/cost/CostModel.java|3|3|100.00%|

**Review by Seaven — DISMISSED** [review]

**Comment by Seaven** [comment]
run starrocks_fe_unittest

**Review by Youngwb — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 36 / 239 (15.06%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/statistic/StatsConstants.java|0|1|00.00%|
|:large_blue_circle:|com/starrocks/statistic/StatisticSQLBuilder.java|0|1|00.00%|
|:large_blue_circle:|com/starrocks/statistic/StatisticAutoCollector.java|0|11|00.00%|
|:large_blue_circle:|com/starrocks/statistic/SampleStatisticsCollectJob.java|0|10|00.00%|
|:large_blue_circle:|com/starrocks/statistic/StatisticExecutor.java|0|20|00.00%|
|:large_blue_circle:|com/starrocks/statistic/StatisticsCollectJobFactory.java|0|66|00.00%|
|:large_blue_circle:|com/starrocks/statistic/StatisticsMetaManager.java|0|16|00.00%|
|:large_blue_circle:|com/starrocks/execution/CreateAnalyzeJobExecutor.java|0|12|00.00%|
|:large_blue_circle:|com/starrocks/statistic/AnalyzeManager.java|0|8|00.00%|
|:large_blue_circle:|com/starrocks/statistic/TableCollectJob.java|0|8|00.00%|
|:large_blue_circle:|com/starrocks/statistic/HistogramStatisticsCollectJob.java|0|5|00.00%|
|:large_blue_circle:|com/starrocks/statistic/AnalyzeJob.java|1|21|04.76%|
|:large_blue_circle:|com/starrocks/qe/StmtExecutor.java|1|13|07.69%|
|:large_blue_circle:|com/starrocks/statistic/FullStatisticsCollectJob.java|1|8|12.50%|
|:large_blue_circle:|com/starrocks/statistic/StatisticsCollectJob.java|4|8|50.00%|
|:large_blue_circle:|com/starrocks/sql/ast/ShowAnalyzeStatusStmt.java|2|3|66.67%|
|:large_blue_circle:|com/starrocks/sql/analyzer/AnalyzeStmtAnalyzer.java|8|9|88.89%|
|:large_blue_circle:|com/starrocks/common/Config.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/sql/ast/CreateAnalyzeJobStmt.java|2|2|100.00%|
|:large_blue_circle:|com/starrocks/statistic/StatisticUtils.java|4|4|100.00%|
|:large_blue_circle:|com/starrocks/sql/analyzer/PrivilegeChecker.java|5|5|100.00%|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/join/JoinOrder.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/sql/ast/ShowAnalyzeJobStmt.java|3|3|100.00%|
|:large_blue_circle:|com/starrocks/sql/optimizer/cost/CostModel.java|3|3|100.00%|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 36 / 244 (14.75%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/statistic/StatsConstants.java|0|1|00.00%|
|:large_blue_circle:|com/starrocks/statistic/StatisticSQLBuilder.java|0|1|00.00%|
|:large_blue_circle:|com/starrocks/statistic/StatisticAutoCollector.java|0|11|00.00%|
|:large_blue_circle:|com/starrocks/statistic/SampleStatisticsCollectJob.java|0|10|00.00%|
|:large_blue_circle:|com/starrocks/statistic/StatisticExecutor.java|0|20|00.00%|
|:large_blue_circle:|com/starrocks/statistic/StatisticsCollectJobFactory.java|0|71|00.00%|
|:large_blue_circle:|com/starrocks/statistic/StatisticsMetaManager.java|0|16|00.00%|
|:large_blue_circle:|com/starrocks/execution/CreateAnalyzeJobExecutor.java|0|12|00.00%|
|:large_blue_circle:|com/starrocks/statistic/AnalyzeManager.java|0|8|00.00%|
|:large_blue_circle:|com/starrocks/statistic/TableCollectJob.java|0|8|00.00%|
|:large_blue_circle:|com/starrocks/statistic/HistogramStatisticsCollectJob.java|0|5|00.00%|
|:large_blue_circle:|com/starrocks/statistic/AnalyzeJob.java|1|21|04.76%|
|:large_blue_circle:|com/starrocks/qe/StmtExecutor.java|1|13|07.69%|
|:large_blue_circle:|com/starrocks/statistic/FullStatisticsCollectJob.java|1|8|12.50%|
|:large_blue_circle:|com/starrocks/statistic/StatisticsCollectJob.java|4|8|50.00%|
|:large_blue_circle:|com/starrocks/sql/ast/ShowAnalyzeStatusStmt.java|2|3|66.67%|
|:large_blue_circle:|com/starrocks/sql/analyzer/AnalyzeStmtAnalyzer.java|8|9|88.89%|
|:large_blue_circle:|com/starrocks/common/Config.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/sql/ast/CreateAnalyzeJobStmt.java|2|2|100.00%|
|:large_blue_circle:|com/starrocks/statistic/StatisticUtils.java|4|4|100.00%|
|:large_blue_circle:|com/starrocks/sql/analyzer/PrivilegeChecker.java|5|5|100.00%|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/join/JoinOrder.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/sql/ast/ShowAnalyzeJobStmt.java|3|3|100.00%|
|:large_blue_circle:|com/starrocks/sql/optimizer/cost/CostModel.java|3|3|100.00%|

**Review by Seaven — APPROVED** [review]

**Review by Youngwb — APPROVED** [review]

**Pull request merged**
