### PR TITLE
[BugFix] Fix unstable ut

### PR DESCRIPTION
**Pull request by ABingHuang**
## What type of PR is this：
- [x] bugfix
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

the UT is unstable because the creation process of materialized views are async, and the column index will be be unstable for count filed of materialized view. Fix it by skip check field id for count field in UT.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Review by kangkaisen — DISMISSED** [review]

**Comment by ABingHuang** [comment]
run starrocks_fe_unittest

**Review by Seaven — APPROVED** [review]

**Comment by Seaven** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by kangkaisen — APPROVED** [review]

**Comment by ABingHuang** [comment]
run starrocks_admit_test

**Pull request merged**
