### PR TITLE
[Enhancement] Support to specify aws cred provider in broker load

### PR DESCRIPTION
**Pull request by dirtysalt**
## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

To support to specify aws cred provider in broker load request. And according to doc link https://hadoop.apache.org/docs/stable/hadoop-aws/tools/hadoop-aws/index.html,  several default providers are chained, it should suffice for most cases.

```
    <property>
        <name>fs.s3a.aws.credentials.provider</name>
        <value>
            org.apache.hadoop.fs.s3a.AnonymousAWSCredentialsProvider,
            org.apache.hadoop.fs.s3a.TemporaryAWSCredentialsProvider,
            org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider,
            com.amazonaws.auth.EnvironmentVariableCredentialsProvider,
            org.apache.hadoop.fs.s3a.auth.IAMInstanceCredentialsProvider
        </value>
    </property>
```

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Review by gengjun-git — APPROVED** [review]

**Review by Youngwb — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by dirtysalt** [comment]
@MergifyIO backport branch-2.4

**Comment by dirtysalt** [comment]
@MergifyIO backport branch-2.3

**Comment by dirtysalt** [comment]
@MergifyIO backport branch-2.2

**Pull request merged**
