### PR TITLE
[Refactor] Remove show statement parser / analyzer deprecated code

### PR DESCRIPTION
**Pull request by HangyuanLiu**
## What type of PR is this：
- [ ] bugfix
- [ ] feature
- [ ] enhancement
- [x] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 193 / 259 (74.52%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/ast/ShowPluginsStmt.java|0|2|00.00%|[27, 32]|
|:large_blue_circle:|com/starrocks/sql/ast/ShowTriggersStmt.java|0|2|00.00%|[27, 32]|
|:large_blue_circle:|com/starrocks/sql/ast/ShowFrontendsStmt.java|0|9|00.00%|[12, 16, 17, 18, 19, 20, 25, 30, 35]|
|:large_blue_circle:|com/starrocks/sql/analyzer/PrivilegeChecker.java|0|8|00.00%|[1094, 1095, 1097, 1099, 1104, 1105, 1107, 1109]|
|:large_blue_circle:|com/starrocks/sql/ast/ShowRepositoriesStmt.java|4|11|36.36%|[11, 19, 20, 21, 22, 23, 28]|
|:large_blue_circle:|com/starrocks/sql/ast/AstVisitor.java|3|6|50.00%|[126, 138, 142]|
|:large_blue_circle:|com/starrocks/sql/ast/ShowBackupStmt.java|12|19|63.16%|[35, 36, 37, 38, 39, 44, 54]|
|:large_blue_circle:|com/starrocks/mysql/privilege/Auth.java|2|3|66.67%|[1665]|
|:large_blue_circle:|com/starrocks/sql/ast/ShowBackendsStmt.java|6|9|66.67%|[24, 29, 34]|
|:large_blue_circle:|com/starrocks/sql/ast/ShowBrokerStmt.java|8|11|72.73%|[25, 26, 28]|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|48|61|78.69%|[2814, 2819, 2881, 2886, 2891, 2896, 2901, 2929, 2934, 2981, 2982, 2986, 2987]|
|:large_blue_circle:|com/starrocks/sql/ast/ShowUserStmt.java|6|7|85.71%|[23]|
|:large_blue_circle:|com/starrocks/sql/ast/ShowIndexStmt.java|23|27|85.19%|[38, 43, 52, 62]|
|:large_blue_circle:|com/starrocks/sql/ast/ShowOpenTableStmt.java|10|11|90.91%|[27]|
|:large_blue_circle:|com/starrocks/sql/ast/ShowResourcesStmt.java|10|11|90.91%|[27]|
|:large_blue_circle:|com/starrocks/sql/ast/ShowDeleteStmt.java|12|13|92.31%|[43]|
|:large_blue_circle:|com/starrocks/sql/ast/DropResourceStmt.java|6|6|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/ShowAuthorStmt.java|8|8|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/ShowStmtAnalyzer.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/ShowWarningStmt.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/ShowProcStmt.java|7|7|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/CreateResourceStmt.java|14|14|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/ShowEnginesStmt.java|11|11|100.00%|[]|

**Comment by HangyuanLiu** [comment]
run starrocks_fe_unittest

**Comment by HangyuanLiu** [comment]
run starrocks_fe_unittest

**Comment by HangyuanLiu** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 193 / 259 (74.52%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/ast/ShowPluginsStmt.java|0|2|00.00%|[27, 32]|
|:large_blue_circle:|com/starrocks/sql/ast/ShowTriggersStmt.java|0|2|00.00%|[27, 32]|
|:large_blue_circle:|com/starrocks/sql/ast/ShowFrontendsStmt.java|0|9|00.00%|[12, 16, 17, 18, 19, 20, 25, 30, 35]|
|:large_blue_circle:|com/starrocks/sql/analyzer/PrivilegeChecker.java|0|8|00.00%|[1104, 1105, 1107, 1109, 1114, 1115, 1117, 1119]|
|:large_blue_circle:|com/starrocks/sql/ast/ShowRepositoriesStmt.java|4|11|36.36%|[11, 19, 20, 21, 22, 23, 28]|
|:large_blue_circle:|com/starrocks/sql/ast/AstVisitor.java|3|6|50.00%|[127, 139, 143]|
|:large_blue_circle:|com/starrocks/sql/ast/ShowBackupStmt.java|12|19|63.16%|[35, 36, 37, 38, 39, 44, 54]|
|:large_blue_circle:|com/starrocks/mysql/privilege/Auth.java|2|3|66.67%|[1665]|
|:large_blue_circle:|com/starrocks/sql/ast/ShowBackendsStmt.java|6|9|66.67%|[24, 29, 34]|
|:large_blue_circle:|com/starrocks/sql/ast/ShowBrokerStmt.java|8|11|72.73%|[25, 26, 28]|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|48|61|78.69%|[2823, 2828, 2890, 2895, 2900, 2905, 2910, 2938, 2943, 2990, 2991, 2995, 2996]|
|:large_blue_circle:|com/starrocks/sql/ast/ShowUserStmt.java|6|7|85.71%|[23]|
|:large_blue_circle:|com/starrocks/sql/ast/ShowIndexStmt.java|23|27|85.19%|[38, 43, 52, 62]|
|:large_blue_circle:|com/starrocks/sql/ast/ShowOpenTableStmt.java|10|11|90.91%|[27]|
|:large_blue_circle:|com/starrocks/sql/ast/ShowResourcesStmt.java|10|11|90.91%|[27]|
|:large_blue_circle:|com/starrocks/sql/ast/ShowDeleteStmt.java|12|13|92.31%|[43]|
|:large_blue_circle:|com/starrocks/sql/ast/DropResourceStmt.java|6|6|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/ShowAuthorStmt.java|8|8|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/ShowStmtAnalyzer.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/ShowWarningStmt.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/ShowProcStmt.java|7|7|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/CreateResourceStmt.java|14|14|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/ShowEnginesStmt.java|11|11|100.00%|[]|

**Review by kangkaisen — APPROVED** [review]

**Review by murphyatwork — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Pull request merged**
