### PR TITLE
[BugFix] Fix AuthenticationManager init failure

### LINKED ISSUE #18640: Authentication manager init failure on UserAuhInfoTreeMap
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
2. INSERT INTO '....'
3. SELECT  '....'

### Real behavior (Required)
```
2023-02-28 14:06:10,040 ERROR (main|1) [StarRocksFE.start():184] StarRocksFE start failed
java.lang.ClassFormatError: Illegal field name "com.starrocks.authentication.AuthenticationManager$this" in class com/starrocks/authentication/AuthenticationManager$UserAuthInfoTreeMap
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_322]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756) ~[?:1.8.0_322]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_322]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473) ~[?:1.8.0_322]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74) ~[?:1.8.0_322]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369) ~[?:1.8.0_322]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363) ~[?:1.8.0_322]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_322]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362) ~[?:1.8.0_322]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_322]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352) ~[?:1.8.0_322]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_322]
	at com.starrocks.authentication.AuthenticationManager.<init>(AuthenticationManager.java:61) ~[starrocks-fe.jar:?]
	at com.starrocks.server.GlobalStateMgr.initAuth(GlobalStateMgr.java:989) ~[starrocks-fe.jar:?]
	at com.starrocks.server.GlobalStateMgr.<init>(GlobalStateMgr.java:613) ~[starrocks-fe.jar:?]
	at com.starrocks.server.GlobalStateMgr.<init>(GlobalStateMgr.java:565) ~[starrocks-fe.jar:?]
	at com.starrocks.server.GlobalStateMgr.<init>(GlobalStateMgr.java:313) ~[starrocks-fe.jar:?]
	at com.starrocks.server.GlobalStateMgr$SingletonHolder.<clinit>(GlobalStateMgr.java:561) ~[starrocks-fe.jar:?]
	at com.starrocks.server.GlobalStateMgr.getCurrentState(GlobalStateMgr.java:705) ~[starrocks-fe.jar:?]
	at com.starrocks.StarRocksFE.start(StarRocksFE.java:130) [starrocks-fe.jar:?]
	at com.starrocks.StarRocksFE.main(StarRocksFE.java:82) [starrocks-fe.jar:?]
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by nshangyiming**
## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #18640 

## Problem Summary(Required) ：

Also fix `userToAuthenticationInfo` init with wrong type of Map, should use TreeMap.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 3.0
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 7 / 7 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/authentication/AuthenticationManager.java|7|7|100.00%|[]|

**Review by gengjun-git — APPROVED** [review]

**Comment by nshangyiming** [comment]
run starrocks_admit_test

**Review by Astralidea — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by HangyuanLiu — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Pull request merged**
