### PR TITLE
[Lake] Improve create table process

### PR DESCRIPTION
**Pull request by wyb**
## What type of PR is this：
- [ ] bug
- [ ] feature
- [x] enhancement
- [ ] refactor
- [ ] others

## Problem Summary(Required) ：

1. Get service shard storage info from StarMgr.
2. Support shard storage info and properties when creating shards.

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 10 / 14 (71.43%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/lake/LakeTable.java|0|2|00.00%|
|:large_blue_circle:|com/starrocks/catalog/StarOSAgent.java|9|11|81.82%|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|1|1|100.00%|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 12 / 16 (75.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/lake/LakeTable.java|0|2|00.00%|
|:large_blue_circle:|com/starrocks/catalog/StarOSAgent.java|11|13|84.62%|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|1|1|100.00%|

**Comment by wyb** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 28 / 32 (87.50%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/StarOSAgent.java|11|13|84.62%|
|:large_blue_circle:|com/starrocks/catalog/lake/LakeTable.java|15|17|88.24%|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|2|2|100.00%|

**Review by sduzh — APPROVED** [review]

**Review by abc982627271 — APPROVED** [review]

**Review by wuleistarrocks — APPROVED** [review]

**Review by gengjun-git — APPROVED** [review]

**Pull request merged**
