### PR TITLE
[Enhancement] Avoid reserve oversize memory for chunk generated by agg operators

### PR DESCRIPTION
**Pull request by satanson**
## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

Runtime three times of query cache tests in daily, the result has proved that memory leak in cache is reduced.

```
+==============+=======+=======+=====================+
| Test         | VIRT  | RES   | cache usage(jeprof) |
+==============+=======+=======+=====================+
| mem_leak     | 85.5g | 13.6g | 44g                 |
| no_leak(1st) | 27.4g | 3.7g  | 499m                |
| no_leak(2nd) | 28.2g | 4.5g  | 983m                |
| no_leak(3rd) | 37.5g | 6.9g  | 1254m               |
+--------------+-------+-------+---------------------+
```
The memory(cache usage) is increased sightly.

### CODE REVIEW

**Review by kangkaisen — DISMISSED** [review]

**Review by ZiheLiu — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by ZiheLiu** [comment]
Should `CacheOperator` use `Chunk::memory_usage` instead of `Chunk::bytes_usage`, since `Chunk::memory_usage` contains container capacity memory usage.

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by silverbullet233 — APPROVED** [review]

**Review by kangkaisen — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
starrocks_be_unittest succeeded.

**Review by ZiheLiu — APPROVED** [review]

**Pull request merged**
