### PR TITLE
[WIP] Test be ut 2

### PR DESCRIPTION
**Pull request by wangruin**
this will be closed soon

### CODE REVIEW

**Comment by wangruin** [comment]
run starrocks_be_unittest

**Comment by wangruin** [comment]
run starrocks_clang-format

**Comment by wangruin** [comment]
run starrocks_clang-format

**Comment by wangruin** [comment]
run starrocks_clang-format

**Comment by wangruin** [comment]
run starrocks_clang-tidy

**Comment by wangruin** [comment]
run starrocks_tscancode

**Comment by wangruin** [comment]
run starrocks_tscancode

**Comment by wangruin** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wangruin** [comment]
run starrocks_tscancode image

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wangruin** [comment]
run starrocks_be_unittest image

**Comment by wangruin** [comment]
run starrocks_be_unittest image

**Comment by wangruin** [comment]
run starrocks_be_unittest image

**Comment by wangruin** [comment]
run starrocks_be_unittest image

**Comment by wangruin** [comment]
run starrocks_be_unittest image

**Comment by wangruin** [comment]
run starrocks_be_unittest image

**Comment by wangruin** [comment]
run starrocks_be_unittest image

**Comment by wangruin** [comment]
run starrocks_be_unittest image

**Comment by wangruin** [comment]
run starrocks_be_unittest image

**Comment by wangruin** [comment]
run starrocks_be_unittest image

**Comment by wangruin** [comment]
run starrocks_be_unittest

**Comment by wangruin** [comment]
run starrocks_clang-format

**Comment by wangruin** [comment]
run starrocks_clang-format

**Comment by wangruin** [comment]
path | covered line | new line | coverage | not covered line detail
-- | -- | -- | -- | --
🔵 | com/starrocks/sql/ast/AstVisitor.java | 0 | 3 | 00.00% | [271, 275, 279]

**Comment by wangruin** [comment]
path | covered line | new line | coverage | not covered line detail |
-- | -- | -- | -- | --
🔵 | com/starrocks/sql/ast/AstVisitor.java | 0 | 3 | 00.00% | [271, 275, 279]
🔵|`com/starrocks/sql/optimizer/statistics/CachedStatisticStorage.javaaaaaaaaaaaaaaaaaaaaaaaaaaaaa` | 0 | 7 | 00.00% | [163, 164, 165, 166, 167, 168, 169]

**Pull request closed without merging**
