### PR TITLE
[Enhancement] Refine profile for version smaller than or equals to 3.0

### PR DESCRIPTION
**Pull request by liuyehcf**
Parts of https://github.com/StarRocks/starrocks/pull/31380 can be cp to version <=3.0, including

1. Using groups of metrics that each group will attach to individual ExchangeSourceOperator, so the time, like `DecompressChunkTime` and `DeserializeChunkTime`, can be treated as wall time after thir pr instead of cumulative time.
2. Add `ShuffleChunkAppendTime`
3. Fix the bug for metrics `BytesUnsent` and `RequestUnsent`(Fixes https://github.com/StarRocks/starrocks/issues/31558), this issue is introduced by runtime profiling, when the query is still under processing, there may be some requests in the sender's buffer, so the metrics `BytesUnsent` and `RequestUnsent` is updated. But when the query is finished, the sender's buffer is emtpy, and it won't update the metrics `BytesUnsent` and `RequestUnsent`, so the final profile will show the previous value, which lead to the problem.

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [x] 2.5

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 0 / 70 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/exec/exchange_node.cpp|0|4|00.00%|[86, 87, 99, 100]|
|:large_blue_circle:|src/exec/pipeline/exchange/exchange_merge_sort_source_operator.cpp|0|1|00.00%|[30]|
|:large_blue_circle:|src/exec/pipeline/exchange/sink_buffer.cpp|0|2|00.00%|[166, 168]|
|:large_blue_circle:|src/runtime/data_stream_recvr.cpp|0|20|00.00%|[72, 134, 177, 178, 179, 180, 181, 182, 183, 184, 186, 188, 192, 193, 194, 195, 221, 222, 223, 229]|
|:large_blue_circle:|src/exec/pipeline/exchange/exchange_source_operator.cpp|0|5|00.00%|[25, 26, 27, 61, 62]|
|:large_blue_circle:|src/exec/pipeline/exchange/exchange_sink_operator.cpp|0|5|00.00%|[203, 204, 207, 449, 450]|
|:large_blue_circle:|src/runtime/sender_queue.cpp|0|33|00.00%|[100, 151, 158, 202, 206, 219, 225, 230, 270, 284, 289, 402, 441, 465, 504, 510, 520, 522, 552, 560, 566, 584, 585, 592, 623, 632, 655, 668, 669, 725, 768, 785, 805]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 0 / 70 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/exec/exchange_node.cpp|0|4|00.00%|[86, 87, 99, 100]|
|:large_blue_circle:|src/exec/pipeline/exchange/exchange_merge_sort_source_operator.cpp|0|1|00.00%|[30]|
|:large_blue_circle:|src/exec/pipeline/exchange/sink_buffer.cpp|0|2|00.00%|[166, 168]|
|:large_blue_circle:|src/runtime/data_stream_recvr.cpp|0|20|00.00%|[72, 134, 177, 178, 179, 180, 181, 182, 183, 184, 186, 188, 192, 193, 194, 195, 221, 222, 223, 229]|
|:large_blue_circle:|src/exec/pipeline/exchange/exchange_source_operator.cpp|0|5|00.00%|[25, 26, 27, 61, 62]|
|:large_blue_circle:|src/exec/pipeline/exchange/exchange_sink_operator.cpp|0|5|00.00%|[203, 204, 207, 449, 450]|
|:large_blue_circle:|src/runtime/sender_queue.cpp|0|33|00.00%|[100, 151, 158, 202, 206, 219, 225, 230, 270, 284, 289, 402, 441, 465, 504, 510, 520, 522, 552, 560, 566, 584, 585, 592, 623, 632, 655, 668, 669, 725, 768, 785, 805]|

**Review by kangkaisen — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
