### PR TITLE
[Enhancement] Pipeline profile refine

### PR DESCRIPTION
**Pull request by liuyehcf**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Changelist

1. Fix the stupid bug of `OverheadTime` because the metric is rarely concerned under normal circumstances
2. Add `DriverPrepareTime` and `FragmentInstancePrepareTime`
3. Fix merge problem of time metrics
    * Before, it might get stupid result with average greater than the max value
    ```
    # first merge, min/max is not saved if values do not differ much
    (1000, 1000, 1000) -> 1000 
    (10, 20, 30) -> 20[MIN=10, MAX=30]

    # second merge
    (1000, 20[MIN=10, MAX=30]) -> 510[MIN=10, MAX=30]
    ```
    * After
    ```
    # first merge, always keep min and max no matter how much they differ
    (1000, 1000, 1000) -> 1000[MIN=1000, MAX=1000]
    (10, 20, 30) -> 20[MIN=10, MAX=30]

    # second merge
    (1000[MIN=1000, MAX=1000], 20[MIN=10, MAX=30]) -> 510[MIN=10, MAX=1000]
    ```

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [x] I have added user document for my new feature or new function

### CODE REVIEW

**Review by murphyatwork — DISMISSED** [review]

**Comment by liuyehcf** [comment]
run starrocks_fe_unittest

**Comment by liuyehcf** [comment]
run starrocks_admit_test

**Comment by liuyehcf** [comment]
run starrocks_admit_test

**Comment by liuyehcf** [comment]
run starrocks_admit_test

**Comment by liuyehcf** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 16 / 16 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/common/util/RuntimeProfile.java|16|16|100.00%|[]|

**Review by murphyatwork — APPROVED** [review]

**Review by kangkaisen — APPROVED** [review]

**Comment by liuyehcf** [comment]
@Mergifyio backport branch-2.3 branch-2.4

**Pull request merged**
