### PR TITLE
[Enhancement] Make repair for bad tablet start ASAP

### PR DESCRIPTION
**Pull request by nshangyiming**
Fixes SR-16234

For manually set bad tablet or manually repaired partition/table,
we should ignore the queue limitation of tablet scheduler and
put them into scheduler queue with top priority.
Also refactored the original "prios" concept with `urgentTable`.

## What type of PR is this:
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.0
  - [x] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 135 / 169 (79.88%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/common/proc/PriorityRepairProcNode.java|0|1|00.00%|[57]|
|:large_blue_circle:|com/starrocks/clone/TabletChecker.java|33|49|67.35%|[177, 178, 406, 408, 474, 482, 494, 507, 519, 526, 527, 536, 537, 538, 540, 541]|
|:large_blue_circle:|com/starrocks/clone/ColocateTableBalancer.java|97|114|85.09%|[701, 715, 720, 732, 735, 745, 752, 775, 776, 809, 811, 814, 817, 818, 838, 839, 840]|
|:large_blue_circle:|com/starrocks/clone/TabletScheduler.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AdminStmtAnalyzer.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|2|2|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 135 / 167 (80.84%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/common/proc/PriorityRepairProcNode.java|0|1|00.00%|[57]|
|:large_blue_circle:|com/starrocks/clone/TabletChecker.java|33|49|67.35%|[177, 178, 407, 409, 475, 483, 495, 508, 520, 527, 528, 537, 538, 539, 541, 542]|
|:large_blue_circle:|com/starrocks/clone/ColocateTableBalancer.java|97|112|86.61%|[701, 715, 739, 742, 752, 775, 776, 809, 811, 814, 817, 818, 838, 839, 840]|
|:large_blue_circle:|com/starrocks/clone/TabletScheduler.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AdminStmtAnalyzer.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|2|2|100.00%|[]|

**Review by gengjun-git — APPROVED** [review]

**Review by Astralidea — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
