### PR TITLE
[BugFix] Fix rewrite nested mv bugs when mv's partition/distribution predicates are not null

### PR DESCRIPTION
**Pull request by LiShuMing**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Problem Summary(Required) ：
-  Fix rewrite nested mv bugs when mv's partition/distribution predicates is not null
   -  Ignore mvOriginalPredicates when `rewriteMVCompensationExpression` rewrites MVScan's predicates to null, which cannot prune partitions/distributions from MV's define.
```
        // Rewrite original mv's predicates into query if needed.
        final ColumnRewriter columnRewriter = new ColumnRewriter(rewriteContext);
        final Map<ColumnRefOperator, ScalarOperator> mvColumnRefToScalarOp = rewriteContext.getMVColumnRefToScalarOp();
        ScalarOperator mvOriginalPredicates = mvScanOperator.getPredicate();
        if (mvOriginalPredicates != null && !ConstantOperator.TRUE.equals(mvOriginalPredicates)) {
            mvOriginalPredicates = rewriteMVCompensationExpression(rewriteContext, columnRewriter,
                    mvColumnRefToScalarOp, mvOriginalPredicates, false);
         
            if (mvOriginalPredicates == null) {
                return null;
            }
            if (!ConstantOperator.TRUE.equals(mvOriginalPredicates)) {
                mvScanBuilder.setPredicate(mvOriginalPredicates);
            }
        }
```
- use `MvUtils.canonizePredicate(prunedOlapScanOperator.getPredicate()` to canonize predicates after  partition/distribution pruning.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 3.0
  - [x] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 4 / 5 (80.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java|1|2|50.00%|[588]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/MVPartitionPruner.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/MvUtils.java|2|2|100.00%|[]|

**Review by murphyatwork — APPROVED** [review]

**Review by ABingHuang — APPROVED** [review]
LGTM

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
