### PR TITLE
[BugFix] fix invalid double/float type cast for mv

### LINKED ISSUE #14314: double type column should not be stored as decimal
### Steps to reproduce the behavior (Required)
1. CREATE TABLE
CREATE TABLE `emps` (
  `empid` int(11) NOT NULL COMMENT "",
  `deptno` int(11) NOT NULL COMMENT "",
  `name` varchar(25) NOT NULL COMMENT "",
  `salary` double NULL COMMENT ""
) ENGINE=OLAP
DUPLICATE KEY(`empid`, `deptno`, `name`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`empid`) BUCKETS 10
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"storage_format" = "DEFAULT",
"enable_persistent_index" = "false",
"compression" = "LZ4"
);

CREATE MATERIALIZED VIEW `agg_join_mv`
COMMENT "MATERIALIZED_VIEW"
DISTRIBUTED BY HASH(`empid`) BUCKETS 6
REFRESH MANUAL
PROPERTIES (
"replication_num" = "1",
"storage_medium" = "HDD"
)
AS SELECT `emps`.`empid`, `depts`.`name`, sum(`emps`.`salary`) AS `total_salary`
FROM `mvdb`.`emps` INNER JOIN `mvdb`.`depts` ON `emps`.`deptno` = `depts`.`deptno`
GROUP BY `emps`.`empid`, `depts`.`name`;

2. query
select emps.empid, sum(emps.salary) from emps join depts on emps.deptno = depts.deptno group by emps.empid;

3. result
mrL4Er04E3

### Expected behavior (Required)
the latter is the right result
### Real behavior (Required)
the result in red box is wrong
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by ABingHuang**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #14314 

## Problem Summary(Required) ：

fix invalid double/float type cast for mv
## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Review by Astralidea — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 20 / 23 (86.96%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/AnalyzerUtils.java|19|22|86.36%|[494, 495, 497]|
|:large_blue_circle:|com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java|1|1|100.00%|[]|

**Review by Youngwb — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by Astralidea** [comment]
run starrocks_admit_test

**Comment by ABingHuang** [comment]
run starrocks_admit_test

**Comment by ABingHuang** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 20 / 23 (86.96%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/AnalyzerUtils.java|19|22|86.36%|[494, 495, 497]|
|:large_blue_circle:|com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java|1|1|100.00%|[]|

**Review by Astralidea — APPROVED** [review]

**Review by Youngwb — APPROVED** [review]

**Pull request merged**
