### PR TITLE
[BugFix] fix join probe metric is 0

### PR DESCRIPTION
**Pull request by fzhedu**
let probe metrics attach to probe_state in prepare_prober(). result
```
UniqueMetrics:
 - DistributionMode: LOCAL_HASH_BUCKET
 - JoinType: INNER_JOIN
 - OtherJoinConjunctEvaluateTime: 0ns
 - OutputBuildColumnTime: 723.293ms
 - __MAX_OF_OutputBuildColumnTime: 777.605ms
 - __MIN_OF_OutputBuildColumnTime: 662.359ms
 - OutputProbeColumnTime: 38.990ms
 - __MAX_OF_OutputProbeColumnTime: 48.890ms
 - __MIN_OF_OutputProbeColumnTime: 32.626ms
 - OutputTupleColumnTime: 383.335us
 - __MAX_OF_OutputTupleColumnTime: 407.101us
 - __MIN_OF_OutputTupleColumnTime: 368.21us
 - ProbeConjunctEvaluateTime: 14.255ms
 - __MAX_OF_ProbeConjunctEvaluateTime: 20.247ms
 - __MIN_OF_ProbeConjunctEvaluateTime: 11.531ms
 - SearchHashTableTime: 5s964ms
 - __MAX_OF_SearchHashTableTime: 6s295ms
 - __MIN_OF_SearchHashTableTime: 5s291ms
 - WhereConjunctEvaluateTime: 0ns
```

## What type of PR is this:
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [x] 3.0
  - [ ] 2.5
  - [ ] 2.4

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by liuyehcf — DISMISSED** [review]

**Review by silverbullet233 — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by silverbullet233 — APPROVED** [review]

**Review by liuyehcf — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Pull request merged**
