### PR TITLE
[Bugfix] Key columns cannot be pruned in the non-skip-aggr scan stage

### LINKED ISSUE #10814: BE crash in sqlancer test env
### Steps to reproduce the behavior (Required)
be.out:
```
*** Aborted at 1662131947 (unix time) try "date -d @1662131947" if you are using GNU date ***
PC: @          0x2277dc3 std::__push_heap<>()
*** SIGSEGV (@0x0) received by PID 130221 (TID 0x7fa0c810f700) from PID 0; stack trace: ***
    @          0x48ed4b2 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7fa14231e5f0 (unknown)
    @          0x2277dc3 std::__push_heap<>()
    @          0x22847ba starrocks::vectorized::HeapMergeIterator::do_get_next()
    @          0x2284db4 starrocks::vectorized::HeapMergeIterator::do_get_next()
    @          0x24dd8b3 starrocks::vectorized::TimedChunkIterator::do_get_next()
    @          0x24d965e starrocks::vectorized::AggregateIterator::do_get_next()
    @          0x24dabd4 starrocks::vectorized::AggregateIterator::do_get_next()
    @          0x24dd8b3 starrocks::vectorized::TimedChunkIterator::do_get_next()
    @          0x228643e starrocks::vectorized::TabletReader::do_get_next()
    @          0x1f95e42 starrocks::vectorized::ProjectionIterator::do_get_next()
    @          0x2fb800b starrocks::pipeline::OlapChunkSource::_read_chunk_from_storage()
    @          0x2fb86db starrocks::pipeline::OlapChunkSource::_read_chunk()
    @          0x2fb2ce0 starrocks::pipeline::ChunkSource::buffer_next_batch_chunks_blocking()
    @          0x2e83e41 _ZNSt17_Function_handlerIFvvEZN9starrocks8pipeline12ScanOperator18_trigger_next_scanEPNS1_12RuntimeStateEiEUlvE_E9_M_invokeERKSt9_Any_data
    @          0x2f250e5 starrocks::workgroup::ScanExecutor::worker_thread()
    @          0x26bb165 starrocks::ThreadPool::dispatch_thread()
    @          0x26b666a starrocks::Thread::supervise_thread()
    @     0x7fa142316e65 start_thread
    @     0x7fa14193188d __clone
    @                0x0 (unknown)
```

core file location:
ssh sr@sqlancer01
sr@test
/home/disk1/sr/sqlancer_master_release_01/be/issue_10814

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
mysql> select current_version();
+----------------------+
| current_version()    |
+----------------------+
| MAIN-RELEASE b438184 |
+----------------------+
1 row in set (0.00 sec)
```

### PR DESCRIPTION
**Pull request by ZiheLiu**
## What type of PR is this：
- [x] bugfix
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #10814.

## Problem Summary(Required) ：

Key columns cannot be pruned in the non-skip-aggr scan stage, because they must be retained in `SegmentIterator`, `MergeIterator`, and `AggregateIterator` to  merge and aggregate rows.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/plan/PlanFragmentBuilder.java|2|2|100.00%|[]|

**Review by kangkaisen — DISMISSED** [review]

**Comment by ZiheLiu** [comment]
@Mergifyio backport branch-2.4

**Review by Seaven — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by ZiheLiu** [comment]
run starrocks_admit_test

**Comment by ZiheLiu** [comment]
@Mergifyio backport branch-2.2 branch-2.3

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by ZiheLiu** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by ZiheLiu** [comment]
run starrocks_admit_test

**Comment by ZiheLiu** [comment]
run starrocks_fe_unittest

**Comment by ZiheLiu** [comment]
run starrocks_fe_unittest

**Comment by ZiheLiu** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/plan/PlanFragmentBuilder.java|2|2|100.00%|[]|

**Review by Seaven — APPROVED** [review]

**Review by kangkaisen — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/plan/PlanFragmentBuilder.java|2|2|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/plan/PlanFragmentBuilder.java|2|2|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/plan/PlanFragmentBuilder.java|2|2|100.00%|[]|

**Pull request merged**
