### PR TITLE
[Enhancement](log) add config to control compression of fe log & fe audit log

### LINKED ISSUE #50593: [Enhancement](log) add config to control compression of fe log & fe audit log
## Enhancement
Managing large logs in a busy StarRocks cluster can be challenging, especially when trying to preserve historical data without consuming excessive disk space. Enabling compression is a practical solution to this problem. Gzip compression can effectively reduce disk usage while still allowing you to access the logs. By implementing gzip compression and utilizing appropriate tools, you can efficiently manage log storage and access in your StarRocks cluster.

### PR DESCRIPTION
**Pull request by rohitrs1983**
## Why I'm doing:
Managing large logs in a busy StarRocks cluster can be challenging, especially when trying to preserve historical data without consuming excessive disk space. Enabling compression is a practical solution to this problem. Gzip compression can effectively reduce disk usage while still allowing you to access the logs. By implementing gzip compression and utilizing appropriate tools, you can efficiently manage log storage and access in your StarRocks cluster.

## What I'm doing:
add config items sys_log_enable_compress & audit_log_enable_compress to enable/disable fe log & fe audit log compression

sys_log_enable_compress=false
Screenshot_20240903_012241

sys_log_enable_compress=true
Screenshot_20240903_012838

Fixes #50593 

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [X] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [X] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.3
  - [x] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Review by Astralidea — APPROVED** [review]

**Review by nshangyiming — APPROVED** [review]

**Comment by nshangyiming** [comment]
@mergify rebase

**Comment by rohitrs1983** [comment]
@Astralidea @nshangyiming

**Comment by kevincai** [comment]
@mergifyio rebase

**Comment by kevincai** [comment]
@mergifyio rebase

**Pull request merged**
