### PR TITLE
[BugFix] fix ExchangeSourceOperator leaking DataStreamReceiver issue

### LINKED ISSUE #35076: BE Crash in starrocks::DataStreamRecvr::~DataStreamRecvr
### Steps to reproduce the behavior (Required)

```
throws exception: std::system_error, trace:
    @          0x28347f4  std::__throw_system_error()
    @          0x2b68e91  starrocks::DataStreamMgr::deregister_recvr()
    @          0x2b9dac1  starrocks::DataStreamRecvr::close()
    @          0x2b9dd35  starrocks::DataStreamRecvr::~DataStreamRecvr()
    @          0x2b6a0cb  std::_Sp_counted_ptr<>::_M_dispose()
    @          0x2b68cd0  starrocks::DataStreamMgr::deregister_recvr()
    @          0x2b9dac1  starrocks::DataStreamRecvr::close()
    @          0x2b9dd35  starrocks::DataStreamRecvr::~DataStreamRecvr()
    @          0x2b6a0cb  std::_Sp_counted_ptr<>::_M_dispose()
    @          0x2b6a19a  std::_Sp_counted_ptr_inplace<>::_M_dispose()
    @          0x2ac2af2  starrocks::ExecEnv::destroy()
    @          0x2be038c  starrocks::start_be()
    @          0x28376a1  main
    @     0x7fa8e446d555  __libc_start_main
    @          0x29cf84f  (unknown)
    @              (nil)  (unknown)

*** Aborted at 1699322059 (unix time) try "date -d @1699322059" if you are using GNU date ***
PC: @     0x7fd0ec1c4387 __GI_raise
*** SIGABRT (@0x3e800000a95) received by PID 2709 (TID 0x7fd0ee791180) from PID 2709; stack trace: ***
    @          0x6394f02 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7fd0ece93630 (unknown)
    @     0x7fd0ec1c4387 __GI_raise
    @     0x7fd0ec1c5a78 __GI_abort
    @          0x282531c _ZN9__gnu_cxx27__verbose_terminate_handlerEv.cold
    @          0x874cd36 __cxxabiv1::__terminate()
    @          0x87f2e29 __cxa_call_terminate
    @          0x874c751 __gxx_personality_v0
    @          0x87f99ee _Unwind_RaiseException_Phase2
    @          0x87fa4e6 _Unwind_Resume
    @          0x24e0e7b _ZN9starrocks13DataStreamMgr16deregister_recvrERKNS_9TUniqueIdEi.cold
    @          0x2b8c331 starrocks::DataStreamRecvr::close()
    @          0x2b8c5a5 starrocks::DataStreamRecvr::~DataStreamRecvr()
    @          0x2b57ebb std::_Sp_counted_ptr<>::_M_dispose()
    @          0x2b56ac0 starrocks::DataStreamMgr::deregister_recvr()
    @          0x2b8c331 starrocks::DataStreamRecvr::close()
    @          0x2b8c5a5 starrocks::DataStreamRecvr::~DataStreamRecvr()
    @          0x2b57ebb std::_Sp_counted_ptr<>::_M_dispose()
    @          0x2b57f8a std::_Sp_counted_ptr_inplace<>::_M_dispose()
    @          0x2ab469a starrocks::ExecEnv::destroy()
    @          0x2bcedec starrocks::start_be()
    @          0x282a141 main
    @     0x7fd0ec1b0555 __libc_start_main
    @          0x29c160f (unknown)
    @                0x0 (unknown)
```

### StarRocks version (Required)

branch-3.2

### PR DESCRIPTION
**Pull request by kevincai**
Fixes #35076, fix coredump

## What type of PR is this:

- [X] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [X] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [X] I have checked the version labels which the pr will be auto-backported to the target branch
  - [X] 3.2
  - [X] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Review by trueeyu — DISMISSED** [review]

**Review by liuyehcf — APPROVED** [review]

**Comment by liuyehcf** [comment]
LGTM

**Review by trueeyu — APPROVED** [review]

**Comment by kevincai** [comment]
@mergifyio backport branch-3.2

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.2

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Comment by kevincai** [comment]
manual backport to branch-3.1 at https://github.com/StarRocks/starrocks/pull/35370

**Pull request merged**
