### PR TITLE
[BugFix] per bucket optimization bug

### LINKED ISSUE #31838: query result error if set enable_per_bucket_optimize=true
### Steps to reproduce the behavior (Required)

```sql
CREATE TABLE t0 (
    c1 int,
    c2 int
) UNIQUE KEY(c1, c2)
PARTITION BY RANGE (c1) (
    PARTITION p1 VALUES [('1'), ('10')),
    PARTITION p2 VALUES [('10'), ('20'))
) DISTRIBUTED BY HASH(c2) buckets 12
PROPERTIES( "replication_num"="1", "colocate_with"="5a5fd327dsdb_2806" );
insert into t0 (c1, c2) values (1, 1), (2, 1), (3, 1), (4, 1), (11, 1), (11, 2), (1, 2), (2, 2), (3, 2), (11, 2), (12, 2), (1, 3), (2, 3), (3, 3), (11, 3);
select c2,count() from c2 group by c2 order by c2;
```

### Expected behavior (Required)
```shell
mysql> select c2,count() from t2 group by c2 order by c2;
+------+---------+
| c2   | count() |
+------+---------+
|    1 |       5 |
|    2 |       5 |
|    3 |       4 |
+------+---------+
3 rows in set (0.04 sec)
```
### Real behavior (Required)
```shell
mysql> select c2,count() from t2 group by c2 order by c2;
+------+---------+
| c2   | count() |
+------+---------+
|    1 |       4 |
|    1 |       1 |
|    2 |       3 |
|    2 |       2 |
|    3 |       3 |
|    3 |       1 |
+------+---------+
6 rows in set (0.04 sec)
```

### StarRocks version (Required)
main-48c56b

### PR DESCRIPTION
**Pull request by silverbullet233**
Fixes #31838 #31869
introduce by #31367

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 19 / 20 (95.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/tree/PhysicalDistributionAggOptRule.java|19|20|95.00%|[89]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 19 / 20 (95.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/tree/PhysicalDistributionAggOptRule.java|19|20|95.00%|[89]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 19 / 20 (95.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/tree/PhysicalDistributionAggOptRule.java|19|20|95.00%|[89]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 19 / 20 (95.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/tree/PhysicalDistributionAggOptRule.java|19|20|95.00%|[89]|

**Review by Seaven — APPROVED** [review]

**Review by stdpain — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/plan/PlanFragmentBuilder.java|2|2|100.00%|[]|

**Comment by luohaha** [comment]
https://github.com/Mergifyio backport branch-3.1-cs

**Pull request merged**
