### PR TITLE
[BugFix] fix boolean decoder in parquet scanner

### PR DESCRIPTION
**Pull request by dirtysalt**
Fixes #issue

When cross parquet pages, you have to reset decoder buffer. 

## What type of PR is this:
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [x] 3.0
  - [x] 2.5
  - [ ] 2.4

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by stephen-shelby — APPROVED** [review]

**Review by Youngwb — APPROVED** [review]

**Comment by dirtysalt** [comment]
@MergifyIO backport branch-3.1

**Comment by dirtysalt** [comment]
@Mergifyio backport branch-3.0

**Comment by dirtysalt** [comment]
@Mergifyio backport branch-2.5

**Comment by dirtysalt** [comment]
@mergify backport branch-2.4

**Comment by dirtysalt** [comment]
@mergify backport branch-2.2

**Comment by dirtysalt** [comment]
@mergify backport branch-2.3

**Pull request merged**
