### PR TITLE
[BugFix] Fix count(*) error during adding smaller type column

### LINKED ISSUE #33242: count(*) returns error when adding smaller type job is running
### Steps to reproduce the behavior (Required)
```sql
ADMIN SET FRONTEND CONFIG ("allow_default_light_schema_change"="false");

create table t0(
    k1 INT,
    c1 INT
) 
DUPLICATE KEY(k1) 
DISTRIBUTED BY HASH(k1) BUCKETS 3;

insert into t0 values (1,1);

alter table t0 add column b1 BOOLEAN;

-- wait util the schema change job is running, and then:
select count(*) from t0;

```

### Expected behavior (Required)
```
+----------+
| count(*) |
+----------+
| 1        |
+----------+
```

### Real behavior (Required)
```
E: (1064, 'invalid field name: b1')
```

### PR DESCRIPTION
**Pull request by ZiheLiu**
Fixes #33242.

`select count(*) from t1` select the smallest column from the table `t1`. However, the candidates includes invisible columns. Therefore, if a smaller column `boolean_col` is added to the table and the schema change job is still running, the invisible column `boolean_col` will be selected wrongly.

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.2
  - [x] 3.1
  - [x] 3.0
  - [x] 2.5

### CODE REVIEW

**Review by packy92 — DISMISSED** [review]

**Review by silverbullet233 — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by ABingHuang — DISMISSED** [review]

**Review by kangkaisen — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 12 / 12 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/Utils.java|6|6|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/PruneScanColumnRule.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/MVColumnPruner.java|3|3|100.00%|[]|

**Review by packy92 — APPROVED** [review]

**Review by Seaven — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
