### PR TITLE
[Enhancement] Default replication_num based on run mode

### LINKED ISSUE #18576: [StarOS] create table with colocate error
### Steps to reproduce the behavior (Required)
````sql
CREATE TABLE t1 (
                            `id` int(18),
                            `name` varchar(20)
                        )

                        UNIQUE KEY(`id`)
                        COMMENT "OLAP"
                        DISTRIBUTED BY HASH(`id`) BUCKETS 3
                        PROPERTIES (
                            "replication_num" = "3",
                            "storage_format" = "v2",
                            "colocate_with" = "group1"
                        );
CREATE TABLE t2 (
                                                `id` int(18),
                                                `t1_id` int(18),
                                                `address` varchar(20)
                                            )

                                            UNIQUE KEY(`id`)
                                            COMMENT "OLAP"
                                            DISTRIBUTED BY HASH(`id`) BUCKETS 3
                                            PROPERTIES (
                                                "replication_num" = "3",
                                                "storage_format" = "v2",
                                                "colocate_with" = "group1"
                                            );
execute sql error and messages: (1064, 'Unexpected exception: Colocate tables must have same replication num: 1'), and time is: 2023-02-27 18:17:06
````

### Expected behavior (Required)
create table t2 successfully

### Real behavior (Required)
error

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
mysql> select current_version();
+-------------------+
| current_version() |
+-------------------+
| UNKNOWN 705d390ff |
+-------------------+
1 row in set (0.00 sec)
```

### PR DESCRIPTION
**Pull request by sduzh**
- If run mode is shared_nothing, set default replication_num to 3
- If run mode is shared_data, set default replication_num to 1

For table with decoupled compute and storage,  if user specify a value of "replication_num"
greater than 1, will NOT really create multiple replicas of data.  However, the check of
 "replication_num" on many code paths still takes effect, such as the check of the number of live backends.

For table with decoupled compute and storage, the `show create table` command will still display
the value specified by the user, although the value has no actual effect.

## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #18576

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 3.0
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Comment by sduzh** [comment]
run starrocks_fe_unittest

**Comment by sduzh** [comment]
run starrocks_clang-format

**Comment by sduzh** [comment]
run starrocks_fe_unittest

**Comment by sduzh** [comment]
run starrocks_fe_unittest

**Comment by sduzh** [comment]
run starrocks_fe_unittest

**Comment by sduzh** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 54 / 67 (80.60%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/RangePartitionInfo.java|0|1|00.00%|[522]|
|:large_blue_circle:|com/starrocks/catalog/ColocateTableIndex.java|0|1|00.00%|[1013]|
|:large_blue_circle:|com/starrocks/catalog/ExpressionRangePartitionInfo.java|0|1|00.00%|[129]|
|:large_blue_circle:|com/starrocks/StarRocksFE.java|0|1|00.00%|[135]|
|:large_blue_circle:|com/starrocks/server/NodeMgr.java|1|6|16.67%|[396, 422, 424, 427, 429]|
|:large_blue_circle:|com/starrocks/server/RunMode.java|20|24|83.33%|[59, 134, 139, 144]|
|:large_blue_circle:|com/starrocks/sql/ast/MultiItemListPartitionDesc.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/common/proc/BackendsProcDir.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/OlapTable.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/ListPartitionInfo.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/SingleItemListPartitionDesc.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/system/SystemInfoService.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AlterTableStatementAnalyzer.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/system/ComputeNode.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/BackupRestoreAnalyzer.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/TableProperty.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|5|5|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/RestoreStmt.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/common/util/PropertyAnalyzer.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/transaction/PublishVersionDaemon.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/SingleRangePartitionDesc.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/system/HeartbeatMgr.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/qe/ShowExecutor.java|1|1|100.00%|[]|

**Review by tracymacding — APPROVED** [review]

**Review by wyb — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by gengjun-git — APPROVED** [review]

**Comment by sduzh** [comment]
run starrocks_admit_test

**Comment by sduzh** [comment]
run starrocks_admit_test

**Comment by sduzh** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Pull request merged**
