### PR TITLE
[Enhancement] Remove sensitive info from create routine load stmt log

### LINKED ISSUE #13324: Sensitive info should be moved from log
## Enhancement
The log of StarRocks may include some sensitive information, like username, password.

### PR DESCRIPTION
**Pull request by rickif**
## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes https://github.com/StarRocks/starrocks/issues/13324

## Problem Summary(Required) ：

The origin log of create routine load stmt is 
image
The new one would be like
```
2022-11-15 17:02:48,704 WARN (starrocks-mysql-nio-pool-1|163) [StmtExecutor.handleDdlStmt():1107] DDL statement (CREATE ROUTINE LOAD db0.rl_simple ON tbl_simple COLUMNS TERMINATED BY '        ', COLUMNS(`key1`, `key2`) PROPERTIES ( "format" = "json", "jsonpaths" = "["$.data.key1", "$.data.key2"]", "strip_outer_array" = "false" ) FROM KAFKA ( "kafka_offsets" = "OFFSET_BEGINNING", "property.sasl.password" = "***", "kafka_partitions" = "0", "kafka_broker_list" = "172.26.92.155:9093", "kafka_topic" = "topic-some-null" )) process failed.
```
The value of `property.sasl.password` would be replaced with `***`.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 3 / 9 (33.33%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/StmtExecutor.java|1|6|16.67%|[1094, 1097, 1098, 1103, 1105]|
|:large_blue_circle:|com/starrocks/sql/ast/CreateRoutineLoadStmt.java|1|2|50.00%|[801]|
|:large_blue_circle:|com/starrocks/sql/ast/StatementBase.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 16 / 25 (64.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/StmtExecutor.java|1|8|12.50%|[1112, 1113, 1114, 1116, 1122, 1123, 1125]|
|:large_blue_circle:|com/starrocks/sql/ast/CreateRoutineLoadStmt.java|2|3|66.67%|[810]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AST2SQL.java|12|13|92.31%|[111]|
|:large_blue_circle:|com/starrocks/common/util/PrintableMap.java|1|1|100.00%|[]|

**Review by meegoo — APPROVED** [review]

**Review by chaoyli — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by rickif** [comment]
run starrocks_admit_test

**Comment by rickif** [comment]
@mergifyio backport branch-2.5

**Pull request merged**
