### PR TITLE
[BugFix] support to read s3 in hudi reader

### LINKED ISSUE #27556: Hudi fails to read Merge On Read table after adding logs files
### Steps to reproduce the behavior (Required)
```python
from pyspark.sql.types import StructType, StructField, StringType, IntegerType
data = [
    (1, "f5c2ebfd-f57b-4ff3-ac5c-f30674037b21", "A", "BC", "C"),
    (2, "f5c2ebfd-f57b-4ff3-ac5c-f30674037b22", "A", "BC", "C"),
    (3, "f5c2ebfd-f57b-4ff3-ac5c-f30674037b21", "A", "BC", "C"),
    (4, "f5c2ebfd-f57b-4ff3-ac5c-f30674037b22", "A", "BC", "C"),
]

schema = StructType(
    [
        StructField("uuid", IntegerType(), True, {"comment": "foo bar"}),
        StructField("user_id", StringType(), True),
        StructField("col1", StringType(), True),
        StructField("ts", StringType(), True),
        StructField("part", StringType(), True),
    ]
)

df = spark.createDataFrame(data=data, schema=schema)


tableName="test_starrocks_mor"

basePath="s3://bucket/test_starrocks_mor"

hudi_options = {
"hoodie.table.name": tableName,
"hoodie.datasource.write.recordkey.field": "uuid",
"hoodie.datasource.write.partitionpath.field": "part",
"hoodie.datasource.write.table.name": tableName,
"hoodie.datasource.write.operation": "insert",
"hoodie.datasource.write.table.type": "MERGE_ON_READ",
"hoodie.datasource.write.precombine.field": "ts",
 "hoodie.datasource.hive_sync.enable": "true",
"hoodie.datasource.hive_sync.database": "default",
"hoodie.datasource.hive_sync.table": tableName,
"hoodie.datasource.hive_sync.mode": "hms",
"hoodie.datasource.hive_sync.partition_fields": "part",
"hoodie.datasource.hive_sync.partition_extractor_class": "org.apache.hudi.hive.MultiPartKeysValueExtractor",
}

# insert
(df.write.format("hudi").options(**hudi_options).mode("overwrite").save(basePath))
# upsert
(df.write.format("hudi").options(**hudi_options).option("hoodie.datasource.write.operation", "upsert").mode("append").save(basePath))
```

### Expected behavior (Required)

Starrocks should not fail with error

### Real behavior (Required)

1. create a MOR table (see below pyspark script)
2. do insert
3. do upsert (to create logs files)
4. sync glue w/ hive sync
5. now try to read both `_ro` / `_rt` tables
6. `_ro` works fine, but `_rt` fails

```
Caused by: java.io.IOException: No FileSystem for scheme: s3
        at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:2660)
        at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2667)
        at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:94)
        at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2703)
        at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2685)
        at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:373)
        at org.apache.hadoop.fs.Path.getFileSystem(Path.java:295)
        at org.apache.parquet.hadoop.util.HadoopInputFile.fromPath(HadoopInputFile.java:38)
        at org.apache.parquet.hadoop.ParquetFileReader.readFooter(ParquetFileReader.java:469)
        at org.apache.parquet.hadoop.ParquetFileReader.readFooter(ParquetFileReader.java:454)
        at org.apache.hadoop.hive.ql.io.parquet.ParquetRecordReaderBase.getSplit(ParquetRecordReaderBase.java:79)
        at org.apache.hadoop.hive.ql.io.parquet.read.ParquetRecordReaderWrapper.<init>(ParquetRecordReaderWrapper.java:75)
        at org.apache.hadoop.hive.ql.io.parquet.read.ParquetRecordReaderWrapper.<init>(ParquetRecordReaderWrapper.java:60)
        at org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat.getRecordReader(MapredParquetInputFormat.java:92)
        at org.apache.hudi.hadoop.HoodieParquetInputFormat.getRecordReaderInternal(HoodieParquetInputFormat.java:89)
        at org.apache.hudi.hadoop.HoodieParquetInputFormat.getRecordReader(HoodieParquetInputFormat.java:83)
        at org.apache.hudi.hadoop.realtime.HoodieParquetRealtimeInputFormat.getRecordReader(HoodieParquetRealtimeInputFormat.java:74)
        at com.starrocks.hudi.reader.HudiSliceScanner.initReader(HudiSliceScanner.java:183)
        at com.starrocks.hudi.reader.HudiSliceScanner.open(HudiSliceScanner.java:201)
```
### StarRocks version (Required)
- 
```
+-------------------+
| current_version() |
+-------------------+
| 3.0.4 f8ff06dcbc  |
+-------------------+
```
- aws glue metastore
- any hudi version from 0.11 to 0.13

 I suspect somehow on glue / s3 for realtimeview w/ logs files, starrocks try to resolve parquet files with `s3` scheme instead of `s3a` (maybe @dirtysalt)

### PR DESCRIPTION
**Pull request by dirtysalt**
Fixes https://github.com/StarRocks/starrocks/issues/27556

Serval things:
- add `hadoop-aws` to hudi reader lib, so we can access s3.
- fix gcc12 warning.

---

__NOTE__

Make sure when backpor this PR, backport this PR also: https://github.com/StarRocks/starrocks/pull/27701

## What type of PR is this:
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4

### CODE REVIEW

**Review by miomiocat — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by Smith-Cruise — COMMENTED** [review]
Have you tested it?
Maybe we need include aws-bundle jar either.

**Review by Youngwb — APPROVED** [review]

**Comment by dirtysalt** [comment]
@mergify backport branch-3.0

**Comment by dirtysalt** [comment]
@mergify backport branch-3.1

**Comment by dirtysalt** [comment]
__NOTE__

Make sure when backpor this PR, backport this PR also: https://github.com/StarRocks/starrocks/pull/27701

**Pull request merged**
