### PR TITLE
[Enhancement] Fix annoying warning and unnecessary downloading of org.glassfish.javax.el

### PR DESCRIPTION
**Pull request by kangkaisen**
## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

https://github.com/StarRocks/starrocks/pull/14061 introduced this issue.

img_v2_7ab143c6-d2b9-4dde-aab8-0db06bdd847g

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by kevincai — APPROVED** [review]

**Review by imay — APPROVED** [review]

**Comment by imay** [comment]
run starrocks_admit_test

**Comment by imay** [comment]
run starrocks_admit_test

**Comment by kevincai** [comment]
please cherry-pick to branch-3.0 as well

**Review by satanson — APPROVED** [review]

**Comment by kevincai** [comment]
@mergerifyio backport branch-3.0

**Pull request merged**
