### PR TITLE
[Enhancement] Fix the checkstyle of semicolons

### PR DESCRIPTION
**Pull request by guoxiaolongzte**
**Fix the checkstyle of semicolons, mainly to fix the issue of two semicolons and extra semicolons. Added relevant rules in checkstyle.xml.**

 <module name="UnnecessarySemicolonAfterOuterTypeDeclaration"/>
        <module name="UnnecessarySemicolonAfterTypeMemberDeclaration"/>
        <module name="UnnecessarySemicolonInEnumeration"/>
        <module name="UnnecessarySemicolonInTryWithResources"/>
        <module name="Regexp">
            <property name="format" value=";{2,}[\r\n]+"/>
            <property name="illegalPattern" value="true"/>
            <property name="ignoreComments" value="true"/>
            <property name="message" value="Two or more semicolons appear, which is a duplicate."/>
        </module>

Fixes #issue

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.2
  - [x] 3.1
  - [x] 3.0
  - [x] 2.5

### CODE REVIEW

**Review by kevincai — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:disappointed: **fail** : 5 / 11 (45.45%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/SimpleScheduler.java|0|1|00.00%|[264]|
|:large_blue_circle:|com/starrocks/privilege/ranger/hive/HiveAccessType.java|0|1|00.00%|[18]|
|:large_blue_circle:|com/starrocks/scheduler/mv/MVEpoch.java|0|1|00.00%|[132]|
|:large_blue_circle:|com/starrocks/sql/analyzer/BackupRestoreAnalyzer.java|0|1|00.00%|[125]|
|:large_blue_circle:|com/starrocks/qe/StmtExecutor.java|0|1|00.00%|[333]|
|:large_blue_circle:|com/starrocks/connector/hive/HiveMetastoreOperations.java|0|1|00.00%|[134]|
|:large_blue_circle:|com/starrocks/scheduler/PartitionBasedMvRefreshProcessor.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/load/pipe/filelist/FileListRepo.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/RuleSetType.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/SetQualifier.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/JDBCTable.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.2

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
