### PR TITLE
[Refactor] Add schema change utils

### PR DESCRIPTION
**Pull request by wyb**
## What type of PR is this：
- [ ] bug
- [ ] feature
- [ ] enhancement
- [x] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

Some common codes are moved to utils and will be used in lake table schema change.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by wyb** [comment]
run starrocks_be_unittest

**Review by sduzh — DISMISSED** [review]

**Review by chaoyli — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wyb** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by sduzh — APPROVED** [review]

**Review by chaoyli — APPROVED** [review]

**Pull request merged**
