### PR TITLE
[Feature] Support full statistics as default collect strategy

### PR DESCRIPTION
**Pull request by HangyuanLiu**
## What type of PR is this：
- [ ] bug
- [x] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #

### CODE REVIEW

**Review by Youngwb — APPROVED** [review]

**Review by kangkaisen — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by HangyuanLiu** [comment]
run starrocks_fe_unittest

**Comment by HangyuanLiu** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 4 / 16 (25.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/statistic/StatisticAutoCollector.java|0|1|00.00%|[64]|
|:large_blue_circle:|com/starrocks/statistic/StatisticsCollectJobFactory.java|0|4|00.00%|[83, 84, 86, 111]|
|:large_blue_circle:|com/starrocks/statistic/StatisticsMetaManager.java|0|2|00.00%|[354, 355]|
|:large_blue_circle:|com/starrocks/statistic/AnalyzeManager.java|0|4|00.00%|[142, 143, 158, 159]|
|:large_blue_circle:|com/starrocks/statistic/StatisticExecutor.java|2|3|66.67%|[65]|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|2|2|100.00%|[]|

**Pull request merged**
