### PR TITLE
[BugFix] Fix Fe lib miss

### LINKED ISSUE #6072: Fe lib miss jar package in 2.2-rc02
### Steps to reproduce the behavior (Required)
select hive external table which file system based on aws

### Expected behavior (Required)
normal result
### Real behavior (Required)
image

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
2.2-rc02

$FE/lib miss aws-java-sdk-bundle-1.11.563.jar.

### PR DESCRIPTION
**Pull request by adzfolc**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] others

## Which issues of this PR fixes ：

Fixes https://github.com/StarRocks/starrocks/issues/6072

## Problem Summary(Required) ：

Fix $FE/lib miss aws-java-sdk-bundle-1.11.563.jar

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by gengjun-git** [comment]
The jar aws-java-sdk-bundle-1.11.563.jar has been introduced in org.apache.hadoop/hadoop-aws. But to save the release package size, we have remove this jar, because it is too large. Users can download the jar from https://starrocks.com/zh-CN/download/community.

**Comment by gengjun-git** [comment]
If more and more users are using s3, you can ask to put this jar into the release package. @Dshadowzh

**Comment by chaoyli** [comment]
@adzfolc Are you still tracking this problem?

**Pull request closed without merging**
