### PR TITLE
[BugFix] fix crash issue caused by RewriteSumByAssociativeRule

### LINKED ISSUE #31277: be crash when evaluating sum  after left outer join
### Steps to reproduce the behavior (Required)
1.prepare data
```sql
create table t0 (
    c0 int,
    c1 int not null
) duplicate key(c0) distributed by hash(c0) buckets 3 properties("replication_num" = "1");
create table t1 (
    c0 int,
    c1 int not null
) duplicate key(c0) distributed by hash(c0) buckets 3 properties("replication_num" = "1");

insert into t0 values (1,1),(2,2),(3,3);
insert into t1 values (1,1),(2,2),(NULL,4);
```
2. query
```sql
select sum(t0.c1+1) from t0 left outer join t1 on t0.c0 = t1.c0;
```
### Expected behavior (Required)
return result

### Real behavior (Required)

be crash

```
*** Aborted at 1695019918 (unix time) try "date -d @1695019918" if you are using GNU date ***
PC: @          0x488b7c7 starrocks::CountNullableAggregateFunction<>::update_batch_single_state()
*** SIGSEGV (@0x0) received by PID 79507 (TID 0x7fb518aa7700) from PID 0; stack trace: ***
    @          0x726af12 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7fb643628630 (unknown)
    @          0x488b7c7 starrocks::CountNullableAggregateFunction<>::update_batch_single_state()
    @          0x3b295bf starrocks::Aggregator::compute_single_agg_state()
    @          0x418636e starrocks::pipeline::AggregateBlockingSinkOperator::push_chunk()
    @          0x414d648 starrocks::pipeline::PipelineDriver::process()
    @          0x413c7ae starrocks::pipeline::GlobalDriverExecutor::_worker_thread()
    @          0x63dad6a starrocks::ThreadPool::dispatch_thread()
    @          0x63d50ba starrocks::Thread::supervise_thread()
    @     0x7fb643620ea5 start_thread
    @     0x7fb642c3bb0d __clone
    @                0x0 (unknown)
```

### StarRocks version (Required)
main-0e9aa73

### PR DESCRIPTION
**Pull request by silverbullet233**
Fixes #31277

root cause:

if arg1 is not null, we will generate an invalid AggregateFunction which the count of arg types and the count of arg expr is not matched.
image

besides, for `sum(col+1)`, if col is not null, we will transform it to `sum(col) + count() * 1`, but if it is an aggregation after outer join, the nullable property of col may be changed and `count()` will get a wrong result.so ,we should always rewrite it to `sum(col)+count(col)*1`.

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.2
  - [x] 3.1
  - [x] 3.0
  - [ ] 2.5

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by Seaven — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 3 / 3 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/RewriteSumByAssociativeRule.java|3|3|100.00%|[]|

**Review by packy92 — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.2

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Pull request merged**
