### PR TITLE
[Enhancement] Support text-based profile analysis(2)

### PR DESCRIPTION
**Pull request by liuyehcf**
## Main work

This pr is an continuation work of #28125, including the following changes:

1. List Top most memory consuming operators
2. Display `ScheduleTime`
3. Display some metrics for query cache.

## Example

image

## What type of PR is this:
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 5 / 43 (11.63%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/ExplainAnalyzer.java|0|38|00.00%|[149, 228, 229, 230, 231, 232, 234, 353, 355, 357, 359, 395, 412, 413, 414, 415, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442, 443, 445, 446, 548, 640, 641, 648, 649, 1192, 1227, 1228, 1229]|
|:large_blue_circle:|com/starrocks/qe/QueryState.java|5|5|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 0 / 38 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/ExplainAnalyzer.java|0|38|00.00%|[149, 228, 229, 230, 231, 232, 234, 353, 355, 357, 359, 395, 412, 413, 414, 415, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442, 443, 445, 446, 548, 640, 641, 648, 649, 1192, 1227, 1228, 1229]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 0 / 62 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/ExplainAnalyzer.java|0|62|00.00%|[229, 230, 231, 232, 234, 236, 359, 395, 398, 413, 414, 415, 416, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442, 443, 445, 446, 549, 641, 649, 708, 709, 710, 712, 713, 715, 716, 717, 719, 720, 721, 722, 723, 724, 725, 726, 727, 728, 731, 732, 733, 734, 735, 975, 976, 978, 1163, 1224, 1227, 1258, 1259, 1260, 1261]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 0 / 62 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/ExplainAnalyzer.java|0|62|00.00%|[229, 230, 231, 232, 234, 236, 359, 395, 398, 413, 414, 415, 416, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442, 443, 445, 446, 549, 641, 649, 708, 709, 710, 712, 713, 715, 716, 717, 719, 720, 721, 722, 723, 724, 725, 726, 727, 728, 731, 732, 733, 734, 735, 975, 976, 978, 1163, 1224, 1227, 1258, 1259, 1260, 1261]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 0 / 71 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/ExplainAnalyzer.java|0|71|00.00%|[229, 230, 231, 232, 234, 236, 359, 395, 398, 413, 414, 415, 416, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442, 443, 445, 446, 549, 641, 649, 708, 709, 710, 712, 713, 715, 716, 717, 719, 720, 721, 722, 723, 724, 725, 726, 727, 728, 731, 732, 733, 734, 735, 736, 772, 775, 975, 976, 978, 979, 980, 987, 988, 989, 1168, 1169, 1228, 1229, 1232, 1263, 1264, 1266]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 0 / 71 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/ExplainAnalyzer.java|0|71|00.00%|[229, 230, 231, 232, 234, 236, 359, 395, 398, 413, 414, 415, 416, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442, 443, 445, 446, 549, 641, 649, 708, 709, 710, 712, 713, 715, 716, 717, 719, 720, 721, 722, 723, 724, 725, 726, 727, 728, 731, 732, 733, 734, 735, 736, 772, 775, 975, 976, 978, 979, 980, 987, 988, 989, 1168, 1169, 1228, 1229, 1232, 1263, 1264, 1266]|

**Review by satanson — DISMISSED** [review]

**Review by Seaven — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 0 / 89 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/ExplainAnalyzer.java|0|89|00.00%|[150, 197, 228, 229, 230, 231, 232, 234, 304, 310, 311, 317, 318, 354, 356, 358, 360, 371, 374, 377, 378, 379, 380, 381, 382, 383, 387, 406, 407, 408, 409, 427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 439, 440, 542, 634, 635, 642, 643, 701, 702, 703, 704, 705, 706, 707, 708, 710, 712, 714, 716, 718, 719, 720, 721, 722, 723, 724, 725, 726, 727, 765, 767, 953, 954, 955, 956, 958, 959, 964, 965, 966, 1009, 1011, 1012, 1207, 1239, 1242, 1243]|

**Review by packy92 — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 0 / 91 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/ExplainAnalyzer.java|0|91|00.00%|[150, 197, 228, 229, 230, 231, 232, 234, 304, 310, 311, 317, 318, 354, 356, 358, 360, 371, 374, 377, 378, 379, 380, 381, 382, 383, 387, 406, 407, 408, 409, 427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 439, 440, 542, 634, 635, 642, 643, 701, 702, 703, 704, 705, 706, 707, 708, 710, 712, 714, 716, 718, 719, 720, 721, 722, 723, 724, 725, 726, 727, 730, 767, 769, 953, 954, 955, 956, 959, 960, 965, 966, 968, 1010, 1013, 1205, 1222, 1227, 1240, 1241, 1242]|

**Review by Seaven — APPROVED** [review]

**Review by satanson — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 0 / 85 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/ExplainAnalyzer.java|0|85|00.00%|[150, 197, 228, 229, 230, 231, 232, 234, 304, 310, 311, 317, 318, 354, 356, 358, 360, 371, 374, 377, 378, 379, 380, 381, 382, 383, 387, 406, 407, 408, 409, 427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 439, 440, 542, 634, 635, 642, 643, 701, 702, 703, 704, 705, 706, 707, 708, 710, 712, 714, 716, 718, 720, 721, 723, 724, 726, 727, 766, 768, 954, 955, 956, 957, 959, 960, 966, 967, 1012, 1206, 1222, 1227, 1241, 1242, 1243]|

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Pull request merged**
