### PR TITLE
[BugFix] Fix querying hive table with capitalized name not hitting MV

### PR DESCRIPTION
**Pull request by letian-jiang**
The cause of not hitting MV is that we have duplicate tables in the loading cache. 

For example, two tables A and B in cache (but they actually refer to a same table in HMS)
- key(A) = dbname.tablename, key(B) = DBNAME.TABLENAME 
- A has attched MV ids, B does not have attached ids

In this case, query with B (e.g. select * from DBNAME.TABLENAME) cannot hit created MV.

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.2
  - [x] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/connector/ConnectorTblMetaInfoMgr.java|2|2|100.00%|[]|

**Review by Youngwb — APPROVED** [review]

**Review by murphyatwork — COMMENTED** [review]
What about the BaseTableInfo::equals ?

**Comment by letian-jiang** [comment]
> What about the BaseTableInfo::equals ?

This may affects MV on olap tables. Because olap table names are case sensitive.

**Review by LiShuMing — APPROVED** [review]
LGTM

**Review by murphyatwork — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.2

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Pull request merged**
