### PR TITLE
[BugFix] Fix In-Subquerys use complex-expression as correlation predicate

### PR DESCRIPTION
**Pull request by Seaven**
Fixes https://github.com/StarRocks/StarRocksTest/issues/3801

Two Bugs
* In-Subquery use complex-expression, plan error
* be LEFE NULL AWARE ANTI JOIN result error,  when the join use SerializedKeyHashMap, because doesn't set `null_array`

1. SQL:
```
SELECT  *
FROM t4
WHERE
  (t4.c_1_4 IN (
      SELECT t0.c_0_0
      FROM t0
      WHERE (t4.c_1_1 IN (1, 2)) = (t0.c_0_1 IS NULL)
  )) IS NULL
```

will rewrite to 
```
with x as (select cast(c_0_0 as varchar) as v_0_0, c_0_1 from t0)      
select *, CASE WHEN (countRows IS NULL) OR (countRows = 0) THEN FALSE WHEN c_1_4 IS NULL THEN NULL WHEN v_0_0 IS NOT NULL THEN TRUE WHEN countNotNulls < countRows THEN NULL ELSE FALSE END IS NULL
from t4 
    left outer join (select distinct v_0_0, c_0_1 from x) j1 on c_1_4 = v_0_0 and (t4.c_1_1 IN (1, 2)) = (j1.c_0_1 IS NULL)
    left outer join (select c_0_1, count(1) as countRows, count(v_0_0) as countNotNulls from x group by c_0_1) j2 on (t4.c_1_1 IN (1, 2)) = (j2.c_0_1 IS NULL);
```

the bug in `on (t4.c_1_1 IN (1, 2)) = (j2.c_0_1 IS NULL)`, the outer table join inner-count table use correlation predicate may be 1-N join realtion, will produce too many rows.
in fact, we expect is `group by (t0_62.c_0_1 IS NULL)`. For outer table, starrocks's implementation only care the correlation column is unique values, but `group by t0_62.c_0_1` only promise `t0_62.c_0_1` unique, can't promise `fn(distinct(t0_62.c_0_1))`

the SQL is execpt:
```
with x as (select cast(c_0_0 as varchar) as v_0_0, c_0_1 IS NULL as v_0_1 from t0)      
select *, CASE WHEN (countRows IS NULL) OR (countRows = 0) THEN FALSE WHEN c_1_4 IS NULL THEN NULL WHEN v_0_0 IS NOT NULL THEN TRUE WHEN countNotNulls < countRows THEN NULL ELSE FALSE END IS NULL
from t4 
    left outer join (select distinct v_0_0, v_0_1 from x) j1 on c_1_4 = v_0_0 and (t4.c_1_1 IN (1, 2)) = v_0_1
    left outer join (select v_0_1, count(1) as countRows, count(v_0_0) as countNotNulls from x group by v_0_1) j2 on (t4.c_1_1 IN (1, 2)) = j2.v_0_1;
```

and for some complex expression predicate, we can't support now, because we can't promise the result is unique. like:
```
SELECT  *
FROM t4
WHERE
  (t4.c_1_4 IN (
      SELECT t0.c_0_0
      FROM t0
      WHERE t4.c_1_1 = t0.c_0_1 + t4.c_1_2
  )) IS NULL
```

`t4.c_1_1 = t0.c_0_1 + t4.c_1_2` must execute in left-outer join for current implementation, it's error, because `t4 left join t0 on t4.c_1_1 = t0.c_0_1 + t4.c_1_2` may be a 1-N join

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool
 
Does this PR entail a change in behavior?

- [x] Yes, this PR will result in a change in behavior.
- [ ] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [x] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [x] 3.0
  - [x] 2.5
  - [ ] 2.4

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 1 / 2 (50.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/exec/join_hash_map.tpp|0|1|00.00%|[373]|
|:large_blue_circle:|src/exec/join_hash_map.cpp|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 1 / 2 (50.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/exec/join_hash_map.tpp|0|1|00.00%|[373]|
|:large_blue_circle:|src/exec/join_hash_map.cpp|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 1 / 2 (50.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/exec/join_hash_map.tpp|0|1|00.00%|[373]|
|:large_blue_circle:|src/exec/join_hash_map.cpp|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 29 / 31 (93.55%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/SubqueryUtils.java|9|11|81.82%|[152, 157]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/ScalarApply2JoinRule.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/ExistentialApply2OuterJoinRule.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/PushDownApplyAggFilterRule.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/QuantifiedApply2OuterJoinRule.java|5|5|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rewrite/CorrelatedPredicateRewriter.java|12|12|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 1 / 2 (50.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/exec/join_hash_map.tpp|0|1|00.00%|[373]|
|:large_blue_circle:|src/exec/join_hash_map.cpp|1|1|100.00%|[]|

**Review by packy92 — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 1 / 2 (50.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/exec/join_hash_map.tpp|0|1|00.00%|[373]|
|:large_blue_circle:|src/exec/join_hash_map.cpp|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 29 / 31 (93.55%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/SubqueryUtils.java|9|11|81.82%|[152, 157]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/ScalarApply2JoinRule.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/ExistentialApply2OuterJoinRule.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/PushDownApplyAggFilterRule.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/QuantifiedApply2OuterJoinRule.java|5|5|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rewrite/CorrelatedPredicateRewriter.java|12|12|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 1 / 2 (50.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/exec/join_hash_map.tpp|0|1|00.00%|[373]|
|:large_blue_circle:|src/exec/join_hash_map.cpp|1|1|100.00%|[]|

**Review by liuyehcf — DISMISSED** [review]

**Review by kangkaisen — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 29 / 31 (93.55%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/SubqueryUtils.java|9|11|81.82%|[152, 157]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/ScalarApply2JoinRule.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/ExistentialApply2OuterJoinRule.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/PushDownApplyAggFilterRule.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/QuantifiedApply2OuterJoinRule.java|5|5|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rewrite/CorrelatedPredicateRewriter.java|12|12|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 1 / 2 (50.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/exec/join_hash_map.tpp|0|1|00.00%|[373]|
|:large_blue_circle:|src/exec/join_hash_map.cpp|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 29 / 31 (93.55%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/SubqueryUtils.java|9|11|81.82%|[152, 157]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/ScalarApply2JoinRule.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/ExistentialApply2OuterJoinRule.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/PushDownApplyAggFilterRule.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/QuantifiedApply2OuterJoinRule.java|5|5|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rewrite/CorrelatedPredicateRewriter.java|12|12|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 1 / 2 (50.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/exec/join_hash_map.tpp|0|1|00.00%|[373]|
|:large_blue_circle:|src/exec/join_hash_map.cpp|1|1|100.00%|[]|

**Review by packy92 — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Comment by Seaven** [comment]
@mergify backport branch-3.2

**Pull request merged**
