### PR TITLE
[BugFix][Cherry-Pick] Fix bug create too much dynamic partition

### LINKED ISSUE #14367: create too much history partition
this pr https://github.com/StarRocks/starrocks/pull/9501 add feature to create history partition.
image

if I set start a small value ， for example -2147483646,  it will create partition from +5775458-11-14, and it is illegal date value, and throw exception as follows 
```
2022-11-30 16:35:01,971 WARN (DynamicPartitionScheduler|43) [DynamicPartitionScheduler.getAddPartitionClause():167] Error in gen addPartitionKeyRange. Error=date literal [+5775458-11-14] is invalid, db: feng, table: xxx
```
then DynamicPartitionScheduler will do it again and again, more important, it always take db lock.

Of course, -2147483646 is not reasonable value, for old version, it is not elegant but ok. so it might cause the problem for upgraded users.

### PR DESCRIPTION
**Pull request by Astralidea**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #14367

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Comment by Astralidea** [comment]
run all

**Comment by Astralidea** [comment]
run all

**Comment by yongbingwang** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
run starrocks_fe_unittest

**Comment by Astralidea** [comment]
run starrocks_fe_unittest

**Comment by Astralidea** [comment]
run starrocks_fe_unittest

**Comment by Astralidea** [comment]
run starrocks_fe_unittest

**Review by gengjun-git — APPROVED** [review]

**Pull request merged**
