### PR TITLE
[Enhancement] upgrade staros to v3.1-rc7

### PR DESCRIPTION
**Pull request by kevincai**
* upgrade staros related module to v3.1-rc7 with variant fixes, including:
  - storage volume compatibility fixes
  - shard info bugfix
  - ttl calculation fix

Fixes #issue

## What type of PR is this:
- [ ] BugFix
- [ ] Feature
- [X] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [X] I have checked the version labels which the pr will be auto-backported to the target branch
  - [X] 3.1
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4

### CODE REVIEW

**Review by starrocks-xupeng — APPROVED** [review]

**Review by wyb — APPROVED** [review]

**Review by sduzh — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by kevincai** [comment]
@mergifyio backport branch-3.1

**Comment by andyziye** [comment]
@Mergify backport branch-3.1

**Comment by andyziye** [comment]
@Mergify backport branch-3.1

**Comment by andyziye** [comment]
@Mergifyio backport branch-3.1

**Pull request merged**
