### PR TITLE
Move column serialize/deserialize to the outside of Column

### PR DESCRIPTION
**Pull request by sduzh**
By moving the serializing/deserializing to the outside of the Column, we can extend the algorithm without modifying the internal implementation of Column.

### CODE REVIEW

**Comment by sduzh** [comment]
@kangkaisen @imay PTAL

**Review by kangkaisen — DISMISSED** [review]

**Comment by kangkaisen** [comment]
Before merge, would better pass the daily test.

**Comment by sduzh** [comment]
> Before merge, would better pass the daily test.

OK

**Review by kangkaisen — APPROVED** [review]

**Comment by kangkaisen** [comment]
run starrocks_clang-format

**Comment by sduzh** [comment]
run starrocks_clang-format

**Comment by sduzh** [comment]
The daily test has passed

**Comment by sduzh** [comment]
@Seaven PTAL

**Comment by dirtysalt** [comment]
Could you briefly describe what the new interface looks lile? Pros and Cons?

**Comment by dirtysalt** [comment]
I see. Chunk are deserialized using following class/method

```
StatusOr<vectorized::Chunk> ProtobufChunkSerde::deserialize(const RowDescriptor& row_desc, const ChunkPB& chunk_pb) ;
```

**Review by dirtysalt — APPROVED** [review]

**Pull request merged**
