### PR TITLE
[Doc]Update iceberg_catalog.md

### PR DESCRIPTION
**Pull request by femiiii**
## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [x] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

### CODE REVIEW

**Comment by femiiii** [comment]
@mergify backport branch-2.4

**Review by amber-create — APPROVED** [review]

**Review by EsoragotoSpirit — APPROVED** [review]

**Comment by femiiii** [comment]
run starrocks_admit_test

**Comment by femiiii** [comment]
run starrocks_admit_test

**Comment by femiiii** [comment]
@mergify backport branch-2.4

**Pull request merged**
