### PR TITLE
[BugFix] The auto incremental sync of other catalogs with the same url will be stopped when drop a hive catalog

### PR DESCRIPTION
**Pull request by stephen-shelby**
…with the same url will be stopped when drop a hive catalog

## What type of PR is this：
- [x] bugfix
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by stephen-shelby** [comment]
@Mergifyio backport branch-2.3

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 0 / 9 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/server/CatalogMgr.java|0|4|00.00%|[173, 174, 175, 176]|
|:large_blue_circle:|com/starrocks/connector/hive/HiveConnector.java|0|5|00.00%|[52, 53, 54, 55, 56]|

**Comment by stephen-shelby** [comment]
https://github.com/Mergifyio backport branch-2.4

**Review by dirtysalt — APPROVED** [review]

**Review by caneGuy — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by stephen-shelby** [comment]
run starrocks_admit_test

**Comment by stephen-shelby** [comment]
run starrocks_admit_test

**Comment by stephen-shelby** [comment]
run starrocks_admit_test

**Comment by stephen-shelby** [comment]
run starrocks_admit_test

**Comment by stephen-shelby** [comment]
run starrocks_admit_test

**Pull request merged**
