### PR TITLE
[BugFix] Fix the mv of a single partition is always refreshed

### LINKED ISSUE #10068: The mv of a single partition is always refreshed
### Steps to reproduce the behavior (Required)
1. CREATE TABLE
```
CREATE TABLE tbl1
(
k1 date,
k2 int,
v1 int sum
)
PARTITION BY RANGE(k1)
(
    PARTITION p1 values less than('2022-02-01'),
    PARTITION p2 values less than('2022-03-01')
)
DISTRIBUTED BY HASH(k2) BUCKETS 3
PROPERTIES('replication_num' = '1');

```
2. CREATE MV
```
CREATE MATERIALIZED VIEW mv1_no_partition
distributed by hash(k2)
refresh async EVERY(INTERVAL 10 SECOND)
PROPERTIES('replication_num' = '1')
as select k1, k2 from tbl1;
```

### Expected behavior (Required)
Refresh one time

### Real behavior (Required)
Refresh all the time , `fe.log` like this:
```
2022-08-16 17:48:32,501 INFO (pool-20-thread-1|126) [DatabaseTransactionMgr.commitTransaction():465] transaction:[TransactionState. txn_id: 36093, label: insert_962919d4-1d48-11ed-9811-92e32e49aa79, db id: 10003, table id list: 194035, callback id: -1, coordinator: FE: 10.136.77.222, transaction status: COMMITTED, error replicas num: 0, replica ids: , prepare time: 1660643312358, commit time: 1660643312478, finish time: -1, write cost: 120ms, reason:  attachment: com.starrocks.transaction.InsertTxnCommitAttachment@19f207cf] successfully committed
2022-08-16 17:48:32,578 INFO (PUBLISH_VERSION|32) [DatabaseTransactionMgr.finishTransaction():1038] finish transaction TransactionState. txn_id: 36093, label: insert_962919d4-1d48-11ed-9811-92e32e49aa79, db id: 10003, table id list: 194035, callback id: -1, coordinator: FE: 10.136.77.222, transaction status: VISIBLE, error replicas num: 0, replica ids: , prepare time: 1660643312358, commit time: 1660643312478, finish time: 1660643312556, write cost: 120ms, publish cost: 78ms, total cost: 198ms, reason:  attachment: com.starrocks.transaction.InsertTxnCommitAttachment@19f207cf successfully
2022-08-16 17:48:32,601 INFO (pool-20-thread-1|126) [OlapTable.renamePartition():723] rename partition mv1_no_partition in table mv1_no_partition
2022-08-16 17:48:32,623 INFO (pool-20-thread-1|126) [InsertOverwriteJobRunner.handle():115] insert overwrite job:216370 succeed. createPartitionElapse:43 ms, insertElapse:246 ms
......
......
......
2022-08-16 17:48:42,379 INFO (pool-20-thread-1|126) [DatabaseTransactionMgr.beginTransaction():296] begin transaction: txn_id: 36094 with label insert_9c1e5e95-1d48-11ed-9811-92e32e49aa79 from coordinator FE: 10.136.77.222, listner id: -1
2022-08-16 17:48:42,379 INFO (pool-20-thread-1|126) [QeProcessorImpl.registerQuery():69] register query id = 9c1e5e95-1d48-11ed-9811-92e32e49aa79, job: -1
2022-08-16 17:48:42,379 INFO (pool-20-thread-1|126) [Coordinator.prepareResultSink():593] dispatch load job: 9c1e5e95-1d48-11ed-9811-92e32e49aa79 to [TNetworkAddress(hostname:10.201.60.216, port:9061)]
2022-08-16 17:48:42,534 INFO (pool-20-thread-1|126) [DatabaseTransactionMgr.commitTransaction():465] transaction:[TransactionState. txn_id: 36094, label: insert_9c1e5e95-1d48-11ed-9811-92e32e49aa79, db id: 10003, table id list: 194035, callback id: -1, coordinator: FE: 10.136.77.222, transaction status: COMMITTED, error replicas num: 0, replica ids: , prepare time: 1660643322379, commit time: 1660643322512, finish time: -1, write cost: 133ms, reason:  attachment: com.starrocks.transaction.InsertTxnCommitAttachment@7a805a89] successfully committed
2022-08-16 17:48:42,534 INFO (PUBLISH_VERSION|32) [PublishVersionDaemon.publishVersionForOlapTable():131] send publish tasks for txn_id: 36094
2022-08-16 17:48:42,604 INFO (PUBLISH_VERSION|32) [DatabaseTransactionMgr.finishTransaction():1038] finish transaction TransactionState. txn_id: 36094, label: insert_9c1e5e95-1d48-11ed-9811-92e32e49aa79, db id: 10003, table id list: 194035, callback id: -1, coordinator: FE: 10.136.77.222, transaction status: VISIBLE, error replicas num: 0, replica ids: , prepare time: 1660643322379, commit time: 1660643322512, finish time: 1660643322581, write cost: 133ms, publish cost: 69ms, total cost: 202ms, reason:  attachment: com.starrocks.transaction.InsertTxnCommitAttachment@7a805a89 successfully
2022-08-16 17:48:42,627 INFO (pool-20-thread-1|126) [OlapTable.renamePartition():723] rename partition mv1_no_partition in table mv1_no_partition
2022-08-16 17:48:42,650 INFO (pool-20-thread-1|126) [InsertOverwriteJobRunner.handle():115] insert overwrite job:216393 succeed. createPartitionElapse:60 ms, insertElapse:252 ms
......
......
......
```

### StarRocks version (Required)
 - main

### PR DESCRIPTION
**Pull request by blackstar-baba**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #10068

## Problem Summary(Required) ：

The mv of a single partition is always refreshed. 

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 7 / 7 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/scheduler/PartitionBasedMaterializedViewRefreshProcessor.java|7|7|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 7 / 7 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/scheduler/PartitionBasedMaterializedViewRefreshProcessor.java|7|7|100.00%|[]|

**Review by ABingHuang — APPROVED** [review]
LGTM

**Review by Astralidea — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by gengjun-git — APPROVED** [review]

**Comment by Astralidea** [comment]
@Mergifyio backport branch-2.4

**Pull request merged**
