### PR TITLE
[BugFix] fix delete predicate of array type

### PR DESCRIPTION
**Pull request by murphyatwork**
## What type of PR is this：
- [ ] bugfix
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

`Delete from t0 where c1 = 1` , where `c1` column is `array<int>`, which could generate an exception, because `ArrayType::getPrimitive()` would return `INVALID_TYPE`.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/load/DeleteHandler.java|1|1|100.00%|[]|

**Comment by kangkaisen** [comment]
need to add test cases.

**Review by ZiheLiu — DISMISSED** [review]

**Comment by mofeiatwork** [comment]
@Mergifyio backport branch-2.3 branch-2.4

**Comment by mofeiatwork** [comment]
run starrocks_admit_test

**Review by Seaven — APPROVED** [review]

**Review by HangyuanLiu — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by kangkaisen — APPROVED** [review]

**Comment by mofeiatwork** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/load/DeleteHandler.java|1|1|100.00%|[]|

**Pull request merged**
