### PR TITLE
[Feature] Support adaptive DOP for Except and UNION

### PR DESCRIPTION
**Pull request by ZiheLiu**
## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Relates to #15717.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 63 / 71 (88.73%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/planner/FileTableScanNode.java|0|1|00.00%|[200]|
|:large_blue_circle:|com/starrocks/planner/HudiScanNode.java|0|1|00.00%|[187]|
|:large_blue_circle:|com/starrocks/planner/EsScanNode.java|0|1|00.00%|[297]|
|:large_blue_circle:|com/starrocks/planner/IcebergScanNode.java|0|1|00.00%|[404]|
|:large_blue_circle:|com/starrocks/planner/DeltaLakeScanNode.java|0|1|00.00%|[296]|
|:large_blue_circle:|com/starrocks/planner/DataSink.java|0|1|00.00%|[104]|
|:large_blue_circle:|com/starrocks/qe/CoordinatorPreprocessor.java|10|12|83.33%|[677, 686]|
|:large_blue_circle:|com/starrocks/planner/HashJoinNode.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/qe/SessionVariable.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/MysqlScanNode.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/AggregationNode.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/OlapScanNode.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/plan/PlanFragmentBuilder.java|5|5|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/SortNode.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/UnionNode.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/MetaScanNode.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/DeletePlanner.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/Utils.java|13|13|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/SelectNode.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/ExchangeNode.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/ExceptNode.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/UpdatePlanner.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/DecodeNode.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/JDBCScanNode.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/PlanFragment.java|8|8|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/MultiCastDataSink.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/PlanNode.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/NestLoopJoinNode.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/HdfsScanNode.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/InsertPlanner.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/DataStreamSink.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/SchemaScanNode.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/ProjectNode.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/ResultSink.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 63 / 71 (88.73%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/planner/FileTableScanNode.java|0|1|00.00%|[200]|
|:large_blue_circle:|com/starrocks/planner/HudiScanNode.java|0|1|00.00%|[187]|
|:large_blue_circle:|com/starrocks/planner/EsScanNode.java|0|1|00.00%|[297]|
|:large_blue_circle:|com/starrocks/planner/IcebergScanNode.java|0|1|00.00%|[404]|
|:large_blue_circle:|com/starrocks/planner/DeltaLakeScanNode.java|0|1|00.00%|[296]|
|:large_blue_circle:|com/starrocks/planner/DataSink.java|0|1|00.00%|[104]|
|:large_blue_circle:|com/starrocks/qe/CoordinatorPreprocessor.java|10|12|83.33%|[677, 686]|
|:large_blue_circle:|com/starrocks/planner/HashJoinNode.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/qe/SessionVariable.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/MysqlScanNode.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/AggregationNode.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/OlapScanNode.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/plan/PlanFragmentBuilder.java|5|5|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/SortNode.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/UnionNode.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/MetaScanNode.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/DeletePlanner.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/Utils.java|13|13|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/SelectNode.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/ExchangeNode.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/ExceptNode.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/UpdatePlanner.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/DecodeNode.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/JDBCScanNode.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/PlanFragment.java|8|8|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/MultiCastDataSink.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/PlanNode.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/NestLoopJoinNode.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/HdfsScanNode.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/InsertPlanner.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/DataStreamSink.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/SchemaScanNode.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/ProjectNode.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/ResultSink.java|1|1|100.00%|[]|

**Comment by ZiheLiu** [comment]
run starrocks_admit_test

**Comment by ZiheLiu** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 63 / 71 (88.73%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/planner/FileTableScanNode.java|0|1|00.00%|[200]|
|:large_blue_circle:|com/starrocks/planner/HudiScanNode.java|0|1|00.00%|[187]|
|:large_blue_circle:|com/starrocks/planner/EsScanNode.java|0|1|00.00%|[297]|
|:large_blue_circle:|com/starrocks/planner/IcebergScanNode.java|0|1|00.00%|[404]|
|:large_blue_circle:|com/starrocks/planner/DeltaLakeScanNode.java|0|1|00.00%|[296]|
|:large_blue_circle:|com/starrocks/planner/DataSink.java|0|1|00.00%|[104]|
|:large_blue_circle:|com/starrocks/qe/CoordinatorPreprocessor.java|10|12|83.33%|[677, 686]|
|:large_blue_circle:|com/starrocks/planner/HashJoinNode.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/qe/SessionVariable.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/MysqlScanNode.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/AggregationNode.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/OlapScanNode.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/plan/PlanFragmentBuilder.java|5|5|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/SortNode.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/UnionNode.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/MetaScanNode.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/DeletePlanner.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/Utils.java|13|13|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/SelectNode.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/ExchangeNode.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/ExceptNode.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/UpdatePlanner.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/DecodeNode.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/JDBCScanNode.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/PlanFragment.java|8|8|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/MultiCastDataSink.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/PlanNode.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/NestLoopJoinNode.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/HdfsScanNode.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/InsertPlanner.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/DataStreamSink.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/SchemaScanNode.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/ProjectNode.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/ResultSink.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 63 / 71 (88.73%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/planner/FileTableScanNode.java|0|1|00.00%|[200]|
|:large_blue_circle:|com/starrocks/planner/HudiScanNode.java|0|1|00.00%|[187]|
|:large_blue_circle:|com/starrocks/planner/EsScanNode.java|0|1|00.00%|[297]|
|:large_blue_circle:|com/starrocks/planner/IcebergScanNode.java|0|1|00.00%|[404]|
|:large_blue_circle:|com/starrocks/planner/DeltaLakeScanNode.java|0|1|00.00%|[296]|
|:large_blue_circle:|com/starrocks/planner/DataSink.java|0|1|00.00%|[104]|
|:large_blue_circle:|com/starrocks/qe/CoordinatorPreprocessor.java|10|12|83.33%|[677, 686]|
|:large_blue_circle:|com/starrocks/planner/HashJoinNode.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/qe/SessionVariable.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/MysqlScanNode.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/AggregationNode.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/OlapScanNode.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/plan/PlanFragmentBuilder.java|5|5|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/SortNode.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/UnionNode.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/MetaScanNode.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/DeletePlanner.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/Utils.java|13|13|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/SelectNode.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/ExchangeNode.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/ExceptNode.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/UpdatePlanner.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/DecodeNode.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/JDBCScanNode.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/PlanFragment.java|8|8|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/MultiCastDataSink.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/PlanNode.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/NestLoopJoinNode.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/HdfsScanNode.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/InsertPlanner.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/DataStreamSink.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/SchemaScanNode.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/ProjectNode.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/ResultSink.java|1|1|100.00%|[]|

**Pull request closed without merging**
