### PR TITLE
Push buck suff colocate grf down to exchange node or two sides of hashjoin according to equal conjuncts

### PR DESCRIPTION
**Pull request by satanson**
## What type of PR is this：
- [ ] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #

https://github.com/StarRocks/starrocks/pull/6445
https://github.com/StarRocks/starrocks/pull/6778
https://github.com/StarRocks/starrocks/issues/6372
https://github.com/StarRocks/starrocks/issues/6686

### CODE REVIEW

**Comment by satanson** [comment]
run starrocks_clang-format

**Comment by satanson** [comment]
run starrocks_fe_unittest

**Review by kangkaisen — APPROVED** [review]

**Comment by satanson** [comment]
run starrocks_fe_unittest

**Comment by satanson** [comment]
run starrocks_fe_unittest

**Pull request merged**
