### PR TITLE
[BugFix] Fix FE restart failed when replaying schema change job

### LINKED ISSUE #11990: [BUG] FE restart failed when replaying schema change job
### Steps to reproduce the behavior (Required)
It's not easy to reproduce this bug. But the following procedures may reproduce it.
1. create a table with dynamic partition;
2. create an add column job on that table.

### Expected behavior (Required)
System runs normally.

### Real behavior (Required)
FE exits
```java
2022-10-09 17:18:15,629 ERROR (replayer|82) [EditLog.loadJournal():887] Operation Type 121
java.lang.NullPointerException: 1881070 vs. 1882419
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:899) ~[spark-dpp-1.0.0.jar:?]
        at com.starrocks.alter.SchemaChangeJobV2.onFinished(SchemaChangeJobV2.java:594) ~[starrocks-fe.jar:?]
        at com.starrocks.alter.SchemaChangeJobV2.replayFinished(SchemaChangeJobV2.java:809) ~[starrocks-fe.jar:?]
        at com.starrocks.alter.SchemaChangeJobV2.replay(SchemaChangeJobV2.java:842) ~[starrocks-fe.jar:?]
        at com.starrocks.alter.AlterHandler.replayAlterJobV2(AlterHandler.java:416) ~[starrocks-fe.jar:?]
        at com.starrocks.persist.EditLog.loadJournal(EditLog.java:762) [starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.replayJournal(GlobalStateMgr.java:1726) [starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr$4.runOneCycle(GlobalStateMgr.java:1518) [starrocks-fe.jar:?]
        at com.starrocks.common.util.Daemon.run(Daemon.java:115) [starrocks-fe.jar:?]
```

### StarRocks version (Required)
 - all

### PR DESCRIPTION
**Pull request by gengjun-git**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #11990

## Problem Summary(Required) ：

This bug arises during the process of finishing schema change job, a partition is added to table just after the table state is change to Normal and before the alter log is written to bdb. This is a common safe problem in our system: bdb log is written outside the db lock.
To fix this bug we should write bdb log inside the db lock. But to reduce the lock occupancy time, we just put the log item to the buffer queue before releasing the db lock, and wait the log to persist outside the db lock. 

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Review by padmejin — APPROVED** [review]
After so many months my asynchronous log writer has finally shown her power!

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 14 / 14 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/persist/EditLog.java|7|7|100.00%|[]|
|:large_blue_circle:|com/starrocks/alter/SchemaChangeJobV2.java|7|7|100.00%|[]|

**Review by nshangyiming — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by sduzh — APPROVED** [review]

**Review by Astralidea — APPROVED** [review]

**Comment by gengjun-git** [comment]
@mergify backport branch-2.4

**Pull request merged**
