### PR TITLE
[Refactor] Remove cluster in ConnectContext

### PR DESCRIPTION
**Pull request by imay**
## What type of PR is this：
- [ ] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #

### CODE REVIEW

**Comment by imay** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 14 / 17 (82.35%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/http/rest/GetLoadInfoAction.java|0|1|00.00%|[51]|
|:large_blue_circle:|com/starrocks/qe/MasterOpExecutor.java|0|1|00.00%|[114]|
|:large_blue_circle:|com/starrocks/load/Load.java|0|1|00.00%|[878]|
|:large_blue_circle:|com/starrocks/analysis/RevokeStmt.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/mysql/privilege/Auth.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/ShowGrantsStmt.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/GrantStmt.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/SetPassVar.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/DropUserStmt.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/TablePattern.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/qe/ConnectContext.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/PrivilegeStmtAnalyzer.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/AlterUserStmt.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/CreateUserStmt.java|1|1|100.00%|[]|

**Review by HangyuanLiu — DISMISSED** [review]

**Review by wyb — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by imay** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 14 / 17 (82.35%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/http/rest/GetLoadInfoAction.java|0|1|00.00%|[51]|
|:large_blue_circle:|com/starrocks/qe/MasterOpExecutor.java|0|1|00.00%|[114]|
|:large_blue_circle:|com/starrocks/load/Load.java|0|1|00.00%|[878]|
|:large_blue_circle:|com/starrocks/analysis/RevokeStmt.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/mysql/privilege/Auth.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/ShowGrantsStmt.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/GrantStmt.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/SetPassVar.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/DropUserStmt.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/TablePattern.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/qe/ConnectContext.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/PrivilegeStmtAnalyzer.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/AlterUserStmt.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/CreateUserStmt.java|1|1|100.00%|[]|

**Pull request merged**
