### PR TITLE
[enhancement] Sql parser use SLL PredictionMode firstly

### PR DESCRIPTION
**Pull request by kangkaisen**
## What type of PR is this：
- [ ] bug
- [ ] feature
- [x] enhancement
- [ ] refactor
- [ ] others

According to https://github.com/StarRocks/starrocks/pull/9363 
when parse, we try SLL PredictionMode firstly.

### CODE REVIEW

**Comment by kangkaisen** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 4 / 10 (40.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/parser/SqlParser.java|4|10|40.00%|[42, 43, 44, 45, 46, 47]|

**Comment by HangyuanLiu** [comment]
The logic of antlr's parse should be done in parser.sqlStatements. Does it make sense to set PredictionMode after that? Or am I misunderstanding

**Comment by kangkaisen** [comment]
> The logic of antlr's parse should be done in parser.sqlStatements. Does it make sense to set PredictionMode after that? Or am I misunderstanding

Yes. you are right.

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 8 / 8 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/parser/SqlParser.java|8|8|100.00%|[]|

**Comment by kangkaisen** [comment]
run starrocks_be_build

**Comment by kangkaisen** [comment]
run starrocks_admit_test

**Review by HangyuanLiu — APPROVED** [review]

**Pull request closed without merging**
