### PR TITLE
[Feature] support protection for admin user

### PR DESCRIPTION
**Pull request by nshangyiming**
## What type of PR is this：
- [ ] BugFix
- [x] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes SR-16144

## Problem Summary(Required) ：

This is a product requirement from byoc, use a configuration
`authorization_enable_admin_user_protection` to control the behavior
that whether we can drop or modify roles of a user named admin.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 3.0
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Comment by nshangyiming** [comment]
run all

**Review by HangyuanLiu — DISMISSED** [review]

**Comment by nshangyiming** [comment]
run starrocks_admit_test

**Review by gengjun-git — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by gengjun-git — APPROVED** [review]

**Comment by nshangyiming** [comment]
@mergify backport branch-3.0

**Pull request merged**
