### PR TITLE
[Tool] support desensitize external table

### PR DESCRIPTION
**Pull request by packy92**
- support desensitize external table 
- add explain cost info

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [x] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:disappointed: **fail** : 7 / 236 (02.97%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/dump/DumpInfo.java|0|2|00.00%|[64, 68]|
|:large_blue_circle:|com/starrocks/http/rest/QueryDumpAction.java|0|1|00.00%|[121]|
|:large_blue_circle:|com/starrocks/sql/optimizer/dump/DesensitizedSQLBuilder.java|0|154|00.00%|[112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 127, 129, 433, 434, 435, 436, 437, 439, 440, 441, 442, 444, 445, 447, 449, 450, 451, 452, 453, 454, 455, 456, 457, 458, 460, 461, 462, 463, 464, 465, 466, 468, 469, 470, 471, 472, 473, 475, 476, 477, 478, 479, 480, 482, 483, 484, 485, 486, 489, 490, 491, 492, 493, 494, 495, 498, 499, 500, 501, 502, 503, 504, 506, 507, 508, 509, 511, 512, 516, 517, 518, 519, 520, 521, 522, 524, 525, 526, 527, 528, 531, 532, 533, 537, 538, 541, 543, 546, 547, 549, 552, 553, 554, 555, 556, 560, 561, 562, 563, 567, 568, 569, 570, 575, 576, 577, 578, 579, 580, 581, 582, 583, 584, 585, 592, 593, 594, 595, 596, 600, 601, 602, 603, 605, 607, 608, 609, 610, 612, 613, 614, 615, 616, 621, 622, 624, 644, 645, 746, 747]|
|:large_blue_circle:|com/starrocks/sql/optimizer/dump/QueryDumpSerializer.java|1|70|01.43%|[96, 175, 188, 189, 190, 191, 192, 193, 207, 208, 210, 211, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 237, 238, 240, 242, 280, 281, 282, 285, 288, 289, 290, 291, 292, 293, 297, 298, 299, 300, 301, 305, 306, 309, 313, 314, 316, 317, 318, 320, 321, 323, 325, 326, 327, 328, 329, 331, 333, 334, 335, 336]|
|:large_blue_circle:|com/starrocks/sql/optimizer/dump/QueryDumpInfo.java|2|4|50.00%|[307, 308]|
|:large_blue_circle:|com/starrocks/qe/StmtExecutor.java|1|2|50.00%|[450]|
|:large_blue_circle:|com/starrocks/sql/optimizer/dump/HiveTableDumpInfo.java|3|3|100.00%|[]|

**Review by Seaven — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:disappointed: **fail** : 7 / 236 (02.97%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/dump/DumpInfo.java|0|2|00.00%|[64, 68]|
|:large_blue_circle:|com/starrocks/http/rest/QueryDumpAction.java|0|1|00.00%|[121]|
|:large_blue_circle:|com/starrocks/sql/optimizer/dump/DesensitizedSQLBuilder.java|0|154|00.00%|[112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 127, 129, 433, 434, 435, 436, 437, 439, 440, 441, 442, 444, 445, 447, 449, 450, 451, 452, 453, 454, 455, 456, 457, 458, 460, 461, 462, 463, 464, 465, 466, 468, 469, 470, 471, 472, 473, 475, 476, 477, 478, 479, 480, 482, 483, 484, 485, 486, 489, 490, 491, 492, 493, 494, 495, 498, 499, 500, 501, 502, 503, 504, 506, 507, 508, 509, 511, 512, 516, 517, 518, 519, 520, 521, 522, 524, 525, 526, 527, 528, 531, 532, 533, 537, 538, 541, 543, 546, 547, 549, 552, 553, 554, 555, 556, 560, 561, 562, 563, 567, 568, 569, 570, 575, 576, 577, 578, 579, 580, 581, 582, 583, 584, 585, 592, 593, 594, 595, 596, 600, 601, 602, 603, 605, 607, 608, 609, 610, 612, 613, 614, 615, 616, 621, 622, 624, 644, 645, 746, 747]|
|:large_blue_circle:|com/starrocks/sql/optimizer/dump/QueryDumpSerializer.java|1|70|01.43%|[96, 175, 188, 189, 190, 191, 192, 193, 207, 208, 210, 211, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 237, 238, 240, 242, 280, 281, 282, 285, 288, 289, 290, 291, 292, 293, 297, 298, 299, 300, 301, 305, 306, 309, 313, 314, 316, 317, 318, 320, 321, 323, 325, 326, 327, 328, 329, 331, 333, 334, 335, 336]|
|:large_blue_circle:|com/starrocks/sql/optimizer/dump/QueryDumpInfo.java|2|4|50.00%|[307, 308]|
|:large_blue_circle:|com/starrocks/qe/StmtExecutor.java|1|2|50.00%|[450]|
|:large_blue_circle:|com/starrocks/sql/optimizer/dump/HiveTableDumpInfo.java|3|3|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:disappointed: **fail** : 7 / 236 (02.97%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/dump/DumpInfo.java|0|2|00.00%|[64, 68]|
|:large_blue_circle:|com/starrocks/http/rest/QueryDumpAction.java|0|1|00.00%|[121]|
|:large_blue_circle:|com/starrocks/sql/optimizer/dump/DesensitizedSQLBuilder.java|0|154|00.00%|[112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 127, 129, 433, 434, 435, 436, 437, 439, 440, 441, 442, 444, 445, 447, 449, 450, 451, 452, 453, 454, 455, 456, 457, 458, 460, 461, 462, 463, 464, 465, 466, 468, 469, 470, 471, 472, 473, 475, 476, 477, 478, 479, 480, 482, 483, 484, 485, 486, 489, 490, 491, 492, 493, 494, 495, 498, 499, 500, 501, 502, 503, 504, 506, 507, 508, 509, 511, 512, 516, 517, 518, 519, 520, 521, 522, 524, 525, 526, 527, 528, 531, 532, 533, 537, 538, 541, 543, 546, 547, 549, 552, 553, 554, 555, 556, 560, 561, 562, 563, 567, 568, 569, 570, 575, 576, 577, 578, 579, 580, 581, 582, 583, 584, 585, 592, 593, 594, 595, 596, 600, 601, 602, 603, 605, 607, 608, 609, 610, 612, 613, 614, 615, 616, 621, 622, 624, 644, 645, 746, 747]|
|:large_blue_circle:|com/starrocks/sql/optimizer/dump/QueryDumpSerializer.java|1|70|01.43%|[96, 175, 188, 189, 190, 191, 192, 193, 207, 208, 210, 211, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 237, 238, 240, 242, 280, 281, 282, 285, 288, 289, 290, 291, 292, 293, 297, 298, 299, 300, 301, 305, 306, 309, 313, 314, 316, 317, 318, 320, 321, 323, 325, 326, 327, 328, 329, 331, 333, 334, 335, 336]|
|:large_blue_circle:|com/starrocks/sql/optimizer/dump/QueryDumpInfo.java|2|4|50.00%|[307, 308]|
|:large_blue_circle:|com/starrocks/qe/StmtExecutor.java|1|2|50.00%|[450]|
|:large_blue_circle:|com/starrocks/sql/optimizer/dump/HiveTableDumpInfo.java|3|3|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by kangkaisen — APPROVED** [review]

**Review by liuyehcf — APPROVED** [review]

**Pull request merged**
