### PR TITLE
fix #5612: forbid use json as key of materialized-view

### LINKED ISSUE #5612: be crash when insert data to table which has json column and materialized view
### Steps to reproduce the behavior (Required)
```
CREATE TABLE `t1` (
  `k1` int(11) NULL COMMENT "",
  `k2` int(11) NULL COMMENT "",
  `k3` int(11) NULL COMMENT "",
  `k4` int(11) NULL COMMENT "",
  `k5` json NULL COMMENT ""
) ENGINE=OLAP
DUPLICATE KEY(`k1`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`k1`) BUCKETS 3
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"storage_format" = "DEFAULT"
);
create materialized view mv11 as select k3,k4,k5 from t1;
insert into t1 values (1,1,1,1,'{1:1,2:2}');
```
### Expected behavior (Required)
`query ok`
### Real behavior (Required)
```
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x0000000001bed472 in starrocks::ZoneMapIndexWriterImpl<(starrocks::FieldType)54>::_reset_zone_map (zone_map=0x1abb7e010, this=0x1abb7e000) at /root/starrocks/be/src/storage/olap_common.h:247
#2  starrocks::ZoneMapIndexWriterImpl<(starrocks::FieldType)54>::ZoneMapIndexWriterImpl (field=0x28ed6abd0, this=0x1abb7e000) at /root/starrocks/be/src/storage/rowset/zone_map_index.cpp:105
#3  std::make_unique<starrocks::ZoneMapIndexWriterImpl<(starrocks::FieldType)54>, starrocks::Field*&> () at /usr/include/c++/10.3.0/bits/unique_ptr.h:962
#4  starrocks::ZoneMapIndexWriterBuilder::operator()<(starrocks::FieldType)54> (field=0x28ed6abd0, this=<synthetic pointer>) at /root/starrocks/be/src/storage/rowset/zone_map_index.cpp:159
#5  starrocks::field_type_dispatch_zonemap_index<starrocks::ZoneMapIndexWriterBuilder, starrocks::Field*> (ftype=starrocks::OLAP_FIELD_TYPE_JSON, fun=...) at /root/starrocks/be/src/storage/olap_type_infra.h:183
#6  0x0000000001beecd5 in starrocks::ZoneMapIndexWriter::create (field=0x28ed6abd0) at /root/starrocks/be/src/storage/field.h:225
#7  0x0000000001b73a54 in starrocks::ScalarColumnWriter::init (this=0xffb84780) at /root/starrocks/be/src/storage/rowset/column_writer.h:126
#8  0x0000000001a17d86 in starrocks::SegmentWriter::init (this=<optimized out>, column_indexes=..., has_key=<optimized out>, footer=<optimized out>) at /root/starrocks/be/src/storage/rowset/segment_writer.cpp:162
#9  0x0000000001a18d61 in starrocks::SegmentWriter::init (this=this@entry=0x3b8af4140) at /root/starrocks/be/src/storage/rowset/segment_writer.cpp:80
#10 0x0000000001ddc114 in starrocks::HorizontalBetaRowsetWriter::_create_segment_writer (this=0x2fd8238c0) at /root/starrocks/be/src/storage/rowset/beta_rowset_writer.cpp:250
#11 0x0000000001ddd613 in starrocks::HorizontalBetaRowsetWriter::flush_chunk (this=0x2fd8238c0, chunk=...) at /root/starrocks/be/src/storage/rowset/beta_rowset_writer.cpp:290
#12 0x0000000001d8dc9d in starrocks::vectorized::MemTable::flush (this=this@entry=0x190810a00) at /root/starrocks/be/src/common/status.h:61
#13 0x0000000001b05df3 in starrocks::FlushToken::_flush_memtable (this=0x8e2ea600, memtable=0x190810a00) at /root/starrocks/be/src/storage/memtable_flush_executor.cpp:82
#14 0x0000000001b06b00 in starrocks::MemtableFlushTask::run (this=0x1165c8b0) at /root/starrocks/be/src/storage/memtable_flush_executor.cpp:42
#15 0x0000000001f55cfd in starrocks::ThreadPool::dispatch_thread (this=0x95a6c40) at /root/starrocks/be/src/util/threadpool.cpp:471
#16 0x0000000001f5150a in std::function<void ()>::operator()() const (this=0x9714478) at /usr/include/c++/10.3.0/bits/std_function.h:248
#17 starrocks::Thread::supervise_thread (arg=0x9714460) at /root/starrocks/be/src/util/thread.cpp:327
#18 0x00007fe387556ea5 in start_thread () from /lib64/libpthread.so.0
#19 0x00007fe386b718dd in clone () from /lib64/libc.so.6
```
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
mysql> select current_version();
+----------------------------+
| current_version()          |
+----------------------------+
| BRANCH-2.2-RELEASE bcd30ee |
+----------------------------+
```

### PR DESCRIPTION
**Pull request by murphyatwork**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] others

## Which issues of this PR fixes ：

Fixes #5612

## Problem Summary(Required) ：

Forbid using `JSON` as key of materialized-view.

### CODE REVIEW

**Comment by mofeiatwork** [comment]
@Mergifyio backport branch-2.2

**Review by kangkaisen — DISMISSED** [review]

**Review by ABingHuang — DISMISSED** [review]
LGTM

**Review by Astralidea — DISMISSED** [review]

**Comment by Astralidea** [comment]
LGTM

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 3 / 3 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/analysis/CreateMaterializedViewStmt.java|2|2|100.00%|
|:large_blue_circle:|com/starrocks/catalog/Type.java|1|1|100.00%|

**Review by kangkaisen — APPROVED** [review]

**Review by Astralidea — APPROVED** [review]

**Pull request merged**
