### PR TITLE
[Enhancement] colocate join need consider column equivalent conduction

### PR DESCRIPTION
**Pull request by packy92**
## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

For sql `select * from t1 join t3 on t1.id = t3.id join t2 on t3.id = t2.id`,   wheter colocate join is available need consider column equivalent conduction `t3.id = t1.id = t2.id`.

What's more, for sql `select * from t1 join t3 on t1.id = t3.age and t1.id = t3.id join t2 on t2.id = t3.age and t2.age = t3.age` the order of equivalence predicates(shuffle columns are derived from them) is meaningless, hence it is correct to use a set to save these shuffle pairs. According to the distribution column information of the left and right children, we can build distribution pairs. We can use colocate join is judged by whether all the distribution pairs are exist in the equivalent predicates set.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

### CODE REVIEW

**Review by Seaven — DISMISSED** [review]

**Review by kangkaisen — DISMISSED** [review]

**Comment by packy92** [comment]
run starrocks_fe_unittest

**Comment by packy92** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 14 / 14 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/ChildOutputPropertyGuarantor.java|14|14|100.00%|[]|

**Review by kangkaisen — APPROVED** [review]

**Review by Seaven — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by packy92** [comment]
run starrocks_admit_test

**Pull request merged**
