### PR TITLE
[Feature] [SR SQL Planner Summer Camp] add showSnapshot analyzer

### PR DESCRIPTION
**Pull request by melt-code**
## What type of PR is this：
- [ ] bug
- [x] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #7951

## Problem Summary(Required) ：

add showSnapshot analyzer

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 62 / 72 (86.11%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/ast/AstVisitor.java|0|1|00.00%|[443]|
|:large_blue_circle:|com/starrocks/sql/analyzer/ShowSnapshotAnalyzer.java|48|56|85.71%|[19, 38, 62, 63, 75, 77, 111, 117]|
|:large_blue_circle:|com/starrocks/analysis/ShowSnapshotStmt.java|6|7|85.71%|[172]|
|:large_blue_circle:|com/starrocks/sql/analyzer/Analyzer.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|6|6|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 62 / 72 (86.11%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/ast/AstVisitor.java|0|1|00.00%|[456]|
|:large_blue_circle:|com/starrocks/sql/analyzer/ShowSnapshotAnalyzer.java|48|56|85.71%|[19, 38, 62, 63, 75, 77, 111, 117]|
|:large_blue_circle:|com/starrocks/analysis/ShowSnapshotStmt.java|6|7|85.71%|[172]|
|:large_blue_circle:|com/starrocks/sql/analyzer/Analyzer.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|6|6|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 62 / 72 (86.11%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/ast/AstVisitor.java|0|1|00.00%|[422]|
|:large_blue_circle:|com/starrocks/sql/analyzer/ShowSnapshotAnalyzer.java|48|56|85.71%|[19, 37, 61, 62, 74, 76, 110, 116]|
|:large_blue_circle:|com/starrocks/analysis/ShowSnapshotStmt.java|6|7|85.71%|[172]|
|:large_blue_circle:|com/starrocks/sql/analyzer/Analyzer.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|6|6|100.00%|[]|

**Comment by melt-code** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 62 / 72 (86.11%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/ast/AstVisitor.java|0|1|00.00%|[480]|
|:large_blue_circle:|com/starrocks/sql/analyzer/ShowSnapshotAnalyzer.java|48|56|85.71%|[19, 37, 60, 61, 73, 75, 109, 115]|
|:large_blue_circle:|com/starrocks/analysis/ShowSnapshotStmt.java|6|7|85.71%|[172]|
|:large_blue_circle:|com/starrocks/sql/analyzer/Analyzer.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|6|6|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 62 / 72 (86.11%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/ast/AstVisitor.java|0|1|00.00%|[492]|
|:large_blue_circle:|com/starrocks/sql/analyzer/ShowSnapshotAnalyzer.java|48|56|85.71%|[19, 37, 60, 61, 73, 75, 109, 115]|
|:large_blue_circle:|com/starrocks/analysis/ShowSnapshotStmt.java|6|7|85.71%|[172]|
|:large_blue_circle:|com/starrocks/sql/analyzer/Analyzer.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|6|6|100.00%|[]|

**Review by HangyuanLiu — APPROVED** [review]

**Review by kangkaisen — APPROVED** [review]

**Pull request merged**
