### PR TITLE
[Refactor] Deprecated status in restful response and use code instead

### PR DESCRIPTION
**Pull request by satanson**
Fixes #issue

## What type of PR is this:
- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [x] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [x] 3.0
  - [x] 2.5
  - [ ] 2.4

### CODE REVIEW

**Review by kevincai — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 10 / 25 (40.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/http/meta/GlobalDictMetaService.java|0|2|00.00%|[98, 100]|
|:large_blue_circle:|com/starrocks/http/rest/GetLogFileAction.java|0|1|00.00%|[114]|
|:large_blue_circle:|com/starrocks/http/action/WebBaseAction.java|0|3|00.00%|[146, 153, 159]|
|:large_blue_circle:|com/starrocks/http/rest/ExecuteSqlAction.java|0|2|00.00%|[140, 141]|
|:large_blue_circle:|com/starrocks/http/rest/CheckDecommissionAction.java|0|1|00.00%|[107]|
|:large_blue_circle:|com/starrocks/http/rest/GetSmallFileAction.java|0|1|00.00%|[102]|
|:large_blue_circle:|com/starrocks/http/rest/BootstrapFinishAction.java|0|1|00.00%|[124]|
|:large_blue_circle:|com/starrocks/http/meta/ColocateMetaService.java|0|3|00.00%|[167, 195, 222]|
|:large_blue_circle:|com/starrocks/http/rest/RestBaseAction.java|2|3|66.67%|[79]|
|:large_blue_circle:|com/starrocks/http/rest/RestBaseResult.java|8|8|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 10 / 25 (40.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/http/meta/GlobalDictMetaService.java|0|2|00.00%|[98, 100]|
|:large_blue_circle:|com/starrocks/http/rest/GetLogFileAction.java|0|1|00.00%|[114]|
|:large_blue_circle:|com/starrocks/http/action/WebBaseAction.java|0|3|00.00%|[146, 153, 159]|
|:large_blue_circle:|com/starrocks/http/rest/ExecuteSqlAction.java|0|2|00.00%|[140, 141]|
|:large_blue_circle:|com/starrocks/http/rest/CheckDecommissionAction.java|0|1|00.00%|[107]|
|:large_blue_circle:|com/starrocks/http/rest/GetSmallFileAction.java|0|1|00.00%|[102]|
|:large_blue_circle:|com/starrocks/http/rest/BootstrapFinishAction.java|0|1|00.00%|[124]|
|:large_blue_circle:|com/starrocks/http/meta/ColocateMetaService.java|0|3|00.00%|[167, 195, 222]|
|:large_blue_circle:|com/starrocks/http/rest/RestBaseAction.java|2|3|66.67%|[79]|
|:large_blue_circle:|com/starrocks/http/rest/RestBaseResult.java|8|8|100.00%|[]|

**Review by imay — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 12 / 13 (92.31%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/http/rest/RestBaseResult.java|9|10|90.00%|[68]|
|:large_blue_circle:|com/starrocks/http/rest/WarehouseAction.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/http/rest/ExecuteSqlAction.java|2|2|100.00%|[]|

**Review by kevincai — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 12 / 12 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/http/rest/WarehouseAction.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/http/rest/RestBaseResult.java|9|9|100.00%|[]|
|:large_blue_circle:|com/starrocks/http/rest/ExecuteSqlAction.java|2|2|100.00%|[]|

**Review by kangkaisen — APPROVED** [review]

**Review by imay — APPROVED** [review]

**Pull request merged**
