### PR TITLE
[Bugfix]there is no partition when create mv use trunc_date(week,col1)

### LINKED ISSUE #9423: [sync materialized view]there is no partition when create mv use trunc_date(week,col1)
### Steps to reproduce the behavior (Required)
```
CREATE TABLE t1 (
                  col1 date,
                  col2 double,
                  col3 varchar(20)
                ) ENGINE=OLAP
                DUPLICATE KEY(col1)
                COMMENT "OLAP"
                PARTITION BY RANGE(`col1`)
                (
                    PARTITION p1 VALUES LESS THAN ("2020-10-01")
                )
                DISTRIBUTED BY HASH(col1) BUCKETS 3
                PROPERTIES (
                "replication_num" = "3"
                );
CREATE MATERIALIZED VIEW mv1
PARTITION BY date_trunc('week',col1)
DISTRIBUTED BY HASH(col1) BUCKETS 10
REFRESH ASYNC
AS SELECT col1, col2
FROM t1;
```
### Expected behavior (Required)
`error:week not support`
### Real behavior (Required)
`query ok`
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
mysql> select current_version();
+----------------------+
| current_version()    |
+----------------------+
| MAIN-RELEASE c3faf63 |
+----------------------+
```

### PR DESCRIPTION
**Pull request by blackstar-baba**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #9423

## Problem Summary(Required) ：

Limit `week` use

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 3 / 3 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java|3|3|100.00%|[]|

**Review by Astralidea — APPROVED** [review]

**Comment by Astralidea** [comment]
run starrocks_admit_test

**Review by ABingHuang — APPROVED** [review]
LGTM

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by Astralidea** [comment]
run starrocks_admit_test

**Comment by Astralidea** [comment]
run starrocks_admit_test

**Review by gengjun-git — APPROVED** [review]

**Pull request merged**
