### PR TITLE
[Enhancement] Support reporting exec state while query aborted

### PR DESCRIPTION
**Pull request by liuyehcf**
## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

Before this pr, the process of cancelation is:
* one fragmentInstance report error.
* fe notify other fragmentInstances to cancel execution, and won't until all fragmentInstance to report its execution status.
* be report execution status which will be simply tossed away by fe.

After this pr, the process of cancelation is:
* one fragmentInstance report error
* fe notify other fragmentInstances to cancel execution, **and will wait all fragmentInstance report its execution status.**
* **fe correctly process all the reported execution status and produce a complete profile.**

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 3.0
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Comment by liuyehcf** [comment]
run starrocks_fe_unittest

**Review by silverbullet233 — APPROVED** [review]

**Comment by liuyehcf** [comment]
run starrocks_fe_unittest

**Review by kangkaisen — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 7 / 9 (77.78%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/StmtExecutor.java|2|4|50.00%|[461, 468]|
|:large_blue_circle:|com/starrocks/qe/Coordinator.java|5|5|100.00%|[]|

**Comment by fzhedu** [comment]
how can we know which fragment encounter errors? from the profile figure?

**Review by stdpain — APPROVED** [review]

**Comment by liuyehcf** [comment]
@Mergifyio backport branch-2.5

**Comment by liuyehcf** [comment]
supported in 2.5.7 or newer.

**Pull request merged**
