### PR TITLE
bug_fix: skip use filter_unused_columns_in_scan_stage case when table…

### LINKED ISSUE #4916: BE crash when turn on enable_filter_unused_columns_in_scan_stage
### Steps to reproduce the behavior (Required)
1. CREATE TABLE `metrics_detail` (
  `tags_id` int(11) NULL COMMENT "",
  `timestamp` datetime NULL COMMENT "",
  `value` double SUM NULL COMMENT ""
) ENGINE=OLAP
AGGREGATE KEY(`tags_id`, `timestamp`)
COMMENT "OLAP"
PARTITION BY RANGE(`timestamp`)
(PARTITION p20200704 VALUES [('0000-01-01 00:00:00'), ('2020-07-05 00:00:00')))
DISTRIBUTED BY HASH(`tags_id`) BUCKETS 32
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"storage_format" = "DEFAULT"
);
2. select     subq_0.c0 as c0,    subq_0.c0 as c1 from    (select           case when ref_0.tags_id <= ref_0.tags_id then ref_0.timestamp else ref_0.timestamp end
           as c0       from          sqlsmith.metrics_detail as ref_0       where ref_0.value is NULL) as subq_0 where (subq_0.c0 is not NULL)    or (cast(nullif(cast(nullif(case when cast(null as DOUBLE) > cast(null as DOUBLE) then e() else e() end           ,         positive(           cast(case when cast(null as VARCHAR) <> cast(null as VARCHAR) then cast(null as DOUBLE) else cast(null as DOUBLE) end              as DOUBLE))) as DOUBLE),       sqrt(         cast(cast(null as DOUBLE) as DOUBLE))) as DOUBLE) <= cast(null as DOUBLE)) limit 93;

### Expected behavior (Required)
Query returns correctly

### Real behavior (Required)
```
start time: Fri Apr 8 15:47:27 CST 2022
*** Aborted at 1649404150 (unix time) try "date -d @1649404150" if you are using GNU date ***
PC: @          0x1aebd6b starrocks::vectorized::SegmentIterator::_finish_late_materialization()
*** SIGSEGV (@0xb9) received by PID 14340 (TID 0x7fdf589d8700) from PID 185; stack trace: ***
    @     0x7fdf6e20c5f0 (unknown)
    @          0x1aebd6b starrocks::vectorized::SegmentIterator::_finish_late_materialization()
    @          0x1af2b8d starrocks::vectorized::SegmentIterator::_do_get_next()
    @          0x1af5961 starrocks::vectorized::SegmentIterator::do_get_next()
    @          0x1b52ed2 starrocks::vectorized::ProjectionIterator::do_get_next()
    @          0x1e9f3aa starrocks::SegmentIteratorWrapper::do_get_next()
    @          0x1b7cb7b starrocks::vectorized::TimedChunkIterator::do_get_next()
    @          0x1b7706e starrocks::vectorized::TabletReader::do_get_next()
    @          0x1b52ed2 starrocks::vectorized::ProjectionIterator::do_get_next()
    @          0x2797e34 starrocks::vectorized::TabletScanner::get_chunk()
    @          0x24ca115 starrocks::vectorized::OlapScanNode::_scanner_thread()
    @          0x1ec99f0 starrocks::PriorityThreadPool::work_thread()
    @          0x3d20187 thread_proxy
    @     0x7fdf6e204e65 start_thread
    @     0x7fdf6d81f88d __clone
    @                0x0 (unknown)
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
branch-2.2 release 46db7d9

### PR DESCRIPTION
**Pull request by laotan332**
… is agg type

## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] others

## Which issues of this PR fixes ：

Fixes #4916

## Problem Summary(Required) ：

This feature should not be used if it is an aggregated table, because the push-down of value column expressions to the storage level is not currently supported

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/plan/PlanFragmentBuilder.java|2|2|100.00%|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 5 / 10 (50.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/plan/PlanFragmentBuilder.java|4|9|44.44%|
|:large_blue_circle:|com/starrocks/planner/OlapScanNode.java|1|1|100.00%|

**Review by HangyuanLiu — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 10 / 10 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/planner/OlapScanNode.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/sql/plan/PlanFragmentBuilder.java|9|9|100.00%|

**Review by HangyuanLiu — DISMISSED** [review]

**Review by kangkaisen — APPROVED** [review]

**Review by HangyuanLiu — APPROVED** [review]

**Comment by laotan332** [comment]
run starrocks_fe_unittest

**Pull request merged**
