### PR TITLE
[Enhancement] Rectify some behaviors when auto creating tablet

### PR DESCRIPTION
**Pull request by chaoyli**
1. When the backnum is smaller, try to creating more tablets
```
if (backendNum <= 12) {
    bucketNum = 2 * backendNum;
} else if (backendNum <= 24) {
    bucketNum = (int) (1.5 * backendNum);
} else if (backendNum <= 36) {
    bucketNum = 36;
} else {
    bucketNum = Math.min(backendNum, 48);
}
```

2. Change the behavior when user specify the tablet num (1) If the user has specified the tablet num, StarRocks will comply the number, ignore the Config.enable_auto_tablet_distribution (2) If enable_auto_tablet_distribution = true, AUTO Tablet Distibution
    also take effect on exist table when adding new partitions

3. ColocateTable should comply the original tablet num when creating table. ColocateTable should keep the tablet num is same among partitions. So the auto tablet distribution is not suitable for this case.

4. Remove the dynamic_partition.buckets After the AUTO Tablet Distibution, the dynamic_partition.buckets is not necessary. We can auto determine the number of tablet

## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [x] This pr will affect users' behaviors
- [x] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 3.0
  - [x] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Review by trueeyu — DISMISSED** [review]

**Comment by chaoyli** [comment]
run starrocks_fe_unittest

**Comment by howrocks** [comment]
Need backport to 2.5  LTS version？  2.5 will exist for a long time.

**Review by Astralidea — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by chaoyli** [comment]
run starrocks_fe_unittest

**Comment by chaoyli** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 17 / 23 (73.91%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/DynamicPartitionProperty.java|3|5|60.00%|[181, 182]|
|:large_blue_circle:|com/starrocks/common/util/DynamicPartitionUtil.java|6|8|75.00%|[132, 218]|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|3|4|75.00%|[939]|
|:large_blue_circle:|com/starrocks/catalog/CatalogUtils.java|4|5|80.00%|[232]|
|:large_blue_circle:|com/starrocks/server/OlapTableFactory.java|1|1|100.00%|[]|

**Review by Astralidea — APPROVED** [review]

**Review by trueeyu — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
