### PR TITLE
[Refactor] Refactor cloud configuration code and improve error msg report

### PR DESCRIPTION
**Pull request by Smith-Cruise**
Refactor cloud configuration code

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [x] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by dirtysalt — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 0 / 2 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/io/s3_input_stream.cpp|0|2|00.00%|[31, 33]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 114 / 127 (89.76%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/credential/azure/AzureCloudConfiguration.java|0|1|00.00%|[61]|
|:large_blue_circle:|com/starrocks/connector/hive/glue/metastore/AWSGlueClientFactory.java|0|2|00.00%|[49, 52]|
|:large_blue_circle:|com/starrocks/fs/hdfs/HdfsFsManager.java|0|1|00.00%|[619]|
|:large_blue_circle:|com/starrocks/credential/aliyun/AliyunCloudConfigurationProvider.java|8|9|88.89%|[41]|
|:large_blue_circle:|com/starrocks/credential/CloudConfigurationFactory.java|9|10|90.00%|[34]|
|:large_blue_circle:|com/starrocks/credential/gcp/GCPCloudConfigurationProvoder.java|10|11|90.91%|[45]|
|:large_blue_circle:|com/starrocks/credential/aws/AWSCloudConfigurationProvider.java|32|35|91.43%|[86, 87, 91]|
|:large_blue_circle:|com/starrocks/credential/azure/AzureCloudConfigurationProvider.java|33|36|91.67%|[75, 89, 99]|
|:large_blue_circle:|com/starrocks/credential/CredentialUtil.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/credential/aws/AWSCloudConfiguration.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/FileTable.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/credential/hdfs/HDFSCloudConfigurationProvider.java|19|19|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 114 / 127 (89.76%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/credential/azure/AzureCloudConfiguration.java|0|1|00.00%|[61]|
|:large_blue_circle:|com/starrocks/connector/hive/glue/metastore/AWSGlueClientFactory.java|0|2|00.00%|[49, 52]|
|:large_blue_circle:|com/starrocks/fs/hdfs/HdfsFsManager.java|0|1|00.00%|[619]|
|:large_blue_circle:|com/starrocks/credential/aliyun/AliyunCloudConfigurationProvider.java|8|9|88.89%|[41]|
|:large_blue_circle:|com/starrocks/credential/CloudConfigurationFactory.java|9|10|90.00%|[34]|
|:large_blue_circle:|com/starrocks/credential/gcp/GCPCloudConfigurationProvoder.java|10|11|90.91%|[45]|
|:large_blue_circle:|com/starrocks/credential/aws/AWSCloudConfigurationProvider.java|32|35|91.43%|[86, 87, 91]|
|:large_blue_circle:|com/starrocks/credential/azure/AzureCloudConfigurationProvider.java|33|36|91.67%|[75, 89, 99]|
|:large_blue_circle:|com/starrocks/credential/CredentialUtil.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/credential/aws/AWSCloudConfiguration.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/FileTable.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/credential/hdfs/HDFSCloudConfigurationProvider.java|19|19|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 0 / 2 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/io/s3_input_stream.cpp|0|2|00.00%|[31, 33]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 114 / 127 (89.76%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/credential/azure/AzureCloudConfiguration.java|0|1|00.00%|[61]|
|:large_blue_circle:|com/starrocks/connector/hive/glue/metastore/AWSGlueClientFactory.java|0|2|00.00%|[49, 52]|
|:large_blue_circle:|com/starrocks/fs/hdfs/HdfsFsManager.java|0|1|00.00%|[619]|
|:large_blue_circle:|com/starrocks/credential/aliyun/AliyunCloudConfigurationProvider.java|8|9|88.89%|[41]|
|:large_blue_circle:|com/starrocks/credential/CloudConfigurationFactory.java|9|10|90.00%|[34]|
|:large_blue_circle:|com/starrocks/credential/gcp/GCPCloudConfigurationProvoder.java|10|11|90.91%|[45]|
|:large_blue_circle:|com/starrocks/credential/aws/AWSCloudConfigurationProvider.java|32|35|91.43%|[86, 87, 91]|
|:large_blue_circle:|com/starrocks/credential/azure/AzureCloudConfigurationProvider.java|33|36|91.67%|[75, 89, 99]|
|:large_blue_circle:|com/starrocks/credential/CredentialUtil.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/credential/aws/AWSCloudConfiguration.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/FileTable.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/credential/hdfs/HDFSCloudConfigurationProvider.java|19|19|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 0 / 2 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/io/s3_input_stream.cpp|0|2|00.00%|[31, 33]|

**Review by letian-jiang — APPROVED** [review]

**Review by ZiheLiu — APPROVED** [review]

**Comment by Smith-Cruise** [comment]
@Mergify backport branch-3.1

**Pull request merged**
