### PR TITLE
[bugfix] show storage info when execute 'show create table' of laket table

### PR DESCRIPTION
**Pull request by abc982627271**
## What type of PR is this：
- [x] bugfix
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 1 / 11 (09.09%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|1|11|09.09%|[2053, 2055, 2056, 2057, 2059, 2060, 2061, 2063, 2064, 2065]|

**Review by wyb — DISMISSED** [review]

**Review by gengjun-git — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by abc982627271** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 1 / 11 (09.09%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|1|11|09.09%|[2053, 2055, 2056, 2057, 2059, 2060, 2061, 2063, 2064, 2065]|

**Review by gengjun-git — APPROVED** [review]

**Review by sduzh — APPROVED** [review]

**Comment by abc982627271** [comment]
run starrocks_admit_test

**Comment by abc982627271** [comment]
run starrocks_admit_test

**Pull request merged**
