### PR TITLE
[BugFix] Fix unknown error of profile merge mechanism

### LINKED ISSUE #9553: admin test fail tpcds query23.sql
### Steps to reproduce the behavior (Required)
Admin test fail
http://39.101.206.100:8090/job/starrocks_admit_test/1108/consoleFull
TPCDS sql: query23.sql

### Expected behavior (Required)
query success
### Real behavior (Required)
image
image

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
97fbbf7c82cb101de9736bc4d2dfaed82d86d4c5

### PR DESCRIPTION
**Pull request by liuyehcf**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #9553

## Problem Summary(Required) ：

Traverse counter in level ordered way, i.e. visit counters through its hierarchy, starting from root counter. In order to avoid missing parent counter when add child counters.

Consider the following 2 profiles. Noticing that profile1 has one counter while profile2 has two counters, and `subCnt1` is a child counter of `cnt1`. These two profiles will be merged into one profile. But if we visit count in the order `subCnt1 -> cnt1`, we may come across an assertion failure if we add `subCnt1` before `cnt1`.

```
# profile1
- cnt1
```

```
# profile2
- cnt1
    - subCnt1
```

So, the solution is straightforward, we need to traverse the counters by its hierarchy. For the above case, we must first visit `cnt1` then `subCnt1`

### CODE REVIEW

**Comment by liuyehcf** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 4 / 8 (50.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/common/util/RuntimeProfile.java|4|8|50.00%|[568, 631, 632, 634]|

**Review by kangkaisen — DISMISSED** [review]

**Comment by kangkaisen** [comment]
need to add test cases

**Comment by liuyehcf** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 44 / 51 (86.27%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/common/util/RuntimeProfile.java|44|51|86.27%|[562, 591, 593, 594, 670, 671, 674]|

**Review by kangkaisen — APPROVED** [review]

**Review by stdpain — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by liuyehcf** [comment]
@Mergifyio backport branch-2.4

**Pull request merged**
