### PR TITLE
[Refactor] abstract a getSelectedPartitionId method for CastToEmptyByPartitionRule

### PR DESCRIPTION
**Pull request by stephen-shelby**
Fixes #issue

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [x] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by Seaven — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:disappointed: **fail** : 7 / 26 (26.92%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/logical/LogicalScanOperator.java|0|1|00.00%|[133]|
|:large_blue_circle:|com/starrocks/connector/iceberg/IcebergMetadata.java|0|1|00.00%|[320]|
|:large_blue_circle:|com/starrocks/connector/paimon/PaimonMetadata.java|0|1|00.00%|[235]|
|:large_blue_circle:|com/starrocks/catalog/IcebergTable.java|0|1|00.00%|[162]|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/logical/LogicalHiveScanOperator.java|0|1|00.00%|[73]|
|:large_blue_circle:|com/starrocks/sql/optimizer/statistics/StatisticsCalculator.java|0|4|00.00%|[287, 289, 290, 294]|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/logical/LogicalHudiScanOperator.java|0|1|00.00%|[66]|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/logical/LogicalPaimonScanOperator.java|0|1|00.00%|[57]|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/logical/LogicalIcebergScanOperator.java|0|1|00.00%|[63]|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/logical/LogicalDeltaLakeScanOperator.java|0|1|00.00%|[63]|
|:large_blue_circle:|com/starrocks/connector/unified/UnifiedMetadata.java|0|1|00.00%|[151]|
|:large_blue_circle:|com/starrocks/connector/iceberg/cost/IcebergStatisticProvider.java|3|8|37.50%|[105, 122, 123, 132, 166]|
|:large_blue_circle:|com/starrocks/server/MetadataMgr.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/connector/CatalogConnectorMetadata.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:disappointed: **fail** : 7 / 26 (26.92%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/logical/LogicalScanOperator.java|0|1|00.00%|[133]|
|:large_blue_circle:|com/starrocks/connector/iceberg/IcebergMetadata.java|0|1|00.00%|[320]|
|:large_blue_circle:|com/starrocks/connector/paimon/PaimonMetadata.java|0|1|00.00%|[235]|
|:large_blue_circle:|com/starrocks/catalog/IcebergTable.java|0|1|00.00%|[162]|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/logical/LogicalHiveScanOperator.java|0|1|00.00%|[73]|
|:large_blue_circle:|com/starrocks/sql/optimizer/statistics/StatisticsCalculator.java|0|4|00.00%|[287, 289, 290, 294]|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/logical/LogicalOlapScanOperator.java|0|1|00.00%|[125]|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/logical/LogicalHudiScanOperator.java|0|1|00.00%|[66]|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/logical/LogicalPaimonScanOperator.java|0|1|00.00%|[57]|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/logical/LogicalIcebergScanOperator.java|0|1|00.00%|[63]|
|:large_blue_circle:|com/starrocks/connector/unified/UnifiedMetadata.java|0|1|00.00%|[151]|
|:large_blue_circle:|com/starrocks/connector/iceberg/cost/IcebergStatisticProvider.java|3|8|37.50%|[105, 122, 123, 132, 166]|
|:large_blue_circle:|com/starrocks/server/MetadataMgr.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/connector/CatalogConnectorMetadata.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:disappointed: **fail** : 7 / 26 (26.92%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/logical/LogicalScanOperator.java|0|1|00.00%|[133]|
|:large_blue_circle:|com/starrocks/connector/iceberg/IcebergMetadata.java|0|1|00.00%|[320]|
|:large_blue_circle:|com/starrocks/connector/paimon/PaimonMetadata.java|0|1|00.00%|[235]|
|:large_blue_circle:|com/starrocks/catalog/IcebergTable.java|0|1|00.00%|[162]|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/logical/LogicalHiveScanOperator.java|0|1|00.00%|[73]|
|:large_blue_circle:|com/starrocks/sql/optimizer/statistics/StatisticsCalculator.java|0|4|00.00%|[287, 289, 290, 294]|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/logical/LogicalOlapScanOperator.java|0|1|00.00%|[125]|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/logical/LogicalHudiScanOperator.java|0|1|00.00%|[66]|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/logical/LogicalPaimonScanOperator.java|0|1|00.00%|[57]|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/logical/LogicalIcebergScanOperator.java|0|1|00.00%|[63]|
|:large_blue_circle:|com/starrocks/connector/unified/UnifiedMetadata.java|0|1|00.00%|[151]|
|:large_blue_circle:|com/starrocks/connector/iceberg/cost/IcebergStatisticProvider.java|3|8|37.50%|[105, 122, 123, 132, 166]|
|:large_blue_circle:|com/starrocks/server/MetadataMgr.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/connector/CatalogConnectorMetadata.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by Seaven — APPROVED** [review]

**Comment by stephen-shelby** [comment]
@Mergifyio backport branch-3.2

**Pull request merged**
