### PR TITLE
[Enhancement][Lake] Does not compact table in schema change

### PR DESCRIPTION
**Pull request by sduzh**
## What type of PR is this：
- [ ] bug
- [ ] feature
- [x] enhancement
- [ ] refactor
- [ ] others

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 0 / 15 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/lake/compaction/CompactionDispatchDaemon.java|0|15|00.00%|[89, 90, 91, 107, 108, 109, 110, 111, 116, 118, 119, 120, 122, 125, 126]|

**Comment by sduzh** [comment]
run starrocks_admit_test

**Comment by sduzh** [comment]
run replayClearRollupInfo

**Comment by sduzh** [comment]
run starrocks_admit_test

**Comment by sduzh** [comment]
run starrocks_admit_test

**Comment by sduzh** [comment]
run starrocks_admit_test

**Review by wyb — DISMISSED** [review]

**Comment by sduzh** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 0 / 15 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/lake/compaction/CompactionDispatchDaemon.java|0|15|00.00%|[89, 90, 91, 107, 108, 109, 110, 111, 116, 118, 119, 120, 122, 125, 126]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 0 / 15 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/lake/compaction/CompactionDispatchDaemon.java|0|15|00.00%|[89, 90, 91, 107, 108, 109, 110, 111, 116, 118, 119, 120, 122, 125, 126]|

**Review by wyb — APPROVED** [review]

**Review by chaoyli — APPROVED** [review]

**Pull request merged**
