### PR TITLE
[BugFix] validate the view name when creating a view

### LINKED ISSUE #10472: [bug]view's name doesn't have limitation as table's name
view's name doesn't have limitation as table's name

### Expected behavior (Required)
incorrect view name

### Real behavior (Required)
image

### StarRocks version (Required)
2.3

### PR DESCRIPTION
**Pull request by padmejin**
## What type of PR is this：
- [x] bugfix
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #10472 

## Problem Summary(Required) ：

Add an extra check logic when creating the view.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by padmejin** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 4 / 5 (80.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/ViewAnalyzer.java|4|5|80.00%|[26]|

**Comment by padmejin** [comment]
run starrocks_admit_test

**Review by HangyuanLiu — APPROVED** [review]

**Review by gengjun-git — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by padmejin** [comment]
@Mergifyio backport branch-2.4 branch-2.3

**Pull request merged**
