### PR TITLE
[Enhancement][RBAC] Refine the error msg of drop func and other priv checking

### LINKED ISSUE #16966: [RBAC] refine the error message of drop func and other privilege checking logic

### PR DESCRIPTION
**Pull request by nshangyiming**
## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #16966 

## Problem Summary(Required) ：

Refine the error message when dropping function,
the existence of function should be checked in analysis phase,
and we also refine some error message on other privilege checking logic.

Signed-off-by: Dejun Xia <xiadejun@starrocks.com>

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Comment by nshangyiming** [comment]
run starrocks_fe_unittest

**Comment by nshangyiming** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 27 / 34 (79.41%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/privilege/DefaultAuthorizationProvider.java|4|8|50.00%|[74, 75, 84, 85]|
|:large_blue_circle:|com/starrocks/sql/analyzer/DropStmtAnalyzer.java|12|14|85.71%|[133, 142]|
|:large_blue_circle:|com/starrocks/sql/analyzer/PrivilegeCheckerV2.java|9|10|90.00%|[1731]|
|:large_blue_circle:|com/starrocks/common/ErrorCode.java|2|2|100.00%|[]|

**Review by imay — APPROVED** [review]

**Comment by imay** [comment]
run starrocks_admit_test

**Review by HangyuanLiu — APPROVED** [review]

**Pull request merged**
