### PR TITLE
Add Boolean as input for array_difference

### PR DESCRIPTION
**Pull request by Pslydhh**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] others

## Problem Summary(Required) ：

Add input type for boolean.

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
Can't set status; build succeeded.

**Comment by wanpengfei-git** [comment]
Can't set status; build succeeded.

**Review by murphyatwork — APPROVED** [review]

**Review by ZiheLiu — APPROVED** [review]

**Review by trueeyu — APPROVED** [review]

**Review by satanson — APPROVED** [review]

**Comment by satanson** [comment]
run starrocks_clang-format

**Comment by kangkaisen** [comment]
run starrocks_clang-format

**Pull request merged**
