### PR TITLE
[BugFix] catch exceptions on table reload

### PR DESCRIPTION
**Pull request by murphyatwork**
Fixes #issue

Without catching exceptions, reload would fail and the FE could not start.

## What type of PR is this:
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [x] 3.0
  - [x] 2.5
  - [ ] 2.4

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 23 / 33 (69.70%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|2|5|40.00%|[349, 350, 355]|
|:large_blue_circle:|com/starrocks/catalog/MaterializedView.java|21|28|75.00%|[873, 874, 875, 878, 879, 882, 883]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 22 / 32 (68.75%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|2|5|40.00%|[349, 350, 355]|
|:large_blue_circle:|com/starrocks/catalog/MaterializedView.java|20|27|74.07%|[873, 874, 875, 878, 879, 882, 883]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 8 / 11 (72.73%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|2|5|40.00%|[349, 350, 355]|
|:large_blue_circle:|com/starrocks/catalog/MaterializedView.java|6|6|100.00%|[]|

**Review by Astralidea — DISMISSED** [review]

**Comment by gengjun-git** [comment]
LocalMetastore.replayCreateTable should be cached too.

**Review by gengjun-git — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 9 / 28 (32.14%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|0|14|00.00%|[349, 351, 352, 353, 354, 355, 2030, 2031, 4763, 4765, 4766, 4767, 4768, 4769]|
|:large_blue_circle:|com/starrocks/catalog/MaterializedView.java|9|14|64.29%|[856, 857, 858, 870, 881]|

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
