### PR TITLE
[Feature] support get_json_object function

### PR DESCRIPTION
**Pull request by xuzifu666**
## What type of PR is this：
- [ ] bug
- [x] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

Introduce a new function `get_json_object`, which is compatible with Databricks SQL, and the functionality is same as `get_json_string`.

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by murphyatwork — APPROVED** [review]

**Review by rickif — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by imay — APPROVED** [review]

**Comment by imay** [comment]
@xuzifu666 You should create an issue related to it.

**Comment by xuzifu666** [comment]
> @xuzifu666 You should create an issue related to it.

https://github.com/StarRocks/starrocks/issues/9289 done @imay

**Pull request merged**
