### PR TITLE
[Refactor] Adjust stream load planner timeout reduce the db lock timeout error (#18992)

### PR DESCRIPTION
**Pull request by meegoo**
Signed-off-by: meegoo <meegoo.sr@gmail.com>
(cherry picked from commit f0195f56db63271858fdaefeec3fb46b179fcc27)

## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Comment by huoyue-git** [comment]
run all

**Comment by huoyue-git** [comment]
@rebase

**Comment by huoyue-git** [comment]
@mergify rebase

**Comment by meegoo** [comment]
@mergify rebase

**Comment by wanpengfei-git** [comment]
@Mergify rebase

**Review by gengjun-git — APPROVED** [review]

**Pull request merged**
