### PR TITLE
[BugFix] Fix wrong query state of insert statement

### PR DESCRIPTION
**Pull request by liuyehcf**
QueryState cannot represent the finished state, so I add an field to indicate if it's the final state.

## What type of PR is this:
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 30 / 101 (29.70%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/http/action/QueryAction.java|0|7|00.00%|[86, 100, 119, 128, 129, 130, 131]|
|:large_blue_circle:|com/starrocks/qe/StmtExecutor.java|21|79|26.58%|[744, 745, 746, 747, 748, 755, 756, 763, 764, 767, 768, 769, 770, 771, 772, 773, 774, 775, 776, 778, 780, 783, 785, 786, 789, 791, 792, 794, 796, 797, 798, 799, 801, 802, 803, 806, 807, 809, 811, 814, 815, 817, 819, 820, 822, 823, 825, 826, 827, 828, 830, 831, 834, 835, 837, 838, 839, 840]|
|:large_blue_circle:|com/starrocks/qe/QueryState.java|9|15|60.00%|[194, 200, 203, 205, 207, 209]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 32 / 104 (30.77%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/http/action/QueryAction.java|0|7|00.00%|[86, 100, 119, 128, 129, 130, 131]|
|:large_blue_circle:|com/starrocks/qe/StmtExecutor.java|23|82|28.05%|[641, 744, 745, 746, 747, 748, 755, 756, 763, 764, 767, 768, 769, 770, 771, 772, 773, 774, 775, 776, 778, 780, 783, 785, 786, 789, 791, 792, 794, 796, 797, 798, 799, 801, 802, 803, 806, 807, 809, 811, 814, 815, 817, 819, 820, 822, 823, 825, 826, 827, 828, 830, 831, 834, 835, 837, 838, 839, 840]|
|:large_blue_circle:|com/starrocks/qe/QueryState.java|9|15|60.00%|[194, 200, 203, 205, 207, 209]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 32 / 104 (30.77%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/http/action/QueryAction.java|0|7|00.00%|[86, 100, 119, 128, 129, 130, 131]|
|:large_blue_circle:|com/starrocks/qe/StmtExecutor.java|23|82|28.05%|[641, 744, 745, 746, 747, 748, 755, 756, 763, 764, 767, 768, 769, 770, 771, 772, 773, 774, 775, 776, 778, 780, 783, 785, 786, 789, 791, 792, 794, 796, 797, 798, 799, 801, 802, 803, 806, 807, 809, 811, 814, 815, 817, 819, 820, 822, 823, 825, 826, 827, 828, 830, 831, 834, 835, 837, 838, 839, 840]|
|:large_blue_circle:|com/starrocks/qe/QueryState.java|9|15|60.00%|[194, 200, 203, 205, 207, 209]|

**Review by LiShuMing — APPROVED** [review]

**Review by stephen-shelby — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 5 / 9 (55.56%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/QueryState.java|5|9|55.56%|[126, 192, 194, 195]|

**Review by Seaven — APPROVED** [review]

**Review by kangkaisen — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Pull request merged**
