### PR TITLE
[BugFix] orc scanner should be case sensitive

### LINKED ISSUE #12711: BE crashes when broker load with orc file which has uppercase field
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
2. INSERT INTO '....'
3. SELECT  '....'

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

2.3.3

link to: SR-13254

### PR DESCRIPTION
**Pull request by dirtysalt**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #12711 #12587

it's introduced in this PR: https://github.com/StarRocks/starrocks/pull/9744. 

For orc broker load, we don't need to consider case-sensitive or not. It has been always case-sensitive before, so we have to  keep backward-compatiblity.

## Problem Summary(Required) ：

TODO: will add it later.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
starrocks_be_unittest succeeded.

**Comment by GavinMar** [comment]
It means case-insensitve will not be supported in orc scanner?

**Comment by dirtysalt** [comment]
> It means case-insensitve will not be supported in orc scanner?

It's never been supported by orc scanner.

**Review by GavinMar — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
starrocks_be_unittest succeeded.

**Review by Smith-Cruise — APPROVED** [review]
LGTM

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by zombee0 — APPROVED** [review]

**Review by Youngwb — APPROVED** [review]

**Review by trueeyu — APPROVED** [review]

**Pull request merged**
