### PR TITLE
[Refactor] Remove FE config max_broker_concurrency

### PR DESCRIPTION
**Pull request by meegoo**
Fixes #issue

## What type of PR is this:
- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [x] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [ ] I have added test cases for my bug fix or my new feature
- [x] This pr will affect users' behaviors
- [x] This pr needs user documentation (for new or modified features or behaviors)
  - [x] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4

### CODE REVIEW

**Comment by imay** [comment]
@meegoo Why do you remove this configuration?

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by meegoo** [comment]
> @meegoo Why do you remove this configuration?

Currently, we have limited the number of concurrent broker load jobs by `max_broker_load_job_concurrency`, and it is also possible to set the parallelism of an individual broker load job through `pipeline_dop`. so that this restriction may not have significant implications and can increase user usage costs. It can also limit the out-of-the-box performance of larger-scale clusters.

**Review by imay — APPROVED** [review]

**Review by Astralidea — APPROVED** [review]

**Comment by meegoo** [comment]
@mergify backport branch-3.1

**Comment by amber-create** [comment]
updated docs at https://github.com/StarRocks/docs.zh-cn/pull/6067 & https://github.com/StarRocks/starrocks/pull/27523

**Pull request merged**
