### PR TITLE
[BugFix] Traverse all the candidates to find path to clone from

### PR DESCRIPTION
**Pull request by nshangyiming**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes SR-11672

## Problem Summary(Required) ：

Currently, when taking a slot from one candidate, replica failed, and the entire tablet schedule task failed,  we should also try other candidates. Besides, when filtering candidates, replicas in DECOMMISSION state should be ignored because these replicas can be deleted at any time.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Review by chaoyli — APPROVED** [review]

**Review by decster — COMMENTED** [review]
are you sure DECOMMISSION should be excluded? The purpose of DECOMMISSION is to move replica in this DECOMMISSION host to another host.
Also what if a tablet that only have 1 replica.

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 7 / 7 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/clone/TabletSchedCtx.java|7|7|100.00%|[]|

**Comment by nshangyiming** [comment]
> are you sure DECOMMISSION should be excluded? The purpose of DECOMMISSION is to move replica in this DECOMMISSION host to another host. Also what if a tablet that only have 1 replica.

@decster replica's DECOMMISSION state is not the same as backend's DECOMMISSION state, replica's state is set to DECOMMISSION only when it's going to be deleted(only set in `deleteReplicaInternal()`) after clone finished. Indeed the two DECOMMISSIONs can easily cause misunderstanding. And if if a tablet that only have 1 replica, it shound't be set to DECOMMISSION state unless you forcefully do that.

**Review by decster — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Pull request merged**
