### PR TITLE
[Enhancement] Add compaction and too many versions write error UT

### LINKED ISSUE #10405: [Enhancement] Add PseudoCluster UT for write txn failures
## Enhancement

  - Too many versions
  - Too many pending versions
  - Memory limit exceed
  - write/publish high latency
  - TXN canceled (caused by timeout or data error)

### PR DESCRIPTION
**Pull request by decster**
## What type of PR is this：
- [ ] bugfix
- [ ] feature
- [x] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #10405

## Problem Summary(Required) ：

Add compaction and too many versions write error UT for PseudoCluster

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by decster** [comment]
run starrocks_fe_unittest

**Comment by wangruin** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by decster** [comment]
run starrocks_admit_test

**Review by chaoyli — APPROVED** [review]

**Review by Astralidea — APPROVED** [review]

**Pull request merged**
