### PR TITLE
[Enhancement] Optimize error message of insert overwrite

### LINKED ISSUE #10284: [insert overwrite]insert overwrite primary table failed when value is null
### Steps to reproduce the behavior (Required)
```
CREATE TABLE t2 ( k1 INT, k2 INT ) PRIMARY KEY(k1) DISTRIBUTED BY HASH(k1) BUCKETS 10;
INSERT OVERWRITE t2 VALUES (null,1);
```
### Expected behavior (Required)
`ERROR 1064 (HY000): Insert has filtered data in strict mode, tracking_url=http://xxx.xxx.xxx.xxx:xxxx/api/_load_error_log?file=error_log_e741a24d21c711ed_8a7f00163e14c85f`
### Real behavior (Required)
```
2022-08-20 17:24:48,595 WARN (starrocks-mysql-nio-pool-223|2911) [StmtExecutor.execute():490] execute Exception, sql INSERT OVERWRITE primary_tbl SELECT * FROM t1
java.lang.RuntimeException: execute insert failed
	at com.starrocks.load.InsertOverwriteJobRunner.executeInsert(InsertOverwriteJobRunner.java:192) ~[starrocks-fe.jar:?]
	at com.starrocks.load.InsertOverwriteJobRunner.doLoad(InsertOverwriteJobRunner.java:127) ~[starrocks-fe.jar:?]
	at com.starrocks.load.InsertOverwriteJobRunner.handle(InsertOverwriteJobRunner.java:107) ~[starrocks-fe.jar:?]
	at com.starrocks.load.InsertOverwriteJobRunner.transferTo(InsertOverwriteJobRunner.java:170) ~[starrocks-fe.jar:?]
	at com.starrocks.load.InsertOverwriteJobRunner.prepare(InsertOverwriteJobRunner.java:181) ~[starrocks-fe.jar:?]
	at com.starrocks.load.InsertOverwriteJobRunner.handle(InsertOverwriteJobRunner.java:104) ~[starrocks-fe.jar:?]
	at com.starrocks.load.InsertOverwriteJobRunner.run(InsertOverwriteJobRunner.java:92) ~[starrocks-fe.jar:?]
	at com.starrocks.load.InsertOverwriteJobManager.executeJob(InsertOverwriteJobManager.java:76) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.StmtExecutor.handleInsertOverwrite(StmtExecutor.java:1091) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.StmtExecutor.handleDMLStmt(StmtExecutor.java:1119) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:442) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:317) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:432) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:670) ~[starrocks-fe.jar:?]
	at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:55) ~[starrocks-fe.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
2022-08-20 17:24:48,595 WARN (starrocks-mysql-nio-pool-223|2911) [Coordinator.cancel():1332] cancel execution of query, this is outside invoke
```
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
+----------------------------+
| current_version()          |
+----------------------------+
| BRANCH-2.4-RELEASE 5ca24bb |
+----------------------------+
```

### PR DESCRIPTION
**Pull request by ABingHuang**
## What type of PR is this：
- [ ] bug
- [ ] feature
- [x] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #10284 

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 37 / 44 (84.09%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/load/InsertOverwriteJobRunner.java|12|15|80.00%|[193, 245, 266]|
|:large_blue_circle:|com/starrocks/load/PartitionUtils.java|25|29|86.21%|[44, 45, 46, 47]|

**Review by Astralidea — DISMISSED** [review]

**Review by gengjun-git — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 38 / 44 (86.36%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/load/PartitionUtils.java|25|29|86.21%|[44, 45, 46, 47]|
|:large_blue_circle:|com/starrocks/load/InsertOverwriteJobRunner.java|13|15|86.67%|[245, 266]|

**Comment by ABingHuang** [comment]
run starrocks_admit_test

**Review by Astralidea — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 12 / 15 (80.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/load/InsertOverwriteJobRunner.java|12|15|80.00%|[202, 254, 275]|

**Comment by ABingHuang** [comment]
run starrocks_admit_test

**Review by Astralidea — APPROVED** [review]

**Review by gengjun-git — APPROVED** [review]

**Pull request merged**
