### PR TITLE
[BugFix] Fix multi count distinct rewite bug

### PR DESCRIPTION
**Pull request by Seaven**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

```
MySQL td> explain select
      count(distinct v2) x1,
      count(distinct v1) x2
from t1
limit 1

(1064, 'There are multi count(distinct) function call, multi distinct rewrite error')
````

because CTE rewrite rule doesn't handle `limit 1`

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Comment by Seaven** [comment]
run starrocks_fe_unittest

**Comment by Seaven** [comment]
run starrocks_be_unittest

**Comment by Seaven** [comment]
run all

**Comment by Seaven** [comment]
run all

**Review by kangkaisen — APPROVED** [review]

**Review by liuyehcf — APPROVED** [review]

**Pull request merged**
