### PR TITLE
[Enhancement] Enable partial update to be used with condition update

### PR DESCRIPTION
**Pull request by sevev**
Actually we can do partial update with condition update, but we reject it. This pr enable it.

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [x] Yes, this PR will result in a change in behavior.
- [ ] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [x] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:disappointed: **fail** : 3 / 11 (27.27%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/load/routineload/PulsarRoutineLoadJob.java|0|1|00.00%|[414]|
|:large_blue_circle:|com/starrocks/load/Load.java|0|7|00.00%|[138, 139, 140, 142, 144, 148, 151]|
|:large_blue_circle:|com/starrocks/planner/StreamLoadPlanner.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/load/loadv2/LoadingTaskPlanner.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/load/routineload/KafkaRoutineLoadJob.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 1 / 3 (33.33%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/storage/delta_writer.cpp|0|2|00.00%|[231, 232]|
|:large_blue_circle:|src/storage/rowset_update_state.cpp|1|1|100.00%|[]|

**Review by decster — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 11 / 12 (91.67%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/load/routineload/PulsarRoutineLoadJob.java|0|1|00.00%|[414]|
|:large_blue_circle:|com/starrocks/planner/StreamLoadPlanner.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/load/loadv2/LoadingTaskPlanner.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/load/routineload/KafkaRoutineLoadJob.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/load/Load.java|7|7|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/LoadStmt.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 1 / 3 (33.33%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/storage/delta_writer.cpp|0|2|00.00%|[231, 232]|
|:large_blue_circle:|src/storage/rowset_update_state.cpp|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 11 / 12 (91.67%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/load/routineload/PulsarRoutineLoadJob.java|0|1|00.00%|[414]|
|:large_blue_circle:|com/starrocks/planner/StreamLoadPlanner.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/load/loadv2/LoadingTaskPlanner.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/load/routineload/KafkaRoutineLoadJob.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/load/Load.java|7|7|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/LoadStmt.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 1 / 3 (33.33%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/storage/delta_writer.cpp|0|2|00.00%|[231, 232]|
|:large_blue_circle:|src/storage/rowset_update_state.cpp|1|1|100.00%|[]|

**Review by chaoyli — APPROVED** [review]

**Comment by decster** [comment]
@mergify backport branch-3.1

**Pull request merged**
