### PR TITLE
[BugFix] Fix str2date partitioned mv for main (#31964)

### PR DESCRIPTION
**Pull request by ABingHuang**
Fix str2date partitioned mv

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Review by Youngwb — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by Youngwb — DISMISSED** [review]

**Review by Astralidea — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 78 / 84 (92.86%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/scheduler/PartitionBasedMvRefreshProcessor.java|20|24|83.33%|[1286, 1287, 1288, 1289]|
|:large_blue_circle:|com/starrocks/connector/PartitionUtil.java|25|27|92.59%|[556, 557]|
|:large_blue_circle:|com/starrocks/catalog/MaterializedView.java|14|14|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/PartitionKey.java|6|6|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/common/SyncPartitionUtils.java|11|11|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/MvUtils.java|2|2|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 78 / 84 (92.86%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/scheduler/PartitionBasedMvRefreshProcessor.java|20|24|83.33%|[1286, 1287, 1288, 1289]|
|:large_blue_circle:|com/starrocks/connector/PartitionUtil.java|25|27|92.59%|[556, 557]|
|:large_blue_circle:|com/starrocks/catalog/MaterializedView.java|14|14|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/PartitionKey.java|6|6|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/common/SyncPartitionUtils.java|11|11|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/MvUtils.java|2|2|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 73 / 86 (84.88%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/MvUtils.java|2|6|33.33%|[1275, 1276, 1277, 1278]|
|:large_blue_circle:|com/starrocks/scheduler/PartitionBasedMvRefreshProcessor.java|13|17|76.47%|[1278, 1279, 1280, 1281]|
|:large_blue_circle:|com/starrocks/catalog/MaterializedView.java|16|19|84.21%|[555, 558, 559]|
|:large_blue_circle:|com/starrocks/connector/PartitionUtil.java|25|27|92.59%|[556, 557]|
|:large_blue_circle:|com/starrocks/catalog/PartitionKey.java|6|6|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/common/SyncPartitionUtils.java|11|11|100.00%|[]|

**Review by murphyatwork — APPROVED** [review]

**Review by Astralidea — APPROVED** [review]

**Pull request merged**
