### PR TITLE
[Feature] Implement MetadataMgr

### PR DESCRIPTION
**Pull request by stephen-shelby**
## What type of PR is this：
- [ ] bug
- [x] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #
related with https://github.com/StarRocks/starrocks/issues/6430

related with https://github.com/StarRocks/starrocks/issues/5062

## Problem Summary(Required) ：

Improve MetadataMgr
- Implement metadata interface about internal and external catalog
- Add readWrite Lock
- Implement `getDb()` at HiveMetadata
- Implement `listTableNames()` and `getTable()` at LocalMetastore

### CODE REVIEW

**Comment by stephen-shelby** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 28 / 78 (35.90%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/connector/hive/HiveMetadata.java|0|1|00.00%|
|:large_blue_circle:|com/starrocks/server/CatalogMgr.java|0|1|00.00%|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|0|4|00.00%|
|:large_blue_circle:|com/starrocks/external/hive/HiveMetaStoreThriftClient.java|0|1|00.00%|
|:large_blue_circle:|com/starrocks/external/hive/HiveMetaClient.java|0|5|00.00%|
|:large_blue_circle:|com/starrocks/connector/ConnectorDatabaseId.java|1|6|16.67%|
|:large_blue_circle:|com/starrocks/external/hive/HiveMetaCache.java|2|9|22.22%|
|:large_blue_circle:|com/starrocks/server/MetadataMgr.java|22|47|46.81%|
|:large_blue_circle:|com/starrocks/external/HiveMetaStoreTableUtils.java|1|2|50.00%|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|2|2|100.00%|

**Review by caneGuy — DISMISSED** [review]

**Comment by stephen-shelby** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 77 / 85 (90.59%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/external/hive/HiveMetaStoreThriftClient.java|0|1|00.00%|
|:large_blue_circle:|com/starrocks/external/hive/HiveMetaClient.java|2|5|40.00%|
|:large_blue_circle:|com/starrocks/connector/ConnectorDatabaseId.java|4|6|66.67%|
|:large_blue_circle:|com/starrocks/server/MetadataMgr.java|45|47|95.74%|
|:large_blue_circle:|com/starrocks/connector/hive/HiveMetadata.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/server/CatalogMgr.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/external/hive/HiveMetaCache.java|11|11|100.00%|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|9|9|100.00%|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|2|2|100.00%|
|:large_blue_circle:|com/starrocks/external/HiveMetaStoreTableUtils.java|2|2|100.00%|

**Review by gengjun-git — APPROVED** [review]

**Review by caneGuy — APPROVED** [review]

**Pull request merged**
