### PR TITLE
[BugFix] MV rewrite with cast expression

### LINKED ISSUE #17212: Rewrite MV with cast expression
### Steps to reproduce the behavior (Required)
```sql
CREATE MATERIALIZED VIEW `mv_q15` DISTRIBUTED BY HASH(`gender`) BUCKETS 2 REFRESH ASYNC AS
SELECT
        CAST((`d_user` -> 'gender') AS string) AS `gender`,
        count(d_user) AS `cnt`
FROM
        `json_tbl`
GROUP BY
        `gender`;

SELECT
        CAST((`d_user` -> 'gender') AS string) AS `gender`,
        count(d_user) AS `cnt`
FROM
        `json_tbl`
GROUP BY
        `gender`;
```

### Expected behavior (Required)

The query should be rewritten to MV, but actually it's not.

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - 2.5

### PR DESCRIPTION
**Pull request by murphyatwork**
Signed-off-by: Murphy <mofei@starrocks.com>

## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #17212

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Comment by mofeiatwork** [comment]
run starrocks_admit_test

**Review by ABingHuang — APPROVED** [review]
LGTM

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java|2|2|100.00%|[]|

**Review by satanson — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by mofeiatwork** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
