### PR TITLE
[WIP] try to eliminate unused include by iwyu

### PR DESCRIPTION
**Pull request by murphyatwork**
## What type of PR is this：
- [ ] bug
- [ ] feature
- [x] enhancement
- [ ] others

## Motivation
Try to eliminate unused include or transitive include by iwyu.

### CODE REVIEW

**Comment by decster** [comment]
Why for most files, this tool only adds more includes rather than remove some unused includes

**Comment by mofeiatwork** [comment]
> 

This tool has failed me. As you see, it does not remove headers.

I guess, one possible reason is that we have put too much code in the header, and they require complete type definition, which could not be replaced with a forward declaration or remove any header.

So, the next investigation step is trying to refactor those **huge header** into cpp file, and try this tool again. 

Do you have any other ideas?

**Comment by mofeiatwork** [comment]
After some analysis of header dependency, I found that several huge header files introduce too much transitive dependencies.

- `column_helper.h`: included by 114 files, and including `column/type_traits.h`, `runtime/primitive_type.h`, which is also very huge
- `runtime/primitive_type.h`: included by 72 files, and including `gen_cpp/Opcodes_types.h`, `gen_cpp/Types_types.h`, which is very huge

I will begin with these two files.

**Comment by mofeiatwork** [comment]
run starrocks_be_unittest

**Pull request closed without merging**
