### PR TITLE
[BugFix] fix case when not been rewrite correctly

### PR DESCRIPTION
**Pull request by packy92**
Fixes 
For sql like `select * from t0 where if(v2 > 4, 1, 0) != 1` the plan is
```
PLAN FRAGMENT 0
 OUTPUT EXPRS:1: v1 | 2: v2 | 3: v3
  PARTITION: RANDOM

  RESULT SINK

  0:OlapScanNode
     TABLE: t0
     PREAGGREGATION: ON
     PREDICATES: 2: v2 <= 4, 2: v2 <= 4 IS NOT NULL
     partitions=0/1
     rollup: t0
     tabletRatio=0/0
     tabletList=
     cardinality=1
     avgRowSize=3.0
```
The rewrite result of if function is wrong when v2 is nullable.

## What type of PR is this:
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [x] 3.0
  - [x] 2.5
  - [ ] 2.4

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 103 / 113 (91.15%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/SessionVariable.java|2|4|50.00%|[2223, 2224]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rewrite/scalar/NegateFilterShuttle.java|6|10|60.00%|[42, 43, 44, 46]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rewrite/scalar/InvertedCaseWhen.java|85|89|95.51%|[81, 349, 350, 442]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rewrite/ScalarRangePredicateExtractor.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rewrite/scalar/PruneTediousPredicateRule.java|7|7|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/PushDownPredicateScanRule.java|2|2|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 103 / 113 (91.15%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/SessionVariable.java|2|4|50.00%|[2223, 2224]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rewrite/scalar/NegateFilterShuttle.java|6|10|60.00%|[42, 43, 44, 46]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rewrite/scalar/InvertedCaseWhen.java|85|89|95.51%|[81, 349, 350, 442]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rewrite/ScalarRangePredicateExtractor.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rewrite/scalar/PruneTediousPredicateRule.java|7|7|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/PushDownPredicateScanRule.java|2|2|100.00%|[]|

**Review by satanson — APPROVED** [review]

**Review by Seaven — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
