### PR TITLE
[Feature] support update lake table colocation info by http api

### PR DESCRIPTION
**Pull request by starrocks-xupeng**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 3.0
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Review by sduzh — APPROVED** [review]

**Review by wyb — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by starrocks-xupeng** [comment]
run starrocks_fe_test

**Comment by starrocks-xupeng** [comment]
run starrocks_fe_unittest

**Comment by starrocks-xupeng** [comment]
run starrocks_fe_unittest

**Comment by starrocks-xupeng** [comment]
run starrocks_fe_unittest

**Comment by starrocks-xupeng** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 15 / 74 (20.27%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/http/meta/ColocateMetaService.java|5|58|08.62%|[225, 226, 227, 228, 230, 231, 232, 233, 234, 236, 237, 238, 239, 240, 242, 243, 244, 245, 246, 247, 249, 250, 251, 252, 253, 254, 256, 257, 258, 259, 261, 262, 264, 267, 268, 269, 270, 271, 273, 275, 276, 277, 278, 279, 281, 282, 283, 284, 286, 287, 288, 290, 292]|
|:large_blue_circle:|com/starrocks/catalog/ColocateTableIndex.java|4|8|50.00%|[1005, 1010, 1011, 1012]|
|:large_blue_circle:|com/starrocks/load/InsertOverwriteJobRunner.java|2|4|50.00%|[322, 324]|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/alter/LakeTableSchemaChangeJob.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/http/HttpServer.java|1|1|100.00%|[]|

**Pull request merged**
