### PR TITLE
[Enhancement] allow set operation in materialized view

### LINKED ISSUE #15314: Support UNION statement in async materialized views
## Enhancement
A query with UNION statement while creating MVs returns an error.
Example
```
create materialized view temp_tok_bal
    distributed by hash(a)
    refresh async
    as
    select a,b from table1,table2
    union all
    select a,b from table1,table2
```

Throws the error
```
ERROR 1064 (HY000): Materialized view query statement only support select
```

### PR DESCRIPTION
**Pull request by murphyatwork**
## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #15314

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Comment by mofeiatwork** [comment]
run starrocks_admit_test

**Review by kangkaisen — APPROVED** [review]

**Review by Seaven — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by mofeiatwork** [comment]
run starrocks_admit_test

**Comment by mofeiatwork** [comment]
run starrocks_admit_test

**Review by ABingHuang — APPROVED** [review]
LGTM

**Comment by mofeiatwork** [comment]
run starrocks_admit_test

**Pull request merged**
