### PR TITLE
Remove some old Analyzer codes 4

### PR DESCRIPTION
**Pull request by kangkaisen**
## What type of PR is this：
- [ ] bug
- [ ] feature
- [ ] enhancement
- [x] refactor
- [ ] others

### CODE REVIEW

**Comment by Astralidea** [comment]
run starrocks_admit_test

**Review by Astralidea — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 0 / 2 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/planner/OlapScanNode.java|0|2|00.00%|[393, 394]|

**Comment by kangkaisen** [comment]
The daily test has passed.

**Review by Astralidea — APPROVED** [review]

**Comment by Astralidea** [comment]
run starrocks_admit_test

**Review by liuyehcf — APPROVED** [review]

**Review by satanson — APPROVED** [review]

**Comment by kangkaisen** [comment]
run starrocks_admit_test

**Pull request merged**
