### PR TITLE
[BugFix] Fix hive partition columns statistics type is UNKNOWN

### LINKED ISSUE #10306: Hive partition column statistics type is UNKNOWN
### Steps to reproduce the behavior (Required)
1. CREATE TABLE hive partition table  `parttbl`
2. analyze table `parttb`l COMPUTE STATISTICS FOR COLUMNS;
3. refresh statistics cache in SR
4. explain select * from parttbl

### Expected behavior (Required)
get right column statistics

### Real behavior (Required)
image

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by Youngwb**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #10306 

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 4 / 4 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/external/hive/HiveColumnStats.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/external/hive/HiveMetaClient.java|1|1|100.00%|[]|

**Review by stephen-shelby — COMMENTED** [review]
LGTM

**Review by stephen-shelby — APPROVED** [review]

**Review by imay — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by dirtysalt — APPROVED** [review]

**Comment by Youngwb** [comment]
run starrocks_admit_test

**Pull request merged**
