### PR TITLE
[Enhancement] Support refresh hive view

### PR DESCRIPTION
**Pull request by Youngwb**
Fixes #issue
Support refresh hive view
## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.2
  - [x] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:disappointed: **fail** : 19 / 30 (63.33%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/HiveView.java|0|1|00.00%|[84]|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|0|3|00.00%|[3784, 3793, 3794]|
|:large_blue_circle:|com/starrocks/connector/hive/IHiveMetastore.java|0|1|00.00%|[80]|
|:large_blue_circle:|com/starrocks/connector/hive/CacheUpdateProcessor.java|4|9|44.44%|[96, 97, 98, 99, 101]|
|:large_blue_circle:|com/starrocks/connector/hive/CachingHiveMetastore.java|15|16|93.75%|[472]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:disappointed: **fail** : 19 / 30 (63.33%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/HiveView.java|0|1|00.00%|[84]|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|0|3|00.00%|[3784, 3793, 3794]|
|:large_blue_circle:|com/starrocks/connector/hive/IHiveMetastore.java|0|1|00.00%|[80]|
|:large_blue_circle:|com/starrocks/connector/hive/CacheUpdateProcessor.java|4|9|44.44%|[96, 97, 98, 99, 101]|
|:large_blue_circle:|com/starrocks/connector/hive/CachingHiveMetastore.java|15|16|93.75%|[472]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:disappointed: **fail** : 22 / 30 (73.33%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|0|3|00.00%|[3784, 3793, 3794]|
|:large_blue_circle:|com/starrocks/connector/hive/CacheUpdateProcessor.java|5|9|55.56%|[97, 98, 99, 101]|
|:large_blue_circle:|com/starrocks/connector/hive/CachingHiveMetastore.java|15|16|93.75%|[472]|
|:large_blue_circle:|com/starrocks/catalog/HiveView.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/connector/hive/IHiveMetastore.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:disappointed: **fail** : 22 / 30 (73.33%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|0|3|00.00%|[3784, 3793, 3794]|
|:large_blue_circle:|com/starrocks/connector/hive/CacheUpdateProcessor.java|5|9|55.56%|[97, 98, 99, 101]|
|:large_blue_circle:|com/starrocks/connector/hive/CachingHiveMetastore.java|15|16|93.75%|[472]|
|:large_blue_circle:|com/starrocks/catalog/HiveView.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/connector/hive/IHiveMetastore.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 25 / 30 (83.33%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|0|3|00.00%|[3784, 3793, 3794]|
|:large_blue_circle:|com/starrocks/connector/hive/CacheUpdateProcessor.java|8|9|88.89%|[99]|
|:large_blue_circle:|com/starrocks/connector/hive/CachingHiveMetastore.java|15|16|93.75%|[472]|
|:large_blue_circle:|com/starrocks/catalog/HiveView.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/connector/hive/IHiveMetastore.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 25 / 30 (83.33%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|0|3|00.00%|[3784, 3793, 3794]|
|:large_blue_circle:|com/starrocks/connector/hive/CacheUpdateProcessor.java|8|9|88.89%|[99]|
|:large_blue_circle:|com/starrocks/connector/hive/CachingHiveMetastore.java|15|16|93.75%|[472]|
|:large_blue_circle:|com/starrocks/catalog/HiveView.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/connector/hive/IHiveMetastore.java|1|1|100.00%|[]|

**Review by stephen-shelby — APPROVED** [review]

**Review by gengjun-git — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.2

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Pull request merged**
