### PR TITLE
[refactor] refactor AnalyzeJob to NativeAnalyzeJob

### PR DESCRIPTION
**Pull request by Youngwb**
#23327
1. Rename  AnalyzeJob to NativeAnalyzeJob
2. Abstracts AnalyzeJob into an interface

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [x] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [x] Yes, this PR will result in a change in behavior.
- [ ] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [ ] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:disappointed: **fail** : 72 / 141 (51.06%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/journal/JournalEntity.java|0|2|00.00%|[884, 889]|
|:large_blue_circle:|com/starrocks/qe/DDLStmtExecutor.java|0|7|00.00%|[767, 768, 769, 770, 771, 773, 777]|
|:large_blue_circle:|com/starrocks/persist/EditLog.java|2|8|25.00%|[909, 910, 914, 915, 1910, 1911]|
|:large_blue_circle:|com/starrocks/statistic/AnalyzeMgr.java|2|6|33.33%|[547, 576, 639, 640]|
|:large_blue_circle:|com/starrocks/statistic/StatisticAutoCollector.java|4|9|44.44%|[91, 92, 93, 96, 100]|
|:large_blue_circle:|com/starrocks/statistic/NativeAnalyzeJob.java|37|75|49.33%|[97, 104, 113, 117, 157, 158, 167, 168, 177, 178, 197, 198, 199, 200, 202, 203, 204, 205, 206, 207, 208, 210, 211, 212, 213, 214, 215, 216, 217, 219, 221, 222, 223, 224, 226, 235, 236, 241]|
|:large_blue_circle:|com/starrocks/sql/ast/CreateAnalyzeJobStmt.java|1|2|50.00%|[93]|
|:large_blue_circle:|com/starrocks/sql/ast/ShowAnalyzeJobStmt.java|14|20|70.00%|[77, 87, 106, 108, 121, 125]|
|:large_blue_circle:|com/starrocks/qe/StmtExecutor.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/statistic/StatisticsCollectJobFactory.java|8|8|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 124 / 142 (87.32%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/statistic/StatisticAutoCollector.java|4|9|44.44%|[91, 92, 93, 96, 100]|
|:large_blue_circle:|com/starrocks/statistic/AnalyzeMgr.java|4|6|66.67%|[547, 576]|
|:large_blue_circle:|com/starrocks/sql/ast/ShowAnalyzeJobStmt.java|15|21|71.43%|[78, 88, 107, 109, 122, 126]|
|:large_blue_circle:|com/starrocks/qe/DDLStmtExecutor.java|6|7|85.71%|[777]|
|:large_blue_circle:|com/starrocks/statistic/NativeAnalyzeJob.java|71|75|94.67%|[104, 113, 117, 241]|
|:large_blue_circle:|com/starrocks/sql/ast/CreateAnalyzeJobStmt.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/qe/StmtExecutor.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/statistic/StatisticsCollectJobFactory.java|8|8|100.00%|[]|
|:large_blue_circle:|com/starrocks/persist/EditLog.java|8|8|100.00%|[]|
|:large_blue_circle:|com/starrocks/journal/JournalEntity.java|2|2|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by dirtysalt — APPROVED** [review]

**Review by gengjun-git — APPROVED** [review]

**Pull request merged**
