### PR TITLE
[Feature] Add INCREASE MODE for window_funnel

### LINKED ISSUE #9595: Aggregate function window_ Funnel adds a mode
现有事件链的筛选模式，类型为INT。取值范围：0，1，2。

需求 ： 针对 0 模式的情况下，相同 time （DATETIME类型）不算转化。

场景 ： 计算用户买了又买的场景，如果是现有的模式，用户只购买一次商品，转化率会是100%。

### PR DESCRIPTION
**Pull request by Pslydhh**
## What type of PR is this：
- [ ] bug
- [x] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #9595

## Problem Summary(Required) ：

Add Strict increase mode fow timestamp of window_funnel to specify timestamp increase strictly.
It sepcified by 4th bit of mode.
example:
```
mysql> select user_id, window_funnel(1800, time, 4, [event_name='购买商品', event_name='购买商品']) from (select 10001 as user_id, 1 as time, '购买商品' as event_name) t group by user_id;
+---------+------------------------------------------------------------------------------------------+
| user_id | window_funnel(1800, time, 4, [event_name = '购买商品', event_name = '购买商品'])         |
+---------+------------------------------------------------------------------------------------------+
|   10001 |                                                                                        1 |
+---------+------------------------------------------------------------------------------------------+
```

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 1 / 2 (50.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/FunctionAnalyzer.java|1|2|50.00%|[169]|

**Comment by kangkaisen** [comment]
please  add UT

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/FunctionAnalyzer.java|2|2|100.00%|[]|

**Review by kangkaisen — DISMISSED** [review]

**Review by stdpain — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 0 / 1 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/FunctionAnalyzer.java|0|1|00.00%|[168]|

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/FunctionAnalyzer.java|2|2|100.00%|[]|

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by Pslydhh** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 1 / 2 (50.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/FunctionAnalyzer.java|1|2|50.00%|[183]|

**Review by kangkaisen — APPROVED** [review]

**Review by stdpain — APPROVED** [review]

**Pull request merged**
