### PR TITLE
[BugFix] Fix compile bugs in clang compiler

### PR DESCRIPTION
**Pull request by LiShuMing**
## What type of PR is this:
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by kevincai — APPROVED** [review]

**Review by imay — APPROVED** [review]

**Comment by fieldsfarmer** [comment]
Could we also merge it into branch-3.1?

**Comment by kevincai** [comment]
@mergifyio backport branch-3.1

**Comment by kevincai** [comment]
> Could we also merge it into branch-3.1? 

done

**Comment by kevincai** [comment]
@mergifyio backport branch-3.0

**Pull request merged**
