### PR TITLE
[BugFix] Find correct index of window_size for window_funnel

### LINKED ISSUE #21474: BE crashed for window_funnel with query cache
### Steps to reproduce the behavior (Required)
```sql
create database test_win_funnel_78d06612_d934_11ed_89de_00163e04d4c2
use test_win_funnel_78d06612_d934_11ed_89de_00163e04d4c2

        CREATE TABLE `t0` (
          `k1` int(11) NULL,
          `c1` int(11) NULL,
          `d1` Date NULL
        ) ENGINE=OLAP
        DUPLICATE KEY(`k1`)
        COMMENT "OLAP"
        DISTRIBUTED BY HASH(`k1`) BUCKETS 6

insert into test_win_funnel_78d06612_d934_11ed_89de_00163e04d4c2.t0 (k1, c1, d1)values (1, 1, '2020-01-01'), (1, 2, '2020-01-02'), (1, 3, '2020-01-03'), (1, 2, '2020-01-02');

-- Q1
            select /*+ SET_VAR(enable_query_cache=true,
                               new_planner_agg_stage=1) */
                k1, window_funnel(10, d1, 0, [c1=1, c1=2, c1=3])
            from t0 group by k1

-- Q2
            select /*+ SET_VAR(enable_query_cache=true,
                               new_planner_agg_stage=2,
                               pipeline_dop=2) */
                k1, window_funnel(10, d1, 0, [c1=1, c1=2, c1=3])
            from t0 group by k1

```

### Expected behavior (Required)
Return the result normally.

### Real behavior (Required)
BE crashed.
```
*** SIGSEGV (@0x10) received by PID 3720 (TID 0x7f91e1ee0700) from PID 16; stack trace: ***
    @          0x5769222 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7f926da8f630 (unknown)
    @          0x34d0134 starrocks::vectorized::WindowFunnelState<>::deserialize_and_merge()
    @          0x34a02a3 starrocks::vectorized::NullableAggregateFunctionBase<>::merge_batch()
    @          0x3008a52 starrocks::Aggregator::compute_batch_agg_states()
    @          0x2f65266 starrocks::pipeline::AggregateStreamingSinkOperator::_push_chunk_by_auto()
    @          0x2f65c41 starrocks::pipeline::AggregateStreamingSinkOperator::push_chunk()
    @          0x2c57e06 starrocks::pipeline::PipelineDriver::process()
    @          0x4e075e7 starrocks::pipeline::GlobalDriverExecutor::_worker_thread()
    @          0x4812f8d starrocks::ThreadPool::dispatch_thread()
    @          0x480dd1a starrocks::Thread::supervise_thread()
    @     0x7f926da87ea5 start_thread
    @     0x7f926d0a29fd __clone
    @                0x0 (unknown)
```

### PR DESCRIPTION
**Pull request by ZiheLiu**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #21474.

## Problem Summary(Required) ：

`agg_expr_ctxs` of `window_funnel` is different between the **update** and **merge** mode of the AggregationOperator.
- **update** mode: [InitLiteral(BIGINT), SlotRef(DATE/DATETIME), IntLiteral(INT), SlotRef(Array<BOOLEAN>)]
- **merge** mode: [SlotRef(ARRAY<BIGINT>), InitLiteral(BIGINT), IntLiteral(INT)]

Therefore, the index of `window_size` is 0 or 1, 
- `WindowFunnelAggregateFunction::update` considers it as 0,
- `WindowFunnelAggregateFunction::merge` considers it as 1.

However, when enabling query cache, the `update` mode AggregateOperator could accepts intermediate input chunk, which also invokes `WindowFunnelAggregateFunction::merge` and consider the index of `window_size` is 1.

---

Besides, the second argument of `window_funnel` should be constrained to the non-constant column. Otherwise, `agg_expr_ctxs` of **merge** mode will be [SlotRef(ARRAY<BIGINT>), InitLiteral(BIGINT), **InitLiteral(Date/Int)** IntLiteral(INT)], which is hard to find the correct index of `window_size` and `window_mode`.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 3.0
  - [x] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Review by satanson — APPROVED** [review]

**Review by stdpain — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.4

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.3

**Pull request merged**
