### PR TITLE
[BugFix] Fix storage cooldown time ut

### PR DESCRIPTION
**Pull request by wyb**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Problem Summary(Required) ：

`storage_cooldown_time` in the ut is too small, and the ut will be failed with `com.starrocks.common.AnalysisException: Cooldown time should later than now` message.

### CODE REVIEW

**Review by imay — DISMISSED** [review]

**Review by gengjun-git — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by gengjun-git** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wyb** [comment]
@Mergifyio backport branch-2.3

**Pull request merged**
