### PR TITLE
[Feature] Create hourly partitions dynamically

### PR DESCRIPTION
**Pull request by shshenhua**
## What type of PR is this：
- [ ] Enhancement
## Which issues of this PR fixes ：

Fixes #

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

### CODE REVIEW

**Comment by shshenhua** [comment]
example :

CREATE TABLE `site_access` (
  `event_day` datetime NULL COMMENT "",
  `site_id` int(11) NULL DEFAULT "10" COMMENT "",
  `city_code` varchar(100) NULL COMMENT "",
  `user_name` varchar(32) NULL DEFAULT "" COMMENT "",
  `pv` bigint(20) NULL DEFAULT "0" COMMENT ""
) ENGINE=OLAP 
DUPLICATE KEY(`event_day`, `site_id`, `city_code`, `user_name`)
COMMENT "OLAP"
PARTITION BY RANGE(`event_day`)
()
DISTRIBUTED BY HASH(`event_day`, `site_id`) BUCKETS 32 
PROPERTIES (
"replication_num" = "1",
"dynamic_partition.enable" = "true",
**"dynamic_partition.time_unit" = "HOUR",
"dynamic_partition.time_zone" = "Asia/Shanghai",
"dynamic_partition.start" = "-3",
"dynamic_partition.end" = "3",**
"dynamic_partition.prefix" = "p",
"dynamic_partition.buckets" = "32",
"in_memory" = "false",
"storage_format" = "DEFAULT",
"enable_persistent_index" = "false"
)

show create table 
CREATE TABLE `site_access` (
  `event_day` datetime NULL COMMENT "",
  `site_id` int(11) NULL DEFAULT "10" COMMENT "",
  `city_code` varchar(100) NULL COMMENT "",
  `user_name` varchar(32) NULL DEFAULT "" COMMENT "",
  `pv` bigint(20) NULL DEFAULT "0" COMMENT ""
) ENGINE=OLAP 
DUPLICATE KEY(`event_day`, `site_id`, `city_code`, `user_name`)
COMMENT "OLAP"
PARTITION BY RANGE(`event_day`)
**(PARTITION p2022110720 VALUES [('2022-11-07 20:00:00'), ('2022-11-07 21:00:00')),
PARTITION p2022110721 VALUES [('2022-11-07 21:00:00'), ('2022-11-07 22:00:00')),
PARTITION p2022110722 VALUES [('2022-11-07 22:00:00'), ('2022-11-07 23:00:00')),
PARTITION p2022110723 VALUES [('2022-11-07 23:00:00'), ('2022-11-08 00:00:00')),
PARTITION p2022110800 VALUES [('2022-11-08 00:00:00'), ('2022-11-08 01:00:00')),
PARTITION p2022110801 VALUES [('2022-11-08 01:00:00'), ('2022-11-08 02:00:00')),
PARTITION p2022110802 VALUES [('2022-11-08 02:00:00'), ('2022-11-08 03:00:00')))**
DISTRIBUTED BY HASH(`event_day`, `site_id`) BUCKETS 32 
PROPERTIES (
"replication_num" = "1",
"dynamic_partition.enable" = "true",
"dynamic_partition.time_unit" = "HOUR",
"dynamic_partition.time_zone" = "Asia/Shanghai",
"dynamic_partition.start" = "-3",
"dynamic_partition.end" = "3",
"dynamic_partition.prefix" = "p",
"dynamic_partition.buckets" = "32",
"in_memory" = "false",
"storage_format" = "DEFAULT",
"enable_persistent_index" = "false",
"compression" = "LZ4"
);

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 6 / 14 (42.86%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/ast/MultiRangePartitionDesc.java|0|3|00.00%|[166, 167, 168]|
|:large_blue_circle:|com/starrocks/common/util/DynamicPartitionUtil.java|6|11|54.55%|[406, 436, 456, 519, 520]|

**Review by Astralidea — APPROVED** [review]

**Comment by Astralidea** [comment]
run starrocks_admit_test

**Comment by nshangyiming** [comment]
@Astralidea please help to review this pr

**Review by gengjun-git — APPROVED** [review]

**Pull request merged**
