### PR TITLE
[Enhancement] add MemUsageBytes when showing current queries

### PR DESCRIPTION
**Pull request by silverbullet233**
## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Comment by silverbullet233** [comment]
run starrocks_admit_test

**Review by kangkaisen — APPROVED** [review]

**Review by murphyatwork — APPROVED** [review]

**Comment by mofeiatwork** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by murphyatwork — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 1 / 13 (07.69%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/common/util/QueryStatisticsFormatter.java|0|1|00.00%|[27]|
|:large_blue_circle:|com/starrocks/common/proc/CurrentQueryHostProcNode.java|0|3|00.00%|[33, 53, 56]|
|:large_blue_circle:|com/starrocks/common/proc/CurrentQueryInfoProvider.java|0|6|00.00%|[118, 202, 237, 268, 272, 273]|
|:large_blue_circle:|com/starrocks/common/proc/CurrentQueryStatisticsProcDir.java|1|3|33.33%|[102, 107]|

**Pull request merged**
