### PR TITLE
[Enhancement] Optimize quorum publish, wait some time util all backends finish

### PR DESCRIPTION
**Pull request by meegoo**
## What type of PR is this：
- [ ] bug
- [ ] feature
- [x] enhancement
- [ ] others

## Which issues of this PR fixes ：

Fixes #

### CODE REVIEW

**Review by chaoyli — APPROVED** [review]

**Comment by meegoo** [comment]
run starrocks_fe_unittest

**Comment by meegoo** [comment]
run starrocks_fe_unittest

**Comment by chaoyli** [comment]
run starrocks_fe_unittest

**Comment by meegoo** [comment]
> What problem it will actually cause if we don't wait for all backends to finish?

https://github.com/StarRocks/starrocks/pull/6170

**Pull request merged**
