### PR TITLE
[BugFix] Enable enable_filter_unused_columns_in_scan_stage by default

### LINKED ISSUE #10523: query result error while set enable_filter_unused_columns_in_scan_stage = true
### Steps to reproduce the behavior (Required)
```
DROP DATABASE IF EXISTS g4;
CREATE DATABASE g4;
USE g4;
admin set frontend config ("enable_decimal_v3" = "true");
CREATE TABLE IF NOT EXISTS t0 (c_0_0 DATETIME NOT NULL ,c_0_1 CHAR(1) NULL ,c_0_2 CHAR(1) NULL ,c_0_3 BOOLEAN NOT NULL ,c_0_4 LARGEINT NOT NULL ,c_0_5 VARCHAR(21) NOT NULL ,c_0_6 INT NULL ,c_0_7 DECIMAL(7, 2)  NULL ,c_0_8 DATE NULL ,c_0_9 BOOLEAN NULL ,c_0_10 DECIMAL(36, 11)  NOT NULL ) DUPLICATE KEY (c_0_0,c_0_1,c_0_2,c_0_3,c_0_4,c_0_5,c_0_6,c_0_7,c_0_8,c_0_9) PARTITION BY RANGE(c_0_0) (START ("2010-01-01") END ("2022-12-31") EVERY (INTERVAL 1186 day)) DISTRIBUTED BY HASH (c_0_9,c_0_5,c_0_0,c_0_3,c_0_8) BUCKETS 3 properties("replication_num"="3", "bloom_filter_columns"="c_0_5") ;
CREATE TABLE IF NOT EXISTS t1 (c_1_0 DECIMAL(34, 1)  NULL ,c_1_1 DATE NULL ,c_1_2 DECIMAL(24, 16)  NOT NULL ,c_1_3 BOOLEAN NOT NULL ,c_1_4 VARCHAR(1) NOT NULL ,c_1_5 HLL HLL_UNION NOT NULL ,c_1_6 INT MIN NOT NULL ) AGGREGATE KEY (c_1_0,c_1_1,c_1_2,c_1_3,c_1_4) PARTITION BY RANGE(c_1_1) (START ("2010-01-01") END ("2022-12-31") EVERY (INTERVAL 791 day)) DISTRIBUTED BY HASH (c_1_4) BUCKETS 3 properties("replication_num"="3") ;
CREATE TABLE t2 (c_2_0 BOOLEAN NOT NULL ,c_2_1 SMALLINT NULL ,c_2_2 ARRAY<STRING> NOT NULL , INDEX index1_c_2_1(`c_2_1`) USING BITMAP) UNIQUE KEY (c_2_0,c_2_1) DISTRIBUTED BY HASH (c_2_1) BUCKETS 3 properties("replication_num"="3") ;
INSERT INTO t2 VALUES (true, 13, ["4", "XSqh", "", "", "M6RKHv", "uf"]), (true, 7, ["", "", "zYDYw", "K4uhFEXj", "m8", "jF", "t", "qv", "L568ba", "cN", "", "", "", "p9D09", "o7rC"]);
INSERT INTO t2 VALUES (true, 12, []);
INSERT INTO t1 VALUES (13445364369550623134088717650636.0, '2010-01-13', 3.624290E-10, true, '', hll_hash('VpO'), 22), (61952467623632409010478517316355.9, '2010-01-11', 3.4259534E-9, true, '', hll_hash('3XAu4'), 2);
TRUNCATE TABLE t0;
INSERT INTO t1 VALUES (79449305159505456690259820092098.4, '2010-01-24', 8.0399052E-9, true, '', hll_hash('W0ixF'), 16), (NULL, '2010-01-19', 7.4326657E-9, true, '', hll_hash('M'), 4);
INSERT INTO t2 VALUES (false, 5, ["", "", "", "", "1a", "ZH"]), (false, 4, ["0mFv0", "FF", "", "q", "", "Af0fktYi", "rZyZm", "k", "HB4MZWGRR", "M", "qZsmoGRX0", "EL"]);
INSERT INTO t1 VALUES (57406103017274298457916554692497.2, '2010-01-25', 2.5021620E-9, true, '', hll_hash('GO'), 25), (41712422959973144675382814088537.8, '2010-01-14', 5.734478E-10, true, '', hll_hash('x'), 16);
INSERT INTO t1 VALUES (45033594022971479522961816107651.2, '2010-01-08', 3.7199420E-9, true, '', hll_hash('Kwb'), 5);
CREATE MATERIALIZED VIEW v0 AS SELECT t2_68.c_2_0, t2_68.c_2_1 FROM t2 AS t2_68;
CREATE VIEW v0 AS SELECT t2_71.c_2_0, t2_71.c_2_1, t2_71.c_2_2, t0_69.c_0_0, t0_69.c_0_1, t0_69.c_0_2, t0_69.c_0_3, t0_69.c_0_4, t0_69.c_0_5, t0_69.c_0_6, t0_69.c_0_7, t0_69.c_0_8, t0_69.c_0_9, t0_69.c_0_10 FROM t2 AS t2_71, t0 AS t0_69 WHERE (NOT (true)) ORDER BY t0_69.c_0_5, t0_69.c_0_5, t0_69.c_0_5, t0_69.c_0_5, t0_69.c_0_6, t0_69.c_0_7, t0_69.c_0_4, t0_69.c_0_3, t0_69.c_0_10;
INSERT INTO t1 VALUES (60476591915357866375339886025885.8, '2010-01-20', 5.8975449E-9, false, '', hll_hash('T0y0RKo'), 12), (16784990613821905653559163255073.0, '2010-01-29', 1.5786229E-9, false, '', hll_hash('Ixdb'), 26);
INSERT INTO t1 VALUES (58314307581167910557463825304891.3, '2010-01-06', 4.9545617E-9, true, '', hll_hash('3vL'), 16);
INSERT INTO t1 VALUES (97515911387754153737660357347261.0, '2010-01-16', 7.7311021E-9, false, '', hll_hash('Dwt1jtGBC'), 29);
-- SELECT t2_78.c_2_0, t2_78.c_2_2 FROM t2 AS t2_78 GROUP BY t2_78.c_2_0, t2_78.c_2_2;
-- cardinality: 5
-- SELECT t2_78.c_2_0, t2_78.c_2_2 FROM t2 AS t2_78 WHERE ((t2_78.c_2_1) IS NULL) GROUP BY t2_78.c_2_0, t2_78.c_2_2 UNION SELECT t2_78.c_2_0, t2_78.c_2_2 FROM t2 AS t2_78 WHERE (NOT (((t2_78.c_2_1) IS NULL))) GROUP BY t2_78.c_2_0, t2_78.c_2_2 UNION SELECT t2_78.c_2_0, t2_78.c_2_2 FROM t2 AS t2_78 WHERE ((((t2_78.c_2_1) IS NULL)) IS NULL) GROUP BY t2_78.c_2_0, t2_78.c_2_2;
-- cardinality: 4

when set enable_filter_unused_columns_in_scan_stage = false, the result is ok:
mysql> set enable_filter_unused_columns_in_scan_stage = false;
Query OK, 0 rows affected (0.01 sec)

mysql> SELECT t2_78.c_2_0, t2_78.c_2_2 FROM t2 AS t2_78 GROUP BY t2_78.c_2_0, t2_78.c_2_2;
+-------+-------------------------------------------------------------------------------------+
| c_2_0 | c_2_2                                                                               |
+-------+-------------------------------------------------------------------------------------+
|     0 | ["","","","","1a","ZH"]                                                             |
|     1 | []                                                                                  |
|     1 | ["","","zYDYw","K4uhFEXj","m8","jF","t","qv","L568ba","cN","","","","p9D09","o7rC"] |
|     0 | ["0mFv0","FF","","q","","Af0fktYi","rZyZm","k","HB4MZWGRR","M","qZsmoGRX0","EL"]    |
|     1 | ["4","XSqh","","","M6RKHv","uf"]                                                    |
+-------+-------------------------------------------------------------------------------------+
5 rows in set (0.01 sec)

mysql> SELECT t2_78.c_2_0, t2_78.c_2_2 FROM t2 AS t2_78 WHERE ((t2_78.c_2_1) IS NULL) GROUP BY t2_78.c_2_0, t2_78.c_2_2 UNION SELECT t2_78.c_2_0, t2_78.c_2_2 FROM t2 AS t2_78 WHERE (NOT (((t2_78.c_2_1) IS NULL))) GROUP BY t2_78.c_2_0, t2_78.c_2_2 UNION SELECT t2_78.c_2_0, t2_78.c_2_2 FROM t2 AS t2_78 WHERE ((((t2_78.c_2_1) IS NULL)) IS NULL) GROUP BY t2_78.c_2_0, t2_78.c_2_2;
+-------+-------------------------------------------------------------------------------------+
| c_2_0 | c_2_2                                                                               |
+-------+-------------------------------------------------------------------------------------+
|     1 | ["","","zYDYw","K4uhFEXj","m8","jF","t","qv","L568ba","cN","","","","p9D09","o7rC"] |
|     0 | ["","","","","1a","ZH"]                                                             |
|     1 | []                                                                                  |
|     0 | ["0mFv0","FF","","q","","Af0fktYi","rZyZm","k","HB4MZWGRR","M","qZsmoGRX0","EL"]    |
|     1 | ["4","XSqh","","","M6RKHv","uf"]                                                    |
+-------+-------------------------------------------------------------------------------------+


```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - mysql> select current_version();
+----------------------+
| current_version()    |
+----------------------+
| MAIN-RELEASE aa27516 |
+----------------------+

### PR DESCRIPTION
**Pull request by LiShuMing**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #10523

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by LiShuMing** [comment]
run starrocks_fe_unittest

**Comment by LiShuMing** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 11 / 11 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/SessionVariable.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/OlapScanNode.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/plan/PlanFragmentBuilder.java|9|9|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 11 / 11 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/SessionVariable.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/OlapScanNode.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/plan/PlanFragmentBuilder.java|9|9|100.00%|[]|

**Review by ZiheLiu — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 9 / 9 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/SessionVariable.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/OlapScanNode.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/plan/PlanFragmentBuilder.java|7|7|100.00%|[]|

**Review by kangkaisen — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Pull request merged**
