### PR TITLE
[Enhancement] Change fe-core compile source/target to 17

### PR DESCRIPTION
**Pull request by gengjun-git**
## What I'm doing:
1. Change fe-core source/target version to 17, and the others(spark-dpp, hive-udf) still use 8.
2. Copy UnmodifiableCollectionsSerializer.java to our repository to fix compilable issue:
`Unable to make field final java.util.Collection java.util.Collections$UnmodifiableCollection.c accessible: module java.base does not "opens java.util" to unnamed module @61322f9d `
  Refer to https://github.com/magro/kryo-serializers/issues/131
3. Upgrade jacoco to 0.8.8
4. For the arrow flight server, users should add `--add-opens=java.base/java.nio=org.apache.arrow.memory.core,ALL-UNNAMED` to JAVA_OPTS 
  Refer to https://arrow.apache.org/docs/java/install.html
5. Fix some UT

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [x] Yes, this PR will result in a change in behavior.
- [ ] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [x] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 3.4
  - [ ] 3.3
  - [ ] 3.2
  - [ ] 3.1
  - [ ] 3.0

### CODE REVIEW

**Comment by gengjun-git** [comment]
@mergifyio rebase

**Comment by gengjun-git** [comment]
@mergifyio rebase

**Comment by gengjun-git** [comment]
@mergifyio rebase

**Review by stephen-shelby — APPROVED** [review]

**Review by Youngwb — APPROVED** [review]

**Comment by zhaohehuhu** [comment]
UnmodifiableCollectionsSerialize is also used by IcebergMetadataScanner, so I guess same compilable issue may occur there.

**Pull request merged**
