### PR TITLE
[BugFix] fix lake pk index cache ref leak and update delvec cache strategy

### PR DESCRIPTION
**Pull request by luohaha**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #14853

## Problem Summary(Required) ：
Fix two problem:
1. When lake primary table publish, and `check_meta_version` failed because base version smaller than index version, will miss release pk index's ref.
2. When `~PrimaryKeyTxnLogApplier()`, we should handle failure first to release pk index, then release tablet lock. Or we will meet concurrent update pk index problem.

Refactor:
And also delete the code about proactively clear the delvec cache. delvec cache will be removed by LRU strategy.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 3.0
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Comment by luohaha** [comment]
run starrocks_be_unittest

**Review by sduzh — DISMISSED** [review]

**Review by wyb — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by luohaha** [comment]
run starrocks_be_unittest

**Comment by luohaha** [comment]
run starrocks_admit_test

**Review by wyb — APPROVED** [review]

**Review by sduzh — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by luohaha** [comment]
run starrocks_admit_test

**Comment by luohaha** [comment]
run starrocks_admit_test

**Comment by luohaha** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Pull request merged**
