### PR TITLE
[BugFix] fix the added filter bug when existential subquery to outer join

### LINKED ISSUE #11910: [sqlancer] query unknown error
### Steps to reproduce the behavior (Required)
```
DROP DATABASE IF EXISTS n0;
CREATE DATABASE n0;
USE n0;
admin set frontend config ("enable_decimal_v3" = "true");
CREATE TABLE t0 (c_0_0 DATE NOT NULL ,c_0_1 BIGINT NOT NULL ) DUPLICATE KEY (c_0_0) PARTITION BY RANGE(c_0_0) (START ("2010-01-01") END ("2022-12-31") EVERY (INTERVAL 128 day)) DISTRIBUTED BY HASH (c_0_0) BUCKETS 3 properties("replication_num"="3") ;
CREATE TABLE IF NOT EXISTS t1 (c_1_0 BOOLEAN NOT NULL,c_1_1 SMALLINT NOT NULL,c_1_2 ARRAY<STRING> NOT NULL,c_1_3 BOOLEAN NOT NULL,c_1_4 DATE NOT NULL) PRIMARY KEY (c_1_0) DISTRIBUTED BY HASH (c_1_0) BUCKETS 3 properties("replication_num"="3") ;
INSERT INTO t0 VALUES ('2010-01-29', -324694830), ('2010-01-19', 1224386271), ('2010-01-13', 447198644);
INSERT INTO t0 VALUES ('2010-01-13', -324694830), ('2010-01-16', 1576273535);
INSERT INTO t1 VALUES (false, 10, ["h", "iNq", "", "DbD", "nEHrOi8Al", "PPd", "xtqeOPR", "", "yZe", "GW2"], false, '2010-01-02'), (true, 6, ["", "CU", "LD7SNSYq", "T", "", "2hpIN5oH", "B", "ziYxl6M", "JFJ", "b"], false, '2010-01-05');
INSERT INTO t0 VALUES ('2010-01-23', -1606614905);
INSERT INTO t1 VALUES (false, 15, ["", "scV", "Di", "uI", "WL"], false, '2010-01-31');
INSERT INTO t1 VALUES (true, 15, ["90J1EJT", "", "U", "", "ojN1", "Y", "", "c", ""], false, '2010-01-23'), (true, 3, ["", "", "rVSC", "fm", "C"], false, '2010-01-17');
INSERT INTO t1 VALUES (true, 6, ["yik5PQt", "3zGmkjLA", "cg6A", "", "I8bu", "lh", "df", "yo3", "tjG3", "MbyKzJ", "nP", "", "j", ""], true, '2010-01-06');
DELETE FROM t0 WHERE c_0_0='1970-01-06';
INSERT INTO t0 VALUES ('2010-01-17', 447198644), ('2010-01-29', 447198644);
CREATE MATERIALIZED VIEW v0 AS SELECT t0_2.c_0_1, MAX(t0_2.c_0_0)  FROM t0 AS t0_2 GROUP BY t0_2.c_0_1 ORDER BY t0_2.c_0_1;
CREATE MATERIALIZED VIEW v0 AS SELECT t1_5.c_1_1, t1_5.c_1_3, t1_5.c_1_4, MAX(t1_5.c_1_0)  FROM t1 AS t1_5 GROUP BY t1_5.c_1_1, t1_5.c_1_3, t1_5.c_1_4 ORDER BY t1_5.c_1_1, t1_5.c_1_3 ASC, t1_5.c_1_4;
INSERT INTO t0 VALUES ('2010-01-11', -1606614905);
INSERT INTO t1 VALUES (false, 8, ["wIFokYF", "m", "", "zwO", "IHGf0XI", "l7q", "", "wh", "xOxB65j4N", "ek", "9", "N", "7d"], false, '2010-01-06'), (true, 12, ["", "W8", "o0", "mu", "AF", "e", "", "", "U1rZnXoH", "r", "", "k", "o0EMlL9R", "NE", ""], false, '2010-01-29'), (false, 10, ["uS4EdY", "", "LlPJZvz7", "PwH3K"], true, '2010-01-09');
INSERT INTO t0 VALUES ('2010-01-23', -604667710);
INSERT INTO t0 VALUES ('2010-01-14', 1224386271), ('2010-01-22', -1606614905);
WITH with_t_0 as (SELECT t1_9.c_1_0, t1_9.c_1_1, t1_9.c_1_3, t1_9.c_1_4 FROM t1 AS t1_9 WHERE (t1_9.c_1_1)  BETWEEN (t1_9.c_1_1) AND (((((((85218641)/(2071139298)))%(((2071139298)/(LEAST(NULL, -292420301, -1575986611) )))))/(1828513875))) ) , with_t_1 as (SELECT t1_9.c_1_0, t1_9.c_1_1, t1_9.c_1_3, t1_9.c_1_4 FROM t1 AS t1_9) SELECT COUNT(*) FROM t1 AS t1_9, with_t_0 AS with_t_0, with_t_1 AS with_t_1 WHERE (false) IN ((SELECT t0_8.c_0_0 FROM t0 AS t0_8, t1 AS t1_9 WHERE  ( ((256292690)-(CASE  WHEN STARTS_WITH('', NULL)  THEN 986364686  WHEN CASE  WHEN false THEN (-1536935850) IN (NULL, 1778735957)   WHEN (NOT (false)) THEN ENDS_WITH('w', 'wUD')   WHEN (t1_9.c_1_4) IN ('1969-12-20', '1970-01-25')  THEN false END THEN 1810216282 ELSE ((1686438706)*(((-90139664)/(-572618050)))) END)) ) = ( t1_9.c_1_1 ) ) ) ;

```

```
java.lang.NullPointerException: null
	at com.starrocks.sql.optimizer.rule.transformation.SemiReorderRule.check(SemiReorderRule.java:70) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.task.ApplyRuleTask.execute(ApplyRuleTask.java:64) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.task.SeriallyTaskScheduler.executeTasks(SeriallyTaskScheduler.java:42) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.Optimizer.memoOptimize(Optimizer.java:166) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.Optimizer.optimize(Optimizer.java:105) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.StatementPlanner.createQueryPlan(StatementPlanner.java:102) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:65) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:39) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:369) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:319) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:434) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:680) ~[starrocks-fe.jar:?]
	at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:55) ~[starrocks-fe.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]

```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - mysql> select current_version();
+----------------------------+
| current_version()          |
+----------------------------+
| BRANCH-2.4-RELEASE 6eb9c76 |
+----------------------------+

### LINKED ISSUE #11978: [sqlancer] unkown error for query
### Steps to reproduce the behavior (Required)
```
DROP DATABASE IF EXISTS g3;
CREATE DATABASE g3;
USE g3;
admin set frontend config ("enable_decimal_v3" = "true");
CREATE TABLE IF NOT EXISTS t0 (c_0_0 BOOLEAN NOT NULL ,c_0_1 DATE NOT NULL ,c_0_2 BOOLEAN NULL ,c_0_3 INT NOT NULL ,c_0_4 CHAR(1) NOT NULL ,c_0_5 ARRAY<INT> NULL ,c_0_6 ARRAY<INT> NULL ,c_0_7 ARRAY<INT> NOT NULL ,c_0_8 LARGEINT NOT NULL ,c_0_9 TINYINT NOT NULL ,c_0_10 DATETIME NULL ,c_0_11 ARRAY<INT> NULL ,c_0_12 FLOAT NOT NULL ,c_0_13 DATETIME NOT NULL ,c_0_14 BIGINT NULL ,c_0_15 LARGEINT NULL ,c_0_16 ARRAY<STRING> NULL , INDEX index1_c_0_0(`c_0_0`) USING BITMAP) UNIQUE KEY (c_0_0) DISTRIBUTED BY HASH (c_0_0) BUCKETS 3 properties("replication_num"="3") ;
CREATE TABLE IF NOT EXISTS t1 (c_1_0 LARGEINT NOT NULL,c_1_1 DATETIME NOT NULL,c_1_2 DATETIME NOT NULL,c_1_3 VARCHAR(41) NOT NULL,c_1_4 DOUBLE NOT NULL,c_1_5 DATETIME NOT NULL,c_1_6 DECIMAL(19, 10)  NOT NULL,c_1_7 FLOAT NOT NULL,c_1_8 ARRAY<STRING> NOT NULL,c_1_9 BOOLEAN NOT NULL,c_1_10 DECIMAL(31, 13)  NOT NULL,c_1_11 ARRAY<INT> NOT NULL,c_1_12 ARRAY<STRING> NOT NULL,c_1_13 DECIMAL(14, 9)  NOT NULL) PRIMARY KEY (c_1_0,c_1_1,c_1_2,c_1_3) PARTITION BY RANGE(c_1_1) (START ("2010-01-01") END ("2022-12-31") EVERY (INTERVAL 169 day)) DISTRIBUTED BY HASH (c_1_3,c_1_1) BUCKETS 3 properties("replication_num"="3") ;
CREATE TABLE IF NOT EXISTS t2 (c_2_0 DATETIME NULL ,c_2_1 TINYINT NULL ) DUPLICATE KEY (c_2_0) DISTRIBUTED BY HASH (c_2_0) BUCKETS 3 properties("replication_num"="3") ;
CREATE TABLE IF NOT EXISTS t3 (c_3_0 DATETIME NOT NULL,c_3_1 DATE NOT NULL,c_3_2 VARCHAR(21) NOT NULL,c_3_3 ARRAY<INT> NOT NULL,c_3_4 VARCHAR(1) NOT NULL,c_3_5 ARRAY<INT> NOT NULL,c_3_6 LARGEINT NOT NULL,c_3_7 DECIMAL(19, 7)  NOT NULL,c_3_8 VARCHAR(21) NOT NULL,c_3_9 VARCHAR(31) NOT NULL,c_3_10 ARRAY<INT> NOT NULL,c_3_11 ARRAY<STRING> NOT NULL,c_3_12 BOOLEAN NOT NULL,c_3_13 DATETIME NOT NULL,c_3_14 VARCHAR(1) NOT NULL,c_3_15 DATE NOT NULL,c_3_16 DECIMAL(21, 3)  NOT NULL,c_3_17 ARRAY<INT> NOT NULL, INDEX index1_c_3_2(`c_3_2`) USING BITMAP, INDEX index1_c_3_14(`c_3_14`) USING BITMAP) PRIMARY KEY (c_3_0,c_3_1,c_3_2) PARTITION BY RANGE(c_3_1) (START ("2010-01-01") END ("2022-12-31") EVERY (INTERVAL 107 day)) DISTRIBUTED BY HASH (c_3_1,c_3_2) BUCKETS 3 properties("replication_num"="3") ;
INSERT INTO t2 VALUES ('2010-01-03 08:00:14', 7), ('2009-12-31 08:00:14', 2), ('2010-01-30 08:00:14', 1);
INSERT INTO t1 VALUES (-45182473, '2010-01-17 08:00:14', '2010-01-28 08:00:14', '', 0.8687839078724616, '2010-01-10 08:00:14', 0.0009094806, 0.4563885764461345, ["1", "4UYOvsE5", "", "H7Mqox1", "Mhod", "8S", "Z", "hug"], true, 63379.9507302434339, [], ["U", "hW", "3ht", "oHU", "11V", "GS", "Q", "", "e3wTXig", "W", "7RHC", "M", "Y26p", "z"], 0.000078195);
INSERT INTO t2 VALUES ('2010-01-03 08:00:14', 5), ('2010-01-13 08:00:14', 0);
INSERT INTO t1 VALUES (-715688585, '2010-01-05 08:00:14', '2010-01-27 08:00:14', '', 0.7046593943032117, '2010-01-13 08:00:14', 0.0286404985, 0.7046593943032117, ["", "d", "", "3Gwl", "LZ", "2", "", "Nd", "6", "2yrMJ", "pCYZ", "c", "", "Tg"], false, 88750.8386157528816, [1999581312, -715688585, 263032458, 1014558999, -404811149, 1151083126, -45182473, 1999581312], ["", "", "o1", "YfXW"], 0.000050878);
INSERT INTO t1 VALUES (1245991362, '2010-01-12 08:00:14', '2010-01-28 08:00:14', 'rU', 0.7056971105778436, '2010-01-03 08:00:14', 0.0137782728, 0.21228367329870912, ["Yh", "iP"], true, 98176.8080823442967, [1151083126, -715688585, 1527980037, 1182217377, 603574541, -1341087800, 1869573753, 377432973, -1341087800, 190344091, 1999581312, 377432973, -45182473, 2083567445, -979101744], ["3", "RNtscfeaE", "W", "xm", "7XtA"], 0.000049073);
INSERT INTO t0 VALUES (true, '2010-01-17', false, 22, '', [1999581312, 259028612, 118831018], [-2138987827, -630179260], [91286826, 377432973, -552156551, 1869573753, 277258679, -2012039199, 1523247574, -45182473, 2083567445], -454848988, 5, '2010-01-29 08:00:14', [91286826], 0.08004322938991681, '2010-01-24 08:00:14', NULL, -940839352, ["o9", "", "iNfNPiMaT", "FImt", "", "tqEdWTIj", "Wrasj", "ah", "", "nTHxH8k", "O", "w6KiTrOcX", "Hn"]), (false, '2010-01-18', false, 18, '', [-1178988126, -1091156653, 377432973, 190344091, -630179260, 32225361, -321085315, 118831018, -1178988126, -224155494, -380788202, -1103086393, 431452899], [226832294, 1014558999, -1014542269, -1662887716, 1032283832, 467625134, 1006330569, -856093840, -1034500410, -857984941, 1245991362], [190344091, 1517497825, 263032458, -380788202, -153092000, -713528242, -321085315], -1827840423, 4, '2010-01-13 08:00:14', [277258679, -552377758, 1534250206, 172942133, -493699523, 1027889592, -2138987827, -200967804, -1662887716], 0.04156917127526849, '2010-01-30 08:00:14', 603574541, -796147264, ["", "N8G1gtV", "wLJ", "S", "5XDB5O", "pmOhh", "4", "", "uQ", "cGULLk29r", "2BSjQi", "oD"]);
INSERT INTO t1 VALUES (1945260860, '2010-01-13 08:00:14', '2010-01-10 08:00:14', '', 0.4563885764461345, '2010-01-13 08:00:14', 0.0850387836, 0.29354793193673967, ["BtURIWxC", "", "", "", "yZ2CtBB", "Y", "lqg89", "L", "Cf92", "j", "q3f"], true, 47886.1251796205833, [-1341087800, 1556680287, -653319457, -557770182, -812028971, 1945260860, -400829826, -268243809, -552377758, -491389383, -268243809, -713528242, -1506853967, -1930309094, -45182473], ["qgs", "JhZiCMd", "", "6", "", "7jwwGWks"], 0.000007372), (-400829826, '2010-01-10 08:00:14', '2010-01-01 08:00:14', 'ZN', 0.6242227070599552, '2010-01-01 08:00:14', 0.0770788830, 0.724439436358567, ["gXI", "", "I", "VY2eLEgB", "GP"], true, 98521.2082519102871, [1881592335, -168383418, 2007870736, 1797765967, -1453212799, -200967804, -153092000], ["", "cNfA3", "G", "5LjqRV", "oTCm"], 0.000096333);
INSERT INTO t2 VALUES ('2010-01-27 08:00:14', 2);
TRUNCATE TABLE t0;
INSERT INTO t3 VALUES ('2010-01-06 08:00:14', '2010-01-24', 'BK', [2043500296, 1726281674, 316757958, 253256514, -1768124892, -1381710409, -1178988126, -223218813, -231335886, 431452899, 496236727], '', [536086871, -175718756, -1389293987, 636956355], 2083567445, 34984.2255110, 'vrjr', '', [-1341087800, 808145331, 903792870, -1381710409], ["", "GwSw9NkIM", "JVKl", ""], true, '2010-01-02 08:00:14', '', '2010-01-02', 416255610376454.432, [1, 883599882]);
SELECT t0_48.c_0_14, t0_48.c_0_8 FROM t1 AS t1_49,  t2 AS t2_50 INNER JOIN t0 AS t0_48 ON t2_50.c_2_0 = t0_48.c_0_0 AND t2_50.c_2_0 = t0_48.c_0_0 WHERE EXISTS (SELECT t2_50.c_2_0 FROM t2 AS t2_50, t1 AS t1_49 WHERE (t0_48.c_0_12) IN (-9.79101744E8) )  GROUP BY t0_48.c_0_14, t0_48.c_0_8 UNION SELECT t0_48.c_0_14, t0_48.c_0_8 FROM t1 AS t1_49,  t2 AS t2_50 INNER JOIN t0 AS t0_48 ON t2_50.c_2_0 = t0_48.c_0_0 AND t2_50.c_2_0 = t0_48.c_0_0 WHERE (NOT (EXISTS (SELECT t2_50.c_2_0 FROM t2 AS t2_50, t1 AS t1_49 WHERE (t0_48.c_0_12) IN (-9.79101744E8) ) )) GROUP BY t0_48.c_0_14, t0_48.c_0_8 UNION SELECT t0_48.c_0_14, t0_48.c_0_8 FROM t1 AS t1_49,  t2 AS t2_50 INNER JOIN t0 AS t0_48 ON t2_50.c_2_0 = t0_48.c_0_0 AND t2_50.c_2_0 = t0_48.c_0_0 WHERE ((EXISTS (SELECT t2_50.c_2_0 FROM t2 AS t2_50, t1 AS t1_49 WHERE (t0_48.c_0_12) IN (-9.79101744E8) ) ) IS NULL) GROUP BY t0_48.c_0_14, t0_48.c_0_8;

```

```
fe.log:
java.lang.NullPointerException: null
        at com.starrocks.sql.optimizer.rewrite.ReplaceColumnRefRewriter$Rewriter.visitVariableReference(ReplaceColumnRefRewriter.java:56) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.rewrite.ReplaceColumnRefRewriter$Rewriter.visitVariableReference(ReplaceColumnRefRewriter.java:37) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.operator.scalar.ColumnRefOperator.accept(ColumnRefOperator.java:113) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.rewrite.ReplaceColumnRefRewriter$Rewriter.visit(ReplaceColumnRefRewriter.java:42) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.rewrite.ReplaceColumnRefRewriter$Rewriter.visit(ReplaceColumnRefRewriter.java:37) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.operator.scalar.ScalarOperatorVisitor.visitIsNullPredicate(ScalarOperatorVisitor.java:62) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.operator.scalar.IsNullPredicateOperator.accept(IsNullPredicateOperator.java:41) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.rewrite.ReplaceColumnRefRewriter.rewrite(ReplaceColumnRefRewriter.java:34) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.rule.transformation.PushDownPredicateProjectRule.transform(PushDownPredicateProjectRule.java:67) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.task.RewriteTreeTask.rewrite(RewriteTreeTask.java:61) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.task.RewriteTreeTask.rewrite(RewriteTreeTask.java:79) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.task.RewriteTreeTask.rewrite(RewriteTreeTask.java:79) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.task.RewriteTreeTask.rewrite(RewriteTreeTask.java:79) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.task.RewriteTreeTask.rewrite(RewriteTreeTask.java:79) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.task.RewriteTreeTask.rewrite(RewriteTreeTask.java:79) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.task.RewriteTreeTask.rewrite(RewriteTreeTask.java:79) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.task.RewriteTreeTask.rewrite(RewriteTreeTask.java:79) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.task.RewriteTreeTask.execute(RewriteTreeTask.java:46) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.task.SeriallyTaskScheduler.executeTasks(SeriallyTaskScheduler.java:49) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.ruleRewriteIterative(Optimizer.java:335) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.logicalRuleRewrite(Optimizer.java:155) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.optimize(Optimizer.java:88) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.createQueryPlan(StatementPlanner.java:100) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:63) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:37) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:360) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:313) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:428) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:674) ~[starrocks-fe.jar:?]
        at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:55) ~[starrocks-fe.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_272]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_272]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_272]
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 mysql> select current_version();
+----------------------+
| current_version()    |
+----------------------+
| MAIN-RELEASE de75d4f |
+----------------------+
1 row in set (0.00 sec)

### PR DESCRIPTION
**Pull request by packy92**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes [#11910](https://github.com/StarRocks/starrocks/issues/11910)
Fixed #11978

## Problem Summary(Required) ：

Table t0(v1, v2, v3);
Table t1(v4, v5, v6);

**Problem one:**
For exists subquery with correlated condition like `select * from t1 where (exists (select v1 from t0 where t1.v4 = t0.v1)) = false;`, we will transform it to:
```
select tmp.v4, tmp.v5, tmp.v6 from 
    (select t1.*,  t0.v1 from t1 
         left join 
        (select v1 from t0 group by v1)) t0 
        on t1.v4 = t0.v1 
        where (t0.v1 is not null) = false
    ) tmp
```
But for sql, `select * from t1 where (exists (select v1 from t0 where t1.v4 = t1.v5)) is null;`  the correlated codnition is `t1.v4 = t1.v5` without inner table col. We cannot generate a group by key and is not null predicate which cause the 'Unknown error' in the second sql of the issue's comment. To avoid this problem, this pr generate countRows aggreation and use it to generate the not null predicate. The above sql will be transformed to:
```
select tmp.v4, tmp.v5, tmp.v6 from 
    (select t1.*,  t0.v1 from t1 
         left join 
        (select countRows, v1 from t0) t0 
        on t1.v4 = t1.v5 
        where (t0.countRows is not null) = false
    ) tmp
```
**Problem two:**
The nullpointer problem in the maintext of the issue is because of pushing the semi/anti join's on condition to its child and without preserving the original on condition. This leads to wrong plan. To avoid this problem, we preserve the original on condition even when it can pushdown to its child when processing semi/anti join.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by kangkaisen** [comment]
please add UT

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 21 / 21 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/QuantifiedApply2JoinRule.java|9|9|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/PushDownJoinPredicateBase.java|6|6|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/ExistentialApply2OuterJoinRule.java|6|6|100.00%|[]|

**Comment by packy92** [comment]
run starrocks_admit_test

**Review by liuyehcf — APPROVED** [review]

**Review by Seaven — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Pull request merged**
