### PR TITLE
fix: remove class PackedInt128

### PR DESCRIPTION
**Pull request by manahshetty**
#2774

### CODE REVIEW

**Comment by kangkaisen** [comment]
run starrocks_clang-format

**Comment by imay** [comment]
@manahshetty 
Thanks for your contribution to StarRocks. The clang-format didn't pass, would you mind to execute `./build-support/clang-format.sh` and make this check happy?

**Comment by manahshetty** [comment]
> @manahshetty Thanks for your contribution to StarRocks. The clang-format didn't pass, would you mind to execute `./build-support/clang-format.sh` and make this check happy?

Will do, thank you!

**Comment by manahshetty** [comment]
> @manahshetty Thanks for your contribution to StarRocks. The clang-format didn't pass, would you mind to execute `./build-support/clang-format.sh` and make this check happy?

@imay hey, I ran the script and it formatted the files (most of which I hadn't edited) but it still fails to pass the clang-format test. Could you help me out?
I'm running/testing using the clang as included in the docker installation (starrocks/dev-env:main image)

**Comment by stdpain** [comment]
@manahshetty You need to run this command from the root of the code
For example:
cd starrocks && ./build-support/clang-format.sh

**Comment by manahshetty** [comment]
> @manahshetty You need to run this command from the root of the code For example: cd starrocks && ./build-support/clang-format.sh

Hey, yes I've run the same script and seen the changes reflected in my commit. It still throws an error in the clang-format test.
Also, running clang-format.sh made changes to files I hadn't opened or edited. Could this be the issue?

Should I recreate my fixes on a new branch and test it out?

**Comment by stdpain** [comment]
@manahshetty 
The version in clang-format in docker is 12.0, I suggest installing a 10.0

**Comment by imay** [comment]
Because of the wrong version of clang-format, I will merge this PR.
And I will format this in the following PR.
Thanks for your contribution and patience @manahshetty

**Pull request merged**
