### PR TITLE
[BugFix] Allow select from view when user is only granted on view

### LINKED ISSUE #10464: query view get a error :does not have privilege on the base table(version:2.2.2)
### Steps to reproduce the behavior (Required)

**1. create the base table sql is as follows:**
CREATE TABLE `sjzx_db`.`posnodinf_sr` (
  `agtorg` varchar(65533) NOT NULL COMMENT "合作机构编号",
  `areacd` varchar(65533) NULL COMMENT "地区码",
  `orgnam` varchar(65533) NULL COMMENT "合作机构名称",
  `rtrsvr` varchar(65533) NULL COMMENT "对应服务名",
  `rdomax` varchar(65533) NULL COMMENT "最大重发次数",
  `invtim` varchar(65533) NULL COMMENT "两次重发间隔时间",
  `crcmax` varchar(65533) NULL COMMENT "最大冲正次数",
  `stldat` varchar(65533) NULL COMMENT "清算日期",
  `chksts` varchar(65533) NULL COMMENT "对账状态",
  `linknm` varchar(65533) NULL COMMENT "联系人",
  `linkte` varchar(65533) NULL COMMENT "联系电话",
  `svrsts` varchar(65533) NULL COMMENT "服务开通状态0 正常 1 关闭",
  `comsts` varchar(65533) NULL COMMENT "通讯状态0 正常 1 故障",
  `merflg` varchar(65533) NULL COMMENT "大小商户类型1 小商户号 2 大商户号",
  `othflg` varchar(65533) NULL COMMENT "是否支持他行卡标志0 本行 1 全部(支持他行)",
  `prvinfo` varchar(65533) NULL COMMENT "定制权限 01?消费?02?消费撤销?03?余额查询?04?可用余额查询?05?订单查询?06?预授权?07?预授权取消?08?预授权完成?09?预授权完成撤销?10?签",
  `bbflg` varchar(65533) NULL COMMENT "默认本本标志 0 默认 1 非默认",
  `agtorgcpus` varchar(65533) NULL COMMENT "银联合作机构编号",
  `btflg` varchar(65533) NULL COMMENT "默认本他标志0 默认 1 非默认"
) ENGINE=OLAP 
DUPLICATE KEY(`agtorg`)
COMMENT "合作机构信息表"
DISTRIBUTED BY HASH(`agtorg`) BUCKETS 1 
PROPERTIES (
"replication_num" = "3",
"in_memory" = "false",
"storage_format" = "DEFAULT"
);

**2.create the view sql is as follows:** 
 CREATE VIEW  `sjzx_db`.`v1_posnodinf_sr` (agtorg COMMENT "合作机构编号", areacd COMMENT "地区码", orgnam COMMENT "合作机构名称", rtrsvr COMMENT "对应服务名", rdomax COMMENT "最大重发次数", invtim COMMENT "两次重发间隔时间", crcmax COMMENT "最大冲正次数", stldat COMMENT "清算日期", chksts COMMENT "对账状态", linknm COMMENT "联系人", linkte COMMENT "联系电话", svrsts COMMENT "服务开通状态0 正常 1 关闭", comsts COMMENT "通讯状态0 正常 1 故障", merflg COMMENT "大小商户类型1 小商户号 2 大商户号", othflg COMMENT "是否支持他行卡标志0 本行 1 全部(支持他行)", prvinfo COMMENT "定制权限 01?消费?02?消费撤销?03?余额查询?04?可用余额查询?05?订单查询?06?预授权?07?预授权取消?08?预授权完成?09?预授权完成撤销?10?签", bbflg COMMENT "默认本本标志 0 默认 1 非默认", agtorgcpus COMMENT "银联合作机构编号", btflg COMMENT "默认本他标志0 默认 1 非默认") COMMENT "合作机构信息表" AS SELECT `agtorg` AS `agtorg`, `areacd` AS `areacd`, `orgnam` AS `orgnam`, `rtrsvr` AS `rtrsvr`, `rdomax` AS `rdomax`, `invtim` AS `invtim`, `crcmax` AS `crcmax`, `stldat` AS `stldat`, `chksts` AS `chksts`, `linknm` AS `linknm`, concat(substr(`linkte`, 1, 3), '*****', substr(`linkte`, -4)) AS `linkte`, `svrsts` AS `svrsts`, `comsts` AS `comsts`, `merflg` AS `merflg`, `othflg` AS `othflg`, `prvinfo` AS `prvinfo`, `bbflg` AS `bbflg`, `agtorgcpus` AS `agtorgcpus`, `btflg` AS `btflg` FROM  `sjzx_db`.`posnodinf_sr`;

**3. grant select privilege to user dev_user@'%';**

grant select_priv on `sjzx_db`.`v1_posnodinf_sr` to dev_user@'%';

**4.use the user dev_user@'%' login starrocks and query the view get a error:**
select * from `sjzx_db`.`v1_posnodinf_sr`;

### Expected behavior (Required)
It is sufficient to grant the view's permissions

### StarRocks version (Required)
MySQL [sjzx_db]> select current_version();
+-------------------+
| current_version() |
+-------------------+
| 2.2.2 e27e2aa     |
+-------------------+
1 row in set (0.00 sec)

### PR DESCRIPTION
**Pull request by padmejin**
## What type of PR is this：
- [x] bugfix
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #10464 

## Problem Summary(Required) ：

When checking the privileges of a query statement, instead of checking the select privileges of all the relative tables, we traversal all nodes and handle them separately. As to view, the operation will be allowed when the user has the privilege to the view itself, otherwise, it will keep looking for select privileges on all the base tables as it used to be.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by padmejin** [comment]
run starrocks_fe_unittest

**Comment by wangruin** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 24 / 24 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/PrivilegeChecker.java|24|24|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 24 / 24 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/PrivilegeChecker.java|24|24|100.00%|[]|

**Review by HangyuanLiu — APPROVED** [review]

**Review by gengjun-git — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by padmejin** [comment]
@Mergifyio backport branch-2.4 branch-2.3
¡Muchas gracias!

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 22 / 25 (88.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/PrivilegeChecker.java|22|25|88.00%|[400, 1057, 1076]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 22 / 25 (88.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/PrivilegeChecker.java|22|25|88.00%|[400, 1057, 1076]|

**Pull request merged**
