### PR TITLE
[Enhancement] Implement a fake mysql.user table

### LINKED ISSUE #19398: Cannot create databases or users via UI in DBeaver
If you pick that starrocks is a mysql database, you can connect but can't "do" anything. 

Screenshot 2023-03-11 at 8 43 15 PM

Screenshot 2023-03-11 at 8 45 05 PM

### PR DESCRIPTION
**Pull request by Astralidea**
## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #19398

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 3.0
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 95 / 130 (73.08%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|4|21|19.05%|[356, 357, 358, 359, 363, 366, 367, 369, 371, 3846, 3848, 3849, 3852, 3853, 3854, 3855, 3856]|
|:large_blue_circle:|com/starrocks/sql/analyzer/DropStmtAnalyzer.java|1|4|25.00%|[130, 131, 132]|
|:large_blue_circle:|com/starrocks/catalog/MysqlSchemaDb.java|7|15|46.67%|[54, 60, 66, 71, 76, 79, 90, 94]|
|:large_blue_circle:|com/starrocks/mysql/privilege/Auth.java|4|6|66.67%|[713, 714]|
|:large_blue_circle:|com/starrocks/cluster/Cluster.java|9|10|90.00%|[196]|
|:large_blue_circle:|com/starrocks/catalog/SchemaTable.java|62|66|93.94%|[844, 845, 846, 848]|
|:large_blue_circle:|com/starrocks/catalog/Database.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/InfoSchemaDb.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/clone/DynamicPartitionScheduler.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/mysql/privilege/DbPrivEntry.java|2|2|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 94 / 129 (72.87%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|4|21|19.05%|[356, 357, 358, 359, 363, 366, 367, 369, 371, 3847, 3849, 3850, 3853, 3854, 3855, 3856, 3857]|
|:large_blue_circle:|com/starrocks/sql/analyzer/DropStmtAnalyzer.java|1|4|25.00%|[130, 131, 132]|
|:large_blue_circle:|com/starrocks/catalog/MysqlSchemaDb.java|7|15|46.67%|[54, 60, 66, 71, 76, 79, 90, 94]|
|:large_blue_circle:|com/starrocks/mysql/privilege/Auth.java|4|6|66.67%|[713, 714]|
|:large_blue_circle:|com/starrocks/cluster/Cluster.java|9|10|90.00%|[196]|
|:large_blue_circle:|com/starrocks/catalog/SchemaTable.java|61|65|93.85%|[860, 861, 862, 864]|
|:large_blue_circle:|com/starrocks/catalog/Database.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/InfoSchemaDb.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/clone/DynamicPartitionScheduler.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/mysql/privilege/DbPrivEntry.java|2|2|100.00%|[]|

**Comment by Astralidea** [comment]
Close this PR first to see if there is any other way to support it.

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Pull request closed without merging**
