### PR TITLE
[Bugfix] Fix bug query INFORMATION_SCHEMA.tasks Failed

### LINKED ISSUE #9919: Internal error processing getTasks, host: unknown
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by Astralidea**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #9919

## Problem Summary(Required) ：

when query INFORMATION_SCHEMA.tasks it will throw Internal error processing getTasks, host: unknown
this because there was no Task type for async before, and an EVENT-TRIGGED type was added later, which was not recognized. If an older version created this type it will affect the display.
## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by ABingHuang** [comment]
Add an UT

**Review by ABingHuang — CHANGES_REQUESTED** [review]
Add an UT

**Review by ABingHuang — DISMISSED** [review]
LGTM

**Review by gengjun-git — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by wyb — DISMISSED** [review]

**Comment by Astralidea** [comment]
run starrocks_admit_test

**Review by imay — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by Astralidea** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by Astralidea** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 3 / 3 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/service/FrontendServiceImpl.java|3|3|100.00%|[]|

**Comment by Astralidea** [comment]
run starrocks_admit_test

**Comment by Astralidea** [comment]
@Mergifyio backport branch-2.4

**Pull request merged**
