### PR TITLE
Update the link for Coloate join

### PR DESCRIPTION
**Pull request by chaoyli**
## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
starrocks_be_unittest succeeded.

**Comment by wanpengfei-git** [comment]
starrocks_be_unittest succeeded.

**Comment by wanpengfei-git** [comment]
starrocks_be_unittest succeeded.

**Review by imay — APPROVED** [review]

**Comment by hellolilyliuyi** [comment]
@mergify backport branch-2.4

**Comment by hellolilyliuyi** [comment]
@mergify backport branch-2.3

**Comment by hellolilyliuyi** [comment]
@mergify backport branch-2.2

**Pull request merged**
