### PR TITLE
[BugFix] fix subquery check in join on predicate

### PR DESCRIPTION
**Pull request by packy92**
Fixes #issue
```
select * from t0 left join t1 on (select count(*) from t2 where v4 = v7) > 0;
```
failed to pass `Preconditions.checkState(isJoinLeftCorrelated || isJoinRightCorrelated);` because of not implement equals method in field.

The root casue is subquery in join on predicate is a little different from it in other position, because we need to define which node in the join operator is the outer node in apply operator.
- scalar subquery
   If uncorrelated, just choose the right node in the join op, else choose the correlated node. If the correlated relationship ref cols from both nodes in the join, throw unsupported exception.
- exists subquery
   the same as scalar subquery.
- in subquery
   It's a little different becuase the `expr in subquery` has implied a correlated realtionship. So just choose the correlated node. If the correlated relationship ref cols from both nodes in the join, throw unsupported exception.

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.2
  - [x] 3.1
  - [x] 3.0
  - [x] 2.5

### CODE REVIEW

**Review by Seaven — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 49 / 51 (96.08%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/analysis/Expr.java|13|14|92.86%|[451]|
|:large_blue_circle:|com/starrocks/sql/optimizer/transformer/RelationTransformer.java|32|33|96.97%|[935]|
|:large_blue_circle:|com/starrocks/sql/optimizer/OptExpression.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/transformer/SqlToScalarOperatorTranslator.java|3|3|100.00%|[]|

**Review by Seaven — APPROVED** [review]

**Review by kangkaisen — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.2

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
