### PR TITLE
[UT] fix unstable union mv rewrite ut

### LINKED ISSUE #17078: union mv rewrite ut is unstable
com.starrocks.sql.optimizer.rule.transformation.materialization.MvRewriteOptimizationTest.testUnionRewrite

Error Message
PLAN FRAGMENT 0
 OUTPUT EXPRS:3: c3 | 5: sum
  PARTITION: UNPARTITIONED

  RESULT SINK

  4:EXCHANGE

PLAN FRAGMENT 1
 OUTPUT EXPRS:
  PARTITION: HASH_PARTITIONED: 3: c3

  STREAM DATA SINK
    EXCHANGE ID: 04
    UNPARTITIONED

  3:AGGREGATE (merge finalize)
  |  output: sum(5: sum)
  |  group by: 3: c3
  |  
  2:EXCHANGE

PLAN FRAGMENT 2
 OUTPUT EXPRS:
  PARTITION: RANDOM

  STREAM DATA SINK
    EXCHANGE ID: 02
    HASH_PARTITIONED: 3: c3

  1:AGGREGATE (update serialize)
  |  STREAMING
  |  output: sum(2: c2)
  |  group by: 3: c3
  |  
  0:OlapScanNode
     TABLE: test_base_part
     PREAGGREGATION: ON
     partitions=6/6
     rollup: test_base_part
     tabletRatio=36/36
     tabletList=10176,10178,10180,10182,10184,10186,10188,10190,10192,10194 ...
     cardinality=1
     avgRowSize=2.0
     numNodes=0
Stacktrace
java.lang.AssertionError: 
PLAN FRAGMENT 0
 OUTPUT EXPRS:3: c3 | 5: sum
  PARTITION: UNPARTITIONED

  RESULT SINK

  4:EXCHANGE

PLAN FRAGMENT 1
 OUTPUT EXPRS:
  PARTITION: HASH_PARTITIONED: 3: c3

  STREAM DATA SINK
    EXCHANGE ID: 04
    UNPARTITIONED

  3:AGGREGATE (merge finalize)
  |  output: sum(5: sum)
  |  group by: 3: c3
  |  
  2:EXCHANGE

PLAN FRAGMENT 2
 OUTPUT EXPRS:
  PARTITION: RANDOM

  STREAM DATA SINK
    EXCHANGE ID: 02
    HASH_PARTITIONED: 3: c3

  1:AGGREGATE (update serialize)
  |  STREAMING
  |  output: sum(2: c2)
  |  group by: 3: c3
  |  
  0:OlapScanNode
     TABLE: test_base_part
     PREAGGREGATION: ON
     partitions=6/6
     rollup: test_base_part
     tabletRatio=36/36
     tabletList=10176,10178,10180,10182,10184,10186,10188,10190,10192,10194 ...
     cardinality=1
     avgRowSize=2.0
     numNodes=0

	at com.starrocks.sql.plan.PlanTestBase.assertContains(PlanTestBase.java:1096)
	at com.starrocks.sql.optimizer.rule.transformation.materialization.MvRewriteOptimizationTest.testUnionRewrite(MvRewriteOptimizationTest.java:1282)
Standard Output
per_driver_seq_scan_range not empty numTablets: 3
not all scanrange used: all:0 used:3
per_driver_seq_scan_range not empty numTablets: 4
not all scanrange used: all:0 used:4
per_driver_seq_scan_range not empty numTablets: 3
not all scanrange used: all:0 used:3
per_driver_seq_scan_range not empty numTablets: 3
not all scanrange used: all:0 used:3
per_driver_seq_scan_range not empty numTablets: 4
not all scanrange used: all:0 used:4
per_driver_seq_scan_range not empty numTablets: 3
not all scanrange used: all:0 used:3
per_driver_seq_scan_range not empty numTablets: 1
not all scanrange used: all:0 used:1
per_driver_seq_scan_range not empty numTablets: 1
not all scanrange used: all:0 used:1
per_driver_seq_scan_range not empty numTablets: 1
not all scanrange used: all:0 used:1

### PR DESCRIPTION
**Pull request by ABingHuang**
Signed-off-by: ABingHuang <codekhuang@163.com>

## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [x] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #17078 

## Problem Summary(Required) ：

fix unstable union mv rewrite ut MvRewriteOptimizationTest.testUnionRewrite

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Review by Youngwb — DISMISSED** [review]

**Review by Astralidea — DISMISSED** [review]

**Review by Youngwb — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by Astralidea — APPROVED** [review]

**Review by Youngwb — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 4 / 4 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/RuleType.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/clone/DynamicPartitionScheduler.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/rule/AggregateAggregateScanRule.java|1|1|100.00%|[]|

**Comment by ABingHuang** [comment]
run DCO

**Comment by ABingHuang** [comment]
run starrocks_admit_test

**Comment by ABingHuang** [comment]
run starrocks_admit_test

**Comment by ABingHuang** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
