### PR TITLE
[Enhancement] remove sensitive info from create resource stmt audit

### LINKED ISSUE #13324: Sensitive info should be moved from log
## Enhancement
The log of StarRocks may include some sensitive information, like username, password.

### PR DESCRIPTION
**Pull request by rickif**
## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes https://github.com/StarRocks/starrocks/issues/13324

## Problem Summary(Required) ：

This PR removes sensitive key words from audit log of create external resouce stmt. The new output would be like
```
2022-11-16 10:28:26,584 [query] |Client=127.0.0.1:41444|User=root|AuthorizedUser='root'@'%'|ResourceGroup=default_wg|Catalog=default_catalog|Db=db0|State=ERR|ErrorCode=|Time=17|ScanBytes=0|ScanRows=0|ReturnRows=0|CpuCostNs=0|MemCostBytes=0|StmtId=4|QueryId=59bf85c0-6556-11ed-8e50-52243889412b|IsQuery=false|feIp=172.17.0.1|Stmt=CREATE EXTERNAL RESOURCE "spark0" PROPERTIES (     "type" = "spark",     "spark.master" = "yarn",     "spark.submit.deployMode" = "cluster",     "spark.jars" = "xxx.jar,yyy.jar",     "spark.files" = "/tmp/aaa,/tmp/bbb",     "spark.executor.memory" = "1g",     "spark.yarn.queue" = "queue0",     "spark.hadoop.yarn.resourcemanager.address" = "resourcemanager_host:8032",     "spark.hadoop.fs.defaultFS" = "hdfs://namenode_host:9000",     "working_dir" = "hdfs://namenode_host:9000/tmp/starrocks",     "broker" = "broker0",     "broker.username" = "user0",     "broker.password" = "***" )|Digest=|PlanCpuCost=0.0|PlanMemCost=0.0|PendingTimeMs=0
```
in which the sensitive key words would be replaced by ***.
Now, the sensitive key words include the following:
```
password
kerberos_keytab_content
bos_secret_accesskey
fs.s3a.access.key
fs.s3a.secret.key
fs.oss.accessKeyId
fs.oss.accessKeySecret
fs.cosn.userinfo.secretId
fs.cosn.userinfo.secretKey
property.sasl.password
```
## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
- [x] 2.5
- [ ] 2.4
- [ ] 2.3
- [ ] 2.2

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 7 / 8 (87.50%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/ast/CreateResourceStmt.java|0|1|00.00%|[65]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AstToStringBuilder.java|6|6|100.00%|[]|
|:large_blue_circle:|com/starrocks/common/util/PrintableMap.java|1|1|100.00%|[]|

**Review by chaoyli — APPROVED** [review]

**Review by meegoo — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by rickif** [comment]
run starrocks_admit_test image

**Comment by rickif** [comment]
run starrocks_admit_test image

**Comment by rickif** [comment]
run starrocks_admit_test

**Pull request merged**
