### PR TITLE
[Enhancement] Optimize complex refresh logic in automatic refresh scenarios

### LINKED ISSUE #13167: Optimize the refresh scenario of large wide tables
## Enhancement
In fact, for the large-width tables generated by materialized views, that is, fact tables and dimension tables, some users may prefer that the latitude table does not completely refresh the entire materialized table when adding data for the sake of refresh efficiency. View all partitions in the history. So see if there is a way to properly optimize for this problem.

### PR DESCRIPTION
**Pull request by Astralidea**
## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #13167

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [x] This pr will affect users' behaviors
- [x] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

### CODE REVIEW

**Comment by Astralidea** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 27 / 75 (36.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/scheduler/TaskManager.java|0|3|00.00%|[134, 135, 137]|
|:large_blue_circle:|com/starrocks/common/util/PropertyAnalyzer.java|0|10|00.00%|[224, 225, 227, 228, 229, 230, 231, 232, 234, 236]|
|:large_blue_circle:|com/starrocks/qe/DDLStmtExecutor.java|0|1|00.00%|[262]|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|8|28|28.57%|[3325, 3326, 3327, 3328, 3517, 3518, 3519, 3520, 3521, 3522, 3523, 3526, 3527, 3528, 3529, 3530, 3531, 3532, 3533, 3534]|
|:large_blue_circle:|com/starrocks/scheduler/PartitionBasedMaterializedViewRefreshProcessor.java|2|6|33.33%|[233, 486, 488, 492]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AnalyzerUtils.java|3|7|42.86%|[488, 489, 490, 492]|
|:large_blue_circle:|com/starrocks/catalog/MaterializedView.java|3|6|50.00%|[660, 661, 662]|
|:large_blue_circle:|com/starrocks/scheduler/TaskRunContext.java|2|3|66.67%|[40]|
|:large_blue_circle:|com/starrocks/catalog/TableProperty.java|7|9|77.78%|[287, 288]|
|:large_blue_circle:|com/starrocks/scheduler/persist/TaskRunStatus.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/scheduler/TaskRun.java|1|1|100.00%|[]|

**Review by ABingHuang — APPROVED** [review]
LGTM

**Review by gengjun-git — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by Youngwb — APPROVED** [review]

**Pull request merged**
