### PR TITLE
[BugFix] Fix calculate next db index after refresh

### LINKED ISSUE #9327: follower FE stop replaying after rolling journal
Follower constantly report "meta out of date" and won't replay any journal.
```
2022-07-28 04:31:52,495 INFO (replayer|78) [BDBJournalCursor.refresh():168] update dbnames [27722028, 27736142, 27736154, 27736165, 27736176, 27736187, 27736198, 27736209, 27736220, 27736279, 27736338, 27736397, 27736456, 27736517, 27736585, 27736644, 27736703, 27736763, 27736822, 27736881, 27736940, 27736999, 27737058, 27737117, 27737176, 27737235, 27737294, 27737353, 27737412, 27737471, 27737530, 27737589, 27737648, 27737707, 27737766, 27737825, 27737884, 27737943, 27738002, 27738061, 27738121, 27738180, 27738239, 27738298, 27738357, 27738416, 27738475, 27738534, 27738593, 27738652, 27738711, 27738770, 27738829, 27738888, 27738947, 27739006, 27739065, 27739124, 27739183, 27739242, 27739301, 27739360, 27739419, 27739478, 27739537, 27739596, 27739655, 27739714, 27739773, 27739832, 27739891, 27739950, 27740009, 27740068, 27740127, 27740186, 27740245] -> [27722028, 27736142, 27736154, 27736165, 27736176, 27736187, 27736198, 27736209, 27736220, 27736279, 27736338, 27736397, 27736456, 27736517, 27736585, 27736644, 27736703, 27736763, 27736822, 27736881, 27736940, 27736999, 27737058, 27737117, 27737176, 27737235, 27737294, 27737353, 27737412, 27737471, 27737530, 27737589, 27737648, 27737707, 27737766, 27737825, 27737884, 27737943, 27738002, 27738061, 27738121, 27738180, 27738239, 27738298, 27738357, 27738416, 27738475, 27738534, 27738593, 27738652, 27738711, 27738770, 27738829, 27738888, 27738947, 27739006, 27739065, 27739124, 27739183, 27739242, 27739301, 27739360, 27739419, 27739478, 27739537, 27739596, 27739655, 27739714, 27739773, 27739832, 27739891, 27739950, 27740009, 27740068, 27740127, 27740186, 27740245, 27740304]
2022-07-28 04:31:52,501 INFO (replayer|78) [BDBJournalCursor.calculateNextDbIndex():126] currentKey 27727349, currentDatabase CloseSafeDatabase{db=27722028}, index of next opened db is 0
2022-07-28 04:31:53,531 WARN (replayer|78) [GlobalStateMgr.replayJournalInner():1698] replay journal cost too much time: 1030 replayedJournalId: 27732016
2022-07-28 04:31:53,531 INFO (replayer|78) [GlobalStateMgr.replayJournalInner():1711] replayed journal from 27727348 - 27732016
2022-07-28 04:31:54,015 INFO (replayer|78) [GlobalStateMgr.replayJournalInner():1711] replayed journal from 27732016 - 27736141
...
2022-07-28 16:53:45,550 WARN (replayer|78) [GlobalStateMgr$5.setCanRead():1614] meta out of date. current time: 1658998425550, synchronized time: 1658919736349, has log: false, fe type: FOLLOWER
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
main

### PR DESCRIPTION
**Pull request by padmejin**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #9327 

## Problem Summary(Required) ：

When we calculate the `nextDbIndex` after local databases changed, there are actually two cases
1. if this is the first time, we're actually looking for the db of currentKey
2. otherwise, we're already open a db for previous key, we're looking for the next db of the previous key

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 9 / 9 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/journal/bdbje/BDBJournalCursor.java|9|9|100.00%|[]|

**Comment by padmejin** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 9 / 9 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/journal/bdbje/BDBJournalCursor.java|9|9|100.00%|[]|

**Review by gengjun-git — APPROVED** [review]

**Review by chaoyli — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Pull request merged**
