### PR TITLE
[BugFix] Fix capitalization issue in struct field name

### LINKED ISSUE #27171: Couldn't use camel naming to query the struct field name
### Steps to reproduce the behavior (Required)
In our PruneSubfieldsForComplexTypeTest UT

only change the field2 to Field2, we will get the NPE error in getFieldPos method

```
-        StructField topLevel2 = new StructField("field2", field2);
+        StructField topLevel2 = new StructField("Field2", field2);
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by kangkaisen**
Fixes https://github.com/StarRocks/starrocks/issues/27171

## What type of PR is this:
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [x] 3.0
  - [ ] 2.5
  - [ ] 2.4

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 1 / 2 (50.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/StructType.java|1|2|50.00%|[210]|

**Review by fzhedu — APPROVED** [review]
LGTM

**Comment by kangkaisen** [comment]
https://github.com/StarRocks/starrocks/pull/27313 this PR include this PR. So close this PR.

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Pull request closed without merging**
