### PR TITLE
[Feature] support hive external table for ks3 storage

### PR DESCRIPTION
**Pull request by xuzifu666**
## What type of PR is this：
- [ ] BugFix
- [x] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Review by dirtysalt — DISMISSED** [review]

**Review by DorianZheng — APPROVED** [review]
LGTM

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 3 / 3 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/external/ObjectStorageUtils.java|3|3|100.00%|[]|

**Review by dirtysalt — APPROVED** [review]

**Comment by xuzifu666** [comment]
have a review plz :)  @imay

**Review by imay — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by YannngHQ** [comment]
Hello, I would like to ask how to configure or create a catalog through an external table in Hive to store data in KS3.

**Pull request merged**
