### PR TITLE
[Enhancement] add position to parse node (step 3) 

### PR DESCRIPTION
**Pull request by packy92**
## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

The following work of this PR #18280
- Add position info when getting analyzing error. Now we can tell where is wrong when analyzing failed.
- simplify the adminCheckTabletsStatement rule to reduce unnecessary check steps.
- add a `PropertySet` contains each propery and its pos info for further replacing `Map<String, String> properties` in clause

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Comment by packy92** [comment]
run starrocks_fe_unittest

**Comment by packy92** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 196 / 417 (47.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/AlterDatabaseRenameStatementAnalyzer.java|0|2|00.00%|[28, 38]|
|:large_blue_circle:|com/starrocks/sql/analyzer/BasicDbStmtAnalyzer.java|0|1|00.00%|[64]|
|:large_blue_circle:|com/starrocks/sql/analyzer/DecimalV3FunctionAnalyzer.java|0|2|00.00%|[348, 351]|
|:large_blue_circle:|com/starrocks/sql/analyzer/InsertAnalyzer.java|0|4|00.00%|[84, 85, 90, 96]|
|:large_blue_circle:|com/starrocks/sql/analyzer/DropStmtAnalyzer.java|0|1|00.00%|[104]|
|:large_blue_circle:|com/starrocks/catalog/CatalogUtils.java|0|1|00.00%|[95]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AlterDbQuotaAnalyzer.java|0|1|00.00%|[29]|
|:large_blue_circle:|com/starrocks/sql/analyzer/PartitionExprAnalyzer.java|0|2|00.00%|[39, 41]|
|:large_blue_circle:|com/starrocks/sql/analyzer/CreateTableAnalyzer.java|5|25|20.00%|[120, 121, 122, 124, 215, 220, 264, 268, 290, 291, 315, 316, 317, 320, 321, 324, 350, 372, 375, 376]|
|:large_blue_circle:|com/starrocks/sql/analyzer/FunctionAnalyzer.java|11|55|20.00%|[40, 107, 108, 115, 116, 124, 125, 129, 135, 136, 144, 153, 159, 168, 180, 183, 189, 195, 201, 207, 211, 222, 225, 243, 268, 269, 281, 282, 288, 295, 299, 300, 305, 306, 317, 323, 333, 334, 346, 347, 351, 356, 364, 365]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AlterTableStatementAnalyzer.java|7|23|30.43%|[279, 287, 292, 296, 297, 317, 320, 334, 349, 357, 427, 431, 436, 437, 441, 442]|
|:large_blue_circle:|com/starrocks/sql/analyzer/SetStmtAnalyzer.java|1|3|33.33%|[199, 210]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AnalyticAnalyzer.java|12|36|33.33%|[38, 41, 48, 51, 71, 72, 77, 78, 80, 89, 98, 151, 152, 167, 168, 203, 214, 226, 234, 255, 270, 293, 296, 297]|
|:large_blue_circle:|com/starrocks/server/NodeMgr.java|1|3|33.33%|[1079, 1080]|
|:large_blue_circle:|com/starrocks/sql/ast/Property.java|4|11|36.36%|[65, 71, 72, 75, 76, 79, 80]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AlterSystemStmtAnalyzer.java|2|5|40.00%|[54, 73, 100]|
|:large_blue_circle:|com/starrocks/sql/analyzer/BackupRestoreAnalyzer.java|3|7|42.86%|[89, 90, 162, 170]|
|:large_blue_circle:|com/starrocks/sql/ast/PropertySet.java|9|20|45.00%|[43, 51, 55, 59, 63, 64, 65, 66, 67, 72, 77]|
|:large_blue_circle:|com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java|16|34|47.06%|[188, 189, 221, 222, 241, 466, 664, 672, 678, 680, 688, 692, 695, 710, 736, 752, 755, 756]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AggregationAnalyzer.java|5|10|50.00%|[120, 121, 220, 252, 253]|
|:large_blue_circle:|com/starrocks/sql/analyzer/ExportStmtAnalyzer.java|1|2|50.00%|[107]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AlterRoutineLoadAnalyzer.java|2|4|50.00%|[44, 50]|
|:large_blue_circle:|com/starrocks/sql/analyzer/DeleteAnalyzer.java|9|16|56.25%|[80, 87, 93, 98, 112, 116, 120]|
|:large_blue_circle:|com/starrocks/sql/analyzer/ExpressionAnalyzer.java|38|67|56.72%|[290, 291, 300, 301, 424, 435, 448, 449, 506, 527, 602, 640, 641, 643, 644, 674, 676, 711, 777, 783, 792, 948, 953, 957, 961, 1013, 1049, 1071, 1091]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AdminStmtAnalyzer.java|30|42|71.43%|[71, 77, 85, 107, 117, 130, 140, 147, 165, 175, 199, 222]|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/SemanticException.java|19|19|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AlterLoadAnalyzer.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/AdminCheckTabletsStmt.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AnalyzerUtils.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/AdminSetConfigStmt.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/ExpressionPartitionDesc.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/common/util/PropertyAnalyzer.java|4|4|100.00%|[]|

**Comment by packy92** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 202 / 425 (47.53%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/AlterDatabaseRenameStatementAnalyzer.java|0|2|00.00%|[28, 38]|
|:large_blue_circle:|com/starrocks/sql/analyzer/BasicDbStmtAnalyzer.java|0|1|00.00%|[64]|
|:large_blue_circle:|com/starrocks/sql/analyzer/DecimalV3FunctionAnalyzer.java|0|2|00.00%|[348, 351]|
|:large_blue_circle:|com/starrocks/sql/analyzer/InsertAnalyzer.java|0|4|00.00%|[84, 85, 90, 96]|
|:large_blue_circle:|com/starrocks/sql/analyzer/DropStmtAnalyzer.java|0|1|00.00%|[104]|
|:large_blue_circle:|com/starrocks/catalog/CatalogUtils.java|0|1|00.00%|[95]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AlterDbQuotaAnalyzer.java|0|1|00.00%|[29]|
|:large_blue_circle:|com/starrocks/sql/analyzer/PartitionExprAnalyzer.java|0|2|00.00%|[39, 41]|
|:large_blue_circle:|com/starrocks/sql/analyzer/CreateTableAnalyzer.java|5|25|20.00%|[120, 121, 122, 124, 215, 220, 264, 268, 290, 291, 315, 316, 317, 320, 321, 324, 350, 372, 375, 376]|
|:large_blue_circle:|com/starrocks/sql/analyzer/FunctionAnalyzer.java|11|55|20.00%|[40, 107, 108, 115, 116, 124, 125, 129, 135, 136, 144, 153, 159, 168, 180, 183, 189, 195, 201, 207, 211, 222, 225, 243, 268, 269, 281, 282, 288, 295, 299, 300, 305, 306, 317, 323, 333, 334, 346, 347, 351, 356, 364, 365]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AlterTableStatementAnalyzer.java|7|23|30.43%|[279, 287, 292, 296, 297, 317, 320, 334, 349, 357, 427, 431, 436, 437, 441, 442]|
|:large_blue_circle:|com/starrocks/sql/analyzer/SetStmtAnalyzer.java|1|3|33.33%|[199, 210]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AnalyticAnalyzer.java|12|36|33.33%|[38, 41, 48, 51, 71, 72, 77, 78, 80, 89, 98, 151, 152, 167, 168, 203, 214, 226, 234, 255, 270, 293, 296, 297]|
|:large_blue_circle:|com/starrocks/server/NodeMgr.java|1|3|33.33%|[1079, 1080]|
|:large_blue_circle:|com/starrocks/sql/ast/Property.java|4|11|36.36%|[65, 71, 72, 75, 76, 79, 80]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AlterSystemStmtAnalyzer.java|2|5|40.00%|[54, 73, 100]|
|:large_blue_circle:|com/starrocks/sql/analyzer/BackupRestoreAnalyzer.java|3|7|42.86%|[89, 90, 162, 170]|
|:large_blue_circle:|com/starrocks/sql/ast/PropertySet.java|9|20|45.00%|[43, 51, 55, 59, 63, 64, 65, 66, 67, 72, 77]|
|:large_blue_circle:|com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java|16|34|47.06%|[188, 189, 221, 222, 241, 466, 664, 672, 678, 680, 688, 692, 695, 710, 736, 752, 755, 756]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AggregationAnalyzer.java|5|10|50.00%|[120, 121, 220, 252, 253]|
|:large_blue_circle:|com/starrocks/sql/analyzer/ExportStmtAnalyzer.java|1|2|50.00%|[107]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AlterRoutineLoadAnalyzer.java|2|4|50.00%|[44, 50]|
|:large_blue_circle:|com/starrocks/sql/analyzer/DeleteAnalyzer.java|9|16|56.25%|[80, 87, 93, 98, 112, 116, 120]|
|:large_blue_circle:|com/starrocks/sql/analyzer/ExpressionAnalyzer.java|44|75|58.67%|[218, 220, 292, 293, 302, 303, 426, 437, 450, 451, 508, 529, 604, 642, 643, 645, 646, 676, 678, 713, 779, 785, 794, 950, 955, 959, 963, 1015, 1051, 1073, 1093]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AdminStmtAnalyzer.java|30|42|71.43%|[71, 77, 85, 107, 117, 130, 140, 147, 165, 175, 199, 222]|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/SemanticException.java|19|19|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AlterLoadAnalyzer.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/AdminCheckTabletsStmt.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AnalyzerUtils.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/AdminSetConfigStmt.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/ExpressionPartitionDesc.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/common/util/PropertyAnalyzer.java|4|4|100.00%|[]|

**Comment by packy92** [comment]
run starrocks_admit_test

**Review by kangkaisen — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 211 / 434 (48.62%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/AlterDatabaseRenameStatementAnalyzer.java|0|2|00.00%|[28, 38]|
|:large_blue_circle:|com/starrocks/sql/analyzer/BasicDbStmtAnalyzer.java|0|1|00.00%|[64]|
|:large_blue_circle:|com/starrocks/sql/analyzer/DecimalV3FunctionAnalyzer.java|0|2|00.00%|[348, 351]|
|:large_blue_circle:|com/starrocks/sql/analyzer/InsertAnalyzer.java|0|4|00.00%|[84, 85, 90, 96]|
|:large_blue_circle:|com/starrocks/sql/analyzer/DropStmtAnalyzer.java|0|1|00.00%|[104]|
|:large_blue_circle:|com/starrocks/catalog/CatalogUtils.java|0|1|00.00%|[95]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AlterDbQuotaAnalyzer.java|0|1|00.00%|[29]|
|:large_blue_circle:|com/starrocks/sql/analyzer/PartitionExprAnalyzer.java|0|2|00.00%|[39, 41]|
|:large_blue_circle:|com/starrocks/sql/analyzer/CreateTableAnalyzer.java|5|25|20.00%|[120, 121, 122, 124, 215, 220, 264, 268, 290, 291, 315, 316, 317, 320, 321, 324, 350, 372, 375, 376]|
|:large_blue_circle:|com/starrocks/sql/analyzer/FunctionAnalyzer.java|12|56|21.43%|[40, 107, 108, 115, 116, 124, 125, 129, 135, 136, 144, 153, 159, 168, 180, 183, 189, 195, 201, 207, 211, 222, 225, 243, 268, 269, 281, 282, 288, 295, 299, 300, 305, 306, 317, 323, 333, 334, 346, 347, 351, 356, 364, 365]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AlterTableStatementAnalyzer.java|7|23|30.43%|[279, 287, 292, 296, 297, 317, 320, 334, 349, 357, 427, 431, 436, 437, 441, 442]|
|:large_blue_circle:|com/starrocks/sql/analyzer/SetStmtAnalyzer.java|1|3|33.33%|[199, 210]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AnalyticAnalyzer.java|12|36|33.33%|[38, 41, 48, 51, 71, 72, 77, 78, 80, 89, 98, 151, 152, 167, 168, 203, 214, 226, 234, 255, 270, 293, 296, 297]|
|:large_blue_circle:|com/starrocks/server/NodeMgr.java|1|3|33.33%|[1079, 1080]|
|:large_blue_circle:|com/starrocks/sql/ast/Property.java|4|11|36.36%|[65, 71, 72, 75, 76, 79, 80]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AlterSystemStmtAnalyzer.java|2|5|40.00%|[54, 73, 100]|
|:large_blue_circle:|com/starrocks/sql/analyzer/BackupRestoreAnalyzer.java|3|7|42.86%|[89, 90, 162, 170]|
|:large_blue_circle:|com/starrocks/sql/ast/PropertySet.java|9|20|45.00%|[43, 51, 55, 59, 63, 64, 65, 66, 67, 72, 77]|
|:large_blue_circle:|com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java|16|34|47.06%|[188, 189, 221, 222, 241, 466, 664, 672, 678, 680, 688, 692, 695, 710, 736, 752, 755, 756]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AggregationAnalyzer.java|5|10|50.00%|[120, 121, 220, 252, 253]|
|:large_blue_circle:|com/starrocks/sql/analyzer/ExportStmtAnalyzer.java|1|2|50.00%|[107]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AlterRoutineLoadAnalyzer.java|2|4|50.00%|[44, 50]|
|:large_blue_circle:|com/starrocks/sql/analyzer/DeleteAnalyzer.java|9|16|56.25%|[80, 87, 93, 98, 112, 116, 120]|
|:large_blue_circle:|com/starrocks/sql/analyzer/ExpressionAnalyzer.java|44|75|58.67%|[218, 220, 292, 293, 302, 303, 426, 437, 450, 451, 508, 529, 604, 642, 643, 645, 646, 676, 678, 713, 779, 785, 794, 950, 955, 959, 963, 1015, 1051, 1073, 1093]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AdminStmtAnalyzer.java|30|42|71.43%|[71, 77, 85, 107, 117, 130, 140, 147, 165, 175, 199, 222]|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|5|5|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/SemanticException.java|19|19|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AlterLoadAnalyzer.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/AdminCheckTabletsStmt.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AnalyzerUtils.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/AdminSetConfigStmt.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/ExpressionPartitionDesc.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/common/util/PropertyAnalyzer.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/IntLiteral.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/LargeIntLiteral.java|3|3|100.00%|[]|

**Comment by packy92** [comment]
run starrocks_admit_test

**Review by HangyuanLiu — DISMISSED** [review]

**Comment by packy92** [comment]
run starrocks_fe_unittest

**Comment by packy92** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 212 / 434 (48.85%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/AlterDatabaseRenameStatementAnalyzer.java|0|2|00.00%|[28, 38]|
|:large_blue_circle:|com/starrocks/sql/analyzer/BasicDbStmtAnalyzer.java|0|1|00.00%|[64]|
|:large_blue_circle:|com/starrocks/sql/analyzer/DecimalV3FunctionAnalyzer.java|0|2|00.00%|[348, 351]|
|:large_blue_circle:|com/starrocks/sql/analyzer/InsertAnalyzer.java|0|4|00.00%|[84, 85, 90, 96]|
|:large_blue_circle:|com/starrocks/sql/analyzer/DropStmtAnalyzer.java|0|1|00.00%|[104]|
|:large_blue_circle:|com/starrocks/server/NodeMgr.java|0|1|00.00%|[1080]|
|:large_blue_circle:|com/starrocks/catalog/CatalogUtils.java|0|1|00.00%|[95]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AlterDbQuotaAnalyzer.java|0|1|00.00%|[29]|
|:large_blue_circle:|com/starrocks/sql/analyzer/PartitionExprAnalyzer.java|0|2|00.00%|[39, 41]|
|:large_blue_circle:|com/starrocks/sql/analyzer/CreateTableAnalyzer.java|5|25|20.00%|[120, 121, 122, 124, 215, 220, 264, 268, 290, 291, 315, 316, 317, 320, 321, 324, 350, 372, 375, 376]|
|:large_blue_circle:|com/starrocks/sql/analyzer/FunctionAnalyzer.java|12|56|21.43%|[40, 107, 108, 115, 116, 124, 125, 129, 135, 136, 144, 153, 159, 168, 180, 183, 189, 195, 201, 207, 211, 222, 225, 243, 268, 269, 281, 282, 288, 295, 299, 300, 305, 306, 317, 323, 333, 334, 346, 347, 351, 356, 364, 365]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AlterTableStatementAnalyzer.java|7|23|30.43%|[279, 287, 292, 296, 297, 317, 320, 334, 349, 357, 427, 431, 436, 437, 441, 442]|
|:large_blue_circle:|com/starrocks/sql/analyzer/SetStmtAnalyzer.java|1|3|33.33%|[199, 210]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AnalyticAnalyzer.java|12|36|33.33%|[38, 41, 48, 51, 71, 72, 77, 78, 80, 89, 98, 151, 152, 167, 168, 203, 214, 226, 234, 255, 270, 293, 296, 297]|
|:large_blue_circle:|com/starrocks/sql/ast/Property.java|4|11|36.36%|[65, 71, 72, 75, 76, 79, 80]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AlterSystemStmtAnalyzer.java|2|5|40.00%|[54, 73, 100]|
|:large_blue_circle:|com/starrocks/sql/analyzer/BackupRestoreAnalyzer.java|3|7|42.86%|[89, 90, 162, 170]|
|:large_blue_circle:|com/starrocks/sql/ast/PropertySet.java|9|20|45.00%|[43, 51, 55, 59, 63, 64, 65, 66, 67, 72, 77]|
|:large_blue_circle:|com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java|16|34|47.06%|[188, 189, 221, 222, 241, 466, 664, 672, 678, 680, 688, 692, 695, 710, 736, 752, 755, 756]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AggregationAnalyzer.java|5|10|50.00%|[120, 121, 220, 252, 253]|
|:large_blue_circle:|com/starrocks/sql/analyzer/ExportStmtAnalyzer.java|1|2|50.00%|[107]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AlterRoutineLoadAnalyzer.java|2|4|50.00%|[44, 50]|
|:large_blue_circle:|com/starrocks/sql/analyzer/DeleteAnalyzer.java|9|16|56.25%|[80, 87, 93, 98, 112, 116, 120]|
|:large_blue_circle:|com/starrocks/sql/analyzer/ExpressionAnalyzer.java|44|75|58.67%|[235, 236, 314, 315, 324, 325, 448, 459, 472, 473, 530, 551, 626, 664, 665, 667, 668, 698, 700, 735, 801, 807, 816, 972, 977, 981, 985, 1056, 1092, 1114, 1134]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AdminStmtAnalyzer.java|30|42|71.43%|[71, 77, 85, 107, 117, 130, 140, 147, 165, 175, 199, 222]|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|7|7|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/SemanticException.java|19|19|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AlterLoadAnalyzer.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/AdminCheckTabletsStmt.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AnalyzerUtils.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/AdminSetConfigStmt.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/ExpressionPartitionDesc.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/common/util/PropertyAnalyzer.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/IntLiteral.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/LargeIntLiteral.java|3|3|100.00%|[]|

**Comment by packy92** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 212 / 434 (48.85%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/AlterDatabaseRenameStatementAnalyzer.java|0|2|00.00%|[28, 38]|
|:large_blue_circle:|com/starrocks/sql/analyzer/BasicDbStmtAnalyzer.java|0|1|00.00%|[64]|
|:large_blue_circle:|com/starrocks/sql/analyzer/DecimalV3FunctionAnalyzer.java|0|2|00.00%|[348, 351]|
|:large_blue_circle:|com/starrocks/sql/analyzer/InsertAnalyzer.java|0|4|00.00%|[84, 85, 90, 96]|
|:large_blue_circle:|com/starrocks/sql/analyzer/DropStmtAnalyzer.java|0|1|00.00%|[104]|
|:large_blue_circle:|com/starrocks/server/NodeMgr.java|0|1|00.00%|[1080]|
|:large_blue_circle:|com/starrocks/catalog/CatalogUtils.java|0|1|00.00%|[95]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AlterDbQuotaAnalyzer.java|0|1|00.00%|[29]|
|:large_blue_circle:|com/starrocks/sql/analyzer/PartitionExprAnalyzer.java|0|2|00.00%|[39, 41]|
|:large_blue_circle:|com/starrocks/sql/analyzer/CreateTableAnalyzer.java|5|25|20.00%|[120, 121, 122, 124, 215, 220, 264, 268, 290, 291, 315, 316, 317, 320, 321, 324, 350, 372, 375, 376]|
|:large_blue_circle:|com/starrocks/sql/analyzer/FunctionAnalyzer.java|12|56|21.43%|[40, 107, 108, 115, 116, 124, 125, 129, 135, 136, 144, 153, 159, 168, 180, 183, 189, 195, 201, 207, 211, 222, 225, 243, 268, 269, 281, 282, 288, 295, 299, 300, 305, 306, 317, 323, 333, 334, 346, 347, 351, 356, 364, 365]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AlterTableStatementAnalyzer.java|7|23|30.43%|[279, 287, 292, 296, 297, 317, 320, 334, 349, 357, 427, 431, 436, 437, 441, 442]|
|:large_blue_circle:|com/starrocks/sql/analyzer/SetStmtAnalyzer.java|1|3|33.33%|[199, 210]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AnalyticAnalyzer.java|12|36|33.33%|[38, 41, 48, 51, 71, 72, 77, 78, 80, 89, 98, 151, 152, 167, 168, 203, 214, 226, 234, 255, 270, 293, 296, 297]|
|:large_blue_circle:|com/starrocks/sql/ast/Property.java|4|11|36.36%|[65, 71, 72, 75, 76, 79, 80]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AlterSystemStmtAnalyzer.java|2|5|40.00%|[54, 73, 100]|
|:large_blue_circle:|com/starrocks/sql/analyzer/BackupRestoreAnalyzer.java|3|7|42.86%|[89, 90, 162, 170]|
|:large_blue_circle:|com/starrocks/sql/ast/PropertySet.java|9|20|45.00%|[43, 51, 55, 59, 63, 64, 65, 66, 67, 72, 77]|
|:large_blue_circle:|com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java|16|34|47.06%|[188, 189, 221, 222, 241, 466, 664, 672, 678, 680, 688, 692, 695, 710, 736, 752, 755, 756]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AggregationAnalyzer.java|5|10|50.00%|[120, 121, 220, 252, 253]|
|:large_blue_circle:|com/starrocks/sql/analyzer/ExportStmtAnalyzer.java|1|2|50.00%|[107]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AlterRoutineLoadAnalyzer.java|2|4|50.00%|[44, 50]|
|:large_blue_circle:|com/starrocks/sql/analyzer/DeleteAnalyzer.java|9|16|56.25%|[80, 87, 93, 98, 112, 116, 120]|
|:large_blue_circle:|com/starrocks/sql/analyzer/ExpressionAnalyzer.java|44|75|58.67%|[235, 236, 314, 315, 324, 325, 448, 459, 472, 473, 530, 551, 626, 664, 665, 667, 668, 698, 700, 735, 801, 807, 816, 972, 977, 981, 985, 1056, 1092, 1114, 1134]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AdminStmtAnalyzer.java|30|42|71.43%|[71, 77, 85, 107, 117, 130, 140, 147, 165, 175, 199, 222]|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|7|7|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/SemanticException.java|19|19|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AlterLoadAnalyzer.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/AdminCheckTabletsStmt.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AnalyzerUtils.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/AdminSetConfigStmt.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/ExpressionPartitionDesc.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/common/util/PropertyAnalyzer.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/IntLiteral.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/LargeIntLiteral.java|3|3|100.00%|[]|

**Pull request merged**
