### PR TITLE
[Refactor] Extract some common utils from automv

### PR DESCRIPTION
**Pull request by satanson**
## What I'm doing:

Fixes #issue

ignore backport check: 3.1.14

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [x] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.3
  - [x] 3.2
  - [x] 3.1
  - [x] 3.0
  - [x] 2.5

### CODE REVIEW

**Review by LiShuMing — DISMISSED** [review]

**Review by packy92 — APPROVED** [review]

**Review by LiShuMing — APPROVED** [review]

**Review by andyziye — APPROVED** [review]

**Review by stdpain — APPROVED** [review]

**Review by dirtysalt — APPROVED** [review]

**Comment by satanson** [comment]
@mergifyio backport branch-3.3

**Comment by satanson** [comment]
https://github.com/Mergifyio backport branch-3.2

**Comment by satanson** [comment]
https://github.com/Mergifyio backport branch-3.1

**Comment by satanson** [comment]
ignore backport check: 3.1.14

**Comment by satanson** [comment]
ignore backport check: 3.1.15

**Pull request merged**
