### PR TITLE
[BugFix] Fix NPE when broker_addresses of export sink is empty.

### LINKED ISSUE #12301: [Bug] BE crash in ExportSink::open_file_writer if broker not exists
```
        FsBroker broker = Catalog.getCurrentCatalog().getBrokerMgr().getAnyBroker(brokerDesc.getName());
        if (broker != null) { // not set broker_addresses here
            tExportSink.addToBroker_addresses(new TNetworkAddress(broker.ip, broker.port));
        }


        } else {
            const TNetworkAddress& broker_addr = _t_export_sink.broker_addresses[0]; // NPE here
            BrokerFileSystem fs_broker(broker_addr, _t_export_sink.properties, timeout_ms);
            ASSIGN_OR_RETURN(output_file, fs_broker.new_writable_file(options, file_path));
            break;
        }

```

### PR DESCRIPTION
**Pull request by Linkerist**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #12301

## Problem Summary(Required) ：

img_v2_71cf8537-4c28-40d5-85b0-2347ab692d0g

### CODE REVIEW

**Comment by Linkerist** [comment]
run starrocks_be_unittest

**Comment by wanpengfei-git** [comment]
starrocks_be_unittest succeeded.

**Review by chaoyli — APPROVED** [review]

**Review by decster — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by Linkerist** [comment]
run starrocks_admit_test

**Pull request merged**
