### PR TITLE
[BugFix] Fix refresh mv failed when table name is upper case

### LINKED ISSUE #19379: Refresh mv failed when base table name is upper case
### Steps to reproduce the behavior (Required)
1. 
```create materialized view ex_mv_par_4
partition by emp_date
distributed by hash(empid)
PROPERTIES (
"replication_num" = "1",
"storage_medium" = "HDD",
"partition_refresh_number"="180"
) 
as
select empid, deptno, name, salary, emp_date
from `hive_catalog`.`ywb`.`EMPS_PAR`;
```
The hive table name in hive is actually in lower case.
2. 
```
refresh materialized view ex_mv_par_4
```

### Expected behavior (Required)
refresh success

### Real behavior (Required)
image

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by Youngwb**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #19379

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 3.0
  - [x] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Review by ABingHuang — APPROVED** [review]

**Review by murphyatwork — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by Youngwb** [comment]
run starrocks_fe_unittest

**Comment by Youngwb** [comment]
run starrocks_admit_test

**Comment by Youngwb** [comment]
run starrocks_fe_unittest

**Comment by Youngwb** [comment]
run starrocks_fe_unittest

**Comment by Youngwb** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 26 / 38 (68.42%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java|14|21|66.67%|[608, 609, 610, 611, 612, 613, 614]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AnalyzerUtils.java|12|17|70.59%|[371, 372, 373, 374, 375]|

**Comment by Youngwb** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
