### PR TITLE
[BugFix] fix multiple statements cannot be split correctly

### PR DESCRIPTION
**Pull request by packy92**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #1988

## Problem Summary(Required) ：

Because of removing `MINUS` from the preserved words, the sql `select * from t1 minus select * from t2` has been parsed into two statements `select * from t1 minus` and `select * from t2`. 
The reason to this situation is the sqlStatements rule has a little problem:
```
sqlStatements
    : singleStatement* EOF
    ;

singleStatement
    : statement (MINUS_SYMBOL MINUS_SYMBOL)? SEMICOLON? | emptyStatement
    ;

emptyStatement
    : SEMICOLON
    ;
``` 
If the antlr parsed to` select * from t1 minus`, it think it's a complete sql and put it into sqlStatmentsContext then parse the left tokens. Actually sql like `select * from tbl  anywords select * from tbl` will be parsed into two sqls.
The end flag of one sql should be a `SEMICOLON` or `EOF`.
53f7e117-34eb-4566-9456-76aca54d6268

If `MINUS` is a non-preserved words, the antlr will think it as a table alias or MINUS opertation and probe both branches. When parsing the next word, the first branch is invalid so it chooses the second branch finally. 

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 3.0
  - [x] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Comment by packy92** [comment]
run starrocks_admit_test

**Comment by packy92** [comment]
run starrocks_admit_test

**Review by kangkaisen — DISMISSED** [review]

**Review by HangyuanLiu — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by packy92** [comment]
run starrocks_admit_test

**Comment by packy92** [comment]
run starrocks_admit_test

**Comment by packy92** [comment]
run starrocks_admit_test

**Review by kangkaisen — DISMISSED** [review]

**Comment by packy92** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by kangkaisen — APPROVED** [review]

**Review by HangyuanLiu — APPROVED** [review]

**Pull request merged**
