### PR TITLE
[Enhancement]Optimize delete_expired_stale_rowset implementation

### PR DESCRIPTION
**Pull request by meegoo**
## What type of PR is this：
- [ ] bug
- [ ] feature
- [x] enhancement
- [ ] others

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

1. Minimize the scope of locks to avoid publish long tails
2. Remove unnecessary code & add some timer

### CODE REVIEW

**Review by chaoyli — APPROVED** [review]

**Review by imay — APPROVED** [review]

**Comment by meegoo** [comment]
@mergify branch-2.2

**Comment by meegoo** [comment]
@mergify branch-2.1

**Comment by meegoo** [comment]
@mergify branch-2.0

**Comment by meegoo** [comment]
@mergify backport branch-2.2

**Comment by meegoo** [comment]
@mergify backport branch-2.1

**Comment by meegoo** [comment]
@mergify backport branch-2.0

**Comment by mofeiatwork** [comment]
@meegoo you need to manually backport this PR to branch-2.2 since there's code conflict.

**Pull request merged**
