### PR TITLE
 [BugFix]Fix unrecognize database name with uppercase in udf FunctionName

### PR DESCRIPTION
**Pull request by liuzhongjun89**
## What type of PR is this:
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes:
Fixes #

## Problem Summary(Required):
we can create database with uppercase, while convert FunctionName to lowercase when create/drop udf,  this leads to Unknown database.  eg:
1 create database 'Test_db'
2 create/drop function in 'Test_db'
3 operation failed with "com.starrocks.common.DdlException: Unknown database 'test_db'"

image
## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 3.0
  - [x] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Comment by kangkaisen** [comment]
Please add UT cover this bug, thanks.

**Comment by liuzhongjun89** [comment]
> Please add UT cover this bug, thanks.

added

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 5 / 6 (83.33%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/analysis/FunctionName.java|0|1|00.00%|[57]|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|5|5|100.00%|[]|

**Review by imay — APPROVED** [review]

**Review by kangkaisen — APPROVED** [review]

**Comment by stdpain** [comment]
https://github.com/Mergifyio backport branch-3.0 branch-3.1

**Pull request merged**
