### PR TITLE
[Enhancement] Query queue supports compute node

### PR DESCRIPTION
**Pull request by ZiheLiu**
Signed-off-by: ZiheLiu <ziheliu1024@gmail.com>

## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes https://github.com/StarRocks/StarRocksTest/issues/1877

## Problem Summary(Required) ：

1. Compute node reports resource usage by `AgentServer`.
2. `QueryQueueManager` considers compute nodes.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 18 / 33 (54.55%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/system/SystemInfoService.java|0|5|00.00%|[455, 456, 457, 459, 653]|
|:large_blue_circle:|com/starrocks/leader/ReportHandler.java|5|15|33.33%|[171, 173, 174, 177, 178, 180, 181, 182, 183, 184]|
|:large_blue_circle:|com/starrocks/qe/QueryQueueManager.java|5|5|100.00%|[]|
|:large_blue_circle:|com/starrocks/common/proc/ComputeNodeProcDir.java|8|8|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 18 / 33 (54.55%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/system/SystemInfoService.java|0|5|00.00%|[455, 456, 457, 459, 653]|
|:large_blue_circle:|com/starrocks/leader/ReportHandler.java|5|15|33.33%|[171, 173, 174, 177, 178, 180, 181, 182, 183, 184]|
|:large_blue_circle:|com/starrocks/qe/QueryQueueManager.java|5|5|100.00%|[]|
|:large_blue_circle:|com/starrocks/common/proc/ComputeNodeProcDir.java|8|8|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 37 / 37 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/QueryQueueManager.java|5|5|100.00%|[]|
|:large_blue_circle:|com/starrocks/system/SystemInfoService.java|9|9|100.00%|[]|
|:large_blue_circle:|com/starrocks/common/proc/ComputeNodeProcDir.java|8|8|100.00%|[]|
|:large_blue_circle:|com/starrocks/leader/ReportHandler.java|15|15|100.00%|[]|

**Review by kangkaisen — APPROVED** [review]

**Review by satanson — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
