### PR TITLE
[BugFix] Fix the `show_be_version.sh` script execute error due to the lack of cachelib dependency

### PR DESCRIPTION
**Pull request by GavinMar**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes https://github.com/StarRocks/StarRocksTest/issues/1452

## Problem Summary(Required) ：

StarRocks BE depends some cachelib dependency now, if not specify the library path, the binary may execute failed.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
## Please check the version labels which this pr will be auto backported to target branch and click the checkbox:

- [ ] check done.

**Comment by GavinMar** [comment]
run starrocks_admit_test

**Review by DorianZheng — APPROVED** [review]

**Comment by GavinMar** [comment]
run starrocks_admit_test

**Review by dirtysalt — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by Youngwb — APPROVED** [review]

**Pull request merged**
