### PR TITLE
[BugFix] Fix resource group in audit log and persist planCostRange

### PR DESCRIPTION
**Pull request by ZiheLiu**
- Because the resource group classifier supports `planCostRange` now, which can only be available after generating the plan in the leader FE for `INSERT INTO` SQLs., it cannot get the selected resource group from the follower FE for `INSERT INTO` SQLs. Therefore, Add a new field  `resource_group_name` to `TMasterOpResult`.
- Add `@SerializedName` to all the fields in `ResourceGroupClassifier::CostRange`.
```java
    /*
     * The exclusion strategy of GSON serialization.
     * Any fields without "@SerializedName" annotation with be ignored with
     * serializing and deserializing.
     */
    public static class HiddenAnnotationExclusionStrategy implements ExclusionStrategy {
        public boolean shouldSkipField(FieldAttributes f) {
            return f.getAnnotation(SerializedName.class) == null;
        }

        @Override
        public boolean shouldSkipClass(Class<?> clazz) {
            return false;
        }
    }
```

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.2 
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:disappointed: **fail** : 14 / 19 (73.68%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/LeaderOpExecutor.java|0|2|00.00%|[114, 115]|
|:large_blue_circle:|com/starrocks/qe/ConnectProcessor.java|0|2|00.00%|[721, 722]|
|:large_blue_circle:|com/starrocks/sql/analyzer/ResourceGroupAnalyzer.java|3|4|75.00%|[148]|
|:large_blue_circle:|com/starrocks/persist/ResourceGroupOpEntry.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/ResourceGroupClassifier.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/ResourceGroupMgr.java|4|4|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by satanson — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:disappointed: **fail** : 13 / 17 (76.47%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/LeaderOpExecutor.java|0|2|00.00%|[114, 115]|
|:large_blue_circle:|com/starrocks/qe/ConnectProcessor.java|0|2|00.00%|[721, 722]|
|:large_blue_circle:|com/starrocks/sql/analyzer/ResourceGroupAnalyzer.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/ResourceGroupClassifier.java|8|8|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/ResourceGroupMgr.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by liuyehcf — APPROVED** [review]

**Review by satanson — APPROVED** [review]

**Comment by ZiheLiu** [comment]
@Mergify backport branch-3.2

**Pull request merged**
