### PR TITLE
[BugFix] Scalar subquery add corrletaion predicate check

### LINKED ISSUE #9618: [sqlancer] query cast error
### Steps to reproduce the behavior (Required)
```
DROP DATABASE IF EXISTS h0;
CREATE DATABASE h0;
USE h0;
admin set frontend config ("enable_decimal_v3" = "true");
CREATE TABLE IF NOT EXISTS t0 (c_0_0 INT NOT NULL,c_0_1 BOOLEAN NOT NULL,c_0_2 DOUBLE NOT NULL,c_0_3 ARRAY<STRING> NOT NULL,c_0_4 ARRAY<INT> NOT NULL,c_0_5 BOOLEAN NOT NULL,c_0_6 VARCHAR(21) NOT NULL,c_0_7 BOOLEAN NOT NULL,c_0_8 DATETIME NOT NULL,c_0_9 DATETIME NOT NULL,c_0_10 VARCHAR(21) NOT NULL,c_0_11 VARCHAR(21) NOT NULL,c_0_12 DECIMAL(26, 13)  NOT NULL,c_0_13 DATETIME NOT NULL,c_0_14 LARGEINT NOT NULL,c_0_15 DOUBLE NOT NULL,c_0_16 ARRAY<STRING> NOT NULL,c_0_17 ARRAY<INT> NOT NULL,c_0_18 DECIMAL(7, 6)  NOT NULL) PRIMARY KEY (c_0_0) DISTRIBUTED BY HASH (c_0_0) BUCKETS 3 properties("replication_num"="3") ;
CREATE TABLE IF NOT EXISTS t1 (c_1_0 BOOLEAN NOT NULL ,c_1_1 DATETIME NULL ,c_1_2 BOOLEAN NOT NULL ,c_1_3 CHAR(41) NOT NULL ,c_1_4 DATETIME NULL ,c_1_5 BOOLEAN NOT NULL ,c_1_6 SMALLINT NULL ,c_1_7 SMALLINT NULL ,c_1_8 VARCHAR(11) NULL ,c_1_9 BOOLEAN NULL ,c_1_10 DOUBLE NULL ,c_1_11 ARRAY<STRING> NOT NULL ,c_1_12 DOUBLE NOT NULL ,c_1_13 DECIMAL(23, 18)  NOT NULL ,c_1_14 DECIMAL(15, 13)  NOT NULL , INDEX index1_c_1_2(`c_1_2`) USING BITMAP) UNIQUE KEY (c_1_0,c_1_1,c_1_2,c_1_3,c_1_4,c_1_5,c_1_6,c_1_7,c_1_8) PARTITION BY RANGE(c_1_1) (START ("2010-01-01") END ("2022-12-31") EVERY (INTERVAL 98 day)) DISTRIBUTED BY HASH (c_1_3,c_1_0,c_1_6,c_1_2) BUCKETS 3 properties("replication_num"="3", "bloom_filter_columns"="c_1_6") ;
CREATE TABLE IF NOT EXISTS t2 (c_2_0 DATE NULL ,c_2_1 BOOLEAN NULL ,c_2_2 JSON NULL ,c_2_3 ARRAY<STRING> NOT NULL ,c_2_4 BOOLEAN NULL ,c_2_5 JSON NULL ,c_2_6 DECIMAL(18, 15)  NOT NULL ,c_2_7 BOOLEAN NULL ,c_2_8 LARGEINT NOT NULL ,c_2_9 DECIMAL(14, 2)  NULL ,c_2_10 CHAR(21) NULL ,c_2_11 INT NOT NULL ,c_2_12 DATETIME NULL ,c_2_13 ARRAY<INT> NULL ,c_2_14 BOOLEAN NULL ,c_2_15 DOUBLE NULL ,c_2_16 LARGEINT NOT NULL ,c_2_17 BIGINT NOT NULL ,c_2_18 DECIMAL(26, 14)  NOT NULL ) DUPLICATE KEY (c_2_0) PARTITION BY RANGE(c_2_0) (START ("2010-01-01") END ("2022-12-31") EVERY (INTERVAL 678 day)) DISTRIBUTED BY HASH (c_2_0) BUCKETS 3 properties("replication_num"="3", "bloom_filter_columns"="c_2_16") ;
INSERT INTO t1 VALUES (true, '2009-12-31 08:00:14', true, 'fSMq69', '2010-01-01 08:00:14', true, NULL, 0, '9', false, 0.9035473075577958, ["Idm", "PhQD", "M", "1h", "F6ksmjY", "yM", "UDN77gbN", "mE", "mliYcso8", "3R5vI", "dGz", "5Plq", ""], 0.9035473075577958, 9.3962E-14, 9E-13), (false, '2010-01-21 08:00:14', false, '', '2010-01-23 08:00:14', false, 2, 13, 'UtI', NULL, 0.25655708431510305, [""], 0.5656212395328153, 4.763E-15, 4E-13);
INSERT INTO t2 VALUES ('2010-01-06', false, parse_json('{"E": "dptJui"}'), ["wL", "xT30KHBZ", "K", "Hq", "7", "n9", "fzxJE3"], true, parse_json('{"juti": true, "C": 0.05285455183326071, "ZScF": ["DP", [], ["7", true, null, null], 2.24955086E8, 0.1531515700345848, true, null, "", [], ["r", true, true, 1028370175, null, 1.028370175E9, "2", 1855847666, null], {"4V": null, "E": "kAwk", "KpFPa": null, "TxFjGImB": true, "f5cMtEf": null, "mX5XhKvPP": "7t4bBoc", "GMVEXSr": null}, "RvprsR5", false, 0.25817039246274653, null], "yG4e9HH3": "Y", "Pk6g": 224955086, "S2m8": true}'), 5.39E-13, false, 1497868992, NULL, '', 27, '2010-01-03 08:00:14', [-1486808010, 1028370175, -1486808010, 621989955, 1621649920, -167434466, -454166108, 1780085887, -192002066, 1888690208, -1597683174, -408763682, 621989955, -1274800904, 768841770], false, 0.10533465233049333, -1872767009, 2052727870, 0.00306563662347);
INSERT INTO t2 VALUES ('2010-01-14', true, parse_json('{"bS3": {"elMc": {"tD": null, "8UFN4k": true, "E": null, "rREZU5b": null, "OQh": -674655519, "X": "bu8MB87", "QoayjB": null, "xae": "NkaUB7ZeY", "5ZjYjN": null}, "WvWX10": {"2l8oJc3A": "cedd", "JuPJ": -4.02387172E8}, "g": "si9cSRs", "hA": null, "IO8rnpbpQ": null, "aN": {"B": null, "CF": null, "szL": 768841770, "03XULqC": true, "l": 1581958274, "D3": -2065694113, "T2Ay": -167434466, "FHroDDy": true, "3": false, "T": null, "Z": null, "ujaRd": -402387172, "gE": -2065694113}, "2wgxzXek": ""}, "OtNaPXr": "kg", "U": true, "mJFs": [0.6671113341609985, true, -586159558], "9": {"GhwohI": null, "Qi9ajMu": null, "Y": [false, true, false, true], "oX": 0.7070099629390303, "H6qO8BiC": {"a": "YpIkhc", "MIp9": -1215912794, "m3OGAL2": false, "rKZiRUCw": "T", "Os2n": null, "1Jf": "", "Ov5": true, "sC": "w", "E9tdokdN": null, "oe": 0.9923515268490384, "OjT": true, "9": -586159558, "4o": null}}}'), ["w", "", "g", "z2IoLxKhE", "", "GiiiBs6MG", "q", "", "hyk", "GyO", "3", "NyeeE7wj", "epr"], false, parse_json('{"ypa9": "jRA", "fm": "d", "iUu": "ZW", "fkbHHn50": false, "Z": "6z", "8j476g": true, "Bn": "O7fVHyvtQ"}'), 4.05E-13, false, -1560326183, 5171406631.54, 'MTj', 5, '2010-01-31 08:00:14', [621989955, -1951581892, 70673019, -1707173445, -1769410545, 882555476, 1351277461, -402387172], false, 0.551776268202205, -674655519, 692311522, 0.00211233044934), ('2010-01-31', false, parse_json('{"4": null, "t8": null, "nfAtV": true, "g": "w8", "mE": null, "ibn8JNzf": "s", "CBKxCYlC": null, "T0": 0.8575446870461456}'), ["", "cGVSL", "8OO5SuL"], false, parse_json('{"B": null, "S": 2004812083, "v": 1386551151, "Z9pyNuNL": {}, "W": false, "PbN9": 1849739739, "8": null, "qYP": 0.850461764543265, "sEgdeYdS": "Meody3Q", "q9Gl5": 0.6935079679312057, "m": [[], 2004812083, 0.6671113341609985, 0.03540458573771488, false, {"Q": true, "q": 1351384592, "s": null, "Ad": true, "CbGKtTde": false, "cASSr": true, "aoiXM0Xo": null, "M6": -1247872902, "WHYAUx7": 0.918451472456464, "rou2UL": null, "0A7qh": true}, 0.2733049396207906, null, 1.351384592E9, {"B": true, "Qyvs": "xdjc", "Oc": null, "m5sZ3widm": 1497868992, "H": false, "gEX9C": 0.3198146725184412, "Aenc57JsV": false, "l": 0.3145702331889231, "CoX": true}]}'), 4.57E-13, true, 224955086, 7646621456.73, 'Z1', 20, '2010-01-06 08:00:14', [70673019, -192002066], false, 0.7188886684116575, -402387172, 1272306561, 0.00006987777275);
INSERT INTO t2 VALUES ('2010-01-26', NULL, parse_json('{"7IS": null}'), ["wu4GApsZA", "", "mN"], false, parse_json('{"riX": false, "FDBgR": null, "hs": ""}'), 2.61E-13, false, -675508503, 4714731554.76, 'hz', 2, '2010-01-24 08:00:14', [2052727870, -1219667096, -987947826, 935346606, 1709609164, -2081064160, 877077209, -1885057371, 1649659183], true, 0.46192230384893307, 1712587994, 1709609164, 0.00479542160699), ('2010-01-11', true, parse_json('{}'), ["sE1VFQX", "A", "", "aYk9", "", "xnp", "4lFVXJI7", "gPcxH1k"], false, parse_json('{"UMd": {"vBN": "", "c": {"1cd": null, "PL1": null, "ui": null, "Rh": null, "9DmobX": 768437195, "W": false, "w": null, "ZXQv": true, "y": true, "AlgPARWTF": "", "TxP": true, "abcjzWKBp": "6fgx"}, "t": [1712587994, true, "", null, true, 1485726997, null, 0.551776268202205, false, 1597742022, false, null], "xx8UfXaQ3": [], "TOQsk": "Bmbv0PXN3", "E3": false}}'), 5.34E-13, true, 766310057, 6745670586.77, 'hzBGSR', 19, '2010-01-09 08:00:14', [-1604092758, -1951581892, -1990875993, -903352886, 783729945, 1621649920, 291367697, -259165840, 1930188233, -402387172, -2065694113, 768841770, 692311522, -224500313, 56635199], true, NULL, -523025133, -294041836, 0.00691646557723);
INSERT INTO t0 VALUES (23, false, 0.9923515268490384, ["", "", "f752ISmk", "O", "", "", "dJBC", "", "tf5Na", "", "bHw", "yoTrSZAzk", "", "J0uWi67Y", "1ztLR"], [1251673448, -1910993139, 1404938905], true, 'kd', false, '2010-01-14 08:00:14', '2010-01-12 08:00:14', 'A', '', 0.8529009438173, '2010-01-01 08:00:14', -1990875993, 0.05285455183326071, ["WA", "", "F2Nv", "M1avQYZHt", "rw", "H0CMDj0", "qKkD4H", "4d", "6SMd", "x", "", "4", "", "ZLv"], [1231163957], 0.000004), (15, false, 0.9035473075577958, ["xiqvX9w", "2M", "2", "hk", "UMFJ90Tr"], [-158501159, 994091923], true, 'OlY6T', true, '2010-01-28 08:00:14', '2010-01-06 08:00:14', '7O', 'YgfyD5', 0.0531282616324, '2009-12-31 08:00:14', -321252046, 0.5784939922370497, ["VMflQvpz", "6V", "fgOA", "", "", "I", "BOpF25mO", ""], [2140738444, 2098276482, 2052727870, -1990875993, 192087311, -983899496, 1976693885, -163597345, 994091923, 9223372036854775807, 1649659183, -1219667096], 0.000007);
INSERT INTO t0 VALUES (31, true, 0.22751161263257802, [], [1930188233], false, '', true, '2010-01-01 08:00:14', '2010-01-31 08:00:14', 'H', '', 0.0817348230946, '2010-01-16 08:00:14', 935346606, 1.351384592E9, ["1"], [1265183326, 965779005, 1197938739, -186686764, 908080590, -1045821651, -583914278, 1750078052, 849446658, -983899496, -1280313261, -576492945, 338762483, -1215912794, 1197938739], 0.000001), (14, true, 0.4712162624124867, ["t9", "x9JiQ", "slOV6c50", "Ml", "uT", "cbn6TK", "", "uM", "1fQ1", "x", "UwCYNzz", "AIGF", "Io7", "F2vfx", ""], [687179035, 1811485536, -127810697, 2053196919, -1633889124, 153252991, -1873331833], true, 'm', false, '2009-12-31 08:00:14', '2010-01-20 08:00:14', '', 'YZ', 0.9527032859444, '2010-01-06 08:00:14', 510781063, 0.7726146918338636, ["WRnPp", "v3uvzb6", "5", "q"], [-417656309, 1036245788, 1351384592, 1841328273, 766310057, -167434466, -2065694113], 0.000008);
INSERT INTO t0 VALUES (27, false, 0.9035473075577958, ["fM", "", "DVA", "c8Fqf", "", "OMQstoxLj", "", "MUVtH7a", "", "3H", "Ez", "UO", "Zliv"], [965779005, 845888949, 203725266, -1963598999, 1930188233, -553902165, 1780085887, -999334225, 2029720725, 931938507, 1158178726, 1050299755, -586159558, -1769410545], false, '', true, '2010-01-23 08:00:14', '2010-01-07 08:00:14', 'E5', 'axa6re', 0.9158445433734, '2010-01-11 08:00:14', -512057024, 0.06637825531057362, ["DiCY", "", "7", "VS", "e", "", "rCk6D7yD", "j", "LAnEs", "Z"], [-133317406], 0.000007);
INSERT INTO t0 VALUES (31, true, 0.8128497769025144, ["", "b", "", "Di", "Z"], [-2058861169, 2090028797, -457768766, 732935905, 1327345117, 594625387, 1154354793, -192002066, 1792556602, 1931679378, -1542360734, -945794528, 291367697, -1837272444, -1633889124], true, 'Fl176cFyG', true, '2010-01-20 08:00:14', '2010-01-14 08:00:14', '9e', '5W', 0.0022670091221, '2010-01-31 08:00:14', 420034321, 0.9068065589886787, [], [12058385, -523025133, -281672841, 2119915060, -1724805907, 1533798389, -383940002], 0.000004), (2, true, 0.3131460337352203, ["GcC5cdMPm", "", "ep", "3jCa7B", "8", "OkbcvYeox", "w", "X4VdjO0", "C", "I8tp"], [1979040895, 1888690208, 1593038036, -294041836, -2015835012, -1367692897, -1787329940], true, 'a', true, '2010-01-03 08:00:14', '2010-01-15 08:00:14', '', 'rl', 0.8959616095022, '2010-01-28 08:00:14', 468382012, 0.41316736616435956, ["vMRrHL3i1", "3CJDLF", "", "gJ6", "UVsd", "2UCh9AReX", "8W8", "U", "", "T", "4rW", "YI70UF", "P", "", "9SSw"], [], 0.000002);
INSERT INTO t2 VALUES ('2010-01-25', NULL, parse_json('{"S4x": {"mKnsfs": {"7": null, "zTs": 1265183326, "Y": 224955086}, "L6p748": true, "JQP": -1.604092758E9, "I8yfS": "", "YAnMgsu": "", "k": [false, null, false, 0.32304980480933565, null, -1573244726, false, null, false, ""], "m9Hz": "5", "N": "aWmFX", "jrJLd": {"P": 0.18982547954922835, "95nl7P": true, "3": "CGaXj60x", "BG": false, "5": -1500375281, "Xo": 1888690208, "hr": null, "Jwyq5": false, "0l": "tHuqXoV", "bzU": true, "m": null, "y8": "w"}, "VQ4v": null, "w": "", "lwKuXhREL": [0.6134964029122867, 1.404938905E9, 7.68437195E8], "J7ftr": {"F": 0.2089539091830327, "f": null, "MQSoTDdE": null, "K": 0.7039820194709103, "L": -338072106, "m": null, "s": "", "EhST74N": null, "LKhtYZC": 510781063, "t": null, "W": false, "eqeT1yGmk": null, "vu": 1570826265}, "Vlz0RjIM2": [true, 352187602, "G0oqA", "YZ", false, null, true, 1497868992, null, true, true, 70673019, null, null, null], "0Dr": 994091923}, "33tmz3Wq": 0.7624202674488294, "Jc": "c4"}'), ["", "D", "Dr", "bcN", "1VTnH4JI", "Ll", "6LWC24"], false, parse_json('{"nO": 751303753, "5": false, "8": true, "nWt": -1597683174, "vR": false, "N": "8I"}'), 2.79E-13, false, -1152164126, NULL, 'qb89', 22, '2010-01-28 08:00:14', [], true, 0.35136980806613904, -1924406664, 2080511215, 0.00205653152142), ('2010-01-29', false, parse_json('{"q": false, "fYXVHoh6d": null, "FwPt": null, "4": false, "oHrTV94": "GL5fws9w", "wyihcd": "mm", "eQT": null, "E2": null, "3LDEFMGhP": "mgtj", "Fu": false}'), ["KEZmNp", "rvlmmb4", "uE", "", "Iz", "ad", "XFPU", "", "E", "QMAh", "", "D", "T"], true, parse_json('{"baFgR": null, "a": 0.7018726455654966, "wBcZo": 0.8770400521366426, "T3vllU": false, "sda8vqzPo": null, "pnyuR": 621989955, "Q70": null, "L": null, "nkN": null, "bCS14": -1729755956, "1F16pH6q": null, "jl9JsUE": true, "W0": "o", "hrd": false, "ZY": null}'), 4.14E-13, NULL, -163597345, 646280765.53, 'eNp5ymqG', 26, '2010-01-03 08:00:14', [-597564867, -1169994110, -1097419002, -1103365536, 1285462107, 576055069, 1068562059, -1299003924, -433475636], NULL, 0.06547179518456914, 1854785274, 728731159, 0.00319387754659);
INSERT INTO t1 VALUES (true, '2009-12-31 08:00:14', false, 'B', '2010-01-30 08:00:14', true, NULL, 4, '', false, NULL, [], 0.3588769093210208, 2.19E-16, 7.2E-12), (true, NULL, false, 'M0Mmuri', '2010-01-28 08:00:14', false, 9, 13, 'up', false, 1.265183326E9, ["", "V", "N", "", "", "1M", "T", "", "fWLUJf"], 0.9923515268490384, 2.5983E-14, 8.0E-12);
INSERT INTO t0 VALUES (29, false, 0.33986209000262235, ["ia", "", "tXh", "VkoY", "l", "O"], [1940578825, 1930188233, -1872767009, -294041836, 994091923, 56635199, 679799604, 402111273, 1888690208, -89141309, 1251673448], true, '', false, '2010-01-24 08:00:14', '2010-01-05 08:00:14', '', 'B', 0.9632439878476, '2010-01-29 08:00:14', -587253252, 0.32304980480933565, [""], [2004812083, -523025133, -1548614240, 2098276482, -157023670, 633307841, 1631598609, 70673019, -1769410545, -408763682, -1707173445, 2004812083, -983899496, 50485163, 2090697263], 0.000004), (10, false, 7.83729945E8, ["", "2aCbQgsFT", "p", "NVqGS1J", "NsS8q", "", "m0", "eTsv", "fh48M", "P", "k6ZZi5b6b"], [-1274800904, 310379072, -186686764, -1670855685, -180698680, 545994784, 965779005, -1597683174, 692311522, -1486808010, 2029206786, 1849739739], false, '3LxHFUy', false, '2010-01-20 08:00:14', '2010-01-20 08:00:14', 'srDyLl', '', 0.5812129700577, '2010-01-19 08:00:14', -158501159, 0.6749412819636916, ["we0", "", "fKtCsH", "6", "eM", "iJ", "", "IAHRQdB9V", "1hX", "L4hoMLrSS"], [-1707173445, 1689191366, 994091923, 768841770, 0, 1180605655, 2111675633, -1699714775, -1984907309, -1471549873, -2129830, -1553370976, -321252046], 0.000004), (0, false, 0.26031402198543085, ["", "m", "fK"], [-885680599, -402387172, -1161151387, 1348235399, 108613506, 1658590698, -436089360, -765819915, 2122362976], false, 'Ui', false, '2010-01-21 08:00:14', '2010-01-31 08:00:14', '', '', 0.3492717844138, '2010-01-17 08:00:14', 1467614859, 6.21989955E8, ["", "R8i5Ag", "", ""], [1841328273, 935346606, 624866089, 1351277461, 1860602301, 1674178470, 1028370175, -167434466, 2098276482], 0.000008);
INSERT INTO t0 VALUES (15, false, -1.597683174E9, ["TDgHx"], [1265183326, 1397237930, -417656309, -1024822098, -204963721, -1278711122, 692311522, -523025133, -1560326183, -2079436284, -157146655, -583914278], true, '', false, '2010-01-11 08:00:14', '2010-01-18 08:00:14', 'l', '', 0.9004199307376, '2010-01-30 08:00:14', 262979181, 0.49927862901322373, ["TF", "", "", "guIp3uY", "", "wYG7e8ACI"], [1649659183, -1089274161, 692311522, -93651674, 1811485536, 2004812083], 0.000000), (4, false, -2.94041836E8, ["Upr8NR", "2X2Ya", "WQdfa", "", "spt", "", "", "V"], [908080590], true, 'HHUdsbm', false, '2010-01-15 08:00:14', '2010-01-29 08:00:14', '', 'YDBWxw4E', 0.3954600917654, '2010-01-20 08:00:14', -861969189, 0.08007298489076187, ["", "1", "", "D", "Hm3L2", "H", "5A", "SsYX2AP", "VM1uFHD", "j"], [-674655519, -783122925, -148839323, -1651864432, -127259179, -590083947, -576492945, 2123223381, -1872235621], 0.000006);
INSERT INTO t1 VALUES (false, NULL, false, '', '2010-01-06 08:00:14', false, 13, 0, '', false, NULL, ["", "l1qJVX", "", "FD"], 0.33986209000262235, 6.4588E-14, 1.2E-12), (true, '2010-01-18 08:00:14', false, '2B', '2010-01-04 08:00:14', true, 13, 2, '', false, 0.5952574959343447, ["l", "o0", "FX5KJ8G", "CRwPMjzO", "7A", "s", "", "RA5l", "YNZkYbV"], 0.41316736616435956, 4.3157E-14, 1.3E-12);
INSERT INTO t0 VALUES (22, true, 0.8048610632794841, [""], [-192002066, -163597345], false, 'zrkO', false, '2010-01-01 08:00:14', '2010-01-17 08:00:14', '', 'q', 0.2480949269661, '2010-01-05 08:00:14', 1197938739, 0.8966927072684531, ["", "74hzG", "", "Ou", "87Th5y", "UU", "BsghN", "", "lj6Sh", "", "VlY", "q8MY17", "Rz"], [-583914278, -57647158, 1350050629, -523025133, 1956802756, 2105447269, -486015976, 1592420055, 877077209], 0.000001);
INSERT INTO t1 VALUES (false, '2010-01-18 08:00:14', true, 'B', '2010-01-06 08:00:14', true, 12, 5, '', false, 0.8435700342398165, ["r", "K2W72wOZ", "", "m1YwAM", "J", "K", "NkX", "N", "4Zoqvy", "5"], 1.265183326E9, 8.0742E-14, 9.1E-12), (true, '2010-01-15 08:00:14', false, '', '2010-01-14 08:00:14', true, 9, 2, '', true, 0.014591731891357984, ["vdHlOmq7g", "", "2edT", "j3", "", ""], 0.5436800174249687, 8.6848E-14, 4.5E-12);
INSERT INTO t0 VALUES (31, true, 0.40076583533071963, ["", "tHH2b", "sIQMb", "", "TK", "gF", "P7", "", "W4J", "9", "20C3", "", "x"], [-1857530956, 11647940, -98547137, -651106177, 735738206], false, '', false, '2010-01-01 08:00:14', '2010-01-12 08:00:14', '19o', 'qu7b6', 0.5723443416173, '2010-01-12 08:00:14', -186686764, 0.22221698120570932, ["5u", "shMhWt", "18UYdJ", "foAW", "H4", "", "", "u", "fXQ9omkv", "WvL", "h", "s1h1", "w"], [-603003400, -876368716, 687179035, -613110892, 1750078052], 0.000007), (14, false, 0.6956527675026424, ["", "wD1yTVTKM", "uuS", "sq", "EO", "fWKidGh", "V", "j", "Ee", "a", "mGTy", "", "fNl", "yWUff"], [1709609164, 1660194944, -675508503, 1287083283, 855882491, 1327055497, 1888741888, 1780085887, -847621967, 132630634, 1476928950, -620443639, 9223372036854775807, -1219667096], false, 'hzt', true, '2010-01-11 08:00:14', '2010-01-06 08:00:14', '', 'INuwtX', 0.4065020009321, '2010-01-27 08:00:14', -983899496, -1.63597345E8, ["bGT0o", "Q", "YS46", "n1", "", "", "HtjijTIO", "", "upG92"], [-724525561, -454166108, 130812982, -399226401, 475663885, 965779005, 691525256, 1563378542, 1070995117, 37081889], 0.000003);
INSERT INTO t1 VALUES (true, '2010-01-21 08:00:14', false, '12X9', '2010-01-09 08:00:14', true, 12, 8, '', true, NULL, ["qDe5cRzY", "", "9O"], 0.09355897147731884, 4.7164E-14, 4.3E-12), (false, '2010-01-05 08:00:14', true, 'lWJ2', '2010-01-07 08:00:14', false, 10, 2, '', false, 0.16609417742308374, ["UxxBqbgO", "deCN", "n", "B", "dB", "", "g", "u", "XQDcYpXYr", "", "Go", "R", ""], 0.7053313262073696, 7.9265E-14, 3.3E-12);
DELETE FROM t2 WHERE c_2_0='1969-12-12';
INSERT INTO t0 VALUES (29, false, 9.65779005E8, ["", "7PHF", "GY", "3u", "xYd", "6", "BHGa7L", "", "Q", "5p", "", "", "VA", "", "JnxDE69yH"], [-375343344, 1497868992, 1887926467, 338762483, 1222325649, 1843642824, 488110900, 1135363006, 845888949, 965779005], true, 'as484h', true, '2010-01-18 08:00:14', '2010-01-03 08:00:14', 'b', '7A', 0.4321295047775, '2010-01-23 08:00:14', -725422504, 0.04710103511457553, ["", "xl", "50Hrw", "U9iDlLAO", "qGmkbfpe", "E"], [-2070532843, -2022175376, -877365240, -1633889124], 0.000000);
INSERT INTO t1 VALUES (true, '2010-01-12 08:00:14', true, 'mtb7z', '2010-01-21 08:00:14', false, 1, 2, 'j', false, 1.351277461E9, ["k", "DXyt2Rz", "H", "", "", "I", "sdyu", "", "bI7Y1Qg"], 9.35346606E8, 7.6975E-14, 7.4E-12);
TRUNCATE TABLE t2;
mysql> SELECT MONTH('1969-12-10 16:42:42')  FROM t1 AS t1_7,  t0 AS t0_6 FULL JOIN t2 AS t2_8 ON t0_6.c_0_11 = t2_8.c_2_14 AND 'e' <= CASE  WHEN false THEN t2_8.c_2_14 ELSE t2_8.c_2_14 END AND t0_6.c_0_11 != t2_8.c_2_15 AND t0_6.c_0_11 < t2_8.c_2_15 AND t0_6.c_0_2 < t2_8.c_2_1 AND t0_6.c_0_2 <= t2_8.c_2_1 WHERE ((t2_8.c_2_7) IS NULL) GROUP BY  ( (SELECT t0_6.c_0_0 FROM t0 AS t0_6 WHERE NULLIF((NOT (true)),  ( ((-1560326183)+(((106410160)*(-669855221)))) ) > ( t2_8.c_2_17 ) ) )  ) != ( (SELECT t2_8.c_2_12 FROM t0 AS t0_6, t2 AS t2_8, t1 AS t1_7 WHERE  ( (SELECT t1_7.c_1_2 FROM t2 AS t2_8, t1 AS t1_7, t0 AS t0_6 WHERE true)  ) = ( (SELECT t1_7.c_1_2 FROM t1 AS t1_7 WHERE CAST(NULL AS BOOLEAN ) )  ) )  ) , t0_6.c_0_0, 1648701586.23;
ERROR 1064 (HY000): com.starrocks.sql.optimizer.operator.scalar.CallOperator cannot be cast to com.starrocks.sql.optimizer.operator.scalar.BinaryPredicateOperator
```

```
fe.log:
2022-08-05 15:40:14,907 WARN (starrocks-mysql-nio-pool-14|1129) [StmtExecutor.execute():490] execute Exception, sql SELECT MONTH('1969-12-10 16:42:42')  FROM t1 AS t1_7,  t0 AS t0_6 FULL JOIN t2 AS t2_8 ON t0_6.c_0_11 = t2_8.c_2_14 AND 'e' <= CASE  WHEN false THEN t2_8.c_2_14 ELSE t2_8.c_2_14 END AND t0_6.c_0_11 != t2_8.c_2_15 AND t0_6.c_0_11 < t2_8.c_2_15 AND t0_6.c_0_2 < t2_8.c_2_1 AND t0_6.c_0_2 <= t2_8.c_2_1 WHERE ((t2_8.c_2_7) IS NULL) GROUP BY  ( (SELECT t0_6.c_0_0 FROM t0 AS t0_6 WHERE NULLIF((NOT (true)),  ( ((-1560326183)+(((106410160)*(-669855221)))) ) > ( t2_8.c_2_17 ) ) )  ) != ( (SELECT t2_8.c_2_12 FROM t0 AS t0_6, t2 AS t2_8, t1 AS t1_7 WHERE  ( (SELECT t1_7.c_1_2 FROM t2 AS t2_8, t1 AS t1_7, t0 AS t0_6 WHERE true)  ) = ( (SELECT t1_7.c_1_2 FROM t1 AS t1_7 WHERE CAST(NULL AS BOOLEAN ) )  ) )  ) , t0_6.c_0_0, 1648701586.23
java.lang.ClassCastException: com.starrocks.sql.optimizer.operator.scalar.CallOperator cannot be cast to com.starrocks.sql.optimizer.operator.scalar.BinaryPredicateOperator
        at com.starrocks.sql.optimizer.SubqueryUtils.rewritePredicateAndExtractColumnRefs(SubqueryUtils.java:68) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.rule.transformation.ScalarApply2JoinRule.transformCorrelateWithCheckOneRows(ScalarApply2JoinRule.java:100) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.rule.transformation.ScalarApply2JoinRule.transformCorrelate(ScalarApply2JoinRule.java:70) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.rule.transformation.ScalarApply2JoinRule.transform(ScalarApply2JoinRule.java:63) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.task.TopDownRewriteTask.doExecute(TopDownRewriteTask.java:53) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.task.TopDownRewriteIterativeTask.execute(TopDownRewriteIterativeTask.java:31) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.task.SeriallyTaskScheduler.executeTasks(SeriallyTaskScheduler.java:42) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.ruleRewriteIterative(Optimizer.java:359) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.rewriteSubquery(Optimizer.java:353) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.logicalRuleRewrite(Optimizer.java:200) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.optimize(Optimizer.java:90) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.createQueryPlan(StatementPlanner.java:89) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:54) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:347) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:316) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:429) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:667) ~[starrocks-fe.jar:?]
        at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:55) ~[starrocks-fe.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_272]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_272]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_272]

```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - mysql> select current_version();
+----------------------+
| current_version()    |
+----------------------+
| MAIN-RELEASE 4c3388d |
+----------------------+

### PR DESCRIPTION
**Pull request by Seaven**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #9618

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Review by liuyehcf — APPROVED** [review]

**Review by kangkaisen — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 3 / 3 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/ScalarApply2JoinRule.java|3|3|100.00%|[]|

**Comment by Seaven** [comment]
@mergeifyio backport branch-2.4

**Comment by Seaven** [comment]
@Mergeifyio backport branch-2.4

**Comment by Seaven** [comment]
@ Mergefiyio backport branch-2.4

**Comment by Seaven** [comment]
@Mergeifyio backport branch-2.4

**Comment by Seaven** [comment]
@Mergifyio backport branch-2.4

**Pull request merged**
