### PR TITLE
[Enhancement] support to analyze external table 

### PR DESCRIPTION
**Pull request by dirtysalt**
## What type of PR is this：
- [ ] bug
- [ ] feature
- [x] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 16 / 37 (43.24%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/Table.java|0|3|00.00%|[349, 353, 357]|
|:large_blue_circle:|com/starrocks/sql/optimizer/statistics/Statistics.java|0|1|00.00%|[131]|
|:large_blue_circle:|com/starrocks/statistic/SampleStatisticsCollectJob.java|0|1|00.00%|[64]|
|:large_blue_circle:|com/starrocks/sql/optimizer/statistics/StatisticsCalculator.java|0|6|00.00%|[332, 336, 337, 339, 340, 342]|
|:large_blue_circle:|com/starrocks/statistic/StatisticExecutor.java|0|2|00.00%|[178, 179]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AnalyzeStmtAnalyzer.java|0|2|00.00%|[126, 127]|
|:large_blue_circle:|com/starrocks/qe/StmtExecutor.java|2|7|28.57%|[220, 221, 808, 819, 824]|
|:large_blue_circle:|com/starrocks/statistic/StatisticsCollectJobFactory.java|8|9|88.89%|[134]|
|:large_blue_circle:|com/starrocks/catalog/OlapTable.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/statistic/StatisticUtils.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/statistic/StatisticsCollectJob.java|1|1|100.00%|[]|

**Review by HangyuanLiu — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 16 / 37 (43.24%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/Table.java|0|3|00.00%|[349, 353, 357]|
|:large_blue_circle:|com/starrocks/sql/optimizer/statistics/Statistics.java|0|1|00.00%|[131]|
|:large_blue_circle:|com/starrocks/statistic/SampleStatisticsCollectJob.java|0|1|00.00%|[64]|
|:large_blue_circle:|com/starrocks/sql/optimizer/statistics/StatisticsCalculator.java|0|6|00.00%|[332, 336, 337, 339, 340, 342]|
|:large_blue_circle:|com/starrocks/statistic/StatisticExecutor.java|0|2|00.00%|[178, 179]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AnalyzeStmtAnalyzer.java|0|2|00.00%|[124, 125]|
|:large_blue_circle:|com/starrocks/qe/StmtExecutor.java|2|7|28.57%|[220, 221, 808, 819, 824]|
|:large_blue_circle:|com/starrocks/statistic/StatisticsCollectJobFactory.java|8|9|88.89%|[134]|
|:large_blue_circle:|com/starrocks/catalog/OlapTable.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/statistic/StatisticUtils.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/statistic/StatisticsCollectJob.java|1|1|100.00%|[]|

**Review by Seaven — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by dirtysalt** [comment]
run starrocks_admit_test

**Pull request merged**
