### PR TITLE
[bugfix] Fix CTAS speculation replication_num is wrong

### LINKED ISSUE #6993: CTAS wrong inference replicate number
### Steps to reproduce the behavior (Required)
1.create table test as select * from fir_test;
fir_test table replicate number is 3
2.create table tmpa_2 as select 1 as id;

### Expected behavior (Required)
for case 1 test should create replicate number 3
for case 2 tmpa_2 should create replicate number 1
### Real behavior (Required)
for case 1 test should create replicate number 1
for case 2 tmpa_2 should create replicate number 1

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
2.2 and 2.3

### PR DESCRIPTION
**Pull request by Astralidea**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #6993

## Problem Summary(Required) ：

The old code may have forgotten to add the logic of this piece, add UT to make this problem no longer occur.

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 7 / 7 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/CTASAnalyzer.java|7|7|100.00%|

**Review by murphyatwork — APPROVED** [review]

**Review by HangyuanLiu — APPROVED** [review]

**Comment by Astralidea** [comment]
@Mergifyio backport branch-2.3

**Comment by Astralidea** [comment]
https://github.com/Mergifyio backport branch-2.2

**Comment by Astralidea** [comment]
@Mergifyio backport branch-2.2

**Pull request merged**
