### PR TITLE
[BugFix] Add logic to handle case: when config type is array

### LINKED ISSUE #12114: frontend config error when type is array
### Steps to reproduce the behavior (Required)
`admin show frontend config like '%modules';`

### Real behavior (Required)
```
+-------------------------+------------+------------------------------+----------+-----------+---------+
| Key                     | AliasNames | Value                        | Type     | IsMutable | Comment |
+-------------------------+------------+------------------------------+----------+-----------+---------+
| audit_log_modules       | []         | [Ljava.lang.String;@4d9af434 | String[] | false     |         |
| dump_log_modules        | []         | [Ljava.lang.String;@3b9870db | String[] | false     |         |
| sys_log_verbose_modules | []         | [Ljava.lang.String;@78e1264f | String[] | false     |         |
+-------------------------+------------+------------------------------+----------+-----------+---------+
```
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
main, 2.4

### PR DESCRIPTION
**Pull request by waittttting**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #12114 

## Problem Summary(Required) ：

Add logic to handle case: when config type is array, the previous logic will get some memory addresses, not the real value of the config
## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 2 / 16 (12.50%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/common/ConfigBase.java|2|16|12.50%|[306, 308, 309, 311, 312, 314, 315, 317, 318, 320, 321, 323, 324, 326]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 14 / 16 (87.50%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/common/ConfigBase.java|14|16|87.50%|[320, 321]|

**Review by nshangyiming — APPROVED** [review]

**Comment by gengjun-git** [comment]
How to config array type in fe.conf file?

**Comment by waittttting** [comment]
> How to config array type in fe.conf file?

sys_log_verbose_modules = v1, v2, v3

**Review by gengjun-git — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by padmejin — APPROVED** [review]

**Comment by padmejin** [comment]
run starrocks_admit_test

**Review by Astralidea — APPROVED** [review]

**Pull request merged**
