### PR TITLE
[Enhancement] Lake table support transactional load

### LINKED ISSUE #18048: [StarOS] INTERNAL_ERROR when stream_load transaction prepare
### Steps to reproduce the behavior (Required)
```
[hadoop@ip-172-31-46-234 StarRocksTest]$ nosetests-3.7 -s --with-xunit --xunit-file=./result/test_stream_load_trans_py_TestStreamLoadTransaction_test_load_begin_load_prepare_rollback.xml --verbose case/system_case/test_dml/test_stream_load_transaction/test_stream_load_trans.py:TestStreamLoadTransaction.test_load_begin_load_prepare_rollback --nologcapture
/usr/local/lib/python3.7/site-packages/nose/plugins/manager.py:395: RuntimeWarning: Unable to load plugin windmill = windmill.authoring.nose_plugin:WindmillNosePlugin: No module named 'bin'
  RuntimeWarning)
test_stream_load_trans.TestStreamLoadTransaction.test_load_begin_load_prepare_rollback ... {'host': '172.31.46.234', 'port': '9030', 'user': 'root', 'password': ''}
show backends;
create database stream_load_test_db_95707168_af4f_11ed_b3b0_069c711e01c6;
use stream_load_test_db_95707168_af4f_11ed_b3b0_069c711e01c6;
decline replication_num to 1 due to lack of backends, expected replication_num=3, actual be_num=2

 CREATE TABLE `duplicate_table_with_null` ( `k1`  date, `k2`  datetime, `k3`  char(20), `k4`  varchar(20), `k5`  boolean, `k6`  tinyint, `k7`  smallint, `k8`  int, `k9`  bigint, `k10` largeint, `k11` float, `k12` double, `k13` decimal(27,9) ) DUPLICATE KEY(`k1`, `k2`, `k3`, `k4`, `k5`) COMMENT "OLAP" DISTRIBUTED BY HASH(`k1`, `k2`, `k3`) BUCKETS 3 PROPERTIES ( "replication_num" = "1", "storage_format" = "v2" );
select count(1) from duplicate_table_with_null;
curl --location-trusted -u root: -H label:stream_load_trans_957d8d6c_af4f_11ed_b3b0_069c711e01c6 -H db:stream_load_test_db_95707168_af4f_11ed_b3b0_069c711e01c6 -H table:duplicate_table_with_null -XPOST http://172.31.46.234:8130/api/transaction/begin
{'Status': 'OK', 'Message': '', 'Label': 'stream_load_trans_957d8d6c_af4f_11ed_b3b0_069c711e01c6', 'TxnId': 23221, 'BeginTxnTimeMs': 0}
curl --location-trusted -u root: -H label:stream_load_trans_957d8d6c_af4f_11ed_b3b0_069c711e01c6 -H db:stream_load_test_db_95707168_af4f_11ed_b3b0_069c711e01c6 -H table:duplicate_table_with_null -T /mnt1/StarRocksTest/lib/../common/data/basic_types_data -XPUT http://172.31.46.234:8130/api/transaction/load
{'Status': 'OK', 'Message': '', 'Label': 'stream_load_trans_957d8d6c_af4f_11ed_b3b0_069c711e01c6', 'TxnId': 23221, 'LoadBytes': 8790855, 'StreamLoadPlanTimeMs': 0, 'ReceivedDataTimeMs': 2}
select count(1) from duplicate_table_with_null;
curl --location-trusted -u root: -H label:stream_load_trans_957d8d6c_af4f_11ed_b3b0_069c711e01c6 -H db:stream_load_test_db_95707168_af4f_11ed_b3b0_069c711e01c6 -XPOST http://172.31.46.234:8130/api/transaction/prepare
{'Status': 'INTERNAL_ERROR', 'Message': ''}
drop database stream_load_test_db_95707168_af4f_11ed_b3b0_069c711e01c6;
FAIL

======================================================================
FAIL: test_stream_load_trans.TestStreamLoadTransaction.test_load_begin_load_prepare_rollback
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/mnt1/StarRocksTest/case/system_case/test_dml/test_stream_load_transaction/test_stream_load_trans.py", line 282, in test_load_begin_load_prepare_rollback
    eq_(res["Status"], "OK", res)
AssertionError: {'Status': 'INTERNAL_ERROR', 'Message': ''}

----------------------------------------------------------------------
XML: /mnt1/StarRocksTest/result/test_stream_load_trans_py_TestStreamLoadTransaction_test_load_begin_load_prepare_rollback.xml
----------------------------------------------------------------------
Ran 1 test in 0.353s

FAILED (failures=1)
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by xiangguangyxg**
## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #18048

## Problem Summary(Required) ：

Lake table support transactional load

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 3.0
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Review by sduzh — DISMISSED** [review]

**Review by tracymacding — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by wyb — DISMISSED** [review]

**Comment by sduzh** [comment]
run starrocks_fe_unittest

**Comment by sduzh** [comment]
@Mergifio backport branch-3.0

**Comment by sduzh** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 1 / 6 (16.67%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/transaction/LakeTableTxnStateListener.java|0|5|00.00%|[112, 113, 117, 118, 119]|
|:large_blue_circle:|com/starrocks/transaction/DatabaseTransactionMgr.java|1|1|100.00%|[]|

**Comment by wyb** [comment]
run starrocks_admit_test

**Comment by wyb** [comment]
run starrocks_admit_test

**Comment by wyb** [comment]
run starrocks_admit_test

**Review by wyb — DISMISSED** [review]

**Review by sduzh — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by wyb — APPROVED** [review]

**Review by sduzh — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by xiangguangyxg** [comment]
run starrocks_fe_unittest

**Comment by xiangguangyxg** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 1 / 6 (16.67%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/transaction/LakeTableTxnStateListener.java|0|5|00.00%|[112, 113, 117, 118, 119]|
|:large_blue_circle:|com/starrocks/transaction/DatabaseTransactionMgr.java|1|1|100.00%|[]|

**Comment by wyb** [comment]
run starrocks_be_unittest

**Pull request merged**
