### PR TITLE
[BugFix] fix to_bitmap statistics calculator

### LINKED ISSUE #29958: join with to_bitmap mv rewrite bug
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'

CREATE TABLE test_starrocks.test_sr_table_join( 
          fdate  int,
          fetl_time BIGINT ,
          facct_type BIGINT ,
          fqqid STRING ,
          fplat_form_itg2 BIGINT  ,
          funit BIGINT  ,
          flcnt BIGINT
 )PARTITION BY range(fdate) (
    PARTITION p1 VALUES [ ("20230702"),("20230703")),
    PARTITION p2 VALUES [ ("20230703"),("20230704")),
    PARTITION p3 VALUES [ ("20230704"),("20230705")),
    PARTITION p4 VALUES [ ("20230705"),("20230706"))
 )
 DISTRIBUTED BY HASH(fqqid)
 PROPERTIES (
    "replication_num" = "1"
);

insert into test_starrocks.test_sr_table_join (fdate,facct_type,fqqid,fplat_form_itg2,funit,flcnt)
values (20230702,1,'aaaaa',2,1000,2000), (20230703,1,'bbbbb',3,6000,7000),  (20230704,1,'cccccc',5,10300,24000), (20230705,1,'dddd',6,9000,8000);

create table test_starrocks.dim_test_sr_table (
    fplat_form_itg2 bigint,
    fplat_form_itg2_name string
)DISTRIBUTED BY HASH(fplat_form_itg2)
PROPERTIES (
    "replication_num" = "1"
);

insert into  test_starrocks.dim_test_sr_table(fplat_form_itg2,fplat_form_itg2_name) 
 values 
 (2,'微信'),
 (3,'PC'),
 (5,'QQ'),
 (6,'其他');

2. create materialized view

create MATERIALIZED VIEW test_starrocks.test_mv_sr_table_v006_1_unnest_range_bitmap
DISTRIBUTED BY HASH(fdate,fplat_form_itg2_name)
REFRESH MANUAL
AS 
    select t1.fdate, t2.fplat_form_itg2_name,  BITMAP_UNION(to_bitmap(abs(MURMUR_HASH3_32(t1.fqqid)))) AS index_0_8228, sum(t1.flcnt)as index_xxx
    FROM test_starrocks.test_sr_table_join t1 
    LEFT JOIN test_starrocks.dim_test_sr_table t2
    ON t1.`fplat_form_itg2` = t2.`fplat_form_itg2`
    WHERE t1.`fdate` >= 20230702 and t1.fdate <= 20230705
    GROUP BY  fdate, `fplat_form_itg2_name`;

3. refresh

refresh MATERIALIZED VIEW test_starrocks.test_mv_sr_table_v006_1_unnest_range_bitmap with sync mode;

4. query
 explain select   t2.fplat_form_itg2_name,  BITMAP_UNION_COUNT(to_bitmap(abs(MURMUR_HASH3_32(t1.fqqid)))) AS index_0_8228
    FROM test_starrocks.test_sr_table_join t1 
    LEFT JOIN test_starrocks.dim_test_sr_table t2
    ON t1.`fplat_form_itg2` = t2.`fplat_form_itg2`
    WHERE t1.`fdate` >= 20230703 and t1.fdate < 20230706
    GROUP BY   `fplat_form_itg2_name`;

### Expected behavior (Required)
query rewritten by test_mv_sr_table_v006_1_unnest_range_bitmap
### Real behavior (Required)
query not rewritten by test_mv_sr_table_v006_1_unnest_range_bitmap
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by ABingHuang**
Fixes #29958 
Fix to_bitmap function statistics calculation bug, which will lead to invalid cost and choose the wrong plan.
Fix it by modifing the average size of statistics after to_bitmap.

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [ ] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [x] 3.0
  - [x] 2.5
  - [ ] 2.4

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by kangkaisen — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 4 / 4 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/statistics/ExpressionStatisticCalculator.java|4|4|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 4 / 4 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/statistics/ExpressionStatisticCalculator.java|4|4|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 4 / 4 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/statistics/ExpressionStatisticCalculator.java|4|4|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by satanson — APPROVED** [review]

**Review by LiShuMing — APPROVED** [review]

**Review by murphyatwork — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
