### PR TITLE
[Backport][branch-2.4][BugFix] BE crash when base rowset is missing (#10161)

### PR DESCRIPTION
**Pull request by rickif**
This is an automatic backport of pull request https://github.com/StarRocks/starrocks/pull/10161 to branch-2.4.

### CODE REVIEW

**Review by wanpengfei-git — DISMISSED** [review]

**Comment by rickif** [comment]
@megifyio rebase

**Review by chaoyli — DISMISSED** [review]

**Comment by rickif** [comment]
@mergifyio rebase

**Comment by rickif** [comment]
run starrocks_clang

**Comment by rickif** [comment]
run starrocks_clang-tidy

**Review by chaoyli — APPROVED** [review]

**Pull request merged**
