### PR TITLE
[BugFix] fix crash on empty chunk of left join

### LINKED ISSUE #10392: 【outer join】be down when full join on view
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
```
 CREATE TABLE `unique_table_with_null` ( `k1` date, `k2` datetime, `k3` char(20), `k4` varchar(20), `k5` boolean, `v1` tinyint, `v2` smallint, `v3` int, `v4` bigint, `v5` largeint, `v6` float, `v7` double, `v8` decimal(27,9) ) ENGINE=OLAP UNIQUE KEY(`k1`, `k2`, `k3`, `k4`, `k5`) COMMENT "OLAP" DISTRIBUTED BY HASH(`k1`, `k2`, `k3`, `k4`, `k5`) BUCKETS 3 PROPERTIES ( "replication_num" = "3", "storage_format" = "v2" );

 CREATE TABLE `primary_table_without_null` ( `k1` date NOT NULL, `k2` datetime NOT NULL, `k3` string NOT NULL, `k4` string NOT NULL, `k5` boolean NOT NULL, `v1` tinyint NOT NULL, `v2` smallint NOT NULL, `v3` int NOT NULL, `v4` bigint NOT NULL, `v5` largeint NOT NULL, `v6` float NOT NULL, `v7` double NOT NULL, `v8` decimal(27,9) NOT NULL ) ENGINE=OLAP PRIMARY KEY(`k1`, `k2`, `k3`, `k4`, `k5`) COMMENT "OLAP" DISTRIBUTED BY HASH(`k1`, `k2`, `k3`, `k4`, `k5`) BUCKETS 3 PROPERTIES ( "replication_num" = "3", "storage_format" = "v2" );
```
2. INSERT INTO '....'
```
curl --location-trusted -u root: -T /home/disk4/lvchenyang/code/StarRocksTest/lib/../common/data/basic_types_data_without_null -XPUT -H label:stream_load_1661325050348 http://ip:port/api/test_full_join_e24fed52_237b_11ed_bd70_00163e0e550b511/primary_table_without_null/_stream_load

curl --location-trusted -u root: -T /home/disk4/lvchenyang/code/StarRocksTest/lib/../common/data/basic_types_data -XPUT -H label:stream_load_1661325050523 http://ip:port/api/test_full_join_e24fed52_237b_11ed_bd70_00163e0e550b511/unique_table_with_null/_stream_load
```
3. create view  '....'
```
CREATE VIEW view1 as select k1 as k1, k2, k3, k4,k5, SUM(v1),v2,v3,v4,v5,v6,v7,v8 FROM primary_table_without_null where k1="2020-06-23" group by k1,k2,k3,k4,k5,v2,v3,v4,v5,v6,v7,v8;

CREATE MATERIALIZED VIEW mv1 DISTRIBUTED BY HASH(k1) BUCKETS 10 REFRESH ASYNC AS  SELECT k1,k2,k3,k4,k5,v1,v2,v3,v4,v5,v6,v7,v8 FROM unique_table_with_null;
```
4. 
```
select count(*) from view1 full join mv1 on v1>mv1.v3 where view1.k5=1 or mv1.k1 is null;
```
### Expected behavior (Required)
The query is successful
### Real behavior (Required)
```
ERROR 1064 (HY000): com.baidu.brpc.exceptions.RpcException: channel is non active, ip=172.26.92.202,port=8260
*** Aborted at 1661327066 (unix time) try "date -d @1661327066" if you are using GNU date ***
PC: @          0x2d1a033 starrocks::pipeline::NLJoinProbeOperator::_probe()
*** SIGSEGV (@0x8) received by PID 2708 (TID 0x7fdca5349700) from PID 8; stack trace: ***
    @          0x4759412 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7fdd0251f630 (unknown)
    @          0x2d1a033 starrocks::pipeline::NLJoinProbeOperator::_probe()
    @          0x2d1b987 starrocks::pipeline::NLJoinProbeOperator::pull_chunk()
    @          0x2d426e3 starrocks::pipeline::PipelineDriver::process()
    @          0x2d38f23 starrocks::pipeline::GlobalDriverExecutor::_worker_thread()
    @          0x2581a25 starrocks::ThreadPool::dispatch_thread()
    @          0x257cf4a starrocks::Thread::supervise_thread()
    @     0x7fdd02517ea5 start_thread
    @     0x7fdd01b328dd __clone
    @                0x0 (unknown)
```
core file
/home/disk1/sr/qa_test_master_01/be/core.2708
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
+----------------------+
| current_version()    |
+----------------------+
| MAIN-RELEASE 47f6f73 |
+----------------------+
```

### PR DESCRIPTION
**Pull request by murphyatwork**
## What type of PR is this：
- [x] bugfix
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #10392 #10384

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by mofeiatwork** [comment]
run starrocks_admit_test

**Comment by mofeiatwork** [comment]
run starrocks_admit_test

**Review by kangkaisen — DISMISSED** [review]

**Comment by mofeiatwork** [comment]
run starrocks_admit_test

**Comment by mofeiatwork** [comment]
run starrocks_admit_test

**Comment by kangkaisen** [comment]
need test cases

**Review by kangkaisen — APPROVED** [review]

**Review by ZiheLiu — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Pull request merged**
