### PR TITLE
[Feature] suport lzo stream compression

### LINKED ISSUE #19908: Hive catalog can't read hive table with textfile lzo format
### Steps to reproduce the behavior (Required)
When use hive catalog read hive table with textfile lzo format, it will throw an exception like below :
`ERROR 1064 (HY000): Unknown compress type: 11:file =...`
图片

### Expected behavior (Required)
Get the correct data from the hive table

### Real behavior (Required)
Throw an exception like above

### StarRocks version (Required)
 - 2.5.2

### PR DESCRIPTION
**Pull request by dirtysalt**
Fixes #19908

And many thanks to this PR: #19909

## What type of PR is this:

- [ ] BugFix
- [x] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 10 / 23 (43.48%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/util/compression/stream_compression.cpp|10|23|43.48%|[429, 430, 434, 435, 436, 437, 438, 439, 443, 444, 445, 446, 447]|

**Comment by DorianZheng** [comment]
Can we also add it to block compression

**Comment by dirtysalt** [comment]
> Can we also add it to block compression

I can. But I don't have any test scenario for that.

If even if we have test scenario, I also suggest to add the feature in an another PR instead of this one.

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 123 / 197 (62.44%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/util/compression/stream_compression.cpp|123|197|62.44%|[543, 570, 584, 590, 591, 592, 593, 598, 599, 601, 602, 607, 608, 610, 611, 612, 617, 620, 640, 641, 678, 679, 684, 685, 686, 694, 695, 696, 697, 703, 704, 705, 706, 712, 713, 714, 715, 721, 722, 723, 733, 734, 735, 755, 756, 771, 772, 773, 775, 776, 777, 780, 781, 782, 784, 785, 802, 803, 804, 808, 809, 810, 811, 815, 817, 818, 824, 825, 827, 828, 829, 830, 831, 832]|

**Review by letian-jiang — APPROVED** [review]

**Review by stdpain — APPROVED** [review]

**Review by satanson — APPROVED** [review]

**Comment by dirtysalt** [comment]
@mergify backport branch-3.1

**Pull request merged**
