### PR TITLE
[Refactor] Remove Cluster.java read access interface

### PR DESCRIPTION
**Pull request by imay**
Because we need to be compatible with old version StarRocks, we can't change
the format of image and log. So we don't change the write interface of Cluster.java.
Then the old version binary can work normally when downgrade.

## What type of PR is this：
- [ ] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #

### CODE REVIEW

**Comment by imay** [comment]
@mergify rebase main

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 44 / 70 (62.86%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/master/MasterImpl.java|0|1|00.00%|
|:large_blue_circle:|com/starrocks/http/rest/TransactionLoadAction.java|0|1|00.00%|
|:large_blue_circle:|com/starrocks/common/proc/StatisticProcDir.java|0|1|00.00%|
|:large_blue_circle:|com/starrocks/clone/BeLoadRebalancer.java|0|1|00.00%|
|:large_blue_circle:|com/starrocks/http/rest/LoadAction.java|0|1|00.00%|
|:large_blue_circle:|com/starrocks/clone/TabletSchedCtx.java|0|1|00.00%|
|:large_blue_circle:|com/starrocks/master/ReportHandler.java|0|1|00.00%|
|:large_blue_circle:|com/starrocks/http/meta/ColocateMetaService.java|0|1|00.00%|
|:large_blue_circle:|com/starrocks/clone/TabletScheduler.java|1|7|14.29%|
|:large_blue_circle:|com/starrocks/clone/ClusterLoadStatistic.java|2|4|50.00%|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|8|14|57.14%|
|:large_blue_circle:|com/starrocks/system/SystemInfoService.java|10|13|76.92%|
|:large_blue_circle:|com/starrocks/common/proc/BackendsProcDir.java|7|8|87.50%|
|:large_blue_circle:|com/starrocks/load/routineload/ScheduleRule.java|2|2|100.00%|
|:large_blue_circle:|com/starrocks/clone/TabletChecker.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/cluster/Cluster.java|2|2|100.00%|
|:large_blue_circle:|com/starrocks/clone/DiskAndTabletLoadReBalancer.java|2|2|100.00%|
|:large_blue_circle:|com/starrocks/catalog/OlapTable.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/load/routineload/KafkaTaskInfo.java|2|2|100.00%|
|:large_blue_circle:|com/starrocks/clone/ColocateTableBalancer.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/load/routineload/RoutineLoadTaskInfo.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/load/routineload/KafkaRoutineLoadJob.java|3|3|100.00%|
|:large_blue_circle:|com/starrocks/qe/ShowExecutor.java|1|1|100.00%|

**Comment by imay** [comment]
run starrocks_fe_unittest

**Review by gengjun-git — APPROVED** [review]

**Comment by gengjun-git** [comment]
run starrocks_fe_unittest

**Comment by imay** [comment]
run starrocks_fe_unittest

**Comment by imay** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 44 / 70 (62.86%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/master/MasterImpl.java|0|1|00.00%|
|:large_blue_circle:|com/starrocks/http/rest/TransactionLoadAction.java|0|1|00.00%|
|:large_blue_circle:|com/starrocks/common/proc/StatisticProcDir.java|0|1|00.00%|
|:large_blue_circle:|com/starrocks/clone/BeLoadRebalancer.java|0|1|00.00%|
|:large_blue_circle:|com/starrocks/http/rest/LoadAction.java|0|1|00.00%|
|:large_blue_circle:|com/starrocks/clone/TabletSchedCtx.java|0|1|00.00%|
|:large_blue_circle:|com/starrocks/master/ReportHandler.java|0|1|00.00%|
|:large_blue_circle:|com/starrocks/http/meta/ColocateMetaService.java|0|1|00.00%|
|:large_blue_circle:|com/starrocks/clone/TabletScheduler.java|1|7|14.29%|
|:large_blue_circle:|com/starrocks/clone/ClusterLoadStatistic.java|2|4|50.00%|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|8|14|57.14%|
|:large_blue_circle:|com/starrocks/system/SystemInfoService.java|10|13|76.92%|
|:large_blue_circle:|com/starrocks/common/proc/BackendsProcDir.java|7|8|87.50%|
|:large_blue_circle:|com/starrocks/load/routineload/ScheduleRule.java|2|2|100.00%|
|:large_blue_circle:|com/starrocks/clone/TabletChecker.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/cluster/Cluster.java|2|2|100.00%|
|:large_blue_circle:|com/starrocks/clone/DiskAndTabletLoadReBalancer.java|2|2|100.00%|
|:large_blue_circle:|com/starrocks/catalog/OlapTable.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/load/routineload/KafkaTaskInfo.java|2|2|100.00%|
|:large_blue_circle:|com/starrocks/clone/ColocateTableBalancer.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/load/routineload/RoutineLoadTaskInfo.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/load/routineload/KafkaRoutineLoadJob.java|3|3|100.00%|
|:large_blue_circle:|com/starrocks/qe/ShowExecutor.java|1|1|100.00%|

**Review by wyb — APPROVED** [review]

**Pull request merged**
