### PR TITLE
[BugFix][Branch-2.5][Cherry-pick] Fix some bug of  separating primary key and sortkey

### PR DESCRIPTION
**Pull request by sevev**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes 

## Problem Summary(Required) ：

CherryPick https://github.com/StarRocks/starrocks/pull/16595
ChrryPick https://github.com/StarRocks/starrocks/pull/17740

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Comment by sevev** [comment]
close https://github.com/StarRocks/starrocks/pull/17851 and https://github.com/StarRocks/starrocks/pull/17386 please.

**Comment by sevev** [comment]
run starrocks_fe_unittest

**Comment by sevev** [comment]
run starrocks_fe_unittest

**Comment by sevev** [comment]
run all

**Comment by sevev** [comment]
run starrocks_fe_unittest

**Comment by sevev** [comment]
run starrocks_fe_unittest

**Comment by sevev** [comment]
run starrocks_fe_unittest

**Comment by sevev** [comment]
run starrocks_fe_unittest

**Comment by sevev** [comment]
run starrocks_fe_unittest

**Review by decster — APPROVED** [review]

**Pull request merged**
