### PR TITLE
[BugFix] fix imcomplete result of multi-unnest

### LINKED ISSUE #14722: result of multi_unnest is imcomplete
### Steps to reproduce the behavior (Required)
CREATE TABLE `tb1` (
  `id` varchar(65533) NULL COMMENT "",
  `type1` varchar(65533) NULL COMMENT "",
  `type2` varchar(65533) NULL COMMENT ""
) ENGINE=OLAP 
DUPLICATE KEY(`id`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`id`) BUCKETS 1 
PROPERTIES (
"replication_num" = "1");

insert into tb1 values("id1", "typeA;typeB", "type1;type2;type3"),("id2", "typeA;typeB;typeC", "type1;type2");

select id, t1.v1, t1.v2 from tb1, unnest(split(type1, ";"), split(type2, ";")) as t1(v1, v2);

### Expected behavior (Required)
+------+-------+-------+
| id   | v1    | v2    |
+------+-------+-------+
| id1  | typeA | type1 |
| id1  | typeB | type2 |
| id1  | NULL  | type3 |
| id2  | typeA  | type1 |
| id2  | typeB  | type2 |
| id2  | typeC  | NULL |
+------+-------+-------+

### Real behavior (Required)
+------+-------+-------+
| id   | v1    | v2    |
+------+-------+-------+
| id1  | typeA | type1 |
| id1  | typeB | type2 |
| id1  | NULL  | type3 |
+------+-------+-------+

### StarRocks version (Required)
2.5.0-XIAOHONGSHU-387 668be88

### PR DESCRIPTION
**Pull request by choury**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #14722

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Review by HangyuanLiu — APPROVED** [review]

**Review by kangkaisen — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by HangyuanLiu** [comment]
https://github.com/StarRocks/StarRocksTest/pull/1563

**Comment by HangyuanLiu** [comment]
@mergify backport branch-2.5

**Comment by HangyuanLiu** [comment]
@Mergify backport branch-2.5

**Pull request merged**
