### PR TITLE
[BugFix] fix agg in order by not being analyzed correctly

### PR DESCRIPTION
**Pull request by packy92**
Fixes #issue
For sql like 
```
select min(v1) v1 from t0 group by v3 order by round(count(v2) / min(v1)), min(v1), abs(v1);
```
The statement had been transformed to a wrong plan fragment like:
```
LogicalProjectOperator {projection=[3: v3, 5: count, 6: min, min(1: v1)]}
            ->  LogicalAggregation {type=GLOBAL ,aggregations={4: min=min(1: v1), 5: count=count(2: v2), 6: min=min(1: v1)} ,groupKeys=[3: v3]}
```
This reason is the scope for analyzing order by is combined querySource scope and output scope. For the order by elements in the sql, its scope is like `output scope: v1(tblName null), source scope: v1(tblName t0), v2(tblName t0), v3(tblName t0)`.  When analyze `min(v1)`, the v1 matched with `v1(tblName null)` firstly, while it should be `v1(tblName t0)`.  Even the old code would analyze the aggregations using source scope in the later step, the fisrt analyzed process has put the `slotRef` in a map. The second analyzed process may change the `slotRef` already in the map, leading to unexpect behavior when get obejct from the map. 
So, the better way is to distinguish the aggregation func from the normal func in the analyze orderby stage, and use the corresponding scope to process them respectively.

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [x] 3.0
  - [ ] 2.5
  - [ ] 2.4

### CODE REVIEW

**Review by kangkaisen — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 10 / 10 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/SelectAnalyzer.java|5|5|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AggregationAnalyzer.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/ExpressionAnalyzer.java|4|4|100.00%|[]|

**Review by kangkaisen — APPROVED** [review]

**Review by Seaven — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Pull request merged**
