### PR TITLE
[Refactor] Remove table statement parser / analyzer deprecated code

### PR DESCRIPTION
**Pull request by HangyuanLiu**
## What type of PR is this：
- [ ] bug
- [ ] feature
- [ ] enhancement
- [x] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 214 / 253 (84.58%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/connector/ConnectorMetadata.java|0|18|00.00%|[63, 66, 81, 84, 87, 90, 93, 96, 100, 103, 106, 110, 113, 116, 120, 124, 131, 134]|
|:large_blue_circle:|com/starrocks/sql/ast/CancelAlterTableStmt.java|11|17|64.71%|[29, 30, 43, 44, 63, 68]|
|:large_blue_circle:|com/starrocks/sql/ast/CreateViewStmt.java|6|8|75.00%|[23, 36]|
|:large_blue_circle:|com/starrocks/sql/ast/TruncateTableStmt.java|8|10|80.00%|[26, 27]|
|:large_blue_circle:|com/starrocks/sql/ast/AlterViewStmt.java|4|5|80.00%|[27]|
|:large_blue_circle:|com/starrocks/sql/ast/CreateTableLikeStmt.java|13|14|92.86%|[55]|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|115|123|93.50%|[590, 593, 634, 635, 654, 659, 660, 796]|
|:large_blue_circle:|com/starrocks/sql/ast/BaseViewStmt.java|18|19|94.74%|[66]|
|:large_blue_circle:|com/starrocks/sql/analyzer/Analyzer.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/DropTableStmt.java|21|21|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/DescribeStmt.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/ShowAlterStmt.java|8|8|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/RecoverTableStmt.java|8|8|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 214 / 253 (84.58%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/connector/ConnectorMetadata.java|0|18|00.00%|[63, 66, 81, 84, 87, 90, 93, 96, 100, 103, 106, 110, 113, 116, 120, 124, 131, 134]|
|:large_blue_circle:|com/starrocks/sql/ast/CancelAlterTableStmt.java|11|17|64.71%|[29, 30, 43, 44, 63, 68]|
|:large_blue_circle:|com/starrocks/sql/ast/CreateViewStmt.java|6|8|75.00%|[23, 36]|
|:large_blue_circle:|com/starrocks/sql/ast/TruncateTableStmt.java|8|10|80.00%|[26, 27]|
|:large_blue_circle:|com/starrocks/sql/ast/AlterViewStmt.java|4|5|80.00%|[27]|
|:large_blue_circle:|com/starrocks/sql/ast/CreateTableLikeStmt.java|13|14|92.86%|[55]|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|115|123|93.50%|[590, 593, 634, 635, 654, 659, 660, 796]|
|:large_blue_circle:|com/starrocks/sql/ast/BaseViewStmt.java|18|19|94.74%|[66]|
|:large_blue_circle:|com/starrocks/sql/analyzer/Analyzer.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/DropTableStmt.java|21|21|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/DescribeStmt.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/ShowAlterStmt.java|8|8|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/RecoverTableStmt.java|8|8|100.00%|[]|

**Review by Seaven — APPROVED** [review]

**Review by kangkaisen — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by imay** [comment]
run starrocks_admit_test

**Pull request merged**
