### PR TITLE
[Enhancement] Check compression codec for parquet writer

### PR DESCRIPTION
**Pull request by letian-jiang**
Fixes #issue

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.2
  - [x] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Review by Smith-Cruise — APPROVED** [review]

**Comment by stephen-shelby** [comment]
Unsupported types need to be disabled in fe.

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 7 / 22 (31.82%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/exec/parquet_writer.cpp|0|3|00.00%|[47, 48, 50]|
|:large_blue_circle:|src/runtime/file_result_writer.cpp|0|1|00.00%|[108]|
|:large_blue_circle:|src/formats/parquet/file_writer.cpp|7|18|38.89%|[113, 115, 119, 123, 127, 131, 135, 142, 147, 148, 149]|

**Comment by letian-jiang** [comment]
> Unsupported types need to be disabled in fe.

This has been done at FE. Double-check for BE in this PR :)

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 8 / 24 (33.33%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/exec/parquet_writer.cpp|0|3|00.00%|[47, 48, 50]|
|:large_blue_circle:|src/runtime/file_result_writer.cpp|0|1|00.00%|[108]|
|:large_blue_circle:|src/formats/parquet/file_writer.cpp|8|20|40.00%|[110, 111, 112, 119, 123, 127, 131, 135, 139, 142, 143, 149]|

**Review by dirtysalt — APPROVED** [review]

**Review by Youngwb — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.2

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Pull request merged**
