### PR TITLE
fix #4981: std decimal (backport #5143)

### LINKED ISSUE #4981: std(decimal) executed error
### Steps to reproduce the behavior (Required)
1. 
```
CREATE TABLE `duplicate_table_with_null` ( `k1`  date, `k2`  datetime, `k3`  char(20), `k4`  varchar(20), `k5`  boolean, `k6`  tinyint, `k7`  smallint, `k8`  int, `k9`  bigint, `k10` largeint, `k11` float, `k12` double, `k13` decimal(27,9) ) ENGINE=OLAP DUPLICATE KEY(`k1`, `k2`, `k3`, `k4`, `k5`) COMMENT "OLAP" DISTRIBUTED BY HASH(`k1`, `k2`, `k3`) BUCKETS 3 PROPERTIES ( "replication_num" = "1", "storage_format" = "v2" );
```
2. 
```
curl --location-trusted -u root: -T /home/disk4/lvchenyang/code/StarRocksTest/lib/../common/data/basic_types_data -XPUT -H label:stream_load_f8b815ec_b9ae_11ec_a1d3_00163e0e550b -H column_separator:	 http://172.26.92.152:8434/api/test_aggregation_f8b648fc_b9ae_11ec_a1d3_00163e0e550b/duplicate_table_with_null/_stream_load
```
3. 
```
select std(k13) from duplicate_table_with_null;
```
```
select std(cast(k13 as decimal32)) from duplicate_table_with_null;
```
```
select std(cast(k13 as decimal64)) from duplicate_table_with_null;
```
```
select std(cast(k13 as decimal128)) from duplicate_table_with_null;
```
### Expected behavior (Required)
return correct standard deviation
### Real behavior (Required)
```
ERROR 1064 (HY000): Invalid agg function plan: std
```
### StarRocks version (Required)
```
+------------------------+
| current_version()      |
+------------------------+
| QA_TEST_MASTER 04d8a0f |
+------------------------+
```

### PR DESCRIPTION
**Pull request by murphyatwork**
This is an automatic backport of pull request https://github.com/StarRocks/starrocks/pull/5143 done by

### CODE REVIEW

**Comment by mofeiatwork** [comment]
run starrocks_fe_unittest

**Comment by kangkaisen** [comment]
run  starrocks_be_unittest

**Comment by mofeiatwork** [comment]
@Mergify rebase

**Comment by mofeiatwork** [comment]
@mergify rebase

**Comment by mofeiatwork** [comment]
@Mergifyio rebase

**Comment by mofeiatwork** [comment]
run starrocks_be_unittest

**Review by kangkaisen — APPROVED** [review]

**Pull request merged**
