### PR TITLE
[Enhancement] save memmove in compressed input stream

### PR DESCRIPTION
**Pull request by dirtysalt**
Why I'm doing:

What I'm doing:

Fixes #issue

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.2
  - [x] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Comment by imay** [comment]
@dirtysalt 
Do you have performance benchmark compared to the original implementation?

**Comment by dirtysalt** [comment]
> @dirtysalt Do you have performance benchmark compared to the original implementation?

Not yet. This bad case is from a customer, and flame graph shows a large portion of CPU is on `memmove`

**Comment by Smith-Cruise** [comment]
> @dirtysalt Do you have performance benchmark compared to the original implementation?

lzo

Here is flame graph

**Review by Smith-Cruise — APPROVED** [review]

**Comment by dirtysalt** [comment]
A interesting finding is that, actually this PR will save FS IO counter.

My explanation is:

before this pr
- application will not read all bytes from compressed buffer.
- if compressed buffer is 8M, and application read 2M, after memmove, there will be 6M left
- which means we will issue 6M read requst to FS InputStream

but after this pr:
- application will consume whole compressed buffer.
- and compressed buffer will be always empty when we read from FS
- that means  we will always issue 8M read request to FS.


----


Take `select count(*) from tpch_1g_csv_bzip2.lineitem` for example, Since this is csv file, there is no way to do read optimization(have to scan whoel file anyway).

Before this pr, the profile shows: FSIOCounter = 104

TotalBytesRead 142 456M (142455592)

And with this pr, the profile shows: FSIOCounter = 26

ExprfilterTine ens

**Review by stephen-shelby — APPROVED** [review]

**Review by Youngwb — APPROVED** [review]

**Pull request merged**
