### PR TITLE
[Enhancement] Remove redundant ES exception handler.

### PR DESCRIPTION
**Pull request by Smith-Cruise**
## What type of PR is this：
- [ ] bugfix
- [ ] feature
- [x] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

Previous PR: https://github.com/StarRocks/starrocks/pull/10695

Fix to pass the daily test.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 0 / 3 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/EsTable.java|0|2|00.00%|[492, 493]|
|:large_blue_circle:|com/starrocks/external/elasticsearch/EsRepository.java|0|1|00.00%|[79]|

**Review by imay — APPROVED** [review]

**Review by DorianZheng — APPROVED** [review]
LGTM

**Comment by DorianZheng** [comment]
run admit_test

**Review by caneGuy — APPROVED** [review]
LGTM

**Pull request merged**
