### PR TITLE
[Feature] Add function utc_time()

### LINKED ISSUE #18569: 能否实现mysql的utc_time()函数，方便一些三方客户端连接和老代码兼容
hi ，开发者们！
  能否在starocks中实现mysql的 utc_time() 函数（尽管目前starrocks已经有 utc_timestamp())， 但有一些三方的mysql客户端和老代码需要这个函数，以便兼容。
谢谢开发者们

### PR DESCRIPTION
**Pull request by yangrong688**
## What type of PR is this：
- [ ] BugFix
- [x] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes [#18569](https://github.com/StarRocks/starrocks/issues/18569)

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by imay — DISMISSED** [review]

**Comment by imay** [comment]
@yangrong688 thanks for your contribution, please add the document of this function.

**Review by kangkaisen — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by yangrong688** [comment]
> @yangrong688 thanks for your contribution, please add the document of this function.

OK, I will add document about this function later.

**Comment by yangrong688** [comment]
run starrocks_fe_unittest

**Comment by yangrong688** [comment]
run starrocks_fe_unittest

**Comment by yangrong688** [comment]
run starrocks_fe_unittest

**Comment by yangrong688** [comment]
Hi @imay, it seems test enviroment is not stable, there is no change of fe codes in this pr, but starrocks_fe_unittest failed to run multiple times.

errors copied from jenkins console output:
10:29:21 [ERROR] thrift failed error: [FAILURE:generation:1] Error: /root/starrocks/fe/fe-core/target/generated-sources/thrift//: No such file or directory

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by kangkaisen** [comment]
https://github.com/Mergifyio backport branch-3.0

**Pull request merged**
