### PR TITLE
[BugFix] all partitions have no load data when jsonroot is set

### LINKED ISSUE #11054: `all partitions have no load data` when jsonroot is set
### Steps to reproduce the behavior (Required)
1. create table
```SQL
CREATE TABLE `tbl_3_col` ( `key1` int NULL COMMENT "", `key2` int NULL COMMENT "",key3 int ) 
ENGINE = OLAP DUPLICATE KEY(`key1`) 
COMMENT "OLAP" DISTRIBUTED BY HASH(`key1`) BUCKETS 10 
PROPERTIES ( "replication_num" = "1", "in_memory" = "false", "storage_format" = "DEFAULT" );
```
1. load data
```bash
 curl --location-trusted -u root:  'http://127.0.0.1:8082/api/db0/tbl_3_col/_stream_load' \
    -X PUT -H 'json_root: $.data' \
    -H 'strip_outer_array: false' \
    -H 'format: json' -d '{"data":{"key1": 1}}'
```

### Expected behavior (Required)
Load data correctly.
### Real behavior (Required)
`all partitions have no load data` is returned.
```
{
    "TxnId": 26044,
    "Label": "d50cfff6-9bd8-4eb7-b7e0-08d2aea895a5",
    "Status": "Fail",
    "Message": "all partitions have no load data",
    "NumberTotalRows": 0,
    "NumberLoadedRows": 0,
    "NumberFilteredRows": 0,
    "NumberUnselectedRows": 0,
    "LoadBytes": 20,
    "LoadTimeMs": 9,
    "BeginTxnTimeMs": 0,
    "StreamLoadPlanTimeMs": 1,
    "ReadDataTimeMs": 0,
    "WriteDataTimeMs": 7,
    "CommitAndPublishTimeMs": 0
}%
```
### StarRocks version (Required)
2.2.5, 2.3.2

### PR DESCRIPTION
**Pull request by rickif**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes https://github.com/StarRocks/starrocks/issues/11054

## Problem Summary(Required) ：

To get better performance in scenes where the column is sparse, we introduced https://github.com/starrocks/starrocks/issues/5357. 
When the jsonroot is set, and the jsonpath is not set, the `_slot_desc_dict` is not initiated, leading the error `all partitions have no load data` being returned.
This PR fixes the problem and simplifies the JsonScanner by removing the `_construct_row_in_slot_order`. In this way, the row would only be constructed in JSON object order, and the JSON object would only be iterated once.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by rickif** [comment]
run all

**Review by chaoyli — APPROVED** [review]

**Review by chaoyli — APPROVED** [review]

**Comment by rickif** [comment]
run all

**Review by meegoo — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by rickif** [comment]
run starrocks_admit_test

**Comment by rickif** [comment]
run starrocks_admit_test

**Pull request merged**
