### PR TITLE
[Cherry-pick] [Enhancement] Enables SR cluster can support IP and FQDN conversion (…

### LINKED ISSUE #10995: Enables SR cluster can rollback from using FQDN to IP

### PR DESCRIPTION
**Pull request by waittttting**
## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #10995 

## Problem Summary(Required) ：

Previously SR cluster can‘t change FQDN to IP, this PR Enables SR cluster can support IP and FQDN conversion
## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Review by wanpengfei-git — APPROVED** [review]

**Comment by waittttting** [comment]
run starrocks_tscancode

**Comment by waittttting** [comment]
run starrocks_tscancode

**Comment by waittttting** [comment]
run starrocks_tscancode

**Comment by waittttting** [comment]
run starrocks_fe_unittest

**Comment by waittttting** [comment]
run starrocks_tscancode

**Comment by waittttting** [comment]
run starrocks_tscancode

**Comment by waittttting** [comment]
run starrocks_tscancode

**Review by gengjun-git — APPROVED** [review]

**Pull request merged**
