### PR TITLE
[BugFix] record db name of view when query dump

### PR DESCRIPTION
**Pull request by Youngwb**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

Query Dump lose db name of view, it will result in unknown database error

### CODE REVIEW

**Comment by Youngwb** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 6 / 9 (66.67%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/dump/QueryDumpSerializer.java|0|3|00.00%|[60, 61, 62]|
|:large_blue_circle:|com/starrocks/sql/analyzer/QueryAnalyzer.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/dump/QueryDumpInfo.java|2|2|100.00%|[]|

**Review by Seaven — APPROVED** [review]

**Review by kangkaisen — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by Youngwb** [comment]
@Mergifyio backport branch-2.3

**Pull request merged**
