### PR TITLE
[BugFix] fix type convert of UNKNOWN_TYPE

### LINKED ISSUE #9941: [sqlancer] query error which contains UNKNOWN_TYPE
### Steps to reproduce the behavior (Required)
```
DROP DATABASE IF EXISTS h8;
CREATE DATABASE h8;
USE h8;
admin set frontend config ("enable_decimal_v3" = "true");
CREATE TABLE t0 (c_0_0 BOOLEAN NOT NULL,c_0_1 VARCHAR(11) NOT NULL,c_0_2 BOOLEAN NOT NULL,c_0_3 DATETIME NOT NULL,c_0_4 BOOLEAN NOT NULL,c_0_5 BOOLEAN NOT NULL,c_0_6 DOUBLE NOT NULL,c_0_7 DOUBLE NOT NULL,c_0_8 TINYINT NOT NULL, INDEX index1_c_0_1(`c_0_1`) USING BITMAP) PRIMARY KEY (c_0_0,c_0_1,c_0_2,c_0_3,c_0_4,c_0_5) PARTITION BY RANGE(c_0_3) (START ("2010-01-01") END ("2022-12-31") EVERY (INTERVAL 175 day)) DISTRIBUTED BY HASH (c_0_1,c_0_0,c_0_3,c_0_2,c_0_5) BUCKETS 3 properties("replication_num"="3") ;
CREATE TABLE t1 (c_1_0 DATE NOT NULL ,c_1_1 DECIMAL(5, 3)  NOT NULL ,c_1_2 BOOLEAN NULL ,c_1_3 BOOLEAN NOT NULL ,c_1_4 DECIMAL(19, 7)  NULL ,c_1_5 DECIMAL(28, 2)  NULL ,c_1_6 BOOLEAN NOT NULL ,c_1_7 VARCHAR(41) NOT NULL ,c_1_8 BOOLEAN NULL ,c_1_9 ARRAY<INT> NULL ,c_1_10 ARRAY<STRING> NULL ,c_1_11 DECIMAL(18, 7)  NULL ,c_1_12 JSON NOT NULL ,c_1_13 DECIMAL(30, 8)  NOT NULL ,c_1_14 ARRAY<INT> NOT NULL , INDEX index1_c_1_3(`c_1_3`) USING BITMAP) DUPLICATE KEY (c_1_0,c_1_1,c_1_2,c_1_3,c_1_4,c_1_5,c_1_6) PARTITION BY RANGE(c_1_0) (START ("2010-01-01") END ("2022-12-31") EVERY (INTERVAL 197 day)) DISTRIBUTED BY HASH (c_1_6,c_1_1,c_1_0,c_1_3,c_1_5,c_1_2) BUCKETS 3 properties("replication_num"="3") ;
CREATE TABLE t2 (c_2_0 DATE NULL ,c_2_1 DECIMAL(30, 0)  NOT NULL ,c_2_2 LARGEINT NULL ,c_2_3 DOUBLE NOT NULL ,c_2_4 BIGINT NOT NULL ,c_2_5 DATE NULL ,c_2_6 ARRAY<INT> NOT NULL ,c_2_7 BOOLEAN NOT NULL ,c_2_8 ARRAY<INT> NULL ,c_2_9 FLOAT NOT NULL ,c_2_10 CHAR(1) NOT NULL ,c_2_11 LARGEINT NULL ) UNIQUE KEY (c_2_0) PARTITION BY RANGE(c_2_0) (START ("2010-01-01") END ("2022-12-31") EVERY (INTERVAL 148 day)) DISTRIBUTED BY HASH (c_2_0) BUCKETS 3 properties("replication_num"="3") ;
CREATE TABLE IF NOT EXISTS t3 (c_3_0 TINYINT NOT NULL,c_3_1 DECIMAL(33, 11)  NOT NULL) PRIMARY KEY (c_3_0) DISTRIBUTED BY HASH (c_3_0) BUCKETS 3 properties("replication_num"="3") ;
CREATE TABLE t4 (c_4_0 DATETIME NULL ,c_4_1 INT NOT NULL ,c_4_2 TINYINT NOT NULL ,c_4_3 DECIMAL(6, 1)  NULL ,c_4_4 BOOLEAN NOT NULL ,c_4_5 DECIMAL(3, 2)  NULL ,c_4_6 BOOLEAN NOT NULL ,c_4_7 BOOLEAN NULL ,c_4_8 SMALLINT NOT NULL ,c_4_9 JSON NOT NULL , INDEX index1_c_4_2(`c_4_2`) USING BITMAP) DUPLICATE KEY (c_4_0,c_4_1,c_4_2,c_4_3,c_4_4,c_4_5,c_4_6,c_4_7) PARTITION BY RANGE(c_4_0) (START ("2010-01-01") END ("2022-12-31") EVERY (INTERVAL 153 day)) DISTRIBUTED BY HASH (c_4_1,c_4_3,c_4_4,c_4_5) BUCKETS 3 properties("replication_num"="3") ;
INSERT INTO t2 VALUES ('2010-01-02', 916569191039893783798035240550, 1429711865, 1.429711865E9, 1429711865, '2010-01-09', [274525027, -334771662, 1429711865, 1429711865, 274525027, -666870706, -666870706, 1635983865, -1092651786, 539534188, -1552374182, -666870706], false, [936525298, 274525027, -1849799313, 1809891168, 1635983865, -1552374182, 1429711865, 1429711865], 0.6395190763538505, '', 1286047193), ('2010-01-24', 243082998406596792364753323312, -1849799313, 0.32755333126242625, -144301359, '2010-01-16', [-836643895, 274525027, 908509388, -1079967691, 1295367329, 117936078, -1699841033, 608383045, -2039111546, 1699275804], false, [-2039111546, 305957400, -144301359, 357498033, -1284366420, 357498033, 305957400, -154144004, 2048944556, 1978489705, -1814554816, 1906607758, -391349106], 0.6395190763538505, '', -51751794);
INSERT INTO t3 VALUES (7, 65738044729.73004207785);
CREATE MATERIALIZED VIEW v0 AS SELECT t0_110.c_0_8, MAX(t0_110.c_0_0) , MAX(t0_110.c_0_1) , MIN(t0_110.c_0_2) , MAX(t0_110.c_0_3) , MAX(t0_110.c_0_4) , MIN(t0_110.c_0_5) , MIN(t0_110.c_0_6) , SUM(t0_110.c_0_7)  FROM t0 AS t0_110 GROUP BY t0_110.c_0_8 ORDER BY t0_110.c_0_8 DESC;
CREATE VIEW v0 AS SELECT t1_116.c_1_0, t1_116.c_1_1, t1_116.c_1_2, t1_116.c_1_3, t1_116.c_1_4, t1_116.c_1_5, t1_116.c_1_6, t1_116.c_1_7, t1_116.c_1_8, t1_116.c_1_9, t1_116.c_1_10, t1_116.c_1_11, t1_116.c_1_12, t1_116.c_1_13, t1_116.c_1_14, t4_119.c_4_0, t4_119.c_4_1, t4_119.c_4_2, t4_119.c_4_3, t4_119.c_4_4, t4_119.c_4_5, t4_119.c_4_6, t4_119.c_4_7, t4_119.c_4_8, t4_119.c_4_9, t2_117.c_2_0, t2_117.c_2_1, t2_117.c_2_2, t2_117.c_2_3, t2_117.c_2_4, t2_117.c_2_5, t2_117.c_2_6, t2_117.c_2_7, t2_117.c_2_8, t2_117.c_2_9, t2_117.c_2_10, t2_117.c_2_11, t0_115.c_0_0, t0_115.c_0_1, t0_115.c_0_2, t0_115.c_0_3, t0_115.c_0_4, t0_115.c_0_5, t0_115.c_0_6, t0_115.c_0_7, t0_115.c_0_8 FROM t1 AS t1_116, t4 AS t4_119, t2 AS t2_117, t0 AS t0_115 WHERE (NOT (false)) ORDER BY t2_117.c_2_0, t0_115.c_0_7, t0_115.c_0_4, t0_115.c_0_3, t1_116.c_1_6, t1_116.c_1_7, t1_116.c_1_7, t1_116.c_1_11, t2_117.c_2_5, t0_115.c_0_7, t1_116.c_1_1, t4_119.c_4_8, t0_115.c_0_8, t2_117.c_2_7, t4_119.c_4_2, t4_119.c_4_5, t0_115.c_0_2, t4_119.c_4_6, t2_117.c_2_3, t0_115.c_0_4, t1_116.c_1_4, t4_119.c_4_5, t4_119.c_4_3, t1_116.c_1_2, t2_117.c_2_3, t2_117.c_2_11, t1_116.c_1_7, t4_119.c_4_1, t2_117.c_2_9, t2_117.c_2_11, t4_119.c_4_8, t1_116.c_1_1, t2_117.c_2_3, t1_116.c_1_4, t1_116.c_1_5, t4_119.c_4_1, t4_119.c_4_3, t0_115.c_0_5, t0_115.c_0_0, t1_116.c_1_3, t2_117.c_2_3, t2_117.c_2_4, t2_117.c_2_7;
INSERT INTO t0 VALUES (true, 'fu', true, '2010-01-27 08:00:14', false, true, 0.6886503838020472, 0.36913198202707576, 0), (false, 'Z', true, '2010-01-12 08:00:14', true, true, 0.9691831528997502, 0.27037104168409576, 6), (false, 'Nr', false, '2010-01-12 08:00:14', true, true, 0.468601492767562, 0.9907123920206582, 1);
INSERT INTO t4 VALUES ('2010-01-08 08:00:14', 7, 1, 1999.4, false, 0.03, true, false, 5, parse_json('{"sA9fFgvy": {"P": null, "3": null, "F": null, "w": 0.8421112246237386, "a0L": "eW1Bu"}, "NPX6cM": 0.6395190763538505, "D8SO1bp": 0.5223169256037717, "zXLRu4": 0.04292502327415293, "qBALUwcw9": "YY", "kjiwFig": false, "wEhU": false, "Lfo": 941110048, "C8": null, "NU17T6XVA": 936525298, "na1BKsWbq": false, "psnYtfr": 0.9794619325701833, "9zcrXHIn": 0.7141555898565601}')), ('2010-01-02 08:00:14', 31, 0, 2095.9, true, 0.00, false, true, 4, parse_json('{"7G": 0.5462884349827478, "P": 0.6704270286403228, "0": "9q5", "4g": -154144004, "g": 0.5462884349827478, "V2": "dz", "BP": {}}'));
INSERT INTO t2 VALUES ('2010-01-17', 460810460688148699436188504563, NULL, 0.2717078172815973, -1922768489, NULL, [-1071785850, 370448157, -154144004, 218432950, 608383045, -1015904971, -1909369386], false, [-514636675, -2039111546, -1725028680, -1922768489, 908509388, -1556140661, -634129052, -1071785850, 1388747731, -51751794, 982364355, 936525298, -1234345494, 370448157, -1817852627], 0.9691831528997502, '', -1817852627);
INSERT INTO t3 VALUES (0, 90825458493.03255320243), (0, 89967167354.69495797456);
INSERT INTO t0 VALUES (false, 'EZ', false, '2010-01-18 08:00:14', false, true, 0.8633650601004679, 0.43141838816716016, 7), (true, 'i', false, '2010-01-13 08:00:14', true, false, 0.9907123920206582, 0.6886503838020472, 3);
INSERT INTO t1 VALUES ('2010-01-16', 0.096, false, false, 8944.1376343, 730457286744424783009321.80, true, '', false, [-2039111546, -92411273, 677534095, 218432950], ["s", "l", "2GuHt49E", "1W3w", "iy", "ufMgAVGVM", "l"], 1734.0725068, parse_json('{"Blxcg": 533932150, "dS6": -1.092651786E9, "ZBOds8EC": -513496481, "l": 0.36913198202707576, "2viIlmX": true, "6dGbnk": null, "5TXg": false, "Jb": null, "Sl": false, "sSgS": -1202539885, "9": null, "zgG": 0.6886503838020472, "QE1": null}'), 54323320610473.05462886, [538273589, 1922608786, 1849832010, -715004741, -383676110, -1725028680, -2003188345, -1188871156]), ('2010-01-24', 0.059, true, false, 20841.1472309, 948644166687759193834494.90, false, '4', false, [-185592942, -1614424571, 533932150, -1909436124], ["yT", "L", "ql", "iuD", ""], 1380.3154359, parse_json('{"TEwPJ": {"B": -40738463, "fK": null}, "AEkpn": null, "9J": null, "iU6qZ52": null, "Kpp": [[false], -290369617, 0.9584774503371175, -2.90369617E8, null, null, 1699275804], "Uc59G1X": false, "bsAc": {"1MZuxQkUf": true, "z": -634129052, "Va": {"g8Rp": null, "hQrKQvb": null, "C": "RwwW6", "jEP4VW": false, "di": 0.07098397320999539, "g": ""}}, "ljeC": "ym"}'), 93771385885364.80774631, [1635983865, -121226739, 288862646, -1814554816, 1877030284, -1, 4823060, 1700390032]);
INSERT INTO t3 VALUES (2, 15565874742.25938766211);
INSERT INTO t3 VALUES (1, 94163143005.09043408775), (2, 90600307458.47029721173), (1, 62121492370.65351947557);
INSERT INTO t2 VALUES ('2010-01-07', 327512817948659710600878280928, 936525298, 0.30001790583936583, 1910673342, '2010-01-16', [-1734893106, 1837306919, -2105135654, 1279025636, 166954436, -1170945115, -1909436124], true, [-2105135654, 55460546, -92411273, -384873011], 0.7767035560879549, '', -463947525);
SELECT t3_129.c_3_0, LAG(t4_130.c_4_9, 3, 1) OVER ( ORDER BY t1_127.c_1_6, v0_131.c_1_14, t4_130.c_4_9, v0_131.c_0_6, t4_130.c_4_7, t1_127.c_1_2, v0_131.c_1_8, v0_131.c_4_0, t3_129.c_3_0, v0_131.c_4_7, t4_130.c_4_5, v0_131.c_4_9, v0_131.c_1_5, t2_128.c_2_9, v0_131.c_0_3, v0_131.c_1_7, v0_131.c_4_4, v0_131.c_1_1, t2_128.c_2_11, t1_127.c_1_13, t4_130.c_4_6, v0_131.c_1_3, v0_131.c_2_1, t4_130.c_4_8, v0_131.c_4_3, t2_128.c_2_5, v0_131.c_2_2, t4_130.c_4_4, v0_131.c_1_9, v0_131.c_4_5, v0_131.c_1_11, v0_131.c_0_8, t1_127.c_1_14, t1_127.c_1_8, v0_131.c_0_7, v0_131.c_2_4, t4_130.c_4_1, v0_131.c_2_10, t3_129.c_3_1, t1_127.c_1_11, v0_131.c_1_4, t4_130.c_4_2) , RANK() OVER ( ORDER BY v0_131.c_2_2, v0_131.c_1_7, v0_131.c_1_1, v0_131.c_2_9, v0_131.c_0_4, t1_127.c_1_14, t2_128.c_2_0, v0_131.c_4_9, t1_127.c_1_4, v0_131.c_4_2, v0_131.c_2_6, t1_127.c_1_12, t2_128.c_2_6, v0_131.c_2_1, t4_130.c_4_6, t4_130.c_4_2, t3_129.c_3_1, v0_131.c_1_6, v0_131.c_2_3, v0_131.c_0_1, t2_128.c_2_4, v0_131.c_4_7, v0_131.c_0_6, v0_131.c_1_12, v0_131.c_1_5, t1_127.c_1_0, v0_131.c_1_11, v0_131.c_1_14, t1_127.c_1_13, t4_130.c_4_7, t1_127.c_1_3, v0_131.c_4_0, t1_127.c_1_11, t4_130.c_4_5, v0_131.c_0_2, t1_127.c_1_2, t4_130.c_4_9, v0_131.c_1_0, v0_131.c_1_4, v0_131.c_0_0, t2_128.c_2_8, v0_131.c_4_4, v0_131.c_4_1, t2_128.c_2_5, v0_131.c_2_8, v0_131.c_1_9, t4_130.c_4_4, t1_127.c_1_1, v0_131.c_1_10, v0_131.c_1_3, v0_131.c_2_11, t4_130.c_4_3, v0_131.c_2_5, t2_128.c_2_7, v0_131.c_2_0, t1_127.c_1_10, t1_127.c_1_6, t4_130.c_4_8, v0_131.c_0_8, t1_127.c_1_7, v0_131.c_1_13, t2_128.c_2_9, v0_131.c_2_4, t1_127.c_1_5, v0_131.c_1_8, t2_128.c_2_11, v0_131.c_0_5, t1_127.c_1_9, v0_131.c_0_7, v0_131.c_4_6, v0_131.c_2_10, t1_127.c_1_8, v0_131.c_0_3, t2_128.c_2_1, v0_131.c_2_7, t4_130.c_4_1, v0_131.c_1_2, t3_129.c_3_0)  FROM t3 AS t3_129, v0 AS v0_131, t4 AS t4_130, t2 AS t2_128, t1 AS t1_127 GROUP BY v0_131.c_4_7, t4_130.c_4_6 ORDER BY t4_130.c_4_4 ASC;
```
```
Please check this error:
mysql> SELECT t3_129.c_3_0, LAG(t4_130.c_4_9, 3, 1) OVER ( ORDER BY t1_127.c_1_6, v0_131.c_1_14, t4_130.c_4_9, v0_131.c_0_6, t4_130.c_4_7, t1_127.c_1_2, v0_131.c_1_8, v0_131.c_4_0, t3_129.c_3_0, v0_131.c_4_7, t4_130.c_4_5, v0_131.c_4_9, v0_131.c_1_5, t2_128.c_2_9, v0_131.c_0_3, v0_131.c_1_7, v0_131.c_4_4, v0_131.c_1_1, t2_128.c_2_11, t1_127.c_1_13, t4_130.c_4_6, v0_131.c_1_3, v0_131.c_2_1, t4_130.c_4_8, v0_131.c_4_3, t2_128.c_2_5, v0_131.c_2_2, t4_130.c_4_4, v0_131.c_1_9, v0_131.c_4_5, v0_131.c_1_11, v0_131.c_0_8, t1_127.c_1_14, t1_127.c_1_8, v0_131.c_0_7, v0_131.c_2_4, t4_130.c_4_1, v0_131.c_2_10, t3_129.c_3_1, t1_127.c_1_11, v0_131.c_1_4, t4_130.c_4_2) , RANK() OVER ( ORDER BY v0_131.c_2_2, v0_131.c_1_7, v0_131.c_1_1, v0_131.c_2_9, v0_131.c_0_4, t1_127.c_1_14, t2_128.c_2_0, v0_131.c_4_9, t1_127.c_1_4, v0_131.c_4_2, v0_131.c_2_6, t1_127.c_1_12, t2_128.c_2_6, v0_131.c_2_1, t4_130.c_4_6, t4_130.c_4_2, t3_129.c_3_1, v0_131.c_1_6, v0_131.c_2_3, v0_131.c_0_1, t2_128.c_2_4, v0_131.c_4_7, v0_131.c_0_6, v0_131.c_1_12, v0_131.c_1_5, t1_127.c_1_0, v0_131.c_1_11, v0_131.c_1_14, t1_127.c_1_13, t4_130.c_4_7, t1_127.c_1_3, v0_131.c_4_0, t1_127.c_1_11, t4_130.c_4_5, v0_131.c_0_2, t1_127.c_1_2, t4_130.c_4_9, v0_131.c_1_0, v0_131.c_1_4, v0_131.c_0_0, t2_128.c_2_8, v0_131.c_4_4, v0_131.c_4_1, t2_128.c_2_5, v0_131.c_2_8, v0_131.c_1_9, t4_130.c_4_4, t1_127.c_1_1, v0_131.c_1_10, v0_131.c_1_3, v0_131.c_2_11, t4_130.c_4_3, v0_131.c_2_5, t2_128.c_2_7, v0_131.c_2_0, t1_127.c_1_10, t1_127.c_1_6, t4_130.c_4_8, v0_131.c_0_8, t1_127.c_1_7, v0_131.c_1_13, t2_128.c_2_9, v0_131.c_2_4, t1_127.c_1_5, v0_131.c_1_8, t2_128.c_2_11, v0_131.c_0_5, t1_127.c_1_9, v0_131.c_0_7, v0_131.c_4_6, v0_131.c_2_10, t1_127.c_1_8, v0_131.c_0_3, t2_128.c_2_1, v0_131.c_2_7, t4_130.c_4_1, v0_131.c_1_2, t3_129.c_3_0)  FROM t3 AS t3_129, v0 AS v0_131, t4 AS t4_130, t2 AS t2_128, t1 AS t1_127 GROUP BY v0_131.c_4_7, t4_130.c_4_6 ORDER BY t4_130.c_4_4 ASC;
ERROR 1064 (HY000): No assignment from JSON to UNKNOWN_TYPE

```

```
fe.log:
java.lang.NullPointerException: No assignment from JSON to UNKNOWN_TYPE
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:899) ~[spark-dpp-1.0.0.jar:?]
        at com.starrocks.catalog.ScalarType.getAssignmentCompatibleType(ScalarType.java:426) ~[starrocks-fe.jar:?]
        at com.starrocks.catalog.ScalarType.isImplicitlyCastable(ScalarType.java:435) ~[starrocks-fe.jar:?]
        at com.starrocks.catalog.Type.isImplicitlyCastable(Type.java:899) ~[starrocks-fe.jar:?]
        at com.starrocks.catalog.Function.isSubtype(Function.java:345) ~[starrocks-fe.jar:?]
        at com.starrocks.catalog.Function.compare(Function.java:307) ~[starrocks-fe.jar:?]
        at com.starrocks.catalog.FunctionSet.getFunction(FunctionSet.java:590) ~[starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.getFunction(GlobalStateMgr.java:2858) ~[starrocks-fe.jar:?]
        at com.starrocks.analysis.Expr.getBuiltinFunction(Expr.java:1123) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.ExpressionAnalyzer$Visitor.visitFunctionCall(ExpressionAnalyzer.java:562) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.ExpressionAnalyzer$Visitor.visitFunctionCall(ExpressionAnalyzer.java:99) ~[starrocks-fe.jar:?]
        at com.starrocks.analysis.FunctionCallExpr.accept(FunctionCallExpr.java:468) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.ast.AstVisitor.visit(AstVisitor.java:131) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.ExpressionAnalyzer$Visitor.visitAnalyticExpr(ExpressionAnalyzer.java:798) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.ExpressionAnalyzer$Visitor.visitAnalyticExpr(ExpressionAnalyzer.java:99) ~[starrocks-fe.jar:?]
        at com.starrocks.analysis.AnalyticExpr.accept(AnalyticExpr.java:434) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.ast.AstVisitor.visit(AstVisitor.java:131) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.ExpressionAnalyzer.bottomUpAnalyze(ExpressionAnalyzer.java:96) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.ExpressionAnalyzer.analyze(ExpressionAnalyzer.java:83) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.ExpressionAnalyzer.analyzeExpression(ExpressionAnalyzer.java:876) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.SelectAnalyzer.analyzeExpression(SelectAnalyzer.java:622) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.SelectAnalyzer.analyzeSelect(SelectAnalyzer.java:230) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.SelectAnalyzer.analyze(SelectAnalyzer.java:62) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.visitSelect(QueryAnalyzer.java:169) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.visitSelect(QueryAnalyzer.java:82) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.ast.SelectRelation.accept(SelectRelation.java:206) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.process(QueryAnalyzer.java:87) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.visitQueryRelation(QueryAnalyzer.java:105) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.visitQueryStatement(QueryAnalyzer.java:99) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.visitQueryStatement(QueryAnalyzer.java:82) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.ast.QueryStatement.accept(QueryStatement.java:36) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.process(QueryAnalyzer.java:87) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.QueryAnalyzer.analyze(QueryAnalyzer.java:75) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.Analyzer$AnalyzerVisitor.visitQueryStatement(Analyzer.java:224) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.Analyzer$AnalyzerVisitor.visitQueryStatement(Analyzer.java:82) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.ast.QueryStatement.accept(QueryStatement.java:36) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.ast.AstVisitor.visit(AstVisitor.java:131) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.Analyzer$AnalyzerVisitor.analyze(Analyzer.java:84) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.Analyzer.analyze(Analyzer.java:79) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:43) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:348) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:316) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:429) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:667) ~[starrocks-fe.jar:?]
        at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:55) ~[starrocks-fe.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_272]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_272]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_272]
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - mysql> select current_version();
+----------------------+
| current_version()    |
+----------------------+
| MAIN-RELEASE e8ba97d |
+----------------------+

### PR DESCRIPTION
**Pull request by murphyatwork**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #9941

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Review by kangkaisen — DISMISSED** [review]

**Comment by kangkaisen** [comment]
Need test cases.

**Review by Seaven — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by mofeiatwork** [comment]
@run all

**Comment by mofeiatwork** [comment]
run starrocks_admit_test

**Comment by mofeiatwork** [comment]
@Mergifyio rebase

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by mofeiatwork** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 3 / 3 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/ScalarType.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/Type.java|1|1|100.00%|[]|

**Review by kangkaisen — APPROVED** [review]

**Review by Seaven — APPROVED** [review]

**Pull request merged**
