### PR TITLE
Update some internal processes for StarOS table

### PR DESCRIPTION
**Pull request by wyb**
## What type of PR is this：
- [ ] bug
- [x] feature
- [ ] enhancement
- [ ] others

## Problem Summary(Required) ：

1. Disable StarOSTablet balance and repair.
2. Disable StarOSTablet report process.
3. Disable StarOSTablet consistency check.
4. Skip resetting replica state when copying OlapTable with StarOSTablet.
5. Tablet statistic for StarOSTablet.

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 6 / 49 (12.24%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/consistency/ConsistencyChecker.java|0|2|00.00%|
|:large_blue_circle:|com/starrocks/catalog/TabletStatMgr.java|0|28|00.00%|
|:large_blue_circle:|com/starrocks/clone/TabletScheduler.java|0|2|00.00%|
|:large_blue_circle:|com/starrocks/catalog/TabletInvertedIndex.java|0|2|00.00%|
|:large_blue_circle:|com/starrocks/master/ReportHandler.java|0|4|00.00%|
|:large_blue_circle:|com/starrocks/clone/TabletChecker.java|1|2|50.00%|
|:large_blue_circle:|com/starrocks/clone/DiskAndTabletLoadReBalancer.java|3|6|50.00%|
|:large_blue_circle:|com/starrocks/catalog/OlapTable.java|2|3|66.67%|

**Review by gengjun-git — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 32 / 49 (65.31%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/consistency/ConsistencyChecker.java|0|2|00.00%|
|:large_blue_circle:|com/starrocks/clone/TabletScheduler.java|0|2|00.00%|
|:large_blue_circle:|com/starrocks/catalog/TabletInvertedIndex.java|0|2|00.00%|
|:large_blue_circle:|com/starrocks/master/ReportHandler.java|0|4|00.00%|
|:large_blue_circle:|com/starrocks/clone/TabletChecker.java|1|2|50.00%|
|:large_blue_circle:|com/starrocks/clone/DiskAndTabletLoadReBalancer.java|3|6|50.00%|
|:large_blue_circle:|com/starrocks/catalog/OlapTable.java|2|3|66.67%|
|:large_blue_circle:|com/starrocks/catalog/TabletStatMgr.java|26|28|92.86%|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 32 / 49 (65.31%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/consistency/ConsistencyChecker.java|0|2|00.00%|
|:large_blue_circle:|com/starrocks/clone/TabletScheduler.java|0|2|00.00%|
|:large_blue_circle:|com/starrocks/catalog/TabletInvertedIndex.java|0|2|00.00%|
|:large_blue_circle:|com/starrocks/master/ReportHandler.java|0|4|00.00%|
|:large_blue_circle:|com/starrocks/clone/TabletChecker.java|1|2|50.00%|
|:large_blue_circle:|com/starrocks/clone/DiskAndTabletLoadReBalancer.java|3|6|50.00%|
|:large_blue_circle:|com/starrocks/catalog/OlapTable.java|2|3|66.67%|
|:large_blue_circle:|com/starrocks/catalog/TabletStatMgr.java|26|28|92.86%|

**Review by wuleistarrocks — DISMISSED** [review]

**Comment by wyb** [comment]
run starrocks_fe_unittest

**Review by gengjun-git — APPROVED** [review]

**Review by wuleistarrocks — APPROVED** [review]

**Review by sduzh — APPROVED** [review]

**Pull request merged**
