### PR TITLE
[Refactor] refactor DdlExecutor into a visitor

### PR DESCRIPTION
**Pull request by murphyatwork**
## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [x] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by mofeiatwork** [comment]
run all

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 94 / 359 (26.18%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/ast/AstVisitor.java|0|15|00.00%|[182, 186, 232, 386, 438, 442, 454, 458, 491, 630, 634, 638, 642, 646, 664]|
|:large_blue_circle:|com/starrocks/qe/DDLStmtExecutor.java|85|333|25.53%|[94, 106, 108, 127, 137, 138, 139, 141, 155, 156, 157, 159, 168, 169, 170, 171, 172, 174, 175, 176, 181, 183, 184, 185, 186, 188, 189, 190, 203, 204, 205, 206, 219, 220, 221, 222, 252, 253, 254, 255, 256, 257, 258, 264, 265, 266, 267, 268, 269, 270, 283, 284, 285, 286, 291, 292, 293, 294, 299, 300, 301, 302, 304, 305, 309, 310, 311, 316, 317, 318, 319, 324, 325, 326, 327, 332, 333, 334, 335, 340, 341, 342, 343, 348, 349, 350, 351, 356, 357, 358, 359, 364, 365, 366, 368, 370, 371, 376, 377, 378, 379, 384, 385, 386, 387, 392, 393, 394, 395, 400, 401, 402, 403, 408, 409, 410, 411, 416, 417, 418, 419, 424, 425, 426, 427, 432, 433, 434, 435, 440, 441, 442, 443, 456, 457, 458, 459, 464, 465, 466, 467, 472, 473, 474, 475, 480, 481, 482, 483, 488, 489, 490, 491, 496, 497, 498, 499, 504, 505, 506, 507, 512, 513, 514, 515, 520, 521, 522, 523, 528, 529, 530, 531, 536, 537, 538, 551, 552, 553, 554, 559, 560, 561, 562, 575, 576, 577, 578, 583, 584, 585, 586, 591, 593, 594, 595, 596, 597, 598, 603, 605, 606, 607, 608, 609, 610, 615, 616, 617, 618, 631, 632, 633, 634, 639, 640, 641, 642, 647, 648, 649, 650, 655, 656, 657, 658, 663, 664, 665, 666, 667, 669, 672, 674, 675, 676, 677, 678, 679, 680, 685, 686, 687, 688, 733, 734, 735, 736]|
|:large_blue_circle:|com/starrocks/qe/StmtExecutor.java|1|2|50.00%|[1097]|
|:large_blue_circle:|com/starrocks/common/ErrorReport.java|5|6|83.33%|[84]|
|:large_blue_circle:|com/starrocks/sql/ast/CreateFunctionStmt.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/ShowFunctionsStmt.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/DropFunctionStmt.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 94 / 359 (26.18%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/ast/AstVisitor.java|0|15|00.00%|[183, 187, 233, 387, 439, 443, 455, 459, 492, 635, 639, 643, 647, 651, 669]|
|:large_blue_circle:|com/starrocks/qe/DDLStmtExecutor.java|85|333|25.53%|[94, 106, 108, 127, 137, 138, 139, 141, 155, 156, 157, 159, 168, 169, 170, 171, 172, 174, 175, 176, 181, 183, 184, 185, 186, 188, 189, 190, 203, 204, 205, 206, 219, 220, 221, 222, 252, 253, 254, 255, 256, 257, 258, 264, 265, 266, 267, 268, 269, 270, 283, 284, 285, 286, 291, 292, 293, 294, 299, 300, 301, 302, 304, 305, 309, 310, 311, 316, 317, 318, 319, 324, 325, 326, 327, 332, 333, 334, 335, 340, 341, 342, 343, 348, 349, 350, 351, 356, 357, 358, 359, 364, 365, 366, 368, 370, 371, 376, 377, 378, 379, 384, 385, 386, 387, 392, 393, 394, 395, 400, 401, 402, 403, 408, 409, 410, 411, 416, 417, 418, 419, 424, 425, 426, 427, 432, 433, 434, 435, 440, 441, 442, 443, 456, 457, 458, 459, 464, 465, 466, 467, 472, 473, 474, 475, 480, 481, 482, 483, 488, 489, 490, 491, 496, 497, 498, 499, 504, 505, 506, 507, 512, 513, 514, 515, 520, 521, 522, 523, 528, 529, 530, 531, 536, 537, 538, 551, 552, 553, 554, 559, 560, 561, 562, 575, 576, 577, 578, 583, 584, 585, 586, 591, 593, 594, 595, 596, 597, 598, 603, 605, 606, 607, 608, 609, 610, 615, 616, 617, 618, 631, 632, 633, 634, 639, 640, 641, 642, 647, 648, 649, 650, 655, 656, 657, 658, 663, 664, 665, 666, 667, 669, 672, 674, 675, 676, 677, 678, 679, 680, 685, 686, 687, 688, 733, 734, 735, 736]|
|:large_blue_circle:|com/starrocks/qe/StmtExecutor.java|1|2|50.00%|[1097]|
|:large_blue_circle:|com/starrocks/common/ErrorReport.java|5|6|83.33%|[84]|
|:large_blue_circle:|com/starrocks/sql/ast/CreateFunctionStmt.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/ShowFunctionsStmt.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/DropFunctionStmt.java|1|1|100.00%|[]|

**Comment by mofeiatwork** [comment]
run starrocks_admit_test

**Comment by mofeiatwork** [comment]
run starrocks_admit_test

**Review by kangkaisen — DISMISSED** [review]

**Review by HangyuanLiu — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 96 / 355 (27.04%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/analysis/InstallPluginStmt.java|0|1|00.00%|[98]|
|:large_blue_circle:|com/starrocks/analysis/DropFileStmt.java|0|1|00.00%|[119]|
|:large_blue_circle:|com/starrocks/analysis/UninstallPluginStmt.java|0|1|00.00%|[78]|
|:large_blue_circle:|com/starrocks/analysis/CancelBackupStmt.java|0|1|00.00%|[90]|
|:large_blue_circle:|com/starrocks/analysis/CreateFileStmt.java|0|1|00.00%|[172]|
|:large_blue_circle:|com/starrocks/analysis/CancelExportStmt.java|0|1|00.00%|[101]|
|:large_blue_circle:|com/starrocks/sql/ast/AstVisitor.java|1|8|12.50%|[224, 459, 602, 606, 610, 614, 618]|
|:large_blue_circle:|com/starrocks/qe/DDLStmtExecutor.java|85|329|25.84%|[97, 109, 111, 130, 140, 141, 142, 144, 158, 159, 160, 162, 171, 172, 173, 174, 175, 177, 178, 179, 184, 186, 187, 188, 189, 191, 192, 193, 206, 207, 208, 209, 222, 223, 224, 225, 255, 256, 257, 258, 259, 260, 261, 267, 268, 269, 270, 271, 272, 273, 286, 287, 288, 289, 294, 295, 296, 297, 302, 303, 304, 305, 307, 308, 312, 313, 314, 319, 320, 321, 322, 327, 328, 329, 330, 335, 336, 337, 338, 343, 344, 345, 346, 351, 352, 353, 354, 359, 360, 361, 362, 367, 368, 369, 370, 372, 374, 375, 377, 379, 380, 385, 386, 387, 388, 393, 394, 395, 397, 399, 400, 405, 406, 407, 409, 411, 412, 417, 418, 419, 420, 425, 426, 427, 428, 433, 434, 435, 436, 449, 450, 451, 452, 457, 458, 459, 460, 465, 466, 467, 468, 473, 474, 475, 476, 481, 482, 483, 484, 489, 490, 491, 492, 497, 498, 499, 500, 505, 506, 507, 508, 513, 514, 515, 516, 521, 522, 523, 524, 529, 530, 531, 544, 545, 546, 547, 552, 553, 554, 555, 568, 569, 570, 571, 576, 577, 578, 579, 584, 586, 587, 588, 589, 590, 591, 596, 598, 599, 600, 601, 602, 603, 608, 609, 610, 611, 624, 625, 626, 627, 632, 633, 634, 635, 640, 641, 642, 643, 648, 649, 650, 651, 656, 657, 658, 659, 660, 662, 665, 667, 668, 669, 670, 671, 672, 673, 678, 679, 680, 681, 726, 727, 728, 729]|
|:large_blue_circle:|com/starrocks/qe/StmtExecutor.java|1|2|50.00%|[1097]|
|:large_blue_circle:|com/starrocks/common/ErrorReport.java|5|6|83.33%|[84]|
|:large_blue_circle:|com/starrocks/sql/ast/SyncStmt.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/CreateFunctionStmt.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/ShowFunctionsStmt.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/DropFunctionStmt.java|1|1|100.00%|[]|

**Review by HangyuanLiu — APPROVED** [review]

**Review by kangkaisen — APPROVED** [review]

**Pull request merged**
