### PR TITLE
[BugFix] Forbid modify bucket when alter colocate dynamic partition table.

### LINKED ISSUE #17409: Colocate causes dynamic partition table to fail
### Steps to reproduce the behavior (Required)
1. CREATE TABLE colocate_table
(
    visitorid   INT,
    sessionid   BIGINT,
    visittime   DATETIME,
    city        CHAR(20),
    province    CHAR(20),
    ip          varchar(32),
    brower      CHAR(20),
    url         VARCHAR(1024)
)
DUPLICATE KEY(visitorid)
DISTRIBUTED BY HASH(visitorid) BUCKETS 10
PROPERTIES(
    "replication_num" = "1",
    "colocate_with" = "group2"
);
2.
CREATE TABLE site_access(
event_day DATETIME,
site_id INT DEFAULT '10',
city_code VARCHAR(100),
user_name VARCHAR(32) DEFAULT '',
pv BIGINT DEFAULT '0'
)
DUPLICATE KEY(event_day, site_id, city_code, user_name)
PARTITION BY RANGE(`event_day`)
(START ("2022-12-02") END ("2023-02-01") EVERY (INTERVAL 1 MONTH))
DISTRIBUTED BY HASH(`site_id`) BUCKETS 10
PROPERTIES (
"replication_num" = "1",
"colocate_with"="group2",
"dynamic_partition.enable" = "true",
"dynamic_partition.time_unit" = "MONTH",
"dynamic_partition.time_zone" = "Asia/Shanghai",
"dynamic_partition.end" = "2",
"dynamic_partition.prefix" = "p",
"dynamic_partition.buckets" = "10",
"in_memory" = "false",
"storage_format" = "DEFAULT"
);
3.
ALTER TABLE site_access SET("dynamic_partition.buckets"="5");

### Expected behavior (Required)
ERROR 1064 (HY000): Unexpected exception: Colocate tables must have same bucket num: 10
### Real behavior (Required)
Success.
But in log.
2023-02-06 14:56:52,242 WARN (DynamicPartitionScheduler|55) [DynamicPartitionScheduler.recordCreatePartitionFailedMsg():500] dynamic add partition failed: Colocate tables must have same bucket num: 10, db: test, table: site_access

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
2.2.10~main

### PR DESCRIPTION
**Pull request by Astralidea**
Signed-off-by: Astralidea <astralidea@163.com>

## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #17409

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [x] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 2.5
  - [x] 2.4
  - [x] 2.3
  - [x] 2.2

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 3 / 4 (75.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/alter/SchemaChangeHandler.java|3|4|75.00%|[1184]|

**Review by gengjun-git — APPROVED** [review]

**Review by ABingHuang — APPROVED** [review]
LGTM

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.4

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.3

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.2

**Pull request merged**
