### PR TITLE
[Refactor] rename the materialized column API to Generated Column

### PR DESCRIPTION
**Pull request by srlch**
Fixes #issue

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [x] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 75 / 124 (60.48%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/AlterTableClauseVisitor.java|7|21|33.33%|[286, 312, 323, 401, 405, 429, 440, 458, 459, 462, 491, 523, 549, 560]|
|:large_blue_circle:|com/starrocks/sql/ast/AddColumnsClause.java|1|3|33.33%|[32, 36]|
|:large_blue_circle:|com/starrocks/alter/SchemaChangeHandler.java|4|11|36.36%|[180, 188, 331, 334, 416, 420, 446]|
|:large_blue_circle:|com/starrocks/alter/SchemaChangeJobV2.java|7|14|50.00%|[528, 529, 550, 551, 592, 594, 605]|
|:large_blue_circle:|com/starrocks/load/Load.java|7|13|53.85%|[185, 242, 323, 324, 449, 675]|
|:large_blue_circle:|com/starrocks/sql/analyzer/UpdateAnalyzer.java|3|5|60.00%|[136, 151]|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|5|8|62.50%|[960, 3648, 3651]|
|:large_blue_circle:|com/starrocks/sql/InsertPlanner.java|4|6|66.67%|[425, 478]|
|:large_blue_circle:|com/starrocks/sql/ast/ColumnDef.java|5|7|71.43%|[213, 496]|
|:large_blue_circle:|com/starrocks/catalog/Column.java|11|13|84.62%|[474, 476]|
|:large_blue_circle:|com/starrocks/sql/analyzer/CreateTableAnalyzer.java|12|14|85.71%|[430, 446]|
|:large_blue_circle:|com/starrocks/catalog/OlapTable.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/InsertAnalyzer.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/QueryAnalyzer.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/UpdatePlanner.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/task/AlterReplicaTask.java|2|2|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 75 / 124 (60.48%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/AlterTableClauseVisitor.java|7|21|33.33%|[286, 312, 323, 401, 405, 429, 440, 458, 459, 462, 491, 523, 549, 560]|
|:large_blue_circle:|com/starrocks/sql/ast/AddColumnsClause.java|1|3|33.33%|[32, 36]|
|:large_blue_circle:|com/starrocks/alter/SchemaChangeHandler.java|4|11|36.36%|[180, 188, 331, 334, 416, 420, 446]|
|:large_blue_circle:|com/starrocks/alter/SchemaChangeJobV2.java|7|14|50.00%|[528, 529, 550, 551, 592, 594, 605]|
|:large_blue_circle:|com/starrocks/load/Load.java|7|13|53.85%|[185, 242, 323, 324, 449, 675]|
|:large_blue_circle:|com/starrocks/sql/analyzer/UpdateAnalyzer.java|3|5|60.00%|[136, 151]|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|5|8|62.50%|[960, 3648, 3651]|
|:large_blue_circle:|com/starrocks/sql/InsertPlanner.java|4|6|66.67%|[425, 478]|
|:large_blue_circle:|com/starrocks/sql/ast/ColumnDef.java|5|7|71.43%|[213, 496]|
|:large_blue_circle:|com/starrocks/catalog/Column.java|11|13|84.62%|[474, 476]|
|:large_blue_circle:|com/starrocks/sql/analyzer/CreateTableAnalyzer.java|12|14|85.71%|[430, 446]|
|:large_blue_circle:|com/starrocks/catalog/OlapTable.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/InsertAnalyzer.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/QueryAnalyzer.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/UpdatePlanner.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/task/AlterReplicaTask.java|2|2|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 75 / 124 (60.48%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/AlterTableClauseVisitor.java|7|21|33.33%|[286, 312, 323, 401, 405, 429, 440, 458, 459, 462, 491, 523, 549, 560]|
|:large_blue_circle:|com/starrocks/sql/ast/AddColumnsClause.java|1|3|33.33%|[32, 36]|
|:large_blue_circle:|com/starrocks/alter/SchemaChangeHandler.java|4|11|36.36%|[180, 188, 331, 334, 416, 420, 446]|
|:large_blue_circle:|com/starrocks/alter/SchemaChangeJobV2.java|7|14|50.00%|[528, 529, 550, 551, 592, 594, 605]|
|:large_blue_circle:|com/starrocks/load/Load.java|7|13|53.85%|[185, 242, 323, 324, 449, 675]|
|:large_blue_circle:|com/starrocks/sql/analyzer/UpdateAnalyzer.java|3|5|60.00%|[136, 151]|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|5|8|62.50%|[960, 3648, 3651]|
|:large_blue_circle:|com/starrocks/sql/InsertPlanner.java|4|6|66.67%|[425, 478]|
|:large_blue_circle:|com/starrocks/sql/ast/ColumnDef.java|5|7|71.43%|[213, 496]|
|:large_blue_circle:|com/starrocks/catalog/Column.java|11|13|84.62%|[474, 476]|
|:large_blue_circle:|com/starrocks/sql/analyzer/CreateTableAnalyzer.java|12|14|85.71%|[430, 446]|
|:large_blue_circle:|com/starrocks/catalog/OlapTable.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/InsertAnalyzer.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/QueryAnalyzer.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/UpdatePlanner.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/task/AlterReplicaTask.java|2|2|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:disappointed: **fail** : 80 / 152 (52.63%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/dump/DesensitizedSQLBuilder.java|0|2|00.00%|[547, 548]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AlterTableClauseVisitor.java|10|38|26.32%|[286, 299, 312, 322, 323, 332, 345, 346, 363, 402, 405, 416, 429, 439, 440, 449, 459, 466, 467, 469, 492, 523, 536, 549, 559, 560, 569, 588]|
|:large_blue_circle:|com/starrocks/sql/ast/AddColumnsClause.java|1|3|33.33%|[32, 36]|
|:large_blue_circle:|com/starrocks/alter/SchemaChangeJobV2.java|6|18|33.33%|[518, 524, 550, 551, 552, 559, 592, 594, 605, 616, 617, 618]|
|:large_blue_circle:|com/starrocks/alter/SchemaChangeHandler.java|4|11|36.36%|[180, 188, 331, 334, 416, 420, 446]|
|:large_blue_circle:|com/starrocks/sql/analyzer/UpdateAnalyzer.java|3|5|60.00%|[136, 151]|
|:large_blue_circle:|com/starrocks/load/Load.java|8|13|61.54%|[185, 242, 324, 449, 675]|
|:large_blue_circle:|com/starrocks/catalog/Column.java|12|19|63.16%|[458, 476, 479, 509, 619, 685, 706]|
|:large_blue_circle:|com/starrocks/sql/InsertPlanner.java|4|6|66.67%|[425, 478]|
|:large_blue_circle:|com/starrocks/sql/ast/ColumnDef.java|5|7|71.43%|[213, 496]|
|:large_blue_circle:|com/starrocks/sql/analyzer/CreateTableAnalyzer.java|14|17|82.35%|[426, 432, 442]|
|:large_blue_circle:|com/starrocks/catalog/OlapTable.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/InsertAnalyzer.java|5|5|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/QueryAnalyzer.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/UpdatePlanner.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/task/AlterReplicaTask.java|2|2|100.00%|[]|

**Review by decster — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 132 / 152 (86.84%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/dump/DesensitizedSQLBuilder.java|0|2|00.00%|[547, 548]|
|:large_blue_circle:|com/starrocks/load/Load.java|8|13|61.54%|[185, 242, 324, 449, 675]|
|:large_blue_circle:|com/starrocks/sql/analyzer/UpdateAnalyzer.java|4|5|80.00%|[136]|
|:large_blue_circle:|com/starrocks/sql/InsertPlanner.java|5|6|83.33%|[478]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AlterTableClauseVisitor.java|32|38|84.21%|[286, 405, 429, 440, 449, 523]|
|:large_blue_circle:|com/starrocks/sql/ast/ColumnDef.java|6|7|85.71%|[496]|
|:large_blue_circle:|com/starrocks/alter/SchemaChangeHandler.java|10|11|90.91%|[446]|
|:large_blue_circle:|com/starrocks/sql/analyzer/CreateTableAnalyzer.java|16|17|94.12%|[432]|
|:large_blue_circle:|com/starrocks/catalog/Column.java|18|19|94.74%|[458]|
|:large_blue_circle:|com/starrocks/alter/SchemaChangeJobV2.java|17|18|94.44%|[559]|
|:large_blue_circle:|com/starrocks/catalog/OlapTable.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/InsertAnalyzer.java|5|5|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/QueryAnalyzer.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/UpdatePlanner.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/task/AlterReplicaTask.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/AddColumnsClause.java|3|3|100.00%|[]|

**Review by HangyuanLiu — APPROVED** [review]

**Pull request merged**
