### PR TITLE
[BugFix] append_trailing_char_if_absent return empty string for const empty strings

### PR DESCRIPTION
**Pull request by fzhedu**
Signed-off-by: fzhedu <fzhedu@gmail.com>

## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #https://github.com/StarRocks/starrocks/issues/12769

## Problem Summary(Required) ：

append_trailing_char_if_absent's behavior is different when the first arg is an empty string from columns or not.
```
mysql> Create table t ( a int, name char(20), pv double) ENGINE=OLAP DUPLICATE KEY(a)  DISTRIBUTED BY HASH(a) BUCKETS 10 PROPERTIES("replication_num" = "1");
Query OK, 0 rows affected (0.01 sec)

mysql> insert into t values (1,'',3);
Query OK, 1 row affected (0.03 sec)
{'label':'insert_a4e0c3d6-670e-11ed-b25b-00163e1f2aee', 'status':'VISIBLE', 'txnId':'5640284'}

mysql> select append_trailing_char_if_absent(name,'a') from t;
+-------------------------------------------+
| append_trailing_char_if_absent(name, 'a') |
+-------------------------------------------+
|                                           |
+-------------------------------------------+
1 row in set (0.01 sec)


mysql> select append_trailing_char_if_absent('','a') from t;
+-----------------------------------------+
| append_trailing_char_if_absent('', 'a') |
+-----------------------------------------+
| a                                       |
+-----------------------------------------+
1 row in set (0.00 sec)
```

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

### CODE REVIEW

**Review by stdpain — APPROVED** [review]

**Review by silverbullet233 — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by kangkaisen — APPROVED** [review]

**Comment by fzhedu** [comment]
run starrocks_be_unittest

**Comment by fzhedu** [comment]
@mergify backport-2.2

**Comment by fzhedu** [comment]
@mergify backport-2.3

**Comment by fzhedu** [comment]
@mergify backport-2.4

**Comment by fzhedu** [comment]
@mergify backport-2.5

**Comment by fzhedu** [comment]
@mergify backport branch-2.4

**Comment by fzhedu** [comment]
@mergify backport branch-2.3

**Comment by fzhedu** [comment]
@mergify backport branch-2.2

**Pull request merged**
