### PR TITLE
Fix No such file or directory when firstly start FE

### PR DESCRIPTION
**Pull request by kangkaisen**
For https://github.com/StarRocks/starrocks/issues/69

### CODE REVIEW

**Comment by kangkaisen** [comment]
run starrocks_be_unittest

**Comment by kangkaisen** [comment]
run starrocks_be_unittest

**Review by dirtysalt — APPROVED** [review]

**Review by satanson — APPROVED** [review]

**Comment by wangruin** [comment]
is this need cherry pick to branch-1.18?

**Comment by kangkaisen** [comment]
> is this need cherry pick to branch-1.18?

No need. This issue doesn't prevent FE start successfully

**Pull request merged**
