### PR TITLE
[Refactor] iceberg and paimon table adapt to partition prune

### PR DESCRIPTION
**Pull request by stephen-shelby**
Fixes #issue

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [x] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:disappointed: **fail** : 16 / 54 (29.63%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/connector/iceberg/IcebergMetadata.java|0|1|00.00%|[318]|
|:large_blue_circle:|com/starrocks/sql/optimizer/statistics/StatisticsCalculator.java|0|2|00.00%|[290, 359]|
|:large_blue_circle:|com/starrocks/connector/unified/UnifiedMetadata.java|0|1|00.00%|[149]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rewrite/OptExternalPartitionPruner.java|12|46|26.09%|[316, 327, 328, 329, 330, 331, 332, 333, 335, 336, 338, 339, 342, 343, 345, 346, 347, 350, 351, 352, 353, 354, 355, 356, 357, 360, 361, 362, 364, 365, 366, 368, 369, 370]|
|:large_blue_circle:|com/starrocks/server/MetadataMgr.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/connector/iceberg/cost/IcebergStatisticProvider.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/connector/CatalogConnectorMetadata.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by Youngwb — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by Seaven — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 44 / 54 (81.48%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/connector/iceberg/IcebergMetadata.java|0|1|00.00%|[318]|
|:large_blue_circle:|com/starrocks/sql/optimizer/statistics/StatisticsCalculator.java|0|2|00.00%|[290, 359]|
|:large_blue_circle:|com/starrocks/connector/unified/UnifiedMetadata.java|0|1|00.00%|[149]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rewrite/OptExternalPartitionPruner.java|40|46|86.96%|[316, 336, 339, 357, 362, 366]|
|:large_blue_circle:|com/starrocks/server/MetadataMgr.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/connector/iceberg/cost/IcebergStatisticProvider.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/connector/CatalogConnectorMetadata.java|1|1|100.00%|[]|

**Pull request merged**
