### PR TITLE
[Enhancement] add position to parse node (step 2)

### PR DESCRIPTION
**Pull request by packy92**
## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

The following work of this PR #17883.
Extract position info from ParseRuleContext and save it in the ParseNode. 
Remove some unnecessary check in `AstBuilder` like:
starrocks.g4 has defind supported window function name and format.
```
windowFunction
    : name = ROW_NUMBER '(' ')'
    | name = RANK '(' ')'
    | name = DENSE_RANK '(' ')'
    | name = NTILE  '(' expression? ')'
    | name = LEAD  '(' (expression ignoreNulls? (',' expression)*)? ')'
    | name = LAG '(' (expression ignoreNulls? (',' expression)*)? ')'
    | name = FIRST_VALUE '(' (expression ignoreNulls? (',' expression)*)? ')'
    | name = LAST_VALUE '(' (expression ignoreNulls? (',' expression)*)? ')'
    ;
```
AstBuilder.java also dose a unnecessary name check.
```
@Override
    public ParseNode visitWindowFunction(StarRocksParser.WindowFunctionContext context) {
        if (WINDOW_FUNCTION_SET.contains(context.name.getText().toLowerCase())) {
            FunctionCallExpr functionCallExpr = new FunctionCallExpr(context.name.getText().toLowerCase(),
                    new FunctionParams(false, visit(context.expression(), Expr.class)));
            functionCallExpr.setIgnoreNulls(context.ignoreNulls() != null);
            return functionCallExpr;
        }
        throw new ParsingException("Unknown window function " + context.name.getText());
    }
```

Now when exception thrown in AstBuilder phase, we can print the error position info like this:
```
mysql> select SUBDATE(1,2,3,4);
ERROR 1064 (HY000): Getting syntax error from line 1, column 7 to line 1, column 22. Detail message: Incorrect number of arguments in expr 'subdate'.

mysql> CREATE MATERIALIZED VIEW lo_mv2
    -> PARTITION BY max(`lo_orderdate`)
    -> DISTRIBUTED BY HASH(`lo_orderkey`) BUCKETS
    -> 10
    ->
    -> REFRESH ASYNC START('2023-07-01 10:00:00') EVERY (interval
    -> 1
    ->  day)
    -> AS
    -> select
    ->     lo_orderkey,
    ->     lo_orderdate,
    ->     lo_custkey,
    ->     sum(lo_quantity) as total_quantity,
    ->     sum(lo_revenue) as total_revenue,
    ->     count(lo_shipmode) as shipmode_count
    -> from lineorder
    -> group by lo_orderkey, lo_orderdate, lo_custkey
    -> order by lo_orderkey;
ERROR 1064 (HY000): Getting syntax error from line 2, column 13 to line 2, column 31. Detail message: Unsupported expr 'max(lo_orderdate)' in PARTITION BY clause.
```

TODO:
1. wrap element(like property) in stmt with NodePosition to provide more specific position info when throw exception.
2. transform all the error message to the new pattern in build analyze phase.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Review by kangkaisen — DISMISSED** [review]

**Review by Seaven — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 187 / 219 (85.39%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/parser/NodePosition.java|0|2|00.00%|[44, 45]|
|:large_blue_circle:|com/starrocks/analysis/MultiInPredicate.java|1|3|33.33%|[38, 39]|
|:large_blue_circle:|com/starrocks/analysis/TimestampArithmeticExpr.java|2|6|33.33%|[74, 75, 91, 92]|
|:large_blue_circle:|com/starrocks/sql/ast/AlterUserStmt.java|1|3|33.33%|[26, 27]|
|:large_blue_circle:|com/starrocks/sql/ast/RevokePrivilegeStmt.java|1|3|33.33%|[28, 29]|
|:large_blue_circle:|com/starrocks/sql/ast/CreateViewStmt.java|1|3|33.33%|[30, 31]|
|:large_blue_circle:|com/starrocks/analysis/ArrowExpr.java|1|3|33.33%|[33, 34]|
|:large_blue_circle:|com/starrocks/analysis/OdbcScalarFunctionCall.java|2|5|40.00%|[70, 77, 90]|
|:large_blue_circle:|com/starrocks/analysis/LabelName.java|4|7|57.14%|[59, 60, 131]|
|:large_blue_circle:|com/starrocks/analysis/VarBinaryLiteral.java|3|5|60.00%|[63, 64]|
|:large_blue_circle:|com/starrocks/sql/ast/ImportColumnDesc.java|5|7|71.43%|[29, 78]|
|:large_blue_circle:|com/starrocks/analysis/InformationFunction.java|6|8|75.00%|[51, 52]|
|:large_blue_circle:|com/starrocks/analysis/RoutineLoadDataSourceProperties.java|5|6|83.33%|[241]|
|:large_blue_circle:|com/starrocks/analysis/ColumnDef.java|6|7|85.71%|[460]|
|:large_blue_circle:|com/starrocks/analysis/UserDesc.java|7|8|87.50%|[96]|
|:large_blue_circle:|com/starrocks/analysis/FunctionCallExpr.java|13|14|92.86%|[104]|
|:large_blue_circle:|com/starrocks/sql/ast/MultiItemListPartitionDesc.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/AnalyticExpr.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/Predicate.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/ShowTabletStmt.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/BetweenPredicate.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/ArithmeticExpr.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/SubfieldExpr.java|5|5|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/CompoundPredicate.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/SubqueryRelation.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/UnionRelation.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/GrantPrivilegeStmt.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/QueryStatement.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/ArrayExpr.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/IntersectRelation.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/DecimalLiteral.java|6|6|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/StringLiteral.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/IsNullPredicate.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/SingleItemListPartitionDesc.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/LambdaFunctionExpr.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/SelectRelation.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/CreateAnalyzeJobStmt.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/Subquery.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/AlterViewStmt.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/NullLiteral.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/DefaultValueExpr.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/BoolLiteral.java|6|6|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/FloatLiteral.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/IntervalLiteral.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/GroupingFunctionCallExpr.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/LikePredicate.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/VariableExpr.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/ExceptRelation.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/ValuesRelation.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/parser/PostProcessListener.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/BinaryPredicate.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/SingleRangePartitionDesc.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/CreateUserStmt.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/CaseExpr.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/ExistsPredicate.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/CastExpr.java|6|6|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/InPredicate.java|6|6|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 187 / 219 (85.39%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/parser/NodePosition.java|0|2|00.00%|[44, 45]|
|:large_blue_circle:|com/starrocks/analysis/MultiInPredicate.java|1|3|33.33%|[38, 39]|
|:large_blue_circle:|com/starrocks/analysis/TimestampArithmeticExpr.java|2|6|33.33%|[74, 75, 91, 92]|
|:large_blue_circle:|com/starrocks/sql/ast/AlterUserStmt.java|1|3|33.33%|[26, 27]|
|:large_blue_circle:|com/starrocks/sql/ast/RevokePrivilegeStmt.java|1|3|33.33%|[28, 29]|
|:large_blue_circle:|com/starrocks/sql/ast/CreateViewStmt.java|1|3|33.33%|[30, 31]|
|:large_blue_circle:|com/starrocks/analysis/ArrowExpr.java|1|3|33.33%|[33, 34]|
|:large_blue_circle:|com/starrocks/analysis/OdbcScalarFunctionCall.java|2|5|40.00%|[70, 77, 90]|
|:large_blue_circle:|com/starrocks/analysis/LabelName.java|4|7|57.14%|[59, 60, 131]|
|:large_blue_circle:|com/starrocks/analysis/VarBinaryLiteral.java|3|5|60.00%|[63, 64]|
|:large_blue_circle:|com/starrocks/sql/ast/ImportColumnDesc.java|5|7|71.43%|[29, 78]|
|:large_blue_circle:|com/starrocks/analysis/InformationFunction.java|6|8|75.00%|[51, 52]|
|:large_blue_circle:|com/starrocks/analysis/RoutineLoadDataSourceProperties.java|5|6|83.33%|[241]|
|:large_blue_circle:|com/starrocks/analysis/ColumnDef.java|6|7|85.71%|[460]|
|:large_blue_circle:|com/starrocks/analysis/UserDesc.java|7|8|87.50%|[96]|
|:large_blue_circle:|com/starrocks/analysis/FunctionCallExpr.java|13|14|92.86%|[104]|
|:large_blue_circle:|com/starrocks/sql/ast/MultiItemListPartitionDesc.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/AnalyticExpr.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/Predicate.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/ShowTabletStmt.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/BetweenPredicate.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/ArithmeticExpr.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/SubfieldExpr.java|5|5|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/CompoundPredicate.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/SubqueryRelation.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/UnionRelation.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/GrantPrivilegeStmt.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/QueryStatement.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/ArrayExpr.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/IntersectRelation.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/DecimalLiteral.java|6|6|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/StringLiteral.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/IsNullPredicate.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/SingleItemListPartitionDesc.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/LambdaFunctionExpr.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/SelectRelation.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/CreateAnalyzeJobStmt.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/Subquery.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/AlterViewStmt.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/NullLiteral.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/DefaultValueExpr.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/BoolLiteral.java|6|6|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/FloatLiteral.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/IntervalLiteral.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/GroupingFunctionCallExpr.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/LikePredicate.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/VariableExpr.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/ExceptRelation.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/ValuesRelation.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/parser/PostProcessListener.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/BinaryPredicate.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/SingleRangePartitionDesc.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/CreateUserStmt.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/CaseExpr.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/ExistsPredicate.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/CastExpr.java|6|6|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/InPredicate.java|6|6|100.00%|[]|

**Comment by packy92** [comment]
run starrocks_admit_test

**Comment by packy92** [comment]
run starrocks_admit_test

**Review by kangkaisen — APPROVED** [review]

**Review by murphyatwork — APPROVED** [review]

**Pull request merged**
