### PR TITLE
[Refactor] Rename ShowMaterializedView to ShowMaterializedViews

### LINKED ISSUE #13929: Enhance show materialized view
## Enhancement

Add several fields in `show materialized view` command:
1. `last_refresh_time`: to measure the freshness of this materialized view
2. `last_refresh_duration`: to measure the cost of refresh
3. `last_refresh_rows`: to measure the cost of refresh
4. `is_active`: whether the MV is active
5. `inactive_reason`: why this MV is not active? 

Current result:
image

### PR DESCRIPTION
**Pull request by LiShuMing**
Signed-off-by: Kevin Li <ming.moriarty@gmail.com>

## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [x] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #13929

- Rename `SHOW MATERIALIZED VIEW` to `SHOW MATERIALIZED VIEWS`;

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Review by Astralidea — DISMISSED** [review]

**Comment by LiShuMing** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 11 / 14 (78.57%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/ShowStmtAnalyzer.java|0|1|00.00%|[178]|
|:large_blue_circle:|com/starrocks/sql/analyzer/PrivilegeChecker.java|0|1|00.00%|[744]|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|2|3|66.67%|[1290]|
|:large_blue_circle:|com/starrocks/sql/analyzer/PrivilegeCheckerV2.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/ShowMaterializedViewsStmt.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/qe/ShowExecutor.java|5|5|100.00%|[]|

**Review by murphyatwork — COMMENTED** [review]
Please update the document in this PR

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 8 / 10 (80.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/PrivilegeChecker.java|0|1|00.00%|[779]|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|2|3|66.67%|[1302]|
|:large_blue_circle:|com/starrocks/sql/ast/ShowMaterializedViewsStmt.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/qe/ShowExecutor.java|3|3|100.00%|[]|

**Comment by LiShuMing** [comment]
run starrocks_fe_unittest

**Comment by LiShuMing** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 7 / 9 (77.78%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/PrivilegeChecker.java|0|1|00.00%|[779]|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|2|3|66.67%|[1305]|
|:large_blue_circle:|com/starrocks/qe/ShowExecutor.java|5|5|100.00%|[]|

**Comment by LiShuMing** [comment]
run starrocks_admit_test

**Review by Astralidea — APPROVED** [review]

**Comment by LiShuMing** [comment]
run starrocks_admit_test

**Pull request merged**
