### PR TITLE
[Refactor] refactor error msg for high-order functions

### PR DESCRIPTION
**Pull request by fzhedu**
Fixes #issue
make error msg more readable appending original expression, for example
```
mysql> select transform_keys((k,v)->(k,v), col_map) from (select map_from_arrays([1,3,null,2,null],['ab','cdd',null,null,'abc']) as col_map)A;
ERROR 1064 (HY000): Getting analyzing error from line 1, column 7 to line 1, column 43. Detail message: The right part of map lambda function ( (k, v) -> map{k:v} ) should have only one arguments in transform_keys((k, v) -> map{k:v}, col_map).
```
## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [x] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [x] 3.0
  - [ ] 2.5
  - [ ] 2.4

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by fzhedu** [comment]
related to https://github.com/StarRocks/starrocks/issues/27936

**Review by Seaven — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:disappointed: **fail** : 44 / 57 (77.19%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/ast/SetType.java|4|6|66.67%|[54, 56]|
|:large_blue_circle:|com/starrocks/sql/analyzer/ExpressionAnalyzer.java|28|39|71.79%|[292, 293, 358, 1216, 1217, 1226, 1227, 1245, 1269, 1273, 1278]|
|:large_blue_circle:|com/starrocks/sql/analyzer/SemanticException.java|7|7|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/Expr.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/VariableExpr.java|4|4|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by packy92 — APPROVED** [review]

**Review by Seaven — APPROVED** [review]

**Comment by fzhedu** [comment]
@mergify backport branch-3.0

**Comment by fzhedu** [comment]
@mergify backport branch-3.1

**Comment by fzhedu** [comment]
@mergify backport branch-3.2

**Pull request merged**
