### PR TITLE
[Refactor] Refactor pt_is_binary to pt_is_string

### PR DESCRIPTION
**Pull request by LiShuMing**
## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [x] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

Original `pt_is_binary` is not exactly correct because:
1. pt_is_binary only represents `TYPE_VARCHAR` and `TYPE_CHAR` which really are string types;
2. multi places use it as just string types, eg, max_by/min_by or runtime_filter.

So correct it to `pt_is_string` so later add a real binary type which is called `pt_is_binary`.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by LiShuMing** [comment]
run starrocks_be_unittest

**Comment by LiShuMing** [comment]
run starrocks_be_unittest

**Review by kangkaisen — DISMISSED** [review]

**Review by murphyatwork — DISMISSED** [review]

**Comment by LiShuMing** [comment]
run starrocks_be_unittest

**Review by kangkaisen — APPROVED** [review]

**Review by murphyatwork — APPROVED** [review]

**Comment by LiShuMing** [comment]
run starrocks_admit_test

**Pull request merged**
