### PR TITLE
[BugFix] compute memory layout of TupleDescriptor after setting nullable for SlotDescriptor

### LINKED ISSUE #14239: [sqlancer] crash of _M_range_insert
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
2. INSERT INTO '....'
3. SELECT  '....'

```sql
DROP DATABASE IF EXISTS g3;
CREATE DATABASE g3;
USE g3;
admin set frontend config ("enable_decimal_v3" = "true");
CREATE TABLE t0 (c_0_0 DATE NOT NULL,c_0_1 DATE NOT NULL,c_0_2 VARCHAR(41) NOT NULL,c_0_3 BOOLEAN NOT NULL,c_0_4 DECIMAL(31, 17)  NOT NULL) PRIMARY KEY (c_0_0,c_0_1,c_0_2,c_0_3) PARTITION BY RANGE(c_0_1) (START ("2010-01-01") END ("2022-12-31") EVERY (INTERVAL 182 day)) DISTRIBUTED BY HASH (c_0_1,c_0_2,c_0_0) BUCKETS 3 properties("replication_num"="3") ;
CREATE TABLE t1 (c_1_0 DATE NOT NULL ,c_1_1 DATE NOT NULL ,c_1_2 DATE NULL ,c_1_3 VARCHAR(1) NULL ,c_1_4 BIGINT NOT NULL ,c_1_5 SMALLINT NOT NULL ,c_1_6 CHAR(21) NOT NULL ,c_1_7 DATE NOT NULL ,c_1_8 BOOLEAN NULL ,c_1_9 VARCHAR(11) NULL ,c_1_10 BOOLEAN NULL ,c_1_11 BOOLEAN REPLACE NOT NULL ,c_1_12 HLL HLL_UNION NOT NULL ,c_1_13 DATETIME MIN NOT NULL ,c_1_14 DOUBLE MIN NOT NULL , INDEX index1_c_1_9(`c_1_9`) USING BITMAP) AGGREGATE KEY (c_1_0,c_1_1,c_1_2,c_1_3,c_1_4,c_1_5,c_1_6,c_1_7,c_1_8,c_1_9,c_1_10) PARTITION BY RANGE(c_1_0) (START ("2010-01-01") END ("2022-12-31") EVERY (INTERVAL 395 day)) DISTRIBUTED BY HASH (c_1_0,c_1_3,c_1_8,c_1_5,c_1_2,c_1_1,c_1_9,c_1_6) BUCKETS 3 properties("replication_num"="3", "bloom_filter_columns"="c_1_3") ;
CREATE TABLE t2 (c_2_0 DATETIME NULL ,c_2_1 DATE NULL ,c_2_2 LARGEINT NULL ,c_2_3 DATE NULL ,c_2_4 CHAR(1) NOT NULL ,c_2_5 SMALLINT NOT NULL ,c_2_6 LARGEINT NOT NULL ,c_2_7 DATETIME NOT NULL ,c_2_8 BOOLEAN NOT NULL ,c_2_9 SMALLINT NOT NULL ,c_2_10 BOOLEAN NOT NULL ,c_2_11 SMALLINT REPLACE NULL , INDEX index1_c_2_1(`c_2_1`) USING BITMAP, INDEX index1_c_2_4(`c_2_4`) USING BITMAP, INDEX index1_c_2_10(`c_2_10`) USING BITMAP) AGGREGATE KEY (c_2_0,c_2_1,c_2_2,c_2_3,c_2_4,c_2_5,c_2_6,c_2_7,c_2_8,c_2_9,c_2_10) PARTITION BY RANGE(c_2_1) (START ("2010-01-01") END ("2022-12-31") EVERY (INTERVAL 279 day)) DISTRIBUTED BY HASH (c_2_6,c_2_1,c_2_5,c_2_10,c_2_8,c_2_3,c_2_7,c_2_2,c_2_0,c_2_4) BUCKETS 3 properties("replication_num"="3") ;
CREATE TABLE t3 (c_3_0 DATE NULL ,c_3_1 VARCHAR(1) NOT NULL ,c_3_2 CHAR(11) NOT NULL ,c_3_3 BOOLEAN NOT NULL ,c_3_4 BOOLEAN NULL ,c_3_5 TINYINT NOT NULL ,c_3_6 BOOLEAN REPLACE NULL ,c_3_7 PERCENTILE PERCENTILE_UNION NOT NULL ,c_3_8 DOUBLE MAX NULL ,c_3_9 HLL HLL_UNION NOT NULL ,c_3_10 FLOAT MAX NULL ,c_3_11 VARCHAR(1) MAX NULL ,c_3_12 INT REPLACE NULL ,c_3_13 DECIMAL(17, 4)  REPLACE_IF_NOT_NULL NOT NULL ,c_3_14 LARGEINT REPLACE_IF_NOT_NULL NOT NULL ) AGGREGATE KEY (c_3_0,c_3_1,c_3_2,c_3_3,c_3_4,c_3_5) PARTITION BY RANGE(c_3_0) (START ("2010-01-01") END ("2022-12-31") EVERY (INTERVAL 143 day)) DISTRIBUTED BY HASH (c_3_0,c_3_1,c_3_5,c_3_2,c_3_3,c_3_4) BUCKETS 3 properties("replication_num"="3") ;
INSERT INTO t0 VALUES ('2009-12-31', '2010-01-16', 'Qw', true, 0.00090988854710509);
INSERT INTO t3 VALUES ('2010-01-13', '', 'P', false, NULL, 7, true, percentile_hash('-1344011015'), 0.4797871226667344, hll_hash('CJUgOQzu'), 0.017684271650853733, '', 6, 223742321.7428, NULL);
INSERT INTO t0 VALUES ('2010-01-26', '2010-01-23', 'UxU6Cw4k', true, 0.00006570509803496), ('2010-01-31', '2010-01-24', '1', true, 0.00002884754874681);
INSERT INTO t2 VALUES ('2010-01-03 08:00:14', '2010-01-17', 610374331, '2009-12-31', '', 1, -1775094353, '2010-01-03 08:00:14', true, 15, false, 10), ('2010-01-28 08:00:14', '2010-01-21', NULL, '2010-01-15', '', 0, 610374331, '2010-01-03 08:00:14', true, 14, false, 5), ('2010-01-29 08:00:14', '2010-01-17', 610374331, NULL, '', 12, -1344011015, '2010-01-12 08:00:14', false, 13, true, 8);
DELETE FROM t3 WHERE c_3_0='1969-12-14';
INSERT INTO t3 VALUES ('2010-01-28', '', '', false, false, 7, true, percentile_hash('610374331'), 0.4557311807711114, hll_hash(''), -1.539528419E9, NULL, 27, 222457997.2822, 723718169), ('2010-01-31', '', '', false, NULL, 1, true, percentile_hash('1125762344'), 0.6148872343353479, hll_hash('D'), 0.7876191137380569, '', 12, 464198463.7973, -1779261424), ('2010-01-14', '', 'CI', false, NULL, 2, false, percentile_hash('-1539528419'), 0.6321328601395277, hll_hash('19d'), 0.7876191137380569, '', NULL, 372678672.1769, NULL);
INSERT INTO t1 VALUES ('2010-01-16', '2010-01-14', '2010-01-14', '', -1844930414, 0, 'J', '2010-01-06', true, 'qgj', false, true, hll_hash('K3'), '2010-01-12 08:00:14', 0.5338839342565082), ('2010-01-03', '2010-01-08', NULL, '', -456043167, 11, 'amSV7thS', '2010-01-18', false, '', false, true, hll_hash('L0uXKNF'), '2010-01-03 08:00:14', -1.775094353E9);
INSERT INTO t2 VALUES ('2010-01-22 08:00:14', '2010-01-21', 1209779933, '2010-01-12', '', 10, 1209779933, '2010-01-05 08:00:14', false, 8, false, 12), ('2010-01-28 08:00:14', '2010-01-12', 40012526, '2010-01-04', '', 13, -1539528419, '2009-12-31 08:00:14', false, 7, true, NULL), ('2010-01-14 08:00:14', '2010-01-28', 866172122, '2010-01-08', '', 13, -1341026521, '2010-01-07 08:00:14', false, 12, false, 0), ('2010-01-13 08:00:14', NULL, -1779261424, '2010-01-14', '', 14, 1125762344, '2010-01-20 08:00:14', true, 4, true, 13), ('2010-01-24 08:00:14', '2010-01-15', 490610568, '2010-01-03', '', 12, -942521328, '2010-01-31 08:00:14', false, 1, false, 8);
INSERT INTO t0 VALUES ('2010-01-09', '2010-01-31', 'a', true, 0.00021586359765046);
INSERT INTO t3 VALUES ('2010-01-09', '', 'DmeJA', false, true, 1, NULL, percentile_hash('-296664487'), -1.779261424E9, hll_hash('2IMj1PK'), '+Inf', '', 2, 721295780.5624, 1754922085), ('2010-01-24', '', '', true, false, 3, true, percentile_hash('1675856663'), 0.15854872130233633, hll_hash(''), 0.4797871226667344, '', 2, 719164424.9198, 2038513747), ('2009-12-31', '', '', false, false, 0, true, percentile_hash('2077046988'), 0.8886701815216368, hll_hash('4lNAsX2'), 0.1319624694437146, '', 8, 669852412.6741, 1209779933);
INSERT INTO t1 VALUES ('2010-01-05', '2010-01-05', NULL, '', -43462582, 8, 'RR', '2010-01-24', false, 'I', false, true, hll_hash('n'), '2010-01-13 08:00:14', 0.1319624694437146);
INSERT INTO t0 VALUES ('2010-01-01', '2010-01-28', '6p', false, 0.00033382156571704), ('2010-01-30', '2010-01-14', 'Cob8xocs', false, 0.00065035831127175);
INSERT INTO t2 VALUES ('2010-01-16 08:00:14', '2010-01-25', -1344011015, '2010-01-15', '', 4, -9223372036854775808, '2010-01-10 08:00:14', true, 9, true, 9);
INSERT INTO t0 VALUES ('2010-01-30', '2010-01-12', 'F', false, 0.00075201157595497);
INSERT INTO t1 VALUES ('2010-01-31', '2010-01-13', '2010-01-27', '', -1341026521, 3, '', '2010-01-10', false, NULL, true, true, hll_hash(''), '2010-01-16 08:00:14', 0.7876191137380569), ('2010-01-10', '2010-01-22', '2010-01-09', '', 753393392, 5, 'gn', '2010-01-11', true, 'FpWU1C', false, false, hll_hash('P'), '2010-01-21 08:00:14', 0.5147423105888222), ('2010-01-22', '2010-01-25', '2010-01-24', '', -1513258045, 8, 'eA', '2010-01-14', false, 's', true, true, hll_hash('gusxTW'), '2010-01-13 08:00:14', 0.8044437987581631);
INSERT INTO t0 VALUES ('2010-01-06', '2010-01-19', 'XZ', true, 0.00031395460140473), ('2010-01-25', '2010-01-17', '', false, 0.00029340248543919);
INSERT INTO t0 VALUES ('2010-01-17', '2010-01-30', '', false, 0.00014899522756783), ('2010-01-02', '2010-01-21', 'Se0z', false, 0.00057998349330871);
INSERT INTO t0 VALUES ('2010-01-03', '2010-01-14', 'Tu', true, 0.00063482495256429), ('2010-01-22', '2010-01-29', 'N', true, 0.00085458350396063);
INSERT INTO t0 VALUES ('2010-01-26', '2010-01-03', 'ayzoDD', true, 0.00015472139242539);
INSERT INTO t2 VALUES (NULL, '2010-01-10', 866172122, '2010-01-14', '', 6, 1675856663, '2010-01-21 08:00:14', false, 10, false, 9), ('2010-01-03 08:00:14', '2010-01-16', -9223372036854775808, '2010-01-19', '', 15, 451212207, '2010-01-11 08:00:14', true, 3, true, 15);

WITH with_t_0 as (SELECT t2_74.c_2_0, t2_74.c_2_1, t2_74.c_2_2, t2_74.c_2_3, t2_74.c_2_4, t2_74.c_2_5, t2_74.c_2_6, t2_74.c_2_7, t2_74.c_2_8, t2_74.c_2_9, t2_74.c_2_10, t2_74.c_2_11 FROM t2 AS t2_74) , with_t_1 as (SELECT t0_72.c_0_0, t0_72.c_0_1, t0_72.c_0_2, t0_72.c_0_3, t0_72.c_0_4 FROM t0 AS t0_72) SELECT t2_74.c_2_0, t2_74.c_2_8, t2_74.c_2_1, t2_74.c_2_3, t2_74.c_2_10, subt0.c_0_3, subt0.c_0_2, t2_74.c_2_11, subt0.c_0_1, t2_74.c_2_7, subt0.c_0_0, t2_74.c_2_2, t2_74.c_2_4, t2_74.c_2_9 FROM t3 AS t3_75, t1 AS t1_73, with_t_0 AS with_t_0, with_t_1 AS with_t_1,  t2 AS t2_74 RIGHT JOIN (SELECT t0_72.c_0_0, t0_72.c_0_1, t0_72.c_0_2, t0_72.c_0_3, t0_72.c_0_4 FROM t0 AS t0_72) subt0 ON t2_74.c_2_1 = subt0.c_0_0 AND t2_74.c_2_1 < subt0.c_0_0 GROUP BY t2_74.c_2_0, t2_74.c_2_8, t2_74.c_2_1, t2_74.c_2_3, t2_74.c_2_10, subt0.c_0_3, subt0.c_0_2, t2_74.c_2_11, subt0.c_0_1, t2_74.c_2_7, subt0.c_0_0, t2_74.c_2_2, t2_74.c_2_4, t2_74.c_2_9;
```

### Expected behavior (Required)
no crash

### Real behavior (Required)
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Internal error: vector::_M_range_insert

(gdb) bt
#0  0x00007f9b9d49c30e in __memcpy_ssse3_back () from /lib64/libc.so.6
#1  0x00000000020d7bb2 in void std::vector<unsigned char, starrocks::raw::RawAllocator<unsigned char, 16ul, std::allocator<unsigned char> > >::_M_range_insert<unsigned char const*>(__gnu_cxx::__normal_iterator<unsigned char*, std::vector<unsigned char, starrocks::raw::RawAllocator<unsigned char, 16ul, std::allocator<unsigned char> > > >, unsigned char const*, unsigned char const*, std::forward_iterator_tag) [clone .constprop.0] ()
#2  0x00000000020db534 in starrocks::vectorized::BinaryColumnBase<unsigned int>::append(starrocks::vectorized::Column const&, unsigned long, unsigned long) ()
#3  0x00000000023cbda7 in starrocks::pipeline::NLJoinProbeOperator::_permute_probe_row(starrocks::RuntimeState*, std::shared_ptr<starrocks::vectorized::Chunk> const&) ()
#4  0x00000000023cc45c in starrocks::pipeline::NLJoinProbeOperator::_permute_chunk(starrocks::RuntimeState*) ()
#5  0x00000000023cda07 in starrocks::pipeline::NLJoinProbeOperator::pull_chunk(starrocks::RuntimeState*) ()
#6  0x0000000002104863 in starrocks::pipeline::PipelineDriver::process(starrocks::RuntimeState*, int) ()
#7  0x00000000042b1c6f in starrocks::pipeline::GlobalDriverExecutor::_worker_thread() ()
#8  0x0000000003ce57a5 in starrocks::ThreadPool::dispatch_thread() ()
#9  0x0000000003ce0c5a in starrocks::Thread::supervise_thread(void*) ()
#10 0x00007f9b9de29e65 in start_thread () from /lib64/libpthread.so.0
#11 0x00007f9b9d44488d in clone () from /lib64/libc.so.6

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
mysql> select current_version();
+----------------------+
| current_version()    |
+----------------------+
| MAIN-RELEASE 40c6659 |
+----------------------+
1 row in set (0.00 sec)

### PR DESCRIPTION
**Pull request by silverbullet233**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #14239 

## Problem Summary(Required) ：

In BE, SlotDescriptor judges nullable based on the information of nullIndicator passed from FE. This information is computed in `TupleDescriptor::computeMemLayout` method, If you only setNullable to SlotDescriptor but not re-compute memory layout of TupleDescriptor, it will pass a wrong result to BE.

The following is the physical plan of the query in the issue
image

`c_2_4` is a NOT NULL column, but it will be rewritten as nullable during `visitPhysicalJoin` because it appears in the left side of right outer join. At this time, the computeMemLayout logic is missed and the correct information is not passed to BE.

In this PR, I fixed the above problem and also handle nullable property of SlotDescriptor in visitPhysicalNestLoopJoin, just like it in visitPhysicalJoin

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 2.5
  - [x] 2.4
  - [x] 2.3
  - [ ] 2.2

### CODE REVIEW

**Comment by silverbullet233** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 18 / 20 (90.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/plan/PlanFragmentBuilder.java|18|20|90.00%|[1851, 1852]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 17 / 17 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/plan/PlanFragmentBuilder.java|17|17|100.00%|[]|

**Comment by silverbullet233** [comment]
run starrocks_admit_test

**Comment by silverbullet233** [comment]
run starrocks_admit_test

**Comment by silverbullet233** [comment]
run starrocks_admit_test

**Review by murphyatwork — APPROVED** [review]

**Review by Seaven — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.3

**Pull request merged**
