### PR TITLE
[BugFix]Revert "[Enhancement] optimize iceberg const column (#31632)"

### PR DESCRIPTION
**Pull request by zombee0**
This reverts commit f82b51ca89556ca7c9625ff90f07a2c204ffa821.
This pr encountered some bad case when deploy exec plan, revert first and optimize later

Fixes #issue

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Review by stephen-shelby — APPROVED** [review]

**Review by dirtysalt — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:disappointed: **fail** : 5 / 17 (29.41%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/plan/PlanFragmentBuilder.java|0|1|00.00%|[1156]|
|:large_blue_circle:|com/starrocks/planner/IcebergScanNode.java|5|16|31.25%|[155, 156, 159, 161, 162, 163, 167, 168, 170, 171, 172]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 3 / 4 (75.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/runtime/descriptors.cpp|0|1|00.00%|[585]|
|:large_blue_circle:|src/connector/hive_connector.cpp|2|2|100.00%|[]|
|:large_blue_circle:|src/formats/parquet/file_reader.cpp|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:disappointed: **fail** : 5 / 17 (29.41%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/plan/PlanFragmentBuilder.java|0|1|00.00%|[1156]|
|:large_blue_circle:|com/starrocks/planner/IcebergScanNode.java|5|16|31.25%|[155, 156, 159, 161, 162, 163, 167, 168, 170, 171, 172]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 3 / 4 (75.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/runtime/descriptors.cpp|0|1|00.00%|[585]|
|:large_blue_circle:|src/connector/hive_connector.cpp|2|2|100.00%|[]|
|:large_blue_circle:|src/formats/parquet/file_reader.cpp|1|1|100.00%|[]|

**Pull request merged**
