### PR TITLE
[Refactor] force arrow links to external jemalloc static library

### PR DESCRIPTION
**Pull request by kevincai**
* maintain only one copy of jemalloc in sr project

## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [X] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [X] I have checked the version labels which the pr will be auto backported to target branch
  - [X] 3.0
  - [X] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Review by dirtysalt — DISMISSED** [review]

**Comment by andyziye** [comment]
@Mergifyio rebase

**Comment by andyziye** [comment]
@Mergifyio rebase

**Comment by andyziye** [comment]
@Mergifyio rebase

**Comment by andyziye** [comment]
@Mergifyio rebase

**Comment by andyziye** [comment]
@Mergifyio rebase

**Comment by kevincai** [comment]
@Mergifyio rebase

**Comment by andyziye** [comment]
@Mergifyio rebase

**Review by silverbullet233 — APPROVED** [review]
LGTM

**Review by imay — APPROVED** [review]

**Comment by kevincai** [comment]
@mergifyio backport branch-3.0

**Comment by kevincai** [comment]
@mergifyio backport branch-2.5

**Comment by yangrong688** [comment]
image
Hi, @kevincai , I found starrocks/dev-env:main docker image not automatically updated after this pr. I think it is better to add a ci script to automatically update dev-env docker image. PTAL, thanks.

**Comment by kevincai** [comment]
@yangrong688 please move to `starrocks/dev-env-centos7:latest` if you are using centos7 development environment or `starrocks/dev-env-ubuntu:latest` if is a ubuntu platform development env.

**Comment by yangrong688** [comment]
> @yangrong688 please move to `starrocks/dev-env-centos7:latest` if you are using centos7 development environment or `starrocks/dev-env-ubuntu:latest` if is a ubuntu platform development env.

I will have a try, thanks for your reply.

**Comment by yangrong688** [comment]
> > @yangrong688 please move to `starrocks/dev-env-centos7:latest` if you are using centos7 development environment or `starrocks/dev-env-ubuntu:latest` if is a ubuntu platform development env.
> 
> I will have a try, thanks for your reply.

I have successfully compiled starrocks after update docker image to starrocks/dev-env-centos7:latest, thanks for your help.

**Pull request merged**
