### PR TITLE
[Refactor] Support to resend request of hive thrift api "getPartitionByNames"

### PR DESCRIPTION
**Pull request by stephen-shelby**
…ames".

## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

 Both 'getPartitionByNames' and 'getPartitionColumnStatistics' could throw exception or no response when querying too many partitions at present. Due to statistics don't affect accuracy, user could adjust session variable 'hive_partition_stats_sample_size' to ensure 'getPartitionColumnStat' normal return.  But "getPartitionByNames" interface must return the full contents due to the need to get partition file information.  So we resend request "getPartitionByNames" when an exception occurs.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by stephen-shelby** [comment]
run starrocks_admit_test

**Review by Youngwb — APPROVED** [review]

**Comment by stephen-shelby** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 0 / 10 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/external/hive/HiveMetaClient.java|0|10|00.00%|[176, 177, 179, 181, 182, 188, 246, 247, 250, 251]|

**Review by caneGuy — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by stephen-shelby** [comment]
run starrocks_admit_test

**Comment by stephen-shelby** [comment]
run starrocks_admit_test

**Pull request merged**
