### PR TITLE
[Feature] refine MV interface

### PR DESCRIPTION
**Pull request by murphyatwork**
## What type of PR is this：
- [ ] BugFix
- [x] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 4 / 32 (12.50%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/scheduler/mv/MVEpoch.java|0|1|00.00%|[110]|
|:large_blue_circle:|com/starrocks/scheduler/mv/TxnBasedEpochCoordinator.java|0|7|00.00%|[149, 161, 162, 163, 166, 167, 169]|
|:large_blue_circle:|com/starrocks/qe/CoordinatorPreprocessor.java|0|1|00.00%|[1331]|
|:large_blue_circle:|com/starrocks/scheduler/mv/MVMaintenanceTask.java|0|8|00.00%|[43, 52, 64, 65, 66, 104, 108, 112]|
|:large_blue_circle:|com/starrocks/scheduler/mv/BinlogConsumeStateVO.java|0|1|00.00%|[55]|
|:large_blue_circle:|com/starrocks/scheduler/mv/MVMaintenanceJob.java|4|14|28.57%|[237, 238, 239, 240, 241, 242, 270, 271, 272, 379]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 4 / 34 (11.76%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/scheduler/mv/MVEpoch.java|0|1|00.00%|[110]|
|:large_blue_circle:|com/starrocks/scheduler/mv/TxnBasedEpochCoordinator.java|0|7|00.00%|[149, 161, 162, 163, 166, 167, 169]|
|:large_blue_circle:|com/starrocks/qe/CoordinatorPreprocessor.java|0|1|00.00%|[1331]|
|:large_blue_circle:|com/starrocks/scheduler/mv/MVMaintenanceTask.java|0|9|00.00%|[45, 53, 55, 67, 68, 69, 107, 111, 115]|
|:large_blue_circle:|com/starrocks/scheduler/mv/BinlogConsumeStateVO.java|0|1|00.00%|[55]|
|:large_blue_circle:|com/starrocks/scheduler/mv/MVMaintenanceJob.java|4|15|26.67%|[237, 238, 239, 240, 241, 242, 243, 271, 272, 273, 380]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 4 / 34 (11.76%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/scheduler/mv/MVEpoch.java|0|1|00.00%|[110]|
|:large_blue_circle:|com/starrocks/scheduler/mv/TxnBasedEpochCoordinator.java|0|7|00.00%|[149, 161, 162, 163, 166, 167, 169]|
|:large_blue_circle:|com/starrocks/qe/CoordinatorPreprocessor.java|0|1|00.00%|[1331]|
|:large_blue_circle:|com/starrocks/scheduler/mv/MVMaintenanceTask.java|0|9|00.00%|[45, 53, 55, 67, 68, 69, 107, 111, 115]|
|:large_blue_circle:|com/starrocks/scheduler/mv/BinlogConsumeStateVO.java|0|1|00.00%|[55]|
|:large_blue_circle:|com/starrocks/scheduler/mv/MVMaintenanceJob.java|4|15|26.67%|[237, 238, 239, 240, 241, 242, 243, 271, 272, 273, 380]|

**Review by kangkaisen — APPROVED** [review]

**Comment by mofeiatwork** [comment]
run starrocks_admit_test

**Review by Seaven — APPROVED** [review]

**Pull request merged**
