### PR TITLE
[Bugfix] fix mv partition refresh all the time if partition roll up

### PR DESCRIPTION
**Pull request by blackstar-baba**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #

## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

1. Create table and mv
```
CREATE TABLE tbl1
(
k1 date,
k2 int,
v1 int sum
)
PARTITION BY RANGE(k1)
(
    PARTITION p1 values less than('2022-02-01'),
    PARTITION p2 values less than('2022-03-01'),
    PARTITION p3 values less than('2022-04-01')
)
DISTRIBUTED BY HASH(k2) BUCKETS 3
PROPERTIES('replication_num' = '1');

CREATE TABLE tbl2
(
k1 date,
k2 int,
v1 int
)
DISTRIBUTED BY HASH(k2) BUCKETS 3
PROPERTIES('replication_num' = '1');

CREATE MATERIALIZED VIEW mv1_multi_tables_partition_by_function_year
PARTITION BY date_trunc('month',s1)
distributed by hash(s2)
refresh async EVERY(INTERVAL 10 SECOND)
PROPERTIES('replication_num' = '1')
AS select t1.k1 s1, t2.k2 s2 from tbl1 t1 join tbl2 t2 on t1.k1 = t2.k1;
```
2. Drop exist base table partition
```
ALTER TABLE tbl1 DROP PARTITION p3;
```
3.  Fe.log like this:
```
2022-07-28 11:14:13,369 INFO (pool-21-thread-3|418) [MvTaskRunProcessor.processSyncBasePartition():227] The process of synchronizing partitions delete range {}
2022-07-28 11:14:13,389 INFO (pool-21-thread-3|418) [MvTaskRunProcessor.processSyncBasePartition():237] The process of synchronizing partitions add range {} 
2022-07-28 11:14:13,390 INFO (pool-21-thread-3|418) [MvTaskRunProcessor.processSyncBasePartition():273] Calculate the partitions that need to be refreshed:[[p2022_2023, p0001_2022]]
……
2022-07-28 11:14:23,366 INFO (pool-21-thread-3|418) [MvTaskRunProcessor.processSyncBasePartition():227] The process of synchronizing partitions delete range {}
2022-07-28 11:14:23,386 INFO (pool-21-thread-3|418) [MvTaskRunProcessor.processSyncBasePartition():237] The process of synchronizing partitions add range {} 
2022-07-28 11:14:23,386 INFO (pool-21-thread-3|418) [MvTaskRunProcessor.processSyncBasePartition():273] Calculate the partitions that need to be refreshed:[[p2022_2023, p0001_2022]]
……
2022-07-28 11:14:33,363 INFO (pool-21-thread-3|418) [MvTaskRunProcessor.processSyncBasePartition():227] The process of synchronizing partitions delete range {}
2022-07-28 11:14:33,384 INFO (pool-21-thread-3|418) [MvTaskRunProcessor.processSyncBasePartition():237] The process of synchronizing partitions add range {} 
2022-07-28 11:14:33,385 INFO (pool-21-thread-3|418) [MvTaskRunProcessor.processSyncBasePartition():273] Calculate the partitions that need to be refreshed:[[p2022_2023, p0001_2022]]
……
```

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 10 / 10 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/MaterializedView.java|5|5|100.00%|[]|
|:large_blue_circle:|com/starrocks/scheduler/MvTaskRunProcessor.java|5|5|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 16 / 18 (88.89%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/scheduler/MvTaskRunProcessor.java|7|9|77.78%|[112, 116]|
|:large_blue_circle:|com/starrocks/catalog/MaterializedView.java|9|9|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 19 / 21 (90.48%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/scheduler/MvTaskRunProcessor.java|10|12|83.33%|[112, 116]|
|:large_blue_circle:|com/starrocks/catalog/MaterializedView.java|9|9|100.00%|[]|

**Review by Astralidea — APPROVED** [review]

**Comment by Astralidea** [comment]
run starrocks_admit_test

**Comment by Astralidea** [comment]
run starrocks_admit_test

**Comment by Astralidea** [comment]
run starrocks_admit_test

**Review by gengjun-git — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Pull request merged**
