### PR TITLE
[BugFix] Fix turn on table name typos

### LINKED ISSUE #14893: Turn on column name restrictions
## Enhancement
Many users who use hive now find that the table limit of hive is 1024, while the limit of mysql is 64. This limit should be opened, and it should not be so small.

### PR DESCRIPTION
**Pull request by Astralidea**
## What type of PR is this：
- [] BugFix
- [ ] Feature
- [ ] Enhancement
- [x] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #14893

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Review by Youngwb — APPROVED** [review]

**Comment by Astralidea** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by Astralidea** [comment]
run starrocks_be_unittest

**Review by imay — APPROVED** [review]

**Comment by mofeiatwork** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
