### PR TITLE
[Enhancement][Cherry-Pick][Branch-3.1] improve parquet reader performance

### PR DESCRIPTION
**Pull request by Smith-Cruise**
cp #28880 #28891 #24566 #28771

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:heart_eyes: **pass** : 74 / 81 (91.36%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/storage/rowset/rle_page.h|0|1|00.00%|[97]|
|:large_blue_circle:|src/formats/parquet/encoding_dict.h|16|18|88.89%|[261, 277]|
|:large_blue_circle:|src/util/compression/block_compression.cpp|19|21|90.48%|[993, 1000]|
|:large_blue_circle:|src/util/rle_encoding.h|38|40|95.00%|[403, 951]|
|:large_blue_circle:|src/column/nullable_column.cpp|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:heart_eyes: **pass** : 76 / 83 (91.57%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/storage/rowset/rle_page.h|0|1|00.00%|[97]|
|:large_blue_circle:|src/util/compression/block_compression.cpp|18|20|90.00%|[993, 1000]|
|:large_blue_circle:|src/formats/parquet/encoding_dict.h|18|20|90.00%|[261, 277]|
|:large_blue_circle:|src/util/rle_encoding.h|39|41|95.12%|[403, 951]|
|:large_blue_circle:|src/column/nullable_column.cpp|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:heart_eyes: **pass** : 78 / 83 (93.98%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/storage/rowset/rle_page.h|0|1|00.00%|[97]|
|:large_blue_circle:|src/util/compression/block_compression.cpp|18|20|90.00%|[993, 1000]|
|:large_blue_circle:|src/util/rle_encoding.h|39|41|95.12%|[403, 951]|
|:large_blue_circle:|src/column/nullable_column.cpp|1|1|100.00%|[]|
|:large_blue_circle:|src/formats/parquet/encoding_dict.h|20|20|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:heart_eyes: **pass** : 64 / 67 (95.52%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/storage/rowset/rle_page.h|0|1|00.00%|[97]|
|:large_blue_circle:|src/util/rle_encoding.h|39|41|95.12%|[403, 951]|
|:large_blue_circle:|src/util/compression/block_compression.cpp|4|4|100.00%|[]|
|:large_blue_circle:|src/column/nullable_column.cpp|1|1|100.00%|[]|
|:large_blue_circle:|src/formats/parquet/encoding_dict.h|20|20|100.00%|[]|

**Review by dirtysalt — APPROVED** [review]

**Comment by Smith-Cruise** [comment]
@Mergify backport branch-3.0

**Pull request merged**
