### PR TITLE
[BugFix] Analyze non-function partition exprs in ExpressionRangePartitionInfo in deserialize

### LINKED ISSUE #31354: Backup/Restore partitioned materialized view coredump in asan mode
### Steps to reproduce the behavior (Required)
```
            CREATE MATERIALIZED VIEW aggregate_table_with_null_mv1
            DISTRIBUTED BY HASH(k1, k2, v2, v3, v4, v5) BUCKETS 4
            PARTITION BY k1
            as select k1, k2, v2, v3, v4, v5, sum(v1), sum(v2), sum(v3), max(v4), max(v5), min(v6), min(v7), sum(v8)
            from aggregate_table_with_null_partition
            group by k1, k2, v2, v3, v4, v5

SELECT * FROM INFORMATION_SCHEMA.task_runs
                       WHERE `DATABASE`='test_backup_c4624db6_56ac_11ee_ac29_c9d28a9636a8' and DEFINITION LIKE '%insert overwrite aggregate_table_with_null_mv1%'
                       ORDER BY CREATE_TIME DESC LIMIT 1;
SELECT * FROM INFORMATION_SCHEMA.task_runs
                       WHERE `DATABASE`='test_backup_c4624db6_56ac_11ee_ac29_c9d28a9636a8' and DEFINITION LIKE '%insert overwrite aggregate_table_with_null_mv1%'
                       ORDER BY CREATE_TIME DESC LIMIT 1;
analyze full table test_backup_c4624db6_56ac_11ee_ac29_c9d28a9636a8.aggregate_table_with_null_mv1;
explain select max(v4), max(v5) from aggregate_table_with_null_partition
select max(v4), max(v5) from aggregate_table_with_null_partition
BACKUP SNAPSHOT test_backup_c4624db6_56ac_11ee_ac29_c9d28a9636a8.test_base_backup1 to backup_repository_c4624db7_56ac_11ee_ac29_c9d28a9636a8 on (aggregate_table_with_null_partition PARTITION (p202006))PROPERTIES ('timeout' = '600')
BACKUP SNAPSHOT test_backup_c4624db6_56ac_11ee_ac29_c9d28a9636a8.test_mv_backup1 to backup_repository_c4624db7_56ac_11ee_ac29_c9d28a9636a8 on (aggregate_table_with_null_mv1 PARTITION (p202006))PROPERTIES ('timeout' = '600')
drop table aggregate_table_with_null_partition
drop materialized view aggregate_table_with_null_mv1
show snapshot on backup_repository_c4624db7_56ac_11ee_ac29_c9d28a9636a8
RESTORE SNAPSHOT test_backup_c4624db6_56ac_11ee_ac29_c9d28a9636a8.`test_mv_backup1` from `backup_repository_c4624db7_56ac_11ee_ac29_c9d28a9636a8` on (aggregate_table_with_null_mv1) PROPERTIES( "backup_timestamp"="2023-09-19-13-24-54-434", "replication_num" = "1", "timeout" = "600")
show snapshot on backup_repository_c4624db7_56ac_11ee_ac29_c9d28a9636a8
RESTORE SNAPSHOT test_backup_c4624db6_56ac_11ee_ac29_c9d28a9636a8.`test_base_backup1` from `backup_repository_c4624db7_56ac_11ee_ac29_c9d28a9636a8` on (aggregate_table_with_null_partition) PROPERTIES( "backup_timestamp"="2023-09-19-13-24-34-390", "replication_num" = "1", "timeout" = "600")
```

### Expected behavior (Required)
should not generate core dump in asan

### Real behavior (Required)

```
*** Aborted at 1694560984 (unix time) try "date -d @1694560984" if you are using GNU date ***
PC: @     0x7f4a1f3c1387 __GI_raise
*** SIGABRT (@0x3e8000009e3) received by PID 2531 (TID 0x7f49a841e700) from PID 2531; stack trace: ***
    @         0x155cc112 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7f4a1fe76630 (unknown)
    @     0x7f4a1f3c1387 __GI_raise
    @     0x7f4a1f3c2a78 __GI_abort
    @          0xa231add starrocks::failure_function()
    @         0x155bfaed google::LogMessage::Fail()
    @         0x155c1f5f google::LogMessage::SendToLog()
    @         0x155bf63e google::LogMessage::Flush()
    @         0x155c2569 google::LogMessageFatal::~LogMessageFatal()
    @         0x102271ef starrocks::Expr::prepare()
    @         0x1021b11c starrocks::ExprContext::prepare()
    @         0x10226e61 starrocks::Expr::prepare()
    @          0xbc13d24 starrocks::OlapTablePartitionParam::prepare()
    @          0xbc4ae69 starrocks::stream_load::OlapTableSink::prepare()
    @          0xcc4917b starrocks::pipeline::OlapTableSinkOperator::prepare()
    @          0xcfa5fef starrocks::pipeline::PipelineDriver::prepare()
    @          0xcb904fe _ZZN9starrocks8pipeline16FragmentExecutor7executeEPNS_7ExecEnvEENKUlRKSt10shared_ptrINS0_14PipelineDriverEEE0_clES8_
    @          0xcb97a36 _ZSt13__invoke_implIN9starrocks6StatusERZNS0_8pipeline16FragmentExecutor7executeEPNS0_7ExecEnvEEUlRKSt10shared_ptrINS2_14PipelineDriverEEE0_JSA_EET_St14__invoke_otherOT0_DpOT1_
    @          0xcb97658 _ZSt10__invoke_rIN9starrocks6StatusERZNS0_8pipeline16FragmentExecutor7executeEPNS0_7ExecEnvEEUlRKSt10shared_ptrINS2_14PipelineDriverEEE0_JSA_EENSt9enable_ifIX16is_invocable_r_vIT_T0_DpT1_EESE_E4typeEOSF_DpOSG_
    @          0xcb97133 _ZNSt17_Function_handlerIFN9starrocks6StatusERKSt10shared_ptrINS0_8pipeline14PipelineDriverEEEZNS3_16FragmentExecutor7executeEPNS0_7ExecEnvEEUlS7_E0_E9_M_invokeERKSt9_Any_dataS7_
    @          0xcfee1f3 std::function<>::operator()()
    @          0xcfe4ccc starrocks::pipeline::FragmentContext::iterate_drivers()
    @          0xcb907c2 starrocks::pipeline::FragmentExecutor::execute()
    @         0x13c7c1a5 starrocks::PInternalServiceImplBase<>::_exec_plan_fragment_by_pipeline()
    @         0x13c7bc46 starrocks::PInternalServiceImplBase<>::_exec_plan_fragment()
    @         0x13c74ce8 starrocks::PInternalServiceImplBase<>::_exec_plan_fragment()
    @         0x13c86bae _ZZN9starrocks24PInternalServiceImplBaseIN5doris15PBackendServiceEE18exec_plan_fragmentEPN6google8protobuf13RpcControllerEPKNS_24PExecPlanFragmentRequestEPNS_23PExecPlanFragmentResultEPNS5_7ClosureEENKUlvE_clEv
    @         0x13c9619a _ZSt13__invoke_implIvRZN9starrocks24PInternalServiceImplBaseIN5doris15PBackendServiceEE18exec_plan_fragmentEPN6google8protobuf13RpcControllerEPKNS0_24PExecPlanFragmentRequestEPNS0_23PExecPlanFragmentResultEPNS6_7ClosureEEUlvE_JEET_St14__invoke_otherOT0_DpOT1_
    @         0x13c93355 _ZSt10__invoke_rIvRZN9starrocks24PInternalServiceImplBaseIN5doris15PBackendServiceEE18exec_plan_fragmentEPN6google8protobuf13RpcControllerEPKNS0_24PExecPlanFragmentRequestEPNS0_23PExecPlanFragmentResultEPNS6_7ClosureEEUlvE_JEENSt9enable_ifIX16is_invocable_r_vIT_T0_DpT1_EESJ_E4typeEOSK_DpOSL_
    @         0x13c8ff46 _ZNSt17_Function_handlerIFvvEZN9starrocks24PInternalServiceImplBaseIN5doris15PBackendServiceEE18exec_plan_fragmentEPN6google8protobuf13RpcControllerEPKNS1_24PExecPlanFragmentRequestEPNS1_23PExecPlanFragmentResultEPNS7_7ClosureEEUlvE_E9_M_invokeERKSt9_Any_data
    @          0xa120ac6 std::function<>::operator()()
    @          0xa51e260 starrocks::PriorityThreadPool::work_thread()
```
F0913 07:23:04.308235  2777 expr.cpp:443] Check failed: _type.type != TYPE_UNKNOWN

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
commit e56cefde4575d9254e70702af6739d01bcddc33e (upstream/main, upstream/HEAD)
Author: stephen <91597003+stephen-shelby@users.noreply.github.com>
Date:   Mon Sep 18 21:22:14 2023 +0800
```

### PR DESCRIPTION
**Pull request by LiShuMing**
Fixes #31354
- Slot ref should be analyzed in ExpressionRangePartitionInfo in deserialize, otherwise, the type will be invalid

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.2
  - [x] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Review by Astralidea — APPROVED** [review]

**Review by murphyatwork — APPROVED** [review]

**Review by ABingHuang — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 12 / 15 (80.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/ExpressionRangePartitionInfo.java|12|15|80.00%|[104, 108, 109]|

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.2

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Pull request merged**
