### PR TITLE
[Enhancement] reduce disk cost of persistent index and do some refactoring (backport #31799)

### PR DESCRIPTION
**Pull request by luohaha**
backport #31799

This PR contains several enhancement about disk cost:
1. Not allow l0's memory size larger than index's total file size, because it is useless to improve IO, and it will also cost waste of disk.
2. Delete useless l2 files immediately after persistent meta info.
3. Allow major compaction when persistent index was expired.
4. re-calculate `_usage_and_size_by_key_length`, to make estimated file size more smaller.

And this PR also contains some refactoring:
1. Remove `PersistentIndexMetaLock`, use index lock in TabletUpdate instead.
2. Improve log print.

Fixes #issue

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 60 / 107 (56.07%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/storage/lake/lake_local_persistent_index.cpp|0|6|00.00%|[87, 88, 89, 297, 298, 299]|
|:large_blue_circle:|src/storage/persistent_index.cpp|44|76|57.89%|[339, 2419, 2423, 2424, 2425, 2426, 2427, 2428, 2429, 2431, 2433, 2434, 2435, 2436, 2437, 2438, 2439, 2440, 2442, 2450, 2721, 2722, 2723, 2960, 3025, 3489, 3519, 3599, 4044, 4412, 4413, 4415]|
|:large_blue_circle:|src/storage/tablet_updates.cpp|15|24|62.50%|[3805, 3806, 3807, 3808, 3809, 3810, 3811, 3812, 3814]|
|:large_blue_circle:|src/storage/persistent_index.h|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 60 / 108 (55.56%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/storage/lake/lake_local_persistent_index.cpp|0|6|00.00%|[87, 88, 89, 297, 298, 299]|
|:large_blue_circle:|src/storage/persistent_index.cpp|44|77|57.14%|[339, 2419, 2423, 2424, 2425, 2426, 2427, 2428, 2429, 2431, 2433, 2434, 2435, 2436, 2437, 2438, 2439, 2440, 2442, 2450, 2721, 2722, 2723, 2960, 3025, 3489, 3519, 3529, 3599, 4044, 4412, 4413, 4415]|
|:large_blue_circle:|src/storage/tablet_updates.cpp|15|24|62.50%|[3805, 3806, 3807, 3808, 3809, 3810, 3811, 3812, 3814]|
|:large_blue_circle:|src/storage/persistent_index.h|1|1|100.00%|[]|

**Review by chaoyli — APPROVED** [review]

**Pull request merged**
