### PR TITLE
[BugFix]when decimal as map's key type in parquet, the real type is FIXED_LEN_BYTE_ARRAY which is OPTIONAL

### LINKED ISSUE #14734: [HIVE-MAP] error from hive map when map[key] is decimal and hive table is parquet file format
### Steps to reproduce the behavior (Required)
```
mysql> select * from hdfs_parquet_gzip_map_decimal_date;
ERROR 1064 (HY000): key in map group must be required:file = hdfs://emr-header-1.cluster-49091:9000/user/hive/warehouse/hive_extbl_test_struct_map.db/hdfs_parquet_gzip_map_decimal_date/000000_0
mysql> desc hdfs_parquet_gzip_map_decimal_date;
+---------+---------------------------+------+-------+---------+-------+
| Field   | Type                      | Null | Key   | Default | Extra |
+---------+---------------------------+------+-------+---------+-------+
| col_int | INT                       | Yes  | false | NULL    |       |
| col_map | MAP<DECIMAL64(10,5),DATE> | Yes  | false | NULL    |       |
+---------+---------------------------+------+-------+---------+-------+
2 rows in set (0.00 sec)
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
mysql> select current_version();
+----------------------------+
| current_version()          |
+----------------------------+
| BRANCH-2.5-RELEASE 868c482 |
+----------------------------+
1 row in set (0.00 sec)
```

### PR DESCRIPTION
**Pull request by zombee0**
截屏2022-12-07 08 24 47

it is similar to pr https://github.com/StarRocks/starrocks/pull/12921
Signed-off-by: zombee0 <flylucas_10@163.com>

## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #14734 

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Review by DorianZheng — APPROVED** [review]

**Review by dirtysalt — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by Youngwb — APPROVED** [review]

**Comment by zombee0** [comment]
run starrocks_admit_test

**Comment by zombee0** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
