### PR TITLE
[Feature] Support materialized view for partitioned iceberg table

### PR DESCRIPTION
**Pull request by Youngwb**
## What type of PR is this：
- [ ] BugFix
- [x] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

#11116 

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 25 / 95 (26.32%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/connector/iceberg/IcebergConnector.java|0|3|00.00%|[31, 32, 35]|
|:large_blue_circle:|com/starrocks/catalog/IcebergPartitionKey.java|0|3|00.00%|[7, 8, 12]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/RemoteScanPartitionPruneRule.java|0|1|00.00%|[102]|
|:large_blue_circle:|com/starrocks/external/PartitionUtil.java|7|31|22.58%|[57, 58, 60, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 136, 147, 148, 149, 154]|
|:large_blue_circle:|com/starrocks/scheduler/PartitionBasedMaterializedViewRefreshProcessor.java|6|25|24.00%|[164, 165, 213, 214, 265, 519, 527, 528, 529, 530, 533, 534, 535, 536, 537, 538, 539, 540, 541]|
|:large_blue_circle:|com/starrocks/external/iceberg/IcebergUtil.java|2|6|33.33%|[186, 189, 203, 204]|
|:large_blue_circle:|com/starrocks/connector/iceberg/IcebergMetadata.java|5|13|38.46%|[48, 49, 50, 53, 57, 89, 107, 108]|
|:large_blue_circle:|com/starrocks/catalog/IcebergTable.java|5|13|38.46%|[95, 107, 108, 109, 110, 114, 131, 174]|

**Comment by Youngwb** [comment]
run starrocks_be_unittest

**Comment by Youngwb** [comment]
run starrocks_be_unittest

**Review by Astralidea — DISMISSED** [review]

**Review by Astralidea — APPROVED** [review]

**Review by stephen-shelby — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by gengjun-git — APPROVED** [review]

**Pull request merged**
