### PR TITLE
[BugFix] fix lambdaFunctionExpr's clone bug

### PR DESCRIPTION
**Pull request by fzhedu**
Cloning agg's sub expressions expose this bug.
```
mysql>  explain SELECT max(g) FROM(SELECT array_sum(array_map(x -> ((x * x) + (x * b)), a)) AS g FROM (SELECT [1,2] a, 1 AS b) AS A) AS B;
+---------------------------------------------------------------------------------------------------------------------------------+
| Explain String                                                                                                                  |
+---------------------------------------------------------------------------------------------------------------------------------+
| PLAN FRAGMENT 0                                                                                                                 |
|  OUTPUT EXPRS:6: max                                                                                                            |
|   PARTITION: UNPARTITIONED                                                                                                      |
|                                                                                                                                 |
|   RESULT SINK                                                                                                                   |
|                                                                                                                                 |
|   1:AGGREGATE (update finalize)                                                                                                 |
|   |  output: max(array_sum(array_map(<slot 4> -> CAST(<slot 8> * <slot 8> AS INT) + CAST(<slot 8> * CAST(1 AS SMALLINT) AS INT) |
|         lambda common expressions:{<slot 8> <-> CAST(<slot 4> AS SMALLINT)}                                                     |
|         , [1,2])))                                                                                                              |
|   |  group by:                                                                                                                  |
|   |                                                                                                                             |
|   0:UNION                                                                                                                       |
|      constant exprs:                                                                                                            |
|          NULL                                                                                                                   |
+---------------------------------------------------------------------------------------------------------------------------------+
```
wrong cases
```
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Explain String                                                                                                                                                                    |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| PLAN FRAGMENT 0                                                                                                                                                                   |
|  OUTPUT EXPRS:6: max                                                                                                                                                              |
|   PARTITION: UNPARTITIONED                                                                                                                                                        |
|                                                                                                                                                                                   |
|   RESULT SINK                                                                                                                                                                     |
|                                                                                                                                                                                   |
|   1:AGGREGATE (update finalize)                                                                                                                                                   |
|   |  output: max(array_sum(array_map((<slot 4>, <slot 8>, CAST(<slot 4> AS SMALLINT)) -> CAST(<slot 8> * <slot 8> AS INT) + CAST(<slot 8> * CAST(1 AS SMALLINT) AS INT), [1,2]))) |
|   |  group by:                                                                                                                                                                    |
|   |                                                                                                                                                                               |
|   0:UNION                                                                                                                                                                         |
|      constant exprs:                                                                                                                                                              |
|          NULL                                                                                                                                                                     |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.2
  - [x] 3.1
  - [x] 3.0
  - [ ] 2.5

### CODE REVIEW

**Review by packy92 — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/ast/LambdaFunctionExpr.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 11 / 11 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/ast/LambdaFunctionExpr.java|9|9|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/plan/ScalarOperatorToExpr.java|2|2|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 11 / 11 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/ast/LambdaFunctionExpr.java|9|9|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/plan/ScalarOperatorToExpr.java|2|2|100.00%|[]|

**Review by packy92 — APPROVED** [review]

**Review by Seaven — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.2

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Pull request merged**
