### PR TITLE
[Enhancement] Simplify date/datetime column predicate in certain cases

### PR DESCRIPTION
**Pull request by kaijianding**
## Why I'm doing:
Some user use `date/datetime` column as string, in this case sparse index is not used.
This pr will do these rewrite
```sql
 --if t is date
 date_format(t, '%Y%m%d') >= '20230327' -> `t` >= '20230327'
 date_format(t, '%Y-%m-%d') >= '2023-03-27' -> `t` >= '2023-03-27'
 substr(t, 1, 10) >= '2023-03-27' -> `t` >= '2023-03-27'
 substring(t, 1, 10) >= '2023-03-27' -> `t` >= '2023-03-27'
 replace(substring(t, 1, 10), "-", "") >= '20230327' -> `t` >= '20230327'
 
 --if t is datetime
 date_format(t, '%Y-%m-%d') >/>=/< '2023-03-27' -> `t` >/>=/< '2023-03-27'
 date_format(t, '%Y-%m-%d') <= '2023-03-27' -> `t` < days_add('2023-03-27', 1)
```
## What I'm doing:

Fixes #issue

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.3
  - [ ] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Comment by packy92** [comment]
please test  date_format(t, '%Y%m%d') >= '20230400'. If the right constant value is a illegal date string, is the rewriten result same with before?

**Comment by kaijianding** [comment]
> please test date_format(t, '%Y%m%d') >= '20230400'. If the right constant value is a illegal date string, is the rewriten result same with before?

`PREDICATES: date_format(2: pt, '%Y%m%d') >= '2023030700'` is the result, no rewritten.

But I will use regex to verify the right constant.

**Comment by packy92** [comment]
> > please test date_format(t, '%Y%m%d') >= '20230400'. If the right constant value is a illegal date string, is the rewriten result same with before?
> 
> `PREDICATES: date_format(2: t, '%Y%m%d') >= '2023030700'` is the result, no rewritten.
> 
> But I will use regex to verify the right constant.

I means clients may use `20230400` as the right constant value,  this value seems to pass the regex check. But it's not a valid date value. Does the rule will rewrite it to dt >= cast('20230400' as date) ? If yes, the right cast returns a null may cause different behavior from before.

**Comment by kaijianding** [comment]
@packy92 U r right, if right constant is not valid date, the result is not consitent with that before rewrite. I will verify the right constant is valid date

**Comment by kaijianding** [comment]
@packy92 any more comment?

**Review by Seaven — APPROVED** [review]

**Review by kangkaisen — APPROVED** [review]

**Pull request merged**
