### PR TITLE
[BugFix] Fix get db unknown error when not using db

### LINKED ISSUE #9215: select query_id unknown error
### Steps to reproduce the behavior (Required)
select query_id()

### Expected behavior (Required)
No matching function with signature: query_id()

### Real behavior (Required)
unknown error

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by Youngwb**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #9215

### CODE REVIEW

**Review by gengjun-git — APPROVED** [review]

**Review by kangkaisen — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by Youngwb** [comment]
run starrocks_fe_unittest

**Comment by imay** [comment]
@Youngwb why select query_id() would call getDb function?

**Comment by Youngwb** [comment]
> @Youngwb why select query_id() would call getDb function?

This function is not builtin funtion, try to find as udf function(getUdfFunction), which will call getDb function.

**Comment by Youngwb** [comment]
run starrocks_fe_unittest

**Pull request merged**
