### PR TITLE
add java format style

### PR DESCRIPTION
**Pull request by ucasfl**
## What type of PR is this：
- [ ] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [x] others

## Which issues of this PR fixes ：
Add java style in .clang-format to avoid format error when writing java code:
image

### CODE REVIEW

**Comment by imay** [comment]
@ucasfl  How to use this feature? After this is merged, I can format java code by executing ./build-support/clang-format.sh?

**Comment by ucasfl** [comment]
> @ucasfl How to use this feature? After this is merged, I can format java code by executing ./build-support/clang-format.sh?

I didn't notice this script, just my editor can format code automatically with this config and clang-format when writing code.

**Comment by imay** [comment]
> > @ucasfl How to use this feature? After this is merged, I can format java code by executing ./build-support/clang-format.sh?
> 
> 
> 
> I didn't notice this script, just my editor can format code automatically with this config and clang-format when writing code.

What editor do you use?

**Comment by ucasfl** [comment]
> > > @ucasfl How to use this feature? After this is merged, I can format java code by executing ./build-support/clang-format.sh?
> > 
> > 
> > I didn't notice this script, just my editor can format code automatically with this config and clang-format when writing code.
> 
> What editor do you use?

vim with releated plugin.

**Review by imay — APPROVED** [review]

**Pull request merged**
