### PR TITLE
[Feature] change file table function name to FILES()

### PR DESCRIPTION
**Pull request by rickif**
Fixes #issue

## What type of PR is this:
- [ ] BugFix
- [x] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

```
> select * from FILES("path" = "s3://xxx/student1.parquet",      "format" = "parquet",   "aws.s3.access_key" = "xxx",     "aws.s3.secret_key" = "xxx",     "aws.s3.region" = "us-west-2");
+----------+------+
| name     | age  |
+----------+------+
| mark835  |   28 |
| jack611  |    9 |
| alice335 |   21 |
| jack1004 |   30 |
| rose800  |   20 |
| mark1021 |   14 |
| rose305  |   27 |
| alice387 |   37 |
| rose312  |   10 |
| jack841  |   22 |
+----------+------+
10 rows in set (4.558 sec)

```
This PR changes the file table function name to `FILES()`.

## Checklist:
- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by meegoo — APPROVED** [review]

**Review by chaoyli — APPROVED** [review]

**Comment by rickif** [comment]
@mergifyio backport branch-3.1

**Pull request merged**
