### PR TITLE
[BugFix] Fix the thrift library conflict in some cases by linking the required cachelib dependencies statically

### PR DESCRIPTION
**Pull request by GavinMar**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

When linking the cachelib dynamically by `find_package`,  all related libraries will be linked.  While some of them are not required in our usage scenarios, and even lead to dependency conflicts in some environments.

So, we choose to only link the required cachelib dependencies statically to avoid unnecessary conflicts. Also, with this change, it is no need to package lots of dynamic libraries in our be output.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by GavinMar** [comment]
run starrocks_admit_test image

**Comment by GavinMar** [comment]
run starrocks_admit_test image

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by GavinMar** [comment]
run starrocks_be_unittest

**Comment by GavinMar** [comment]
run starrocks_admit_test

**Review by dirtysalt — APPROVED** [review]

**Comment by GavinMar** [comment]
run starrocks_fe_unittest

**Comment by dirtysalt** [comment]
run starrocks_fe_unittest

**Review by stephen-shelby — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by bigsusu123** [comment]
hi @GavinMar 

I'm trying to customize a cachelib for our own purpose, but not knowing how to build a static cachelib so that it can still integrate into SR.

I'm using this version of cachelib: https://github.com/facebook/CacheLib/releases/tag/v2023.01.30.00, 
and adding -DBUILD_SHARED_LIBS=OFF in contrib/build-package.sh to change default dynamic lib to static lib.
But I find the outcome .a files are significantly smaller than in https://cdn-thirdparty.starrocks.com/cachelib/cachelib-20230130.tar.gz:

my libs: 

libcachelib_allocator.a 48M
libcachelib_common.a 4.4M

cdn-thirdparty:

libcachelib_allocator.a 170M
libcachelib_common.a 17M

am I doing it correctly ? can you please share some notes on how to build the cachelib?






can you pleas

**Comment by GavinMar** [comment]
> hi @GavinMar
> 
> I'm trying to customize a cachelib for our own purpose, but not knowing how to build a static cachelib so that it can still integrate into SR.
> 
> I'm using this version of cachelib: https://github.com/facebook/CacheLib/releases/tag/v2023.01.30.00, and adding -DBUILD_SHARED_LIBS=OFF in contrib/build-package.sh to change default dynamic lib to static lib. But I find the outcome .a files are significantly smaller than in https://cdn-thirdparty.starrocks.com/cachelib/cachelib-20230130.tar.gz:
> 
> my libs:
> 
> libcachelib_allocator.a 48M libcachelib_common.a 4.4M
> 
> cdn-thirdparty:
> 
> libcachelib_allocator.a 170M libcachelib_common.a 17M
> 
> am I doing it correctly ? can you please share some notes on how to build the cachelib?
> 
> thanks!



>  Yes, I also built cachelib by adding DBUILD_SHARED_LIBS=OFF in contrib/build-package.sh. I'm not quite sure why your output is so much smaller than mine because you choose a newer cachelib version. So, if you could build all libraries successfully, I think you can try to integrate it into SR and check whether the block cache can work as expected.

**Comment by bigsusu123** [comment]
hi @GavinMar  

thanks for the reply. 
may i know which cachelib version did you use?

**Comment by GavinMar** [comment]
> hi @GavinMar
> 
> thanks for the reply. may i know which cachelib version did you use?

I used the version v2023.01.23 and I think your version is also ok. And you'd better build the cachelib with the same toolkits, such as g++ version, to avoid some abi compatibility problems.

**Comment by bigsusu123** [comment]
thank you so much for the tips! I'll give another shot

**Pull request merged**
