### PR TITLE
[Refactor][meta-format-change] Change colocate table index to json format

### PR DESCRIPTION
**Pull request by gengjun-git**
Fixes #issue

## What type of PR is this:
- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 30 / 38 (78.95%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|0|2|00.00%|[1425, 1429]|
|:large_blue_circle:|com/starrocks/journal/JournalEntity.java|0|6|00.00%|[517, 518, 519, 528, 529, 530]|
|:large_blue_circle:|com/starrocks/catalog/ColocateGroupSchema.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/ColocateTableIndex.java|23|23|100.00%|[]|
|:large_blue_circle:|com/starrocks/persist/ColocatePersistInfo.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/persist/EditLog.java|5|5|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 29 / 37 (78.38%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|0|2|00.00%|[1425, 1429]|
|:large_blue_circle:|com/starrocks/journal/JournalEntity.java|0|6|00.00%|[517, 518, 519, 528, 529, 530]|
|:large_blue_circle:|com/starrocks/catalog/ColocateGroupSchema.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/ColocateTableIndex.java|22|22|100.00%|[]|
|:large_blue_circle:|com/starrocks/persist/ColocatePersistInfo.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/persist/EditLog.java|5|5|100.00%|[]|

**Review by HangyuanLiu — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 29 / 37 (78.38%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|0|2|00.00%|[1429, 1434]|
|:large_blue_circle:|com/starrocks/journal/JournalEntity.java|0|6|00.00%|[536, 537, 538, 547, 548, 549]|
|:large_blue_circle:|com/starrocks/catalog/ColocateGroupSchema.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/ColocateTableIndex.java|22|22|100.00%|[]|
|:large_blue_circle:|com/starrocks/persist/ColocatePersistInfo.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/persist/EditLog.java|5|5|100.00%|[]|

**Comment by gengjun-git** [comment]
@mergifyio rebase

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 29 / 37 (78.38%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|0|2|00.00%|[1429, 1434]|
|:large_blue_circle:|com/starrocks/journal/JournalEntity.java|0|6|00.00%|[536, 537, 538, 547, 548, 549]|
|:large_blue_circle:|com/starrocks/catalog/ColocateGroupSchema.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/ColocateTableIndex.java|22|22|100.00%|[]|
|:large_blue_circle:|com/starrocks/persist/ColocatePersistInfo.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/persist/EditLog.java|5|5|100.00%|[]|

**Review by HangyuanLiu — APPROVED** [review]

**Review by nshangyiming — APPROVED** [review]

**Pull request merged**
