### PR TITLE
[Doc] Fix the numeric range description in the documentation for array_to_b…

### PR DESCRIPTION
**Pull request by MrLevo520**
…itmap and bitmap_from_string functions.

In the bitmap_from_string function of StarRocks, the documentation description and code implementation are inconsistent
same problem as array_to_bitmap

Fixes #issue

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [x] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.2
  - [x] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Comment by imay** [comment]
@MrLevo520 can you sign the CLA, then we can accept your contribution

**Comment by MrLevo520** [comment]
> @MrLevo520 can you sign the CLA, then we can accept your contribution

sry,  done

**Review by evelynzhaojie — APPROVED** [review]

**Review by evelynzhaojie — APPROVED** [review]

**Comment by evelynzhaojie** [comment]
@kangkaisen pls review the code

**Review by kangkaisen — APPROVED** [review]

**Comment by andyziye** [comment]
@Mergify rebase

**Comment by evelynzhaojie** [comment]
@mergify backport branch-3.3

**Comment by evelynzhaojie** [comment]
@mergify backport branch-2.5

**Pull request merged**
