### PR TITLE
[BugFix] json stream load failed with Transfer-Encoding: chunked set

### LINKED ISSUE #5327: json stream load failed when `Transfer-Encoding: chunked` is set
### Steps to reproduce the behavior (Required)
1. create table
```
CREATE TABLE `student` (
  `id` int(11) NOT NULL COMMENT "",
  `name` varchar(65533) NULL COMMENT "",
  `address` varchar(65533) NULL COMMENT "",
  `city` varchar(65533) NULL COMMENT ""
) ENGINE=OLAP 
DUPLICATE KEY(`id`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`id`) BUCKETS 10 
PROPERTIES (
"replication_num" = "3",
"in_memory" = "false",
"storage_format" = "DEFAULT"
);
```
2. do stream load with `Transfer-Encoding: chunked`
```
 curl --location-trusted -u root:  'http://127.0.0.1:8082/api/db0/student/_stream_load' \-X PUT \-H 'table-name: student' \-H 'strip_outer_array: true' \-H 'format: json' \-H 'Transfer-Encoding: chunked' \-H 'Host: 127.0.0.1:8045' \-H 'Connection: Keep-Alive' \-H 'User-Agent: Apache-HttpClient/4.5.13 (Java/11.0.14)' \-d '[{"address":"UjDPeZkYchsE","city":"jYJTYTIBJzgW","id":77887,"name":"vhsT9xgVS7MO"},{"address":"oOKmiqVGmcXe","city":"C3sCmuzYKtls","id":76072,"name":"D9K6zIG9p3As"},{"address":"2LVCgicZdoH1","city":"yKec2oEOgZAy","id":77167,"name":"TqWjAQqQ5YNS"},{"address":"MSqB6d5oG5cE","city":"QdGEwXCGreN8","id":78983,"name":"eppeircYHSqc"},{"address":"4rFvTBq5evta","city":"sdLnhpr0CHKR","id":74189,"name":"7Mbl9j4ARWHp"},{"address":"kWSXhkWL8pfo","city":"MuMrs1Or9zaO","id":70132,"name":"KicIh94QJEY5"},{"address":"czKPPfbKMH8M","city":"TyCHKYqdmXI9","id":77028,"name":"dDhD3hBCHzk3"},{"address":"DYR3xADARcZd","city":"u3UFux9xUfZZ","id":71485,"name":"BYqYNlefXy1X"},{"address":"3p52gFrRPNxb","city":"x4UCbDdQk0TH","id":73175,"name":"7Pcs9rJvs2qZ"},{"address":"MXkQafjkKq2w","city":"F3ugvFyUvzWC","id":71912,"name":"jzOE8t3uRtOq"}]'

```

### Expected behavior (Required)
succeeded to load data.
### Real behavior (Required)
```
{
    "TxnId": 130867,
    "Label": "444c22d9-b6e1-4117-85ec-8d0e9c8a48a0",
    "Status": "Fail",
    "Message": "all partitions have no load data",
    "NumberTotalRows": 0,
    "NumberLoadedRows": 0,
    "NumberFilteredRows": 0,
    "NumberUnselectedRows": 0,
    "LoadBytes": 0,
    "LoadTimeMs": 6607,
    "BeginTxnTimeMs": 0,
    "StreamLoadPutTimeMs": 0,
    "ReadDataTimeMs": 0,
    "WriteDataTimeMs": 203,
    "CommitAndPublishTimeMs": 0
}
```
### StarRocks version (Required)
main, branch-2.2, branch-2.1, branch-2.0

### PR DESCRIPTION
**Pull request by rickif**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] others

## Which issues of this PR fixes ：

Fixes #5327 

## Problem Summary(Required) ：

When `Transfer-Encoding: chunked` is set, the content of HTTP body cannot be known from HTTP header `Content-Length`.
However, the previous implement of `StreamLoadPipe` need the http body size for initializing `_total_length`, and the `StreamLoadPipe:read_one_message` also needs `_total_length`.

This PR includes the following modifications:
1. remove the `StreamLoadPipe`'s dependency on HTTP body size as the initial size
2. redefine the semantics of `StreamLoadPipe:read_one_message` as `returns data that is written by append in one time`
3. new unit tests for `StreamLoadPipe:read_one_message`

The `StreamLoadPipe` is a pipe to store data from stream load. Every time we use `StreamLoadPipe::append` for JSON, we must append a complete JSON payload. So, it's OK to parse the data as JSON returned by  `StreamLoadPipe:read_one_message`.

### CODE REVIEW

**Comment by rickif** [comment]
run starrocks_be_unittest

**Review by sduzh — APPROVED** [review]

**Review by chaoyli — APPROVED** [review]

**Comment by rickif** [comment]
@mergifyio backport branch-2.2

**Comment by rickif** [comment]
@mergifyio backport branch-2.1

**Comment by rickif** [comment]
This may leads chunked json parsing failure. Since `Transfer-Encoding: chunked` is not released now, I have reverted this PR on branch-2.1/branch-2.2. The fix will be done at branch main later.

**Pull request merged**
