### PR TITLE
OSS file shoud split by object storage file size

### PR DESCRIPTION
**Pull request by caneGuy**
Since OSS file also use default blocklocation which use full file size, so we should split it like s3 files for performance consideration

### CODE REVIEW

**Comment by caneGuy** [comment]
cc @wyb @gengjun-git could you help review this pr? thanks

**Comment by imay** [comment]
> cc @wyb @gengjun-git could you help review this pr? thanks

StarRocks now supports some kinds of Object Service, such as OSS, COS.
I think it is better to create a class to manage all this supported object service.
For this case, this class can support an interface to tell if this service is supported.

**Comment by caneGuy** [comment]
> > cc @wyb @gengjun-git could you help review this pr? thanks
> 
> StarRocks now supports some kinds of Object Service, such as OSS, COS. I think it is better to create a class to manage all this supported object service. For this case, this class can support an interface to tell if this service is supported.

+1, i will refactor this pr

**Review by imay — APPROVED** [review]

**Comment by gengjun-git** [comment]
After this PR https://github.com/StarRocks/starrocks/pull/1173 is merged, there is no need to split the block according to the scheme type.

**Comment by caneGuy** [comment]
> After this PR #1173 is merged, there is no need to split the block according to the scheme type.

+1, but i think the 'objectstorageutils' class can keep? @gengjun-git

**Review by gengjun-git — APPROVED** [review]

**Pull request merged**
