### PR TITLE
[BugFix] fix visitor cannot process case when operator

### LINKED ISSUE #15631: [sqlancer] unknown error
### Steps to reproduce the behavior (Required)
```
DROP DATABASE IF EXISTS n10;
CREATE DATABASE n10;
USE n10;
admin set frontend config ("enable_decimal_v3" = "true");
CREATE TABLE t0 (c_0_0 DATE NULL ,c_0_1 PERCENTILE PERCENTILE_UNION NOT NULL ,c_0_2 FLOAT MIN NULL ,c_0_3 SMALLINT MIN NOT NULL ,c_0_4 BIGINT MIN NOT NULL ) AGGREGATE KEY (c_0_0) PARTITION BY RANGE(c_0_0) (START ("2010-01-01") END ("2022-12-31") EVERY (INTERVAL 215 day)) DISTRIBUTED BY HASH (c_0_0) BUCKETS 3 properties("replication_num"="3") ;
CREATE TABLE IF NOT EXISTS t1 (c_1_0 VARCHAR(21) NOT NULL,c_1_1 DATETIME NOT NULL,c_1_2 BOOLEAN NOT NULL,c_1_3 TINYINT NOT NULL,c_1_4 VARCHAR(31) NOT NULL,c_1_5 BIGINT NOT NULL,c_1_6 ARRAY<INT> NOT NULL,c_1_7 ARRAY<STRING> NOT NULL,c_1_8 INT NOT NULL,c_1_9 TINYINT NOT NULL,c_1_10 BOOLEAN NOT NULL,c_1_11 ARRAY<INT> NOT NULL) PRIMARY KEY (c_1_0,c_1_1,c_1_2,c_1_3,c_1_4,c_1_5) PARTITION BY RANGE(c_1_1) (START ("2010-01-01") END ("2022-12-31") EVERY (INTERVAL 175 day)) DISTRIBUTED BY HASH (c_1_4,c_1_3,c_1_1,c_1_5,c_1_0,c_1_2) BUCKETS 3 properties("replication_num"="3") ;
INSERT INTO t1 VALUES ('etzuLUe6k', '2010-01-03 08:00:14', false, 7, 'M', 111446386, [], ["", "It3vSqt", "9Hlg0iZ0", "q0", "BH"], 23, 4, false, [111446386, 111446386, 111446386, 110778961, 542715837, 542715837, 754247407, -1652495381, 954079392, -1230982208]), ('B', '2010-01-21 08:00:14', true, 0, 'mPUCtG35K', 954079392, [110778961, 542715837, -1009537920, -1808477302, 111446386, -1230982208, -411288191, -1375098288, 542715837, 111446386, -1230982208, 754247407, 1778543971, 185872525], ["", "Pa", "mP", "JnPr6PHh", "La", "IwlHj9cv", "YG3", "bUs", "8", "FRTC"], 16, 7, false, [567523346, 594272708, -1009537920, -411288191, 1903062711, -1216213480, -1077269220, 81752474]), ('Pkug9', '2010-01-09 08:00:14', true, 4, 'ume', -1111169506, [-2015288686], ["", "Inv", "UQCeu75", "pJZ8vZs", "t", "D", "hZjFvtA5Q", "rapTVl", "", "R", "U6", "d", ""], 21, 3, false, []);
INSERT INTO t0 VALUES ('2010-01-01', percentile_hash('1994104403'), 0.246107408548369, 5, -1683495222), ('2010-01-17', percentile_hash('594272708'), 0.5211458037672304, 9, -56710038), ('2010-01-21', percentile_hash('1402985176'), 1.903062711E9, 8, -1493483904);
INSERT INTO t1 VALUES ('', '2010-01-14 08:00:14', true, 1, '2w', -1652495381, [-1652495381, 1185917524, -1116297703, -1948010082, -1794171454, -1652495381, 1318077459, 2089654360, -919616763, -16412529], ["", "", "u", "kXAxDCEAP", "3H", "JdALAf", "6tOCJUCfe", "sZ", "", "", "M", "u", "oBqDO", "QiEe"], 14, 3, false, [865104132, 169140312, 567523346, -1343877680, -1867598444, -863911642, -881034620, 805703203, -267407033, 1929402771, 1626069475, 1499363417]);
INSERT INTO t0 VALUES ('2010-01-01', percentile_hash('-1897854485'), NULL, 9, 1345670670);
INSERT INTO t1 VALUES ('WIsamotFU', '2010-01-26 08:00:14', true, 1, 'RUJLB', -1652495381, [1365343083, -33701742, 185872525, -924328732, 321814802, 567523346, 562083189], ["0", "icSKL9", "", "", "IE0uO", "", "z", "LH0", "gj1cnYJg", "", "E", "UJt878Av", "AJ", "L"], 13, 3, false, [737191119, 749662580, -9223372036854775808, 1929402771, 439199131, -1413572576, 1691818492, -24852567, -1683495222, -2081270439, -2065313007, 468404554, 1499363417]), ('9o', '2010-01-07 08:00:14', true, 0, 'upxVPbE', -1230982208, [-66233661, 648688161, 377831955, -2073201127, 81752474, 1163678871, 634310646, 98094951, -33701742, 1, -1375098288, -1778063436], ["", "IIbiKEeD", "", "", "YG", "Y", "46", "SI", "j", "", "GosFwUG", "OE3KpKr"], 21, 5, false, []);
INSERT INTO t1 VALUES ('QmA', '2010-01-18 08:00:14', true, 4, 'K', -1872545511, [], ["HiKh4", "9", "G70Ci", "Yi2", "9", "5A", "F", "j5gRC", "P4bHAic5", "e", "Nxvpch4d", "am", "8Zm"], 5, 1, false, [-56710038, -362392360, 983422358]), ('t', '2010-01-01 08:00:14', false, 0, 'fj', 185872525, [-1375098288, 1140331862, -1037952605, -28433894, 1994104403, -1778063436, -1, 1614556363, 787074343, 48446129, 1365343083, -1948010082], ["wZN", "OaqxcZRB"], 24, 4, false, [805703203, 594272708, 676353621, -881034620, 310755293, -28433894, 1345670670, 1130670377, 9223372036854775807, 1283075306, 537111947]);
INSERT INTO t1 VALUES ('QHAHq', '2010-01-27 08:00:14', true, 2, 'c0', -807710395, [809103681], ["p", "iK", "bvT3uDFqy", "", "", "JR2bz2LR", "m7yGTp", "JjSZvr9", "CQM8mM", "kN", ""], 8, 7, true, [1635764074, -478839292]), ('PC', '2010-01-03 08:00:14', true, 5, '', 731573410, [], ["q", "M", "9", "NL", "d", "", "", "29"], 13, 6, false, [-1116297703, 699105481, -1065007870, 803704226, 462032736, -735263759, 1626069475, -1077269220, -1116297703, 1119440793]);
INSERT INTO t1 VALUES ('G', '2010-01-09 08:00:14', true, 6, '7l', 47883425, [1584589056, 983422358, -1762813208, 1341415475, -924328732, -1825937796, -1847285885], ["GPgT5UFhO", "", "zi", "bDtktN5I", "TP2VoYY", "gmK1U3YK"], 25, 4, false, [1281077557, 1283075306, -1254855018, 1471911, 185068699]), ('v', '2010-01-21 08:00:14', false, 4, '', 1785669788, [-28433894, -864032050, -1441943768, -268906654, 98094951, 1209803455, -895108223, -1884145370, 1119440793, 171432785, 517954631, -411288191, -203154693], ["i"], 2, 4, true, []);
INSERT INTO t1 VALUES ('X', '2010-01-04 08:00:14', false, 6, '55', -2109094193, [-1530124652, 537111947, 618187608], ["e", "e14", "R6", "", "", "wBAsD", "tKIBra3vS", "A", "R", "Qw", "i", "", "uvQ", ""], 13, 7, false, [502110049, -1343877680, 1559134250, 480949407, -1903431098, -139428332, -1645126661, 120593480, -706110644, -1230982208, -45452908, -1506617060, -1358321256]);
INSERT INTO t0 VALUES ('2010-01-10', percentile_hash('1031730840'), 0.5738164880582219, 9, -2015288686), ('2010-01-09', percentile_hash('-1230982208'), 0.37425521055815714, 14, 407378198), ('2010-01-26', percentile_hash('-903895007'), 8.05703203E8, 8, 1626069475), ('2010-01-27', percentile_hash('-736966254'), 0.9766966398468027, 5, 995341663);
INSERT INTO t0 VALUES ('2010-01-15', percentile_hash('369380707'), 0.9766966398468027, 11, -1903179157), ('2010-01-13', percentile_hash('2051376949'), 0.0987117594394995, 12, 1318077459), ('2010-01-15', percentile_hash('-2015288686'), 0.48866602452421437, 15, 1109536752);
INSERT INTO t0 VALUES ('2010-01-26', percentile_hash('304991168'), 0.38008885032222006, 1, 1567658045), ('2010-01-14', percentile_hash('2133835127'), 0.5211458037672304, 13, 911817379), ('2010-01-14', percentile_hash('-357857431'), -3.3701742E7, 7, 462032736);
INSERT INTO t0 VALUES (NULL, percentile_hash('-1762813208'), 0.27376983323793425, 10, -2064030234), ('2010-01-09', percentile_hash('405604996'), 0.9450880895551899, 6, 1691818492);
INSERT INTO t0 VALUES ('2010-01-08', percentile_hash('-883430479'), 0.6628023376865484, 10, -113222145);
INSERT INTO t1 VALUES ('zO', '2010-01-13 08:00:14', true, 6, '', -923550811, [787074343, -1111169506, 1635764074, -689364533], ["kIG", "", "f4IOcQJ", "Mf", "lNTmFmHX"], 23, 0, false, [1651627312, -715771931, -33701742, -1343877680, 634310646, -1976115337]), ('B5gi', '2010-01-20 08:00:14', true, 5, 'tbgA', 2093550627, [-614561010, 983422358, -1563720418, 98094951, 1506051624, -261530502, 737191119, -1009537920, -66233661, -1294357063, 460447617, 305926784], ["LI2", "PFU", "zVP", "eB39e", "eqYtM", "7", "", "", "O", "UNTZR4", "qecz32", "7rt", "lr"], 3, 6, false, [-1541022080, -1475691874, -1975653862, 737191119, -880816703, 542715837, 1795293727]), ('HvyhgUK', '2010-01-10 08:00:14', true, 0, 'X0eoDcpu', -863911642, [1902743677, 763045522, 954079392, 1691818492, -1926747024, 930597573, 511730576, 809103681, 676353621, 1871267495], ["grTC", "Hq"], 30, 3, true, [-979268691, -1111169506, -627958529, 1916303112, 1758738044, -1281652733, 1341415475, 1170766396, -924328732, -914971347]);
INSERT INTO t1 VALUES ('N', '2010-01-20 08:00:14', true, 4, 'q8', -24852567, [620944798], ["", "", "xvv8", "tgc1N", "GBk", "", "It", "So3ZPh"], 8, 3, false, [-1493904217, 674327998, -2081270439, -1593176140, -1024008967]);

WITH with_t_0 as (SELECT t0_140.c_0_0, t0_140.c_0_2, t0_140.c_0_3, t0_140.c_0_4 FROM t0 AS t0_140) , with_t_1 as (SELECT t0_140.c_0_0, t0_140.c_0_2, t0_140.c_0_3, t0_140.c_0_4 FROM t0 AS t0_140) SELECT COUNT(*) FROM t0 AS t0_140, with_t_0 AS with_t_0, with_t_1 AS with_t_1 WHERE  ( (SELECT t1_141.c_1_0 FROM t1 AS t1_141 WHERE true)  ) < ( (SELECT t1_141.c_1_0 FROM t1 AS t1_141 WHERE (CASE  WHEN (NOT ((t1_141.c_1_9) IN (561376651, -1025981074) )) THEN t0_140.c_0_0  WHEN ENDS_WITH('', 'ha')  THEN t0_140.c_0_0 END) IN ('1969-12-20') )  ) ;


```
```
fe.log:
java.lang.IllegalStateException: null
        at com.google.common.base.Preconditions.checkState(Preconditions.java:494) ~[spark-dpp-1.0.0.jar:?]
        at com.starrocks.sql.optimizer.operator.scalar.CaseWhenOperator.getElseClause(CaseWhenOperator.java:87) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.rewrite.BaseScalarOperatorShuttle.visitCaseWhenOperator(BaseScalarOperatorShuttle.java:201) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.rewrite.CorrelatedPredicateRewriter.visitCaseWhenOperator(CorrelatedPredicateRewriter.java:92) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.rewrite.CorrelatedPredicateRewriter.visitCaseWhenOperator(CorrelatedPredicateRewriter.java:29) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.operator.scalar.CaseWhenOperator.accept(CaseWhenOperator.java:199) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.rewrite.BaseScalarOperatorShuttle.visitList(BaseScalarOperatorShuttle.java:217) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.rewrite.BaseScalarOperatorShuttle.visitBinaryPredicate(BaseScalarOperatorShuttle.java:111) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.rewrite.BaseScalarOperatorShuttle.visitBinaryPredicate(BaseScalarOperatorShuttle.java:32) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.operator.scalar.BinaryPredicateOperator.accept(BinaryPredicateOperator.java:62) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.SubqueryUtils.rewritePredicateAndExtractColumnRefs(SubqueryUtils.java:206) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.rule.transformation.ScalarApply2JoinRule.transformCorrelateWithCheckOneRows(ScalarApply2JoinRule.java:109) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.rule.transformation.ScalarApply2JoinRule.transformCorrelate(ScalarApply2JoinRule.java:76) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.rule.transformation.ScalarApply2JoinRule.transform(ScalarApply2JoinRule.java:64) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.task.RewriteTreeTask.rewrite(RewriteTreeTask.java:61) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.task.RewriteTreeTask.rewrite(RewriteTreeTask.java:79) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.task.RewriteTreeTask.rewrite(RewriteTreeTask.java:79) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.task.RewriteTreeTask.rewrite(RewriteTreeTask.java:79) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.task.RewriteTreeTask.rewrite(RewriteTreeTask.java:79) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.task.RewriteTreeTask.execute(RewriteTreeTask.java:46) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.task.SeriallyTaskScheduler.executeTasks(SeriallyTaskScheduler.java:49) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.ruleRewriteIterative(Optimizer.java:455) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.logicalRuleRewrite(Optimizer.java:215) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.rewriteAndValidatePlan(Optimizer.java:309) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.optimizeByCost(Optimizer.java:130) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.optimize(Optimizer.java:91) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.createQueryPlan(StatementPlanner.java:95) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:66) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:37) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:371) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:312) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:427) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:673) ~[starrocks-fe.jar:?]
        at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:55) ~[starrocks-fe.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]

```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - mysql> select current_version();
+-------------------------+
| current_version()       |
+-------------------------+
| BRANCH-2.5-ASAN 2da8668 |
+-------------------------+

### PR DESCRIPTION
**Pull request by packy92**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #15631

## Problem Summary(Required) ：

The last modification in this [pr](https://github.com/StarRocks/starrocks/pull/15149) missed a line. 

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Comment by packy92** [comment]
run all

**Comment by packy92** [comment]
@Mergify backport branch-2.5

**Review by kangkaisen — APPROVED** [review]

**Comment by packy92** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rewrite/BaseScalarOperatorShuttle.java|1|1|100.00%|[]|

**Review by murphyatwork — APPROVED** [review]

**Pull request merged**
