### PR TITLE
[BugFix] Fix persistent index upsert with wrong size

### LINKED ISSUE #14279: [condition update]be crash when enable_persistent_index is true
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
```
        CREATE TABLE `primary_table_test` (
            `k0` date,
            `k1` date,
            `k2` datetime,
            `k3` string,
            `k4` string,
            `k5` boolean,
            `v1` tinyint NOT NULL,
            `v2` smallint NOT NULL,
            `v3` int NOT NULL,
            `v4` bigint NOT NULL,
            `v5` largeint NOT NULL,
            `v6` float NOT NULL,
            `v7` double NOT NULL,
            `v8` decimal(27,9) NOT NULL
        ) ENGINE=OLAP
        PRIMARY KEY(`k0`)
        COMMENT "OLAP"
        DISTRIBUTED BY HASH(`k0`) BUCKETS 3
        ORDER BY(`k0`, `k1`)
        PROPERTIES (
            "replication_num" = "3",
            "enable_persistent_index" = "true",
            "storage_format" = "v2"
        )
```
2. INSERT INTO '....'
```
curl --location-trusted -u root: -T /home/disk4/lvchenyang/codebak/StarRocksTest/lib/../common/data/condition_update/basic_types_data_condition_sort -XPUT -H label:stream_load_1669708949432 -H columns:k0,k1,k2,k3,k4,k5,v1,v1_not_exist,v2,v3,v4,v5,v6,v7,v8 -H merge_condition:k1 http://ip:port/api/test_condition_2b689ee4_6fbc_11ed_8dec_00163e0e550b/primary_table_test/_stream_load
```
3. SELECT  '....'
```
select count(*) from primary_table_test;
```
### Expected behavior (Required)
998
### Real behavior (Required)
be crash
failed to start be
```
*** Aborted at 1669708949 (unix time) try "date -d @1669708949" if you are using GNU date ***
PC: @          0x364ddf0 XXH_INLINE_XXH3_64bits
*** SIGSEGV (@0x0) received by PID 7487 (TID 0x7f927d1e4700) from PID 0; stack trace: ***
    @          0x4e0faa2 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7f94675ba630 (unknown)
    @          0x364ddf0 XXH_INLINE_XXH3_64bits
    @          0x3656ada starrocks::ShardByLengthMutableIndex::split_keys_by_shard()
    @          0x365e464 starrocks::ShardByLengthMutableIndex::upsert()
    @          0x3664f91 starrocks::PersistentIndex::upsert()
    @          0x33cf592 starrocks::PrimaryIndex::_upsert_into_persistent_index()
    @          0x348ff0e starrocks::TabletUpdates::_do_update()
    @          0x349b45b starrocks::TabletUpdates::_apply_rowset_commit()
    @          0x349da93 starrocks::TabletUpdates::do_apply()
    @          0x3cc1385 starrocks::ThreadPool::dispatch_thread()
    @          0x3cbc73a starrocks::Thread::supervise_thread()
    @     0x7f94675b2ea5 start_thread
    @     0x7f9466bcdb0d __clone
    @                0x0 (unknown)
```
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
MAIN-RELEASE-aeef667

### PR DESCRIPTION
**Pull request by caneGuy**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #14279 

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Review by sevev — APPROVED** [review]

**Review by dirtysalt — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by decster — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Comment by decster** [comment]
@caneGuy  does 2.4 also need to backport?

**Comment by caneGuy** [comment]
> @caneGuy does 2.4 also need to backport?

no, we do not support conditional update on branch 2.4

**Pull request merged**
