### PR TITLE
[BugFix]Fix desc external catalog table not have [partition key] for partition tables

### LINKED ISSUE #15394: Desc external catalog partition table,iceberg/hudi table no partition key for partition columns
### Steps to reproduce the behavior (Required)
iceberg_catalog_01.test.test_iceberg_par
### Expected behavior (Required)
+-------+------------------+------+-------+---------+---------------+
| Field | Type             | Null | Key   | Default | Extra         |
+-------+------------------+------+-------+---------+---------------+
| id    | INT              | Yes  | false | NULL    |               |
| name  | VARCHAR(1048576) | Yes  | false | NULL    |               |
| dt    | VARCHAR(1048576) | Yes  | false | NULL    | partition key |
+-------+------------------+------+-------+---------+---------------+
### Real behavior (Required)
+-------+----------------+------+-------+---------+-------+
| Field | Type           | Null | Key   | Default | Extra |
+-------+----------------+------+-------+---------+-------+
| dt    | VARCHAR(65533) | Yes  | false | NULL    |       |
| name  | VARCHAR(65533) | Yes  | false | NULL    |       |
| id    | BIGINT         | Yes  | false | NULL    |       |
+-------+----------------+------+-------+---------+-------+
### StarRocks version (Required)

**main-branch code**

### PR DESCRIPTION
**Pull request by leoyy0316**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #15394

## Problem Summary(Required) ：

Fix desc external catalog table not have [partition key] for partitio…

**desc iceberg_catalog_01.test.test_iceberg_par;**
+-------+------------------+------+-------+---------+---------------+
| Field | Type             | Null | Key   | Default | Extra         |
+-------+------------------+------+-------+---------+---------------+
| dt    | VARCHAR(1048576) | Yes  | false | NULL    | partition key |
| name  | VARCHAR(1048576) | Yes  | false | NULL    |               |
| id    | BIGINT           | Yes  | false | NULL    |               |
+-------+------------------+------+-------+---------+---------------+

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Comment by leoyy0316** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 2 / 3 (66.67%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/ShowStmtAnalyzer.java|1|2|50.00%|[309]|
|:large_blue_circle:|com/starrocks/common/proc/ExternalSchemaProcNode.java|1|1|100.00%|[]|

**Comment by wangruin** [comment]
run starrocks_admit_test

**Review by Youngwb — APPROVED** [review]

**Review by stephen-shelby — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
