### PR TITLE
Fix limit on subquery lose gather required

### LINKED ISSUE #4997: query result error in norec mode
### Steps to reproduce the behavior (Required)
```
DROP DATABASE IF EXISTS d0;
CREATE DATABASE d0;
USE d0;
admin set frontend config ("enable_decimal_v3" = "true");
CREATE TABLE t0 (c_0_0 DATETIME NOT NULL ,c_0_1 DATE NOT NULL ,c_0_2 DECIMAL(29, 7)  NULL ,c_0_3 INT NULL ,c_0_4 DECIMAL(30, 20)  NULL ,c_0_5 INT NOT NULL ,c_0_6 BOOLEAN NULL ,c_0_7 BOOLEAN NULL ,c_0_8 DECIMAL(31, 18)  NULL ,c_0_9 ARRAY<STRING> NULL ) UNIQUE KEY (c_0_0,c_0_1) PARTITION BY RANGE(c_0_0) (START ("2010-01-01") END ("2021-12-31") EVERY (INTERVAL 95 day)) DISTRIBUTED BY HASH (c_0_0) BUCKETS 3 properties("replication_num"="3") ;
CREATE TABLE IF NOT EXISTS t1 (c_1_0 DATE NULL ,c_1_1 LARGEINT MAX NOT NULL ,c_1_2 PERCENTILE PERCENTILE_UNION NULL ,c_1_3 PERCENTILE PERCENTILE_UNION NULL ,c_1_4 HLL HLL_UNION NULL ,c_1_5 PERCENTILE PERCENTILE_UNION NOT NULL ,c_1_6 DATE MIN NULL ,c_1_7 PERCENTILE PERCENTILE_UNION NULL ,c_1_8 HLL HLL_UNION NULL ,c_1_9 DATETIME REPLACE NULL ) AGGREGATE KEY (c_1_0) PARTITION BY RANGE(c_1_0) (START ("2010-01-01") END ("2021-12-31") EVERY (INTERVAL 93 day)) DISTRIBUTED BY HASH (c_1_0) BUCKETS 3 properties("replication_num"="3") ;
INSERT INTO t1 VALUES ("2010-01-19", -2119614095, percentile_hash("298497629"), percentile_hash("-1051144791"), hll_hash("N"), percentile_hash("1748281836"), "2010-01-18", percentile_hash("-2135282216"), hll_hash("xg83Z3"), "2010-01-26 08:00:14"), ("2010-01-08", 2014626667, percentile_hash("549738981"), percentile_hash("-772482649"), hll_hash("K"), percentile_hash("2014626667"), "2010-01-05", percentile_hash("-1051144791"), hll_hash("vTnxpX"), "2010-01-19 08:00:14");
INSERT INTO t0 VALUES ("2010-01-17 08:00:14", "2010-01-23", 541769816668136.1748050, 0, 7.542453918E-11, 24, true, true, 0.000005056155417629, ["", "V", "rG2", "V3", "plZ", "", "", "lxfTUupuZ"]), ("2010-01-12 08:00:14", "2010-01-28", 206268446764048.7363035, 27, 6.967040044E-11, 14, NULL, true, NULL, ["jG3v", "Z", "DZp", "", "aLS", "V4CaUeNFB", "WBCW", "69", "C", "A2p", "", "", "V"]), ("2010-01-12 08:00:14", "2010-01-17", 721923673222889.6169120, 4, 4.799928396E-11, 16, true, NULL, 7.12253877546E-7, ["u", "", "m"]);
INSERT INTO t0 VALUES ("2010-01-03 08:00:14", "2010-01-24", 529705535517852.3720193, 10, 2.273591398E-11, 2, true, true, 0.000006507133018569, []);
INSERT INTO t1 VALUES ("2010-01-08", 1809440797, percentile_hash("-1546181039"), percentile_hash("1810751430"), hll_hash(""), percentile_hash("305529257"), "2009-12-31", percentile_hash("929999263"), hll_hash("q"), "2010-01-20 08:00:14");
INSERT INTO t0 VALUES ("2010-01-26 08:00:14", "2010-01-29", 964079292878474.0442393, 29, 3.91914095E-12, 15, false, NULL, 0.000003496537490969, ["4", "9F", "RUqBu", "U45ybxP", "g", "C5", "", "", "zn6", "", "", "6"]);
INSERT INTO t1 VALUES ("2010-01-06", 1518198894, percentile_hash("2014626667"), percentile_hash("-2004236434"), hll_hash(""), percentile_hash("28129472"), "2010-01-19", percentile_hash("891401931"), hll_hash("nQp"), NULL), ("2010-01-14", -1275735147, percentile_hash("703398865"), percentile_hash("-2119614095"), hll_hash(""), percentile_hash("298497629"), "2010-01-08", percentile_hash("2070718504"), hll_hash("NUOtP1DV"), "2010-01-30 08:00:14"), ("2010-01-05", -226521699, percentile_hash("4313609"), percentile_hash("993309169"), hll_hash("P1"), percentile_hash("914127660"), "2010-01-03", percentile_hash("655055478"), hll_hash(""), "2010-01-09 08:00:14");
-- SELECT DISTINCT subt0.c_0_0 FROM  (SELECT t1.c_1_0, t1.c_1_1, t1.c_1_6, t1.c_1_9 FROM t1 WHERE CASE  WHEN false THEN (t1.c_1_6)  BETWEEN (t1.c_1_6) AND (t1.c_1_6)   WHEN true THEN BITMAP_CONTAINS(bitmap_hash("D"), CASE  WHEN (t1.c_1_1) IN (1427007947, 301588202)  THEN NULL  WHEN false THEN -2004236434  WHEN ((t1.c_1_9) IS NOT NULL) THEN 1217649153 ELSE ((-109138084)*(1898880645)) END)  END) subt1 RIGHT ANTI JOIN (SELECT t0.c_0_0, t0.c_0_1, t0.c_0_2, t0.c_0_3, t0.c_0_4, t0.c_0_5, t0.c_0_6, t0.c_0_7, t0.c_0_8 FROM t0 WHERE true LIMIT 4 OFFSET 4) subt0 ON subt1.c_1_0 = subt0.c_0_4 AND subt1.c_1_0 != subt0.c_0_4 AND subt1.c_1_6 >= subt0.c_0_1 AND "1969-12-21" = subt0.c_0_1;
-- cardinality: 3
-- SELECT DISTINCT * FROM (SELECT DISTINCT subt0.c_0_0 FROM  (SELECT t1.c_1_0, t1.c_1_1, t1.c_1_6, t1.c_1_9 FROM t1 WHERE CASE  WHEN false THEN (t1.c_1_6)  BETWEEN (t1.c_1_6) AND (t1.c_1_6)   WHEN true THEN BITMAP_CONTAINS(bitmap_hash("D"), CASE  WHEN (t1.c_1_1) IN (1427007947, 301588202)  THEN NULL  WHEN false THEN -2004236434  WHEN ((t1.c_1_9) IS NOT NULL) THEN 1217649153 ELSE ((-109138084)*(1898880645)) END)  END) subt1 RIGHT ANTI JOIN (SELECT t0.c_0_0, t0.c_0_1, t0.c_0_2, t0.c_0_3, t0.c_0_4, t0.c_0_5, t0.c_0_6, t0.c_0_7, t0.c_0_8 FROM t0 WHERE true LIMIT 4 OFFSET 4) subt0 ON subt1.c_1_0 = subt0.c_0_4 AND subt1.c_1_0 != subt0.c_0_4 AND subt1.c_1_6 >= subt0.c_0_1 AND "1969-12-21" = subt0.c_0_1 WHERE (subt0.c_0_1)  BETWEEN (subt0.c_0_1) AND (subt0.c_0_1)  UNION ALL SELECT DISTINCT subt0.c_0_0 FROM  (SELECT t1.c_1_0, t1.c_1_1, t1.c_1_6, t1.c_1_9 FROM t1 WHERE CASE  WHEN false THEN (t1.c_1_6)  BETWEEN (t1.c_1_6) AND (t1.c_1_6)   WHEN true THEN BITMAP_CONTAINS(bitmap_hash("D"), CASE  WHEN (t1.c_1_1) IN (1427007947, 301588202)  THEN NULL  WHEN false THEN -2004236434  WHEN ((t1.c_1_9) IS NOT NULL) THEN 1217649153 ELSE ((-109138084)*(1898880645)) END)  END) subt1 RIGHT ANTI JOIN (SELECT t0.c_0_0, t0.c_0_1, t0.c_0_2, t0.c_0_3, t0.c_0_4, t0.c_0_5, t0.c_0_6, t0.c_0_7, t0.c_0_8 FROM t0 WHERE true LIMIT 4 OFFSET 4) subt0 ON subt1.c_1_0 = subt0.c_0_4 AND subt1.c_1_0 != subt0.c_0_4 AND subt1.c_1_6 >= subt0.c_0_1 AND "1969-12-21" = subt0.c_0_1 WHERE (NOT ((subt0.c_0_1)  BETWEEN (subt0.c_0_1) AND (subt0.c_0_1) )) UNION ALL SELECT DISTINCT subt0.c_0_0 FROM  (SELECT t1.c_1_0, t1.c_1_1, t1.c_1_6, t1.c_1_9 FROM t1 WHERE CASE  WHEN false THEN (t1.c_1_6)  BETWEEN (t1.c_1_6) AND (t1.c_1_6)   WHEN true THEN BITMAP_CONTAINS(bitmap_hash("D"), CASE  WHEN (t1.c_1_1) IN (1427007947, 301588202)  THEN NULL  WHEN false THEN -2004236434  WHEN ((t1.c_1_9) IS NOT NULL) THEN 1217649153 ELSE ((-109138084)*(1898880645)) END)  END) subt1 RIGHT ANTI JOIN (SELECT t0.c_0_0, t0.c_0_1, t0.c_0_2, t0.c_0_3, t0.c_0_4, t0.c_0_5, t0.c_0_6, t0.c_0_7, t0.c_0_8 FROM t0 WHERE true LIMIT 4 OFFSET 4) subt0 ON subt1.c_1_0 = subt0.c_0_4 AND subt1.c_1_0 != subt0.c_0_4 AND subt1.c_1_6 >= subt0.c_0_1 AND "1969-12-21" = subt0.c_0_1 WHERE (((subt0.c_0_1)  BETWEEN (subt0.c_0_1) AND (subt0.c_0_1) ) IS NULL)) t;
-- cardinality: 4

```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - branch-2.2 ASAN
 - mysql> select current_version();
+--------------------------+
| current_version()        |
+--------------------------+
| SQLANCER_01_ASAN 34240af |
+--------------------------+

### PR DESCRIPTION
**Pull request by Seaven**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] others

## Which issues of this PR fixes ：

Fixes #4997

## Problem Summary(Required) ：

```
select * from (select * from t0 limit 10) xx where xx.v1 = 1
```

```
| PLAN FRAGMENT 0                 |
|  OUTPUT EXPRS:1: v1             |
|   PARTITION: UNPARTITIONED      |
|                                 |
|   RESULT SINK                   |
|                                 |
|   2:EXCHANGE                    |
|                                 |
| PLAN FRAGMENT 1                 |
|  OUTPUT EXPRS:                  |
|   PARTITION: RANDOM             |
|                                 |
|   STREAM DATA SINK              |
|     EXCHANGE ID: 02             |
|     UNPARTITIONED               |
|                                 |
|   1:SELECT                      |
|   |  predicates: 1: v1 > 0      |
|   |                             |
|   0:OlapScanNode                |
|      TABLE: t0                  |
|      PREAGGREGATION: ON         |
|      partitions=1/1             |
|      rollup: t0                 |
|      tabletRatio=2/3            |
|      tabletList=3036479,3036481 |
|      cardinality=4              |
|      avgRowSize=1.0             |
|      numNodes=0                 |
|      limit: 10
```

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 13 / 13 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/RequiredPropertyDeriver.java|3|3|100.00%|
|:large_blue_circle:|com/starrocks/sql/optimizer/base/ColumnRefSet.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/sql/optimizer/OutputPropertyDeriver.java|9|9|100.00%|

**Comment by HangyuanLiu** [comment]
Please add details on what to fix and how. In addition, in the example you gave, sql is "limit 2", why is "limit 10" in the query plan. Are sql and query plan the same? or because of a bug

**Comment by Seaven** [comment]
> Please add details on what to fix and how. In addition, in the example you gave, sql is "limit 2", why is "limit 10" in the query plan. Are sql and query plan the same? or because of a bug

Lose gather on select when child has limit

**Review by Youngwb — APPROVED** [review]

**Review by kangkaisen — APPROVED** [review]

**Comment by Seaven** [comment]
@mergify backport branch-2.2

**Comment by Seaven** [comment]
@mergify backport branch-2.1

**Pull request merged**
