### PR TITLE
[SR SQL Planner Summer Camp] antlr4 for CreateDbStmt

### LINKED ISSUE #7947: New Parser and Analyzer support database-related statements (Challenging)
# Required work and output

1.  Use antlr4 to complete parse statements. The generated statement must follow the original data structure, and should be compatible with the old statement.
    
2.  In the original syntax file  **sql_parser.cup**, the new syntax needs to be compatible with the syntax of the old version, using the syntax file sql_parser.cup of the old version as the reference standard.
    
3.  Remove the logic of analytic functions in the statement and move the relevant logic to the new Analyzer framework. The new Analyzer is in the SQL/Analyzer directory.
    
4.  If the code related to Privilege Check exists in the original analyzer, move the code related to privilege control into PrivilegeChecker.
    
5.  When submitting the PR, please make sure there is unit test coverage for related changes.
    

# Tasks

 - [ ] AlterDatabaseRename
 - [ ] ShowCreateDbStmt
 - [ ] CreateDbStmt
 - [ ] DropDbStmt
 - [ ] RecoverDbStmt
 - [ ] ShowDataStmt
 - [ ] AlterDatabaseQuotaStmt

# How to participate?

1.  Pick an issue you are interested in, click the issue link and leave a comment under the issue to sign up.  **One person can only choose one issue and the first person who picks the issue will be assigned.**
    
2.  **After the issue is assigned, you should complete the task in 14 days.** If you are unable to complete it within the specified time, the task will be withdrawn and assigned to others.
    
3.  Participants are required to produce two pieces of content (forms including but not limited to mind maps, study notes, blogs, and tutorials) in the course of the activity, each of which should be at least 200 words.
    
4.  Got questions? Join our  [Slack channel](https://join.slack.com/t/starrocks/shared_invite/zt-192zeqlc7-9MAvqAXNcveW_l5Pqr8r2g)  and find channel:  **#sql-planner**.
    

# Before you start

1.  Read  [Contributing.md](https://github.com/StarRocks/starrocks/blob/main/CONTRIBUTING.md)  carefully to understand how to submit a pull request and how to configure BE and FE development environment.
    
2.  Sign the  [Contributor License Agreement](https://cla-assistant.io/StarRocks/starrocks)  before you make a pull request.
    
3.  To learn more about StarRocks, please refer to  [StarRocks documentation](https://github.com/StarRocks/docs/blob/main/TOC.md).
    

# Pull request requirements

1.  Create a pull request (PR) after you complete the task.
* PR title format: [SR SQL Planner Summer Camp] + PR title
2. After submitting PR, you can comment under the pinned Issue [SR SQL Planner Summer Camp].
* Comment format: "I have finished Issue #" + PR link

### PR DESCRIPTION
**Pull request by zombee0**
Signed-off-by: zombee0 <flylucas_10@163.com>

## What type of PR is this：
- [ ]  AlterDatabaseRename
- [ ] ShowCreateDbStmt
- [x] CreateDbStmt
- [x] DropDbStmt
- [ ] RecoverDbStmt
- [ ] ShowDataStmt
- [ ] AlterDatabaseQuotaStmt

## Which issues of this PR fixes ：

Fixes #7947 

## Problem Summary(Required) ：

antlr4 Refactor CreateDbStmt

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 0 / 26 (00.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/Analyzer.java|0|2|00.00%|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|0|3|00.00%|
|:large_blue_circle:|com/starrocks/sql/ast/AstVisitor.java|0|1|00.00%|
|:large_blue_circle:|com/starrocks/sql/analyzer/PrivilegeChecker.java|0|5|00.00%|
|:large_blue_circle:|com/starrocks/sql/analyzer/CreateDbAnalyzer.java|0|11|00.00%|
|:large_blue_circle:|com/starrocks/analysis/CreateDbStmt.java|0|4|00.00%|

**Review by imay — DISMISSED** [review]
LGTM

**Comment by imay** [comment]
Could you add some unit test?

**Comment by zombee0** [comment]
> Could you add some unit test?

OK，I will add some unit test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 21 / 26 (80.77%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/ast/AstVisitor.java|0|1|00.00%|
|:large_blue_circle:|com/starrocks/sql/analyzer/CreateDbAnalyzer.java|8|11|72.73%|
|:large_blue_circle:|com/starrocks/sql/analyzer/PrivilegeChecker.java|4|5|80.00%|
|:large_blue_circle:|com/starrocks/sql/analyzer/Analyzer.java|2|2|100.00%|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|3|3|100.00%|
|:large_blue_circle:|com/starrocks/analysis/CreateDbStmt.java|4|4|100.00%|

**Comment by zombee0** [comment]
I am going to pr the statement one by one, should i make them together?

**Review by imay — APPROVED** [review]

**Review by kangkaisen — APPROVED** [review]

**Pull request merged**
