### PR TITLE
[BugFix] avoid ConcurrentModificationException when refresh mv

### LINKED ISSUE #27211: failed to refresh mv with ConcurrentModificationException
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
2. INSERT INTO '....'
3. SELECT  '....'

### Real behavior (Required)
```
java.util.ConcurrentModificationException: null
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445) ~[?:1.8.0_292]
        at java.util.HashMap$EntryIterator.next(HashMap.java:1479) ~[?:1.8.0_292]
        at java.util.HashMap$EntryIterator.next(HashMap.java:1477) ~[?:1.8.0_292]
        at com.starrocks.catalog.OlapTable.getRangePartitionMap(OlapTable.java:733) ~[starrocks-fe.jar:?]
        at com.starrocks.scheduler.PartitionBasedMaterializedViewRefreshProcessor.syncPartitionsForExpr(PartitionBasedMaterializedViewRefreshProcessor.java:547) ~[starrocks-fe.jar:?]
        at com.starrocks.scheduler.PartitionBasedMaterializedViewRefreshProcessor.syncPartitions(PartitionBasedMaterializedViewRefreshProcessor.java:490) ~[starrocks-fe.jar:?]
        at com.starrocks.scheduler.PartitionBasedMaterializedViewRefreshProcessor.processTaskRun(PartitionBasedMaterializedViewRefreshProcessor.java:142) ~[starrocks-fe.jar:?]
        at com.starrocks.scheduler.TaskRun.executeTaskRun(TaskRun.java:128) ~[starrocks-fe.jar:?]
        at com.starrocks.scheduler.TaskRunExecutor.lambda$executeTaskRun$0(TaskRunExecutor.java:34) ~[starrocks-fe.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604) ~[?:1.8.0_292]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_292]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_292]
        at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_292]
2023-07-14 12:50:19,151 INFO (DynamicPartitionScheduler|52) [LocalMetastore.dropPartition():1543] succeed in droping partition[p20211109], is temp : false, is force : true
2023-07-14 12:50:19,157 INFO (DynamicPartitionScheduler|52) [LocalMetastore.dropPartition():1543] succeed in droping partition[p20211110], is temp : false, is force : true
2023-07-14 12:50:19,162 INFO (DynamicPartitionScheduler|52) [LocalMetastore.dropPartition():1543] succeed in droping partition[p20211111], is temp : false, is force : true
2023-07-14 12:50:19,167 INFO (DynamicPartitionScheduler|52) [LocalMetastore.dropPartition():1543] succeed in droping partition[p20211112], is temp : false, is force : true
2023-07-14 12:50:19,172 INFO (DynamicPartitionScheduler|52) [LocalMetastore.dropPartition():1543] succeed in droping partition[p20211113], is temp : false, is force : true
2023-07-14 12:50:19,178 INFO (DynamicPartitionScheduler|52) [LocalMetastore.dropPartition():1543] succeed in droping partition[p20211114], is temp : false, is force : true
2023-07-14 12:50:19,184 INFO (DynamicPartitionScheduler|52) [LocalMetastore.dropPartition():1543] succeed in droping partition[p20211115], is temp : false, is force : true
```
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by choury**
Fixes #27211

## What type of PR is this:
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [x] 3.0
  - [x] 2.5
  - [ ] 2.4

### CODE REVIEW

**Review by imay — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/scheduler/PartitionBasedMvRefreshProcessor.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
