### PR TITLE
[BugFix] fix min-readable-version lost during replay

### LINKED ISSUE #17191: get_applied_rowsets failed for newly cloned tablet for query at FE follower
### Real behavior (Required)
```
I0201 15:30:29.183106 25550 tablet_manager.cpp:779] Reporting tablet info. tablet_id=2883044
I0201 15:30:29.183177 25550 engine_clone_task.cpp:315] clone get tablet info success. tablet_id:2883044, schema_hash:475721122, signature:2883044, version:16316
I0201 15:30:29.183195 25550 agent_task.cpp:324] clone success, set tablet infos. status:0, signature:2883044
W0201 15:30:30.371259 19069 tablet_updates.cpp:2333] get_applied_rowsets(version 16314) failed tablet:2883044 #version:1 [16316 16316@0 16316] #pending:0
W0201 15:30:30.371539 19069 internal_service.cpp:189] exec multi plan fragments failed, errmsg=get_applied_rowsets(version 16314) failed tablet:2883044 #version:1 [16316 16316@0 16316] #pending:0
I0201 15:30:30.459359 19075 local_tablets_channel.cpp:483] LocalTabletsChannel txn_id: 1666735 load_id: 4e30abbe-a202-11ed-bb0f-00163e15de67 open delta writer: [2883180:0][2883196:0][2883144:0][2883112:0][2883108:0][2883084:0][2883080:0][2883064:0][2883052:0][2883044:0][2883020:0][2883172:0][2883016:0] failed_tablets:

```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by decster**
Signed-off-by: Binglin Chang <decstery@gmail.com>

## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #17191
Relates to #10694

## Problem Summary(Required) ：

When replay ReplicaPersistInfo, minReadableVersion is omitted, this PR fixes this.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 2.5
  - [x] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 4 / 8 (50.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|0|3|00.00%|[2939, 2940, 2953]|
|:large_blue_circle:|com/starrocks/persist/ReplicaPersistInfo.java|0|1|00.00%|[308]|
|:large_blue_circle:|com/starrocks/catalog/Replica.java|4|4|100.00%|[]|

**Review by chaoyli — APPROVED** [review]

**Review by Astralidea — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by decster** [comment]
run starrocks_admit_test

**Comment by decster** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.4

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.3

**Pull request merged**
