### PR TITLE
[BugFix] Check whether storage volume is enabled

### PR DESCRIPTION
**Pull request by TszKitLo40**
Fixes #issue

## What type of PR is this:
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4

### CODE REVIEW

**Review by silverbullet233 — APPROVED** [review]

**Comment by TszKitLo40** [comment]
@Mergify rebase

**Comment by TszKitLo40** [comment]
@mergify rebase

**Comment by silverbullet233** [comment]
@mergify rebase

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 24 / 24 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/server/SharedDataStorageVolumeMgr.java|19|19|100.00%|[]|
|:large_blue_circle:|com/starrocks/server/SharedNothingStorageVolumeMgr.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/server/StorageVolumeMgr.java|4|4|100.00%|[]|

**Pull request merged**
