### PR TITLE
[BugFix] Fix parser for unitBoundary

### LINKED ISSUE #12135: time_slice can't distinguish FLOOR/CEIL
### Steps to reproduce the behavior (Required)
```
time_slice(id_datetime, INTERVAL 7 minute, CEIL)
```
can't distinguish FLOOR/CEIL.

### Expected behavior (Required)
execute with CEIL

### Real behavior (Required)
can't distinguish FLOOR/CEIL.

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by Pslydhh**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes https://github.com/StarRocks/starrocks/issues/12135

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by kangkaisen — DISMISSED** [review]

**Comment by Pslydhh** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by kangkaisen — APPROVED** [review]

**Review by ZiheLiu — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Pull request merged**
