### PR TITLE
[Enhancement] Add all known keywords in the new version of Parser

### LINKED ISSUE #6132: [Enhancement] Add all known keywords in the new version of Parser

### PR DESCRIPTION
**Pull request by HangyuanLiu**
## What type of PR is this：
- [ ] bug
- [ ] feature
- [x] enhancement
- [ ] others

## Which issues of this PR fixes ：

Fixes #6132

## Problem Summary(Required) ：

First add all keywords in the old version of parser to the new version to prevent inconsistencies in future statement support

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by imay — DISMISSED** [review]

**Comment by HangyuanLiu** [comment]
run starrocks_fe_unittest

**Comment by HangyuanLiu** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by Seaven — APPROVED** [review]

**Review by imay — APPROVED** [review]

**Pull request merged**
