### PR TITLE
Fix error return value of containsMaterializedColumn for iceberg

### PR DESCRIPTION
**Pull request by caneGuy**
## What type of PR is this：
- [x] enhancement

## Which issues of this PR fixes ：

Fixes #
Fix error return value of containsMaterializedColumn for iceberg, which will cause this rule invalid for iceberg table
Related with #1030 

## Problem Summary(Required) ：

```
MySQL [external_db]> explain select col_date from ex_iceberg_tbl8 where col_date >= '2020-01-01';
+----------------------------------------------+
| Explain String                               |
+----------------------------------------------+
| PLAN FRAGMENT 0                              |
|  OUTPUT EXPRS:7: col_date                    |
|   PARTITION: UNPARTITIONED                   |
|                                              |
|   RESULT SINK                                |
|                                              |
|   2:EXCHANGE                                 |
|                                              |
| PLAN FRAGMENT 1                              |
|  OUTPUT EXPRS:                               |
|   PARTITION: RANDOM                          |
|                                              |
|   STREAM DATA SINK                           |
|     EXCHANGE ID: 02                          |
|     UNPARTITIONED                            |
|                                              |
|   1:Project                                  |
|   |  <slot 7> : 7: col_date                  |
|   |                                          |
|   0:IcebergScanNode                          |
|      TABLE: ex_iceberg_tbl8                  |
|      PREDICATES: 7: col_date >= '2020-01-01' |
|      cardinality=1                           |
|      avgRowSize=2.0                          |
|      numNodes=0                              |
+----------------------------------------------+
```
to
```
MySQL [external_db]> explain select col_date from ex_iceberg_tbl8 where col_date >= '2020-01-01';
+----------------------------------------------+
| Explain String                               |
+----------------------------------------------+
| PLAN FRAGMENT 0                              |
|  OUTPUT EXPRS:7: col_date                    |
|   PARTITION: UNPARTITIONED                   |
|                                              |
|   RESULT SINK                                |
|                                              |
|   1:EXCHANGE                                 |
|                                              |
| PLAN FRAGMENT 1                              |
|  OUTPUT EXPRS:                               |
|   PARTITION: RANDOM                          |
|                                              |
|   STREAM DATA SINK                           |
|     EXCHANGE ID: 01                          |
|     UNPARTITIONED                            |
|                                              |
|   0:IcebergScanNode                          |
|      TABLE: ex_iceberg_tbl8                  |
|      PREDICATES: 7: col_date >= '2020-01-01' |
|      cardinality=1                           |
|      avgRowSize=1.0                          |
|      numNodes=0                              |
+----------------------------------------------+
```

### CODE REVIEW

**Comment by caneGuy** [comment]
@dirtysalt @DorianZheng @stephen-shelby @imay PTAL thanks!

**Comment by DorianZheng** [comment]
Should add UT for this issue

**Comment by caneGuy** [comment]
> Should add UT for this issue

i will add ut later @DorianZheng

**Review by imay — DISMISSED** [review]

**Comment by caneGuy** [comment]
i have added some ut cases for iceberg.PTAL thanks

**Review by imay — APPROVED** [review]

**Review by DorianZheng — APPROVED** [review]
LGTM

**Comment by caneGuy** [comment]
@DorianZheng @imay sorry, i deleted the branch by mistake.PTAL THANKS

**Review by kangkaisen — APPROVED** [review]

**Pull request merged**
