### PR TITLE
[BugFix] Fix priv check for set catalog statement

### LINKED ISSUE #19224: [access control]use catalog 'catalog_name'  succseefuly，set catalog catalog_name failed
### Steps to reproduce the behavior (Required)
1. conn SR use root user
```
CREATE EXTERNAL CATALOG catalog_e5a0bdda_bda7_11ed_9139_00163e0e550b properties ("type" = "hive","hive.metastore.uris" = "thrift://xxx.xx.xxx.xxx:9083") ;
create user user_e5a7f870_bda7_11ed_9139_00163e0e550b identified by '123456';
set catalog catalog_e5a0bdda_bda7_11ed_9139_00163e0e550b;
GRANT alter ON database tpcds_orc TO user user_e5a7f870_bda7_11ed_9139_00163e0e550b ;
```
2. conn SR use  user_e5a7f870_bda7_11ed_9139_00163e0e550b user
```
use catalog 'catalog_e5a0bdda_bda7_11ed_9139_00163e0e550b'  ;
set catalog catalog_e5a0bdda_bda7_11ed_9139_00163e0e550b  ;
```
2523d5d0-e8b0-4831-822f-6fb634494e1e

### Expected behavior (Required)
success
### Real behavior (Required)
use catalog success
set catalog failed
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
mysql> select current_version();
+----------------------------+
| current_version()          |
+----------------------------+
| BRANCH-3.0-RELEASE d659a54 |
+----------------------------+
1 row in set (0.01 sec)

### PR DESCRIPTION
**Pull request by nshangyiming**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #19224

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 3.0
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/PrivilegeCheckerV2.java|1|1|100.00%|[]|

**Review by gengjun-git — APPROVED** [review]

**Review by HangyuanLiu — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by nshangyiming** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Pull request merged**
