### PR TITLE
[BugFix] Add DropAnalyze handle

### LINKED ISSUE #17827: Drop analyze error
### Expected behavior (Required)
```
MySQL td> drop analyze 1;
(1064, 'Unexpected exception: New AST not implement toSql function')
```

### Real behavior (Required)
```
MySQL td> drop analyze 1;
Query OK, 0 rows affected
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by Seaven**
Signed-off-by: Seaven <seaven_7@qq.com>

## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #17827

lost in PR: 4b3a044ad

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 2.5
  - [x] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 5 / 6 (83.33%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/ast/DropAnalyzeJobStmt.java|1|2|50.00%|[31]|
|:large_blue_circle:|com/starrocks/sql/ast/AstVisitor.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/qe/DDLStmtExecutor.java|3|3|100.00%|[]|

**Comment by imay** [comment]
What foes drop analyze mean

**Review by murphyatwork — APPROVED** [review]

**Comment by Seaven** [comment]
> What foes drop analyze mean

drop schedule analyze job

**Review by kangkaisen — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.4

**Pull request merged**
