### PR TITLE
[Refactor] refactor lambda error msg

### PR DESCRIPTION
**Pull request by fzhedu**
Signed-off-by: fzhedu <fzhedu@gmail.com>

## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [x] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

before
```
mysql> SELECT arrry_filter((x,y)->(y!="1"),cast(j->'$.a[*].b' as array<string>), cast(j->'$.a[*].b' as array<string>)) from (select PARSE_JSON('{"a" :[ {"b": 1}, {"b":2}]}')  as j)A;
ERROR 1064 (HY000): Lambda Functions can only be used in supported high-order functions.
```
after
```
mysql> SELECT arrry_filter((x,y)->(y!="1"),cast(j->'$.a[*].b' as array<string>), cast(j->'$.a[*].b' as array<string>)) from (select PARSE_JSON('{"a" :[ {"b": 1}, {"b":2}]}')  as j)A;
ERROR 1064 (HY000): arrry_filter can't use Lambda Functions, as it is not a supported high-order function.
```

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature (mannual tests)
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Review by imay — DISMISSED** [review]

**Review by kangkaisen — APPROVED** [review]

**Review by Seaven — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by fzhedu** [comment]
run starrocks_admit_test

**Comment by fzhedu** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 7 / 7 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/analysis/Expr.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/ExpressionAnalyzer.java|5|5|100.00%|[]|

**Pull request merged**
