### PR TITLE
[Enhancement] add iceberg row count with v2 format from snapshot

### PR DESCRIPTION
**Pull request by stephen-shelby**
Fixes #issue

## What type of PR is this:
- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 5 / 5 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/connector/iceberg/cost/IcebergStatisticProvider.java|5|5|100.00%|[]|

**Review by dirtysalt — APPROVED** [review]

**Review by Youngwb — APPROVED** [review]

**Comment by stephen-shelby** [comment]
https://github.com/Mergifyio backport branch-3.1

**Comment by stephen-shelby** [comment]
[https://github.com/Mergifyio backport](https://github.com/Mergifyio%C2%A0backport) branch-3.1

**Comment by stephen-shelby** [comment]
https://github.com/Mergifyio backport branch-3.1

**Comment by stephen-shelby** [comment]
https://github.com/Mergifyio backport branch-3.1

**Pull request merged**
