### PR TITLE
[Feature]Support function isnotnull

### LINKED ISSUE #22702: [function] isnotnull
StarRocks already have a function named isnull.
https://docs.starrocks.io/en-us/latest/sql-reference/sql-functions/utility-functions/isnull
For easy of use, it's better to have a function that isnotnull.

### PR DESCRIPTION
**Pull request by leoyy0316**
## What type of PR is this:
- [ ] BugFix
- [x] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes:

Fixes #22702

## Problem Summary(Required):

Test
select * from test.t_leo;
+------+------+-------+
| id   | name | money |
+------+------+-------+
|    1 | a    |  NULL |
+------+------+-------+

select isnotnull(money) from test.t_leo;
+-------------------+
| money IS NOT NULL |
+-------------------+
|                 0 |
+-------------------+

select isnotnull(id) from test.t_leo;
+----------------+
| id IS NOT NULL |
+----------------+
|              1 |
+----------------+
## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 3 / 3 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|3|3|100.00%|[]|

**Comment by wangsimo0** [comment]
hi could you please add a document?

**Comment by leoyy0316** [comment]
> hi could you please add a document?
@wangsimo0 done

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|2|2|100.00%|[]|

**Review by Seaven — APPROVED** [review]

**Review by stephen-shelby — APPROVED** [review]

**Pull request merged**
