### PR TITLE
[Feature] support alter table prop storage_cooldown_ttl

### PR DESCRIPTION
**Pull request by Astralidea**
Fixes #issue

## What type of PR is this:
- [ ] BugFix
- [x] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [x] 3.0
  - [ ] 2.5
  - [ ] 2.4

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 2 / 22 (09.09%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|0|12|00.00%|[3488, 3489, 3491, 3492, 3493, 3494, 3510, 3511, 3512, 3513, 3514, 3515]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AlterTableClauseVisitor.java|1|7|14.29%|[159, 161, 162, 163, 164, 165]|
|:large_blue_circle:|com/starrocks/alter/SchemaChangeHandler.java|1|3|33.33%|[1293, 1294]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 17 / 22 (77.27%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/AlterTableClauseVisitor.java|5|7|71.43%|[162, 163]|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|9|12|75.00%|[3492, 3493, 3515]|
|:large_blue_circle:|com/starrocks/alter/SchemaChangeHandler.java|3|3|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 17 / 22 (77.27%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/AlterTableClauseVisitor.java|5|7|71.43%|[162, 163]|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|9|12|75.00%|[3492, 3493, 3515]|
|:large_blue_circle:|com/starrocks/alter/SchemaChangeHandler.java|3|3|100.00%|[]|

**Review by nshangyiming — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 22 / 26 (84.62%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|8|11|72.73%|[3490, 3491, 3513]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AlterTableClauseVisitor.java|6|7|85.71%|[163]|
|:large_blue_circle:|com/starrocks/common/util/PropertyAnalyzer.java|5|5|100.00%|[]|
|:large_blue_circle:|com/starrocks/alter/SchemaChangeHandler.java|3|3|100.00%|[]|

**Review by gengjun-git — APPROVED** [review]

**Comment by Astralidea** [comment]
https://github.com/Mergifyio backport branch-3.1

**Comment by Astralidea** [comment]
https://github.com/Mergifyio backport branch-3.0

**Pull request merged**
