### PR TITLE
[BugFix] Materialized view type inference error import failed

### LINKED ISSUE #12731: [materialized view]refresh failed when max(varchar) lenth>3
### Steps to reproduce the behavior (Required)
```
CREATE TABLE t2 (
    k1 INT,
    k2 varchar(10))
DUPLICATE KEY(k1)
DISTRIBUTED BY HASH(k1);
INSERT INTO t2 VALUES (1,"12345");
CREATE MATERIALIZED VIEW mv1
DISTRIBUTED BY HASH(k1) BUCKETS 10
REFRESH ASYNC
AS SELECT k1, max(k2) as k2
FROM t2 group by k1;
SELECT * FROM INFORMATION_SCHEMA.task_runs order by create_time desc limit 1;
```
### Expected behavior (Required)
`refresh ok`
### Real behavior (Required)
`com.starrocks.sql.common.DmlException: 172.26.92.202: string length(5) > limit(3), string: 12345`
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
+----------------------+
| current_version()    |
+----------------------+
| MAIN-RELEASE 8c5420b |
+----------------------+
```

### PR DESCRIPTION
**Pull request by Astralidea**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #12731

## Problem Summary(Required) ：

Incorrect type inference of the materialized view caused this problem, borrowing the type inference of CTAS to form the correct type, this allows the import to become normal.
## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
BE Build Success

**Review by ABingHuang — APPROVED** [review]
LGTM

**Review by gengjun-git — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by Astralidea** [comment]
run starrocks_admit_test

**Comment by Astralidea** [comment]
run starrocks_admit_test

**Review by meegoo — APPROVED** [review]

**Comment by Astralidea** [comment]
@Mergifyio backport branch-2.4

**Pull request merged**
