### PR TITLE
[BugFix] catch exception for mv when replaying journal

### LINKED ISSUE #30019: FE restart failed due to Materialized View
### Steps to reproduce the behavior (Required)

FE cannot restart when replaying the journal, which contains inactive MV.

```java
2023-08-26 12:07:26,524 WARN (stateChangeExecutor|91) [GlobalStateMgr.replayJournal():1883] got interrupt exception or inconsistent exception when replay 
journal 3070926, will exit,
com.starrocks.journal.JournalInconsistentException: failed to load journal type 10097
        at com.starrocks.persist.EditLog.loadJournal(EditLog.java:954) ~[starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.replayJournalInner(GlobalStateMgr.java:1930) ~[starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.replayJournal(GlobalStateMgr.java:1881) ~[starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.transferToLeader(GlobalStateMgr.java:1050) ~[starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.access$100(GlobalStateMgr.java:298) ~[starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr$1.transferToLeader(GlobalStateMgr.java:655) ~[starrocks-fe.jar:?]
        at com.starrocks.ha.StateChangeExecutor.runOneCycle(StateChangeExecutor.java:86) ~[starrocks-fe.jar:?]
        at com.starrocks.common.util.Daemon.run(Daemon.java:115) ~[starrocks-fe.jar:?]
Caused by: com.starrocks.sql.analyzer.SemanticException: Create materialized view from inactive materialized view: cyb_dwd_catarc_mix_merge_mon_v
        at com.starrocks.sql.analyzer.MaterializedViewAnalyzer.lambda$getBaseTableInfos$0(MaterializedViewAnalyzer.java:114) ~[starrocks-fe.jar:?]
        at java.util.HashMap.forEach(HashMap.java:1288) ~[?:1.8.0_131]
        at com.starrocks.sql.analyzer.MaterializedViewAnalyzer.getBaseTableInfos(MaterializedViewAnalyzer.java:106) ~[starrocks-fe.jar:?]
        at com.starrocks.alter.Alter.processChangeMaterializedViewStatus(Alter.java:336) ~[starrocks-fe.jar:?]
        at com.starrocks.alter.Alter.replayAlterMaterializedViewStatus(Alter.java:574) ~[starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.replayAlterMaterializedViewStatus(GlobalStateMgr.java:3099) ~[starrocks-fe.jar:?]
        at com.starrocks.persist.EditLog.loadJournal(EditLog.java:294) ~[starrocks-fe.jar:?]
        ... 7 more
```

### StarRocks version (Required)
- 2.5.*, 3.0.*, 3.1.*

### PR DESCRIPTION
**Pull request by murphyatwork**
Fixes #30019

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [ ] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [x] 3.0
  - [x] 2.5
  - [ ] 2.4

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:disappointed: **fail** : 0 / 32 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/alter/AlterJobMgr.java|0|32|00.00%|[300, 302, 304, 305, 306, 307, 320, 321, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 336, 358, 386, 387, 388, 389, 390, 404, 406, 415, 416, 417, 418]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by LiShuMing — APPROVED** [review]

**Review by satanson — APPROVED** [review]

**Review by satanson — APPROVED** [review]

**Review by packy92 — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
