### PR TITLE
[BugFix]Avoid printing token in be log (#51728)(backport #51728)

### PR DESCRIPTION
**Pull request by xyllq999**
(cherry picked from commit 94938ddd608c497e46049cc3bd6095203051e5ed)

## What I'm doing:

Fixes #issue

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [x] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.3
  - [x] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

backport #51728

### CODE REVIEW

**Comment by xyllq999** [comment]
@gengjun-git The pipeline has been successful, please help check it.

**Review by kevincai — APPROVED** [review]

**Comment by kevincai** [comment]
@xyllq999 need additional fix to this PR, the new test file is not added into CMakefilesLists.txt in branch-3.3. The unit test will never be compiled and run.

**Comment by xyllq999** [comment]
> @xyllq999 need additional fix to this PR, the new test file is not added into CMakefilesLists.txt in branch-3.3. The unit test will never be compiled and run.

Thank you very much for the reminder, and I'll patch this PR based on the code for the main branch.

**Comment by xyllq999** [comment]
> @xyllq999 need additional fix to this PR, the new test file is not added into CMakefilesLists.txt in branch-3.3. The unit test will never be compiled and run.

https://github.com/StarRocks/starrocks/pull/52851

**Comment by xyllq999** [comment]
> @xyllq999 need additional fix to this PR, the new test file is not added into CMakefilesLists.txt in branch-3.3. The unit test will never be compiled and run.

I have submitted a new PR for the repair. Do I need to incorporate the code?

**Comment by kevincai** [comment]
> > @xyllq999 need additional fix to this PR, the new test file is not added into CMakefilesLists.txt in branch-3.3. The unit test will never be compiled and run.
> 
> I have submitted a new PR for the repair. Do I need to incorporate the code?

done

**Comment by xyllq999** [comment]
> > > @xyllq999 need additional fix to this PR, the new test file is not added into CMakefilesLists.txt in branch-3.3. The unit test will never be compiled and run.
> > 
> > 
> > I have submitted a new PR for the repair. Do I need to incorporate the code?
> 
> done

Thanks.

**Pull request merged**
