### PR TITLE
[BugFix] add check when push down AssertNode on project

### PR DESCRIPTION
**Pull request by Seaven**
## What type of PR is this：
- [ ] bugfix
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

PR #5079 wasn't consider `assert-project-agg`, the groupby isn't empty of aggregate scenes

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 4 / 5 (80.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/PushDownAssertOneRowProjectRule.java|4|5|80.00%|[31]|

**Review by kangkaisen — APPROVED** [review]

**Review by HangyuanLiu — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by Seaven** [comment]
@mergifyio backport branch-2.2

**Comment by Seaven** [comment]
https://github.com/Mergifyio backport branch-2.3

**Comment by Seaven** [comment]
https://github.com/Mergifyio backport branch-2.4

**Pull request merged**
