### PR TITLE
[BugFix] Fix InfoSchemaDb id increasing continuously bug

### LINKED ISSUE #9810: [BUG] FE do checkpoint failed with error: InfoSchemaDb id should't larger than 10000, please restart you FE server
### Steps to reproduce the behavior (Required)
It's not easy to reproduce this bug. Because it needs running for several months without restart.

### Expected behavior (Required)
do checkpoint successfully.

### Real behavior (Required)
Sp2CRDZihY

### StarRocks version (Required)
 - all

### PR DESCRIPTION
**Pull request by gengjun-git**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #9810

## Problem Summary(Required) ：

The information_schema db is not persisted, it is generated in loadCluster when loading image. Its id will increase once the loadCluster is called. If the cluster runs for a long time(3 months for example), its id may be bigger than 10000 ( which is the upper limit of system id), because the loadCluster will be called every time a checkpoint is done. The reason why the information_schema db's id will be increased maybe there will be many clusters in the system and every cluster will have its own information_schema db. But the cluster has be deprecated in our system, so we just give a fixed id number for every system db or table.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 1 / 2 (50.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/common/SystemId.java|0|1|00.00%|[22]|
|:large_blue_circle:|com/starrocks/catalog/InfoSchemaDb.java|1|1|100.00%|[]|

**Review by padmejin — DISMISSED** [review]

**Review by imay — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by gengjun-git** [comment]
run starrocks_fe_unittest

**Comment by gengjun-git** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 1 / 2 (50.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/common/SystemId.java|0|1|00.00%|[7]|
|:large_blue_circle:|com/starrocks/catalog/InfoSchemaDb.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 1 / 2 (50.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/common/SystemId.java|0|1|00.00%|[7]|
|:large_blue_circle:|com/starrocks/catalog/InfoSchemaDb.java|1|1|100.00%|[]|

**Review by meegoo — APPROVED** [review]

**Review by Astralidea — APPROVED** [review]

**Comment by gengjun-git** [comment]
@mergify backport branch-2.4

**Pull request merged**
