### PR TITLE
[BugFix] Fix alter materialized view property

### LINKED ISSUE #13547: [materialized view]The partition_ttl_number parameter does not take effect when alter mv
### Steps to reproduce the behavior (Required)
```
CREATE TABLE `t1` (
    `k1` date,
    `k2` int
) ENGINE=OLAP
DUPLICATE KEY(`k1`)
PARTITION BY RANGE (k1) (
START ("2020-01-15") END ("2020-02-12") EVERY (INTERVAL 3 day)
)
DISTRIBUTED BY HASH(`k1`);
CREATE MATERIALIZED VIEW mv2
partition by k1
DISTRIBUTED BY HASH(k1)
AS SELECT k1,k2 FROM t1;
ALTER materialized view mv2 set ("partition_ttl_number" = "5");
refresh materialized view mv2;
```
wait task finished
`show partitions from mv2`
### Expected behavior (Required)
`5 partitions`
### Real behavior (Required)
`10 partitions`
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
mysql> select current_version();
+----------------------------+
| current_version()          |
+----------------------------+
| BRANCH-2.5-RELEASE 512d9ca |
+----------------------------+
```

### LINKED ISSUE #13549: [materialized view]no error when set partition_ttl_number=0
### Steps to reproduce the behavior (Required)
```
CREATE TABLE `t1` (
    `k1` date,
    `k2` int
) ENGINE=OLAP
DUPLICATE KEY(`k1`)
PARTITION BY RANGE (k1) (
START ("2020-01-15") END ("2020-02-12") EVERY (INTERVAL 3 day)
)
DISTRIBUTED BY HASH(`k1`);
CREATE MATERIALIZED VIEW mv1
partition by k1
DISTRIBUTED BY HASH(k1)
PROPERTIES (
    "partition_ttl_number" = "0"
)
```
### Expected behavior (Required)
`error reoprted`
### Real behavior (Required)
`query ok`
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
+----------------------------+
| current_version()          |
+----------------------------+
| BRANCH-2.5-RELEASE 512d9ca |
+----------------------------+
```

### PR DESCRIPTION
**Pull request by Astralidea**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #13547
Fixes #13549

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

### CODE REVIEW

**Comment by Astralidea** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 2 / 7 (28.57%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/alter/Alter.java|0|1|00.00%|[322]|
|:large_blue_circle:|com/starrocks/common/util/PropertyAnalyzer.java|2|6|33.33%|[235, 236, 251, 252]|

**Comment by Astralidea** [comment]
run starrocks_admit_test

**Review by ABingHuang — APPROVED** [review]
LGTM

**Review by gengjun-git — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by Astralidea** [comment]
run starrocks_admit_test

**Review by Youngwb — APPROVED** [review]

**Comment by Astralidea** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
