### PR TITLE
[Refactor] Support RoutineLoadCreate Statement in new Parser and Analyzer (#9981)

### PR DESCRIPTION
**Pull request by shshenhua**
## What type of PR is this：
- [ ] BugFix  https://github.com/StarRocks/starrocks/pull/9981

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 78 / 96 (81.25%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/ast/AstVisitor.java|0|1|00.00%|[363]|
|:large_blue_circle:|com/starrocks/analysis/CreateRoutineLoadStmt.java|7|11|63.64%|[202, 203, 652, 657]|
|:large_blue_circle:|com/starrocks/sql/analyzer/CreateRoutineLoadAnalyzer.java|17|24|70.83%|[20, 21, 28, 29, 30, 32, 35]|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|48|54|88.89%|[1776, 1777, 1778, 1780, 1781, 1782]|
|:large_blue_circle:|com/starrocks/sql/analyzer/Analyzer.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/PrivilegeChecker.java|4|4|100.00%|[]|

**Comment by shshenhua** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 89 / 108 (82.41%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/analysis/CreateRoutineLoadStmt.java|7|11|63.64%|[202, 203, 652, 657]|
|:large_blue_circle:|com/starrocks/sql/analyzer/PrivilegeChecker.java|4|6|66.67%|[1032, 1033]|
|:large_blue_circle:|com/starrocks/sql/analyzer/CreateRoutineLoadAnalyzer.java|17|24|70.83%|[20, 21, 28, 29, 30, 32, 35]|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|49|55|89.09%|[1777, 1778, 1779, 1781, 1782, 1783]|
|:large_blue_circle:|com/starrocks/sql/analyzer/Analyzer.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/AstVisitor.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/load/RoutineLoadDesc.java|9|9|100.00%|[]|

**Review by HangyuanLiu — APPROVED** [review]

**Review by kangkaisen — APPROVED** [review]

**Comment by HangyuanLiu** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by imay — APPROVED** [review]

**Comment by imay** [comment]
run starrocks_admit_test

**Pull request merged**
