### PR TITLE
[Feature] support star client access shard info without grpc

### PR DESCRIPTION
**Pull request by starrocks-xupeng**
## What type of PR is this：
- [ ] BugFix
- [x] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

- [ ] I have checked the version labels which the pr will be auto backported to target branch

### CODE REVIEW

**Review by tracymacding — DISMISSED** [review]

**Review by sduzh — DISMISSED** [review]

**Comment by starrocks-xupeng** [comment]
run starrocks_fe_unittest

**Comment by tracymacding** [comment]
run starrocks_fe_unittest

**Review by wyb — DISMISSED** [review]

**Comment by starrocks-xupeng** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 4 / 6 (66.67%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/staros/StarMgrServer.java|2|4|50.00%|[130, 131]|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/lake/StarOSAgent.java|1|1|100.00%|[]|

**Comment by starrocks-xupeng** [comment]
run starrocks_admit_test

**Comment by starrocks-xupeng** [comment]
run starrocks_clang-format

**Comment by starrocks-xupeng** [comment]
run starrocks_clang-tidy

**Review by sduzh — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by starrocks-xupeng** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 4 / 6 (66.67%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/staros/StarMgrServer.java|2|4|50.00%|[130, 131]|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/lake/StarOSAgent.java|1|1|100.00%|[]|

**Comment by starrocks-xupeng** [comment]
run starrocks_admit_test

**Review by sduzh — APPROVED** [review]

**Review by wyb — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by starrocks-xupeng** [comment]
run starrocks_admit_test

**Comment by starrocks-xupeng** [comment]
run starrocks_admit_test

**Pull request merged**
