### PR TITLE
[Enhancement] Make assignment bucket sequences to backend more evenly 

### PR DESCRIPTION
**Pull request by ZiheLiu**
It gives priority to selecting the bucket sequence with the highest sum of selection counts for backends where its replicas are located.

A high value indicates that some backends used by this bucket sequence might have been assigned a substantial number of bucket sequences already, so it's advisable to assign this bucket sequence to the other backends as soon as possible.
For example, assume that there are 4 buckets(a~d) and 4 BEs, and the distribution of buckets is as follows:

- a: 1, 3
- b: 4, 2
- c: 3, 2
- d: 4, 1

With the old algorithm, the traverse order of the bucket sequences is `a, b, c, d`, and the result is as follows:

- a: 1
- b: 4
- c: 3
- b: 4 (here, both the backend `#4` and `#1` have already been selected once, resulting in either backend `#4` or `#1` being responsible for two bucket sequences, while backend `#2` remains unassigned any bucket sequence.)

With the new algorithm,  the traverse order of the bucket sequences is  `a, d, b, c`, and the result is as follows:
- a: 1
- d: 4
- b: 2
- c: 3

The time complexity of the new one is `numBucketsPerBE` times than that of the old one, because it must update the counter `backendUsedTimes` of all the bucket sequences in this backend. Therefore, it is only used when numBucketsPerBE is small enough (smaller than the session variable `max_buckets_per_be_to_use_balancer_assignment`). 

BTW, we could use binary search with [Ford–Fulkerson algorithm](https://oi-wiki.org/graph/flow/bound/) to perfectly solve this problem. However, 
- this algorithm is a little complex and the the time complexity is too high $O((n+m)(nk)^2logn)$, where $n$, $m$, $k$ denote the number of tablets, backends, replications, respectively.
- When the number of replications in a BE is pretty large (maybe > 10), the simple algorithm before this PR is evenly enough.

## Test
The following are some test results.
`var-before` and `var-after` are the variance of the number of assigned tablets in each BE, before and after this PR.

| num_tablets | num_replications | num_backends | var-before | var-after |
| ----------- | ---------------- | ------------ | ---------- | --------- |
| 23          | 2                | 7            | 0.49       | 0.2       |
| 23          | 3                | 11           | 0.26       | 0.08      |
| 33          | 2                | 11           | 0.36       | 0.18      |
| 33          | 2                | 16           | 0.18       | 0.31      |
| 33          | 3                | 16           | 0.43       | 0.06      |
| 53          | 2                | 17           | 0.34       | 0.1       |
| 63          | 2                | 31           | 0.22       | 0.1       |
| 73          | 2                | 36           | 0.3        | 0.14      |
| 73          | 2                | 24           | 0.46       | 0.04      |
| 83          | 2                | 41           | 0.32       | 0.02      |
| 93          | 2                | 46           | 0.15       | 0.02      |
| 93          | 2                | 31           | 0.39       | 0.26      |
| 103         | 2                | 34           | 0.44       | 0.26      |
| 103         | 2                | 51           | 0.22       | 0.06      |
| 113         | 2                | 56           | 0.23       | 0.05      |
| 113         | 3                | 56           | 0.3        | 0.12      |
| 123         | 2                | 41           | 0.34       | 0.2       |
| 123         | 2                | 61           | 0.25       | 0.05      |
| 133         | 3                | 66           | 0.26       | 0.11      |
| 143         | 2                | 71           | 0.27       | 0.04      |
| 143         | 2                | 47           | 0.47       | 0.25      |
| 153         | 2                | 76           | 0.2        | 0.07      |
| 153         | 2                | 51           | 0.35       | 0.2       |
| 153         | 3                | 76           | 0.25       | 0.12      |
| 173         | 3                | 86           | 0.24       | 0.1       |
| 183         | 2                | 91           | 0.23       | 0.12      |
| 183         | 2                | 61           | 0.36       | 0.23      |
| 193         | 2                | 64           | 0.39       | 0.23      |
| 193         | 2                | 96           | 0.22       | 0.03      |
| 193         | 3                | 96           | 0.3        | 0.16      |

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [x] This pr needs user documentation (for new or modified features or behaviors)
  - [x] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 13 / 13 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/SessionVariable.java|6|6|100.00%|[]|
|:large_blue_circle:|com/starrocks/qe/ColocatedBackendSelector.java|7|7|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by kevincai** [comment]
do we have internal doc for this? the example in the description is not very intuitive.

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 73 / 80 (91.25%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/SessionVariable.java|4|6|66.67%|[1905, 1906]|
|:large_blue_circle:|com/starrocks/qe/ColocatedBackendSelector.java|65|70|92.86%|[191, 314, 328, 338, 354]|
|:large_blue_circle:|com/starrocks/qe/scheduler/assignment/BackendSelectorFactory.java|4|4|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 73 / 80 (91.25%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/SessionVariable.java|4|6|66.67%|[1905, 1906]|
|:large_blue_circle:|com/starrocks/qe/ColocatedBackendSelector.java|65|70|92.86%|[191, 314, 328, 338, 354]|
|:large_blue_circle:|com/starrocks/qe/scheduler/assignment/BackendSelectorFactory.java|4|4|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 73 / 80 (91.25%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/SessionVariable.java|4|6|66.67%|[1905, 1906]|
|:large_blue_circle:|com/starrocks/qe/ColocatedBackendSelector.java|65|70|92.86%|[191, 314, 328, 338, 354]|
|:large_blue_circle:|com/starrocks/qe/scheduler/assignment/BackendSelectorFactory.java|4|4|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by ZiheLiu** [comment]
@Mergify rebase main

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 73 / 80 (91.25%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/SessionVariable.java|4|6|66.67%|[1917, 1918]|
|:large_blue_circle:|com/starrocks/qe/ColocatedBackendSelector.java|65|70|92.86%|[191, 314, 328, 338, 354]|
|:large_blue_circle:|com/starrocks/qe/scheduler/assignment/BackendSelectorFactory.java|4|4|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by Seaven — APPROVED** [review]

**Review by satanson — APPROVED** [review]

**Pull request merged**
