### PR TITLE
[Enhancement] Reduce fragment plan size

### PR DESCRIPTION
**Pull request by Seaven**
Fixes #issue

in complex query（a lot of union/expression/select-columns）, will make the fragment plan very large.
a `SlotDescriptor` size is 100 byte, 1000+ column will be 100k, so the whole fragment plan reach 1-2MB easily.
In x10 BE cluster, a FE's network output bandwidth will reach 10-20MB,  and reach 500MB when  FE support 50QPS

* Change unused paramter in thrift
* Add scalar operator rewrite when merge project

to handle union sql like:
```
select * from t0 union all select 1, 1, 1 from t1
```

before:
```
  4:Project
  |  <slot 10> : 16: cast
  |  <slot 11> : CAST(1 AS BIGINT)
  |  <slot 12> : CAST(1 AS BIGINT)
  |  common expressions:
  |  <slot 16> : CAST(1 AS BIGINT)
  |  
  3:OlapScanNode
     TABLE: t1
     PREAGGREGATION: ON
     partitions=0/1
     rollup: t1
     tabletRatio=0/0
     tabletList=
     cardinality=1
     avgRowSize=4.0
```

after:
```
  4:Project
  |  <slot 10> : 1
  |  <slot 11> : 1
  |  <slot 12> : 1
  |  
  3:OlapScanNode
     TABLE: t1
     PREAGGREGATION: ON
     partitions=0/1
     rollup: t1
     tabletRatio=0/0
     tabletList=
     cardinality=1
     avgRowSize=25.0
```

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:heart_eyes: **pass** : 5 / 5 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/runtime/descriptors.cpp|5|5|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:heart_eyes: **pass** : 6 / 6 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/runtime/descriptors.cpp|6|6|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:heart_eyes: **pass** : 4 / 4 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/runtime/descriptors.cpp|4|4|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:heart_eyes: **pass** : 4 / 4 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/runtime/descriptors.cpp|4|4|100.00%|[]|

**Review by kangkaisen — APPROVED** [review]

**Review by packy92 — APPROVED** [review]

**Pull request merged**
