### PR TITLE
Add prune Iceberg scan column rule

### PR DESCRIPTION
**Pull request by caneGuy**
related with #1030 
This pr will prune unnecessary column during scanning. Which will make query consume less memory.
before
```
PLAN FRAGMENT 24
 OUTPUT EXPRS:
  PARTITION: RANDOM

  STREAM DATA SINK
    EXCHANGE ID: 06
    UNPARTITIONED

  5:Project
  |  <slot 52> : 52: ca_address_sk
  |  <slot 59> : 59: ca_county
  |
  4:IcebergScanNode
     TABLE: customer_address
     cardinality=250000
     avgRowSize=19.8634
     numNodes=0
```
after
```
PLAN FRAGMENT 24
 OUTPUT EXPRS:
  PARTITION: RANDOM

  STREAM DATA SINK
    EXCHANGE ID: 03
    UNPARTITIONED

  2:IcebergScanNode
     TABLE: customer_address
     cardinality=250000
     avgRowSize=5.48192
     numNodes=0
```

### CODE REVIEW

**Comment by caneGuy** [comment]
cc @DorianZheng @dirtysalt @stephen-shelby

**Comment by dirtysalt** [comment]
Does `PruneIcebergScanColumnRule` share a lot code with `PruneHiveScanColumnRule`? Could we extract a common class to handle both? It's very hard to maintain both hive and iceberg rules.

**Comment by caneGuy** [comment]
> Does `PruneIcebergScanColumnRule` share a lot code with `PruneHiveScanColumnRule`? Could we extract a common class to handle both? It's very hard to maintain both hive and iceberg rules.

i will change later @dirtysalt

**Comment by caneGuy** [comment]
> > Does `PruneIcebergScanColumnRule` share a lot code with `PruneHiveScanColumnRule`? Could we extract a common class to handle both? It's very hard to maintain both hive and iceberg rules.
> 
> I will refactor these codes later @dirtysalt

I refactored this code
 PTAL thanks!

**Review by dirtysalt — APPROVED** [review]

**Comment by DorianZheng** [comment]
@Seaven PTAL

**Review by Seaven — APPROVED** [review]

**Review by DorianZheng — APPROVED** [review]

**Comment by kangkaisen** [comment]
@caneGuy You should add UT for the your change.

**Pull request merged**
