### PR TITLE
[BugFix] fix some error handling bugs

### LINKED ISSUE #27033: ExchangeSourceOperator doesn't handle error correctly during prepare
### Steps to reproduce the behavior (Required)
1. I tried to inject a rand error in Operator::prepare
image

2. them run some random queries and be crashes at the following line

image

3. this is because ExchangeSourceOperator doesn't handle prepare error correctly
image

### StarRocks version (Required)
main 754a8f4f6ea7f3c44224dcb4ca02044b7a421fee

### PR DESCRIPTION
**Pull request by silverbullet233**
Fixes #27033 #27160

## What type of PR is this:
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [x] 3.0
  - [x] 2.5
  - [x] 2.4

### CODE REVIEW

**Review by stdpain — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Pull request closed without merging**
