### PR TITLE
[Enhancement] output more thread metrics for PrometheusMetricVisitor

### PR DESCRIPTION
**Pull request by goldenbean**
Fixes #issue

## What type of PR is this:
- [ ] BugFix
- [ ] Feature
- [X] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [X] I have checked the version labels which the pr will be auto-backported to the target branch
  - [X] 3.1
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4

### CODE REVIEW

**Review by gengjun-git — DISMISSED** [review]

**Review by kangkaisen — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:disappointed: **fail** : 0 / 42 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/monitor/jvm/JvmStats.java|0|36|00.00%|[105, 294, 295, 307, 311, 315, 319, 323, 327, 333, 334, 335, 336, 337, 338, 339, 340, 345, 346, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 367]|
|:large_blue_circle:|com/starrocks/metric/PrometheusMetricVisitor.java|0|6|00.00%|[167, 168, 169, 170, 171, 172]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:disappointed: **fail** : 31 / 42 (73.81%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/monitor/jvm/JvmStats.java|25|36|69.44%|[333, 334, 335, 336, 337, 338, 339, 340, 359, 362, 363]|
|:large_blue_circle:|com/starrocks/metric/PrometheusMetricVisitor.java|6|6|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:disappointed: **fail** : 31 / 48 (64.58%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/common/proc/JvmProcDir.java|0|6|00.00%|[96, 97, 98, 99, 100, 101]|
|:large_blue_circle:|com/starrocks/monitor/jvm/JvmStats.java|25|36|69.44%|[333, 334, 335, 336, 337, 338, 339, 340, 359, 362, 363]|
|:large_blue_circle:|com/starrocks/metric/PrometheusMetricVisitor.java|6|6|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Pull request closed without merging**
