### PR TITLE
[Enhancement] Optimizing information for tables

### LINKED ISSUE #9498: Improve the Information_schema

### PR DESCRIPTION
**Pull request by waittttting**
## What type of PR is this：
- [ ] bugfix
- [ ] feature
- [x] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #9498

## Problem Summary(Required) ：

Optimizing information for tables
1. Refactoring the way the tables gets data
2. TABLE_CATALOG: Use 'def' as the default value
3. TABLE_TYPE: Show specific table types
4. TABLE_ROWS, AVG_ROW_LENGTH, DATA_LENGTH, UPDATE_TIME: Fill with more accurate values

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by waittttting** [comment]
run starrocks_clang-tidy

**Comment by waittttting** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 0 / 87 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/service/FrontendServiceImpl.java|0|1|00.00%|[1323]|
|:large_blue_circle:|com/starrocks/service/InformationSchemaDataSource.java|0|86|00.00%|[30, 32, 42, 43, 44, 46, 47, 48, 49, 50, 53, 54, 55, 57, 58, 59, 61, 63, 64, 65, 68, 69, 70, 72, 73, 74, 79, 80, 81, 82, 83, 84, 85, 87, 88, 89, 91, 92, 93, 94, 95, 96, 97, 101, 102, 103, 104, 105, 107, 108, 109, 110, 111, 113, 114, 115, 120, 126, 129, 130, 132, 135, 136, 137, 142, 143, 144, 145, 146, 147, 148, 150, 151, 152, 154, 156, 157, 159, 162, 164, 165, 169, 170, 171, 172, 173]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 79 / 87 (90.80%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/service/FrontendServiceImpl.java|0|1|00.00%|[1323]|
|:large_blue_circle:|com/starrocks/service/InformationSchemaDataSource.java|79|86|91.86%|[30, 48, 49, 59, 65, 70, 157]|

**Comment by waittttting** [comment]
run starrocks_admit_test

**Comment by waittttting** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 79 / 87 (90.80%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/service/FrontendServiceImpl.java|0|1|00.00%|[1464]|
|:large_blue_circle:|com/starrocks/service/InformationSchemaDataSource.java|79|86|91.86%|[30, 48, 49, 59, 65, 70, 157]|

**Review by gengjun-git — APPROVED** [review]

**Comment by waittttting** [comment]
run starrocks_admit_test

**Review by Astralidea — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 79 / 87 (90.80%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/service/FrontendServiceImpl.java|0|1|00.00%|[1462]|
|:large_blue_circle:|com/starrocks/service/InformationSchemaDataSource.java|79|86|91.86%|[30, 48, 49, 59, 65, 70, 157]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 79 / 87 (90.80%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/service/FrontendServiceImpl.java|0|1|00.00%|[1462]|
|:large_blue_circle:|com/starrocks/service/InformationSchemaDataSource.java|79|86|91.86%|[30, 48, 49, 59, 65, 70, 157]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 79 / 87 (90.80%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/service/FrontendServiceImpl.java|0|1|00.00%|[1462]|
|:large_blue_circle:|com/starrocks/service/InformationSchemaDataSource.java|79|86|91.86%|[30, 48, 49, 59, 65, 70, 157]|

**Pull request merged**
