### PR TITLE
[Feature]Add more info to routine load metrics

### PR DESCRIPTION
**Pull request by hongli-my**
## What type of PR is this：
- [ ] bug
- [X] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

1.   add `database name`, `table name`, `routine load name` to  routine_load_jobs  metrics's  label
2.  only `master fe` expose  `routine_load_jobs` metrics, because `state`  not `sync to follower`,   curl `every fe 8040/metircs`  have difference value, so remove it.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by hongli-my** [comment]
PTAL @kangkaisen      

unittest maybe have some problems?

**Comment by hongli-my** [comment]
run starrocks_fe_unittest

**Comment by kangkaisen** [comment]
run starrocks_fe_unittest

**Comment by kangkaisen** [comment]
> PTAL @kangkaisen
> 
> unittest maybe have some problems?

We will fix the untable UT ASAP.

**Comment by kangkaisen** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 0 / 20 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/metric/MetricRepo.java|0|20|00.00%|[506, 621, 622, 623, 625, 626, 630, 631, 633, 635, 637, 638, 639, 640, 641, 642, 643, 645, 646, 647]|

**Pull request closed without merging**
