### PR TITLE
[BugFix] Fix unstable UT testUpdateResourceUsage and SetPasswordTest

### PR DESCRIPTION
**Pull request by ZiheLiu**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Problem Summary(Required) ：

#15452 adds a new UT in `FrontendServiceImplTest`, which invokes `createMinStarRocksCluster` in `FrontendServiceImplTest::beforeClass`, which will call `GlobalStateMgr.getCurrentSystemInfo().getBackendIds` in daemon.

`FrontendServiceImplTest::testUpdateResourceUsage` mocks the object  `GlobalStateMgr.getCurrentSystemInfo()`, but doesn't mock the method `getBackendIds`.
Therefore, when calling `getBackendIds` by daemon, the UT will fail.

Use `MockUp` to only mock the specific methods, not the object.
`SetPasswordTest` is similar as it.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Comment by ZiheLiu** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by ZiheLiu** [comment]
run starrocks_admit_test

**Review by Seaven — APPROVED** [review]

**Review by kangkaisen — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
