### PR TITLE
Cleanup some unused test datas

### PR DESCRIPTION
**Pull request by xlwh**
## What type of PR is this：
- [ ] bug
- [ ] feature
- [ ] enhancement
- [x] others

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：
Some useless test data files need to be deleted. thanks.

### CODE REVIEW

**Comment by mofeiatwork** [comment]
Did you do this manually? Or some tools?

**Comment by xlwh** [comment]
> 
No tools. But it looks like there is an unrelated failure in the CI test, I'll look at it later, thanks!

**Comment by imay** [comment]
> 

This failure test may not be caused by your change. You could rebase main branch, push, and run the test again to see if the test will pass.

**Comment by xlwh** [comment]
> > 
> 
> This failure test may not be caused by your change. You could rebase main branch, push, and run the test again to see if the test will pass.

OK, thanks!

**Review by imay — APPROVED** [review]
LGTM

**Pull request merged**
