### PR TITLE
[BugFix] enable non-general jdbc class can be loaded

### LINKED ISSUE #32718: query oracle timestamp column via jdbc return error
### Steps to reproduce the behavior (Required)
1. create table in oracle
```sql
create table tbl_oracle_type_text_date (
 type_timestamp timestamp(6)
);
```
2. insert some data into oracle table
3. create jdbc external table and query
```sql
create external resource oracle_test
                properties (
                    "type"="jdbc",
                    "user"="xx",
                    "password"="xx",
                    "jdbc_uri"="xx",
                    "driver_url"="file:///home/ojdbc6-11.2.0.4.jar",
                    "driver_class"="oracle.jdbc.driver.OracleDriver"
                );
create external table jdbc_ext_tbl_oracle_type_timestamp_test (
type_timestamp datetime
) ENGINE=jdbc PROPERTIES (
    "resource"="oracle_test",
    "table"="tbl_oracle_type_text_date"
);
select * from jdbc_ext_tbl_oracle_type_timestamp_test;
```
### Expected behavior (Required)
return result successfully
### Real behavior (Required)
```sql
mysql> select * from jdbc_ext_tbl_oracle_type_timestamp_test;
ERROR 1064 (HY000): open JDBCScanner failed, error: java.lang.ClassNotFoundException: oracle.sql.TIMESTAMP
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.starrocks.jdbcbridge.JDBCScanner.open(JDBCScanner.java:76)
```
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by silverbullet233**
Fixes #32718

root casue: JDBCScanner used the wrong class loader, causing the jdbc driver's custom class to not be loaded correctly.

The current behavior of jdbc external table query is to ensure that the returned data is complete. If the data type of SR cannot fully represent the data in the external table, the query will directly report an error, such as a varchar's length overflow or the data exceeds the value range.

Going back to the bug itself, the results returned by many jdbc drivers may be represented by internally defined java classes. For example, Oracle will use `orcale.sql.TIMESTAMP` to represent the timestamp type. Before this, because SR did not know how to convert it into its own internal type, the query would directly report an error, which was not user-friendly.

After this change, for unrecognized JDBC result type, SR will return an error and recommend that users specify it as string type when creating a table, and then directly return the string representation of the data, and then the user can process the data himself.

so, for this issue,  if we recreate external table like the following, the query will execute successfully.
```sql
create external table jdbc_ext_tbl_oracle_type_timestamp_test (
type_timestamp string
) ENGINE=jdbc PROPERTIES (
    "resource"="oracle_test",
    "table"="tbl_oracle_type_text_date"
);
```

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [x] Yes, this PR will result in a change in behavior.
- [ ] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [x] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.2
  - [x] 3.1
  - [x] 3.0
  - [x] 2.5

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 0 / 5 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/exec/jdbc_scanner.cpp|0|5|00.00%|[287, 288, 289, 291, 293]|

**Review by stdpain — APPROVED** [review]

**Review by Seaven — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.2

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
