### PR TITLE
[Enhancement] more control on cbo

### PR DESCRIPTION
**Pull request by dirtysalt**
## What type of PR is this：
- [ ] bug
- [ ] feature
- [x] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

summary
===
This PR is to have more control on CBO:
1. put `aliveBackendNumber` and `totalBackendNumebr` into ConnectContext.It's more modular.
2. refactor init of `ConnectContext`, to share a common init function.
3. add session variable `broadcast_right_table_scale_factor`
4. add session variable `cbo_debug_alive_backend_number` to fake alive backend number(which will affect final plan)
5. rename `backendSize` to `getTotalBackendNumber`

rationale
===

The variable `cbo_debug_alive_backend_number` can be very useful. You can emulate running a query on 50 machines, and spot plan bug as soon as possible without actually deploying our planner on 50 machines.

__following are deleted__
`cbo_enable_derived_predicate_when_column_stats_missing` is to avoid bad plan(tpch-100g q2) by this PR. https://github.com/StarRocks/starrocks/pull/8219/files. I suspect a lot of derived predicate will affect statistics and finally affect plan. Perhaps there is a better solution but I've tried my best. 

```
select
  s_acctbal,
  s_name,
  n_name,
  p_partkey,
  p_mfgr,
  s_address,
  s_phone,
  s_comment
from
  part,
  supplier,
  partsupp,
  nation,
  region
where
  p_partkey = ps_partkey
  and s_suppkey = ps_suppkey
  and p_size = 15
  and p_type like '%BRASS'
  and s_nationkey = n_nationkey
  and n_regionkey = r_regionkey
  and r_name = 'EUROPE'
  and ps_supplycost = ( 
    select
      min(ps_supplycost)
    from
      partsupp,
      supplier,
      nation,
      region
    where
      p_partkey = ps_partkey
      and s_suppkey = ps_suppkey
      and s_nationkey = n_nationkey
      and n_regionkey = r_regionkey
      and r_name = 'EUROPE'
  )
order by
  s_acctbal desc,
  n_name,
  s_name,
  p_partkey limit 100
```

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 47 / 48 (97.92%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/ConnectContext.java|8|9|88.89%|[559]|
|:large_blue_circle:|com/starrocks/qe/SessionVariable.java|8|8|100.00%|[]|
|:large_blue_circle:|com/starrocks/http/rest/TransactionLoadAction.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/PushDownJoinPredicateBase.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/system/SystemInfoService.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/scalar/IsNullPredicateOperator.java|7|7|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/Utils.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/statistics/PredicateStatisticsCalculator.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/task/EnforceAndCostTask.java|6|6|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/dump/QueryDumpSerializer.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/cost/CostModel.java|5|5|100.00%|[]|

**Comment by kangkaisen** [comment]
I don't think we need to mock the query plan by this way, you could do this work in UT. refer to `DistributedEnvPlanTestBase` and `ReplayFromDumpTest`.  we should make the code clean and simple.

**Comment by dirtysalt** [comment]
> I don't think we need to mock the query plan by this way, you could do this work in UT. refer to `DistributedEnvPlanTestBase` and `ReplayFromDumpTest`. we should make the code clean and simple.

Yes, but when you want to reproduce user case in your local env, it's quite laboring. 

And `DistributedEnvPlanTestBase` and `ReplayFromDumpTest` don't work well with lake right now.

**Comment by kangkaisen** [comment]
> > I don't think we need to mock the query plan by this way, you could do this work in UT. refer to `DistributedEnvPlanTestBase` and `ReplayFromDumpTest`. we should make the code clean and simple.
> 
> Yes, but when you want to reproduce user case in your local env, it's quite laboring.
> 
> And `DistributedEnvPlanTestBase` and `ReplayFromDumpTest` don't work well with lake right now.

So, I think you first should do is making UT support lake,  UT is a better way that reproduce user case in local env.

**Review by kangkaisen — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 30 / 31 (96.77%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/ConnectContext.java|8|9|88.89%|[559]|
|:large_blue_circle:|com/starrocks/qe/SessionVariable.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/http/rest/TransactionLoadAction.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/system/SystemInfoService.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/Utils.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/task/EnforceAndCostTask.java|6|6|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/dump/QueryDumpSerializer.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/cost/CostModel.java|5|5|100.00%|[]|

**Review by Seaven — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by Seaven** [comment]
I don't recommend add debug flag in SessionVariable too...

**Comment by dirtysalt** [comment]
> I don't recommend add debug flag in SessionVariable too...

Got it. We can remove it anytime if necessary.

**Pull request merged**
