### PR TITLE
[BugFix] BinlogConfig buildFromProperties fix

### PR DESCRIPTION
**Pull request by beanflower-bs**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

fix the incorrect logic of BinlogConfig.java

## Problem Summary(Required) ：

change it

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 0 / 1 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/binlog/BinlogConfig.java|0|1|00.00%|[68]|

**Comment by beanflower-bs** [comment]
> #### [FE PR Coverage Check]
> 😞 **fail** : 0 / 1 (00.00%)
> 
> #### file detail
> path	covered_line	new_line	coverage	not_covered_line_detail
> 🔵	com/starrocks/binlog/BinlogConfig.java	0	1	00.00%	[68]

already add BinlogConfigTest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/binlog/BinlogConfig.java|1|1|100.00%|[]|

**Comment by imay** [comment]
@beanflower-bs thanks for your contribution, could you sign the CLA?

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/binlog/BinlogConfig.java|1|1|100.00%|[]|

**Comment by beanflower-bs** [comment]
@imay I already sign the CLA!

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/binlog/BinlogConfig.java|1|1|100.00%|[]|

**Review by imay — APPROVED** [review]

**Comment by imay** [comment]
@beanflower-bs Thank you and congratulate to be the 200th contributor.

**Pull request merged**
