### PR TITLE
[BugFix] Don't limit scan threads for stream load to avoid deadlock (backport #31929)

### PR DESCRIPTION
**Pull request by banmoy**
Fixes #issue

## What type of PR is this:

- [X] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [ ] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [X] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 25 / 41 (60.98%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/exec/connector_scan_node.cpp|14|25|56.00%|[400, 401, 411, 412, 413, 414, 415, 416, 417, 418, 419]|
|:large_blue_circle:|src/runtime/exec_env.cpp|8|13|61.54%|[183, 184, 185, 189, 190]|
|:large_blue_circle:|src/util/threadpool.cpp|3|3|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 26 / 44 (59.09%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/exec/connector_scan_node.cpp|15|28|53.57%|[400, 401, 411, 412, 413, 414, 415, 416, 417, 418, 419, 433, 434]|
|:large_blue_circle:|src/runtime/exec_env.cpp|8|13|61.54%|[183, 184, 185, 189, 190]|
|:large_blue_circle:|src/util/threadpool.cpp|3|3|100.00%|[]|

**Review by trueeyu — APPROVED** [review]

**Pull request merged**
