### PR TITLE
[BugFix] Disable broker load retry

### PR DESCRIPTION
**Pull request by meegoo**
## What type of PR is this：
- [x] bugfix
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Review by sevev — APPROVED** [review]

**Review by rickif — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/load/loadv2/LoadLoadingTask.java|1|1|100.00%|[]|

**Review by chaoyli — APPROVED** [review]

**Review by trueeyu — APPROVED** [review]

**Comment by meegoo** [comment]
@mergify backport branch-2.4 branch-2.3 branch-2.2

**Comment by meegoo** [comment]
@mergify backport branch-2.1

**Pull request merged**
