### PR TITLE
[Enhancement] Support auto_refresh_partitions_limit for periodic refresh mv task

### PR DESCRIPTION
**Pull request by Youngwb**
## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 3.0
  - [x] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 46 / 55 (83.64%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/scheduler/MvTaskRunContext.java|1|2|50.00%|[95]|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|8|13|61.54%|[1510, 1511, 3034, 3978, 3979]|
|:large_blue_circle:|com/starrocks/scheduler/TaskRunContext.java|2|3|66.67%|[70]|
|:large_blue_circle:|com/starrocks/scheduler/TaskRun.java|3|4|75.00%|[107]|
|:large_blue_circle:|com/starrocks/sql/common/SyncPartitionUtils.java|17|18|94.44%|[393]|
|:large_blue_circle:|com/starrocks/scheduler/PartitionBasedMaterializedViewRefreshProcessor.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/scheduler/TaskRunBuilder.java|5|5|100.00%|[]|
|:large_blue_circle:|com/starrocks/scheduler/TaskManager.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/scheduler/ExecuteOption.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/transaction/PublishVersionDaemon.java|2|2|100.00%|[]|

**Review by Astralidea — APPROVED** [review]

**Review by gengjun-git — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
