### PR TITLE
[BugFix] Fix ignore password not working

### LINKED ISSUE #18267: [access control]set enable_auth_check = false, can's connect SR
### Steps to reproduce the behavior (Required)
1.modify fe.conf
add 
enable_auth_check = false
2.restart fe
3.connect SR
mysql -hxxx.xx.xx.xxx -P9232 -uroot
### Expected behavior (Required)
connect success
### Real behavior (Required)
connect failed
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
mysql> select current_version();
+------------------------+
| current_version()      |
+------------------------+
| 3.0.0-20230222 bf84ae2 |
+------------------------+
1 row in set (0.05 sec)

### PR DESCRIPTION
**Pull request by nshangyiming**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #18267

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 3.0
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 34 / 44 (77.27%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/mysql/MysqlProto.java|7|14|50.00%|[85, 86, 87, 88, 89, 90, 92]|
|:large_blue_circle:|com/starrocks/qe/ShowExecutor.java|4|7|57.14%|[1993, 2037, 2039]|
|:large_blue_circle:|com/starrocks/authentication/AuthenticationManager.java|23|23|100.00%|[]|

**Comment by nshangyiming** [comment]
run starrocks_admit_test

**Review by gengjun-git — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 36 / 46 (78.26%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/mysql/MysqlProto.java|7|14|50.00%|[87, 88, 89, 90, 91, 92, 94]|
|:large_blue_circle:|com/starrocks/qe/ShowExecutor.java|4|7|57.14%|[1993, 2037, 2039]|
|:large_blue_circle:|com/starrocks/authentication/AuthenticationManager.java|25|25|100.00%|[]|

**Review by HangyuanLiu — APPROVED** [review]

**Review by gengjun-git — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Pull request merged**
