### PR TITLE
[BugFix] Routine load name with backquotes

### LINKED ISSUE #11550: identifier with backquotes in `ROUTINE LOAD`  stmt cannot be parsed correctly
### Steps to reproduce the behavior (Required)
The following statement, where the identifier is quoted with backquotes cannot be parsed correctly.
```
show routine load for `db_test`.`rl_test`
pause routine load for `db_test.`rl_test`
resume routine load for `db_test`.`rl_test`
stop routine load for `db_test`.`rl_test`
alter routine load for `db_test`.`rl_tset` ...
show routine load task from `db_test` where jobname = "rl_trest"
```

### Expected behavior (Required)
The correct result is returned.
### Real behavior (Required)
The db name and the routine load name are parsed with backquotes.
```
ERROR 1064 (HY000): failed to find database by dbFullName `db`
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by rickif**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes https://github.com/StarRocks/starrocks/issues/11550

## Problem Summary(Required) ：

The new parser cannot handle the identifiers with backquotes. This PR is to fix the problem and keep compatible with old versions.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 1 / 4 (25.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|1|4|25.00%|[1809, 1822, 1835]|

**Review by chaoyli — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 9 / 9 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|9|9|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 2 / 3 (66.67%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/analysis/ShowRoutineLoadTaskStmt.java|1|2|50.00%|[91]|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|1|1|100.00%|[]|

**Review by chaoyli — APPROVED** [review]

**Comment by rickif** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 8 / 11 (72.73%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/analysis/ShowRoutineLoadTaskStmt.java|1|2|50.00%|[91]|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|7|9|77.78%|[1809, 1813]|

**Review by HangyuanLiu — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Pull request merged**
