### PR TITLE
[Bugfix] Fix negative scale for function round/truncate

### LINKED ISSUE #10267: ROUND doesn't work with negative input
### Steps to reproduce the behavior (Required)
it's expected to return  `10` for the query  `mysql> select round(13.14,-1);` but it returns `13`

### Expected behavior (Required)
it's expected to return  `10` for the query  `mysql> select round(13.14,-1);` but it returns `13`

### Real behavior (Required)
image

### StarRocks version (Required)
 - `2.2.5`

### PR DESCRIPTION
**Pull request by liuyehcf**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #10267

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [x] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by liuyehcf** [comment]
run starrocks_admit_test

**Comment by liuyehcf** [comment]
run starrocks_admit_test

**Review by satanson — APPROVED** [review]

**Review by kangkaisen — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by liuyehcf** [comment]
Admit test failed, because the failed cases should also be updated.

**Comment by kangkaisen** [comment]
run starrocks_admit_test

**Comment by liuyehcf** [comment]
run starrocks_admit_test

**Comment by liuyehcf** [comment]
run starrocks_admit_test

**Comment by liuyehcf** [comment]
run starrocks_admit_test

**Comment by liuyehcf** [comment]
@Mergifyio backport branch-2.2

**Comment by liuyehcf** [comment]
@Mergifyio backport branch-2.3

**Comment by liuyehcf** [comment]
@Mergifyio backport branch-2.4

**Pull request merged**
