### PR TITLE
[Feature] support user variable hint

### PR DESCRIPTION
**Pull request by packy92**
Why I'm doing:
Users want use user variable hint in query scope.  #32024

What I'm doing:
1. support /*+ set_user_variable() */ hint. The user variable only takes effect in this query and will be removed after finished.
2. HintCollector collects all query scope hint info.  Set all query scope hints in`statementBase.allQueryScopeHints`.  `StmtExecutor` initials hint info before analyze and plan and finally remove hint info in connect context.
3. extract hints in clause and set them in `statementBase.hintNodes` or `selectList.hintNodes` to build sql string from ast like previous.

A simple example:
user variables are replaced with value in query stmt.
image
user variables had been cleaned.
image

Fixes #issue

## What type of PR is this:

- [ ] BugFix
- [x] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Comment by Seaven** [comment]
if I write `select /+user_variable(select /+user_variable(select /+..../)/)/`, how to execute?

**Comment by packy92** [comment]
> if I write `select /+user_variable(select /+user_variable(select /+..../)/)/`, the nest sql how to execute?
like 
```
select /*+ set_user_variable(
    @a = (select 
    /*+set_var(query_timeout = 1) */  
    c1 from t1 limit 1 )
    ) */ 
    @a from t1;
```
the parser regards`/*+ set_user_variable(
    @a = (select 
    /*+set_var(query_timeout = 1) */ ` as a hint in hidden channel, so any nested hint query is unsupported.

**Review by kangkaisen — DISMISSED** [review]

**Review by liuyehcf — DISMISSED** [review]

**Review by liuyehcf — APPROVED** [review]

**Review by murphyatwork — APPROVED** [review]

**Comment by packy92** [comment]
@mergify backport branch-3.2

**Comment by jaogoy** [comment]
@packy92 Does this PR fix issue #39819?

**Comment by jaogoy** [comment]
@packy92 what's the difference between these two pictures?

**Pull request merged**
