### PR TITLE
[BugFix] Fix mv refresh bug when mv's original query has extra predicates (#29808)

### PR DESCRIPTION
**Pull request by LiShuMing**
[[BugFix] Add enable_materialized_view_rewrite_greedy_mode param to co](https://github.com/StarRocks/starrocks/commit/68e0aaf9d931b4891c7b0e74d98bdf1d06d76941)

[Fix mv refresh bug when mv's original query has extra predicates (](https://github.com/StarRocks/starrocks/commit/d2208ba78ee6f165fd814285aff2455ce2569a0b)https://github.com/StarRocks/starrocks/pull/29808
## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 56 / 60 (93.33%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/MaterializedView.java|6|7|85.71%|[875]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java|16|18|88.89%|[1110, 2284]|
|:large_blue_circle:|com/starrocks/sql/optimizer/MvRewritePreprocessor.java|12|13|92.31%|[239]|
|:large_blue_circle:|com/starrocks/qe/SessionVariable.java|5|5|100.00%|[]|
|:large_blue_circle:|com/starrocks/common/Log4jConfig.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rewrite/scalar/MvNormalizePredicateRule.java|13|13|100.00%|[]|
|:large_blue_circle:|com/starrocks/alter/AlterJobMgr.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 56 / 60 (93.33%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/MaterializedView.java|6|7|85.71%|[875]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java|16|18|88.89%|[1110, 2284]|
|:large_blue_circle:|com/starrocks/sql/optimizer/MvRewritePreprocessor.java|12|13|92.31%|[239]|
|:large_blue_circle:|com/starrocks/qe/SessionVariable.java|5|5|100.00%|[]|
|:large_blue_circle:|com/starrocks/common/Log4jConfig.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rewrite/scalar/MvNormalizePredicateRule.java|13|13|100.00%|[]|
|:large_blue_circle:|com/starrocks/alter/AlterJobMgr.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 49 / 60 (81.67%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/MvRewritePreprocessor.java|7|12|58.33%|[240, 241, 242, 246, 247]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rewrite/scalar/MvNormalizePredicateRule.java|11|15|73.33%|[49, 51, 53, 80]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java|14|16|87.50%|[156, 264]|
|:large_blue_circle:|com/starrocks/catalog/MaterializedView.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/scheduler/PartitionBasedMvRefreshProcessor.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/qe/SessionVariable.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/common/Log4jConfig.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/MvUtils.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/alter/AlterJobMgr.java|1|1|100.00%|[]|

**Review by murphyatwork — APPROVED** [review]

**Pull request merged**
