### PR TITLE
[BugFix] round double/float to decimal in BE

### PR DESCRIPTION
**Pull request by fzhedu**
## What type of PR is this:
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes:

Fixes #

## Problem Summary(Required):

round double/float to decimal in BE, keep consisten with FE and MySQL.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 3.0
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Review by stdpain — DISMISSED** [review]

**Review by satanson — DISMISSED** [review]

**Review by silverbullet233 — DISMISSED** [review]

**Review by kangkaisen — DISMISSED** [review]

**Review by imay — APPROVED** [review]

**Review by murphyatwork — APPROVED** [review]

**Review by packy92 — APPROVED** [review]

**Comment by fzhedu** [comment]
@mergify backport branch-3.0

**Comment by fzhedu** [comment]
@mergify backport branch-2.5

**Comment by fzhedu** [comment]
@mergify backport branch-2.4

**Comment by fzhedu** [comment]
@mergify backport branch-2.3

**Pull request merged**
