### PR TITLE
[Refactor] set defineExpr use new parser

### PR DESCRIPTION
**Pull request by Astralidea**
## What type of PR is this：
- [ ] bug
- [ ] feature
- [ ] enhancement
- [x] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

DefineExpr was parsed with the old parser before, but the new one was used when building the table, so there may be a problem of inconsistent statements. So we switch to the new one to cover all the old parsing cases.

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 14 / 18 (77.78%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/analysis/CreateMaterializedViewStmt.java|8|11|72.73%|
|:large_blue_circle:|com/starrocks/catalog/MaterializedIndexMeta.java|3|4|75.00%|
|:large_blue_circle:|com/starrocks/alter/RollupJobV2.java|3|3|100.00%|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 14 / 18 (77.78%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/analysis/CreateMaterializedViewStmt.java|8|11|72.73%|
|:large_blue_circle:|com/starrocks/catalog/MaterializedIndexMeta.java|3|4|75.00%|
|:large_blue_circle:|com/starrocks/alter/RollupJobV2.java|3|3|100.00%|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 14 / 18 (77.78%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/analysis/CreateMaterializedViewStmt.java|8|11|72.73%|
|:large_blue_circle:|com/starrocks/catalog/MaterializedIndexMeta.java|3|4|75.00%|
|:large_blue_circle:|com/starrocks/alter/RollupJobV2.java|3|3|100.00%|

**Review by kangkaisen — APPROVED** [review]

**Review by HangyuanLiu — APPROVED** [review]

**Comment by Astralidea** [comment]
@Mergifyio backport branch-2.3

**Pull request merged**
