### PR TITLE
[BugFix] Fix bug primary key table does not display current_timestamp

### LINKED ISSUE #24237: about “show create table” bug
### Steps to reproduce the behavior (Required)

1. create table test_db.test
( id int(9), 
create_time datetime NOT NULL DEFAULT current_timestamp )
ENGINE=OLAP
PRIMARY KEY (`id`)
DISTRIBUTED BY HASH(`id`) BUCKETS 5

2. show create table test_db.test

3. result  ： CREATE TABLE `test` ( `id` int(11) NOT NULL COMMENT "", **`create_time` datetime NOT NULL COMMENT ""** ) ENGINE=OLAP PRIMARY KEY(`id`) COMMENT "OLAP" DISTRIBUTED BY HASH(`id`) BUCKETS 5 PROPERTIES ( "replication_num" = "3", "in_memory" = "false", "storage_format" = "DEFAULT" );

4.create table test_db.test
( id int(9), 
create_time datetime NOT NULL DEFAULT current_timestamp )
ENGINE=OLAP
DISTRIBUTED BY HASH(`id`) BUCKETS 5

5.show create table test_db.test

6.result  ：CREATE TABLE `test` ( `id` int(11) NULL COMMENT "", **`create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT ""** ) ENGINE=OLAP DUPLICATE KEY(`id`, `create_time`) COMMENT "OLAP" DISTRIBUTED BY HASH(`id`) BUCKETS 10 PROPERTIES ( "replication_num" = "3", "in_memory" = "false", "storage_format" = "DEFAULT" );

### Expected behavior (Required)

This happens only when PRIMARY KEY is used, and it does not happen when using UNIQUE KEY, DUPLICATE KEY or not using PRIMARY KEY，it should be fixed

### Real behavior (Required)
image

### StarRocks version (Required)
starrocks-2.4.3、        
starrocks-2.2.2

### PR DESCRIPTION
**Pull request by Astralidea**
Fixes #24237

## What type of PR is this:
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.0
  - [x] 2.5
  - [x] 2.4
  - [ ] 2.3

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 5 / 7 (71.43%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/Column.java|5|7|71.43%|[607, 615]|

**Review by gengjun-git — APPROVED** [review]

**Review by ABingHuang — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.4

**Pull request merged**
