### PR TITLE
[Refactor] rename resource_group to resource group in parser

### PR DESCRIPTION
**Pull request by murphyatwork**
## What type of PR is this：
- [ ] bug
- [ ] feature
- [ ] enhancement
- [x] others

## Which issues of this PR fixes ：

Fixes #

### CODE REVIEW

**Review by satanson — APPROVED** [review]

**Comment by kangkaisen** [comment]
please submit the document PR at the same time.

**Comment by kangkaisen** [comment]
https://github.com/StarRocks/docs.zh-cn/pull/599 The doc PR

**Review by kangkaisen — APPROVED** [review]

**Review by HangyuanLiu — APPROVED** [review]

**Comment by mofeiatwork** [comment]
run starrocks_fe_unittest

**Comment by mofeiatwork** [comment]
run starrocks_fe_unittest

**Comment by mofeiatwork** [comment]
run starrocks_fe_unittest

**Pull request merged**
