### PR TITLE
[BugFix] fix the problem that privileges do not take effect in JDBC external table

### LINKED ISSUE #14235: jdbc extertnal table query result is error
### Steps to reproduce the behavior (Required)
1. char and varchar type , length is different
8627a608-63ed-4088-b5ef-f2145e0cf664
mysql 
image

2. oracle float
image

3. pg timestamp
image

### Expected behavior (Required)
1. error
2. sucess
3. without ms
### Real behavior (Required)
1.mysql> select * from jdbc_ext_tbl_mysql_type_char_test;
+-----------+
| type_char |
+-----------+
| abcdefgh  |
+-----------+
1 row in set (0.01 sec)

mysql> select * from jdbc_ext_tbl_mysql_type_varchar_test;
+--------------+
| type_varchar |
+--------------+
| abcdefgh     |
+--------------+
1 row in set (0.02 sec)

2. failed

3.
mysql> select * from jdbc_ext_tbl_pg_type_timestamp_test;
+----------------------------+----------------------------+
| type_timestamp             | type_timestamp2            |
+----------------------------+----------------------------+
| 0001-01-01 00:00:00.789000 | 0001-12-31 23:54:17.798000 |
| 9999-12-31 10:00:00.001000 | 9999-12-31 10:00:00.001000 |
+----------------------------+----------------------------+
2 rows in set (0.02 sec)
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
mysql> select current_version();
+----------------------------+
| current_version()          |
+----------------------------+
| BRANCH-2.5-RELEASE 1e7e914 |
+----------------------------+
1 row in set (0.01 sec)

### PR DESCRIPTION
**Pull request by silverbullet233**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #14235 #15082

## Problem Summary(Required) ：

1. fix the privilege problem when querying jdbc external table which was introduced by [#12295](https://github.com/StarRocks/starrocks/pull/12295).
We use jdbc_uri as the key in DataSourceCache to identify the connection pool, the queries with the same jdbc_uri will share the same connection pool. user will be used to authenticate when creating a connection. if we create jdbc_resources with the same jdbc_uri but different user, they will use the same connection pool, which will cause privilege confusion.
in this PR, I also add user to the key of DataSourceCache and use user+jdbc_uri as key to fix this problem.

2. I miss a problem when I fixed #14235 in #14903, I forgot to check data length for TYPE_CHAR, so fix it here.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Comment by silverbullet233** [comment]
run starrocks_admit_test

**Comment by silverbullet233** [comment]
run starrocks_be_unittest

**Comment by silverbullet233** [comment]
run starrocks_admit_test

**Review by kangkaisen — APPROVED** [review]

**Review by stdpain — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
