### PR TITLE
[BugFix] Modify the RedirectStatus of ShowRestoreStmt form FORWARD_NO_SYNC to NO_FORWARD

### LINKED ISSUE #7009: An error was reported when querying from a non-primary `FE` even though the restore task returned `finished`.
### Steps to reproduce the behavior (Required)
1. CREATE REPOSITORY '...'
```REATE REPOSITORY `backup_repository_c066d0ea_e71f_11ec_9906_00163e0e489a` with broker `hdfs_broker` on location "hdfs://xxx:9002/user/backup_repository_c066d0ea_e71f_11ec_9906_00163e0e489a" properties ( "username"= "sr","password" = "");```
2. create table.
```
 CREATE TABLE `unique_table_with_null_partition` ( `k1` date, `k2` datetime, `k3` char(20), `k4` varchar(20), `k5` boolean, `v1` tinyint, `v2` smallint, `v3` int, `v4` bigint, `v5` largeint, `v6` float, `v7` double, `v8` decimal(27,9) ) ENGINE=OLAP UNIQUE KEY(`k1`, `k2`, `k3`, `k4`, `k5`) COMMENT "OLAP" PARTITION BY RANGE(`k1`) ( PARTITION `p202006` VALUES LESS THAN ("2020-07-01"), PARTITION `p202007` VALUES LESS THAN ("2020-08-01"), PARTITION `p202008` VALUES LESS THAN ("2020-09-01") ) DISTRIBUTED BY HASH(`k1`, `k2`, `k3`, `k4`, `k5`) BUCKETS 3 PROPERTIES ( "replication_num" = "3", "storage_format" = "v2" );
```
3. load data.
```
LOAD LABEL test_backup_c065c858_e71f_11ec_9906_00163e0e489a.unique_table_with_null_partition (DATA INFILE( "hdfs://xxx:9002/user/nose-ut-data/data") INTO TABLE `unique_table_with_null_partition` )  WITH BROKER hdfs_broker ("username"="sr","password"="sr@test") PROPERTIES("timeout"="300");
```
4.truncate partition.
```
truncate table unique_table_with_null_partition partition(p202006);
```
5.restore.
```
RESTORE SNAPSHOT test_backup_c065c858_e71f_11ec_9906_00163e0e489a.`test_backup` from `backup_repository_c066d0ea_e71f_11ec_9906_00163e0e489a` on (`unique_table_with_null_partition`) PROPERTIES( "backup_timestamp"="2022-06-08-19-40-15-067", "replication_num" = "3", "timeout" = "600");
```
### Expected behavior (Required)
```
Execute sql correctly after the restore task returns `FINISHED`.
```
### Real behavior (Required)
```
select sum(cast(v1 as int)), sum(v2), sum(v3), max(v4), max(v5), min(v6), min(v7), sum(v8) from unique_table_with_null_partition;
execute sql error and messages: (1064, "Table state is not NORMAL: 'RESTORING'"), and time is: 2022-06-08 19:40:49
```
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - MAIN-RELEASE dfa20e0

### PR DESCRIPTION
**Pull request by waittttting**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #7009

## Problem Summary(Required) ：

When querying the restore task on the follower, the forward policy used before is FORWARD_NO_SYNC, which causes the restore task to be completed on the master, but the status of the table on the follower is still restoring, so If you query the data on the follower, you will get an error.
Now we have two ways to fix it, NO_FORWARD and FORWARD_WITH_SYNC, but since the two operations, fe write metadata memory and  write  log, are not atomic, so the moment when the request get restore has been finished from master, the finished log may still not generated yet, so the follower actually waits for a log id lower than the finish one, so in this case the follower thinks that the restore has finished, but the state of these tables is still restoring, and does not change the state to normal by replaying the log，you will get an error too.
so we have to choose NO_FORWARD

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/analysis/ShowRestoreStmt.java|1|1|100.00%|

**Comment by waittttting** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/analysis/ShowRestoreStmt.java|1|1|100.00%|

**Comment by waittttting** [comment]
run starrocks_fe_unittest

**Review by padmejin — APPROVED** [review]
LGTM

**Review by imay — APPROVED** [review]

**Pull request merged**
