### PR TITLE
Refactored the format in StarRocks.g4 and AstBuilder

### PR DESCRIPTION
**Pull request by HangyuanLiu**
## What type of PR is this：
- [ ] bug
- [ ] feature
- [ ] enhancement
- [x] others

## Which issues of this PR fixes ：

Fixes #

### CODE REVIEW

**Comment by HangyuanLiu** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 169 / 221 (76.47%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/analysis/AlterClause.java|0|1|00.00%|
|:large_blue_circle:|com/starrocks/sql/ast/AstVisitor.java|1|3|33.33%|
|:large_blue_circle:|com/starrocks/sql/StatementPlanner.java|5|8|62.50%|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|152|196|77.55%|
|:large_blue_circle:|com/starrocks/sql/analyzer/AlterTableStatementAnalyzer.java|7|9|77.78%|
|:large_blue_circle:|com/starrocks/analysis/DropIndexClause.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/analysis/CreateIndexClause.java|3|3|100.00%|

**Comment by HangyuanLiu** [comment]
starrocks_fe_unittest

**Comment by HangyuanLiu** [comment]
starrocks_fe_unittest

**Comment by HangyuanLiu** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 189 / 250 (75.60%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/analysis/AlterClause.java|0|1|00.00%|
|:large_blue_circle:|com/starrocks/sql/ast/AstVisitor.java|1|6|16.67%|
|:large_blue_circle:|com/starrocks/analysis/AlterTableStmt.java|2|3|66.67%|
|:large_blue_circle:|com/starrocks/analysis/AlterSystemStmt.java|3|4|75.00%|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|167|218|76.61%|
|:large_blue_circle:|com/starrocks/sql/analyzer/AlterTableStatementAnalyzer.java|8|10|80.00%|
|:large_blue_circle:|com/starrocks/analysis/DropIndexClause.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/analysis/CreateIndexClause.java|3|3|100.00%|
|:large_blue_circle:|com/starrocks/sql/StatementPlanner.java|4|4|100.00%|

**Review by kangkaisen — APPROVED** [review]

**Review by Youngwb — APPROVED** [review]

**Pull request merged**
