### PR TITLE
[BugFix] Fix bug set sql_select_limit cause query external doltdb failed

### LINKED ISSUE #18596: `SQL_SELECT_LIMIT` causes a valid query to external MySQL table to return a syntax error
Hey StarRocks, we're working with a customer who is testing out the [new support for temporal/as-of queries with external MySQL databases](https://github.com/StarRocks/starrocks/pull/13707), but we ran into an issue where the queries fail with a syntax error when the `SQL_SELECT_LIMIT` system var is set, which happens automatically by SQL workbench tools like DBeaver and DataGrip. We were able to workaround this problem by disabling the option to send `SQL_SELECT_LIMIT` in DBeaver, but wanted to circle back and see if there is a change needed on StarRocks to smooth this out. 

When `SQL_SELECT_LIMIT` is NOT set, the query is dispatched to the external MySQL instance and the correct results are returned. When `SQL_SELECT_LIMIT` is set, the query seems to fail on the frontend node with a syntax error exception, starting at the "as of" clause in the query. 

I'm guessing that when `SQL_SELECT_LIMIT` is set, StarRocks tries to pass that limit on to other queries it's dispatching to be executed. I'm not sure why the parser is failing to parse the query in this case though. 

Thanks for any help you can provide! 

### Steps to reproduce the behavior (Required)
Launch an external MySQL-compatible server on localhost:
```sql
# install Dolt
sudo bash -c 'curl -L https://github.com/dolthub/dolt/releases/latest/download/install.sh | bash'

# set up a Dolt database with some test data
mkdir doltdb
cd doltdb
dolt init
dolt sql -q "CREATE TABLE t (pk int NOT NULL, value varchar(100), PRIMARY KEY (pk));"
dolt commit -Am "Creating table t"
dolt sql -q "INSERT INTO t VALUES (1, 'one');"
dolt commit -Am "Inserting row 1"
dolt sql -q "INSERT INTO t VALUES (2, 'twooo');"
dolt commit -Am "Inserting row 2"
dolt sql -q "INSERT INTO t VALUES (100, 'one hundy!');"
dolt commit -Am "Inserting row 3"

# start the server process 
dolt sql-server -udolt --port 11223 
```

After starting an FE and BE node on localhost, connect to the FE SQL shell, configure the external MySQL table, and trigger the error: 
```sql
set enable_pipeline_engine=true;

-- Create a database to test with
create database db01;
use db01;

-- Declare the external MySQL table 
CREATE EXTERNAL TABLE mysql_external_table1
(
    pk INT,
    value VARCHAR(100)
)
ENGINE=mysql
PROPERTIES
(
    "host" = "127.0.0.1",
    "port" = "11223",
    "user" = "dolt",
    "password" = "",
    "database" = "dolt",
    "table" = "t"
);

-- Test out some queries
select * from mysql_external_table1;
select * from mysql_external_table1 as of ‘HEAD’;

-- This same query will fail with a syntax error after setting SQL_SELECT_LIMIT
SET SQL_SELECT_LIMIT=200;
select * from mysql_external_table1 as of ‘HEAD’;
```

### Expected behavior (Required)
I would expect the query above to return the same results (up to a maximum of `SQL_SELECT_LIMIT` rows) as it does when `SQL_SELECT_LIMIT` is not set. 

### Real behavior (Required)
StarRocks returns a syntax error about being unable to parse the statement when `SQL_SELECT_LIMIT` is set, but happily executes the query without any problems when `SQL_SELECT_LIMIT` is NOT set. 

### StarRocks version (Required)
2.5.2 c3772fb

### PR DESCRIPTION
**Pull request by Astralidea**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #18596

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 3.0
  - [x] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Review by ABingHuang — APPROVED** [review]

**Review by wyb — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by Astralidea** [comment]
run starrocks_admit_test

**Comment by Astralidea** [comment]
run starrocks_admit_test

**Comment by Astralidea** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
