### PR TITLE
[BugFix] Fix bug multi partition support maxvalue

### LINKED ISSUE #28594: create table for multi partition use max value
### Steps to reproduce the behavior (Required)
create table test_multi_partition(
f1 bigint, f2 date, f3 string, f4 bigint
)
partition by range(f1, f2, f4) (
	partition p1 values less than('10', '2020-01-01', '100'),
	partition p2 values less than('20', '2020-01-01', '200'),
	partition p3 values less than(MAXVALUE)
);

### Expected behavior (Required)
Error.
### Real behavior (Required)
Success.
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by Astralidea**
Fixes #28594

## What type of PR is this:
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [x] 3.0
  - [x] 2.5
  - [ ] 2.4

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 5 / 5 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/ast/RangePartitionDesc.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/PartitionKeyDesc.java|4|4|100.00%|[]|

**Review by ABingHuang — APPROVED** [review]

**Review by gengjun-git — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
