### PR TITLE
[BugFix]Fix brokerload failed when data size greater than the type defined by orc

### LINKED ISSUE #29977: broker load failed when data size greate than the type defined by orc, but sr table type is greater than datasize
### Steps to reproduce the behavior (Required)
1. CREATE TABLE `ods_info_02` (
  `status` varchar(60000) NULL COMMENT ""
) ENGINE=OLAP
DUPLICATE KEY(status)
DISTRIBUTED BY HASH(`status`)
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"enable_persistent_index" = "false",
"replicated_storage" = "true",
"compression" = "LZ4"
);

2.LOAD LABEL test.hive_to_starrocks_14_202308
(
DATA INFILE("hdfs://xxx:xxx/warehouse/tablespace/temp_db.db/ods_info_02/*")
INTO TABLE ods_info_02
FORMAT AS "ORC"(
status)
)
WITH BROKER
PROPERTIES("strict_mode"="true",
"load_mem_limit" = "2147483648",
"timeout" = "6000")
3. **starrocks throw error:**
Error: String ' C l o s e d  xxxxxx  ooo o s t' is too long. The type of 'vendor_lead_status' is VARCHAR(60000)'. Row:
4. orc type:status:varchar(30)
5. https://github.com/StarRocks/starrocks/blob/main/be/src/formats/orc/column_reader.cpp#L550C58-L550C58 _type.len always orc file type length

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by leoyy0316**
Fixes #29977 
https://github.com/StarRocks/starrocks/issues/29977

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [x] Yes, this PR will result in a change in behavior.
- [ ] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [ ] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 0 / 1 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/formats/orc/column_reader.cpp|0|1|00.00%|[574]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/formats/orc/orc_chunk_reader.cpp|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/formats/orc/orc_chunk_reader.cpp|1|1|100.00%|[]|

**Review by Smith-Cruise — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/formats/orc/orc_chunk_reader.cpp|1|1|100.00%|[]|

**Review by stephen-shelby — APPROVED** [review]

**Review by Youngwb — APPROVED** [review]

**Comment by leoyy0316** [comment]
@mergify backport branch-3.1

**Comment by leoyy0316** [comment]
@mergify backport branch-3.0

**Comment by jaogoy** [comment]
@leoyy0316 So, what't the final behavior of loading a string larger than the dest string column? Will it fail if the `strict_mode = true`?

**Comment by Smith-Cruise** [comment]
> @leoyy0316 So, what't the final behavior of loading a string larger than the dest string column? Will it fail if the `strict_mode = true`?

yes

**Pull request merged**
