### PR TITLE
[Enhancement] Support drop storage volume if exists

### PR DESCRIPTION
**Pull request by TszKitLo40**
Fixes #issue

## What type of PR is this:
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4

### CODE REVIEW

**Review by wyb — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 11 / 11 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/ast/DropStorageVolumeStmt.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/server/StorageVolumeMgr.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/qe/DDLStmtExecutor.java|8|8|100.00%|[]|

**Review by kevincai — APPROVED** [review]

**Review by silverbullet233 — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 11 / 11 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/ast/DropStorageVolumeStmt.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/server/StorageVolumeMgr.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/qe/DDLStmtExecutor.java|8|8|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 11 / 11 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/ast/DropStorageVolumeStmt.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/server/StorageVolumeMgr.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/qe/DDLStmtExecutor.java|8|8|100.00%|[]|

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 11 / 11 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/ast/DropStorageVolumeStmt.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/server/StorageVolumeMgr.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/qe/DDLStmtExecutor.java|8|8|100.00%|[]|

**Pull request merged**
