### PR TITLE
BugFix: schema change will not store the tablet to TabletInvertedIndex

### LINKED ISSUE #3952: Fe startup failure: java.lang.IllegalStateException: null
### Steps to reproduce the behavior (Required)
Do schema change concurrently.

### Expected behavior (Required)
start success.
### Real behavior (Required)
```java
2022-04-01 04:45:13,819 ERROR (stateListener|70) [EditLog.loadJournal():821] Operation Type 42
java.lang.IllegalStateException: null
        at com.google.common.base.Preconditions.checkState(Preconditions.java:494) ~[spark-dpp-1.0.0.jar:?]
        at com.starrocks.catalog.TabletInvertedIndex.addReplica(TabletInvertedIndex.java:454) ~[starrocks-fe.jar:?]
        at com.starrocks.catalog.Tablet.addReplica(Tablet.java:152) ~[starrocks-fe.jar:?]
        at com.starrocks.catalog.Tablet.addReplica(Tablet.java:158) ~[starrocks-fe.jar:?]
        at com.starrocks.catalog.Catalog.unprotectAddReplica(Catalog.java:4821) ~[starrocks-fe.jar:?]
        at com.starrocks.catalog.Catalog.replayAddReplica(Catalog.java:4841) ~[starrocks-fe.jar:?]
        at com.starrocks.persist.EditLog.loadJournal(EditLog.java:385) [starrocks-fe.jar:?]
        at com.starrocks.catalog.Catalog.replayJournal(Catalog.java:2481) [starrocks-fe.jar:?]
        at com.starrocks.catalog.Catalog.transferToMaster(Catalog.java:1220) [starrocks-fe.jar:?]
        at com.starrocks.catalog.Catalog.access$800(Catalog.java:287) [starrocks-fe.jar:?]
        at com.starrocks.catalog.Catalog$4.runOneCycle(Catalog.java:2398) [starrocks-fe.jar:?]
        at com.starrocks.common.util.Daemon.run(Daemon.java:119) [starrocks-fe.jar:?]
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - 40d791d

### PR DESCRIPTION
**Pull request by gengjun-git**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] others

## Which issues of this PR fixes ：

Fixes #3952

## Problem Summary(Required) ：

Put tablet to TabletInvertedIndex in onFinished;

### CODE REVIEW

**Comment by gengjun-git** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 6 / 6 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/alter/SchemaChangeJobV2.java|6|6|100.00%|

**Review by Astralidea — DISMISSED** [review]

**Review by chaoyli — APPROVED** [review]

**Review by Astralidea — APPROVED** [review]

**Comment by gengjun-git** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 6 / 6 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/alter/SchemaChangeJobV2.java|6|6|100.00%|

**Pull request merged**
