### PR TITLE
[Enhancement] Refine profile to support visualization refactor(6)

### PR DESCRIPTION
**Pull request by liuyehcf**
This pr is an continuation work of #32303, and the main works of this pr lies in

1. Modify the calculation of `ResultDeliverTime`, now it comes from two parts `OutputFullTime` and `PendingFinishTime`. And the `PendingFinishTime` means the time of waiting the last batch of I/O operations to be finished.
    * make profile visiualization like this https://gist.github.com/hagonzal/1ffb86c865dc673f2068ab8208f3a6a7 more reasonable.
3. Fix bugs of text-baed analysis for insert into iceberg table and other types of external tables.

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.2
  - [x] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 12 / 12 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/scheduler/QueryRuntimeProfile.java|8|8|100.00%|[]|
|:large_blue_circle:|com/starrocks/common/util/ProfilingExecPlan.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ExplainAnalyzer.java|3|3|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/exec/pipeline/operator.cpp|1|1|100.00%|[]|

**Review by kangkaisen — APPROVED** [review]

**Review by satanson — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 12 / 12 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/scheduler/QueryRuntimeProfile.java|8|8|100.00%|[]|
|:large_blue_circle:|com/starrocks/common/util/ProfilingExecPlan.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ExplainAnalyzer.java|3|3|100.00%|[]|

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.2

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/exec/pipeline/operator.cpp|1|1|100.00%|[]|

**Pull request merged**
