### PR TITLE
[BugFix] Check the nullable property based on slot instead of parquet field to avoid inconsistency in decoding

### PR DESCRIPTION
**Pull request by GavinMar**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes https://github.com/StarRocks/StarRocksTest/issues/1211

## Problem Summary(Required) ：

Fix the BE crash problem when select array from iceberg external table with parquet file format.

As we treats all column slots from hive are `nullable`,  and then create columns based on slots property. If the parquet array columns are `required`,  the field parsed from parquet schema will be `not nullable`. In this case, if we depend on field property, the nullable column will be converted unexpected.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Review by DorianZheng — APPROVED** [review]

**Review by dirtysalt — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by GavinMar** [comment]
run starrocks_be_unittest

**Comment by GavinMar** [comment]
run starrocks_admit_test

**Comment by GavinMar** [comment]
run starrocks_be_unittest images

**Comment by GavinMar** [comment]
run starrocks_be_unittest

**Comment by GavinMar** [comment]
run starrocks_admit_test

**Review by imay — APPROVED** [review]

**Pull request merged**
