### PR TITLE
[BugFix] Fix broker load with invalid expr will not fail

### LINKED ISSUE #9141: Broker load with invalid expr will not fail
### Steps to reproduce the behavior (Required)
``` sql
create table tarray(
    k int,
    v array<string>
) ENGINE=OLAP
DUPLICATE KEY(k)
DISTRIBUTED BY HASH(k) BUCKETS 1
PROPERTIES (
"replication_num" = "1"
);

LOAD LABEL t.xxxx
(
    DATA INFILE('hdfs://x.x.x.x:9000/user/hive/warehouse/t/*')
    INTO TABLE tarray
    FORMAT AS "parquet"
    set(v=cast(v as array<string>))
)
WITH BROKER 'broker1'
PROPERTIES
(
    'timeout' = '3600'
)
```

### Expected behavior (Required)
```
| 20013 | xxxx | CANCELLED | ETL:N/A; LOAD:N/A   | BROKER | NULL| cluster:N/A; timeout(s):3600; max_filter_ratio:0.0 | type:ETL_RUN_FAIL; msg:Invalid type cast from varchar(-1) to ARRAY<varchar(65533)> in sql `v`| 2022-07-25 14:51:28 | 2022-07-25 14:51:29 | 2022-07-25 14:51:29 | 2022-07-25 14:51:29 | 2022-07-25 14:51:29 | NULL| {"Unfinished backends":{},"ScannedRows":0,"TaskNumber":0,"All backends":{},"FileNumber":1,"FileSize":363}
```

### Real behavior (Required)
```
| 19064 | xxxx | LOADING   | ETL:100%; LOAD:0%   | BROKER | NULL| cluster:N/A; timeout(s):3600; max_filter_ratio:0.0 | NULL| 2022-07-25 14:19:18 | 2022-07-25 14:19:20 | 2022-07-25 14:19:20 | 2022-07-25 14:19:20 | NULL| NULL | {"Unfinished backends":{},"ScannedRows":0,"TaskNumber":0,"All backends":{},"FileNumber":1,"FileSize":363}|
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by meegoo**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #9141

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 0 / 1 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/load/loadv2/BrokerLoadJob.java|0|1|00.00%|[158]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 0 / 1 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/load/loadv2/BrokerLoadJob.java|0|1|00.00%|[158]|

**Review by chaoyli — APPROVED** [review]

**Review by rickif — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by Astralidea — APPROVED** [review]

**Comment by meegoo** [comment]
@mergify backport branch-2.3 branch-2.2 branch-2.1

**Pull request merged**
