### PR TITLE
[BugFix] repo prefix incorrect (#19195)

### LINKED ISSUE #19195: [BugFix] repo prefix incorrect
Problem:
This problem is introduced by d1de07fe693. This commit want to reason the correct repo prefix when FE restart. In Repository.readField, list the file using palo prefix and determine the prefix base on the result. But we can not just return
palo prefix if status is ok. Because in some case, it will return ok even if we can not find any file named by __ palo__repo__name.

This problem cause another runtime problem. Repository.readField not only called by init thread but also checkpoint thread, so it will reason a wrong prefix even during fe is running.

Solution:
1. change the predicate : if (st.ok()) -> if (result.size() != 0)
2. Don't execute the code when the function is called by checkpoint thread.

### PR DESCRIPTION
**Pull request by srlch**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #19195

## Problem Summary(Required) ：
[BugFix] repo prefix incorrect (#19195)

Problem:
This problem is introduced by d1de07fe693. This commit want to reason the correct repo prefix when FE restart. In Repository.readField,
list the snapshot using palo prefix and determine the prefix base on the result. But there are two problem here:

1. We can not just return palo prefix if status is ok. Because in some case, it will return ok even if we can not find any snapshot file in repo by __ palo__repo__name.
2. If the repo is empty, this predicate will also fail.

This will cause other run time problem. If leader FE create a repo, follower will apply edit log and but because the Repository.readField is incorrect, follower will may get a wrong prefix.

Solution:
1. Use checkPathExist to check whether the __ palo__repo__name path is exist instead.
2. Don't execute the code when the function is called by checkpoint thread.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 3.0
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 5 / 6 (83.33%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/backup/Repository.java|5|6|83.33%|[710]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 6 / 11 (54.55%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/backup/Repository.java|6|11|54.55%|[710, 711, 712, 713, 717]|

**Review by gengjun-git — APPROVED** [review]

**Review by trueeyu — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by srlch** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Pull request merged**
