### PR TITLE
[Refactor] Remove unnecessary warning logs

### PR DESCRIPTION
**Pull request by liuyehcf**
Fixes #issue

## What type of PR is this:
- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [x] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.0
  - [x] 2.5
  - [x] 2.4
  - [x] 2.3

### CODE REVIEW

**Review by Seaven — APPROVED** [review]

**Review by satanson — APPROVED** [review]

**Review by ZiheLiu — APPROVED** [review]

**Comment by liuyehcf** [comment]
@Mergifyio backport branch-3.0

**Comment by liuyehcf** [comment]
@Mergifyio backport branch-2.5

**Comment by liuyehcf** [comment]
@Mergifyio backport branch-2.4

**Comment by liuyehcf** [comment]
@Mergifyio backport branch-2.3

**Pull request merged**
