### PR TITLE
[Feature] Add function get_query_dump

### LINKED ISSUE #48039: [Function] get_query_dump
- [x] https://github.com/StarRocks/starrocks/pull/48212
- [x] https://github.com/StarRocks/starrocks/pull/48105
need a function to repeatedly generate array.

## Description

```
get_query_dump(query, enable_mock)
```

in which,
- `query`: `VARCAHR`. Must be a constant value.
- `enable_mock`: `BOOL`. Must be a constant value.

Result:
- Success: a string with JSON format.
- Fail: a string with format `{"err_msg": "xxx"}`.

## Examples

```
select get_query_dump(c_int_2_seq) from t1;
(1064, 'Getting analyzing error. Detail message: Meta function get_query_dump does not support non-constant arguments.')

select get_query_dump("select count(1) from t1") ;

+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| {"statement":"select * from t1","table_meta":{"d2.t1":"CREATE TABLE `t1` (\n  `k1` bigint(20) NULL COMMENT \"\",\n  `c_int_1_seq` bigint(20) NULL COMMENT \"\",\n  `c_int_2_seq` varchar(65533) NULL COMMENT \"\"\n) ENGINE=OLAP \nDUPLICATE KEY(`k1`)\nDISTRIBUTED BY HASH(`k1`) BUCKETS 32 \nPROPERTIES (\n\"compression\" = \"LZ4\",\n\"fast_schema_evolution\" = \"true\",\n\"replicated_storage\" = \"true\",\n\"replication_num\" = \"1\"\n);"},"table_row_count":{"d2.t1":{"t1":1280000}},"column_statisti... |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+


with 
    query_dump as (select get_query_dump(concat('select *', ' from t1')) as x),
    w1 as (
        select 'statement' as k, get_json_string(x, '$.statement') as not_empty from query_dump
        UNION ALL
        select 'table_meta' as k, get_json_string(x, '$.table_meta')  as not_empty from query_dump
        UNION ALL
        select 'table_row_count' as k, get_json_string(x, '$.table_row_count')  as not_empty from query_dump
        UNION ALL
        select 'column_statistics' as k, get_json_string(x, '$.column_statistics')  as not_empty from query_dump
    ) 
select * from w1 order by k;

+-------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| k                 | not_empty                                                                                                                                                                                                                                                                                                                                                                                                 |
+-------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| column_statistics | {"d2.t1": {"c_int_1_seq": "[1.0, 1280000.0, 0.0, 8.0, 1273013.0] ESTIMATE", "c_int_2_seq": "[-Infinity, Infinity, 0.0, 11.13195, 1268234.0] ESTIMATE", "k1": "[1.0, 1280000.0, 0.0, 8.0, 1273013.0] ESTIMATE"}}                                                                                                                                                                                           |
| statement         | select * from t1                                                                                                                                                                                                                                                                                                                                                                                          |
| table_meta        | {"d2.t1": "CREATE TABLE `t1` (\n  `k1` bigint(20) NULL COMMENT \"\",\n  `c_int_1_seq` bigint(20) NULL COMMENT \"\",\n  `c_int_2_seq` varchar(65533) NULL COMMENT \"\"\n) ENGINE=OLAP \nDUPLICATE KEY(`k1`)\nDISTRIBUTED BY HASH(`k1`) BUCKETS 32 \nPROPERTIES (\n\"compression\" = \"LZ4\",\n\"fast_schema_evolution\" = \"true\",\n\"replicated_storage\" = \"true\",\n\"replication_num\" = \"1\"\n);"} |
| table_row_count   | {"d2.t1": {"t1": 1280000}}                                                                                                                                                                                                                                                                                                                                                                                |
+-------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```

### PR DESCRIPTION
**Pull request by ZiheLiu**
## Why I'm doing:

Add function `get_query_dump` to get query dump more easily.

```
select get_query_dump(c_int_2_seq) from t1;
(1064, 'Getting analyzing error. Detail message: Meta function get_query_dump does not support non-constant arguments.')

select get_query_dump("select count(1) from t1") ;

+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| {"statement":"select * from t1","table_meta":{"d2.t1":"CREATE TABLE `t1` (\n  `k1` bigint(20) NULL COMMENT \"\",\n  `c_int_1_seq` bigint(20) NULL COMMENT \"\",\n  `c_int_2_seq` varchar(65533) NULL COMMENT \"\"\n) ENGINE=OLAP \nDUPLICATE KEY(`k1`)\nDISTRIBUTED BY HASH(`k1`) BUCKETS 32 \nPROPERTIES (\n\"compression\" = \"LZ4\",\n\"fast_schema_evolution\" = \"true\",\n\"replicated_storage\" = \"true\",\n\"replication_num\" = \"1\"\n);"},"table_row_count":{"d2.t1":{"t1":1280000}},"column_statisti... |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

with 
    query_dump as (select get_query_dump(concat('select *', ' from t1')) as x),
    w1 as (
        select 'statement' as k, get_json_string(x, '$.statement') as not_empty from query_dump
        UNION ALL
        select 'table_meta' as k, get_json_string(x, '$.table_meta')  as not_empty from query_dump
        UNION ALL
        select 'table_row_count' as k, get_json_string(x, '$.table_row_count')  as not_empty from query_dump
        UNION ALL
        select 'column_statistics' as k, get_json_string(x, '$.column_statistics')  as not_empty from query_dump
    ) 
select * from w1 order by k;

+-------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| k                 | not_empty                                                                                                                                                                                                                                                                                                                                                                                                 |
+-------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| column_statistics | {"d2.t1": {"c_int_1_seq": "[1.0, 1280000.0, 0.0, 8.0, 1273013.0] ESTIMATE", "c_int_2_seq": "[-Infinity, Infinity, 0.0, 11.13195, 1268234.0] ESTIMATE", "k1": "[1.0, 1280000.0, 0.0, 8.0, 1273013.0] ESTIMATE"}}                                                                                                                                                                                           |
| statement         | select * from t1                                                                                                                                                                                                                                                                                                                                                                                          |
| table_meta        | {"d2.t1": "CREATE TABLE `t1` (\n  `k1` bigint(20) NULL COMMENT \"\",\n  `c_int_1_seq` bigint(20) NULL COMMENT \"\",\n  `c_int_2_seq` varchar(65533) NULL COMMENT \"\"\n) ENGINE=OLAP \nDUPLICATE KEY(`k1`)\nDISTRIBUTED BY HASH(`k1`) BUCKETS 32 \nPROPERTIES (\n\"compression\" = \"LZ4\",\n\"fast_schema_evolution\" = \"true\",\n\"replicated_storage\" = \"true\",\n\"replication_num\" = \"1\"\n);"} |
| table_row_count   | {"d2.t1": {"t1": 1280000}}                                                                                                                                                                                                                                                                                                                                                                                |
+-------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```

## What I'm doing:

1. Extract `QueryDumper` used by the HTTP API `QueryDumperAction` and the function `get_query_dump`.
2. Implement constant meta function `get_query_dump` only in FE.
3. Report error `Meta function xxx does not support non-constant arguments` when meta functions accept non-constant arguments.
4. The user privilege of `get_query_dump` is the same as the HTTP API `/api/query_dump`.

Close #48039


## What type of PR is this:

- [ ] BugFix
- [x] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.3
  - [ ] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Review by satanson — APPROVED** [review]

**Review by murphyatwork — APPROVED** [review]

**Review by LiShuMing — APPROVED** [review]

**Review by kangkaisen — APPROVED** [review]

**Review by Seaven — APPROVED** [review]

**Review by HangyuanLiu — APPROVED** [review]

**Comment by ZiheLiu** [comment]
@Mergify backport branch-2.5 branch-3.0 branch-3.1 branch-3.2 branch-3.3

**Comment by ZiheLiu** [comment]
ignore backport check: 3.1.14

**Comment by ZiheLiu** [comment]
@Mergify ignore backport check: 3.1.14

**Comment by ZiheLiu** [comment]
ignore backport check: 3.3.1

**Pull request merged**
