### PR TITLE
[Feature] New privilege: support authorization on catalog object

### PR DESCRIPTION
**Pull request by nshangyiming**
## What type of PR is this：
- [ ] BugFix
- [x] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

Support authorization on catalog object, we don't distinguish between external catalog and internal catalog when checking 
 or granting privilege.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

### CODE REVIEW

**Review by waittttting — APPROVED** [review]

**Comment by nshangyiming** [comment]
run pr-title-check

**Comment by nshangyiming** [comment]
run starrocks_admit_test

**Review by Astralidea — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by nshangyiming** [comment]
run all

**Review by gengjun-git — APPROVED** [review]

**Pull request merged**
