### PR TITLE
[BugFix] Modify solve hdfs uri contains empty space function

### PR DESCRIPTION
**Pull request by leoyy0316**
## What type of PR is this：
- [X] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #https://github.com/StarRocks/starrocks/issues/15671

## Problem Summary(Required) ：

when hdfs path has empty space, can not get hdfs filesystem, we need to solve it
## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Comment by leoyy0316** [comment]
run starrocks_fe_unittest

**Comment by leoyy0316** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/connector/hive/HiveRemoteFileIO.java|1|1|100.00%|[]|

**Review by imay — DISMISSED** [review]
It will be better to add some test to cover it.

**Comment by leoyy0316** [comment]
run starrocks_admit_test

**Comment by leoyy0316** [comment]
> 

@imay  added ut done

**Comment by leoyy0316** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/connector/hive/HiveRemoteFileIO.java|1|1|100.00%|[]|

**Review by imay — APPROVED** [review]

**Comment by letian-jiang** [comment]
@Mergifyio backport branch-2.5

**Comment by letian-jiang** [comment]
@Mergifyio backport branch-2.4

**Comment by letian-jiang** [comment]
@Mergifyio backport branch-2.3

**Pull request merged**
