### PR TITLE
[Enhancement] reduce compaction log

### PR DESCRIPTION
**Pull request by rickif**
## What type of PR is this：
- [ ] bugfix
- [ ] feature
- [x] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #https://github.com/StarRocks/starrocks/issues/10343

## Problem Summary(Required) ：

This PR reduces the compaction log.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Review by chaoyli — APPROVED** [review]

**Review by meegoo — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by rickif** [comment]
run starrocks_admit_test

**Comment by chaoyli** [comment]
run starrocks_admit_test

**Comment by rickif** [comment]
run starrocks_admit_test

**Pull request merged**
