### PR TITLE
[Enhancement] Normalizes the naming of the glue property

### PR DESCRIPTION
**Pull request by Youngwb**
## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

#12249

## Problem Summary(Required) ：

Use case:

```
CREATE EXTERNAL CATALOG hive_glue_catalog
PROPERTIES(
  "type"="hive", 
  "hive.metastore.type"="glue",
  "aws.hive.metastore.glue.aws-access-key" = "xxxxxx",
  "aws.hive.metastore.glue.aws-secret-key" = "xxxxxxxxxxxx",
  "aws.hive.metastore.glue.endpoint"="https://glue.${region}.amazonaws.com"
);

CREATE EXTERNAL CATALOG hudi_glue_catalog
PROPERTIES(
  "type"="hudi", 
  "hive.metastore.type"="glue",
  "aws.hive.metastore.glue.aws-access-key" = "xxxxxx",
  "aws.hive.metastore.glue.aws-secret-key" = "xxxxxxxxxxxx",
  "aws.hive.metastore.glue.endpoint"="https://glue.${region}.amazonaws.com"
);

CREATE EXTERNAL CATALOG delta_glue_catalog
PROPERTIES(
  "type"="deltalake", 
  "hive.metastore.type"="glue",
  "aws.hive.metastore.glue.aws-access-key" = "xxxxxx",
  "aws.hive.metastore.glue.aws-secret-key" = "xxxxxxxxxxxx",
  "aws.hive.metastore.glue.endpoint"="https://glue.${region}.amazonaws.com"
);

CREATE EXTERNAL CATALOG iceberg_glue_catalog
PROPERTIES(
  "type"="iceberg", 
  "iceberg.catalog.type"="glue",
  "aws.hive.metastore.glue.aws-access-key" = "xxxxx",
  "aws.hive.metastore.glue.aws-secret-key" = "xxx",
  "aws.hive.metastore.glue.endpoint"="https://glue.${region}.amazonaws.com"
);
```

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by stephen-shelby — APPROVED** [review]

**Review by imay — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by Youngwb** [comment]
run starrocks_admit_test

**Comment by Youngwb** [comment]
run starrocks_admit_test

**Comment by Youngwb** [comment]
run starrocks_admit_test

**Comment by Youngwb** [comment]
@Mergify backport branch-2.5

**Pull request merged**
