### PR TITLE
Disable colocate/bucket join when table with empty partition

### LINKED ISSUE #4265: Query error while broker load
### Steps to reproduce the behavior (Required)
1. create tpch tables;
2. broker load:
```
LOAD LABEL test_pipeline_dml_sel.broker_load_tpch_lineitem_1647655921 (DATA INFILE( "hdfs://***:9000/starrocks_test_data/stability_data/standard_testsets/tpch/csv/lineitem.tbl.1*") INTO TABLE `lineitem` COLUMNS TERMINATED BY "|" )  WITH BROKER hdfs_broker ("username"="dorisdb","password"="dorisdb@test") PROPERTIES("timeout"="259200");
LOAD LABEL test_pipeline_dml_sel.broker_load_tpch_customer_1647656346 (DATA INFILE( "hdfs://***:9000/starrocks_test_data/stability_data/standard_testsets/tpch/csv/customer.tbl.1*") INTO TABLE `customer` COLUMNS TERMINATED BY "|" )  WITH BROKER hdfs_broker ("username"="dorisdb","password"="dorisdb@test") PROPERTIES("timeout"="259200");
LOAD LABEL test_pipeline_dml_sel.broker_load_tpch_nation_1647656411 (DATA INFILE( "hdfs://***:9000/starrocks_test_data/stability_data/standard_testsets/tpch/csv/nation.tbl*") INTO TABLE `nation` COLUMNS TERMINATED BY "|" )  WITH BROKER hdfs_broker ("username"="dorisdb","password"="dorisdb@test") PROPERTIES("timeout"="259200");
LOAD LABEL test_pipeline_dml_sel.broker_load_tpch_region_1647656417 (DATA INFILE( "hdfs://***:9000/starrocks_test_data/stability_data/standard_testsets/tpch/csv/region.tbl*") INTO TABLE `region` COLUMNS TERMINATED BY "|" )  WITH BROKER hdfs_broker ("username"="dorisdb","password"="dorisdb@test") PROPERTIES("timeout"="259200");
LOAD LABEL test_pipeline_dml_sel.broker_load_tpch_orders_1647656422 (DATA INFILE( "hdfs://***:9000/starrocks_test_data/stability_data/standard_testsets/tpch/csv/orders.tbl.1*") INTO TABLE `orders` COLUMNS TERMINATED BY "|" )  WITH BROKER hdfs_broker ("username"="dorisdb","password"="dorisdb@test") PROPERTIES("timeout"="259200");
LOAD LABEL test_pipeline_dml_sel.broker_load_tpch_part_1647656967 (DATA INFILE( "hdfs://***:9000/starrocks_test_data/stability_data/standard_testsets/tpch/csv/part.tbl.1*") INTO TABLE `part` COLUMNS TERMINATED BY "|" )  WITH BROKER hdfs_broker ("username"="dorisdb","password"="dorisdb@test") PROPERTIES("timeout"="259200");
LOAD LABEL test_pipeline_dml_sel.broker_load_tpch_partsupp_1647657033 (DATA INFILE( "hdfs://***:9000/starrocks_test_data/stability_data/standard_testsets/tpch/csv/partsupp.tbl.1*") INTO TABLE `partsupp` COLUMNS TERMINATED BY "|" )  WITH BROKER hdfs_broker ("username"="dorisdb","password"="dorisdb@test") PROPERTIES("timeout"="259200");
LOAD LABEL test_pipeline_dml_sel.broker_load_tpch_supplier_1647657158 (DATA INFILE( "hdfs://***:9000/starrocks_test_data/stability_data/standard_testsets/tpch/csv/supplier.tbl*") INTO TABLE `supplier` COLUMNS TERMINATED BY "|" )  WITH BROKER hdfs_broker ("username"="dorisdb","password"="dorisdb@test") PROPERTIES("timeout"="259200");
```
3. execute tpch querys while broker load
query returned error:
ERR-1:
```
=======current loop time: 1=======
== begin execute q2 ===
execute sql error and messages: (1064, 'Unknown error'), and time is: 2022-03-19 10:13:13
{'status': False, 'msg': (1064, 'Unknown error')}
== begin execute q4 ===
execute sql error and messages: (1064, 'Unknown error'), and time is: 2022-03-19 10:13:13
{'status': False, 'msg': (1064, 'Unknown error')}
```

fe.log:
```
2022-03-19 10:30:31,810 WARN (starrocks-mysql-nio-pool-478|21048) [StmtExecutor.execute():484] execute Exception, sql  select count(*) from ( select p_brand, p_type, p_size, count(distinct ps_suppkey) as supplier_cnt from partsupp, part where p_partkey = ps_partkey and p_brand <> 'Brand#45' and p_type not like 'MEDIUM POLISHED%' and p_size in (49, 14, 23, 45, 19, 3, 36, 9) and ps_suppkey not in ( select s_suppkey from supplier where s_comment like '%Customer%Complaints%' ) group by p_brand, p_type, p_size order by supplier_cnt desc, p_brand, p_type, p_size ) as t1;
java.lang.ArithmeticException: null
```

ERR-2:
```
== begin execute q5 ===
execute sql error and messages: (1064, '/ by zero'), and time is: 2022-03-19 10:14:28
{'status': False, 'msg': (1064, '/ by zero')}
== begin execute q15 ===
execute sql error and messages: (1064, '/ by zero'), and time is: 2022-03-19 10:14:28
{'status': False, 'msg': (1064, '/ by zero')}
== begin execute q13 ===
execute sql error and messages: (1064, '/ by zero'), and time is: 2022-03-19 10:14:28
{'status': False, 'msg': (1064, '/ by zero')}
== begin execute q14 ===
execute sql error and messages: (1064, '/ by zero'), and time is: 2022-03-19 10:14:28
{'status': False, 'msg': (1064, '/ by zero')}
```

fe.log:
```
2022-03-19 10:16:40,950 WARN (starrocks-mysql-nio-pool-478|21048) [StmtExecutor.execute():484] execute Exception, sql  select count(*) from ( select s_acctbal, s_name, n_name, p_partkey, p_mfgr, s_address, s_phone, s_comment from part, supplier, partsupp, nation, region where p_partkey = ps_partkey and s_suppkey = ps_suppkey and p_size = 15 and p_type like '%BRASS' and s_nationkey = n_nationkey and n_regionkey = r_regionkey and r_name = 'EUROPE' and ps_supplycost = ( select min(ps_supplycost) from partsupp, supplier, nation, region where p_partkey = ps_partkey and s_suppkey = ps_suppkey and s_nationkey = n_nationkey and n_regionkey = r_regionkey and r_name = 'EUROPE' ) order by s_acctbal desc, n_name, s_name, p_partkey ) as t1;
java.lang.ArithmeticException: / by zero
        at com.starrocks.qe.Coordinator.computeColocatedJoinInstanceParam(Coordinator.java:1465) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.Coordinator.computeFragmentHosts(Coordinator.java:1212) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.Coordinator.computeFragmentExecParams(Coordinator.java:879) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.Coordinator.exec(Coordinator.java:416) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.handleQueryStmt(StmtExecutor.java:715) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:403) [starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:283) [starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:430) [starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:666) [starrocks-fe.jar:?]
        at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$448(ReadListener.java:55) [starrocks-fe.jar:?]
        at com.starrocks.mysql.nio.ReadListener$$Lambda$302/1344880581.run(Unknown Source) [starrocks-fe.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_41]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_41]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_41]
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
mysql> select current_version();
+--------------------------+
| current_version()        |
+--------------------------+
| STABILITY_MASTER 8413c2b |
+--------------------------+
1 row in set (0.00 sec)
```

### PR DESCRIPTION
**Pull request by Youngwb**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] others

## Which issues of this PR fixes ：

Fixes #4265

## Problem Summary(Required) ：

Disable colocate/bucket join when table with empty partition, because of this will result in hang when excution

### CODE REVIEW

**Comment by Youngwb** [comment]
run starrocks_fe_unittest

**Comment by Youngwb** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 4 / 5 (80.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/OutputPropertyDeriver.java|1|2|50.00%|
|:large_blue_circle:|com/starrocks/sql/optimizer/base/DistributionSpec.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/sql/optimizer/base/HashDistributionSpec.java|2|2|100.00%|

**Review by Seaven — APPROVED** [review]

**Review by kangkaisen — APPROVED** [review]

**Comment by Youngwb** [comment]
backport branch-2.2

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 4 / 5 (80.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/OutputPropertyDeriver.java|1|2|50.00%|
|:large_blue_circle:|com/starrocks/sql/optimizer/base/DistributionSpec.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/sql/optimizer/base/HashDistributionSpec.java|2|2|100.00%|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 4 / 5 (80.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/OutputPropertyDeriver.java|1|2|50.00%|
|:large_blue_circle:|com/starrocks/sql/optimizer/base/DistributionSpec.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/sql/optimizer/base/HashDistributionSpec.java|2|2|100.00%|

**Pull request merged**
