### PR TITLE
update StreamLoad

### PR DESCRIPTION
**Pull request by amber-create**
## What type of PR is this：
- [ ] bugfix
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Review by femiiii — DISMISSED** [review]

**Review by evelynzhaojie — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by evelynzhaojie — APPROVED** [review]

**Review by femiiii — APPROVED** [review]

**Review by evelynzhaojie — DISMISSED** [review]

**Review by femiiii — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by evelynzhaojie — APPROVED** [review]

**Review by femiiii — APPROVED** [review]

**Comment by amber-create** [comment]
@mergify backport branch-2.3

**Comment by amber-create** [comment]
@mergify backport branch-2.2

**Pull request merged**
