### PR TITLE
[BugFix] fix unexpected error message when cast invalid value to float/double

### LINKED ISSUE #26014: cast NaN as double return error
### Steps to reproduce the behavior (Required)
```sql
mysql>   select cast('NaN' as double);
ERROR 1064 (HY000): Invalid literal:NaN
```

### Expected behavior (Required)

return NULL
### Real behavior (Required)
return error

fe log
image

### StarRocks version (Required)

main-ca4b28305e

### PR DESCRIPTION
**Pull request by silverbullet233**
Fixes #26014

## What type of PR is this:
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [x] 3.0
  - [x] 2.5
  - [x] 2.4

### CODE REVIEW

**Review by Seaven — DISMISSED** [review]
BTW, could you explain how to get `NULL`?

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 4 / 5 (80.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/scalar/ConstantOperator.java|4|5|80.00%|[91]|

**Comment by silverbullet233** [comment]
> BTW, could you explain how to get `NULL`?

under normal circumstances, cast('NaN' as double) shoud be pushed to BE to execute and this cast will fail and return NULL.

Unfortunately, before this change,  FoldConstantsRule is applied at below and CastOperator is rewrited to a ConstantOperator with value NaN, This will cause an exception in the next processing, and finally return an error.
image

after this change, FoldConstantsRule will take no effect here.

**Review by packy92 — APPROVED** [review]

**Review by Seaven — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.4

**Pull request merged**
