### PR TITLE
[Enhancement][Cherry-pick] make mv preprocess more robust for 2.5 (#19551)

### LINKED ISSUE #19549: make mv rewrite preprocess more robust
## Enhancement
now when mv rewrite preprocess failed for one mv, the query will fail too. it is better to skip this mv candidate, not to disturb the query process.

### PR DESCRIPTION
**Pull request by ABingHuang**
## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #19549 

## Problem Summary(Required) ：

make mv preprocess more robust

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Review by Astralidea — DISMISSED** [review]

**Comment by ABingHuang** [comment]
run starrocks_fe_unittest

**Comment by wangruin** [comment]
run starrocks_fe_unittest

**Review by Astralidea — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
@Mergify rebase

**Comment by wanpengfei-git** [comment]
@mergify rebase

**Review by Astralidea — APPROVED** [review]

**Pull request merged**
