### PR TITLE
[Refactor] Extract JNI related class to independent module

### PR DESCRIPTION
**Pull request by miomiocat**
## What type of PR is this：
- [ ] bug
- [ ] feature
- [ ] enhancement
- [x] refactor
- [ ] others

Decouple JNI related codes to independent module in preparation for jni connector work

### CODE REVIEW

**Review by stdpain — DISMISSED** [review]

**Comment by miomiocat** [comment]
run starrocks_fe_unittest

**Comment by miomiocat** [comment]
run starrocks_fe_unittest

**Comment by miomiocat** [comment]
run starrocks_fe_unittest

**Comment by miomiocat** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by miomiocat** [comment]
run starrocks_admit_test

**Review by stdpain — APPROVED** [review]

**Comment by stdpain** [comment]
run starrocks_admit_test

**Review by kangkaisen — APPROVED** [review]

**Pull request merged**
