### PR TITLE
[Refactor] fix performance issue by clang-tidy

### PR DESCRIPTION
**Pull request by dirtysalt**
## What I'm doing:

Fixes #issue

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [x] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 3.3
  - [ ] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Review by imay — COMMENTED** [review]
How about adding this clang tidy rule in our clang-tidy script

**Comment by dirtysalt** [comment]
> How about adding this clang tidy rule in our clang-tidy script

Drawbacks:
- if enable `modern-xxx` in .clang-tidy,  there are more changes than this.  And most of them, I think it's like coding-style. so I just enable `performance-xxx`
- and it will  increase compile time.
- and I'm not sure if all machines are equipped with clang.

Benefits:
- `performance-xxx` will definitely help you find some code could be optimized, but I feel margin is not that large.
- we probably get more uniformed coding-style.

So my suggestion is
- run this clang-tidy but only with `performance-xxx` once for a while
- urge all developers use clang
- enable `performance-xxx` by default
- enable `modern-xxx` gradually, and we will get sort-of uniformed coding-style.

**Comment by kevincai** [comment]
> > How about adding this clang tidy rule in our clang-tidy script
> 
> Drawbacks:
> 
> * if enable `modern-xxx` in .clang-tidy,  there are more changes than this.  And most of them, I think it's like coding-style. so I just enable `performance-xxx`
> * and it will  increase compile time.
> * and I'm not sure if all machines are equipped with clang.
> 
> Benefits:
> 
> * `performance-xxx` will definitely help you find some code could be optimized, but I feel margin is not that large.
> * we probably get more uniformed coding-style.
> 
> So my suggestion is
> 
> * run this clang-tidy but only with `performance-xxx` once for a while(do it by hand and offline)
> * urge all developers use clang (Have to install clang for all developing machines, and show potential benefits that if we switch to clang).
> * enable `performance-xxx` by default
> * enable `modern-xxx` gradually, and we will get sort-of uniformed coding-style.

our CI workflow has clang-tidy checks, so just enable the rule and let CI do the checks.
Also not sure if these checks can be enabled by `-Wxxx` if using clang compiler, and add them to CMakeLists.txt for clang if possible.

**Review by kevincai — DISMISSED** [review]

**Comment by dirtysalt** [comment]
> > > How about adding this clang tidy rule in our clang-tidy script
> > 
> > 
> > Drawbacks:
> > 
> > * if enable `modern-xxx` in .clang-tidy,  there are more changes than this.  And most of them, I think it's like coding-style. so I just enable `performance-xxx`
> > * and it will  increase compile time.
> > * and I'm not sure if all machines are equipped with clang.
> > 
> > Benefits:
> > 
> > * `performance-xxx` will definitely help you find some code could be optimized, but I feel margin is not that large.
> > * we probably get more uniformed coding-style.
> > 
> > So my suggestion is
> > 
> > * run this clang-tidy but only with `performance-xxx` once for a while(do it by hand and offline)
> > * urge all developers use clang (Have to install clang for all developing machines, and show potential benefits that if we switch to clang).
> > * enable `performance-xxx` by default
> > * enable `modern-xxx` gradually, and we will get sort-of uniformed coding-style.
> 
> our CI workflow has clang-tidy checks, so just enable the rule and let CI do the checks. Also not sure if these checks can be enabled by `-Wxxx` if using clang compiler, and add them to CMakeLists.txt for clang if possible.

Not sure. I enable clang-tidy adding following to CMakeLists.txt

> set(CMAKE_CXX_CLANG_TIDY clang-tidy; -fix; -fix-errors)

It will fix files instead of just checking them.

Plus, I guess right now clang-tidy checks maybe just check modified files? Because if I run clang-tidy on all files with `modern-xxx` enabled, a lot of files need to be modified.  But the good side of it is that we can have a more consistent C++ coding style.

**Comment by dirtysalt** [comment]
We can also apply clang-tidy to fix files by

> run-clang-tidy -p . -fix -j 32 be/src/formats/parquet

No need to modify cmakelists.txt

**Review by kevincai — APPROVED** [review]

**Pull request merged**
