### PR TITLE
[BugFix] Fix plan connectedness for NlJoin

### PR DESCRIPTION
**Pull request by ZiheLiu**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #14416.

## Problem Summary(Required) ：

When merge right fragment and left fragment, we use `leftFragment.addChild(rightFragment.getChild(0))`. However, right fragment may have multiple children, when multiple nested Nl Join in one fragment.

Validate the plan connectedness in the entrance of getting plan of UT, that is in `UtFrameUtils::getPlanAndFragment`.

```text
  11:NESTLOOP JOIN
  |  join op: RIGHT OUTER JOIN
  |  colocate: false, reason: 
  |  other join predicates: 1: v1 < 10: v1
  |  
  |----10:Project
  |    |  <slot 10> : 10: v1
  |    |  
  |    9:NESTLOOP JOIN
  |    |  join op: CROSS JOIN
  |    |  colocate: false, reason: 
  |    |  
  |    |----8:EXCHANGE
  |    |    
  |    6:Project
  |    |  <slot 4> : 4: v1
  |    |  
  |    5:NESTLOOP JOIN
  |    |  join op: CROSS JOIN
  |    |  colocate: false, reason: 
  |    |  
  |    |----4:EXCHANGE
  |    |    
  |    2:EMPTYSET
  |    
  1:EXCHANGE
````

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Comment by ZiheLiu** [comment]
@Mergify backport branch-2.5

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/plan/PlanFragmentBuilder.java|1|1|100.00%|[]|

**Review by Seaven — DISMISSED** [review]

**Review by kangkaisen — APPROVED** [review]

**Review by Seaven — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 6 / 6 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/plan/PlanFragmentBuilder.java|6|6|100.00%|[]|

**Comment by mofeiatwork** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Comment by mofeiatwork** [comment]
@Mergifyio backport branch-2.4

**Pull request merged**
