### PR TITLE
Remove some old Analyzer codes

### PR DESCRIPTION
**Pull request by kangkaisen**
## What type of PR is this：
- [ ] bug
- [ ] feature
- [ ] enhancement
- [x] refactor
- [ ] others

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 5 / 11 (45.45%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/analysis/TimestampArithmeticExpr.java|1|7|14.29%|
|:large_blue_circle:|com/starrocks/sql/plan/PlanFragmentBuilder.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/planner/SortNode.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/planner/PlanFragment.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/planner/PlanNode.java|1|1|100.00%|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 5 / 11 (45.45%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/analysis/TimestampArithmeticExpr.java|1|7|14.29%|
|:large_blue_circle:|com/starrocks/sql/plan/PlanFragmentBuilder.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/planner/SortNode.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/planner/PlanFragment.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/planner/PlanNode.java|1|1|100.00%|

**Review by murphyatwork — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 7 / 19 (36.84%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/planner/FileScanNode.java|0|1|00.00%|
|:large_blue_circle:|com/starrocks/load/ExportJob.java|0|2|00.00%|
|:large_blue_circle:|com/starrocks/planner/StreamLoadScanNode.java|0|1|00.00%|
|:large_blue_circle:|com/starrocks/task/ExportExportingTask.java|0|1|00.00%|
|:large_blue_circle:|com/starrocks/analysis/TimestampArithmeticExpr.java|1|7|14.29%|
|:large_blue_circle:|com/starrocks/planner/MysqlScanNode.java|2|3|66.67%|
|:large_blue_circle:|com/starrocks/sql/plan/PlanFragmentBuilder.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/planner/SortNode.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/planner/PlanFragment.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/planner/PlanNode.java|1|1|100.00%|

**Comment by kangkaisen** [comment]
This PR has passed all daily tests.

**Review by imay — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 15 / 27 (55.56%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/load/ExportJob.java|0|2|00.00%|
|:large_blue_circle:|com/starrocks/task/ExportExportingTask.java|0|1|00.00%|
|:large_blue_circle:|com/starrocks/analysis/TimestampArithmeticExpr.java|1|7|14.29%|
|:large_blue_circle:|com/starrocks/planner/MysqlScanNode.java|2|3|66.67%|
|:large_blue_circle:|com/starrocks/planner/StreamLoadScanNode.java|3|4|75.00%|
|:large_blue_circle:|com/starrocks/planner/FileScanNode.java|5|6|83.33%|
|:large_blue_circle:|com/starrocks/sql/plan/PlanFragmentBuilder.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/planner/SortNode.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/planner/PlanFragment.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/planner/PlanNode.java|1|1|100.00%|

**Review by murphyatwork — APPROVED** [review]

**Review by Seaven — APPROVED** [review]

**Pull request merged**
