### PR TITLE
[Enhancement] implement add_months function in FE

### PR DESCRIPTION
**Pull request by even986025158**
## What type of PR is this：
- [x] Enhancement

## Which issues of this PR fixes ：
implement add_months function in FE

## Problem Summary(Required) ：
when user use add_months function in where clause  compare with partition field；it will result in a full table scan。

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rewrite/ScalarOperatorFunctions.java|2|2|100.00%|[]|

**Review by imay — APPROVED** [review]

**Comment by imay** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rewrite/ScalarOperatorFunctions.java|2|2|100.00%|[]|

**Comment by even986025158** [comment]
run starrocks_admit_test

**Review by kangkaisen — APPROVED** [review]

**Pull request merged**
