### PR TITLE
[Enhancement] disable `__MIN/MAX_OF`  and avg in connector chunk source profile

### PR DESCRIPTION
**Pull request by dirtysalt**
## Why I'm doing:

To remove min/max value in chunk source profile.

Because values in chunk source profile are accumulated.  If chunk source is not well balanced, then values are skewed. And right now, we do have the problem that chunk source is not balanced assigned. 

Not balanced assigned is not problem for performance at all. But it will hurt profile analysis. So I guess it's better to remove min/max value.

----

And also right now time unit is handled in a average way,  and almost that's not interpretable? time is avg through chunk source, and then avg through BEs. I guess there is almost useless. 

## What I'm doing:

For chunk source merged profile, we set counter category to "skip min max" and "skip avg".

Fixes #issue

----

Before this PR

img_v3_0290_848990b5-972c-4a62-a949-82e8cba1051g

And after this PR, it looks better

image

by comparing metrics, we can easily tell where is the bottleneck: fs io time.

image

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Comment by Smith-Cruise** [comment]
Can we get metrics for each chunk source, not accumulated.

Although min/max is not accurate, it is still useful. If it is removed, we will have no way to detect slow io.

**Comment by dirtysalt** [comment]
> Can we get metrics for each chunk source, not accumulated.
> 
> Although min/max is not accurate, it is still useful. If it is removed, we will have no way to detect slow io.

Right now we can not. If that, we have to collect N(# scan ranges) profiles, and then merge them into one, which costs a lot. 

Right trino implement it in a simple way, that's to randomly collect some chunk soruce profile for a scan range, so you probably have chance to spot the real problem.

**Comment by GavinMar** [comment]
As the io tasks execute in parallel, if we just accumelate it without average, is it can represent the approximately time? In the old way, we usually can estimated the execution time by the max value.

**Comment by dirtysalt** [comment]
> As the io tasks execute in parallel, if we just accumelate it without average, is it can represent the approximately time? In the old way, we usually can estimated the execution time by the max value.

It can represent how long we spent on this operation.

you must know, max value and min value is not for a single operation. It's for accmulated time of a chunk source.

**Pull request closed without merging**
