### PR TITLE
[Refactor] refactor hdfs scan node to thrift and scan optimization options

### PR DESCRIPTION
**Pull request by dirtysalt**
Fixes #issue

This PR has done two points of refactor:
1. put duplicated `toThrift` code into static method.
2. put several options about scan optimization into a class.(easier to manage and assign)

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [x] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [ ] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 115 / 138 (83.33%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/planner/HudiScanNode.java|0|5|00.00%|[154, 155, 156, 157, 158]|
|:large_blue_circle:|com/starrocks/planner/PaimonScanNode.java|0|3|00.00%|[238, 239, 240]|
|:large_blue_circle:|com/starrocks/planner/IcebergScanNode.java|0|3|00.00%|[351, 352, 353]|
|:large_blue_circle:|com/starrocks/planner/DeltaLakeScanNode.java|0|3|00.00%|[281, 282, 283]|
|:large_blue_circle:|com/starrocks/sql/plan/PlanFragmentBuilder.java|6|11|54.55%|[926, 1056, 1098, 1143, 1401]|
|:large_blue_circle:|com/starrocks/planner/HdfsScanNode.java|34|36|94.44%|[218, 227]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/MinMaxCountOptOnScanRule.java|44|46|95.65%|[64, 105]|
|:large_blue_circle:|com/starrocks/sql/optimizer/Optimizer.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/logical/LogicalScanOperator.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/FileTableScanNode.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/ScanOptimzeOption.java|11|11|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/PruneHDFSScanColumnRule.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/ScanNode.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/tree/AddDecodeNodeForDictStringRule.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/PruneScanColumnRule.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/physical/PhysicalScanOperator.java|4|4|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by stephen-shelby — APPROVED** [review]

**Review by Youngwb — APPROVED** [review]

**Comment by dirtysalt** [comment]
@mergify backport branch-3.1

**Comment by dirtysalt** [comment]
@mergify backport branch-3.2

**Pull request merged**
