### PR TITLE
[Enhancement] support cast struct/map/array to json

### LINKED ISSUE #19320: Support type casting from struct to json
## Enhancement

Since 2.5 SR supported the `struct` type, without native storage.

The workaround should be, store it as JSON and cast struct to json when ingestion.

So the requirement is, support various type casting from struct to JSON:
- [x] Broker load/Stream load from parquet struct to JSON
- [ ] Support cast operator from struct to JSON

### PR DESCRIPTION
**Pull request by murphyatwork**
## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #19320

## Problem Summary(Required) ：

Implement two functions:
- `JSON to_json(MAP)`
- `JSON to_json(STRUCT)`

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 3.0
  - [x] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 7 / 7 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/PrimitiveType.java|5|5|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/Type.java|2|2|100.00%|[]|

**Comment by mofeiatwork** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 10 / 11 (90.91%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/Type.java|4|5|80.00%|[1061]|
|:large_blue_circle:|com/starrocks/catalog/PrimitiveType.java|5|5|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/Function.java|1|1|100.00%|[]|

**Review by dirtysalt — DISMISSED** [review]

**Comment by mofeiatwork** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 10 / 11 (90.91%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/Type.java|4|5|80.00%|[1061]|
|:large_blue_circle:|com/starrocks/catalog/PrimitiveType.java|5|5|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/Function.java|1|1|100.00%|[]|

**Comment by mofeiatwork** [comment]
run starrocks_be_unittest

**Comment by mofeiatwork** [comment]
run all

**Comment by mofeiatwork** [comment]
@Mergifyio rebase

**Comment by wanpengfei-git** [comment]
@Mergify rebase

**Review by dirtysalt — APPROVED** [review]

**Review by satanson — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
