### PR TITLE
[BugFix] Fix all Role is MASTER when showing frontends

### LINKED ISSUE #8121: [BUG] All frontend's role is MASTER
### Steps to reproduce the behavior (Required)
`show frontends`

### Real behavior (Required)
image

### StarRocks version (Required)
 - main

### PR DESCRIPTION
**Pull request by gengjun-git**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #8121

## Problem Summary(Required) ：

Check the Role type according to the fe's host and master's host.

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 0 / 5 (00.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/common/proc/FrontendsProcNode.java|0|5|00.00%|

**Review by imay — APPROVED** [review]

**Comment by imay** [comment]
We need to change mater to leader

**Comment by gengjun-git** [comment]
> We need to change mater to leader

I will change the related code in another PR

**Review by padmejin — APPROVED** [review]
LGTM

**Review by chaoyli — APPROVED** [review]

**Pull request merged**
