### PR TITLE
[BugFix] Fix single replica lost after consecutive balance

### PR DESCRIPTION
**Pull request by nshangyiming**
Fixes SSU-895

We should avoid full clone task to run concurrently with replica drop task,
otherwise it may cause replica lost in the following scenario:
we have a tablet T with only one replica,
t1: balancer move T from backend 10001 to backend 10002
t2: after clone finished, redundant replica on 10001 will be dropped,
      but this will only clean the meta from FE, replica is physically
      dropped until next tablet report from BE
t3: balancer schedule a task to move back T from backend 10002 to backend 10001
t4: tablet report from 10001 received, and a replica drop task is sent to backend 10001
t5: clone on backend 10001 finished, and a new replica of T is created on FE
t6: replica drop task has been executed on backend 10001
t7: after the second clone finished, redundant replica on 10002 will be dropped
t8: replica of T is physically lost with only meta of replica on 10001 is left on FE

If the timing of consecutive full clones is too close, we will delay the next full clone
so that report handler will delete the src replica physically in time.

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [x] 3.0
  - [x] 2.5
  - [ ] 2.4

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 65 / 78 (83.33%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/clone/TabletSchedCtx.java|2|3|66.67%|[836]|
|:large_blue_circle:|com/starrocks/leader/LeaderImpl.java|58|70|82.86%|[288, 323, 331, 713, 996, 998, 1001, 1021, 1071, 1072, 1073, 1074]|
|:large_blue_circle:|com/starrocks/catalog/LocalTablet.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/common/Config.java|1|1|100.00%|[]|

**Review by gengjun-git — APPROVED** [review]

**Review by Astralidea — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
