### PR TITLE
[Bugfix] ignore partition and columns name case when create mv.#9386

### PR DESCRIPTION
**Pull request by QingdongZeng3**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #
#9386
## Problem Summary(Required) ：

```
CREATE TABLE t1 (
                  col1 int,
                  col2 double,
                  col3 varchar(20)
                ) ENGINE=OLAP
                DUPLICATE KEY(col1)
                COMMENT "OLAP"
                PARTITION BY RANGE(`col1`)
                (
                    PARTITION p1 VALUES LESS THAN ("100")
                )
                DISTRIBUTED BY HASH(col1) BUCKETS 3
                PROPERTIES (
                "replication_num" = "3"
                );

CREATE MATERIALIZED VIEW mv1
PARTITION BY COL1
DISTRIBUTED BY HASH(col1) BUCKETS 10
REFRESH ASYNC
AS SELECT col1, col2
FROM t1;


CREATE MATERIALIZED VIEW mv2
PARTITION BY COL1
DISTRIBUTED BY HASH(col1) BUCKETS 10
REFRESH ASYNC
AS SELECT COL1, col2
FROM t1;
```

image

If there are two identical fields ignore case in select , it will report error "Duplicate column name ".For example:

```
CREATE MATERIALIZED VIEW mv5
PARTITION BY COL1
DISTRIBUTED BY HASH(col1) BUCKETS 10
REFRESH ASYNC
AS SELECT COL1, col2 ,Col1 
FROM t1;

ERROR 1064 (HY000): Duplicate column name 'col1'
```

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 7 / 8 (87.50%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java|7|8|87.50%|[363]|

**Comment by QingdongZeng3** [comment]
@Astralidea PTAL

**Review by Astralidea — DISMISSED** [review]

**Review by ABingHuang — CHANGES_REQUESTED** [review]
Add related UTs please.

**Review by caneGuy — COMMENTED** [review]
Please add UT

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 7 / 8 (87.50%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java|7|8|87.50%|[363]|

**Review by Astralidea — APPROVED** [review]

**Comment by QingdongZeng3** [comment]
> Add related UTs please.

ok, I have done it.

**Comment by Astralidea** [comment]
run starrocks_admit_test

**Review by ABingHuang — APPROVED** [review]
LGTM

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by QingdongZeng3** [comment]
run starrocks_admit_test

**Review by imay — APPROVED** [review]

**Comment by imay** [comment]
run starrocks_admit_test

**Pull request merged**
