### PR TITLE
[BugFix] merge pushdown predicate to cte

### PR DESCRIPTION
**Pull request by packy92**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #14100

## Problem Summary(Required) ：

CTE consumer should remain all pushdown predicates for non-inline execute mode.
## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 2.5
  - [x] 2.4
  - [x] 2.3
  - [x] 2.2

### CODE REVIEW

**Review by Seaven — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/PushDownPredicateCTEConsumeRule.java|2|2|100.00%|[]|

**Review by Seaven — APPROVED** [review]

**Comment by packy92** [comment]
@Mergify backport branch-2.2 branch-2.3 branch-2.4 branch-2.5

**Review by kangkaisen — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by HangyuanLiu — APPROVED** [review]

**Comment by packy92** [comment]
run starrocks_fe_unittest

**Comment by packy92** [comment]
run starrocks_fe_unittest

**Comment by packy92** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/PushDownPredicateCTEConsumeRule.java|2|2|100.00%|[]|

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5 --ignore_conflicts=false

**Comment by wanpengfei-git** [comment]
@Mergify backport branch-2.5

**Comment by wanpengfei-git** [comment]
@Mergify backport branch-2.1

**Pull request merged**
