### PR TITLE
[BugFix] Fix compaction crash since lock conflict

### LINKED ISSUE #17387: crash in max_continuous_version
### Steps to reproduce the behavior (Required)
*** Aborted at 1675426448 (unix time) try "date -d @1675426448" if you are using GNU date ***
PC: @     0x7f195e77f387 __GI_raise
*** SIGABRT (@0x3eb00034636) received by PID 214582 (TID 0x7f14017f9700) from PID 214582; stack trace: ***
    @          0x6189be2 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7f195f03e630 (unknown)
    @     0x7f195e77f387 __GI_raise
    @     0x7f195e780a78 __GI_abort
    @          0x2fe4b60 _ZN9__gnu_cxx27__verbose_terminate_handlerEv.cold
    @          0x82b9bb6 __cxxabiv1::__terminate()
    @          0x82b9c21 std::terminate()
    @          0x82b9d75 __cxa_throw
    @          0x2fe6b34 std::__throw_system_error()
    @          0x47c66be starrocks::Tablet::max_continuous_version()
    @          0x4eac523 starrocks::CompactionTask::_commit_compaction()
    @          0x4eab949 starrocks::HorizontalCompactionTask::run_impl()
    @          0x4ea6c5a starrocks::CompactionTask::run()
    @          0x50cb70d starrocks::ThreadPool::dispatch_thread()
    @          0x50c653a starrocks::Thread::supervise_thread()
    @     0x7f195f036ea5 start_thread
    @     0x7f195e847b0d __clone
    @                0x0 (unknown)

### Expected behavior (Required)
no crash

### Real behavior (Required)
crash

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by meegoo**
Signed-off-by: meegoo <hujie-dlut@qq.com>

## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #17387 

## Problem Summary(Required) ：

Fix crash introduced by https://github.com/StarRocks/starrocks/pull/17008

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Review by sduzh — DISMISSED** [review]

**Comment by meegoo** [comment]
run starrocks_be_unittest

**Comment by meegoo** [comment]
run starrocks_be_unittest

**Review by chaoyli — APPROVED** [review]

**Comment by meegoo** [comment]
run starrocks_be_unittest

**Comment by meegoo** [comment]
run starrocks_be_unittest

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by meegoo** [comment]
run license/cla

**Comment by meegoo** [comment]
run starrocks_admit_test

**Comment by meegoo** [comment]
run starrocks_be_unittest

**Review by satanson — APPROVED** [review]

**Comment by meegoo** [comment]
run starrocks_be_unittest

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
