### PR TITLE
[Doc]the feature "the maximum length of a varchar value can be 1048576 bytes" is still under public testing

### PR DESCRIPTION
**Pull request by femiiii**
…es" is under public testing

## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [x] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

### CODE REVIEW

**Comment by femiiii** [comment]
@mergify backport branch-2.5 branch-2.4 branch-2.3

**Review by evelynzhaojie — APPROVED** [review]

**Review by EsoragotoSpirit — APPROVED** [review]

**Review by amber-create — APPROVED** [review]

**Comment by dulong41** [comment]
run starrocks_admit_test

**Comment by dulong41** [comment]
run starrocks_clang-tidy

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Comment by femiiii** [comment]
@dulong41  it is not for 2.5

**Pull request merged**
