### PR TITLE
[Enhancement] lambda functions can work with aggregation and window functions without lambda arguments

### PR DESCRIPTION
**Pull request by fzhedu**
…unctions.

Signed-off-by: fzhedu <fzhedu@gmail.com>

## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

let lambda functions work with aggregations and window functions
```
select array_agg(array_length(array_map(x->x*2, c3))) from test_array;


mysql> select array_map(x->x+ array_length(array_agg(x)),[2,6]) from t;
ERROR 1064 (HY000): Column '`__LAMBDA_TABLE`.`__LAMBDA_TABLE`.`x`' cannot be resolved
mysql> select array_map(x->x+ array_length(array_agg(a)),[2,6]) from t;
+----------------------------------------------------------+
| array_map(x -> x + (array_length(array_agg(a))), [2, 6]) |
+----------------------------------------------------------+
| [4,8]                                                    |
+----------------------------------------------------------+

mysql> select array_agg(a), array_map(x->(array_map((y,z)->y+z, x, array_agg(a))), [[2,4]]) from t;
+--------------+-----------------------------------------------------------------------+
| array_agg(a) | array_map(x -> array_map((y, z) -> y + z, x, array_agg(a)), [[2, 4]]) |
+--------------+-----------------------------------------------------------------------+
| [1,11]       | [[3,15]]                                                              |
+--------------+-----------------------------------------------------------------------+
1 row in set (0.02 sec)

mysql> select array_map(x->x+12, array_agg(a)) from t;
+--------------------------------------+
| array_map(x -> x + 12, array_agg(a)) |
+--------------------------------------+
| [13,23]                              |
+--------------------------------------+
1 row in set (0.03 sec)

mysql> select array_group(array_map(x->x+3,[2,6])) from test_array;
ERROR 1064 (HY000): No matching function with signature: array_group(ARRAY<smallint(6)>).

mysql> select array_map(x->x >  count(c1), c2) from test_array;
ERROR 1064 (HY000): 'array_map(x -> `__LAMBDA_TABLE`.`__LAMBDA_TABLE`.`x` > count(`test`.`test_array`.`c1`), `test`.`test_array`.`c2`)' must be an aggregate expression or appear in GROUP BY clause

mysql> select c2, count(c1), array_map(x->x >  count(c1), c2) from test_array group by c2;
+-------------+-----------+-------------------------------------+
| c2          | count(c1) | array_map(x -> x > (count(c1)), c2) |
+-------------+-----------+-------------------------------------+
| []          |         2 | []                                  |
| [3,4,5]     |         1 | [1,1,1]                             |
| [432,23]    |         1 | [1,1]                               |
| [2,4]       |         1 | [1,1]                               |
| NULL        |         3 | NULL                                |
| [null,null] |         1 | [null,null]                         |
+-------------+-----------+-------------------------------------+
6 rows in set (0.03 sec)

/// window functions 
mysql> select array_map(x-> x +  count(a) over (partition by a order by x),[111] ) from t;
ERROR 1064 (HY000): Column '`__LAMBDA_TABLE`.`__LAMBDA_TABLE`.`x`' cannot be resolved
mysql> select array_map(x-> x +  count(a) over (partition by a order by pv),[111] ) from t;
+------------------------------------------------------------------------------+
| array_map(x -> x + (count(a) OVER (PARTITION BY a ORDER BY pv ASC )), [111]) |
+------------------------------------------------------------------------------+
| [112]                                                                        |
| [113]                                                                        |
| [114]                                                                        |
| [112]                                                                        |
+------------------------------------------------------------------------------+
4 rows in set (0.03 sec)

mysql> select a, pv, count(a) over (partition by a order by pv) from t;
+------+------+-------------------------------------------------+
| a    | pv   | count(a) OVER (PARTITION BY a ORDER BY pv ASC ) |
+------+------+-------------------------------------------------+
|   11 |   33 |                                               1 |
|    1 |    3 |                                               1 |
|    1 |    4 |                                               2 |
|    1 |    5 |                                               3 |
+------+------+-------------------------------------------------+
4 rows in set (0.03 sec)

mysql> select a, pv, count(a) over (partition by array_map(x->x+1, [1]) order by pv) from t;
ERROR 1064 (HY000): order by type ARRAY<SMALLINT> is not supported
mysql> select a, pv, count(a) over (partition by array_sum(array_map(x->x+1, [1])) order by pv) from t;
+------+------+-------------------------------------------------------------------------------------+
| a    | pv   | count(a) OVER (PARTITION BY array_sum(array_map(x -> x + 1, [1])) ORDER BY pv ASC ) |
+------+------+-------------------------------------------------------------------------------------+
|    1 |    3 |                                                                                   1 |
|    1 |    4 |                                                                                   2 |
|    1 |    5 |                                                                                   3 |
|   11 |   33 |                                                                                   4 |
+------+------+-------------------------------------------------------------------------------------+
4 rows in set (0.04 sec)

```

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 7 / 7 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/analysis/SlotRef.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/transformer/ExpressionMapping.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AggregationAnalyzer.java|3|3|100.00%|[]|

**Comment by fzhedu** [comment]
run starrocks_admit_test

**Comment by fzhedu** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 7 / 7 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/analysis/SlotRef.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/transformer/ExpressionMapping.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AggregationAnalyzer.java|3|3|100.00%|[]|

**Review by HangyuanLiu — DISMISSED** [review]

**Comment by fzhedu** [comment]
run starrocks_fe_unittest

**Comment by fzhedu** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 7 / 7 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/analysis/SlotRef.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/transformer/ExpressionMapping.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AggregationAnalyzer.java|3|3|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 7 / 7 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/analysis/SlotRef.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/transformer/ExpressionMapping.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AggregationAnalyzer.java|3|3|100.00%|[]|

**Review by Seaven — APPROVED** [review]

**Review by HangyuanLiu — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by fzhedu** [comment]
run starrocks_admit_test

**Comment by fzhedu** [comment]
@mergify backport branch-2.5

**Pull request merged**
