### PR TITLE
Primary index support partial update.

### LINKED ISSUE #2212: Primary index needs support partial update for multi column
## Feature request

**Is your feature request related to a problem? Please describe.**
Primary index needs support partial update for multi column.

**Describe the solution you'd like**
Add a method to PrimaryIndex and HashIndex class inheritance to get primary columns' corresponding rowids.

### PR DESCRIPTION
**Pull request by Linkerist**
The primary index is also useful when a partial update. To clarify, add a method to PrimaryIndex and HashIndex class inheritance to get primary columns' corresponding rowids. resolve #2212

### CODE REVIEW

**Comment by decster** [comment]
Add some unittest?

**Comment by Linkerist** [comment]
> Add some unittest?

ok, done.

**Comment by Linkerist** [comment]
run starrocks_be_unittest

**Review by decster — APPROVED** [review]

**Comment by chaoyli** [comment]
What's the purpose of this pull request? Support primary index in partial update?

**Comment by Linkerist** [comment]
> What's the purpose of this pull request? Support primary index in partial update?

yes, provide get API for primary index to get partial columns mapping, use it after #2220 .

**Review by chaoyli — APPROVED** [review]

**Pull request merged**
