### PR TITLE
[Enhancement] upgrade aliyun jindo SDK and remove useless codes

### PR DESCRIPTION
**Pull request by miomiocat**
## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

upgrade aliyun jindo SDK to improve user experience

doc update: https://github.com/StarRocks/docs.zh-cn/pull/3793

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Comment by miomiocat** [comment]
run starrocks_fe_unittest

**Review by caneGuy — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by dirtysalt — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by miomiocat** [comment]
run starrocks_be_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by miomiocat** [comment]
run starrocks_admit_test

**Comment by wangruin** [comment]
run starrocks_admit_test image

**Review by dirtysalt — APPROVED** [review]

**Review by caneGuy — APPROVED** [review]

**Comment by xiaoyong-z** [comment]
@miomiocat dead-lock when closing oss file system in broker, maybe relate to this oss upgrade?
5f478700-90ae-496a-a7c0-623ac2ffd868

**Comment by chaoyli** [comment]
@mergify backport branch-2.5

**Pull request merged**
