### PR TITLE
[Cherry-pick][BugFix] Fix complex window + agg prune bug

### PR DESCRIPTION
**Pull request by Seaven**
## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by Seaven** [comment]
@mergify backport branch-2.2 branch-2.3

**Comment by wanpengfei-git** [comment]
starrocks_be_unittest succeeded.

**Review by wanpengfei-git — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
starrocks_be_unittest succeeded.

**Comment by Seaven** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
starrocks_be_unittest succeeded.

**Comment by Seaven** [comment]
run FE Sonar Build / build (pull_request)

**Review by kangkaisen — APPROVED** [review]

**Pull request merged**
