### PR TITLE
[BugFix] Fix excessive recursion and optimizer timeout due to too many OR

### LINKED ISSUE #12875: Excessive recursion and optimizer timeout due to too many OR
### Steps to reproduce the behavior (Required)
       String sql = "SELECT\n" +
                 "  *\n" +
                 "FROM t0\n" +
                 "WHERE\n" +
                 "  (\n" +
                 "    (v1 >= 27)\n" +
                 "    AND (v1 < 28)\n" +
                 "  )\n" +
                 "  OR (\n" +
                 "    (\n" +
                 "      (v1 >= 26)\n" +
                 "      AND (v1 < 27)\n" +
                 "    )\n" +
                 "    OR (\n" +
                 "      (\n" +
                 "        (v1 >= 25)\n" +
                 "        AND (v1 < 26)\n" +
                 "      )\n" +
                 "      OR (\n" +
                 "        (\n" +
                 "          (v1 >= 24)\n" +
                 "          AND (v1 < 25)\n" +
                 "        )\n" +
                 "        OR (\n" +
                 "          (\n" +
                 "            (v1 >= 23)\n" +
                 "            AND (v1 < 24)\n" +
                 "          )\n" +
                 "          OR (\n" +
                 "            (\n" +
                 "              (v1 >= 22)\n" +
                 "              AND (v1 < 23)\n" +
                 "            )\n" +
                 "            OR (\n" +
                 "              (\n" +
                 "                (v1 >= 21)\n" +
                 "                AND (v1 < 22)\n" +
                 "              )\n" +
                 "              OR (\n" +
                 "                (\n" +
                 "                  (v1 >= 20)\n" +
                 "                  AND (v1 < 21)\n" +
                 "                )\n" +
                 "                OR (\n" +
                 "                  (\n" +
                 "                    (v1 >= 19)\n" +
                 "                    AND (v1 < 20)\n" +
                 "                  )\n" +
                 "                  OR (\n" +
                 "                    (\n" +
                 "                      (v1 >= 18)\n" +
                 "                      AND (v1 < 19)\n" +
                 "                    )\n" +
                 "                    OR (\n" +
                 "                      (\n" +
                 "                        (v1 >= 17)\n" +
                 "                        AND (v1 < 18)\n" +
                 "                      )\n" +
                 "                      OR (\n" +
                 "                        (\n" +
                 "                          (v1 >= 16)\n" +
                 "                          AND (v1 < 17)\n" +
                 "                        )\n" +
                 "                        OR (\n" +
                 "                          (\n" +
                 "                            (v1 >= 15)\n" +
                 "                            AND (v1 < 16)\n" +
                 "                          )\n" +
                 "                          OR (\n" +
                 "                            (\n" +
                 "                              (v1 >= 14)\n" +
                 "                              AND (v1 < 15)\n" +
                 "                            )\n" +
                 "                            OR (\n" +
                 "                              (\n" +
                 "                                (v1 >= 13)\n" +
                 "                                AND (v1 < 14)\n" +
                 "                              )\n" +
                 "                              OR (\n" +
                 "                                (\n" +
                 "                                  (v1 >= 12)\n" +
                 "                                  AND (v1 < 13)\n" +
                 "                                )\n" +
                 "                                OR (\n" +
                 "                                  (\n" +
                 "                                    (v1 >= 11)\n" +
                 "                                    AND (v1 < 12)\n" +
                 "                                  )\n" +
                 "                                  OR (\n" +
                 "                                    (\n" +
                 "                                      (v1 >= 10)\n" +
                 "                                      AND (v1 < 11)\n" +
                 "                                    )\n" +
                 "                                    OR (\n" +
                 "                                      (\n" +
                 "                                        (v1 >= 09)\n" +
                 "                                        AND (v1 < 10)\n" +
                 "                                      )\n" +
                 "                                      OR (\n" +
                 "                                        (\n" +
                 "                                          (v1 >= 08)\n" +
                 "                                          AND (v1 < 09)\n" +
                 "                                        )\n" +
                 "                                        OR (\n" +
                 "                                          (\n" +
                 "                                            (v1 >= 07)\n" +
                 "                                            AND (v1 < 08)\n" +
                 "                                          )\n" +
                 "                                          OR (\n" +
                 "                                            (\n" +
                 "                                              (v1 >= 06)\n" +
                 "                                              AND (v1 < 07)\n" +
                 "                                            )\n" +
                 "                                            OR (\n" +
                 "                                              (\n" +
                 "                                                (v1 >= 05)\n" +
                 "                                                AND (v1 < 06)\n" +
                 "                                              )\n" +
                 "                                              OR (\n" +
                 "                                                (\n" +
                 "                                                  (v1 >= 04)\n" +
                 "                                                  AND (v1 < 05)\n" +
                 "                                                )\n" +
                 "                                                OR (\n" +
                 "                                                  (\n" +
                 "                                                    (v1 >= 03)\n" +
                 "                                                    AND (v1 < 04)\n" +
                 "                                                  )\n" +
                 "                                                  OR (\n" +
                 "                                                    (\n" +
                 "                                                      (v1 >= 02)\n" +
                 "                                                      AND (v1 < 03)\n" +
                 "                                                    )\n" +
                 "                                                    OR (\n" +
                 "                                                      (v1 >= 01)\n" +
                 "                                                      AND (v1 < 02)\n" +
                 "                                                    )\n" +
                 "                                                  )\n" +
                 "                                                )\n" +
                 "                                              )\n" +
                 "                                            )\n" +
                 "                                          )\n" +
                 "                                        )\n" +
                 "                                      )\n" +
                 "                                    )\n" +
                 "                                  )\n" +
                 "                                )\n" +
                 "                              )\n" +
                 "                            )\n" +
                 "                          )\n" +
                 "                        )\n" +
                 "                      )\n" +
                 "                    )\n" +
                 "                  )\n" +
                 "                )\n" +
                 "              )\n" +
                 "            )\n" +
                 "          )\n" +
                 "        )\n" +
                 "      )\n" +
                 "    )\n" +
                 "  )";

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by HangyuanLiu**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #12875

## Problem Summary(Required) ：

In the original method, there are too many repeated recursive calculations, which leads to a very slow acquisition time of statistical information when the number of ORs is large.
## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
BE Build Success

**Comment by wanpengfei-git** [comment]
BE Build Success

**Comment by wanpengfei-git** [comment]
BE Build Success

**Review by Seaven — APPROVED** [review]

**Review by kangkaisen — APPROVED** [review]

**Review by Youngwb — APPROVED** [review]

**Comment by HangyuanLiu** [comment]
run starrocks_admit_test

**Pull request merged**
