### PR TITLE
[BugFix] fix mv on union bug

### LINKED ISSUE #24460: count of materialized view on union is wrong
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
CREATE TABLE `customer_nullable_1` (
  `c_custkey` int(11) NULL COMMENT "",
  `c_name` varchar(26) NULL COMMENT "",
  `c_address` varchar(41) NULL COMMENT "",
  `c_city` varchar(11) NULL COMMENT "",
  `c_nation` varchar(16) NULL COMMENT "",
  `c_region` varchar(13) NULL COMMENT "",
  `c_phone` varchar(16) NOT NULL COMMENT "",
  `c_mktsegment` varchar(11) NOT NULL COMMENT ""
) ENGINE=OLAP
DUPLICATE KEY(`c_custkey`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`c_custkey`) BUCKETS 12
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"enable_persistent_index" = "false",
"replicated_storage" = "true",
"compression" = "LZ4"
);

CREATE TABLE `customer_nullable_2` (
  `c_custkey` int(11) NULL COMMENT "",
  `c_name` varchar(26) NULL COMMENT "",
  `c_address` varchar(41) NULL COMMENT "",
  `c_city` varchar(11) NULL COMMENT "",
  `c_nation` varchar(16) NULL COMMENT "",
  `c_region` varchar(13) NULL COMMENT "",
  `c_phone` varchar(16) NOT NULL COMMENT "",
  `c_mktsegment` varchar(11) NOT NULL COMMENT ""
) ENGINE=OLAP
DUPLICATE KEY(`c_custkey`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`c_custkey`) BUCKETS 12
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"enable_persistent_index" = "false",
"replicated_storage" = "true",
"compression" = "LZ4"
);

CREATE TABLE `customer_nullable_3` (
  `c_custkey` int(11) NULL COMMENT "",
  `c_name` varchar(26) NULL COMMENT "",
  `c_address` varchar(41) NULL COMMENT "",
  `c_city` varchar(11) NULL COMMENT "",
  `c_nation` varchar(16) NULL COMMENT "",
  `c_region` varchar(13) NULL COMMENT "",
  `c_phone` varchar(16) NOT NULL COMMENT "",
  `c_mktsegment` varchar(11) NOT NULL COMMENT "",
  `c_total` decimal128(19, 6) NULL DEFAULT "0.0" COMMENT ""
) ENGINE=OLAP
DUPLICATE KEY(`c_custkey`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`c_custkey`) BUCKETS 12
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"enable_persistent_index" = "false",
"replicated_storage" = "true",
"compression" = "LZ4"
);

2. INSERT INTO '....'

insert into customer_nullable_1(c_custkey, c_name, c_address, c_city, c_nation, c_region, c_phone, c_mktsegment) select c_custkey, c_name, c_address, c_city, c_nation, c_region, c_phone, c_mktsegment from customer limit 10;

insert into customer_nullable_2(c_custkey, c_name, c_address, c_city, c_nation, c_region, c_phone, c_mktsegment) select c_custkey, c_name, c_address, c_city, c_nation, c_region, c_phone, c_mktsegment from customer limit 10;

insert into customer_nullable_3(c_custkey, c_name, c_address, c_city, c_nation, c_region, c_phone, c_mktsegment) select c_custkey, c_name, c_address, c_city, c_nation, c_region, c_phone, c_mktsegment from customer_nullable_1;

3. create materialized view

CREATE MATERIALIZED VIEW `customer_mv` (custkey, name, phone, total)
COMMENT "MATERIALIZED_VIEW"
DISTRIBUTED BY HASH(`custkey`) BUCKETS 6
REFRESH MANUAL
PROPERTIES (
"replication_num" = "1",
"replicated_storage" = "true",
"storage_medium" = "HDD"
)
AS SELECT `customer_nullable_1`.`c_custkey` AS `custkey`, `customer_nullable_1`.`c_name` AS `name`, `customer_nullable_1`.`c_phone` AS `phone`, 0 AS `total`
FROM `ssb_100g_new`.`customer_nullable_1` UNION ALL SELECT `customer_nullable_2`.`c_custkey` AS `custkey`, NULL AS `name`, NULL AS `phone`, 0 AS `total`
FROM `ssb_100g_new`.`customer_nullable_2` UNION ALL SELECT `customer_nullable_3`.`c_custkey` AS `custkey`, NULL AS `name`, NULL AS `phone`, `customer_nullable_3`.`c_total` AS `total`
FROM `ssb_100g_new`.`customer_nullable_3`;

4. desc customer_mv
+---------+-------------+------+-------+---------+-------+
| Field   | Type        | Null | Key   | Default | Extra |
+---------+-------------+------+-------+---------+-------+
| custkey | int         | YES  | true  | NULL    |       |
| name    | varchar(26) | YES  | true  | NULL    |       |
| phone   | varchar(16) | NO   | false | NULL    | NONE  |
| total   | tinyint     | NO   | false | NULL    | NONE  |
+---------+-------------+------+-------+---------+-------+

### Expected behavior (Required)
+---------+-------------+------+-------+---------+-------+
| Field   | Type        | Null | Key   | Default | Extra |
+---------+-------------+------+-------+---------+-------+
| custkey | int         | YES  | true  | NULL    |       |
| name    | varchar(26) | YES  | true  | NULL    |       |
| phone   | varchar(16) | YES   | false | NULL    | NONE  |
| total   | decimal(19,6)     | YES   | false | NULL    | NONE  |
+---------+-------------+------+-------+---------+-------+
### Real behavior (Required)

+---------+-------------+------+-------+---------+-------+
| Field   | Type        | Null | Key   | Default | Extra |
+---------+-------------+------+-------+---------+-------+
| custkey | int         | YES  | true  | NULL    |       |
| name    | varchar(26) | YES  | true  | NULL    |       |
| phone   | varchar(16) | NO   | false | NULL    | NONE  |
| total   | tinyint     | NO   | false | NULL    | NONE  |
+---------+-------------+------+-------+---------+-------+
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by ABingHuang**
Fixes #24460 
the bugs' reason are:
1. the mv's column type and nullable are invalid
2. the refresh process does not fail when there are filtered rows.

Fix it by deriving the correct nullable property and column type for mv and enable insert strict mode for mv refresh.

## What type of PR is this:
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.0
  - [x] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Review by murphyatwork — DISMISSED** [review]

**Review by Astralidea — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 11 / 11 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/QueryAnalyzer.java|6|6|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java|5|5|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 11 / 11 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/QueryAnalyzer.java|6|6|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java|5|5|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 11 / 11 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/QueryAnalyzer.java|6|6|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java|5|5|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 11 / 11 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/QueryAnalyzer.java|6|6|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java|5|5|100.00%|[]|

**Review by Astralidea — APPROVED** [review]

**Review by murphyatwork — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
