### PR TITLE
[Enhancement] Upgrade hudi dependency version to 0.12.1

### PR DESCRIPTION
**Pull request by miomiocat**
## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

upgrade hudi dependency to the latest version and resolve class conflicts

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by stephen-shelby** [comment]
run starrocks_admit_test

**Comment by stephen-shelby** [comment]
I think the failure of stream load in admin_test isn't an accident. I have reproducted this issue by your branch.

**Comment by miomiocat** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by miomiocat** [comment]
run starrocks_admit_test

**Review by stephen-shelby — APPROVED** [review]

**Comment by stephen-shelby** [comment]
run starrocks_admit_test

**Review by caneGuy — APPROVED** [review]

**Comment by Astralidea** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
