### PR TITLE
capture RuntimeState in shared_ptr to avoid MemTracker inside it to be freed

### PR DESCRIPTION
**Pull request by satanson**
## What type of PR is this：
- [x ] bug
- [ ] feature
- [ ] enhancement
- [ ] others

## Which issues of this PR fixes ：

Fixes #

### CODE REVIEW

**Comment by satanson** [comment]
run starrocks_be_unittest

**Comment by satanson** [comment]
@mergifyio rebase

**Comment by satanson** [comment]
@Mergifyio rebase

**Comment by stdpain** [comment]
run starrocks_be_unittest

**Comment by satanson** [comment]
@Mergifyio rebase

**Comment by satanson** [comment]
@stdpain @kangkaisen http://39.101.206.100:8090/view/Daily/job/master_release/898/#showFailuresLink, no BE have crashed

**Review by stdpain — APPROVED** [review]

**Review by kangkaisen — APPROVED** [review]

**Pull request merged**
