### PR TITLE
[BugFix] Fix fe meta error when use merge condition

### PR DESCRIPTION
**Pull request by caneGuy**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

Related with #12159 we should not add new fields into loadjob

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

### CODE REVIEW

**Review by gengjun-git — DISMISSED** [review]

**Review by gengjun-git — APPROVED** [review]

**Comment by Astralidea** [comment]
run starrocks_fe_unittest

**Review by Astralidea — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 1 / 4 (25.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/analysis/BrokerDesc.java|0|3|00.00%|[79, 80, 82]|
|:large_blue_circle:|com/starrocks/load/loadv2/BrokerLoadJob.java|1|1|100.00%|[]|

**Comment by decster** [comment]
@mergify backport branch-2.5

**Pull request merged**
