### PR TITLE
[Enhancment] Add MorselsCount and TabletCount to profile of scan operator

### PR DESCRIPTION
**Pull request by ZiheLiu**
## What type of PR is this：
- [ ] bug
- [ ] feature
- [x] enhancement
- [ ] refactor
- [ ] others

## Problem Summary(Required) ：

Add `MorselsCount` and `TabletCount` to profile of scan operator.

### CODE REVIEW

**Comment by ZiheLiu** [comment]
@Mergifyio backport branch-2.3

**Review by liuyehcf — DISMISSED** [review]

**Comment by kangkaisen** [comment]
```
if SharedScan in profile is true, TabletCount will be dop*real_tablets_count.
```
Why the TabletCount couldn't be equal to the  real_tablets_count?

**Review by murphyatwork — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by ZiheLiu** [comment]
> ```
> if SharedScan in profile is true, TabletCount will be dop*real_tablets_count.
> ```
> 
> Why the TabletCount couldn't be equal to the real_tablets_count always?

Fixed it.

**Comment by ZiheLiu** [comment]
run starrocks_be_unittest

**Comment by ZiheLiu** [comment]
run all

**Review by liuyehcf — APPROVED** [review]

**Review by murphyatwork — APPROVED** [review]

**Pull request merged**
