### PR TITLE
[BugFix] search globalUdfFunction only when GlobalStateMgr() is available

### LINKED ISSUE #29209: stream load failed with vague error message
```
$ curl --location-trusted -u root -p -H "label:label_000" \
    -H "format: CSV" \
    -H "skip_header: 1" \
    -H "column_separator:," \
    -H "columns: col1,sender,receiver,txhash,timestamp=str_to_date(col1)" \
    -T USDC-Polygon-transfers.csv -XPUT \
    https://<be_ip>:<be_port>/api/test_db/<table>/_stream_load
{
    "TxnId": 1010,
    "Label": "label_000",
    "Status": "Fail",
    "Message": "",
    "NumberTotalRows": 0,
    "NumberLoadedRows": 0,
    "NumberFilteredRows": 0,
    "NumberUnselectedRows": 0,
    "LoadBytes": 0,
    "LoadTimeMs": 0,
    "BeginTxnTimeMs": 3,
    "StreamLoadPlanTimeMs": 5,
    "ReadDataTimeMs": 0,
    "WriteDataTimeMs": 0,
    "CommitAndPublishTimeMs": 0
}
curl: (18) HTTP/2 stream 1 was reset
```

BE LOG:
```
W0815 00:27:05.901499   749 stream_load.cpp:591] plan streaming load failed. errmsg=id=ed483fd735c45ff7-02b078b89403e887, job_id=-1, txn_id: 1010, label=label_000, db=test_db
```

FE LOG:
```
2023-08-15 00:27:05,901 INFO (thrift-server-pool-102|346) [FrontendServiceImpl.loadTxnRollback():1328] receive txn rollback request. db: test_db, tbl: ***, txn_id: 1010, reason: , backend: ***
at java.lang.Thread.run(Thread.java:829) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
at com.starrocks.common.SRTThreadPoolServer$WorkerProcess.run(SRTThreadPoolServer.java:311) ~[starrocks-fe.jar:?]
at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:38) ~[libthrift-0.13.0.jar:0.13.0]
at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:38) ~[libthrift-0.13.0.jar:0.13.0]
at com.starrocks.thrift.FrontendService$Processor$streamLoadPut.getResult(FrontendService.java:3326) ~[starrocks-fe.jar:?]
at com.starrocks.thrift.FrontendService$Processor$streamLoadPut.getResult(FrontendService.java:3346) ~[starrocks-fe.jar:?]
at com.starrocks.service.FrontendServiceImpl.streamLoadPut(FrontendServiceImpl.java:1433) ~[starrocks-fe.jar:?]
at com.starrocks.service.FrontendServiceImpl.streamLoadPutImpl(FrontendServiceImpl.java:1479) ~[starrocks-fe.jar:?]
at com.starrocks.planner.StreamLoadPlanner.plan(StreamLoadPlanner.java:181) ~[starrocks-fe.jar:?]
at com.starrocks.planner.StreamLoadScanNode.init(StreamLoadScanNode.java:186) ~[starrocks-fe.jar:?]
at com.starrocks.planner.StreamLoadScanNode.initParams(StreamLoadScanNode.java:228) ~[starrocks-fe.jar:?]
at com.starrocks.planner.StreamLoadScanNode.initColumns(StreamLoadScanNode.java:234) ~[starrocks-fe.jar:?]
at com.starrocks.load.Load.initColumns(Load.java:640) ~[starrocks-fe.jar:?]
at com.starrocks.load.Load.analyzeMappingExprs(Load.java:780) ~[starrocks-fe.jar:?]
at com.starrocks.analysis.Expr.analyzeAndCastFold(Expr.java:1435) ~[starrocks-fe.jar:?]
at com.starrocks.sql.analyzer.ExpressionAnalyzer.analyzeExpressionIgnoreSlot(ExpressionAnalyzer.java:1623) ~[starrocks-fe.jar:?]
at com.starrocks.sql.analyzer.ExpressionAnalyzer.analyzeIgnoreSlot(ExpressionAnalyzer.java:127) ~[starrocks-fe.jar:?]
at com.starrocks.sql.analyzer.ExpressionAnalyzer.bottomUpAnalyze(ExpressionAnalyzer.java:331) ~[starrocks-fe.jar:?]
at com.starrocks.sql.ast.AstVisitor.visit(AstVisitor.java:55) ~[starrocks-fe.jar:?]
at com.starrocks.analysis.FunctionCallExpr.accept(FunctionCallExpr.java:487) ~[starrocks-fe.jar:?]
at com.starrocks.sql.analyzer.ExpressionAnalyzer$Visitor.visitFunctionCall(ExpressionAnalyzer.java:334) ~[starrocks-fe.jar:?]
at com.starrocks.sql.analyzer.ExpressionAnalyzer$Visitor.visitFunctionCall(ExpressionAnalyzer.java:1078) ~[starrocks-fe.jar:?]
at com.starrocks.sql.analyzer.AnalyzerUtils.getUdfFunction(AnalyzerUtils.java:213) ~[starrocks-fe.jar:?]
at com.starrocks.sql.analyzer.AnalyzerUtils.getGlobalUdfFunction(AnalyzerUtils.java:198) ~[starrocks-fe.jar:?]
java.lang.NullPointerException: null
2023-08-15 00:27:05,900 WARN (thrift-server-pool-103|347) [FrontendServiceImpl.streamLoadPut():1439] catch unknown result.
```

It is the `timestamp=str_to_date(col1)` incorrect use of `str_to_date` causes the error. The failure is reasonable, but the error message doesn't to the stream load response, doesn't contain any useful information, neither in the BE log.

Need improve the failure reason so the end user can easily understand and adjust the request accordingly.

### PR DESCRIPTION
**Pull request by kevincai**
* take StarRocksPlannerException as ANALYSIS_ERROR error, so the user can get detailed error info.

Fixes #29209

## What type of PR is this:
- [X] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [X] I have checked the version labels which the pr will be auto-backported to the target branch
  - [X] 3.1
  - [X] 3.0
  - [X] 2.5
  - [ ] 2.4

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 1 / 2 (50.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/service/FrontendServiceImpl.java|0|1|00.00%|[1639]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AnalyzerUtils.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 1 / 2 (50.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/service/FrontendServiceImpl.java|0|1|00.00%|[1639]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AnalyzerUtils.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/service/FrontendServiceImpl.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AnalyzerUtils.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/service/FrontendServiceImpl.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AnalyzerUtils.java|1|1|100.00%|[]|

**Review by starrocks-xupeng — APPROVED** [review]

**Review by stdpain — APPROVED** [review]

**Review by wyb — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
