### PR TITLE
[BugFix] fix mv with ttl rewrite bug

### LINKED ISSUE #14821: [materialized view]not rewrite when use ttl
### Steps to reproduce the behavior (Required)
```
CREATE TABLE t1 (
                            k1 INT,
                            v1 INT,
                            v2 INT)
                        DUPLICATE KEY(k1)
                        PARTITION BY RANGE(`k1`)
                        (
                        PARTITION `p1` VALUES LESS THAN ('2'),
                        PARTITION `p2` VALUES LESS THAN ('3'),
                        PARTITION `p3` VALUES LESS THAN ('4'),
                        PARTITION `p4` VALUES LESS THAN ('5'),
                        PARTITION `p5` VALUES LESS THAN ('6'),
                        PARTITION `p6` VALUES LESS THAN ('7')
                        )
                        DISTRIBUTED BY HASH(k1);
                        insert into t1 values (1,1,1),(1,1,2),(1,2,1),(1,2,2),
                                              (2,1,1),(2,1,2),(2,2,1),(2,2,2),
                                              (3,1,1),(3,1,2),(3,2,1),(3,2,2);
CREATE MATERIALIZED VIEW mv1
               PARTITION BY k1
               DISTRIBUTED BY HASH(k1) BUCKETS 10
               REFRESH ASYNC
               PROPERTIES(
               "partition_ttl_number"="4"
               )
               AS SELECT k1, sum(v1) as sum_v1 FROM t1 group by k1;
```
waite refresh ok and partitions of mv1 deleted
`explain select k1, sum(v1) FROM t1 where k1=3 group by k1;`
### Expected behavior (Required)
`TABLE: mv1`
### Real behavior (Required)
`TABLE: t1`
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by ABingHuang**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #14821 

## Problem Summary(Required) ：

fix mv with ttl rewrite bug. the reason for the bug is that the calculation of 
partial partition predicate is wrong. fix it by sorting the range of partition before merge.
## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Review by kangkaisen — DISMISSED** [review]

**Review by Youngwb — APPROVED** [review]

**Review by kangkaisen — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by ABingHuang** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 4 / 4 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/MvUtils.java|2|2|100.00%|[]|

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
