### PR TITLE
[Enhancement] array_agg supports distinct (backport #29907)

### PR DESCRIPTION
**Pull request by fzhedu**
* [Enhancement] array_agg supports distinct

---------

Fixes #issue

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:disappointed: **fail** : 46 / 62 (74.19%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/SplitAggregateRule.java|0|5|00.00%|[282, 283, 284, 288, 289]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/RewriteMultiDistinctRule.java|1|7|14.29%|[88, 188, 189, 190, 192, 193]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/RewriteMultiDistinctByCTERule.java|1|2|50.00%|[288]|
|:large_blue_circle:|com/starrocks/sql/analyzer/FunctionAnalyzer.java|3|4|75.00%|[165]|
|:large_blue_circle:|com/starrocks/sql/analyzer/ExpressionAnalyzer.java|12|15|80.00%|[872, 879, 880]|
|:large_blue_circle:|com/starrocks/catalog/FunctionSet.java|19|19|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/plan/PlanFragmentBuilder.java|6|6|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/DecimalV3FunctionAnalyzer.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AstToStringBuilder.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/GroupByCountDistinctRewriteRule.java|2|2|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 19 / 49 (38.78%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/exprs/agg/array_agg.h|8|37|21.62%|[35, 37, 38, 50, 52, 54, 57, 58, 61, 63, 64, 65, 66, 67, 68, 70, 71, 74, 75, 77, 80, 81, 84, 86, 87, 88, 90, 91, 92]|
|:large_blue_circle:|src/exec/aggregator.cpp|2|3|66.67%|[398]|
|:large_blue_circle:|src/exprs/agg/factory/aggregate_resolver_avg.cpp|9|9|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 19 / 49 (38.78%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/exprs/agg/array_agg.h|8|37|21.62%|[35, 37, 38, 50, 52, 54, 57, 58, 61, 63, 64, 65, 66, 67, 68, 70, 71, 74, 75, 77, 80, 81, 84, 86, 87, 88, 90, 91, 92]|
|:large_blue_circle:|src/exec/aggregator.cpp|2|3|66.67%|[398]|
|:large_blue_circle:|src/exprs/agg/factory/aggregate_resolver_avg.cpp|9|9|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 19 / 49 (38.78%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/exprs/agg/array_agg.h|8|37|21.62%|[35, 37, 38, 50, 52, 54, 57, 58, 61, 63, 64, 65, 66, 67, 68, 70, 71, 74, 75, 77, 80, 81, 84, 86, 87, 88, 90, 91, 92]|
|:large_blue_circle:|src/exec/aggregator.cpp|2|3|66.67%|[398]|
|:large_blue_circle:|src/exprs/agg/factory/aggregate_resolver_avg.cpp|9|9|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:disappointed: **fail** : 50 / 66 (75.76%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/SplitAggregateRule.java|0|5|00.00%|[282, 283, 284, 288, 289]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/RewriteMultiDistinctRule.java|1|7|14.29%|[88, 188, 189, 190, 192, 193]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/RewriteMultiDistinctByCTERule.java|1|2|50.00%|[288]|
|:large_blue_circle:|com/starrocks/sql/analyzer/FunctionAnalyzer.java|3|4|75.00%|[165]|
|:large_blue_circle:|com/starrocks/sql/analyzer/ExpressionAnalyzer.java|16|19|84.21%|[881, 888, 889]|
|:large_blue_circle:|com/starrocks/catalog/FunctionSet.java|19|19|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/plan/PlanFragmentBuilder.java|6|6|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/DecimalV3FunctionAnalyzer.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AstToStringBuilder.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/GroupByCountDistinctRewriteRule.java|2|2|100.00%|[]|

**Review by kangkaisen — APPROVED** [review]

**Pull request merged**
