### PR TITLE
[Enhancement] add flag `hudi_mor_force_jni_reader`

### PR DESCRIPTION
**Pull request by dirtysalt**
## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [X] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

Right now, HUDI MOR and COW have two different impls. MOR goes via JNI and COW goes via C++. And If MOR has no delta logs, it also goes via C++(not JNI), which is hard for us to test. Because sometimes QA does not know if there is delta logs or not.

So the purpose of this SV is to enfoce hudi mor reader goes via JNI, we can test it thoroughly.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Review by miomiocat — APPROVED** [review]
LGTM

**Review by stephen-shelby — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 1 / 9 (11.11%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/connector/RemoteScanRangeLocations.java|0|4|00.00%|[200, 212, 213, 214]|
|:large_blue_circle:|com/starrocks/qe/CoordinatorPreprocessor.java|0|3|00.00%|[1015, 1016, 1018]|
|:large_blue_circle:|com/starrocks/qe/SessionVariable.java|1|2|50.00%|[849]|

**Review by Youngwb — APPROVED** [review]

**Comment by dirtysalt** [comment]
@MergifyIO backport branch-2.5

**Pull request merged**
