### PR TITLE
[BugFix]Revert "[Enhancement] remove some useless operatitons when start as c…

### PR DESCRIPTION
**Pull request by abc982627271**
…n (#31947)"

This reverts commit 6b577c1926fd68bffb5675b23fdfff0ba14dc7fd.

Fixes #issue

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Review by sduzh — APPROVED** [review]

**Review by wyb — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 9 / 12 (75.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/agent/heartbeat_server.cpp|0|1|00.00%|[221]|
|:large_blue_circle:|src/storage/storage_engine.h|0|1|00.00%|[268]|
|:large_blue_circle:|src/service/service_be/starrocks_be.cpp|0|1|00.00%|[100]|
|:large_blue_circle:|src/storage/storage_engine.cpp|7|7|100.00%|[]|
|:large_blue_circle:|src/storage/data_dir.cpp|2|2|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 9 / 12 (75.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/agent/heartbeat_server.cpp|0|1|00.00%|[221]|
|:large_blue_circle:|src/storage/storage_engine.h|0|1|00.00%|[268]|
|:large_blue_circle:|src/service/service_be/starrocks_be.cpp|0|1|00.00%|[100]|
|:large_blue_circle:|src/storage/storage_engine.cpp|7|7|100.00%|[]|
|:large_blue_circle:|src/storage/data_dir.cpp|2|2|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 9 / 12 (75.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/agent/heartbeat_server.cpp|0|1|00.00%|[221]|
|:large_blue_circle:|src/storage/storage_engine.h|0|1|00.00%|[268]|
|:large_blue_circle:|src/service/service_be/starrocks_be.cpp|0|1|00.00%|[100]|
|:large_blue_circle:|src/storage/storage_engine.cpp|7|7|100.00%|[]|
|:large_blue_circle:|src/storage/data_dir.cpp|2|2|100.00%|[]|

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.2

**Pull request merged**
