### PR TITLE
[Enhancement] Reject create table request if checkPersistentIndex failed

### PR DESCRIPTION
**Pull request by sevev**
## What type of PR is this：
- [ ] bug
- [ ] feature
- [x] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

PersistentIndex is available in version 2.3, but there are many limitations in key columns. For example, key column is not supported as varchar(char) type, and the length of key columns cannot exceed 64 bytes.

In the previous implementation, if we create a primary key table enable PersistentIndex but the restrictions are not met, we will use PrimaryIndex in memory but not PersistentIndex, and primary key table will be create successfully. This may be a bit confusing to the user.

So we will reject the create  table request directly if we find that the restrictions are not met.

### CODE REVIEW

**Comment by sevev** [comment]
run starrocks_fe_unittest

**Comment by sevev** [comment]
run starrocks_admit_test

**Comment by sevev** [comment]
run starrocks_fe_unittest

**Comment by sevev** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 3 / 18 (16.67%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/OlapTable.java|2|16|12.50%|[1535, 1536, 1537, 1538, 1540, 1541, 1542, 1543, 1546, 1547, 1548, 1549, 1550, 1552]|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|1|2|50.00%|[1754]|

**Comment by sevev** [comment]
run starrocks_admit_test

**Comment by sevev** [comment]
run starrocks_fe_unittest

**Comment by sevev** [comment]
run starrocks_admit_test

**Comment by sevev** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 18 / 25 (72.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|1|3|33.33%|[1754, 1755]|
|:large_blue_circle:|com/starrocks/catalog/OlapTable.java|10|14|71.43%|[1539, 1540, 1546, 1547]|
|:large_blue_circle:|com/starrocks/alter/Alter.java|7|8|87.50%|[486]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 13 / 20 (65.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|1|3|33.33%|[1754, 1755]|
|:large_blue_circle:|com/starrocks/alter/SchemaChangeHandler.java|2|3|66.67%|[1601]|
|:large_blue_circle:|com/starrocks/catalog/OlapTable.java|10|14|71.43%|[1539, 1540, 1546, 1547]|

**Comment by sevev** [comment]
run starrocks_admit_test

**Review by decster — APPROVED** [review]

**Review by chaoyli — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Pull request merged**
