### PR TITLE
[Feature] New RBAC framework: PrivilegeManager persist as image

### PR DESCRIPTION
**Pull request by padmejin**
## What type of PR is this：
- [ ] BugFix
- [x] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

Introduce a new privilege framework.
To avoid huge PR which is hard to review and easy to conflict, I'm splitting into several small PR, each implementing an individual aspect of the new privilege framework. This is the fifth one. For previous PRs see 
https://github.com/StarRocks/starrocks/pull/11447
https://github.com/StarRocks/starrocks/pull/11528
https://github.com/StarRocks/starrocks/pull/11593
https://github.com/StarRocks/starrocks/pull/11732

This PR implements the `save()` and `load()` function of the `PrivilegeManager` class so that it can be persisted in image.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by padmejin** [comment]
run starrocks_fe_unittest

**Comment by padmejin** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 42 / 52 (80.77%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|0|2|00.00%|[1323, 1534]|
|:large_blue_circle:|com/starrocks/authentication/AuthenticationManager.java|0|1|00.00%|[271]|
|:large_blue_circle:|com/starrocks/privilege/PrivilegeManager.java|42|49|85.71%|[350, 351, 367, 382, 383, 391, 392]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 54 / 67 (80.60%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/ResourceGroupMgr.java|1|2|50.00%|[148]|
|:large_blue_circle:|com/starrocks/authentication/AuthenticationManager.java|3|6|50.00%|[73, 74, 275]|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|8|10|80.00%|[1321, 1532]|
|:large_blue_circle:|com/starrocks/privilege/PrivilegeManager.java|42|49|85.71%|[352, 353, 369, 383, 384, 392, 393]|

**Review by gengjun-git — DISMISSED** [review]

**Comment by padmejin** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 43 / 54 (79.63%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|0|2|00.00%|[1319, 1530]|
|:large_blue_circle:|com/starrocks/authentication/AuthenticationManager.java|0|1|00.00%|[337]|
|:large_blue_circle:|com/starrocks/catalog/ResourceGroupMgr.java|1|2|50.00%|[148]|
|:large_blue_circle:|com/starrocks/privilege/PrivilegeManager.java|42|49|85.71%|[352, 353, 369, 383, 384, 392, 393]|

**Comment by padmejin** [comment]
run starrocks_admit_test

**Comment by padmejin** [comment]
run starrocks_admit_test

**Review by nshangyiming — APPROVED** [review]

**Comment by padmejin** [comment]
@mergify rebase

**Comment by padmejin** [comment]
run starrocks_admit_test

**Review by gengjun-git — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by meegoo — APPROVED** [review]

**Pull request merged**
