### PR TITLE
[Enhancement] set exception_stack_level and white/black lists

### PR DESCRIPTION
**Pull request by fzhedu**
Signed-off-by: fzhedu <fzhedu@gmail.com>

## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes # https://github.com/StarRocks/StarRocksTest/issues/1495

## Problem Summary(Required) ：

Add `exception_stack_level` to control when to print exception's stack
1. -1, enable print all exceptions' stack
2. 0, disable print exceptions' stack
3. 1, print the white list's exceptions' stack (default)
4.  2, print all exceptions' stack that is not in black_lists
5.  other value means the default value

### results
```
mysql> select get_json_int('{"a": "str"}', '$.a');
+-------------------------------------+
| get_json_int('{"a": "str"}', '$.a') |
+-------------------------------------+
|                                NULL |
+-------------------------------------+
```
default parameters (unit: ns)
```
print exception stack cost time = 4779
print exception stack cost time = 5143
print exception stack cost time = 4650
print exception stack cost time = 4107
print exception stack cost time = 3230
print exception stack cost time = 3287
print exception stack cost time = 3515
print exception stack cost time = 6829
print exception stack cost time = 6565
print exception stack cost time = 8008
print exception stack cost time = 6212
print exception stack cost time = 5614
print exception stack cost time = 5532
print exception stack cost time = 6493
print exception stack cost time = 6325
```
-1 (print all stack) (unit: ns)

```
print exception stack cost time = 57949400
print exception stack cost time = 56149434
print exception stack cost time = 56165425
print exception stack cost time = 57021296
print exception stack cost time = 56560388
print exception stack cost time = 56647435
```

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [x] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Review by murphyatwork — DISMISSED** [review]

**Review by silverbullet233 — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by murphyatwork — DISMISSED** [review]

**Review by kangkaisen — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by fzhedu** [comment]
run starrocks_be_unittest

**Comment by fzhedu** [comment]
run starrocks_admit_test

**Comment by fzhedu** [comment]
run starrocks_be_unittest

**Comment by fzhedu** [comment]
run starrocks_admit_test

**Review by Pslydhh — APPROVED** [review]

**Comment by Pslydhh** [comment]
run starrocks_be_unittest

**Comment by Pslydhh** [comment]
run starrocks_admit_test

**Review by silverbullet233 — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by kangkaisen — APPROVED** [review]

**Review by Pslydhh — APPROVED** [review]

**Review by murphyatwork — APPROVED** [review]

**Comment by fzhedu** [comment]
@mergify backport branch-2.5

**Pull request merged**
