### PR TITLE
[Bugfix] fix star mgr get wrong db name

### PR DESCRIPTION
**Pull request by starrocks-xupeng**
## What type of PR is this：
- [x] bugfix
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Review by wyb — DISMISSED** [review]

**Review by imay — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 3 / 3 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/journal/bdbje/BDBJEJournal.java|3|3|100.00%|[]|

**Comment by starrocks-xupeng** [comment]
run starrocks_admit_test

**Comment by starrocks-xupeng** [comment]
run starrocks_admit_test

**Comment by starrocks-xupeng** [comment]
run starrocks_admit_test

**Pull request merged**
