### PR TITLE
[BugFix] Fix replace function bugs when input is a const null column

### LINKED ISSUE #18758: [StarOS] BE crash from sqlsmith query: MysqlRowBuffer::_push_string_normal
### Steps to reproduce the behavior (Required)
create ssb tables and load 1G data
BE crash with sql:
````sql
mysql> use ssb_1g;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> select     pi() as c0,    cast(nullif(append_trailing_char_if_absent(       cast(case when true then cast(null as VARCHAR) else cast(null as VARCHAR) end          as VARCHAR),       cast(cast(null as VARCHAR) as VARCHAR)),     cast(coalesce(case when (7 <> 71)            or (86 >= 38) then cast(nullif(cast(nullif(cast(null as VARCHAR),             cast(null as VARCHAR)) as VARCHAR),           cast(null as VARCHAR)) as VARCHAR) else cast(nullif(cast(nullif(cast(null as VARCHAR),             cast(null as VARCHAR)) as VARCHAR),           cast(null as VARCHAR)) as VARCHAR) end         ,       case when 91 is not NULL then case when cast(null as VARCHAR) < cast(null as VARCHAR) then cast(null as VARCHAR) else cast(null as VARCHAR) end            else case when cast(null as VARCHAR) < cast(null as VARCHAR) then cast(null as VARCHAR) else cast(null as VARCHAR) end            end         ) as VARCHAR)) as VARCHAR) as c1,    case when 49 >= 32 then case when (case when cast(null as VARCHAR) > cast(null as VARCHAR) then cast(null as VARCHAR) else cast(null as VARCHAR) end              > cast(null as VARCHAR))          and (true) then replace(         cast(cast(nullif(cast(null as VARCHAR),           case when cast(null as VARCHAR) >= cast(null as VARCHAR) then cast(null as VARCHAR) else cast(null as VARCHAR) end             ) as VARCHAR) as VARCHAR),         cast(case when (cast(null as VARCHAR) <> cast(null as VARCHAR))              and (cast(null as VARCHAR) <> cast(null as VARCHAR)) then cast(null as VARCHAR) else cast(null as VARCHAR) end            as VARCHAR),         cast(cast(coalesce(cast(nullif(cast(null as VARCHAR),             cast(null as VARCHAR)) as VARCHAR),           cast(null as VARCHAR)) as VARCHAR) as VARCHAR)) else replace(         cast(cast(nullif(cast(null as VARCHAR),           case when cast(null as VARCHAR) >= cast(null as VARCHAR) then cast(null as VARCHAR) else cast(null as VARCHAR) end             ) as VARCHAR) as VARCHAR),         cast(case when (cast(null as VARCHAR) <> cast(null as VARCHAR))              and (cast(null as VARCHAR) <> cast(null as VARCHAR)) then cast(null as VARCHAR) else cast(null as VARCHAR) end            as VARCHAR),         cast(cast(coalesce(cast(nullif(cast(null as VARCHAR),             cast(null as VARCHAR)) as VARCHAR),           cast(null as VARCHAR)) as VARCHAR) as VARCHAR)) end        else case when (case when cast(null as VARCHAR) > cast(null as VARCHAR) then cast(null as VARCHAR) else cast(null as VARCHAR) end              > cast(null as VARCHAR))          and (true) then replace(         cast(cast(nullif(cast(null as VARCHAR),           case when cast(null as VARCHAR) >= cast(null as VARCHAR) then cast(null as VARCHAR) else cast(null as VARCHAR) end             ) as VARCHAR) as VARCHAR),         cast(case when (cast(null as VARCHAR) <> cast(null as VARCHAR))              and (cast(null as VARCHAR) <> cast(null as VARCHAR)) then cast(null as VARCHAR) else cast(null as VARCHAR) end            as VARCHAR),         cast(cast(coalesce(cast(nullif(cast(null as VARCHAR),             cast(null as VARCHAR)) as VARCHAR),           cast(null as VARCHAR)) as VARCHAR) as VARCHAR)) else replace(         cast(cast(nullif(cast(null as VARCHAR),           case when cast(null as VARCHAR) >= cast(null as VARCHAR) then cast(null as VARCHAR) else cast(null as VARCHAR) end             ) as VARCHAR) as VARCHAR),         cast(case when (cast(null as VARCHAR) <> cast(null as VARCHAR))              and (cast(null as VARCHAR) <> cast(null as VARCHAR)) then cast(null as VARCHAR) else cast(null as VARCHAR) end            as VARCHAR),         cast(cast(coalesce(cast(nullif(cast(null as VARCHAR),             cast(null as VARCHAR)) as VARCHAR),           cast(null as VARCHAR)) as VARCHAR) as VARCHAR)) end        end      as c2,    cast(coalesce(unix_timestamp(),     year(       cast(cast(coalesce(case when cast(null as DOUBLE) > cast(null as DOUBLE) then cast(null as DATETIME) else cast(null as DATETIME) end           ,         cast(coalesce(cast(null as DATETIME),           cast(null as DATETIME)) as DATETIME)) as DATETIME) as DATETIME))) as INT) as c3 from    ssb_1g.lineorder as ref_0 where true;
ERROR 1064 (HY000): Backend node not found. Check if any backend node is down.backend: [172.26.92.201 alive: true inBlacklist: false] [172.26.92.200 alive: true inBlacklist: true] [172.26.92.202 alive: false inBlacklist: false]
````

be.out:
```
*** Aborted at 1677676606 (unix time) try "date -d @1677676606" if you are using GNU date ***
PC: @          0x67e4cba starrocks::MysqlRowBuffer::_push_string_normal()
*** SIGSEGV (@0x0) received by PID 5818 (TID 0x7ff6d7fb1700) from PID 0; stack trace: ***
    @          0x77bb532 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7ff75c176655 os::Linux::chained_handler()
    @     0x7ff75c17b481 JVM_handle_linux_signal
    @     0x7ff75c16e678 signalHandler()
    @     0x7ff75b297630 (unknown)
    @          0x67e4cba starrocks::MysqlRowBuffer::_push_string_normal()
    @          0x665fd9c starrocks::MysqlResultWriter::process_chunk()
    @          0x65a6695 starrocks::pipeline::ResultSinkOperator::push_chunk()
    @          0x449d3f8 starrocks::pipeline::PipelineDriver::process()
    @          0x64f5f81 starrocks::pipeline::GlobalDriverExecutor::_worker_thread()
    @          0x6812d6d starrocks::ThreadPool::dispatch_thread()
    @          0x680cf6a starrocks::Thread::supervise_thread()
    @     0x7ff75b28fea5 start_thread
    @     0x7ff75aaa08dd __clone
    @                0x0 (unknown)
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
UNKNOWN-f763a0591
```

### PR DESCRIPTION
**Pull request by LiShuMing**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Problem Summary(Required) ：

Fix #18758

`replace` function should take attention when input column is a const coumn:
- if input is only_null, return input directly;
- if input is const_column, use input's column size instead of ColumnViewer's size as num_row.

Add unit tests for two cases.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 3.0
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Review by satanson — APPROVED** [review]

**Review by kangkaisen — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by murphyatwork — APPROVED** [review]

**Comment by mofeiatwork** [comment]
run starrocks_admit_test

**Comment by LiShuMing** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Pull request merged**
