### PR TITLE
[BugFix] Fix delta lake use null value as partition key

### LINKED ISSUE #15539: [delta lake] query error:Invalid number format: null
### Steps to reproduce the behavior (Required)
1. hive
```
CREATE TABLE `sample_multi_partitions_s3` ( 
`id` BIGINT,  
`data` STRING,  
`ts` DATE, 
`year` int) 
USING delta PARTITIONED BY (ts,year,id);
insert into sample_multi_partitions_s3 values(1, '2012-01-01', '2012-01-01', '1000');
```
select * from sample_multi_partitions_s3
image

2. sr
```
CREATE EXTERNAL CATALOG "delta_catalog"  PROPERTIES ("type"="deltalake","hive.metastore.uris"="thrift://xxx.xx.xxx.xxx:xxxx");
use delta_catalog.delta_lake_db;
select * from sample_multi_partitions_s3
```

### Expected behavior (Required)
result as same as in hive query
### Real behavior (Required)
ERROR 1064 (HY000): Invalid number format: null
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
mysql> select current_version();
+----------------------------+
| current_version()          |
+----------------------------+
| BRANCH-2.5-RELEASE ed963f8 |
+----------------------------+
1 row in set (0.52 sec)

### PR DESCRIPTION
**Pull request by Youngwb**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #15539 

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Review by stephen-shelby — DISMISSED** [review]

**Comment by Youngwb** [comment]
run starrocks_fe_unittest

**Review by gengjun-git — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by Youngwb** [comment]
run starrocks_fe_unittest

**Comment by Youngwb** [comment]
run starrocks_admit_test

**Review by stephen-shelby — APPROVED** [review]

**Comment by Youngwb** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 1 / 9 (11.11%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/DeltaLakePartitionKey.java|0|3|00.00%|[19, 20, 24]|
|:large_blue_circle:|com/starrocks/planner/DeltaLakeScanNode.java|0|2|00.00%|[136, 137]|
|:large_blue_circle:|com/starrocks/connector/PartitionUtil.java|1|4|25.00%|[79, 80, 93]|

**Review by gengjun-git — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
