### PR TITLE
[Bugfix] fix #6179: check resource group property supported

### LINKED ISSUE #6179: Illegal parameters are not reported error when creating a resource_group
### Steps to reproduce the behavior (Required)
```
create resource group rg3
to
    (user='root')
with (
    'cpu_core_limit' = '4',
    'mem_limit' = '10%',
    'concurrency_limit' = '5',
    'type' = 'normal',
    'abcasgsadg' = '100'
);
```

### Expected behavior (Required)
`error reported`
### Real behavior (Required)
`query ok`
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
mysql> select current_version();
+----------------------+
| current_version()    |
+----------------------+
| MAIN-RELEASE 1039f18 |
+----------------------+
```

### PR DESCRIPTION
**Pull request by murphyatwork**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #6179

## Problem Summary(Required) ：

Throw exception when create resource with unknown property.

### CODE REVIEW

**Comment by mofeiatwork** [comment]
run starrocks_fe_unittest

**Comment by mofeiatwork** [comment]
@Mergifyio backport branch-2.2

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/WorkGroupAnalyzer.java|1|1|100.00%|

**Review by Seaven — APPROVED** [review]

**Review by kangkaisen — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/WorkGroupAnalyzer.java|1|1|100.00%|

**Pull request merged**
