### PR TITLE
[BugFix] Column mapping may not take effect in Spark load

### PR DESCRIPTION
**Pull request by wangshisan**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes(https://github.com/StarRocks/starrocks/issues/12642)

## Problem Summary(Required) ：

If column mapping is specified, we should add the column with the mapping function to the dataframe otherwise add the column itself to the dataframe.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by wangshisan** [comment]
@wyb Please help to take a look.

**Review by wyb — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by xiaoyong-z** [comment]
Better to add a unit test

**Comment by wanpengfei-git** [comment]
starrocks_be_unittest succeeded.

**Comment by wangshisan** [comment]
> Better to add a unit test

We need to initialize a SparkContext to add a unit test, which may need a complete Spark environment, do you have any idea on this?

**Comment by chaoyli** [comment]
@wangshisan Thanks for you contributions. And you can sign the CLA

**Comment by xiaoyong-z** [comment]
> > Better to add a unit test
> 
> We need to initialize a SparkContext to add a unit test, which may need a complete Spark environment, do you have any idea on this?

It is true that the current testing framework is not quite able to support this one

**Review by xiaoyong-z — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wangshisan** [comment]
> @wangshisan Thanks for you contributions. And you can sign the CLA

image
Looks I have signed CLA, why the status is still pending to be signed?

**Comment by wangshisan** [comment]
> 

Done, it's due to the email address used to submit this commit was not bound to my github account.

**Comment by wangshisan** [comment]
> > @wangshisan Thanks for you contributions. And you can sign the CLA
> 
> image
> 
> Looks I have signed CLA, why the status is still pending to be signed?


Done, it's due to the email address used to submit this commit was not bound to my github account.

**Review by xiaoyong-z — APPROVED** [review]

**Review by meegoo — APPROVED** [review]

**Comment by kateshaowanjou** [comment]
@wangshisan Congrats on your first PR! 🎉

**Pull request merged**
