### PR TITLE
[Feature] Support url_extract_host Function(#31969)

### LINKED ISSUE #31969: Need support url_extract_host function in builtfunction
## Feature request

**Is your feature request related to a problem? Please describe.**
starrrocks need url_extract_host function in built function 

**Describe the solution you'd like**
pr as https://github.com/StarRocks/starrocks/pull/31968

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by superdiaodiao**
Fixes #31969

## What type of PR is this:

- [ ] BugFix
- [x] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [x] This pr needs user documentation (for new or modified features or behaviors)
  - [x] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [ ] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Review by imay — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 0 / 4 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/exprs/string_functions.cpp|0|4|00.00%|[3966, 3967, 3968, 3969]|

**Comment by xuzifu666** [comment]
@superdiaodiao had done in https://github.com/StarRocks/starrocks/pull/31968 before the pr，and testcase simple as same with it

**Comment by superdiaodiao** [comment]
> @superdiaodiao had done in https://github.com/StarRocks/starrocks/pull/31968 before the pr，and testcase simple as same with it

So, did you copy my code into your pr without my permission?

**Review by kangkaisen — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Pull request merged**
