### PR TITLE
[BugFix] Broker load parser bug

### LINKED ISSUE #10385: Broker load without broker parser bug
### Steps to reproduce the behavior (Required)
1. CREATE TABLE `table_10380` ( `a` bigint(20) NULL, `b` varchar(6) NULL, `c` varchar(5) NULL ) ENGINE=OLAP DUPLICATE KEY(`a`) COMMENT "OLAP" DISTRIBUTED BY HASH(`a`) BUCKETS 1 PROPERTIES ( "replication_num" = "1", "in_memory" = "false", "storage_format" = "DEFAULT" );
2. LOAD LABEL test.table_103811 (DATA INFILE( "xxxa/10380.orc") INTO TABLE `table_10380` FORMAT AS "orc" )  WITH BROKER hdfs_broker PROPERTIES("timeout"="300");

### Expected behavior (Required)
Load success

### Real behavior (Required)
Load fail: Unknown broker name(PROPERTIES)

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
9cfeee922f1bb73c6777857a85bf4836827d7d3b

### Other case
we need to add ("username"="sr","password"="sr@test")  after broker, it can load successfully
```
LOAD LABEL ab_10381 (DATA INFILE("hdfs://172.26.194.238:9000/user/xyz/a.orc") INTO TABLE `agreementmgmt__ecoupon_item_detail`) 
WITH broker ("username"="sr","password"="sr@test") PROPERTIES("timeout"="300","max_filter_ratio"="0.0");
```

### PR DESCRIPTION
**Pull request by xiaoyong-z**
Signed-off-by: xyz <a997647204@gmail.com>

## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #10385

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

Broker load without a broker will recognize PROPERTIES as identifierOrString if it doesn't have propertyList after it.
Misidentified cases: Load xxx WITH BROKER hdfs_broker PROPERTIES("timeout"="300");
Correctly identified case:  LOad xxx WITH BROKER hdfs_broker ("user_name"="xx") PROPERTIES("timeout"="300");

### CODE REVIEW

**Review by chaoyli — DISMISSED** [review]

**Comment by xiaoyong-z** [comment]
@mergify rebase

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by HangyuanLiu — COMMENTED** [review]
please cover case with unit test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by chaoyli — APPROVED** [review]

**Review by meegoo — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by xiaoyong-z** [comment]
run starrocks_admit_test

**Comment by xiaoyong-z** [comment]
run starrocks_admit_test

**Review by HangyuanLiu — APPROVED** [review]

**Comment by xiaoyong-z** [comment]
run starrocks_admit_test

**Comment by xiaoyong-z** [comment]
run starrocks_admit_test

**Comment by xiaoyong-z** [comment]
run starrocks_admit_test

**Pull request merged**
