### PR TITLE
[BugFix] Forbid the usage of user-defined op column name __op

### LINKED ISSUE #33269: Load JSON to table with column named with `__op` leads BE crash
### Steps to reproduce the behavior (Required)
1. create table
```
create table tbl_simple (key1 string, __op boolean) distributed by hash(key1) properties("replication_num"="1");
```
3. load data
```
curl --location-trusted -u root:  'http://127.0.0.1:18040/api/db0/tbl_simple/_stream_load' \-X PUT \-H 'format: json' -d '{"key1":"123"}'
```

### Expected behavior (Required)
Load is successful.

### Real behavior (Required)
Be crashes.
```
     @          0x22f6559  std::__throw_bad_variant_access()
    @          0x22f6576  std::__throw_bad_variant_access()
    @          0x2862633  starrocks::BinaryColumnBase<>::append_datum()
    @          0x2ae097f  starrocks::JsonReader::_construct_row_without_jsonpath()
    @          0x2ae7655  starrocks::JsonReader::_read_rows<>()
    @          0x2ae13c1  starrocks::JsonReader::read_chunk()
    @          0x2ae173a  starrocks::JsonScanner::get_next()
    @          0x5298941  starrocks::connector::FileDataSource::get_next()
    @          0x2be235a  starrocks::ConnectorScanNode::_scanner_thread()
    @          0x4a5a120  starrocks::PriorityThreadPool::work_thread()
    @          0x5ff2cc7  thread_proxy
    @     0x7f07f2018ea5  start_thread
    @     0x7f07f1633b0d  __clone
    @              (nil)  (unknown)
```

### StarRocks version (Required)
3.1.3,.3.0.5,2.5.13

### PR DESCRIPTION
**Pull request by rickif**
Fixes https://github.com/StarRocks/starrocks/issues/33269
This PR forbids to name column as `__op`. An error ` Getting analyzing error. Detail message: [__op] is a prohibited system reserved name, if you are sure you want to use it. Please reset FE configuration prohibit_op_column_name.
` would be returned if a column name `__op` is used..
 To keep the compatibility, a FE config `prohibit_op_column_name` is added.
```
MySQL [db0]>  create table tbl_op1 (key1 string not null, __op boolean) primary key(key1)  distributed by hash(key1) properties("replication_num"="1");
ERROR 1064 (HY000): Getting analyzing error. Detail message: [__op] is a prohibited system reserved name, if you are sure you want to use it. Please reset FE configuration prohibit_op_column_name.
```
```
MySQL [db0]> alter table tbl_op rename column  __op2 to __op;
ERROR 1064 (HY000): Getting analyzing error. Detail message: [__op] is a prohibited system reserved name, if you are sure you want to use it. Please reset FE configuration prohibit_op_column_name.

```

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [x] Yes, this PR will result in a change in behavior.
- [ ] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [x] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [x] This pr needs user documentation (for new or modified features or behaviors)
- [x] I have added documentation for my new feature or new function
https://github.com/StarRocks/starrocks/pull/35304

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.2
  - [x] 3.1
  - [x] 3.0
  - [x] 2.5

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 3 / 3 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/analysis/KeysDesc.java|3|3|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by decster — DISMISSED** [review]

**Comment by rickif** [comment]
@mergifyio rebase

**Comment by rickif** [comment]
@mergifyio rebase

**Comment by rickif** [comment]
@mergifyio rebase

**Comment by rickif** [comment]
@mergifyio rebase

**Comment by rickif** [comment]
@mergifyio rebase

**Review by trueeyu — DISMISSED** [review]

**Comment by rickif** [comment]
@mergifyio rebase

**Review by decster — APPROVED** [review]

**Review by trueeyu — APPROVED** [review]

**Review by liuyehcf — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.2

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
