### PR TITLE
[Enhancement] Fix incomplete prune partition when mv with union-all

### LINKED ISSUE #20719: incomplete prune partition when mv with union-all
## Enhancement
```
create a mv with union-all
create materialized view test.union_all_mv 
partition by dt 
distributed by hash(k2) buckets 10
refresh manual
as
select dt,
    -1 as k2
from tbl5
where k2 is null
union all
select dt,
    k2
from tbl5;
```
the partition prune just work in one subquery
```
PLAN FRAGMENT 0
 OUTPUT EXPRS:11: dt | 13: k2
  PARTITION: RANDOM

  OLAP TABLE SINK
    TABLE: union_all_mv
    TUPLE ID: 5
    RANDOM

  6:Project
  |  <slot 11> : 11: dt
  |  <slot 13> : CAST(12: cast AS TINYINT)
  |  
  0:UNION
  |  
  |----5:EXCHANGE
  |    
  3:EXCHANGE

PLAN FRAGMENT 1
 OUTPUT EXPRS:
  PARTITION: RANDOM

  STREAM DATA SINK
    EXCHANGE ID: 05
    RANDOM

  4:OlapScanNode
     TABLE: tbl5
     PREAGGREGATION: ON
     partitions=1/5
     rollup: tbl5
     tabletRatio=3/3
     tabletList=10134,10136,10138
     cardinality=1
     avgRowSize=2.0
     numNodes=0

PLAN FRAGMENT 2
 OUTPUT EXPRS:
  PARTITION: RANDOM

  STREAM DATA SINK
    EXCHANGE ID: 03
    RANDOM

  2:Project
  |  <slot 1> : 1: dt
  |  <slot 6> : CAST(-1 AS INT)
  |  
  1:OlapScanNode
     TABLE: tbl5
     PREAGGREGATION: ON
     PREDICATES: 3: k2 IS NULL
     partitions=5/5
     rollup: tbl5
     tabletRatio=5/15
     tabletList=10112,10118,10124,10130,10136
     cardinality=1
     avgRowSize=3.0
     numNodes=0

```

### PR DESCRIPTION
**Pull request by mchades**
## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #20719 

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 3.0
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Review by murphyatwork — APPROVED** [review]

**Comment by ABingHuang** [comment]
add a problem related issue to describe the problem.

**Comment by mchades** [comment]
> add a problem related issue to describe the problem.

@ABingHuang done

**Review by ABingHuang — APPROVED** [review]
LGTM

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Pull request merged**
