### PR TITLE
[Refactor][Minor] Reduce level of nesting

### PR DESCRIPTION
**Pull request by sduzh**
## What type of PR is this：
- [ ] bugfix
- [ ] feature
- [ ] enhancement
- [x] refactor
- [ ] others

### CODE REVIEW

**Comment by sduzh** [comment]
run starrocks_fe_unittest

**Review by wyb — DISMISSED** [review]

**Review by imay — DISMISSED** [review]

**Comment by sduzh** [comment]
@mergify rebase

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 20 / 25 (80.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|20|25|80.00%|[1928, 1929, 1932, 1935, 1938]|

**Pull request merged**
