### PR TITLE
[BugFix] Forgot to run drop table task

### PR DESCRIPTION
**Pull request by sduzh**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 3 / 22 (13.64%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/lake/LakeTable.java|0|1|00.00%|[134]|
|:large_blue_circle:|com/starrocks/lake/DeleteTableTask.java|0|14|00.00%|[17, 18, 19, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33]|
|:large_blue_circle:|com/starrocks/catalog/CatalogRecycleBin.java|3|7|42.86%|[380, 746, 747, 748]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 3 / 22 (13.64%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/lake/LakeTable.java|0|1|00.00%|[134]|
|:large_blue_circle:|com/starrocks/lake/DeleteTableTask.java|0|14|00.00%|[17, 18, 19, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33]|
|:large_blue_circle:|com/starrocks/catalog/CatalogRecycleBin.java|3|7|42.86%|[380, 746, 747, 748]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 3 / 23 (13.04%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/lake/LakeTable.java|0|1|00.00%|[134]|
|:large_blue_circle:|com/starrocks/lake/DeleteTableTask.java|0|15|00.00%|[17, 18, 19, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34]|
|:large_blue_circle:|com/starrocks/catalog/CatalogRecycleBin.java|3|7|42.86%|[380, 746, 747, 748]|

**Review by imay — APPROVED** [review]

**Comment by sduzh** [comment]
run starrocks_admit_test

**Pull request merged**
