### PR TITLE
[Enhancement] Support compact thrift protocol

### PR DESCRIPTION
**Pull request by Seaven**
Fixes #issue

* support thrift serialized protocol, for a complex sql, fragment plan size:

| binary(default) | compact | json |
| ---- | ---- | ---- |
| 901347 bytes | 336452 bytes | 2171040 bytes |

and support `thrift_plan_protocol` in session variables  to control it

* remove unused thrift parameters: `signature` and `useVectorized`

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 0 / 3 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/service/internal_service.cpp|0|3|00.00%|[305, 398, 404]|

**Review by kangkaisen — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 0 / 3 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/service/internal_service.cpp|0|3|00.00%|[305, 398, 399]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 16 / 20 (80.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/rpc/AttachmentRequest.java|3|7|42.86%|[39, 41, 52, 54]|
|:large_blue_circle:|com/starrocks/qe/SessionVariable.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/qe/scheduler/dag/FragmentInstanceExecState.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/rpc/PExecPlanFragmentRequest.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/qe/scheduler/dag/JobSpec.java|5|5|100.00%|[]|
|:large_blue_circle:|com/starrocks/rpc/BackendServiceClient.java|2|2|100.00%|[]|

**Review by stdpain — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 18 / 20 (90.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/rpc/AttachmentRequest.java|5|7|71.43%|[39, 41]|
|:large_blue_circle:|com/starrocks/qe/SessionVariable.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/qe/scheduler/dag/FragmentInstanceExecState.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/rpc/PExecPlanFragmentRequest.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/qe/scheduler/dag/JobSpec.java|5|5|100.00%|[]|
|:large_blue_circle:|com/starrocks/rpc/BackendServiceClient.java|2|2|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 0 / 9 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/util/thrift_util.h|0|6|00.00%|[172, 173, 174, 175, 176, 178]|
|:large_blue_circle:|src/service/internal_service.cpp|0|3|00.00%|[305, 398, 405]|

**Pull request merged**
