### PR TITLE
[BugFix] Fix alter job failed if leader transferred when doing pending job

### LINKED ISSUE #11260: [BUG] Alter job failed if leader transferred when doing pending job
### Steps to reproduce the behavior (Required)
1. create an olap table
2. execute an alter column command on that table.
3. restart fe leader node immediately after alter command returns success.

### Expected behavior (Required)
alter job should success.

### Real behavior (Required)
alter job failed with error:
```
failed to do alter task. status=Internal error: failed to find new tablet base_tablet_id=254047, base_schema_hash=256312001, new_tablet_id=257048, new_schema_hash=415238138
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by gengjun-git**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #11260

## Problem Summary(Required) ：

The job state should be set to PENDING when replay pending state job. As RollupJob did.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Review by chaoyli — APPROVED** [review]

**Review by sevev — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by gengjun-git** [comment]
run starrocks_fe_unittest

**Comment by gengjun-git** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 0 / 1 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/alter/SchemaChangeJobV2.java|0|1|00.00%|[809]|

**Review by Astralidea — APPROVED** [review]

**Comment by gengjun-git** [comment]
@mergify backport branch-2.2 branch-2.3 branch-2.4

**Pull request merged**
