### PR TITLE
[Enhancement] Add location message for show create external table

### LINKED ISSUE #7286: Support `show create table` of external catalog
## Feature request

**Is your feature request related to a problem? Please describe.**

https://github.com/StarRocks/starrocks/issues/7268

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by leoyy0316**
## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes https://github.com/StarRocks/starrocks/issues/7286

## Problem Summary(Required) ：

Add location message for show create external table
| test_iceberg | CREATE TABLE ice_catalog01.test.test_iceberg (
`name` VARCHAR(65533),
`id` BIGINT
)
LOCATION 'hdfs://hadoop/test/hive/warehouse/test.db/test_iceberg'
## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 3 / 5 (60.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/Table.java|0|1|00.00%|[254]|
|:large_blue_circle:|com/starrocks/catalog/IcebergTable.java|0|1|00.00%|[176]|
|:large_blue_circle:|com/starrocks/qe/ShowExecutor.java|3|3|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 5 / 11 (45.45%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/Table.java|0|1|00.00%|[220]|
|:large_blue_circle:|com/starrocks/catalog/IcebergTable.java|0|1|00.00%|[176]|
|:large_blue_circle:|com/starrocks/qe/ShowExecutor.java|5|9|55.56%|[732, 733, 734, 735]|

**Review by stephen-shelby — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 7 / 13 (53.85%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/Table.java|0|1|00.00%|[220]|
|:large_blue_circle:|com/starrocks/catalog/IcebergTable.java|0|1|00.00%|[176]|
|:large_blue_circle:|com/starrocks/qe/ShowExecutor.java|7|11|63.64%|[732, 733, 734, 735]|

**Review by Youngwb — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by leoyy0316** [comment]
run starrocks_admit_test

**Comment by leoyy0316** [comment]
run starrocks_admit_test

**Comment by wangyouzhuo** [comment]
LGTM

**Comment by stephen-shelby** [comment]
@Mergifyio backport branch-2.5

**Comment by leoyy0316** [comment]
@Mergifyio backport branch-2.5

**Comment by leoyy0316** [comment]
@Mergifyio pls create new backport, because 15192 has conflicts, when 15193 merged, new backport will not hava confilcts

**Pull request merged**
