### PR TITLE
[BugFix] Fix partial partition query rewrite for external table

### LINKED ISSUE #19011: Partial partition query rewrite for external table error
### Steps to reproduce the behavior (Required)
1. 
```
create materialized view hive_union_mv_1 distributed by hash(s_suppkey) 
PROPERTIES (
"force_external_table_query_rewrite" = "true"
)  
as select s_suppkey, s_name, s_address, s_acctbal from hive0.tpch.supplier where s_suppkey < 5
```

```
create materialized view hive_join_mv_1
distributed by hash(s_suppkey)
PROPERTIES ( 
"force_external_table_query_rewrite" = "true"
)
as 
SELECT s_suppkey , s_name, n_name
from hive0.tpch.supplier join hive0.tpch.nation
on s_nationkey = n_nationkey
where s_suppkey < 100
```

2. 
```
select s_suppkey, s_name, s_address, s_acctbal from hive0.tpch.supplier where s_suppkey < 10
```

### Expected behavior (Required)
query correct

### Real behavior (Required)
image

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by Youngwb**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #19011 

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 3.0
  - [x] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Comment by Youngwb** [comment]
run starrocks_fe_unittest

**Comment by Youngwb** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 10 / 14 (71.43%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/logical/LogicalHudiScanOperator.java|0|1|00.00%|[103]|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/logical/LogicalIcebergScanOperator.java|0|1|00.00%|[88]|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/logical/LogicalFileScanOperator.java|0|1|00.00%|[97]|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/logical/LogicalDeltaLakeScanOperator.java|0|1|00.00%|[82]|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/ScanOperatorPredicates.java|9|9|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/logical/LogicalHiveScanOperator.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 10 / 14 (71.43%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/logical/LogicalHudiScanOperator.java|0|1|00.00%|[103]|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/logical/LogicalIcebergScanOperator.java|0|1|00.00%|[88]|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/logical/LogicalFileScanOperator.java|0|1|00.00%|[97]|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/logical/LogicalDeltaLakeScanOperator.java|0|1|00.00%|[82]|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/ScanOperatorPredicates.java|9|9|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/logical/LogicalHiveScanOperator.java|1|1|100.00%|[]|

**Review by ABingHuang — APPROVED** [review]
LGTM

**Review by gengjun-git — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
