### PR TITLE
[Enhancement] Add config refresh daemon

### PR DESCRIPTION
**Pull request by gengjun-git**
## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

Even though our config param can be updated using command, but it may not take effect because the value has been taken to local variable. Add a config refresh daemon, and we can use it to refresh the Config param to those local variables.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Review by Astralidea — APPROVED** [review]

**Comment by gengjun-git** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 15 / 22 (68.18%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/common/ThriftServer.java|1|5|20.00%|[128, 129, 130, 132]|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|2|3|66.67%|[531]|
|:large_blue_circle:|com/starrocks/common/ConfigRefreshDaemon.java|12|14|85.71%|[39, 40]|

**Comment by gengjun-git** [comment]
run starrocks_admit_test

**Review by meegoo — APPROVED** [review]

**Comment by gengjun-git** [comment]
@mergify backport branch-2.5

**Pull request merged**
