### PR TITLE
[BugFix] fix aggregate on single table query rewrite bug

### LINKED ISSUE #13819: aggregate query rewrite for single table failed when there are two more results
### Steps to reproduce the behavior (Required)
1. create table 
create table emps (
 empid int not null,
 deptno int not null,
  name varchar(25) not null,
  salary double)
 distributed by hash(`empid`) buckets 10
 properties ("replication_num\" = "1");

2. create mv
create materialized view agg_mv_1 distributed by hash(empid)
as select empid, deptno, sum(salary) as total_salary from emps
 where empid < 5 group by empid, deptno;

create materialized view agg_mv_2 distributed by hash(empid)
as select empid, deptno, sum(salary) as total_salary from emps
 where empid < 10 group by empid, deptno;

3. query
explain select empid, sum(salary) from emps where empid < 5 group by empid

### Expected behavior (Required)
plan contain agg_mv_
### Real behavior (Required)
plan failed
java.lang.IllegalStateException: Rewrite rule should provide at most 1 expression

	at com.google.common.base.Preconditions.checkState(Preconditions.java:510)
	at com.starrocks.sql.optimizer.task.RewriteTreeTask.rewrite(RewriteTreeTask.java:62)
	at com.starrocks.sql.optimizer.task.RewriteTreeTask.execute(RewriteTreeTask.java:46)
	at com.starrocks.sql.optimizer.task.SeriallyTaskScheduler.executeTasks(SeriallyTaskScheduler.java:49)
	at com.starrocks.sql.optimizer.Optimizer.ruleRewriteIterative(Optimizer.java:510)
	at com.starrocks.sql.optimizer.Optimizer.logicalRuleRewrite(Optimizer.java:365)
	at com.starrocks.sql.optimizer.Optimizer.optimizeByCost(Optimizer.java:140)
	at com.starrocks.sql.optimizer.Optimizer.optimize(Optimizer.java:101)
	at com.starrocks.sql.StatementPlanner.createQueryPlan(StatementPlanner.java:104)
	at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:65)
	at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:37)
	at com.starrocks.utframe.UtFrameUtils.getPlanAndFragment(UtFrameUtils.java:319)

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by ABingHuang**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #13819 

## Problem Summary(Required) ：

fix aggregate on single table with two or more candidate mvs rewrite bug by selecting the best one result for rewrite.
## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

- [ ] I have checked the version labels which the pr will be auto backported to target branch

### CODE REVIEW

**Review by Seaven — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 7 / 8 (87.50%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/rule/AggregateScanRule.java|3|4|75.00%|[35]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/rule/AggregateJoinRule.java|4|4|100.00%|[]|

**Comment by ABingHuang** [comment]
run starrocks_admit_test

**Review by kangkaisen — APPROVED** [review]

**Comment by ABingHuang** [comment]
run starrocks_fe_unittest

**Review by Youngwb — APPROVED** [review]

**Comment by ABingHuang** [comment]
run starrocks_fe_unittest

**Comment by ABingHuang** [comment]
run starrocks_admit_test

**Comment by ABingHuang** [comment]
run starrocks_fe_unittest

**Comment by ABingHuang** [comment]
run starrocks_admit_test

**Comment by ABingHuang** [comment]
run starrocks_admit_test

**Comment by ABingHuang** [comment]
run starrocks_admit_test

**Comment by ABingHuang** [comment]
run starrocks_clang-tidy

**Comment by ABingHuang** [comment]
run starrocks_clang-tidy

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.4

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.3

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.2

**Comment by dulong41** [comment]
@Mergifyio backport branch-2.2

**Pull request merged**
