### PR TITLE
[BugFix] Use repeated_ancestor_def_level in parquet writer

### PR DESCRIPTION
**Pull request by letian-jiang**
This PR introduces `repeated_ancestor_def_level` to determine whether an undefined value has a slot in the leaf column. More specifically,
- `def_level < repeated_ancestor_def_level` means undefined and not having a slot
- `repeated_ancestor_def_level <= def_level < max_def_level` means undefined and having a slot
- `def_level = max_def_level` means defined and (surely) having a slot

Previously, we rely on `def_level = max_def_level` to determine both, but unfortunately, this is wrong. A simple case would be a null struct, whose def_level is zero but also have slots in child columns.

Example:
```
mysql> create table ice_struct1(a int,b struct<col_int int, col_string string, col_date date>);
Query OK, 0 rows affected (0.43 sec)

mysql> insert into ice_struct1 values(1,row(0,'ABC',null)),(2,null),(3,row(null,null,'2003-09-13'));
Query OK, 3 rows affected (0.33 sec)
{'label':'FAKE_ICEBERG_SINK_LABEL', 'status':'VISIBLE', 'txnId':'-1'}

mysql> select * from ice_struct1 order by 1;
+------+----------------------------------------------------+
| a    | b                                                  |
+------+----------------------------------------------------+
|    1 | {"col_int":0,"col_string":"ABC","col_date":null}   |
|    2 | NULL                                               |
|    3 | {"col_int":null,"col_string":null,"col_date":null} |
+------+----------------------------------------------------+
3 rows in set (0.04 sec)
```

Fixed with this PR:
image

More complex test cases are tested as well.

## What type of PR is this:
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by Smith-Cruise — APPROVED** [review]
Better add ut about LevelBuilder

**Review by stephen-shelby — APPROVED** [review]

**Review by zombee0 — APPROVED** [review]

**Review by dirtysalt — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Pull request merged**
