### PR TITLE
[BugFix] Fix bug grant system objectType object NPE

### LINKED ISSUE #18632: [access control] grant priv to user with grant option，then grant to other user:Unknown error
### Steps to reproduce the behavior (Required)
1. conn1
```
create user user_01 identified by '123456';
create user user_02 identified by '123456';
GRANT CREATE_RESOURCE_GROUP, CREATE_RESOURCE, CREATE_EXTERNAL_CATALOG, REPOSITORY, BLACKLIST, FILE, CREATE_GLOBAL_FUNCTION, OPERATE ON SYSTEM TO USER user_01 WITH GRANT OPTION;
```
2. conn2
mysql -hxxx.xx.xx.xxx -P9232 -uuser_01 -p123456
```
GRANT CREATE_RESOURCE_GROUP, CREATE_RESOURCE, CREATE_EXTERNAL_CATALOG, REPOSITORY, BLACKLIST, FILE, CREATE_GLOBAL_FUNCTION, OPERATE ON SYSTEM TO USER user_02 WITH GRANT OPTION;
```

### Expected behavior (Required)
grant success
### Real behavior (Required)
Unknown error
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
mysql> select current_version();
+------------------------+
| current_version()      |
+------------------------+
| 3.0.0-20230227 705d390 |
+------------------------+
1 row in set (0.00 sec)

### PR DESCRIPTION
**Pull request by HangyuanLiu**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #18632 #18714

## Problem Summary(Required) ：

The location of the error is in PrivilegeCollection#allowGrant, because there is no special case where the object list is NULL
## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
run starrocks_fe_unittest

**Comment by HangyuanLiu** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 12 / 13 (92.31%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/ast/SetDefaultRoleStmt.java|0|1|00.00%|[59]|
|:large_blue_circle:|com/starrocks/sql/ast/BaseGrantRevokePrivilegeStmt.java|9|9|100.00%|[]|
|:large_blue_circle:|com/starrocks/privilege/PrivilegeManager.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/PrivilegeStmtAnalyzerV2.java|1|1|100.00%|[]|

**Review by gengjun-git — APPROVED** [review]

**Review by Astralidea — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by nshangyiming — APPROVED** [review]

**Comment by HangyuanLiu** [comment]
@Mergifyio backport branch-3.0

**Pull request merged**
