### PR TITLE
[Feature]iceberg support v2 position-deletes part 1

### PR DESCRIPTION
**Pull request by cbcbq**
## What type of PR is this：
- [ ] BugFix
- [x] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 0 / 8 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/planner/IcebergScanNode.java|0|8|00.00%|[180, 181, 182, 183, 184, 185, 187, 188]|

**Review by caneGuy — DISMISSED** [review]

**Review by DorianZheng — DISMISSED** [review]
LGTM

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by dirtysalt — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
starrocks_be_unittest succeeded.

**Comment by cbcbq** [comment]
run starrocks_fe_unittest

**Comment by cbcbq** [comment]
run starrocks_fe_unittest

**Comment by cbcbq** [comment]
run starrocks_fe_unittest

**Comment by cbcbq** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 0 / 8 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/planner/IcebergScanNode.java|0|8|00.00%|[180, 181, 182, 183, 184, 185, 187, 188]|

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by caneGuy — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
starrocks_be_unittest succeeded.

**Comment by cbcbq** [comment]
run starrocks_admit_test

**Review by DorianZheng — DISMISSED** [review]

**Comment by cbcbq** [comment]
run starrocks_admit_test

**Review by dirtysalt — DISMISSED** [review]

**Comment by caneGuy** [comment]
run starrocks_admit_test

**Comment by caneGuy** [comment]
run starrocks_admit_test

**Comment by cbcbq** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 8 / 8 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/planner/IcebergScanNode.java|8|8|100.00%|[]|

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 8 / 8 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/planner/IcebergScanNode.java|8|8|100.00%|[]|

**Comment by wanpengfei-git** [comment]
starrocks_be_unittest succeeded.

**Review by caneGuy — APPROVED** [review]

**Review by Youngwb — APPROVED** [review]

**Pull request merged**
