### PR TITLE
[BugFix] Log statement cannot be serialized

### LINKED ISSUE #14572: [materialized view]NPE when create mv
### Steps to reproduce the behavior (Required)
```
CREATE TABLE `duplicate_table_with_null_partition` (
                    `k1` date,
                    `k2` datetime,
                    `k3` char(20),
                    `k4` varchar(20),
                    `k5` boolean,
                    `k6` tinyint,
                    `k7` smallint,
                    `k8` int,
                    `k9` bigint,
                    `k10` largeint,
                    `k11` float,
                    `k12` double,
                    `k13` decimal(27,9),
                    `k14` array<int>,
                    `k15` json
                    ) ENGINE=OLAP
                    DUPLICATE KEY(`k1`, `k2`, `k3`, `k4`, `k5`)
                    COMMENT "OLAP"
                    PARTITION BY RANGE(`k1`)
                    (
                    PARTITION `p202006` VALUES LESS THAN ("2020-07-01"),
                    PARTITION `p202007` VALUES LESS THAN ("2020-08-01"),
                    PARTITION `p202008` VALUES LESS THAN ("2020-09-01")
                    )
                    DISTRIBUTED BY HASH(`k1`, `k2`, `k3`, `k4`, `k5`) BUCKETS 3
                    PROPERTIES (
                    "replication_num" = "3",
                    "storage_format" = "v2"
                    );
INSERT INTO duplicate_table_with_null_partition VALUES
                ("2020-06-23","2020-06-23 00:00:00","beijing","haidian",-1,-128,-32768,-2147483648,-9223372036854775808,-18446744073709551616,-3.1,-3.14,-3.141,[1,1,1],parse_json('{"a": 1, "b": true}')),
                ("2020-07-23","2020-07-23 00:00:00","shanghai","pudong",0,0,0,0,0,0,-3.1,-3.14,-3.141,[2,2,2],parse_json('{"a": 1, "b": true}')),
                ("2020-07-23","2020-07-24 00:00:00","shanghai1","pudong1",1,1,1,1,1,1,-3.2,-3.44,-3.441,[3,3,3],parse_json('{"a": 1, "b": true}')),
                ("2020-08-23","2020-08-23 00:00:00","xian","zhonglou",1,127,32767,2147483647,9223372036854775807,18446744073709551615,-3.1,-3.14,-3.141,[3,3,3],parse_json('{"a": 1, "b": true}')),
                (NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
CREATE MATERIALIZED VIEW mv1 PARTITION BY k1 DISTRIBUTED BY HASH(k1) BUCKETS 10
REFRESH ASYNC AS SELECT k1, k2, k3, k4, k5, k6, k7, k8, k9, k10, k11, k12, k13, k14, k15 FROM duplicate_table_with_null_partition;

CREATE MATERIALIZED VIEW mv2 PARTITION BY k1 DISTRIBUTED BY HASH(k1) BUCKETS 10
REFRESH ASYNC AS SELECT k1, count(k2) as count_datetime, min(k3) as min_char, max(k4) as max_varchar,
                         sum(k5) as sum_boolean, avg(k6) as avg_tinyint FROM mv1 group by k1;

CREATE MATERIALIZED VIEW mv3 DISTRIBUTED BY HASH(k1)
REFRESH ASYNC AS SELECT k1, count_datetime as k2, min_char as k3, max_varchar as k4,
                         sum_boolean as k5, avg_tinyint as k6 FROM mv2;

CREATE MATERIALIZED VIEW mv3 DISTRIBUTED BY HASH(k1)
REFRESH ASYNC AS SELECT k1, count(k2) as count_datetime, min(k3) as min_char, max(k4) as max_varchar,
                         sum(k5) as sum_boolean, avg(k6) as avg_tinyint FROM mv3 group by k1;

```

### Expected behavior (Required)
`create ok`
### Real behavior (Required)
```
2022-12-05 09:44:33,390 WARN (starrocks-mysql-nio-pool-96|10423) [StmtExecutor.execute():516] execute Exception, sql CREATE MATERIALIZED VIEW mv3 DISTRIBUTED BY HASH(k1) REFRESH ASYNC AS SELECT k1, count(k2) as count_datetime, min(k3) as min_char, max(k4) as max_varchar,                          sum(k5) as sum_boolean, avg(k6) as avg_tinyint FROM mv3 group by k1
java.lang.NullPointerException: null
	at com.starrocks.qe.StmtExecutor.handleDdlStmt(StmtExecutor.java:1118) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:475) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:312) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:427) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:673) ~[starrocks-fe.jar:?]
	at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:55) ~[starrocks-fe.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_262]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_262]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]
```
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
+----------------------------+
| current_version()          |
+----------------------------+
| BRANCH-2.5-RELEASE 1d329ce |
+----------------------------+
```

### PR DESCRIPTION
**Pull request by rickif**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes https://github.com/StarRocks/starrocks/issues/14572

## Problem Summary(Required) ：

Not all statements implement the `AstVisitor<R, C>` interface, so the `AST2SQL.toString` may return null String.
The fixes the null check of `AST2SQL`.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
 - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Comment by rickif** [comment]
@mergifyio backport branch-2.5

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 1 / 2 (50.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/StmtExecutor.java|1|2|50.00%|[1119]|

**Review by meegoo — APPROVED** [review]

**Review by chaoyli — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
