### PR TITLE
[Refactor][meta-format-change] Change export job to json format

### PR DESCRIPTION
**Pull request by gengjun-git**
Fixes #issue

## What type of PR is this:
- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [x] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 2 / 52 (03.85%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/load/ExportMgr.java|0|21|00.00%|[366, 427, 428, 429, 430, 431, 432, 433, 434, 438, 440, 441, 442, 443, 445, 446, 447, 449, 452, 455, 456]|
|:large_blue_circle:|com/starrocks/journal/JournalEntity.java|0|6|00.00%|[359, 360, 361, 373, 374, 375]|
|:large_blue_circle:|com/starrocks/load/ExportJob.java|1|22|04.55%|[1021, 1022, 1023, 1024, 1025, 1027, 1028, 1030, 1094, 1108, 1109, 1110, 1123, 1131, 1132, 1133, 1134, 1138, 1139, 1140, 1142]|
|:large_blue_circle:|com/starrocks/persist/EditLog.java|1|3|33.33%|[1390, 1392]|

**Review by nshangyiming — DISMISSED** [review]

**Comment by nshangyiming** [comment]
code conflicts

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 36 / 53 (67.92%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|0|1|00.00%|[1428]|
|:large_blue_circle:|com/starrocks/journal/JournalEntity.java|0|6|00.00%|[359, 360, 361, 373, 374, 375]|
|:large_blue_circle:|com/starrocks/persist/EditLog.java|1|3|33.33%|[1390, 1392]|
|:large_blue_circle:|com/starrocks/load/ExportJob.java|17|22|77.27%|[1094, 1108, 1109, 1110, 1123]|
|:large_blue_circle:|com/starrocks/load/ExportMgr.java|18|21|85.71%|[366, 446, 447]|

**Review by HangyuanLiu — DISMISSED** [review]

**Review by HangyuanLiu — DISMISSED** [review]

**Review by nshangyiming — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 44 / 68 (64.71%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|0|1|00.00%|[1428]|
|:large_blue_circle:|com/starrocks/journal/JournalEntity.java|0|6|00.00%|[359, 360, 361, 373, 374, 375]|
|:large_blue_circle:|com/starrocks/persist/EditLog.java|1|3|33.33%|[1390, 1392]|
|:large_blue_circle:|com/starrocks/load/ExportJob.java|25|37|67.57%|[1094, 1108, 1123, 1155, 1157, 1165, 1169, 1170, 1173, 1177, 1178, 1189]|
|:large_blue_circle:|com/starrocks/load/ExportMgr.java|18|21|85.71%|[366, 446, 447]|

**Review by HangyuanLiu — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 44 / 68 (64.71%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|0|1|00.00%|[1428]|
|:large_blue_circle:|com/starrocks/journal/JournalEntity.java|0|6|00.00%|[359, 360, 361, 373, 374, 375]|
|:large_blue_circle:|com/starrocks/persist/EditLog.java|1|3|33.33%|[1392, 1394]|
|:large_blue_circle:|com/starrocks/load/ExportJob.java|25|37|67.57%|[1094, 1108, 1123, 1155, 1157, 1165, 1169, 1170, 1173, 1177, 1178, 1189]|
|:large_blue_circle:|com/starrocks/load/ExportMgr.java|18|21|85.71%|[366, 446, 447]|

**Comment by gengjun-git** [comment]
@mergifyio rebase

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 44 / 69 (63.77%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|0|1|00.00%|[1428]|
|:large_blue_circle:|com/starrocks/journal/JournalEntity.java|0|6|00.00%|[359, 360, 361, 373, 374, 375]|
|:large_blue_circle:|com/starrocks/persist/EditLog.java|1|3|33.33%|[1392, 1394]|
|:large_blue_circle:|com/starrocks/load/ExportJob.java|25|38|65.79%|[1095, 1109, 1124, 1156, 1158, 1166, 1170, 1171, 1174, 1178, 1179, 1190, 1195]|
|:large_blue_circle:|com/starrocks/load/ExportMgr.java|18|21|85.71%|[366, 446, 447]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 44 / 69 (63.77%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|0|1|00.00%|[1432]|
|:large_blue_circle:|com/starrocks/journal/JournalEntity.java|0|6|00.00%|[369, 370, 371, 383, 384, 385]|
|:large_blue_circle:|com/starrocks/persist/EditLog.java|1|3|33.33%|[1394, 1396]|
|:large_blue_circle:|com/starrocks/load/ExportJob.java|25|38|65.79%|[1095, 1109, 1124, 1156, 1158, 1166, 1170, 1171, 1174, 1178, 1179, 1190, 1195]|
|:large_blue_circle:|com/starrocks/load/ExportMgr.java|18|21|85.71%|[366, 446, 447]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 44 / 69 (63.77%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|0|1|00.00%|[1432]|
|:large_blue_circle:|com/starrocks/journal/JournalEntity.java|0|6|00.00%|[369, 370, 371, 383, 384, 385]|
|:large_blue_circle:|com/starrocks/persist/EditLog.java|1|3|33.33%|[1394, 1396]|
|:large_blue_circle:|com/starrocks/load/ExportJob.java|25|38|65.79%|[1095, 1109, 1124, 1156, 1158, 1166, 1170, 1171, 1174, 1178, 1179, 1190, 1195]|
|:large_blue_circle:|com/starrocks/load/ExportMgr.java|18|21|85.71%|[366, 446, 447]|

**Review by Astralidea — APPROVED** [review]

**Review by HangyuanLiu — APPROVED** [review]

**Pull request merged**
