### PR TITLE
[Feature] implement json_length function

### LINKED ISSUE #10550: JSON_LENGTH() function
## JSON_LENGTH() function

**Is your feature request related to a problem? Please describe.**
 sometimes I need to get the number of keys in a json object, or the number of objects in a json array.

**Describe the solution you'd like**
Implement JSON_LENGTH() function
https://database.guide/json_length-return-the-length-of-a-json-document-in-mysql/

**Describe alternatives you've considered**
I have used json_each lateral join to get the the count. But this makes the SQL query very complicated

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by murphyatwork**
## What type of PR is this：
- [ ] bugfix
- [x] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #10550

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by mofeiatwork** [comment]
@Mergifyio backport branch-2.4

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by mofeiatwork** [comment]
run starrocks_admit_test

**Review by ZiheLiu — APPROVED** [review]

**Review by kangkaisen — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by mofeiatwork** [comment]
run starrocks_admit_test

**Pull request merged**
