### PR TITLE
fix insert event npe

### PR DESCRIPTION
**Pull request by stephen-shelby**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] others

## Which issues of this PR fixes ：

Fixes #

### CODE REVIEW

**Review by gengjun-git — APPROVED** [review]

**Comment by stdpain** [comment]
more details ?

**Comment by gengjun-git** [comment]
run starrocks_fe_unittest

**Comment by gengjun-git** [comment]
run starrocks_fe_unittest

**Review by imay — APPROVED** [review]

**Comment by imay** [comment]
@stephen-shelby this should be merged in branch-main first

**Comment by stephen-shelby** [comment]
@Mergifyio backport main

**Pull request merged**
