### PR TITLE
[BugFix] Fix the missing encoding of password in create user statement bug

### LINKED ISSUE #17771: [access control] Create a user with auth_option, but fail to connect to the SR
### Steps to reproduce the behavior (Required)
1. CREATE USER
```
create user user_test2 IDENTIFIED WITH mysql_native_password BY '123456';

mysql -hxxx.xx.xx.xxx -P9232 -uuser_test2 -p123456
```

image

### Expected behavior (Required)
connect SR success
### Real behavior (Required)
[huoyue@starrocks-sandbox04 StarRocksTest]$ mysql -h172.26.92.200 -P9232 -uuser_test2 -p123456
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1064 (HY000): Access denied for user 'user_test2' (using password: YES)

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
mysql> select current_version();
+----------------------+
| current_version()    |
+----------------------+
| MAIN-RELEASE 2b32b43 |
+----------------------+
1 row in set (0.00 sec)

### PR DESCRIPTION
**Pull request by HangyuanLiu**
Signed-off-by: HangyuanLiu <460660596@qq.com>

## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #17771 #17765

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Review by Astralidea — DISMISSED** [review]

**Review by gengjun-git — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by HangyuanLiu** [comment]
run starrocks_fe_unittest

**Comment by HangyuanLiu** [comment]
run starrocks_fe_unittest

**Comment by HangyuanLiu** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 27 / 34 (79.41%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/AstToStringBuilder.java|0|3|00.00%|[155, 156, 157]|
|:large_blue_circle:|com/starrocks/sql/analyzer/PrivilegeStmtAnalyzer.java|5|9|55.56%|[288, 293, 294, 299]|
|:large_blue_circle:|com/starrocks/mysql/privilege/Auth.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/authentication/PlainPasswordAuthenticationProvider.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/PrivilegeStmtAnalyzerV2.java|6|6|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/BaseCreateAlterUserStmt.java|11|11|100.00%|[]|

**Review by gengjun-git — APPROVED** [review]

**Review by Astralidea — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by HangyuanLiu** [comment]
run starrocks_admit_test

**Pull request merged**
