### PR TITLE
[BugFix] fix sonar security issue

### PR DESCRIPTION
**Pull request by murphyatwork**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

Related security issues:
1. Using slow regular expressions is security-sensitive: javas5852, replace it with `google/re2j`
2. `Exception.printStackTrace`: replace it with a logger
3. InsecureRandom: replace it with `SecureRandom` for password scenario
4. Weak hash: don't fix

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Comment by mofeiatwork** [comment]
run starrocks_admit_test

**Comment by Seaven** [comment]
> SonarCloud Quality Gate failed.    [Quality Gate failed](https://sonarcloud.io/dashboard?id=StarRocks_starrocks&pullRequest=14250)
> 
> [Bug](https://sonarcloud.io/project/issues?id=StarRocks_starrocks&pullRequest=14250&resolved=false&types=BUG) [D](https://sonarcloud.io/project/issues?id=StarRocks_starrocks&pullRequest=14250&resolved=false&types=BUG) [1 Bug](https://sonarcloud.io/project/issues?id=StarRocks_starrocks&pullRequest=14250&resolved=false&types=BUG) [Vulnerability](https://sonarcloud.io/project/issues?id=StarRocks_starrocks&pullRequest=14250&resolved=false&types=VULNERABILITY) [A](https://sonarcloud.io/project/issues?id=StarRocks_starrocks&pullRequest=14250&resolved=false&types=VULNERABILITY) [0 Vulnerabilities](https://sonarcloud.io/project/issues?id=StarRocks_starrocks&pullRequest=14250&resolved=false&types=VULNERABILITY) [Security Hotspot](https://sonarcloud.io/project/security_hotspots?id=StarRocks_starrocks&pullRequest=14250&resolved=false&types=SECURITY_HOTSPOT) [A](https://sonarcloud.io/project/security_hotspots?id=StarRocks_starrocks&pullRequest=14250&resolved=false&types=SECURITY_HOTSPOT) [0 Security Hotspots](https://sonarcloud.io/project/security_hotspots?id=StarRocks_starrocks&pullRequest=14250&resolved=false&types=SECURITY_HOTSPOT) [Code Smell](https://sonarcloud.io/project/issues?id=StarRocks_starrocks&pullRequest=14250&resolved=false&types=CODE_SMELL) [A](https://sonarcloud.io/project/issues?id=StarRocks_starrocks&pullRequest=14250&resolved=false&types=CODE_SMELL) [0 Code Smells](https://sonarcloud.io/project/issues?id=StarRocks_starrocks&pullRequest=14250&resolved=false&types=CODE_SMELL)
> 
> [](https://sonarcloud.io/component_measures?id=StarRocks_starrocks&pullRequest=14250&metric=new_coverage&view=list) [0.0% Coverage](https://sonarcloud.io/component_measures?id=StarRocks_starrocks&pullRequest=14250&metric=new_coverage&view=list) [](https://sonarcloud.io/component_measures?id=StarRocks_starrocks&pullRequest=14250&metric=new_duplicated_lines_density&view=list) [0.0% Duplication](https://sonarcloud.io/component_measures?id=StarRocks_starrocks&pullRequest=14250&metric=new_duplicated_lines_density&view=list)

found a bug

**Comment by mofeiatwork** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 12 / 30 (40.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/plan/PlanFragmentBuilder.java|0|1|00.00%|[772]|
|:large_blue_circle:|com/starrocks/server/NodeMgr.java|0|1|00.00%|[279]|
|:large_blue_circle:|com/starrocks/common/util/SmallFileMgr.java|0|1|00.00%|[528]|
|:large_blue_circle:|com/starrocks/common/GenericPool.java|0|1|00.00%|[112]|
|:large_blue_circle:|com/starrocks/StarRocksFE.java|0|2|00.00%|[170, 259]|
|:large_blue_circle:|com/starrocks/qe/ConnectContext.java|0|1|00.00%|[574]|
|:large_blue_circle:|com/starrocks/ha/BDBHA.java|0|1|00.00%|[107]|
|:large_blue_circle:|com/starrocks/clone/TabletSchedulerStat.java|1|4|25.00%|[143, 168, 194]|
|:large_blue_circle:|com/starrocks/load/streamload/StreamLoadInfo.java|1|3|33.33%|[208, 282]|
|:large_blue_circle:|com/starrocks/http/action/HaAction.java|1|2|50.00%|[137]|
|:large_blue_circle:|com/starrocks/journal/bdbje/BDBTool.java|2|4|50.00%|[70, 161]|
|:large_blue_circle:|com/starrocks/common/io/Text.java|1|2|50.00%|[164]|
|:large_blue_circle:|com/starrocks/qe/Coordinator.java|2|3|66.67%|[1957]|
|:large_blue_circle:|com/starrocks/common/MarkDownParser.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/common/util/Util.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/mysql/MysqlPassword.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 11 / 29 (37.93%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/plan/PlanFragmentBuilder.java|0|1|00.00%|[772]|
|:large_blue_circle:|com/starrocks/server/NodeMgr.java|0|1|00.00%|[279]|
|:large_blue_circle:|com/starrocks/common/util/SmallFileMgr.java|0|1|00.00%|[528]|
|:large_blue_circle:|com/starrocks/common/GenericPool.java|0|1|00.00%|[112]|
|:large_blue_circle:|com/starrocks/StarRocksFE.java|0|2|00.00%|[170, 259]|
|:large_blue_circle:|com/starrocks/qe/ConnectContext.java|0|1|00.00%|[574]|
|:large_blue_circle:|com/starrocks/ha/BDBHA.java|0|1|00.00%|[107]|
|:large_blue_circle:|com/starrocks/clone/TabletSchedulerStat.java|1|4|25.00%|[143, 168, 194]|
|:large_blue_circle:|com/starrocks/load/streamload/StreamLoadInfo.java|1|3|33.33%|[208, 282]|
|:large_blue_circle:|com/starrocks/http/action/HaAction.java|1|2|50.00%|[137]|
|:large_blue_circle:|com/starrocks/journal/bdbje/BDBTool.java|2|4|50.00%|[70, 161]|
|:large_blue_circle:|com/starrocks/common/io/Text.java|1|2|50.00%|[164]|
|:large_blue_circle:|com/starrocks/qe/Coordinator.java|2|3|66.67%|[1957]|
|:large_blue_circle:|com/starrocks/common/MarkDownParser.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/mysql/MysqlPassword.java|1|1|100.00%|[]|

**Comment by mofeiatwork** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 11 / 28 (39.29%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/plan/PlanFragmentBuilder.java|0|1|00.00%|[772]|
|:large_blue_circle:|com/starrocks/server/NodeMgr.java|0|1|00.00%|[279]|
|:large_blue_circle:|com/starrocks/common/util/SmallFileMgr.java|0|1|00.00%|[528]|
|:large_blue_circle:|com/starrocks/common/GenericPool.java|0|1|00.00%|[112]|
|:large_blue_circle:|com/starrocks/StarRocksFE.java|0|1|00.00%|[258]|
|:large_blue_circle:|com/starrocks/qe/ConnectContext.java|0|1|00.00%|[574]|
|:large_blue_circle:|com/starrocks/ha/BDBHA.java|0|1|00.00%|[107]|
|:large_blue_circle:|com/starrocks/clone/TabletSchedulerStat.java|1|4|25.00%|[143, 168, 194]|
|:large_blue_circle:|com/starrocks/load/streamload/StreamLoadInfo.java|1|3|33.33%|[208, 282]|
|:large_blue_circle:|com/starrocks/http/action/HaAction.java|1|2|50.00%|[137]|
|:large_blue_circle:|com/starrocks/journal/bdbje/BDBTool.java|2|4|50.00%|[70, 161]|
|:large_blue_circle:|com/starrocks/common/io/Text.java|1|2|50.00%|[164]|
|:large_blue_circle:|com/starrocks/qe/Coordinator.java|2|3|66.67%|[1957]|
|:large_blue_circle:|com/starrocks/common/MarkDownParser.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/mysql/MysqlPassword.java|1|1|100.00%|[]|

**Review by Seaven — APPROVED** [review]

**Review by kangkaisen — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
