### PR TITLE
[BugFix] const_null_column has lost type use unfold_const_column to expand it

### PR DESCRIPTION
**Pull request by zombee0**
Fixes #issue
introduced by #26484 

## What type of PR is this:
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4

### CODE REVIEW

**Review by stdpain — DISMISSED** [review]

**Comment by stdpain** [comment]
It looks like there are a lot of bugs in our column's handling of null/literal, and I may have to refactor them later.

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by fzhedu — APPROVED** [review]
LGTM

**Review by Seaven — DISMISSED** [review]

**Review by stdpain — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by stdpain — DISMISSED** [review]

**Review by Seaven — DISMISSED** [review]

**Comment by Seaven** [comment]
> It looks like there are a lot of bugs in our column's handling of null/literal, and I may have to refactor them later.

I think a lot of new expressions don't handle only_null very well

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by stdpain — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by Seaven — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Pull request merged**
