### PR TITLE
Debayan sen96 patch 1

### PR DESCRIPTION
**Pull request by DebayanSen96**
Hello Sir this is my first time here. Hope I did everything correctly. Thank You.

### CODE REVIEW

**Comment by imay** [comment]
@DebayanSen96 Thank you very much for your contribution.

**Comment by Gri-ffin** [comment]
@DebayanSen96 Thank you but there is already an open pull request for that #3157

**Comment by DebayanSen96** [comment]
> [CLA assistant check](https://cla-assistant.io/StarRocks/starrocks?pullRequest=3161) All committers have signed the CLA.

Thank you Sir, for providing this oppurtonity.

**Comment by stdpain** [comment]
@DebayanSen96 It looks like this this issue has been solved by other PRs, I suggest you try to fix this issue-https://github.com/StarRocks/starrocks/issues/3163

**Pull request merged**
