### PR TITLE
[BugFix] Fix synchronized materialized view with upper column names

### LINKED ISSUE #31504: Result of synchronized materialized view with upper column names of the base table is wrong
### Steps to reproduce the behavior (Required)
```
CREATE TABLE `lineitem` (\n  `L_ORDERKEY` int(11) NOT NULL COMMENT "",\n  `L_PARTKEY` int(11) NOT NULL COMMENT "",\n  `L_SUPPKEY` int(11) NOT NULL COMMENT "",\n  `L_LINENUMBER` int(11) NOT NULL COMMENT "",\n  `L_QUANTITY` decimal64(15, 2) NOT NULL COMMENT "",\n  `L_EXTENDEDPRICE` decimal64(15, 2) NOT NULL COMMENT "",\n  `L_DISCOUNT` decimal64(15, 2) NOT NULL COMMENT "",\n  `L_TAX` decimal64(15, 2) NOT NULL COMMENT "",\n  `L_RETURNFLAG` char(1) NOT NULL COMMENT "",\n  `L_LINESTATUS` char(1) NOT NULL COMMENT "",\n  `L_SHIPDATE` date NOT NULL COMMENT "",\n  `L_COMMITDATE` date NOT NULL COMMENT "",\n  `L_RECEIPTDATE` date NOT NULL COMMENT "",\n  `L_SHIPINSTRUCT` char(25) NOT NULL COMMENT "",\n  `L_SHIPMODE` char(10) NOT NULL COMMENT "",\n  `L_COMMENT` varchar(44) NOT NULL COMMENT ""\n) ENGINE=OLAP \nDUPLICATE KEY(`L_ORDERKEY`)\nCOMMENT "OLAP"\nDISTRIBUTED BY HASH(`L_ORDERKEY`) BUCKETS 10 \nPROPERTIES (\n"replication_num" = "1",\n"in_memory" = "false",\n"enable_persistent_index" = "false",\n"replicated_storage" = "true",\n"compression" = "LZ4"\n);
```

```
create MATERIALIZED view my_test_mv2 as select L_LINESTATUS, sum(L_DISCOUNT), sum(L_TAX) from lineitem group by L_LINESTATUS
```

### Expected behavior (Required)
`l_linestatus` column should not be null.

### Real behavior (Required)
```
MySQL root@127.0.0.1:tpch>  select * from my_test_mv2 [_SYNC_MV_];
+--------------+-------------------+--------------+
| l_linestatus | mv_sum_l_discount | mv_sum_l_tax |
+--------------+-------------------+--------------+
|              | 29874.13          | 23941.37     |
|              | 29846.69          | 23890.56     |
|              | 29766.88          | 23798.42     |
|              | 29904.26          | 23942.12     |
|              | 30161.73          | 24107.16     |
|              | 29985.59          | 23984.34     |
|              | 30025.25          | 24082.90     |
|              | 30199.27          | 24146.46     |
|              | 30065.54          | 24054.70     |
|              | 30227.99          | 24181.64     |
+--------------+-------------------+--------------+
10 rows in set
```
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by LiShuMing**
Fix #31504 

- synchronized materialized view should be case sensitive for base table's column names.

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.2
  - [x] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 7 / 7 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/ast/CreateMaterializedViewStmt.java|7|7|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 7 / 7 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/ast/CreateMaterializedViewStmt.java|7|7|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by ABingHuang — APPROVED** [review]

**Review by murphyatwork — APPROVED** [review]

**Review by liuyehcf — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.2

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Pull request merged**
