### PR TITLE
[Bugfix] fix select subquery with order by throw exception

### PR DESCRIPTION
**Pull request by Seaven**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

```
MySQL td> select
    a.*,
    (select sum(t1.v1) from t1) initial_balance,
    ( select sum(t2.v2) from t2) ending_balance
from t3 a
order by a.v3
(1064, 'complex subquery on (SELECT sum(v1) FROM td.t1)')
```

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Review by kangkaisen — DISMISSED** [review]

**Comment by Seaven** [comment]
run starrocks_fe_unittest

**Comment by Seaven** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 13 / 13 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/transformer/QueryTransformer.java|13|13|100.00%|[]|

**Review by kangkaisen — APPROVED** [review]

**Comment by ZiheLiu** [comment]
run starrocks_admit_test

**Review by ZiheLiu — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by Seaven** [comment]
@Mergifyio backport branch-2.3

**Comment by Seaven** [comment]
https://github.com/Mergifyio backport branch-2.4

**Comment by yongbingwang** [comment]
branch-2.3
https://github.com/StarRocks/starrocks/pull/10209

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 13 / 13 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/transformer/QueryTransformer.java|13|13|100.00%|[]|

**Pull request merged**
