### PR TITLE
[Enhancement] Support alter materialized view to active

### PR DESCRIPTION
**Pull request by Astralidea**
Fixes #23304

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 57 / 174 (32.76%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/MaterializedView.java|0|3|00.00%|[181, 182, 183]|
|:large_blue_circle:|com/starrocks/sql/analyzer/SemanticException.java|0|1|00.00%|[72]|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|0|27|00.00%|[1570, 1571, 1580, 1581, 1582, 1583, 1584, 1585, 1586, 1588, 1589, 1590, 1591, 1592, 1593, 1594, 1596, 1597, 1598, 1599, 1600, 1601, 1602, 1604, 1605, 3302, 3303]|
|:large_blue_circle:|com/starrocks/persist/AlterMaterializedViewStatusLog.java|0|17|00.00%|[38, 39, 40, 41, 42, 45, 49, 50, 53, 57, 58, 61, 65, 66, 70, 71, 74]|
|:large_blue_circle:|com/starrocks/persist/EditLog.java|0|6|00.00%|[331, 332, 333, 334, 1639, 1640]|
|:large_blue_circle:|com/starrocks/journal/JournalEntity.java|0|3|00.00%|[328, 329, 330]|
|:large_blue_circle:|com/starrocks/alter/AlterJobMgr.java|1|48|02.08%|[319, 320, 321, 322, 324, 325, 326, 327, 328, 329, 330, 332, 334, 335, 337, 339, 340, 341, 353, 354, 355, 356, 357, 358, 360, 361, 363, 364, 365, 367, 368, 370, 371, 372, 373, 375, 376, 377, 379, 382, 383, 384, 385, 387, 388, 390, 392]|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|3|4|75.00%|[1642]|
|:large_blue_circle:|com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java|48|60|80.00%|[141, 142, 155, 157, 185, 186, 187, 188, 190, 876, 877, 878]|
|:large_blue_circle:|com/starrocks/sql/ast/AlterMaterializedViewStmt.java|5|5|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 57 / 174 (32.76%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/MaterializedView.java|0|3|00.00%|[181, 182, 183]|
|:large_blue_circle:|com/starrocks/sql/analyzer/SemanticException.java|0|1|00.00%|[72]|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|0|27|00.00%|[1570, 1571, 1580, 1581, 1582, 1583, 1584, 1585, 1586, 1588, 1589, 1590, 1591, 1592, 1593, 1594, 1596, 1597, 1598, 1599, 1600, 1601, 1602, 1604, 1605, 3302, 3303]|
|:large_blue_circle:|com/starrocks/persist/AlterMaterializedViewStatusLog.java|0|17|00.00%|[38, 39, 40, 41, 42, 45, 49, 50, 53, 57, 58, 61, 65, 66, 70, 71, 74]|
|:large_blue_circle:|com/starrocks/persist/EditLog.java|0|6|00.00%|[331, 332, 333, 334, 1639, 1640]|
|:large_blue_circle:|com/starrocks/journal/JournalEntity.java|0|3|00.00%|[328, 329, 330]|
|:large_blue_circle:|com/starrocks/alter/AlterJobMgr.java|1|48|02.08%|[319, 320, 321, 322, 324, 325, 326, 327, 328, 329, 330, 332, 334, 335, 337, 339, 340, 341, 353, 354, 355, 356, 357, 358, 360, 361, 363, 364, 365, 367, 368, 370, 371, 372, 373, 375, 376, 377, 379, 382, 383, 384, 385, 387, 388, 390, 392]|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|3|4|75.00%|[1642]|
|:large_blue_circle:|com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java|48|60|80.00%|[141, 142, 155, 157, 185, 186, 187, 188, 190, 876, 877, 878]|
|:large_blue_circle:|com/starrocks/sql/ast/AlterMaterializedViewStmt.java|5|5|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 57 / 174 (32.76%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/MaterializedView.java|0|3|00.00%|[181, 182, 183]|
|:large_blue_circle:|com/starrocks/sql/analyzer/SemanticException.java|0|1|00.00%|[72]|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|0|27|00.00%|[1570, 1571, 1580, 1581, 1582, 1583, 1584, 1585, 1586, 1588, 1589, 1590, 1591, 1592, 1593, 1594, 1596, 1597, 1598, 1599, 1600, 1601, 1602, 1604, 1605, 3302, 3303]|
|:large_blue_circle:|com/starrocks/persist/AlterMaterializedViewStatusLog.java|0|17|00.00%|[38, 39, 40, 41, 42, 45, 49, 50, 53, 57, 58, 61, 65, 66, 70, 71, 74]|
|:large_blue_circle:|com/starrocks/persist/EditLog.java|0|6|00.00%|[331, 332, 333, 334, 1639, 1640]|
|:large_blue_circle:|com/starrocks/journal/JournalEntity.java|0|3|00.00%|[328, 329, 330]|
|:large_blue_circle:|com/starrocks/alter/AlterJobMgr.java|1|48|02.08%|[319, 320, 321, 322, 324, 325, 326, 327, 328, 329, 330, 332, 334, 335, 337, 339, 340, 341, 353, 354, 355, 356, 357, 358, 360, 361, 363, 364, 365, 367, 368, 370, 371, 372, 373, 375, 376, 377, 379, 382, 383, 384, 385, 387, 388, 390, 392]|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|3|4|75.00%|[1642]|
|:large_blue_circle:|com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java|48|60|80.00%|[141, 142, 155, 157, 185, 186, 187, 188, 190, 876, 877, 878]|
|:large_blue_circle:|com/starrocks/sql/ast/AlterMaterializedViewStmt.java|5|5|100.00%|[]|

**Review by murphyatwork — APPROVED** [review]

**Review by packy92 — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
