### PR TITLE
[Refactor] Refactor transaction stream load interface

### PR DESCRIPTION
**Pull request by meegoo**
## What type of PR is this：
- [ ] bug
- [ ] feature
- [ ] enhancement
- [x] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

Currently, we only support single-DB and single-table transactions. In the future, when we support multi-table transactions across DBs, we can keep the interface compatible, and users do not need to modify the URL.
* BeginTrasaction:
> POST /api/transaction/begin
* CommitTransaction:
> POST /api/transaction/commit
* RollbackTransaction:
> POST /api/transaction/rollback
* LoadData:
> PUT /api/transaction/load

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 1 / 4 (25.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/http/rest/TransactionLoadAction.java|1|4|25.00%|

**Review by mark-phoenix-ai — APPROVED** [review]
Remember to update the  corresponding  documents.

**Review by chaoyli — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by Astralidea — APPROVED** [review]

**Comment by meegoo** [comment]
@mergify backport branch-2.3

**Pull request merged**
