### PR TITLE
[BugFix] Fix auto partition function missing

### PR DESCRIPTION
**Pull request by Astralidea**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 3.0
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Comment by Astralidea** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 14 / 21 (66.67%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/backup/RestoreJob.java|0|3|00.00%|[525, 555, 843]|
|:large_blue_circle:|com/starrocks/leader/LeaderImpl.java|0|1|00.00%|[922]|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|0|1|00.00%|[2623]|
|:large_blue_circle:|com/starrocks/catalog/OlapTable.java|1|2|50.00%|[580]|
|:large_blue_circle:|com/starrocks/common/proc/PartitionsProcDir.java|2|3|66.67%|[322]|
|:large_blue_circle:|com/starrocks/common/proc/TablesProcDir.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/OlapScanNode.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/load/PartitionUtils.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/ColocateTableIndex.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/load/InsertOverwriteJobRunner.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/service/InformationSchemaDataSource.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/alter/SchemaChangeHandler.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rewrite/OptOlapPartitionPruner.java|3|3|100.00%|[]|

**Comment by Astralidea** [comment]
run starrocks_admit_test

**Review by gengjun-git — APPROVED** [review]

**Review by ABingHuang — APPROVED** [review]
LGTM

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Pull request merged**
