### PR TITLE
[Refactor] rename to big_query_cpu_second_limit

### PR DESCRIPTION
**Pull request by murphyatwork**
## What type of PR is this：
- [ ] bug
- [ ] feature
- [ ] enhancement
- [x] others

## Problem Summary(Required) ：

Rename resource setting `big_query_cpu_core_second_limit` to `big_query_cpu_second_limit`.

### CODE REVIEW

**Comment by mofeiatwork** [comment]
run starrocks_fe_unittest

**Comment by mofeiatwork** [comment]
run starrocks_clang-format

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 12 / 14 (85.71%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/analysis/AlterWorkGroupStmt.java|0|1|00.00%|
|:large_blue_circle:|com/starrocks/sql/analyzer/WorkGroupAnalyzer.java|2|3|66.67%|
|:large_blue_circle:|com/starrocks/catalog/WorkGroup.java|8|8|100.00%|
|:large_blue_circle:|com/starrocks/catalog/WorkGroupMgr.java|2|2|100.00%|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 12 / 14 (85.71%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/analysis/AlterWorkGroupStmt.java|0|1|00.00%|
|:large_blue_circle:|com/starrocks/sql/analyzer/WorkGroupAnalyzer.java|2|3|66.67%|
|:large_blue_circle:|com/starrocks/catalog/WorkGroup.java|8|8|100.00%|
|:large_blue_circle:|com/starrocks/catalog/WorkGroupMgr.java|2|2|100.00%|

**Review by kangkaisen — APPROVED** [review]

**Review by Seaven — APPROVED** [review]

**Pull request merged**
