### PR TITLE
[Enhancement] Add catch bad alloc for serialize/finalize/transmit_chunk

### PR DESCRIPTION
**Pull request by Pslydhh**
## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

It appear when We execute sql with two-phase aggregate and massive datas:
```
select window_funnel(100 , time, 0 , [event_type = '浏览', event_type = '点击', event_type = '下单' ]) from window_funnel;
```

## Problem Summary(Required) ：

When we use window_funnel for two-phase aggregate(**update-serialize=>merge-finalize**), It will collect records through serialization to second phase, If there records are massive and overflow available memory, It will throw bad alloc exception, and we missed it. **So we should catch it.**

Add TRY_CATCH_BAD_ALLOC for serialize_to_column for bad alloc.

### CODE REVIEW

**Review by kangkaisen — DISMISSED** [review]

**Review by satanson — APPROVED** [review]

**Review by kangkaisen — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.4

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.3

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.2

**Pull request merged**
