### PR TITLE
[Enhancement] reduce trivial lambda functions

### PR DESCRIPTION
**Pull request by fzhedu**
Signed-off-by: fzhedu <fzhedu@gmail.com>

## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

reduce trivial lambda functions, which just return original elements of an input array.

```
mysql> explain  select  array_map(x-> x, c2) from test_array;
+-----------------------------+
| Explain String              |
+-----------------------------+
| PLAN FRAGMENT 0             |
|  OUTPUT EXPRS:2: c2         |
|   PARTITION: UNPARTITIONED  |
|                             |
|   RESULT SINK               |
|                             |
|   1:EXCHANGE                |
|                             |
| PLAN FRAGMENT 1             |
|  OUTPUT EXPRS:              |
|   PARTITION: RANDOM         |
|                             |
|   STREAM DATA SINK          |
|     EXCHANGE ID: 01         |
|     UNPARTITIONED           |
|                             |
|   0:OlapScanNode            |
|      TABLE: test_array      |
|      PREAGGREGATION: ON     |
|      partitions=1/1         |
|      rollup: test_array     |
|      tabletRatio=2/2        |
|      tabletList=13004,13006 |
|      cardinality=9          |
|      avgRowSize=16.0        |
|      numNodes=0             |
+-----------------------------+
26 rows in set (0.01 sec)

mysql> explain  select  array_map(x-> x+1, c2) from test_array;
+----------------------------------------------------------------------------+
| Explain String                                                             |
+----------------------------------------------------------------------------+
| PLAN FRAGMENT 0                                                            |
|  OUTPUT EXPRS:5: array_map                                                 |
|   PARTITION: UNPARTITIONED                                                 |
|                                                                            |
|   RESULT SINK                                                              |
|                                                                            |
|   2:EXCHANGE                                                               |
|                                                                            |
| PLAN FRAGMENT 1                                                            |
|  OUTPUT EXPRS:                                                             |
|   PARTITION: RANDOM                                                        |
|                                                                            |
|   STREAM DATA SINK                                                         |
|     EXCHANGE ID: 02                                                        |
|     UNPARTITIONED                                                          |
|                                                                            |
|   1:Project                                                                |
|   |  <slot 5> : array_map(<slot 4> -> CAST(<slot 4> AS BIGINT) + 1, 2: c2) |
|   |                                                                        |
|   0:OlapScanNode                                                           |
|      TABLE: test_array                                                     |
|      PREAGGREGATION: ON                                                    |
|      partitions=1/1                                                        |
|      rollup: test_array                                                    |
|      tabletRatio=2/2                                                       |
|      tabletList=13004,13006                                                |
|      cardinality=9                                                         |
|      avgRowSize=17.0                                                       |
|      numNodes=0                                                            |
+----------------------------------------------------------------------------+
29 rows in set (0.01 sec)

mysql> explain  select  array_map((x,y)->y, c2,c3) from test_array;
+-----------------------------+
| Explain String              |
+-----------------------------+
| PLAN FRAGMENT 0             |
|  OUTPUT EXPRS:3: c3         |
|   PARTITION: UNPARTITIONED  |
|                             |
|   RESULT SINK               |
|                             |
|   1:EXCHANGE                |
|                             |
| PLAN FRAGMENT 1             |
|  OUTPUT EXPRS:              |
|   PARTITION: RANDOM         |
|                             |
|   STREAM DATA SINK          |
|     EXCHANGE ID: 01         |
|     UNPARTITIONED           |
|                             |
|   0:OlapScanNode            |
|      TABLE: test_array      |
|      PREAGGREGATION: ON     |
|      partitions=1/1         |
|      rollup: test_array     |
|      tabletRatio=2/2        |
|      tabletList=13004,13006 |
|      cardinality=9          |
|      avgRowSize=1.0         |
|      numNodes=0             |
+-----------------------------+
mysql> explain  select  array_map((x,y)->y, c2,c3) from test_array where array_length(array_map(x->x,c2)) >0;
+------------------------------------------+
| Explain String                           |
+------------------------------------------+
| PLAN FRAGMENT 0                          |
|  OUTPUT EXPRS:3: c3                      |
|   PARTITION: UNPARTITIONED               |
|                                          |
|   RESULT SINK                            |
|                                          |
|   2:EXCHANGE                             |
|                                          |
| PLAN FRAGMENT 1                          |
|  OUTPUT EXPRS:                           |
|   PARTITION: RANDOM                      |
|                                          |
|   STREAM DATA SINK                       |
|     EXCHANGE ID: 02                      |
|     UNPARTITIONED                        |
|                                          |
|   1:Project                              |
|   |  <slot 3> : 3: c3                    |
|   |                                      |
|   0:OlapScanNode                         |
|      TABLE: test_array                   |
|      PREAGGREGATION: ON                  |
|      PREDICATES: array_length(2: c2) > 0 |
|      partitions=1/1                      |
|      rollup: test_array                  |
|      tabletRatio=2/2                     |
|      tabletList=13004,13006              |
|      cardinality=5                       |
|      avgRowSize=32.0                     |
|      numNodes=0                          |
+------------------------------------------+
30 rows in set (0.01 sec)

mysql> explain  select  array_map((x,y)->y, c2,c3) from test_array where array_length(array_map(x->x,c2)) is null;
+----------------------------------------------+
| Explain String                               |
+----------------------------------------------+
| PLAN FRAGMENT 0                              |
|  OUTPUT EXPRS:3: c3                          |
|   PARTITION: UNPARTITIONED                   |
|                                              |
|   RESULT SINK                                |
|                                              |
|   2:EXCHANGE                                 |
|                                              |
| PLAN FRAGMENT 1                              |
|  OUTPUT EXPRS:                               |
|   PARTITION: RANDOM                          |
|                                              |
|   STREAM DATA SINK                           |
|     EXCHANGE ID: 02                          |
|     UNPARTITIONED                            |
|                                              |
|   1:Project                                  |
|   |  <slot 3> : 3: c3                        |
|   |                                          |
|   0:OlapScanNode                             |
|      TABLE: test_array                       |
|      PREAGGREGATION: ON                      |
|      PREDICATES: array_length(2: c2) IS NULL |
|      partitions=1/1                          |
|      rollup: test_array                      |
|      tabletRatio=2/2                         |
|      tabletList=13004,13006                  |
|      cardinality=1                           |
|      avgRowSize=32.0                         |
|      numNodes=0                              |
+----------------------------------------------+
30 rows in set (0.01 sec)
```
## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 12 / 12 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/scalar/LambdaFunctionOperator.java|5|5|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rewrite/scalar/SimplifiedPredicateRule.java|7|7|100.00%|[]|

**Comment by fzhedu** [comment]
run starrocks_admit_test

**Comment by fzhedu** [comment]
run starrocks_admit_test

**Review by kangkaisen — APPROVED** [review]

**Review by Seaven — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by fzhedu** [comment]
run starrocks_admit_test

**Review by murphyatwork — APPROVED** [review]

**Comment by mofeiatwork** [comment]
run wr_order_number

**Comment by fzhedu** [comment]
run run starrocks_admit_test

**Comment by mofeiatwork** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
