### PR TITLE
[BugFix] fix mv refresh all the time if base table dropped partition

### PR DESCRIPTION
**Pull request by blackstar-baba**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

1. Create mv
```
CREATE MATERIALIZED VIEW mv1_multi_tables_partition_by_function_month
PARTITION BY date_trunc('month',s1)
distributed by hash(s2)
refresh async EVERY(INTERVAL 10 SECOND)
PROPERTIES('replication_num' = '1')
AS select t1.k1 s1, t2.k2 s2 from tbl1 t1 join tbl2 t2 on t1.k1 = t2.k1;
```
2. Drop exist base table partition
```
ALTER TABLE tbl1 DROP PARTITION p3;
```
3.  Fe.log like this:
```

2022-07-27 16:40:41,485 INFO (pool-21-thread-1|134) [MvTaskRunProcessor.processSyncBasePartition():227] The process of synchronizing partitions delete range {}
2022-07-27 16:40:41,505 INFO (pool-21-thread-1|134) [MvTaskRunProcessor.processSyncBasePartition():237] The process of synchronizing partitions add range {} 
2022-07-27 16:40:41,505 INFO (pool-21-thread-1|134) [MvTaskRunProcessor.processSyncBasePartition():281] Calculate the partitions that need to be refreshed:[[p000101_202202, p202202_202203]]
……
……
……
2022-07-27 16:40:45,485 INFO (pool-21-thread-1|134) [MvTaskRunProcessor.processSyncBasePartition():227] The process of synchronizing partitions delete range {}
2022-07-27 16:40:45,506 INFO (pool-21-thread-1|134) [MvTaskRunProcessor.processSyncBasePartition():237] The process of synchronizing partitions add range {} 
2022-07-27 16:40:45,506 INFO (pool-21-thread-1|134) [MvTaskRunProcessor.processSyncBasePartition():281] Calculate the partitions that need to be refreshed:[[p000101_202202, p202202_202203]]
……
……
……
2022-07-27 16:40:51,485 INFO (pool-21-thread-1|134) [MvTaskRunProcessor.processSyncBasePartition():227] The process of synchronizing partitions delete range {}
2022-07-27 16:40:51,506 INFO (pool-21-thread-1|134) [MvTaskRunProcessor.processSyncBasePartition():237] The process of synchronizing partitions add range {} 
2022-07-27 16:40:51,506 INFO (pool-21-thread-1|134) [MvTaskRunProcessor.processSyncBasePartition():281] Calculate the partitions that need to be refreshed:[[p000101_202202, p202202_202203]]
```

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 10 / 10 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/MaterializedView.java|8|8|100.00%|[]|
|:large_blue_circle:|com/starrocks/scheduler/MvTaskRunProcessor.java|2|2|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 10 / 10 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/MaterializedView.java|8|8|100.00%|[]|
|:large_blue_circle:|com/starrocks/scheduler/MvTaskRunProcessor.java|2|2|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 10 / 10 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/MaterializedView.java|8|8|100.00%|[]|
|:large_blue_circle:|com/starrocks/scheduler/MvTaskRunProcessor.java|2|2|100.00%|[]|

**Review by Astralidea — DISMISSED** [review]

**Review by Astralidea — APPROVED** [review]

**Comment by Astralidea** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 10 / 10 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/MaterializedView.java|8|8|100.00%|[]|
|:large_blue_circle:|com/starrocks/scheduler/MvTaskRunProcessor.java|2|2|100.00%|[]|

**Review by gengjun-git — APPROVED** [review]

**Pull request merged**
