### PR TITLE
[Enhancement] support statistics for iceberg table and optimize statistics calculation 

### PR DESCRIPTION
**Pull request by packy92**
Fixes #issue

## Main work:
- support push down predicate generated from range join on condition to its children.
- support collect ndv info from iceberg ndv metadata.
- optimize join statistics calculation process

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:disappointed: **fail** : 265 / 461 (57.48%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/Utils.java|0|1|00.00%|[399]|
|:large_blue_circle:|com/starrocks/connector/iceberg/cost/IcebergFileStats.java|2|33|06.06%|[127, 135, 136, 139, 143, 144, 146, 147, 149, 150, 151, 156, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 275, 276, 279, 280, 281, 283, 286]|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/logical/LogicalIcebergScanOperator.java|1|4|25.00%|[62, 66, 67]|
|:large_blue_circle:|com/starrocks/qe/SessionVariable.java|3|8|37.50%|[1100, 1104, 1105, 1307, 1308]|
|:large_blue_circle:|com/starrocks/connector/iceberg/cost/IcebergStatisticProvider.java|64|159|40.25%|[90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 101, 102, 110, 111, 118, 119, 120, 122, 179, 180, 181, 184, 185, 191, 192, 212, 214, 215, 216, 217, 218, 219, 220, 234, 265, 266, 267, 268, 269, 270, 275, 276, 277, 278, 279, 280, 286, 295, 296, 347, 348, 359, 360, 375, 376, 378, 379, 381, 384, 385, 386, 387, 388, 389, 391, 392, 393, 394, 395, 396, 397, 399, 400, 402, 403, 405, 409, 410, 413, 414, 416, 418, 419, 422, 423, 424, 425, 429, 432, 434, 435, 436, 438, 439, 441]|
|:large_blue_circle:|com/starrocks/sql/optimizer/statistics/StatisticsCalculator.java|23|53|43.40%|[298, 299, 300, 301, 1394, 1395, 1396, 1397, 1398, 1399, 1400, 1401, 1402, 1403, 1406, 1408, 1409, 1410, 1411, 1412, 1415, 1418, 1419, 1425, 1426, 1427, 1428, 1429, 1430, 1432]|
|:large_blue_circle:|com/starrocks/connector/iceberg/IcebergMetadata.java|1|2|50.00%|[289]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/DeriveRangeJoinPredicateRule.java|89|115|77.39%|[75, 86, 122, 131, 138, 139, 145, 146, 169, 178, 185, 192, 193, 194, 195, 197, 198, 199, 209, 210, 211, 213, 214, 215, 218, 229]|
|:large_blue_circle:|com/starrocks/sql/optimizer/statistics/ColumnStatistic.java|21|25|84.00%|[271, 272, 276, 277]|
|:large_blue_circle:|com/starrocks/sql/optimizer/Optimizer.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/IcebergTable.java|5|5|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/statistics/PredicateStatisticsCalculator.java|19|19|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/RuleType.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/statistics/ExpressionStatisticCalculator.java|35|35|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by liuyehcf — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:disappointed: **fail** : 265 / 463 (57.24%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/Utils.java|0|1|00.00%|[399]|
|:large_blue_circle:|com/starrocks/connector/iceberg/cost/IcebergFileStats.java|2|33|06.06%|[127, 135, 136, 139, 143, 144, 146, 147, 149, 150, 151, 156, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 275, 276, 279, 280, 281, 283, 286]|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/logical/LogicalIcebergScanOperator.java|1|4|25.00%|[62, 66, 67]|
|:large_blue_circle:|com/starrocks/qe/SessionVariable.java|3|8|37.50%|[1100, 1104, 1105, 1307, 1308]|
|:large_blue_circle:|com/starrocks/connector/iceberg/cost/IcebergStatisticProvider.java|64|159|40.25%|[90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 101, 102, 110, 111, 118, 119, 120, 122, 179, 180, 181, 184, 185, 191, 192, 212, 214, 215, 216, 217, 218, 219, 220, 234, 265, 266, 267, 268, 269, 270, 275, 276, 277, 278, 279, 280, 286, 295, 296, 347, 348, 359, 360, 375, 376, 378, 379, 381, 384, 385, 386, 387, 388, 389, 391, 392, 393, 394, 395, 396, 397, 399, 400, 402, 403, 405, 409, 410, 413, 414, 416, 418, 419, 422, 423, 424, 425, 429, 432, 434, 435, 436, 438, 439, 441]|
|:large_blue_circle:|com/starrocks/sql/optimizer/statistics/StatisticsCalculator.java|23|53|43.40%|[298, 299, 300, 301, 1394, 1395, 1396, 1397, 1398, 1399, 1400, 1401, 1402, 1403, 1406, 1408, 1409, 1410, 1411, 1412, 1415, 1418, 1419, 1425, 1426, 1427, 1428, 1429, 1430, 1432]|
|:large_blue_circle:|com/starrocks/connector/iceberg/IcebergMetadata.java|1|2|50.00%|[289]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/DeriveRangeJoinPredicateRule.java|89|117|76.07%|[75, 86, 122, 131, 138, 139, 145, 146, 147, 148, 171, 180, 187, 194, 195, 196, 197, 199, 200, 201, 211, 212, 213, 215, 216, 217, 220, 231]|
|:large_blue_circle:|com/starrocks/sql/optimizer/statistics/ColumnStatistic.java|21|25|84.00%|[271, 272, 276, 277]|
|:large_blue_circle:|com/starrocks/sql/optimizer/Optimizer.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/IcebergTable.java|5|5|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/statistics/PredicateStatisticsCalculator.java|19|19|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/RuleType.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/statistics/ExpressionStatisticCalculator.java|35|35|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Pull request merged**
