### PR TITLE
[Feature] (DataSketches) Support Quantile/Theta/Frequency Sketches Aggregate Functions

### LINKED ISSUE #50671: [Aggregate Function] Support DataSketches in StarRocks
- [x] https://github.com/StarRocks/starrocks/pull/56960
## Enhancement

Since StarRocks has already integrated with [DataSketches](https://datasketches.apache.org/) and supported [HLLSketch](https://github.com/StarRocks/starrocks/issues/20831), but we can support more sketches for more user scenes.

- `ds_theta_count_distinct`(Theta Sketch): https://github.com/StarRocks/starrocks/pull/56960
- `ds_quantile_percentile_approx`(Quantile Sketches): 
- `ds_frequency_approx_top_k`(Frequency Sketches )

- ....

### PR DESCRIPTION
**Pull request by chenminghua8**
## What I'm doing:
Add more data sketch functions:
- ds_quantile
- ds_frequent
- ds_theta_count_distinct

```
CREATE TABLE t2 (
  id BIGINT NOT NULL,
  province VARCHAR(64),
  age SMALLINT,
  dt VARCHAR(10) NOT NULL 
)
DUPLICATE KEY(id)
DISTRIBUTED BY HASH(id) BUCKETS 4
PROPERTIES (
    "replication_num" = "1"
);

insert into t2 select generate_series, generate_series, generate_series % 10, "2024-07-24" from table(generate_series(1, 100));

select ds_quantile(id), ds_quantile(age) from t2 order by 1, 2;

select ds_quantile(id, [0.1, 0.5, 0.9]), ds_quantile(age, [0.1, 0.5, 0.9]) from t2 order by 1, 2;

select ds_quantile(id, [0.1, 0.5, 0.9], 10000), ds_quantile(age, [0.1, 0.5, 0.9], 10000) from t2 order by 1, 2;


select ds_frequent(age, 1) from t1;

select ds_frequent(age, 2, 21) from t1;

select ds_frequent(age, 2, 21, 3) from t1;


select ds_theta(id), ds_theta(province), ds_theta(age), ds_theta(dt) from t1 order by 1, 2;

```

Fixes #50671

## What type of PR is this:

- [ ] BugFix
- [x] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [x] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 3.3
  - [ ] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Comment by LiShuMing** [comment]
Thanks for you contributions. Can you fix failed tests and try it again?

The new agg functions cannot be used in `AggState`, so you can add them into `UNSUPPORTED_AGG_STATE_FUNCTIONS` to skip uts.  
```
    // Unsupported functions for agg state combinator.
    public static final Set<String> UNSUPPORTED_AGG_STATE_FUNCTIONS =
            new ImmutableSortedSet.Builder<>(String.CASE_INSENSITIVE_ORDER)
                    // TODO: Add unsupported functions here.
                    .add(GROUP_CONCAT) // Unsupported function
                    // UNSUPPORTED functions
                    .add(COUNT_IF) // count_if is a syntax sugar in fe
                    .add(HLL_RAW) // hll_raw use `hll` as input, use existed `hll_union` instead
                    // Internal functions are not supported.
                    .add(FLAT_JSON_META)
                    .add(EXCHANGE_BYTES)
                    .add(EXCHANGE_SPEED)
                    .add(FIRST_VALUE_REWRITE)
                    .add(HISTOGRAM)
                    .add(DICT_MERGE)
                    // Functions with constant contexts in be are not supported.
                    .add(WINDOW_FUNNEL)
                    .add(APPROX_TOP_K)
                    .add(INTERSECT_COUNT)
                    .add(LC_PERCENTILE_DISC)
                    .add(MAP_AGG)
                    .build();
```

**Comment by chenminghua8** [comment]
@ 

> Thanks for you contributions. Can you fix failed tests and try it again?
> 
> The new agg functions cannot be used in `AggState`, so you can add them into `UNSUPPORTED_AGG_STATE_FUNCTIONS` to skip uts.
> 
> ```
>     // Unsupported functions for agg state combinator.
>     public static final Set<String> UNSUPPORTED_AGG_STATE_FUNCTIONS =
>             new ImmutableSortedSet.Builder<>(String.CASE_INSENSITIVE_ORDER)
>                     // TODO: Add unsupported functions here.
>                     .add(GROUP_CONCAT) // Unsupported function
>                     // UNSUPPORTED functions
>                     .add(COUNT_IF) // count_if is a syntax sugar in fe
>                     .add(HLL_RAW) // hll_raw use `hll` as input, use existed `hll_union` instead
>                     // Internal functions are not supported.
>                     .add(FLAT_JSON_META)
>                     .add(EXCHANGE_BYTES)
>                     .add(EXCHANGE_SPEED)
>                     .add(FIRST_VALUE_REWRITE)
>                     .add(HISTOGRAM)
>                     .add(DICT_MERGE)
>                     // Functions with constant contexts in be are not supported.
>                     .add(WINDOW_FUNNEL)
>                     .add(APPROX_TOP_K)
>                     .add(INTERSECT_COUNT)
>                     .add(LC_PERCENTILE_DISC)
>                     .add(MAP_AGG)
>                     .build();
> ```

@LiShuMing Fixed, but the CreateTableWithAggStateTest.testCreateTableWithAggStateHllSketch test fails. Can I remove CreateTableWithAggStateTest.testCreateTableWithAggStateHllSketch?

**Comment by LiShuMing** [comment]
@merigify rebase

**Comment by LiShuMing** [comment]
@mergify rebase

**Pull request closed without merging**
