### PR TITLE
2.2.5 release notes-en

### PR DESCRIPTION
**Pull request by evelynzhaojie**
## What type of PR is this：
- [ ] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by evelynzhaojie** [comment]
[@mergify](https://github.com/mergify) backport branch-2.3

**Review by hellolilyliuyi — APPROVED** [review]

**Review by femiiii — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by evelynzhaojie** [comment]
@mergify backport branch-2.3

**Comment by evelynzhaojie** [comment]
@mergify backport branch-2.2

**Pull request merged**
