### PR TITLE
[BugFix][cherry-pick][branch-2.5] Give a default value to eliminate the DCHECK error in debug mode

### PR DESCRIPTION
**Pull request by zombee0**
…mode (#13745)

## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

- [ ] I have checked the version labels which the pr will be auto backported to target branch

### CODE REVIEW

**Comment by zombee0** [comment]
run starrocks_clang-format

**Comment by zombee0** [comment]
run starrocks_fe_unittest

**Comment by zombee0** [comment]
run starrocks_clang-tidy

**Comment by zombee0** [comment]
run starrocks_tscancode

**Review by Youngwb — APPROVED** [review]

**Pull request merged**
