### PR TITLE
std::variant added

### LINKED ISSUE #2619: use std::variant instead of boost::variant
StarRocks is compiled using c++17, so instead of relying on boost::variant, we can use std::variant.

This is a very simple issue, you can try this modification

### PR DESCRIPTION
**Pull request by karan-kap00r**
## What type of PR is this：
- [ ] bug
- [ ] feature
- [x] enhancement
- [ ] others

## Which issues of this PR fixes ：

Fixes #

### CODE REVIEW

**Comment by stdpain** [comment]
Hi there are some still changes need to do.
1. add header in be/src/exec/vectorized/olap_scan_prepare.cpp
```patch
@@ -2,6 +2,7 @@
 // This file is licensed under the Elastic License 2.0. Copyright 2021-present, StarRocks Limited.
 
 #include "exec/vectorized/olap_scan_prepare.h"
+#include <variant>
```
2. use std::get instead of boost::get in be/src/exec/vectorized/olap_scan_prepare.cpp
```patch
@@ -513,7 +514,7 @@ struct ColumnRangeBuilder {
                 full_range.set_scale(slot->type().scale);
             }
             ColumnValueRangeType& v = LookupOrInsert(column_value_ranges, col_name, full_range);
-            RangeType& range = boost::get<ColumnValueRange<value_type>>(v);
+            RangeType& range = std::get<ColumnValueRange<value_type>>(v);
             if constexpr (pt_is_decimal<limit_type>) {
```
3. use std::visit instead of boost::visit in be/src/exec/vectorized/olap_scan_prepare.cpp
```patch
@@ -546,8 +547,8 @@ Status OlapScanConjunctsManager::build_olap_filters() {
 
     for (auto iter : column_value_ranges) {
         std::vector<TCondition> filters;
-        boost::apply_visitor([&](auto&& range) { range.to_olap_filter(filters); }, iter.second);
-        bool empty_range = boost::apply_visitor([](auto&& range) { return range.is_empty_value_range(); }, 
iter.second);
+        std::visit([&](auto&& range) { range.to_olap_filter(filters); }, iter.second);
+        bool empty_range = std::visit([](auto&& range) { return range.is_empty_value_range(); }, iter.secon
d);
```
```patch
@@ -604,7 +605,7 @@ Status OlapScanConjunctsManager::build_scan_keys(bool unlimited, int32_t max_sca
     if (conditional_key_columns > 1) {
         for (int i = 0; i < conditional_key_columns && !scan_keys.has_range_value(); ++i) {
             ExtendScanKeyVisitor visitor(&scan_keys, max_scan_key_num);
-            if (!boost::apply_visitor(visitor, column_value_ranges[ref_key_column_names[i]]).ok()) {
+            if (!std::visit(visitor, column_value_ranges[ref_key_column_names[i]]).ok()) {
                 break;
             }
         }
```

**Comment by karan-kap00r** [comment]
@stdpain  hey....Is it better now??

**Comment by stdpain** [comment]
plz format olap_scan_prepare.cpp
```patch
--- /home/disk1/jenkins/workspace/starrocks_clang-format/starrocks/be/src/exec/vectorized/olap_scan_prepare.cpp
+++ /home/disk1/jenkins/workspace/starrocks_clang-format/starrocks/be/src/exec/vectorized/olap_scan_prepare.cpp (after clang format)
@@ -2,6 +2,8 @@
 // This file is licensed under the Elastic License 2.0. Copyright 2021-present, StarRocks Limited.
 
 #include "exec/vectorized/olap_scan_prepare.h"
+
+#include <variant>
 
 #include "column/type_traits.h"
 #include "exprs/vectorized/in_const_predicate.hpp"
@@ -12,7 +14,6 @@
 #include "runtime/primitive_type_infra.h"
 #include "storage/vectorized/column_predicate.h"
 #include "storage/vectorized/predicate_parser.h"
-#include <variant>
 
 namespace starrocks {
 namespace vectorized {
/home/disk1/jenkins/workspace/starrocks_clang-format/starrocks/be/src/exec/vectorized/olap_scan_prepare.cpp had clang-format style issues
```

**Comment by karan-kap00r** [comment]
@stdpain  Mate, do i have to add this line also??
/home/disk1/jenkins/workspace/starrocks_clang-format/starrocks/be/src/exec/vectorized/olap_scan_prepare.cpp (after clang format)

**Comment by stdpain** [comment]
sure. we need pass format check

**Comment by stdpain** [comment]
you should remove line
be/src/exec/vectorized/olap_scan_prepare.cpp 18

**Comment by karan-kap00r** [comment]
now i think its fine as all the checks have passed..!

**Review by stdpain — APPROVED** [review]

**Review by kangkaisen — APPROVED** [review]

**Pull request merged**
