### PR TITLE
[Enhancement] Remove unsed Jindo sdk in BE

### PR DESCRIPTION
**Pull request by Smith-Cruise**
## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

In BE, we access OSS using S3 SDK, so there is no need to add jindo SDK anymore, it can save nearly 200MB of space.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 3.0
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by adrian-wang** [comment]
If BE need to access [OSS-HDFS](https://help.aliyun.com/document_detail/405089.html), then JindoSDK is a necessity.

**Comment by Smith-Cruise** [comment]
> If BE need to access [OSS-HDFS](https://help.aliyun.com/document_detail/405089.html), then JindoSDK is a necessity.

What's the oss-hdfs protocol? `oss://` ?

**Comment by adrian-wang** [comment]
> > If BE need to access [OSS-HDFS](https://help.aliyun.com/document_detail/405089.html), then JindoSDK is a necessity.
> 
> What's the oss-hdfs protocol? `oss://` ?

Yes, it only varies by a separate endpoint.

**Comment by Smith-Cruise** [comment]
> > > If BE need to access [OSS-HDFS](https://help.aliyun.com/document_detail/405089.html), then JindoSDK is a necessity.
> > 
> > 
> > What's the oss-hdfs protocol? `oss://` ?
> 
> Yes, it only varies by a separate endpoint.

We already redirect `oss://` protocol to s3 sdk, not used jindo sdk already.
If you want to use jindo, you can change the code and put jindo jar in be.

**Comment by adrian-wang** [comment]
> 

you cannot access oss-hdfs using s3 sdk. OSS-HDFS does NOT support S3 protocol.

**Comment by Smith-Cruise** [comment]
> > 
> 
> you cannot access oss-hdfs using s3 sdk. OSS-HDFS does NOT support S3 protocol.

Yes, I know about it, but we didn't decide to support oss-hdfs officially.

**Pull request merged**
