### PR TITLE
[Refactor] Refactor show materialzied views command

### PR DESCRIPTION
**Pull request by LiShuMing**
- Add the `ShowMaterializedViewStatus ` class to represent the result of the `show materialized views command`
- Current test cases can cover the changed codes.

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [x] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:disappointed: **fail** : 107 / 141 (75.89%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/ShowMaterializedViewStatus.java|85|116|73.28%|[53, 57, 58, 61, 65, 66, 69, 73, 74, 77, 85, 93, 101, 109, 117, 121, 122, 125, 129, 130, 133, 137, 138, 141, 145, 146, 149, 157, 239, 272, 273]|
|:large_blue_circle:|com/starrocks/qe/ShowExecutor.java|19|22|86.36%|[585, 625, 629]|
|:large_blue_circle:|com/starrocks/service/FrontendServiceImpl.java|3|3|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by ABingHuang — APPROVED** [review]

**Review by Astralidea — APPROVED** [review]

**Pull request merged**
