### PR TITLE
[BugFix] Remove the helpers from bdb ReplicationGroupAdmin when dropped fe

### LINKED ISSUE #5663: Remove the helpers from bdb ReplicationGroupAdmin when dropped fe
## Enhancement
Remove the helpers from bdb ReplicationGroupAdmin when dropped fe. Or the dropped fe will block the operation of ReplicationGroupAdmin.

### PR DESCRIPTION
**Pull request by waittttting**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #5663

## Problem Summary(Required) ：

Remove the helpers from bdb ReplicationGroupAdmin when dropped fe

### CODE REVIEW

**Review by gengjun-git — DISMISSED** [review]
LGTM

**Comment by waittttting** [comment]
run starrocks_fe_unittest

**Comment by waittttting** [comment]
run starrocks_fe_unittest

**Comment by gengjun-git** [comment]
run starrocks_fe_unittest

**Comment by waittttting** [comment]
run starrocks_fe_unittest

**Comment by waittttting** [comment]
run starrocks_fe_unittest

**Comment by waittttting** [comment]
run starrocks_fe_unittest

**Comment by waittttting** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 9 / 9 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/server/NodeMgr.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/ha/BDBHA.java|8|8|100.00%|

**Review by chaoyli — APPROVED** [review]

**Review by gengjun-git — APPROVED** [review]

**Pull request merged**
