### PR TITLE
[BugFix] Fix lake table get updated partitions in materialized view

### LINKED ISSUE #19252: [StarOS] empty result set from mv after refresh mv
### Steps to reproduce the behavior (Required)
````sql
CREATE TABLE `t2` (
                    `k1` int,
                    `k2` int
                )
                DUPLICATE KEY(`k1`)
                COMMENT "OLAP"
                DISTRIBUTED BY HASH(`k1`) BUCKETS 3;
CREATE MATERIALIZED VIEW mv1
                 DISTRIBUTED BY HASH(k1) BUCKETS 10
                 REFRESH ASYNC
                 AS SELECT k1,k2 FROM t2;
INSERT INTO t2 VALUES (1,1);
````

### Expected behavior (Required)
```
mysql> select * from t2;
+------+------+
| k1   | k2   |
+------+------+
|    1 |    1 |
+------+------+
1 row in set (0.21 sec)
```

### Real behavior (Required)
```
mysql> select * from t2;
Empty set (0.01 sec)
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
mysql> select current_version();
+-------------------+
| current_version() |
+-------------------+
| UNKNOWN a69a535fa |
+-------------------+
1 row in set (0.01 sec)
```

### PR DESCRIPTION
**Pull request by wyb**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #19252

## Problem Summary(Required) ：

Lake table materialized view is almost same as local table, so use table.isNativeTable() when getting updated partitions.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 3.0
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Review by Youngwb — APPROVED** [review]

**Review by kevincai — APPROVED** [review]

**Review by sduzh — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/MaterializedView.java|1|1|100.00%|[]|

**Comment by wyb** [comment]
run starrocks_admit_test

**Comment by wyb** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Pull request merged**
