### PR TITLE
[Enhancement] Support broker load non nested array type from parquet file

### LINKED ISSUE #9136: Support broker load non nested array type from parquet file

### PR DESCRIPTION
**Pull request by meegoo**
## What type of PR is this：
- [ ] bug
- [ ] feature
- [x] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #9136

### CODE REVIEW

**Review by satanson — APPROVED** [review]

**Review by chaoyli — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by imay** [comment]
run starrocks_admit_test

**Comment by meegoo** [comment]
@mergify backport branch-2.3 brach-2.2

**Comment by meegoo** [comment]
@mergify backport branch-2.2

**Comment by meegoo** [comment]
@mergify backport branch-2.3

**Pull request merged**
