### PR TITLE
[Enhancement] Add hint to insert into error msg if thrift server pool is exhausted

### PR DESCRIPTION
**Pull request by gengjun-git**
## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

Check the thrift server pool size when waiting for the fragments to finish. If the thrift server pool size is bigger than the max thrift server worker, the timeout reason maybe the rejection of request by thrift server.

BTW, remove the unused thrift server type.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 3.0
  - [x] 2.5
  - [x] 2.4
  - [x] 2.3

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 8 / 15 (53.33%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/StmtExecutor.java|0|3|00.00%|[1451, 1452, 1458]|
|:large_blue_circle:|com/starrocks/qe/Coordinator.java|2|5|40.00%|[1582, 1583, 1820]|
|:large_blue_circle:|com/starrocks/common/ThriftServerEventProcessor.java|3|4|75.00%|[81]|
|:large_blue_circle:|com/starrocks/common/ThriftServer.java|3|3|100.00%|[]|

**Review by Astralidea — APPROVED** [review]

**Review by meegoo — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.4

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.3

**Pull request merged**
