### PR TITLE
[BugFix] Fix upper/lower struct field error

### PR DESCRIPTION
**Pull request by Seaven**
Fixes #issue

## What type of PR is this:
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

coverage check fail. please retry. :fearful:

[Please let me know](https://github.com/naver/cover-checker/issues/new) when error again.

com.naver.nid.cover.parser.coverage.exception.ParseException: java.nio.file.NoSuchFileException: /home/runner/_work/starrocks/starrocks/result

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

coverage check fail. please retry. :fearful:

[Please let me know](https://github.com/naver/cover-checker/issues/new) when error again.

com.naver.nid.cover.parser.coverage.exception.ParseException: java.nio.file.NoSuchFileException: /home/runner/_work/starrocks/starrocks/result

**Review by kangkaisen — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 13 / 14 (92.86%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/StructType.java|3|4|75.00%|[210]|
|:large_blue_circle:|com/starrocks/analysis/SubfieldExpr.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/StructField.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/ExpressionAnalyzer.java|5|5|100.00%|[]|

**Review by fzhedu — APPROVED** [review]
LGTM

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 14 / 15 (93.33%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/StructType.java|3|4|75.00%|[210]|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/scalar/SubfieldOperator.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/SubfieldExpr.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/StructField.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/ExpressionAnalyzer.java|5|5|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 14 / 15 (93.33%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/StructType.java|3|4|75.00%|[210]|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/scalar/SubfieldOperator.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/SubfieldExpr.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/StructField.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/ExpressionAnalyzer.java|5|5|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 14 / 15 (93.33%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/StructType.java|3|4|75.00%|[210]|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/scalar/SubfieldOperator.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/SubfieldExpr.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/StructField.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/ExpressionAnalyzer.java|5|5|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 14 / 15 (93.33%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/StructType.java|3|4|75.00%|[210]|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/scalar/SubfieldOperator.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/SubfieldExpr.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/StructField.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/ExpressionAnalyzer.java|5|5|100.00%|[]|

**Review by kangkaisen — DISMISSED** [review]

**Review by zombee0 — APPROVED** [review]
LGTM

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 14 / 15 (93.33%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/StructType.java|3|4|75.00%|[210]|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/scalar/SubfieldOperator.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/SubfieldExpr.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/StructField.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/ExpressionAnalyzer.java|5|5|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 14 / 16 (87.50%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/StructType.java|3|4|75.00%|[210]|
|:large_blue_circle:|com/starrocks/sql/analyzer/ExpressionAnalyzer.java|5|6|83.33%|[366]|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/scalar/SubfieldOperator.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/SubfieldExpr.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/StructField.java|2|2|100.00%|[]|

**Review by kangkaisen — APPROVED** [review]

**Review by stdpain — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Pull request merged**
