### PR TITLE
[BugFix] Disable query for external table which partition column type is float/timestamp/decimal

### LINKED ISSUE #15800: [delta lake] The float type in hive is a partition column, and the query error
### Steps to reproduce the behavior (Required)
1. hive
```
CREATE TABLE `delta_lake_hive_par_col_float` ( 
col_float             float           ,
col_smallint          smallint        ,
col_int               integer
)
USING delta PARTITIONED BY (col_float);
insert into delta_lake_hive_par_col_float values (1,1,1.1),(2,2,2.2),(3,3,3.3);
```
2. sr
```
CREATE EXTERNAL CATALOG "delta_catalog"  PROPERTIES ("type"="deltalake","hive.metastore.uris"="thrift://xxx.xx.xxx.xxx:xxxx");
use delta_catalog.delta_lake_db;
```
3. SELECT  '....'
```
select * from delta_lake_hive_par_col_float;
```

### Expected behavior (Required)
result as same as in hive query
92a9ca6b-9279-4811-9008-490bc65640fa

### Real behavior (Required)
mysql> select * from delta_lake_hive_par_col_float;
+--------------+---------+----------------+
| col_smallint | col_int | col_float      |
+--------------+---------+----------------+
|            1 |       1 | -1.5881868e-23 |
|            3 |       3 |   2.720083e+23 |
|            2 |       2 | -1.5881868e-23 |
+--------------+---------+----------------+
3 rows in set (0.88 sec)
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
mysql> select current_version();
+----------------------------+
| current_version()          |
+----------------------------+
| BRANCH-2.5-RELEASE ab2f742 |
+----------------------------+
1 row in set (0.00 sec)

### PR DESCRIPTION
**Pull request by Youngwb**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [x] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #15800   #15801  #15802

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 10 / 11 (90.91%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/PruneHDFSScanColumnRule.java|10|11|90.91%|[138]|

**Review by stephen-shelby — DISMISSED** [review]

**Review by gengjun-git — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 10 / 11 (90.91%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/PruneHDFSScanColumnRule.java|10|11|90.91%|[139]|

**Comment by Youngwb** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 10 / 12 (83.33%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/IcebergTable.java|0|1|00.00%|[149]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/PruneHDFSScanColumnRule.java|10|11|90.91%|[139]|

**Review by gengjun-git — APPROVED** [review]

**Review by stephen-shelby — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
