### PR TITLE
[BugFix] Fix primary key table may have concurrent compaction

### PR DESCRIPTION
**Pull request by sevev**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

The commit phase and apply phase of primary key table compaction is asynchronous, and we use `_compaction_running` to prevent multiple compaction tasks from being executed on the same table.

However, the `_compaction_running` will be set false after commit finish and it is possible that the tablet is selected to execute compaction again while the last compaction task has not yet finish the apply. The two compaction tasks may be concurrent and modify the `_compaction_state` at the same time which may cause unexpected error.

This is just a potential bug, not sure if it has caused the problem.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 3.0
  - [x] 2.5
  - [x] 2.4
  - [ ] 2.3

### CODE REVIEW

**Comment by sevev** [comment]
run starrocks_be_unittest

**Review by trueeyu — DISMISSED** [review]

**Review by chaoyli — DISMISSED** [review]

**Comment by sevev** [comment]
run starrocks_admit_test

**Comment by sevev** [comment]
run starrocks_admit_test

**Comment by sevev** [comment]
run all

**Comment by sevev** [comment]
run ADMIT TEST

**Comment by sevev** [comment]
@mergify rebase main

**Review by chaoyli — APPROVED** [review]

**Review by imay — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.4

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.3

**Pull request merged**
