### PR TITLE
[BugFix] Fix grant function miss check function exists bug

### LINKED ISSUE #17960: [access control]user connect SR, global_function privileges disappeared
### Steps to reproduce the behavior (Required)
step 1
con1: mysql -hxxx.xx.xx.xxx -P9232 --uroot 
```
CREATE GLOBAL FUNCTION global_func_d0de1b0c_ae6d_11ed_8960_00163e0e550b (int)
            RETURNS int
            properties
            (
                "symbol" = "Echoint",
                "type" = "StarrocksJar",
                "file" = "http://starrocks-thirdparty.xxx/starrocks-jdbc%2FEchoint.jar"
            ); ;
create user user_d0e0d734_ae6d_11ed_8960_00163e0e550b identified by '123456';
GRANT usage ON GLOBAL_FUNCTION global_func_d0de1b0c_ae6d_11ed_8960_00163e0e550b TO USER user_d0e0d734_ae6d_11ed_8960_00163e0e550b;
show grants for user_d0e0d734_ae6d_11ed_8960_00163e0e550b;
```
step 2
con2:
```
mysql -hxxx.xx.xx.xxx -P9232 -uuser_d0e0d734_ae6d_11ed_8960_00163e0e550b -p123456
```
step3
con1:
```
show grants for user_d0e0d734_ae6d_11ed_8960_00163e0e550b;
```

image

image

### Expected behavior (Required)
image

### Real behavior (Required)
image

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
mysql> select current_version();
+----------------------+
| current_version()    |
+----------------------+
| MAIN-RELEASE 32f71cf |
+----------------------+
1 row in set (0.03 sec)

### PR DESCRIPTION
**Pull request by HangyuanLiu**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #17960 #18120

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 10 / 10 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/privilege/FunctionPEntryObject.java|6|6|100.00%|[]|
|:large_blue_circle:|com/starrocks/privilege/GlobalFunctionPEntryObject.java|4|4|100.00%|[]|

**Review by gengjun-git — DISMISSED** [review]

**Comment by nshangyiming** [comment]
pr title: grant function -> global function

**Review by Astralidea — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 51 / 59 (86.44%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/PrivilegeStmtAnalyzerV2.java|13|17|76.47%|[330, 331, 332, 334]|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|25|29|86.21%|[3117, 3139, 3164, 4331]|
|:large_blue_circle:|com/starrocks/sql/ast/GrantRevokePrivilegeObjects.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/BaseGrantRevokePrivilegeStmt.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/privilege/FunctionPEntryObject.java|6|6|100.00%|[]|
|:large_blue_circle:|com/starrocks/privilege/GlobalFunctionPEntryObject.java|4|4|100.00%|[]|

**Review by nshangyiming — APPROVED** [review]

**Review by Astralidea — APPROVED** [review]

**Comment by HangyuanLiu** [comment]
@Mergifyio backport branch-3.0

**Pull request merged**
