### PR TITLE
[Refactor] Remove the namespace vectorized

### LINKED ISSUE #13805: Refactor the namespace by remove the vectorized namespace
The namespace vectorized is not used and misunderstanding. I will remove the vectorized namespace and unify the directory structure.
1.  column/field.h and column/schema.h has conflicts with the storage directory. I rename them to VectorizedField/VectorizedSchema (#13804)
2. Rename Chunk in runtime to MemChunk(https://github.com/StarRocks/starrocks/pull/13906)
3. Remove the namespace vectorized(https://github.com/StarRocks/starrocks/pull/15429)
4. Unify the directory structure by removing the vectorized directory
5. Unify the Field/VectorizedField, Schema/VectorizedSchema

### PR DESCRIPTION
**Pull request by chaoyli**
## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [x] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #13805

## Problem Summary(Required) ：

The namespace vectorized is not used. So I remove the namespace related codes.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by murphyatwork — DISMISSED** [review]

**Review by imay — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by murphyatwork — DISMISSED** [review]

**Review by imay — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by imay — DISMISSED** [review]

**Review by Astralidea — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by mofeiatwork** [comment]
run starrocks_admit_test

**Review by murphyatwork — APPROVED** [review]

**Review by imay — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by chaoyli** [comment]
run starrocks_admit_test

**Comment by chaoyli** [comment]
run starrocks_admit_test

**Comment by chaoyli** [comment]
run starrocks_admit_test

**Comment by chaoyli** [comment]
run starrocks_admit_test

**Pull request merged**
