### PR TITLE
Remove tablet directory directly if trash expire time is 0

### LINKED ISSUE #1009: Remove tablet directory directly if config::trash_file_expire_time_sec =0
`config::trash_file_expire_time_sec` is used to indicate how long a tablet directory is deleted after it is moved to the trash directory. 0 means that it should be deleted immediately after being moved to the trash directory, thereby, moving the directory is meaningless, we can delete the directory directly

### PR DESCRIPTION
**Pull request by sduzh**
Close issue #1009

### CODE REVIEW

**Comment by sduzh** [comment]
run starrocks_be_unittest

**Review by chaoyli — DISMISSED** [review]

**Comment by imay** [comment]
run starrocks_be_unittest

**Comment by wanpengfei-git** [comment]
Can't set status; build succeeded.

**Comment by sduzh** [comment]
run starrocks_be_unittest

**Review by chaoyli — APPROVED** [review]

**Review by imay — APPROVED** [review]

**Pull request merged**
