### PR TITLE
[Refactor] Remove unuse code & move path

### PR DESCRIPTION
**Pull request by Seaven**
## What type of PR is this：
- [ ] bugfix
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes 

## Problem Summary(Required) ：

For #10743

* Remove unused code
* move rewrite/physical to rule/tree and rename interface
* modify optimizer timeout compute

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
Can't set status; build succeeded.

**Review by liuyehcf — APPROVED** [review]

**Review by kangkaisen — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by HangyuanLiu — APPROVED** [review]

**Comment by Seaven** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 17 / 19 (89.47%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/task/SeriallyTaskScheduler.java|2|4|50.00%|[32, 33]|
|:large_blue_circle:|com/starrocks/sql/optimizer/Optimizer.java|6|6|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/tree/PruneAggregateNodeRule.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/tree/PruneShuffleColumnRule.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/tree/AddDecodeNodeForDictStringRule.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/OptimizerTraceInfo.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/tree/ScalarOperatorsReuseRule.java|1|1|100.00%|[]|

**Pull request merged**
