### PR TITLE
[BugFix] Make S3Filesystem thread-safe

### PR DESCRIPTION
**Pull request by sduzh**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 3.0
  - [x] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Review by chaoyli — DISMISSED** [review]

**Review by Smith-Cruise — DISMISSED** [review]

**Comment by Smith-Cruise** [comment]
Plz remember cherry-pick to branch-3.0, branch-2.5.

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by Smith-Cruise — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
