### PR TITLE
[Enhancement][WIP] Iceberg partition column as constcolumn

### PR DESCRIPTION
**Pull request by zombee0**
Fixes #issue

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [ ] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:heart_eyes: **pass** : 59 / 62 (95.16%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/runtime/descriptors.h|0|1|00.00%|[217]|
|:large_blue_circle:|src/connector/hive_connector.cpp|2|3|66.67%|[514]|
|:large_blue_circle:|src/formats/parquet/meta_helper.cpp|9|10|90.00%|[134]|
|:large_blue_circle:|src/exec/hdfs_scanner.cpp|1|1|100.00%|[]|
|:large_blue_circle:|src/formats/parquet/file_reader.cpp|44|44|100.00%|[]|
|:large_blue_circle:|src/formats/parquet/meta_helper.h|3|3|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/SessionVariable.java|2|2|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/SessionVariable.java|2|2|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:heart_eyes: **pass** : 267 / 305 (87.54%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/runtime/descriptors.h|0|1|00.00%|[217]|
|:large_blue_circle:|src/connector/hive_connector.cpp|2|3|66.67%|[514]|
|:large_blue_circle:|src/formats/parquet/file_reader.cpp|252|287|87.80%|[117, 118, 119, 233, 234, 236, 237, 240, 241, 242, 246, 247, 251, 252, 253, 283, 317, 318, 319, 321, 322, 323, 335, 362, 363, 372, 373, 374, 376, 377, 378, 382, 383, 387, 419]|
|:large_blue_circle:|src/formats/parquet/meta_helper.cpp|9|10|90.00%|[134]|
|:large_blue_circle:|src/exec/hdfs_scanner.cpp|1|1|100.00%|[]|
|:large_blue_circle:|src/formats/parquet/meta_helper.h|3|3|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/SessionVariable.java|2|2|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:heart_eyes: **pass** : 62 / 65 (95.38%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/runtime/descriptors.h|0|1|00.00%|[217]|
|:large_blue_circle:|src/connector/hive_connector.cpp|2|3|66.67%|[514]|
|:large_blue_circle:|src/formats/parquet/meta_helper.cpp|9|10|90.00%|[134]|
|:large_blue_circle:|src/exec/hdfs_scanner.cpp|1|1|100.00%|[]|
|:large_blue_circle:|src/formats/parquet/file_reader.cpp|47|47|100.00%|[]|
|:large_blue_circle:|src/formats/parquet/meta_helper.h|3|3|100.00%|[]|

**Comment by zombee0** [comment]
another implement https://github.com/StarRocks/starrocks/pull/31586

**Pull request closed without merging**
