### PR TITLE
[BugFix] Ignore update when no load data.

### LINKED ISSUE #7419: query error when update or insert into select on primary table with no data
### Steps to reproduce the behavior (Required)
```
mysql> create table pri_tbl(col1 int,col2 varchar) primary key(col1) distributed by hash(col1);
Query OK, 0 rows affected (0.32 sec)

mysql> delete from pri_tbl where col1=1;
Query OK, 0 rows affected (31.26 sec)

mysql> update pri_tbl set col2='a' where col1 = 1;
ERROR 1064 (HY000): all partitions have no load data
mysql> insert into pri_tbl select * from pri_tbl;
ERROR 1064 (HY000): all partitions have no load data
```

### Expected behavior (Required)
no error

### Real behavior (Required)
error

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
mysql> select current_version();
+-----------------------+
| current_version()     |
+-----------------------+
| 2.3.0-0617 8970dbc |
+-----------------------+
1 row in set (0.02 sec)
```

### PR DESCRIPTION
**Pull request by Linkerist**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #7419

### CODE REVIEW

**Review by Astralidea — APPROVED** [review]

**Review by decster — APPROVED** [review]

**Comment by Linkerist** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 0 / 1 (00.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/StmtExecutor.java|0|1|00.00%|

**Review by chaoyli — APPROVED** [review]

**Comment by chaoyli** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 0 / 1 (00.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/StmtExecutor.java|0|1|00.00%|

**Pull request merged**
