### PR TITLE
Disable some commands on StarOS table

### PR DESCRIPTION
**Pull request by wyb**
## What type of PR is this：
- [ ] bug
- [x] feature
- [ ] enhancement
- [ ] others

## Problem Summary(Required) ：

Disable the following commands:
1. Alter table
2. Backup and restore
3. Create materialized view
4. Delete
5. Spark load
6. Admin show tablet status
7. Admin show tablet distribution

Some of them will be supported later.

### CODE REVIEW

**Review by gengjun-git — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 25 / 34 (73.53%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/http/rest/MigrationAction.java|0|4|00.00%|
|:large_blue_circle:|com/starrocks/analysis/AbstractBackupStmt.java|0|1|00.00%|
|:large_blue_circle:|com/starrocks/catalog/MetadataViewer.java|4|8|50.00%|
|:large_blue_circle:|com/starrocks/analysis/AlterTableStmt.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/analysis/CreateMaterializedViewStmt.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/analysis/DeleteStmt.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/catalog/CatalogUtils.java|14|14|100.00%|
|:large_blue_circle:|com/starrocks/analysis/LoadStmt.java|4|4|100.00%|

**Review by wuleistarrocks — COMMENTED** [review]
It would be better to add more description about what you have disabled for staros table in commit message

**Comment by wyb** [comment]
> It would be better to add more description about what you have disabled for staros table in commit message

Already has.

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 21 / 28 (75.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/analysis/AdminShowReplicaStatusStmt.java|0|1|00.00%|
|:large_blue_circle:|com/starrocks/analysis/AdminShowReplicaDistributionStmt.java|0|1|00.00%|
|:large_blue_circle:|com/starrocks/http/rest/MigrationAction.java|0|4|00.00%|
|:large_blue_circle:|com/starrocks/analysis/AbstractBackupStmt.java|0|1|00.00%|
|:large_blue_circle:|com/starrocks/analysis/AlterTableStmt.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/analysis/CreateMaterializedViewStmt.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/analysis/DeleteStmt.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/catalog/CatalogUtils.java|14|14|100.00%|
|:large_blue_circle:|com/starrocks/analysis/LoadStmt.java|4|4|100.00%|

**Comment by wyb** [comment]
run starrocks_fe_unittest

**Comment by wyb** [comment]
run starrocks_fe_unittest

**Comment by wyb** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 21 / 24 (87.50%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/analysis/AdminShowReplicaStatusStmt.java|0|1|00.00%|
|:large_blue_circle:|com/starrocks/analysis/AdminShowReplicaDistributionStmt.java|0|1|00.00%|
|:large_blue_circle:|com/starrocks/analysis/AbstractBackupStmt.java|0|1|00.00%|
|:large_blue_circle:|com/starrocks/analysis/AlterTableStmt.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/analysis/CreateMaterializedViewStmt.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/analysis/DeleteStmt.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/catalog/CatalogUtils.java|14|14|100.00%|
|:large_blue_circle:|com/starrocks/analysis/LoadStmt.java|4|4|100.00%|

**Review by gengjun-git — APPROVED** [review]

**Review by sduzh — APPROVED** [review]

**Pull request merged**
