### PR TITLE
[BugFix] array_filter[nullable_col, null] results' null col is not set

### PR DESCRIPTION
**Pull request by fzhedu**
Signed-off-by: fzhedu <fzhedu@gmail.com>

## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

array_filter[nullable_col, null] results' null col is not set, and it causes crash.

before
```
crash
```
after
```
mysql> select c5, array_filter(c5,null) from array_sort_null;
+---------------------------+------------------------+
| c5                        | array_filter(c5, NULL) |
+---------------------------+------------------------+
| ["222feds","中文",null]   | []                     |
+---------------------------+------------------------+
1 row in set (0.02 sec)
```
## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Review by murphyatwork — DISMISSED** [review]

**Comment by fzhedu** [comment]
run starrocks_be_unittest

**Comment by fzhedu** [comment]
run starrocks_clang-format

**Review by murphyatwork — APPROVED** [review]

**Review by stdpain — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by kangkaisen — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
