### PR TITLE
[Enhancement] make all now(), current_timestamp(), localtime(), localtimestamp(), utc_timestamp() functions microsecond-aware 

### LINKED ISSUE #17499: make all DATETIME-related functions microsecond-aware
## Feature request

here is a checklist from `gensrc/script/functions.py`

- [ ] least
- [ ] greatest
- [ ] year
- [ ] year
- [ ] month
- [ ] month
- [ ] quarter
- [ ] dayofweek
- [ ] to_date
- [ ] date
- [ ] day
- [ ] dayofmonth
- [ ] dayofmonth
- [ ] day
- [ ] dayofyear
- [ ] weekofyear
- [ ] week
- [ ] week
- [ ] hour
- [ ] hour
- [ ] minute
- [ ] minute
- [ ] second
- [ ] second
- [ ] years_add
- [ ] years_sub
- [ ] months_add
- [ ] months_sub
- [ ] add_months
- [ ] weeks_add
- [ ] weeks_sub
- [ ] days_add
- [ ] days_sub
- [ ] date_add
- [ ] date_sub
- [ ] adddate
- [ ] subdate
- [ ] hours_add
- [ ] hours_sub
- [ ] minutes_add
- [ ] minutes_sub
- [ ] seconds_add
- [ ] seconds_sub
- [ ] microseconds_add
- [ ] microseconds_sub
- [ ] years_diff
- [ ] months_diff
- [ ] weeks_diff
- [ ] days_diff
- [ ] hours_diff
- [ ] minutes_diff
- [ ] seconds_diff
- [ ] datediff
- [ ] timediff
- [ ] now
- [ ] current_timestamp
- [ ] localtime
- [ ] localtimestamp
- [ ] str_to_date
- [ ] date_format
- [ ] unix_timestamp
- [ ] dayname
- [ ] monthname
- [ ] convert_tz
- [ ] utc_timestamp
- [ ] date_trunc
- [ ] timestamp
- [ ] time_slice
- [ ] time_slice
- [ ] if
- [ ] ifnull
- [ ] nullif
- [ ] coalesce
- [ ] array_avg
- [ ] array_min
- [ ] array_max
- [ ] array_distinct
- [ ] array_sort
- [ ] reverse
- [ ] array_slice
- [ ] array_concat
- [ ] arrays_overlap
- [ ] array_intersect
- [ ] array_slice
- [ ] array_sortby
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by ghost**
Fixes #17499

## What type of PR is this:
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [x] I have added test cases for my bug fix or my new feature
- [x] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4

### CODE REVIEW

**Comment by LiShuMing** [comment]
You may fix the errors in the CI.

Add some sql tests in `test/sql`?

**Comment by SilvaXiang** [comment]
> You may fix the errors in the CI.
> 
> Add some sql tests in `test/sql`?

Ok, I will fix them in the free time.

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rewrite/ScalarOperatorFunctions.java|2|2|100.00%|[]|

**Comment by SilvaXiang** [comment]
Hi, I have pass all the CI testing, please review.
My patch is making now(), current_timestamp(), localtime(), localtimestamp(), utc_timestamp microsecond-aware.

**Comment by SilvaXiang** [comment]
Hi, I have pass all the CI testing, please review.
My patch is making now(), current_timestamp(), localtime(), localtimestamp(), utc_timestamp microsecond-aware.
@LiShuMing

**Comment by silverbullet233** [comment]
@SilvaXiang Hi, I saw DCO and license/cla are not passed in CI, plz fix it.
for DCO, you can click details link and get what need to do.
for CLA, you can see the above comment of CLAassistant

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rewrite/ScalarOperatorFunctions.java|2|2|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rewrite/ScalarOperatorFunctions.java|2|2|100.00%|[]|

**Comment by silverbullet233** [comment]
> [CLA assistant check](https://cla-assistant.io/StarRocks/starrocks?pullRequest=25021) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/StarRocks/starrocks?pullRequest=25021) before we can accept your contribution.**3** out of **4** committers have signed the CLA.✅ LiShuMing✅ packy92✅ kangkaisen❌ SilvaXiangYou have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/StarRocks/starrocks?pullRequest=25021) it.

@SilvaXiang hi, could you sign our CLA? I saw this check not passed in CI.

**Comment by SilvaXiang** [comment]
> > [CLA assistant check](https://cla-assistant.io/StarRocks/starrocks?pullRequest=25021) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/StarRocks/starrocks?pullRequest=25021) before we can accept your contribution.**3** out of **4** committers have signed the CLA.✅ LiShuMing✅ packy92✅ kangkaisen❌ SilvaXiangYou have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/StarRocks/starrocks?pullRequest=25021) it.
> 
> @SilvaXiang hi, could you sign our CLA? I saw this check not passed in CI.

OK

**Review by silverbullet233 — APPROVED** [review]

**Review by kangkaisen — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Pull request merged**
