### PR TITLE
[Enhancement] s3 sdk support path-style-access

### PR DESCRIPTION
**Pull request by dirtysalt**
## What type of PR is this：
- [ ] bug
- [ ] feature
- [x] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

This PR is to support access s3-compatible object storage in path style.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Review by caneGuy — APPROVED** [review]

**Review by Youngwb — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by DorianZheng** [comment]
https://docs.aws.amazon.com/zh_cn/AmazonS3/latest/userguide/VirtualHosting.html

**Review by DorianZheng — APPROVED** [review]
LGTM

**Comment by dirtysalt** [comment]
@MergifyIO backport branch-2.3

**Comment by dirtysalt** [comment]
@MergifyIO backport branch-2.4

**Pull request merged**
