### PR TITLE
[UT] Add avro parsing unit tests

### PR DESCRIPTION
**Pull request by zaorangyang**
## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [x] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 3.0
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Review by chaoyli — DISMISSED** [review]

**Comment by zaorangyang** [comment]
run starrocks_be_unittest

**Comment by zaorangyang** [comment]
run starrocks_be_unittest

**Comment by zaorangyang** [comment]
run starrocks_be_unittest

**Comment by zaorangyang** [comment]
run starrocks_be_unittest

**Review by chaoyli — APPROVED** [review]

**Review by imay — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by zaorangyang** [comment]
@Mergifyio backport branch-3.0

**Pull request merged**
