### PR TITLE
[BugFix] Fix analyze error of if expr whose first argument is decimal

### PR DESCRIPTION
**Pull request by satanson**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #
https://github.com/StarRocks/starrocks/issues/21363
## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 3.0
  - [x] 2.5
  - [x] 2.4
  - [x] 2.3

### CODE REVIEW

**Review by Seaven — DISMISSED** [review]

**Review by packy92 — DISMISSED** [review]

**Review by liuyehcf — DISMISSED** [review]

**Review by fzhedu — COMMENTED** [review]
does other condition expressions have similar problems? such as case... when, if null, COALESCE ...

**Review by liuyehcf — APPROVED** [review]

**Review by Seaven — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.3

**Comment by satanson** [comment]
https://github.com/Mergifyio backport branch-3.0

**Pull request merged**
