### PR TITLE
[SR SQL Planner Summer Camp] Support show index in new parser

### PR DESCRIPTION
**Pull request by xlwh**
## What type of PR is this：
- [ ] bug
- [x] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #7938

### CODE REVIEW

**Comment by xlwh** [comment]
run starrocks_fe_unittest

**Comment by xlwh** [comment]
run starrocks_fe_unittest

**Comment by xlwh** [comment]
run starrocks_fe_unittest

**Comment by xlwh** [comment]
run starrocks_fe_unittest

**Comment by xlwh** [comment]
run starrocks_fe_unittest

**Comment by xlwh** [comment]
run starrocks_fe_unittest

**Comment by xlwh** [comment]
run starrocks_fe_unittest

**Comment by xlwh** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 20 / 23 (86.96%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/analysis/ShowIndexStmt.java|3|5|60.00%|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|5|6|83.33%|
|:large_blue_circle:|com/starrocks/sql/ast/AstVisitor.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/sql/analyzer/ShowStmtAnalyzer.java|7|7|100.00%|
|:large_blue_circle:|com/starrocks/sql/analyzer/PrivilegeChecker.java|4|4|100.00%|

**Review by imay — APPROVED** [review]

**Pull request merged**
