### PR TITLE
[Enhancement] Automatically create partitions to optimize the use of batch interfaces

### PR DESCRIPTION
**Pull request by Astralidea**
Fixes #issue

Opt create 1000 partition from 70s -> 15s in my env.

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.2
  - [x] 3.1
  - [x] 3.0
  - [ ] 2.5

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:disappointed: **fail** : 38 / 76 (50.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/ast/ListPartitionDesc.java|0|6|00.00%|[77, 78, 79, 81, 82, 84]|
|:large_blue_circle:|com/starrocks/load/InsertOverwriteJobRunner.java|0|7|00.00%|[244, 254, 255, 256, 257, 258, 259]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AnalyzerUtils.java|11|22|50.00%|[961, 962, 973, 974, 975, 976, 977, 978, 981, 982, 983]|
|:large_blue_circle:|com/starrocks/service/FrontendServiceImpl.java|9|17|52.94%|[2228, 2229, 2246, 2247, 2248, 2249, 2250, 2251]|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|18|24|75.00%|[885, 886, 887, 1259, 1269, 1270]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 71 / 84 (84.52%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/service/FrontendServiceImpl.java|11|17|64.71%|[2246, 2247, 2248, 2249, 2250, 2251]|
|:large_blue_circle:|com/starrocks/load/InsertOverwriteJobRunner.java|11|15|73.33%|[258, 259, 260, 269]|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|21|24|87.50%|[1259, 1269, 1270]|
|:large_blue_circle:|com/starrocks/sql/ast/ListPartitionDesc.java|6|6|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AnalyzerUtils.java|22|22|100.00%|[]|

**Review by gengjun-git — APPROVED** [review]

**Review by stephen-shelby — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.2

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Pull request merged**
