### PR TITLE
[BugFix] fix stuck issue when some agg operator has no data to process under auto spill mode

### LINKED ISSUE #23491: [spill] hang when insert into select
### Steps to reproduce the behavior (Required)
````sql
set enable_spill=true;
set spill_mode='auto';
CREATE TABLE t1 (
    k1 INT,
    k2 VARCHAR(20))
DUPLICATE KEY(k1)
DISTRIBUTED BY HASH(k1);
CREATE TABLE t2 (
    k1 INT,
    k2 VARCHAR(20))
DUPLICATE KEY(k1)
DISTRIBUTED BY HASH(k1);
insert into t1 values (1,"1");
insert into t2 select sum(k1),k2 from t1 group by k2;
````

### Expected behavior (Required)
`query ok`
### Real behavior (Required)
`ERROR 1064 (HY000): Query timeout. Increase the query_timeout session variable and retry`
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
`BRANCH-3.0-RELEASE-1e3d950`

### PR DESCRIPTION
**Pull request by silverbullet233**
## Problem Summary:
Fixes #23491 

under auto spill mode, if some agg blocking sink operator has no data to spill, its _spill_strategy will always be NO_SPILL, we should make sure SpillProcessChannel::set_finishing is invoked so that spill_process operator can finish.

## What type of PR is this:
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 3.0
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Review by stdpain — DISMISSED** [review]

**Review by fzhedu — COMMENTED** [review]
what about distinct agg?

**Review by fzhedu — COMMENTED** [review]
what about distinct agg?

**Comment by kangkaisen** [comment]
Please add test cases

**Comment by silverbullet233** [comment]
> what about distinct agg?

@fzhedu  I have confirmed that distinct agg does not have a similar problem, because it does not clearly distinguish between  NO_SPILL and SPILL_ALL mode in the set_finishing phase, so SpillProcessChannel::set_finishing will always be invoked

**Comment by silverbullet233** [comment]
> Please add test cases

done

**Review by stdpain — APPROVED** [review]

**Review by kangkaisen — APPROVED** [review]

**Review by fzhedu — APPROVED** [review]
LGTM

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Pull request merged**
