### PR TITLE
[Tool] test

### PR DESCRIPTION
**Pull request by andyziye**
Fixes #issue

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [x] Yes, this PR will result in a change in behavior.
- [ ] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [ ] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Comment by andyziye** [comment]
#### [BE Incremental Coverage Report]

coverage check fail. please retry. :fearful:

[Please let me know](https://github.com/naver/cover-checker/issues/new) when error again.

com.naver.nid.cover.parser.coverage.exception.ParseException: org.xml.sax.SAXParseException; systemId: file:/Users/yezi/Desktop/empty_cov_result/; lineNumber: 1; columnNumber: 1; 前言中不允许有内容。

**Comment by andyziye** [comment]
#### [BE Incremental Coverage Report]


:white_check_mark: **pass** : 0 / 0 (0%)

**Comment by andyziye** [comment]
#### [BE Incremental Coverage Report]


:white_check_mark: **pass** : 0 / 0 (0%)

**Comment by andyziye** [comment]
#### [BE Incremental Coverage Report]


:white_check_mark: **pass** : 0 / 0 (0%)

**Comment by andyziye** [comment]
#### [BE Incremental Coverage Report]


:white_check_mark: **pass** : 0 / 0 (0%)

**Comment by andyziye** [comment]
#### [BE Incremental Coverage Report]


:white_check_mark: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
PR was manually closed

**Pull request closed without merging**
