### PR TITLE
rename run-ut.sh to run-be-ut.sh for it is ambiguous (#359)

### PR DESCRIPTION
**Pull request by DeepThinker666**
rename run-ut.sh to run-be-ut.sh for it is ambiguous. In fact, run-ut.sh is to run UTs of BE.

### CODE REVIEW

**Comment by imay** [comment]
starrocks_be_unittest should be changed to adjust this CL.

**Comment by DeepThinker666** [comment]
@imay you mean starrocks_test should be renamed to starrocks_be_test?

**Comment by sduzh** [comment]
> @imay you mean starrocks_test should be renamed to starrocks_be_test?

You need to make the Jenkins job `starrocks_be_unittest` run your new script `run-be-ut.sh` instead of `run-ut.sh`

**Comment by DeepThinker666** [comment]
@sduzh how can I change the configuration of Jenkins job?

**Comment by sduzh** [comment]
> @sduzh how can I change the configuration of Jenkins job?

PTAL @wanpengfei-git

**Review by chaoyli — DISMISSED** [review]

**Comment by dirtysalt** [comment]
@DeepThinker666 Do you think it's okay to close it?

**Pull request closed without merging**
