### PR TITLE
[Feature] Implement HiveMetastore

### PR DESCRIPTION
**Pull request by stephen-shelby**
## What type of PR is this：
- [ ] BugFix
- [x] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #
https://github.com/StarRocks/starrocks/issues/11349

## Problem Summary(Required) ：

- HiveMetastore implement IHiveMetastore interface, it mainly to use hive meta client to access hive metastore.
- HiveMetastoreApiConverter is mainly to convert org.apache.hadoop.hive.metastore.api.x object to StarRocks object.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 0 / 258 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/external/hive/HiveMetastore.java|0|66|00.00%|[26, 27, 28, 29, 33, 37, 42, 43, 47, 48, 52, 57, 58, 59, 60, 61, 62, 63, 66, 70, 71, 73, 74, 76, 77, 79, 81, 82, 83, 84, 85, 86, 91, 92, 93, 94, 95, 98, 99, 100, 101, 102, 103, 104, 108, 109, 110, 111, 112, 113, 115, 116, 118, 119, 121, 122, 123, 125, 126, 128, 129, 130, 131, 132, 133, 135]|
|:large_blue_circle:|com/starrocks/catalog/HudiTable.java|0|1|00.00%|[185]|
|:large_blue_circle:|com/starrocks/catalog/HiveTable.java|0|1|00.00%|[161]|
|:large_blue_circle:|com/starrocks/server/CatalogMgr.java|0|1|00.00%|[63]|
|:large_blue_circle:|com/starrocks/external/hive/Partition.java|0|14|00.00%|[73, 83, 84, 87, 88, 92, 93, 97, 98, 102, 103, 107, 108, 112]|
|:large_blue_circle:|com/starrocks/external/hive/Utils.java|0|14|00.00%|[70, 71, 73, 74, 76, 77, 78, 79, 81, 82, 84, 85, 86, 87]|
|:large_blue_circle:|com/starrocks/external/ColumnTypeConverter.java|0|83|00.00%|[18, 25, 28, 30, 32, 33, 35, 36, 39, 40, 42, 43, 45, 46, 49, 50, 53, 54, 56, 57, 59, 60, 62, 64, 66, 68, 69, 71, 72, 73, 76, 80, 81, 83, 84, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 106, 107, 109, 111, 116, 118, 119, 120, 121, 123, 128, 129, 130, 132, 137, 138, 140, 142, 143, 144, 146, 149, 151, 156, 157, 162, 163, 164, 166, 171, 172, 173, 175]|
|:large_blue_circle:|com/starrocks/external/hive/HiveMetastoreApiConverter.java|0|78|00.00%|[32, 34, 37, 38, 40, 44, 45, 48, 49, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 71, 72, 73, 74, 75, 76, 77, 79, 83, 84, 88, 89, 90, 91, 92, 93, 94, 95, 99, 100, 101, 102, 106, 107, 110, 123, 124, 126, 129, 130, 131, 133, 137, 138, 139, 145, 146, 147, 148, 149, 150, 156, 158, 162, 163, 164, 168, 169, 172, 173, 174, 178, 179, 182]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 0 / 258 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/external/hive/HiveMetastore.java|0|66|00.00%|[26, 27, 28, 29, 33, 37, 42, 43, 47, 48, 52, 57, 58, 59, 60, 61, 62, 63, 66, 70, 71, 73, 74, 76, 77, 79, 81, 82, 83, 84, 85, 86, 90, 91, 92, 93, 94, 97, 98, 99, 100, 101, 102, 103, 107, 108, 109, 110, 111, 112, 114, 115, 117, 118, 120, 121, 122, 124, 125, 127, 128, 129, 130, 131, 132, 134]|
|:large_blue_circle:|com/starrocks/catalog/HudiTable.java|0|1|00.00%|[185]|
|:large_blue_circle:|com/starrocks/catalog/HiveTable.java|0|1|00.00%|[161]|
|:large_blue_circle:|com/starrocks/server/CatalogMgr.java|0|1|00.00%|[63]|
|:large_blue_circle:|com/starrocks/external/hive/Partition.java|0|14|00.00%|[73, 83, 84, 87, 88, 92, 93, 97, 98, 102, 103, 107, 108, 112]|
|:large_blue_circle:|com/starrocks/external/hive/Utils.java|0|14|00.00%|[70, 71, 73, 74, 76, 77, 78, 79, 81, 82, 84, 85, 86, 87]|
|:large_blue_circle:|com/starrocks/external/ColumnTypeConverter.java|0|83|00.00%|[18, 25, 28, 30, 32, 33, 35, 36, 39, 40, 42, 43, 45, 46, 49, 50, 53, 54, 56, 57, 59, 60, 62, 64, 66, 68, 69, 71, 72, 73, 76, 80, 81, 83, 84, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 106, 107, 109, 111, 116, 118, 119, 120, 121, 123, 128, 129, 130, 132, 137, 138, 140, 142, 143, 144, 146, 149, 151, 156, 157, 162, 163, 164, 166, 171, 172, 173, 175]|
|:large_blue_circle:|com/starrocks/external/hive/HiveMetastoreApiConverter.java|0|78|00.00%|[32, 34, 37, 38, 40, 44, 45, 48, 49, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 71, 72, 73, 74, 75, 76, 77, 79, 83, 84, 88, 89, 90, 91, 92, 93, 94, 95, 99, 100, 101, 102, 106, 107, 110, 123, 124, 126, 129, 130, 131, 133, 137, 138, 139, 145, 146, 147, 148, 149, 150, 156, 158, 162, 163, 164, 168, 169, 172, 173, 174, 178, 179, 182]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 261 / 339 (76.99%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/external/hive/HiveMetastore.java|34|68|50.00%|[94, 95, 96, 97, 98, 101, 102, 103, 104, 105, 106, 107, 111, 112, 113, 114, 115, 116, 118, 119, 121, 122, 124, 125, 126, 128, 129, 131, 132, 133, 134, 135, 136, 138]|
|:large_blue_circle:|com/starrocks/external/hive/HiveMetastoreApiConverter.java|50|78|64.10%|[32, 38, 45, 49, 107, 124, 137, 138, 139, 145, 146, 147, 148, 149, 150, 156, 158, 162, 163, 164, 168, 169, 172, 173, 174, 178, 179, 182]|
|:large_blue_circle:|com/starrocks/external/hive/HiveMetaClient.java|2|3|66.67%|[180]|
|:large_blue_circle:|com/starrocks/catalog/HiveTable.java|5|6|83.33%|[308]|
|:large_blue_circle:|com/starrocks/external/Utils.java|61|68|89.71%|[25, 45, 77, 88, 135, 145, 148]|
|:large_blue_circle:|com/starrocks/external/ColumnTypeConverter.java|87|94|92.55%|[20, 83, 133, 168, 172, 188, 197]|
|:large_blue_circle:|com/starrocks/external/hive/HiveColumnStats.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/HudiTable.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/server/CatalogMgr.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/external/hive/Partition.java|14|14|100.00%|[]|
|:large_blue_circle:|com/starrocks/external/HiveMetaStoreTableUtils.java|5|5|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 312 / 356 (87.64%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/external/hive/HiveColumnStatistics.java|0|9|00.00%|[211, 212, 213, 214, 215, 216, 217, 218, 219]|
|:large_blue_circle:|com/starrocks/external/hive/Partition.java|14|22|63.64%|[74, 75, 76, 77, 78, 79, 80, 81]|
|:large_blue_circle:|com/starrocks/external/hive/HiveMetaClient.java|2|3|66.67%|[180]|
|:large_blue_circle:|com/starrocks/catalog/HiveTable.java|5|6|83.33%|[308]|
|:large_blue_circle:|com/starrocks/external/hive/HiveMetastoreApiConverter.java|68|78|87.18%|[32, 38, 45, 49, 107, 124, 169, 174, 179, 182]|
|:large_blue_circle:|com/starrocks/external/Utils.java|61|68|89.71%|[25, 45, 77, 88, 135, 145, 148]|
|:large_blue_circle:|com/starrocks/external/ColumnTypeConverter.java|87|94|92.55%|[20, 83, 133, 168, 172, 188, 197]|
|:large_blue_circle:|com/starrocks/external/hive/HiveMetastore.java|67|68|98.53%|[98]|
|:large_blue_circle:|com/starrocks/external/hive/HiveColumnStats.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/HudiTable.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/server/CatalogMgr.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/external/HiveMetaStoreTableUtils.java|5|5|100.00%|[]|

**Review by caneGuy — APPROVED** [review]

**Pull request merged**
