### PR TITLE
[Enhancement] profile merge mechanism enhancement

### PR DESCRIPTION
**Pull request by liuyehcf**
## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Enhancement

1. Counter add merge strategy, including CounterAggregateType and CounterMergeType
    * CounterAggregateType can be `AVG` and `SUM`. By default, time counter use `AVG`, non-time counter use `SUM`
    * CounterMergeType can be `MERGE_ALL`、`SKIP_ALL`、`SKIP_FIRST_MERGE`、`SKIP_SECOND_MERGE`. Default value is `MERGE_ALL` which means merging operation happens both in be and fe. If `SKIP_FIRST_MERGE` is choosed, the merge processing at be side is skipped while at fe side is still onging. If `SKIP_SECOND_MERGE` is choosed, things are just opposite of `SKIP_FIRST_MERGE`
3. Change ExecutionTotalTime to OperatorCumulativeTime
4. Add ExecutionWallTime

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Comment by liuyehcf** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 32 / 52 (61.54%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/Coordinator.java|0|15|00.00%|[1558, 1593, 1601, 1602, 1608, 1609, 1610, 1611, 1612, 1613, 1623, 1627, 1632, 1637, 1638]|
|:large_blue_circle:|com/starrocks/common/util/RuntimeProfile.java|15|19|78.95%|[216, 294, 296, 651]|
|:large_blue_circle:|com/starrocks/common/util/Counter.java|17|18|94.44%|[68]|

**Review by ZiheLiu — APPROVED** [review]

**Comment by liuyehcf** [comment]
run all

**Comment by liuyehcf** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 32 / 52 (61.54%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/Coordinator.java|0|15|00.00%|[1558, 1593, 1601, 1602, 1608, 1609, 1610, 1611, 1612, 1613, 1623, 1627, 1632, 1637, 1638]|
|:large_blue_circle:|com/starrocks/common/util/RuntimeProfile.java|15|19|78.95%|[216, 294, 296, 651]|
|:large_blue_circle:|com/starrocks/common/util/Counter.java|17|18|94.44%|[68]|

**Review by satanson — APPROVED** [review]

**Pull request merged**
