### PR TITLE
[Feature] Support compact rocksdb meta action

### PR DESCRIPTION
**Pull request by caneGuy**
## What type of PR is this：
- [ ] bug
- [x] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

Support compact rocksdb meta use http api
## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by caneGuy** [comment]
run starrocks_be_build

**Comment by caneGuy** [comment]
run starrocks_be_unittest

**Review by chaoyli — DISMISSED** [review]

**Comment by chaoyli** [comment]
```
12:58:27 /root/starrocks/be/src/http/action/compact_rocksdb_meta_action.cpp: In member function 'void starrocks::CompactRocksDbMetaAction::_compact(starrocks::HttpRequest*)':
12:58:27 /root/starrocks/be/src/http/action/compact_rocksdb_meta_action.cpp:24:16: error: 'class starrocks::ExecEnv' has no member named 'storage_engine'; did you mean 'starrocks::StorageEngine* starrocks::ExecEnv::_storage_engine'? (not accessible from this context)
12:58:27    24 |     _exec_env->storage_engine()->do_manual_compact(true);
12:58:27       |                ^~~~~~~~~~~~~~
12:58:27 In file included from /root/starrocks/be/src/storage/page_cache.h:30,
12:58:27                  from /root/starrocks/be/src/storage/rowset/page_handle.h:25,
12:58:27                  from /root/starrocks/be/src/storage/rowset/segment.h:34,
12:58:27                  from /root/starrocks/be/src/storage/rowset/rowset.h:37,
12:58:27                  from /root/starrocks/be/src/storage/tablet_meta.h:36,
12:58:27                  from /root/starrocks/be/src/storage/base_tablet.h:27,
12:58:27                  from /root/starrocks/be/src/storage/tablet.h:37,
12:58:27                  from /root/starrocks/be/src/storage/storage_engine.h:50,
12:58:27                  from /root/starrocks/be/src/http/action/compact_rocksdb_meta_action.cpp:10:
12:58:27 /root/starrocks/be/src/runtime/exec_env.h:267:20: note: declared private here
12:58:27   267 |     StorageEngine* _storage_engine = nullptr;
12:58:27       |                    ^~~~~~~~~~~~~~~
12:58:27 make[2]: *** [src/http/CMakeFiles/Webserver.dir/action/compact_rocksdb_meta_action.cpp.o] Error 1
12:58:27 make[1]: *** [src/http/CMakeFiles/Webserver.dir/all] Error 2
```
The compilation fail.

**Comment by caneGuy** [comment]
run starrocks_be_build

**Comment by caneGuy** [comment]
run starrocks_admit_test

**Comment by caneGuy** [comment]
cc @chaoyli PTAL thanks

**Review by chaoyli — APPROVED** [review]

**Review by dirtysalt — APPROVED** [review]

**Review by dirtysalt — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Pull request merged**
