### PR TITLE
[Enhancement] support config too_many_version sleep time on statistic…

### PR DESCRIPTION
**Pull request by Seaven**
…s collect

## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 3.0
  - [x] 2.5
  - [x] 2.4
  - [ ] 2.3

### CODE REVIEW

**Comment by Seaven** [comment]
@mergify backport branch-3.0 branch-2.5 branch-2.4

**Review by packy92 — APPROVED** [review]

**Review by kangkaisen — APPROVED** [review]

**Review by stdpain — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.4

**Comment by Seaven** [comment]
https://github.com/Mergifyio backport branch-3.0

**Comment by Seaven** [comment]
https://github.com/Mergifyio backport branch-3.0

**Pull request merged**
