### PR TITLE
[Feature] add routine load executor

### LINKED ISSUE #11779: Refactor routine load executor for pipeline routine load

### PR DESCRIPTION
**Pull request by xiaoyong-z**
## What type of PR is this：
- [ ] BugFix
- [x] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #11779

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by rickif** [comment]
run starrocks_admit_test

**Review by chaoyli — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by xiaoyong-z** [comment]
run starrocks_admit_test

**Review by chaoyli — APPROVED** [review]

**Pull request closed without merging**
