### PR TITLE
[Feature] Create history partitions automatically when start is specified for dynamic partition

### PR DESCRIPTION
**Pull request by ucasfl**
## What type of PR is this：
- [ ] bug
- [x] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

```sql
CREATE TABLE test
(
    `day_` DATE,
    `hour_` DATETIME,
    `minute_` DATETIME,
    `second_` DATETIME, 
    `timestamp_` INT,
    `nickname` VARCHAR(65533)
)ENGINE=OLAP
PRIMARY KEY(`day_`)
PARTITION BY RANGE(`day_`)()
DISTRIBUTED BY HASH(`day_`) BUCKETS 128 
PROPERTIES (
"replication_num" = "2",
"dynamic_partition.enable" = "true",
"dynamic_partition.time_unit" = "Day",
"dynamic_partition.time_zone" = "Asia/Shanghai",
"dynamic_partition.start" = "-7",
"dynamic_partition.end" = "3",
"dynamic_partition.prefix" = "p",
"dynamic_partition.buckets" = "128",
"dynamic_partition.create_history_partition" = "true",
"dynamic_partition.history_partition_num" = "7",
"in_memory" = "false",
"storage_format" = "DEFAULT"
);
```
When create table, we can use properties of `dynamic_partition.create_history_partition` and `dynamic_partition.history_partition_num` to create history partitions automatically.

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 75 / 98 (76.53%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/clone/DynamicPartitionScheduler.java|8|11|72.73%|[146, 147, 149]|
|:large_blue_circle:|com/starrocks/common/util/DynamicPartitionUtil.java|55|75|73.33%|[92, 108, 136, 144, 152, 155, 156, 236, 237, 238, 239, 240, 353, 355, 356, 357, 359, 360, 363, 367]|
|:large_blue_circle:|com/starrocks/common/Config.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/DynamicPartitionProperty.java|9|9|100.00%|[]|
|:large_blue_circle:|com/starrocks/common/ErrorCode.java|2|2|100.00%|[]|

**Comment by imay** [comment]
@ucasfl Thanks for you contribution. 
I have some advises. 
1. I think only one property is enough. for your case, "history_partitions_count" is enough.
2. How about give a start time other than a history_partitions_count? and it will be an absolute time not a relative time. Saying that you execute the same SQL but get different result at different time. 
4. you should add some unit test for this feature.
5. you should care about "dynamic_partition.start" and "dynamic_partition.history_partition_num", seems that in your example you configure is unnecessary. we can let starrocks create history partition if "start" is not 0.

**Comment by ucasfl** [comment]
> 4. you should care about "dynamic_partition.start" and "dynamic_partition.history_partition_num", seems that in your example you configure is unnecessary. we can let starrocks create history partition if "start" is not 0.

No, it's necessary. When create table, it will create partition from `current_day` to `current_day + end`, but never create history partition, `start` is not 0 just means it will keep `-start` partitions later, but can not create history partitions.

**Comment by ucasfl** [comment]
> @ucasfl Thanks for you contribution. I have some advises.
> 
> 1. I think only one property is enough. for your case, "history_partitions_count" is enough.
> 2. How about give a start time other than a history_partitions_count? and it will be an absolute time not a relative time. Saying that you execute the same SQL but get different result at different time.

Yes, one property is enough. For our usage, history_partitions_count is more convenient, usually, user need to store `x` days data, so when create data load task, just need to specify `start= -x`, `history_partition_count=x`. If give a start time, user may need to calculate the start time manually.

**Comment by ucasfl** [comment]
I also think it's better to keep both of the properties. 
https://github.com/StarRocks/starrocks/pull/9501/files#diff-f7ad8478f464a125f645519b7a1c83f8e5526706d3f5aa93c61e9d224ff19f29R145-R153

Such that, if we just specify `create_history_partiton = true` but do not specify `history_partition_num`, it will create partions from `current_day - (-start) day` to `current_day`, if specify `history_partition_num`, will create history partitions as user wanted.

**Comment by imay** [comment]
> I also think it's better to keep both of the properties. https://github.com/StarRocks/starrocks/pull/9501/files#diff-f7ad8478f464a125f645519b7a1c83f8e5526706d3f5aa93c61e9d224ff19f29R145-R153
> 
> Such that, if we just specify `create_history_partiton = true` but do not specify `history_partition_num`, it will create partions from `current_day - (-start) day` to `current_day`, if specify `history_partition_num`, will create history partitions as user wanted.

Good suggestion.
One more question do you know when the start is not set explicitly what its default value? If it is a very large number I don't think it is a good idea to create all partition when create_history_partition is true.

So IMO if start is not set explicitly, we don't create any history partition even create_history_partition is set.

**Comment by ucasfl** [comment]
> > I also think it's better to keep both of the properties. https://github.com/StarRocks/starrocks/pull/9501/files#diff-f7ad8478f464a125f645519b7a1c83f8e5526706d3f5aa93c61e9d224ff19f29R145-R153
> > Such that, if we just specify `create_history_partiton = true` but do not specify `history_partition_num`, it will create partions from `current_day - (-start) day` to `current_day`, if specify `history_partition_num`, will create history partitions as user wanted.
> 
> Good suggestion. One more question do you know when the start is not set explicitly what its default value? If it is a very large number I don't think it is a good idea to create all partition when create_history_partition is true.
> 
> So IMO if start is not set explicitly, we don't create any history partition even create_history_partition is set.

The default value of start is Integer.MIN_VALUE, if start is not set but create_history_partition is true, it will throw exception:

https://github.com/StarRocks/starrocks/pull/9501/files#diff-5bd59051ca81fc45dad09a9e3ebd97318b9dd5a03f1056a9e9a8b2fd01323aa8R358-R364

**Comment by imay** [comment]
> The default value of start is Integer.MIN_VALUE, if start is not set but create_history_partition is true, it will throw exception:
> 
> https://github.com/StarRocks/starrocks/pull/9501/files#diff-5bd59051ca81fc45dad09a9e3ebd97318b9dd5a03f1056a9e9a8b2fd01323aa8R358-R364

If so, how about creating history partition automatically when start is set and not create history partition if start is not set? Then no new property is needed.

**Comment by ucasfl** [comment]
> > The default value of start is Integer.MIN_VALUE, if start is not set but create_history_partition is true, it will throw exception:
> > https://github.com/StarRocks/starrocks/pull/9501/files#diff-5bd59051ca81fc45dad09a9e3ebd97318b9dd5a03f1056a9e9a8b2fd01323aa8R358-R364
> 
> If so, how about creating history partition automatically when start is set and not create history partition if start is not set? Then no new property is needed.

This can be a good idea, I agree with it if you also accept it.

**Comment by imay** [comment]
> This can be a good idea, I agree with it if you also accept it.

Of course, go ahead.

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 13 / 22 (59.09%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/clone/DynamicPartitionScheduler.java|0|7|00.00%|[140, 143, 144, 146, 148, 149, 151]|
|:large_blue_circle:|com/starrocks/common/util/DynamicPartitionUtil.java|11|13|84.62%|[197, 198]|
|:large_blue_circle:|com/starrocks/catalog/DynamicPartitionProperty.java|2|2|100.00%|[]|

**Review by imay — APPROVED** [review]

**Review by Astralidea — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Pull request merged**
