### PR TITLE
[Enhancement] assign tablets to driver sequence only if num_tablets>dop/2

### PR DESCRIPTION
**Pull request by ZiheLiu**
## What type of PR is this：
- [ ] bug
- [ ] feature
- [x] enhancement
- [ ] refactor
- [ ] others

## Problem Summary(Required) ：

The strategy of assigning scanRanges to each driver sequence is to avoid local shuffle.

However, if the number of buckets assigned to a fragment instance is less than `pipelineDop`, `pipelineDop` will be set to `num_buckets`, which will reduce the degree of operator parallelism.

Therefore, when there are few buckets, insert local shuffle instead of using this strategy to improve the degree of parallelism.

To balance the cost of local shuffle and lower `DOP`, we insert local shuffle when `num_tablets <=pipeline_dop/2`.
- If `num_tablets` is not very small, inserting local shuffle cannot significantly improve `DOP` but the cost of local shuffle may be expensive.
- If `num_tablets` is very small,  inserting local shuffle can significantly improve `DOP`.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by ZiheLiu** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 5 / 6 (83.33%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/Coordinator.java|5|6|83.33%|[278]|

**Comment by ZiheLiu** [comment]
@Mergifyio backport branch-2.4

**Review by satanson — APPROVED** [review]

**Review by silverbullet233 — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by murphyatwork — APPROVED** [review]

**Comment by ZiheLiu** [comment]
run starrocks_admit_test

**Pull request merged**
