### PR TITLE
[BugFix] Shadow all modified columns in schema changing

### LINKED ISSUE #19519: Question about MV column name when modify column
## General Question

1. Create table
```
mysql> CREATE TABLE IF NOT EXISTS detail_demo3 (
    ->     id            BIGINT         COMMENT "range [-2^63 + 1 ~ 2^63 - 1]",
    ->     pass      LARGEINT       COMMENT "range [-2^127 + 1 ~ 2^127 - 1]",
    ->     info      LARGEINT       COMMENT "range [-2^127 + 1 ~ 2^127 - 1]"
    -> ) ENGINE=OLAP
    -> DUPLICATE KEY(id)
    -> DISTRIBUTED BY HASH(id) BUCKETS 1
    -> properties (
    -> "replication_num" = "1"
    -> );
```
2. Create MV
```
mysql> CREATE MATERIALIZED VIEW store_amt AS select id, pass FROM detail_demo3;
Query OK, 0 rows affected (0.01 sec)
```
3. desc
```
mysql> desc detail_demo3 all;
+--------------+---------------+-------+----------+------+-------+---------+-------+
| IndexName    | IndexKeysType | Field | Type     | Null | Key   | Default | Extra |
+--------------+---------------+-------+----------+------+-------+---------+-------+
| detail_demo3 | DUP_KEYS      | id    | bigint   | YES  | true  | NULL    |       |
|              |               | pass  | largeint | YES  | false | NULL    | NONE  |
|              |               | info  | largeint | YES  | false | NULL    | NONE  |
|              |               |       |          |      |       |         |       |
| store_amt    | DUP_KEYS      | id    | bigint   | YES  | true  | NULL    |       |
|              |               | pass  | largeint | YES  | true  | NULL    |       |
+--------------+---------------+-------+----------+------+-------+---------+-------+
6 rows in set (0.01 sec)
```
4.mofity column, change type
```
mysql> alter table detail_demo3 modify column pass varchar;
Query OK, 0 rows affected (0.01 sec)
```
5. middle state when process alter table.
```
mysql> desc detail_demo3 all;
+---------------------------------+---------------+-------------------------+------------+------+-------+---------+-------+
| IndexName                       | IndexKeysType | Field                   | Type       | Null | Key   | Default | Extra |
+---------------------------------+---------------+-------------------------+------------+------+-------+---------+-------+
| detail_demo3                    | DUP_KEYS      | id                      | bigint     | YES  | true  | NULL    |       |
|                                 |               | pass                    | largeint   | YES  | false | NULL    | NONE  |
|                                 |               | info                    | largeint   | YES  | false | NULL    | NONE  |
|                                 |               |                         |            |      |       |         |       |
| __starrocks_shadow_detail_demo3 | DUP_KEYS      | id                      | bigint     | YES  | true  | NULL    |       |
|                                 |               | __starrocks_shadow_pass | varchar(1) | YES  | false | NULL    | NONE  |
|                                 |               | info                    | largeint   | YES  | false | NULL    | NONE  |
|                                 |               |                         |            |      |       |         |       |
| __starrocks_shadow_store_amt    | DUP_KEYS      | id                      | bigint     | YES  | true  | NULL    |       |
|                                 |               | pass                    | varchar(1) | YES  | true  | NULL    |       |
|                                 |               |                         |            |      |       |         |       |
| store_amt                       | DUP_KEYS      | id                      | bigint     | YES  | true  | NULL    |       |
|                                 |               | pass                    | largeint   | YES  | true  | NULL    |       |
+---------------------------------+---------------+-------------------------+------------+------+-------+---------+-------+
13 rows in set (0.00 sec)
```
My question is, should `__starrocks_shadow_store_amt` have column name `__starrocks_shadow_pass` instead of `pass`? Or we can get a wrong `TPlanFragment`?

### PR DESCRIPTION
**Pull request by LiShuMing**
Fixes #19519

- all modfied columns in the schema changing should add the `__starrocks_shadow_` prefix to ensure not break the concurrent load tasks.
```
    /**
     * When doing schema change, there may have some 'shadow' columns, with prefix '__starrocks_shadow_' in
     * their names. These columns are invisible to user, but we need to generate data for these columns.
     * So we add column mappings for these column.
     * eg1:
     * base schema is (A, B, C), and B is under schema change, so there will be a shadow column: '__starrocks_shadow_B'
     * So the final column mapping should looks like: (A, B, C, __starrocks_shadow_B = substitute(B));
     */
```
## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [x] 3.0
  - [x] 2.5
  - [ ] 2.4

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:disappointed: **fail** : 3 / 5 (60.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/alter/SchemaChangeHandler.java|3|5|60.00%|[616, 631]|

**Review by luohaha — APPROVED** [review]

**Review by kangkaisen — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
