### PR TITLE
[BugFix] fix mistakenly pushed-down subfield to child

### PR DESCRIPTION
**Pull request by packy92**
For sql like
```
select t.c1, t.c2.s1 from 
(
select array_map(x -> (x + t.v1), t.a1) c1, t.st1 c2 from (select pc0.a1, sc0.* from pc0 join sc0) t
) t join pc0
```
When we try push the `array_map` expr to a child , the child must output all these used cols in the expr. The `array_map` used cols from both table `pc0` and `sc0`, pushing it to any child is wrong. We should keep it above the join operator.

Other changes:
- add input dependency check to scanOperator and valuesOperator.
- ensure lambdaOperator `getUsedColumns` result just contains outer ref cols instead of lambda common sub output cols after common expr reuse rule.

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [x] 3.0
  - [ ] 2.5
  - [ ] 2.4

### CODE REVIEW

**Review by Seaven — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 20 / 20 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/validate/InputDependenciesChecker.java|17|17|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/tree/prunesubfield/PushDownSubfieldRule.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/RowOutputInfo.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 20 / 20 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/validate/InputDependenciesChecker.java|17|17|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/tree/prunesubfield/PushDownSubfieldRule.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/RowOutputInfo.java|1|1|100.00%|[]|

**Review by Seaven — DISMISSED** [review]

**Review by kangkaisen — DISMISSED** [review]

**Review by liuyehcf — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 24 / 24 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/validate/InputDependenciesChecker.java|17|17|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/scalar/LambdaFunctionOperator.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/tree/prunesubfield/PushDownSubfieldRule.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/RowOutputInfo.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 24 / 24 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/validate/InputDependenciesChecker.java|17|17|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/scalar/LambdaFunctionOperator.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/tree/prunesubfield/PushDownSubfieldRule.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/RowOutputInfo.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 24 / 24 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/validate/InputDependenciesChecker.java|17|17|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/scalar/LambdaFunctionOperator.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/tree/prunesubfield/PushDownSubfieldRule.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/RowOutputInfo.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by fzhedu — APPROVED** [review]

**Review by kangkaisen — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Pull request merged**
