### PR TITLE
[Enhancement] Refine profile to support visualization refactor(5)

### PR DESCRIPTION
**Pull request by liuyehcf**
This pr is an continuation work of #29063, #30381, #30975 and #31380, and the main objectives of this pr are:

1. Fix incorrect `ScheduleTime`
2. Fix incorrect `ResultDeliverTime `

## Incorrect ScheduleTime

This issue is introduced by runtime profiling #27021.

When executing a long-running query with session variable `enable_profile=true`, the runtime profiling mechanism is automitically enabled. And there may have some pipelines that are soon finished at the first beginning, which will be  also updated incorrectly as those still-running pipelines reporting their states. And the `TotalDriverTime` will be updated to a large value, and results in the large `ScheduleTime`

So the solution is simple, add a check at the start of `PipelineDriver::runtime_report_action`

```cpp
void PipelineDriver::runtime_report_action() {
    if (is_finished()) {
        return;
    }
    ...
}
```

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.2
  - [x] 3.1
  - [x] 3.0
  - [ ] 2.5

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:heart_eyes: **pass** : 15 / 18 (83.33%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/exec/pipeline/pipeline_driver.cpp|14|17|82.35%|[463, 464, 467]|
|:large_blue_circle:|src/exec/pipeline/pipeline_driver_executor.cpp|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:heart_eyes: **pass** : 15 / 18 (83.33%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/exec/pipeline/pipeline_driver.cpp|14|17|82.35%|[463, 464, 467]|
|:large_blue_circle:|src/exec/pipeline/pipeline_driver_executor.cpp|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:disappointed: **fail** : 0 / 1 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/scheduler/QueryRuntimeProfile.java|0|1|00.00%|[437]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:heart_eyes: **pass** : 15 / 18 (83.33%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/exec/pipeline/pipeline_driver.cpp|14|17|82.35%|[463, 464, 467]|
|:large_blue_circle:|src/exec/pipeline/pipeline_driver_executor.cpp|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:disappointed: **fail** : 0 / 1 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/scheduler/QueryRuntimeProfile.java|0|1|00.00%|[437]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:heart_eyes: **pass** : 15 / 18 (83.33%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/exec/pipeline/pipeline_driver.cpp|14|17|82.35%|[463, 464, 467]|
|:large_blue_circle:|src/exec/pipeline/pipeline_driver_executor.cpp|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/scheduler/QueryRuntimeProfile.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:heart_eyes: **pass** : 15 / 18 (83.33%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/exec/pipeline/pipeline_driver.cpp|14|17|82.35%|[463, 464, 467]|
|:large_blue_circle:|src/exec/pipeline/pipeline_driver_executor.cpp|1|1|100.00%|[]|

**Review by satanson — APPROVED** [review]

**Review by ZiheLiu — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.2

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by liuyehcf** [comment]
3.0 needn't cp.

**Pull request merged**
