### PR TITLE
[Doc] Modify enable_hive_metastore_cache to enable_metastore_cache in external catalog

### LINKED ISSUE #18939: Doc and code are inconsistent about hive catalog config key
### Expected behavior (Required)
doc and code are inconsistent cause 
image
image
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by leoyy0316**
## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [x] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #18939

## Problem Summary(Required) ：

doc and code are inconsistent
image

image

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Comment by leoyy0316** [comment]
run starrocks_admit_test

**Review by imay — DISMISSED** [review]

**Review by stephen-shelby — DISMISSED** [review]

**Comment by imay** [comment]
@leoyy0316 please sing-off this change

**Comment by leoyy0316** [comment]
run starrocks_admit_test

**Comment by leoyy0316** [comment]
> @leoyy0316 please sing-off this change
@imay done, pls help merge, thanks

**Review by imay — APPROVED** [review]

**Comment by leoyy0316** [comment]
@Mergifyio backport branch-2.5

**Comment by leoyy0316** [comment]
@Mergifyio backport branch-3.0

**Pull request merged**
