### PR TITLE
[CherryPick][BugFix] Fix transaction stream load empty label return message

### PR DESCRIPTION
**Pull request by meegoo**
Conflicts:
	fe/fe-core/src/main/java/com/starrocks/http/rest/TransactionLoadAction.java

## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
starrocks_be_unittest succeeded.

**Comment by wanpengfei-git** [comment]
starrocks_be_unittest succeeded.

**Comment by meegoo** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
starrocks_be_unittest succeeded.

**Comment by wanpengfei-git** [comment]
starrocks_be_unittest succeeded.

**Comment by meegoo** [comment]
run starrocks_fe_unittest

**Review by gengjun-git — APPROVED** [review]

**Pull request merged**
