### PR TITLE
[Feature] Support list partition

### LINKED ISSUE #4035: Support list partition【Moderate】
# Requirement Description
1. List partition design.
2. List partition implementation, including table creation, loading and query.

```
CREATE TABLE h2 (
  c1 INT,
  c2 INT
)
PARTITION BY LIST(c1) (
  PARTITION p0 VALUES IN (1, 4, 7),
  PARTITION p1 VALUES IN (2, 5, 8)
)
DISTRIBUTED BY HASH(c2) BUCKETS 3;
```

# Mentor
@wyb 

# Registration procedure

**Step 1.** Add a comment when you sign up. The comment can be a brief self-introduction and reason for signing up, including what you do, what you're good at, what you're interested in and your technology stack, and how familiar you are with StarRocks. Example:

> I pick! My name is Johnny. I am from StarRocks and I have been working on database kernel development for 1 year. I am interested in OLAP, good at C++ programming, and have been using StarRocks for 6 months. I chose to solve this issue because I am familiar with execution engine.

**Step 2.** On your WeChat, add the StarRocks community assistant "**_StarRocks-1_**" as a WeChat friend and leave your GitHub ID. The assistant will invite you to a WeChat group based on the issue you picked.

**Step 3.** The mentor will communicate with all the participants who picked this issue and assign the task to the best match. 

# Before you start
1. Read the StarRocks [GitHub workflow](https://github.com/StarRocks/community/blob/main/Contributors/guide/workflow.md) carefully, which provides the configurations of BE and FE and describes how to submit a pull request.
2. To learn more about StarRocks, read [StarRocks documentation](https://github.com/StarRocks/docs/blob/main/TOC.md).

# Pull request requirements

1. After you complete code development, upload the code to the StarRocks code repo as a pull request (PR).

  - PR title format: **[SR GeekCamp] + PR title**
  - Labels ：[Geek Camp 2022/feature]
2. After you submit your PR, comment on the status of your PR submission as requested under the Pinned Issue [[StarRocks geek Camp 2022] ](https://github.com/StarRocks/starrocks/issues/4008)page.

  - Comment format: **"I have finished Issue #" + PR link id**

### PR DESCRIPTION
**Pull request by Astralidea**
Signed-off-by: Astralidea <astralidea@163.com>

## What type of PR is this：
- [ ] BugFix
- [x] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #4035

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 25 / 44 (56.82%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|0|4|00.00%|[3058, 3059, 3060, 3061]|
|:large_blue_circle:|com/starrocks/sql/ast/ListPartitionDesc.java|3|5|60.00%|[80, 81]|
|:large_blue_circle:|com/starrocks/catalog/OlapTable.java|21|34|61.76%|[768, 769, 770, 771, 772, 773, 774, 776, 855, 856, 858, 859, 862]|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 79 / 155 (50.97%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/PartitionInfo.java|0|1|00.00%|[180]|
|:large_blue_circle:|com/starrocks/catalog/CatalogUtils.java|9|56|16.07%|[104, 105, 106, 108, 109, 110, 111, 112, 113, 114, 115, 117, 118, 119, 120, 121, 122, 124, 125, 127, 128, 129, 130, 131, 132, 134, 136, 137, 138, 139, 140, 141, 142, 143, 144, 147, 148, 149, 150, 151, 152, 154, 155, 157, 158, 159, 160]|
|:large_blue_circle:|com/starrocks/catalog/ListPartitionInfo.java|8|19|42.11%|[367, 368, 369, 370, 371, 372, 373, 376, 377, 378, 380]|
|:large_blue_circle:|com/starrocks/sql/ast/ListPartitionDesc.java|5|7|71.43%|[80, 81]|
|:large_blue_circle:|com/starrocks/catalog/OlapTable.java|54|69|78.26%|[768, 769, 770, 771, 772, 773, 774, 776, 855, 856, 858, 859, 862, 1911, 1914]|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|2|2|100.00%|[]|

**Comment by Astralidea** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 81 / 159 (50.94%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/PartitionInfo.java|0|1|00.00%|[180]|
|:large_blue_circle:|com/starrocks/catalog/CatalogUtils.java|9|56|16.07%|[104, 105, 106, 108, 109, 110, 111, 112, 113, 114, 115, 117, 118, 119, 120, 121, 122, 124, 125, 127, 128, 129, 130, 131, 132, 134, 136, 137, 138, 139, 140, 141, 142, 143, 144, 147, 148, 149, 150, 151, 152, 154, 155, 157, 158, 159, 160]|
|:large_blue_circle:|com/starrocks/catalog/ListPartitionInfo.java|8|18|44.44%|[367, 368, 369, 370, 371, 372, 373, 377, 378, 379]|
|:large_blue_circle:|com/starrocks/sql/ast/ListPartitionDesc.java|5|7|71.43%|[79, 80]|
|:large_blue_circle:|com/starrocks/catalog/OlapTable.java|56|74|75.68%|[768, 769, 770, 771, 772, 773, 774, 776, 854, 855, 856, 858, 859, 860, 861, 864, 1913, 1916]|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|2|2|100.00%|[]|

**Comment by Astralidea** [comment]
run starrocks_admit_test

**Review by wyb — APPROVED** [review]

**Review by gengjun-git — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by Astralidea** [comment]
run starrocks_admit_test

**Comment by Astralidea** [comment]
run starrocks_admit_test

**Comment by Astralidea** [comment]
run starrocks_admit_test

**Comment by Astralidea** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 81 / 163 (49.69%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|0|4|00.00%|[3158, 3159, 3160, 3161]|
|:large_blue_circle:|com/starrocks/catalog/PartitionInfo.java|0|1|00.00%|[180]|
|:large_blue_circle:|com/starrocks/catalog/CatalogUtils.java|9|56|16.07%|[104, 105, 106, 108, 109, 110, 111, 112, 113, 114, 115, 117, 118, 119, 120, 121, 122, 124, 125, 127, 128, 129, 130, 131, 132, 134, 136, 137, 138, 139, 140, 141, 142, 143, 144, 147, 148, 149, 150, 151, 152, 154, 155, 157, 158, 159, 160]|
|:large_blue_circle:|com/starrocks/catalog/ListPartitionInfo.java|8|18|44.44%|[367, 368, 369, 370, 371, 372, 373, 377, 378, 379]|
|:large_blue_circle:|com/starrocks/sql/ast/ListPartitionDesc.java|5|7|71.43%|[79, 80]|
|:large_blue_circle:|com/starrocks/catalog/OlapTable.java|56|74|75.68%|[768, 769, 770, 771, 772, 773, 774, 776, 854, 855, 856, 858, 859, 860, 861, 864, 1913, 1916]|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|3|3|100.00%|[]|

**Pull request merged**
