### PR TITLE
[BugFix] fix external table commit timeout treated as failure

### PR DESCRIPTION
**Pull request by starrocks-xupeng**
Fixes #issue

## What type of PR is this:
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [x] Doc
- [ ] Tool

## Checklist:
- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.0
  - [x] 2.5
  - [x] 2.4
  - [x] 2.3

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 1 / 11 (09.09%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/transaction/GlobalTransactionMgr.java|0|4|00.00%|[207, 228, 229, 231]|
|:large_blue_circle:|com/starrocks/leader/LeaderImpl.java|0|4|00.00%|[1243, 1250, 1251, 1252]|
|:large_blue_circle:|com/starrocks/qe/StmtExecutor.java|0|1|00.00%|[1669]|
|:large_blue_circle:|com/starrocks/catalog/ExternalOlapTable.java|0|1|00.00%|[586]|
|:large_blue_circle:|com/starrocks/common/Config.java|1|1|100.00%|[]|

**Comment by kevincai** [comment]
should be `[BugFix]`, case senstive.

**Review by kevincai — APPROVED** [review]

**Review by wyb — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 1 / 11 (09.09%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/transaction/GlobalTransactionMgr.java|0|4|00.00%|[207, 228, 229, 231]|
|:large_blue_circle:|com/starrocks/leader/LeaderImpl.java|0|4|00.00%|[1243, 1250, 1251, 1252]|
|:large_blue_circle:|com/starrocks/qe/StmtExecutor.java|0|1|00.00%|[1674]|
|:large_blue_circle:|com/starrocks/catalog/ExternalOlapTable.java|0|1|00.00%|[570]|
|:large_blue_circle:|com/starrocks/common/Config.java|1|1|100.00%|[]|

**Review by sduzh — APPROVED** [review]

**Review by wyb — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Comment by evelynzhaojie** [comment]
@starrocks-xupeng Is this FE parameter visible to users? If yes, pls add it to doc https://github.com/StarRocks/starrocks/blob/main/docs/administration/Configuration.md and submit a doc pr.

**Comment by starrocks-xupeng** [comment]
https://github.com/StarRocks/starrocks/pull/25165

**Comment by starrocks-xupeng** [comment]
https://github.com/StarRocks/starrocks/pull/25168

**Pull request merged**
