### PR TITLE
[BugFix] check brpc stub in exchange sink

### PR DESCRIPTION
**Pull request by fzhedu**
## What type of PR is this:
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes:

Fixes #

## Problem Summary(Required):

```
PC: @          0x3fbffa2 starrocks::pipeline::SinkBuffer::_try_to_send_rpc()
*** SIGSEGV (@0x0) received by PID 769 (TID 0x7f489efff700) from PID 0; stack trace: ***
    @          0x487c722 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7f49c5619630 (unknown)
    @          0x3fbffa2 starrocks::pipeline::SinkBuffer::_try_to_send_rpc()
    @          0x3fc0742 starrocks::pipeline::SinkBuffer::add_request()
    @          0x3fb4357 starrocks::pipeline::ExchangeSinkOperator::Channel::send_one_chunk()
    @          0x3fb4cb4 starrocks::pipeline::ExchangeSinkOperator::Channel::_close_internal()
    @          0x3fb4d46 starrocks::pipeline::ExchangeSinkOperator::Channel::close()
    @          0x3fb5137 starrocks::pipeline::ExchangeSinkOperator::set_finishing()
    @          0x1e5c1a7 starrocks::pipeline::PipelineDriver::_mark_operator_finishing()
    @          0x1e5cdc5 starrocks::pipeline::PipelineDriver::process()
    @          0x3ce8805 starrocks::pipeline::GlobalDriverExecutor::_worker_thread()
    @          0x37adbf5 starrocks::ThreadPool::dispatch_thread()
    @          0x37a8a9a starrocks::Thread::supervise_thread()
    @     0x7f49c5611ea5 start_thread
    @     0x7f49c4c2cb0d __clone
    @                0x0 (unknown)
```

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 3.0
  - [x] 2.5
  - [x] 2.4
  - [x] 2.3

### CODE REVIEW

**Review by imay — APPROVED** [review]

**Review by silverbullet233 — APPROVED** [review]

**Review by stdpain — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.4

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.3

**Pull request merged**
