### PR TITLE
Optimize error message for alter table with materialized view

### LINKED ISSUE #8546: [Enhancement] optimize error message when use alter table to rename partition name of materialized view
## Enhancement
for table:
CREATE TABLE `tbl1` (
  `k1` date NULL COMMENT "",
  `k2` int(11) NULL COMMENT "",
  `v1` int(11) SUM NULL COMMENT ""
) ENGINE=OLAP
AGGREGATE KEY(`k1`, `k2`)
COMMENT "OLAP"
PARTITION BY RANGE(`k1`)
(PARTITION p1 VALUES [('0000-01-01'), ('2022-02-01')),
PARTITION p2 VALUES [('2022-02-01'), ('2022-03-01')))
DISTRIBUTED BY HASH(`k2`) BUCKETS 3
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"storage_format" = "DEFAULT",
"enable_persistent_index" = "false"
);

create a materialized view:
CREATE MATERIALIZED VIEW mv1_partition_by_column
PARTITION BY k1
distributed by hash(k2)
refresh async START('2122-12-31') EVERY(INTERVAL 1 HOUR)
PROPERTIES('replication_num' = '1')
as select k1, k2 from tbl1;

then alter table rename partition of materialized view:
alter table mv1_partition_by_column rename partition p00000101_20220201 pbase;

the error message is:
Do not support alter non-OLAP table[mv1_partition_by_column]

which is not precise.

### PR DESCRIPTION
**Pull request by ABingHuang**
## What type of PR is this：
- [ ] bug
- [ ] feature
- [x] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #8546 

## Problem Summary(Required) ：

Optimize error message for alter table with materialized view

### CODE REVIEW

**Comment by Astralidea** [comment]
run starrocks_fe_unittest

**Comment by Astralidea** [comment]
run starrocks_fe_unittest

**Comment by ABingHuang** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 9 / 11 (81.82%)




#### file detail

|   |path|covered line|new line|coverage|not covered line detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/common/MetaUtils.java|5|7|71.43%|[46, 50]|
|:large_blue_circle:|com/starrocks/analysis/AlterTableStmt.java|4|4|100.00%|[]|

**Review by Astralidea — APPROVED** [review]

**Review by kangkaisen — APPROVED** [review]

**Pull request merged**
