### PR TITLE
[Enhancement] Support load_transmission_compression_type session variable unified load compress config

### PR DESCRIPTION
**Pull request by meegoo**
## What type of PR is this：
- [ ] bug
- [ ] feature
- [x] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 11 / 24 (45.83%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/load/ExportJob.java|0|1|00.00%|[399]|
|:large_blue_circle:|com/starrocks/qe/Coordinator.java|0|7|00.00%|[276, 285, 286, 287, 288, 289, 290]|
|:large_blue_circle:|com/starrocks/task/StreamLoadTask.java|1|4|25.00%|[298, 299, 300]|
|:large_blue_circle:|com/starrocks/load/loadv2/LoadLoadingTask.java|1|2|50.00%|[122]|
|:large_blue_circle:|com/starrocks/load/loadv2/BulkLoadJob.java|1|2|50.00%|[100]|
|:large_blue_circle:|com/starrocks/load/routineload/RoutineLoadJob.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/qe/SessionVariable.java|5|5|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/StreamLoadPlanner.java|2|2|100.00%|[]|

**Comment by meegoo** [comment]
@mergify rebase

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 11 / 24 (45.83%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/load/ExportJob.java|0|1|00.00%|[399]|
|:large_blue_circle:|com/starrocks/qe/Coordinator.java|0|7|00.00%|[276, 285, 286, 287, 288, 289, 290]|
|:large_blue_circle:|com/starrocks/task/StreamLoadTask.java|1|4|25.00%|[298, 299, 300]|
|:large_blue_circle:|com/starrocks/load/loadv2/LoadLoadingTask.java|1|2|50.00%|[122]|
|:large_blue_circle:|com/starrocks/load/loadv2/BulkLoadJob.java|1|2|50.00%|[100]|
|:large_blue_circle:|com/starrocks/load/routineload/RoutineLoadJob.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/qe/SessionVariable.java|5|5|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/StreamLoadPlanner.java|2|2|100.00%|[]|

**Review by chaoyli — APPROVED** [review]

**Review by gengjun-git — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by meegoo** [comment]
run starrocks_admit_test

**Comment by meegoo** [comment]
@mergify backport branch-2.4

**Pull request merged**
