### PR TITLE
[Enhancement] simplify column name for show create mv

### PR DESCRIPTION
**Pull request by murphyatwork**
## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

Simplify the output of `show create table` for materialized view:
- Avoid show db name if all tables are in the same db
- Avoid add an alias if column name unchanged

Before:
```sql
AS SELECT `rtmv`.`t0`.`t0_c0` + 1 AS `mv3_c0`, `rtmv`.`t0`.`t0_c1` AS `t0_c1`, `rtmv`.`t1`.`t1_c0` AS `t1_c0`, `rtmv`.`t1`.`t1_c1` AS `t1_c1`
 FROM `rtmv`.`t0` INNER JOIN `rtmv`.`t1` ON `rtmv`.`t0`.`t0_c0` = `rtmv`.`t1`.`t1_c0`
 WHERE `rtmv`.`t0`.`t0_c1` = 'star';

```

After:
```sql
AS SELECT `t0`.`t0_c0` + 1 AS `mv3_c0`, `t0`.`t0_c1`, `t1`.`t1_c0`, `t1`.`t1_c1`
 FROM `t0` INNER JOIN `t1` ON `t0`.`t0_c0` = `t1`.`t1_c0`
 WHERE `t0`.`t0_c1` = 'star';

```

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Review by Astralidea — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 84 / 90 (93.33%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/AnalyzerUtils.java|0|3|00.00%|[300, 301, 302]|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|2|4|50.00%|[949, 972]|
|:large_blue_circle:|com/starrocks/catalog/MaterializedView.java|48|49|97.96%|[549]|
|:large_blue_circle:|com/starrocks/sql/analyzer/ViewDefBuilder.java|29|29|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/CreateMaterializedViewStatement.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/qe/ShowExecutor.java|1|1|100.00%|[]|

**Comment by mofeiatwork** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 85 / 91 (93.41%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/AnalyzerUtils.java|0|3|00.00%|[300, 301, 302]|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|2|4|50.00%|[949, 972]|
|:large_blue_circle:|com/starrocks/catalog/MaterializedView.java|48|49|97.96%|[569]|
|:large_blue_circle:|com/starrocks/sql/analyzer/ViewDefBuilder.java|29|29|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/CreateMaterializedViewStatement.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/qe/ShowExecutor.java|1|1|100.00%|[]|

**Comment by mofeiatwork** [comment]
run starrocks_admit_test

**Review by kangkaisen — APPROVED** [review]

**Review by Seaven — APPROVED** [review]

**Pull request merged**
