### PR TITLE
[Enhancement][jemalloc] Phase 2: adapt the pprof web interface and use jemalloc as default mem allocator

### PR DESCRIPTION
**Pull request by silverbullet233**
## What type of PR is this：
- [ ] bugfix
- [ ] feature
- [x] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

Major changes:
1. adapt to pprof related web interfaces, including /pprof/heap and /pprof/profile
2. use jemalloc as the default memory allocator

**Note**:
1. the file format of jemalloc heap profiling is different from that of tcmalloc, and jeprof needs to be used for analysis
2. jemalloc does not have a direct interface to obtain heap growth so that **/pprof/growth interface is not supported now**, and a similar effect can be achieved by diffing two heap profiling files

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by silverbullet233** [comment]
run starrocks_admit_test

**Comment by silverbullet233** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by silverbullet233** [comment]
run starrocks_clang-tidy

**Comment by kangkaisen** [comment]
need full performance test report

**Review by kangkaisen — APPROVED** [review]

**Review by murphyatwork — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by silverbullet233** [comment]
https://github.com/Mergifyio backport branch-2.4

**Pull request merged**
