### PR TITLE
[BugFix] Make pipeline_driver's total_timer exclude the prepare time

### LINKED ISSUE #24534: Poor query performance cause by too high schedule time when deployed with k8s
#### sql
TPCH 1000G

Q2
select count(*) from (
select  s_acctbal, s_name,  n_name,  p_partkey,  p_mfgr,  s_address,  s_phone,  s_comment
from  part,  partsupp,  supplier,  nation,  region
where
  p_partkey = ps_partkey
  and s_suppkey = ps_suppkey
  and p_size = 15
  and p_type like '%BRASS'
  and s_nationkey = n_nationkey
  and n_regionkey = r_regionkey
  and r_name = 'EUROPE'
  and ps_supplycost = (
    select  min(ps_supplycost)
    from  partsupp,  supplier,  nation,  region
    where
      p_partkey = ps_partkey
      and s_suppkey = ps_suppkey
      and s_nationkey = n_nationkey
      and n_regionkey = r_regionkey
      and r_name = 'EUROPE'
  )
order by  s_acctbal desc, n_name,  s_name,  p_partkey
) as t1;

#### Test enviroment
3 fe and 3 be, 84 core 350g, Linux version 5.4.119, gcc version 8.5.0 20210514 (Red Hat 8.5.0-10)
Both k8s deployment and physical cluster deployment have the same physical hardware resources.

#### Query performance
k8s deployment with best-effort
image

Physical cluster deployment
image

#### Profile
[profile-k8s.txt](https://github.com/StarRocks/starrocks/files/11621958/profile-k8s.txt)
[profile-physical-cluster.txt](https://github.com/StarRocks/starrocks/files/11621963/profile-physical-cluster.txt)

k8s deployment with best-effort
image

Physical cluster deployment
image

#### Flame Graph
k8s deployment with best-effort
image

Physical cluster deployment
image

found that 22% cpu overhead show at poll thread to schedule pipeline_driver when deployed with k8s whereas physical cluster deployment show 1%~ cpu overhead.

### StarRocks version (Required)
2.5.4-TQ-0.6 dbc1950

Can someone offer some clues or provide any better way to analyze this problem?

### PR DESCRIPTION
**Pull request by liuyehcf**
Fixes #24534

`PipelineDriver::prepre` is executed in a serial way. And some of the timers are triggered at prepare stage. And the total time may include other driver's prepare time usage, which further results in an abnomal ScheduleTime in profile if other dirver's prepare stage persists for a long while.

## What type of PR is this:
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.0
  - [x] 2.5
  - [x] 2.4
  - [x] 2.3

### CODE REVIEW

**Review by murphyatwork — APPROVED** [review]

**Review by ZiheLiu — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 0 / 2 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/Coordinator.java|0|2|00.00%|[1687, 1688]|

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.4

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.3

**Pull request merged**
