### PR TITLE
[UT] Fix two unstable FE UT

### PR DESCRIPTION
**Pull request by kangkaisen**
## What type of PR is this：
- [ ] bug
- [ ] feature
- [x] enhancement
- [ ] refactor
- [ ] others

Unstable FE UT will waste a lot of time of our RDs, we should fix it.

https://github.com/StarRocks/starrocks/pull/8184 failed to fix com.starrocks.alter.RollupJobV2Test.testSchemaChange1, this PR should fix it once and for all.

Fix two unstable FE UT:
1. com.starrocks.alter.RollupJobV2Test.testSchemaChange1
2. RestrictOpMaterializedViewTest.testBrokerLoad

The core idea to fix these two UT:

### CODE REVIEW

**Comment by kangkaisen** [comment]
run starrocks_fe_unittest

**Comment by kangkaisen** [comment]
run starrocks_fe_unittest

**Review by Astralidea — APPROVED** [review]

**Comment by Astralidea** [comment]
run starrocks_admit_test

**Review by satanson — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 3 / 3 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/common/util/MasterDaemon.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/alter/AlterHandler.java|2|2|100.00%|[]|

**Pull request merged**
