### PR TITLE
[BugFix] exchange source forgets running closure in two cases

### PR DESCRIPTION
**Pull request by fzhedu**
Signed-off-by: fzhedu <fzhedu@gmail.com>

## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #https://github.com/StarRocks/starrocks/issues/12981

## Problem Summary(Required) ：

the callback function `closure-Run()` is ignored being called in exchange source. In detail:

### place 1
https://github.com/StarRocks/starrocks/blob/c354c8f0933342454edf5bde4689437fa35db516/be/src/runtime/sender_queue.cpp#L677-L689

https://github.com/StarRocks/starrocks/blob/c354c8f0933342454edf5bde4689437fa35db516/be/src/runtime/sender_queue.cpp#L496-L536

before enqueue blocks into `_chunk_queues`, the cancelled status may be set, so the new added blocks's callback functions are not called anymore.

### place 2

https://github.com/StarRocks/starrocks/blob/c354c8f0933342454edf5bde4689437fa35db516/be/src/runtime/sender_queue.cpp#L417-L435

if early return at L420, the existing closure is not called anymore.

by the way, append `fragment_status` to the http interface.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature (mannel test 20 times ok)
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Review by murphyatwork — APPROVED** [review]

**Review by kangkaisen — APPROVED** [review]

**Comment by dulong41** [comment]
run starrocks_admit_test

**Comment by fzhedu** [comment]
run starrocks_be_unittest

**Comment by fzhedu** [comment]
run starrocks_be_unittest

**Comment by fzhedu** [comment]
@mergify backport branch-2.5

**Pull request merged**
