### PR TITLE
[Feature] upgrade alter/drop/create/select on table/db/view

### PR DESCRIPTION
**Pull request by padmejin**
## What type of PR is this：
- [ ] BugFix
- [x] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

* Refactor AuthUpgrader, seperating upgrade method on different types.
* Implement upgrade logic of action alter/drop/create/select on table/db/view
   * select
     * select on `*.*`/`db.*` will be applied to both view & table
     * select on a specific table will be applied to either view or table by the actual type of it.
  * drop & alter
     * drop/alter on `*.*`/`db.*` will be applied to view, table & db
     * drop/alter on a specific table will be applied to either view or table by the actual type of it.
  * create
     * create on `*.*`/`db.*` will be applied to db with action `create_table`, `create_view`, `create_mv`
     * create on a specific table will be discarded.
* Impelement load on table, but doesn't test it. 

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

### CODE REVIEW

**Review by nshangyiming — APPROVED** [review]

**Comment by nshangyiming** [comment]
run starrocks_admit_test

**Review by gengjun-git — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by meegoo — APPROVED** [review]

**Comment by padmejin** [comment]
run starrocks_fe_unittest

**Comment by nshangyiming** [comment]
run all

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 132 / 165 (80.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/mysql/privilege/AuthUpgrader.java|130|163|79.75%|[242, 243, 302, 303, 364, 417, 538, 539, 543, 593, 634, 635, 636, 648, 649, 650, 651, 655, 656, 657, 658, 659, 662, 663, 664, 718, 767, 815, 816, 817, 818, 819, 820]|
|:large_blue_circle:|com/starrocks/privilege/PrivilegeType.java|2|2|100.00%|[]|

**Comment by Kimi-SH** [comment]
I've received your email and will will reply to you as soon as possible after the vacation.————————————This is an auto reply email from QQ Mail.

**Pull request merged**
