### PR TITLE
[BugFix] fix scalarOperator not being negated correctly 

### LINKED ISSUE #28902: Sqlancer report error: CardinalityOfResultSetsMismatchError
### Steps to reproduce the behavior (Required)
1. Prepare Data:

```sql
-- Time: 2023/08/09 08:38:52
-- Database: g0
-- Database version: 5.1.0
-- seed value: 1691541524951
DROP DATABASE IF EXISTS g0;
CREATE DATABASE g0;
USE g0;
admin set frontend config ("enable_decimal_v3" = "true");
CREATE TABLE IF NOT EXISTS t0 (c_0_0 DECIMAL(6, 0)  NOT NULL ) AGGREGATE KEY (c_0_0) DISTRIBUTED BY HASH (c_0_0) BUCKETS 3 properties("replication_num"="1") ;
CREATE TABLE t1 (c_1_0 DATE NULL ,c_1_1 DECIMAL(32, 15)  NOT NULL ,c_1_2 CHAR(11) NOT NULL ,c_1_3 VARCHAR(1) NOT NULL ,c_1_4 DATE NULL ,c_1_5 TINYINT NOT NULL ,c_1_6 CHAR(31) REPLACE NULL , INDEX index1_c_1_2(`c_1_2`) USING BITMAP) AGGREGATE KEY (c_1_0,c_1_1,c_1_2,c_1_3,c_1_4,c_1_5) PARTITION BY RANGE(c_1_0) (START ("2010-01-01") END ("2022-12-31") EVERY (INTERVAL 148 day)) DISTRIBUTED BY HASH (c_1_3) BUCKETS 3 properties("replication_num"="1") ;
INSERT INTO t0 VALUES (215903);
INSERT INTO t1 VALUES ('2010-01-15', 51.396746013849584, '', '', '2010-01-30', 5, 'qjE');
INSERT INTO t0 VALUES (640977), (619477), (757921);
INSERT INTO t1 VALUES ('2010-01-29', 41.283428079284240, '', '', '2010-01-29', 0, NULL);
INSERT INTO t0 VALUES (709214);
INSERT INTO t1 VALUES (NULL, 14.046441836681588, '', '', '2010-01-01', 7, 'PJsPap'), ('2009-12-31', 21.683372558081660, '', '', '2010-01-29', 1, ''), (NULL, 15.368331127899953, 'x', '', '2010-01-16', 2, '');
INSERT INTO t0 VALUES (540193), (54435);
INSERT INTO t0 VALUES (889008), (147853);
INSERT INTO t1 VALUES ('2010-01-08', 77.820766610909028, '', '', '2010-01-11', 3, 'aF');
INSERT INTO t0 VALUES (490807), (231039);
INSERT INTO t1 VALUES ('2010-01-22', 80.358453977010951, '', '', '2009-12-31', 4, '6'), ('2010-01-07', 21.354453808309748, 'C2iA5kv', '', '2010-01-05', 1, 'rYM'), ('2010-01-13', 51.502861530668964, 'if', '', '2010-01-10', 6, 'Gd8l');
INSERT INTO t0 VALUES (752639);
INSERT INTO t0 VALUES (9987), (851937), (958981);
CREATE MATERIALIZED VIEW v0 AS SELECT t1_3.c_1_0, t1_3.c_1_1, t1_3.c_1_2, t1_3.c_1_3, t1_3.c_1_4, t1_3.c_1_6, COUNT(t1_3.c_1_5)  FROM t1 AS t1_3 GROUP BY t1_3.c_1_0, t1_3.c_1_1, t1_3.c_1_2, t1_3.c_1_3, t1_3.c_1_4, t1_3.c_1_6 ORDER BY t1_3.c_1_0, t1_3.c_1_1, t1_3.c_1_2, t1_3.c_1_3, t1_3.c_1_4, t1_3.c_1_6 ASC;
CREATE VIEW v0 AS SELECT t0_4.c_0_0 FROM t0 AS t0_4 WHERE true GROUP BY t0_4.c_0_0;
INSERT INTO t0 VALUES (232000), (163910);
INSERT INTO t0 VALUES (149599), (407074);
INSERT INTO t1 VALUES ('2010-01-02', 24.704641121116167, '9mPj', '', '2010-01-21', 2, '');
-- SELECT t1_10.c_1_2, t1_10.c_1_3, t1_10.c_1_4, t1_10.c_1_1, t1_10.c_1_6, t1_10.c_1_5 FROM t1 AS t1_10 GROUP BY t1_10.c_1_2, t1_10.c_1_3, t1_10.c_1_4, t1_10.c_1_1, t1_10.c_1_6, t1_10.c_1_5;
-- cardinality: 7
-- SELECT t1_10.c_1_2, t1_10.c_1_3, t1_10.c_1_4, t1_10.c_1_1, t1_10.c_1_6, t1_10.c_1_5 FROM t1 AS t1_10 WHERE CASE  WHEN CAST(t1_10.c_1_2 AS BOOLEAN )  THEN false  WHEN  ( t1_10.c_1_4 ) > ( t1_10.c_1_4 )  THEN (((('')||(''))) IS NOT NULL)  WHEN false THEN false END GROUP BY t1_10.c_1_2, t1_10.c_1_3, t1_10.c_1_4, t1_10.c_1_1, t1_10.c_1_6, t1_10.c_1_5 UNION SELECT t1_10.c_1_2, t1_10.c_1_3, t1_10.c_1_4, t1_10.c_1_1, t1_10.c_1_6, t1_10.c_1_5 FROM t1 AS t1_10 WHERE (NOT (CASE  WHEN CAST(t1_10.c_1_2 AS BOOLEAN )  THEN false  WHEN  ( t1_10.c_1_4 ) > ( t1_10.c_1_4 )  THEN (((('')||(''))) IS NOT NULL)  WHEN false THEN false END)) GROUP BY t1_10.c_1_2, t1_10.c_1_3, t1_10.c_1_4, t1_10.c_1_1, t1_10.c_1_6, t1_10.c_1_5 UNION SELECT t1_10.c_1_2, t1_10.c_1_3, t1_10.c_1_4, t1_10.c_1_1, t1_10.c_1_6, t1_10.c_1_5 FROM t1 AS t1_10 WHERE ((CASE  WHEN CAST(t1_10.c_1_2 AS BOOLEAN )  THEN false  WHEN  ( t1_10.c_1_4 ) > ( t1_10.c_1_4 )  THEN (((('')||(''))) IS NOT NULL)  WHEN false THEN false END) IS NULL) GROUP BY t1_10.c_1_2, t1_10.c_1_3, t1_10.c_1_4, t1_10.c_1_1, t1_10.c_1_6, t1_10.c_1_5;
-- cardinality: 0

```

2. Query

```sql
-- The size of the result sets mismatch (7 and 0)!
-- SELECT t1_10.c_1_2, t1_10.c_1_3, t1_10.c_1_4, t1_10.c_1_1, t1_10.c_1_6, t1_10.c_1_5 FROM t1 AS t1_10 GROUP BY t1_10.c_1_2, t1_10.c_1_3, t1_10.c_1_4, t1_10.c_1_1, t1_10.c_1_6, t1_10.c_1_5;
-- cardinality: 7
-- SELECT t1_10.c_1_2, t1_10.c_1_3, t1_10.c_1_4, t1_10.c_1_1, t1_10.c_1_6, t1_10.c_1_5 FROM t1 AS t1_10 WHERE CASE  WHEN CAST(t1_10.c_1_2 AS BOOLEAN )  THEN false  WHEN  ( t1_10.c_1_4 ) > ( t1_10.c_1_4 )  THEN (((('')||(''))) IS NOT NULL)  WHEN false THEN false END GROUP BY t1_10.c_1_2, t1_10.c_1_3, t1_10.c_1_4, t1_10.c_1_1, t1_10.c_1_6, t1_10.c_1_5 UNION SELECT t1_10.c_1_2, t1_10.c_1_3, t1_10.c_1_4, t1_10.c_1_1, t1_10.c_1_6, t1_10.c_1_5 FROM t1 AS t1_10 WHERE (NOT (CASE  WHEN CAST(t1_10.c_1_2 AS BOOLEAN )  THEN false  WHEN  ( t1_10.c_1_4 ) > ( t1_10.c_1_4 )  THEN (((('')||(''))) IS NOT NULL)  WHEN false THEN false END)) GROUP BY t1_10.c_1_2, t1_10.c_1_3, t1_10.c_1_4, t1_10.c_1_1, t1_10.c_1_6, t1_10.c_1_5 UNION SELECT t1_10.c_1_2, t1_10.c_1_3, t1_10.c_1_4, t1_10.c_1_1, t1_10.c_1_6, t1_10.c_1_5 FROM t1 AS t1_10 WHERE ((CASE  WHEN CAST(t1_10.c_1_2 AS BOOLEAN )  THEN false  WHEN  ( t1_10.c_1_4 ) > ( t1_10.c_1_4 )  THEN (((('')||(''))) IS NOT NULL)  WHEN false THEN false END) IS NULL) GROUP BY t1_10.c_1_2, t1_10.c_1_3, t1_10.c_1_4, t1_10.c_1_1, t1_10.c_1_6, t1_10.c_1_5;
-- cardinality: 0
```
### Expected behavior (Required)
NO Error

### Real behavior (Required)
Error as follows
```
--sqlancer.Errors$CardinalityOfResultSetsMismatchError: -- The size of the result sets mismatch (7 and 0)!
---- SELECT t1_10.c_1_2, t1_10.c_1_3, t1_10.c_1_4, t1_10.c_1_1, t1_10.c_1_6, t1_10.c_1_5 FROM t1 AS t1_10 GROUP BY t1_10.c_1_2, t1_10.c_1_3, t1_10.c_1_4, t1_10.c_1_1, t1_10.c_1_6, t1_10.c_1_5;
---- cardinality: 7
---- SELECT t1_10.c_1_2, t1_10.c_1_3, t1_10.c_1_4, t1_10.c_1_1, t1_10.c_1_6, t1_10.c_1_5 FROM t1 AS t1_10 WHERE CASE  WHEN CAST(t1_10.c_1_2 AS BOOLEAN )  THEN false  WHEN  ( t1_10.c_1_4 ) > ( t1_10.c_1_4 )  THEN (((('')||(''))) IS NOT NULL)  WHEN false THEN false END GROUP BY t1_10.c_1_2, t1_10.c_1_3, t1_10.c_1_4, t1_10.c_1_1, t1_10.c_1_6, t1_10.c_1_5 UNION SELECT t1_10.c_1_2, t1_10.c_1_3, t1_10.c_1_4, t1_10.c_1_1, t1_10.c_1_6, t1_10.c_1_5 FROM t1 AS t1_10 WHERE (NOT (CASE  WHEN CAST(t1_10.c_1_2 AS BOOLEAN )  THEN false  WHEN  ( t1_10.c_1_4 ) > ( t1_10.c_1_4 )  THEN (((('')||(''))) IS NOT NULL)  WHEN false THEN false END)) GROUP BY t1_10.c_1_2, t1_10.c_1_3, t1_10.c_1_4, t1_10.c_1_1, t1_10.c_1_6, t1_10.c_1_5 UNION SELECT t1_10.c_1_2, t1_10.c_1_3, t1_10.c_1_4, t1_10.c_1_1, t1_10.c_1_6, t1_10.c_1_5 FROM t1 AS t1_10 WHERE ((CASE  WHEN CAST(t1_10.c_1_2 AS BOOLEAN )  THEN false  WHEN  ( t1_10.c_1_4 ) > ( t1_10.c_1_4 )  THEN (((('')||(''))) IS NOT NULL)  WHEN false THEN false END) IS NULL) GROUP BY t1_10.c_1_2, t1_10.c_1_3, t1_10.c_1_4, t1_10.c_1_1, t1_10.c_1_6, t1_10.c_1_5;
---- cardinality: 0
--	at sqlancer.ComparatorHelper.assumeResultSetsAreEqual(ComparatorHelper.java:105)
--	at sqlancer.starrocks.oracle.tlp.StarRocksTLPGroupByOracle.check(StarRocksTLPGroupByOracle.java:50)
--	at sqlancer.ProviderAdapter.generateAndTestDatabase(ProviderAdapter.java:55)
--	at sqlancer.Main$DBMSExecutor.run(Main.java:334)
--	at sqlancer.Main$2.run(Main.java:544)
--	at sqlancer.Main$2.runThread(Main.java:521)
--	at sqlancer.Main$2.run(Main.java:511)
--	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
--	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
--	at java.lang.Thread.run(Thread.java:748)
--
```
### StarRocks version (Required)
- main(225ba0d)

### PR DESCRIPTION
**Pull request by packy92**
Fixes #28902

### Problem
The `NegateFilterShuttle` doesn't process `constantOperator`, `CallOperator` correctly leading to a wrong rewrited result.

## What type of PR is this:
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [x] 3.0
  - [x] 2.5
  - [ ] 2.4

### CODE REVIEW

**Review by satanson — DISMISSED** [review]

**Review by Seaven — DISMISSED** [review]

**Review by liuyehcf — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 3 / 6 (50.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rewrite/scalar/NegateFilterShuttle.java|2|5|40.00%|[112, 113, 115]|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/scalar/ColumnRefOperator.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 6 / 6 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rewrite/scalar/NegateFilterShuttle.java|5|5|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/scalar/ColumnRefOperator.java|1|1|100.00%|[]|

**Review by liuyehcf — APPROVED** [review]

**Review by Seaven — APPROVED** [review]

**Review by satanson — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
