### PR TITLE
[Bugfix] fix init database failed in QueryDetail when executing multiple statements

### PR DESCRIPTION
**Pull request by stephen-shelby**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

When we send multiple external_catalog's queries by jdbc.  it will failed when init database in QueryDetail.

### CODE REVIEW

**Review by caneGuy — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 2 / 3 (66.67%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/QueryDetail.java|2|3|66.67%|

**Comment by stephen-shelby** [comment]
@Mergifyio backport branch-2.3

**Review by gengjun-git — APPROVED** [review]

**Comment by stephen-shelby** [comment]
run starrocks_fe_unittest

**Comment by stephen-shelby** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 2 / 3 (66.67%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/QueryDetail.java|2|3|66.67%|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 2 / 3 (66.67%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/QueryDetail.java|2|3|66.67%|

**Pull request merged**
