### PR TITLE
[BugFix] Fix FE dead lock bug where db lock and TabletInvertedIndex lock waiting for each other

### PR DESCRIPTION
**Pull request by gengjun-git**
backport #30703

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:disappointed: **fail** : 9 / 13 (69.23%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/leader/ReportHandler.java|6|9|66.67%|[1048, 1049, 1050]|
|:large_blue_circle:|com/starrocks/catalog/TabletInvertedIndex.java|3|4|75.00%|[221]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:disappointed: **fail** : 9 / 13 (69.23%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/leader/ReportHandler.java|6|9|66.67%|[1048, 1049, 1050]|
|:large_blue_circle:|com/starrocks/catalog/TabletInvertedIndex.java|3|4|75.00%|[221]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by Astralidea — APPROVED** [review]

**Pull request merged**
