### PR TITLE
[Cherry-Pick][BugFix] Insert plan required gather when select limit (#10080)

### PR DESCRIPTION
**Pull request by Seaven**
## What type of PR is this：
- [ ] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Review by wanpengfei-git — APPROVED** [review]

**Comment by Seaven** [comment]
run starrocks_fe_unittest

**Comment by Seaven** [comment]
run starrocks_fe_unittest

**Comment by Seaven** [comment]
run starrocks_fe_unittest

**Comment by Seaven** [comment]
run starrocks_tscancode

**Comment by Seaven** [comment]
run SonarCloud Code Analysis

**Review by kangkaisen — APPROVED** [review]

**Pull request merged**
