### PR TITLE
[Refactor] Extract BackendExecState from Coordinator

### PR DESCRIPTION
**Pull request by ZiheLiu**
Relates to #27846.

Extract `BackendExecState` from `Coordinator`. Use the state pattern and remove the related fields `isInitialized`, `hasCancelled`, `isDone`.
```java

/**
 * Maintain the single execution of a fragment instance.
 * Executions begin in the state CREATED and transition between states following this diagram:
 *
 * <pre>{@code
 * CREATED ────► DEPLOYING ────► EXECUTING ───► FINISHED
 *                  │                │
 *                  │                │
 *                  │                │
 *                  ├─► CANCELLING ◄─┤
 *                  │       │        │
 *                  │       │        │
 *                  │       ▼        │
 *                  └───► FAILED ◄───┘
 * }
 * </pre>
 * <p>
 * All the methods are thead-safe.
 * The {@link #state} and {@link #profile} are protected by {@code synchronized(this)}.
 */
```

## What type of PR is this:
- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [x] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 172 / 201 (85.57%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/scheduler/dag/ExecutionFragmentInstance.java|128|153|83.66%|[140, 145, 150, 163, 197, 258, 275, 277, 298, 299, 300, 301, 303, 304, 305, 351, 352, 353, 357, 358, 374, 375, 376, 377, 378]|
|:large_blue_circle:|com/starrocks/qe/DefaultCoordinator.java|44|48|91.67%|[804, 1666, 1667, 1670]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 176 / 208 (84.62%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/scheduler/dag/ExecutionFragmentInstance.java|128|153|83.66%|[140, 145, 150, 163, 197, 258, 275, 277, 298, 299, 300, 301, 303, 304, 305, 351, 352, 353, 357, 358, 374, 375, 376, 377, 378]|
|:large_blue_circle:|com/starrocks/qe/DefaultCoordinator.java|48|55|87.27%|[380, 804, 1228, 1344, 1666, 1667, 1670]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 176 / 208 (84.62%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/scheduler/dag/ExecutionFragmentInstance.java|128|153|83.66%|[140, 145, 150, 163, 197, 258, 275, 277, 298, 299, 300, 301, 303, 304, 305, 351, 352, 353, 357, 358, 374, 375, 376, 377, 378]|
|:large_blue_circle:|com/starrocks/qe/DefaultCoordinator.java|48|55|87.27%|[380, 804, 1228, 1344, 1666, 1667, 1670]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 178 / 210 (84.76%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/scheduler/dag/ExecutionFragmentInstance.java|128|153|83.66%|[140, 145, 150, 163, 197, 258, 275, 277, 298, 299, 300, 301, 303, 304, 305, 351, 352, 353, 357, 358, 374, 375, 376, 377, 378]|
|:large_blue_circle:|com/starrocks/qe/DefaultCoordinator.java|50|57|87.72%|[380, 804, 1228, 1344, 1666, 1667, 1670]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 51 / 58 (87.93%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/DefaultCoordinator.java|51|58|87.93%|[380, 804, 1228, 1344, 1666, 1667, 1670]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 186 / 210 (88.57%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/DefaultCoordinator.java|51|58|87.93%|[380, 804, 1228, 1344, 1666, 1667, 1670]|
|:large_blue_circle:|com/starrocks/qe/scheduler/dag/FragmentInstanceExecState.java|135|152|88.82%|[161, 166, 171, 184, 218, 315, 317, 383, 384, 385, 389, 390, 406, 407, 408, 409, 410]|

**Review by satanson — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 186 / 210 (88.57%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/DefaultCoordinator.java|51|58|87.93%|[380, 804, 1228, 1344, 1666, 1667, 1670]|
|:large_blue_circle:|com/starrocks/qe/scheduler/dag/FragmentInstanceExecState.java|135|152|88.82%|[161, 166, 171, 184, 218, 315, 317, 383, 384, 385, 389, 390, 406, 407, 408, 409, 410]|

**Review by Seaven — APPROVED** [review]

**Pull request merged**
