### PR TITLE
[Enhancement] Schemachange can convert from latest version for PK table

### LINKED ISSUE #31128: Schemachange can convert from latest version for PK table
## Enhancement
Currently, schemachange may fail if it executes to long and the specified version maybe GCed(default 30minutes), this means schemachange lasts over 30 minutes are likely to fail, this often happens for huge tables, wastes lot of resources and fails to get job done.
Actually, schemachange can convert from the lastest version rather than specified version, avoid the version GCed problem.

### PR DESCRIPTION
**Pull request by decster**
Fixes #31128

Currently, schema change may fail if it executes too long and the specified version maybe GCed(default 30 minutes), this means schema change that lasts over 30 minutes are likely to fail, which often happens for huge tables, wastes a lot of resources, and fails to get the job done.

This PR changes schema change behavior to convert from the base tablet's latest version rather than the specified version, avoiding the version GCed problem.

This PR also split UTs in tablet_updates_test, cause it's too large.

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.2
  - [x] 3.1
  - [x] 3.0
  - [x] 2.5

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 5 / 14 (35.71%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/storage/schema_change.cpp|5|14|35.71%|[796, 797, 798, 799, 800, 803, 804, 806, 807]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 5 / 14 (35.71%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/storage/schema_change.cpp|5|14|35.71%|[796, 797, 798, 799, 800, 803, 804, 806, 807]|

**Review by sevev — APPROVED** [review]

**Review by luohaha — APPROVED** [review]

**Review by Astralidea — APPROVED** [review]

**Review by chaoyli — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.2

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
