### PR TITLE
[Feature][Cherry-Pick] Unload data via table function (backport #30544)

### PR DESCRIPTION
**Pull request by letian-jiang**
This PR gives users a new way to unload data to remote storage, especially when data partitioning is required.

```sql
# Unpartitioned Data
INSERT INTO 
FILES(
    "path" = "s3://my_bucket/path/parquet_file/",
    "format" = "parquet",
    "compression" = "zstd"
) 
SELECT * FROM SOURCE;

# Partitioned Data
INSERT INTO 
FILES(
    "path" = "s3://my_bucket/path/parquet_file/",
    "format" = "parquet",
    "compression" = "zstd",
    "partition_by" = "dt"
) 
SELECT * FROM SOURCE;

# Single DataFile
INSERT INTO 
FILES(
    "path" = "s3://my_bucket/path/parquet_file/",
    "format" = "parquet",
    "compression" = "zstd"
    "single" = "true"
) 
SELECT * FROM SOURCE;
```

## What type of PR is this:

- [ ] BugFix
- [x] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [x] Yes, this PR will result in a change in behavior.
- [ ] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [x] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 161 / 197 (81.73%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/planner/DataSink.java|1|2|50.00%|[103]|
|:large_blue_circle:|com/starrocks/sql/InsertPlanner.java|7|13|53.85%|[272, 273, 303, 304, 639, 640]|
|:large_blue_circle:|com/starrocks/qe/CoordinatorPreprocessor.java|3|5|60.00%|[243, 244]|
|:large_blue_circle:|com/starrocks/planner/PlanFragment.java|3|5|60.00%|[296, 297]|
|:large_blue_circle:|com/starrocks/qe/StmtExecutor.java|9|14|64.29%|[1922, 1923, 1985, 1986, 2113]|
|:large_blue_circle:|com/starrocks/sql/analyzer/InsertAnalyzer.java|27|40|67.50%|[312, 319, 331, 334, 335, 336, 337, 342, 343, 344, 346, 350, 351]|
|:large_blue_circle:|com/starrocks/catalog/TableFunctionTable.java|23|28|82.14%|[126, 143, 144, 157, 363]|
|:large_blue_circle:|com/starrocks/planner/TableFunctionTableSink.java|23|25|92.00%|[61, 66]|
|:large_blue_circle:|com/starrocks/catalog/Table.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/OutFileClause.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/InsertStmt.java|62|62|100.00%|[]|
|:large_blue_circle:|com/starrocks/qe/scheduler/dag/FragmentInstance.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 161 / 197 (81.73%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/planner/DataSink.java|1|2|50.00%|[103]|
|:large_blue_circle:|com/starrocks/sql/InsertPlanner.java|7|13|53.85%|[272, 273, 303, 304, 639, 640]|
|:large_blue_circle:|com/starrocks/qe/CoordinatorPreprocessor.java|3|5|60.00%|[243, 244]|
|:large_blue_circle:|com/starrocks/planner/PlanFragment.java|3|5|60.00%|[296, 297]|
|:large_blue_circle:|com/starrocks/qe/StmtExecutor.java|9|14|64.29%|[1922, 1923, 1985, 1986, 2113]|
|:large_blue_circle:|com/starrocks/sql/analyzer/InsertAnalyzer.java|27|40|67.50%|[312, 319, 331, 334, 335, 336, 337, 342, 343, 344, 346, 350, 351]|
|:large_blue_circle:|com/starrocks/catalog/TableFunctionTable.java|23|28|82.14%|[126, 143, 144, 157, 363]|
|:large_blue_circle:|com/starrocks/planner/TableFunctionTableSink.java|23|25|92.00%|[61, 66]|
|:large_blue_circle:|com/starrocks/catalog/Table.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/OutFileClause.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/InsertStmt.java|62|62|100.00%|[]|
|:large_blue_circle:|com/starrocks/qe/scheduler/dag/FragmentInstance.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 1 / 30 (03.33%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/exec/data_sink.cpp|0|4|00.00%|[165, 166, 169, 170]|
|:large_blue_circle:|src/exec/parquet_writer.cpp|0|10|00.00%|[79, 80, 115, 118, 119, 120, 121, 128, 129, 132]|
|:large_blue_circle:|src/formats/parquet/file_writer.cpp|1|16|06.25%|[436, 437, 438, 439, 440, 473, 474, 475, 476, 479, 480, 482, 483, 484, 486]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 1 / 30 (03.33%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/exec/data_sink.cpp|0|4|00.00%|[165, 166, 169, 170]|
|:large_blue_circle:|src/exec/parquet_writer.cpp|0|10|00.00%|[79, 80, 115, 118, 119, 120, 121, 128, 129, 132]|
|:large_blue_circle:|src/formats/parquet/file_writer.cpp|1|16|06.25%|[436, 437, 438, 439, 440, 473, 474, 475, 476, 479, 480, 482, 483, 484, 486]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 1 / 30 (03.33%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/exec/data_sink.cpp|0|4|00.00%|[165, 166, 169, 170]|
|:large_blue_circle:|src/exec/parquet_writer.cpp|0|10|00.00%|[79, 80, 115, 118, 119, 120, 121, 128, 129, 132]|
|:large_blue_circle:|src/formats/parquet/file_writer.cpp|1|16|06.25%|[436, 437, 438, 439, 440, 473, 474, 475, 476, 479, 480, 482, 483, 484, 486]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 161 / 197 (81.73%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/planner/DataSink.java|1|2|50.00%|[103]|
|:large_blue_circle:|com/starrocks/sql/InsertPlanner.java|7|13|53.85%|[272, 273, 303, 304, 639, 640]|
|:large_blue_circle:|com/starrocks/qe/CoordinatorPreprocessor.java|3|5|60.00%|[243, 244]|
|:large_blue_circle:|com/starrocks/planner/PlanFragment.java|3|5|60.00%|[305, 306]|
|:large_blue_circle:|com/starrocks/qe/StmtExecutor.java|9|14|64.29%|[1935, 1936, 1998, 1999, 2126]|
|:large_blue_circle:|com/starrocks/sql/analyzer/InsertAnalyzer.java|27|40|67.50%|[312, 319, 331, 334, 335, 336, 337, 342, 343, 344, 346, 350, 351]|
|:large_blue_circle:|com/starrocks/catalog/TableFunctionTable.java|23|28|82.14%|[126, 143, 144, 157, 363]|
|:large_blue_circle:|com/starrocks/planner/TableFunctionTableSink.java|23|25|92.00%|[61, 66]|
|:large_blue_circle:|com/starrocks/catalog/Table.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/OutFileClause.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/InsertStmt.java|62|62|100.00%|[]|
|:large_blue_circle:|com/starrocks/qe/scheduler/dag/FragmentInstance.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 1 / 30 (03.33%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/exec/data_sink.cpp|0|4|00.00%|[165, 166, 169, 170]|
|:large_blue_circle:|src/exec/parquet_writer.cpp|0|10|00.00%|[79, 80, 115, 118, 119, 120, 121, 128, 129, 132]|
|:large_blue_circle:|src/formats/parquet/file_writer.cpp|1|16|06.25%|[436, 437, 438, 439, 440, 473, 474, 475, 476, 479, 480, 482, 483, 484, 486]|

**Review by packy92 — APPROVED** [review]

**Review by murphyatwork — APPROVED** [review]

**Pull request merged**
