### PR TITLE
[Enhancement] Add some necessary logs for external table

### PR DESCRIPTION
**Pull request by stephen-shelby**
## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by stephen-shelby** [comment]
run starrocks_admit_test

**Review by gengjun-git — APPROVED** [review]

**Review by Youngwb — APPROVED** [review]

**Comment by stephen-shelby** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 7 / 34 (20.59%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/connector/hive/events/DropPartitionEvent.java|0|11|00.00%|[46, 47, 48, 49, 88, 98, 99, 101, 102, 107, 108]|
|:large_blue_circle:|com/starrocks/connector/hive/events/AlterPartitionEvent.java|0|5|00.00%|[79, 95, 97, 113, 115]|
|:large_blue_circle:|com/starrocks/connector/hive/events/InsertEvent.java|0|3|00.00%|[87, 123, 124]|
|:large_blue_circle:|com/starrocks/connector/hive/events/MetastoreEventFactory.java|0|6|00.00%|[114, 118, 123, 125, 127, 139]|
|:large_blue_circle:|com/starrocks/connector/CachingRemoteFileIO.java|1|2|50.00%|[60]|
|:large_blue_circle:|com/starrocks/connector/hive/CachingHiveMetastore.java|2|3|66.67%|[339]|
|:large_blue_circle:|com/starrocks/connector/PartitionUtil.java|4|4|100.00%|[]|

**Comment by stephen-shelby** [comment]
run starrocks_clang-tidy

**Pull request merged**
