### PR TITLE
[BugFix] rewrite query by using mv's binary predicate with no typecas…

### PR DESCRIPTION
**Pull request by huangfeng1993**
https://hsn4s18zbn.feishu.cn/docx/YlMfdi7A8omV5Vx6bk5cCYsynxh

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/EquationRewriter.java|1|1|100.00%|[]|

**Comment by LiShuMing** [comment]
image

can you fix the sonar checks?

**Review by murphyatwork — DISMISSED** [review]

**Review by kangkaisen — DISMISSED** [review]

**Comment by mofeiatwork** [comment]
@Mergifyio rebase

**Comment by mofeiatwork** [comment]
@Mergifyio rebase

**Review by murphyatwork — APPROVED** [review]

**Review by dirtysalt — APPROVED** [review]

**Comment by mofeiatwork** [comment]
@Mergifyio backport branch-2.5 branch-3.0

**Pull request merged**
