### PR TITLE
[Enhancement] display table names when show colocate group info

### PR DESCRIPTION
**Pull request by packy92**
Add colocate table names col like:
```
mysql> show proc '/colocation_group';
+-------------+-----------------+----------------------------+------------------+------------+----------------+----------------------+----------+
| GroupId     | GroupName       | TableIds                   | TableNames       | BucketsNum | ReplicationNum | DistCols             | IsStable |
+-------------+-----------------+----------------------------+------------------+------------+----------------+----------------------+----------+
| 91023.91027 | 91023_group1    | 91025, 91039, 91052, 91065 | t1, t2, t3, t4   | 5          | 1              | int(11), varchar(20) | true     |
| 40011.53215 | 40011_cg_group1 | 53213, 63611, 74008        | EKPO, RSEG, EKKO | 5197       | 1              | int(11)              | true     |
| 40011.44022 | 40011_g2        | 44020                      | test_fifa_month  | 160        | 1              | varchar(65533)       | true     |
+-------------+-----------------+----------------------------+------------------+------------+----------------+----------------------+----------+
3 rows in set (0.00 sec)
```

## What type of PR is this:
- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [x] 3.0
  - [x] 2.5
  - [ ] 2.4

### CODE REVIEW

**Review by satanson — APPROVED** [review]

**Review by Seaven — APPROVED** [review]

**Review by gengjun-git — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 16 / 16 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/common/proc/ColocationGroupProcDir.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/ColocateTableIndex.java|15|15|100.00%|[]|

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
