### PR TITLE
[Feature] Support ssl for mysql protocol

### PR DESCRIPTION
**Pull request by gengjun-git**
## What type of PR is this：
- [ ] BugFix
- [x] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

This PR provides the ssl interface framework. Users can implement SSLChannel and put the jar to fe/lib directory to support ssl encryption.

There are three config params to enable ssl, `ssl_keystore_location`, `ssl_keystore_password`, `ssl_key_password`. Users can generate ssl keys using the command 
`keytool -genkeypair -alias starrocks -keypass starrocks -keyalg RSA -keysize 1024 -validity 365 -keystore starrocks.jks -storepass starrocks`
 - `-keystore` specify generated keystore file name, set this file path to `ssl_keystore_location`
 - `-storepass` specify the keystore file password, set this password to `ssl_keystore_password`
 - `-keypass` sepecify the private key password, set this password to `ssl_key_password`

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

### CODE REVIEW

**Comment by nshangyiming** [comment]
fe unit test failed

**Review by nshangyiming — DISMISSED** [review]

**Review by Astralidea — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by gengjun-git** [comment]
run starrocks_fe_unittest

**Comment by gengjun-git** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 53 / 118 (44.92%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/mysql/ssl/SSLChannelImpClassLoader.java|0|17|00.00%|[14, 15, 17, 22, 23, 26, 27, 28, 29, 32, 33, 34, 35, 36, 37, 38, 39]|
|:large_blue_circle:|com/starrocks/qe/QeService.java|4|15|26.67%|[48, 49, 54, 76, 77, 78, 80, 81, 83, 84, 85]|
|:large_blue_circle:|com/starrocks/mysql/MysqlChannel.java|13|32|40.62%|[138, 141, 146, 147, 151, 152, 154, 155, 156, 157, 160, 161, 162, 163, 164, 165, 170, 206, 249]|
|:large_blue_circle:|com/starrocks/mysql/MysqlProto.java|10|24|41.67%|[127, 128, 129, 130, 131, 132, 134, 138, 139, 140, 226, 230, 231, 232]|
|:large_blue_circle:|com/starrocks/mysql/MysqlHandshakePacket.java|3|5|60.00%|[76, 77]|
|:large_blue_circle:|com/starrocks/mysql/MysqlAuthPacket.java|2|3|66.67%|[89]|
|:large_blue_circle:|com/starrocks/qe/ConnectContext.java|6|7|85.71%|[635]|
|:large_blue_circle:|com/starrocks/mysql/nio/AcceptListener.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/common/Config.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/common/ErrorCode.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/mysql/nio/NMysqlServer.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/mysql/MysqlCapability.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/mysql/nio/NConnectContext.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/mysql/nio/NMysqlChannel.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/mysql/MysqlServer.java|3|3|100.00%|[]|

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 57 / 120 (47.50%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/mysql/ssl/SSLChannelImpClassLoader.java|0|17|00.00%|[14, 15, 17, 22, 23, 26, 27, 28, 29, 32, 33, 34, 35, 36, 37, 38, 39]|
|:large_blue_circle:|com/starrocks/qe/QeService.java|4|15|26.67%|[48, 49, 54, 76, 77, 78, 80, 81, 83, 84, 85]|
|:large_blue_circle:|com/starrocks/qe/ConnectContext.java|6|19|31.58%|[652, 653, 654, 655, 659, 660, 661, 662, 664, 665, 667, 668, 669]|
|:large_blue_circle:|com/starrocks/mysql/MysqlProto.java|10|24|41.67%|[127, 128, 129, 130, 131, 132, 134, 138, 139, 140, 226, 230, 231, 232]|
|:large_blue_circle:|com/starrocks/mysql/MysqlHandshakePacket.java|3|5|60.00%|[76, 77]|
|:large_blue_circle:|com/starrocks/mysql/MysqlAuthPacket.java|2|3|66.67%|[89]|
|:large_blue_circle:|com/starrocks/mysql/MysqlChannel.java|13|18|72.22%|[135, 136, 140, 176, 219]|
|:large_blue_circle:|com/starrocks/mysql/nio/AcceptListener.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/common/Config.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/common/ErrorCode.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/mysql/nio/NMysqlServer.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/mysql/MysqlCapability.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/mysql/nio/NConnectContext.java|5|5|100.00%|[]|
|:large_blue_circle:|com/starrocks/mysql/nio/NMysqlChannel.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/mysql/MysqlServer.java|3|3|100.00%|[]|

**Review by Astralidea — APPROVED** [review]

**Review by meegoo — APPROVED** [review]

**Pull request merged**
