### PR TITLE
[BugFix] Fix checking of apply stopped in _wait_for_version

### LINKED ISSUE #17848: [BugFix] wait_for_version failed apply stopped error when query
### Real behavior (Required)

```
I0215 07:58:08.132460 44166 tablet_updates.cpp:1051] apply_rowset_commit finish. tablet:732297 version:136060 txn_id: 555687 total del/row:0/2027 0% rowset:269 #seg:0 #op(upsert:0 del:0) #del:0+0=0 #dv:0 duration:0ms(0/0/0/0)
I0215 07:58:08.517830 44181 tablet_updates.cpp:1051] apply_rowset_commit finish. tablet:732297 version:136061 txn_id: 555689 total del/row:0/2027 0% rowset:270 #seg:0 #op(upsert:0 del:0) #del:0+0=0 #dv:0 duration:0ms(0/0/0/0)
W0215 07:58:09.366883 37429 internal_service.cpp:189] exec multi plan fragments failed, errmsg=wait_for_version version:136062 failed: apply stopped tablet:732297 #version:272 [135792.1 136061@270 136062] pending: rowsets:235[id/seg/row/del/byte/compaction]: [37/0/0/0/0/32.00 MB],[38/1/2027/0/1.87 MB/30.13 MB],[39/0/0/0/0/32.00 MB],[40/0/0/0/0/32.00 MB],[41/0/0/0/0/32.00 MB],[42/0/0/0/0/32.00 MB],[43/0/0/0/0/32.00 MB],[44/0/0/0/0/32.00 MB],[45/0/0/0/0/32.00 MB],[46/0/0/0/0/32.00 MB],[47/0/0/0/0/32.00 MB]...,[263/0/0/0/0/32.00 MB],[264/0/0/0/0/32.00 MB],[265/0/0/0/0/32.00 MB],[266/0/0/0/0/32.00 MB],[267/0/0/0/0/32.00 MB],[268/0/0/0/0/32.00 MB],[269/0/0/0/0/32.00 MB],[270/0/0/0/0/32.00 MB],[271/0/0/0/0/32.00 MB]
I0215 07:58:10.375375 44209 tablet_updates.cpp:1051] apply_rowset_commit finish. tablet:732297 version:136062 txn_id: 555688 total del/row:0/2027 0% rowset:271 #seg:0 #op(upsert:0 del:0) #del:0+0=0 #dv:0 duration:0ms(0/0/0/0)
I0215 07:58:10.375463 44209 tablet_updates.cpp:1051] apply_rowset_commit finish. tablet:732297 version:136063 txn_id: 555690 total del/row:0/2027 0% rowset:272 #seg:0 #op(upsert:0 del:0) #del:0+0=0 #dv:0 duration:0ms(0/0/0/0)

```
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by decster**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #17848

## Problem Summary(Required) ：

The checking of apply stopped in _wait_for_version uses the wrong variable `_apply_running`, should use _apply_stopped.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 2.5
  - [x] 2.4
  - [x] 2.3
  - [ ] 2.2

### CODE REVIEW

**Review by chaoyli — APPROVED** [review]

**Review by Astralidea — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.4

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.3

**Pull request merged**
