### PR TITLE
[Doc] Can't use time_slice for date with time(hour/minute/second)

### PR DESCRIPTION
**Pull request by tomscut**
## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [x] Doc
- [ ] Tool

## Problem Summary(Required) ：
Now, we can't use time_slice for date with time(hour/minute/second). But the document is stale, we should update it.
image

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

### CODE REVIEW

**Review by fzhedu — APPROVED** [review]
LGTM

**Review by Seaven — APPROVED** [review]

**Comment by Pslydhh** [comment]
> ## What type of PR is this：
> * [ ]  BugFix
> * [ ]  Feature
> * [ ]  Enhancement
> * [ ]  Refactor
> * [ ]  UT
> * [x]  Doc
> * [ ]  Tool
> 
> ## Problem Summary(Required) ：
> Now, we can't use time_slice for date with time(hour/minute/second). But the document is stale, we should update it. image
> 
> ## Checklist:
> * [ ]  I have added test cases for my bug fix or my new feature
> * [ ]  This pr will affect users' behaviors
> * [ ]  This pr needs user documentation (for new or modified features or behaviors)
>   
>   * [ ]  I have added documentation for my new feature or new function

This is a previous issue, caused by use It as DATE type.
Now, We could execute it without report errors(Use **time_slice** for DATETIME/ Use **date_slice** for DATE)

**Comment by Pslydhh** [comment]
> > ## What type of PR is this：
> > 
> > * [ ]   BugFix
> > * [ ]   Feature
> > * [ ]   Enhancement
> > * [ ]   Refactor
> > * [ ]   UT
> > * [x]   Doc
> > * [ ]   Tool
> > 
> > ## Problem Summary(Required) ：
> > Now, we can't use time_slice for date with time(hour/minute/second). But the document is stale, we should update it. image
> > ## Checklist:
> > 
> > * [ ]   I have added test cases for my bug fix or my new feature
> > * [ ]   This pr will affect users' behaviors
> > * [ ]   This pr needs user documentation (for new or modified features or behaviors)
> >   
> >   * [ ]   I have added documentation for my new feature or new function
> 
> This is a previous issue, caused by use It as DATE type. Now, We could execute it without report errors(Use **time_slice** for DATETIME/ Use **date_slice** for DATE).

**Comment by Seaven** [comment]
@tomscut Hi, the feature supported in 2.3+, check your starrocks version plz?

**Comment by tomscut** [comment]
Thanks @Seaven and @Pslydhh . I ran it on the latest version and there were no problems. I will close this PR.

**Pull request closed without merging**
