### PR TITLE
[BugFix] Fix the wrong IS_NULLABLE result of system table

### LINKED ISSUE #27572: the wrong IS_NULLABLE result of system table
### Steps to reproduce the behavior (Required)
create table pk_test_null (
    name string NOT NULL,
    age int NULL
) PRIMARY KEY (name)
DISTRIBUTED BY HASH(name) BUCKETS 4
PROPERTIES("replication_num" = "1",
"enable_persistent_index" = "true");

SELECT * FROM INFORMATION_SCHEMA.COLUMNS where TABLE_NAME = 'pk_test_null';

### Expected behavior (Required)
return YES of `IS_NULLABLE` for `age`

### Real behavior (Required)
image

### StarRocks version (Required)
main branch

### PR DESCRIPTION
**Pull request by miomiocat**
Fixes #27572 

## What type of PR is this:
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [x] 3.0
  - [x] 2.5
  - [ ] 2.4

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 0 / 1 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/service/FrontendServiceImpl.java|0|1|00.00%|[919]|

**Review by Astralidea — APPROVED** [review]

**Review by gengjun-git — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 0 / 1 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/service/FrontendServiceImpl.java|0|1|00.00%|[919]|

**Pull request merged**
