### PR TITLE
[Enhancement] Replace Boolean to Tinyint for semi-type's null

### PR DESCRIPTION
**Pull request by Seaven**
Fixes #issue

Before (st1 is `NULL Struct`, st is `NOT NULL Struct`)
image

After (st is `NULL Struct`, st1 is `NOT NULL Struct`)
image

## What type of PR is this:
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by imay — APPROVED** [review]

**Review by chaoyli — APPROVED** [review]

**Comment by imay** [comment]
@Seaven I think we need to backport this to version 3.1

**Comment by Seaven** [comment]
backport branch-3.1 @mergify

**Comment by Seaven** [comment]
@mergify backport branch-3.1

**Pull request merged**
