### PR TITLE
[StarRocks On ES] fix wanOnly value always return false when FE restart

### PR DESCRIPTION
**Pull request by RowenWoo**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #

### CODE REVIEW

**Review by DorianZheng — DISMISSED** [review]
LGTM

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 0 / 1 (00.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/EsTable.java|0|1|00.00%|

**Review by imay — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 1 / 2 (50.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/EsTable.java|1|2|50.00%|

**Comment by RowenWoo** [comment]
@stdpain Plz check this PR

**Review by imay — APPROVED** [review]

**Review by stdpain — APPROVED** [review]

**Comment by RowenWoo** [comment]
@mofeiatwork backport branch-2.3

**Comment by RowenWoo** [comment]
https://github.com/Mergifyio backport branch-2.3

**Pull request merged**
