### PR TITLE
[BugFix] Fix bug add plugin has intermediate state

### LINKED ISSUE #20468: The plugin can neither be installed nor deleted
### Steps to reproduce the behavior (Required)

mysql> install plugin from "/home/astralidea/soft/AuditLoader/2.4/auditloader.zip";
ERROR 1064 (HY000): Unexpected exception: Plugin AuditLoader has already been installed.
mysql> install plugin from "/home/astralidea/soft/AuditLoader/2.4/auditloader.zip";
ERROR 1064 (HY000): Unexpected exception: Plugin AuditLoader has already been installed.
mysql> uninstall plugin AuditLoader;
ERROR 1064 (HY000): Unexpected exception: Plugin AuditLoader does not exist

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
2.3~3.0

### PR DESCRIPTION
**Pull request by Astralidea**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #20468

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 3.0
  - [x] 2.5
  - [x] 2.4
  - [x] 2.3

### CODE REVIEW

**Review by ABingHuang — APPROVED** [review]

**Review by imay — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.4

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.3

**Pull request merged**
