### PR TITLE
[SR SQL Planner Summer Camp] Support create table like in new parser

### PR DESCRIPTION
**Pull request by xlwh**
## What type of PR is this：
- [ ] bug
- [x] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #7938

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 20 / 27 (74.07%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/ast/AstVisitor.java|0|1|00.00%|
|:large_blue_circle:|com/starrocks/analysis/CreateTableLikeStmt.java|3|5|60.00%|
|:large_blue_circle:|com/starrocks/sql/analyzer/PrivilegeChecker.java|5|7|71.43%|
|:large_blue_circle:|com/starrocks/sql/analyzer/CreateTableLikeAnalyzer.java|7|9|77.78%|
|:large_blue_circle:|com/starrocks/sql/analyzer/Analyzer.java|2|2|100.00%|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|3|3|100.00%|

**Comment by xlwh** [comment]
run starrocks_fe_unittest

**Review by HangyuanLiu — APPROVED** [review]

**Comment by HangyuanLiu** [comment]
run starrocks_fe_unittest

**Comment by xlwh** [comment]
run starrocks_fe_unittest

**Comment by xlwh** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 20 / 27 (74.07%)




#### file detail

|   |path|covered line|new line|coverage|not covered line detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/ast/AstVisitor.java|0|1|00.00%|[175]|
|:large_blue_circle:|com/starrocks/analysis/CreateTableLikeStmt.java|3|5|60.00%|[70, 79]|
|:large_blue_circle:|com/starrocks/sql/analyzer/PrivilegeChecker.java|5|7|71.43%|[141, 146]|
|:large_blue_circle:|com/starrocks/sql/analyzer/CreateTableLikeAnalyzer.java|7|9|77.78%|[13, 22]|
|:large_blue_circle:|com/starrocks/sql/analyzer/Analyzer.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|3|3|100.00%|[]|

**Review by imay — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Pull request merged**
