### PR TITLE
[BugFix] Fix limit offset bugs

### PR DESCRIPTION
**Pull request by Seaven**
Fixes #issue

* compute offset error, the result should be 0 rows, but 10 rows now
```
MySQL td> explain select count(*) from (select * from (select * from t0 limit 10) x limit 10, 10) xx;
+---------------------------------+
| Explain String                  |
+---------------------------------+
| PLAN FRAGMENT 0                 |
|  OUTPUT EXPRS:4: count          |
|   PARTITION: UNPARTITIONED      |
|                                 |
|   RESULT SINK                   |
|                                 |
|   3:AGGREGATE (update finalize) |
|   |  output: count(*)           |
|   |  group by:                  |
|   |                             |
|   2:MERGING-EXCHANGE            |
|      offset: 10                 |
|      limit: 10                  |
|                                 |
| PLAN FRAGMENT 1                 |
|  OUTPUT EXPRS:                  |
|   PARTITION: RANDOM             |
|                                 |
|   STREAM DATA SINK              |
|     EXCHANGE ID: 02             |
|     UNPARTITIONED               |
|                                 |
|   1:Project                     |
|   |  <slot 9> : 1               |
|   |  limit: 20                  |
|   |                             |
|   0:OlapScanNode                |
|      TABLE: t0                  |
|      PREAGGREGATION: ON         |
|      partitions=0/1             |
|      rollup: t0                 |
|      tabletRatio=0/0            |
|      tabletList=                |
|      cardinality=1              |
|      avgRowSize=2.0             |
|      limit: 20                  |
+---------------------------------+
36 rows in set
Time: 1.384s
```

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 0 / 10 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/exec/exchange_node.cpp|0|1|00.00%|[257]|
|:large_blue_circle:|src/runtime/sorted_chunks_merger.cpp|0|9|00.00%|[370, 371, 372, 383, 384, 385, 387, 392, 394]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 4 / 4 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/MergeLimitWithLimitRule.java|4|4|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 0 / 10 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/exec/exchange_node.cpp|0|1|00.00%|[257]|
|:large_blue_circle:|src/runtime/sorted_chunks_merger.cpp|0|9|00.00%|[370, 371, 372, 383, 384, 385, 387, 392, 394]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 4 / 4 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/MergeLimitWithLimitRule.java|4|4|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 2 / 13 (15.38%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/exec/exchange_node.cpp|0|1|00.00%|[257]|
|:large_blue_circle:|src/runtime/sorted_chunks_merger.cpp|1|11|09.09%|[350, 370, 371, 372, 383, 384, 385, 387, 392, 394]|
|:large_blue_circle:|src/runtime/sorted_chunks_merger.h|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 3 / 17 (17.65%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/exec/exchange_node.cpp|0|1|00.00%|[257]|
|:large_blue_circle:|src/runtime/sorted_chunks_merger.cpp|1|14|07.14%|[350, 370, 371, 383, 384, 385, 386, 388, 393, 394, 396, 400, 401]|
|:large_blue_circle:|src/runtime/sorted_chunks_merger.h|2|2|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 4 / 4 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/MergeLimitWithLimitRule.java|4|4|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 3 / 17 (17.65%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/exec/exchange_node.cpp|0|1|00.00%|[257]|
|:large_blue_circle:|src/runtime/sorted_chunks_merger.cpp|1|14|07.14%|[350, 370, 371, 383, 384, 385, 386, 388, 393, 394, 396, 400, 401]|
|:large_blue_circle:|src/runtime/sorted_chunks_merger.h|2|2|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 4 / 4 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/MergeLimitWithLimitRule.java|4|4|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by packy92 — APPROVED** [review]

**Review by kangkaisen — APPROVED** [review]

**Comment by Seaven** [comment]
@mergify backport branch-3.2

**Pull request merged**
