### PR TITLE
[Enhancement] Refactor iceberg connector on fe [stage 1]

### PR DESCRIPTION
**Pull request by stephen-shelby**
## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #
ref https://github.com/StarRocks/starrocks/issues/18560

## Problem Summary(Required) ：

update some connector metadata interface in order to adapt iceberg to current query level metadata cache in fe.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 3.0
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Comment by stephen-shelby** [comment]
run starrocks_admit_test

**Review by Youngwb — DISMISSED** [review]

**Review by Astralidea — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by stephen-shelby** [comment]
run starrocks_fe_unittest

**Comment by stephen-shelby** [comment]
run starrocks_admit_test

**Comment by stephen-shelby** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 10 / 23 (43.48%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/connector/iceberg/IcebergMetadata.java|0|2|00.00%|[159, 168]|
|:large_blue_circle:|com/starrocks/connector/hudi/HudiMetadata.java|0|5|00.00%|[147, 150, 163, 167, 168]|
|:large_blue_circle:|com/starrocks/connector/RemoteFileDesc.java|1|5|20.00%|[48, 49, 50, 91]|
|:large_blue_circle:|com/starrocks/connector/RemoteFileInfo.java|1|3|33.33%|[34, 35]|
|:large_blue_circle:|com/starrocks/connector/hive/HiveMetadata.java|5|5|100.00%|[]|
|:large_blue_circle:|com/starrocks/server/MetadataMgr.java|3|3|100.00%|[]|

**Review by Astralidea — APPROVED** [review]

**Review by ZiheLiu — APPROVED** [review]

**Comment by stephen-shelby** [comment]
@Mergifyio backport branch-3.0

**Pull request merged**
