### PR TITLE
[Bugfix] Fix bug check pendingTask in concurrency

### LINKED ISSUE #10761: Task framework pendingTaskRun in concurrency
### Steps to reproduce the behavior (Required)
2022-09-02 00:37:26,472 WARN (starrocks-mysql-nio-pool-45|2364) [StmtExecutor.handleDdlStmt():1027] DDL statement(CREATE MATERIALIZED VIEW mv9
                             PARTITION BY date_trunc('month',k1)
                             DISTRIBUTED BY HASH(k1) BUCKETS 10
                             REFRESH ASYNC
                             AS SELECT k1, k6, k7, k8, k9, k10
                             FROM duplicate_table_with_null_partition;) process failed.
java.lang.NullPointerException: null
        at com.starrocks.scheduler.TaskRunManager.submitTaskRun(TaskRunManager.java:54) ~[starrocks-fe.jar:?]
        at com.starrocks.scheduler.TaskManager.executeTask(TaskManager.java:274) ~[starrocks-fe.jar:?]
        at com.starrocks.scheduler.TaskManager.executeTask(TaskManager.java:266) ~[starrocks-fe.jar:?]
        at com.starrocks.server.LocalMetastore.createTaskForMaterializedView(LocalMetastore.java:3311) ~[starrocks-fe.jar:?]
        at com.starrocks.server.LocalMetastore.createMaterializedView(LocalMetastore.java:3291) ~[starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.createMaterializedView(GlobalStateMgr.java:2704) ~[starrocks-fe.jar:?]
        at com.starrocks.execution.CreateMaterializedViewStatementExecutor.execute(CreateMaterializedViewStatementExecutor.java:14) ~[starrocks-fe.jar:?]
        at com.starrocks.execution.DataDefinitionExecutorFactory.execute(DataDefinitionExecutorFactory.java:163) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.handleDdlStmt(StmtExecutor.java:1005) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:454) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:312) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:427) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:665) ~[starrocks-fe.jar:?]
        at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:55) ~[starrocks-fe.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by Astralidea**
## What type of PR is this：
- [x] bugfix
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #10761

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/scheduler/TaskRunManager.java|2|2|100.00%|[]|

**Review by gengjun-git — APPROVED** [review]

**Review by wyb — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by Astralidea** [comment]
run starrocks_admit_test

**Comment by Astralidea** [comment]
@Mergifyio backport branch-2.4 branch-2.3

**Pull request merged**
