### PR TITLE
[BugFix] Fix query rewrite based on MV failed after refresh MV

### LINKED ISSUE #17066: Can not query rewrite after refresh mv
### Steps to reproduce the behavior (Required)
```
CREATE MATERIALIZED VIEW mv1 DISTRIBUTED BY HASH(col_date) BUCKETS 10                     
PROPERTIES ("force_external_table_query_rewrite"="true") AS 
SELECT col_date, PERCENTILE_UNION(percentile_hash(col_smallint)) as percentile_smallint,  
HLL_UNION(hll_hash(col_int)) as hll_int, BITMAP_UNION(to_bitmap(col_integer)) as bitmap_big_int                        
FROM hive_catalog.hive_extbl_test.hive_hdfs_csv_nocompress GROUP
BY col_date;

REFRESH MATERIALIZED VIEW mv1;

explain SELECT col_date, PERCENTILE_UNION(percentile_hash(col_smallint)) as percentile_smallint,                        HLL_UNION(hll_hash(col_int)) as hll_int, BITMAP_UNION(to_bitmap(col_integer)) as bitmap_big_int                        FROM hive_catalog.hive_extbl_test.hive_hdfs_csv_nocompress GROUP BY col_date;
```

### Expected behavior (Required)
query rewrite success

### Real behavior (Required)
img_v2_605e2056-59eb-40b6-8e34-926609ea568g

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by Youngwb**
Signed-off-by: Youngwb <yangwenbo_mailbox@163.com>

## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #17066 

## Problem Summary(Required) ：

**problem**: 
query rewrite failed aftre refresh mv, and can rewrite successfully a few seconds later.
**reason**:
In refresh mv task, we would refresh external table to get latest data, but refresh table will generate a new table which lost  relatedMaterializedViews info, we should add it after refresh table.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Review by stephen-shelby — APPROVED** [review]

**Review by ABingHuang — APPROVED** [review]
LGTM

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 7 / 7 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/scheduler/PartitionBasedMaterializedViewRefreshProcessor.java|7|7|100.00%|[]|

**Comment by Youngwb** [comment]
run starrocks_admit_test

**Comment by Youngwb** [comment]
run starrocks_admit_test

**Comment by Youngwb** [comment]
run starrocks_admit_test

**Comment by Youngwb** [comment]
run starrocks_admit_test

**Comment by Youngwb** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
