### PR TITLE
[BugFix]  Be maybe crash if upgrade from version 2.2 to version 2.4 

### LINKED ISSUE #13699: Be crash update from version2.2.1 to version2.4
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
2. INSERT INTO '....'
3. SELECT  '....'

### Real behavior (Required)
image

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by sevev**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes https://github.com/StarRocks/starrocks/issues/13699

## Problem Summary(Required) ：

If you upgrade directly from version 2.2 to 2.4, the PrimaryKey table compaction may cause be crash. Because in version 2.2, a pure delete data load of primary key will create a empty rowset with empty segment and version 2.4 will get a NPE while doing update compaction.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

### CODE REVIEW

**Comment by sevev** [comment]
run starrocks_admit_test

**Comment by sevev** [comment]
run starrocks_admit_test

**Comment by sevev** [comment]
run starrocks_admit_test

**Review by chaoyli — DISMISSED** [review]

**Comment by sevev** [comment]
run starrocks_admit_test

**Review by decster — APPROVED** [review]

**Review by chaoyli — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by sevev** [comment]
@mergify backport branch-2.4

**Comment by sevev** [comment]
@mergify backport branch-2.5

**Pull request merged**
