### PR TITLE
[BugFix] Fix metrics api concurrent bug

### PR DESCRIPTION
**Pull request by gengjun-git**
Fixes
```
2023-08-21 14:05:20,014 WARN (nioEventLoopGroup-4-9|246) [RestBaseAction.handleRequest():85] fail to process url: /metrics
java.util.ConcurrentModificationException: null
        at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719) ~[?:1.8.0_292]
        at java.util.LinkedHashMap$LinkedValueIterator.next(LinkedHashMap.java:747) ~[?:1.8.0_292]
        at com.google.common.collect.StandardTable.size(StandardTable.java:123) ~[spark-dpp-1.0.0.jar:?]
        at com.google.common.collect.HashBasedTable.size(HashBasedTable.java:49) ~[spark-dpp-1.0.0.jar:?]
        at com.starrocks.catalog.TabletInvertedIndex.getReplicaCount(TabletInvertedIndex.java:863) ~[starrocks-fe.jar:?]
        at com.starrocks.metric.MetricRepo$14.getValue(MetricRepo.java:543) ~[starrocks-fe.jar:?]
        at com.starrocks.metric.MetricRepo$14.getValue(MetricRepo.java:540) ~[starrocks-fe.jar:?]
        at com.starrocks.metric.PrometheusMetricVisitor.visit(PrometheusMetricVisitor.java:194) ~[starrocks-fe.jar:?]
        at com.starrocks.metric.MetricRepo.getMetric(MetricRepo.java:874) ~[starrocks-fe.jar:?]
        at com.starrocks.http.rest.MetricsAction.execute(MetricsAction.java:107) ~[starrocks-fe.jar:?]
        at com.starrocks.http.rest.RestBaseAction.handleRequest(RestBaseAction.java:75) ~[starrocks-fe.jar:?]
        at com.starrocks.http.HttpServerHandler.channelRead(HttpServerHandler.java:99) ~[starrocks-fe.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.87.Fi
```

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [x] 3.0
  - [x] 2.5
  - [ ] 2.4

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 6 / 6 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/TabletInvertedIndex.java|6|6|100.00%|[]|

**Review by Astralidea — APPROVED** [review]

**Review by sduzh — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
