### PR TITLE
[BugFix] filter invalid plan generated by reorder algorithm

### LINKED ISSUE #14257: [sqlsmith] unknown error of IllegalStateException
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
2. INSERT INTO '....'
3. SELECT  '....'

```sql
select  
  ref_0.N_NAME as c0, 
  case when ref_3.d_weekend > ref_3.d_following_holiday then ref_1.cd_dep_college_count else ref_1.cd_dep_college_count end
     as c1
from 
  sqlsmith.tpch_100g_nation as ref_0
            inner join sqlsmith.tpcds_100g_customer_demographics as ref_1
            on (ref_0.N_REGIONKEY = ref_1.cd_demo_sk )
          left join sqlsmith.t2 as ref_2
          on (ref_0.N_NATIONKEY = ref_2.c1 )
        inner join sqlsmith.tpcds_100g_date_dim as ref_3
        on (ref_1.cd_dep_college_count = ref_3.d_date_sk )
      inner join sqlsmith.tpcds_100g_ship_mode as ref_4
      on (ref_1.cd_credit_rating = ref_4.sm_ship_mode_id )
    left join sqlsmith.tpch_100g_supplier as ref_5
    on (ref_2.c2 = ref_5.S_SUPPKEY )
where cast(coalesce(ref_3.d_following_holiday,
    ref_0.N_NAME) as VARCHAR) = ref_5.S_ADDRESS
limit 56;
```

### Expected behavior (Required)
no unknown error

### Real behavior (Required)
ERROR 1064 (HY000): Unknown error

fe.log:
java.lang.IllegalStateException: null
        at com.google.common.base.Preconditions.checkState(Preconditions.java:494) ~[spark-dpp-1.0.0.jar:?]
        at com.starrocks.sql.optimizer.statistics.Statistics.getColumnStatistic(Statistics.java:56) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.ExpressionStatisticCalculator$ExpressionStatisticVisitor.visitVariableReference(ExpressionStatisticCalculator.java:63) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.ExpressionStatisticCalculator$ExpressionStatisticVisitor.visitVariableReference(ExpressionStatisticCalculator.java:42) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.operator.scalar.ColumnRefOperator.accept(ColumnRefOperator.java:126) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.ExpressionStatisticCalculator.calculate(ExpressionStatisticCalculator.java:39) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.ExpressionStatisticCalculator.calculate(ExpressionStatisticCalculator.java:35) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.PredicateStatisticsCalculator$PredicateStatisticsCalculatingVisitor.getExpressionStatistic(PredicateStatisticsCalculator.java:317) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.PredicateStatisticsCalculator$PredicateStatisticsCalculatingVisitor.visitBinaryPredicate(PredicateStatisticsCalculator.java:195) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.PredicateStatisticsCalculator$PredicateStatisticsCalculatingVisitor.visitBinaryPredicate(PredicateStatisticsCalculator.java:31) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.operator.scalar.BinaryPredicateOperator.accept(BinaryPredicateOperator.java:62) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.PredicateStatisticsCalculator.statisticsCalculate(PredicateStatisticsCalculator.java:28) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.estimateStatistics(StatisticsCalculator.java:1242) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.computeJoinNode(StatisticsCalculator.java:802) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.visitLogicalJoin(StatisticsCalculator.java:681) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.visitLogicalJoin(StatisticsCalculator.java:136) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.operator.logical.LogicalJoinOperator.accept(LogicalJoinOperator.java:145) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.estimatorStats(StatisticsCalculator.java:152) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.rule.join.JoinOrder.calculateStatistics(JoinOrder.java:229) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.rule.join.JoinReorderLeftDeep.enumerate(JoinReorderLeftDeep.java:79) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.rule.join.JoinOrder.reorder(JoinOrder.java:179) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.rule.join.ReorderJoinRule.enumerate(ReorderJoinRule.java:70) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.rule.join.ReorderJoinRule.transform(ReorderJoinRule.java:145) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.memoOptimize(Optimizer.java:347) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.optimizeByCost(Optimizer.java:149) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.optimize(Optimizer.java:91) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.createQueryPlan(StatementPlanner.java:104) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:65) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:37) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:367) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:308) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:423) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:669) ~[starrocks-fe.jar:?]
        at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:55) ~[starrocks-fe.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 mysql> select current_version();
+----------------------------+
| current_version()          |
+----------------------------+
| BRANCH-2.5-RELEASE 70b7179 |
+----------------------------+
1 row in set (0.01 sec)

### PR DESCRIPTION
**Pull request by packy92**
Fixes #14257
For sql like:
```
select  
  ref_0.N_NAME as c0, 
  case when ref_3.C_NATIONKEY > ref_3.C_ACCTBAL then ref_1.O_ORDERPRIORITY else ref_1.O_SHIPPRIORITY end as c1
from 
  nation as ref_0 inner join orders as ref_1
            on (ref_0.N_REGIONKEY = ref_1.O_CUSTKEY )
          left join t2 as ref_2
          on (ref_0.N_NATIONKEY = ref_2.v8 )
        inner join customer as ref_3
        on (ref_1.O_ORDERPRIORITY = ref_3.C_NAME )
      inner join supplier as ref_4
      on (ref_1.O_CLERK = ref_4.S_PHONE )
    left join supplier as ref_5
    on (ref_2.v9 = ref_5.S_SUPPKEY )
where cast(coalesce(ref_3.C_MKTSEGMENT, ref_0.N_NAME) as VARCHAR) = ref_5.S_ADDRESS
```
The  logical plan with a on predicate `46: coalesce = 38: S_ADDRESS ` generated by two tables `ref_3` and `ref_0`. So when reorder, if we need build a join with on predicate `46: coalesce = 38: S_ADDRESS`, the `ref_3` and `ref_0` should be in oneside of the join. But our reorder algorithm may generate a plan which the outermost  join's left child contains `ref_3` and its right child contains `ref_0` which failes to yield a valid plan.
This pr add a check step to filter these planes. For `DP algorithm`, it enumerate all posibility, so it can yield at least one valid plan. For other algorithm, it may yield empty result.

Anohter changes:
Forcibly update rowOutputInfo when there is a projection, to avoid invalidation of rowOutputInfo because only the projection is updated in the transformation rule.

## What type of PR is this:
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [x] 3.0
  - [ ] 2.5
  - [ ] 2.4

### CODE REVIEW

**Comment by Seaven** [comment]
the reason because left outer join lose a column? I think we was handle these case on inner join reorder

**Comment by packy92** [comment]
> the reason because left outer join lose a column? I think we was handle these case on inner join reorder

Actually not. Because we do nothing to limit the enumerate space, so the order may illegal. Like the example, `46: coalesce` is generated by two tables `ref_3` and `ref_0`, but the reorder result may like this
```
join 
      leftChild(with ref_1, ref_2, ref_3, ref_4, ref_4)
      rightChild(only with ref_0)
```
I think we can add a step to build a correct search space for join orders when support the outer join reorder algorithm.

**Review by Seaven — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 63 / 68 (92.65%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/JoinAssociateBaseRule.java|3|6|50.00%|[180, 181, 182]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/join/JoinReorderCardinalityPreserving.java|4|5|80.00%|[262]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/join/JoinReorderLeftDeep.java|10|11|90.91%|[93]|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/Operator.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/validate/InputDependenciesChecker.java|17|17|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/join/JoinReorderGreedy.java|8|8|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/join/JoinOrder.java|11|11|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/join/JoinReorderDP.java|7|7|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/logical/LogicalTableFunctionOperator.java|1|1|100.00%|[]|

**Review by liuyehcf — APPROVED** [review]

**Review by Seaven — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Pull request merged**
