### PR TITLE
[Refactor] refactor hive query dump

### PR DESCRIPTION
**Pull request by stephen-shelby**
## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [x] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
starrocks_be_unittest succeeded.

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 23 / 63 (36.51%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/Catalog.java|0|15|00.00%|[62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 91]|
|:large_blue_circle:|com/starrocks/sql/optimizer/dump/HiveMetaStoreTableDumpInfo.java|0|2|00.00%|[34, 38]|
|:large_blue_circle:|com/starrocks/sql/optimizer/dump/QueryDumpSerializer.java|1|8|12.50%|[41, 42, 43, 45, 63, 65, 69]|
|:large_blue_circle:|com/starrocks/sql/optimizer/dump/HiveTableDumpInfo.java|2|12|16.67%|[62, 107, 121, 122, 141, 142, 143, 144, 145, 146]|
|:large_blue_circle:|com/starrocks/sql/optimizer/dump/QueryDumpDeserializer.java|1|6|16.67%|[37, 38, 39, 40, 41]|
|:large_blue_circle:|com/starrocks/sql/optimizer/dump/QueryDumpInfo.java|10|11|90.91%|[210]|
|:large_blue_circle:|com/starrocks/connector/hive/HiveMetadata.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/server/CatalogMgr.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/QueryAnalyzer.java|6|6|100.00%|[]|

**Comment by stephen-shelby** [comment]
run starrocks_admit_test

**Comment by stephen-shelby** [comment]
run starrocks_admit_test

**Comment by stephen-shelby** [comment]
run starrocks_admit_test

**Comment by stephen-shelby** [comment]
run starrocks_admit_test

**Comment by stephen-shelby** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 23 / 65 (35.38%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/Catalog.java|0|17|00.00%|[62, 63, 64, 65, 66, 67, 68, 69, 70, 72, 73, 74, 75, 76, 77, 78, 94]|
|:large_blue_circle:|com/starrocks/sql/optimizer/dump/HiveMetaStoreTableDumpInfo.java|0|2|00.00%|[34, 38]|
|:large_blue_circle:|com/starrocks/sql/optimizer/dump/QueryDumpSerializer.java|1|8|12.50%|[41, 42, 43, 45, 63, 65, 69]|
|:large_blue_circle:|com/starrocks/sql/optimizer/dump/HiveTableDumpInfo.java|2|12|16.67%|[62, 107, 121, 122, 141, 142, 143, 144, 145, 146]|
|:large_blue_circle:|com/starrocks/sql/optimizer/dump/QueryDumpDeserializer.java|1|6|16.67%|[37, 38, 39, 40, 41]|
|:large_blue_circle:|com/starrocks/sql/optimizer/dump/QueryDumpInfo.java|10|11|90.91%|[210]|
|:large_blue_circle:|com/starrocks/connector/hive/HiveMetadata.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/server/CatalogMgr.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/QueryAnalyzer.java|6|6|100.00%|[]|

**Comment by wanpengfei-git** [comment]
starrocks_be_unittest succeeded.

**Comment by stephen-shelby** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
starrocks_be_unittest succeeded.

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 23 / 65 (35.38%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/Catalog.java|0|17|00.00%|[62, 63, 64, 65, 66, 67, 68, 69, 70, 72, 73, 74, 75, 76, 77, 78, 94]|
|:large_blue_circle:|com/starrocks/sql/optimizer/dump/HiveMetaStoreTableDumpInfo.java|0|2|00.00%|[34, 38]|
|:large_blue_circle:|com/starrocks/sql/optimizer/dump/QueryDumpSerializer.java|1|8|12.50%|[41, 42, 43, 45, 63, 65, 69]|
|:large_blue_circle:|com/starrocks/sql/optimizer/dump/HiveTableDumpInfo.java|2|12|16.67%|[62, 107, 121, 122, 141, 142, 143, 144, 145, 146]|
|:large_blue_circle:|com/starrocks/sql/optimizer/dump/QueryDumpDeserializer.java|1|6|16.67%|[37, 38, 39, 40, 41]|
|:large_blue_circle:|com/starrocks/sql/optimizer/dump/QueryDumpInfo.java|10|11|90.91%|[210]|
|:large_blue_circle:|com/starrocks/connector/hive/HiveMetadata.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/server/CatalogMgr.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/QueryAnalyzer.java|6|6|100.00%|[]|

**Comment by stephen-shelby** [comment]
run starrocks_admit_test

**Comment by stephen-shelby** [comment]
run starrocks_admit_test

**Pull request closed without merging**
