### PR TITLE
[Feature] Add a time function for get yesterday

### PR DESCRIPTION
**Pull request by xlwh**
## What type of PR is this：
- [ ] bug
- [x] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by imay** [comment]
@xlwh Thank you for you contribution firstly. However I think user can get yesterday by executing `date_add(now(), -1)`. So I think it isn't necessary to introduce this function.

**Comment by xlwh** [comment]
Ok, my original idea is to simplify the above SQL, if it not nedd, I will close first, thank you

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Pull request closed without merging**
