### PR TITLE
[BugFix] Fix FE dead lock bug where db lock and TabletInvertedIndex lock waiting for each other 

### PR DESCRIPTION
**Pull request by gengjun-git**
backport #30703

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:disappointed: **fail** : 0 / 17 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/TabletInvertedIndex.java|0|4|00.00%|[211, 212, 214, 216]|
|:large_blue_circle:|com/starrocks/master/ReportHandler.java|0|13|00.00%|[896, 898, 899, 900, 901, 905, 906, 907, 918, 919, 926, 927, 929]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by Astralidea — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:disappointed: **fail** : 0 / 17 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/TabletInvertedIndex.java|0|4|00.00%|[211, 212, 214, 216]|
|:large_blue_circle:|com/starrocks/master/ReportHandler.java|0|13|00.00%|[896, 898, 899, 900, 901, 905, 906, 907, 918, 919, 926, 927, 929]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Pull request merged**
