### PR TITLE
[BugFix] Missing cast expression

### PR DESCRIPTION
**Pull request by rickif**
Fixes https://github.com/StarRocks/starrocks/issues/32224
image
The parameters of function `if` are in different types, which leads this error.

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 93 / 102 (91.18%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/analysis/Expr.java|5|7|71.43%|[1847, 1848]|
|:large_blue_circle:|com/starrocks/sql/optimizer/transformer/SqlToScalarOperatorTranslator.java|8|9|88.89%|[512]|
|:large_blue_circle:|com/starrocks/sql/plan/ScalarOperatorToExpr.java|65|71|91.55%|[170, 171, 172, 302, 303, 304]|
|:large_blue_circle:|com/starrocks/analysis/SlotRef.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/load/Load.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/SlotDescriptor.java|7|7|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 93 / 102 (91.18%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/analysis/Expr.java|5|7|71.43%|[1847, 1848]|
|:large_blue_circle:|com/starrocks/sql/optimizer/transformer/SqlToScalarOperatorTranslator.java|8|9|88.89%|[512]|
|:large_blue_circle:|com/starrocks/sql/plan/ScalarOperatorToExpr.java|65|71|91.55%|[170, 171, 172, 302, 303, 304]|
|:large_blue_circle:|com/starrocks/analysis/SlotRef.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/load/Load.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/SlotDescriptor.java|7|7|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by packy92 — APPROVED** [review]

**Pull request merged**
