### PR TITLE
[BugFix] remove line separator correctly when log stmt

### PR DESCRIPTION
**Pull request by packy92**
Fixes #issue
The client may send query using a connector in windows platform and the line separtator is `\r\n`. When we record this query in audit log, we just replace the `\n` but not replace `\r`. In Java, \r is an escape character that represents a carriage return. When you use `\r` within a string, it tells the output device (such as a terminal or console) to move the cursor to the beginning of the current line.
Like this
```
System.out.println("select \r from");
# only outoput
 from
```

This pr remove line separator and comments correctly when log a valid statement and just log the orginal statement if its invalid.

BTW, ensure a fixed test order in `MultiJoinReorderTest` to avoid failure when concurrent test.

## What type of PR is this:
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [x] 3.0
  - [x] 2.5
  - [ ] 2.4

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 44 / 44 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/common/util/LogUtil.java|42|42|100.00%|[]|
|:large_blue_circle:|com/starrocks/qe/ConnectProcessor.java|2|2|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 45 / 45 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/common/util/LogUtil.java|43|43|100.00%|[]|
|:large_blue_circle:|com/starrocks/qe/ConnectProcessor.java|2|2|100.00%|[]|

**Review by kangkaisen — APPROVED** [review]

**Review by stdpain — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
