### PR TITLE
[Enhancement] Get thread dump before acquire database lock

### LINKED ISSUE #16747: get thread dump after acquire db lock is not accurate
## Enhancement
image

log thread dump  after  acquire or try  database lock,  thread dump is not accurate

### PR DESCRIPTION
**Pull request by hongli-my**
## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #16747

## Problem Summary(Required) ：

get thread dump before acquire database lock , and thread dump maybe more accurate.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 12 / 21 (57.14%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/Database.java|12|21|57.14%|[188, 190, 193, 205, 207, 210, 269, 271, 274]|

**Review by nshangyiming — DISMISSED** [review]

**Review by gengjun-git — DISMISSED** [review]
LGTM

**Review by choury — DISMISSED** [review]

**Review by choury — APPROVED** [review]

**Review by nshangyiming — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by gengjun-git — APPROVED** [review]

**Comment by hongli-my** [comment]
run starrocks_fe_unittest

**Comment by choury** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 12 / 21 (57.14%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/Database.java|12|21|57.14%|[188, 190, 193, 205, 207, 210, 269, 271, 274]|

**Comment by nshangyiming** [comment]
i will backport this pr to branch 2.3- 2.5

**Comment by nshangyiming** [comment]
@mergify backport branch-3.0 branch-2.5 branch-2.4 branch-2.3

**Comment by nshangyiming** [comment]
@mergify backport branch-3.0

**Comment by nshangyiming** [comment]
@mergify backport branch-2.5

**Comment by bulolo** [comment]
still exist
```
2024-10-31 14:18:52,744 ERROR  ||  Stream load failure 4 times, which bigger than maxRetryTimes 3, sink task will be stopped   [com.starrocks.connector.kafka.StarRocksSinkTask]
2024-10-31 14:18:52,744 ERROR  ||  Error message is    [com.starrocks.connector.kafka.StarRocksSinkTask]
java.lang.RuntimeException: com.starrocks.data.load.stream.exception.StreamLoadFailException: Stream load failed because of error, db: scm, table: ods_pms_issue, label: -049cbc82-27fd-42c1-bd0e-1ec522c608c7, 
responseBody: {
    "Status": "TIMEOUT",
    "Message": "get database read lock timeout, database=scm, timeout=3750ms"
}
errorLog: null
        at com.starrocks.data.load.stream.v2.StreamLoadManagerV2.AssertNotException(StreamLoadManagerV2.java:427)
        at com.starrocks.data.load.stream.v2.StreamLoadManagerV2.flush(StreamLoadManagerV2.java:355)
        at com.starrocks.connector.kafka.StarRocksSinkTask.preCommit(StarRocksSinkTask.java:349)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.commitOffsets(WorkerSinkTask.java:411)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.commitOffsets(WorkerSinkTask.java:381)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:221)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:206)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:204)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:259)
        at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:181)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.starrocks.data.load.stream.exception.StreamLoadFailException: Stream load failed because of error, db: scm, table: ods_pms_issue, label: -049cbc82-27fd-42c1-bd0e-1ec522c608c7, 
responseBody: {
    "Status": "TIMEOUT",
    "Message": "get database read lock timeout, database=scm, timeout=3750ms"
}
errorLog: null
        at com.starrocks.data.load.stream.DefaultStreamLoader.sendToSR(DefaultStreamLoader.java:339)
        at com.starrocks.data.load.stream.DefaultStreamLoader.lambda$send$3(DefaultStreamLoader.java:170)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        ... 3 more
```

**Pull request merged**
