### PR TITLE
[BugFix] when the path contains(),replaceFirst not work

### LINKED ISSUE #12641: When the path contains (), be can't read the data correctly
### Steps to reproduce the behavior (Required)
External hive table;

the hive table looks like this:
create table test(id int, name string) PARTITIONED BY(dt string) STORED AS ORC;
insert into test0 partition(dt="(test)") select 1, "lily" from (select 1) x;

then we query the data by starrocks
select * from test0;

### Expected behavior (Required)
get the data
### Real behavior (Required)
ERROR 1064 (HY000): hdfsOpenFile failed, path=hdfs://172.17.0.3/user/hive/warehouse/test_0/dt=(test)/hdfs://172.17.0.3/user/hive/warehouse/test_0/dt=(test)/000000_0:file = hdfs://172.17.0.3/user/hive/warehouse/test_0/dt=(test)/hdfs://172.17.0.3/user/hive/warehouse/test_0/dt=(test)/000000_0

be.out
hdfsOpenFile(hdfs://172.17.0.3/user/hive/warehouse/test_0/dt=(test)/hdfs://172.17.0.3/user/hive/warehouse/test_0/dt=(test)/000000_0): FileSystem#open((Lorg/apache/hadoop/fs/Path;I)Lorg/apache/hadoop/fs/FSDataInputStream;) error:
IllegalArgumentException: Pathname /user/hive/warehouse/test_0/dt=(test)/hdfs:/172.17.0.3/user/hive/warehouse/test_0/dt=(test)/000000_0 from hdfs://172.17.0.3/user/hive/warehouse/test_0/dt=(test)/hdfs:/172.17.0.3/user/hive/warehouse/test_0/dt=(test)/000000_0 is not a valid DFS filename.java.lang.IllegalArgumentException: Pathname /user/hive/warehouse/test_0/dt=(test)/hdfs:/172.17.0.3/user/hive/warehouse/test_0/dt=(test)/000000_0 from hdfs://172.17.0.3/user/hive/warehouse/test_0/dt=(test)/hdfs:/172.17.0.3/user/hive/warehouse/test_0/dt=(test)/000000_0 is not a valid DFS filename.
	at org.apache.hadoop.hdfs.DistributedFileSystem.getPathName(DistributedFileSystem.java:250)
	at org.apache.hadoop.hdfs.DistributedFileSystem$4.doCall(DistributedFileSystem.java:333)
	at org.apache.hadoop.hdfs.DistributedFileSystem$4.doCall(DistributedFileSystem.java:329)
	at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
	at org.apache.hadoop.hdfs.DistributedFileSystem.open(DistributedFileSystem.java:346)

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by zombee0**
Signed-off-by: zombee0 <flylucas_10@163.com>

## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #12641 

## Problem Summary(Required) ：

repalceFirst will use the first param as regex, so when the path contains (), it will not work.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Review by DorianZheng — APPROVED** [review]
LGTM

**Review by gengjun-git — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
starrocks_be_unittest succeeded.

**Comment by zombee0** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/external/PartitionUtil.java|1|1|100.00%|[]|

**Review by dirtysalt — APPROVED** [review]

**Comment by DorianZheng** [comment]
run starrocks_admit_test

**Pull request merged**
