### PR TITLE
[BugFix] Fix no push_chunk() before set_finishing() in OlapTableSinkOperator

### PR DESCRIPTION
**Pull request by meegoo**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

#8239 will block pipeline engine in set_finishing(), we need check is_open_done() before open_wait()

### CODE REVIEW

**Comment by meegoo** [comment]
run starrocks_be_unittest

**Review by murphyatwork — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by meegoo** [comment]
run starrocks_admit_test

**Comment by meegoo** [comment]
run starrocks_admit_test

**Comment by meegoo** [comment]
run starrocks_admit_test

**Review by chaoyli — APPROVED** [review]

**Pull request merged**
