### PR TITLE
Fixup divided by zero (#2868)

### LINKED ISSUE #2867: Fe report devided by zero error
### Steps to reproduce the behavior (Required)
```
select * from(select * from t0 where t0.dt between "2021-01-31" and "2021-02-01" and price between 750.00 and 751.00) t0 where not exists (select * from t1 where t1.dt between "2021-01-03" and "2021-01-04" and price between 881.00 and 882.00 and t0.id=t1.id) and length(t0.name) < 10 limit 2, 4097
```

### Expected behavior (Required)
execute query correctly
### Real behavior (Required)
```
java.lang.ArithmeticException: / by zero
        at com.starrocks.qe.Coordinator.computeFragmentHosts(Coordinator.java:1306) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.Coordinator.computeFragmentExecParams(Coordinator.java:820) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.Coordinator.exec(Coordinator.java:408) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.handleQueryStmt(StmtExecutor.java:673) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:370) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:268) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:415) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:651) ~[starrocks-fe.jar:?]
        at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:55) ~[starrocks-fe.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_202]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_202]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
```

### StarRocks version (Required)
b54eff0b9f9d4ac9fd4b0fe259f38eb31c3eb85f

### PR DESCRIPTION
**Pull request by satanson**
https://github.com/StarRocks/starrocks/pull/2868
https://github.com/StarRocks/starrocks/issues/2867

### CODE REVIEW

**Review by kangkaisen — APPROVED** [review]

**Comment by kangkaisen** [comment]
run starrocks_fe_unittest

**Comment by satanson** [comment]
run starrocks_fe_unittest

**Comment by satanson** [comment]
run starrocks_fe_unittest

**Comment by satanson** [comment]
run starrocks_fe_unittest

**Pull request merged**
