### PR TITLE
[Enhancement] cp dla optimize

### PR DESCRIPTION
**Pull request by zombee0**
cp #30176, #28867, #28843, #29597

Fixes #issue

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 210 / 312 (67.31%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/formats/parquet/column_reader.h|0|11|00.00%|[88, 106, 109, 111, 114, 117, 120, 121, 123, 124, 126]|
|:large_blue_circle:|src/formats/parquet/group_reader.h|0|3|00.00%|[89, 91, 93]|
|:large_blue_circle:|src/connector/hive_connector.cpp|1|5|20.00%|[254, 255, 256, 510]|
|:large_blue_circle:|src/column/struct_column.cpp|3|6|50.00%|[488, 503, 507]|
|:large_blue_circle:|src/formats/parquet/group_reader.cpp|29|43|67.44%|[86, 248, 255, 256, 456, 487, 490, 491, 492, 495, 496, 497, 503, 504]|
|:large_blue_circle:|src/formats/parquet/column_reader.cpp|158|225|70.22%|[93, 95, 96, 129, 145, 162, 259, 260, 275, 276, 284, 321, 322, 333, 334, 354, 359, 360, 361, 362, 364, 369, 371, 373, 399, 588, 589, 631, 704, 717, 718, 719, 720, 721, 722, 723, 725, 726, 727, 730, 732, 736, 737, 740, 741, 742, 743, 744, 745, 746, 747, 749, 753, 757, 758, 759, 760, 761, 762, 763, 765, 766, 768, 779, 780, 781, 845]|
|:large_blue_circle:|src/exprs/expr.cpp|5|5|100.00%|[]|
|:large_blue_circle:|src/exprs/subfield_expr.cpp|3|3|100.00%|[]|
|:large_blue_circle:|src/exec/hdfs_scanner.cpp|2|2|100.00%|[]|
|:large_blue_circle:|src/runtime/descriptors.h|1|1|100.00%|[]|
|:large_blue_circle:|src/formats/parquet/meta_helper.cpp|4|4|100.00%|[]|
|:large_blue_circle:|src/runtime/descriptors.cpp|4|4|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 210 / 312 (67.31%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/formats/parquet/column_reader.h|0|11|00.00%|[88, 106, 109, 111, 114, 117, 120, 121, 123, 124, 126]|
|:large_blue_circle:|src/formats/parquet/group_reader.h|0|3|00.00%|[89, 91, 93]|
|:large_blue_circle:|src/connector/hive_connector.cpp|1|5|20.00%|[254, 255, 256, 510]|
|:large_blue_circle:|src/column/struct_column.cpp|3|6|50.00%|[488, 503, 507]|
|:large_blue_circle:|src/formats/parquet/group_reader.cpp|29|43|67.44%|[86, 248, 255, 256, 456, 487, 490, 491, 492, 495, 496, 497, 503, 504]|
|:large_blue_circle:|src/formats/parquet/column_reader.cpp|158|225|70.22%|[93, 95, 96, 129, 145, 162, 259, 260, 275, 276, 284, 321, 322, 333, 334, 354, 359, 360, 361, 362, 364, 369, 371, 373, 399, 588, 589, 631, 704, 717, 718, 719, 720, 721, 722, 723, 725, 726, 727, 730, 732, 736, 737, 740, 741, 742, 743, 744, 745, 746, 747, 749, 753, 757, 758, 759, 760, 761, 762, 763, 765, 766, 768, 779, 780, 781, 845]|
|:large_blue_circle:|src/exprs/expr.cpp|5|5|100.00%|[]|
|:large_blue_circle:|src/exprs/subfield_expr.cpp|3|3|100.00%|[]|
|:large_blue_circle:|src/exec/hdfs_scanner.cpp|2|2|100.00%|[]|
|:large_blue_circle:|src/runtime/descriptors.h|1|1|100.00%|[]|
|:large_blue_circle:|src/formats/parquet/meta_helper.cpp|4|4|100.00%|[]|
|:large_blue_circle:|src/runtime/descriptors.cpp|4|4|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 65 / 66 (98.48%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/analysis/SlotDescriptor.java|12|13|92.31%|[180]|
|:large_blue_circle:|com/starrocks/qe/SessionVariable.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/plan/PlanFragmentBuilder.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/tree/PruneSubfieldsForComplexType.java|25|25|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/tree/PruneComplexTypeUtil.java|22|22|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/pattern/Pattern.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 210 / 312 (67.31%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/formats/parquet/column_reader.h|0|11|00.00%|[88, 106, 109, 111, 114, 117, 120, 121, 123, 124, 126]|
|:large_blue_circle:|src/formats/parquet/group_reader.h|0|3|00.00%|[89, 91, 93]|
|:large_blue_circle:|src/connector/hive_connector.cpp|1|5|20.00%|[254, 255, 256, 510]|
|:large_blue_circle:|src/column/struct_column.cpp|3|6|50.00%|[488, 503, 507]|
|:large_blue_circle:|src/formats/parquet/group_reader.cpp|29|43|67.44%|[86, 248, 255, 256, 456, 487, 490, 491, 492, 495, 496, 497, 503, 504]|
|:large_blue_circle:|src/formats/parquet/column_reader.cpp|158|225|70.22%|[93, 95, 96, 129, 145, 162, 259, 260, 275, 276, 284, 321, 322, 333, 334, 354, 359, 360, 361, 362, 364, 369, 371, 373, 399, 588, 589, 631, 704, 717, 718, 719, 720, 721, 722, 723, 725, 726, 727, 730, 732, 736, 737, 740, 741, 742, 743, 744, 745, 746, 747, 749, 753, 757, 758, 759, 760, 761, 762, 763, 765, 766, 768, 779, 780, 781, 845]|
|:large_blue_circle:|src/exprs/expr.cpp|5|5|100.00%|[]|
|:large_blue_circle:|src/exprs/subfield_expr.cpp|3|3|100.00%|[]|
|:large_blue_circle:|src/exec/hdfs_scanner.cpp|2|2|100.00%|[]|
|:large_blue_circle:|src/runtime/descriptors.h|1|1|100.00%|[]|
|:large_blue_circle:|src/formats/parquet/meta_helper.cpp|4|4|100.00%|[]|
|:large_blue_circle:|src/runtime/descriptors.cpp|4|4|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 210 / 312 (67.31%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/formats/parquet/column_reader.h|0|11|00.00%|[88, 106, 109, 111, 114, 117, 120, 121, 123, 124, 126]|
|:large_blue_circle:|src/formats/parquet/group_reader.h|0|3|00.00%|[89, 91, 93]|
|:large_blue_circle:|src/connector/hive_connector.cpp|1|5|20.00%|[254, 255, 256, 510]|
|:large_blue_circle:|src/column/struct_column.cpp|3|6|50.00%|[488, 503, 507]|
|:large_blue_circle:|src/formats/parquet/group_reader.cpp|29|43|67.44%|[86, 248, 255, 256, 456, 487, 490, 491, 492, 495, 496, 497, 503, 504]|
|:large_blue_circle:|src/formats/parquet/column_reader.cpp|158|225|70.22%|[93, 95, 96, 129, 145, 162, 259, 260, 275, 276, 284, 321, 322, 333, 334, 354, 359, 360, 361, 362, 364, 369, 371, 373, 399, 588, 589, 631, 704, 717, 718, 719, 720, 721, 722, 723, 725, 726, 727, 730, 732, 736, 737, 740, 741, 742, 743, 744, 745, 746, 747, 749, 753, 757, 758, 759, 760, 761, 762, 763, 765, 766, 768, 779, 780, 781, 845]|
|:large_blue_circle:|src/exprs/expr.cpp|5|5|100.00%|[]|
|:large_blue_circle:|src/exprs/subfield_expr.cpp|3|3|100.00%|[]|
|:large_blue_circle:|src/exec/hdfs_scanner.cpp|2|2|100.00%|[]|
|:large_blue_circle:|src/runtime/descriptors.h|1|1|100.00%|[]|
|:large_blue_circle:|src/formats/parquet/meta_helper.cpp|4|4|100.00%|[]|
|:large_blue_circle:|src/runtime/descriptors.cpp|4|4|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 65 / 66 (98.48%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/analysis/SlotDescriptor.java|12|13|92.31%|[180]|
|:large_blue_circle:|com/starrocks/qe/SessionVariable.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/plan/PlanFragmentBuilder.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/tree/PruneSubfieldsForComplexType.java|25|25|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/tree/PruneComplexTypeUtil.java|22|22|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/pattern/Pattern.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 211 / 312 (67.63%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/formats/parquet/column_reader.h|0|11|00.00%|[88, 106, 109, 111, 114, 117, 120, 121, 123, 124, 126]|
|:large_blue_circle:|src/formats/parquet/group_reader.h|0|3|00.00%|[89, 91, 93]|
|:large_blue_circle:|src/connector/hive_connector.cpp|1|4|25.00%|[254, 255, 256]|
|:large_blue_circle:|src/column/struct_column.cpp|3|6|50.00%|[488, 503, 507]|
|:large_blue_circle:|src/formats/parquet/group_reader.cpp|29|43|67.44%|[86, 248, 255, 256, 456, 487, 490, 491, 492, 495, 496, 497, 503, 504]|
|:large_blue_circle:|src/formats/parquet/column_reader.cpp|158|225|70.22%|[93, 95, 96, 129, 145, 162, 259, 260, 275, 276, 284, 321, 322, 333, 334, 354, 359, 360, 361, 362, 364, 369, 371, 373, 399, 588, 589, 631, 704, 717, 718, 719, 720, 721, 722, 723, 725, 726, 727, 730, 732, 736, 737, 740, 741, 742, 743, 744, 745, 746, 747, 749, 753, 757, 758, 759, 760, 761, 762, 763, 765, 766, 768, 779, 780, 781, 845]|
|:large_blue_circle:|src/exprs/expr.cpp|5|5|100.00%|[]|
|:large_blue_circle:|src/exprs/subfield_expr.cpp|3|3|100.00%|[]|
|:large_blue_circle:|src/exec/hdfs_scanner.cpp|2|2|100.00%|[]|
|:large_blue_circle:|src/runtime/descriptors.h|1|1|100.00%|[]|
|:large_blue_circle:|src/formats/parquet/meta_helper.cpp|4|4|100.00%|[]|
|:large_blue_circle:|src/runtime/descriptors.cpp|5|5|100.00%|[]|

**Review by Youngwb — APPROVED** [review]

**Pull request merged**
