### PR TITLE
[BugFix] Init scan executor for compute node

### PR DESCRIPTION
**Pull request by ZiheLiu**
Signed-off-by: ZiheLiu <ziheliu1024@gmail.com>

## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Problem Summary(Required) ：

Scanning schema on the compute node will throw error:

```
*** Aborted at 1674546502 (unix time) try "date -d @1674546502" if you are using GNU date ***
PC: @          0x2d581aa starrocks::workgroup::ScanExecutor::submit()
*** SIGSEGV (@0x10) received by PID 7878 (TID 0x7f8eb9f16700) from PID 16; stack trace: ***
    @          0x59fe902 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7f8f2b464630 (unknown)
    @          0x2d581aa starrocks::workgroup::ScanExecutor::submit()
    @          0x2d45bfc starrocks::pipeline::ScanOperator::_trigger_next_scan()
    @          0x2d4643d starrocks::pipeline::ScanOperator::_pickup_morsel()
    @          0x2d46645 starrocks::pipeline::ScanOperator::_try_to_trigger_next_scan()
    @          0x2d46864 starrocks::pipeline::ScanOperator::pull_chunk()
    @          0x2d245a3 starrocks::pipeline::PipelineDriver::process()
    @          0x4e5d3b7 starrocks::pipeline::GlobalDriverExecutor::_worker_thread()
    @          0x48814ad starrocks::ThreadPool::dispatch_thread()
    @          0x487c23a starrocks::Thread::supervise_thread()
    @     0x7f8f2b45cea5 start_thread
    @     0x7f8f2aa779fd __clone
    @                0x0 (unknown)
```

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 2.5
  - [x] 2.4
  - [x] 2.3
  - [ ] 2.2

### CODE REVIEW

**Review by kangkaisen — APPROVED** [review]

**Review by silverbullet233 — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by satanson — APPROVED** [review]

**Comment by ZiheLiu** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.4

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.3

**Pull request merged**
