### PR TITLE
[BugFix] Specify storage medium of materialized view

### LINKED ISSUE #17352: Specify storage medium of materialized view
## Enhancement

Create Materialized view works without any storage medium property, but it shows as HDD although we have only 1 disk SSD and also create works when HDD is set explicitly , & create gives no error, but shows failed in task_runs when SSD is set explicitly in create like below.

To simplify the question here, when we set storage target = 'SSD' we get an error, although the only storage medium we have is SSD. However, default sets to 'HDD', which we have removed form our configurations

```sql
CREATE MATERIALIZED VIEW mv
DISTRIBUTED BY HASH(block_number)  BUCKETS 10
REFRESH ASYNC EVERY (interval 1 hour)
PROPERTIES (
"replication_num" = "1",
"storage_medium" = "SSD"
)

xxxx
```

### PR DESCRIPTION
**Pull request by blackstar-baba**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #17352 

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 3.0
  - [x] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 4 / 4 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/scheduler/PartitionBasedMaterializedViewRefreshProcessor.java|4|4|100.00%|[]|

**Review by Astralidea — APPROVED** [review]

**Review by murphyatwork — APPROVED** [review]

**Comment by mofeiatwork** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
