### PR TITLE
[Enhancement] remove warning log for auto increment id (#19415)

### PR DESCRIPTION
**Pull request by srlch**
## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #19416

## Problem Summary(Required) ：
remove warning log if BackupJobInfo has no auto increment id info.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Review by gengjun-git — APPROVED** [review]

**Review by kangkaisen — APPROVED** [review]

**Review by chaoyli — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by srlch** [comment]
run starrocks_admit_test

**Comment by srlch** [comment]
run starrocks_admit_test

**Comment by srlch** [comment]
run starrocks_admit_test

**Pull request merged**
