### PR TITLE
[Enhance] optimize  json_query function

### PR DESCRIPTION
**Pull request by murphyatwork**
## What type of PR is this：
- [ ] bug
- [ ] feature
- [x] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

Optimize the performance of `json_query/get_json_string/get_json_int` functions:
- Improvement: 10B rows of data, 16 `get_json_string` expression in select clause; improve from `12s` to `6s`
- Inline the type convert into `_json_query_impl` function, reduce the overhead of construct immediate Json object
- Specialize `get_json_string`, avoid call `Slice::toJson` but read the string directly

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by mofeiatwork** [comment]
@Mergifyio backport branch-2.3 branch-2.4

**Comment by mofeiatwork** [comment]
run starrocks_admit_test

**Review by kangkaisen — APPROVED** [review]

**Review by stdpain — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by rickif — APPROVED** [review]

**Comment by imay** [comment]
run starrocks_admit_test

**Pull request merged**
