### PR TITLE
[Refactor] Refactor Variable related code to support User Define Variable

### PR DESCRIPTION
**Pull request by HangyuanLiu**
## What type of PR is this：
- [ ] bug
- [ ] feature
- [ ] enhancement
- [x] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [x] I have added user document for my new feature or new function

### CODE REVIEW

**Review by imay — APPROVED** [review]

**Review by imay — DISMISSED** [review]

**Comment by HangyuanLiu** [comment]
run starrocks_fe_unittest

**Comment by HangyuanLiu** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 56 / 72 (77.78%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/analysis/VariableExpr.java|8|18|44.44%|[59, 68, 84, 85, 88, 152, 156, 189, 192, 193]|
|:large_blue_circle:|com/starrocks/analysis/SetVar.java|24|29|82.76%|[86, 87, 121, 133, 139]|
|:large_blue_circle:|com/starrocks/sql/ast/SetUserVar.java|8|9|88.89%|[20]|
|:large_blue_circle:|com/starrocks/analysis/SetType.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|10|10|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AST2SQL.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/qe/VariableMgr.java|2|2|100.00%|[]|

**Review by kangkaisen — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by Seaven — APPROVED** [review]

**Pull request merged**
