### PR TITLE
[Enhancement] Don't fetch column Statistics when there is no need for Iceberg

### PR DESCRIPTION
**Pull request by zombee0**
## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

Avro decode is cpu intensive, so we shouldn't fetch column statistics when there is no need
## Checklist:
#18560

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Review by imay — DISMISSED** [review]

**Comment by zombee0** [comment]
run starrocks_fe_unittest

**Comment by zombee0** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 1 / 5 (20.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/connector/iceberg/cost/IcebergTableStatisticCalculator.java|0|1|00.00%|[228]|
|:large_blue_circle:|com/starrocks/connector/iceberg/IcebergUtil.java|0|3|00.00%|[178, 179, 180]|
|:large_blue_circle:|com/starrocks/planner/IcebergScanNode.java|1|1|100.00%|[]|

**Review by Youngwb — DISMISSED** [review]

**Review by stephen-shelby — DISMISSED** [review]

**Comment by zombee0** [comment]
run starrocks_admit_test

**Comment by zombee0** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 1 / 5 (20.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/connector/iceberg/cost/IcebergTableStatisticCalculator.java|0|1|00.00%|[228]|
|:large_blue_circle:|com/starrocks/connector/iceberg/IcebergUtil.java|0|3|00.00%|[178, 179, 180]|
|:large_blue_circle:|com/starrocks/planner/IcebergScanNode.java|1|1|100.00%|[]|

**Comment by zombee0** [comment]
run starrocks_admit_test

**Comment by zombee0** [comment]
run starrocks_admit_test

**Comment by zombee0** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 1 / 5 (20.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/connector/iceberg/cost/IcebergTableStatisticCalculator.java|0|1|00.00%|[228]|
|:large_blue_circle:|com/starrocks/connector/iceberg/IcebergUtil.java|0|3|00.00%|[178, 179, 180]|
|:large_blue_circle:|com/starrocks/planner/IcebergScanNode.java|1|1|100.00%|[]|

**Comment by zombee0** [comment]
run starrocks_admit_test

**Comment by zombee0** [comment]
run starrocks_admit_test

**Review by Youngwb — APPROVED** [review]

**Review by stephen-shelby — APPROVED** [review]

**Pull request merged**
