### PR TITLE
[Feature] support file/plugin/blacklist stmts in new RBAC privilege framework

### PR DESCRIPTION
**Pull request by padmejin**
## What type of PR is this：
- [ ] BugFix
- [x] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

* PrivilegeCheckerV2 support file/plugin/blacklist stmts
* Add UT to verify the privilege check after the upgrade.

I also find some bugs and fix them.
* `catalog` is a required property in `create file` & `drop file` statements, but the previous refactor of renaming `Catalog` to `GlobalStateMgr` has mistakenly changed the name of this property as well.
* `uninstall plugin name` from the user's manual will cause an error because a `FROM` is mistakenly added before the name of the plugin.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 31 / 40 (77.50%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/PrivilegeCheckerV2.java|25|34|73.53%|[76, 225, 233, 241, 251, 260, 276, 284, 292]|
|:large_blue_circle:|com/starrocks/sql/ast/ShowPluginsStmt.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/AstVisitor.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/privilege/PrivilegeType.java|4|4|100.00%|[]|

**Review by gengjun-git — DISMISSED** [review]

**Review by nshangyiming — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by HangyuanLiu — DISMISSED** [review]

**Comment by padmejin** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by nshangyiming** [comment]
run starrocks_admit_test

**Pull request merged**
