### PR TITLE
[BugFix] only set not null for primary key column

### PR DESCRIPTION
**Pull request by packy92**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

For now, we cannot obatin the correct nullable info from both logical plan and excutable plan, so we cannot define the meta of cols in the create table statement based on the output cols of the query.
So we take a loose restriction for nullable info. Only cols in the primary key are non-nullable and the other cols are all nullable.
## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 2.5
  - [x] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Review by Astralidea — DISMISSED** [review]

**Review by liuyehcf — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/analysis/KeysDesc.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/CTASAnalyzer.java|1|1|100.00%|[]|

**Comment by packy92** [comment]
run starrocks_admit_test

**Review by kangkaisen — DISMISSED** [review]

**Comment by packy92** [comment]
run starrocks_admit_testt

**Review by Seaven — APPROVED** [review]

**Comment by packy92** [comment]
@Mergify backport branch-2.5

**Review by Astralidea — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by packy92** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
