### PR TITLE
[Refactor] rename to `getAliveBackendNumber` & `getTotalBackendNumber`

### PR DESCRIPTION
**Pull request by dirtysalt**
## What type of PR is this：
- [ ] bug
- [ ] feature
- [ ] enhancement
- [x] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

Refactor:
- `getBackendIds(true).size()` -> `getAliveBackendNumber`
- `getBackendIds(false).size()` -> `getTotalBackendNumber`

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 13 / 14 (92.86%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/clone/BeLoadRebalancer.java|0|1|00.00%|[109]|
|:large_blue_circle:|com/starrocks/load/routineload/ScheduleRule.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/system/SystemInfoService.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/Utils.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/statistic/StatisticsMetaManager.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/dump/QueryDumpSerializer.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/load/routineload/KafkaRoutineLoadJob.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/cost/CostModel.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 16 / 23 (69.57%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/http/rest/HealthAction.java|0|2|00.00%|[46, 47]|
|:large_blue_circle:|com/starrocks/clone/BeLoadRebalancer.java|0|1|00.00%|[109]|
|:large_blue_circle:|com/starrocks/metric/PrometheusMetricVisitor.java|0|2|00.00%|[209, 211]|
|:large_blue_circle:|com/starrocks/statistic/StatisticsMetaManager.java|3|5|60.00%|[140, 141]|
|:large_blue_circle:|com/starrocks/load/routineload/ScheduleRule.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/system/SystemInfoService.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/Utils.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/task/EnforceAndCostTask.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/dump/QueryDumpSerializer.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/load/routineload/KafkaRoutineLoadJob.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/cost/CostModel.java|2|2|100.00%|[]|

**Comment by dirtysalt** [comment]
run starrocks_clang-format

**Comment by dirtysalt** [comment]
run starrocks_clang-format

**Review by imay — APPROVED** [review]

**Pull request merged**
