### PR TITLE
[BugFix] Fix drop partition log is written behind drop table log bug

### LINKED ISSUE #12552: [BUG] FE exits when replaying drop partition log
### Steps to reproduce the behavior (Required)
Execute drop table and drop partition command concurrently.

### Expected behavior (Required)
System runs normally.

### Real behavior (Required)
```
2022-10-25 12:45:53,172 INFO (replayer|82) [EditLog.loadJournal():219] Begin to unprotect drop partition. db = 6095728 table = 20826296 partitionName = p20210204
2022-10-25 12:45:53,172 ERROR (replayer|82) [EditLog.loadJournal():830] Operation Type 13
java.lang.NullPointerException: null
        at com.starrocks.catalog.Catalog.replayDropPartition(Catalog.java:3552) ~[starrocks-fe.jar:?]
        at com.starrocks.persist.EditLog.loadJournal(EditLog.java:222) [starrocks-fe.jar:?]
        at com.starrocks.catalog.Catalog.replayJournal(Catalog.java:2503) [starrocks-fe.jar:?]
        at com.starrocks.catalog.Catalog$3.runOneCycle(Catalog.java:2287) [starrocks-fe.jar:?]
        at com.starrocks.common.util.Daemon.run(Daemon.java:119) [starrocks-fe.jar:?]
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by gengjun-git**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #12552

## Problem Summary(Required) ：

The table may be dropped after getting from db, so we should check again (in the db lock). Besides the db may be dropped after getting from catalog, so check it again too.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
starrocks_be_unittest succeeded.

**Review by padmejin — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
starrocks_be_unittest succeeded.

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 4 / 8 (50.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|2|4|50.00%|[1339, 1340]|
|:large_blue_circle:|com/starrocks/clone/DynamicPartitionScheduler.java|2|4|50.00%|[352, 353]|

**Review by Astralidea — APPROVED** [review]

**Review by nshangyiming — APPROVED** [review]

**Review by meegoo — APPROVED** [review]

**Comment by gengjun-git** [comment]
run starrocks_admit_test

**Comment by gengjun-git** [comment]
@mergify backport branch-2.2 branch-2.3 branch-2.4

**Comment by gengjun-git** [comment]
@mergify backport branch-2.3

**Pull request merged**
