### PR TITLE
[Enhancement] backoff routine load job scheduling when all kafka brokers are down

### PR DESCRIPTION
**Pull request by rickif**
Fixes #issue

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 0 / 11 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/runtime/routine_load/data_consumer.cpp|0|2|00.00%|[339, 342]|
|:large_blue_circle:|src/runtime/routine_load/data_consumer.h|0|9|00.00%|[92, 93, 121, 122, 133, 134, 135, 136, 171]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:disappointed: **fail** : 18 / 50 (36.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/common/KafkaAllBrokersDownException.java|0|2|00.00%|[42, 43]|
|:large_blue_circle:|com/starrocks/load/routineload/RoutineLoadTaskScheduler.java|4|12|33.33%|[208, 209, 210, 211, 401, 402, 406, 408]|
|:large_blue_circle:|com/starrocks/common/util/KafkaUtil.java|13|35|37.14%|[185, 186, 187, 188, 189, 192, 193, 195, 198, 214, 221, 223, 225, 230, 231, 232, 233, 235, 236, 238, 239, 242]|
|:large_blue_circle:|com/starrocks/common/Config.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 0 / 4 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/runtime/routine_load/data_consumer.cpp|0|4|00.00%|[319, 350, 362, 398]|

**Comment by rickif** [comment]
@mergifyio rebase

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 0 / 4 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/runtime/routine_load/data_consumer.cpp|0|4|00.00%|[319, 350, 362, 398]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 0 / 4 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/runtime/routine_load/data_consumer.cpp|0|4|00.00%|[319, 350, 362, 398]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:disappointed: **fail** : 5 / 20 (25.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/common/util/KafkaUtil.java|0|5|00.00%|[235, 236, 237, 249, 250]|
|:large_blue_circle:|com/starrocks/common/KafkaAllBrokersDownException.java|0|2|00.00%|[19, 20]|
|:large_blue_circle:|com/starrocks/load/routineload/RoutineLoadTaskScheduler.java|4|12|33.33%|[208, 209, 210, 211, 401, 402, 406, 408]|
|:large_blue_circle:|com/starrocks/common/Config.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 0 / 4 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/runtime/routine_load/data_consumer.cpp|0|4|00.00%|[319, 350, 362, 398]|

**Pull request closed without merging**
