### PR TITLE
[BugFix] Fix wrong cast from double to decimal when using "create table as select" statement to create hive table

### LINKED ISSUE #42671: Wrong cast from double to decimal when using "create table as select" statement to create hive table
### Steps to reproduce the behavior (Required)
```sql
create table xx as select * from yy
```
yy is a external catalog table, such as hive table。

When there is a column with type double/float, it will be cast to decimal automatically, which is not as expected.

### Expected behavior (Required)
image

image

### Real behavior (Required)
image

### StarRocks version (Required)
main branch

### PR DESCRIPTION
**Pull request by mxdzs0612**
## Why I'm doing:
create table as:
image

create table like:
image

Source table:
image

## What I'm doing:

Fixes #42671

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Comment by mxdzs0612** [comment]
@kangkaisen @Seaven @packy92 PTAL, thx~

**Comment by kangkaisen** [comment]
@mxdzs0612 Could you add the UT for this bug? Thanks.

**Review by kangkaisen — DISMISSED** [review]

**Review by letian-jiang — APPROVED** [review]
LGTM

**Review by kangkaisen — DISMISSED** [review]

**Comment by kangkaisen** [comment]
```
TestSQLCases.testIcebergHadoopCatalog
Element counts were not equal:
First has 1, Second has 0:  'c0\\tDOUBLE\\tYes\\tfalse\\tNone\\t'
First has 0, Second has 1:  'c0\tDOUBLE\tYes\tfalse\tNone\t' : sql result not match:
- [SQL]: describe ice_hadoop116eb6925e404ab1a02ce81abbc49f13.ice_hadoop_db116eb6925e404ab1a02ce81abbc49f13.test_double_as;
- [exp]: ['c0\\tDOUBLE\\tYes\\tfalse\\tNone\\t']
- [act]: ['c0\tDOUBLE\tYes\tfalse\tNone\t']
---
```

**Comment by mxdzs0612** [comment]
> ```
> TestSQLCases.testIcebergHadoopCatalog
> Element counts were not equal:
> First has 1, Second has 0:  'c0\\tDOUBLE\\tYes\\tfalse\\tNone\\t'
> First has 0, Second has 1:  'c0\tDOUBLE\tYes\tfalse\tNone\t' : sql result not match:
> - [SQL]: describe ice_hadoop116eb6925e404ab1a02ce81abbc49f13.ice_hadoop_db116eb6925e404ab1a02ce81abbc49f13.test_double_as;
> - [exp]: ['c0\\tDOUBLE\\tYes\\tfalse\\tNone\\t']
> - [act]: ['c0\tDOUBLE\tYes\tfalse\tNone\t']
> ---
> ```

@kangkaisen Done, PTAL

**Review by kangkaisen — APPROVED** [review]

**Review by LiShuMing — APPROVED** [review]

**Pull request merged**
