### PR TITLE
[Feature] Add lake materialized view class

### PR DESCRIPTION
**Pull request by wyb**
## What type of PR is this：
- [ ] BugFix
- [x] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

LakeMaterializedView extends MaterializedView and storage (cache) related operations are added in class like LakeTable.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 3.0
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Comment by wyb** [comment]
run all

**Review by Astralidea — DISMISSED** [review]

**Review by sduzh — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by ABingHuang — DISMISSED** [review]
LGTM

**Comment by wyb** [comment]
run starrocks_fe_unittest

**Comment by wyb** [comment]
run  starrocks_fe_unittest

**Comment by wyb** [comment]
run starrocks_admit_test

**Comment by wyb** [comment]
run starrocks_fe_unittest

**Comment by wyb** [comment]
run starrocks_fe_unittest

**Comment by wyb** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 45 / 67 (67.16%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/lake/LakeTable.java|3|6|50.00%|[202, 203, 205]|
|:large_blue_circle:|com/starrocks/lake/LakeMaterializedView.java|27|46|58.70%|[66, 75, 94, 95, 121, 122, 123, 124, 126, 127, 130, 131, 134, 135, 138, 143, 148, 149, 151]|
|:large_blue_circle:|com/starrocks/catalog/Table.java|11|11|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/OlapTable.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/lake/DeleteLakeTableTask.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/persist/gson/GsonUtils.java|2|2|100.00%|[]|

**Review by Astralidea — DISMISSED** [review]

**Comment by wyb** [comment]
run starrocks_admit_test

**Comment by wyb** [comment]
run starrocks_admit_test

**Comment by wyb** [comment]
run starrocks_fe_unittest

**Comment by wyb** [comment]
run starrocks_fe_unittest

**Review by sduzh — APPROVED** [review]

**Review by Astralidea — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wyb** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 45 / 67 (67.16%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/lake/LakeTable.java|3|6|50.00%|[202, 203, 205]|
|:large_blue_circle:|com/starrocks/lake/LakeMaterializedView.java|27|46|58.70%|[66, 75, 94, 95, 121, 122, 123, 124, 126, 127, 130, 131, 134, 135, 138, 143, 148, 149, 151]|
|:large_blue_circle:|com/starrocks/catalog/Table.java|11|11|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/OlapTable.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/lake/DeleteLakeTableTask.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/persist/gson/GsonUtils.java|2|2|100.00%|[]|

**Comment by wyb** [comment]
run starrocks_admit_test

**Comment by wyb** [comment]
run starrocks_admit_test

**Comment by wyb** [comment]
@Mergifyio backport branch-3.0

**Pull request merged**
