### PR TITLE
[Tool] Add allin1 docker image build to release-docker-image flow

### PR DESCRIPTION
**Pull request by dengliu**
## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [X] Tool

## Which issues of this PR fixes ：
Add allin1 docker image build to release-docker-image flow

## Problem Summary(Required) ：
Ditto
## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [X] I have checked the version labels which the pr will be auto backported to target branch
  - [X] 3.0
  - [X] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Comment by dengliu** [comment]
@imay @chaoyli PTAL

**Review by kevincai — APPROVED** [review]

**Review by chaoyli — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by dengliu** [comment]
@Mergifyio backport branch-2.5

**Comment by dengliu** [comment]
@Mergifyio backport branch-3.0

**Pull request merged**
