### PR TITLE
[Enhancement] Change Sort Key Order for AirByte Tables

### PR DESCRIPTION
**Pull request by Ashish-Bansal**
## Description 

1. Fix AirByte destination StarRocks build by dep change
2. Change Sort Key Order to improve performance for querying newly added rows by AirByte

## What type of PR is this:
- [x] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4

### CODE REVIEW

**Review by dirtysalt — APPROVED** [review]

**Comment by dirtysalt** [comment]
@liuzhongjun89 could you take a look?

And BTW, is it possible to do normalization in starrocks-destination?  Is that hard?

**Comment by liuzhongjun89** [comment]
> And BTW, is it possible to do normalization in starrocks-destination? Is that hard?
Airbyte use dbt to do normalization or simply we can do a data type mapping in starrocks-destination.

**Review by liuzhongjun89 — APPROVED** [review]

**Review by imay — APPROVED** [review]

**Comment by Ashish-Bansal** [comment]
@liuzhongjun89 

> simply we can do a data type mapping in starrocks-destination

Do other AirByte destinations support simple data type mapping? Do they handle schema changes in the sources?

**Comment by liuzhongjun89** [comment]
As far as I know,  the ElasticSearch destination write data directly into its own column echo field.  SQL based destinations such as mysql/bigquery/clickhouse etc support basic normalization with dbt.

https://docs.airbyte.com/understanding-airbyte/basic-normalization

**Comment by liuzhongjun89** [comment]
https://docs.airbyte.com/integrations/destinations/elasticsearch

**Comment by Ashish-Bansal** [comment]
I introduced a bug here. Basically, I changed the order of columns here https://github.com/StarRocks/starrocks/pull/25026/files#diff-dd73711ca4525d7cda2f966cf133d5b86391546fafbf601e6a297096ef4a8567R83-R84 but during data load to StarRocks, we end up inserting `_airbyte_emitted_at` value into `_airbyte_ab_id` and vice-versa. I'll try to fix it later tomorrow.

**Pull request merged**
