### PR TITLE
[BugFix] Fix field display order is inconsistent with the statement of table creation when select * from iceberg_table

### LINKED ISSUE #15498: Iceberg table field display order is inconsistent with the statement of table creation when select * from icebergtable
### Steps to reproduce the behavior (Required)
1.hive create talbe 
create table hive_prod.sr_orc_02(
c_bool boolean,
c_int int,
c_date date,
c_string string
)
USING iceberg
TBLPROPERTIES('write.format.default'='orc','write.parquet.compression-codec'='snappy');
insert into hive_prod.iceberg_db.sr_orc_02 select true,1,cast('2022-08-08' as date),'Hello, China!';

2.sr create catalog
create external catalog iceberg_catalog_02  properties("type"="iceberg","iceberg.catalog.hive.metastore.uris"="thrift://xxx:9083","iceberg.catalog.type"="HIVE");
3.select * from 
### Expected behavior (Required)
+--------+-------+------------+---------------+
| c_bool | c_int | c_date     | c_string      |
+--------+-------+------------+---------------+
|      1 |     1 | 2022-08-08 | Hello, China! |
+--------+-------+------------+---------------+
### Real behavior (Required)
+------------+---------------+-------+--------+
| c_date     | c_string      | c_int | c_bool |
+------------+---------------+-------+--------+
| 2022-08-08 | Hello, China! |     1 |      1 |
+------------+---------------+-------+--------+
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
**main-branch code**

### PR DESCRIPTION
**Pull request by leoyy0316**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #15498

## Problem Summary(Required) ：

Fix field display order is inconsistent with the statement of table creation when select * from icebergtable
## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 6 / 9 (66.67%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/connector/iceberg/IcebergUtil.java|6|9|66.67%|[312, 313, 314]|

**Comment by mofeiatwork** [comment]
run starrocks_fe_unittest

**Comment by mofeiatwork** [comment]
run starrocks_admit_test

**Review by murphyatwork — APPROVED** [review]

**Review by imay — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by leoyy0316** [comment]
run starrocks_fe_unittest

**Comment by leoyy0316** [comment]
run starrocks_fe_unittest

**Comment by leoyy0316** [comment]
run starrocks_fe_unittest

**Comment by leoyy0316** [comment]
run starrocks_fe_unittest

**Comment by leoyy0316** [comment]
run starrocks_fe_unittest

**Comment by leoyy0316** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 6 / 9 (66.67%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/connector/iceberg/IcebergUtil.java|6|9|66.67%|[312, 313, 314]|

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
