### PR TITLE
[BugFix] Fix the issue of returning empty results when querying the hudi table

### LINKED ISSUE #12931: [HUDI] error from hudi external table after hudi table delete some rows
### Steps to reproduce the behavior (Required)
1. create hudi table and insert 2 rows:
```
create table hudi_mor_tbl_refresh_test_new(
 uuid int,
 col_boolean boolean,
 col_long bigint,
 col_float float,
 col_double double,
 col_decimal decimal(38,18),
 col_timestamp timestamp,
 col_string string,
 col_binary binary,
 col_array array<int>,
 col_struct struct<a:string,b:int>,
 col_map map<string,int>
 ) USING hudi 
 TBLPROPERTIES(
 type = 'mor',
 primarykey = 'uuid');
 insert into hudi_mor_tbl_refresh_test_new select 1,true,1.01,1.001,1.0001,10000000000.0000000001,cast('2020-01-01 00:00:01' as timestamp),'Top 10 Unsolved Mysteries of Paleontological Dinosaurs, Did You Know?',cast('1110001010101011001001' as binary),array(1,10,100),null,null;
 insert into hudi_mor_tbl_refresh_test_new select 2,true,1.01,1.001,1.0001,10000000000.0000000001,cast('2020-01-01 00:00:01' as timestamp),'Top 10 Unsolved Mysteries of Paleontological Dinosaurs, Did You Know?',cast('1110001010101011001001' as binary),array(1,10,100),null,null;
```
 
2. select from catalog.hudi_db.hudi_tbl:
```
mysql> select col_float from hudi_catalog.hudi_db.hudi_mor_tbl_refresh_test_new;
+-----------+
| col_float |
+-----------+
|     1.001 |
|     1.001 |
+-----------+
2 rows in set (0.05 sec)
```

3. delete 1 row from hudi table:
delete from hudi_mor_tbl_refresh_test_new where uuid=2;

4. select from catalog.hudi_db.hudi_tbl error after refresh external table:
```
mysql> select col_float from hudi_catalog.hudi_db.hudi_mor_tbl_refresh_test_new;
+-----------+
| col_float |
+-----------+
|     1.001 |
|     1.001 |
+-----------+
2 rows in set (0.05 sec)
 
mysql> refresh external table hudi_catalog.hudi_db.hudi_mor_tbl_refresh_test_new;
Query OK, 0 rows affected (0.06 sec)

mysql> select col_float from hudi_catalog.hudi_db.hudi_mor_tbl_refresh_test_new;
ERROR 1064 (HY000): Failed to open the off-heap table scanner.:file = hdfs://emr-header-1.cluster-49155:9000/user/hive/warehouse/hudi_db.db/hudi_mor_tbl_refresh_test_new/01e16254-f814-4689-ad25-cd596a529cda-0_0-643-4036_20221103174839928.parquet
```

### Expected behavior (Required)
return 1 row

### Real behavior (Required)
error

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
mysql> select current_version();
+----------------------+
| current_version()    |
+----------------------+
| MAIN-RELEASE 100ad04 |
+----------------------+
1 row in set (0.01 sec)
```

### PR DESCRIPTION
**Pull request by miomiocat**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：
- Fix #12931
- Add/Fix some metrics

### CODE REVIEW

**Review by dirtysalt — DISMISSED** [review]

**Review by caneGuy — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by miomiocat** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by miomiocat** [comment]
run starrocks_admit_test

**Comment by miomiocat** [comment]
run starrocks_fe_unittest

**Comment by miomiocat** [comment]
run starrocks_fe_unittest

**Comment by miomiocat** [comment]
run starrocks_admit_test

**Comment by miomiocat** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/connector/hive/HiveMetastoreApiConverter.java|1|1|100.00%|[]|

**Review by dirtysalt — APPROVED** [review]

**Review by caneGuy — APPROVED** [review]

**Pull request merged**
