### PR TITLE
[BugFix] fix bugs from reusing common expressions with nested high-order functions (backport #18330) 

### PR DESCRIPTION
**Pull request by fzhedu**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #https://github.com/StarRocks/starrocks/pull/19026

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Review by kangkaisen — DISMISSED** [review]

**Comment by fzhedu** [comment]
run starrocks_clang-format

**Comment by fzhedu** [comment]
run starrocks_fe_unittest

**Comment by fzhedu** [comment]
ruun
starrocks_tscancode

**Comment by fzhedu** [comment]
run starrocks_fe_unittest

**Comment by fzhedu** [comment]
run starrocks_fe_unittest

**Comment by fzhedu** [comment]
run starrocks_fe_unittest

**Comment by fzhedu** [comment]
run starrocks_clang-format

**Comment by fzhedu** [comment]
run starrocks_fe_unittest

**Comment by fzhedu** [comment]
run starrocks_clang-format

**Comment by fzhedu** [comment]
run starrocks_tscancode

**Comment by fzhedu** [comment]
run starrocks_fe_unittest

**Comment by fzhedu** [comment]
run starrocks_fe_unittest

**Comment by fzhedu** [comment]
run starrocks_tscancode

**Pull request merged**
