### PR TITLE
[BugFix] create_cast_expr encounter unexpected null causing crash

### PR DESCRIPTION
**Pull request by fzhedu**
Signed-off-by: fzhedu <fzhedu@gmail.com>

## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #
array_filter encounters BE crash, introuduced by https://github.com/StarRocks/starrocks/pull/16117

```
mysql> select array_filter([1],[[1]]) ;
ERROR 1064 (HY000): Backend not found. Check if any backend is down or not. backend: [172.26.92.195 alive: false inBlacklist: true]
```
## Problem Summary(Required) ：

create_cast_expr encounter unexpected null causing crash, so change return null to error status.

results:
```
mysql> select array_filter([1],[[1]]) ;
ERROR 1064 (HY000): Vectorized engine does not support the operator, cast from INVALID to ARRAY failed, maybe use switch function

```

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Comment by fzhedu** [comment]
@alvin-coding add some tests for https://github.com/StarRocks/starrocks/pull/16117, which introduct this bug. The tests should include some unsupported cases, map casts, structs casts.

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 1 / 3 (33.33%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/ExpressionAnalyzer.java|1|3|33.33%|[833, 834]|

**Review by imay — DISMISSED** [review]

**Review by kangkaisen — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 1 / 3 (33.33%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/ExpressionAnalyzer.java|1|3|33.33%|[833, 834]|

**Review by murphyatwork — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by mofeiatwork** [comment]
run starrocks_admit_test

**Pull request merged**
