### PR TITLE
[WIP][Refactor] Refactor tablet schema map for support different version tablet schema

### PR DESCRIPTION
**Pull request by sevev**
Why I'm doing:

What I'm doing:

Fixes #issue

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [x] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Comment by sduzh** [comment]
Different versions of Schema have the same schema id?

**Comment by sevev** [comment]
> Different versions of Schema have the same schema id?

Yes. After support fast schema evolution, a tablet may has multiple versions of schemas, and each rowset will hold a tablet schema. Presently, the `tablet_schema_map` does not support storing multiple versions of tablet schemas. Therefore, I am considering adding support for versions to save memory.

**Comment by sduzh** [comment]
> > Different versions of Schema have the same schema id?
> 
> Yes. After support fast schema evolution, a tablet may has multiple versions of schemas, and each rowset will hold a tablet schema. Presently, the `tablet_schema_map` does not support storing multiple versions of tablet schemas. Therefore, I am considering adding support for versions to save memory.

Can't we change the schema id every time a schena change occurs?

**Comment by sduzh** [comment]
> > > Different versions of Schema have the same schema id?
> > 
> > 
> > Yes. After support fast schema evolution, a tablet may has multiple versions of schemas, and each rowset will hold a tablet schema. Presently, the `tablet_schema_map` does not support storing multiple versions of tablet schemas. Therefore, I am considering adding support for versions to save memory.
> 
> Can't we change the schema id every time a schena change occurs?

It's a bit strange that the schema id is the same for different schemas

**Comment by sevev** [comment]
> schena

I have considered this implementation approach, but I feel that maintaining an immutable `schema_id` for a tablet seems more reasonable. Another consideration is that I am currently unable to fully assess the impact of changing the schema id, and I am still evaluating this aspect.

**Comment by sduzh** [comment]
> > schena
> 
> I have considered this implementation approach, but I feel that maintaining an immutable `schema_id` for a tablet seems more reasonable. Another consideration is that I am currently unable to fully assess the impact of changing the schema id, and I am still evaluating this aspect.

Actually, I'm going to change the schema id in the new schema evolution implementation in shared data mode, which should ideally be consistent with non-shared data mode.

**Comment by sduzh** [comment]
> > schena
> 
> I have considered this implementation approach, but I feel that maintaining an immutable `schema_id` for a tablet seems more reasonable. Another consideration is that I am currently unable to fully assess the impact of changing the schema id, and I am still evaluating this aspect.

IMHO, The schema id should be used to uniquely identify a schema. If you change the schema, i.e. create a new schema, then you should use a different schema id.

**Comment by sevev** [comment]
> > > schena
> > 
> > 
> > I have considered this implementation approach, but I feel that maintaining an immutable `schema_id` for a tablet seems more reasonable. Another consideration is that I am currently unable to fully assess the impact of changing the schema id, and I am still evaluating this aspect.
> 
> IMHO, The schema id should be used to uniquely identify a schema. If you change the schema, i.e. create a new schema, then you should use a different schema id.

I agree with you, what I think is the schema id right now is index id of the `MaterializeIndex` right now and I think the index id should be immutable and that is why I don't want to change the schema id even we update the table schema. I feel this might not be the most critical issue, just a difference in implementation choices. If you will change the schema id in shared-data mode, I  believe maintaining consistency is necessary. I will close this PR and modify the implementation approach.

**Pull request closed without merging**
