### PR TITLE
[Doc] EN WalkThrough - INSERT

### PR DESCRIPTION
**Pull request by EsoragotoSpirit**
## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [x] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Review by hellolilyliuyi — APPROVED** [review]

**Review by femiiii — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by EsoragotoSpirit** [comment]
run starrocks_be_unittest

**Comment by EsoragotoSpirit** [comment]
run starrocks_fe_unittest

**Comment by EsoragotoSpirit** [comment]
@mergify backport branch-2.4

**Pull request merged**
