### PR TITLE
[Feature] Support group-level queue and control concurrency limit in Leader FE 

### PR DESCRIPTION
**Pull request by ZiheLiu**
Cherry-pick from #29803 #29412 #29869 #30145 #30395 #30626 #30580.

[BugFix] Fix pending queryeis when group.concurrency_limit is null (#29803)

[Enhancement] Mark statistics Job and no need queued jobs for query queue (#29412)

[Enhancement] Add metrics for group-level query queue (#29869)
[Build] Add the test dependency assertj
[Feature] Support group-level queue with max_cpu_cores (backport #30145)
[Enhancement] Add group-level metric inuse_cpu_cores in BE (#30395)
[BugFix] Fix load type resource group selection
[BugFix] Fix lost resource group in audit log for insert (backport #30626)
[Feature] Support plan_cpu_cost_range and plan_mem_cost_range in resource group classifier (backport #30580)
[BugFix] Fix resource group in audit log and persist planCostRange

## What type of PR is this:

- [ ] BugFix
- [ x Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.2
  - [x] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:disappointed: **fail** : 344 / 929 (37.03%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/ast/AstVisitor.java|0|2|00.00%|[546, 550]|
|:large_blue_circle:|com/starrocks/service/FrontendServiceImpl.java|0|15|00.00%|[2071, 2075, 2113, 2114, 2116, 2122, 2123, 2125, 2126, 2128, 2133, 2135, 2136, 2137, 2139]|
|:large_blue_circle:|com/starrocks/common/Status.java|0|5|00.00%|[82, 86, 87, 88, 90]|
|:large_blue_circle:|com/starrocks/sql/ast/ShowResourceGroupUsageStmt.java|0|38|00.00%|[33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 51, 52, 55, 56, 57, 58, 63, 64, 65, 68, 73, 78, 83, 87, 94, 95, 96, 97, 101, 102, 103, 104, 108, 112]|
|:large_blue_circle:|com/starrocks/qe/scheduler/slot/LogicalSlot.java|0|65|00.00%|[53, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 68, 72, 73, 76, 77, 80, 81, 84, 85, 88, 89, 92, 93, 94, 95, 96, 97, 98, 99, 101, 105, 106, 110, 114, 118, 122, 126, 130, 134, 138, 142, 146, 151, 152, 156, 157, 158, 159, 165, 166, 168, 170, 171, 172, 173, 174, 175, 178, 182, 184, 186, 188, 191, 193]|
|:large_blue_circle:|com/starrocks/qe/scheduler/RecoverableException.java|0|2|00.00%|[19, 20]|
|:large_blue_circle:|com/starrocks/sql/ast/ShowRunningQueriesStmt.java|0|32|00.00%|[33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 50, 51, 56, 57, 60, 61, 62, 63, 68, 69, 70, 73, 78, 83, 88, 92]|
|:large_blue_circle:|com/starrocks/qe/scheduler/SchedulerException.java|0|2|00.00%|[21, 22]|
|:large_blue_circle:|com/starrocks/qe/scheduler/slot/PendingSlotRequest.java|0|23|00.00%|[25, 27, 28, 29, 30, 33, 37, 41, 45, 46, 49, 50, 51, 54, 55, 56, 59, 60, 61, 64, 65, 66, 70]|
|:large_blue_circle:|com/starrocks/qe/ShowExecutor.java|2|34|05.88%|[289, 291, 707, 708, 710, 711, 712, 714, 716, 717, 718, 720, 721, 723, 725, 726, 729, 730, 732, 733, 734, 735, 736, 737, 738, 739, 740, 741, 742, 743, 745, 746]|
|:large_blue_circle:|com/starrocks/qe/QueryQueueManager.java|5|43|11.63%|[61, 62, 65, 68, 70, 71, 72, 77, 78, 79, 81, 82, 85, 89, 90, 91, 92, 93, 95, 96, 98, 104, 106, 107, 126, 137, 138, 139, 140, 143, 144, 146, 147, 148, 149, 150, 152, 153]|
|:large_blue_circle:|com/starrocks/qe/scheduler/slot/SlotProvider.java|12|76|15.79%|[53, 54, 55, 57, 61, 62, 63, 64, 68, 69, 70, 71, 72, 73, 75, 79, 80, 81, 82, 83, 86, 87, 89, 90, 93, 101, 102, 103, 106, 107, 108, 115, 116, 117, 127, 128, 129, 132, 133, 135, 140, 141, 142, 143, 146, 147, 148, 149, 151, 156, 159, 160, 161, 164, 168, 169, 170, 171, 172, 174, 176, 177, 178, 179]|
|:large_blue_circle:|com/starrocks/system/ComputeNode.java|6|33|18.18%|[360, 361, 362, 364, 365, 591, 595, 596, 599, 601, 602, 605, 606, 607, 616, 617, 618, 619, 620, 621, 624, 625, 629, 633, 637, 641, 645]|
|:large_blue_circle:|com/starrocks/qe/scheduler/slot/SlotRequestQueue.java|16|75|21.33%|[52, 53, 54, 57, 58, 59, 60, 61, 65, 66, 67, 70, 72, 73, 75, 82, 83, 85, 86, 97, 98, 99, 103, 104, 105, 106, 109, 110, 111, 114, 115, 116, 118, 119, 120, 122, 123, 124, 126, 130, 131, 135, 139, 140, 144, 145, 148, 149, 152, 160, 161, 162, 163, 166, 167, 170, 171, 172, 174]|
|:large_blue_circle:|com/starrocks/qe/scheduler/slot/SlotManager.java|50|154|32.47%|[123, 124, 127, 128, 135, 136, 140, 141, 142, 145, 149, 150, 151, 152, 153, 155, 156, 157, 158, 159, 160, 161, 162, 163, 166, 167, 168, 169, 170, 171, 173, 174, 175, 177, 178, 179, 181, 184, 185, 186, 188, 189, 190, 191, 192, 193, 196, 204, 205, 206, 207, 210, 211, 212, 215, 216, 218, 219, 220, 221, 223, 224, 225, 228, 229, 230, 231, 233, 234, 235, 236, 237, 240, 242, 243, 244, 245, 246, 247, 248, 249, 252, 253, 254, 255, 257, 258, 259, 269, 275, 289, 290, 291, 292, 293, 308, 309, 311, 312, 313, 314, 322, 332, 333]|
|:large_blue_circle:|com/starrocks/qe/scheduler/slot/AllocatedSlots.java|12|32|37.50%|[37, 41, 45, 46, 48, 49, 50, 51, 54, 55, 56, 59, 61, 62, 64, 71, 72, 74, 75, 83]|
|:large_blue_circle:|com/starrocks/system/SystemInfoService.java|8|17|47.06%|[492, 493, 494, 495, 496, 497, 499, 500, 501]|
|:large_blue_circle:|com/starrocks/sql/ast/AlterResourceGroupStmt.java|1|2|50.00%|[87]|
|:large_blue_circle:|com/starrocks/server/NodeMgr.java|11|21|52.38%|[925, 927, 940, 941, 1069, 1087, 1088, 1115, 1247, 1248]|
|:large_blue_circle:|com/starrocks/qe/Coordinator.java|19|31|61.29%|[248, 249, 320, 321, 336, 355, 356, 411, 415, 416, 419, 423]|
|:large_blue_circle:|com/starrocks/catalog/ResourceGroupMgr.java|15|23|65.22%|[312, 313, 314, 317, 318, 321, 322, 325]|
|:large_blue_circle:|com/starrocks/qe/scheduler/slot/ResourceUsageMonitor.java|25|37|67.57%|[43, 44, 51, 55, 56, 62, 83, 85, 86, 104, 127, 128]|
|:large_blue_circle:|com/starrocks/system/Frontend.java|5|7|71.43%|[193, 195]|
|:large_blue_circle:|com/starrocks/catalog/ResourceGroup.java|13|15|86.67%|[216, 260]|
|:large_blue_circle:|com/starrocks/catalog/ResourceGroupClassifier.java|41|42|97.62%|[247]|
|:large_blue_circle:|com/starrocks/metric/ResourceGroupMetricMgr.java|39|39|100.00%|[]|
|:large_blue_circle:|com/starrocks/qe/QeProcessorImpl.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/ResourceGroupAnalyzer.java|23|23|100.00%|[]|
|:large_blue_circle:|com/starrocks/common/Config.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/scheduler/mv/MVMaintenanceJob.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/statistic/StatisticUtils.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AnalyzerUtils.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/qe/StmtExecutor.java|7|7|100.00%|[]|
|:large_blue_circle:|com/starrocks/leader/ReportHandler.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/qe/CoordinatorPreprocessor.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|8|8|100.00%|[]|
|:large_blue_circle:|com/starrocks/qe/ConnectContext.java|11|11|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 34 / 61 (55.74%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/agent/task_worker_pool.cpp|0|3|00.00%|[780, 781, 782]|
|:large_blue_circle:|src/exec/pipeline/pipeline_driver.cpp|0|3|00.00%|[743, 744, 745]|
|:large_blue_circle:|src/exec/workgroup/work_group.h|1|2|50.00%|[145]|
|:large_blue_circle:|src/exec/workgroup/work_group.cpp|33|53|62.26%|[48, 49, 389, 406, 407, 408, 409, 410, 413, 414, 416, 418, 419, 423, 424, 425, 427, 431, 432, 433]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 34 / 61 (55.74%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/agent/task_worker_pool.cpp|0|3|00.00%|[780, 781, 782]|
|:large_blue_circle:|src/exec/pipeline/pipeline_driver.cpp|0|3|00.00%|[743, 744, 745]|
|:large_blue_circle:|src/exec/workgroup/work_group.h|1|2|50.00%|[145]|
|:large_blue_circle:|src/exec/workgroup/work_group.cpp|33|53|62.26%|[48, 49, 389, 406, 407, 408, 409, 410, 413, 414, 416, 418, 419, 423, 424, 425, 427, 431, 432, 433]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:disappointed: **fail** : 344 / 929 (37.03%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/ast/AstVisitor.java|0|2|00.00%|[546, 550]|
|:large_blue_circle:|com/starrocks/service/FrontendServiceImpl.java|0|15|00.00%|[2071, 2075, 2113, 2114, 2116, 2122, 2123, 2125, 2126, 2128, 2133, 2135, 2136, 2137, 2139]|
|:large_blue_circle:|com/starrocks/common/Status.java|0|5|00.00%|[82, 86, 87, 88, 90]|
|:large_blue_circle:|com/starrocks/sql/ast/ShowResourceGroupUsageStmt.java|0|38|00.00%|[33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 51, 52, 55, 56, 57, 58, 63, 64, 65, 68, 73, 78, 83, 87, 94, 95, 96, 97, 101, 102, 103, 104, 108, 112]|
|:large_blue_circle:|com/starrocks/qe/scheduler/slot/LogicalSlot.java|0|65|00.00%|[53, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 68, 72, 73, 76, 77, 80, 81, 84, 85, 88, 89, 92, 93, 94, 95, 96, 97, 98, 99, 101, 105, 106, 110, 114, 118, 122, 126, 130, 134, 138, 142, 146, 151, 152, 156, 157, 158, 159, 165, 166, 168, 170, 171, 172, 173, 174, 175, 178, 182, 184, 186, 188, 191, 193]|
|:large_blue_circle:|com/starrocks/qe/scheduler/RecoverableException.java|0|2|00.00%|[19, 20]|
|:large_blue_circle:|com/starrocks/sql/ast/ShowRunningQueriesStmt.java|0|32|00.00%|[33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 50, 51, 56, 57, 60, 61, 62, 63, 68, 69, 70, 73, 78, 83, 88, 92]|
|:large_blue_circle:|com/starrocks/qe/scheduler/SchedulerException.java|0|2|00.00%|[21, 22]|
|:large_blue_circle:|com/starrocks/qe/scheduler/slot/PendingSlotRequest.java|0|23|00.00%|[25, 27, 28, 29, 30, 33, 37, 41, 45, 46, 49, 50, 51, 54, 55, 56, 59, 60, 61, 64, 65, 66, 70]|
|:large_blue_circle:|com/starrocks/qe/ShowExecutor.java|2|34|05.88%|[289, 291, 707, 708, 710, 711, 712, 714, 716, 717, 718, 720, 721, 723, 725, 726, 729, 730, 732, 733, 734, 735, 736, 737, 738, 739, 740, 741, 742, 743, 745, 746]|
|:large_blue_circle:|com/starrocks/qe/QueryQueueManager.java|5|43|11.63%|[61, 62, 65, 68, 70, 71, 72, 77, 78, 79, 81, 82, 85, 89, 90, 91, 92, 93, 95, 96, 98, 104, 106, 107, 126, 137, 138, 139, 140, 143, 144, 146, 147, 148, 149, 150, 152, 153]|
|:large_blue_circle:|com/starrocks/qe/scheduler/slot/SlotProvider.java|12|76|15.79%|[53, 54, 55, 57, 61, 62, 63, 64, 68, 69, 70, 71, 72, 73, 75, 79, 80, 81, 82, 83, 86, 87, 89, 90, 93, 101, 102, 103, 106, 107, 108, 115, 116, 117, 127, 128, 129, 132, 133, 135, 140, 141, 142, 143, 146, 147, 148, 149, 151, 156, 159, 160, 161, 164, 168, 169, 170, 171, 172, 174, 176, 177, 178, 179]|
|:large_blue_circle:|com/starrocks/system/ComputeNode.java|6|33|18.18%|[360, 361, 362, 364, 365, 591, 595, 596, 599, 601, 602, 605, 606, 607, 616, 617, 618, 619, 620, 621, 624, 625, 629, 633, 637, 641, 645]|
|:large_blue_circle:|com/starrocks/qe/scheduler/slot/SlotRequestQueue.java|16|75|21.33%|[52, 53, 54, 57, 58, 59, 60, 61, 65, 66, 67, 70, 72, 73, 75, 82, 83, 85, 86, 97, 98, 99, 103, 104, 105, 106, 109, 110, 111, 114, 115, 116, 118, 119, 120, 122, 123, 124, 126, 130, 131, 135, 139, 140, 144, 145, 148, 149, 152, 160, 161, 162, 163, 166, 167, 170, 171, 172, 174]|
|:large_blue_circle:|com/starrocks/qe/scheduler/slot/SlotManager.java|50|154|32.47%|[123, 124, 127, 128, 135, 136, 140, 141, 142, 145, 149, 150, 151, 152, 153, 155, 156, 157, 158, 159, 160, 161, 162, 163, 166, 167, 168, 169, 170, 171, 173, 174, 175, 177, 178, 179, 181, 184, 185, 186, 188, 189, 190, 191, 192, 193, 196, 204, 205, 206, 207, 210, 211, 212, 215, 216, 218, 219, 220, 221, 223, 224, 225, 228, 229, 230, 231, 233, 234, 235, 236, 237, 240, 242, 243, 244, 245, 246, 247, 248, 249, 252, 253, 254, 255, 257, 258, 259, 269, 275, 289, 290, 291, 292, 293, 308, 309, 311, 312, 313, 314, 322, 332, 333]|
|:large_blue_circle:|com/starrocks/qe/scheduler/slot/AllocatedSlots.java|12|32|37.50%|[37, 41, 45, 46, 48, 49, 50, 51, 54, 55, 56, 59, 61, 62, 64, 71, 72, 74, 75, 83]|
|:large_blue_circle:|com/starrocks/system/SystemInfoService.java|8|17|47.06%|[492, 493, 494, 495, 496, 497, 499, 500, 501]|
|:large_blue_circle:|com/starrocks/sql/ast/AlterResourceGroupStmt.java|1|2|50.00%|[87]|
|:large_blue_circle:|com/starrocks/server/NodeMgr.java|11|21|52.38%|[925, 927, 940, 941, 1069, 1087, 1088, 1115, 1247, 1248]|
|:large_blue_circle:|com/starrocks/qe/Coordinator.java|19|31|61.29%|[248, 249, 320, 321, 336, 355, 356, 411, 415, 416, 419, 423]|
|:large_blue_circle:|com/starrocks/catalog/ResourceGroupMgr.java|15|23|65.22%|[312, 313, 314, 317, 318, 321, 322, 325]|
|:large_blue_circle:|com/starrocks/qe/scheduler/slot/ResourceUsageMonitor.java|25|37|67.57%|[43, 44, 51, 55, 56, 62, 83, 85, 86, 104, 127, 128]|
|:large_blue_circle:|com/starrocks/system/Frontend.java|5|7|71.43%|[193, 195]|
|:large_blue_circle:|com/starrocks/catalog/ResourceGroup.java|13|15|86.67%|[216, 260]|
|:large_blue_circle:|com/starrocks/catalog/ResourceGroupClassifier.java|41|42|97.62%|[247]|
|:large_blue_circle:|com/starrocks/metric/ResourceGroupMetricMgr.java|39|39|100.00%|[]|
|:large_blue_circle:|com/starrocks/qe/QeProcessorImpl.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/ResourceGroupAnalyzer.java|23|23|100.00%|[]|
|:large_blue_circle:|com/starrocks/common/Config.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/scheduler/mv/MVMaintenanceJob.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/statistic/StatisticUtils.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AnalyzerUtils.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/qe/StmtExecutor.java|7|7|100.00%|[]|
|:large_blue_circle:|com/starrocks/leader/ReportHandler.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/qe/CoordinatorPreprocessor.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|8|8|100.00%|[]|
|:large_blue_circle:|com/starrocks/qe/ConnectContext.java|11|11|100.00%|[]|

**Review by satanson — APPROVED** [review]

**Review by satanson — APPROVED** [review]

**Review by kangkaisen — APPROVED** [review]

**Pull request merged**
