### PR TITLE
[BugFix] Redefine mv's staleness to make it more clear (#27659)

### LINKED ISSUE #27371: [materialized view optimization] mv_rewrite_staleness_second parameter invalid
### Steps to reproduce the behavior (Required)
```
CREATE TABLE t1 (
    k1 int,
    k2 int
)
DUPLICATE KEY(k1);
INSERT INTO t1 VALUES (1,1),(1,2);
CREATE MATERIALIZED VIEW mv1 REFRESH MANUAL PROPERTIES ("mv_rewrite_staleness_second"="5") AS SELECT k1,sum(k2) FROM t1 group by k1;

REFRESH MATERIALIZED VIEW mv1 with sync mode;
INSERT INTO t1 VALUES (2,2);
SELECT k1,sum(k2) FROM t1 group by k1 order by 1;
select sleep(5);
REFRESH MATERIALIZED VIEW mv1 with sync mode;
INSERT INTO t1 VALUES (2,2);
SELECT k1,sum(k2) FROM t1 group by k1 order by 1;
```

### Expected behavior (Required)
```
+------+---------+
| k1   | sum(k2) |
+------+---------+
|    1 |       3 |
|    2 |       2 |
+------+---------+
```
### Real behavior (Required)
```
+------+---------+
| k1   | sum(k2) |
+------+---------+
|    1 |       3 |
|    2 |       4 |
+------+---------+
```
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
`branch-3.1-0f690e6`

### PR DESCRIPTION
**Pull request by LiShuMing**
Fixes #27371

Fixes #issue

## What type of PR is this:
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 49 / 58 (84.48%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/alter/AlterJobMgr.java|0|3|00.00%|[669, 670, 671]|
|:large_blue_circle:|com/starrocks/catalog/MaterializedView.java|40|46|86.96%|[571, 618, 641, 656, 676, 691]|
|:large_blue_circle:|com/starrocks/scheduler/PartitionBasedMvRefreshProcessor.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/common/util/DateUtils.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/MvUtils.java|3|3|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 60 / 67 (89.55%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/alter/AlterJobMgr.java|0|3|00.00%|[669, 670, 671]|
|:large_blue_circle:|com/starrocks/catalog/MaterializedView.java|47|51|92.16%|[630, 638, 649, 655]|
|:large_blue_circle:|com/starrocks/scheduler/PartitionBasedMvRefreshProcessor.java|5|5|100.00%|[]|
|:large_blue_circle:|com/starrocks/common/util/DateUtils.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/MvUtils.java|6|6|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 60 / 67 (89.55%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/alter/AlterJobMgr.java|0|3|00.00%|[669, 670, 671]|
|:large_blue_circle:|com/starrocks/catalog/MaterializedView.java|47|51|92.16%|[630, 638, 649, 655]|
|:large_blue_circle:|com/starrocks/scheduler/PartitionBasedMvRefreshProcessor.java|5|5|100.00%|[]|
|:large_blue_circle:|com/starrocks/common/util/DateUtils.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/MvUtils.java|6|6|100.00%|[]|

**Review by kangkaisen — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Pull request merged**
