### PR TITLE
[BugFix] fix NLJ stuck for empty output

### LINKED ISSUE #16869: Complex expression evaluation could not be interruptted
### Steps to reproduce the behavior (Required)

1. Create a SQL with a super complex evaluation, which would takes tens of minutes to evaluate a chunk
2. If user try to cancel this query, the execution could not be interrupted, until the expression evaluation terminates
3. Finally, this query would become a zombie query, which run at background, but not visible at FE
4. Causes
    1. The `Expr::evaluate` could not be interrupted until it finishes
    2. This execution thread would be occupied in pipeline engine

Solutions:
1. optimize these expensive json functions
2. Make the NLJoin operator interruptable for corner case
3. make the `Expr::evaluate` interruptable 
4. make the UDF interruptable

For example, construct an expensive expression on ssb dataset:
```sql
select
    count(*)
from
    lineorder t0
    right join lineorder t1 
    on 
      cast(json_object('k1', t0.lo_orderkey) -> 'k1' as string) = 
      cast(json_object('k2', t1.lo_linenumber) -> 'k2' as string)
    or t0.lo_custkey = t1.lo_suppkey;
```

perf: 
image

### PR DESCRIPTION
**Pull request by murphyatwork**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #16869

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 2.5
  - [x] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Comment by mofeiatwork** [comment]
run starrocks_admit_test

**Review by kangkaisen — DISMISSED** [review]

**Comment by mofeiatwork** [comment]
run starrocks_admit_test

**Review by imay — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.4

**Pull request merged**
