### PR TITLE
[Bugfix] Fix the collecting of table-level scanning statistics

### LINKED ISSUE #9306: Table-level scanning statistics not collected
### Steps to reproduce the behavior (Required)
1. SELECT * FROM table1;
2. curl http://fe:http_port/metrics?type=json\&with_table_metrics=minified

### Expected behavior (Required)
Scanning statistics like `table_scan_rows`, `table_scan_bytes` are not collected for `table1`.

### Real behavior (Required)
There should be some scanning statistics for `table1` returned in the response. 

```json
{"tags":{"metric":"table_scan_bytes","db_name":"db","table1":"t1","tbl_id":"20015"},"unit":"bytes","value":81},
{"tags":{"metric":"table_scan_rows","db_name":"db","table1":"t1","tbl_id":"20015"},"unit":"rows","value":9},
{"tags":{"metric":"table_scan_finished","db_name":"db","table1":"t1","tbl_id":"20015"},"unit":"requests","value":9}
```

### StarRocks version (Required)
 - 2.3

### PR DESCRIPTION
**Pull request by hffariel**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #9306

## Problem Summary(Required) ：

There should be some table-level scanning statistics returned in the `http://fe:http_port/metrics?type=json&with_table_metrics=minified`'s response.
```json
{"tags":{"metric":"table_scan_bytes","db_name":"db","table1":"t1","tbl_id":"20015"},"unit":"bytes","value":81},
{"tags":{"metric":"table_scan_rows","db_name":"db","table1":"t1","tbl_id":"20015"},"unit":"rows","value":9},
{"tags":{"metric":"table_scan_finished","db_name":"db","table1":"t1","tbl_id":"20015"},"unit":"requests","value":9}
```

### CODE REVIEW

**Review by chaoyli — DISMISSED** [review]

**Review by gengjun-git — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by hffariel** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by gengjun-git — APPROVED** [review]

**Comment by gengjun-git** [comment]
run starrocks_admit_test

**Review by chaoyli — APPROVED** [review]

**Review by chaoyli — APPROVED** [review]

**Pull request closed without merging**
