### PR TITLE
[BugFix] Fix information schema issue

### LINKED ISSUE #13311: [information_schema]MATERIALIZED VIEW  information error
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
```
CREATE TABLE `duplicate_table_with_null_partition` (
                                        `k1` date,
                                        `k2` datetime,
                                        `k3` char(20),
                                        `k4` varchar(20),
                                        `k5` boolean,
                                        `k6` tinyint,
                                        `k7` smallint,
                                        `k8` int,
                                        `k9` bigint,
                                        `k10` largeint,
                                        `k11` float,
                                        `k12` double,
                                        `k13` decimal(27,9)
                                    ) ENGINE=OLAP
                                    DUPLICATE KEY(`k1`, `k2`, `k3`, `k4`, `k5`)
                                    COMMENT "OLAP"
                                    PARTITION BY RANGE (k1) (
                                        START ("2020-05-01") END ("2021-10-04") EVERY (INTERVAL 15 day)
                                    )
                                    DISTRIBUTED BY HASH(`k1`, `k2`, `k3`, `k4`, `k5`) BUCKETS 3
                                    PROPERTIES (
                                        "replication_num" = "3",
                                        "storage_format" = "v2"
                                    );
curl --location-trusted -u root: -T /home/disk4/lvchenyang/codebak/StarRocksTest/lib/../common/data/basic_types_data_without_null -XPUT -H label:view_d668c55e_61ce_11ed_b633_00163e0e550b http://ip:port/api/test_info_tables_conf_d661acec_61ce_11ed_b633_00163e0e550b/duplicate_table_with_null_partition/_stream_load
CREATE MATERIALIZED VIEW mv1
                                             DISTRIBUTED BY HASH(k1) BUCKETS 10
                                             REFRESH ASYNC
                                             AS SELECT k1, k6, k7, k8, k9, k10
                                             FROM duplicate_table_with_null_partition;
```
2. SELECT  '....'
```
select * from information_schema.tables_config where TABLE_SCHEMA='test_info_tables_conf_d661acec_61ce_11ed_b633_00163e0e550b' and TABLE_NAME='mv1';
```
### Expected behavior (Required)
PRIMARY_KEY=def
PARTITION_KEY=def
PROPERTIES should be equal to reality
### Real behavior (Required)
image

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
+----------------------+
| current_version()    |
+----------------------+
| MAIN-RELEASE e21cd48 |
+----------------------+
```

### PR DESCRIPTION
**Pull request by waittttting**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #13311

## Problem Summary(Required) ：

Fix information schema issue
1. Added method getMaterializedViewPropMap for get mv.properties
2. Modify get sort key logic

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
## Please check the version labels which this pr will be auto backported to target branch and click the checkbox:

- [ ] check done.

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 9 / 25 (36.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/service/InformationSchemaDataSource.java|1|3|33.33%|[144, 145]|
|:large_blue_circle:|com/starrocks/catalog/MaterializedView.java|8|22|36.36%|[705, 707, 708, 711, 712, 713, 716, 717, 718, 719, 720, 722, 725, 726]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 34 / 42 (80.95%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/service/InformationSchemaDataSource.java|16|20|80.00%|[196, 311, 372, 393]|
|:large_blue_circle:|com/starrocks/catalog/MaterializedView.java|18|22|81.82%|[718, 719, 720, 722]|

**Review by nshangyiming — APPROVED** [review]

**Review by Astralidea — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by gengjun-git — APPROVED** [review]

**Pull request merged**
