### PR TITLE
[BugFix] backup empty database: error message is not clear (#13382)

### LINKED ISSUE #13382: backup empty datbase：error message is not clear
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
```
mysql> create database test_backup_529b928a_6429_11ed_a94d_00163e0e550b;
Query OK, 0 rows affected (0.00 sec)

mysql> use test_backup_529b928a_6429_11ed_a94d_00163e0e550b;
Database changed
mysql> CREATE REPOSITORY `backup_repository_52a4baea_6429_11ed_a94d_00163e0e550b` with broker `hdfs_broker` on location "hdfs://172.26.194.238:9000/user/starrocks_test_tmp/backup_repository_52a4baea_6429_11ed_a94d_00163e0e550b" properties ( "username"= "sr","password" = "");
Query OK, 0 rows affected (0.08 sec)

mysql> BACKUP SNAPSHOT test_backup_529b928a_6429_11ed_a94d_00163e0e550b.test_backup to backup_repository_52a4baea_6429_11ed_a94d_00163e0e550b PROPERTIES ('timeout' = '600');
```

### Expected behavior (Required)
error message is not clear
### Real behavior (Required)
ERROR 1064 (HY000): Index: 0, Size: 0
### StarRocks version (Required)
MAIN-RELEASE e21cd48

### PR DESCRIPTION
**Pull request by srlch**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #13382

## Problem Summary(Required) ：
Problem:
When backup a entire database, the statement will fail if db is empty. But the error msg is unclear.

Solution:
Add more error msg.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Review by chaoyli — APPROVED** [review]

**Review by decster — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by decster** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 6 / 8 (75.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/PrivilegeChecker.java|6|8|75.00%|[1224, 1228]|

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
