### PR TITLE
[Bugfix] Handle null scan ranges in OLAPScanNode in UT

### LINKED ISSUE #10024: [Bug] ConcurrentTxnNewPublishTest is flaky
### Real behavior (Required)
```
java.lang.NullPointerException: null
    at com.starrocks.pseudocluster.PseudoBackend.runOlapScan(PseudoBackend.java:896) ~[test-classes/:?]
    at com.starrocks.pseudocluster.PseudoBackend.execBatchPlanFragment(PseudoBackend.java:867) ~[test-classes/:?]
    at com.starrocks.pseudocluster.PseudoBackend.execBatchPlanFragmentsWithReport(PseudoBackend.java:891) ~[test-classes/:?]
    at com.starrocks.pseudocluster.PseudoBackend$PseudoPBackendService.lambda$execBatchPlanFragments$2(PseudoBackend.java:765) ~[test-classes/:?]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_322]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_322]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_322]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_322]
    at java.lang.Thread.run(Thread.java:750) [?:1.8.0_322]

```
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by decster**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #10024

## Problem Summary(Required) ：

Some OLAPScanNode do not have scan range, this PR adds code to handle this situation.
## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by decster** [comment]
run starrocks_fe_unittest

**Comment by decster** [comment]
run starrocks_fe_unittest

**Review by chaoyli — APPROVED** [review]

**Comment by decster** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 0 / 6 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/planner/OlapScanNode.java|0|6|00.00%|[315, 316, 317, 319, 320, 331]|

**Review by gengjun-git — APPROVED** [review]

**Review by Astralidea — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Pull request merged**
