### PR TITLE
[MaterializedView] Drop materialized view

### LINKED ISSUE #4792: [MaterializedView] add drop MaterializedView logic [P1]
## Feature request

**Is your feature request related to a problem? Please describe.**

to #3680

**Describe the solution you'd like**

add drop MaterializedView logic

### PR DESCRIPTION
**Pull request by ABingHuang**
## What type of PR is this：
- [ ] bug
- [x] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #4792 

## Problem Summary(Required) ：

support to drop materialized view logic

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 13 / 16 (81.25%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|13|16|81.25%|

**Review by murphyatwork — DISMISSED** [review]

**Review by imay — DISMISSED** [review]

**Review by kangkaisen — DISMISSED** [review]

**Comment by kangkaisen** [comment]
run all

**Comment by ABingHuang** [comment]
run starrocks_fe_unittest

**Review by HangyuanLiu — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 57 / 90 (63.33%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/Database.java|35|57|61.40%|
|:large_blue_circle:|com/starrocks/sql/analyzer/DropStmtAnalyzer.java|12|19|63.16%|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|10|14|71.43%|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 57 / 90 (63.33%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/Database.java|35|57|61.40%|
|:large_blue_circle:|com/starrocks/sql/analyzer/DropStmtAnalyzer.java|12|19|63.16%|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|10|14|71.43%|

**Pull request merged**
