### PR TITLE
[BugFix] Fix refresh bug for unpartitioned base table

### LINKED ISSUE #9830: [sync materialized view]refresh failed
### Steps to reproduce the behavior (Required)
```
CREATE TABLE t1
(a BIGINT,
b BIGINT,
c BIGINT,
d BIGINT,
e BIGINT,
f BIGINT)
DUPLICATE KEY(a)
DISTRIBUTED BY HASH(a) BUCKETS 10
PROPERTIES ("replication_num" = "1");
INSERT INTO t1 VALUES (1,1,1,1,1,1);
CREATE MATERIALIZED VIEW mv1
DISTRIBUTED BY HASH(a) BUCKETS 10
REFRESH ASYNC
AS SELECT a, b, c
FROM t1;
REFRESH MATERIALIZED VIEW mv1;
```
### Expected behavior (Required)
`refresh ok`
### Real behavior (Required)
```
2022-08-10 15:55:55,226 WARN (pool-21-thread-8|306) [TaskRunExecutor.lambda$executeTaskRun$0():42] failed to execute TaskRun.
java.lang.IllegalArgumentException: null
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:130) ~[spark-dpp-1.0.0.jar:?]
	at com.starrocks.catalog.OlapTable.getRangePartitionMap(OlapTable.java:663) ~[starrocks-fe.jar:?]
	at com.starrocks.scheduler.PartitionBasedMaterializedViewRefreshProcessor.checkBaseTablePartitionChange(PartitionBasedMaterializedViewRefreshProcessor.java:420) ~[starrocks-fe.jar:?]
	at com.starrocks.scheduler.PartitionBasedMaterializedViewRefreshProcessor.processTaskRun(PartitionBasedMaterializedViewRefreshProcessor.java:113) ~[starrocks-fe.jar:?]
	at com.starrocks.scheduler.TaskRun.executeTaskRun(TaskRun.java:106) ~[starrocks-fe.jar:?]
	at com.starrocks.scheduler.TaskRunExecutor.lambda$executeTaskRun$0(TaskRunExecutor.java:35) ~[starrocks-fe.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_252]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_252]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
```
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
+----------------------------+
| current_version()          |
+----------------------------+
| BRANCH-2.4-RELEASE bf34cec |
+----------------------------+
```

### PR DESCRIPTION
**Pull request by ABingHuang**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #9830 

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Review by Astralidea — APPROVED** [review]

**Comment by Astralidea** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 10 / 11 (90.91%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/scheduler/PartitionBasedMaterializedViewRefreshProcessor.java|10|11|90.91%|[424]|

**Review by kangkaisen — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by Astralidea** [comment]
run starrocks_admit_test

**Comment by Astralidea** [comment]
@Mergifyio backport branch-2.4

**Pull request merged**
