### PR TITLE
[Refactor] remove JsonValue from datum

### PR DESCRIPTION
**Pull request by murphyatwork**
## What type of PR is this：
- [ ] bug
- [ ] feature
- [ ] enhancement
- [x] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

`JsonValue` in `Datum` makes it a huge header, so remove it.

### CODE REVIEW

**Review by imay — DISMISSED** [review]

**Comment by mofeiatwork** [comment]
@Mergifyio rebase

**Comment by mofeiatwork** [comment]
run starrocks_be_unittest

**Comment by mofeiatwork** [comment]
run starrocks_be_unittest

**Comment by mofeiatwork** [comment]
@Mergifyio backport branch-2.3

**Comment by stdpain** [comment]
it seems get_if and move_in is also unused

**Comment by mofeiatwork** [comment]
> it seems get_if and move_in is also unused

done

**Review by kangkaisen — APPROVED** [review]

**Review by stdpain — APPROVED** [review]

**Pull request merged**
