### PR TITLE
[Enhancement] Refactored statistics expired logic and support Drop statistics statement

### PR DESCRIPTION
**Pull request by HangyuanLiu**
## What type of PR is this：
- [ ] bug
- [ ] feature
- [x] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

1. Added dropStats statement to support deleting basic statistics
2. Improve the function of drop histogram statistics, and delete meta and histogram analyze status at the same time
3. Add analyze status expiration function, records that exceed the time will no longer be retained
4. If the entity of the table is deleted, the corresponding statistics related information will also be deleted (meta, analyze status, data, cache stats)

### CODE REVIEW

**Comment by kangkaisen** [comment]
Need test cases

**Comment by HangyuanLiu** [comment]
> need more comments

1. Added dropStats statement to support deleting basic statistics
2. Improve the function of drop histogram statistics, and delete meta and histogram analyze status at the same time
3. Add analyze status expiration function, records that exceed the time will no longer be retained
4. If the entity of the table is deleted, the corresponding statistics related information will also be deleted (meta, analyze status, data, cache stats)

**Comment by wanpengfei-git** [comment]
run all

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 19 / 148 (12.84%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/ast/AstVisitor.java|0|1|00.00%|[422]|
|:large_blue_circle:|com/starrocks/statistic/StatisticExecutor.java|0|10|00.00%|[91, 92, 94, 97, 98, 99, 100, 101, 102, 103]|
|:large_blue_circle:|com/starrocks/statistic/StatisticsMetaManager.java|0|2|00.00%|[357, 358]|
|:large_blue_circle:|com/starrocks/sql/ast/DropHistogramStmt.java|0|1|00.00%|[40]|
|:large_blue_circle:|com/starrocks/persist/EditLog.java|0|15|00.00%|[838, 839, 840, 848, 849, 850, 858, 859, 860, 1482, 1483, 1490, 1491, 1498, 1499]|
|:large_blue_circle:|com/starrocks/journal/JournalEntity.java|0|9|00.00%|[620, 621, 622, 630, 631, 632, 640, 641, 642]|
|:large_blue_circle:|com/starrocks/statistic/AnalyzeManager.java|2|77|02.60%|[109, 110, 117, 118, 119, 120, 121, 123, 124, 125, 126, 127, 128, 131, 132, 133, 134, 136, 137, 138, 139, 140, 141, 153, 154, 161, 162, 163, 164, 167, 168, 169, 172, 173, 180, 181, 182, 183, 184, 185, 188, 189, 191, 192, 193, 194, 195, 198, 199, 200, 201, 202, 204, 205, 206, 207, 208, 211, 212, 213, 214, 215, 217, 220, 222, 223, 224, 226, 227, 228, 229, 230, 231, 232, 233]|
|:large_blue_circle:|com/starrocks/qe/StmtExecutor.java|1|15|06.67%|[472, 825, 826, 827, 828, 830, 831, 832, 833, 838, 839, 841, 842, 843]|
|:large_blue_circle:|com/starrocks/sql/ast/DropStatsStmt.java|5|7|71.43%|[27, 32]|
|:large_blue_circle:|com/starrocks/sql/analyzer/Analyzer.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/statistic/StatisticSQLBuilder.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AnalyzeStmtAnalyzer.java|2|2|100.00%|[]|

**Review by Youngwb — APPROVED** [review]

**Review by Seaven — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by HangyuanLiu** [comment]
run starrocks_admit_test

**Pull request merged**
