### PR TITLE
[Feature] get_json_object with char args

### PR DESCRIPTION
**Pull request by xuzifu666**
## What type of PR is this：
- [ ] BugFix
- [x] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Review by dirtysalt — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by dirtysalt — APPROVED** [review]

**Comment by xuzifu666** [comment]
77a7335bf960f8f0824aee0ed9ff53d
error message like the picture

**Comment by mofeiatwork** [comment]
run starrocks_clang-format

**Review by murphyatwork — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by xuzifu666** [comment]
run starrocks_admit_test

**Comment by xuzifu666** [comment]
run starrocks_clang-format

**Comment by xuzifu666** [comment]
run starrocks_admit_test

**Comment by xuzifu666** [comment]
run starrocks_clang-tidy

**Pull request merged**
