### PR TITLE
[Refactor] [1/N] Refactor orc chunk reader

### PR DESCRIPTION
**Pull request by DorianZheng**
Signed-off-by: dorianzheng <xingzhengde72@gmail.com>

## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [x] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

since the file `orc_chunk_reader.cpp` is too bloated, I will file some PR to refactor it. this is the first PR which move fill functions and util functions out of the file.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Review by Smith-Cruise — APPROVED** [review]

**Review by dirtysalt — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by DorianZheng** [comment]
run starrocks_admit_test

**Comment by DorianZheng** [comment]
run starrocks_be_unittest

**Review by Youngwb — APPROVED** [review]

**Comment by DorianZheng** [comment]
run starrocks_admit_test

**Pull request merged**
