### PR TITLE
[BugFix] Fix refresh mv error with multi external partitioned table

### LINKED ISSUE #18390: Refresh mv error with multi partitioned external table
### Steps to reproduce the behavior (Required)
1. hive table :
image
image

2. CREATE mv
```
create materialized view ex_join_mv_6
partition by emp_date
distributed by hash(empid)
REFRESH MANUAL
PROPERTIES (
"replication_num" = "1",
"storage_medium" = "HDD"
) 
as
select emps_par.empid, depts_par.deptno, depts_par.name, emps_par.emp_date from `hive_catalog`.`ywb`.emps_par join `hive_catalog`.`ywb`.depts_par using (deptno)
```

3. refresh mv
```
refresh materialized view ex_join_mv_6
```

### Expected behavior (Required)
refresh successfully

### Real behavior (Required)
image

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by Youngwb**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #18390 

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 3.0
  - [x] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Comment by Youngwb** [comment]
run all

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 2 / 3 (66.67%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/scheduler/PartitionBasedMaterializedViewRefreshProcessor.java|2|3|66.67%|[742]|

**Review by Astralidea — APPROVED** [review]

**Review by ABingHuang — APPROVED** [review]
LGTM

**Comment by Youngwb** [comment]
run starrocks_admit_test

**Comment by Youngwb** [comment]
run starrocks_admit_test

**Comment by Youngwb** [comment]
run starrocks_admit_test

**Comment by Youngwb** [comment]
run starrocks_clang-format

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
