### PR TITLE
[BugFix] Support storage_cooldown_ttl = ""

### LINKED ISSUE #29841: [storage_cooldown_ttl] storage_cooldown_ttl = "" error
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
```
 CREATE TABLE `cooldown_ttl_month1_table_with_null`
        ( `k1`  date, `k2`  datetime,`k3`  string, `k4`  varchar(20), `k5`  boolean, `k6`  tinyint, `k7`  smallint, `k8`  int, `k9`  bigint, `k10` largeint, `k11` float, `k12` double, `k13` decimal(27,9))
        unique KEY(`k1`, `k2`, `k3`, `k4`, `k5`)
        PARTITION BY time_slice(k2, interval 1 month)
        DISTRIBUTED BY HASH(`k1`, `k2`, `k3`)
        PROPERTIES ("storage_medium" = "SSD", "storage_cooldown_ttl" = "");
```

### Expected behavior (Required)
execute successfully
### Real behavior (Required)
execute failed
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
mysql> select current_version();
+--------------------+
| current_version()  |
+--------------------+
| branch-3.1-2f9251d |
+--------------------+
1 row in set (0.03 sec)

### PR DESCRIPTION
**Pull request by Astralidea**
Fixes #29841

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [x] 3.0
  - [ ] 2.5
  - [ ] 2.4

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 18 / 19 (94.74%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/TableProperty.java|3|4|75.00%|[515]|
|:large_blue_circle:|com/starrocks/alter/AlterJobMgr.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/SinglePartitionDesc.java|11|11|100.00%|[]|
|:large_blue_circle:|com/starrocks/common/util/PropertyAnalyzer.java|2|2|100.00%|[]|

**Review by ABingHuang — APPROVED** [review]

**Review by gengjun-git — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Pull request merged**
