### PR TITLE
[BugFix] fix CompoundPredicateOperator equals method

### PR DESCRIPTION
**Pull request by packy92**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

In memo phase, we use join transform rules to generate more plans. These rules split conjuncts and generate new predicate which may change the order of nodes in compoundPredicate. For a predicate like `v1 = v2 and v3 = v4 and v5 = v6`, the order of these three eqaul predicates doesn't affect the meaning of the compoundPredicate. For exampe, `v3 = v4 and v5 = v6 and v1 = v2` should equal `v1 = v2 and v3 = v4 and v5 = v6`. 

This pr helps to prevent  groupExpression acctually with the same meaning from being repeatedly inserted into the memo.
BTW, a test had been disabled and this pr restored it.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

### CODE REVIEW

**Comment by packy92** [comment]
run starrocks_admit_test

**Comment by packy92** [comment]
run starrocks_fe_unittest

**Review by murphyatwork — DISMISSED** [review]

**Comment by packy92** [comment]
run starrocks_fe_unittest

**Comment by packy92** [comment]
run starrocks_fe_unittest

**Comment by packy92** [comment]
run starrocks_fe_unittest

**Comment by packy92** [comment]
run starrocks_admit_test

**Comment by packy92** [comment]
run starrocks_fe_unittest

**Comment by packy92** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 9 / 12 (75.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/GroupExpression.java|0|3|00.00%|[311, 312, 313]|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/scalar/CompoundPredicateOperator.java|9|9|100.00%|[]|

**Comment by packy92** [comment]
run starrocks_admit_test

**Comment by packy92** [comment]
run starrocks_admit_test

**Comment by packy92** [comment]
run starrocks_admit_test

**Comment by packy92** [comment]
run pr-title-check

**Comment by packy92** [comment]
run starrocks_admit_test

**Review by murphyatwork — APPROVED** [review]

**Review by kangkaisen — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Pull request merged**
