### PR TITLE
[cherry-pick]Support multi-character row delimiter during load (#3900)

### PR DESCRIPTION
**Pull request by Astralidea**
The pull request supports multi-character row delimiter. After that, the ```<br>``` can be used as a row delimiter.

## What type of PR is this：
- [ ] bug
- [x] feature
- [ ] enhancement
- [ ] others

## Which issues of this PR fixes ：

Fixes #

### CODE REVIEW

**Comment by wangruin** [comment]
run all

**Comment by Astralidea** [comment]
run all

**Comment by Astralidea** [comment]
run starrocks_be_unittest

**Comment by Astralidea** [comment]
run starrocks_fe_unittest

**Comment by Astralidea** [comment]
run starrocks_fe_unittest

**Comment by wangruin** [comment]
run starrocks_be_unittest

**Comment by wangruin** [comment]
run starrocks_be_unittest

**Comment by Astralidea** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 0 / 10 (00.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/planner/StreamLoadScanNode.java|0|7|00.00%|
|:large_blue_circle:|com/starrocks/planner/FileScanNode.java|0|3|00.00%|

**Pull request merged**
