### PR TITLE
[BugFix] Fix FSIO stats lost in hdfs_scanner_text

### PR DESCRIPTION
**Pull request by Smith-Cruise**
Fixes #issue

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.2
  - [x] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 32 / 50 (64.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/exec/hdfs_scanner.h|0|2|00.00%|[287, 288]|
|:large_blue_circle:|src/exec/jni_scanner.cpp|0|7|00.00%|[40, 52, 143, 144, 145, 428, 434]|
|:large_blue_circle:|src/exec/hdfs_scanner.cpp|7|13|53.85%|[154, 297, 298, 299, 300, 301]|
|:large_blue_circle:|src/exec/hdfs_scanner_text.cpp|2|3|66.67%|[219]|
|:large_blue_circle:|src/exec/hdfs_scanner_orc.cpp|7|9|77.78%|[305, 546]|
|:large_blue_circle:|src/exec/hdfs_scanner_parquet.cpp|16|16|100.00%|[]|

**Review by letian-jiang — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 48 / 67 (71.64%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/exec/hdfs_scanner.h|0|5|00.00%|[287, 288, 289, 290, 291]|
|:large_blue_circle:|src/exec/jni_scanner.cpp|0|7|00.00%|[40, 52, 143, 144, 145, 428, 434]|
|:large_blue_circle:|src/exec/hdfs_scanner_orc.cpp|9|15|60.00%|[519, 526, 545, 546, 553, 556]|
|:large_blue_circle:|src/exec/hdfs_scanner_text.cpp|2|3|66.67%|[219]|
|:large_blue_circle:|src/exec/hdfs_scanner_parquet.cpp|17|17|100.00%|[]|
|:large_blue_circle:|src/exec/hdfs_scanner.cpp|20|20|100.00%|[]|

**Review by dirtysalt — APPROVED** [review]

**Review by Youngwb — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.2

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Pull request merged**
