### PR TITLE
[Enhancement] Use shuffle bucket join to reduce data shuffle

### LINKED ISSUE #9790: More cases are supported to generate shuffle bucket join
## Enhancement
For sql like 
```
select a.v1, a.v4 from (select v1, v2, v4 from t0 join[shuffle] t1 on t0.v1 = t1.v4) a join[shuffle]  
(select v7,v8, v10 from t2 join[shuffle] t3 on t2.v7 = t3.v10) b on a.v1 = b.v7 and a.v2 = b.v8
```
StarRocks use plan now:
```
PLAN FRAGMENT 0
 OUTPUT EXPRS:1: v1 | 4: v4
  PARTITION: UNPARTITIONED

  RESULT SINK

  15:EXCHANGE

PLAN FRAGMENT 1
 OUTPUT EXPRS:
  PARTITION: HASH_PARTITIONED: 1: v1, 2: v2

  STREAM DATA SINK
    EXCHANGE ID: 15
    UNPARTITIONED

  14:Project
  |  <slot 1> : 1: v1
  |  <slot 4> : 4: v4
  |  
  13:HASH JOIN
  |  join op: INNER JOIN (PARTITIONED)
  |  colocate: false, reason: 
  |  equal join conjunct: 1: v1 = 7: v7
  |  equal join conjunct: 2: v2 = 8: v8
  |  
  |----12:EXCHANGE
  |    
  5:EXCHANGE

PLAN FRAGMENT 2
 OUTPUT EXPRS:
  PARTITION: HASH_PARTITIONED: 7: v7

  STREAM DATA SINK
    EXCHANGE ID: 12
    HASH_PARTITIONED: 7: v7, 8: v8

  11:Project
  |  <slot 7> : 7: v7
  |  <slot 8> : 8: v8
  |  
  10:HASH JOIN
  |  join op: INNER JOIN (PARTITIONED)
  |  colocate: false, reason: 
  |  equal join conjunct: 7: v7 = 10: v10
  |  
  |----9:EXCHANGE
  |    
  7:EXCHANGE

PLAN FRAGMENT 3
 OUTPUT EXPRS:
  PARTITION: RANDOM

  STREAM DATA SINK
    EXCHANGE ID: 09
    HASH_PARTITIONED: 10: v10

  8:OlapScanNode
     TABLE: t3
     PREAGGREGATION: ON
     PREDICATES: 10: v10 IS NOT NULL
     partitions=1/1
     rollup: t3
     tabletRatio=3/3
     tabletList=10033,10035,10037
     cardinality=1
     avgRowSize=1.0
     numNodes=0

PLAN FRAGMENT 4
 OUTPUT EXPRS:
  PARTITION: RANDOM

  STREAM DATA SINK
    EXCHANGE ID: 07
    HASH_PARTITIONED: 7: v7

  6:OlapScanNode
     TABLE: t2
     PREAGGREGATION: ON
     PREDICATES: 7: v7 IS NOT NULL, 8: v8 IS NOT NULL
     partitions=1/1
     rollup: t2
     tabletRatio=3/3
     tabletList=10024,10026,10028
     cardinality=1
     avgRowSize=2.0
     numNodes=0

PLAN FRAGMENT 5
 OUTPUT EXPRS:
  PARTITION: HASH_PARTITIONED: 1: v1

  STREAM DATA SINK
    EXCHANGE ID: 05
    HASH_PARTITIONED: 1: v1, 2: v2

  4:HASH JOIN
  |  join op: INNER JOIN (PARTITIONED)
  |  colocate: false, reason: 
  |  equal join conjunct: 1: v1 = 4: v4
  |  
  |----3:EXCHANGE
  |    
  1:EXCHANGE

PLAN FRAGMENT 6
 OUTPUT EXPRS:
  PARTITION: RANDOM

  STREAM DATA SINK
    EXCHANGE ID: 03
    HASH_PARTITIONED: 4: v4

  2:OlapScanNode
     TABLE: t1
     PREAGGREGATION: ON
     PREDICATES: 4: v4 IS NOT NULL
     partitions=1/1
     rollup: t1
     tabletRatio=3/3
     tabletList=10015,10017,10019
     cardinality=1
     avgRowSize=1.0
     numNodes=0

PLAN FRAGMENT 7
 OUTPUT EXPRS:
  PARTITION: RANDOM

  STREAM DATA SINK
    EXCHANGE ID: 01
    HASH_PARTITIONED: 1: v1

  0:OlapScanNode
     TABLE: t0
     PREAGGREGATION: ON
     PREDICATES: 1: v1 IS NOT NULL, 2: v2 IS NOT NULL
     partitions=1/1
     rollup: t0
     tabletRatio=3/3
     tabletList=10006,10008,10010
     cardinality=1
     avgRowSize=2.0
     numNodes=0
```
In this plan, top join need hash by(v1,v2 or v7,v8) two columns, but the bottom joins, one is hash by v1 or v4 one column,  the other one needs to hash by v7 or v10 one column, which can not satisfy the requirements (v1,v2 or v7,v8) from top join, but hash by only one column is enough for top join, we can generate better plan like this :
```
PLAN FRAGMENT 0
 OUTPUT EXPRS:1: v1 | 4: v4
  PARTITION: UNPARTITIONED

  RESULT SINK

  13:EXCHANGE

PLAN FRAGMENT 1
 OUTPUT EXPRS:
  PARTITION: HASH_PARTITIONED: 1: v1

  STREAM DATA SINK
    EXCHANGE ID: 13
    UNPARTITIONED

  12:Project
  |  <slot 1> : 1: v1
  |  <slot 4> : 4: v4
  |  
  11:HASH JOIN
  |  join op: INNER JOIN (BUCKET_SHUFFLE(S))
  |  colocate: false, reason: 
  |  equal join conjunct: 1: v1 = 7: v7
  |  equal join conjunct: 2: v2 = 8: v8
  |  
  |----10:Project
  |    |  <slot 7> : 7: v7
  |    |  <slot 8> : 8: v8
  |    |  
  |    9:HASH JOIN
  |    |  join op: INNER JOIN (PARTITIONED)
  |    |  colocate: false, reason: 
  |    |  equal join conjunct: 7: v7 = 10: v10
  |    |  
  |    |----8:EXCHANGE
  |    |    
  |    6:EXCHANGE
  |    
  4:HASH JOIN
  |  join op: INNER JOIN (PARTITIONED)
  |  colocate: false, reason: 
  |  equal join conjunct: 1: v1 = 4: v4
  |  
  |----3:EXCHANGE
  |    
  1:EXCHANGE

PLAN FRAGMENT 2
 OUTPUT EXPRS:
  PARTITION: RANDOM

  STREAM DATA SINK
    EXCHANGE ID: 08
    HASH_PARTITIONED: 10: v10

  7:OlapScanNode
     TABLE: t3
     PREAGGREGATION: ON
     PREDICATES: 10: v10 IS NOT NULL
     partitions=1/1
     rollup: t3
     tabletRatio=3/3
     tabletList=10033,10035,10037
     cardinality=1
     avgRowSize=1.0
     numNodes=0

PLAN FRAGMENT 3
 OUTPUT EXPRS:
  PARTITION: RANDOM

  STREAM DATA SINK
    EXCHANGE ID: 06
    HASH_PARTITIONED: 7: v7

  5:OlapScanNode
     TABLE: t2
     PREAGGREGATION: ON
     PREDICATES: 7: v7 IS NOT NULL, 8: v8 IS NOT NULL
     partitions=1/1
     rollup: t2
     tabletRatio=3/3
     tabletList=10024,10026,10028
     cardinality=1
     avgRowSize=2.0
     numNodes=0

PLAN FRAGMENT 4
 OUTPUT EXPRS:
  PARTITION: RANDOM

  STREAM DATA SINK
    EXCHANGE ID: 03
    HASH_PARTITIONED: 4: v4

  2:OlapScanNode
     TABLE: t1
     PREAGGREGATION: ON
     PREDICATES: 4: v4 IS NOT NULL
     partitions=1/1
     rollup: t1
     tabletRatio=3/3
     tabletList=10015,10017,10019
     cardinality=1
     avgRowSize=1.0
     numNodes=0

PLAN FRAGMENT 5
 OUTPUT EXPRS:
  PARTITION: RANDOM

  STREAM DATA SINK
    EXCHANGE ID: 01
    HASH_PARTITIONED: 1: v1

  0:OlapScanNode
     TABLE: t0
     PREAGGREGATION: ON
     PREDICATES: 1: v1 IS NOT NULL, 2: v2 IS NOT NULL
     partitions=1/1
     rollup: t0
     tabletRatio=3/3
     tabletList=10006,10008,10010
     cardinality=1
     avgRowSize=2.0
     numNodes=0

```

### PR DESCRIPTION
**Pull request by Youngwb**
## What type of PR is this：
- [ ] bug
- [ ] feature
- [x] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #9790 

## Problem Summary(Required) ：

Main change:
1.  Satisty requirement for SHFFLE_JOIN property, hash by column A can satisfy hash by A,B columns
2. check plan is legal for shuffle join in ChildOutputPropertyGuarantor. if not, add or modify the enforcer to be legal
## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 52 / 57 (91.23%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/ChildOutputPropertyGuarantor.java|51|56|91.07%|[146, 147, 148, 149, 150]|
|:large_blue_circle:|com/starrocks/sql/optimizer/base/HashDistributionDesc.java|1|1|100.00%|[]|

**Comment by Youngwb** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 50 / 55 (90.91%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/ChildOutputPropertyGuarantor.java|49|54|90.74%|[146, 147, 148, 149, 150]|
|:large_blue_circle:|com/starrocks/sql/optimizer/base/HashDistributionDesc.java|1|1|100.00%|[]|

**Comment by Youngwb** [comment]
run starrocks_admit_test

**Review by liuyehcf — APPROVED** [review]

**Review by kangkaisen — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Pull request merged**
