### PR TITLE
[cherry-pick] Get hive column statistics downgrade policy (#4409)

### PR DESCRIPTION
**Pull request by stephen-shelby**
## What type of PR is this：
- [ ] bug
- [x] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #
https://github.com/StarRocks/starrocks/pull/4409

### CODE REVIEW

**Review by DorianZheng — APPROVED** [review]
LGTM

**Review by gengjun-git — APPROVED** [review]

**Review by caneGuy — APPROVED** [review]

**Comment by stephen-shelby** [comment]
run starrocks_fe_unittest

**Comment by stephen-shelby** [comment]
run starrocks_fe_unittest

**Comment by stephen-shelby** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 0 / 23 (00.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/external/hive/HiveMetaClient.java|0|23|00.00%|

**Comment by stephen-shelby** [comment]
@Mergifyio backport branch-2.3

**Pull request merged**
