### PR TITLE
[BugFix][cherry-pick] Fix the thrift library conflict in some cases by linking the required cachelib dependencies statically

### PR DESCRIPTION
**Pull request by GavinMar**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

When linking the cachelib dynamically by find_package, all related libraries will be linked. While some of them are not required in our usage scenarios, and even lead to dependency conflicts in some environments.

So, we choose to only link the required cachelib dependencies statically to avoid unnecessary conflicts. Also, with this change, it is no need to package lots of dynamic libraries in our be output.

(cherry-pick from #16674)

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Comment by GavinMar** [comment]
run starrocks_be_unittest

**Comment by GavinMar** [comment]
run starrocks_be_unittest

**Comment by GavinMar** [comment]
run starrocks_admit_test

**Comment by GavinMar** [comment]
run starrocks_admit_test image

**Review by dirtysalt — APPROVED** [review]

**Pull request merged**
