### PR TITLE
[Feature] Support mv refresh by partition for hive table

### PR DESCRIPTION
**Pull request by Youngwb**
Signed-off-by: Youngwb <yangwenbo_mailbox@163.com>

## What type of PR is this：
- [ ] BugFix
- [x] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

#11116 
Mv refreshes partitions which data changes in the base table

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 3.0
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Comment by Youngwb** [comment]
run all

**Comment by Youngwb** [comment]
run all

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 192 / 246 (78.05%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/connector/hive/HiveMetadata.java|0|8|00.00%|[135, 136, 137, 138, 140, 141, 142, 143]|
|:large_blue_circle:|com/starrocks/connector/hive/HiveMetastoreOperations.java|0|3|00.00%|[77, 78, 79]|
|:large_blue_circle:|com/starrocks/connector/ConnectorMetadata.java|0|1|00.00%|[101]|
|:large_blue_circle:|com/starrocks/catalog/BaseTableInfo.java|1|11|09.09%|[154, 155, 157, 158, 160, 161, 162, 163, 164, 165]|
|:large_blue_circle:|com/starrocks/server/MetadataMgr.java|6|9|66.67%|[190, 191, 192]|
|:large_blue_circle:|com/starrocks/connector/PartitionUtil.java|36|50|72.00%|[197, 199, 203, 204, 205, 216, 269, 270, 352, 353, 354, 355, 356, 358]|
|:large_blue_circle:|com/starrocks/catalog/MaterializedView.java|56|68|82.35%|[447, 448, 483, 484, 485, 725, 726, 733, 734, 741, 742, 906]|
|:large_blue_circle:|com/starrocks/scheduler/PartitionBasedMaterializedViewRefreshProcessor.java|90|93|96.77%|[497, 576, 830]|
|:large_blue_circle:|com/starrocks/analysis/Expr.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/connector/hive/Partition.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 191 / 246 (77.64%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/connector/hive/HiveMetadata.java|0|8|00.00%|[138, 139, 140, 141, 143, 144, 145, 146]|
|:large_blue_circle:|com/starrocks/connector/hive/HiveMetastoreOperations.java|0|3|00.00%|[77, 78, 79]|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|0|1|00.00%|[903]|
|:large_blue_circle:|com/starrocks/connector/ConnectorMetadata.java|0|1|00.00%|[111]|
|:large_blue_circle:|com/starrocks/catalog/BaseTableInfo.java|1|11|09.09%|[154, 155, 157, 158, 160, 161, 162, 163, 164, 165]|
|:large_blue_circle:|com/starrocks/server/MetadataMgr.java|6|9|66.67%|[198, 199, 200]|
|:large_blue_circle:|com/starrocks/connector/PartitionUtil.java|36|50|72.00%|[200, 202, 206, 207, 208, 219, 272, 273, 375, 376, 377, 378, 379, 381]|
|:large_blue_circle:|com/starrocks/catalog/MaterializedView.java|56|68|82.35%|[447, 448, 483, 484, 485, 725, 726, 733, 734, 741, 742, 906]|
|:large_blue_circle:|com/starrocks/scheduler/PartitionBasedMaterializedViewRefreshProcessor.java|90|93|96.77%|[497, 576, 830]|
|:large_blue_circle:|com/starrocks/analysis/Expr.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/connector/hive/Partition.java|1|1|100.00%|[]|

**Review by Astralidea — APPROVED** [review]

**Review by gengjun-git — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by Youngwb** [comment]
@Mergifyio backport branch-2.5

**Comment by Youngwb** [comment]
@Mergifyio backport branch-3.0

**Pull request merged**
