### PR TITLE
[Enhancement] remove some useless operatitons when start as cn

### PR DESCRIPTION
**Pull request by abc982627271**
Fixes #issue

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.2
  - [x] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 8 / 13 (61.54%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/agent/heartbeat_server.cpp|0|1|00.00%|[221]|
|:large_blue_circle:|src/storage/storage_engine.h|0|1|00.00%|[268]|
|:large_blue_circle:|src/service/service_be/starrocks_be.cpp|0|1|00.00%|[100]|
|:large_blue_circle:|src/storage/storage_engine.cpp|5|7|71.43%|[261, 448]|
|:large_blue_circle:|src/storage/data_dir.cpp|3|3|100.00%|[]|

**Review by kevincai — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 8 / 13 (61.54%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/agent/heartbeat_server.cpp|0|1|00.00%|[221]|
|:large_blue_circle:|src/storage/storage_engine.h|0|1|00.00%|[268]|
|:large_blue_circle:|src/service/service_be/starrocks_be.cpp|0|1|00.00%|[100]|
|:large_blue_circle:|src/storage/storage_engine.cpp|5|7|71.43%|[261, 448]|
|:large_blue_circle:|src/storage/data_dir.cpp|3|3|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 8 / 13 (61.54%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/agent/heartbeat_server.cpp|0|1|00.00%|[221]|
|:large_blue_circle:|src/storage/storage_engine.h|0|1|00.00%|[268]|
|:large_blue_circle:|src/service/service_be/starrocks_be.cpp|0|1|00.00%|[100]|
|:large_blue_circle:|src/storage/storage_engine.cpp|5|7|71.43%|[261, 448]|
|:large_blue_circle:|src/storage/data_dir.cpp|3|3|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 8 / 14 (57.14%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/agent/heartbeat_server.cpp|0|1|00.00%|[221]|
|:large_blue_circle:|src/storage/storage_engine.h|0|1|00.00%|[268]|
|:large_blue_circle:|src/service/service_be/starrocks_be.cpp|0|1|00.00%|[100]|
|:large_blue_circle:|src/storage/storage_engine.cpp|5|8|62.50%|[261, 262, 264]|
|:large_blue_circle:|src/storage/data_dir.cpp|3|3|100.00%|[]|

**Review by kevincai — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:heart_eyes: **pass** : 13 / 16 (81.25%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/agent/heartbeat_server.cpp|0|1|00.00%|[221]|
|:large_blue_circle:|src/storage/storage_engine.h|0|1|00.00%|[268]|
|:large_blue_circle:|src/service/service_be/starrocks_be.cpp|0|1|00.00%|[100]|
|:large_blue_circle:|src/storage/storage_engine.cpp|10|10|100.00%|[]|
|:large_blue_circle:|src/storage/data_dir.cpp|3|3|100.00%|[]|

**Review by wyb — APPROVED** [review]

**Review by sduzh — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.2

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Pull request merged**
