### PR TITLE
[Enhancement] Support S3A-compliant connection maximum configuration

### LINKED ISSUE #31215: [Paimon Catalog] Query from external table stored on s3
### Steps to reproduce the behavior (Required)
It works find on small table, but it will raise error sometimes when querying data from big table.
Besides, I wonder if it is necessary to add `fs.s3a.connection.maximum` in catalog option on which paimon deals with this case or maybe there is another way to avoid this error?

### Expected behavior (Required)
Return normally

### Real behavior (Required)
```
StarRocks > select * from my_table limit 1;
-- CASE 1
ERROR 1064 (HY000): Failed to open the off-heap table scanner. java exception details: java.io.IOException: Failed to open the paimon reader.
        at com.starrocks.paimon.reader.PaimonSplitScanner.open(PaimonSplitScanner.java:173)
Caused by: java.io.InterruptedIOException: getFileStatus on s3://paimon/dev/default.db/my_table/bucket-28/data-dc4bf88e-1610-45d2-b414-a1d0ea1a9d43-12.orc: com.amazonaws.SdkClientException: Unable to execute HTTP request: Timeout waiting for connection from pool
        at org.apache.hadoop.fs.s3a

-- CASE 2
-- it will return normally
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 in the latest main branch

### PR DESCRIPTION
**Pull request by 0akarma**
Fixes #31215

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [x] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [ ] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Comment by 0akarma** [comment]
Hi, @miomiocat
After trying to add `options.setString("fs.s3a.connection.maximum", "1000");` in `PaimonSplitScanner.java:initTable()` to push down configuration for paimon api, it does not come out the time out error.

 So I tryied to make an PR to enhance this behavior, please help me review it at your time

**Comment by miomiocat** [comment]
> Hi, @miomiocat After trying to add `options.setString("fs.s3a.connection.maximum", "1000");` in `PaimonSplitScanner.java:initTable()` to push down configuration for paimon api, it does not come out the time out error.
> 
> So I tryied to make an PR to enhance this behavior, please help me review it at your time

thanks for your contribution.

I think we need a general parameter passing method to solve similar problems after I reviewed the current implementation of `paimon catalog in starrocks` and `paimon project`.

The initial idea is to remove the s3 related code of `PaimonConnector` and allow all catalog configurations starting with `paimon.option.` can be set in `paimonOptions`.

This way, we don't have to think about the configuration of a specific file system like s3

**Comment by 0akarma** [comment]
> > Hi, @miomiocat After trying to add `options.setString("fs.s3a.connection.maximum", "1000");` in `PaimonSplitScanner.java:initTable()` to push down configuration for paimon api, it does not come out the time out error.
> > So I tryied to make an PR to enhance this behavior, please help me review it at your time
> 
> thanks for your contribution.
> 
> I think we need a general parameter passing method to solve similar problems after I reviewed the current implementation of `paimon catalog in starrocks` and `paimon project`.
> 
> The initial idea is to remove the s3 related code of `PaimonConnector` and allow all catalog configurations starting with `paimon.option.` can be set in `paimonOptions`.
> 
> This way, we don't have to think about the configuration of a specific file system like s3

I agreed. I think it is better to follow `paimon api` usages, which will not confuse users about the differences of options between starrocks and paimon.
Besides, I will have a try on adding `paimon.option` properties to set `paimonOptions`, and make some tests to make it worked.

**Comment by miomiocat** [comment]
related PR: https://github.com/StarRocks/starrocks/pull/34996

**Pull request closed without merging**
