### PR TITLE
[Bugfix] Fix bug create MV with explain query

### LINKED ISSUE #10347: Bad `CREATE MATERIALIZED VIEW` will cause FE down
### Steps to reproduce the behavior (Required)
```
mysql> create table customer (c_name varchar(100), c_phone int(18)) DUPLICATE KEY(c_name) DISTRIBUTED BY HASH(c_name) BUCKETs 4 PROPERTIES("replication_num" = "1");
Query OK, 0 rows affected (0.02 sec)

mysql> CREATE MATERIALIZED VIEW mv_customer_sumc_phone AS
    -> EXPLAIN SELECT c_name, MAX(c_phone)
    -> FROM customer
    -> GROUP BY c_name;
Query OK, 0 rows affected (0.06 sec)
```

### Expected behavior (Required)
Execute failed with error messages.

### Real behavior (Required)
It seems to execute well, but later all FE are down when replaying the journal.

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
2.3.0

### PR DESCRIPTION
**Pull request by Astralidea**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #10347

## Problem Summary(Required) ：

we should not support create explain query for materialized view 

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 7 / 8 (87.50%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|3|4|75.00%|[1188]|
|:large_blue_circle:|com/starrocks/sql/common/MetaUtils.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/parser/SqlParser.java|3|3|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 8 / 8 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/common/MetaUtils.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/parser/SqlParser.java|3|3|100.00%|[]|

**Review by kangkaisen — APPROVED** [review]

**Review by gengjun-git — APPROVED** [review]

**Review by HangyuanLiu — COMMENTED** [review]
Why does illegal sql appear in replay, shouldn't it be banned when creating mv?

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by HangyuanLiu — CHANGES_REQUESTED** [review]
Why does illegal sql appear in replay, shouldn't it be banned when creating mv?

**Pull request closed without merging**
