### PR TITLE
[BugFix] Make the first parameter of date_trunc case-insensitive

### LINKED ISSUE #17424: Creating a materialized view of rollup partition causes FE crash
### Steps to reproduce the behavior (Required)
1. CREATE TABLE orders ( 
    dt date NOT NULL, 
    order_id bigint NOT NULL, 
    user_id int NOT NULL, 
    merchant_id int NOT NULL, 
    good_id int NOT NULL, 
    good_name string NOT NULL, 
    price int NOT NULL, 
    cnt int NOT NULL, 
    revenue int NOT NULL, 
    state tinyint NOT NULL 
) 
PRIMARY KEY (dt, order_id) 
PARTITION BY RANGE(`dt`) 
(
PARTITION p20210820 VALUES [('2021-08-20'), ('2021-08-21')), 
PARTITION p20210821 VALUES [('2021-08-21'), ('2021-08-22'))
) 
DISTRIBUTED BY HASH(order_id) BUCKETS 4
PROPERTIES (
    "replication_num" = "1", 
    "enable_persistent_index" = "true"
);
2. CREATE MATERIALIZED VIEW order_mv2
PARTITION BY date_trunc('MONTH', `dt`)
DISTRIBUTED BY HASH(`order_id`) BUCKETS 10
REFRESH ASYNC START('2023-07-01 10:00:00') EVERY (interval 1 day)
AS
select
    dt,
    order_id,
    user_id,
    sum(cnt) as total_cnt,
    sum(revenue) as total_revenue, 
    count(state) as state_count
from orders
group by dt, order_id, user_id;

### Expected behavior (Required)
Create Success.
### Real behavior (Required)
com.starrocks.journal.JournalInconsistentException: failed to load journal type 10094
        at com.starrocks.persist.EditLog.loadJournal(EditLog.java:1011) ~[classes/:?]
        at com.starrocks.server.GlobalStateMgr.replayJournalInner(GlobalStateMgr.java:1938) [classes/:?]
        at com.starrocks.server.GlobalStateMgr.replayJournal(GlobalStateMgr.java:1889) [classes/:?]
        at com.starrocks.leader.Checkpoint.replayAndGenerateGlobalStateMgrImage(Checkpoint.java:215) [classes/:?]
        at com.starrocks.leader.Checkpoint.runAfterCatalogReady(Checkpoint.java:106) [classes/:?]
        at com.starrocks.common.util.LeaderDaemon.runOneCycle(LeaderDaemon.java:73) [classes/:?]
        at com.starrocks.common.util.Daemon.run(Daemon.java:115) [classes/:?]
Caused by: com.starrocks.sql.analyzer.SemanticException: date_trunc function can't support argument other than year|quarter|month|week|day
        at com.starrocks.sql.analyzer.FunctionAnalyzer.analyze(FunctionAnalyzer.java:60) ~[classes/:?]
        at com.starrocks.sql.analyzer.ExpressionAnalyzer$Visitor.visitFunctionCall(ExpressionAnalyzer.java:897) ~[classes/:?]
        at com.starrocks.sql.analyzer.ExpressionAnalyzer$Visitor.visitFunctionCall(ExpressionAnalyzer.java:214) ~[classes/:?]
        at com.starrocks.analysis.FunctionCallExpr.accept(FunctionCallExpr.java:454) ~[classes/:?]
        at com.starrocks.sql.ast.AstVisitor.visit(AstVisitor.java:55) ~[classes/:?]
        at com.starrocks.sql.analyzer.ExpressionAnalyzer.bottomUpAnalyze(ExpressionAnalyzer.java:211) ~[classes/:?]
        at com.starrocks.sql.analyzer.ExpressionAnalyzer.analyze(ExpressionAnalyzer.java:111) ~[classes/:?]
        at com.starrocks.sql.analyzer.ExpressionAnalyzer.analyzeExpression(ExpressionAnalyzer.java:1217) ~[classes/:?]
        at com.starrocks.catalog.MaterializedView.analyzePartitionInfo(MaterializedView.java:612) ~[classes/:?]
        at com.starrocks.catalog.MaterializedView.onCreate(MaterializedView.java:578) ~[classes/:?]
        at com.starrocks.catalog.Database.createMaterializedWithLock(Database.java:551) ~[classes/:?]
        at com.starrocks.server.LocalMetastore.replayCreateMaterializedView(LocalMetastore.java:2701) ~[classes/:?]
        at com.starrocks.server.GlobalStateMgr.replayCreateMaterializedView(GlobalStateMgr.java:2594) ~[classes/:?]
        at com.starrocks.persist.EditLog.loadJournal(EditLog.java:260) ~[classes/:?]
        ... 6 more
2023-02-06 17:12:53,993 WARN (leaderCheckpointer|84) [GlobalStateMgr.replayJournal():1891] got interrupt exception or inconsistent exception when replay journal 523335, will exit,
com.starrocks.journal.JournalInconsistentException: failed to load journal type 10094
        at com.starrocks.persist.EditLog.loadJournal(EditLog.java:1011) ~[classes/:?]
        at com.starrocks.server.GlobalStateMgr.replayJournalInner(GlobalStateMgr.java:1938) ~[classes/:?]
        at com.starrocks.server.GlobalStateMgr.replayJournal(GlobalStateMgr.java:1889) [classes/:?]
        at com.starrocks.leader.Checkpoint.replayAndGenerateGlobalStateMgrImage(Checkpoint.java:215) [classes/:?]
        at com.starrocks.leader.Checkpoint.runAfterCatalogReady(Checkpoint.java:106) [classes/:?]
        at com.starrocks.common.util.LeaderDaemon.runOneCycle(LeaderDaemon.java:73) [classes/:?]
        at com.starrocks.common.util.Daemon.run(Daemon.java:115) [classes/:?]
Caused by: com.starrocks.sql.analyzer.SemanticException: date_trunc function can't support argument other than year|quarter|month|week|day
        at com.starrocks.sql.analyzer.FunctionAnalyzer.analyze(FunctionAnalyzer.java:60) ~[classes/:?]
        at com.starrocks.sql.analyzer.ExpressionAnalyzer$Visitor.visitFunctionCall(ExpressionAnalyzer.java:897) ~[classes/:?]
        at com.starrocks.sql.analyzer.ExpressionAnalyzer$Visitor.visitFunctionCall(ExpressionAnalyzer.java:214) ~[classes/:?]
        at com.starrocks.analysis.FunctionCallExpr.accept(FunctionCallExpr.java:454) ~[classes/:?]
        at com.starrocks.sql.ast.AstVisitor.visit(AstVisitor.java:55) ~[classes/:?]
        at com.starrocks.sql.analyzer.ExpressionAnalyzer.bottomUpAnalyze(ExpressionAnalyzer.java:211) ~[classes/:?]
        at com.starrocks.sql.analyzer.ExpressionAnalyzer.analyze(ExpressionAnalyzer.java:111) ~[classes/:?]
        at com.starrocks.sql.analyzer.ExpressionAnalyzer.analyzeExpression(ExpressionAnalyzer.java:1217) ~[classes/:?]
        at com.starrocks.catalog.MaterializedView.analyzePartitionInfo(MaterializedView.java:612) ~[classes/:?]
        at com.starrocks.catalog.MaterializedView.onCreate(MaterializedView.java:578) ~[classes/:?]
        at com.starrocks.catalog.Database.createMaterializedWithLock(Database.java:551) ~[classes/:?]
        at com.starrocks.server.LocalMetastore.replayCreateMaterializedView(LocalMetastore.java:2701) ~[classes/:?]
        at com.starrocks.server.GlobalStateMgr.replayCreateMaterializedView(GlobalStateMgr.java:2594) ~[classes/:?]
        at com.starrocks.persist.EditLog.loadJournal(EditLog.java:260) ~[classes/:?]
        ... 6 more
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
2.5.0

### PR DESCRIPTION
**Pull request by Astralidea**
Signed-off-by: Astralidea <astralidea@163.com>

## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #17424

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Review by ABingHuang — APPROVED** [review]
LGTM

**Review by HangyuanLiu — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by Astralidea** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 6 / 6 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/MaterializedView.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/scheduler/PartitionBasedMaterializedViewRefreshProcessor.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/FunctionAnalyzer.java|4|4|100.00%|[]|

**Comment by Astralidea** [comment]
run starrocks_admit_test

**Comment by Astralidea** [comment]
run starrocks_admit_test

**Comment by Astralidea** [comment]
run starrocks_be_unittest

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
