### PR TITLE
[BugFix] Fix some bugs of light schema change

### LINKED ISSUE #32632: Non-primary key table compaction cause BE crash
### Steps to reproduce the behavior (Required)
1. CREATE TABLE  using light schema change
2. Concurrent Execution of DML and DDL Operations

### Expected behavior (Required)
run normal

### Real behavior (Required)
BE maybe crash
```
*** Aborted at 1697065809 (unix time) try "date -d @1697065809" if you are using GNU date ***
PC: @     0x7f6c050d48c1 __strlen_sse2_pminub
*** SIGSEGV (@0x0) received by PID 2565 (TID 0x7f6b21174700) from PID 0; stack trace: ***
    @          0x6314e02 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7f6c0688fcfb os::Linux::chained_handler()
    @     0x7f6c068949bd JVM_handle_linux_signal
    @     0x7f6c06888ad8 signalHandler()
    @     0x7f6c05a50630 (unknown)
    @     0x7f6c050d48c1 __strlen_sse2_pminub
    @          0x4daa7bc starrocks::Segment::new_column_iterator()
    @          0x4dc0e1d starrocks::SegmentIterator::_init_column_iterator_by_cid()
    @          0x4dd2d0b starrocks::SegmentIterator::_init_column_iterators<>()
    @          0x4dc740b starrocks::SegmentIterator::_init()
    @          0x4dc77f0 starrocks::SegmentIterator::do_get_next()
    @          0x5453255 starrocks::SegmentIteratorWrapper::do_get_next()
    @          0x529a903 starrocks::TimedChunkIterator::do_get_next()
    @          0x4e89f06 starrocks::TabletReader::do_get_next()
    @          0x543f4ff starrocks::HorizontalCompactionTask::_compact_data()
    @          0x5440262 starrocks::HorizontalCompactionTask::_horizontal_compact_data()
    @          0x54409b9 starrocks::HorizontalCompactionTask::run_impl()
    @          0x543bc8a starrocks::CompactionTask::run()
    @          0x4eea2b3 _ZNSt17_Function_handlerIFvvEZN9starrocks17CompactionManager9_scheduleEvEUlvE_E9_M_invokeERKSt9_Any_data
    @          0x2c487aa starrocks::ThreadPool::dispatch_thread()
    @          0x2c4321a starrocks::Thread::supervise_thread()
    @     0x7f6c05a48ea5 start_thread
    @     0x7f6c05063b0d __clone
    @                0x0 (unknown)
```

### StarRocks version (Required)
 - main and branch-3.2
 

### Reason
The reason is when we do compaction task for non-primary key table, we use the newest schema of candidate rowset as the output rowset schema. But when we create tablet reader, we use the latest tablet schema to init tablet reader.

### LINKED ISSUE #32633: Some directly schema change job maybe run as linked schema change job.
### Steps to reproduce the behavior (Required)
1. CREATE TABLE using light schema change
2. Import data during direct schema change job
### Expected behavior (Required)
run sucess

### Real behavior (Required)
BE maybe crash
e49da00a-2d38-4eac-a2d0-ea27289113f7

### StarRocks version (Required)
 - main
 - branch-3.2

### Reason
If we create a table using light schema change.
```
CREATE TABLE `pk1` (
  `k1` bigint NOT NULL COMMENT "",
  `v1` int NOT NULL COMMENT ""
) ENGINE=OLAP
PRIMARY KEY(`k1`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`k1`) BUCKETS 1
PROPERTIES (
"replication_num" = "1"
);
```
And we submit an alter job `alter table pk1 modify column v1 bigint`. We will create new tablet for each tablet of origin table. And the new tablet schema in FE is:
```
`k1` bigint
`__starrocks_shadow_v1` bigint
```
The prefix `__starrocks_shadow` will be remove after alter job finish. And during alter job, the new tablet schema in BE is:
```
`k1` bigint
`v1` bigint
```
If we import data into new tablet during the alter job, we will create a new tablet schema according to tablet schema in FE and we will update the tablet schema in BE. After that, when BE execute alter job, this alter job will be treated as a linked schema change job.

### PR DESCRIPTION
**Pull request by sevev**
Fixes https://github.com/StarRocks/starrocks/issues/32632
Fixes https://github.com/StarRocks/starrocks/issues/32633

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 8 / 16 (50.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/storage/tablet_updates.cpp|3|6|50.00%|[3167, 3275, 3525]|
|:large_blue_circle:|src/storage/schema_change.cpp|5|10|50.00%|[699, 700, 701, 823, 826]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 8 / 16 (50.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/storage/tablet_updates.cpp|3|6|50.00%|[3167, 3275, 3525]|
|:large_blue_circle:|src/storage/schema_change.cpp|5|10|50.00%|[699, 700, 701, 823, 826]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 7 / 12 (58.33%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/storage/schema_change.cpp|7|12|58.33%|[705, 706, 707, 780, 783]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:disappointed: **fail** : 12 / 16 (75.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/backup/RestoreJob.java|0|2|00.00%|[863, 864]|
|:large_blue_circle:|com/starrocks/leader/ReportHandler.java|0|2|00.00%|[814, 815]|
|:large_blue_circle:|com/starrocks/planner/OlapTableSink.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/task/CreateReplicaTask.java|7|7|100.00%|[]|
|:large_blue_circle:|com/starrocks/clone/TabletSchedCtx.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/alter/SchemaChangeJobV2.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 12 / 19 (63.16%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/storage/vertical_compaction_task.cpp|0|1|00.00%|[127]|
|:large_blue_circle:|src/storage/metadata_util.cpp|1|2|50.00%|[199]|
|:large_blue_circle:|src/storage/schema_change.cpp|8|13|61.54%|[702, 703, 704, 778, 781]|
|:large_blue_circle:|src/storage/horizontal_compaction_task.cpp|1|1|100.00%|[]|
|:large_blue_circle:|src/storage/tablet_reader.cpp|2|2|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 12 / 19 (63.16%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/storage/vertical_compaction_task.cpp|0|1|00.00%|[127]|
|:large_blue_circle:|src/storage/metadata_util.cpp|1|2|50.00%|[199]|
|:large_blue_circle:|src/storage/schema_change.cpp|8|13|61.54%|[702, 703, 704, 778, 781]|
|:large_blue_circle:|src/storage/horizontal_compaction_task.cpp|1|1|100.00%|[]|
|:large_blue_circle:|src/storage/tablet_reader.cpp|2|2|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:disappointed: **fail** : 12 / 16 (75.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/backup/RestoreJob.java|0|2|00.00%|[863, 864]|
|:large_blue_circle:|com/starrocks/leader/ReportHandler.java|0|2|00.00%|[814, 815]|
|:large_blue_circle:|com/starrocks/planner/OlapTableSink.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/task/CreateReplicaTask.java|7|7|100.00%|[]|
|:large_blue_circle:|com/starrocks/clone/TabletSchedCtx.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/alter/SchemaChangeJobV2.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:disappointed: **fail** : 12 / 16 (75.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/backup/RestoreJob.java|0|2|00.00%|[863, 864]|
|:large_blue_circle:|com/starrocks/leader/ReportHandler.java|0|2|00.00%|[814, 815]|
|:large_blue_circle:|com/starrocks/planner/OlapTableSink.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/task/CreateReplicaTask.java|7|7|100.00%|[]|
|:large_blue_circle:|com/starrocks/clone/TabletSchedCtx.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/alter/SchemaChangeJobV2.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 11 / 18 (61.11%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/storage/vertical_compaction_task.cpp|0|1|00.00%|[127]|
|:large_blue_circle:|src/storage/metadata_util.cpp|1|2|50.00%|[199]|
|:large_blue_circle:|src/storage/schema_change.cpp|7|12|58.33%|[702, 703, 704, 777, 780]|
|:large_blue_circle:|src/storage/horizontal_compaction_task.cpp|1|1|100.00%|[]|
|:large_blue_circle:|src/storage/tablet_reader.cpp|2|2|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 12 / 15 (80.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/backup/RestoreJob.java|0|1|00.00%|[863]|
|:large_blue_circle:|com/starrocks/leader/ReportHandler.java|0|2|00.00%|[814, 815]|
|:large_blue_circle:|com/starrocks/planner/OlapTableSink.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/task/CreateReplicaTask.java|7|7|100.00%|[]|
|:large_blue_circle:|com/starrocks/clone/TabletSchedCtx.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/alter/SchemaChangeJobV2.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 11 / 18 (61.11%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/storage/vertical_compaction_task.cpp|0|1|00.00%|[127]|
|:large_blue_circle:|src/storage/metadata_util.cpp|1|2|50.00%|[199]|
|:large_blue_circle:|src/storage/schema_change.cpp|7|12|58.33%|[702, 703, 704, 777, 780]|
|:large_blue_circle:|src/storage/horizontal_compaction_task.cpp|1|1|100.00%|[]|
|:large_blue_circle:|src/storage/tablet_reader.cpp|2|2|100.00%|[]|

**Review by decster — APPROVED** [review]

**Review by chaoyli — APPROVED** [review]

**Pull request merged**
