### PR TITLE
[BugFix] Avoid sampling statistics using count as an alias to duplicate the column name in the table

### LINKED ISSUE #18685: Sampling statistics using count as an alias to duplicate the column name in the table
### Steps to reproduce the behavior (Required)
1. CREATE TABLE `t3` (
  `v1` bigint(20) NULL COMMENT "",
  `count` bigint(20) NULL COMMENT "",
  `v3` varchar(20) NULL COMMENT ""
) ENGINE=OLAP
DUPLICATE KEY(`v1`, `count`, `v3`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`v1`) BUCKETS 3
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"storage_format" = "DEFAULT",
"enable_persistent_index" = "false",
"replicated_storage" = "false",
"compression" = "LZ4"
);
2. INSERT INTO '....'
3. analyze sample table t3

### Real behavior (Required)
Column 'count' cannot be resolved
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by HangyuanLiu**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #18685

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 0 / 2 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/statistic/StatisticsCollectJob.java|0|2|00.00%|[129, 131]|

**Comment by wangruin** [comment]
run starrocks_image_update

**Review by kangkaisen — APPROVED** [review]

**Review by Seaven — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by HangyuanLiu** [comment]
@Mergifyio backport branch-3.0

**Comment by HangyuanLiu** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
