### PR TITLE
[Enhancement] profile add metrics

### PR DESCRIPTION
**Pull request by liuyehcf**
## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [x] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
starrocks_be_unittest succeeded.

**Review by murphyatwork — APPROVED** [review]

**Review by kangkaisen — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by satanson** [comment]
run starrocks_admit_test

**Comment by satanson** [comment]
run starrocks_admit_test

**Comment by satanson** [comment]
run starrocks_admit_test

**Comment by liuyehcf** [comment]
run starrocks_admit_test

**Review by ZiheLiu — APPROVED** [review]

**Comment by liuyehcf** [comment]
run starrocks_admit_test

**Pull request merged**
