### PR TITLE
[BugFix] Fix two window with cte bug

### LINKED ISSUE #13798: [sqlancer] NPE of physical plan translator
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
2. INSERT INTO '....'
3. SELECT  '....'

```sql
DROP DATABASE IF EXISTS w2;
CREATE DATABASE w2;
USE w2;
admin set frontend config ("enable_decimal_v3" = "true");
CREATE TABLE IF NOT EXISTS t0 (c_0_0 DATE NOT NULL ,c_0_1 DOUBLE NOT NULL ,c_0_2 DECIMAL(27, 19)  NULL ,c_0_3 ARRAY<STRING> NULL ) DUPLICATE KEY (c_0_0) PARTITION BY RANGE(c_0_0) (START ("2010-01-01") END ("2022-12-31") EVERY (INTERVAL 175 day)) DISTRIBUTED BY HASH (c_0_0) BUCKETS 3 properties("replication_num"="3") ;
CREATE TABLE t1 (c_1_0 DATE NULL ) UNIQUE KEY (c_1_0) PARTITION BY RANGE(c_1_0) (START ("2010-01-01") END ("2022-12-31") EVERY (INTERVAL 131 day)) DISTRIBUTED BY HASH (c_1_0) BUCKETS 3 properties("replication_num"="3") ;
INSERT INTO t0 VALUES ('2010-01-12', 0.29438749363927297, 8.781646E-13, ["DF", "K", "cFCmjPZA0", "e", "s", "", "2", "KbsMbOYcU", "Tr", "Xrwln0qN", "HOTugUYl", "O", "Dp4WC", "a0dkP"]), ('2010-01-08', 0.1710817481746646, 6.4065468E-12, ["20", "LY2", "", "", "S0K", "ZIVggpQ", "", "", "", "", "B", ""]);
INSERT INTO t0 VALUES ('2010-01-31', 0.7127058571080402, NULL, ["t", "ekBDr", "", "Yxy", "", "", "", "c", "LR", "", "t5r", "cU", "kbz"]), ('2010-01-04', 0.9304568071955054, 3.7725053E-12, ["xZpy"]);
INSERT INTO t1 VALUES ('2010-01-06'), ('2010-01-22');
INSERT INTO t1 VALUES ('2010-01-19');
DELETE FROM t1 WHERE c_1_0='1970-01-01';
INSERT INTO t0 VALUES ('2010-01-25', 0.29438749363927297, 4.6099712E-12, ["9GpOEz0WG", "D4AuLz0", "aC", "Q7lYMZAZ", "0V", "phoCZ", "", "oq", "F8"]), ('2010-01-05', 0.5326011520792849, 5.2060531E-12, ["", "", "", "D", "", "02gR8P9jm", "eyi", "eef8", "Vg9Hyor", "u6cn", "ajM0", "cjR", "07jWkxKVF", "q6FSPp"]);
INSERT INTO t0 VALUES ('2010-01-12', 0.4746284241293818, 5.9919142E-12, ["B5", "clC6", "", ""]), ('2010-01-07', 1.1748564E7, 5.7196880E-12, ["1", "XPE", "pt97Sajt3", "LUfLf"]);
INSERT INTO t1 VALUES ('2010-01-16'), ('2010-01-11'), ('2010-01-17');
CREATE MATERIALIZED VIEW v0 AS SELECT t1_22.c_1_0 FROM t1 AS t1_22;
CREATE VIEW v0 AS SELECT DISTINCT t1_24.c_1_0 FROM t1 AS t1_24 WHERE (NOT (false));
INSERT INTO t0 VALUES ('2010-01-13', 1.1748564E7, 7.4870152E-12, ["s9D2", "JafHH", "kWhsi", "EU5M", "QNO3E", "PX", "r", "GA"]), ('2010-01-03', 0.9735727717624472, 2.3774140E-12, ["Z", "BLBP", "oIy", "54M0B3tND", "AUK2u6", "AQ", "", "", "CMTeuLie", "yTPbr60"]), ('2010-01-28', 0.920787524240705, 5.0780819E-12, ["P"]);
INSERT INTO t0 VALUES ('2010-01-19', 0.18127973113885543, 9.4736294E-12, ["", "FyiV", "", "y2", "72t", "h", "G", "", "", "", "", "3wsX0H", "3"]);
INSERT INTO t0 VALUES ('2010-01-12', 0.5218319565901469, 6.3877909E-12, ["qLRE", "N", "", "gPbBZPZPd", "3dOcT", ""]), ('2009-12-31', 1.1748564E7, 7.4311410E-12, ["", "", "P", "czKjmKo", "EhX8", "", ""]);
INSERT INTO t1 VALUES ('2010-01-10');
INSERT INTO t0 VALUES ('2010-01-04', 0.828250324138595, NULL, ["8", "D"]);
INSERT INTO t1 VALUES ('2010-01-16');
TRUNCATE TABLE t1;

WITH with_t_0 as (SELECT v0_30.c_1_0 FROM v0 AS v0_30) SELECT subt0.c_0_0, ROW_NUMBER() OVER ( PARTITION BY subt0.c_0_0, subt0.c_0_1, with_t_0.c_1_0, subt0.c_0_2) , LAST_VALUE(subv0.c_1_0) OVER ( ORDER BY subt0.c_0_0) , RANK() OVER ( ORDER BY with_t_0.c_1_0, subv0.c_1_0)  FROM  (SELECT t0_28.c_0_0, t0_28.c_0_1, t0_28.c_0_2 FROM t0 AS t0_28) subt0 INNER JOIN (SELECT v0_30.c_1_0 FROM v0 AS v0_30 WHERE false) subv0 ON subt0.c_0_2 = subv0.c_1_0 AND subt0.c_0_2 >= subv0.c_1_0 AND subt0.c_0_0 > subv0.c_1_0 AND subt0.c_0_0 != subv0.c_1_0,  (SELECT t1_29.c_1_0 FROM t1 AS t1_29) subt1 RIGHT ANTI JOIN with_t_0 AS with_t_0 ON subt1.c_1_0 = with_t_0.c_1_0 AND subt1.c_1_0 >= with_t_0.c_1_0 AND subt1.c_1_0 < with_t_0.c_1_0 AND subt1.c_1_0 = with_t_0.c_1_0 WHERE (subt0.c_0_0)  BETWEEN (subt0.c_0_0) AND (subt0.c_0_0)  UNION ALL SELECT subt0.c_0_0, ROW_NUMBER() OVER ( PARTITION BY subt0.c_0_0, subt0.c_0_1, with_t_0.c_1_0, subt0.c_0_2) , LAST_VALUE(subv0.c_1_0) OVER ( ORDER BY subt0.c_0_0) , RANK() OVER ( ORDER BY with_t_0.c_1_0, subv0.c_1_0)  FROM  (SELECT t0_28.c_0_0, t0_28.c_0_1, t0_28.c_0_2 FROM t0 AS t0_28) subt0 INNER JOIN (SELECT v0_30.c_1_0 FROM v0 AS v0_30 WHERE false) subv0 ON subt0.c_0_2 = subv0.c_1_0 AND subt0.c_0_2 >= subv0.c_1_0 AND subt0.c_0_0 > subv0.c_1_0 AND subt0.c_0_0 != subv0.c_1_0,  (SELECT t1_29.c_1_0 FROM t1 AS t1_29) subt1 RIGHT ANTI JOIN with_t_0 AS with_t_0 ON subt1.c_1_0 = with_t_0.c_1_0 AND subt1.c_1_0 >= with_t_0.c_1_0 AND subt1.c_1_0 < with_t_0.c_1_0 AND subt1.c_1_0 = with_t_0.c_1_0 WHERE (NOT ((subt0.c_0_0)  BETWEEN (subt0.c_0_0) AND (subt0.c_0_0) )) UNION ALL SELECT subt0.c_0_0, ROW_NUMBER() OVER ( PARTITION BY subt0.c_0_0, subt0.c_0_1, with_t_0.c_1_0, subt0.c_0_2) , LAST_VALUE(subv0.c_1_0) OVER ( ORDER BY subt0.c_0_0) , RANK() OVER ( ORDER BY with_t_0.c_1_0, subv0.c_1_0)  FROM  (SELECT t0_28.c_0_0, t0_28.c_0_1, t0_28.c_0_2 FROM t0 AS t0_28) subt0 INNER JOIN (SELECT v0_30.c_1_0 FROM v0 AS v0_30 WHERE false) subv0 ON subt0.c_0_2 = subv0.c_1_0 AND subt0.c_0_2 >= subv0.c_1_0 AND subt0.c_0_0 > subv0.c_1_0 AND subt0.c_0_0 != subv0.c_1_0,  (SELECT t1_29.c_1_0 FROM t1 AS t1_29) subt1 RIGHT ANTI JOIN with_t_0 AS with_t_0 ON subt1.c_1_0 = with_t_0.c_1_0 AND subt1.c_1_0 >= with_t_0.c_1_0 AND subt1.c_1_0 < with_t_0.c_1_0 AND subt1.c_1_0 = with_t_0.c_1_0 WHERE (((subt0.c_0_0)  BETWEEN (subt0.c_0_0) AND (subt0.c_0_0) ) IS NULL);
```

### Expected behavior (Required)
no error

### Real behavior (Required)
ERROR 1064 (HY000): Unknown error

fe.log
java.lang.NullPointerException: null
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visitPhysicalCTEConsume(PlanFragmentBuilder.java:2527) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visitPhysicalCTEConsume(PlanFragmentBuilder.java:255) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.operator.physical.PhysicalCTEConsumeOperator.accept(PhysicalCTEConsumeOperator.java:41) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visit(PlanFragmentBuilder.java:264) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visitPhysicalDistribution(PlanFragmentBuilder.java:1559) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visitPhysicalDistribution(PlanFragmentBuilder.java:255) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.operator.physical.PhysicalDistributionOperator.accept(PhysicalDistributionOperator.java:44) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visit(PlanFragmentBuilder.java:264) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visitPhysicalHashJoin(PlanFragmentBuilder.java:1760) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visitPhysicalHashJoin(PlanFragmentBuilder.java:255) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.operator.physical.PhysicalHashJoinOperator.accept(PhysicalHashJoinOperator.java:33) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visit(PlanFragmentBuilder.java:264) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visitPhysicalDistribution(PlanFragmentBuilder.java:1559) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visitPhysicalDistribution(PlanFragmentBuilder.java:255) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.operator.physical.PhysicalDistributionOperator.accept(PhysicalDistributionOperator.java:44) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visit(PlanFragmentBuilder.java:264) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visitPhysicalNestLoopJoin(PlanFragmentBuilder.java:1775) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visitPhysicalNestLoopJoin(PlanFragmentBuilder.java:255) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.operator.physical.PhysicalNestLoopJoinOperator.accept(PhysicalNestLoopJoinOperator.java:32) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visit(PlanFragmentBuilder.java:264) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visitPhysicalTopN(PlanFragmentBuilder.java:1610) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visitPhysicalTopN(PlanFragmentBuilder.java:255) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.operator.physical.PhysicalTopNOperator.accept(PhysicalTopNOperator.java:110) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visit(PlanFragmentBuilder.java:264) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visitPhysicalAnalytic(PlanFragmentBuilder.java:2242) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visitPhysicalAnalytic(PlanFragmentBuilder.java:255) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.operator.physical.PhysicalWindowOperator.accept(PhysicalWindowOperator.java:75) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visit(PlanFragmentBuilder.java:264) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visitPhysicalTopN(PlanFragmentBuilder.java:1610) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visitPhysicalTopN(PlanFragmentBuilder.java:255) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.operator.physical.PhysicalTopNOperator.accept(PhysicalTopNOperator.java:110) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visit(PlanFragmentBuilder.java:264) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visitPhysicalTopN(PlanFragmentBuilder.java:1610) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visitPhysicalTopN(PlanFragmentBuilder.java:255) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.operator.physical.PhysicalTopNOperator.accept(PhysicalTopNOperator.java:110) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visit(PlanFragmentBuilder.java:264) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visitPhysicalAnalytic(PlanFragmentBuilder.java:2242) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visitPhysicalAnalytic(PlanFragmentBuilder.java:255) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.operator.physical.PhysicalWindowOperator.accept(PhysicalWindowOperator.java:75) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visit(PlanFragmentBuilder.java:264) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visitPhysicalTopN(PlanFragmentBuilder.java:1610) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visitPhysicalTopN(PlanFragmentBuilder.java:255) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.operator.physical.PhysicalTopNOperator.accept(PhysicalTopNOperator.java:110) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visit(PlanFragmentBuilder.java:264) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visitPhysicalAnalytic(PlanFragmentBuilder.java:2242) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visitPhysicalAnalytic(PlanFragmentBuilder.java:255) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.operator.physical.PhysicalWindowOperator.accept(PhysicalWindowOperator.java:75) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visit(PlanFragmentBuilder.java:264) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.buildSetOperation(PlanFragmentBuilder.java:2359) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visitPhysicalUnion(PlanFragmentBuilder.java:2404) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visitPhysicalUnion(PlanFragmentBuilder.java:255) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.operator.physical.PhysicalUnionOperator.accept(PhysicalUnionOperator.java:37) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visit(PlanFragmentBuilder.java:264) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visitPhysicalNoCTE(PlanFragmentBuilder.java:2592) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visitPhysicalNoCTE(PlanFragmentBuilder.java:255) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.operator.physical.PhysicalNoCTEOperator.accept(PhysicalNoCTEOperator.java:33) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visit(PlanFragmentBuilder.java:264) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.plan.PlanFragmentBuilder.createPhysicalPlan(PlanFragmentBuilder.java:169) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.createQueryPlan(StatementPlanner.java:119) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:65) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:37) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:367) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:305) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:420) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:666) ~[starrocks-fe.jar:?]
        at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:55) ~[starrocks-fe.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
mysql> select current_version();
+-------------------------+
| current_version()       |
+-------------------------+
| BRANCH-2.5-ASAN d2634e6 |
+-------------------------+
1 row in set (0.00 sec)

### PR DESCRIPTION
**Pull request by Seaven**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes https://github.com/StarRocks/starrocks/issues/13798

## Problem Summary(Required) ：

when Window Node enforce sort & distribute, replace ANY property lose CTE propery

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

- [ ] I have checked the version labels which the pr will be auto backported to target branch

### CODE REVIEW

**Review by kangkaisen — DISMISSED** [review]

**Comment by Seaven** [comment]
@mergify rebase

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/task/EnforceAndCostTask.java|1|1|100.00%|[]|

**Comment by Seaven** [comment]
run starrocks_admit_test

**Review by kangkaisen — APPROVED** [review]

**Review by liuyehcf — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
