### PR TITLE
[Refactor] delete Database::getFullName

### PR DESCRIPTION
**Pull request by zombee0**
Signed-off-by: zombee0 <flylucas_10@163.com>

## What type of PR is this：
- [ ] bugfix
- [ ] feature
- [ ] enhancement
- [x] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

we have removed default_cluster from dbname, so the getfullname is same with getoriginname and can be deleted.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 34 / 67 (50.75%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/lake/compaction/CompactionDispatchDaemon.java|0|1|00.00%|[124]|
|:large_blue_circle:|com/starrocks/scheduler/PartitionBasedMaterializedViewRefreshProcessor.java|0|2|00.00%|[544, 557]|
|:large_blue_circle:|com/starrocks/load/ExportMgr.java|0|1|00.00%|[218]|
|:large_blue_circle:|com/starrocks/http/rest/QueryDumpAction.java|0|1|00.00%|[66]|
|:large_blue_circle:|com/starrocks/catalog/TabletStatMgr.java|0|1|00.00%|[101]|
|:large_blue_circle:|com/starrocks/load/PartitionUtils.java|0|1|00.00%|[29]|
|:large_blue_circle:|com/starrocks/statistic/SampleStatisticsCollectJob.java|0|1|00.00%|[121]|
|:large_blue_circle:|com/starrocks/load/loadv2/LoadJob.java|0|2|00.00%|[520, 527]|
|:large_blue_circle:|com/starrocks/load/routineload/KafkaTaskInfo.java|0|1|00.00%|[140]|
|:large_blue_circle:|com/starrocks/common/proc/StatisticProcDir.java|0|1|00.00%|[167]|
|:large_blue_circle:|com/starrocks/transaction/GlobalTransactionMgr.java|0|1|00.00%|[369]|
|:large_blue_circle:|com/starrocks/load/InsertOverwriteJobRunner.java|0|1|00.00%|[168]|
|:large_blue_circle:|com/starrocks/analysis/Analyzer.java|0|1|00.00%|[288]|
|:large_blue_circle:|com/starrocks/transaction/PublishVersionDaemon.java|0|1|00.00%|[382]|
|:large_blue_circle:|com/starrocks/qe/ShowExecutor.java|1|4|25.00%|[614, 1129, 1494]|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|7|18|38.89%|[319, 333, 509, 515, 521, 617, 659, 683, 1450, 2437, 4019]|
|:large_blue_circle:|com/starrocks/load/routineload/RoutineLoadJob.java|2|3|66.67%|[1308]|
|:large_blue_circle:|com/starrocks/catalog/CatalogRecycleBin.java|2|3|66.67%|[476]|
|:large_blue_circle:|com/starrocks/transaction/DatabaseTransactionMgr.java|2|3|66.67%|[1400]|
|:large_blue_circle:|com/starrocks/catalog/MaterializedView.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/http/rest/TableQueryPlanAction.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/OlapTable.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/InsertAnalyzer.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/ResourceGroupClassifier.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AnalyzerUtils.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/common/SqlWithIdUtils.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/qe/StmtExecutor.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/statistic/StatisticsCollectJobFactory.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/ColocateTableIndex.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/PrivilegeChecker.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/alter/SchemaChangeHandler.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/statistic/AnalyzeManager.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/load/loadv2/InsertLoadJob.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/alter/MaterializedViewHandler.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/load/loadv2/BulkLoadJob.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/load/DeleteHandler.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/statistics/ColumnBasicStatsCacheLoader.java|1|1|100.00%|[]|

**Review by gengjun-git — DISMISSED** [review]

**Comment by zombee0** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 33 / 65 (50.77%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/lake/compaction/CompactionDispatchDaemon.java|0|1|00.00%|[124]|
|:large_blue_circle:|com/starrocks/load/ExportMgr.java|0|1|00.00%|[218]|
|:large_blue_circle:|com/starrocks/http/rest/QueryDumpAction.java|0|1|00.00%|[66]|
|:large_blue_circle:|com/starrocks/catalog/TabletStatMgr.java|0|1|00.00%|[101]|
|:large_blue_circle:|com/starrocks/load/PartitionUtils.java|0|1|00.00%|[30]|
|:large_blue_circle:|com/starrocks/statistic/SampleStatisticsCollectJob.java|0|1|00.00%|[119]|
|:large_blue_circle:|com/starrocks/load/loadv2/LoadJob.java|0|2|00.00%|[520, 527]|
|:large_blue_circle:|com/starrocks/load/routineload/KafkaTaskInfo.java|0|1|00.00%|[140]|
|:large_blue_circle:|com/starrocks/common/proc/StatisticProcDir.java|0|1|00.00%|[167]|
|:large_blue_circle:|com/starrocks/transaction/GlobalTransactionMgr.java|0|1|00.00%|[369]|
|:large_blue_circle:|com/starrocks/load/InsertOverwriteJobRunner.java|0|2|00.00%|[223, 322]|
|:large_blue_circle:|com/starrocks/analysis/Analyzer.java|0|1|00.00%|[288]|
|:large_blue_circle:|com/starrocks/transaction/PublishVersionDaemon.java|0|1|00.00%|[382]|
|:large_blue_circle:|com/starrocks/qe/ShowExecutor.java|0|1|00.00%|[613]|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|7|19|36.84%|[318, 332, 514, 520, 526, 533, 634, 676, 700, 1467, 2449, 4018]|
|:large_blue_circle:|com/starrocks/load/routineload/RoutineLoadJob.java|1|2|50.00%|[1308]|
|:large_blue_circle:|com/starrocks/scheduler/PartitionBasedMaterializedViewRefreshProcessor.java|1|2|50.00%|[557]|
|:large_blue_circle:|com/starrocks/catalog/CatalogRecycleBin.java|2|3|66.67%|[476]|
|:large_blue_circle:|com/starrocks/transaction/DatabaseTransactionMgr.java|2|3|66.67%|[1403]|
|:large_blue_circle:|com/starrocks/catalog/MaterializedView.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/http/rest/TableQueryPlanAction.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/OlapTable.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/InsertAnalyzer.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/ResourceGroupClassifier.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AnalyzerUtils.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/common/SqlWithIdUtils.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/qe/StmtExecutor.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/statistic/StatisticsCollectJobFactory.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/ColocateTableIndex.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/PrivilegeChecker.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/alter/SchemaChangeHandler.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/statistic/AnalyzeManager.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/load/loadv2/InsertLoadJob.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/alter/MaterializedViewHandler.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/load/loadv2/BulkLoadJob.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/load/DeleteHandler.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/statistics/ColumnBasicStatsCacheLoader.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 35 / 75 (46.67%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/alter/Alter.java|0|3|00.00%|[131, 167, 232]|
|:large_blue_circle:|com/starrocks/scheduler/PartitionBasedMaterializedViewRefreshProcessor.java|0|4|00.00%|[153, 547, 554, 572]|
|:large_blue_circle:|com/starrocks/load/ExportMgr.java|0|1|00.00%|[218]|
|:large_blue_circle:|com/starrocks/http/rest/QueryDumpAction.java|0|1|00.00%|[66]|
|:large_blue_circle:|com/starrocks/catalog/TabletStatMgr.java|0|1|00.00%|[101]|
|:large_blue_circle:|com/starrocks/statistic/SampleStatisticsCollectJob.java|0|1|00.00%|[119]|
|:large_blue_circle:|com/starrocks/load/loadv2/LoadJob.java|0|2|00.00%|[520, 527]|
|:large_blue_circle:|com/starrocks/load/routineload/KafkaTaskInfo.java|0|1|00.00%|[140]|
|:large_blue_circle:|com/starrocks/lake/compaction/CompactionScheduler.java|0|1|00.00%|[244]|
|:large_blue_circle:|com/starrocks/common/proc/StatisticProcDir.java|0|1|00.00%|[167]|
|:large_blue_circle:|com/starrocks/transaction/GlobalTransactionMgr.java|0|1|00.00%|[372]|
|:large_blue_circle:|com/starrocks/load/InsertOverwriteJobRunner.java|0|2|00.00%|[223, 322]|
|:large_blue_circle:|com/starrocks/analysis/Analyzer.java|0|1|00.00%|[275]|
|:large_blue_circle:|com/starrocks/transaction/PublishVersionDaemon.java|0|1|00.00%|[382]|
|:large_blue_circle:|com/starrocks/qe/ShowExecutor.java|1|4|25.00%|[611, 1125, 1490]|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|7|19|36.84%|[318, 332, 514, 520, 526, 533, 634, 676, 700, 1467, 2449, 4018]|
|:large_blue_circle:|com/starrocks/qe/StmtExecutor.java|1|2|50.00%|[1080]|
|:large_blue_circle:|com/starrocks/load/routineload/RoutineLoadJob.java|2|3|66.67%|[1307]|
|:large_blue_circle:|com/starrocks/catalog/CatalogRecycleBin.java|2|3|66.67%|[476]|
|:large_blue_circle:|com/starrocks/transaction/DatabaseTransactionMgr.java|2|3|66.67%|[1413]|
|:large_blue_circle:|com/starrocks/catalog/MaterializedView.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/http/rest/TableQueryPlanAction.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/load/PartitionUtils.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/OlapTable.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/InsertAnalyzer.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/ResourceGroupClassifier.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AnalyzerUtils.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/common/SqlWithIdUtils.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/statistic/StatisticsCollectJobFactory.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/ColocateTableIndex.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/PrivilegeChecker.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/alter/SchemaChangeHandler.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/statistic/AnalyzeManager.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/load/loadv2/InsertLoadJob.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/alter/MaterializedViewHandler.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/load/loadv2/BulkLoadJob.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/load/DeleteHandler.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/statistics/ColumnBasicStatsCacheLoader.java|1|1|100.00%|[]|

**Review by imay — DISMISSED** [review]

**Comment by gengjun-git** [comment]
@zombee0 please fix the conflict

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 35 / 75 (46.67%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/alter/Alter.java|0|3|00.00%|[131, 167, 232]|
|:large_blue_circle:|com/starrocks/load/ExportMgr.java|0|1|00.00%|[218]|
|:large_blue_circle:|com/starrocks/http/rest/QueryDumpAction.java|0|1|00.00%|[66]|
|:large_blue_circle:|com/starrocks/catalog/TabletStatMgr.java|0|1|00.00%|[101]|
|:large_blue_circle:|com/starrocks/load/PartitionUtils.java|0|1|00.00%|[30]|
|:large_blue_circle:|com/starrocks/statistic/SampleStatisticsCollectJob.java|0|1|00.00%|[119]|
|:large_blue_circle:|com/starrocks/load/loadv2/LoadJob.java|0|2|00.00%|[521, 528]|
|:large_blue_circle:|com/starrocks/load/routineload/KafkaTaskInfo.java|0|1|00.00%|[140]|
|:large_blue_circle:|com/starrocks/lake/compaction/CompactionScheduler.java|0|1|00.00%|[244]|
|:large_blue_circle:|com/starrocks/common/proc/StatisticProcDir.java|0|1|00.00%|[167]|
|:large_blue_circle:|com/starrocks/transaction/GlobalTransactionMgr.java|0|1|00.00%|[372]|
|:large_blue_circle:|com/starrocks/load/InsertOverwriteJobRunner.java|0|2|00.00%|[223, 322]|
|:large_blue_circle:|com/starrocks/analysis/Analyzer.java|0|1|00.00%|[275]|
|:large_blue_circle:|com/starrocks/transaction/PublishVersionDaemon.java|0|1|00.00%|[382]|
|:large_blue_circle:|com/starrocks/scheduler/PartitionBasedMaterializedViewRefreshProcessor.java|1|4|25.00%|[153, 554, 572]|
|:large_blue_circle:|com/starrocks/qe/ShowExecutor.java|1|4|25.00%|[611, 1125, 1490]|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|7|19|36.84%|[318, 332, 514, 520, 526, 533, 634, 676, 700, 1467, 2449, 4018]|
|:large_blue_circle:|com/starrocks/qe/StmtExecutor.java|1|2|50.00%|[1082]|
|:large_blue_circle:|com/starrocks/load/routineload/RoutineLoadJob.java|2|3|66.67%|[1307]|
|:large_blue_circle:|com/starrocks/catalog/CatalogRecycleBin.java|2|3|66.67%|[476]|
|:large_blue_circle:|com/starrocks/transaction/DatabaseTransactionMgr.java|2|3|66.67%|[1413]|
|:large_blue_circle:|com/starrocks/catalog/MaterializedView.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/http/rest/TableQueryPlanAction.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/OlapTable.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/InsertAnalyzer.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/ResourceGroupClassifier.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AnalyzerUtils.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/common/SqlWithIdUtils.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/statistic/StatisticsCollectJobFactory.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/ColocateTableIndex.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/PrivilegeChecker.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/alter/SchemaChangeHandler.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/statistic/AnalyzeManager.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/load/loadv2/InsertLoadJob.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/alter/MaterializedViewHandler.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/load/loadv2/BulkLoadJob.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/load/DeleteHandler.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/statistics/ColumnBasicStatsCacheLoader.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 35 / 75 (46.67%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/alter/Alter.java|0|3|00.00%|[131, 167, 232]|
|:large_blue_circle:|com/starrocks/load/ExportMgr.java|0|1|00.00%|[218]|
|:large_blue_circle:|com/starrocks/http/rest/QueryDumpAction.java|0|1|00.00%|[66]|
|:large_blue_circle:|com/starrocks/catalog/TabletStatMgr.java|0|1|00.00%|[101]|
|:large_blue_circle:|com/starrocks/load/PartitionUtils.java|0|1|00.00%|[30]|
|:large_blue_circle:|com/starrocks/statistic/SampleStatisticsCollectJob.java|0|1|00.00%|[127]|
|:large_blue_circle:|com/starrocks/load/loadv2/LoadJob.java|0|2|00.00%|[521, 528]|
|:large_blue_circle:|com/starrocks/load/routineload/KafkaTaskInfo.java|0|1|00.00%|[140]|
|:large_blue_circle:|com/starrocks/lake/compaction/CompactionScheduler.java|0|1|00.00%|[244]|
|:large_blue_circle:|com/starrocks/common/proc/StatisticProcDir.java|0|1|00.00%|[167]|
|:large_blue_circle:|com/starrocks/transaction/GlobalTransactionMgr.java|0|1|00.00%|[372]|
|:large_blue_circle:|com/starrocks/load/InsertOverwriteJobRunner.java|0|2|00.00%|[223, 322]|
|:large_blue_circle:|com/starrocks/analysis/Analyzer.java|0|1|00.00%|[275]|
|:large_blue_circle:|com/starrocks/transaction/PublishVersionDaemon.java|0|1|00.00%|[382]|
|:large_blue_circle:|com/starrocks/scheduler/PartitionBasedMaterializedViewRefreshProcessor.java|1|4|25.00%|[153, 554, 572]|
|:large_blue_circle:|com/starrocks/qe/ShowExecutor.java|1|4|25.00%|[611, 1125, 1490]|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|7|19|36.84%|[318, 332, 514, 520, 526, 533, 634, 676, 700, 1467, 2449, 4018]|
|:large_blue_circle:|com/starrocks/qe/StmtExecutor.java|1|2|50.00%|[1114]|
|:large_blue_circle:|com/starrocks/load/routineload/RoutineLoadJob.java|2|3|66.67%|[1308]|
|:large_blue_circle:|com/starrocks/catalog/CatalogRecycleBin.java|2|3|66.67%|[476]|
|:large_blue_circle:|com/starrocks/transaction/DatabaseTransactionMgr.java|2|3|66.67%|[1413]|
|:large_blue_circle:|com/starrocks/catalog/MaterializedView.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/http/rest/TableQueryPlanAction.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/OlapTable.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/InsertAnalyzer.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/ResourceGroupClassifier.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AnalyzerUtils.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/common/SqlWithIdUtils.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/statistic/StatisticsCollectJobFactory.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/ColocateTableIndex.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/PrivilegeChecker.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/alter/SchemaChangeHandler.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/statistic/AnalyzeManager.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/load/loadv2/InsertLoadJob.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/alter/MaterializedViewHandler.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/load/loadv2/BulkLoadJob.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/load/DeleteHandler.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/statistics/ColumnBasicStatsCacheLoader.java|1|1|100.00%|[]|

**Pull request closed without merging**
