### PR TITLE
[BugFix] Support non slotref exprs for partition by exprs

### PR DESCRIPTION
**Pull request by LiShuMing**
## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #
https://github.com/StarRocks/StarRocksBenchmark/issues/230

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/planner/RuntimeFilterDescription.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/ExchangeNode.java|1|1|100.00%|[]|

**Review by satanson — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/planner/RuntimeFilterDescription.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/ExchangeNode.java|1|1|100.00%|[]|

**Comment by Seaven** [comment]
Add some test case?

**Review by kangkaisen — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by LiShuMing** [comment]
run starrocks_be_unittest

**Review by Seaven — APPROVED** [review]

**Review by kangkaisen — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by dulong41** [comment]
run starrocks_admit_test

**Comment by dulong41** [comment]
run starrocks_admit_test

**Comment by dulong41** [comment]
run starrocks_admit_test

**Comment by dulong41** [comment]
run starrocks_be_unittest

**Comment by dulong41** [comment]
run starrocks_be_unittest

**Comment by dulong41** [comment]
run starrocks_be_unittest

**Comment by dulong41** [comment]
run starrocks_be_unittest

**Comment by LiShuMing** [comment]
run starrocks_be_unittest

**Comment by dulong41** [comment]
rerun starrocks_be_unittest

**Comment by dulong41** [comment]
starrocks_be_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/planner/RuntimeFilterDescription.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/ExchangeNode.java|1|1|100.00%|[]|

**Pull request merged**
