### PR TITLE
[Enhancement] Support colocate sender in tablet sink

### PR DESCRIPTION
**Pull request by LiShuMing**
Fixes #22401 

This PR follows https://github.com/StarRocks/starrocks/pull/8831 and https://github.com/StarRocks/starrocks/pull/7062 , and make mv colocate index work.

Make MV Index Colocate Optimization work. MV Index Colocate Optimization work only:
1. FE's `enable_colocate_mv_index ` is set (by default true)
2. BE's `enable_colocate_mv_index` is set (by default true)
3. MV's `colocate_mv` is set (by default false)

MV Index Colocate Optimization will send the chunk once to the node that all indexes are colocated in, so it can
reduce load time when there are many table's sync mvs or there are many columns in  base table/sync mv's.

You can choose this optimization like this:
```
create table user_tags (time date, user_id int, user_name varchar(20), tag_id int) partition by range (time)  (partition p1 values less than MAXVALUE) distributed by hash(time) buckets 3 properties('colocate_with' = 'colocate_gorup1', 'replication_num' = '1');

create materialized view user_tags_mv1
PROPERTIES ("colocate_mv" = "true")
as select user_id, time, bitmap_union(to_bitmap(tag_id)) from user_tags group by user_id, time;

```

If the table is not in colocate group, you need to set the table's `colocate_with`(https://docs.starrocks.io/en-us/2.4/sql-reference/sql-statements/data-definition/ALTER%20TABLE#modify-table-properties)

### Benchmark
image

## What type of PR is this:
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 22 / 33 (66.67%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/planner/OlapTableSink.java|1|2|50.00%|[244]|
|:large_blue_circle:|com/starrocks/catalog/OlapTable.java|12|22|54.55%|[1256, 1257, 1258, 1260, 1261, 1262, 1264, 1265, 1271, 1278]|
|:large_blue_circle:|com/starrocks/alter/MaterializedViewHandler.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/alter/RollupJobV2.java|8|8|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 21 / 21 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/MaterializedIndexMeta.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/OlapTable.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/common/Config.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/OlapTableSink.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/ColocateTableIndex.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/alter/MaterializedViewHandler.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/alter/RollupJobV2.java|3|3|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 26 / 28 (92.86%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/OlapTable.java|8|10|80.00%|[1201, 1212]|
|:large_blue_circle:|com/starrocks/catalog/MaterializedIndexMeta.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/common/Config.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/OlapTableSink.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/ColocateTableIndex.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/alter/MaterializedViewHandler.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/alter/RollupJobV2.java|3|3|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 18 / 31 (58.06%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/OlapTable.java|0|12|00.00%|[1200, 1201, 1205, 1206, 1210, 1211, 1215, 1216, 1217, 1221, 1222, 1223]|
|:large_blue_circle:|com/starrocks/planner/OlapTableSink.java|2|3|66.67%|[246]|
|:large_blue_circle:|com/starrocks/catalog/MaterializedIndexMeta.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/common/Config.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/ColocateTableIndex.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/alter/MaterializedViewHandler.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/alter/RollupJobV2.java|3|3|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 46 / 54 (85.19%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/planner/OlapTableSink.java|22|28|78.57%|[526, 527, 559, 560, 561, 564]|
|:large_blue_circle:|com/starrocks/catalog/OlapTable.java|8|10|80.00%|[1201, 1217]|
|:large_blue_circle:|com/starrocks/catalog/MaterializedIndexMeta.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/common/Config.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/ColocateTableIndex.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/alter/MaterializedViewHandler.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/alter/RollupJobV2.java|3|3|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 42 / 56 (75.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/OlapTable.java|5|12|41.67%|[1201, 1215, 1216, 1217, 1221, 1222, 1223]|
|:large_blue_circle:|com/starrocks/planner/OlapTableSink.java|21|28|75.00%|[242, 526, 527, 559, 560, 561, 564]|
|:large_blue_circle:|com/starrocks/catalog/MaterializedIndexMeta.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/common/Config.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/ColocateTableIndex.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/alter/MaterializedViewHandler.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/alter/RollupJobV2.java|3|3|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 42 / 56 (75.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/OlapTable.java|5|12|41.67%|[1201, 1215, 1216, 1217, 1221, 1222, 1223]|
|:large_blue_circle:|com/starrocks/planner/OlapTableSink.java|21|28|75.00%|[242, 526, 527, 559, 560, 561, 564]|
|:large_blue_circle:|com/starrocks/catalog/MaterializedIndexMeta.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/common/Config.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/ColocateTableIndex.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/alter/MaterializedViewHandler.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/alter/RollupJobV2.java|3|3|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 42 / 56 (75.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/OlapTable.java|5|12|41.67%|[1201, 1215, 1216, 1217, 1221, 1222, 1223]|
|:large_blue_circle:|com/starrocks/planner/OlapTableSink.java|21|28|75.00%|[242, 526, 527, 559, 560, 561, 564]|
|:large_blue_circle:|com/starrocks/catalog/MaterializedIndexMeta.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/common/Config.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/ColocateTableIndex.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/alter/MaterializedViewHandler.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/alter/RollupJobV2.java|3|3|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 42 / 56 (75.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/OlapTable.java|5|12|41.67%|[1204, 1218, 1219, 1220, 1224, 1225, 1226]|
|:large_blue_circle:|com/starrocks/planner/OlapTableSink.java|21|28|75.00%|[242, 526, 527, 559, 560, 561, 564]|
|:large_blue_circle:|com/starrocks/catalog/MaterializedIndexMeta.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/common/Config.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/ColocateTableIndex.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/alter/MaterializedViewHandler.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/alter/RollupJobV2.java|3|3|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 42 / 56 (75.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/OlapTable.java|5|12|41.67%|[1204, 1218, 1219, 1220, 1224, 1225, 1226]|
|:large_blue_circle:|com/starrocks/planner/OlapTableSink.java|21|28|75.00%|[242, 526, 527, 559, 560, 561, 564]|
|:large_blue_circle:|com/starrocks/catalog/MaterializedIndexMeta.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/common/Config.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/ColocateTableIndex.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/alter/MaterializedViewHandler.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/alter/RollupJobV2.java|3|3|100.00%|[]|

**Review by Astralidea — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 41 / 49 (83.67%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/planner/OlapTableSink.java|21|28|75.00%|[242, 526, 527, 559, 560, 561, 564]|
|:large_blue_circle:|com/starrocks/catalog/OlapTable.java|5|6|83.33%|[1212]|
|:large_blue_circle:|com/starrocks/catalog/MaterializedIndexMeta.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/common/Config.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/ColocateTableIndex.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/alter/MaterializedViewHandler.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/alter/RollupJobV2.java|3|3|100.00%|[]|

**Review by Astralidea — APPROVED** [review]

**Review by murphyatwork — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Pull request merged**
