### PR TITLE
[Enhancement] Cancel queries when BE is crashed

### LINKED ISSUE #11309: Cancel queries when FE finds BE is crashed
## Enhancement
When `BE#1` is crashed, there will be two possible situations as follows:
1. Query will be cancelled soon, if another `BE#2` sends packages to `BE#1`.
2. Query will be blocked until timeout, if no one sends packages to `BE#1` and another `BE#2` wait to receive data from `BE#1`.
    
We could add a timer scheduler to check whether a BE becomes dead, and cancel queries related to it.

### PR DESCRIPTION
**Pull request by ZiheLiu**
## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Closes #11309.

## Problem Summary(Required) ：

When `BE#1` is crashed, there will be two possible situations as follows:
1. Query will be cancelled soon, if another `BE#2` sends packages to `BE#1`.
2. Query will be blocked until timeout, if no one sends packages to `BE#1` and another `BE#2` wait to receive data from `BE#1`.
    
We could add a timer scheduler to check whether a BE becomes dead, and cancel queries related to it. 

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by ZiheLiu** [comment]
run starrocks_admit_test

**Comment by ZiheLiu** [comment]
run starrocks_fe_unittest

**Comment by ZiheLiu** [comment]
run starrocks_fe_unittest

**Comment by ZiheLiu** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 15 / 56 (26.79%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/CoordinatorScheduler.java|0|33|00.00%|[30, 33, 39, 40, 41, 42, 45, 50, 52, 54, 57, 58, 59, 61, 63, 64, 66, 67, 68, 69, 70, 71, 74, 76, 77, 78, 79, 80, 81, 82, 84, 86, 87]|
|:large_blue_circle:|com/starrocks/qe/QeProcessorImpl.java|0|3|00.00%|[69, 70, 71]|
|:large_blue_circle:|com/starrocks/StarRocksFE.java|0|1|00.00%|[145]|
|:large_blue_circle:|com/starrocks/qe/Coordinator.java|13|17|76.47%|[422, 1724, 1867, 3266]|
|:large_blue_circle:|com/starrocks/qe/HDFSBackendSelector.java|2|2|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 45 / 56 (80.36%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/QeProcessorImpl.java|0|3|00.00%|[69, 70, 71]|
|:large_blue_circle:|com/starrocks/StarRocksFE.java|0|1|00.00%|[145]|
|:large_blue_circle:|com/starrocks/qe/Coordinator.java|13|17|76.47%|[422, 1724, 1867, 3266]|
|:large_blue_circle:|com/starrocks/qe/CoordinatorScheduler.java|29|32|90.62%|[61, 62, 63]|
|:large_blue_circle:|com/starrocks/system/ComputeNode.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/qe/HDFSBackendSelector.java|2|2|100.00%|[]|

**Comment by ZiheLiu** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 45 / 56 (80.36%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/QeProcessorImpl.java|0|3|00.00%|[69, 70, 71]|
|:large_blue_circle:|com/starrocks/StarRocksFE.java|0|1|00.00%|[145]|
|:large_blue_circle:|com/starrocks/qe/Coordinator.java|13|17|76.47%|[422, 1724, 1867, 3266]|
|:large_blue_circle:|com/starrocks/qe/CoordinatorMonitor.java|29|32|90.62%|[61, 62, 63]|
|:large_blue_circle:|com/starrocks/system/ComputeNode.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/qe/HDFSBackendSelector.java|2|2|100.00%|[]|

**Review by kangkaisen — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 48 / 59 (81.36%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/QeProcessorImpl.java|0|3|00.00%|[69, 70, 71]|
|:large_blue_circle:|com/starrocks/StarRocksFE.java|0|1|00.00%|[145]|
|:large_blue_circle:|com/starrocks/qe/Coordinator.java|14|18|77.78%|[422, 1725, 1868, 3267]|
|:large_blue_circle:|com/starrocks/qe/CoordinatorMonitor.java|29|32|90.62%|[61, 62, 63]|
|:large_blue_circle:|com/starrocks/common/Status.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/system/ComputeNode.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/qe/HDFSBackendSelector.java|2|2|100.00%|[]|

**Comment by ZiheLiu** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 49 / 60 (81.67%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/QeProcessorImpl.java|0|3|00.00%|[69, 70, 71]|
|:large_blue_circle:|com/starrocks/StarRocksFE.java|0|1|00.00%|[145]|
|:large_blue_circle:|com/starrocks/qe/Coordinator.java|14|18|77.78%|[422, 1725, 1868, 3267]|
|:large_blue_circle:|com/starrocks/qe/CoordinatorMonitor.java|30|33|90.91%|[61, 62, 63]|
|:large_blue_circle:|com/starrocks/common/Status.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/system/ComputeNode.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/qe/HDFSBackendSelector.java|2|2|100.00%|[]|

**Review by kangkaisen — APPROVED** [review]

**Review by murphyatwork — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Pull request merged**
