### PR TITLE
[Feature] Support trino current_catalog and current_schema function

### PR DESCRIPTION
**Pull request by macroguo-ghy**
## Why I'm doing:
https://github.com/StarRocks/starrocks/issues/40894
## What I'm doing:

Fixes #issue

## What type of PR is this:

- [ ] BugFix
- [x] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.2
  - [x] 3.1
  - [x] 3.0
  - [ ] 2.5

### CODE REVIEW

**Comment by macroguo-ghy** [comment]
@mergify rebase

**Comment by macroguo-ghy** [comment]
FE UT run timeout, I don't think it is caused by this commit

**Comment by stephen-shelby** [comment]
> FE UT run timeout, I don't think it is caused by this commit

I have rerun it.

**Review by Youngwb — APPROVED** [review]

**Review by stephen-shelby — APPROVED** [review]

**Comment by Youngwb** [comment]
@Mergify backport branch-3.2

**Comment by Youngwb** [comment]
@mergify backport branch-3.1

**Comment by Youngwb** [comment]
@mergify backport branch-3.0

**Pull request merged**
