### PR TITLE
[Feature] Support modify table property default storage medium

### LINKED ISSUE #25870: Allowing to modify the olap-table's "storage medium" property by ALTER command
Allowing to modify the olap-table's "storage medium" property by ALTER command
 
ex: ALTER TABLE   db.some_table   SET("default.storage_medium"="SSD");

### Real behavior (Required)

MySQL [db]> ALTER TABLE   db.some_table   SET("default.storage_medium"="SSD");
ERROR 1064 (HY000): Unknown table property: [default.storage_medium]

### StarRocks version (Required)

2.5.3

### PR DESCRIPTION
**Pull request by Astralidea**
Fixes #25870

## What type of PR is this:
- [ ] BugFix
- [x] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [x] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [x] 3.0
  - [x] 2.5
  - [ ] 2.4

### CODE REVIEW

**Review by ABingHuang — APPROVED** [review]

**Review by gengjun-git — APPROVED** [review]

**Comment by Astralidea** [comment]
@Mergifyio backport branch-3.1

**Comment by Astralidea** [comment]
@Mergifyio backport branch-3.0

**Comment by goldenbean** [comment]
@Astralidea Please backport this to 2.5

**Comment by Astralidea** [comment]
https://github.com/Mergifyio backport branch-3.1

**Comment by Astralidea** [comment]
> @Astralidea Please backport this to branch-2.5

It's not easy to get to 2.5. Because he relies on a log type. I'll try to check it out.

**Pull request merged**
