### PR TITLE
[Enhancement] Optimized statistics scheduling and not collecting empty tables and partitions

### PR DESCRIPTION
**Pull request by HangyuanLiu**
## What type of PR is this：
- [ ] bug
- [ ] feature
- [x] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #

### CODE REVIEW

**Review by Seaven — DISMISSED** [review]

**Comment by HangyuanLiu** [comment]
run all

**Comment by wanpengfei-git** [comment]
run all

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 21 / 38 (55.26%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/statistic/SampleStatisticsCollectJob.java|0|5|00.00%|[50, 51, 53, 54, 55]|
|:large_blue_circle:|com/starrocks/statistic/FullStatisticsCollectJob.java|0|7|00.00%|[42, 43, 45, 46, 49, 50, 51]|
|:large_blue_circle:|com/starrocks/statistic/BasicStatsMeta.java|2|3|66.67%|[113]|
|:large_blue_circle:|com/starrocks/statistic/StatisticsCollectJobFactory.java|19|23|82.61%|[82, 83, 111, 129]|

**Review by Seaven — APPROVED** [review]

**Review by Youngwb — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Pull request merged**
