### PR TITLE
[Enhancement] Enhance ShowMaterializedViews command

### LINKED ISSUE #13929: Enhance show materialized view
## Enhancement

Add several fields in `show materialized view` command:
1. `last_refresh_time`: to measure the freshness of this materialized view
2. `last_refresh_duration`: to measure the cost of refresh
3. `last_refresh_rows`: to measure the cost of refresh
4. `is_active`: whether the MV is active
5. `inactive_reason`: why this MV is not active? 

Current result:
image

### PR DESCRIPTION
**Pull request by LiShuMing**
## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #13929

- Unify `listMaterializedViews` in FEServiceImpl  and `handleShowMaterializedView` in ShowExecutor  into one table.
- Optimize `handleShowMaterializedView` method by iterating tables of the db only once.
- Enhance ShowMaterializedViews command to display last_refresh MV's detail message.



eg.
```
mysql> show materialized view;
+-------+------+---------------+--------------+-----------+-------------------------+----------------------------+-----------------------+--------------------+---------------+-----------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------+
| id    | name | database_name | refresh_type | is_active | last_refresh_start_time | last_refresh_finished_time | last_refresh_duration | last_refresh_state | inactive_code | inactive_reason | text                                                                                                                                                                                                                                                                     | rows |
+-------+------+---------------+--------------+-----------+-------------------------+----------------------------+-----------------------+--------------------+---------------+-----------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------+
| 10037 | mv0  | test          | MANUAL       | true      | 2023-02-09 13:38:13     | 2023-02-09 13:38:13        | 0                     | SUCCESS            | 0             | NULL            | CREATE MATERIALIZED VIEW `mv0`
COMMENT "MATERIALIZED_VIEW"
DISTRIBUTED BY HASH(`col1`) BUCKETS 12
REFRESH MANUAL
PROPERTIES (
"replication_num" = "1",
"storage_medium" = "HDD"
)
AS SELECT `emps`.`empid` + 1 AS `col1`
FROM `test`.`emps`
WHERE `emps`.`deptno` = 10; | 0    |
| 11001 | mv1  | test          | MANUAL       | true      |                         |                            |                       |                    |               |                 | CREATE MATERIALIZED VIEW `mv1`
COMMENT "MATERIALIZED_VIEW"
DISTRIBUTED BY HASH(`col1`) BUCKETS 12
REFRESH MANUAL
PROPERTIES (
"replication_num" = "1",
"storage_medium" = "HDD"
)
AS SELECT `emps`.`empid` + 1 AS `col1`
FROM `test`.`emps`
WHERE `emps`.`deptno` = 10; | 0    |
| 12003 | mv2  | test          | ROLLUP       | true      |                         |                            |                       |                    |               |                 | CREATE MATERIALIZED VIEW mv2 asselect name, max(deptno) as max_deptno from emps group by name                                                                                                                                                                            | 0    |
+-------+------+---------------+--------------+-----------+-------------------------+----------------------------+-----------------------+--------------------+---------------+-----------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------+
3 rows in set (0.00 sec)
```


```

mysql> show materialized view  where name='customer_mv'\G;
*************************** 1. row ***************************
                        id: 10142
                      name: customer_mv
             database_name: test
              refresh_type: MANUAL
                 is_active: true
   last_refresh_start_time: 2023-02-17 10:27:33
last_refresh_finished_time: 2023-02-17 10:27:33
     last_refresh_duration: 0
        last_refresh_state: SUCCESS
             inactive_code: 0
           inactive_reason:
                      text: CREATE MATERIALIZED VIEW `customer_mv`
COMMENT "MATERIALIZED_VIEW"
DISTRIBUTED BY HASH(`c_custkey`) BUCKETS 10
REFRESH MANUAL
PROPERTIES (
"replication_num" = "1",
"storage_medium" = "HDD"
)
AS SELECT `customer`.`c_custkey`, `customer`.`c_phone`, `customer`.`c_acctbal`, count(1) AS `c_count`, sum(`customer`.`c_acctbal`) AS `c_sum`
FROM `test`.`customer`
GROUP BY `customer`.`c_custkey`, `customer`.`c_phone`, `customer`.`c_acctbal`;
                      rows: 0
1 row in set (0.12 sec)
```


## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 64 / 104 (61.54%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/scheduler/TaskManager.java|12|33|36.36%|[505, 506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 521, 522, 523, 524, 525, 526, 527]|
|:large_blue_circle:|com/starrocks/qe/ShowExecutor.java|44|63|69.84%|[465, 469, 509, 511, 512, 513, 515, 517, 518, 519, 528, 530, 531, 572, 574, 576, 578, 580, 582]|
|:large_blue_circle:|com/starrocks/sql/ast/ShowMaterializedViewStmt.java|8|8|100.00%|[]|

**Review by murphyatwork — COMMENTED** [review]
Please update the document at the same time

**Review by murphyatwork — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 105 / 232 (45.26%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/service/FrontendServiceImpl.java|0|57|00.00%|[292, 323, 375, 399, 426, 431, 433, 434, 435, 436, 440, 441, 442, 443, 445, 448, 456, 458, 459, 460, 463, 464, 465, 466, 467, 468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480, 481, 487, 488, 489, 491, 492, 493, 494, 495, 498, 499, 500, 502, 503, 518, 519, 527, 799, 840]|
|:large_blue_circle:|com/starrocks/privilege/PrivilegeManager.java|2|7|28.57%|[1952, 1953, 1954, 1956, 1965]|
|:large_blue_circle:|com/starrocks/scheduler/TaskManager.java|12|33|36.36%|[505, 506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 521, 522, 523, 524, 525, 526, 527]|
|:large_blue_circle:|com/starrocks/qe/ShowExecutor.java|51|95|53.68%|[455, 459, 478, 528, 529, 531, 532, 533, 534, 535, 537, 539, 540, 541, 542, 543, 545, 546, 547, 548, 550, 551, 552, 553, 554, 555, 557, 558, 559, 560, 561, 562, 563, 564, 565, 567, 568, 569, 576, 578, 580, 582, 584, 586]|
|:large_blue_circle:|com/starrocks/sql/ast/ShowMaterializedViewStmt.java|32|32|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/SchemaTable.java|8|8|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 105 / 232 (45.26%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/service/FrontendServiceImpl.java|0|57|00.00%|[292, 323, 375, 399, 426, 431, 433, 434, 435, 436, 440, 441, 442, 443, 445, 448, 456, 458, 459, 460, 463, 464, 465, 466, 467, 468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480, 481, 487, 488, 489, 491, 492, 493, 494, 495, 498, 499, 500, 502, 503, 518, 519, 527, 799, 840]|
|:large_blue_circle:|com/starrocks/privilege/PrivilegeManager.java|2|7|28.57%|[1952, 1953, 1954, 1956, 1965]|
|:large_blue_circle:|com/starrocks/scheduler/TaskManager.java|12|33|36.36%|[505, 506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 521, 522, 523, 524, 525, 526, 527]|
|:large_blue_circle:|com/starrocks/qe/ShowExecutor.java|51|95|53.68%|[455, 459, 478, 528, 529, 531, 532, 533, 534, 535, 537, 539, 540, 541, 542, 543, 545, 546, 547, 548, 550, 551, 552, 553, 554, 555, 557, 558, 559, 560, 561, 562, 563, 564, 565, 567, 568, 569, 576, 578, 580, 582, 584, 586]|
|:large_blue_circle:|com/starrocks/sql/ast/ShowMaterializedViewStmt.java|32|32|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/SchemaTable.java|8|8|100.00%|[]|

**Review by ABingHuang — APPROVED** [review]
LGTM

**Review by Astralidea — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Pull request merged**
