### PR TITLE
[BugFix] Decimal precision

### LINKED ISSUE #25201: [Simple load from S3] select * from table fucntion error
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
```
 select * from table("path" = "s3://xxx/xxx/xxx/data_type_parquet_none",
                          "format" = "parquet",
                          "aws.s3.use_instance_profile" = "false",
                          "aws.s3.region" = "xxx,
                          "aws.s3.access_key"= "xxx",
                          "aws.s3.secret_key"="xxx"
                           );

select * from table("path" = "s3://xxx/xxx/xxx/xxx/xxx/000000_0",
                          "format" = "parquet",
                          "aws.s3.use_instance_profile" = "false",
                          "aws.s3.region" = "xxx",
                          "aws.s3.access_key"= "xxx",
                          "aws.s3.secret_key"="xxx"
                           );
```

image

image

use python execute query
```
import pymysql

def connec_mysql():
    # 读取数据
    conn = pymysql.connect(
        host="xxxxxxxxx",
        user="root",
        port=9030,
        passwd='',
        )

    cur = conn.cursor()
    cur.execute("show databases")
    print(cur.fetchall())
    sql = """ select * from table("path" = "s3://xxx/customer/*",
                          "format" = "parquet",
                          "aws.s3.use_instance_profile" = "false",
                          "aws.s3.region" = "xxx",
                          "aws.s3.access_key"= "xxx",
                          "aws.s3.secret_key"="xxx"
                           ) """
    cur.execute(sql)

if __name__ == '__main__':
     connec_mysql()
```

image

### Expected behavior (Required)
query successfully
### Real behavior (Required)
query failed
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
mysql> select current_version();
+-------------------+
| current_version() |
+-------------------+
| main-1980bcf      |
+-------------------+
1 row in set (0.02 sec)

### PR DESCRIPTION
**Pull request by rickif**
Fixes https://github.com/StarRocks/starrocks/issues/25201
This PR includes following changes:
1. parquet decimal type
Now, the decimal type mapping is as:

| Parquet Logical Type| Parquet Physical Type|SR Column Type |
| -- | -- | --|
| int32| decimal| decimal32|
| int64| decimal| decimal64|
| byte_array| decimal| decimal128|
| fixed_len_byte_array| decimal| decimal128|

Reference: https://github.com/apache/parquet-format/blob/master/LogicalTypes.md#decimal
2. parquet timestamp timezone
The origin `timezone_util::find_cctz_time_zone` only supports pattern `Asia/Shanghai`, `+08:00`. Now, the support of pattern `GMT+8:00` is added.

## What type of PR is this:
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 0 / 9 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/TableFunctionTable.java|0|1|00.00%|[221]|
|:large_blue_circle:|com/starrocks/catalog/ScalarType.java|0|8|00.00%|[132, 134, 136, 138, 140, 142, 146, 148]|

**Review by chaoyli — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 0 / 9 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/TableFunctionTable.java|0|1|00.00%|[236]|
|:large_blue_circle:|com/starrocks/catalog/ScalarType.java|0|8|00.00%|[132, 134, 136, 138, 140, 142, 146, 148]|

**Review by chaoyli — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 0 / 9 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/TableFunctionTable.java|0|1|00.00%|[236]|
|:large_blue_circle:|com/starrocks/catalog/ScalarType.java|0|8|00.00%|[132, 134, 136, 138, 140, 142, 146, 148]|

**Review by meegoo — APPROVED** [review]

**Review by chaoyli — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Pull request merged**
