### PR TITLE
[BugFix]Fix olap external table meta synchronization bug

### LINKED ISSUE #12367: [BUG] OLAP external table meta should not be added to tabletInvertedIndex
### Steps to reproduce the behavior (Required)
1. create an OLAP external table.
2. show a tablet of the external table.

### Expected behavior (Required)
The tablet of the external table should not exist.

### Real behavior (Required)
The tablet of the external table has been stored into TabletInvertedIndex.

### StarRocks version (Required)
 - all

### PR DESCRIPTION
**Pull request by gengjun-git**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #12367

## Problem Summary(Required) ：

The tablet of the external OLAP table should not be added to TabletInvertedIndex; it will replace the local tablet if they have the same id, which will cause some inconsistency bugs.
Besides, this PR changes the param from isRestore to updateInvertedIndex, which makes the param more visible. And there is no need to cache the OLAP external table metadata in the non-leader node, so if the current node is not a leader, do nothing.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
starrocks_be_unittest succeeded.

**Review by padmejin — DISMISSED** [review]

**Review by Astralidea — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
starrocks_be_unittest succeeded.

**Review by Astralidea — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 5 / 10 (50.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/lake/LakeTable.java|0|1|00.00%|[187]|
|:large_blue_circle:|com/starrocks/catalog/OlapTable.java|0|2|00.00%|[564, 578]|
|:large_blue_circle:|com/starrocks/catalog/ExternalOlapTable.java|0|2|00.00%|[486, 491]|
|:large_blue_circle:|com/starrocks/external/starrocks/StarRocksRepository.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/MaterializedIndex.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/LocalTablet.java|2|2|100.00%|[]|

**Review by meegoo — APPROVED** [review]

**Comment by gengjun-git** [comment]
@mergify backport branch-2.4 branch-2.3 branch-2.2

**Pull request merged**
