### PR TITLE
[BugFix] enlarge the varchar length for statistics

### LINKED ISSUE #19847: too short string length for statistics
### Steps to reproduce the behavior (Required)
```sql
MySQL root@127.1:_statistics_> desc table_statistic_v1;
+----------------+----------------+------+-------+---------+-------+
| Field          | Type           | Null | Key   | Default | Extra |
+----------------+----------------+------+-------+---------+-------+
| table_id       | bigint         | NO   | true  | <null>  |       |
| column_name    | varchar(65530) | NO   | true  | <null>  |       |
| db_id          | bigint         | NO   | true  | <null>  |       |
| table_name     | varchar(65530) | NO   | false | <null>  |       |
| db_name        | varchar(65530) | NO   | false | <null>  |       |
| row_count      | bigint         | NO   | false | <null>  |       |
| data_size      | bigint         | NO   | false | <null>  |       |
| distinct_count | bigint         | NO   | false | <null>  |       |
| null_count     | bigint         | NO   | false | <null>  |       |
| max            | varchar(65530) | NO   | false | <null>  |       |
| min            | varchar(65530) | NO   | false | <null>  |       |
| update_time    | datetime       | NO   | false | <null>  |       |
+----------------+----------------+------+-------+---------+-------+

```

`min` and `max` are both `varchar(65530)`, which is not enough to store large string.

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by murphyatwork**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #19847

## Problem Summary(Required) ：

65535 is not enough to store min/max of string value, should be enlarged.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 3.0
  - [x] 2.5
  - [x] 2.4
  - [x] 2.3

### CODE REVIEW

**Review by Seaven — DISMISSED** [review]

**Review by dirtysalt — DISMISSED** [review]

**Comment by mofeiatwork** [comment]
@Mergifyio rebase

**Review by dirtysalt — APPROVED** [review]

**Review by DorianZheng — APPROVED** [review]

**Review by kangkaisen — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.4

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.3

**Pull request merged**
