### PR TITLE
[BugFix] Avoid join reorder cost too much time at greedy algorithm stage

### PR DESCRIPTION
**Pull request by Youngwb**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes https://github.com/StarRocks/StarRocksBenchmark/issues/236

## Problem Summary(Required) ：

At greedy join reorder, SR will try to generate bushy tree (JoinReorderGreedy::searchBushyJoinOrders),  in this method, it would explore a lot of  plan which costs too much time. eg :
image

There are so many groups start from level 4 join order, it is generated by searchBushyJoinOrders.
In order to reduce search bushy join time, we will not use use all right groupinfo to generate bushy tree, just choose the bset right groupinfos. 

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 5 / 5 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/join/JoinReorderGreedy.java|5|5|100.00%|[]|

**Review by kangkaisen — APPROVED** [review]

**Review by dirtysalt — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wangruin** [comment]
run starrocks_admit_test

**Comment by Youngwb** [comment]
run starrocks_admit_test

**Pull request merged**
