### PR TITLE
[Enhancement] rename a few starmgr related configuration

### PR DESCRIPTION
**Pull request by kevincai**
* change starmgr related name to `cloud_native`
* disable separate starmgr configuration, always use builtin starmgr server

## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [X] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [X] I have checked the version labels which the pr will be auto backported to target branch
  - [X] 3.0
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Review by sduzh — DISMISSED** [review]

**Review by starrocks-xupeng — DISMISSED** [review]

**Review by tracymacding — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 31 / 39 (79.49%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/lake/StarOSAgent.java|1|4|25.00%|[103, 112, 113]|
|:large_blue_circle:|com/starrocks/staros/StarMgrServer.java|16|21|76.19%|[149, 150, 151, 152, 153]|
|:large_blue_circle:|com/starrocks/common/Config.java|14|14|100.00%|[]|

**Review by sduzh — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 29 / 36 (80.56%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/lake/StarOSAgent.java|1|4|25.00%|[103, 112, 113]|
|:large_blue_circle:|com/starrocks/staros/StarMgrServer.java|16|20|80.00%|[149, 150, 151, 152]|
|:large_blue_circle:|com/starrocks/common/Config.java|12|12|100.00%|[]|

**Review by sduzh — APPROVED** [review]

**Review by starrocks-xupeng — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by wyb — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Pull request merged**
