### PR TITLE
[Feature] Alembic support

### LINKED ISSUE #52580: Alembic support
- [x] https://github.com/StarRocks/starrocks/pull/52581
## Feature request

**Is your feature request related to a problem? Please describe.**
I need a tool for object management in Starrocks database and migrations.

**Describe the solution you'd like**
Alembic is defacto standard database migration tool in Python.
I'd like to be able to use Alembic with Starrocks.

### PR DESCRIPTION
**Pull request by maver1ck**
## Why I'm doing:

Adding Alembic support for Starrocks dialect.
This depends on: https://github.com/sqlalchemy/alembic/pull/1563

## What I'm doing:

Fixes [#issue](https://github.com/StarRocks/starrocks/issues/52580)

## What type of PR is this:

- [ ] BugFix
- [x] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 3.3
  - [ ] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Comment by maver1ck** [comment]
https://github.com/sqlalchemy/alembic/pull/1563 was merge so this PR is ready to review.

**Comment by maver1ck** [comment]
@miomiocat @Astralidea 
Any chance for review ?

**Review by Astralidea — APPROVED** [review]

**Comment by maver1ck** [comment]
Ping @miomiocat

**Review by miomiocat — APPROVED** [review]

**Comment by jaogoy** [comment]
@maver1ck Hi, Maciej, I've noticed that you have impelemented something about SQLAlchemy and Alembic in StarRocks. Does Alembic support StarRocks now?
I've installed sqlalchemy/starrocks, but I can't use it in Alembic, it reports:
```
  File ".../alembic/alembic/ddl/impl.py", line 134, in get_by_dialect
    return _impls[dialect.name]
KeyError: 'starrocks'
```
Do you have any information to share about how to use Alembic with starrocks?
Thank you very much.

**Pull request merged**
