### PR TITLE
[Cherrypick] Fix crash of sha2 function with null parameter

### PR DESCRIPTION
**Pull request by murphyatwork**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] others

## Problem Summary(Required) ：
Cherrypicked from #4217.

Fix sha2 function crash on null parameter .

### CODE REVIEW

**Comment by mofeiatwork** [comment]
run starrocks_fe_unittest

**Comment by mofeiatwork** [comment]
run starrocks_fe_unittest

**Comment by mofeiatwork** [comment]
@Mergify hello?

**Comment by mofeiatwork** [comment]
@Mergifyio update

**Comment by mofeiatwork** [comment]
run starrocks_fe_unittest

**Comment by mofeiatwork** [comment]
run starrocks_fe_unittest

**Comment by mofeiatwork** [comment]
run starrocks_fe_unittest

**Review by kangkaisen — APPROVED** [review]

**Pull request merged**
