### PR TITLE
[BugFix] Fix wrong subfields prune for Array type

### LINKED ISSUE #27345: ERROR 1064 (HY000): setSelectedField() is not implemented for type varchar
### Steps to reproduce the behavior (Required)
```
MySQL [(none)]> SELECT str_to_map('age=18&sex=1&gender=1','&','=')['age'] AS age, str_to_map('age=18&sex=1&gender=1','&', '=')['sex'] AS sex;
ERROR 1064 (HY000): setSelectedField() is not implemented for type varchar
```

### Expected behavior (Required)
Works well.
### Real behavior (Required)
ERROR 1064 (HY000): setSelectedField() is not implemented for type varchar

### StarRocks version (Required)
 Latest main branch

### PR DESCRIPTION
**Pull request by ucasfl**
Fixes #27345.

## What type of PR is this:
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [x] 3.0
  - [x] 2.5
  - [ ] 2.4

### CODE REVIEW

**Review by Seaven — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/tree/PruneComplexTypeUtil.java|2|2|100.00%|[]|

**Review by kangkaisen — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
