### PR TITLE
[Enhancement] sync column comment when manually executing refresh external table

### PR DESCRIPTION
**Pull request by stephen-shelby**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

### CODE REVIEW

**Review by DorianZheng — DISMISSED** [review]

**Comment by stephen-shelby** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 10 / 19 (52.63%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/HiveTable.java|0|5|00.00%|[188, 189, 190, 191, 193]|
|:large_blue_circle:|com/starrocks/connector/hive/CacheUpdateProcessor.java|0|1|00.00%|[102]|
|:large_blue_circle:|com/starrocks/connector/ColumnTypeConverter.java|10|13|76.92%|[476, 480, 484]|

**Comment by stephen-shelby** [comment]
run starrocks_admit_test

**Review by gengjun-git — APPROVED** [review]

**Review by Youngwb — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by stephen-shelby** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
