### PR TITLE
[BugFix] control running_queries via RAII (backport #13919)

### PR DESCRIPTION
**Pull request by ZiheLiu**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Problem Summary(Required) ：

This is cherry-picked from #13919.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 2.5
  - [x] 2.4
  - [x] 2.3
  - [ ] 2.2

### CODE REVIEW

**Review by wanpengfei-git — APPROVED** [review]

**Comment by ZiheLiu** [comment]
run starrocks_fe_unittest

**Comment by ZiheLiu** [comment]
run starrocks_be_unittest

**Comment by ZiheLiu** [comment]
run starrocks_clang-tidy

**Comment by ZiheLiu** [comment]
run starrocks_be_unittest

**Comment by ZiheLiu** [comment]
run starrocks_be_unittest

**Review by murphyatwork — APPROVED** [review]

**Pull request merged**
