### PR TITLE
[Enhancement] Some optimization for dla datacache.

### PR DESCRIPTION
**Pull request by GavinMar**
Some optimization for dla datacache:
1. Rename `block_cache` to `datacache`.
2. Support time-based cache adaptor.
3. Support parquet footercache.

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [x] Yes, this PR will result in a change in behavior.
- [ ] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [ ] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 6 / 6 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/SessionVariable.java|6|6|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 129 / 169 (76.33%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/storage/options.cpp|0|3|00.00%|[163, 186, 187]|
|:large_blue_circle:|src/connector/hive_connector.cpp|17|31|54.84%|[94, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 330, 534]|
|:large_blue_circle:|src/exec/hdfs_scanner.cpp|7|12|58.33%|[302, 304, 305, 306, 307]|
|:large_blue_circle:|src/io/cache_input_stream.cpp|17|27|62.96%|[117, 118, 119, 120, 121, 154, 155, 159, 161, 172]|
|:large_blue_circle:|src/block_cache/block_cache.cpp|10|15|66.67%|[80, 81, 89, 105, 137]|
|:large_blue_circle:|src/block_cache/starcache_wrapper.cpp|12|15|80.00%|[58, 60, 61]|
|:large_blue_circle:|src/block_cache/starcache_wrapper.h|2|2|100.00%|[]|
|:large_blue_circle:|src/exec/hdfs_scanner_parquet.cpp|12|12|100.00%|[]|
|:large_blue_circle:|src/formats/parquet/file_reader.cpp|46|46|100.00%|[]|
|:large_blue_circle:|src/formats/parquet/metadata.cpp|1|1|100.00%|[]|
|:large_blue_circle:|src/common/status.h|1|1|100.00%|[]|
|:large_blue_circle:|src/formats/parquet/meta_helper.h|4|4|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 129 / 169 (76.33%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/storage/options.cpp|0|3|00.00%|[163, 186, 187]|
|:large_blue_circle:|src/connector/hive_connector.cpp|17|31|54.84%|[94, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 330, 534]|
|:large_blue_circle:|src/exec/hdfs_scanner.cpp|7|12|58.33%|[302, 304, 305, 306, 307]|
|:large_blue_circle:|src/io/cache_input_stream.cpp|17|27|62.96%|[117, 118, 119, 120, 121, 154, 155, 159, 161, 172]|
|:large_blue_circle:|src/block_cache/block_cache.cpp|10|15|66.67%|[80, 81, 89, 105, 137]|
|:large_blue_circle:|src/block_cache/starcache_wrapper.cpp|12|15|80.00%|[58, 60, 61]|
|:large_blue_circle:|src/block_cache/starcache_wrapper.h|2|2|100.00%|[]|
|:large_blue_circle:|src/exec/hdfs_scanner_parquet.cpp|12|12|100.00%|[]|
|:large_blue_circle:|src/formats/parquet/file_reader.cpp|46|46|100.00%|[]|
|:large_blue_circle:|src/formats/parquet/metadata.cpp|1|1|100.00%|[]|
|:large_blue_circle:|src/common/status.h|1|1|100.00%|[]|
|:large_blue_circle:|src/formats/parquet/meta_helper.h|4|4|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 129 / 169 (76.33%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/storage/options.cpp|0|3|00.00%|[163, 186, 187]|
|:large_blue_circle:|src/connector/hive_connector.cpp|17|31|54.84%|[94, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 330, 534]|
|:large_blue_circle:|src/exec/hdfs_scanner.cpp|7|12|58.33%|[302, 304, 305, 306, 307]|
|:large_blue_circle:|src/io/cache_input_stream.cpp|17|27|62.96%|[117, 118, 119, 120, 121, 154, 155, 159, 161, 172]|
|:large_blue_circle:|src/block_cache/block_cache.cpp|10|15|66.67%|[80, 81, 89, 105, 137]|
|:large_blue_circle:|src/block_cache/starcache_wrapper.cpp|12|15|80.00%|[58, 60, 61]|
|:large_blue_circle:|src/block_cache/starcache_wrapper.h|2|2|100.00%|[]|
|:large_blue_circle:|src/exec/hdfs_scanner_parquet.cpp|12|12|100.00%|[]|
|:large_blue_circle:|src/formats/parquet/file_reader.cpp|46|46|100.00%|[]|
|:large_blue_circle:|src/formats/parquet/metadata.cpp|1|1|100.00%|[]|
|:large_blue_circle:|src/common/status.h|1|1|100.00%|[]|
|:large_blue_circle:|src/formats/parquet/meta_helper.h|4|4|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 6 / 6 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/SessionVariable.java|6|6|100.00%|[]|

**Review by Youngwb — APPROVED** [review]

**Pull request merged**
