### PR TITLE
[Enhancement] Log version info when adding clone task for VERSION_INCOMPLETE

### PR DESCRIPTION
**Pull request by nshangyiming**
Fixes SR-19200

## What type of PR is this:
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [x] 3.0
  - [x] 2.5
  - [ ] 2.4

### CODE REVIEW

**Review by Astralidea — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 29 / 41 (70.73%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/clone/TabletScheduler.java|11|21|52.38%|[223, 778, 922, 923, 925, 926, 1106, 1161, 1605, 1722]|
|:large_blue_circle:|com/starrocks/clone/TabletSchedCtx.java|8|10|80.00%|[641, 988]|
|:large_blue_circle:|com/starrocks/transaction/OlapTableTxnStateListener.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/Partition.java|6|6|100.00%|[]|
|:large_blue_circle:|com/starrocks/transaction/OlapTableTxnLogApplier.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/transaction/DatabaseTransactionMgr.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/system/Backend.java|1|1|100.00%|[]|

**Review by gengjun-git — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 29 / 41 (70.73%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/clone/TabletScheduler.java|11|21|52.38%|[223, 778, 922, 923, 925, 926, 1106, 1161, 1605, 1722]|
|:large_blue_circle:|com/starrocks/clone/TabletSchedCtx.java|8|10|80.00%|[641, 988]|
|:large_blue_circle:|com/starrocks/transaction/OlapTableTxnStateListener.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/Partition.java|6|6|100.00%|[]|
|:large_blue_circle:|com/starrocks/transaction/OlapTableTxnLogApplier.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/transaction/DatabaseTransactionMgr.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/system/Backend.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 43 / 47 (91.49%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/clone/TabletScheduler.java|23|26|88.46%|[222, 226, 1748]|
|:large_blue_circle:|com/starrocks/clone/TabletSchedCtx.java|9|10|90.00%|[641]|
|:large_blue_circle:|com/starrocks/catalog/Partition.java|8|8|100.00%|[]|
|:large_blue_circle:|com/starrocks/transaction/OlapTableTxnLogApplier.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/transaction/DatabaseTransactionMgr.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/system/Backend.java|1|1|100.00%|[]|

**Review by gengjun-git — APPROVED** [review]

**Review by Astralidea — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
