### PR TITLE
[Doc] Update Import_and_query.md

### PR DESCRIPTION
**Pull request by alberttwong**
missing SQL to use the correct database before inserting.

## What type of PR is this：
- [ ] Doc

### CODE REVIEW

**Comment by EsoragotoSpirit** [comment]
Thank you @alberttwong for your contribution. Would you mind adding the sign-off message to your commit by using  `git commit -s`?

**Review by imay — APPROVED** [review]

**Comment by EsoragotoSpirit** [comment]
@mergify backport branch-2.3 branch-2.4 branch-2.5 branch-3.0

**Comment by EsoragotoSpirit** [comment]
@mergify backport branch-2.3 branch-2.4 branch-2.5 branch-3.0

**Comment by EsoragotoSpirit** [comment]
@mergify backport branch-3.0

**Comment by EsoragotoSpirit** [comment]
@mergify backport branch-3.0

**Pull request merged**
