### PR TITLE
[Enhancement] Add columns name message for generated and auto columns

### PR DESCRIPTION
**Pull request by xuzifu666**
Fixes #issue

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Review by satanson — DISMISSED** [review]

**Comment by xuzifu666** [comment]
cc @kangkaisen @silverbullet233 @fzhedu https://github.com/StarRocks/starrocks/pull/34135 change to this pr , thanks

**Review by kangkaisen — DISMISSED** [review]

**Comment by silverbullet233** [comment]
FE Cover Checker failed, could you add more test cases to cover your change?

**Comment by xuzifu666** [comment]
> FE Cover Checker failed, could you add more test cases to cover your change?

ok，I would add more testcase @silverbullet233

**Comment by xuzifu666** [comment]
@silverbullet233 all fe ut cover had passed

**Review by silverbullet233 — APPROVED** [review]

**Review by satanson — APPROVED** [review]

**Review by kangkaisen — APPROVED** [review]

**Pull request merged**
