### PR TITLE
[Enhancement] Extend interval type for 'date_trunc', 'days_add', 'time_slice'

### PR DESCRIPTION
**Pull request by liuyehcf**
Support MILLI SECOND AND MICRO SECOND type interval for function `date_trunc`/`adddate`/`time_slice`

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.2
  - [x] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Review by kangkaisen — APPROVED** [review]

**Review by silverbullet233 — APPROVED** [review]

**Comment by liuyehcf** [comment]
@Mergifyio backport branch-3.2

**Comment by silverbullet233** [comment]
@mergify backport branch-3.1

**Comment by liuyehcf** [comment]
version >= 3.1.7 or 3.2.1

**Comment by liuyehcf** [comment]
these functions also supported. 
* adddate
* date_add
* subdate
* date_sub

**Pull request merged**
