### PR TITLE
[Refactor] Remove useless analyze method and mini code format in RowDelimiter

### PR DESCRIPTION
**Pull request by HangyuanLiu**
## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [x] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

### CODE REVIEW

**Comment by HangyuanLiu** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 16 / 21 (76.19%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/task/StreamLoadTask.java|0|2|00.00%|[207, 210]|
|:large_blue_circle:|com/starrocks/analysis/Delimiter.java|2|4|50.00%|[31, 38]|
|:large_blue_circle:|com/starrocks/sql/LoadPlanner.java|2|3|66.67%|[156]|
|:large_blue_circle:|com/starrocks/sql/ast/ColumnSeparator.java|7|7|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/PrivilegeCheckerV2.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/FunctionCallExpr.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/RowDelimiter.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/FloatLiteral.java|1|1|100.00%|[]|

**Review by kangkaisen — DISMISSED** [review]

**Review by murphyatwork — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by Seaven — DISMISSED** [review]

**Comment by HangyuanLiu** [comment]
run starrocks_fe_unittest

**Comment by HangyuanLiu** [comment]
run starrocks_fe_unittest

**Comment by HangyuanLiu** [comment]
run starrocks_fe_unittest

**Comment by HangyuanLiu** [comment]
run starrocks_fe_unittest

**Comment by HangyuanLiu** [comment]
run all

**Comment by HangyuanLiu** [comment]
run starrocks_fe_unittest

**Comment by HangyuanLiu** [comment]
run starrocks_admit_test

**Comment by HangyuanLiu** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 15 / 22 (68.18%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/load/streamload/StreamLoadInfo.java|0|4|00.00%|[200, 203, 274, 277]|
|:large_blue_circle:|com/starrocks/analysis/Delimiter.java|2|4|50.00%|[31, 38]|
|:large_blue_circle:|com/starrocks/sql/LoadPlanner.java|2|3|66.67%|[185]|
|:large_blue_circle:|com/starrocks/sql/ast/ColumnSeparator.java|7|7|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/FunctionCallExpr.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/RowDelimiter.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/FloatLiteral.java|1|1|100.00%|[]|

**Review by kangkaisen — APPROVED** [review]

**Review by murphyatwork — APPROVED** [review]

**Pull request merged**
