### PR TITLE
[BugFix] Cherry-Pick ORC-1304 bug fix from apache-orc

### PR DESCRIPTION
**Pull request by Smith-Cruise**
Cherry-Pick from https://github.com/apache/orc/pull/1299

I didn't cp ut because many commits are missed in the middle, it will cause ut compilation to fail.

**We will refactor orc later, so this is just a temporary solution.**

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 4 / 16 (25.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/formats/orc/apache-orc/c++/src/RLEv1.cc|0|7|00.00%|[190, 192, 197, 199, 201, 205, 212]|
|:large_blue_circle:|src/formats/orc/apache-orc/c++/src/ByteRLE.cc|4|9|44.44%|[382, 384, 386, 394, 395]|

**Review by dirtysalt — DISMISSED** [review]

**Review by GavinMar — APPROVED** [review]

**Review by dirtysalt — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 6 / 18 (33.33%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/formats/orc/orc_chunk_reader.cpp|0|1|00.00%|[512]|
|:large_blue_circle:|src/formats/orc/apache-orc/c++/src/RLEv1.cc|0|10|00.00%|[190, 191, 192, 193, 194, 195, 196, 200, 201, 208]|
|:large_blue_circle:|src/formats/orc/apache-orc/c++/src/ByteRLE.cc|6|7|85.71%|[391]|

**Review by Youngwb — APPROVED** [review]

**Comment by Smith-Cruise** [comment]
@Mergify backport branch-3.1 branch-3.0 branch-2.5

**Pull request merged**
