### PR TITLE
[BugFix] Forbid Async Mv create HLL/BITMAP/PERCENTILE type

### LINKED ISSUE #14223: [materialized view]be crash when select from mv
### Steps to reproduce the behavior (Required)
```
CREATE TABLE `duplicate_table_with_null_partition` (
                    `k1` date,
                    `k2` datetime,
                    `k3` char(20),
                    `k4` varchar(20),
                    `k5` boolean,
                    `k6` tinyint,
                    `k7` smallint,
                    `k8` int,
                    `k9` bigint,
                    `k10` largeint,
                    `k11` float,
                    `k12` double,
                    `k13` decimal(27,9),
                    `k14` array<int>,
                    `k15` json
                    ) ENGINE=OLAP
                    DUPLICATE KEY(`k1`, `k2`, `k3`, `k4`, `k5`)
                    COMMENT "OLAP"
                    PARTITION BY RANGE(`k1`)
                    (
                    PARTITION `p202006` VALUES LESS THAN ("2020-07-01"),
                    PARTITION `p202007` VALUES LESS THAN ("2020-08-01"),
                    PARTITION `p202008` VALUES LESS THAN ("2020-09-01")
                    )
                    DISTRIBUTED BY HASH(`k1`, `k2`, `k3`, `k4`, `k5`) BUCKETS 3
                    PROPERTIES (
                    "replication_num" = "3",
                    "storage_format" = "v2"
                    );
INSERT INTO duplicate_table_with_null_partition VALUES 
                ("2020-06-23","2020-06-23 00:00:00","beijing","haidian",-1,-128,-32768,-2147483648,-9223372036854775808,-18446744073709551616,-3.1,-3.14,-3.141,[1,1,1],parse_json('{"a": 1, "b": true}')),
                ("2020-07-23","2020-07-23 00:00:00","shanghai","pudong",0,0,0,0,0,0,-3.1,-3.14,-3.141,[2,2,2],parse_json('{"a": 1, "b": true}')),
                ("2020-07-23","2020-07-24 00:00:00","shanghai1","pudong1",1,1,1,1,1,1,-3.2,-3.44,-3.441,[3,3,3],parse_json('{"a": 1, "b": true}')),
                ("2020-08-23","2020-08-23 00:00:00","xian","zhonglou",1,127,32767,2147483647,9223372036854775807,18446744073709551615,-3.1,-3.14,-3.141,[3,3,3],parse_json('{"a": 1, "b": true}')),
                (NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
CREATE MATERIALIZED VIEW mv1
                 PARTITION BY k1
                 DISTRIBUTED BY HASH(k1) BUCKETS 10
                 REFRESH ASYNC 
                 AS SELECT k1, count(k2) as count_datetime, min(k3) as min_char, max(k4) as max_varchar, 
                 sum(k5) as sum_boolean, avg(k6) as avg_tinyint, 
                 PERCENTILE_UNION(percentile_hash(k7)) as percentile_smallint,
                 HLL_UNION(hll_hash(k8)) as hll_int, BITMAP_UNION(to_bitmap(k9)) as bitmap_big_int, 
                 sum(distinct k10) as sum_largeint, count(distinct k11) as count_float, 
                 max(distinct k12) as max_double, min(distinct k13) as min_decimal
                 FROM duplicate_table_with_null_partition GROUP BY k1 ORDER BY k1;
```
wait a minute
### Real behavior (Required)
```
*** Check failure stack trace: ***
    @          0x577d3fd  google::LogMessage::Fail()
    @          0x577d3fd  google::LogMessage::Fail()
    @          0x577f86f  google::LogMessage::SendToLog()
    @          0x577f86f  google::LogMessage::SendToLog()
    @          0x577cf4e  google::LogMessage::Flush()
    @          0x577cf4e  google::LogMessage::Flush()
    @          0x577fe79  google::LogMessageFatal::~LogMessageFatal()
    @          0x425bdba  _ZN9starrocks33field_type_dispatch_zonemap_indexINS_25ZoneMapIndexWriterBuilderEJPNS_5FieldEEEEDaNS_9FieldTypeET_DpT0_.isra.0
    @          0x577fe79  google::LogMessageFatal::~LogMessageFatal()
    @          0x425bdba  _ZN9starrocks33field_type_dispatch_zonemap_indexINS_25ZoneMapIndexWriterBuilderEJPNS_5FieldEEEEDaNS_9FieldTypeET_DpT0_.isra.0
    @          0x425d6e5  starrocks::ZoneMapIndexWriter::create()
    @          0x425d6e5  starrocks::ZoneMapIndexWriter::create()
    @          0x41e5744  starrocks::ScalarColumnWriter::init()
    @          0x41e5744  starrocks::ScalarColumnWriter::init()
    @          0x3e52e2b  starrocks::SegmentWriter::init()
    @          0x3e52e2b  starrocks::SegmentWriter::init()
    @          0x3e53d81  starrocks::SegmentWriter::init()
    @          0x445529f  starrocks::HorizontalRowsetWriter::_create_segment_writer()
    @          0x3e53d81  starrocks::SegmentWriter::init()
    @          0x4456e16  starrocks::HorizontalRowsetWriter::_flush_chunk()
    @          0x445529f  starrocks::HorizontalRowsetWriter::_create_segment_writer()
    @          0x44570a2  starrocks::HorizontalRowsetWriter::flush_chunk()
    @          0x4456e16  starrocks::HorizontalRowsetWriter::_flush_chunk()
    @          0x44570a2  starrocks::HorizontalRowsetWriter::flush_chunk()
    @          0x3eebc52  starrocks::vectorized::MemTableRowsetWriterSink::flush_chunk()
    @          0x3f156e4  starrocks::vectorized::MemTable::flush()
    @          0x3eebc52  starrocks::vectorized::MemTableRowsetWriterSink::flush_chunk()
    @          0x3f8cadc  starrocks::FlushToken::_flush_memtable()
    @          0x3f156e4  starrocks::vectorized::MemTable::flush()
    @          0x3f8d5f0  starrocks::MemtableFlushTask::run()
    @          0x3f8cadc  starrocks::FlushToken::_flush_memtable()
    @          0x4635345  starrocks::ThreadPool::dispatch_thread()
    @          0x3f8d5f0  starrocks::MemtableFlushTask::run()
    @          0x4635345  starrocks::ThreadPool::dispatch_thread()
    @          0x463065a  starrocks::Thread::supervise_thread()
    @          0x463065a  starrocks::Thread::supervise_thread()
    @     0x7ff579d25ea5  start_thread
    @     0x7ff579d25ea5  start_thread
    @     0x7ff56f40bb0d  __clone
    @     0x7ff56f40bb0d  __clone
    @              (nil)  (unknown)
    @              (nil)  (unknown)
```
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
+----------------------------+
| current_version()          |
+----------------------------+
| BRANCH-2.5-RELEASE 9e39279 |
+----------------------------+
```

### PR DESCRIPTION
**Pull request by Astralidea**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #14223

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [x] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 1 / 2 (50.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/AnalyzerUtils.java|1|2|50.00%|[492]|

**Review by ABingHuang — APPROVED** [review]
LGTM

**Review by gengjun-git — APPROVED** [review]

**Review by Youngwb — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Comment by Astralidea** [comment]
https://github.com/Mergifyio backport branch-2.4

**Pull request merged**
