### PR TITLE
[Enhancement] Set the default `block_cache_checksum_enable` to `false` to avoid the checksum overhead

### PR DESCRIPTION
**Pull request by GavinMar**
## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

We change the default `block_cache_checksum_enable` to `false` to avoid the checksum overhead because data usually be verified on other levels in many situations.
Also, this PR remove the `shutdown` procedure when block cache stop, because it is only useful for shared memory cache.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 3.0
  - [x] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Comment by GavinMar** [comment]
run starrocks_admit_test

**Comment by GavinMar** [comment]
run starrocks_admit_test

**Comment by GavinMar** [comment]
run starrocks_clang-format

**Review by dirtysalt — APPROVED** [review]

**Review by stephen-shelby — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
