### PR TITLE
[Enhancement] audit the mv usage

### LINKED ISSUE #31150: Record MV info into audit log
## Enhancement

To analyze the usage of materialized view, we should:
1. record the mv usage (candidates, matched) into audit log
    1. `CandidateMVs`: candidate materialized views for query before optimization
    2. `HitMVs`:  chosen materialized views after optimizaiton
3. display the mv usage in query plan and query profile
    1. Query plan: print `MaterializedView: true` in OlapScan node
    2. Query profile: print `HitMaterializedViews` if the query hit any materialized views

### PR DESCRIPTION
**Pull request by murphyatwork**
Fixes #31150

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.2
  - [x] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 37 / 42 (88.10%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/StmtExecutor.java|0|3|00.00%|[318, 319, 320]|
|:large_blue_circle:|com/starrocks/sql/optimizer/validate/MVRewriteValidator.java|12|13|92.31%|[45]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/MvUtils.java|13|14|92.86%|[170]|
|:large_blue_circle:|com/starrocks/sql/optimizer/Optimizer.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/qe/AuditLogBuilder.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/OlapScanNode.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/plugin/AuditEvent.java|5|5|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/Explain.java|2|2|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by satanson — APPROVED** [review]

**Review by ABingHuang — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Pull request merged**
