### PR TITLE
[BugFix] Fix/Unify batch create week partition logical

### LINKED ISSUE #17128: A range is missing when creating a week partition
### Steps to reproduce the behavior (Required)
CREATE TABLE site_access(
event_day DATE,
site_id INT DEFAULT '10',
city_code VARCHAR(100),
user_name VARCHAR(32) DEFAULT '',
pv BIGINT DEFAULT '0'
)
DUPLICATE KEY(event_day, site_id, city_code, user_name)
PARTITION BY RANGE(`event_day`)
(START ("2022-05-01") END ("2023-01-23") EVERY (INTERVAL 1 WEEK))
DISTRIBUTED BY HASH(`event_day`) BUCKETS 4 
PROPERTIES (
"replication_num" = "1",
"dynamic_partition.enable" = "true",
"dynamic_partition.time_unit" = "WEEK",
"dynamic_partition.time_zone" = "Asia/Shanghai",
"dynamic_partition.start" = "-2147483648",
"dynamic_partition.end" = "2",
"dynamic_partition.prefix" = "p",
"dynamic_partition.buckets" = "4",
"in_memory" = "false",
"storage_format" = "DEFAULT"
);

### Expected behavior (Required)
CREATE TABLE `site_access` (
  `event_day` date NULL COMMENT "",
  `site_id` int(11) NULL DEFAULT "10" COMMENT "",
  `city_code` varchar(100) NULL COMMENT "",
  `user_name` varchar(32) NULL DEFAULT "" COMMENT "",
  `pv` bigint(20) NULL DEFAULT "0" COMMENT ""
) ENGINE=OLAP 
DUPLICATE KEY(`event_day`, `site_id`, `city_code`, `user_name`)
COMMENT "OLAP"
PARTITION BY RANGE(`event_day`)
(PARTITION p2022_18 VALUES [("2022-05-01"), ("2022-05-02")),
PARTITION p2022_19 VALUES [("2022-05-02"), ("2022-05-09")),
PARTITION p2022_20 VALUES [("2022-05-09"), ("2022-05-16")),
PARTITION p2022_21 VALUES [("2022-05-16"), ("2022-05-23")),
PARTITION p2022_22 VALUES [("2022-05-23"), ("2022-05-30")),
PARTITION p2022_23 VALUES [("2022-05-30"), ("2022-06-06")),
PARTITION p2022_24 VALUES [("2022-06-06"), ("2022-06-13")),
PARTITION p2022_25 VALUES [("2022-06-13"), ("2022-06-20")),
PARTITION p2022_26 VALUES [("2022-06-20"), ("2022-06-27")),
PARTITION p2022_27 VALUES [("2022-06-27"), ("2022-07-04")),
PARTITION p2022_28 VALUES [("2022-07-04"), ("2022-07-11")),
PARTITION p2022_29 VALUES [("2022-07-11"), ("2022-07-18")),
PARTITION p2022_30 VALUES [("2022-07-18"), ("2022-07-25")),
PARTITION p2022_31 VALUES [("2022-07-25"), ("2022-08-01")),
PARTITION p2022_32 VALUES [("2022-08-01"), ("2022-08-08")),
PARTITION p2022_33 VALUES [("2022-08-08"), ("2022-08-15")),
PARTITION p2022_34 VALUES [("2022-08-15"), ("2022-08-22")),
PARTITION p2022_35 VALUES [("2022-08-22"), ("2022-08-29")),
PARTITION p2022_36 VALUES [("2022-08-29"), ("2022-09-05")),
PARTITION p2022_37 VALUES [("2022-09-05"), ("2022-09-12")),
PARTITION p2022_38 VALUES [("2022-09-12"), ("2022-09-19")),
PARTITION p2022_39 VALUES [("2022-09-19"), ("2022-09-26")),
PARTITION p2022_40 VALUES [("2022-09-26"), ("2022-10-03")),
PARTITION p2022_41 VALUES [("2022-10-03"), ("2022-10-10")),
PARTITION p2022_42 VALUES [("2022-10-10"), ("2022-10-17")),
PARTITION p2022_43 VALUES [("2022-10-17"), ("2022-10-24")),
PARTITION p2022_44 VALUES [("2022-10-24"), ("2022-10-31")),
PARTITION p2022_45 VALUES [("2022-10-31"), ("2022-11-07")),
PARTITION p2022_46 VALUES [("2022-11-07"), ("2022-11-14")),
PARTITION p2022_47 VALUES [("2022-11-14"), ("2022-11-21")),
PARTITION p2022_48 VALUES [("2022-11-21"), ("2022-11-28")),
PARTITION p2022_49 VALUES [("2022-11-28"), ("2022-12-05")),
PARTITION p2022_50 VALUES [("2022-12-05"), ("2022-12-12")),
PARTITION p2022_51 VALUES [("2022-12-12"), ("2022-12-19")),
PARTITION p2022_52 VALUES [("2022-12-19"), ("2022-12-26")),
PARTITION p2022_53 VALUES [("2022-12-26"), ("2023-01-02")),
PARTITION p2023_01 VALUES [("2023-01-02"), ("2023-01-09")),
PARTITION p2023_02 VALUES [("2023-01-09"), ("2023-01-16")),
PARTITION p2023_03 VALUES [("2023-01-16"), ("2023-01-23")),
PARTITION p2023_05 VALUES [("2023-01-30"), ("2023-02-06")),
PARTITION p2023_06 VALUES [("2023-02-06"), ("2023-02-13")),
PARTITION p2023_07 VALUES [("2023-02-13"), ("2023-02-20")))
DISTRIBUTED BY HASH(`event_day`) BUCKETS 4 
PROPERTIES (
"replication_num" = "1",
"dynamic_partition.enable" = "true",
"dynamic_partition.time_unit" = "WEEK",
"dynamic_partition.time_zone" = "Asia/Shanghai",
"dynamic_partition.start" = "-2147483648",
"dynamic_partition.end" = "2",
"dynamic_partition.prefix" = "p",
"dynamic_partition.buckets" = "4",
"dynamic_partition.start_day_of_week" = "1",
"in_memory" = "false",
"storage_format" = "DEFAULT",
"enable_persistent_index" = "false",
"replicated_storage" = "true",
"compression" = "LZ4"
);
### Real behavior (Required)
CREATE TABLE `site_access` (
  `event_day` date NULL COMMENT "",
  `site_id` int(11) NULL DEFAULT "10" COMMENT "",
  `city_code` varchar(100) NULL COMMENT "",
  `user_name` varchar(32) NULL DEFAULT "" COMMENT "",
  `pv` bigint(20) NULL DEFAULT "0" COMMENT ""
) ENGINE=OLAP 
DUPLICATE KEY(`event_day`, `site_id`, `city_code`, `user_name`)
COMMENT "OLAP"
PARTITION BY RANGE(`event_day`)
(PARTITION p2022_18 VALUES [("2022-05-01"), ("2022-05-02")),
PARTITION p2022_19 VALUES [("2022-05-02"), ("2022-05-09")),
PARTITION p2022_20 VALUES [("2022-05-09"), ("2022-05-16")),
PARTITION p2022_21 VALUES [("2022-05-16"), ("2022-05-23")),
PARTITION p2022_22 VALUES [("2022-05-23"), ("2022-05-30")),
PARTITION p2022_23 VALUES [("2022-05-30"), ("2022-06-06")),
PARTITION p2022_24 VALUES [("2022-06-06"), ("2022-06-13")),
PARTITION p2022_25 VALUES [("2022-06-13"), ("2022-06-20")),
PARTITION p2022_26 VALUES [("2022-06-20"), ("2022-06-27")),
PARTITION p2022_27 VALUES [("2022-06-27"), ("2022-07-04")),
PARTITION p2022_28 VALUES [("2022-07-04"), ("2022-07-11")),
PARTITION p2022_29 VALUES [("2022-07-11"), ("2022-07-18")),
PARTITION p2022_30 VALUES [("2022-07-18"), ("2022-07-25")),
PARTITION p2022_31 VALUES [("2022-07-25"), ("2022-08-01")),
PARTITION p2022_32 VALUES [("2022-08-01"), ("2022-08-08")),
PARTITION p2022_33 VALUES [("2022-08-08"), ("2022-08-15")),
PARTITION p2022_34 VALUES [("2022-08-15"), ("2022-08-22")),
PARTITION p2022_35 VALUES [("2022-08-22"), ("2022-08-29")),
PARTITION p2022_36 VALUES [("2022-08-29"), ("2022-09-05")),
PARTITION p2022_37 VALUES [("2022-09-05"), ("2022-09-12")),
PARTITION p2022_38 VALUES [("2022-09-12"), ("2022-09-19")),
PARTITION p2022_39 VALUES [("2022-09-19"), ("2022-09-26")),
PARTITION p2022_40 VALUES [("2022-09-26"), ("2022-10-03")),
PARTITION p2022_41 VALUES [("2022-10-03"), ("2022-10-10")),
PARTITION p2022_42 VALUES [("2022-10-10"), ("2022-10-17")),
PARTITION p2022_43 VALUES [("2022-10-17"), ("2022-10-24")),
PARTITION p2022_44 VALUES [("2022-10-24"), ("2022-10-31")),
PARTITION p2022_45 VALUES [("2022-10-31"), ("2022-11-07")),
PARTITION p2022_46 VALUES [("2022-11-07"), ("2022-11-14")),
PARTITION p2022_47 VALUES [("2022-11-14"), ("2022-11-21")),
PARTITION p2022_48 VALUES [("2022-11-21"), ("2022-11-28")),
PARTITION p2022_49 VALUES [("2022-11-28"), ("2022-12-05")),
PARTITION p2022_50 VALUES [("2022-12-05"), ("2022-12-12")),
PARTITION p2022_51 VALUES [("2022-12-12"), ("2022-12-19")),
PARTITION p2022_52 VALUES [("2022-12-19"), ("2022-12-26")),
PARTITION p2022_53 VALUES [("2022-12-26"), ("2023-01-02")),
PARTITION p2023_02 VALUES [("2023-01-02"), ("2023-01-09")),
PARTITION p2023_03 VALUES [("2023-01-09"), ("2023-01-16")),
PARTITION p2023_04 VALUES [("2023-01-16"), ("2023-01-23")),
PARTITION p2023_05 VALUES [("2023-01-30"), ("2023-02-06")),
PARTITION p2023_06 VALUES [("2023-02-06"), ("2023-02-13")),
PARTITION p2023_07 VALUES [("2023-02-13"), ("2023-02-20")))
DISTRIBUTED BY HASH(`event_day`) BUCKETS 4 
PROPERTIES (
"replication_num" = "1",
"dynamic_partition.enable" = "true",
"dynamic_partition.time_unit" = "WEEK",
"dynamic_partition.time_zone" = "Asia/Shanghai",
"dynamic_partition.start" = "-2147483648",
"dynamic_partition.end" = "2",
"dynamic_partition.prefix" = "p",
"dynamic_partition.buckets" = "4",
"dynamic_partition.start_day_of_week" = "1",
"in_memory" = "false",
"storage_format" = "DEFAULT",
"enable_persistent_index" = "false",
"replicated_storage" = "true",
"compression" = "LZ4"
);
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
2.4,2.5

### PR DESCRIPTION
**Pull request by Astralidea**
Signed-off-by: Astralidea <astralidea@163.com>

## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #17128

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 2.5
  - [x] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Comment by Astralidea** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 11 / 13 (84.62%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/ast/MultiRangePartitionDesc.java|10|12|83.33%|[197, 198]|
|:large_blue_circle:|com/starrocks/common/util/DynamicPartitionUtil.java|1|1|100.00%|[]|

**Review by gengjun-git — APPROVED** [review]

**Review by ABingHuang — APPROVED** [review]
LGTM

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.4

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.3

**Pull request merged**
