### PR TITLE
[Refactor] Refactor alter materialized view statement executor to eliminate code coupling

### PR DESCRIPTION
**Pull request by HangyuanLiu**
Fixes #issue

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [x] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [x] Yes, this PR will result in a change in behavior.
- [ ] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [ ] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

coverage check fail. please retry. :fearful:

[Please let me know](https://github.com/naver/cover-checker/issues/new) when error again.

com.naver.nid.cover.parser.coverage.exception.ParseException: java.nio.file.NoSuchFileException: /home/runner/_work/test/report/result

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:disappointed: **fail** : 239 / 393 (60.81%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/ast/AstVisitor.java|0|2|00.00%|[978, 982]|
|:large_blue_circle:|com/starrocks/sql/ast/AlterMaterializedViewStatusClause.java|0|9|00.00%|[25, 28, 29, 30, 35, 36, 37, 40, 45]|
|:large_blue_circle:|com/starrocks/catalog/TableProperty.java|0|5|00.00%|[381, 397, 412, 422, 491]|
|:large_blue_circle:|com/starrocks/alter/SchemaChangeHandler.java|0|2|00.00%|[1795, 1815]|
|:large_blue_circle:|com/starrocks/alter/AlterJobException.java|0|2|00.00%|[19, 20]|
|:large_blue_circle:|com/starrocks/common/util/PropertyAnalyzer.java|5|32|15.62%|[293, 324, 332, 335, 348, 351, 360, 371, 389, 726, 736, 742, 748, 757, 786, 791, 795, 801, 832, 837, 863, 886, 909, 920, 925, 928, 952]|
|:large_blue_circle:|com/starrocks/catalog/UniqueConstraint.java|2|8|25.00%|[129, 135, 138, 145, 148, 158]|
|:large_blue_circle:|com/starrocks/alter/AlterJobMgr.java|7|14|50.00%|[265, 289, 301, 600, 601, 602, 603]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AlterTableClauseVisitor.java|13|24|54.17%|[752, 760, 761, 766, 767, 768, 769, 778, 779, 780, 782]|
|:large_blue_circle:|com/starrocks/alter/AlterMVJobExecutor.java|139|213|65.26%|[68, 95, 104, 108, 116, 117, 121, 122, 127, 128, 129, 134, 135, 136, 167, 168, 169, 170, 172, 173, 174, 175, 188, 189, 190, 191, 194, 195, 198, 199, 208, 209, 210, 211, 212, 215, 216, 217, 218, 219, 252, 253, 254, 269, 275, 276, 294, 309, 310, 316, 317, 318, 321, 322, 323, 325, 326, 327, 328, 329, 330, 331, 332, 334, 336, 337, 338, 340, 342, 343, 344, 345, 346, 347]|
|:large_blue_circle:|com/starrocks/alter/AlterJobExecutor.java|56|64|87.50%|[86, 126, 136, 137, 288, 323, 329, 337]|
|:large_blue_circle:|com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java|7|8|87.50%|[912]|
|:large_blue_circle:|com/starrocks/alter/AlterOpType.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AlterMVClauseAnalyzerVisitor.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/AlterMaterializedViewStmt.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/RefreshSchemeClause.java|2|2|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:disappointed: **fail** : 239 / 393 (60.81%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/ast/AstVisitor.java|0|2|00.00%|[978, 982]|
|:large_blue_circle:|com/starrocks/sql/ast/AlterMaterializedViewStatusClause.java|0|9|00.00%|[25, 28, 29, 30, 35, 36, 37, 40, 45]|
|:large_blue_circle:|com/starrocks/catalog/TableProperty.java|0|5|00.00%|[381, 397, 412, 422, 491]|
|:large_blue_circle:|com/starrocks/alter/SchemaChangeHandler.java|0|2|00.00%|[1795, 1815]|
|:large_blue_circle:|com/starrocks/alter/AlterJobException.java|0|2|00.00%|[19, 20]|
|:large_blue_circle:|com/starrocks/common/util/PropertyAnalyzer.java|5|32|15.62%|[293, 324, 332, 335, 348, 351, 360, 371, 389, 726, 736, 742, 748, 757, 786, 791, 795, 801, 832, 837, 863, 886, 909, 920, 925, 928, 952]|
|:large_blue_circle:|com/starrocks/catalog/UniqueConstraint.java|2|8|25.00%|[129, 135, 138, 145, 148, 158]|
|:large_blue_circle:|com/starrocks/alter/AlterJobMgr.java|7|14|50.00%|[265, 289, 301, 600, 601, 602, 603]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AlterTableClauseVisitor.java|13|24|54.17%|[752, 760, 761, 766, 767, 768, 769, 778, 779, 780, 782]|
|:large_blue_circle:|com/starrocks/alter/AlterMVJobExecutor.java|139|213|65.26%|[68, 95, 104, 108, 116, 117, 121, 122, 127, 128, 129, 134, 135, 136, 167, 168, 169, 170, 172, 173, 174, 175, 188, 189, 190, 191, 194, 195, 198, 199, 208, 209, 210, 211, 212, 215, 216, 217, 218, 219, 252, 253, 254, 269, 275, 276, 294, 309, 310, 316, 317, 318, 321, 322, 323, 325, 326, 327, 328, 329, 330, 331, 332, 334, 336, 337, 338, 340, 342, 343, 344, 345, 346, 347]|
|:large_blue_circle:|com/starrocks/alter/AlterJobExecutor.java|56|64|87.50%|[86, 126, 136, 137, 288, 323, 329, 337]|
|:large_blue_circle:|com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java|7|8|87.50%|[912]|
|:large_blue_circle:|com/starrocks/alter/AlterOpType.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AlterMVClauseAnalyzerVisitor.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/AlterMaterializedViewStmt.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/RefreshSchemeClause.java|2|2|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:disappointed: **fail** : 284 / 404 (70.30%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/ast/AstVisitor.java|0|2|00.00%|[978, 982]|
|:large_blue_circle:|com/starrocks/catalog/TableProperty.java|0|5|00.00%|[381, 397, 412, 422, 491]|
|:large_blue_circle:|com/starrocks/alter/SchemaChangeHandler.java|0|2|00.00%|[1795, 1815]|
|:large_blue_circle:|com/starrocks/common/util/PropertyAnalyzer.java|5|32|15.62%|[293, 324, 332, 335, 348, 351, 360, 371, 389, 726, 736, 742, 748, 757, 786, 791, 795, 801, 832, 837, 863, 886, 909, 920, 925, 928, 952]|
|:large_blue_circle:|com/starrocks/catalog/UniqueConstraint.java|2|8|25.00%|[129, 135, 138, 145, 148, 158]|
|:large_blue_circle:|com/starrocks/sql/ast/RefreshSchemeClause.java|8|13|61.54%|[29, 30, 33, 34, 49]|
|:large_blue_circle:|com/starrocks/alter/AlterJobMgr.java|9|14|64.29%|[301, 600, 601, 602, 603]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AlterTableClauseVisitor.java|16|24|66.67%|[752, 760, 761, 766, 767, 768, 769, 780]|
|:large_blue_circle:|com/starrocks/alter/AlterMVJobExecutor.java|160|213|75.12%|[68, 95, 104, 108, 116, 117, 121, 122, 127, 128, 129, 134, 135, 136, 167, 168, 169, 170, 172, 173, 174, 175, 188, 189, 190, 191, 194, 195, 198, 199, 208, 209, 210, 211, 212, 215, 216, 217, 218, 219, 252, 253, 254, 269, 275, 276, 294, 309, 310, 332, 340, 346, 347]|
|:large_blue_circle:|com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java|7|8|87.50%|[912]|
|:large_blue_circle:|com/starrocks/alter/AlterJobExecutor.java|58|64|90.62%|[86, 126, 288, 323, 329, 337]|
|:large_blue_circle:|com/starrocks/sql/ast/AlterMaterializedViewStatusClause.java|9|9|100.00%|[]|
|:large_blue_circle:|com/starrocks/alter/AlterOpType.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AlterMVClauseAnalyzerVisitor.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/AlterMaterializedViewStmt.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/alter/AlterJobException.java|2|2|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by Astralidea — APPROVED** [review]

**Review by ABingHuang — APPROVED** [review]

**Pull request merged**
