### PR TITLE
[Enhancement] Provide instructions on how to modify mem_limit for a resource group

### PR DESCRIPTION
**Pull request by ZiheLiu**
## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

When the memory exceeds limit of a workgroup, it returns `Memory of rg1 exceed limit. Used: 48768571277, Limit: 48768455281.` to the user, which is hard to know what to do next.

After this PR:
For `default_wg`, it returns:
```
Memory of default_wg exceed limit. Used: 48768571277, Limit: 48768455281.
Mem usage has exceed the limit of query pool
```

For the other groups, it returns:
```
Memory of rg1 exceed limit. Used: 48768571277, Limit: 48768455281.
Mem usage has exceed the limit of the resource group [rg1]. 
You can change the limit by modify [mem_limit] of this group.
```

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 3.0
  - [x] 2.5
  - [x] 2.4
  - [x] 2.3

### CODE REVIEW

**Review by satanson — APPROVED** [review]

**Review by murphyatwork — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.4

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.3

**Pull request merged**
