### PR TITLE
[BugFix] Fix init_position_in_orc() case sensitive bug

### LINKED ISSUE #15409: OrcChunkReader::init_position_in_orc error
### Steps to reproduce the behavior (Required)
1. create iceberg table in spark:
```
create table hive_prod.iceberg_db.sr_13908_orc(
C_BOOL boolean,
c_INT int,
C_date date,
c_String string
)
USING iceberg
TBLPROPERTIES('write.format.default'='orc','write.parquet.compression-codec'='snappy');
insert into hive_prod.iceberg_db.sr_13908_orc select true,1,cast('2022-08-08' as date),'Hello, China!';
insert into hive_prod.iceberg_db.sr_13908_orc select false,2,cast('2023-08-08' as date),'Hello, World!';
```

2. create iceberg external table in sr:
```
create external table ex_iceberg_tbl(
                    C_BOOL boolean,
                    c_INT int,
                    C_date date,
                    c_String string)
                    ENGINE=iceberg
                    properties (
                        "resource" = "iceberg_resource_380427ba_7f82_11ed_a91f_00163e0e550b",
                        "table" = "sr_13908_orc",
                        "database" = "iceberg_db");
```

3. select error:
```
select * from ex_iceberg_tbl order by 1;
execute sql error and messages: (1064, 'OrcChunkReader::init_position_in_orc. failed to find position. col_name = C_BOOL, file = :file = hdfs://emr-header-1.cluster-49155:9000/user/hive/warehouse/iceberg_db.db/sr_13908_orc/data/00000-3-bf5f6be5-2ce5-4620-9e32-e53e25d67bb6-00001.orc'), and time is: 2022-12-19 17:47:58
```

### Expected behavior (Required)
return the right result

### Real behavior (Required)
error

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
mysql> select current_version();
+----------------------------+
| current_version()          |
+----------------------------+
| BRANCH-2.3-RELEASE 6d44898 |
+----------------------------+
1 row in set (0.00 sec)
```

### PR DESCRIPTION
**Pull request by Smith-Cruise**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #15409

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 2.5
  - [x] 2.4
  - [x] 2.3
  - [x] 2.2

### CODE REVIEW

**Review by dirtysalt — DISMISSED** [review]

**Comment by DorianZheng** [comment]
add some UT

**Comment by DorianZheng** [comment]
check case sensitive issue more systematically to see if there are any issue.

**Review by DorianZheng — APPROVED** [review]

**Review by dirtysalt — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by Youngwb — APPROVED** [review]

**Comment by Smith-Cruise** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.4

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.3

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.2

**Pull request merged**
