### PR TITLE
[BugFix] Fix runtime filter value escape problem in mysql external table

### LINKED ISSUE #23554: query failed in mysql external table:
### Steps to reproduce the behavior (Required)
```
set enable_pipeline_engine=false;
CREATE TABLE `allstring` (
  `v1` varchar(20) NOT NULL COMMENT "",
  `v2` varchar(20) NOT NULL COMMENT "",
  `v3` varchar(20) NOT NULL COMMENT ""
) ENGINE=OLAP 
DUPLICATE KEY(`v1`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`v1`) BUCKETS 1 
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"enable_persistent_index" = "false",
"replicated_storage" = "false",
"compression" = "LZ4"
);
insert into allstring values ('"key"',"1", "2");
insert into allstring values ("'key'","1", "2");
CREATE EXTERNAL TABLE external_allstring
(
  `v1` varchar(20) NOT NULL COMMENT "",
  `v2` varchar(20) NOT NULL COMMENT "",
  `v3` varchar(20) NOT NULL COMMENT ""
)
ENGINE=mysql
PROPERTIES
(
    "host" = "127.0.0.1",
    "port" = "3306",
    "user" = "root",
    "password" = "",
    "database" = "dev",
    "table" = "allstring"
);
select count(*) from external_allstring l join [broadcast] allstring r on l.v1=r.v1;
```

### Expected behavior (Required)
```
+----------+
| count(*) |
+----------+
|        2 |
+----------+
```

### Real behavior (Required)
```
ERROR 1064 (HY000): mysql query failed. Err: Getting syntax error at line 1, column 54. Detail message: Input 'AND' is not valid at this position.
```

### StarRocks version (Required)
 -

### PR DESCRIPTION
**Pull request by dirtysalt**
## Problem Summary:
Fixes https://github.com/StarRocks/starrocks/issues/23554

add test cases on https://github.com/StarRocks/starrocks/pull/23555

## What type of PR is this:
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 3.0
  - [x] 2.5
  - [x] 2.4
  - [x] 2.3

### CODE REVIEW

**Review by stdpain — APPROVED** [review]

**Review by Astralidea — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.4

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.3

**Pull request merged**
