### PR TITLE
[Enhancement] remove sensitive info from create repo audit

### LINKED ISSUE #13324: Sensitive info should be moved from log
## Enhancement
The log of StarRocks may include some sensitive information, like username, password.

### PR DESCRIPTION
**Pull request by rickif**
## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes https://github.com/StarRocks/starrocks/issues/13324

## Problem Summary(Required) ：

This PR removes sensitive key words from audit log of create repo stmt. The new output would be like
```
2022-11-15 20:45:32,777 [query] |Client=127.0.0.1:56422|User=root|AuthorizedUser='root'@'%'|ResourceGroup=default_wg|Catalog=default_catalog|Db=db0|State=ERR|ErrorCode=|Time=10|ScanBytes=0|ScanRows=0|ReturnRows=0|CpuCostNs=0|MemCostBytes=0|StmtId=3|QueryId=2834574d-64f4-11ed-bbf0-52243889412b|IsQuery=false|feIp=172.17.0.1|Stmt=CREATE REPOSITORY `hdfs_repo` WITH BROKER `hdfs_broker` ON LOCATION "hdfs://hadoop-name-node:54310/path/to/repo/" PROPERTIES ( "username" = "user", "password" = "***" )|
```
in which the sensitive key words would be replaced by `***`.
Now, the sensitive key words include the following: 
```
password
kerberos_keytab_content
bos_secret_accesskey
fs.s3a.access.key
fs.s3a.secret.key
fs.oss.accessKeyId
fs.oss.accessKeySecret
fs.cosn.userinfo.secretId
fs.cosn.userinfo.secretKey
property.sasl.password

```

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
 - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Review by imay — DISMISSED** [review]

**Comment by rickif** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 8 / 9 (88.89%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/ast/CreateRepositoryStmt.java|0|1|00.00%|[73]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AstToStringBuilder.java|8|8|100.00%|[]|

**Review by chaoyli — DISMISSED** [review]

**Review by meegoo — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by rickif** [comment]
run starrocks_admit_test

**Comment by rickif** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 8 / 9 (88.89%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/ast/CreateRepositoryStmt.java|0|1|00.00%|[73]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AstToStringBuilder.java|8|8|100.00%|[]|

**Review by chaoyli — DISMISSED** [review]

**Review by HangyuanLiu — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by rickif** [comment]
starrocks_admit_test

**Comment by rickif** [comment]
starrocks_admit_test

**Comment by rickif** [comment]
run starrocks_admit_test

**Comment by rickif** [comment]
run starrocks_admit_test

**Pull request closed without merging**
