### PR TITLE
[SR SQL Planner Summer Camp] Support show tablet in new parser

### PR DESCRIPTION
**Pull request by xlwh**
## What type of PR is this：
- [ ] bug
- [x] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #7938

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 116 / 150 (77.33%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/ShowTabletStmtAnalyzer.java|76|107|71.03%|
|:large_blue_circle:|com/starrocks/sql/analyzer/PrivilegeChecker.java|3|4|75.00%|
|:large_blue_circle:|com/starrocks/analysis/ShowTabletStmt.java|16|18|88.89%|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|18|18|100.00%|
|:large_blue_circle:|com/starrocks/sql/ast/AstVisitor.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/sql/analyzer/ShowStmtAnalyzer.java|2|2|100.00%|

**Comment by xlwh** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 116 / 150 (77.33%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/ShowTabletStmtAnalyzer.java|76|107|71.03%|
|:large_blue_circle:|com/starrocks/sql/analyzer/PrivilegeChecker.java|3|4|75.00%|
|:large_blue_circle:|com/starrocks/analysis/ShowTabletStmt.java|16|18|88.89%|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|18|18|100.00%|
|:large_blue_circle:|com/starrocks/sql/ast/AstVisitor.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/sql/analyzer/ShowStmtAnalyzer.java|2|2|100.00%|

**Review by HangyuanLiu — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 116 / 150 (77.33%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/ShowTabletStmtAnalyzer.java|76|107|71.03%|[27, 42, 43, 50, 64, 87, 93, 94, 112, 117, 127, 128, 132, 133, 137, 138, 143, 144, 149, 150, 155, 156, 161, 162, 167, 168, 169, 170, 173, 174, 179]|
|:large_blue_circle:|com/starrocks/sql/analyzer/PrivilegeChecker.java|3|4|75.00%|[354]|
|:large_blue_circle:|com/starrocks/analysis/ShowTabletStmt.java|16|18|88.89%|[189, 193]|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|18|18|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/AstVisitor.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/ShowStmtAnalyzer.java|2|2|100.00%|[]|

**Comment by xlwh** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
> run starrocks_admit_test

admit show tablet case error, please fix it.

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 117 / 150 (78.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/ShowTabletStmtAnalyzer.java|77|107|71.96%|[27, 42, 43, 64, 87, 93, 94, 112, 117, 127, 128, 132, 133, 137, 138, 143, 144, 149, 150, 155, 156, 161, 162, 167, 168, 169, 170, 173, 174, 179]|
|:large_blue_circle:|com/starrocks/sql/analyzer/PrivilegeChecker.java|3|4|75.00%|[369]|
|:large_blue_circle:|com/starrocks/analysis/ShowTabletStmt.java|16|18|88.89%|[189, 193]|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|18|18|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/AstVisitor.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/ShowStmtAnalyzer.java|2|2|100.00%|[]|

**Comment by xlwh** [comment]
run starrocks_admit_test

**Comment by xlwh** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 122 / 149 (81.88%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/PrivilegeChecker.java|3|4|75.00%|[369]|
|:large_blue_circle:|com/starrocks/sql/analyzer/ShowTabletStmtAnalyzer.java|82|107|76.64%|[27, 42, 43, 64, 87, 112, 117, 127, 128, 132, 133, 137, 138, 143, 144, 149, 150, 155, 156, 161, 162, 167, 168, 169, 170]|
|:large_blue_circle:|com/starrocks/analysis/ShowTabletStmt.java|16|17|94.12%|[188]|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|18|18|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/AstVisitor.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/ShowStmtAnalyzer.java|2|2|100.00%|[]|

**Pull request merged**
