### PR TITLE
[BugFix] Fix bug show full column does not display default value

### LINKED ISSUE #27716: default value is not displayed
### Steps to reproduce the behavior (Required)
1. create table test_default
(id varchar(255) default (uuid()))
distributed by hash(id)
PROPERTIES ( "replication_num" = "1" )
2.show full columns from test_default;

### Expected behavior (Required)
+-------+--------------+-----------+------+------+---------+-------+------------+---------+
| Field | Type         | Collation | Null | Key  | Default | Extra | Privileges | Comment |
+-------+--------------+-----------+------+------+---------+-------+------------+---------+
| id    | varchar(255) |           | YES  | YES  | uuid()  |       |            |         |
+-------+--------------+-----------+------+------+---------+-------+------------+---------+
### Real behavior (Required)
+-------+--------------+-----------+------+------+---------+-------+------------+---------+
| Field | Type         | Collation | Null | Key  | Default | Extra | Privileges | Comment |
+-------+--------------+-----------+------+------+---------+-------+------------+---------+
| id    | varchar(255) |           | YES  | YES  | NULL    |       |            |         |
+-------+--------------+-----------+------+------+---------+-------+------------+---------+
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
3.0.3 ~ main

### PR DESCRIPTION
**Pull request by Astralidea**
Fixes #27716

## What type of PR is this:
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [x] 3.0
  - [x] 2.5
  - [ ] 2.4

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/Column.java|2|2|100.00%|[]|

**Review by ABingHuang — APPROVED** [review]

**Review by wyb — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
