### PR TITLE
[Feature] Suppport jodatime_format function

### LINKED ISSUE #23422: [function enhancement]date_format and str_to_date
in the past, to be compatible with mysql, we use the MySQL's date format in date_format and str_to_date. However, many users find it hard to write. They need a more common date format types.

so here is a proposal:

support JodaTime’s [DateTimeFormat](http://joda-time.sourceforge.net/apidocs/org/joda/time/format/DateTimeFormat.html) pattern format in [date_format](https://docs.starrocks.io/en-us/latest/sql-reference/sql-functions/date-time-functions/date_format)  and in [str_to_date](https://docs.starrocks.io/en-us/latest/sql-reference/sql-functions/date-time-functions/str_to_date) as well.

because the date format MySQL use always contains %, so it is possible to distinguish which format the user is using by whether the string contains %.

### PR DESCRIPTION
**Pull request by Youngwb**
Fixes 
#23422

## Description

Converts a date into a string according to the format that is compatible with JodaTime’s DateTimeFormat pattern format. Currently it supports strings with a maximum of 128 bytes. If the length of the returned value exceeds 128, NULL is returned.

## Syntax

```Haskell
VARCHAR JODATIME_FORMAT(DATETIME date, VARCHAR format)
```

## Parameters

- The `date` parameter must be a valid date or date expression.

- `format` specifies the output format of the date or time.

The available formats could refer to [joda-time format](https://joda-time.sourceforge.net/apidocs/org/joda/time/format/DateTimeFormat.html)

## Examples

```Plain Text
mysql> select jodatime_format('2020-06-25 15:58:51', 'yyyy-MM-dd');
+------------------------------------------------------+
| jodatime_format('2020-06-25 15:58:51', 'yyyy-MM-dd') |
+------------------------------------------------------+
| 2020-06-25                                           |
+------------------------------------------------------+
mysql> select jodatime_format('2020-06-25 15:58:51', 'yyyy-MM-dd HH:mm:ss');
+---------------------------------------------------------------+
| jodatime_format('2020-06-25 15:58:51', 'yyyy-MM-dd HH:mm:ss') |
+---------------------------------------------------------------+
| 2020-06-25 15:58:51                                           |
+---------------------------------------------------------------+

```

## What type of PR is this:
- [ ] BugFix
- [x] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [x] 3.0
  - [ ] 2.5
  - [ ] 2.4

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by Seaven — APPROVED** [review]

**Review by wangsimo0 — APPROVED** [review]

**Comment by Youngwb** [comment]
@Mergifyio backport branch-3.1

**Comment by Youngwb** [comment]
@Mergifyio branckport branch-3.0

**Pull request merged**
