### PR TITLE
[Enhancement] Support create statistics table with all machines as the number of replicas

### PR DESCRIPTION
**Pull request by HangyuanLiu**
## What type of PR is this：
- [ ] bug
- [ ] feature
- [x] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

1. To create a statistics table, the total number of machines should be used as a reference value, not the previous number of surviving machines. Because if the BE is upgraded in a rolling manner, there may be no or very few machines alive for a certain period of time, resulting in too few replicas of the statistics table created.
2. delete some unused code

### CODE REVIEW

**Comment by HangyuanLiu** [comment]
run starrocks_fe_unittest

**Comment by wangruin** [comment]
run starrocks_fe_unittest

**Comment by wangruin** [comment]
run starrocks_fe_unittest

**Review by Youngwb — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 9 / 14 (64.29%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/statistic/StatisticUtils.java|6|11|54.55%|[99, 100, 101, 102, 104]|
|:large_blue_circle:|com/starrocks/statistic/StatisticsMetaManager.java|3|3|100.00%|[]|

**Comment by HangyuanLiu** [comment]
run starrocks_be_build

**Comment by HangyuanLiu** [comment]
run starrocks_be_unittest

**Comment by HangyuanLiu** [comment]
run starrocks_clang-format

**Comment by HangyuanLiu** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 9 / 14 (64.29%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/statistic/StatisticUtils.java|6|11|54.55%|[99, 100, 101, 102, 104]|
|:large_blue_circle:|com/starrocks/statistic/StatisticsMetaManager.java|3|3|100.00%|[]|

**Review by Seaven — APPROVED** [review]

**Review by liuyehcf — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Pull request merged**
