### PR TITLE
[BugFix] Analyze and PlanBuilder should be in the same read lock

### LINKED ISSUE #10651: [Bug] IndexOutOfBoundException when concurrent AlterTable with Insert
```
java.lang.IndexOutOfBoundsException: Index: 3, Size: 3
    at java.util.ArrayList.rangeCheck(ArrayList.java:659) ~[?:1.8.0_322]
    at java.util.ArrayList.get(ArrayList.java:435) ~[?:1.8.0_322]
    at com.starrocks.sql.InsertPlanner.castLiteralToTargetColumnsType(InsertPlanner.java:167) ~[classes/:?]
    at com.starrocks.sql.InsertPlanner.plan(InsertPlanner.java:82) ~[classes/:?]
    at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:77) ~[classes/:?]
    at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:40) ~[classes/:?]
    at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:342) ~[classes/:?]
    at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:312) ~[classes/:?]
    at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:427) ~[classes/:?]
    at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:665) ~[classes/:?]
    at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:55) ~[classes/:?]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_322]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_322]
    at java.lang.Thread.run(Thread.java:750) [?:1.8.0_322]

```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by HangyuanLiu**
## What type of PR is this：
- [x] bugfix
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #10651 

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 23 / 23 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/AnalyzerUtils.java|6|6|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/StatementPlanner.java|17|17|100.00%|[]|

**Review by kangkaisen — DISMISSED** [review]

**Review by Seaven — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 25 / 27 (92.59%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/AnalyzerUtils.java|8|10|80.00%|[195, 203]|
|:large_blue_circle:|com/starrocks/sql/StatementPlanner.java|17|17|100.00%|[]|

**Comment by HangyuanLiu** [comment]
run starrocks_admit_test

**Pull request merged**
