### PR TITLE
Move 'exprs/vectorized' to 'exprs'

### PR DESCRIPTION
**Pull request by xlwh**
## What type of PR is this：
- [ ] bug
- [ ] feature
- [x] enhancement
- [ ] others

## Which issues of this PR fixes ：

Fixes #

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by xlwh** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by murphyatwork — DISMISSED** [review]

**Review by imay — DISMISSED** [review]

**Comment by stdpain** [comment]
I think it's a meaningful thing, but maybe we're having more trouble with the cherry-pick bug fix patch.

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by xlwh** [comment]
> 

Yes, this change will be relatively large and may cause some difficulties for cherry-pick, do you have any good suggestions? When should we make this change? Thanks!

**Comment by kangkaisen** [comment]
> > 
> 
> Yes, this change will be relatively large and may cause some difficulties for cherry-pick, do you have any good suggestions? When should we make this change? Thanks!

I think you could do this work now. After all CI pass, we could merge your PR.

**Comment by xlwh** [comment]
> > > 
> > 
> > 
> > Yes, this change will be relatively large and may cause some difficulties for cherry-pick, do you have any good suggestions? When should we make this change? Thanks!
> 
> I think you could do this work now. After all CI pass, we could merge your PR.

OK, I will rebase it later

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Pull request closed without merging**
