### PR TITLE
[BugFix] fix window_funnel udf lost condition

### LINKED ISSUE #6811: window_funnel  udf ignore data if more than one conditions match
### Steps to reproduce the behavior (Required)
1.
```
CREATE TABLE `action` (
  `uid` int(11) NULL COMMENT "",
  `event_type` varchar(65533) NULL COMMENT "",
  `time` datetime NULL COMMENT ""
) ENGINE=OLAP
DUPLICATE KEY(`uid`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`uid`) BUCKETS 1
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"storage_format" = "DEFAULT"
);
```
2.  select uid, window_funnel(1800, time, 0, [true, true, true]) as level from action where uid=1  group by uid; 
```
+------+-------+
| uid  | level |
+------+-------+
|    1 |     1 |
+------+-------+
```
result is 1 not 3

### StarRocks version (Required)
 -  main branch

### PR DESCRIPTION
**Pull request by hongli-my**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #6811

### CODE REVIEW

**Comment by hongli-my** [comment]
> Please add UT to cover this bug, thanks!
add here like sum function?
https://github.com/StarRocks/starrocks/blob/main/be/test/exprs/agg/aggregate_test.cpp#L303

**Comment by hongli-my** [comment]
> Please add UT to cover this bug, thanks!

add here , like sum function?
https://github.com/StarRocks/starrocks/blob/main/be/test/exprs/agg/aggregate_test.cpp#L303

**Comment by hongli-my** [comment]
> Please add UT to cover this bug, thanks!

done

**Review by kangkaisen — APPROVED** [review]

**Review by murphyatwork — APPROVED** [review]

**Comment by mofeiatwork** [comment]
@Mergifyio backport branch-2.3

**Review by Pslydhh — APPROVED** [review]

**Comment by kangkaisen** [comment]
run starrocks_fe_unittest

**Pull request merged**
