### PR TITLE
[BugFix] ensure cteId auto increment

### LINKED ISSUE #22266: different cte anchors have same cte id
### Steps to reproduce the behavior (Required)
```
with tmp as (select 8 id, 'season' type1, 'a.season' pretype, 'season' ranktype from dual ) select case when id = abs(0) then 'a' else case when exists (select 1 from tmp) then id in (select id > (select type1 from tmp) from tmp ) else 'test' end end from tmp a;
```

### Expected behavior (Required)
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| CASE WHEN (id = (abs(0))) THEN 'a' ELSE (CASE WHEN (EXISTS (SELECT 1 FROM tmp)) THEN (id IN (((SELECT id > ((SELECT type1 FROM tmp)) FROM tmp)))) ELSE 'test' END) END |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| NULL                                                                                                                                                                   |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

### Real behavior (Required)
BE crash

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by packy92**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #22266

## Problem Summary(Required) ：

In some transformation rules, `this.cteId = factory.getNextRelationId();` may obtain a duplicate cte id.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 3.0
  - [x] 2.5
  - [x] 2.4
  - [ ] 2.3

### CODE REVIEW

**Review by Seaven — DISMISSED** [review]

**Review by kangkaisen — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 7 / 7 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/RewriteGroupingSetsByCTERule.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/RewriteMultiDistinctByCTERule.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/CTEContext.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/QuantifiedApply2OuterJoinRule.java|1|1|100.00%|[]|

**Review by kangkaisen — APPROVED** [review]

**Review by ZiheLiu — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.4

**Pull request merged**
