### PR TITLE
[BugFix] Fix restore automatic bucket table fail

### PR DESCRIPTION
**Pull request by meegoo**
Fixes #issue

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Review by Astralidea — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by Astralidea — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:disappointed: **fail** : 50 / 250 (20.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/Partition.java|0|5|00.00%|[184, 194, 214, 215, 232]|
|:large_blue_circle:|com/starrocks/catalog/PhysicalPartitionImpl.java|0|6|00.00%|[108, 109, 110, 114, 124, 125]|
|:large_blue_circle:|com/starrocks/catalog/OlapTable.java|0|33|00.00%|[664, 686, 687, 688, 689, 690, 691, 692, 693, 710, 711, 712, 713, 714, 715, 716, 717, 727, 728, 729, 730, 731, 732, 733, 735, 736, 740, 741, 742, 743, 744, 745, 746]|
|:large_blue_circle:|com/starrocks/backup/RestoreJob.java|0|79|00.00%|[397, 566, 567, 568, 798, 856, 857, 858, 859, 860, 861, 862, 863, 864, 865, 866, 867, 868, 869, 870, 871, 872, 874, 875, 876, 877, 878, 879, 880, 881, 882, 883, 884, 919, 921, 922, 924, 925, 926, 927, 930, 933, 934, 935, 936, 938, 939, 940, 941, 950, 951, 953, 955, 971, 972, 973, 975, 976, 981, 982, 983, 984, 985, 986, 987, 988, 989, 990, 991, 992, 993, 994, 995, 996, 997, 998, 1200, 1211, 1254]|
|:large_blue_circle:|com/starrocks/backup/BackupJobInfo.java|50|127|39.37%|[207, 212, 213, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 349, 350, 351, 352, 353, 355, 356, 357, 358, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 520, 521, 522, 524, 525, 527, 528, 529, 530, 531, 532, 533, 534, 536, 538, 641, 642, 643, 644, 645, 646, 647, 648, 649, 650, 651, 652, 653, 654, 655, 656, 657, 658, 659, 661, 662, 663, 664, 665, 666]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by gengjun-git — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:disappointed: **fail** : 173 / 252 (68.65%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/Partition.java|1|5|20.00%|[194, 214, 215, 232]|
|:large_blue_circle:|com/starrocks/backup/RestoreJob.java|40|81|49.38%|[570, 571, 572, 923, 925, 926, 928, 929, 930, 931, 934, 937, 938, 939, 940, 942, 943, 944, 945, 955, 985, 986, 987, 988, 989, 990, 991, 992, 993, 994, 995, 996, 997, 998, 999, 1000, 1001, 1002, 1204, 1215, 1258]|
|:large_blue_circle:|com/starrocks/catalog/OlapTable.java|18|33|54.55%|[690, 691, 692, 693, 710, 711, 712, 713, 714, 715, 716, 717, 735, 736, 746]|
|:large_blue_circle:|com/starrocks/backup/BackupJobInfo.java|108|127|85.04%|[337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 348, 349, 350, 351, 352, 354, 355, 356, 357]|
|:large_blue_circle:|com/starrocks/catalog/PhysicalPartitionImpl.java|6|6|100.00%|[]|

**Review by Astralidea — APPROVED** [review]

**Review by gengjun-git — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 206 / 255 (80.78%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/backup/RestoreJob.java|59|82|71.95%|[570, 571, 572, 573, 923, 925, 926, 928, 929, 930, 931, 934, 937, 938, 939, 940, 942, 943, 944, 945, 1204, 1215, 1258]|
|:large_blue_circle:|com/starrocks/catalog/Partition.java|4|5|80.00%|[232]|
|:large_blue_circle:|com/starrocks/catalog/OlapTable.java|29|35|82.86%|[714, 715, 716, 717, 737, 738]|
|:large_blue_circle:|com/starrocks/backup/BackupJobInfo.java|108|127|85.04%|[337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 348, 349, 350, 351, 352, 354, 355, 356, 357]|
|:large_blue_circle:|com/starrocks/catalog/PhysicalPartitionImpl.java|6|6|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.2

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 206 / 255 (80.78%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/backup/RestoreJob.java|59|82|71.95%|[570, 571, 572, 573, 923, 925, 926, 928, 929, 930, 931, 934, 937, 938, 939, 940, 942, 943, 944, 945, 1204, 1215, 1258]|
|:large_blue_circle:|com/starrocks/catalog/Partition.java|4|5|80.00%|[232]|
|:large_blue_circle:|com/starrocks/catalog/OlapTable.java|29|35|82.86%|[714, 715, 716, 717, 737, 738]|
|:large_blue_circle:|com/starrocks/backup/BackupJobInfo.java|108|127|85.04%|[337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 348, 349, 350, 351, 352, 354, 355, 356, 357]|
|:large_blue_circle:|com/starrocks/catalog/PhysicalPartitionImpl.java|6|6|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Pull request merged**
