### PR TITLE
[BugFix] Fix delta table binary predicate error

### LINKED ISSUE #16062: Delta table binaryOperator left and right DataTypes must be the same, found: boolean = short
### Steps to reproduce the behavior (Required)
1.hive
CREATE TABLE `delta_lake_data_type` ( 
col_tinyint           tinyint         ,
col_smallint          smallint        ,
col_int               integer         ,
col_long              long            ,
col_float             float           ,
col_double            double          ,
col_date              date            ,
col_timestamp         timestamp       ,
col_string            string          ,
col_decimal           decimal(10,2)   ,
col_boolean           boolean         ,
col_byte              byte            ,
col_array             array<int> )     
USING delta ;

insert into delta_lake_data_type
values
(null,10,10,10,10.002,100.2,'2022-12-10','2022-12-10 01:01:01','hello world', '1111.10',false,2,array(cast(10 as int), cast(11 as int))),
(11,null,null,null,null,null,null,null,null, null,null,null,array(cast(11 as int), cast(12 as int))),
(127,32767,2147483647,9223372036854775807,3.40E+38,1.79E+308,'9999-12-31','9999-12-31 23:59:59','hello world','9999.99',true, 0, null),
(-128,-32768,-2147483648,-9223372036854775808,-3.40E+38,-1.79E+308,'9999-12-31','9999-12-31 23:59:59','hello world','0.01',true, 0,array(null));
2.starrocks create catalog
CREATE EXTERNAL CATALOG "delta_catalog"  PROPERTIES ("type"="deltalake","hive.metastore.uris"="thrift://xxx.xx.xxx.xxx:xxxx");
use delta_catalog.delta_lake_db;
select * from delta_lake_data_type
3.starrocks select
select * from delta_lake_data_type where col_boolean = 1;
### Expected behavior (Required)
return correct result
### Real behavior (Required)
MySQL [delta_catalog.test]> select * from delta_lake_data_type where col_boolean = 1;
ERROR 1064 (HY000): BinaryOperator left and right DataTypes must be the same, found: boolean = short
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by leoyy0316**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #16062 #15794

## Problem Summary(Required) ：

Fix delta table binary expr error 
## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Comment by Youngwb** [comment]
run all

**Comment by Youngwb** [comment]
@leoyy0316 Please fix your FE ut

**Comment by leoyy0316** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 0 / 24 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/connector/delta/ExpressionConverter.java|0|24|00.00%|[128, 160, 179, 181, 182, 183, 184, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 203]|

**Comment by leoyy0316** [comment]
> @leoyy0316 Please fix your FE ut

@Youngwb done

**Review by stephen-shelby — APPROVED** [review]

**Comment by stephen-shelby** [comment]
run starrocks_admit_test

**Review by Youngwb — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by Youngwb** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
