### PR TITLE
Add view test and fix expression preceding bug

### PR DESCRIPTION
**Pull request by HangyuanLiu**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] others

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

- The interface of relation is divided into three types
>   1. getName, get the real name
>   2. getAlias, get the alias
>   3. getResolveTableName, get the resolution name, such as TableRelation, there is an alias as an alias, and there is no alias to get the table name

- Fix some sql spelling mistakes in AST2SQL
- Fix the bug of expression precedence

### CODE REVIEW

**Comment by HangyuanLiu** [comment]
run starrocks_fe_unittest

**Comment by HangyuanLiu** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 168 / 180 (93.33%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/ast/JoinRelation.java|6|9|66.67%|
|:large_blue_circle:|com/starrocks/sql/ast/ViewRelation.java|3|4|75.00%|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|6|7|85.71%|
|:large_blue_circle:|com/starrocks/sql/analyzer/AST2SQL.java|111|117|94.87%|
|:large_blue_circle:|com/starrocks/sql/analyzer/QueryAnalyzer.java|28|29|96.55%|
|:large_blue_circle:|com/starrocks/sql/optimizer/transformer/RelationTransformer.java|4|4|100.00%|
|:large_blue_circle:|com/starrocks/sql/analyzer/AnalyzerUtils.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/sql/analyzer/SelectAnalyzer.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/sql/ast/SubqueryRelation.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/http/rest/TableQueryPlanAction.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/sql/ast/Relation.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/sql/analyzer/ViewDefBuilder.java|5|5|100.00%|

**Comment by wanpengfei-git** [comment]
Can't set status; build succeeded.

**Comment by wanpengfei-git** [comment]
Can't set status; build succeeded.

**Comment by HangyuanLiu** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 162 / 177 (91.53%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/ast/ViewRelation.java|3|4|75.00%|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|7|8|87.50%|
|:large_blue_circle:|com/starrocks/sql/analyzer/AST2SQL.java|79|89|88.76%|
|:large_blue_circle:|com/starrocks/sql/analyzer/ViewDefBuilder.java|28|30|93.33%|
|:large_blue_circle:|com/starrocks/sql/analyzer/QueryAnalyzer.java|28|29|96.55%|
|:large_blue_circle:|com/starrocks/sql/optimizer/transformer/RelationTransformer.java|4|4|100.00%|
|:large_blue_circle:|com/starrocks/sql/analyzer/AnalyzerUtils.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/sql/ast/SubqueryRelation.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/http/rest/TableQueryPlanAction.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/sql/ast/Relation.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/sql/ast/JoinRelation.java|9|9|100.00%|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 162 / 177 (91.53%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/ast/ViewRelation.java|3|4|75.00%|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|7|8|87.50%|
|:large_blue_circle:|com/starrocks/sql/analyzer/AST2SQL.java|79|89|88.76%|
|:large_blue_circle:|com/starrocks/sql/analyzer/ViewDefBuilder.java|28|30|93.33%|
|:large_blue_circle:|com/starrocks/sql/analyzer/QueryAnalyzer.java|28|29|96.55%|
|:large_blue_circle:|com/starrocks/sql/optimizer/transformer/RelationTransformer.java|4|4|100.00%|
|:large_blue_circle:|com/starrocks/sql/analyzer/AnalyzerUtils.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/sql/ast/SubqueryRelation.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/http/rest/TableQueryPlanAction.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/sql/ast/Relation.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/sql/ast/JoinRelation.java|9|9|100.00%|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 163 / 178 (91.57%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/ast/ViewRelation.java|3|4|75.00%|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|7|8|87.50%|
|:large_blue_circle:|com/starrocks/sql/analyzer/AST2SQL.java|80|90|88.89%|
|:large_blue_circle:|com/starrocks/sql/analyzer/ViewDefBuilder.java|28|30|93.33%|
|:large_blue_circle:|com/starrocks/sql/analyzer/QueryAnalyzer.java|28|29|96.55%|
|:large_blue_circle:|com/starrocks/sql/optimizer/transformer/RelationTransformer.java|4|4|100.00%|
|:large_blue_circle:|com/starrocks/sql/analyzer/AnalyzerUtils.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/sql/ast/SubqueryRelation.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/http/rest/TableQueryPlanAction.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/sql/ast/Relation.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/sql/ast/JoinRelation.java|9|9|100.00%|

**Review by Seaven — APPROVED** [review]

**Review by kangkaisen — APPROVED** [review]

**Pull request merged**
