### PR TITLE
[BugFix] Fix double/float/date cast to string in FE (backport #27070)

### PR DESCRIPTION
**Pull request by Seaven**
Fixes #issue

1. keep same cast logical as BE on double/float type

before:
```
MySQL td> select cast(cast(1.00 as double) as string);
+------------------------------------------------+
| CAST((CAST(1.00 AS DOUBLE)) AS VARCHAR(65533)) |
+------------------------------------------------+
| 1.0                                            |
+------------------------------------------------+
1 row in set
```

after
```
MySQL td> select cast(cast(1.00 as double) as string);
+------------------------------------------------+
| CAST((CAST(1.00 AS DOUBLE)) AS VARCHAR(65533)) |
+------------------------------------------------+
| 1                                              |
+------------------------------------------------+
1 row in set
```

3. support `cast('2020-05-01T13:45:57' as datetime)` on FE
4. move the cast logical of DateLiteral to DateUtils

Note: the double cast change will take `insert` logical change ---------

Fixes #issue

## What type of PR is this:
- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by andyziye** [comment]
@Mergify rebase

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 64 / 65 (98.46%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/scalar/ConstantOperator.java|8|9|88.89%|[173]|
|:large_blue_circle:|com/starrocks/common/util/DateUtils.java|49|49|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/DateLiteral.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rewrite/ScalarOperatorFunctions.java|6|6|100.00%|[]|

**Review by stdpain — APPROVED** [review]

**Pull request merged**
