### PR TITLE
[BugFix] fix refresh external table when partition or table doen't exist

### PR DESCRIPTION
**Pull request by stephen-shelby**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #
https://github.com/StarRocks/starrocks/issues/13771

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

### CODE REVIEW

**Comment by stephen-shelby** [comment]
run starrocks_admit_test

**Comment by stephen-shelby** [comment]
run starrocks_fe_unittest

**Comment by stephen-shelby** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 1 / 36 (02.78%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/connector/hive/CachingHiveMetastore.java|0|19|00.00%|[300, 302, 304, 308, 310, 316, 317, 318, 319, 320, 322, 324, 326, 327, 328, 329, 330, 331, 334]|
|:large_blue_circle:|com/starrocks/connector/hive/CacheUpdateProcessor.java|1|17|05.88%|[67, 75, 76, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 89, 137, 165]|

**Review by Youngwb — APPROVED** [review]

**Review by Astralidea — APPROVED** [review]

**Comment by stephen-shelby** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
