### PR TITLE
[Refactor] Refactor lake table storage cache info

### PR DESCRIPTION
**Pull request by wyb**
## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [x] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

1. Only save partition cache info in PartitionInfo.
2. Directly use ShardStorageInfo to save table storage group and default cache info.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 76 / 84 (90.48%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/common/proc/PartitionsProcDir.java|0|4|00.00%|[290, 291, 292, 293]|
|:large_blue_circle:|com/starrocks/catalog/CatalogRecycleBin.java|5|7|71.43%|[661, 662]|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|8|9|88.89%|[4160]|
|:large_blue_circle:|com/starrocks/lake/LakeTable.java|13|14|92.86%|[73]|
|:large_blue_circle:|com/starrocks/lake/StorageCacheInfo.java|15|15|100.00%|[]|
|:large_blue_circle:|com/starrocks/alter/LakeTableAlterJobV2Builder.java|8|8|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/OlapTable.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/RangePartitionInfo.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/lake/StorageInfo.java|6|6|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/PartitionInfo.java|6|6|100.00%|[]|
|:large_blue_circle:|com/starrocks/persist/PartitionPersistInfoV2.java|5|5|100.00%|[]|
|:large_blue_circle:|com/starrocks/persist/RangePartitionPersistInfo.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/SingleRangePartitionDesc.java|2|2|100.00%|[]|

**Comment by wyb** [comment]
run starrocks_admit_test

**Comment by wyb** [comment]
run starrocks_fe_unittest

**Comment by wyb** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 74 / 82 (90.24%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/common/proc/PartitionsProcDir.java|0|4|00.00%|[290, 291, 292, 293]|
|:large_blue_circle:|com/starrocks/catalog/CatalogRecycleBin.java|5|7|71.43%|[661, 662]|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|8|9|88.89%|[4160]|
|:large_blue_circle:|com/starrocks/lake/LakeTable.java|11|12|91.67%|[73]|
|:large_blue_circle:|com/starrocks/lake/StorageCacheInfo.java|15|15|100.00%|[]|
|:large_blue_circle:|com/starrocks/alter/LakeTableAlterJobV2Builder.java|8|8|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/OlapTable.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/RangePartitionInfo.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/lake/StorageInfo.java|6|6|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/PartitionInfo.java|6|6|100.00%|[]|
|:large_blue_circle:|com/starrocks/persist/PartitionPersistInfoV2.java|5|5|100.00%|[]|
|:large_blue_circle:|com/starrocks/persist/RangePartitionPersistInfo.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/SingleRangePartitionDesc.java|2|2|100.00%|[]|

**Review by sduzh — APPROVED** [review]

**Review by kevincai — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Pull request merged**
