### PR TITLE
[Enhancement] add more error msg for restore if schema check fail (#26794)

### LINKED ISSUE #26794: [Enhancement] add more error msg for restore if schema check fail
add more error msg for restore if schema check fail.

### PR DESCRIPTION
**Pull request by srlch**
Fixes #26794

## What type of PR is this:
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [x] 3.0
  - [x] 2.5
  - [ ] 2.4

### CODE REVIEW

**Review by Astralidea — DISMISSED** [review]

**Review by gengjun-git — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 0 / 66 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/OlapTable.java|0|50|00.00%|[1380, 1381, 1382, 1385, 1386, 1388, 1389, 1390, 1393, 1394, 1395, 1396, 1397, 1398, 1399, 1401, 1402, 1404, 1405, 1406, 1409, 1410, 1411, 1412, 1413, 1414, 1415, 1419, 1420, 1422, 1423, 1424, 1425, 1426, 1430, 1431, 1432, 1433, 1434, 1435, 1436, 1437, 1438, 1439, 1440, 1441, 1442, 1443, 1445, 1447]|
|:large_blue_circle:|com/starrocks/backup/RestoreJob.java|0|16|00.00%|[516, 518, 521, 522, 523, 524, 525, 526, 527, 528, 533, 534, 537, 540, 554, 556]|

**Review by chaoyli — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 0 / 66 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/OlapTable.java|0|50|00.00%|[1458, 1459, 1460, 1463, 1464, 1466, 1467, 1468, 1471, 1472, 1473, 1474, 1475, 1476, 1477, 1479, 1480, 1482, 1483, 1484, 1487, 1488, 1489, 1490, 1491, 1492, 1493, 1497, 1498, 1500, 1501, 1502, 1503, 1504, 1508, 1509, 1510, 1511, 1512, 1513, 1514, 1515, 1516, 1517, 1518, 1519, 1520, 1521, 1523, 1525]|
|:large_blue_circle:|com/starrocks/backup/RestoreJob.java|0|16|00.00%|[517, 519, 522, 523, 524, 525, 526, 527, 528, 529, 534, 535, 538, 541, 555, 557]|

**Review by Astralidea — APPROVED** [review]

**Review by gengjun-git — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 0 / 66 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/OlapTable.java|0|50|00.00%|[1469, 1470, 1471, 1474, 1475, 1477, 1478, 1479, 1482, 1483, 1484, 1485, 1486, 1487, 1488, 1490, 1491, 1493, 1494, 1495, 1498, 1499, 1500, 1501, 1502, 1503, 1504, 1508, 1509, 1511, 1512, 1513, 1514, 1515, 1519, 1520, 1521, 1522, 1523, 1524, 1525, 1526, 1527, 1528, 1529, 1530, 1531, 1532, 1534, 1536]|
|:large_blue_circle:|com/starrocks/backup/RestoreJob.java|0|16|00.00%|[517, 519, 522, 523, 524, 525, 526, 527, 528, 529, 534, 535, 538, 541, 555, 557]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 0 / 66 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/OlapTable.java|0|50|00.00%|[1469, 1470, 1471, 1474, 1475, 1477, 1478, 1479, 1482, 1483, 1484, 1485, 1486, 1487, 1488, 1490, 1491, 1493, 1494, 1495, 1498, 1499, 1500, 1501, 1502, 1503, 1504, 1508, 1509, 1511, 1512, 1513, 1514, 1515, 1519, 1520, 1521, 1522, 1523, 1524, 1525, 1526, 1527, 1528, 1529, 1530, 1531, 1532, 1534, 1536]|
|:large_blue_circle:|com/starrocks/backup/RestoreJob.java|0|16|00.00%|[517, 519, 522, 523, 524, 525, 526, 527, 528, 529, 534, 535, 538, 541, 555, 557]|

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
