### PR TITLE
[BugFix] Forbid partition-related parameters for non-partitioned materialized …

### LINKED ISSUE #18739: Materialized view refresh failed
### Steps to reproduce the behavior (Required)
1. CREATE TABLE goods(
    item_id1          INT,
    item_name         STRING,
    price             FLOAT
) DISTRIBUTED BY HASH(item_id1)
PROPERTIES("replication_num" = "1");
2.CREATE MATERIALIZED VIEW order_mv
DISTRIBUTED BY HASH(`item_id1`) BUCKETS 12
PROPERTIES (
  "partition_refresh_number" = "10"
)
REFRESH ASYNC
AS SELECT
    item_id1,
    sum(price) as total
FROM goods
GROUP BY item_id1;

### Expected behavior (Required)
refresh success.
### Real behavior (Required)
2023-02-28 09:33:45,248 WARN (pool-19-thread-22|2545559) [TaskRunExecutor.lambda$executeTaskRun$0():41] failed to execute TaskRun.
java.lang.IllegalArgumentException: null
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:130) ~[spark-dpp-1.0.0.jar:?]
        at com.starrocks.catalog.OlapTable.getRangePartitionMap(OlapTable.java:683) ~[starrocks-fe.jar:?]
        at com.starrocks.scheduler.PartitionBasedMaterializedViewRefreshProcessor.filterPartitionByRefreshNumber(PartitionBasedMaterializedViewRefreshProcessor.java:183) ~[starrocks-fe.jar:?]
        at com.starrocks.scheduler.PartitionBasedMaterializedViewRefreshProcessor.processTaskRun(PartitionBasedMaterializedViewRefreshProcessor.java:151) ~[starrocks-fe.jar:?]
        at com.starrocks.scheduler.TaskRun.executeTaskRun(TaskRun.java:113) ~[starrocks-fe.jar:?]
        at com.starrocks.scheduler.TaskRunExecutor.lambda$executeTaskRun$0(TaskRunExecutor.java:34) ~[starrocks-fe.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) [?:1.8.0_144]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_144]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_144]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
2.5.1

### PR DESCRIPTION
**Pull request by Astralidea**
…views

## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #18739

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 3.0
  - [x] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Comment by Astralidea** [comment]
run all

**Comment by Astralidea** [comment]
run all

**Comment by Astralidea** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 4 / 7 (57.14%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|4|7|57.14%|[3479, 3488, 3489]|

**Review by ABingHuang — APPROVED** [review]
LGTM

**Review by gengjun-git — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
