### PR TITLE
[Refactor] move files in fe external dir to connector dir

### PR DESCRIPTION
**Pull request by stephen-shelby**
## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [x] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

move hive/hudi/delta/iceberg in external to connector equivalent.  If other directories need to be adjusted, please adjust them in the corresponding sub dir.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by stephen-shelby** [comment]
run starrocks_admit_test

**Review by Youngwb — DISMISSED** [review]

**Comment by stephen-shelby** [comment]
run starrocks_admit_test

**Comment by stephen-shelby** [comment]
run starrocks_fe_unittest

**Comment by stephen-shelby** [comment]
run starrocks_admit_test

**Comment by stephen-shelby** [comment]
run starrocks_admit_test

**Comment by stephen-shelby** [comment]
run starrocks_admit_test

**Comment by stephen-shelby** [comment]
run starrocks_fe_unittest

**Comment by stephen-shelby** [comment]
run starrocks_fe_unittest

**Review by Youngwb — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 0 / 30 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/connector/hive/glue/metastore/AWSGlueMetastoreFactory.java|0|2|00.00%|[22, 23]|
|:large_blue_circle:|com/starrocks/connector/hive/glue/metastore/AWSGlueMetastoreCacheDecorator.java|0|10|00.00%|[53, 55, 56, 59, 60, 74, 76, 77, 80, 81]|
|:large_blue_circle:|com/starrocks/connector/hive/glue/metastore/GlueMetastoreClientDelegate.java|0|10|00.00%|[161, 302, 348, 420, 472, 522, 531, 607, 873, 915]|
|:large_blue_circle:|com/starrocks/connector/hive/glue/util/BatchCreatePartitionsHelper.java|0|1|00.00%|[58]|
|:large_blue_circle:|com/starrocks/connector/hive/glue/metastore/AWSGlueClientFactory.java|0|7|00.00%|[38, 39, 70, 80, 81, 83, 85]|

**Comment by wanpengfei-git** [comment]
starrocks_be_unittest succeeded.

**Review by gengjun-git — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by stephen-shelby** [comment]
run starrocks_admit_test

**Pull request merged**
