### PR TITLE
[BugFix] fixup one-phase aggregation fails to use query cache

### PR DESCRIPTION
**Pull request by satanson**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #
These two daily cases fails:
nosetests-3.4 -s --with-xunit --xunit-file=./result/test_query_cache_one_phase_only_one_tablet_py_TestQueryCacheOnePhaseOnlyOneTablet_test_query_cache_one_phase_only_one_tablet.xml --verbose case/system_case/test_dql/test_query_cache/test_query_cache_one_phase_only_one_tablet.py:TestQueryCacheOnePhaseOnlyOneTablet.test_query_cache_one_phase_only_one_tablet --nologcapture

nosetests-3.4 -s --with-xunit --xunit-file=./result/test_query_cache_one_phase_only_one_partition_group_by_py_TestQueryCacheOnePhaseOnlyOnePartitionGroupBy_test_query_cache_one_phase_only_one_partition_group_by.xml --verbose case/system_case/test_dql/test_query_cache/test_query_cache_one_phase_only_one_partition_group_by.py:TestQueryCacheOnePhaseOnlyOnePartitionGroupBy.test_query_cache_one_phase_only_one_partition_group_by --nologcapture

## Problem Summary(Required) ：

For one-phase agg, ScanRanges must be assigned to each driver sequences, FragmentNormalizer flip the flag.
## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Review by kangkaisen — DISMISSED** [review]

**Comment by satanson** [comment]
run starrocks_fe_unittest

**Review by ZiheLiu — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by satanson** [comment]
@mergifyio rebase

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/planner/PlanFragment.java|1|1|100.00%|[]|

**Review by ZiheLiu — APPROVED** [review]

**Review by kangkaisen — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Pull request merged**
