### PR TITLE
Fix date formatter different from be

### PR DESCRIPTION
**Pull request by Seaven**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] others

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

bugs:
```
mysql> select date_format('2021-03-04 22:37:45', '%w') from tt;
+------------------------------------------+
| date_format('2021-03-04 22:37:45', '%w') |
+------------------------------------------+
| 7                                     |
+------------------------------------------+

mysql> select date_format('2021-03-04 22:37:45', '%p') from tt;
+------------------------------------------+
| date_format('2021-03-04 22:37:45', '%p') |
+------------------------------------------+
| 下午                                     |
+------------------------------------------+
```

except:
```
mysql> select date_format('2021-03-04 22:37:45', '%w') from tt;
+------------------------------------------+
| date_format('2021-03-04 22:37:45', '%w') |
+------------------------------------------+
| 0                                     |
+------------------------------------------+

mysql> select date_format('2021-03-04 22:37:45', '%p') from tt;
+------------------------------------------+
| date_format('2021-03-04 22:37:45', '%p') |
+------------------------------------------+
| PM                                     |
+------------------------------------------+
```

### CODE REVIEW

**Review by kangkaisen — DISMISSED** [review]

**Comment by Seaven** [comment]
run starrocks_fe_unittest

**Comment by Seaven** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 4 / 4 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/scalar/ConstantOperator.java|3|3|100.00%|
|:large_blue_circle:|com/starrocks/common/util/DateUtils.java|1|1|100.00%|

**Review by kangkaisen — APPROVED** [review]

**Review by Youngwb — APPROVED** [review]

**Review by HangyuanLiu — APPROVED** [review]

**Comment by Seaven** [comment]
backport branch-2.1

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 4 / 4 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/scalar/ConstantOperator.java|3|3|100.00%|
|:large_blue_circle:|com/starrocks/common/util/DateUtils.java|1|1|100.00%|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 4 / 4 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/scalar/ConstantOperator.java|3|3|100.00%|
|:large_blue_circle:|com/starrocks/common/util/DateUtils.java|1|1|100.00%|

**Comment by jaogoy** [comment]
cherry-picked to branch-1.19: https://github.com/StarRocks/starrocks/pull/4165 https://github.com/StarRocks/starrocks/pull/4171

**Comment by jaogoy** [comment]
@Seaven There is no cooresponding issue, so you should comment other cherry-pick PRs here for link, and whether you have cherry-picked to branch-2.1 & branch-2.2

**Pull request merged**
