### PR TITLE
[Refactor]Minor: refactor SchemaChangeHandler

### PR DESCRIPTION
**Pull request by sduzh**
## What type of PR is this：
- [ ] bug
- [ ] feature
- [ ] enhancement
- [x] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 5 / 34 (14.71%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/alter/SchemaChangeHandler.java|5|34|14.71%|[192, 199, 208, 209, 210, 212, 218, 219, 220, 229, 233, 234, 235, 238, 239, 240, 244, 245, 275, 283, 467, 473, 474, 477, 478, 480, 500, 565, 1499]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 29 / 69 (42.03%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/alter/SchemaChangeHandler.java|29|69|42.03%|[190, 197, 206, 207, 208, 210, 216, 217, 218, 227, 231, 232, 233, 236, 237, 238, 242, 243, 273, 281, 465, 471, 472, 475, 476, 478, 498, 563, 892, 894, 944, 955, 956, 960, 961, 976, 977, 981, 982, 1454]|

**Review by wyb — APPROVED** [review]

**Comment by sduzh** [comment]
run starrocks_admit_test

**Review by gengjun-git — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Pull request merged**
