### PR TITLE
[BugFix] Fix iceberg timestamp partition column percision lost

### LINKED ISSUE #21216: Query iceberg datetime columns return empty
### Steps to reproduce the behavior (Required)
spark-sql
1. create table test (k1 int, dt timestamp) using iceberg partitioned by (days(dt));
2. insert into test select 2, cast(date_format('2023-04-06 13:22:30.521000000', 'yyyy-MM-dd HH:mm:ss.SSS') as timestamp);

mysql-client
image

### Expected behavior (Required)
retrun 2023-04-06 14:54:30.048000
### Real behavior (Required)
empty

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - 2b95712

### PR DESCRIPTION
**Pull request by Smith-Cruise**
Fixes https://github.com/StarRocks/starrocks/issues/21216
Replace #21225

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [x] 3.0
  - [ ] 2.5
  - [ ] 2.4

### CODE REVIEW

**Review by stephen-shelby — APPROVED** [review]

**Review by letian-jiang — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 3 / 3 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/connector/iceberg/ScalarOperatorToIcebergExpr.java|3|3|100.00%|[]|

**Review by dirtysalt — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by Smith-Cruise** [comment]
@Mergify backport branch-2.5

**Pull request merged**
