### PR TITLE
[BugFix] Fix bug NPE when show partition after truncate partition

### LINKED ISSUE #17943: [list partition] npe when show partitions after truncate partition
### Steps to reproduce the behavior (Required)
````sql
CREATE TABLE t1 (
                          dt date not null,
                          num int,
                          city varchar(20),
                          name varchar(20)
                        ) ENGINE=OLAP
                        DUPLICATE KEY(dt)
                        COMMENT "OLAP"
                        PARTITION BY LIST (dt) (
                           PARTITION p1 VALUES IN (("2022-04-01")),
                           PARTITION p2 VALUES IN (("2022-04-02")),
                           PARTITION p3 VALUES IN (("2022-04-03"))
                        )
                        DISTRIBUTED BY HASH(dt) BUCKETS 3
                        PROPERTIES (
                        "replication_num" = "1"
                        );
truncate table t1 partition(p2);
show partitions from t1;
````

### Expected behavior (Required)
`query ok`
### Real behavior (Required)
```
2023-02-16 20:14:43,690 WARN (starrocks-mysql-nio-pool-23|794) [StmtExecutor.execute():543] execute Exception, sql show partitions from t1
java.lang.NullPointerException: null
	at com.starrocks.catalog.ListPartitionInfo.multiValuesToString(ListPartitionInfo.java:291) ~[starrocks-fe.jar:?]
	at com.starrocks.catalog.ListPartitionInfo.getValuesFormat(ListPartitionInfo.java:307) ~[starrocks-fe.jar:?]
	at com.starrocks.common.proc.PartitionsProcDir.findRangeOrListValues(PartitionsProcDir.java:431) ~[starrocks-fe.jar:?]
	at com.starrocks.common.proc.PartitionsProcDir.getOlapPartitionInfo(PartitionsProcDir.java:369) ~[starrocks-fe.jar:?]
	at com.starrocks.common.proc.PartitionsProcDir.getOlapPartitionInfos(PartitionsProcDir.java:297) ~[starrocks-fe.jar:?]
	at com.starrocks.common.proc.PartitionsProcDir.getPartitionInfos(PartitionsProcDir.java:266) ~[starrocks-fe.jar:?]
	at com.starrocks.common.proc.PartitionsProcDir.fetchResultByFilter(PartitionsProcDir.java:202) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ShowExecutor.handleShowPartitions(ShowExecutor.java:1543) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ShowExecutor.execute(ShowExecutor.java:294) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.StmtExecutor.handleShow(StmtExecutor.java:1086) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:501) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:342) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:459) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:723) ~[starrocks-fe.jar:?]
	at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:68) ~[starrocks-fe.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
```
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
`MAIN-RELEASE-f256177`

### PR DESCRIPTION
**Pull request by Astralidea**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #17943

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 3.0
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Comment by Astralidea** [comment]
run all

**Comment by Astralidea** [comment]
run all

**Comment by Astralidea** [comment]
run starrocks_fe_unittest

**Comment by Astralidea** [comment]
run starrocks_fe_unittest

**Comment by Astralidea** [comment]
run starrocks_fe_unittest

**Comment by Astralidea** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 15 / 20 (75.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/OlapTable.java|8|11|72.73%|[1619, 1620, 1621]|
|:large_blue_circle:|com/starrocks/catalog/ListPartitionInfo.java|6|8|75.00%|[394, 395]|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|1|1|100.00%|[]|

**Review by gengjun-git — APPROVED** [review]

**Review by ABingHuang — APPROVED** [review]
LGTM

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Pull request merged**
