### PR TITLE
[Enhancement] External olap table support temp partition

### PR DESCRIPTION
**Pull request by xiangguangyxg**
Fixes #issue

## What type of PR is this:
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [x] 3.0
  - [x] 2.5
  - [ ] 2.4

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 0 / 13 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/PartitionType.java|0|1|00.00%|[69]|
|:large_blue_circle:|com/starrocks/leader/LeaderImpl.java|0|5|00.00%|[942, 972, 973, 987, 1014]|
|:large_blue_circle:|com/starrocks/catalog/ExternalOlapTable.java|0|7|00.00%|[398, 437, 438, 554, 556, 557, 558]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 0 / 13 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/PartitionType.java|0|1|00.00%|[69]|
|:large_blue_circle:|com/starrocks/leader/LeaderImpl.java|0|5|00.00%|[942, 972, 973, 987, 1014]|
|:large_blue_circle:|com/starrocks/catalog/ExternalOlapTable.java|0|7|00.00%|[398, 437, 438, 554, 556, 557, 558]|

**Comment by xiangguangyxg** [comment]
run Fe Cover Checker

**Review by wyb — APPROVED** [review]

**Review by Astralidea — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 8 / 9 (88.89%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/ExternalOlapTable.java|3|4|75.00%|[555]|
|:large_blue_circle:|com/starrocks/leader/LeaderImpl.java|5|5|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 8 / 9 (88.89%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/ExternalOlapTable.java|3|4|75.00%|[555]|
|:large_blue_circle:|com/starrocks/leader/LeaderImpl.java|5|5|100.00%|[]|

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
