### PR TITLE
[Enhancement] Add BE decommission and restart related UT

### LINKED ISSUE #10315: [Enhancement] Add backend dicommission/restart and related UT in PseudoCluster
## Enhancement
Add backend dicommission/restart and related UT in PseudoCluster

### PR DESCRIPTION
**Pull request by decster**
## What type of PR is this：
- [ ] bug
- [ ] feature
- [x] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #10315

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 3 / 6 (50.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/clone/TabletScheduler.java|1|3|33.33%|[1096, 1097]|
|:large_blue_circle:|com/starrocks/leader/ReportHandler.java|1|2|50.00%|[242]|
|:large_blue_circle:|com/starrocks/clone/TabletSchedCtx.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 3 / 6 (50.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/clone/TabletScheduler.java|1|3|33.33%|[1096, 1097]|
|:large_blue_circle:|com/starrocks/leader/ReportHandler.java|1|2|50.00%|[242]|
|:large_blue_circle:|com/starrocks/clone/TabletSchedCtx.java|1|1|100.00%|[]|

**Review by Astralidea — APPROVED** [review]

**Comment by decster** [comment]
run starrocks_be_unittest

**Comment by decster** [comment]
run starrocks_fe_unittest

**Comment by decster** [comment]
run starrocks_clang-format

**Comment by decster** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 3 / 6 (50.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/clone/TabletScheduler.java|1|3|33.33%|[1096, 1097]|
|:large_blue_circle:|com/starrocks/leader/ReportHandler.java|1|2|50.00%|[242]|
|:large_blue_circle:|com/starrocks/clone/TabletSchedCtx.java|1|1|100.00%|[]|

**Review by chaoyli — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by decster** [comment]
run starrocks_admit_test

**Pull request merged**
