### PR TITLE
[Enhancement] Support query dump for hive

### PR DESCRIPTION
**Pull request by Youngwb**
## What type of PR is this：
- [ ] bug
- [ ] feature
- [x] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

QueryDump can dump necessary info of optimizer to replay the plan in UT. for hive table, we need info like
1. Partition Key
2. Hive Partition meta info
3. Hive Partition column Statistics
4. table stats
5. partition stats
6. BE core stats

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 250 / 363 (68.87%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/Resource.java|0|1|00.00%|[134]|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|0|2|00.00%|[2154, 2167]|
|:large_blue_circle:|com/starrocks/sql/optimizer/dump/HiveMetaStoreTableDumpInfo.java|0|15|00.00%|[16, 20, 23, 27, 30, 34, 37, 41, 44, 48, 51, 55, 58, 62, 65]|
|:large_blue_circle:|com/starrocks/external/hive/HiveRepository.java|0|5|00.00%|[188, 189, 190, 192, 193]|
|:large_blue_circle:|com/starrocks/sql/optimizer/dump/QueryDumpSerializer.java|8|31|25.81%|[41, 42, 43, 44, 45, 60, 62, 63, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79]|
|:large_blue_circle:|com/starrocks/sql/optimizer/dump/HiveTableDumpInfo.java|86|148|58.11%|[112, 119, 120, 121, 122, 123, 124, 125, 127, 129, 130, 131, 132, 133, 134, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 159, 160, 163, 164, 165, 166, 167, 168, 171, 172, 173, 174, 175, 176, 180, 181, 182, 183, 184, 185, 188, 189, 190, 191, 192, 193, 196]|
|:large_blue_circle:|com/starrocks/external/hive/HiveColumnStats.java|7|9|77.78%|[73, 75]|
|:large_blue_circle:|com/starrocks/sql/optimizer/dump/DumpInfo.java|9|11|81.82%|[17, 38]|
|:large_blue_circle:|com/starrocks/catalog/PartitionKey.java|20|21|95.24%|[251]|
|:large_blue_circle:|com/starrocks/catalog/Table.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/HiveResource.java|10|10|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/HiveTable.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/statistics/StatisticsCalculator.java|12|12|100.00%|[]|
|:large_blue_circle:|com/starrocks/external/hive/events/MetastoreEventsProcessor.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/system/BackendCoreStat.java|7|7|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/QueryAnalyzer.java|12|12|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/dump/QueryDumpInfo.java|30|30|100.00%|[]|
|:large_blue_circle:|com/starrocks/persist/gson/GsonUtils.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/external/RemoteScanRangeLocations.java|6|6|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/RemoteScanPartitionPruneRule.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/dump/QueryDumpDeserializer.java|31|31|100.00%|[]|

**Comment by DorianZheng** [comment]
Is it another PR to consider `Connector` case?

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 250 / 372 (67.20%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/http/rest/QueryDumpAction.java|0|9|00.00%|[49, 51, 52, 54, 55, 56, 58, 59, 60]|
|:large_blue_circle:|com/starrocks/catalog/Resource.java|0|1|00.00%|[134]|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|0|2|00.00%|[2154, 2167]|
|:large_blue_circle:|com/starrocks/sql/optimizer/dump/HiveMetaStoreTableDumpInfo.java|0|15|00.00%|[16, 20, 23, 27, 30, 34, 37, 41, 44, 48, 51, 55, 58, 62, 65]|
|:large_blue_circle:|com/starrocks/external/hive/HiveRepository.java|0|5|00.00%|[188, 189, 190, 192, 193]|
|:large_blue_circle:|com/starrocks/sql/optimizer/dump/QueryDumpSerializer.java|8|31|25.81%|[41, 42, 43, 44, 45, 60, 62, 63, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79]|
|:large_blue_circle:|com/starrocks/sql/optimizer/dump/HiveTableDumpInfo.java|86|148|58.11%|[112, 119, 120, 121, 122, 123, 124, 125, 127, 129, 130, 131, 132, 133, 134, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 159, 160, 163, 164, 165, 166, 167, 168, 171, 172, 173, 174, 175, 176, 180, 181, 182, 183, 184, 185, 188, 189, 190, 191, 192, 193, 196]|
|:large_blue_circle:|com/starrocks/external/hive/HiveColumnStats.java|7|9|77.78%|[73, 75]|
|:large_blue_circle:|com/starrocks/sql/optimizer/dump/DumpInfo.java|9|11|81.82%|[17, 38]|
|:large_blue_circle:|com/starrocks/catalog/PartitionKey.java|20|21|95.24%|[251]|
|:large_blue_circle:|com/starrocks/catalog/Table.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/HiveResource.java|10|10|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/HiveTable.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/statistics/StatisticsCalculator.java|12|12|100.00%|[]|
|:large_blue_circle:|com/starrocks/external/hive/events/MetastoreEventsProcessor.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/system/BackendCoreStat.java|7|7|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/QueryAnalyzer.java|12|12|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/dump/QueryDumpInfo.java|30|30|100.00%|[]|
|:large_blue_circle:|com/starrocks/persist/gson/GsonUtils.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/external/RemoteScanRangeLocations.java|6|6|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/RemoteScanPartitionPruneRule.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/dump/QueryDumpDeserializer.java|31|31|100.00%|[]|

**Comment by Youngwb** [comment]
> Is it another PR to consider `Connector` case?

I support `connector` case in the case, user can get the query dump using hive external catalog

**Comment by Youngwb** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 250 / 375 (66.67%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/http/rest/QueryDumpAction.java|0|9|00.00%|[49, 51, 52, 54, 55, 56, 58, 59, 60]|
|:large_blue_circle:|com/starrocks/catalog/Resource.java|0|1|00.00%|[134]|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|0|5|00.00%|[2154, 2156, 2157, 2158, 2170]|
|:large_blue_circle:|com/starrocks/sql/optimizer/dump/HiveMetaStoreTableDumpInfo.java|0|15|00.00%|[16, 20, 23, 27, 30, 34, 37, 41, 44, 48, 51, 55, 58, 62, 65]|
|:large_blue_circle:|com/starrocks/external/hive/HiveRepository.java|0|5|00.00%|[188, 189, 190, 192, 193]|
|:large_blue_circle:|com/starrocks/sql/optimizer/dump/QueryDumpSerializer.java|8|31|25.81%|[41, 42, 43, 44, 45, 60, 62, 63, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79]|
|:large_blue_circle:|com/starrocks/sql/optimizer/dump/HiveTableDumpInfo.java|86|148|58.11%|[112, 119, 120, 121, 122, 123, 124, 125, 127, 129, 130, 131, 132, 133, 134, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 159, 160, 163, 164, 165, 166, 167, 168, 171, 172, 173, 174, 175, 176, 180, 181, 182, 183, 184, 185, 188, 189, 190, 191, 192, 193, 196]|
|:large_blue_circle:|com/starrocks/external/hive/HiveColumnStats.java|7|9|77.78%|[73, 75]|
|:large_blue_circle:|com/starrocks/sql/optimizer/dump/DumpInfo.java|9|11|81.82%|[17, 38]|
|:large_blue_circle:|com/starrocks/catalog/PartitionKey.java|20|21|95.24%|[251]|
|:large_blue_circle:|com/starrocks/catalog/Table.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/HiveResource.java|10|10|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/HiveTable.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/statistics/StatisticsCalculator.java|12|12|100.00%|[]|
|:large_blue_circle:|com/starrocks/external/hive/events/MetastoreEventsProcessor.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/system/BackendCoreStat.java|7|7|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/QueryAnalyzer.java|12|12|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/dump/QueryDumpInfo.java|30|30|100.00%|[]|
|:large_blue_circle:|com/starrocks/persist/gson/GsonUtils.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/external/RemoteScanRangeLocations.java|6|6|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/RemoteScanPartitionPruneRule.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/dump/QueryDumpDeserializer.java|31|31|100.00%|[]|

**Review by Seaven — DISMISSED** [review]

**Review by HangyuanLiu — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by Youngwb** [comment]
run starrocks_admit_test

**Comment by Youngwb** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 250 / 375 (66.67%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/http/rest/QueryDumpAction.java|0|9|00.00%|[49, 51, 52, 54, 55, 56, 58, 59, 60]|
|:large_blue_circle:|com/starrocks/catalog/Resource.java|0|1|00.00%|[134]|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|0|5|00.00%|[2154, 2156, 2157, 2158, 2170]|
|:large_blue_circle:|com/starrocks/sql/optimizer/dump/HiveMetaStoreTableDumpInfo.java|0|15|00.00%|[16, 20, 23, 27, 30, 34, 37, 41, 44, 48, 51, 55, 58, 62, 65]|
|:large_blue_circle:|com/starrocks/external/hive/HiveRepository.java|0|5|00.00%|[188, 189, 190, 192, 193]|
|:large_blue_circle:|com/starrocks/sql/optimizer/dump/QueryDumpSerializer.java|8|31|25.81%|[41, 42, 43, 44, 45, 60, 62, 63, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79]|
|:large_blue_circle:|com/starrocks/sql/optimizer/dump/HiveTableDumpInfo.java|86|148|58.11%|[112, 119, 120, 121, 122, 123, 124, 125, 127, 129, 130, 131, 132, 133, 134, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 159, 160, 163, 164, 165, 166, 167, 168, 171, 172, 173, 174, 175, 176, 180, 181, 182, 183, 184, 185, 188, 189, 190, 191, 192, 193, 196]|
|:large_blue_circle:|com/starrocks/external/hive/HiveColumnStats.java|7|9|77.78%|[73, 75]|
|:large_blue_circle:|com/starrocks/sql/optimizer/dump/DumpInfo.java|9|11|81.82%|[17, 38]|
|:large_blue_circle:|com/starrocks/catalog/PartitionKey.java|20|21|95.24%|[251]|
|:large_blue_circle:|com/starrocks/catalog/Table.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/HiveResource.java|10|10|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/HiveTable.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/statistics/StatisticsCalculator.java|12|12|100.00%|[]|
|:large_blue_circle:|com/starrocks/external/hive/events/MetastoreEventsProcessor.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/system/BackendCoreStat.java|7|7|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/QueryAnalyzer.java|12|12|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/dump/QueryDumpInfo.java|30|30|100.00%|[]|
|:large_blue_circle:|com/starrocks/persist/gson/GsonUtils.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/external/RemoteScanRangeLocations.java|6|6|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/RemoteScanPartitionPruneRule.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/dump/QueryDumpDeserializer.java|31|31|100.00%|[]|

**Review by Seaven — APPROVED** [review]

**Review by HangyuanLiu — APPROVED** [review]

**Pull request merged**
