### PR TITLE
[BugFix] Fix unsupported type reporting NPE

### LINKED ISSUE #20999: Unsupported type reports NPE
### Steps to reproduce the behavior (Required)
1. CREATE TABLE ods_warehoused (
 warehouse_id                                bigint(20)                 COMMENT        ''
,company_id                                        bigint(20)                 COMMENT        ''
,company_name                                string                        COMMENT        ''
,is_sort_express_by_cost        tinyint(1)                COMMENT        ''
,is_order_intercepted                tinyint(1)                COMMENT        ''
,intercept_time_type                tinyint(3)                 COMMENT        ''
,intercept_time                                time                        COMMENT        ''
,intercept_begin_time                time                        COMMENT        ''
,intercept_end_time                        time                        COMMENT        ''

)
PRIMARY KEY(warehouse_id)
COMMENT ""
DISTRIBUTED BY HASH(warehouse_id)
PROPERTIES (
"replication_num" = "1"
);
### Expected behavior (Required)
report error
### Real behavior (Required)
Unexpected exception: null
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
2.3.3

### PR DESCRIPTION
**Pull request by Astralidea**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #20999

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 3.0
  - [x] 2.5
  - [x] 2.4
  - [x] 2.3

### CODE REVIEW

**Review by imay — APPROVED** [review]

**Review by decster — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.4

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.3

**Pull request merged**
