### PR TITLE
[Refactor] Decoupling ObjectType and PrivilegeType in RBAC privilege

### PR DESCRIPTION
**Pull request by HangyuanLiu**
## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [x] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Comment by HangyuanLiu** [comment]
run starrocks_admit_test

**Review by Astralidea — APPROVED** [review]

**Comment by nshangyiming** [comment]
Could you explain why you want to do this refactoring in the pr description, i think it will help the others to better understand it. @HangyuanLiu

**Review by dirtysalt — APPROVED** [review]

**Comment by HangyuanLiu** [comment]
run starrocks_fe_unittest

**Comment by HangyuanLiu** [comment]
run starrocks_fe_unittest

**Review by nshangyiming — APPROVED** [review]

**Pull request merged**
