### PR TITLE
[BugFix] Clear dumped_shard_idxes in meta before dump a new snapshot

### LINKED ISSUE #10891: [persistent index] BE crash because of bad_alloc when dml&ddl&dql on primary table
### Steps to reproduce the behavior (Required)
DDL & DML & DQL operations execute concurrently on primary table, BE crash because of bad_alloc:

```
tcmalloc: large alloc 24996958761091072 bytes == (nil) @  0x5f9cadf 0x622f19c 0x2574300 0x617c945 0x2247f94 0x225f41c 0x22608d7 0x2262237 0x1fb16ec 0x1fb246f 0x1e36896 0x1e38aed 0x262f5f5 0x262aa2a 0x7f978c788ea5
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
query_id:00000000-0000-0000-0000-000000000000, fragment_instance:00000000-0000-0000-0000-000000000000
*** Aborted at 1662387048 (unix time) try "date -d @1662387048" if you are using GNU date ***
PC: @     0x7f978bcdb387 __GI_raise
*** SIGABRT (@0x3e8000090f5) received by PID 37109 (TID 0x7f97749d3700) from PID 37109; stack trace: ***
    @          0x47744b2 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7f978c790630 (unknown)
    @     0x7f978bcdb387 __GI_raise
    @     0x7f978bcdca78 __GI_abort
    @          0x1c134d9 _ZN9__gnu_cxx27__verbose_terminate_handlerEv.cold
    @          0x617c3f6 __cxxabiv1::__terminate()
    @          0x617c461 std::terminate()
    @          0x617c5b4 __cxa_throw
    @          0x1c133e0 _Znwm.cold
    @          0x226eaf5 starrocks::FixedMutableIndex<>::load_snapshot()
    @          0x2247f94 starrocks::ShardByLengthMutableIndex::load()
    @          0x225f41c starrocks::PersistentIndex::_load()
    @          0x22608d7 starrocks::PersistentIndex::load()
    @          0x2262237 starrocks::PersistentIndex::load_from_tablet()
    @          0x1fb16ec starrocks::PrimaryIndex::_do_load()
    @          0x1fb246f starrocks::PrimaryIndex::load()
    @          0x1e36896 starrocks::TabletUpdates::_apply_compaction_commit()
    @          0x1e38aed starrocks::TabletUpdates::do_apply()
    @          0x262f5f5 starrocks::ThreadPool::dispatch_thread()
    @          0x262aa2a starrocks::Thread::supervise_thread()
    @     0x7f978c788ea5 start_thread
    @     0x7f978bda3b0d __clone
    @                0x0 (unknown)
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
mysql> select current_version();
+----------------------------+
| current_version()          |
+----------------------------+
| BRANCH-2.4-RELEASE 0415c27 |
+----------------------------+
1 row in set (0.24 sec)
```

### PR DESCRIPTION
**Pull request by sevev**
## What type of PR is this：
- [x] bugfix
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes https://github.com/StarRocks/starrocks/issues/10891

## Problem Summary(Required) ：

When we dump a new snapshot of ShardByLengthMutableIndex, we need to clear up`dumped_shard_idxes` before adding the shard_idxes, otherwise it will cause unpredictable errors when loading snapshot.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by sevev** [comment]
run fix_error_snapshot_size

**Comment by sevev** [comment]
run starrocks_admit_test

**Comment by wangruin** [comment]
run starrocks_be_unittest

**Comment by sevev** [comment]
run starrocks_be_unittest

**Review by Linkerist — APPROVED** [review]

**Review by decster — APPROVED** [review]

**Review by chaoyli — APPROVED** [review]

**Comment by sevev** [comment]
@mergify backport branch-2.4

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Pull request merged**
