### PR TITLE
[Enhancement] add more info in logging for the cases of exec plan fragment failed and clone

### PR DESCRIPTION
**Pull request by decster**
Signed-off-by: Binglin Chang <decstery@gmail.com>

## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Problem Summary(Required) ：

Add related BE hostname to err message when query failed;
Add version info in be log when clone finished

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 2.5
  - [x] 2.4
  - [x] 2.3
  - [ ] 2.2

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 6 / 6 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/Coordinator.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/clone/TabletSchedCtx.java|5|5|100.00%|[]|

**Review by murphyatwork — APPROVED** [review]

**Review by chaoyli — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by decster** [comment]
run starrocks_admit_test

**Comment by decster** [comment]
run starrocks_admit_test

**Comment by decster** [comment]
@mergify backport branch-2.5

**Comment by decster** [comment]
@mergify backport branch-2.4

**Comment by decster** [comment]
@mergify backport branch-2.3

**Pull request merged**
