### PR TITLE
[Enhancement] Improve iceberg storage cloud configuration and make tabular more generic

### PR DESCRIPTION
**Pull request by Smith-Cruise**
Remove hard coding about when to use tabular authentication
Remove hard coding about selecting FileIO implement, we using resolving file io instead.

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 13 / 16 (81.25%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/connector/iceberg/rest/IcebergRESTCatalog.java|0|1|00.00%|[83]|
|:large_blue_circle:|com/starrocks/planner/IcebergScanNode.java|6|8|75.00%|[118, 381]|
|:large_blue_circle:|com/starrocks/planner/IcebergTableSink.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/connector/iceberg/io/IcebergCachingFileIO.java|4|4|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 13 / 16 (81.25%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/connector/iceberg/rest/IcebergRESTCatalog.java|0|1|00.00%|[83]|
|:large_blue_circle:|com/starrocks/planner/IcebergScanNode.java|6|8|75.00%|[118, 381]|
|:large_blue_circle:|com/starrocks/planner/IcebergTableSink.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/connector/iceberg/io/IcebergCachingFileIO.java|4|4|100.00%|[]|

**Review by stephen-shelby — APPROVED** [review]

**Review by dirtysalt — APPROVED** [review]

**Comment by Smith-Cruise** [comment]
@Mergify backport branch-3.1

**Pull request merged**
