### PR TITLE
[Lake] Support lake tablet statistic collection

### PR DESCRIPTION
**Pull request by wyb**
## What type of PR is this：
- [ ] bug
- [x] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

FE periodically collect lake tablet statistic, such as num rows and data size.
Num rows statistic is used in CBO optimizer.

### CODE REVIEW

**Review by kevincai — DISMISSED** [review]

**Comment by wyb** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 94 / 129 (72.87%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/lake/Utils.java|0|1|00.00%|[33]|
|:large_blue_circle:|com/starrocks/rpc/LakeServiceClient.java|0|4|00.00%|[65, 66, 67, 68]|
|:large_blue_circle:|com/starrocks/catalog/TabletStatMgr.java|94|124|75.81%|[117, 118, 119, 121, 122, 123, 125, 126, 128, 129, 130, 132, 133, 135, 138, 171, 179, 187, 188, 204, 212, 226, 238, 260, 261, 262, 268, 277, 285, 286]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 99 / 129 (76.74%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/lake/Utils.java|0|1|00.00%|[34]|
|:large_blue_circle:|com/starrocks/rpc/LakeServiceClient.java|0|4|00.00%|[72, 73, 74, 75]|
|:large_blue_circle:|com/starrocks/catalog/TabletStatMgr.java|99|124|79.84%|[123, 125, 126, 128, 129, 130, 132, 133, 135, 138, 171, 179, 187, 188, 204, 212, 226, 238, 260, 261, 262, 268, 277, 285, 286]|

**Review by kevincai — APPROVED** [review]

**Review by tracymacding — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by sduzh — APPROVED** [review]

**Review by gengjun-git — APPROVED** [review]

**Pull request merged**
