### PR TITLE
[WIP] test build image in PR

### PR DESCRIPTION
**Pull request by wangruin**
## What type of PR is this：
- [ ] bug
- [ ] feature
- [ ] enhancement
- [x] others

This PR is just for testing

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by imay — APPROVED** [review]

**Comment by wangruin** [comment]
run starrocks_be_unittest

**Comment by wangruin** [comment]
run starrocks_be_unittest

**Comment by wangruin** [comment]
run starrocks_be_unittest image

**Comment by wangruin** [comment]
run starrocks_be_unittest image

**Comment by wangruin** [comment]
run starrocks_be_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wangruin** [comment]
run starrocks_be_build

**Comment by wanpengfei-git** [comment]
starrocks_be_unittest succeeded.

**Comment by wanpengfei-git** [comment]
starrocks_be_unittest succeeded.

**Comment by wanpengfei-git** [comment]
starrocks_be_unittest succeeded.

**Comment by wanpengfei-git** [comment]
starrocks_be_unittest succeeded.

**Pull request closed without merging**
