### PR TITLE
Fix predicates pushdown in external tables (#3803)

### PR DESCRIPTION
**Pull request by silverbullet233**
(cherry picked from commit 9351c372e680e356f3f76864e11d7fe7372ae28a)

## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] others

## Which issues of this PR fixes ：

Fixes #

### CODE REVIEW

**Review by kangkaisen — DISMISSED** [review]

**Comment by silverbullet233** [comment]
run starrocks_fe_unittest

**Comment by silverbullet233** [comment]
run starrocks_be_unittest

**Comment by silverbullet233** [comment]
run starrocks_be_unittest

**Comment by silverbullet233** [comment]
run starrocks_be_unittest

**Review by kangkaisen — APPROVED** [review]

**Pull request merged**
