### PR TITLE
refactor sorting in aggregator

### PR DESCRIPTION
**Pull request by murphyatwork**
## What type of PR is this：
- [ ] bug
- [ ] feature
- [x] enhancement
- [ ] others

## Problem Summary(Required) ：

Refactor sorting in aggregator.

### CODE REVIEW

**Review by Seaven — APPROVED** [review]
LGTM, but I want to know what meanings about `Tie`

**Review by kangkaisen — APPROVED** [review]

**Comment by kangkaisen** [comment]
would better merge this PR after  daily test pass

**Comment by mofeiatwork** [comment]
> LGTM, but I want to know what meanings about `Tie`

There's comment in the `sort_permute.h`.

**Comment by mofeiatwork** [comment]
> would better merge this PR after daily test pass

Fine

**Pull request merged**
