### PR TITLE
[BugFix] Fix some daily test bug

### PR DESCRIPTION
**Pull request by sevev**
This pr fix two bugs: https://github.com/StarRocks/starrocks/issues/31333, https://github.com/StarRocks/starrocks/issues/31642

1. First issue(https://github.com/StarRocks/starrocks/issues/31333) is when we create a scalar type column and all value is null. In order to save disk usage, we don't write data in data page but only write null flags. And the scalar column type column encoded type is BITSHUFFLE by default right now. When we try to read data page, we will find the data page is empty and `bitshuffle_page_reader` will return error but this could be reasonable.
2. Second issue(https://github.com/StarRocks/starrocks/issues/31642) is when we do update sql for primary key table which primary key and sort key is separated, if we update sort key column which is not primary key column, the update sql will failed. The reason is when we do column mode partial update, we modify the `sort_key_idx` of partial table schema but ignore the sort key property in `TabletColumn`. So the following check in `SegmentWriter` will fail.

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:heart_eyes: **pass** : 6 / 6 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/storage/tablet_schema.cpp|3|3|100.00%|[]|
|:large_blue_circle:|src/storage/rowset/bitshuffle_page.h|3|3|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 1 / 7 (14.29%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/storage/tablet_schema.h|0|4|00.00%|[294, 295, 299, 300]|
|:large_blue_circle:|src/storage/rowset/bitshuffle_page.h|1|3|33.33%|[311, 312]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 1 / 7 (14.29%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/storage/tablet_schema.h|0|4|00.00%|[294, 295, 299, 300]|
|:large_blue_circle:|src/storage/rowset/bitshuffle_page.h|1|3|33.33%|[307, 308]|

**Review by decster — APPROVED** [review]

**Review by chaoyli — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Pull request merged**
