### PR TITLE
[Refactor] Using half query_timeout as automatic partition creation timeout

### LINKED ISSUE #19510: [load auto create part]Creating a large number of partitions timed out when insert data
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
```
CREATE TABLE `duplicate_max_partition_num` (v1 date,v2 datetime,v3 char(20)) DUPLICATE KEY(`v1`) PARTITION BY date_trunc('day', v1) DISTRIBUTED BY HASH(`v1`, `v2`, `v3`) PROPERTIES (  "replication_num" = "3", "storage_format" = "v2");

```
insert into duplicate_max_partition_num values xxx
will create 1000 partitions

### Expected behavior (Required)
successfuly
### Real behavior (Required)
failed
95058c52-c1bb-4cd2-ad8a-e246be70288d

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
mysql> select current_version();
+----------------------------+
| current_version()          |
+----------------------------+
| BRANCH-3.0-RELEASE cbc57d0 |
+----------------------------+
1 row in set (0.00 sec)

### PR DESCRIPTION
**Pull request by meegoo**
## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [x] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #19510

## Problem Summary(Required) ：

create partition timeout us `thrift_rpc_timeout_ms`, which is not convinent to change for load.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 3.0
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Review by Astralidea — DISMISSED** [review]

**Review by gengjun-git — APPROVED** [review]

**Review by Astralidea — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by Astralidea** [comment]
run starrocks_admit_test

**Comment by meegoo** [comment]
run starrocks_admit_test

**Comment by meegoo** [comment]
@merfigy backport branch-3.0

**Pull request merged**
