### PR TITLE
[Feature]Support explain CTAS

### LINKED ISSUE #19108: Support explain CTAS
## Feature request

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

support explain CTAS
demo:explain create table test.test as select * from test.explain_test;
**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by leoyy0316**
## What type of PR is this：
- [ ] BugFix
- [x] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #19108

## Problem Summary(Required) ：

support explain CTAS
image

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Comment by leoyy0316** [comment]
run starrocks_admit_test

**Comment by stephen-shelby** [comment]
I think you should refer to others how to show explain CTAS.

**Review by murphyatwork — CHANGES_REQUESTED** [review]
please write a test case for this feature

**Comment by leoyy0316** [comment]
@mofeiatwork need to do any thing?

**Pull request closed without merging**
