### PR TITLE
[BugFix] Add user-name auth for broker load without broker

### LINKED ISSUE #9435: [BugFix] Add user-name auth for broker load without broker
currently broker load without broker doesn't support username-auth

### PR DESCRIPTION
**Pull request by xiaoyong-z**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #9435

## Problem Summary(Required) ：

currently broker load without broker doesn't support username auth

### CODE REVIEW

**Comment by xiaoyong-z** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 12 / 19 (63.16%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/fs/hdfs/HdfsFsManager.java|8|13|61.54%|[340, 349, 350, 356, 357]|
|:large_blue_circle:|com/starrocks/fs/hdfs/HdfsFs.java|4|6|66.67%|[88, 89]|

**Review by chaoyli — APPROVED** [review]

**Review by chaoyli — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 12 / 19 (63.16%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/fs/hdfs/HdfsFsManager.java|8|13|61.54%|[340, 349, 350, 356, 357]|
|:large_blue_circle:|com/starrocks/fs/hdfs/HdfsFs.java|4|6|66.67%|[88, 89]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 12 / 19 (63.16%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/fs/hdfs/HdfsFsManager.java|8|13|61.54%|[340, 349, 350, 356, 357]|
|:large_blue_circle:|com/starrocks/fs/hdfs/HdfsFs.java|4|6|66.67%|[88, 89]|

**Review by chaoyli — APPROVED** [review]

**Review by meegoo — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Pull request merged**
