### PR TITLE
Compatible with custom delimiter in Hive2.

### PR DESCRIPTION
**Pull request by Smith-Cruise**
## What type of PR is this：
- [ ] bug
- [ ] feature
- [x] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

There is a typo in Hive 2.x, we need to be compatible with it.

### CODE REVIEW

**Review by DorianZheng — APPROVED** [review]
LGTM

**Review by stephen-shelby — APPROVED** [review]
LGTM

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 6 / 7 (85.71%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/external/hive/HiveMetaClient.java|6|7|85.71%|[663]|

**Pull request merged**
