### PR TITLE
[Enhancement] Try refresh Iceberg table on file not found

### PR DESCRIPTION
**Pull request by Samrose-Ahmed**
## Why I'm doing:

Currently, if in Iceberg a compaction/deletion happens and file is physically deleted from S3, if the Iceberg metadata is cached, it can result in repeated query failure with Remote file not found.

## What I'm doing:

Make sure RemoteFileNotFound exception is propagated to FE and refresh Iceberg metadata on encountering. Also try to replan and retry.

Fixes #issue

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [x] Yes, this PR will result in a change in behavior.
- [ ] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [x] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.3
  - [ ] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

## Documentation PRs only:

If you are submitting a PR that adds or changes English documentation and have not
included Chinese documentation, then you can check the box to request GPT to translate the
English doc to Chinese. Please ensure to uncheck the **Do not translate** box if translation is needed.
The workflow will generate a new PR with the Chinese translation after this PR is merged.

- [ ] Yes, translate English markdown files with GPT
- [x] Do not translate

### CODE REVIEW

**Comment by kevincai** [comment]
@before-Sunrise @Smith-Cruise please take a look at this PR at your convenience.

**Comment by kevincai** [comment]
@Samrose-Ahmed The code coverage on FE side doesn't look good. Please take a look and check if more cases or sql-tester can be added to increase the coverage.

**Comment by Smith-Cruise** [comment]
@stephen-shelby PTAL

**Comment by stephen-shelby** [comment]
hi, thanks for your contribution.  Iceberg refresh costs far more than hive. hive table only need to refresh cached partition or files. but iceberg catalog need to refresh all table files if you don't pass predicate. we provide a background refresh every 10mins. If you have strict requirements for timeliness and accuracy. you could disable iceberg metadata cache in the catalog properties. the property key is "enable_iceberg_metadata_cache".

**Comment by Samrose-Ahmed** [comment]
That's kinda fine, I solved this for us in a different way so its not critical. You can close this.

**Comment by stephen-shelby** [comment]
> That's kinda fine, I solved this for us in a different way by not physically deleting quickly so its not critical. You can close this.

so, how did you solve this issue?

**Comment by Samrose-Ahmed** [comment]
We just adjust don't delete so aggressively, it's ok for us to have some stale result.

**Pull request closed without merging**
