### PR TITLE
[Feature]Support partition by expr in BE

### PR DESCRIPTION
**Pull request by kangkaisen**
## What type of PR is this：
- [ ] bug
- [x] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by kangkaisen** [comment]
For https://github.com/StarRocks/starrocks/issues/5114

**Review by ABingHuang — DISMISSED** [review]
LGTM

**Review by Astralidea — DISMISSED** [review]

**Comment by Astralidea** [comment]
LGTM

**Comment by kangkaisen** [comment]
run starrocks_fe_unittest

**Comment by kangkaisen** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 1 / 4 (25.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/planner/OlapTableSink.java|1|4|25.00%|

**Review by Astralidea — APPROVED** [review]

**Review by HangyuanLiu — APPROVED** [review]

**Pull request merged**
