### PR TITLE
[BugFix] return null when loadtable() get null to avoid npe

### PR DESCRIPTION
**Pull request by zombee0**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #https://github.com/StarRocks/StarRocksBenchmark/issues/369

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 3.0
  - [x] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Comment by DorianZheng** [comment]
when does it return null ptr?

**Comment by zombee0** [comment]
> when does it return null ptr?

@DorianZheng table not exists.

**Review by stephen-shelby — APPROVED** [review]

**Review by Youngwb — APPROVED** [review]

**Comment by DorianZheng** [comment]
@zombee0 why do we load a non-exist table?

**Comment by zombee0** [comment]
> @zombee0 why do we load a non-exist table?

@DorianZheng we load table use tablename given by the sql user.

**Review by DorianZheng — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
