### PR TITLE
[BugFix] Fix correlated subquery unknown error when equals predicate has expression

### LINKED ISSUE #9349: [sqlancer] query unknow error
### Steps to reproduce the behavior (Required)
```
DROP DATABASE IF EXISTS w6;
CREATE DATABASE w6;
USE w6;
admin set frontend config ("enable_decimal_v3" = "true");
CREATE TABLE IF NOT EXISTS t0 (c_0_0 DATE NULL ,c_0_1 DECIMAL(32, 17)  NULL ,c_0_2 DATE NOT NULL ,c_0_3 DATE NULL ,c_0_4 DATE NULL ,c_0_5 FLOAT NULL ) DUPLICATE KEY (c_0_0,c_0_1,c_0_2,c_0_3) PARTITION BY RANGE(c_0_0) (START ("2010-01-01") END ("2022-12-31") EVERY (INTERVAL 237 day)) DISTRIBUTED BY HASH (c_0_1,c_0_3,c_0_2,c_0_0) BUCKETS 3 properties("replication_num"="3") ;
CREATE TABLE t1 (c_1_0 LARGEINT NOT NULL,c_1_1 FLOAT NOT NULL) PRIMARY KEY (c_1_0) DISTRIBUTED BY HASH (c_1_0) BUCKETS 3 properties("replication_num"="3") ;
CREATE TABLE t2 (c_2_0 DATETIME NOT NULL ,c_2_1 BOOLEAN REPLACE NULL , INDEX index1_c_2_0(`c_2_0`) USING BITMAP) AGGREGATE KEY (c_2_0) DISTRIBUTED BY HASH (c_2_0) BUCKETS 3 properties("replication_num"="3") ;
TRUNCATE TABLE t0;
INSERT INTO t2 VALUES ('1970-01-01 16:20:49', false), ('1970-01-01 16:20:49', true);
INSERT INTO t1 VALUES (-1772249410, 0.5044184075978423), (-936973503, 0.8624197080523109);
INSERT INTO t2 VALUES ('1970-01-10 01:02:13', NULL);
INSERT INTO t0 VALUES ('1969-12-21', NULL, '1969-12-11', '1970-01-01', '1969-12-10', 0.2361396819503695), (NULL, 0.00035444446789749, '1970-01-24', '1970-01-03', '1969-12-11', NULL);
INSERT INTO t0 VALUES ('1969-12-27', 0.00128640386662091, '1969-12-08', '1969-12-26', '1970-01-01', 0.40977639075376515), (NULL, 0.00142724788925741, '1970-01-24', '1969-12-16', '1970-01-18', 0.40977639075376515);
INSERT INTO t2 VALUES ('1969-12-24 12:01:13', true), ('1970-01-06 21:23:22', true);
INSERT INTO t1 VALUES (1972084960, 0.6935039326758717), (-703751606, 0.02344653297554511);
INSERT INTO t1 VALUES (-491443269, 0.47432266199307227);
INSERT INTO t0 VALUES ('1970-01-12', 0.00364416809706534, '1969-12-09', '1969-12-28', NULL, 0.8624197080523109), ('1970-01-24', 0.00972706426574444, '1969-12-11', '1970-01-23', NULL, 0.13169367694367795);
INSERT INTO t1 VALUES (-1715170027, 0.29908874332863267), (-1666287434, 0.9701675750169672);
INSERT INTO t1 VALUES (752533260, 0.2801419237622752);
INSERT INTO t1 VALUES (393311454, -9.36973503E8), (-1332190990, -3.51832806E8);
INSERT INTO t0 VALUES (NULL, 0.00104584108043172, '1970-01-04', '1970-01-07', '1970-01-09', 0.5870796348388088);
INSERT INTO t1 VALUES (702182066, 0.8044055674144999), (-1666287434, -1.666287434E9);
INSERT INTO t2 VALUES ('1969-12-24 03:34:26', false);
SELECT t0_101.c_0_0 FROM t0 AS t0_101 WHERE (t0_101.c_0_0) IN ((SELECT subt0.c_0_0 FROM  (SELECT t0_101.c_0_0, t0_101.c_0_1, t0_101.c_0_2, t0_101.c_0_3, t0_101.c_0_4, t0_101.c_0_5 FROM t0 AS t0_101 WHERE true) subt0 LEFT ANTI JOIN t2 AS t2_103 ON subt0.c_0_1 = t2_103.c_2_1 AND subt0.c_0_1 <= t2_103.c_2_1 AND subt0.c_0_1 < t2_103.c_2_1 AND subt0.c_0_1 >= t2_103.c_2_1 WHERE (CASE  WHEN  ( subt0.c_0_0 ) != ( t0_101.c_0_0 )  THEN t0_101.c_0_3 ELSE subt0.c_0_3 END) IN ('1969-12-28') ) )  UNION ALL SELECT t0_101.c_0_0 FROM t0 AS t0_101 WHERE (NOT ((t0_101.c_0_0) IN ((SELECT subt0.c_0_0 FROM  (SELECT t0_101.c_0_0, t0_101.c_0_1, t0_101.c_0_2, t0_101.c_0_3, t0_101.c_0_4, t0_101.c_0_5 FROM t0 AS t0_101 WHERE true) subt0 LEFT ANTI JOIN t2 AS t2_103 ON subt0.c_0_1 = t2_103.c_2_1 AND subt0.c_0_1 <= t2_103.c_2_1 AND subt0.c_0_1 < t2_103.c_2_1 AND subt0.c_0_1 >= t2_103.c_2_1 WHERE (CASE  WHEN  ( subt0.c_0_0 ) != ( t0_101.c_0_0 )  THEN t0_101.c_0_3 ELSE subt0.c_0_3 END) IN ('1969-12-28') ) ) )) UNION ALL SELECT t0_101.c_0_0 FROM t0 AS t0_101 WHERE (((t0_101.c_0_0) IN ((SELECT subt0.c_0_0 FROM  (SELECT t0_101.c_0_0, t0_101.c_0_1, t0_101.c_0_2, t0_101.c_0_3, t0_101.c_0_4, t0_101.c_0_5 FROM t0 AS t0_101 WHERE true) subt0 LEFT ANTI JOIN t2 AS t2_103 ON subt0.c_0_1 = t2_103.c_2_1 AND subt0.c_0_1 <= t2_103.c_2_1 AND subt0.c_0_1 < t2_103.c_2_1 AND subt0.c_0_1 >= t2_103.c_2_1 WHERE (CASE  WHEN  ( subt0.c_0_0 ) != ( t0_101.c_0_0 )  THEN t0_101.c_0_3 ELSE subt0.c_0_3 END) IN ('1969-12-28') ) ) ) IS NULL);

```

```
java.lang.IllegalStateException: null
        at com.google.common.base.Preconditions.checkState(Preconditions.java:494) ~[spark-dpp-1.0.0.jar:?]
        at com.starrocks.sql.optimizer.statistics.Statistics.getColumnStatistic(Statistics.java:56) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.ExpressionStatisticCalculator$ExpressionStatisticVisitor.visitVariableReference(ExpressionStatisticCalculato
r.java:59) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.ExpressionStatisticCalculator$ExpressionStatisticVisitor.visitVariableReference(ExpressionStatisticCalculato
r.java:38) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.operator.scalar.ColumnRefOperator.accept(ColumnRefOperator.java:99) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.ExpressionStatisticCalculator$ExpressionStatisticVisitor.lambda$visitCall$0(ExpressionStatisticCalculator.ja
va:139) ~[starrocks-fe.jar:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_252]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[?:1.8.0_252]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_252]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_252]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_252]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_252]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566) ~[?:1.8.0_252]
        at com.starrocks.sql.optimizer.statistics.ExpressionStatisticCalculator$ExpressionStatisticVisitor.visitCall(ExpressionStatisticCalculator.java:139) ~
[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.ExpressionStatisticCalculator$ExpressionStatisticVisitor.visitCall(ExpressionStatisticCalculator.java:38) ~[
starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.operator.scalar.CallOperator.accept(CallOperator.java:173) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.ExpressionStatisticCalculator.calculate(ExpressionStatisticCalculator.java:35) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.ExpressionStatisticCalculator.calculate(ExpressionStatisticCalculator.java:31) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.PredicateStatisticsCalculator$PredicateStatisticsCalculatingVisitor.getExpressionStatistic(PredicateStatisti
csCalculator.java:324) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.PredicateStatisticsCalculator$PredicateStatisticsCalculatingVisitor.visitBinaryPredicate(PredicateStatistics
Calculator.java:215) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.PredicateStatisticsCalculator$PredicateStatisticsCalculatingVisitor.visitBinaryPredicate(PredicateStatistics
Calculator.java:32) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.operator.scalar.BinaryPredicateOperator.accept(BinaryPredicateOperator.java:62) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.PredicateStatisticsCalculator.statisticsCalculate(PredicateStatisticsCalculator.java:29) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.estimateStatistics(StatisticsCalculator.java:1250) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.computeJoinNode(StatisticsCalculator.java:829) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.visitLogicalJoin(StatisticsCalculator.java:721) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.visitLogicalJoin(StatisticsCalculator.java:136) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.operator.logical.LogicalJoinOperator.accept(LogicalJoinOperator.java:117) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.estimatorStats(StatisticsCalculator.java:152) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.task.DeriveStatsTask.execute(DeriveStatsTask.java:76) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.task.SeriallyTaskScheduler.executeTasks(SeriallyTaskScheduler.java:42) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.memoOptimize(Optimizer.java:162) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.optimize(Optimizer.java:103) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.createQueryPlan(StatementPlanner.java:124) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:89) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:338) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:283) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:401) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:637) ~[starrocks-fe.jar:?]
        at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:55) ~[starrocks-fe.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]

```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - mysql> select current_version();
+-------------------------+
| current_version()       |
+-------------------------+
| BRANCH-2.3-ASAN 9742790 |
+-------------------------+

### PR DESCRIPTION
**Pull request by Youngwb**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #9349 

## Problem Summary(Required) ：

When correlated subquery sql like 
```
select t0.v1 from t0 where (t0.v2 in (select t1.v4 from t1 where t0.v3 + t1.v5 = 1)) is NULL
```

The QuantifiedApply2OuterJoinRule would transfrom plan like 
```
  /*
         * In:
         * before: select t0.v1, t0.v2 in (select t1.v2 from t1 where t0.v3 = t1.v3) from t0;
         * after: with xx as (select t1.v2, t1.v3 from t1)
         *        select t0.v1,
         *             case
         *                 // t1 empty table and without where clause `t0.v3 = t1.v3`, then t1Rows may be 0
         *                 // t1 empty table, if t1Rows is null, means the result of join correlation predicate must be false
         *                 // `any_or_null in (empty) -> false`
         *                 when t1Rows = 0 or t1Rows is null then false
         *                 // `null in (any_or_null...) -> null`
         *                 when t0.v2 is null then null
         *                 // `a in (a, [any_or_null...]) -> true`
         *                 when t1d.v2 is not null then true
         *                 // `a in (null, [not_a_or_null...]) -> null`
         *                 when v2NotNulls < t1Rows then null
         *                 // `a in (not_a...) -> false`, not_a cannot be null
         *                 else false
         *             end
         *         from t0
         *              left outer join (select xx.v2, xx.v3 from xx group by xx.v2, xx.v3) as t1d
         *                              on t0.v2= t1d.v2 and t0.v3 = t1d.v3
         *              left outer join (select v3, count(*) as t1Rows, count(xx.v2) as v2NotNulls from xx group by xx.v3) as t1c
         *                              on t1c.v3 = t0.v3
         *
         *                                           CTEAnchor
         *                                          /        \
         *                                    CTEProduce     Project
         *    Apply(t0.v2 in t1.v2)              /               \
         *    /          \          ===>     Project         left/cross join
         *   t0          t1                   /              /          \
         *                                Filter         Left join       Agg(count)
         *                                 /             /       \           \
         *                               t1            t0     Agg(distinct)  CTEConsume
         *                                                         \
         *                                                        CTEConsume
         * */
```

The agg(distinct) and agg(count) should add the v5 column to group by which will used in left join/cross join predicate

### CODE REVIEW

**Comment by Youngwb** [comment]
run starrocks_fe_unittest

**Review by kangkaisen — APPROVED** [review]

**Comment by Youngwb** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 24 / 24 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/QuantifiedApply2OuterJoinRule.java|24|24|100.00%|[]|

**Review by Seaven — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by Youngwb** [comment]
run starrocks_admit_test

**Comment by Youngwb** [comment]
@mergifyio backport branch-2.3

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 24 / 24 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/QuantifiedApply2OuterJoinRule.java|24|24|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 24 / 24 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/QuantifiedApply2OuterJoinRule.java|24|24|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 24 / 24 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/QuantifiedApply2OuterJoinRule.java|24|24|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 24 / 24 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/QuantifiedApply2OuterJoinRule.java|24|24|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 24 / 24 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/QuantifiedApply2OuterJoinRule.java|24|24|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 24 / 24 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/QuantifiedApply2OuterJoinRule.java|24|24|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 24 / 24 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/QuantifiedApply2OuterJoinRule.java|24|24|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 24 / 24 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/QuantifiedApply2OuterJoinRule.java|24|24|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 24 / 24 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/QuantifiedApply2OuterJoinRule.java|24|24|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 24 / 24 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/QuantifiedApply2OuterJoinRule.java|24|24|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 24 / 24 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/QuantifiedApply2OuterJoinRule.java|24|24|100.00%|[]|

**Pull request merged**
