### PR TITLE
[Enhancement] Support excluded_trigger_tables property for materialized view

### LINKED ISSUE #13167: Optimize the refresh scenario of large wide tables
## Enhancement
In fact, for the large-width tables generated by materialized views, that is, fact tables and dimension tables, some users may prefer that the latitude table does not completely refresh the entire materialized table when adding data for the sake of refresh efficiency. View all partitions in the history. So see if there is a way to properly optimize for this problem.

### PR DESCRIPTION
**Pull request by Astralidea**
## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #13167

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [x] This pr will affect users' behaviors
- [x] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 16 / 90 (17.78%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/AnalyzerUtils.java|0|8|00.00%|[468, 469, 470, 471, 472, 473, 474, 476]|
|:large_blue_circle:|com/starrocks/common/util/PropertyAnalyzer.java|0|13|00.00%|[240, 241, 242, 243, 244, 245, 246, 247, 249, 250, 252, 253, 255]|
|:large_blue_circle:|com/starrocks/catalog/MaterializedView.java|1|24|04.17%|[575, 576, 578, 579, 580, 581, 582, 585, 586, 589, 590, 669, 670, 671, 686, 687, 688, 689, 692, 693, 694, 697, 698]|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|1|13|07.69%|[3326, 3327, 3328, 3329, 3330, 3331, 3333, 3335, 3336, 3339, 3340, 3341]|
|:large_blue_circle:|com/starrocks/catalog/TableProperty.java|7|17|41.18%|[195, 196, 197, 198, 199, 200, 201, 279, 283, 284]|
|:large_blue_circle:|com/starrocks/transaction/PublishVersionDaemon.java|7|15|46.67%|[382, 383, 387, 388, 390, 391, 393, 397]|

**Comment by Astralidea** [comment]
run starrocks_admit_test

**Comment by Astralidea** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 18 / 91 (19.78%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/AnalyzerUtils.java|0|8|00.00%|[468, 469, 470, 471, 472, 473, 474, 476]|
|:large_blue_circle:|com/starrocks/common/util/PropertyAnalyzer.java|0|13|00.00%|[240, 241, 242, 243, 244, 245, 246, 247, 249, 250, 252, 253, 255]|
|:large_blue_circle:|com/starrocks/catalog/MaterializedView.java|1|24|04.17%|[575, 576, 578, 579, 580, 581, 582, 585, 586, 589, 590, 669, 670, 671, 686, 687, 688, 689, 692, 693, 694, 697, 698]|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|1|13|07.69%|[3326, 3327, 3328, 3329, 3330, 3331, 3333, 3335, 3336, 3339, 3340, 3341]|
|:large_blue_circle:|com/starrocks/catalog/TableProperty.java|7|17|41.18%|[195, 196, 197, 198, 199, 200, 201, 279, 283, 284]|
|:large_blue_circle:|com/starrocks/transaction/PublishVersionDaemon.java|9|16|56.25%|[385, 386, 390, 391, 393, 396, 397]|

**Review by gengjun-git — APPROVED** [review]

**Review by Youngwb — APPROVED** [review]

**Pull request merged**
