### PR TITLE
[BugFix] string column writer will check data's length even it is null

### LINKED ISSUE #10380: [BugFix] string column writer will check data's length even it is null

### PR DESCRIPTION
**Pull request by xiaoyong-z**
Signed-off-by: xyz <a997647204@gmail.com>

## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #10380

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Review by chaoyli — APPROVED** [review]

**Review by chaoyli — APPROVED** [review]

**Review by meegoo — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by xiaoyong-z** [comment]
@mergify backport branch-2.4

**Comment by xiaoyong-z** [comment]
@mergify backport branch-2.3

**Comment by xiaoyong-z** [comment]
@mergify backport branch-2.2

**Comment by xiaoyong-z** [comment]
@mergify backport branch-2.1

**Comment by yongbingwang** [comment]
https://github.com/StarRocks/starrocks/pull/10444

**Comment by yongbingwang** [comment]
branch-2.3
https://github.com/StarRocks/starrocks/pull/10446

**Pull request merged**
