### PR TITLE
[SR SQL Planner Summer Camp] destroy (Add restore analysis)

### PR DESCRIPTION
**Pull request by melt-code**
## What type of PR is this：
- [ ] bug
- [x] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #7951

## Problem Summary(Required) ：

Add restore analysis

### CODE REVIEW

**Comment by melt-code** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 41 / 92 (44.57%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|0|30|00.00%|[1943, 1944, 1945, 1947, 1948, 1949, 1950, 1951, 1952, 1953, 1954, 1956, 1957, 1958, 1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1970, 3122, 3123, 3124, 3125, 3126, 3128]|
|:large_blue_circle:|com/starrocks/sql/ast/AstVisitor.java|0|1|00.00%|[317]|
|:large_blue_circle:|com/starrocks/sql/analyzer/RestoreStmtAnalyzer.java|37|57|64.91%|[26, 42, 48, 52, 60, 65, 71, 83, 90, 96, 97, 99, 100, 101, 102, 103, 104, 106, 115, 116]|
|:large_blue_circle:|com/starrocks/sql/analyzer/Analyzer.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/RestoreStmt.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/common/ErrorCode.java|1|1|100.00%|[]|

**Comment by melt-code** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 80 / 95 (84.21%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/ast/AstVisitor.java|0|1|00.00%|[317]|
|:large_blue_circle:|com/starrocks/sql/analyzer/RestoreStmtAnalyzer.java|45|57|78.95%|[26, 42, 48, 60, 65, 71, 83, 90, 97, 106, 115, 116]|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|31|33|93.94%|[1951, 3128]|
|:large_blue_circle:|com/starrocks/sql/analyzer/Analyzer.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/RestoreStmt.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/common/ErrorCode.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 80 / 95 (84.21%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/ast/AstVisitor.java|0|1|00.00%|[371]|
|:large_blue_circle:|com/starrocks/sql/analyzer/RestoreStmtAnalyzer.java|45|57|78.95%|[26, 42, 48, 60, 65, 71, 83, 90, 97, 106, 115, 116]|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|31|33|93.94%|[2199, 3384]|
|:large_blue_circle:|com/starrocks/sql/analyzer/Analyzer.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/RestoreStmt.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/common/ErrorCode.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 80 / 95 (84.21%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/ast/AstVisitor.java|0|1|00.00%|[371]|
|:large_blue_circle:|com/starrocks/sql/analyzer/RestoreStmtAnalyzer.java|45|57|78.95%|[26, 42, 48, 60, 65, 71, 83, 90, 97, 106, 115, 116]|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|31|33|93.94%|[2199, 3384]|
|:large_blue_circle:|com/starrocks/sql/analyzer/Analyzer.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/RestoreStmt.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/common/ErrorCode.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 80 / 95 (84.21%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/ast/AstVisitor.java|0|1|00.00%|[371]|
|:large_blue_circle:|com/starrocks/sql/analyzer/RestoreStmtAnalyzer.java|45|57|78.95%|[26, 42, 48, 60, 65, 71, 83, 90, 97, 106, 115, 116]|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|31|33|93.94%|[2199, 3384]|
|:large_blue_circle:|com/starrocks/sql/analyzer/Analyzer.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/RestoreStmt.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/common/ErrorCode.java|1|1|100.00%|[]|

**Pull request closed without merging**
