### PR TITLE
Make complex set var use old parser

### PR DESCRIPTION
**Pull request by kangkaisen**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Problem Summary(Required) ：
https://github.com/StarRocks/starrocks/pull/7840 introduced a bug: will make the following stmts parsed error:

- SetNamesVar
- SetPassVar
- SetTransaction
- SetUserPropertyVar

### CODE REVIEW

**Comment by kangkaisen** [comment]
I will add test cases to daily test.

**Review by Youngwb — DISMISSED** [review]

**Comment by kangkaisen** [comment]
run starrocks_fe_unittest

**Comment by kangkaisen** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 0 / 1 (00.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/analysis/SetStmt.java|0|1|00.00%|

**Review by liuyehcf — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 0 / 2 (00.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|0|1|00.00%|
|:large_blue_circle:|com/starrocks/analysis/SetStmt.java|0|1|00.00%|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 0 / 4 (00.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|0|1|00.00%|
|:large_blue_circle:|com/starrocks/analysis/SetStmt.java|0|1|00.00%|
|:large_blue_circle:|com/starrocks/analysis/SetPassVar.java|0|2|00.00%|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 1 / 5 (20.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|0|1|00.00%|
|:large_blue_circle:|com/starrocks/analysis/SetPassVar.java|0|2|00.00%|
|:large_blue_circle:|com/starrocks/analysis/SetStmt.java|1|2|50.00%|

**Review by Youngwb — APPROVED** [review]

**Review by HangyuanLiu — APPROVED** [review]

**Pull request merged**
