### PR TITLE
[BugFix] SchedEntityComparator should obey asymmetric relation

### PR DESCRIPTION
**Pull request by ZiheLiu**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Problem Summary(Required) ：

`WorkGroupDriverQueue::_wg_entities` uses `std::set` to store workgroups ordered by `wg.vruntime`.
The comparator of `_wg_entities` overrides `<` operator to `lhs_ptr.vruntime<rhs_ptr.vruntime`.

However, the comparator of `std::set` should obey asymmetric relation, because it consider `a==b` is true if `a<b` is false and `a>b` is false.
Therefore, when the set receives two different workgroups with the same vruntime, it will only store the first one.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 2.5
  - [x] 2.4
  - [x] 2.3
  - [ ] 2.2

### CODE REVIEW

**Review by murphyatwork — DISMISSED** [review]

**Review by kangkaisen — DISMISSED** [review]

**Comment by ZiheLiu** [comment]
run starrocks_be_unittest

**Comment by ZiheLiu** [comment]
run starrocks_admit_test

**Comment by ZiheLiu** [comment]
run starrocks_be_unittest

**Comment by ZiheLiu** [comment]
run starrocks_admit_test

**Review by kangkaisen — APPROVED** [review]

**Review by murphyatwork — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.3

**Pull request merged**
