### PR TITLE
[BugFix] Fix INFORMATION_SCHEMA for MV table type

### LINKED ISSUE #13898: Table Type Not Recognized by BI System
https://dev.mysql.com/doc/mysql-infoschema-excerpt/8.0/en/information-schema-tables-table.html
TABLE_TYPE
BASE TABLE for a table, VIEW for a view, or SYSTEM VIEW for an INFORMATION_SCHEMA table.
so we should not use MATERIALIZED VIEW type.
### Steps to reproduce the behavior (Required)
1. SHOW FULL TABLES FROM `test`;

### Expected behavior (Required)
+----------------+-------------------+
| Tables_in_test | Table_type        |
+----------------+-------------------+
| mv2            | MATERIALIZED VIEW |
| site_access    | BASE TABLE        |
| t1             | BASE TABLE        |
| view_1         | VIEW              |
+----------------+-------------------+
### Real behavior (Required)
+----------------+-------------------+
| Tables_in_test | Table_type        |
+----------------+-------------------+
| mv2            |VIEW |
| site_access    | BASE TABLE        |
| t1             | BASE TABLE        |
| view_1         | VIEW              |
+----------------+-------------------+
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
2.4.x 2.5.x

### PR DESCRIPTION
**Pull request by Astralidea**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #13898

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Review by waittttting — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by gengjun-git — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by Astralidea** [comment]
run starrocks_admit_test

**Comment by mofeiatwork** [comment]
run starrocks_admit_test

**Review by imay — APPROVED** [review]

**Comment by Astralidea** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
