### PR TITLE
[Enhancement] Materialized view query rewrite support cross join

### LINKED ISSUE #14451: Materialized view query rewrite should support cross join
### Steps to reproduce the behavior (Required)
1. Using SSB benchmark data
2. create materialized view mv_1 distributed by hash(s_city) as  select s_city, s_nation , lo_orderpriority, sum(lo_revenue) as sum_1, sum(lo_revenue*lo_discount) as sum_2 from lineorder join supplier group by s_city, s_nation , lo_orderpriority;
3. refresh refresh materialized view mv_1; 
4. select s_city, s_nation , lo_orderpriority, sum(lo_revenue) as sum_1, sum(lo_revenue*lo_discount) as sum_2 from lineorder join supplier group by s_city, s_nation , lo_orderpriority; 

### Expected behavior (Required)
It should be hit the materialized view and query rewrite, but it not worked.
If I change the cross join to inner join, it works.

### Real behavior (Required)
Still query to base table and cost a lot of time.

### StarRocks version (Required)
 - branch-2.5- 35c84c8

### PR DESCRIPTION
**Pull request by huangfeng1993**
## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #14451

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 19 / 19 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java|14|14|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/MvUtils.java|5|5|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 18 / 18 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java|13|13|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/MvUtils.java|5|5|100.00%|[]|

**Review by ABingHuang — DISMISSED** [review]
LGTM

**Review by murphyatwork — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by mofeiatwork** [comment]
@Mergifyio backport branch-2.5

**Review by kangkaisen — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 16 / 22 (72.73%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java|6|12|50.00%|[641, 642, 643, 644, 645, 649]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/MvUtils.java|10|10|100.00%|[]|

**Comment by huangfeng1993** [comment]
run starrocks_admit_test

**Comment by huangfeng1993** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 13 / 13 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/MvUtils.java|10|10|100.00%|[]|

**Comment by huangfeng1993** [comment]
run starrocks_admit_test

**Review by murphyatwork — APPROVED** [review]

**Review by imay — APPROVED** [review]

**Pull request merged**
