### PR TITLE
[BugFix] Fix 'remove_unused_buffer_values' of window function

### PR DESCRIPTION
**Pull request by liuyehcf**
## Main works of this pr

1. `Analytor::BUFFER_CHUNK_NUMBER` is set to 1000, which is too large that may lead to significant memory usage for buffering 1000 chunks.
2. Fix the bug in the function `remove_unused_buffer_values`, if previous parts are discarded, all the related field will be updated, like the partition boundary, peer group boundary. But some window function will record the previous boundary, and these information need to be udpated as well. So I introduced a method named `reset_state_for_contraction`, which will be invoded within `remove_unused_buffer_values` to update previously recorded partition boundary.

```cpp
    void update_batch_single_state_with_frame(FunctionContext* ctx, AggDataPtr __restrict state, const Column** columns,
                                              int64_t peer_group_start, int64_t peer_group_end, int64_t frame_start,
                                              int64_t frame_end) const override {
        int64_t peer_group_count = peer_group_end - peer_group_start;
        if (this->data(state).peer_group_start != peer_group_start) {
            // !!! HERE, this state record the peer group boundary
            this->data(state).peer_group_start = peer_group_start;
            this->data(state).rank += this->data(state).count;
        }
        this->data(state).count = peer_group_count;
    }
```

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.2
  - [x] 3.1
  - [x] 3.0
  - [x] 2.5

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 0 / 3 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/exec/analytor.cpp|0|3|00.00%|[675, 763, 765]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 0 / 28 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/exprs/agg/aggregate.h|0|1|00.00%|[108]|
|:large_blue_circle:|src/exprs/agg/window.h|0|14|00.00%|[183, 184, 221, 222, 256, 260, 261, 268, 269, 296, 301, 302, 310, 311]|
|:large_blue_circle:|src/exec/analytor.cpp|0|13|00.00%|[563, 724, 725, 726, 760, 761, 762, 763, 764, 765, 766, 767, 768]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 0 / 28 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/exprs/agg/aggregate.h|0|1|00.00%|[108]|
|:large_blue_circle:|src/exprs/agg/window.h|0|14|00.00%|[183, 184, 221, 222, 256, 260, 261, 268, 269, 296, 301, 302, 310, 311]|
|:large_blue_circle:|src/exec/analytor.cpp|0|13|00.00%|[563, 724, 725, 726, 760, 761, 762, 763, 764, 765, 766, 767, 768]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 0 / 31 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/exec/pipeline/analysis/analytic_sink_operator.h|0|1|00.00%|[35]|
|:large_blue_circle:|src/exprs/agg/aggregate.h|0|1|00.00%|[108]|
|:large_blue_circle:|src/exprs/agg/window.h|0|14|00.00%|[183, 184, 221, 222, 256, 260, 261, 268, 269, 296, 301, 302, 310, 311]|
|:large_blue_circle:|src/exec/analytor.cpp|0|15|00.00%|[381, 382, 567, 728, 729, 730, 764, 765, 766, 767, 768, 769, 770, 771, 772]|

**Review by stdpain — APPROVED** [review]

**Review by kangkaisen — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.2

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
