### PR TITLE
[Enhancement] Remove log4j conflict jar

### PR DESCRIPTION
**Pull request by gengjun-git**
Fixes 
```
SLF4J: Found binding in [jar:file:/home/disk4/gengjun/fe2/lib/spark-dpp-1.0.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/disk4/gengjun/fe2/lib/log4j-slf4j-impl-2.19.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
```

## What type of PR is this:
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [x] 3.0
  - [ ] 2.5
  - [ ] 2.4

### CODE REVIEW

**Comment by kevincai** [comment]
don't understand why it works on jdk8

**Comment by kevincai** [comment]
and also need backport to branch-2.5 if this fixes the issue

**Comment by gengjun-git** [comment]
> and also need backport to branch-2.5 if this fixes the issue

To fix the bug on 2.5, we should backport 3 PR, and I issue anther PR by hand https://github.com/StarRocks/starrocks/pull/27671

**Comment by gengjun-git** [comment]
> don't understand why it works on jdk8

Maybe class load logic is changed on jdk11

**Comment by kevincai** [comment]
ok

**Review by kevincai — APPROVED** [review]

**Review by imay — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Pull request merged**
