### PR TITLE
[BugFix] Fix unstable ut for disk simulation

### PR DESCRIPTION
**Pull request by nshangyiming**
## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [x] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #SR-12336

## Problem Summary(Required) ：

New code introduce the new logic that Version GC is executed every `PseudoBackend.tabletCheckIntervalMs`, so we also need to sleep that extra time to wait for versions really got GCed. Also add some debug information in case that it shows again.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by nshangyiming** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by chaoyli — DISMISSED** [review]

**Review by chaoyli — DISMISSED** [review]

**Comment by nshangyiming** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by decster — APPROVED** [review]

**Review by gengjun-git — APPROVED** [review]

**Comment by nshangyiming** [comment]
run starrocks_admit_test

**Pull request merged**
