### PR TITLE
[BugFix] Remove push down assert node on project

### PR DESCRIPTION
**Pull request by Seaven**
## What type of PR is this：
- [x] bugfix
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

For #10455

AssertNode will add one row(null) when the output of chlid is empty, push down to project will lead to get a wrong result easily(Project value vs NULL)

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by kangkaisen — APPROVED** [review]

**Comment by liuyehcf** [comment]
Please explain the motivation or reason of this pr

**Comment by Seaven** [comment]
> Please explain the motivation or reason of this pr

AssertNode will add one row(null) when the output of chlid is empty, push down to project will lead to get a wrong result easily(Project value vs NULL)

**Review by HangyuanLiu — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Pull request merged**
