### PR TITLE
[Enhancement] Support create mv when base table has multi partition columns for external table

### LINKED ISSUE #17751: Support create mv when base table has multi partition columns
## Enhancement
create mv will meet this error when base table has multi partition columns
image

### PR DESCRIPTION
**Pull request by Youngwb**
Signed-off-by: Youngwb <yangwenbo_mailbox@163.com>

## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #17751 

## Problem Summary(Required) ：

Solve two problems:
1. The base external table can have multiple partitioned columns
2. prune the external table partition when refreshing the external mv

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Comment by Youngwb** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 86 / 113 (76.11%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java|5|13|38.46%|[530, 544, 545, 546, 547, 548, 550, 552]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/MvUtils.java|16|25|64.00%|[519, 525, 527, 528, 529, 531, 532, 533, 534]|
|:large_blue_circle:|com/starrocks/scheduler/PartitionBasedMaterializedViewRefreshProcessor.java|41|50|82.00%|[716, 734, 738, 740, 741, 743, 744, 747, 749]|
|:large_blue_circle:|com/starrocks/connector/PartitionUtil.java|10|11|90.91%|[231]|
|:large_blue_circle:|com/starrocks/sql/optimizer/transformer/RelationTransformer.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/TableRelation.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/scheduler/MvTaskRunContext.java|7|7|100.00%|[]|

**Comment by Youngwb** [comment]
> Can this pr support internal Starrocks tables too?

No, This PR do not support

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 89 / 117 (76.07%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java|5|13|38.46%|[530, 544, 545, 546, 547, 548, 550, 552]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/MvUtils.java|16|25|64.00%|[520, 526, 528, 529, 530, 532, 533, 534, 535]|
|:large_blue_circle:|com/starrocks/sql/common/SyncPartitionUtils.java|2|3|66.67%|[393]|
|:large_blue_circle:|com/starrocks/scheduler/PartitionBasedMaterializedViewRefreshProcessor.java|41|50|82.00%|[716, 734, 738, 740, 741, 743, 744, 747, 749]|
|:large_blue_circle:|com/starrocks/connector/PartitionUtil.java|10|11|90.91%|[231]|
|:large_blue_circle:|com/starrocks/sql/optimizer/transformer/RelationTransformer.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/TableRelation.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AnalyzerUtils.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/scheduler/MvTaskRunContext.java|7|7|100.00%|[]|

**Review by Astralidea — APPROVED** [review]

**Review by gengjun-git — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
