### PR TITLE
[Enhancement] add disk_spill in runtime query statistics 

### PR DESCRIPTION
**Pull request by murphyatwork**
Fixes #issue

```sql
> show proc '/current_queries'
+--------------------------------------+--------------+----------+------+------------+---------------+-------------+---------------+----------+----------+
| QueryId                              | ConnectionId | Database | User | ScanBytes  | ScanRows      | MemoryUsage | DiskSpillSize | CPUTime  | ExecTime |
+--------------------------------------+--------------+----------+------+------------+---------------+-------------+---------------+----------+----------+
| 6e770804-0c22-11ee-92dc-162d24e49988 | 2            | ssb_1g   | root | 321.250 MB | 67371008 rows | 902.750 MB  | 113.523 MB    | 10.362 s | 7.501 s  |
+--------------------------------------+--------------+----------+------+------------+---------------+-------------+---------------+----------+----------+
```

## What type of PR is this:
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4

### CODE REVIEW

**Review by stdpain — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 11 / 33 (33.33%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/common/util/QueryStatisticsFormatter.java|0|5|00.00%|[29, 34, 39, 40, 48]|
|:large_blue_circle:|com/starrocks/common/proc/CurrentQueryHostProcNode.java|0|1|00.00%|[55]|
|:large_blue_circle:|com/starrocks/common/proc/CurrentQueryInfoProvider.java|0|8|00.00%|[118, 119, 205, 206, 226, 265, 266, 269]|
|:large_blue_circle:|com/starrocks/qe/QueryStatisticsItem.java|0|2|00.00%|[69, 70]|
|:large_blue_circle:|com/starrocks/common/proc/CurrentQueryBackendInstanceProcDir.java|0|1|00.00%|[69]|
|:large_blue_circle:|com/starrocks/common/proc/CurrentQueryStatisticsProcDir.java|11|16|68.75%|[110, 111, 113, 114, 115]|

**Review by kangkaisen — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 11 / 33 (33.33%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/common/util/QueryStatisticsFormatter.java|0|5|00.00%|[29, 34, 39, 40, 48]|
|:large_blue_circle:|com/starrocks/common/proc/CurrentQueryHostProcNode.java|0|1|00.00%|[55]|
|:large_blue_circle:|com/starrocks/common/proc/CurrentQueryInfoProvider.java|0|8|00.00%|[118, 119, 205, 206, 226, 265, 266, 269]|
|:large_blue_circle:|com/starrocks/qe/QueryStatisticsItem.java|0|2|00.00%|[69, 70]|
|:large_blue_circle:|com/starrocks/common/proc/CurrentQueryBackendInstanceProcDir.java|0|1|00.00%|[69]|
|:large_blue_circle:|com/starrocks/common/proc/CurrentQueryStatisticsProcDir.java|11|16|68.75%|[110, 111, 113, 114, 115]|

**Review by ZiheLiu — APPROVED** [review]

**Review by satanson — COMMENTED** [review]
Have you test this feature when enable_profile is on? 
Does it work fine in gray upgradation?

**Comment by mofeiatwork** [comment]
> Have you test this feature when enable_profile is on? Does it work fine in gray upgradation?

The query statistics and query profile are two separated feature, they don't depend on each other. 
The first one is always on, and the second is controlled by `enable_profile`.

So the answer is, This feature has nothing to do with `enable_profile`.

**Review by stdpain — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Pull request merged**
