### PR TITLE
[Feature] support view statements in new RBAC privilege framework

### PR DESCRIPTION
**Pull request by padmejin**
## What type of PR is this：
- [ ] BugFix
- [x] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

* Add a new type of privilege object to represent privileges on views.
* PrivilegeCheckerV2 support `select view`, `create view`, `alter view` and `drop view` statements.
* `checkAnyActionInDB` will check view as well.
* `db_admin` will be granted with all the privileges on all the views in all the databases.
Note that upgrading the privilege of view to current version is not implemented yet.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 78 / 83 (93.98%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/privilege/PrivilegeManager.java|13|16|81.25%|[630, 631, 632]|
|:large_blue_circle:|com/starrocks/sql/analyzer/PrivilegeCheckerV2.java|21|22|95.45%|[101]|
|:large_blue_circle:|com/starrocks/privilege/ViewPEntryObject.java|25|26|96.15%|[47]|
|:large_blue_circle:|com/starrocks/privilege/PrivilegeType.java|15|15|100.00%|[]|
|:large_blue_circle:|com/starrocks/privilege/DefaultAuthorizationProvider.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/persist/gson/GsonUtils.java|2|2|100.00%|[]|

**Review by gengjun-git — DISMISSED** [review]

**Review by nshangyiming — DISMISSED** [review]

**Comment by nshangyiming** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by chaoyli — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 82 / 89 (92.13%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/privilege/PrivilegeManager.java|13|16|81.25%|[630, 631, 632]|
|:large_blue_circle:|com/starrocks/sql/analyzer/PrivilegeCheckerV2.java|27|30|90.00%|[118, 478, 502]|
|:large_blue_circle:|com/starrocks/privilege/ViewPEntryObject.java|25|26|96.15%|[47]|
|:large_blue_circle:|com/starrocks/privilege/PrivilegeType.java|13|13|100.00%|[]|
|:large_blue_circle:|com/starrocks/privilege/DefaultAuthorizationProvider.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/persist/gson/GsonUtils.java|2|2|100.00%|[]|

**Review by gengjun-git — APPROVED** [review]

**Pull request merged**
