### PR TITLE
[Feature] Support lake materialized view crud

### PR DESCRIPTION
**Pull request by wyb**
## What type of PR is this：
- [ ] BugFix
- [x] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

1. create lake mv in shared-data mode.
2. async and manual refresh lake mv.
3. query lake mv.
4. drop lake mv.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 3.0
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Comment by wyb** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 91 / 172 (52.91%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/Database.java|0|1|00.00%|[590]|
|:large_blue_circle:|com/starrocks/lake/LakeMaterializedView.java|0|12|00.00%|[154, 156, 159, 160, 163, 164, 165, 168, 169, 170, 171, 172]|
|:large_blue_circle:|com/starrocks/catalog/OlapTable.java|0|4|00.00%|[2281, 2285, 2289, 2293]|
|:large_blue_circle:|com/starrocks/transaction/LakeTableTxnLogApplier.java|0|1|00.00%|[35]|
|:large_blue_circle:|com/starrocks/lake/compaction/CompactionScheduler.java|0|2|00.00%|[204, 232]|
|:large_blue_circle:|com/starrocks/transaction/LakeTableTxnStateListener.java|0|1|00.00%|[52]|
|:large_blue_circle:|com/starrocks/scheduler/mv/MVMaintenanceJob.java|0|1|00.00%|[128]|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|0|1|00.00%|[1428]|
|:large_blue_circle:|com/starrocks/transaction/PublishVersionDaemon.java|0|3|00.00%|[266, 320, 382]|
|:large_blue_circle:|com/starrocks/alter/LakeTableSchemaChangeJob.java|6|39|15.38%|[546, 548, 549, 550, 551, 552, 553, 555, 556, 557, 559, 560, 562, 563, 565, 566, 570, 571, 578, 579, 580, 581, 582, 583, 585, 586, 587, 588, 589, 590, 592, 593, 594]|
|:large_blue_circle:|com/starrocks/planner/OlapScanNode.java|1|3|33.33%|[461, 862]|
|:large_blue_circle:|com/starrocks/planner/MetaScanNode.java|1|2|50.00%|[91]|
|:large_blue_circle:|com/starrocks/transaction/TransactionStateListenerFactory.java|1|2|50.00%|[24]|
|:large_blue_circle:|com/starrocks/transaction/TransactionLogApplierFactory.java|1|2|50.00%|[24]|
|:large_blue_circle:|com/starrocks/scheduler/PartitionBasedMaterializedViewRefreshProcessor.java|9|13|69.23%|[830, 831, 832, 834]|
|:large_blue_circle:|com/starrocks/common/proc/TablesProcDir.java|3|4|75.00%|[229]|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|39|51|76.47%|[323, 2021, 2022, 2025, 2029, 2032, 2756, 3425, 3426, 3435, 4820, 5130]|
|:large_blue_circle:|com/starrocks/catalog/MaterializedView.java|15|15|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/StreamLoadPlanner.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/load/PartitionUtils.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/transaction/TransactionChecker.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/OlapTableSink.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/transaction/DatabaseTransactionMgr.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/lake/ShardDeleter.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/MaterializedViewOptimizer.java|5|5|100.00%|[]|
|:large_blue_circle:|com/starrocks/connector/PartitionUtil.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java|1|1|100.00%|[]|

**Comment by wyb** [comment]
run starrocks_admit_test

**Comment by sduzh** [comment]
@Mergifyio backport branch-3.0

**Review by abc982627271 — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 131 / 173 (75.72%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/Database.java|0|1|00.00%|[590]|
|:large_blue_circle:|com/starrocks/catalog/OlapTable.java|0|4|00.00%|[2326, 2330, 2334, 2338]|
|:large_blue_circle:|com/starrocks/transaction/LakeTableTxnLogApplier.java|0|1|00.00%|[35]|
|:large_blue_circle:|com/starrocks/lake/compaction/CompactionScheduler.java|0|2|00.00%|[204, 232]|
|:large_blue_circle:|com/starrocks/transaction/LakeTableTxnStateListener.java|0|1|00.00%|[52]|
|:large_blue_circle:|com/starrocks/scheduler/mv/MVMaintenanceJob.java|0|1|00.00%|[128]|
|:large_blue_circle:|com/starrocks/transaction/PublishVersionDaemon.java|0|3|00.00%|[266, 320, 382]|
|:large_blue_circle:|com/starrocks/planner/OlapScanNode.java|1|3|33.33%|[461, 862]|
|:large_blue_circle:|com/starrocks/planner/MetaScanNode.java|1|2|50.00%|[91]|
|:large_blue_circle:|com/starrocks/transaction/TransactionStateListenerFactory.java|1|2|50.00%|[24]|
|:large_blue_circle:|com/starrocks/transaction/TransactionLogApplierFactory.java|1|2|50.00%|[24]|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|1|2|50.00%|[1432]|
|:large_blue_circle:|com/starrocks/common/proc/TablesProcDir.java|3|4|75.00%|[229]|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|39|51|76.47%|[323, 2021, 2022, 2025, 2029, 2032, 2759, 3428, 3429, 3438, 4823, 5133]|
|:large_blue_circle:|com/starrocks/alter/LakeTableSchemaChangeJob.java|30|39|76.92%|[560, 562, 563, 565, 566, 582, 583, 593, 594]|
|:large_blue_circle:|com/starrocks/scheduler/PartitionBasedMaterializedViewRefreshProcessor.java|12|13|92.31%|[832]|
|:large_blue_circle:|com/starrocks/catalog/MaterializedView.java|15|15|100.00%|[]|
|:large_blue_circle:|com/starrocks/lake/LakeMaterializedView.java|12|12|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/StreamLoadPlanner.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/load/PartitionUtils.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/transaction/TransactionChecker.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/OlapTableSink.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/transaction/DatabaseTransactionMgr.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/lake/ShardDeleter.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/MaterializedViewOptimizer.java|5|5|100.00%|[]|
|:large_blue_circle:|com/starrocks/connector/PartitionUtil.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java|1|1|100.00%|[]|

**Comment by wyb** [comment]
run starrocks_admit_test

**Review by Astralidea — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wyb** [comment]
run starrocks_admit_test

**Comment by wyb** [comment]
run starrocks_admit_test

**Comment by wyb** [comment]
run starrocks_admit_test

**Review by ABingHuang — DISMISSED** [review]
LGTM

**Review by sduzh — DISMISSED** [review]

**Comment by wyb** [comment]
run starrocks_admit_test

**Comment by wyb** [comment]
run starrocks_admit_test

**Comment by wyb** [comment]
run starrocks_admit_test

**Comment by wyb** [comment]
run starrocks_admit_test

**Comment by tracymacding** [comment]
run starrocks_admit_test

**Review by Astralidea — DISMISSED** [review]

**Review by sduzh — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by Astralidea — APPROVED** [review]

**Review by sduzh — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 131 / 172 (76.16%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/Database.java|0|1|00.00%|[590]|
|:large_blue_circle:|com/starrocks/catalog/OlapTable.java|0|4|00.00%|[2326, 2330, 2334, 2338]|
|:large_blue_circle:|com/starrocks/transaction/LakeTableTxnLogApplier.java|0|1|00.00%|[35]|
|:large_blue_circle:|com/starrocks/lake/compaction/CompactionScheduler.java|0|2|00.00%|[204, 232]|
|:large_blue_circle:|com/starrocks/scheduler/mv/MVMaintenanceJob.java|0|1|00.00%|[128]|
|:large_blue_circle:|com/starrocks/transaction/PublishVersionDaemon.java|0|3|00.00%|[266, 320, 382]|
|:large_blue_circle:|com/starrocks/planner/OlapScanNode.java|1|3|33.33%|[461, 862]|
|:large_blue_circle:|com/starrocks/planner/MetaScanNode.java|1|2|50.00%|[91]|
|:large_blue_circle:|com/starrocks/transaction/TransactionStateListenerFactory.java|1|2|50.00%|[24]|
|:large_blue_circle:|com/starrocks/transaction/TransactionLogApplierFactory.java|1|2|50.00%|[24]|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|1|2|50.00%|[1430]|
|:large_blue_circle:|com/starrocks/common/proc/TablesProcDir.java|3|4|75.00%|[229]|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|39|51|76.47%|[323, 2021, 2022, 2025, 2029, 2032, 2759, 3428, 3429, 3438, 4823, 5133]|
|:large_blue_circle:|com/starrocks/alter/LakeTableSchemaChangeJob.java|30|39|76.92%|[560, 562, 563, 565, 566, 582, 583, 593, 594]|
|:large_blue_circle:|com/starrocks/scheduler/PartitionBasedMaterializedViewRefreshProcessor.java|12|13|92.31%|[832]|
|:large_blue_circle:|com/starrocks/catalog/MaterializedView.java|15|15|100.00%|[]|
|:large_blue_circle:|com/starrocks/lake/LakeMaterializedView.java|12|12|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/StreamLoadPlanner.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/load/PartitionUtils.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/transaction/TransactionChecker.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/OlapTableSink.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/transaction/DatabaseTransactionMgr.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/lake/ShardDeleter.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/MaterializedViewOptimizer.java|5|5|100.00%|[]|
|:large_blue_circle:|com/starrocks/connector/PartitionUtil.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java|1|1|100.00%|[]|

**Comment by wyb** [comment]
@Mergifyio backport branch-3.0

**Pull request merged**
