### PR TITLE
[BugFix] Abnormally exit in JAVA UDF call_function_in_pthread shows all-zeros of query_id and fragment_instance_id

### PR DESCRIPTION
**Pull request by satanson**
Some methods' invocations of Java UADF  is off-loaded to other pthreads from bthread, in these off-load threads, query_id and fragment_instance_id is missed to set for the thread_local tls_thread_status, so when crashes happen in these off-load threads,  Abnormally exit print all-zeros query_id and fragment_instance_id, for an example:
```
query_id:00000000-0000-0000-0000-000000000000, fragment_instance:00000000-0000-0000-0000-000000000000
```
## What type of PR is this:
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.0
  - [x] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Review by silverbullet233 — DISMISSED** [review]

**Comment by stdpain** [comment]
prefer SCOPED_SET_TRACE_INFO

**Review by ZiheLiu — DISMISSED** [review]

**Review by stdpain — APPROVED** [review]

**Review by ZiheLiu — APPROVED** [review]

**Review by murphyatwork — APPROVED** [review]

**Comment by satanson** [comment]
@mergifyio rebase

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
