### PR TITLE
[Enhancement] Keep all different string infos when merging profile if there is conflict

### PR DESCRIPTION
**Pull request by liuyehcf**
## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Enhancement

After #18150, we can get profile if query abort execution. But under current profile merge mechanims, some string info will be missed.

So, this pr enhance the profile merge mechanism on the merge of info string. Examples are listed as belows:

```
        EXCHANGE_SOURCE (plan_node_id=1):
          CommonMetrics:
             - ErrorMsg: Memory of query_pool exceed limit. try consume:224 Used: 40784057845, Limit: 40877351239. Mem usage has exceed the limit of query pool
             - ErrorMsg__DUP(0): Memory of query_pool exceed limit. try consume:117440512 Used: 40787074317, Limit: 40877351239. Mem usage has exceed the limit of query pool
             - ErrorMsg__DUP(1): Memory of query_pool exceed limit. try consume:160 Used: 40861113432, Limit: 40877351239. Mem usage has exceed the limit of query pool
             - ErrorMsg__DUP(2): Memory of query_pool exceed limit. try consume:160 Used: 40856209344, Limit: 40877351239. Mem usage has exceed the limit of query pool
             - ErrorMsg__DUP(3): Memory of query_pool exceed limit. try consume:160 Used: 40845399952, Limit: 40877351239. Mem usage has exceed the limit of query pool
             - ErrorMsg__DUP(4): Memory of query_pool exceed limit. try consume:117440512 Used: 40870606280, Limit: 40877351239. Mem usage has exceed the limit of query pool
             - ErrorMsg__DUP(5): Memory of query_pool exceed limit. try consume:160 Used: 40849431752, Limit: 40877351239. Mem usage has exceed the limit of query pool
             - CloseTime: 919ns
```

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Review by satanson — DISMISSED** [review]

**Review by ZiheLiu — APPROVED** [review]

**Review by satanson — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by liuyehcf** [comment]
run starrocks_fe_unittest

**Comment by liuyehcf** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 16 / 16 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/common/util/RuntimeProfile.java|16|16|100.00%|[]|

**Comment by liuyehcf** [comment]
@Mergifyio backport branch-3.0

**Comment by liuyehcf** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
