### PR TITLE
[BugFix] Add WARNING log when stats collect fail

### PR DESCRIPTION
**Pull request by HangyuanLiu**
## What type of PR is this：
- [x] bugfix
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

1. Add WARNING log when stats collect fail
2. Fix the problem that the Config.statistic_collect_max_row_count_per_query configuration is too large, resulting in int out of bounds

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Review by kangkaisen — APPROVED** [review]

**Review by Seaven — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by HangyuanLiu** [comment]
run starrocks_fe_unittest

**Comment by HangyuanLiu** [comment]
run starrocks_fe_unittest

**Comment by HangyuanLiu** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 8 / 17 (47.06%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/statistic/StatisticAutoCollector.java|0|1|00.00%|[55]|
|:large_blue_circle:|com/starrocks/statistic/SampleStatisticsCollectJob.java|0|1|00.00%|[54]|
|:large_blue_circle:|com/starrocks/statistic/StatisticExecutor.java|0|3|00.00%|[205, 226, 233]|
|:large_blue_circle:|com/starrocks/statistic/AnalyzeJob.java|0|1|00.00%|[131]|
|:large_blue_circle:|com/starrocks/qe/StmtExecutor.java|0|2|00.00%|[784, 793]|
|:large_blue_circle:|com/starrocks/statistic/FullStatisticsCollectJob.java|0|1|00.00%|[40]|
|:large_blue_circle:|com/starrocks/statistic/BasicStatsMeta.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/statistic/StatisticsCollectJob.java|6|6|100.00%|[]|

**Pull request merged**
