### PR TITLE
[Doc] Add doc for some math functions

### PR DESCRIPTION
**Pull request by tomscut**
Signed-off-by: Tao Li <tomscut@apache.org>

## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [x] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

Add doc for some math functions: `cos`,`acos`,`cosh`,`sin`,`asin`,`sinh`,`tan`,`atan`,`tanh`.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Review by imay — COMMENTED** [review]
should add the new added to `docs/TOC.md` too.

**Comment by tomscut** [comment]
> should add the new added to `docs/TOC.md` too.

Thanks @imay for your review. I updated `TOC.md`.

**Review by imay — APPROVED** [review]

**Comment by evelynzhaojie** [comment]
@mergify backport 2.5 2.4 2.3

**Comment by evelynzhaojie** [comment]
@mergify backport branch-2.5 branch-2.4 branch-2.3

**Pull request merged**
