### PR TITLE
[BugFix] Null JSON array

### LINKED ISSUE #31520: jsonpath extract null key
### Steps to reproduce the behavior (Required)
1. Create table
```
create table tbl_simple (key1 string)  distributed by hash(key1) properties("replication_num"="1");
```
3. Load data
```
 curl --location-trusted -u root:  'http://127.0.0.1:18040/api/db0/tbl_simple/_stream_load' \-X PUT \-H 'format: json'  -H "jsonpaths: [\"$.key1[1].key4\"]" -d '{"key1":null}{"key1":[{"key2":3}, {"key4":5}]}'
```

### Expected behavior (Required)
Load is OK. The value `5` is inserted to column `key1`.
### Real behavior (Required)
Load reports error.
```
curl --location-trusted -u root:  'http://127.0.0.1:18040/api/db0/tbl_simple/_stream_load' \-X PUT \-H 'format: json'  -H "jsonpaths: [\"$.key1[1].key4\"]" -d '{"key1":null}{"key1":[{"key2":3}, {"key4":5}]}'
{
    "TxnId": 16,
    "Label": "cc498e2b-d376-4457-b912-2cb75621c28c",
    "Status": "Fail",
    "Message": "too many filtered rows",
    "NumberTotalRows": 2,
    "NumberLoadedRows": 1,
    "NumberFilteredRows": 1,
    "NumberUnselectedRows": 0,
    "LoadBytes": 46,
    "LoadTimeMs": 28,
    "BeginTxnTimeMs": 1,
    "StreamLoadPlanTimeMs": 1,
    "ReadDataTimeMs": 0,
    "WriteDataTimeMs": 24,
    "CommitAndPublishTimeMs": 0,
    "ErrorURL": "http://127.0.0.1:18040/api/_load_error_log?file=error_log_cb4b39f9a9f237e6_220fa354a97958af"
}%    
```
```
Error: Data quality error: err: The JSON element does not have the requested type., msg: failed to access field as array, field: key1, jsonpath: $.key1[1].key4. Row: {"key1":null}

```
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by rickif**
Fixes https://github.com/StarRocks/starrocks/issues/31520
This PR fixes the issue when use jsonpath to extract null key.

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
- [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.2
  - [x] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/exprs/json_functions.cpp|2|2|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:heart_eyes: **pass** : 4 / 4 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/exprs/json_functions.cpp|4|4|100.00%|[]|

**Review by chaoyli — APPROVED** [review]

**Review by meegoo — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.2

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Pull request merged**
