### PR TITLE
[Refactor] Rename FieldType to LogicalType

### PR DESCRIPTION
**Pull request by imay**

### CODE REVIEW

**Comment by imay** [comment]
run starrocks_admit_test

**Comment by imay** [comment]
run starrocks_admit_test

**Review by chaoyli — APPROVED** [review]

**Comment by imay** [comment]
run starrocks_admit_test

**Review by murphyatwork — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Pull request merged**
