### PR TITLE
[BugFix] fix element_memory_usage of ArrayColumn

### LINKED ISSUE #17035: [sqlancer] asan be crash
### Steps to reproduce the behavior (Required)
```sql
DROP DATABASE IF EXISTS g1;
CREATE DATABASE g1;
USE g1;
admin set frontend config ("enable_decimal_v3" = "true");
CREATE TABLE t0 (c_0_0 VARCHAR(21) NOT NULL,c_0_1 VARCHAR(11) NOT NULL,c_0_2 DATE NOT NULL,c_0_3 DATETIME NOT NULL,c_0_4 BOOLEAN NOT NULL,c_0_5 FLOAT NOT NULL,c_0_6 DOUBLE NOT NULL, INDEX index1_c_0_2(`c_0_2`) USING BITMAP) PRIMARY KEY (c_0_0,c_0_1,c_0_2,c_0_3,c_0_4) PARTITION BY RANGE(c_0_2) (START ("2010-01-01") END ("2022-12-31") EVERY (INTERVAL 395 day)) DISTRIBUTED BY HASH (c_0_4) BUCKETS 3 properties("replication_num"="3") ;
CREATE TABLE IF NOT EXISTS t1 (c_1_0 DATETIME NULL ,c_1_1 DATETIME NULL ,c_1_2 DECIMAL(22, 20)  NULL ,c_1_3 DECIMAL(29, 10)  NULL ,c_1_4 ARRAY<STRING> NULL ) UNIQUE KEY (c_1_0,c_1_1,c_1_2,c_1_3) PARTITION BY RANGE(c_1_1) (START ("2010-01-01") END ("2022-12-31") EVERY (INTERVAL 4747 day)) DISTRIBUTED BY HASH (c_1_1) BUCKETS 3 properties("replication_num"="3") ;
CREATE TABLE IF NOT EXISTS t2 (c_2_0 DATE NOT NULL ,c_2_1 DECIMAL(10, 2)  NULL ,c_2_2 SMALLINT NULL ,c_2_3 DATETIME NULL ,c_2_4 DATETIME NULL ,c_2_5 BOOLEAN NULL ,c_2_6 LARGEINT NOT NULL ) UNIQUE KEY (c_2_0,c_2_1,c_2_2,c_2_3,c_2_4) PARTITION BY RANGE(c_2_0) (START ("2010-01-01") END ("2022-12-31") EVERY (INTERVAL 158 day)) DISTRIBUTED BY HASH (c_2_2) BUCKETS 3 properties("replication_num"="3") ;
CREATE TABLE IF NOT EXISTS t3 (c_3_0 BIGINT NOT NULL ,c_3_1 DATE NULL ,c_3_2 CHAR(1) NULL ,c_3_3 DATE NOT NULL ,c_3_4 DECIMAL(31, 5)  NOT NULL ,c_3_5 BOOLEAN NULL ,c_3_6 DATETIME NOT NULL ,c_3_7 CHAR(11) NOT NULL ,c_3_8 JSON NOT NULL ,c_3_9 BIGINT NULL , INDEX index1_c_3_0(`c_3_0`) USING BITMAP, INDEX index1_c_3_1(`c_3_1`) USING BITMAP) DUPLICATE KEY (c_3_0,c_3_1,c_3_2,c_3_3,c_3_4,c_3_5,c_3_6,c_3_7) PARTITION BY RANGE(c_3_1) (START ("2010-01-01") END ("2022-12-31") EVERY (INTERVAL 431 day)) DISTRIBUTED BY HASH (c_3_2,c_3_4,c_3_7,c_3_3,c_3_1,c_3_0) BUCKETS 3 properties("replication_num"="3") ;
CREATE TABLE t4 (c_4_0 DATE NULL ,c_4_1 DATE NOT NULL ,c_4_2 BIGINT NOT NULL ,c_4_3 DATETIME NOT NULL ,c_4_4 BIGINT NULL ,c_4_5 ARRAY<INT> NOT NULL ) UNIQUE KEY (c_4_0,c_4_1,c_4_2,c_4_3) PARTITION BY RANGE(c_4_0) (START ("2010-01-01") END ("2022-12-31") EVERY (INTERVAL 197 day)) DISTRIBUTED BY HASH (c_4_1,c_4_2,c_4_0,c_4_3) BUCKETS 3 properties("replication_num"="3") ;
INSERT INTO t1 VALUES ('2010-01-12 08:00:14', '2009-12-31 08:00:14', 6.2E-19, 3282632.1101824035, ["hX", "", "gYHA1B1", "V", "ip", "V"]), ('2010-01-01 08:00:14', '2010-01-23 08:00:14', 1.7E-19, 105453677.5535555583, ["", "rqW", "NGCm", "", "33nj", "3VCeBrRiV", "G", "jj"]);
INSERT INTO t4 VALUES ('2010-01-20', '2010-01-03', 308586070, '2010-01-02 08:00:14', 308586070, []), ('2010-01-10', '2010-01-25', -853605359, '2009-12-31 08:00:14', 741017903, [308586070, -853605359, 741017903]);
INSERT INTO t0 VALUES ('', 'IzN', '2010-01-11', '2010-01-14 08:00:14', false, 0.33101541936034307, 0.33101541936034307);
INSERT INTO t1 VALUES ('2010-01-02 08:00:14', '2010-01-01 08:00:14', 3.3E-19, 724436162.5298733594, ["sA", "nl", "mn", "H1", "j", "wgbYb"]);
INSERT INTO t3 VALUES (830310348, '2010-01-31', '', '2010-01-25', 984691510701089400825.48087, true, '2010-01-26 08:00:14', '3', parse_json('{"xx": null, "Div": null, "T3bRDqBC": [true, {"zsz": null, "A": null, "IiJILK": "JK", "VpEk": 8.30310348E8, "yT5j": null, "v5da": "", "p": false, "D6": -1030020985, "DtOqPCLU7": null, "rVPY": 0.06962082666178093, "ib": false, "WvQjvRubv": 0.09354133284116084, "ez7s8Zm": true, "hKWwzmn": 0.6401034765282018}, null, [0.314646588943846], null, "V", {"WkfOaM8d": -967187686, "CZUfFS": null, "mul": "x", "e": false, "O7": true, "is": null, "IHNBcp": -967187686, "P": "", "R": false, "neIs": 1198660436, "oZs6wEbX": 0.9766763645169708, "MPEy": true, "cd46zT": true, "4C9l": false, "gC": true}], "S": 0.9766763645169708, "wZ": "OKP", "PsvJe8": 741017903, "g9H4TnU": "", "zBgXMYjE3": "iBUEtdx"}'), -853605359);
INSERT INTO t3 VALUES (-999622060, '2010-01-15', '', '2010-01-28', 338872957444539268934.13615, false, '2010-01-10 08:00:14', 'bbCo', parse_json('{"t6": null, "f": "PV", "tF1": false}'), 1865696245), (308586070, '2010-01-07', '', '2010-01-16', 166552980468208433606.49178, false, '2010-01-09 08:00:14', '', parse_json('{"wm": null}'), -2014174463);
CREATE MATERIALIZED VIEW v0 AS SELECT t0_30.c_0_2, t0_30.c_0_5, MIN(t0_30.c_0_0) , MIN(t0_30.c_0_1) , MIN(t0_30.c_0_3) , MAX(t0_30.c_0_4) , MAX(t0_30.c_0_6)  FROM t0 AS t0_30 GROUP BY t0_30.c_0_2, t0_30.c_0_5 ORDER BY t0_30.c_0_2, t0_30.c_0_5 ASC;
CREATE MATERIALIZED VIEW v0 AS SELECT t2_37.c_2_0, t2_37.c_2_1, t2_37.c_2_2, t2_37.c_2_3, t2_37.c_2_4, t2_37.c_2_5, t2_37.c_2_6 FROM t2 AS t2_37;
DELETE FROM t4 WHERE c_4_3='1969-12-20 18:19:37';
INSERT INTO t1 VALUES ('2010-01-16 08:00:14', '2010-01-05 08:00:14', 2.6E-19, 873442335.1899409528, ["Ug", "uOtQ75", "6", "M", "8idEXMG4g"]);
INSERT INTO t1 VALUES ('2010-01-25 08:00:14', '2010-01-15 08:00:14', 8.6E-19, 697594508.6993303864, ["a", "16o8nXITb", "kQ", "mQBCNJh9", "KJOP5Am", "v", "Vz"]);
INSERT INTO t4 VALUES ('2010-01-25', '2010-01-20', 1, '2010-01-19 08:00:14', -506405533, [-493622612, 317316045, 593437103, -967187686, 974083477, 1198660436, 317316045, -493622612, 1484401309, 9223372036854775807]), ('2010-01-11', '2010-01-06', 387646362, '2010-01-31 08:00:14', 1115321934, [540498582, 559316933, 1115321934, 555353127, 1484401309, -108983382, 1198660436, -506405533, 1367342245, -994720520]), ('2010-01-26', '2010-01-25', -1519481478, '2010-01-06 08:00:14', NULL, [-362441983, -1219638716, -1030020985, 210379819, -1192517174, -2065807042, 270285852, -517629440, 1198660436, -1219638716]);
INSERT INTO t1 VALUES ('2010-01-29 08:00:14', '2010-01-29 08:00:14', 8.4E-19, 589214830.8127466201, ["JAA", ""]), ('2010-01-05 08:00:14', '2010-01-20 08:00:14', 1E-20, 252545139.1480325774, ["F", "HugBJj", "", "", ""]), ('2010-01-11 08:00:14', '2010-01-04 08:00:14', 2.4E-19, 642194647.6556075885, ["", "SpYQSZMn3", "Y", "Ro6"]);
INSERT INTO t3 VALUES (540498582, '2010-01-16', '', '2010-01-15', 544138253118803705277.17333, true, '2010-01-30 08:00:14', 'z', parse_json('{"9SF7": true, "tHU": null, "8i3Thzd": 0.9877528294777786, "zLjH6e": "", "LHqF": null, "3vW": 0.836506707094925, "Y": -1576296042, "53FY82": 0.19198389867796528, "q39FTq9Lv": true, "X70JgKX": 323313324}'), NULL), (-362441983, '2010-01-29', '', '2010-01-03', 502721284569970867650.56792, true, '2010-01-09 08:00:14', '', parse_json('{}'), -1099211251);
INSERT INTO t4 VALUES ('2010-01-14', '2010-01-07', -1018724209, '2010-01-04 08:00:14', NULL, [1183792843, 210379819, 370684634, -1505614576, 150613391, -1576296042]);
TRUNCATE TABLE t4;
INSERT INTO t2 VALUES ('2010-01-04', 245103.06, 7, '2010-01-22 08:00:14', '2010-01-25 08:00:14', false, 984393204);
INSERT INTO t0 VALUES ('W', 'J', '2010-01-27', '2010-01-31 08:00:14', false, 0.9877528294777786, 0.06962082666178093), ('Eb', '', '2010-01-19', '2010-01-28 08:00:14', false, 0.4720317334337063, 0.21833116709566214), ('', 'g6', '2010-01-17', '2010-01-03 08:00:14', true, 0.4686173767637849, 0.4255496133107617);
INSERT INTO t1 VALUES ('2010-01-30 08:00:14', '2010-01-17 08:00:14', 5.1E-19, 166468690.0899580155, ["", "Ay", "Ro", "Dz", "n3", "ecy7r", "p07nJ", "4QwKiBI", "jY", "0", "Hhbedw", ""]), ('2010-01-01 08:00:14', NULL, 8.9E-19, 313221737.2962274668, ["m", "", "mTD"]);
INSERT INTO t2 VALUES ('2010-01-31', NULL, 0, '2010-01-18 08:00:14', NULL, false, 440235454), ('2010-01-30', 140893.47, 4, '2010-01-09 08:00:14', '2010-01-20 08:00:14', false, -1112446922);
SELECT t1_46.c_1_2, t1_46.c_1_3, t1_46.c_1_1, t1_46.c_1_4 FROM t1 AS t1_46 GROUP BY t1_46.c_1_2, t1_46.c_1_3, t1_46.c_1_1, t1_46.c_1_4;
```

be.out
```Prolog
*** Check failure stack trace: ***
query_id:983b9ac3-a064-11ed-a201-00163e03f184, fragment_instance:983b9ac3-a064-11ed-a201-00163e03f185
tracker:process consumption: 0
tracker:query_pool consumption: -182291
tracker:load consumption: 0
tracker:metadata consumption: 4349407
tracker:tablet_metadata consumption: 2797754
tracker:rowset_metadata consumption: 1493828
tracker:segment_metadata consumption: 13017
tracker:column_metadata consumption: 44808
tracker:tablet_schema consumption: 30770
tracker:segment_zonemap consumption: 7388
tracker:short_key_index consumption: 0
tracker:column_zonemap_index consumption: 13216
tracker:ordinal_index consumption: 10696
tracker:bitmap_index consumption: 5200
tracker:bloom_filter_index consumption: 0
tracker:compaction consumption: 0
tracker:schema_change consumption: 0
tracker:column_pool consumption: 401408
tracker:page_cache consumption: 2275
tracker:update consumption: 147
tracker:chunk_allocator consumption: -262144
tracker:clone consumption: 0
tracker:consistency consumption: 0
*** Aborted at 1675058943 (unix time) try "date -d @1675058943" if you are using GNU date ***
PC: @     0x7ff824630337 __GI_raise
*** SIGABRT (@0x3e80000ed87) received by PID 60807 (TID 0x7ff7a207c700) from PID 60807; stack trace: ***
    @         0x13a6cd32 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7ff8250e55f0 (unknown)
    @     0x7ff824630337 __GI_raise
    @     0x7ff824631a28 __GI_abort
    @          0xaa952f0 starrocks::failure_function()
    @         0x13a6070d google::LogMessage::Fail()
    @         0x13a62b7f google::LogMessage::SendToLog()
    @         0x13a6025e google::LogMessage::Flush()
    @         0x13a63189 google::LogMessageFatal::~LogMessageFatal()
    @         0x1280cdf3 starrocks::NullableColumn::element_memory_usage()
    @         0x127b014a starrocks::ArrayColumn::element_memory_usage()
    @         0x1280ce6b starrocks::NullableColumn::element_memory_usage()
    @         0x127baef2 starrocks::Chunk::element_memory_usage()
    @          0xc590e6d starrocks::pipeline::PartitionExchanger::Partitioner::partition_chunk()
    @          0xc591ff6 starrocks::pipeline::PartitionExchanger::accept()
    @          0xc59af62 starrocks::pipeline::LocalExchangeSinkOperator::push_chunk()
    @          0xacf581d starrocks::pipeline::PipelineDriver::process()
    @         0x12aa2279 starrocks::pipeline::GlobalDriverExecutor::_worker_thread()
    @         0x12aa0bb0 _ZZN9starrocks8pipeline20GlobalDriverExecutor10initializeEiENKUlvE2_clEv
    @         0x12aa9cb4 _ZSt13__invoke_implIvRZN9starrocks8pipeline20GlobalDriverExecutor10initializeEiEUlvE2_JEET_St14__invoke_otherOT0_DpOT1_
    @         0x12aa91b9 _ZSt10__invoke_rIvRZN9starrocks8pipeline20GlobalDriverExecutor10initializeEiEUlvE2_JEENSt9enable_ifIX16is_invocable_r_vIT_T0_DpT1_EES6_E4typeEOS7_DpOS8_
    @         0x12aa84c3 _ZNSt17_Function_handlerIFvvEZN9starrocks8pipeline20GlobalDriverExecutor10initializeEiEUlvE2_E9_M_invokeERKSt9_Any_data
    @          0xa99a00c std::function<>::operator()()
    @         0x11a2c522 starrocks::FunctionRunnable::run()
    @         0x11a29324 starrocks::ThreadPool::dispatch_thread()
    @         0x11a44f30 std::__invoke_impl<>()
    @         0x11a44889 std::__invoke<>()
    @         0x11a43c80 _ZNSt5_BindIFMN9starrocks10ThreadPoolEFvvEPS1_EE6__callIvJEJLm0EEEET_OSt5tupleIJDpT0_EESt12_Index_tupleIJXspT1_EEE
    @         0x11a425e2 std::_Bind<>::operator()<>()
    @         0x11a3f646 std::__invoke_impl<>()
    @         0x11a3cfaa _ZSt10__invoke_rIvRSt5_BindIFMN9starrocks10ThreadPoolEFvvEPS2_EEJEENSt9enable_ifIX16is_invocable_r_vIT_T0_DpT1_EESA_E4typeEOSB_DpOSC_
    @         0x11a39013 std::_Function_handler<>::_M_invoke()
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```sql
mysql> select current_version();
+-------------------+
| current_version() |
+-------------------+
| MAIN-ASAN 2b40640 |
+-------------------+
```

### PR DESCRIPTION
**Pull request by silverbullet233**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #17035 

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 2.5
  - [x] 2.4
  - [x] 2.3
  - [x] 2.2

### CODE REVIEW

**Comment by silverbullet233** [comment]
run starrocks_admit_test

**Review by liuyehcf — APPROVED** [review]

**Review by imay — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.4

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.3

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.2

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Pull request merged**
