### PR TITLE
[Enhancement] Optimze `cosine_similarity` by avx2

### PR DESCRIPTION
**Pull request by yulongfufu**
The dimensions of the vectors are generally very high when performing brute-force vector retrieval calculations. In our online scenarios, there are at least **800** dimensions, and the use of SIMD instructions has a clear optimization effect. The optimization method is similar to: https://github.com/nmslib/hnswlib/blob/master/hnswlib/space_ip.h

The results are consistent with the test case results in the previous unit test：
image

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [x] Yes, this PR will result in a change in behavior.
- [ ] No, this PR will not result in a change in behavior.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [ ] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Review by imay — DISMISSED** [review]

**Review by dirtysalt — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 0 / 7 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/exprs/math_functions.cpp|0|7|00.00%|[754, 755, 756, 757, 760, 762, 845]|

**Comment by dirtysalt** [comment]
@yulongfufu you have to run `./build-support/clang-format.sh` to format cpp code.

**Comment by yulongfufu** [comment]
> @yulongfufu you have to run `./build-support/clang-format.sh` to format cpp code.

Thank you for your guidance~
I have formatted my cpp code and pushed it up again.

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 0 / 24 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/exprs/math_functions.cpp|0|24|00.00%|[754, 755, 756, 757, 758, 759, 760, 844, 847, 848, 849, 850, 851, 852, 854, 855, 858, 859, 860, 861, 864, 866, 867, 871]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 0 / 24 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/exprs/math_functions.cpp|0|24|00.00%|[754, 755, 756, 757, 758, 759, 760, 844, 847, 848, 849, 850, 851, 852, 854, 855, 858, 859, 860, 861, 864, 866, 867, 871]|

**Review by dirtysalt — APPROVED** [review]

**Review by imay — APPROVED** [review]

**Pull request merged**
