### PR TITLE
[BugFix] Fix scheduler problem of colocate and multi-partition cases

### LINKED ISSUE #11834: [Bug] count distinct yields wrong output
### Steps to reproduce the behavior (Required)

Key elements of reproducing the issue:

1. colocate
2. 3 be with 3 replica
3. Insert some data with same bucket key and different partition, so these data will be stored into different tablets.

```sql
CREATE TABLE t0 (
v1 INT(11) NOT NULL,
v2 INT(11) NOT NULL,
v3 DATETIME NOT NULL
) ENGINE=OLAP
DUPLICATE KEY(`v1`)
PARTITION BY RANGE(`v3`)
(
PARTITION p1 VALUES [('2022-09-19 00:00:00'), ('2022-09-26 00:00:00')),
PARTITION p2 VALUES [('2022-09-26 00:00:00'), ('2022-10-03 00:00:00'))
)
DISTRIBUTED BY HASH(`v1`) BUCKETS 10
PROPERTIES (
 "replication_num" = "3",
 "colocate_with" = "not_exist_table"
);

INSERT INTO t0(v1, v2, v3) VALUES
(1, 1, '2022-09-25 01:25:00'),
(1, 2, '2022-09-27 01:20:00'),
(1, 3, '2022-09-27 01:25:00'),
(1, 4, '2022-09-27 01:30:00');

SELECT COUNT(DISTINCT(v1)) from t0;
```

### Expected behavior (Required)

```
+--------------------+
| count(DISTINCT v1) |
+--------------------+
| 1                  |
+--------------------+
```

### Real behavior (Required)

```
+--------------------+
| count(DISTINCT v1) |
+--------------------+
| 2                  |
+--------------------+
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

9f4a558ed

### LINKED ISSUE #11851: [Bug] Window function yields wrong result
### Steps to reproduce the behavior (Required)

Key elements of reproducing the issue:

1. colocate
1. 3 be with 3 replica
1. Insert some data with same bucket key and different partition, so these data will be stored into different tablets.

```sql
CREATE TABLE t0 (
v1 INT(11) NOT NULL,
v2 INT(11) NOT NULL,
v3 DATETIME NOT NULL
) ENGINE=OLAP
DUPLICATE KEY(`v1`)
PARTITION BY RANGE(`v3`)
(
PARTITION p1 VALUES [('2022-09-19 00:00:00'), ('2022-09-26 00:00:00')),
PARTITION p2 VALUES [('2022-09-26 00:00:00'), ('2022-10-03 00:00:00'))
)
DISTRIBUTED BY HASH(`v1`) BUCKETS 10
PROPERTIES (
 "replication_num" = "3",
 "colocate_with" = "not_exist_table"
);

INSERT INTO t0(v1, v2, v3) VALUES
(1, 1, '2022-09-25 01:25:00'),
(1, 2, '2022-09-27 01:20:00'),
(1, 3, '2022-09-27 01:25:00'),
(1, 4, '2022-09-27 01:30:00');

SELECT LAG(v2, 1) OVER(PARTITION BY v1 ORDER BY v2) FROM t0 ORDER BY v2;
```

### Expected behavior (Required)

```
+----------------------------------------------------+
| lag(v2, 1) OVER (PARTITION BY v1 ORDER BY v2 ASC ) |
+----------------------------------------------------+
| <null>                                             |
| 1                                                  |
| 2                                                  |
| 3                                                  |
+----------------------------------------------------+
```

### Real behavior (Required)

```
+----------------------------------------------------+
| lag(v2, 1) OVER (PARTITION BY v1 ORDER BY v2 ASC ) |
+----------------------------------------------------+
| <null>                                             |
| <null>                                             |
| 2                                                  |
| 3                                                  |
+----------------------------------------------------+
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

9f4a558

### PR DESCRIPTION
**Pull request by liuyehcf**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #11834
Fixes #11851

## Problem Summary(Required) ：

For agg and window, lable it with `colocate` if necessary, then ColocatedBackendSelector rather than NormalBackendSelector will be used to select the backends.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [x] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by liuyehcf** [comment]
run starrocks_fe_unittest

**Comment by liuyehcf** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/plan/PlanFragmentBuilder.java|2|2|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 3 / 3 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/plan/PlanFragmentBuilder.java|3|3|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/plan/PlanFragmentBuilder.java|2|2|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 3 / 4 (75.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/plan/PlanFragmentBuilder.java|3|4|75.00%|[2123]|

**Comment by liuyehcf** [comment]
run starrocks_admit_test

**Review by Seaven — DISMISSED** [review]

**Comment by liuyehcf** [comment]
run starrocks_fe_unittest

**Comment by liuyehcf** [comment]
run starrocks_admit_test

**Comment by liuyehcf** [comment]
run starrocks_fe_unittest

**Comment by liuyehcf** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 3 / 4 (75.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/plan/PlanFragmentBuilder.java|3|4|75.00%|[2123]|

**Review by Seaven — APPROVED** [review]

**Review by kangkaisen — APPROVED** [review]

**Comment by liuyehcf** [comment]
@Mergifyio backport branch-2.2 branch-2.3 branch-2.4

**Comment by liuyehcf** [comment]
This pr will induce another problem, which is solved by #12218

**Comment by liuyehcf** [comment]
At least version 2.2.9 is required

**Pull request merged**
