### PR TITLE
[BugFix] Invalid transaction state of stream load task

### PR DESCRIPTION
**Pull request by sduzh**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 9 / 14 (64.29%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/transaction/LakeTableTxnStateListener.java|0|1|00.00%|
|:large_blue_circle:|com/starrocks/transaction/PublishVersionDaemon.java|0|4|00.00%|
|:large_blue_circle:|com/starrocks/transaction/OlapTableTxnStateListener.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/transaction/DatabaseTransactionMgr.java|8|8|100.00%|

**Review by decster — DISMISSED** [review]

**Review by decster — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 3 / 24 (12.50%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/service/FrontendServiceImpl.java|0|5|00.00%|
|:large_blue_circle:|com/starrocks/transaction/LakeTableTxnStateListener.java|0|1|00.00%|
|:large_blue_circle:|com/starrocks/transaction/PublishVersionDaemon.java|0|4|00.00%|
|:large_blue_circle:|com/starrocks/transaction/DatabaseTransactionMgr.java|1|9|11.11%|
|:large_blue_circle:|com/starrocks/transaction/TransactionState.java|1|4|25.00%|
|:large_blue_circle:|com/starrocks/transaction/OlapTableTxnStateListener.java|1|1|100.00%|

**Review by imay — APPROVED** [review]

**Review by chaoyli — APPROVED** [review]

**Comment by imay** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 3 / 24 (12.50%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/service/FrontendServiceImpl.java|0|5|00.00%|
|:large_blue_circle:|com/starrocks/transaction/LakeTableTxnStateListener.java|0|1|00.00%|
|:large_blue_circle:|com/starrocks/transaction/PublishVersionDaemon.java|0|4|00.00%|
|:large_blue_circle:|com/starrocks/transaction/DatabaseTransactionMgr.java|1|9|11.11%|
|:large_blue_circle:|com/starrocks/transaction/TransactionState.java|1|4|25.00%|
|:large_blue_circle:|com/starrocks/transaction/OlapTableTxnStateListener.java|1|1|100.00%|

**Pull request merged**
