### PR TITLE
[Cherry-pick][Enhancement] Validate replica number by BE count in CREATE/ALTER TABLE (#9555)

### LINKED ISSUE #6619: 【show replica】Should be restricted when replication_num of changes is greater than the number of Be nodes
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
```
CREATE TABLE `aggregate_table_with_null` ( `k1` date, `k2` datetime, `k3` char(20), `k4` varchar(20), `k5` boolean, `v1` tinyint sum, `v2` smallint sum, `v3` int sum, `v4` bigint max, `v5` largeint max, `v6` float min, `v7` double min, `v8` decimal(27,9) sum ) ENGINE=OLAP AGGREGATE KEY(`k1`, `k2`, `k3`, `k4`, `k5`) COMMENT "OLAP" DISTRIBUTED BY HASH(`k1`, `k2`, `k3`, `k4`, `k5`) BUCKETS 3 PROPERTIES ( "replication_num" = "3", "storage_format" = "v2" );
```
2. ALTER TABLE '....'
```
ALTER TABLE aggregate_table_with_null SET ("replication_num" = "4")
```
3. SHOW  '....'
```
ADMIN SHOW REPLICA STATUS FROM aggregate_table_with_null;
```

### Expected behavior (Required)
Users should be prompted when the replication_num of changes is greater than the number of Be number
e.g.
```
ERROR 1064 (HY000): Failed to find enough host in all backends. need: 4, Current alive backend is [10006,321442,10007]
```
### Real behavior (Required)
alter table replication_num success，ADMIN SHOW REPLICA STATUS command execution failure 
```
mysql> ADMIN SHOW REPLICA STATUS FROM primary_table_without_null;
ERROR 2027 (HY000): Malformed packet
mysql> ADMIN SHOW REPLICA STATUS FROM primary_table_without_null;
ERROR 2013 (HY000): Lost connection to MySQL server during query
```
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 ```
+----------------------+
| current_version()    |
+----------------------+
| MAIN-RELEASE d12a28a |
+----------------------+
```

### PR DESCRIPTION
**Pull request by waittttting**
## What type of PR is this：
- [ ] bug
- [ ] feature
- [x] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #6619

## Problem Summary(Required) ：

Validate replica number by BE count in CREATE/ALTER TABLE
Currently, we have the following two rules
1. replication_num needs larger than 0
2. replication_num need less than current alive be node count

### CODE REVIEW

**Review by wanpengfei-git — DISMISSED** [review]

**Comment by waittttting** [comment]
run starrocks_fe_unittest

**Review by chaoyli — APPROVED** [review]

**Comment by chaoyli** [comment]
run starrocks_fe_unittest

**Comment by chaoyli** [comment]
run starrocks_fe_unittest

**Comment by waittttting** [comment]
run starrocks_fe_unittes

**Comment by waittttting** [comment]
run starrocks_fe_unittest

**Pull request merged**
