### PR TITLE
[Enhancement] Fix some unchecked Status

### PR DESCRIPTION
**Pull request by sduzh**
Fixes #issue

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 15 / 30 (50.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/runtime/plan_fragment_executor.cpp|0|1|00.00%|[399]|
|:large_blue_circle:|src/exec/pipeline/sink/file_sink_operator.cpp|0|1|00.00%|[111]|
|:large_blue_circle:|src/column/fixed_length_column_base.h|0|3|00.00%|[124, 126, 128]|
|:large_blue_circle:|src/storage/storage_engine.cpp|0|1|00.00%|[676]|
|:large_blue_circle:|src/testutil/desc_tbl_builder.cc|0|1|00.00%|[97]|
|:large_blue_circle:|src/runtime/result_sink.cpp|0|2|00.00%|[158, 160]|
|:large_blue_circle:|src/storage/olap_runtime_range_pruner.hpp|0|1|00.00%|[155]|
|:large_blue_circle:|src/exec/pipeline/result_sink_operator.cpp|0|1|00.00%|[85]|
|:large_blue_circle:|src/util/thrift_util.h|1|5|20.00%|[80, 95, 189, 192]|
|:large_blue_circle:|src/util/thread.cpp|2|2|100.00%|[]|
|:large_blue_circle:|src/exec/query_cache/cache_manager.cpp|1|1|100.00%|[]|
|:large_blue_circle:|src/util/failpoint/fail_point.cpp|1|1|100.00%|[]|
|:large_blue_circle:|src/exec/workgroup/scan_executor.cpp|1|1|100.00%|[]|
|:large_blue_circle:|src/storage/lake/tablet_manager.cpp|2|2|100.00%|[]|
|:large_blue_circle:|src/exec/pipeline/pipeline_driver_executor.cpp|1|1|100.00%|[]|
|:large_blue_circle:|src/runtime/exec_env.cpp|2|2|100.00%|[]|
|:large_blue_circle:|src/fs/fs_broker.cpp|3|3|100.00%|[]|
|:large_blue_circle:|src/util/threadpool.cpp|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 15 / 30 (50.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/runtime/plan_fragment_executor.cpp|0|1|00.00%|[399]|
|:large_blue_circle:|src/exec/pipeline/sink/file_sink_operator.cpp|0|1|00.00%|[111]|
|:large_blue_circle:|src/column/fixed_length_column_base.h|0|3|00.00%|[124, 126, 128]|
|:large_blue_circle:|src/storage/storage_engine.cpp|0|1|00.00%|[676]|
|:large_blue_circle:|src/testutil/desc_tbl_builder.cc|0|1|00.00%|[97]|
|:large_blue_circle:|src/runtime/result_sink.cpp|0|2|00.00%|[158, 160]|
|:large_blue_circle:|src/storage/olap_runtime_range_pruner.hpp|0|1|00.00%|[155]|
|:large_blue_circle:|src/exec/pipeline/result_sink_operator.cpp|0|1|00.00%|[85]|
|:large_blue_circle:|src/util/thrift_util.h|1|5|20.00%|[80, 95, 189, 192]|
|:large_blue_circle:|src/util/thread.cpp|2|2|100.00%|[]|
|:large_blue_circle:|src/exec/query_cache/cache_manager.cpp|1|1|100.00%|[]|
|:large_blue_circle:|src/util/failpoint/fail_point.cpp|1|1|100.00%|[]|
|:large_blue_circle:|src/exec/workgroup/scan_executor.cpp|1|1|100.00%|[]|
|:large_blue_circle:|src/storage/lake/tablet_manager.cpp|2|2|100.00%|[]|
|:large_blue_circle:|src/exec/pipeline/pipeline_driver_executor.cpp|1|1|100.00%|[]|
|:large_blue_circle:|src/runtime/exec_env.cpp|2|2|100.00%|[]|
|:large_blue_circle:|src/fs/fs_broker.cpp|3|3|100.00%|[]|
|:large_blue_circle:|src/util/threadpool.cpp|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 26 / 62 (41.94%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/runtime/plan_fragment_executor.cpp|0|2|00.00%|[399, 400]|
|:large_blue_circle:|src/runtime/multi_cast_data_stream_sink.cpp|0|4|00.00%|[33, 37, 41, 45]|
|:large_blue_circle:|src/exec/pipeline/sink/file_sink_operator.cpp|0|3|00.00%|[111, 112, 113]|
|:large_blue_circle:|src/column/fixed_length_column_base.h|0|3|00.00%|[124, 126, 128]|
|:large_blue_circle:|src/storage/storage_engine.cpp|0|3|00.00%|[676, 677, 1027]|
|:large_blue_circle:|src/testutil/desc_tbl_builder.cc|0|1|00.00%|[97]|
|:large_blue_circle:|src/runtime/result_buffer_mgr.cpp|0|2|00.00%|[168, 169]|
|:large_blue_circle:|src/runtime/result_sink.cpp|0|3|00.00%|[158, 159, 160]|
|:large_blue_circle:|src/storage/olap_runtime_range_pruner.hpp|0|4|00.00%|[155, 156, 166, 167]|
|:large_blue_circle:|src/exec/pipeline/result_sink_operator.cpp|0|3|00.00%|[85, 86, 87]|
|:large_blue_circle:|src/common/daemon.cpp|0|1|00.00%|[279]|
|:large_blue_circle:|src/util/thrift_util.h|1|4|25.00%|[80, 95, 173]|
|:large_blue_circle:|src/exec/workgroup/scan_executor.cpp|2|4|50.00%|[45, 46]|
|:large_blue_circle:|src/exec/pipeline/pipeline_driver_executor.cpp|2|4|50.00%|[69, 70]|
|:large_blue_circle:|src/util/thread.cpp|2|2|100.00%|[]|
|:large_blue_circle:|src/exec/query_cache/cache_manager.cpp|1|1|100.00%|[]|
|:large_blue_circle:|src/exec/pipeline/query_context.cpp|2|2|100.00%|[]|
|:large_blue_circle:|src/util/failpoint/fail_point.cpp|1|1|100.00%|[]|
|:large_blue_circle:|src/storage/lake/tablet_manager.cpp|6|6|100.00%|[]|
|:large_blue_circle:|src/runtime/exec_env.cpp|2|2|100.00%|[]|
|:large_blue_circle:|src/fs/fs_broker.cpp|4|4|100.00%|[]|
|:large_blue_circle:|src/exec/pipeline/exec_state_reporter.cpp|2|2|100.00%|[]|
|:large_blue_circle:|src/util/threadpool.cpp|1|1|100.00%|[]|

**Review by kevincai — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 15 / 32 (46.88%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/runtime/plan_fragment_executor.cpp|0|1|00.00%|[399]|
|:large_blue_circle:|src/exec/pipeline/sink/file_sink_operator.cpp|0|1|00.00%|[111]|
|:large_blue_circle:|src/column/fixed_length_column_base.h|0|3|00.00%|[124, 126, 128]|
|:large_blue_circle:|src/storage/storage_engine.cpp|0|3|00.00%|[352, 676, 986]|
|:large_blue_circle:|src/testutil/desc_tbl_builder.cc|0|1|00.00%|[97]|
|:large_blue_circle:|src/runtime/result_sink.cpp|0|2|00.00%|[158, 160]|
|:large_blue_circle:|src/storage/olap_runtime_range_pruner.hpp|0|1|00.00%|[155]|
|:large_blue_circle:|src/exec/pipeline/result_sink_operator.cpp|0|1|00.00%|[85]|
|:large_blue_circle:|src/util/thrift_util.h|1|5|20.00%|[80, 95, 189, 192]|
|:large_blue_circle:|src/util/thread.cpp|2|2|100.00%|[]|
|:large_blue_circle:|src/exec/query_cache/cache_manager.cpp|1|1|100.00%|[]|
|:large_blue_circle:|src/exec/workgroup/scan_executor.cpp|1|1|100.00%|[]|
|:large_blue_circle:|src/storage/lake/tablet_manager.cpp|2|2|100.00%|[]|
|:large_blue_circle:|src/exec/pipeline/pipeline_driver_executor.cpp|1|1|100.00%|[]|
|:large_blue_circle:|src/runtime/runtime_state.cpp|1|1|100.00%|[]|
|:large_blue_circle:|src/runtime/exec_env.cpp|2|2|100.00%|[]|
|:large_blue_circle:|src/fs/fs_broker.cpp|3|3|100.00%|[]|
|:large_blue_circle:|src/util/threadpool.cpp|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 15 / 32 (46.88%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/runtime/plan_fragment_executor.cpp|0|1|00.00%|[399]|
|:large_blue_circle:|src/exec/pipeline/sink/file_sink_operator.cpp|0|1|00.00%|[111]|
|:large_blue_circle:|src/column/fixed_length_column_base.h|0|3|00.00%|[124, 126, 128]|
|:large_blue_circle:|src/storage/storage_engine.cpp|0|3|00.00%|[352, 676, 986]|
|:large_blue_circle:|src/testutil/desc_tbl_builder.cc|0|1|00.00%|[97]|
|:large_blue_circle:|src/runtime/result_sink.cpp|0|2|00.00%|[158, 160]|
|:large_blue_circle:|src/storage/olap_runtime_range_pruner.hpp|0|1|00.00%|[155]|
|:large_blue_circle:|src/exec/pipeline/result_sink_operator.cpp|0|1|00.00%|[85]|
|:large_blue_circle:|src/util/thrift_util.h|1|5|20.00%|[80, 95, 189, 192]|
|:large_blue_circle:|src/util/thread.cpp|2|2|100.00%|[]|
|:large_blue_circle:|src/exec/query_cache/cache_manager.cpp|1|1|100.00%|[]|
|:large_blue_circle:|src/exec/workgroup/scan_executor.cpp|1|1|100.00%|[]|
|:large_blue_circle:|src/storage/lake/tablet_manager.cpp|2|2|100.00%|[]|
|:large_blue_circle:|src/exec/pipeline/pipeline_driver_executor.cpp|1|1|100.00%|[]|
|:large_blue_circle:|src/runtime/runtime_state.cpp|1|1|100.00%|[]|
|:large_blue_circle:|src/runtime/exec_env.cpp|2|2|100.00%|[]|
|:large_blue_circle:|src/fs/fs_broker.cpp|3|3|100.00%|[]|
|:large_blue_circle:|src/util/threadpool.cpp|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 33 / 73 (45.21%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/runtime/plan_fragment_executor.cpp|0|2|00.00%|[399, 400]|
|:large_blue_circle:|src/runtime/multi_cast_data_stream_sink.cpp|0|4|00.00%|[33, 37, 41, 45]|
|:large_blue_circle:|src/exec/pipeline/sink/file_sink_operator.cpp|0|3|00.00%|[111, 112, 113]|
|:large_blue_circle:|src/column/fixed_length_column_base.h|0|3|00.00%|[124, 126, 128]|
|:large_blue_circle:|src/storage/storage_engine.cpp|0|7|00.00%|[352, 576, 577, 675, 676, 986, 1026]|
|:large_blue_circle:|src/testutil/desc_tbl_builder.cc|0|1|00.00%|[97]|
|:large_blue_circle:|src/runtime/result_buffer_mgr.cpp|0|2|00.00%|[168, 169]|
|:large_blue_circle:|src/runtime/result_sink.cpp|0|3|00.00%|[158, 159, 160]|
|:large_blue_circle:|src/storage/olap_runtime_range_pruner.hpp|0|4|00.00%|[155, 156, 166, 167]|
|:large_blue_circle:|src/exec/pipeline/result_sink_operator.cpp|0|3|00.00%|[85, 86, 87]|
|:large_blue_circle:|src/common/daemon.cpp|0|1|00.00%|[279]|
|:large_blue_circle:|src/util/thrift_util.h|1|4|25.00%|[80, 95, 173]|
|:large_blue_circle:|src/exec/workgroup/scan_executor.cpp|2|4|50.00%|[45, 46]|
|:large_blue_circle:|src/exec/pipeline/pipeline_driver_executor.cpp|2|4|50.00%|[69, 70]|
|:large_blue_circle:|src/storage/lake/vertical_compaction_task.cpp|1|1|100.00%|[]|
|:large_blue_circle:|src/util/thread.cpp|2|2|100.00%|[]|
|:large_blue_circle:|src/storage/lake/general_tablet_writer.cpp|2|2|100.00%|[]|
|:large_blue_circle:|src/exec/query_cache/cache_manager.cpp|1|1|100.00%|[]|
|:large_blue_circle:|src/exec/pipeline/query_context.cpp|2|2|100.00%|[]|
|:large_blue_circle:|src/storage/lake/tablet_manager.cpp|6|6|100.00%|[]|
|:large_blue_circle:|src/storage/lake/delta_writer.cpp|2|2|100.00%|[]|
|:large_blue_circle:|src/runtime/runtime_state.cpp|1|1|100.00%|[]|
|:large_blue_circle:|src/runtime/exec_env.cpp|2|2|100.00%|[]|
|:large_blue_circle:|src/storage/lake/async_delta_writer.cpp|2|2|100.00%|[]|
|:large_blue_circle:|src/fs/fs_broker.cpp|4|4|100.00%|[]|
|:large_blue_circle:|src/exec/pipeline/exec_state_reporter.cpp|2|2|100.00%|[]|
|:large_blue_circle:|src/util/threadpool.cpp|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 33 / 73 (45.21%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/runtime/plan_fragment_executor.cpp|0|2|00.00%|[399, 400]|
|:large_blue_circle:|src/runtime/multi_cast_data_stream_sink.cpp|0|4|00.00%|[33, 37, 41, 45]|
|:large_blue_circle:|src/exec/pipeline/sink/file_sink_operator.cpp|0|3|00.00%|[111, 112, 113]|
|:large_blue_circle:|src/column/fixed_length_column_base.h|0|3|00.00%|[124, 126, 128]|
|:large_blue_circle:|src/storage/storage_engine.cpp|0|7|00.00%|[352, 576, 577, 675, 676, 986, 1026]|
|:large_blue_circle:|src/testutil/desc_tbl_builder.cc|0|1|00.00%|[97]|
|:large_blue_circle:|src/runtime/result_buffer_mgr.cpp|0|2|00.00%|[168, 169]|
|:large_blue_circle:|src/runtime/result_sink.cpp|0|3|00.00%|[158, 159, 160]|
|:large_blue_circle:|src/storage/olap_runtime_range_pruner.hpp|0|4|00.00%|[155, 156, 166, 167]|
|:large_blue_circle:|src/exec/pipeline/result_sink_operator.cpp|0|3|00.00%|[85, 86, 87]|
|:large_blue_circle:|src/common/daemon.cpp|0|1|00.00%|[279]|
|:large_blue_circle:|src/util/thrift_util.h|1|4|25.00%|[80, 95, 173]|
|:large_blue_circle:|src/exec/workgroup/scan_executor.cpp|2|4|50.00%|[45, 46]|
|:large_blue_circle:|src/exec/pipeline/pipeline_driver_executor.cpp|2|4|50.00%|[69, 70]|
|:large_blue_circle:|src/storage/lake/vertical_compaction_task.cpp|1|1|100.00%|[]|
|:large_blue_circle:|src/util/thread.cpp|2|2|100.00%|[]|
|:large_blue_circle:|src/storage/lake/general_tablet_writer.cpp|2|2|100.00%|[]|
|:large_blue_circle:|src/exec/query_cache/cache_manager.cpp|1|1|100.00%|[]|
|:large_blue_circle:|src/exec/pipeline/query_context.cpp|2|2|100.00%|[]|
|:large_blue_circle:|src/storage/lake/tablet_manager.cpp|6|6|100.00%|[]|
|:large_blue_circle:|src/storage/lake/delta_writer.cpp|2|2|100.00%|[]|
|:large_blue_circle:|src/runtime/runtime_state.cpp|1|1|100.00%|[]|
|:large_blue_circle:|src/runtime/exec_env.cpp|2|2|100.00%|[]|
|:large_blue_circle:|src/storage/lake/async_delta_writer.cpp|2|2|100.00%|[]|
|:large_blue_circle:|src/fs/fs_broker.cpp|4|4|100.00%|[]|
|:large_blue_circle:|src/exec/pipeline/exec_state_reporter.cpp|2|2|100.00%|[]|
|:large_blue_circle:|src/util/threadpool.cpp|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 50 / 92 (54.35%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/runtime/plan_fragment_executor.cpp|0|2|00.00%|[399, 400]|
|:large_blue_circle:|src/runtime/multi_cast_data_stream_sink.cpp|0|4|00.00%|[33, 37, 41, 45]|
|:large_blue_circle:|src/exec/pipeline/sink/file_sink_operator.cpp|0|3|00.00%|[111, 112, 113]|
|:large_blue_circle:|src/column/fixed_length_column_base.h|0|3|00.00%|[124, 126, 128]|
|:large_blue_circle:|src/storage/storage_engine.cpp|0|7|00.00%|[352, 576, 577, 675, 676, 986, 1026]|
|:large_blue_circle:|src/testutil/desc_tbl_builder.cc|0|1|00.00%|[97]|
|:large_blue_circle:|src/runtime/result_buffer_mgr.cpp|0|2|00.00%|[168, 169]|
|:large_blue_circle:|src/runtime/result_sink.cpp|0|3|00.00%|[158, 159, 160]|
|:large_blue_circle:|src/storage/olap_runtime_range_pruner.hpp|0|4|00.00%|[155, 156, 166, 167]|
|:large_blue_circle:|src/exec/pipeline/result_sink_operator.cpp|0|3|00.00%|[85, 86, 87]|
|:large_blue_circle:|src/common/daemon.cpp|0|1|00.00%|[279]|
|:large_blue_circle:|src/util/thrift_util.h|1|4|25.00%|[80, 95, 173]|
|:large_blue_circle:|src/storage/tablet_manager.cpp|1|2|50.00%|[1405]|
|:large_blue_circle:|src/exec/workgroup/scan_executor.cpp|2|4|50.00%|[45, 46]|
|:large_blue_circle:|src/exec/pipeline/pipeline_driver_executor.cpp|2|4|50.00%|[69, 70]|
|:large_blue_circle:|src/storage/rowset/scalar_column_iterator.cpp|7|8|87.50%|[138]|
|:large_blue_circle:|src/storage/lake/vertical_compaction_task.cpp|1|1|100.00%|[]|
|:large_blue_circle:|src/util/thread.cpp|2|2|100.00%|[]|
|:large_blue_circle:|src/storage/lake/general_tablet_writer.cpp|2|2|100.00%|[]|
|:large_blue_circle:|src/exec/query_cache/cache_manager.cpp|1|1|100.00%|[]|
|:large_blue_circle:|src/exec/pipeline/query_context.cpp|2|2|100.00%|[]|
|:large_blue_circle:|src/storage/lake/tablet_manager.cpp|6|6|100.00%|[]|
|:large_blue_circle:|src/storage/lake/delta_writer.cpp|2|2|100.00%|[]|
|:large_blue_circle:|src/runtime/runtime_state.cpp|1|1|100.00%|[]|
|:large_blue_circle:|src/runtime/exec_env.cpp|3|3|100.00%|[]|
|:large_blue_circle:|src/storage/tablet_reader.cpp|1|1|100.00%|[]|
|:large_blue_circle:|src/storage/lake/async_delta_writer.cpp|2|2|100.00%|[]|
|:large_blue_circle:|src/fs/fs_broker.cpp|4|4|100.00%|[]|
|:large_blue_circle:|src/storage/tablet_meta.cpp|3|3|100.00%|[]|
|:large_blue_circle:|src/exec/pipeline/exec_state_reporter.cpp|2|2|100.00%|[]|
|:large_blue_circle:|src/util/threadpool.cpp|1|1|100.00%|[]|
|:large_blue_circle:|src/storage/rowset/segment_iterator.cpp|4|4|100.00%|[]|

**Review by kevincai — APPROVED** [review]

**Review by wyb — APPROVED** [review]

**Review by Astralidea — APPROVED** [review]

**Pull request merged**
