### PR TITLE
Update SHOW RESTORE.md

### PR DESCRIPTION
**Pull request by fieldsfarmer**
Add two missing fields.

## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [x] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：
This will clarify the return fields of the query return.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Comment by fieldsfarmer** [comment]
Signed-off-by: Kaiwei Wang <fieldsfarmer@gmail.com>

**Comment by EsoragotoSpirit** [comment]
Thank you for your contribution @fieldsfarmer . Your PR has been modified and will be merged soon.

**Review by EsoragotoSpirit — APPROVED** [review]

**Review by hellolilyliuyi — APPROVED** [review]

**Comment by EsoragotoSpirit** [comment]
run starrocks_be_unittest

**Comment by EsoragotoSpirit** [comment]
run starrocks_clang-format

**Comment by EsoragotoSpirit** [comment]
run starrocks_fe_unittest

**Comment by EsoragotoSpirit** [comment]
run starrocks_fe_unittest

**Comment by EsoragotoSpirit** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
