### PR TITLE
[Feature] Migrate the desc statement from the old to new parser and analyzer

### PR DESCRIPTION
**Pull request by leoyy0316**
## What type of PR is this：
- [ ] bug
- [ ] feature
- [ ] enhancement
- [x] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #https://github.com/StarRocks/starrocks/issues/7285

### CODE REVIEW

**Comment by leoyy0316** [comment]
link: https://github.com/StarRocks/starrocks/pull/8053

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 68 / 118 (57.63%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/ShowStmtAnalyzer.java|50|96|52.08%|
|:large_blue_circle:|com/starrocks/analysis/DescribeStmt.java|9|13|69.23%|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|3|3|100.00%|
|:large_blue_circle:|com/starrocks/sql/ast/AstVisitor.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/sql/analyzer/PrivilegeChecker.java|5|5|100.00%|

**Comment by dulong41** [comment]
run starrocks_admit_test

**Review by HangyuanLiu — APPROVED** [review]

**Comment by imay** [comment]
Should pay attention to sonar alert

**Comment by leoyy0316** [comment]
> Should pay attention to sonar alert

I don't think NPE will be reported here，I think this test is not reasonable. https://github.com/StarRocks/starrocks/pull/8053 same code check successfully

**Review by imay — APPROVED** [review]

**Pull request merged**
