### PR TITLE
[Lake] Support lake table query plan

### PR DESCRIPTION
**Pull request by wyb**
## What type of PR is this：
- [ ] bug
- [x] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Problem Summary(Required) ：

Use the same query plan as olap table.
1. Add new TLakeScanNode, and BE will scan lake tablet by connector framework if is lake table.
2. Other plan adaptation: analyzer, statistics calculator.
3. Refactor table type method.

### CODE REVIEW

**Review by Seaven — DISMISSED** [review]

**Review by wuleistarrocks — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 9 / 14 (64.29%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/statistic/StatisticAutoCollector.java|0|1|00.00%|
|:large_blue_circle:|com/starrocks/statistic/AnalyzeManager.java|0|2|00.00%|
|:large_blue_circle:|com/starrocks/planner/OlapScanNode.java|1|2|50.00%|
|:large_blue_circle:|com/starrocks/sql/analyzer/AnalyzeStmtAnalyzer.java|1|2|50.00%|
|:large_blue_circle:|com/starrocks/catalog/Table.java|2|2|100.00%|
|:large_blue_circle:|com/starrocks/transaction/TransactionStateListenerFactory.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/sql/optimizer/statistics/StatisticsCalculator.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/transaction/TransactionLogApplierFactory.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/sql/optimizer/Utils.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/sql/analyzer/QueryAnalyzer.java|1|1|100.00%|

**Comment by wyb** [comment]
run starrocks_fe_unittest

**Comment by wyb** [comment]
run starrocks_fe_unittest

**Comment by wyb** [comment]
run starrocks_fe_unittest

**Comment by wyb** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 22 / 42 (52.38%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/statistic/StatisticAutoCollector.java|0|1|00.00%|
|:large_blue_circle:|com/starrocks/statistic/AnalyzeManager.java|0|2|00.00%|
|:large_blue_circle:|com/starrocks/planner/OlapScanNode.java|14|30|46.67%|
|:large_blue_circle:|com/starrocks/sql/analyzer/AnalyzeStmtAnalyzer.java|1|2|50.00%|
|:large_blue_circle:|com/starrocks/catalog/Table.java|2|2|100.00%|
|:large_blue_circle:|com/starrocks/transaction/TransactionStateListenerFactory.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/sql/optimizer/statistics/StatisticsCalculator.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/transaction/TransactionLogApplierFactory.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/sql/optimizer/Utils.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/sql/analyzer/QueryAnalyzer.java|1|1|100.00%|

**Review by wuleistarrocks — APPROVED** [review]

**Review by Seaven — APPROVED** [review]

**Review by sduzh — APPROVED** [review]

**Pull request merged**
