### PR TITLE
[BugFix] VectorizedCastToStringExpr cast varchar to varchar need clone

### PR DESCRIPTION
**Pull request by zombee0**
## What type of PR is this:
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes:

Fixes # 
VectorizedCaseToStringExpr cast Varchar to Varchar need clone, 
1.SELF_CAST clone column, 
2. Varchar to Varchar is dealed by VectorizedCastToStringExpr::_evaluate_string, we need clone it too,
3. we encountered bug in JDBC scanner, because we use reference, if we don't clone, column pass to pipeline but update by scanner.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
        I will add case in StarrocksTest
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 3.0
  - [x] 2.5
  - [x] 2.4
  - [x] 2.3

### CODE REVIEW

**Review by Seaven — APPROVED** [review]

**Comment by Seaven** [comment]
BTW，why will appear cast(string to string)?

**Comment by zombee0** [comment]
> BTW，why will appear cast(string to string)?

@Seaven In jdbc scanner, some type can't be written directly to the column, so we have an intermediate type. for date type, it is Date->Varchar->SR's Date type, for Varchar type, it is String->Varchar->Varchar. so there is Varchar to Varchar.

**Review by dirtysalt — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.4

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.3

**Pull request merged**
