### PR TITLE
[Refactor][meta-format-change] Refactor resource and task image using SRMetaBlock API

### PR DESCRIPTION
**Pull request by gengjun-git**
Fixes #issue

## What type of PR is this:
- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [x] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 0 / 37 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/scheduler/TaskManager.java|0|26|00.00%|[483, 484, 485, 486, 487, 488, 490, 491, 492, 493, 494, 495, 522, 523, 524, 525, 526, 527, 528, 529, 531, 532, 533, 534, 536, 537]|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|0|2|00.00%|[1429, 1430]|
|:large_blue_circle:|com/starrocks/catalog/ResourceMgr.java|0|9|00.00%|[354, 355, 356, 357, 360, 362, 363, 365, 367]|

**Review by HangyuanLiu — DISMISSED** [review]

**Review by nshangyiming — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 0 / 37 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/scheduler/TaskManager.java|0|26|00.00%|[504, 505, 506, 507, 508, 509, 511, 512, 513, 514, 515, 516, 543, 544, 545, 546, 547, 548, 549, 550, 552, 553, 554, 555, 557, 558]|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|0|2|00.00%|[1452, 1453]|
|:large_blue_circle:|com/starrocks/catalog/ResourceMgr.java|0|9|00.00%|[354, 355, 356, 357, 360, 362, 363, 365, 367]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 23 / 74 (31.08%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/scheduler/TaskManager.java|0|26|00.00%|[505, 506, 507, 508, 509, 510, 512, 513, 514, 515, 516, 517, 544, 545, 546, 547, 548, 549, 550, 551, 553, 554, 555, 556, 558, 559]|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|0|12|00.00%|[1428, 1433, 1439, 1440, 1441, 1442, 1444, 1445, 1446, 1447, 1448, 1455]|
|:large_blue_circle:|com/starrocks/catalog/ResourceMgr.java|0|13|00.00%|[356, 357, 358, 359, 363, 365, 366, 368, 370, 372, 373, 374, 375]|
|:large_blue_circle:|com/starrocks/persist/metablock/SRMetaBlockID.java|23|23|100.00%|[]|

**Comment by gengjun-git** [comment]
@mergifyio rebase

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 23 / 74 (31.08%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/scheduler/TaskManager.java|0|26|00.00%|[505, 506, 507, 508, 509, 510, 512, 513, 514, 515, 516, 517, 544, 545, 546, 547, 548, 549, 550, 551, 553, 554, 555, 556, 558, 559]|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|0|12|00.00%|[1428, 1433, 1439, 1440, 1441, 1442, 1444, 1445, 1446, 1447, 1448, 1455]|
|:large_blue_circle:|com/starrocks/catalog/ResourceMgr.java|0|13|00.00%|[356, 357, 358, 359, 363, 365, 366, 368, 370, 372, 373, 374, 375]|
|:large_blue_circle:|com/starrocks/persist/metablock/SRMetaBlockID.java|23|23|100.00%|[]|

**Review by nshangyiming — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 23 / 74 (31.08%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/scheduler/TaskManager.java|0|26|00.00%|[505, 506, 507, 508, 509, 510, 512, 513, 514, 515, 516, 517, 544, 545, 546, 547, 548, 549, 550, 551, 553, 554, 555, 556, 558, 559]|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|0|12|00.00%|[1428, 1433, 1439, 1440, 1441, 1442, 1444, 1445, 1446, 1447, 1448, 1455]|
|:large_blue_circle:|com/starrocks/catalog/ResourceMgr.java|0|13|00.00%|[356, 357, 358, 359, 363, 365, 366, 368, 370, 372, 373, 374, 375]|
|:large_blue_circle:|com/starrocks/persist/metablock/SRMetaBlockID.java|23|23|100.00%|[]|

**Review by Youngwb — APPROVED** [review]

**Review by Astralidea — APPROVED** [review]

**Pull request merged**
