### PR TITLE
[Feature] Adding str2date Function to mv creation statement based on jdbc catalog. (#29923)

### PR DESCRIPTION
**Pull request by LiShuMing**
…jdbc catalog. (#29923)

Fixes #issue

## What type of PR is this:

- [ ] BugFix
- [x] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 113 / 138 (81.88%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/PartitionKey.java|0|8|00.00%|[300, 301, 302, 371, 372, 373, 510, 511]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AnalyzerUtils.java|9|12|75.00%|[1229, 1237, 1241]|
|:large_blue_circle:|com/starrocks/sql/analyzer/MaterializedViewPartitionFunctionChecker.java|10|13|76.92%|[108, 114, 125]|
|:large_blue_circle:|com/starrocks/scheduler/PartitionBasedMvRefreshProcessor.java|24|29|82.76%|[661, 662, 663, 1243, 1244]|
|:large_blue_circle:|com/starrocks/connector/PartitionUtil.java|34|38|89.47%|[654, 658, 659, 660]|
|:large_blue_circle:|com/starrocks/sql/common/SyncPartitionUtils.java|23|25|92.00%|[199, 200]|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|8|8|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/PartitionExprAnalyzer.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 121 / 146 (82.88%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/PartitionKey.java|0|8|00.00%|[300, 301, 302, 371, 372, 373, 510, 511]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AnalyzerUtils.java|9|12|75.00%|[1229, 1237, 1241]|
|:large_blue_circle:|com/starrocks/sql/analyzer/MaterializedViewPartitionFunctionChecker.java|10|13|76.92%|[108, 114, 125]|
|:large_blue_circle:|com/starrocks/scheduler/PartitionBasedMvRefreshProcessor.java|32|37|86.49%|[671, 672, 673, 1253, 1254]|
|:large_blue_circle:|com/starrocks/connector/PartitionUtil.java|34|38|89.47%|[654, 658, 659, 660]|
|:large_blue_circle:|com/starrocks/sql/common/SyncPartitionUtils.java|23|25|92.00%|[188, 189]|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|8|8|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/PartitionExprAnalyzer.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by murphyatwork — APPROVED** [review]

**Pull request merged**
