### PR TITLE
Support more data types and fix a operator error for hudi table

### PR DESCRIPTION
**Pull request by miomiocat**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] others

1. remove useless codes in HiveTable
2. fix a rule transform exception of hudi operator in some code path due to typo
3. support datetime and binary data type

### CODE REVIEW

**Comment by miomiocat** [comment]
run starrocks_be_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 0 / 2 (00.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/physical/PhysicalHudiScanOperator.java|0|1|00.00%|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/logical/LogicalHudiScanOperator.java|0|1|00.00%|

**Comment by miomiocat** [comment]
run starrocks_be_unittest

**Comment by miomiocat** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 1 / 5 (20.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/physical/PhysicalHudiScanOperator.java|0|1|00.00%|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/logical/LogicalHudiScanOperator.java|0|1|00.00%|
|:large_blue_circle:|com/starrocks/catalog/HudiTable.java|1|3|33.33%|

**Pull request closed without merging**
