### PR TITLE
[BugFix] Fix sonar test warning in FE

### PR DESCRIPTION
**Pull request by HangyuanLiu**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 21 / 41 (51.22%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/fs/hdfs/HdfsFsManager.java|0|9|00.00%|[65, 120, 124, 222, 227, 320, 878, 887, 898]|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/ScanOperatorPredicates.java|1|12|08.33%|[76, 79, 80, 82, 83, 84, 85, 86, 87, 88, 89]|
|:large_blue_circle:|com/starrocks/qe/HelpModule.java|20|20|100.00%|[]|

**Review by kangkaisen — DISMISSED** [review]

**Review by murphyatwork — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by HangyuanLiu** [comment]
run starrocks_admit_test

**Comment by HangyuanLiu** [comment]
run starrocks_fe_unittest

**Comment by HangyuanLiu** [comment]
run starrocks_fe_unittest

**Comment by packy92** [comment]
run starrocks_fe_unittest

**Review by murphyatwork — APPROVED** [review]

**Review by kangkaisen — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by HangyuanLiu** [comment]
run starrocks_fe_unittest

**Comment by HangyuanLiu** [comment]
starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 21 / 40 (52.50%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/fs/hdfs/HdfsFsManager.java|0|8|00.00%|[65, 120, 124, 222, 227, 320, 878, 887]|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/ScanOperatorPredicates.java|1|12|08.33%|[89, 92, 93, 95, 96, 97, 98, 99, 100, 101, 102]|
|:large_blue_circle:|com/starrocks/qe/HelpModule.java|20|20|100.00%|[]|

**Comment by HangyuanLiu** [comment]
starrocks_admit_test

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Pull request merged**
