### PR TITLE
[Tool] disable release docker image workflow trigers

### LINKED ISSUE #29699: File specified in your workflow does not exist.
- File name: https://github.com/StarRocks/starrocks/actions/workflows/release-docker-image.yml
- Error message: ERROR: failed to solve: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount3962177920/artifact-ubuntu.Dockerfile: no such file or directory

Please update your Dockerfile accordingly. 

### Expected behavior (Required)

Job succeeds for each artifact Docker image build. 

### Real behavior (Required)

artifact Docker image build job fails for every release. 

### StarRocks version (Required)

The latest release.

### PR DESCRIPTION
**Pull request by kevincai**
* don't trigger release-docker-image action
* let the workflow here just as an example

Fixes #29699

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [X] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [X] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [X] I have checked the version labels which the pr will be auto-backported to the target branch
  - [X] 3.1
  - [X] 3.0
  - [X] 2.5
  - [ ] 2.4

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by imay — APPROVED** [review]

**Review by imay — APPROVED** [review]

**Comment by kevincai** [comment]
@mergifyio backport branch-3.1 branch-3.0 branch-2.5

**Comment by kevincai** [comment]
manual backport to branch-2.5 at https://github.com/StarRocks/starrocks/pull/29766

**Pull request merged**
