### PR TITLE
[BugFix] Avoid BE crash when apache-orc throw orc::ParseError exception

### PR DESCRIPTION
**Pull request by Smith-Cruise**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes [#1974](https://github.com/StarRocks/StarRocksTest/issues/1974)

## Problem Summary(Required) ：

apache-orc will throw `orc::ParseError` exception when parse orc fails, we need to catch it every where we use it. Otherwise, it will occur BE crashed.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 3.0
  - [x] 2.5
  - [x] 2.4
  - [x] 2.3

### CODE REVIEW

**Review by DorianZheng — APPROVED** [review]

**Review by dirtysalt — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by dirtysalt — APPROVED** [review]

**Comment by Smith-Cruise** [comment]
run starrocks_be_unittest

**Comment by Smith-Cruise** [comment]
run starrocks_admit_test

**Review by imay — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.4

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.3

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Pull request merged**
