### PR TITLE
[Refactor] Remove materialized view statement parser / analyzer deprecated code

### PR DESCRIPTION
**Pull request by HangyuanLiu**
## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [x] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 162 / 260 (62.31%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/load/loadv2/LoadManager.java|0|2|00.00%|[159, 162]|
|:large_blue_circle:|com/starrocks/execution/CancelRefreshMaterializedViewExecutor.java|0|1|00.00%|[12]|
|:large_blue_circle:|com/starrocks/sql/analyzer/LoadStmtAnalyzer.java|0|2|00.00%|[108, 109]|
|:large_blue_circle:|com/starrocks/sql/ast/RandomDistributionDesc.java|0|1|00.00%|[61]|
|:large_blue_circle:|com/starrocks/catalog/SchemaTable.java|1|51|01.96%|[506, 508, 509, 510, 511, 514, 515, 517, 518, 519, 520, 521, 523, 525, 526, 527, 528, 529, 530, 531, 533, 534, 535, 537, 538, 540, 541, 542, 543, 544, 546, 547, 549, 550, 551, 552, 553, 554, 555, 556, 562, 563, 564, 565, 566, 569, 570, 571, 574, 578]|
|:large_blue_circle:|com/starrocks/sql/ast/CreateFunctionStmt.java|1|8|12.50%|[186, 281, 282, 289, 292, 293, 299]|
|:large_blue_circle:|com/starrocks/sql/ast/DefaultValueExpr.java|2|6|33.33%|[13, 17, 23, 27]|
|:large_blue_circle:|com/starrocks/sql/ast/SyncStmt.java|2|4|50.00%|[11, 16]|
|:large_blue_circle:|com/starrocks/sql/ast/KillStmt.java|5|9|55.56%|[23, 27, 32, 42]|
|:large_blue_circle:|com/starrocks/sql/ast/SelectListItem.java|16|27|59.26%|[33, 34, 35, 37, 39, 40, 41, 42, 46, 62, 63]|
|:large_blue_circle:|com/starrocks/sql/ast/DropFunctionStmt.java|9|12|75.00%|[32, 41, 51]|
|:large_blue_circle:|com/starrocks/sql/ast/DataDescription.java|4|5|80.00%|[674]|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|21|25|84.00%|[367, 368, 372, 373]|
|:large_blue_circle:|com/starrocks/sql/ast/FunctionArgsDef.java|13|15|86.67%|[41, 42]|
|:large_blue_circle:|com/starrocks/sql/ast/PartitionKeyDesc.java|8|9|88.89%|[104]|
|:large_blue_circle:|com/starrocks/sql/ast/RecoverPartitionStmt.java|9|10|90.00%|[35]|
|:large_blue_circle:|com/starrocks/sql/ast/CancelLoadStmt.java|12|13|92.31%|[47]|
|:large_blue_circle:|com/starrocks/sql/ast/RangePartitionDesc.java|16|17|94.12%|[185]|
|:large_blue_circle:|com/starrocks/alter/Alter.java|10|10|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/AstVisitor.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/DropMaterializedViewStmt.java|10|10|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/ListPartitionDesc.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/CancelRefreshMaterializedViewStmt.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/RangePartitionInfo.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/InsertStmt.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/execution/AlterMaterializedViewExecutor.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/AlterMaterializedViewStmt.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/MultiRangePartitionDesc.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/load/RoutineLoadDesc.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/load/InsertOverwriteJobRunner.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/SingleRangePartitionDesc.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/execution/DataDefinitionExecutorFactory.java|2|2|100.00%|[]|

**Comment by HangyuanLiu** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 162 / 260 (62.31%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/load/loadv2/LoadManager.java|0|2|00.00%|[160, 163]|
|:large_blue_circle:|com/starrocks/execution/CancelRefreshMaterializedViewExecutor.java|0|1|00.00%|[12]|
|:large_blue_circle:|com/starrocks/sql/analyzer/LoadStmtAnalyzer.java|0|2|00.00%|[108, 109]|
|:large_blue_circle:|com/starrocks/sql/ast/RandomDistributionDesc.java|0|1|00.00%|[61]|
|:large_blue_circle:|com/starrocks/catalog/SchemaTable.java|1|51|01.96%|[506, 508, 509, 510, 511, 514, 515, 517, 518, 519, 520, 521, 523, 525, 526, 527, 528, 529, 530, 531, 533, 534, 535, 537, 538, 540, 541, 542, 543, 544, 546, 547, 549, 550, 551, 552, 553, 554, 555, 556, 562, 563, 564, 565, 566, 569, 570, 571, 574, 578]|
|:large_blue_circle:|com/starrocks/sql/ast/CreateFunctionStmt.java|1|8|12.50%|[186, 281, 282, 289, 292, 293, 299]|
|:large_blue_circle:|com/starrocks/sql/ast/DefaultValueExpr.java|2|6|33.33%|[13, 17, 23, 27]|
|:large_blue_circle:|com/starrocks/sql/ast/SyncStmt.java|2|4|50.00%|[11, 16]|
|:large_blue_circle:|com/starrocks/sql/ast/KillStmt.java|5|9|55.56%|[23, 27, 32, 42]|
|:large_blue_circle:|com/starrocks/sql/ast/SelectListItem.java|16|27|59.26%|[33, 34, 35, 37, 39, 40, 41, 42, 46, 62, 63]|
|:large_blue_circle:|com/starrocks/sql/ast/DropFunctionStmt.java|9|12|75.00%|[32, 41, 51]|
|:large_blue_circle:|com/starrocks/sql/ast/DataDescription.java|4|5|80.00%|[674]|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|21|25|84.00%|[362, 363, 367, 368]|
|:large_blue_circle:|com/starrocks/sql/ast/FunctionArgsDef.java|13|15|86.67%|[41, 42]|
|:large_blue_circle:|com/starrocks/sql/ast/PartitionKeyDesc.java|8|9|88.89%|[104]|
|:large_blue_circle:|com/starrocks/sql/ast/RecoverPartitionStmt.java|9|10|90.00%|[35]|
|:large_blue_circle:|com/starrocks/sql/ast/CancelLoadStmt.java|12|13|92.31%|[47]|
|:large_blue_circle:|com/starrocks/sql/ast/RangePartitionDesc.java|16|17|94.12%|[185]|
|:large_blue_circle:|com/starrocks/alter/Alter.java|10|10|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/AstVisitor.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/DropMaterializedViewStmt.java|10|10|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/ListPartitionDesc.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/CancelRefreshMaterializedViewStmt.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/RangePartitionInfo.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/InsertStmt.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/execution/AlterMaterializedViewExecutor.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/AlterMaterializedViewStmt.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/MultiRangePartitionDesc.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/load/RoutineLoadDesc.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/load/InsertOverwriteJobRunner.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/SingleRangePartitionDesc.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/execution/DataDefinitionExecutorFactory.java|2|2|100.00%|[]|

**Comment by HangyuanLiu** [comment]
run starrocks_admit_test

**Comment by HangyuanLiu** [comment]
run starrocks_fe_unittest

**Comment by HangyuanLiu** [comment]
run starrocks_admit_test

**Comment by HangyuanLiu** [comment]
run starrocks_fe_unittest

**Comment by HangyuanLiu** [comment]
run starrocks_fe_unittest

**Comment by HangyuanLiu** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 162 / 262 (61.83%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/load/loadv2/LoadManager.java|0|2|00.00%|[160, 163]|
|:large_blue_circle:|com/starrocks/execution/CancelRefreshMaterializedViewExecutor.java|0|1|00.00%|[12]|
|:large_blue_circle:|com/starrocks/sql/analyzer/LoadStmtAnalyzer.java|0|2|00.00%|[108, 109]|
|:large_blue_circle:|com/starrocks/analysis/TableRef.java|0|1|00.00%|[376]|
|:large_blue_circle:|com/starrocks/sql/ast/RandomDistributionDesc.java|0|1|00.00%|[61]|
|:large_blue_circle:|com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java|0|1|00.00%|[132]|
|:large_blue_circle:|com/starrocks/catalog/SchemaTable.java|1|51|01.96%|[506, 508, 509, 510, 511, 514, 515, 517, 518, 519, 520, 521, 523, 525, 526, 527, 528, 529, 530, 531, 533, 534, 535, 537, 538, 540, 541, 542, 543, 544, 546, 547, 549, 550, 551, 552, 553, 554, 555, 556, 562, 563, 564, 565, 566, 569, 570, 571, 574, 578]|
|:large_blue_circle:|com/starrocks/sql/ast/CreateFunctionStmt.java|1|8|12.50%|[186, 281, 282, 289, 292, 293, 299]|
|:large_blue_circle:|com/starrocks/sql/ast/DefaultValueExpr.java|2|6|33.33%|[13, 17, 23, 27]|
|:large_blue_circle:|com/starrocks/sql/ast/SyncStmt.java|2|4|50.00%|[11, 16]|
|:large_blue_circle:|com/starrocks/sql/ast/KillStmt.java|5|9|55.56%|[23, 27, 32, 42]|
|:large_blue_circle:|com/starrocks/sql/ast/SelectListItem.java|16|27|59.26%|[33, 34, 35, 37, 39, 40, 41, 42, 46, 62, 63]|
|:large_blue_circle:|com/starrocks/sql/ast/DropFunctionStmt.java|9|12|75.00%|[32, 41, 51]|
|:large_blue_circle:|com/starrocks/sql/ast/DataDescription.java|4|5|80.00%|[674]|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|21|25|84.00%|[365, 366, 370, 371]|
|:large_blue_circle:|com/starrocks/sql/ast/FunctionArgsDef.java|13|15|86.67%|[41, 42]|
|:large_blue_circle:|com/starrocks/sql/ast/PartitionKeyDesc.java|8|9|88.89%|[104]|
|:large_blue_circle:|com/starrocks/sql/ast/RecoverPartitionStmt.java|9|10|90.00%|[35]|
|:large_blue_circle:|com/starrocks/sql/ast/CancelLoadStmt.java|12|13|92.31%|[47]|
|:large_blue_circle:|com/starrocks/sql/ast/RangePartitionDesc.java|16|17|94.12%|[185]|
|:large_blue_circle:|com/starrocks/alter/Alter.java|10|10|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/AstVisitor.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/DropMaterializedViewStmt.java|10|10|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/ListPartitionDesc.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/CancelRefreshMaterializedViewStmt.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/RangePartitionInfo.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/InsertStmt.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/execution/AlterMaterializedViewExecutor.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/AlterMaterializedViewStmt.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/MultiRangePartitionDesc.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/load/RoutineLoadDesc.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/load/InsertOverwriteJobRunner.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/SingleRangePartitionDesc.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/execution/DataDefinitionExecutorFactory.java|2|2|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 162 / 262 (61.83%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/load/loadv2/LoadManager.java|0|2|00.00%|[160, 163]|
|:large_blue_circle:|com/starrocks/execution/CancelRefreshMaterializedViewExecutor.java|0|1|00.00%|[12]|
|:large_blue_circle:|com/starrocks/sql/analyzer/LoadStmtAnalyzer.java|0|2|00.00%|[108, 109]|
|:large_blue_circle:|com/starrocks/analysis/TableRef.java|0|1|00.00%|[376]|
|:large_blue_circle:|com/starrocks/sql/ast/RandomDistributionDesc.java|0|1|00.00%|[61]|
|:large_blue_circle:|com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java|0|1|00.00%|[132]|
|:large_blue_circle:|com/starrocks/catalog/SchemaTable.java|1|51|01.96%|[506, 508, 509, 510, 511, 514, 515, 517, 518, 519, 520, 521, 523, 525, 526, 527, 528, 529, 530, 531, 533, 534, 535, 537, 538, 540, 541, 542, 543, 544, 546, 547, 549, 550, 551, 552, 553, 554, 555, 556, 562, 563, 564, 565, 566, 569, 570, 571, 574, 578]|
|:large_blue_circle:|com/starrocks/sql/ast/CreateFunctionStmt.java|1|8|12.50%|[186, 281, 282, 289, 292, 293, 299]|
|:large_blue_circle:|com/starrocks/sql/ast/DefaultValueExpr.java|2|6|33.33%|[13, 17, 23, 27]|
|:large_blue_circle:|com/starrocks/sql/ast/SyncStmt.java|2|4|50.00%|[11, 16]|
|:large_blue_circle:|com/starrocks/sql/ast/KillStmt.java|5|9|55.56%|[23, 27, 32, 42]|
|:large_blue_circle:|com/starrocks/sql/ast/SelectListItem.java|16|27|59.26%|[33, 34, 35, 37, 39, 40, 41, 42, 46, 62, 63]|
|:large_blue_circle:|com/starrocks/sql/ast/DropFunctionStmt.java|9|12|75.00%|[32, 41, 51]|
|:large_blue_circle:|com/starrocks/sql/ast/DataDescription.java|4|5|80.00%|[674]|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|21|25|84.00%|[371, 372, 376, 377]|
|:large_blue_circle:|com/starrocks/sql/ast/FunctionArgsDef.java|13|15|86.67%|[41, 42]|
|:large_blue_circle:|com/starrocks/sql/ast/PartitionKeyDesc.java|8|9|88.89%|[104]|
|:large_blue_circle:|com/starrocks/sql/ast/RecoverPartitionStmt.java|9|10|90.00%|[35]|
|:large_blue_circle:|com/starrocks/sql/ast/CancelLoadStmt.java|12|13|92.31%|[47]|
|:large_blue_circle:|com/starrocks/sql/ast/RangePartitionDesc.java|16|17|94.12%|[185]|
|:large_blue_circle:|com/starrocks/alter/Alter.java|10|10|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/AstVisitor.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/DropMaterializedViewStmt.java|10|10|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/ListPartitionDesc.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/CancelRefreshMaterializedViewStmt.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/RangePartitionInfo.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/InsertStmt.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/execution/AlterMaterializedViewExecutor.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/AlterMaterializedViewStmt.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/MultiRangePartitionDesc.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/load/RoutineLoadDesc.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/load/InsertOverwriteJobRunner.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/SingleRangePartitionDesc.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/execution/DataDefinitionExecutorFactory.java|2|2|100.00%|[]|

**Comment by HangyuanLiu** [comment]
run starrocks_admit_test

**Comment by HangyuanLiu** [comment]
run starrocks_fe_unittest

**Review by kangkaisen — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 162 / 262 (61.83%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/load/loadv2/LoadManager.java|0|2|00.00%|[160, 163]|
|:large_blue_circle:|com/starrocks/execution/CancelRefreshMaterializedViewExecutor.java|0|1|00.00%|[12]|
|:large_blue_circle:|com/starrocks/sql/analyzer/LoadStmtAnalyzer.java|0|2|00.00%|[108, 109]|
|:large_blue_circle:|com/starrocks/analysis/TableRef.java|0|1|00.00%|[376]|
|:large_blue_circle:|com/starrocks/sql/ast/RandomDistributionDesc.java|0|1|00.00%|[61]|
|:large_blue_circle:|com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java|0|1|00.00%|[132]|
|:large_blue_circle:|com/starrocks/catalog/SchemaTable.java|1|51|01.96%|[506, 508, 509, 510, 511, 514, 515, 517, 518, 519, 520, 521, 523, 525, 526, 527, 528, 529, 530, 531, 533, 534, 535, 537, 538, 540, 541, 542, 543, 544, 546, 547, 549, 550, 551, 552, 553, 554, 555, 556, 562, 563, 564, 565, 566, 569, 570, 571, 574, 578]|
|:large_blue_circle:|com/starrocks/sql/ast/CreateFunctionStmt.java|1|8|12.50%|[186, 281, 282, 289, 292, 293, 299]|
|:large_blue_circle:|com/starrocks/sql/ast/DefaultValueExpr.java|2|6|33.33%|[13, 17, 23, 27]|
|:large_blue_circle:|com/starrocks/sql/ast/SyncStmt.java|2|4|50.00%|[11, 16]|
|:large_blue_circle:|com/starrocks/sql/ast/KillStmt.java|5|9|55.56%|[23, 27, 32, 42]|
|:large_blue_circle:|com/starrocks/sql/ast/SelectListItem.java|16|27|59.26%|[33, 34, 35, 37, 39, 40, 41, 42, 46, 62, 63]|
|:large_blue_circle:|com/starrocks/sql/ast/DropFunctionStmt.java|9|12|75.00%|[32, 41, 51]|
|:large_blue_circle:|com/starrocks/sql/ast/DataDescription.java|4|5|80.00%|[674]|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|21|25|84.00%|[375, 376, 380, 381]|
|:large_blue_circle:|com/starrocks/sql/ast/FunctionArgsDef.java|13|15|86.67%|[41, 42]|
|:large_blue_circle:|com/starrocks/sql/ast/PartitionKeyDesc.java|8|9|88.89%|[104]|
|:large_blue_circle:|com/starrocks/sql/ast/RecoverPartitionStmt.java|9|10|90.00%|[35]|
|:large_blue_circle:|com/starrocks/sql/ast/CancelLoadStmt.java|12|13|92.31%|[47]|
|:large_blue_circle:|com/starrocks/sql/ast/RangePartitionDesc.java|16|17|94.12%|[185]|
|:large_blue_circle:|com/starrocks/alter/Alter.java|10|10|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/AstVisitor.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/DropMaterializedViewStmt.java|10|10|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/ListPartitionDesc.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/CancelRefreshMaterializedViewStmt.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/RangePartitionInfo.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/InsertStmt.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/execution/AlterMaterializedViewExecutor.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/AlterMaterializedViewStmt.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/MultiRangePartitionDesc.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/load/RoutineLoadDesc.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/load/InsertOverwriteJobRunner.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/SingleRangePartitionDesc.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/execution/DataDefinitionExecutorFactory.java|2|2|100.00%|[]|

**Review by murphyatwork — APPROVED** [review]

**Review by Seaven — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Pull request merged**
