### PR TITLE
[BugFix] fix show verbose variables bug

### LINKED ISSUE #14228: invalid show verbose variable result
### Steps to reproduce the behavior (Required)
1. show verbose variables
img_v2_f7b14a89-5dcc-4bab-9919-cc71bce6a58g

### Expected behavior (Required)
result is right when add where predicate
### Real behavior (Required)
default_value and is_changed columns result are wrong when there is where predicate
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by ABingHuang**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #14228 

## Problem Summary(Required) ：

fix show verbose variables bug when there is where predicate
## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 10 / 28 (35.71%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/service/FrontendServiceImpl.java|0|14|00.00%|[797, 798, 800, 801, 802, 803, 805, 806, 807, 808, 809, 810, 811, 812]|
|:large_blue_circle:|com/starrocks/sql/ast/SetType.java|0|2|00.00%|[33, 34]|
|:large_blue_circle:|com/starrocks/sql/ast/ShowVariablesStmt.java|2|3|66.67%|[77]|
|:large_blue_circle:|com/starrocks/catalog/SchemaTable.java|6|7|85.71%|[569]|
|:large_blue_circle:|com/starrocks/qe/VariableMgr.java|2|2|100.00%|[]|

**Comment by ABingHuang** [comment]
run starrocks_be_unittest

**Review by murphyatwork — APPROVED** [review]

**Review by Seaven — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by murphyatwork — DISMISSED** [review]

**Comment by ABingHuang** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 10 / 28 (35.71%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/service/FrontendServiceImpl.java|0|14|00.00%|[797, 798, 800, 801, 802, 803, 805, 806, 807, 808, 809, 810, 811, 812]|
|:large_blue_circle:|com/starrocks/sql/ast/SetType.java|0|2|00.00%|[33, 34]|
|:large_blue_circle:|com/starrocks/sql/ast/ShowVariablesStmt.java|2|3|66.67%|[77]|
|:large_blue_circle:|com/starrocks/catalog/SchemaTable.java|6|7|85.71%|[569]|
|:large_blue_circle:|com/starrocks/qe/VariableMgr.java|2|2|100.00%|[]|

**Comment by ABingHuang** [comment]
run starrocks_admit_test

**Review by kangkaisen — DISMISSED** [review]

**Review by murphyatwork — DISMISSED** [review]

**Comment by mofeiatwork** [comment]
run starrocks_admit_test

**Comment by ABingHuang** [comment]
run starrocks_admit_test

**Comment by ABingHuang** [comment]
run starrocks_admit_test

**Comment by ABingHuang** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 10 / 28 (35.71%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/service/FrontendServiceImpl.java|0|14|00.00%|[797, 798, 800, 801, 802, 803, 805, 806, 807, 808, 809, 810, 811, 812]|
|:large_blue_circle:|com/starrocks/sql/ast/SetType.java|0|2|00.00%|[33, 34]|
|:large_blue_circle:|com/starrocks/sql/ast/ShowVariablesStmt.java|2|3|66.67%|[77]|
|:large_blue_circle:|com/starrocks/catalog/SchemaTable.java|6|7|85.71%|[569]|
|:large_blue_circle:|com/starrocks/qe/VariableMgr.java|2|2|100.00%|[]|

**Comment by ABingHuang** [comment]
run starrocks_admit_test

**Review by kangkaisen — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by Seaven — APPROVED** [review]

**Comment by decster** [comment]
@mergify backport branch-2.5

**Pull request merged**
