### PR TITLE
[Enhancement] Decouple the static privilege check function from PrivilegeManager

### PR DESCRIPTION
**Pull request by HangyuanLiu**
## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 241 / 403 (59.80%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/http/rest/GetLoadInfoAction.java|0|1|00.00%|[82]|
|:large_blue_circle:|com/starrocks/load/routineload/RoutineLoadFunctionalExprProvider.java|0|1|00.00%|[253]|
|:large_blue_circle:|com/starrocks/load/streamload/StreamLoadFunctionalExprProvider.java|0|1|00.00%|[163]|
|:large_blue_circle:|com/starrocks/service/FrontendServiceImpl.java|2|15|13.33%|[276, 326, 378, 402, 403, 495, 595, 802, 830, 844, 845, 1018, 1493]|
|:large_blue_circle:|com/starrocks/http/BaseAction.java|1|5|20.00%|[304, 317, 318, 319]|
|:large_blue_circle:|com/starrocks/privilege/PrivilegeActions.java|117|247|47.37%|[29, 42, 43, 44, 45, 46, 47, 48, 58, 59, 60, 61, 62, 63, 64, 78, 79, 80, 91, 92, 93, 94, 95, 96, 97, 110, 111, 112, 113, 114, 115, 116, 127, 128, 129, 130, 131, 132, 133, 144, 145, 146, 147, 148, 149, 150, 161, 162, 163, 164, 165, 166, 167, 180, 181, 182, 183, 184, 185, 186, 197, 198, 199, 200, 201, 202, 203, 215, 216, 217, 218, 219, 220, 222, 234, 235, 236, 237, 238, 239, 241, 259, 260, 261, 262, 263, 264, 266, 271, 275, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 306, 307, 308, 309, 355, 356, 357, 358, 405, 406, 407, 408, 409, 410, 411, 412, 427, 428, 429, 430, 431, 432, 433, 438, 439, 441, 443, 445, 447]|
|:large_blue_circle:|com/starrocks/load/ExportMgr.java|1|2|50.00%|[233]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AnalyzerUtils.java|1|2|50.00%|[161]|
|:large_blue_circle:|com/starrocks/qe/ShowExecutor.java|9|12|75.00%|[1268, 1487, 1543]|
|:large_blue_circle:|com/starrocks/privilege/PrivilegeBuiltinConstants.java|4|5|80.00%|[20]|
|:large_blue_circle:|com/starrocks/sql/analyzer/PrivilegeCheckerV2.java|67|73|91.78%|[307, 1048, 1165, 1324, 1762, 1767]|
|:large_blue_circle:|com/starrocks/mysql/privilege/AuthUpgrader.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/ShowAnalyzeStatusStmt.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/DataDescription.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/qe/ConnectScheduler.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/ShowBasicStatsMetaStmt.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/privilege/PrivilegeManager.java|22|22|100.00%|[]|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/ResourceGroupMgr.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/ResourceMgr.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/service/InformationSchemaDataSource.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/ShowAnalyzeJobStmt.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/ShowHistogramStatsMetaStmt.java|1|1|100.00%|[]|

**Review by Astralidea — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 252 / 410 (61.46%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/http/rest/GetLoadInfoAction.java|0|1|00.00%|[82]|
|:large_blue_circle:|com/starrocks/load/routineload/RoutineLoadFunctionalExprProvider.java|0|1|00.00%|[253]|
|:large_blue_circle:|com/starrocks/load/streamload/StreamLoadFunctionalExprProvider.java|0|1|00.00%|[163]|
|:large_blue_circle:|com/starrocks/service/FrontendServiceImpl.java|2|15|13.33%|[276, 326, 378, 402, 403, 495, 595, 802, 830, 844, 845, 1018, 1493]|
|:large_blue_circle:|com/starrocks/http/BaseAction.java|1|5|20.00%|[304, 317, 318, 319]|
|:large_blue_circle:|com/starrocks/privilege/PrivilegeActions.java|125|252|49.60%|[29, 46, 47, 48, 58, 59, 60, 61, 62, 63, 64, 78, 79, 80, 91, 92, 93, 94, 95, 96, 97, 110, 111, 112, 113, 114, 115, 116, 127, 128, 129, 130, 131, 132, 133, 144, 145, 146, 147, 148, 149, 150, 161, 162, 163, 164, 165, 166, 167, 180, 181, 182, 183, 184, 185, 186, 197, 198, 199, 200, 201, 202, 203, 215, 216, 217, 218, 219, 220, 222, 234, 235, 236, 237, 238, 239, 241, 259, 260, 261, 262, 263, 264, 266, 271, 275, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 306, 307, 308, 309, 355, 364, 365, 366, 367, 414, 415, 416, 417, 418, 419, 420, 421, 436, 437, 438, 439, 440, 441, 442, 447, 448, 450, 452, 454, 456]|
|:large_blue_circle:|com/starrocks/load/ExportMgr.java|1|2|50.00%|[233]|
|:large_blue_circle:|com/starrocks/qe/ShowExecutor.java|9|12|75.00%|[1271, 1490, 1546]|
|:large_blue_circle:|com/starrocks/privilege/PrivilegeBuiltinConstants.java|4|5|80.00%|[20]|
|:large_blue_circle:|com/starrocks/sql/analyzer/PrivilegeCheckerV2.java|67|73|91.78%|[307, 1048, 1165, 1324, 1762, 1767]|
|:large_blue_circle:|com/starrocks/mysql/privilege/AuthUpgrader.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/ShowAnalyzeStatusStmt.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/DataDescription.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/qe/ConnectScheduler.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/ShowBasicStatsMetaStmt.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/privilege/PrivilegeManager.java|22|22|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AnalyzerUtils.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/ResourceGroupMgr.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/ResourceMgr.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/service/InformationSchemaDataSource.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/ShowAnalyzeJobStmt.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/ShowHistogramStatsMetaStmt.java|1|1|100.00%|[]|

**Review by Astralidea — APPROVED** [review]

**Review by nshangyiming — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by gengjun-git — APPROVED** [review]

**Comment by HangyuanLiu** [comment]
@Mergifyio backport branch-3.0

**Pull request merged**
