### PR TITLE
[Enhancement] Fixes #15063, Support COUNT_IF function

### LINKED ISSUE #15063: support count_if
StarRocks already support count() and if().
However, this function is easier to implement count(if()). 
It is already supported in many database systems like clickhouse, snowflake, bigquery, databricks and so on.

## Description: 
```
COUNT_IF( <condition> )
```
The condition:
1. Can include multiple column, like column a>column b
2. Can use multiple conditions, and use 'and' to link
The count:
1. has the same behavior with the native count when dealing with null, that is, ignore

some examples:
```
MySQL [simo]> select * from table1;
+------+------+
| id   | id1  |
+------+------+
|    1 | NULL |
|    1 |    1 |
|    2 |    1 |
+------+------+
3 rows in set (0.01 sec)

MySQL [simo]> select countif(id>id1) from table1;
+------------+
| count(id1) |
+------------+
|          1 |
+------------+
1 row in set (0.02 sec)

MySQL [simo]> select countif(true) from table1;
+-------------+
| count(TRUE) |
+-------------+
|           3 |
+-------------+
1 row in set (0.02 sec)
```

### PR DESCRIPTION
**Pull request by silly-carbon**
Fixes #15063

## What type of PR is this:

- [ ] BugFix
- [x] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [x] This pr needs user documentation (for new or modified features or behaviors)
  - [x] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.2
  - [x] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:disappointed: **fail** : 6 / 9 (66.67%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/FunctionAnalyzer.java|1|4|25.00%|[125, 126, 127]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/RuleSet.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/FunctionSet.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/DecimalV3FunctionAnalyzer.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/RuleType.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 43 / 46 (93.48%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/FunctionAnalyzer.java|1|2|50.00%|[125]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/RewriteCountIfFunction.java|37|39|94.87%|[85, 103]|
|:large_blue_circle:|com/starrocks/catalog/FunctionSet.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/DecimalV3FunctionAnalyzer.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/RuleType.java|1|1|100.00%|[]|

**Comment by silly-carbon** [comment]
@stdpain  Could you please help review this? I've made a direct rewrite as in https://github.com/StarRocks/starrocks/pull/22902#issuecomment-1537881921

**Comment by silly-carbon** [comment]
@wangsimo0 Could you please help review this?

**Review by stdpain — COMMENTED** [review]
LGTM

**Review by Seaven — APPROVED** [review]

**Review by stdpain — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.2

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Pull request merged**
