### PR TITLE
[BugFix] Fail to parse big json

### LINKED ISSUE #14207: Failure to parse json > 1MB in ndjson format
### Steps to reproduce the behavior (Required)
1. Create table
```
CREATE TABLE `tbl_simple` ( `key2` int(11) NULL COMMENT "") ENGINE=OLAP duplicate KEY(`key1`) COMMENT "OLAP" DISTRIBUTED BY HASH(`key1`) BUCKETS 3 PROPERTIES ( "replication_num" = "1", "in_memory" = "false", "storage_format" = "DEFAULT" );
```
2. Do stream load
 `curl --location-trusted -u root:  'http://127.0.0.1:8082/api/db0/tbl_simple/_stream_load' \-X PUT \-H 'columns: key2' \-H 'format: json' -T big_value.json`

### Expected behavior (Required)
Load successfully.
### Real behavior (Required)
The load return error.
```
{
    "TxnId": 31072,
    "Label": "aa916aa7-9a6a-49d6-9bf7-5475c847fa35",
    "Status": "Fail",
    "Message": "The input payload size is beyond parser limit. Please set strip_outer_array true if you want to load json array",
    "NumberTotalRows": 0,
    "NumberLoadedRows": 0,
    "NumberFilteredRows": 0,
    "NumberUnselectedRows": 0,
    "LoadBytes": 1067082,
    "LoadTimeMs": 371,
    "BeginTxnTimeMs": 0,
    "StreamLoadPutTimeMs": 13,
    "ReadDataTimeMs": 1,
    "WriteDataTimeMs": 285,
    "CommitAndPublishTimeMs": 0,
    "ErrorURL": "http://172.26.92.226:8082/api/_load_error_log?file=error_log_de4523bc3c487d37_a2c2f483607dd58f"
* Connection #1 to host 172.26.92.226 left intact
```
### StarRocks version (Required)
2.4.1, 2.3.4, 2.2.9

### PR DESCRIPTION
**Pull request by rickif**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes https://github.com/StarRocks/starrocks/issues/14207

## Problem Summary(Required) ：

> The iterate_many function can also take an optional parameter size_t batch_size which defines the window processing size. It is set by default to a large value (1000000 corresponding to 1 MB). None of your JSON documents should exceed this window size, or else you will get the error simdjson::CAPACITY. You cannot set this window size larger than 4 GB: you will get the error simdjson::CAPACITY

https://github.com/simdjson/simdjson/blob/master/doc/basics.md#newline-delimited-json-ndjson-and-json-lines

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 2.5 
  - [] 2.4
  - [] 2.3
  - [] 2.2

### CODE REVIEW

**Comment by rickif** [comment]
run starrocks_be_unittest

**Comment by rickif** [comment]
run starrocks_be_unittest

**Comment by rickif** [comment]
run starrocks_be_unittest

**Review by meegoo — APPROVED** [review]

**Review by chaoyli — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Comment by rickif** [comment]
@mergifyio backport branch-2.4

**Comment by rickif** [comment]
@Mergifyio backport branch-2.3 branch-2.2

**Pull request merged**
