### PR TITLE
[BugFix] fix empty conjuncts of left join

### PR DESCRIPTION
**Pull request by murphyatwork**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

For such SQL: `select * from t0 left join t1 on false`
1. The `false` predicate would be pushdown to right table, so right side of join would be empty
2. And the join conjuncts would be empty, the left join should output the left side, but actually it's not

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by mofeiatwork** [comment]
@Mergifyio backport branch-2.

**Comment by mofeiatwork** [comment]
@Mergifyio backport branch-2.4

**Comment by mofeiatwork** [comment]
run starrocks_be_unittest

**Review by stdpain — APPROVED** [review]

**Comment by stdpain** [comment]
need a case to cover this problem

**Review by kangkaisen — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by mofeiatwork** [comment]
run starrocks_be_unittest

**Pull request merged**
