### PR TITLE
[BugFix] Fix primary key table vertical compaction bug

### LINKED ISSUE #12856: Be crash when do vertical compaction of primary key table
### Steps to reproduce the behavior (Required)
1. CREATE Primary Key TABLE '...'
2. Load a small batch data into table(you can just insert one or two rows)
3. Load a large batch data into table(the data of step 2 need to be a part of the data in step 3)
4. Repeat step 3
5. restart be and wait for compaction

### Expected behavior (Required)
compaction success

### Real behavior (Required)
image

### StarRocks version (Required)
 - branch-2.4

### PR DESCRIPTION
**Pull request by sevev**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes https://github.com/StarRocks/starrocks/issues/12856

## Problem Summary(Required) ：

In vertical compaction of PrimaryKey table, The `rowsets_mask_buffer` parameter should correspond to the rowsets because we use `rowsets_mask_buffer` to determine the order in which subsequent segments are read. And if rowset only has one segment, we should push a emtpy RowSourceMask into `rowsets_mask_buffer` but not skip it, otherwise the misalignment may cause some unexpected error.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
BE Build Success

**Comment by sevev** [comment]
run starrocks_admit_test

**Comment by sevev** [comment]
run starrocks_be_unittest

**Comment by sevev** [comment]
run starrocks_be_unittest

**Review by decster — APPROVED** [review]

**Review by chaoyli — APPROVED** [review]

**Comment by sevev** [comment]
run starrocks_admit_test

**Comment by sevev** [comment]
@mergify backport branch-2.4

**Pull request merged**
