### PR TITLE
[Refactor] refactor error msg for high-order functions (backport #30766)

### PR DESCRIPTION
**Pull request by fzhedu**
This is a backport of pull request https://github.com/StarRocks/starrocks/pull/30766

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [x] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 34 / 35 (97.14%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/analysis/VariableExpr.java|1|2|50.00%|[106]|
|:large_blue_circle:|com/starrocks/sql/analyzer/SemanticException.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/ExpressionAnalyzer.java|29|29|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 32 / 35 (91.43%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/ast/SetType.java|4|6|66.67%|[54, 56]|
|:large_blue_circle:|com/starrocks/sql/analyzer/ExpressionAnalyzer.java|18|19|94.74%|[294]|
|:large_blue_circle:|com/starrocks/sql/analyzer/SemanticException.java|5|5|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/Expr.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/VariableExpr.java|4|4|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by fzhedu** [comment]
also cp https://github.com/StarRocks/starrocks/pull/31198

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:disappointed: **fail** : 26 / 33 (78.79%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/analysis/VariableExpr.java|0|4|00.00%|[103, 104, 105, 107]|
|:large_blue_circle:|com/starrocks/sql/ast/SetType.java|3|6|50.00%|[48, 54, 56]|
|:large_blue_circle:|com/starrocks/sql/analyzer/SemanticException.java|7|7|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/Expr.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/ExpressionAnalyzer.java|15|15|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by ABingHuang — APPROVED** [review]

**Pull request merged**
