### PR TITLE
[Enhancement][CherryPick] optimize or predicate mv rewrite for 3.1 (#26403)

### LINKED ISSUE #26038: optimize mv rewrite to support or predicate rewrite
## Enhancement
for mv:

select * from lineorder where lo_orderdate < "20201001" or lo_orderdate > "20210101";

for query:
select * from lineorder where lo_orderdate > "20210201";

the predicate in query  lo_orderdate > "20210201" is subset of mv, query is expected to be rewritten by mv.
now the query can not be rewritten by mv because or predicate is not processed well.

we should support this type of rewrite.

### PR DESCRIPTION
**Pull request by ABingHuang**
Fixes #26038

Optimize or predicate rewrite and add support to rewrite in predicate.

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [ ] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by Astralidea — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by stdpain — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 318 / 370 (85.95%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/RangePredicate.java|4|10|40.00%|[31, 32, 33, 46, 55, 63]|
|:large_blue_circle:|com/starrocks/catalog/PartitionKeyDiscreteDomain.java|3|7|42.86%|[33, 38, 42, 47]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rewrite/scalar/MvNormalizePredicateRule.java|18|28|64.29%|[147, 150, 160, 162, 165, 176, 177, 179, 181, 182]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/OrRangePredicate.java|23|32|71.88%|[37, 38, 39, 40, 41, 44, 47, 49, 96]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/AndRangePredicate.java|58|71|81.69%|[33, 34, 35, 36, 37, 39, 40, 41, 44, 45, 49, 50, 137]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/PredicateExtractor.java|118|125|94.40%|[71, 72, 73, 74, 176, 178, 226]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/ColumnRangePredicate.java|65|68|95.59%|[82, 128, 163]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/PredicateSplit.java|11|11|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/MvUtils.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/RangeSimplifier.java|5|5|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rewrite/PartitionColPredicateEvaluator.java|8|8|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Pull request merged**
