### PR TITLE
[BugFix] Fix the problem of udtf not processing the eos flag

### LINKED ISSUE #12653: [Bug] UDTF unusual time consuming
### Steps to reproduce the behavior (Required)

```sql
CREATE TABLE `bitmap_table` (
  `c1` bigint(20) NOT NULL COMMENT "",
  `c2` bitmap BITMAP_UNION NULL COMMENT ""
) ENGINE=OLAP
AGGREGATE KEY(`c1`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`c1`) BUCKETS 1
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"storage_format" = "DEFAULT",
"enable_persistent_index" = "false",
"compression" = "LZ4"
);

insert into bitmap_table (c1, c2) values 
(1, to_bitmap(1)),
(1, to_bitmap(2)),
(1, to_bitmap(3)),
...
(1, to_bitmap(600000));

select count(*) from ( SELECT convert_rows FROM (     SELECT c2     FROM bitmap_table ) tt1, convert_rows (bitmap_to_string (tt1.c2)) ) tx;
```

### Expected behavior (Required)

time usage < 1s

### Real behavior (Required)

time usage > 1min

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by liuyehcf**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #12653

## Problem Summary(Required) ：

1. `JavaUDTFFunction::process` not process `eos` correctly
2. non-pipeline not process `_table_function_result_eos` correctly

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [x] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by kangkaisen** [comment]
please add daily cases.

**Comment by wanpengfei-git** [comment]
starrocks_be_unittest succeeded.

**Review by kangkaisen — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
starrocks_be_unittest succeeded.

**Review by imay — COMMENTED** [review]
LGTM.
BTW, why not adding some test to cover this fix?

**Comment by liuyehcf** [comment]
> LGTM. BTW, why not adding some test to cover this fix?

I added daily case:  https://github.com/StarRocks/StarRocksTest/pull/1369

**Comment by liuyehcf** [comment]
run starrocks_admit_test

**Review by imay — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by liuyehcf** [comment]
@Mergifyio backport branch-2.2 branch-2.3 branch-2.4

**Pull request merged**
