### PR TITLE
[BugFix] Fix Query hive/hudi with class cast exception

### PR DESCRIPTION
**Pull request by Youngwb**
Fixes #issue
query hive/hudi will occurs this error:
```
mysql> select col_date,sum(col_decimal) from hudi_catalog.hudi_db.hudi_par_parquet_gzip where col_int is not null and col_long != 12 group by 1 order by 2 desc,1 limit 2;
ERROR 1064 (HY000): com.starrocks.sql.optimizer.operator.scalar.CompoundPredicateOperator cannot be cast to com.starrocks.sql.optimizer.operator.scalar.BinaryPredicateOperator
```
This error was introduced by https://github.com/StarRocks/starrocks/pull/24880
It modified the logical of splitPredicate

## What type of PR is this:
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [x] 3.0
  - [ ] 2.5
  - [ ] 2.4

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 13 / 13 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rewrite/OptExternalPartitionPruner.java|13|13|100.00%|[]|

**Review by zombee0 — APPROVED** [review]
LGTM

**Review by stephen-shelby — APPROVED** [review]

**Review by gengjun-git — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Pull request merged**
