### PR TITLE
Support to analyze external table

### PR DESCRIPTION
**Pull request by dirtysalt**
## What type of PR is this：
- [ ] bug
- [ ] feature
- [X] enhancement
- [ ] others

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

This PR is to：
1. support to run `analyze table` on external tables
2. get hive column stats from olap statistics storage.

---

tpch_100g_zlib is a hive table.

image

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
Can't set status; build succeeded.

**Comment by wanpengfei-git** [comment]
Can't set status; build succeeded.

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 6 / 13 (46.15%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/Table.java|0|2|00.00%|
|:large_blue_circle:|com/starrocks/sql/optimizer/statistics/StatisticsCalculator.java|0|1|00.00%|
|:large_blue_circle:|com/starrocks/statistic/StatisticExecutor.java|6|10|60.00%|

**Comment by DorianZheng** [comment]
Great job, It's a exciting work.👍

**Review by murphyatwork — APPROVED** [review]

**Comment by silverbullet233** [comment]
after this changes, can `analyze table` be used on other types of external table, such as MySQL/ES Table?

**Comment by dirtysalt** [comment]
> after this changes, can `analyze table` be used on other types of external table, such as MySQL/ES Table?

I've not tested it yet, but I guess so. It works on hive/iceberg table.

**Comment by dirtysalt** [comment]
For background analyze table, by default, it only works on olap table. You have to run `analyze table` on external table manually.

41d34dNVRj

**Comment by dirtysalt** [comment]
Since we're satisified with current statu, introducing this functionality seems useless. So I close this PR.

**Pull request closed without merging**
