### PR TITLE
[Enhancement] Compatible with the default partition value of the new hudi version

### PR DESCRIPTION
**Pull request by Youngwb**
old hudi version use `default` as null partition value, new hudi version use `__HIVE_DEFAULT_PARTITION__` as partition value

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [x] Yes, this PR will result in a change in behavior.
- [ ] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [x] 3.0
  - [x] 2.5
  - [ ] 2.4

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:disappointed: **fail** : 10 / 13 (76.92%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/DeltaLakePartitionKey.java|0|1|00.00%|[28]|
|:large_blue_circle:|com/starrocks/catalog/NullablePartitionKey.java|0|1|00.00%|[24]|
|:large_blue_circle:|com/starrocks/catalog/IcebergPartitionKey.java|0|1|00.00%|[30]|
|:large_blue_circle:|com/starrocks/catalog/PartitionKey.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/HudiPartitionKey.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/JDBCPartitionKey.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/HivePartitionKey.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/connector/PartitionUtil.java|3|3|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:disappointed: **fail** : 10 / 13 (76.92%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/DeltaLakePartitionKey.java|0|1|00.00%|[28]|
|:large_blue_circle:|com/starrocks/catalog/NullablePartitionKey.java|0|1|00.00%|[24]|
|:large_blue_circle:|com/starrocks/catalog/IcebergPartitionKey.java|0|1|00.00%|[30]|
|:large_blue_circle:|com/starrocks/catalog/PartitionKey.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/HudiPartitionKey.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/JDBCPartitionKey.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/HivePartitionKey.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/connector/PartitionUtil.java|3|3|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 12 / 13 (92.31%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/NullablePartitionKey.java|0|1|00.00%|[24]|
|:large_blue_circle:|com/starrocks/catalog/DeltaLakePartitionKey.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/PartitionKey.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/HudiPartitionKey.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/JDBCPartitionKey.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/HivePartitionKey.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/IcebergPartitionKey.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/connector/PartitionUtil.java|3|3|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by miomiocat — APPROVED** [review]

**Review by stephen-shelby — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Pull request merged**
