### PR TITLE
[BugFix] check random distribution not support colocate_with

### LINKED ISSUE #27075: [materialized view optimization] create mv failed when "colocate_with" in properties
### Steps to reproduce the behavior (Required)
```
CREATE TABLE t1 (
    k1 int,
    k2 int
)
DUPLICATE KEY(k1);
CREATE MATERIALIZED VIEW mv4 REFRESH MANUAL properties ("colocate_with" = "groupmnbvc") AS SELECT k1,sum(k2) FROM t1 group by k1;
```

### Expected behavior (Required)
`Query OK, 0 rows affected (0.02 sec)`
### Real behavior (Required)
`ERROR 1064 (HY000): Unexpected exception: com.starrocks.catalog.RandomDistributionInfo cannot be cast to com.starrocks.catalog.HashDistributionInfo`
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
`branch-3.1-dca7ca2`

### PR DESCRIPTION
**Pull request by murphyatwork**
Fixes #27075

Random distribution does not support colocate.

## What type of PR is this:
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by meegoo — APPROVED** [review]

**Review by packy92 — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 12 / 14 (85.71%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/ast/DistributionDesc.java|0|1|00.00%|[69]|
|:large_blue_circle:|com/starrocks/server/OlapTableFactory.java|6|7|85.71%|[372]|
|:large_blue_circle:|com/starrocks/catalog/HashDistributionInfo.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/RandomDistributionInfo.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/ColocateTableIndex.java|1|1|100.00%|[]|

**Pull request merged**
