### PR TITLE
[BugFix] fix union mv rewrite bug

### LINKED ISSUE #15642: query rewrite failed with unknown error
### Steps to reproduce the behavior (Required)
1. CREATE TABLE 
CREATE TABLE `emps` (
  `empid` int(11) NOT NULL COMMENT "",
  `deptno` int(11) NOT NULL COMMENT "",
  `name` varchar(25) NOT NULL COMMENT "",
  `salary` double NULL COMMENT ""
) ENGINE=OLAP
DUPLICATE KEY(`empid`, `deptno`, `name`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`empid`) BUCKETS 10
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"storage_format" = "DEFAULT",
"enable_persistent_index" = "false",
"compression" = "LZ4"
);

CREATE MATERIALIZED VIEW `mv_agg_1`
COMMENT "MATERIALIZED_VIEW"
DISTRIBUTED BY HASH(`name`) BUCKETS 2
REFRESH MANUAL
PROPERTIES (
"replication_num" = "1",
"storage_medium" = "HDD"
)
AS SELECT `emps`.`deptno`, `emps`.`name`, sum(`emps`.`salary`) AS `salary`
FROM `query_mv`.`emps`
WHERE `emps`.`empid` < 5
GROUP BY `emps`.`deptno`, `emps`.`name`;

2. admin set frontend config ("enable_experimental_mv" = "true");
3. query
SELECT `emps`.`deptno`, `emps`.`name`, sum(salary) as salary FROM `emps` group by deptno, name;

### Expected behavior (Required)
query success

### Real behavior (Required)
Unknown error
image

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by ABingHuang**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #15642 

## Problem Summary(Required) ：

fix union mv rewrite bug. the compensation predicate should be validated against the query outputs. fix it by adding a check the predicate should be calculated from the output columns of query
## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Comment by ABingHuang** [comment]
run starrocks_clang-format

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 25 / 25 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java|16|16|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/MvUtils.java|9|9|100.00%|[]|

**Review by kangkaisen — DISMISSED** [review]

**Review by Youngwb — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 25 / 25 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java|16|16|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/MvUtils.java|9|9|100.00%|[]|

**Review by kangkaisen — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by ABingHuang** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
