### PR TITLE
[BugFix]support cross database udf in view

### LINKED ISSUE #17200: [Bug] cross database udf not recognized in view
### Steps to reproduce the behavior (Required)
```
MySQL [test]> select db_with_udf.UDF_STR_UPPER("hello");
+------------------+
| udf_str_upper('hello') |
+------------------+
| HELLO            |
+------------------+
1 row in set (2.54 sec)

MySQL [test]> create view v_test AS select db_with_udf.UDF_STR_UPPER("hello");
Query OK, 0 rows affected (0.03 sec)

MySQL [test]> select * from v_test;
ERROR 1064 (HY000): No matching function with signature: udf_str_upper(varchar).
MySQL [test]> show create table v_test;
+--------+----------------------------------------------------------------------------------------------------------+----------------------+----------------------+
| View   | Create View                                                                                              | character_set_client | collation_connection |
+--------+----------------------------------------------------------------------------------------------------------+----------------------+----------------------+
| v_test | CREATE VIEW `v_test` (udf_str_upper('hello')) COMMENT "VIEW" AS SELECT udf_str_upper('hello') AS `udf_str_upper('hello')`; | utf8                 | utf8_general_ci      |
+--------+----------------------------------------------------------------------------------------------------------+----------------------+----------------------+
1 row in set (0.00 sec)
```
### Expected behavior (Required)
 sql(select * from v_test;) runs without error

### Real behavior (Required)
error,
lost database domain information, can not recognize udf in current database.

### StarRocks version (Required)
```
MySQL [test]> select current_version();
+-------------------+
| current_version() |
+-------------------+
| UNKNOWN 8e978c04b |
+-------------------+
1 row in set (0.04 sec)
```

### PR DESCRIPTION
**Pull request by ruyliu**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #17200

## Problem Summary(Required) ：

cross database udf not recognized in view, udf lost database domain information.
## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Comment by imay** [comment]
@ruyliu thanks you for your contribution, you need to sign off by `git commit -s` and you need to approve the CLA

**Comment by ruyliu** [comment]
@imay Hi, I have signed off and approved the CLA, please review the code. please review the code. thx!

**Comment by imay** [comment]
@ruyliu some FE unit tests failed, could you take a look and fix them?

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 6 / 6 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/AstToStringBuilder.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AstToSQLBuilder.java|4|4|100.00%|[]|

**Comment by ruyliu** [comment]
@imay I have fixed UT，did I miss anything else?

**Review by imay — APPROVED** [review]

**Comment by imay** [comment]
run starrocks_admit_test

**Pull request merged**
