### PR TITLE
[Enhancement] spark-dpp support spark3

### PR DESCRIPTION
**Pull request by cxzl25**
## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：
Fixes #

## Problem Summary(Required) ：
1. spark-dpp support spark3
2. remove `org.spark_project.guava.collect`
3. remove `jersey.repackaged.com.google.common.collect`

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

- [ ] I have checked the version labels which the pr will be auto backported to target branch

### CODE REVIEW

**Comment by wyb** [comment]
@cxzl25 reflection may cause performance loss. have you done a comparison test?

**Comment by cxzl25** [comment]
> reflection may cause performance loss. have you done a comparison test?

I added the `ExpressionEncoderHelper` performance test and there is no significant performance degradation with multiple calls.

```
Benchmark                                (fieldSize)  (useReflect)   Mode  Cnt   Score    Error   Units
ExpressionEncoderHelperBench.toRowBench           50          true  thrpt    3   0.046 ±  0.031  ops/ms
ExpressionEncoderHelperBench.toRowBench           50         false  thrpt    3   0.043 ±  0.010  ops/ms
ExpressionEncoderHelperBench.toRowBench          150          true  thrpt    3   0.013 ±  0.011  ops/ms
ExpressionEncoderHelperBench.toRowBench          150         false  thrpt    3   0.013 ±  0.007  ops/ms
ExpressionEncoderHelperBench.toRowBench           50          true   avgt    3  23.448 ±  5.014   ms/op
ExpressionEncoderHelperBench.toRowBench           50         false   avgt    3  22.336 ± 10.413   ms/op
ExpressionEncoderHelperBench.toRowBench          150          true   avgt    3  73.045 ± 38.812   ms/op
ExpressionEncoderHelperBench.toRowBench          150         false   avgt    3  77.985 ± 34.139   ms/op
```

**Review by wyb — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by gengjun-git — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by wyb — DISMISSED** [review]

**Review by mark-phoenix-ai — DISMISSED** [review]

**Review by gengjun-git — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by gengjun-git — APPROVED** [review]

**Review by mark-phoenix-ai — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by wyb — APPROVED** [review]

**Comment by kateshaowanjou** [comment]
@cxzl25  Congrats on merging your first pull request! 🎉

**Comment by Astralidea** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
