### PR TITLE
Revert "[Feature] support FE integrate with StarMgr"

### PR DESCRIPTION
**Pull request by starrocks-xupeng**
Reverts StarRocks/starrocks#7129

wait StarMgr 0.1.3 release for metadata compatibility.

### CODE REVIEW

**Review by wyb — APPROVED** [review]

**Review by gengjun-git — APPROVED** [review]

**Comment by starrocks-xupeng** [comment]
run starrocks_fe_unittest

**Comment by wyb** [comment]
run starrocks_fe_unittest

**Comment by starrocks-xupeng** [comment]
run starrocks_fe_unittest

**Comment by starrocks-xupeng** [comment]
run starrocks_fe_unittest

**Comment by starrocks-xupeng** [comment]
run starrocks_fe_unittest

**Pull request merged**
