### PR TITLE
[BugFix] Fix gzip decompressor memory leak

### PR DESCRIPTION
**Pull request by letian-jiang**
Fixes #issue

image

## What type of PR is this:
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by imay — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by DorianZheng** [comment]
there will be no memleak, thread_local variable is static
https://stackoverflow.com/questions/22794382/are-c11-thread-local-variables-automatically-static

**Review by DorianZheng — APPROVED** [review]

**Comment by imay** [comment]
@letian-jiang 
Do you need to cherry-pick this fix to other branches?

**Comment by letian-jiang** [comment]
> @letian-jiang Do you need to cherry-pick this fix to other branches?

No need. This compressor is added only in the main branch.

**Pull request merged**
