### PR TITLE
[BugFix] Make The column TABLE_TYPE of information_schema.tables match the mysql definition

### LINKED ISSUE #11506: The column TABLE_TYPE of information_schema.tables not match the mysql definition
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
2. INSERT INTO '....'
3. SELECT  '....'

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by waittttting**
…ql definition

## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #11506

Make The column TABLE_TYPE of information_schema.tables match the mysql definition
This issue  just introduced in main
Maybe it is not a bug, SR has some custom table types, but in order to adapt to some more BI tools, table type must correspond to the definition of mysql

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 4 / 7 (57.14%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/service/InformationSchemaDataSource.java|4|7|57.14%|[292, 297, 304]|

**Review by Astralidea — APPROVED** [review]

**Comment by waittttting** [comment]
> Please complete the description of this issue. Is it a bug that just introduced in main? I have just fixed another bug in older branches, `information_schema.tables` seems to works fine.

sry, my bad, I have added some description. PTAL

**Review by gengjun-git — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by Astralidea** [comment]
run starrocks_admit_test

**Pull request merged**
