### PR TITLE
[BugFix] fix nested agg/join mv rewrite bug

### LINKED ISSUE #27578: fix nested agg + join mv rewrite
### Steps to reproduce the behavior (Required)
@Test
    public void testAggregateBelowJoin2() throws Exception {
        String mv1 = "create materialized view mv1 \n" +
                "distributed by random \n" +
                "refresh async\n" +
                "as select empid, deptno, locationid, \n" +
                " sum(salary) as total, count(salary)  as cnt\n" +
                " from emps group by empid, deptno, locationid ";
        String mv2 = "create materialized view mv2 \n" +
                "distributed by random \n" +
                "refresh async\n" +
                "as select sum(total) as sum, t.locationid,  t.empid, t.deptno  from \n" +
                "(select empid, deptno, locationid, total, cnt from mv1) t join locations \n" +
                "on t.locationid = locations.locationid\n" +
                "group by t.locationid, t.empid, t.deptno";
        starRocksAssert.withMaterializedView(mv1);
        starRocksAssert.withMaterializedView(mv2);
        sql("select sum(total) as sum, t.locationid  from \n" +
                "(select locationid, \n" +
                " sum(salary) as total, count(salary)  as cnt\n" +
                " from emps where empid = 2 and deptno = 10 group by locationid) t join locations \n" +
                "on t.locationid = locations.locationid\n" +
                "group by t.locationid")
                .match("mv2");
    }

### Expected behavior (Required)
rewritten by mv2
### Real behavior (Required)
not rewritten by mv2
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by ABingHuang**
Fixes #27578 

## What type of PR is this:
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [x] 3.0
  - [x] 2.5
  - [ ] 2.4

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 3 / 3 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/Binder.java|3|3|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 3 / 3 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/Binder.java|3|3|100.00%|[]|

**Review by murphyatwork — DISMISSED** [review]

**Review by Seaven — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/Binder.java|1|1|100.00%|[]|

**Review by murphyatwork — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
