### PR TITLE
support jsonpath of top-level array

### LINKED ISSUE #4162: can't get the elements in the json array directly
### Steps to reproduce the behavior (Required)
```
CREATE TABLE `t1` (
  `k1` int(11) NULL COMMENT "",
  `k2` json NULL COMMENT ""
) ENGINE=OLAP
DUPLICATE KEY(`k1`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`k1`) BUCKETS 3
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"storage_format" = "DEFAULT"
);
insert into t1 values (1,json_array(1,2,3));
select k2->'$[1]' from t1;
```

### Expected behavior (Required)
2
### Real behavior (Required)
NULL
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
select current_version();
+------------------------------------------+
| current_version()                        |
+------------------------------------------+
| PIPELINE_SQLANCER_MASTER_RELEASE 6ce5b2b |
+------------------------------------------+
1 row in set (0.01 sec)
```

### PR DESCRIPTION
**Pull request by murphyatwork**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] others

## Which issues of this PR fixes ：

Fixes #4162 

## Problem Summary(Required) ：

Support query singleton json array:
- JSON Document: `[1,2,3]`
- JSONPath: `$[1]`
- Query result: `2`

### CODE REVIEW

**Comment by mofeiatwork** [comment]
@Mergifyio backport branch-2.2

**Comment by mofeiatwork** [comment]
run starrocks_be_unittest

**Comment by mofeiatwork** [comment]
@Mergify rebase

**Comment by mofeiatwork** [comment]
run starrocks_be_unittest

**Comment by mofeiatwork** [comment]
run starrocks_be_unittest

**Comment by wangruin** [comment]
run starrocks_be_unittest

**Comment by mofeiatwork** [comment]
run starrocks_be_unittest

**Comment by wangruin** [comment]
run starrocks_be_unittest

**Comment by wangruin** [comment]
run starrocks_be_unittest

**Comment by wangruin** [comment]
run starrocks_be_unittest

**Review by Seaven — APPROVED** [review]

**Review by kangkaisen — APPROVED** [review]

**Pull request merged**
