### PR TITLE
[Feature] New RBAC privilege framework: build-in roles and users

### PR DESCRIPTION
**Pull request by padmejin**
## What type of PR is this：
- [ ] BugFix
- [x] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

Introduce a new privilege framework.
To avoid huge PR which is hard to review and easy to conflict, I'm splitting into several small PR, each implementing an individual aspect of the new privilege framework. This is the twelfth one. For previous PRs see 
https://github.com/StarRocks/starrocks/pull/11447
https://github.com/StarRocks/starrocks/pull/11528
https://github.com/StarRocks/starrocks/pull/11593
https://github.com/StarRocks/starrocks/pull/11732
https://github.com/StarRocks/starrocks/pull/11777
https://github.com/StarRocks/starrocks/pull/11847
https://github.com/StarRocks/starrocks/pull/11909
https://github.com/StarRocks/starrocks/pull/12035
https://github.com/StarRocks/starrocks/pull/12128
https://github.com/StarRocks/starrocks/pull/12172
https://github.com/StarRocks/starrocks/pull/12468

This PR support built-in roles and users. 
* Add a function to initialize all built-in roles and users
* Check if the role is mutable when executing `GRANT` or `REVOKE` on a role.
* Check if the role is removable when dropping a role.
* Grant the `public` role to every user newly created.
* Fix a bug. `drop table` will check the `drop` action on the table instead of the `drop` action on the database.
* Remove the `ADMIN` action, which is totally my misunderstanding.
* Support granting privileges on all users.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 99 / 117 (84.62%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/PrivilegeStmtAnalyzerV2.java|1|2|50.00%|[148]|
|:large_blue_circle:|com/starrocks/privilege/UserPEntryObject.java|7|12|58.33%|[30, 41, 70, 74, 77]|
|:large_blue_circle:|com/starrocks/privilege/PrivilegeManager.java|81|93|87.10%|[168, 170, 206, 243, 338, 398, 466, 552, 579, 580, 581, 895]|
|:large_blue_circle:|com/starrocks/sql/analyzer/PrivilegeCheckerV2.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/privilege/PrivilegeTypes.java|5|5|100.00%|[]|
|:large_blue_circle:|com/starrocks/privilege/DefaultAuthorizationProvider.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/privilege/RolePrivilegeCollection.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/authentication/AuthenticationManager.java|2|2|100.00%|[]|

**Comment by wanpengfei-git** [comment]
starrocks_be_unittest succeeded.

**Comment by padmejin** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 112 / 125 (89.60%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/privilege/UserPEntryObject.java|11|16|68.75%|[71, 72, 74, 78, 96]|
|:large_blue_circle:|com/starrocks/privilege/PrivilegeManager.java|80|88|90.91%|[166, 168, 204, 241, 255, 567, 568, 569]|
|:large_blue_circle:|com/starrocks/sql/analyzer/PrivilegeCheckerV2.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/privilege/PrivilegeTypes.java|5|5|100.00%|[]|
|:large_blue_circle:|com/starrocks/privilege/DefaultAuthorizationProvider.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/privilege/RolePrivilegeCollection.java|12|12|100.00%|[]|
|:large_blue_circle:|com/starrocks/authentication/AuthenticationManager.java|2|2|100.00%|[]|

**Comment by wanpengfei-git** [comment]
starrocks_be_unittest succeeded.

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 118 / 131 (90.08%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/privilege/UserPEntryObject.java|11|16|68.75%|[71, 72, 74, 78, 96]|
|:large_blue_circle:|com/starrocks/privilege/PrivilegeManager.java|85|93|91.40%|[169, 171, 207, 244, 259, 571, 572, 573]|
|:large_blue_circle:|com/starrocks/sql/analyzer/PrivilegeCheckerV2.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/privilege/PrivilegeTypes.java|5|5|100.00%|[]|
|:large_blue_circle:|com/starrocks/privilege/DefaultAuthorizationProvider.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/privilege/RolePrivilegeCollection.java|12|12|100.00%|[]|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/authentication/AuthenticationManager.java|2|2|100.00%|[]|

**Comment by wanpengfei-git** [comment]
starrocks_be_unittest succeeded.

**Comment by wanpengfei-git** [comment]
starrocks_be_unittest succeeded.

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 122 / 135 (90.37%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/privilege/UserPEntryObject.java|11|16|68.75%|[71, 72, 74, 78, 96]|
|:large_blue_circle:|com/starrocks/privilege/PrivilegeManager.java|89|97|91.75%|[179, 181, 217, 254, 269, 581, 582, 583]|
|:large_blue_circle:|com/starrocks/sql/analyzer/PrivilegeCheckerV2.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/privilege/PrivilegeTypes.java|5|5|100.00%|[]|
|:large_blue_circle:|com/starrocks/privilege/DefaultAuthorizationProvider.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/privilege/RolePrivilegeCollection.java|12|12|100.00%|[]|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/authentication/AuthenticationManager.java|2|2|100.00%|[]|

**Comment by wanpengfei-git** [comment]
starrocks_be_unittest succeeded.

**Comment by padmejin** [comment]
run starrocks_fe_unittest

**Review by gengjun-git — APPROVED** [review]

**Comment by padmejin** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 135 / 147 (91.84%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/privilege/UserPEntryObject.java|11|16|68.75%|[71, 72, 74, 78, 96]|
|:large_blue_circle:|com/starrocks/privilege/PrivilegeManager.java|103|110|93.64%|[174, 176, 209, 246, 573, 574, 575]|
|:large_blue_circle:|com/starrocks/sql/analyzer/PrivilegeCheckerV2.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/privilege/PrivilegeTypes.java|5|5|100.00%|[]|
|:large_blue_circle:|com/starrocks/privilege/DefaultAuthorizationProvider.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/privilege/RolePrivilegeCollection.java|12|12|100.00%|[]|
|:large_blue_circle:|com/starrocks/authentication/AuthenticationManager.java|2|2|100.00%|[]|

**Review by nshangyiming — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by meegoo — APPROVED** [review]

**Pull request merged**
