### PR TITLE
[BugFix] Fix create view with lateral join bug

### PR DESCRIPTION
**Pull request by Seaven**
Fixes #issue

lateral join to sql print output column `ie(key,value) `: 

`KEY`,`VALUE` is keywords, we should print sql use quota, like ```ie(`key`,`value`)```

the origin SQL:
```
SELECT `test`.`ge`.`v_id`, get_json_string(`ie`.`value`, '$.b') AS `b`, get_json_string(`ie`.`value`, '$.c') AS `c`
FROM `test`.`json_test` AS `ge` , LATERAL json_each(CAST(`test`.`ge`.`v_json` AS JSON)->'$.') ie
```

but the view SQL:
```
SELECT `test`.`ge`.`v_id`, get_json_string(`ie`.`value`, '$.b') AS `b`, get_json_string(`ie`.`value`, '$.c') AS `c`
FROM `test`.`json_test` AS `ge` , LATERAL json_each(CAST(`test`.`ge`.`v_json` AS JSON)->'$.') ie(key,value) 
```

## What type of PR is this:
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [x] 3.0
  - [x] 2.5
  - [x] 2.4

### CODE REVIEW

**Review by kangkaisen — APPROVED** [review]

**Review by packy92 — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.4

**Pull request merged**
