### PR TITLE
[BugFix] Fix correlated scalar non-agg subquery loss non-correlated predicates

### LINKED ISSUE #9870: [Bug] Correlated scalar non-agg subquery result error
### Steps to reproduce the behavior (Required)

```sql
DROP TABLE IF EXISTS `t0`;
CREATE TABLE IF NOT EXISTS `t0` (
  `v1` int(11) NULL,
  `v2` int(11) NULL,
  `v3` int(11) NULL
) ENGINE=OLAP
DUPLICATE KEY(`v1`)
DISTRIBUTED BY HASH(`v1`) BUCKETS 10
PROPERTIES (
 "replication_num" = "1"
);

DROP TABLE IF EXISTS `t1`;
CREATE TABLE IF NOT EXISTS `t1` (
  `v1` int(11) NULL,
  `v2` int(11) NULL,
  `v3` int(11) NULL
) ENGINE=OLAP
DUPLICATE KEY(`v1`)
DISTRIBUTED BY HASH(`v1`) BUCKETS 10
PROPERTIES (
 "replication_num" = "1"
);

INSERT INTO `t0`(v1, v2, v3) VALUES
(1, 1, 1), (2, 2, 2), (3, 3, 3);

INSERT INTO `t1`(v1, v2, v3) VALUES
(1, 1, 1), (2, 2, 2), (3, 3, 3);
```

```sql
SELECT * FROM 
t0 WHERE t0.v1 = (
    SELECT v1 FROM t1
    WHERE t0.v2 = t1.v2 and t1.v3 = 3
);
```

### Expected behavior (Required)

```
+----+----+----+
| v1 | v2 | v3 |
+----+----+----+
| 3  | 3  | 3  |
+----+----+----+
```

### Real behavior (Required)

```
+----+----+----+
| v1 | v2 | v3 |
+----+----+----+
| 3  | 3  | 3  |
| 2  | 2  | 2  |
| 1  | 1  | 1  |
+----+----+----+
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by liuyehcf**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #9870

## Problem Summary(Required) ：

The non-correlated predicates is lossed when transforming ApplyOperator to Left Outer Join.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/ScalarApply2JoinRule.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/ScalarApply2JoinRule.java|2|2|100.00%|[]|

**Review by Seaven — APPROVED** [review]

**Comment by liuyehcf** [comment]
run starrocks_fe_unittest

**Comment by liuyehcf** [comment]
run starrocks_clang-format

**Comment by liuyehcf** [comment]
run starrocks_fe_unittest

**Comment by liuyehcf** [comment]
run starrocks_admit_test

**Comment by liuyehcf** [comment]
run starrocks_fe_unittest

**Review by kangkaisen — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by liuyehcf** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/ScalarApply2JoinRule.java|2|2|100.00%|[]|

**Pull request merged**
