### PR TITLE
[Refactor] Delete obsolete isAnalyze flag in UserIdentity and drop obsolete UserIdentifier

### PR DESCRIPTION
**Pull request by HangyuanLiu**
## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [x] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

[Refactor] Delete obsolete isAnalyze flag in UserIdentity and drop obsolete UserIdentifier #17664
## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 68 / 74 (91.89%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/LoadPlanner.java|0|1|00.00%|[177]|
|:large_blue_circle:|com/starrocks/sql/analyzer/LoadStmtAnalyzer.java|0|4|00.00%|[114, 117, 118, 119]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/RangeSimplifier.java|0|1|00.00%|[93]|
|:large_blue_circle:|com/starrocks/catalog/MaterializedView.java|7|7|100.00%|[]|
|:large_blue_circle:|com/starrocks/persist/ImpersonatePrivInfo.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/PartitionPruneRule.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|23|23|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/RewriteSumByAssociativeRule.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/mysql/privilege/PrivEntry.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/PruneGroupByKeysRule.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/UserIdentity.java|21|21|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/OptExpressionDuplicator.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/ExpressionPartitionDesc.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/service/InformationSchemaDataSource.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/CTASAnalyzer.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/PartitionExprAnalyzer.java|1|1|100.00%|[]|

**Comment by HangyuanLiu** [comment]
run starrocks_admit_test

**Comment by HangyuanLiu** [comment]
run starrocks_fe_unittest

**Comment by HangyuanLiu** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 68 / 74 (91.89%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/LoadPlanner.java|0|1|00.00%|[177]|
|:large_blue_circle:|com/starrocks/sql/analyzer/LoadStmtAnalyzer.java|0|4|00.00%|[114, 117, 118, 119]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/RangeSimplifier.java|0|1|00.00%|[93]|
|:large_blue_circle:|com/starrocks/catalog/MaterializedView.java|7|7|100.00%|[]|
|:large_blue_circle:|com/starrocks/persist/ImpersonatePrivInfo.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/PartitionPruneRule.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|23|23|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/RewriteSumByAssociativeRule.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/mysql/privilege/PrivEntry.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/PruneGroupByKeysRule.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/UserIdentity.java|21|21|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/OptExpressionDuplicator.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/ExpressionPartitionDesc.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/service/InformationSchemaDataSource.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/CTASAnalyzer.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/PartitionExprAnalyzer.java|1|1|100.00%|[]|

**Review by Astralidea — APPROVED** [review]

**Review by gengjun-git — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by HangyuanLiu** [comment]
run starrocks_admit_test

**Pull request merged**
