### PR TITLE
[Enhancement] Optimize logic of materialized view when base table is dropped

### LINKED ISSUE #8612: [Enhancement] optimize logic of materialized view when base table is dropped
## Enhancement
1. now when base table is dropped, the related materialized views are not set to invalid
2. the refresh of materialized view will succeed if the materialized view is invalid.

### PR DESCRIPTION
**Pull request by ABingHuang**
## What type of PR is this：
- [ ] bug
- [ ] feature
- [x] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #8612 

## Problem Summary(Required) ：

Optimize logic of materialized view when base table is dropped

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 3 / 12 (25.00%)




#### file detail

|   |path|covered line|new line|coverage|not covered line detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/scheduler/MvTaskRunProcessor.java|0|4|00.00%|[75, 76, 77, 78]|
|:large_blue_circle:|com/starrocks/catalog/Database.java|3|8|37.50%|[415, 416, 417, 418, 420]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 12 / 12 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|not covered line detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/Database.java|8|8|100.00%|[]|
|:large_blue_circle:|com/starrocks/scheduler/MvTaskRunProcessor.java|4|4|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 17 / 18 (94.44%)




#### file detail

|   |path|covered line|new line|coverage|not covered line detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/common/DmlException.java|5|6|83.33%|[13]|
|:large_blue_circle:|com/starrocks/catalog/Database.java|8|8|100.00%|[]|
|:large_blue_circle:|com/starrocks/scheduler/MvTaskRunProcessor.java|4|4|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 17 / 18 (94.44%)




#### file detail

|   |path|covered line|new line|coverage|not covered line detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/common/DmlException.java|5|6|83.33%|[13]|
|:large_blue_circle:|com/starrocks/catalog/Database.java|8|8|100.00%|[]|
|:large_blue_circle:|com/starrocks/scheduler/MvTaskRunProcessor.java|4|4|100.00%|[]|

**Review by Astralidea — DISMISSED** [review]

**Review by Astralidea — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 17 / 18 (94.44%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/common/DmlException.java|5|6|83.33%|[13]|
|:large_blue_circle:|com/starrocks/catalog/Database.java|8|8|100.00%|[]|
|:large_blue_circle:|com/starrocks/scheduler/MvTaskRunProcessor.java|4|4|100.00%|[]|

**Review by kangkaisen — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by Astralidea** [comment]
run starrocks_admit_test

**Comment by ABingHuang** [comment]
run starrocks_admit_test

**Pull request merged**
