### PR TITLE
[Feature] Support create mv select data from different internal database

### LINKED ISSUE #9792: [sync materialized view]create mv failed when select data from different database
### Steps to reproduce the behavior (Required)
```
create database db1;
create database db2;
CREATE TABLE db1.t1 (
                                            `k1` int,
                                            `k2` int,
                                            `k3` int
                                        ) ENGINE=OLAP
                                        DUPLICATE KEY(`k1`)
                                        COMMENT "OLAP"
                                        DISTRIBUTED BY HASH(`k1`) BUCKETS 3;
CREATE TABLE db2.t1 (
                                            `k1` int,
                                            `k2` int,
                                            `k3` int
                                        ) ENGINE=OLAP
                                        DUPLICATE KEY(`k1`)
                                        COMMENT "OLAP"
                                        DISTRIBUTED BY HASH(`k1`) BUCKETS 3;
CREATE MATERIALIZED VIEW mv1
                             DISTRIBUTED BY HASH(k1) BUCKETS 10
                             REFRESH ASYNC
                             AS SELECT t1.k1 as k1, t1.k2 as k2, t2.k1 as k3, t2.k2 as k4
                             FROM db1.t1 t1 join db2.t1 t2 on t1.k1=t2.k1;
```
### Expected behavior (Required)
`Query OK, 0 rows affected (0.01 sec)`
### Real behavior (Required)
`ERROR 1064 (HY000): Materialized view do not support table: t1 do not exist in database: yn_db`
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
mysql> select current_version();
+----------------------------+
| current_version()          |
+----------------------------+
| BRANCH-2.4-RELEASE d401dc8 |
+----------------------------+
```

### PR DESCRIPTION
**Pull request by Astralidea**
## What type of PR is this：
- [ ] bug
- [x] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #9792

## Problem Summary(Required) ：

add new meta @SerializedName(value = "baseTableInfos") used to record dbId information.Then use baseDb to do it at different times of checking and using.
## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 93 / 118 (78.81%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/MaterializedView.java|10|22|45.45%|[248, 249, 342, 347, 348, 349, 354, 355, 356, 357, 362, 363]|
|:large_blue_circle:|com/starrocks/scheduler/PartitionBasedMaterializedViewRefreshProcessor.java|41|50|82.00%|[428, 436, 492, 493, 497, 498, 499, 506, 511]|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|6|7|85.71%|[3326]|
|:large_blue_circle:|com/starrocks/catalog/BaseTableInfo.java|12|14|85.71%|[26, 27]|
|:large_blue_circle:|com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java|22|23|95.65%|[156]|
|:large_blue_circle:|com/starrocks/sql/ast/CreateMaterializedViewStatement.java|2|2|100.00%|[]|

**Comment by Astralidea** [comment]
run starrocks_admit_test

**Comment by Astralidea** [comment]
run all

**Comment by Astralidea** [comment]
run starrocks_fe_unittest

**Comment by Astralidea** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 93 / 118 (78.81%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/MaterializedView.java|10|22|45.45%|[248, 249, 342, 347, 348, 349, 354, 355, 356, 357, 362, 363]|
|:large_blue_circle:|com/starrocks/scheduler/PartitionBasedMaterializedViewRefreshProcessor.java|41|50|82.00%|[428, 436, 492, 493, 497, 498, 499, 506, 511]|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|6|7|85.71%|[3326]|
|:large_blue_circle:|com/starrocks/catalog/BaseTableInfo.java|12|14|85.71%|[26, 27]|
|:large_blue_circle:|com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java|22|23|95.65%|[156]|
|:large_blue_circle:|com/starrocks/sql/ast/CreateMaterializedViewStatement.java|2|2|100.00%|[]|

**Comment by Astralidea** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 103 / 127 (81.10%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/MaterializedView.java|10|21|47.62%|[248, 342, 347, 348, 349, 354, 355, 356, 357, 362, 363]|
|:large_blue_circle:|com/starrocks/scheduler/PartitionBasedMaterializedViewRefreshProcessor.java|49|58|84.48%|[447, 455, 511, 512, 516, 517, 518, 525, 530]|
|:large_blue_circle:|com/starrocks/catalog/BaseTableInfo.java|12|14|85.71%|[26, 27]|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|8|9|88.89%|[3340]|
|:large_blue_circle:|com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java|22|23|95.65%|[154]|
|:large_blue_circle:|com/starrocks/sql/ast/CreateMaterializedViewStatement.java|2|2|100.00%|[]|

**Comment by Astralidea** [comment]
This close because we have a better solution in #11131

**Pull request closed without merging**
