### PR TITLE
[BugFix] Fix the type output of show create table statement

### PR DESCRIPTION
**Pull request by miomiocat**
## Problem Summary:

Fix the wrong type output of show create table statement

expect: double, actual: doubledecimal
expect: struct<...>, actual: binary
expect: array<...>, actual: binary
expect: map<...>, actual: binary

## What type of PR is this:
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Review by Astralidea — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/ScalarType.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/qe/ShowExecutor.java|1|1|100.00%|[]|

**Review by stephen-shelby — DISMISSED** [review]

**Comment by miomiocat** [comment]
@mergify rebase

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 5 / 8 (62.50%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/MapType.java|1|2|50.00%|[138]|
|:large_blue_circle:|com/starrocks/catalog/StructType.java|1|2|50.00%|[125]|
|:large_blue_circle:|com/starrocks/catalog/ArrayType.java|1|2|50.00%|[59]|
|:large_blue_circle:|com/starrocks/catalog/ScalarType.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/qe/ShowExecutor.java|1|1|100.00%|[]|

**Review by Astralidea — APPROVED** [review]

**Review by stephen-shelby — APPROVED** [review]

**Comment by dirtysalt** [comment]
@mergify backport branch-3.0

**Pull request merged**
