### PR TITLE
[Feature] Support aws sdk default behavior + assume role authentication

### PR DESCRIPTION
**Pull request by Smith-Cruise**
Support below grammar:
```sql
"aws.s3.use_aws_sdk_default_behavior"="true",
"aws.s3.iam_role_arn"="xxx"
```

## What type of PR is this:
- [ ] BugFix
- [x] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 0 / 12 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/connector/iceberg/glue/IcebergAwsClientFactory.java|0|5|00.00%|[144, 145, 192, 193, 196]|
|:large_blue_circle:|com/starrocks/credential/aws/AWSCloudCredential.java|0|7|00.00%|[138, 160, 161, 163, 164, 165, 169]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 0 / 12 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/connector/iceberg/glue/IcebergAwsClientFactory.java|0|5|00.00%|[144, 145, 192, 193, 196]|
|:large_blue_circle:|com/starrocks/credential/aws/AWSCloudCredential.java|0|7|00.00%|[147, 148, 169, 171, 172, 174, 177]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 0 / 13 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/connector/iceberg/glue/IcebergAwsClientFactory.java|0|4|00.00%|[144, 170, 194, 195]|
|:large_blue_circle:|com/starrocks/credential/aws/AWSCloudCredential.java|0|9|00.00%|[146, 147, 148, 167, 168, 170, 172, 173, 175]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 6 / 14 (42.86%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/connector/iceberg/glue/IcebergAwsClientFactory.java|0|5|00.00%|[144, 170, 194, 195, 196]|
|:large_blue_circle:|com/starrocks/credential/aws/AWSCloudCredential.java|6|9|66.67%|[146, 147, 148]|

**Review by Knight0xffff — APPROVED** [review]

**Review by letian-jiang — APPROVED** [review]

**Comment by Smith-Cruise** [comment]
@Mergify backport branch-3.1

**Pull request merged**
