### PR TITLE
[BugFix] Fix create user and create role log compatibility bug

### PR DESCRIPTION
**Pull request by HangyuanLiu**
Fixes #issue
In #25364, we used CollectionV2 to replace the original data structure, but missed the compatibility issue in Create user log
## What type of PR is this:
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 6 / 41 (14.63%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/persist/RolePrivilegeCollectionInfo.java|3|30|10.00%|[61, 62, 63, 66, 67, 68, 71, 72, 73, 75, 76, 77, 80, 81, 84, 85, 86, 88, 89, 90, 92, 93, 94, 95, 97, 98, 99]|
|:large_blue_circle:|com/starrocks/persist/CreateUserInfo.java|3|11|27.27%|[88, 89, 90, 92, 93, 94, 95, 96]|

**Review by Astralidea — APPROVED** [review]

**Review by gengjun-git — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Comment by HangyuanLiu** [comment]
https://github.com/Mergifyio backport branch-3.1

**Comment by HangyuanLiu** [comment]
https://github.com/Mergifyio backport branch-3.0

**Comment by HangyuanLiu** [comment]
https://github.com/Mergifyio backport branch-3.1

**Pull request merged**
