### PR TITLE
[Enhancement] make mv preprocess more robust

### LINKED ISSUE #19549: make mv rewrite preprocess more robust
## Enhancement
now when mv rewrite preprocess failed for one mv, the query will fail too. it is better to skip this mv candidate, not to disturb the query process.

### PR DESCRIPTION
**Pull request by ABingHuang**
## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #19549

## Problem Summary(Required) ：

make mv preprocess more robust to exception. skip the failed mv during preprocess.
## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 44 / 57 (77.19%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/MaterializedView.java|1|8|12.50%|[919, 920, 921, 1018, 1019, 1020, 1021]|
|:large_blue_circle:|com/starrocks/sql/optimizer/MvRewritePreprocessor.java|43|49|87.76%|[85, 86, 87, 94, 105, 128]|

**Review by murphyatwork — APPROVED** [review]

**Review by Youngwb — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by ABingHuang** [comment]
run starrocks_admit_test

**Comment by ABingHuang** [comment]
run starrocks_admit_test

**Pull request merged**
