### PR TITLE
[Refactor] remove hash predicates line from Join explain

### PR DESCRIPTION
**Pull request by murphyatwork**
## What type of PR is this：
- [ ] bug
- [ ] feature
- [ ] enhancement
- [x] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

Remove the useless `hash predicates` from Join's explain, which becomes:

```sql
HASH JOIN
  |  join op: LEFT OUTER JOIN (BUCKET_SHUFFLE)
  |  equal join conjunct: [1: PS_PARTKEY, INT, false] = [7: P_PARTKEY, INT, true]
  |  other predicates: 7: P_PARTKEY IS NULL
  |  output columns: 1, 2
  |  cardinality: 8000000
```

### CODE REVIEW

**Comment by imay** [comment]
Could you explain the background about this PR? I can't get any background about it.

**Comment by mofeiatwork** [comment]
run all

**Review by Seaven — APPROVED** [review]

**Review by Youngwb — APPROVED** [review]

**Comment by mofeiatwork** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/planner/JoinNode.java|1|1|100.00%|

**Pull request merged**
