### PR TITLE
[Enhancement] Support show tables from external catalog database

### LINKED ISSUE #15705: Support show (full) tables from catalog.db for external catalog
## Enhancement
**support show (full) tables from catalog.db for external catalog**
Now
image

support  after:
image

### PR DESCRIPTION
**Pull request by leoyy0316**
## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #15705

## Problem Summary(Required) ：

Now
image

Support after:
image

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 34 / 40 (85.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/ShowStmtAnalyzer.java|3|5|60.00%|[110, 116]|
|:large_blue_circle:|com/starrocks/qe/ShowExecutor.java|8|12|66.67%|[630, 631, 632, 634]|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|8|8|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/ShowTableStmt.java|15|15|100.00%|[]|

**Comment by leoyy0316** [comment]
run starrocks_fe_unittest

**Comment by leoyy0316** [comment]
run starrocks_fe_unittest

**Comment by leoyy0316** [comment]
run starrocks_admit_test

**Comment by leoyy0316** [comment]
run starrocks_fe_unittest

**Comment by leoyy0316** [comment]
run starrocks_admit_test

**Comment by leoyy0316** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 37 / 40 (92.50%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/ShowStmtAnalyzer.java|3|5|60.00%|[110, 116]|
|:large_blue_circle:|com/starrocks/qe/ShowExecutor.java|11|12|91.67%|[632]|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|8|8|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/ShowTableStmt.java|15|15|100.00%|[]|

**Comment by leoyy0316** [comment]
run starrocks_admit_test

**Review by stephen-shelby — APPROVED** [review]

**Review by Youngwb — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by leoyy0316** [comment]
https://github.com/Mergifyio backport branch-2.5

**Comment by leoyy0316** [comment]
@Mergifyio backport branch-2.5

**Pull request merged**
