### PR TITLE
[Refactor] revert Refactor hive tpch plan test

### PR DESCRIPTION
**Pull request by stephen-shelby**
Reverts StarRocks/starrocks#12425
commit message is wrong

### CODE REVIEW

**Review by gengjun-git — APPROVED** [review]

**Comment by stephen-shelby** [comment]
run starrocks_fe_unittest

**Comment by stephen-shelby** [comment]
run starrocks_clang-format

**Comment by stephen-shelby** [comment]
run starrocks_be_unittest

**Comment by stephen-shelby** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
starrocks_be_unittest succeeded.

**Review by ZiheLiu — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Pull request merged**
