### PR TITLE
[BugFix]Fix mv matched when query columns in the agg function all are key columns

### LINKED ISSUE #6984: MV matched when query columns in the agg function all are key columns will return wrong results
### Steps to reproduce the behavior (Required)
1. create table and mv, insert some values
```SQL
CREATE TABLE test_bl_test1(
    timed DATE,
    event varchar(30),
    userId varchar(256)
)
DUPLICATE KEY(timed, event) 
PARTITION BY RANGE(timed)(
START ("2022-05-12") END ("2022-05-31") EVERY (INTERVAL 1 day)
)
DISTRIBUTED BY HASH(userId) BUCKETS 32
PROPERTIES(
"dynamic_partition.enable" = "true",
"dynamic_partition.time_unit" = "DAY",
"dynamic_partition.start" = "-45",
"dynamic_partition.end" = "45",
"dynamic_partition.prefix" = "p",
"dynamic_partition.buckets" = "32"
);


CREATE MATERIALIZED VIEW test_bl_mv3 AS
select timed, event, count(userId) as PV
from test_bl_test2
group by timed, event; 
```
2. select with count(1)
```SQL
select count(1), timed,  sum(case when event='test0' then 0 else 1 end) as test , 
    sum(case when event='test0' then 1 else 0 end) as nontest
from test_bl_test1
group by timed
```
4. select without count(1)
```SQL
select timed,  sum(case when event='test0' then 0 else 1 end) as test ,
    sum(case when event='test0' then 1 else 0 end) as nontest
from test_bl_test1
group by timed
```

### Expected behavior (Required)
step 3 and step 4 will return same results

### Real behavior (Required)
43125900-DCF9-45AC-9078-2C0F319673AA

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by caneGuy**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #6984

### CODE REVIEW

**Comment by caneGuy** [comment]
run starrocks_fe_unittest

**Comment by caneGuy** [comment]
run starrocks_fe_unittest

**Comment by caneGuy** [comment]
@ABingHuang done

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 6 / 7 (85.71%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/mv/MaterializedViewRule.java|6|7|85.71%|

**Review by imay — APPROVED** [review]

**Review by Astralidea — APPROVED** [review]

**Comment by caneGuy** [comment]
@Mergifyio backport branch-2.2

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 6 / 7 (85.71%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/mv/MaterializedViewRule.java|6|7|85.71%|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 6 / 7 (85.71%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/mv/MaterializedViewRule.java|6|7|85.71%|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 6 / 7 (85.71%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/mv/MaterializedViewRule.java|6|7|85.71%|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 6 / 7 (85.71%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/mv/MaterializedViewRule.java|6|7|85.71%|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 6 / 7 (85.71%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/mv/MaterializedViewRule.java|6|7|85.71%|

**Pull request merged**
