### PR TITLE
[Enhancement] reference need for enhancement in geo_types

### PR DESCRIPTION
**Pull request by xuzifu666**
Fixes #issue

## What type of PR is this:
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4

### CODE REVIEW

**Review by kevincai — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by murphyatwork — APPROVED** [review]

**Comment by silverbullet233** [comment]
title has typo, should be reference

**Comment by xuzifu666** [comment]
> title has typo, should be reference

done，thanks~

**Review by silverbullet233 — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 145 / 200 (72.50%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/connector/RemoteScanRangeLocations.java|0|1|00.00%|[88]|
|:large_blue_circle:|com/starrocks/connector/delta/DeltaLakeInternalMgr.java|0|3|00.00%|[43, 52, 53]|
|:large_blue_circle:|com/starrocks/connector/delta/DeltaLakeConnector.java|0|1|00.00%|[72]|
|:large_blue_circle:|com/starrocks/connector/hive/IHiveMetastore.java|0|1|00.00%|[40]|
|:large_blue_circle:|com/starrocks/connector/delta/DeltaLakeMetadataFactory.java|0|1|00.00%|[36]|
|:large_blue_circle:|com/starrocks/connector/hive/HiveMetastoreApiConverter.java|7|35|20.00%|[143, 145, 146, 147, 148, 149, 150, 154, 155, 156, 159, 160, 161, 162, 164, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 179]|
|:large_blue_circle:|com/starrocks/connector/hive/CachingHiveMetastore.java|2|4|50.00%|[215, 216]|
|:large_blue_circle:|com/starrocks/connector/hudi/HudiConnectorInternalMgr.java|4|7|57.14%|[80, 82, 90]|
|:large_blue_circle:|com/starrocks/connector/hive/HiveMetadata.java|6|8|75.00%|[134, 135]|
|:large_blue_circle:|com/starrocks/connector/ColumnTypeConverter.java|44|56|78.57%|[190, 191, 196, 197, 198, 212, 213, 225, 226, 241, 242, 246]|
|:large_blue_circle:|com/starrocks/connector/hive/HiveConnectorInternalMgr.java|6|7|85.71%|[90]|
|:large_blue_circle:|com/starrocks/connector/hive/RemoteFileInputFormat.java|9|9|100.00%|[]|
|:large_blue_circle:|com/starrocks/connector/hive/HiveMetastore.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/CreateTableAnalyzer.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/ListPartitionDesc.java|30|30|100.00%|[]|
|:large_blue_circle:|com/starrocks/connector/hive/HiveMetadataFactory.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/connector/hive/HiveMetaClient.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AstToStringBuilder.java|7|7|100.00%|[]|
|:large_blue_circle:|com/starrocks/connector/hive/HiveConnector.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/connector/hudi/HudiMetadataFactory.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/connector/hive/HiveMetastoreOperations.java|9|9|100.00%|[]|
|:large_blue_circle:|com/starrocks/qe/HDFSBackendSelector.java|9|9|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by xuzifu666** [comment]
close it  and move to https://github.com/StarRocks/starrocks/pull/28732，this pr misstake some problem @mofeiatwork @silverbullet233 @kevincai

**Pull request closed without merging**
