### PR TITLE
[BugFix] Fix bitnot largeint cast

### PR DESCRIPTION
**Pull request by kangkaisen**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

https://github.com/StarRocks/StarRocksTest/issues/1733

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3

before https://github.com/StarRocks/starrocks/pull/15757
 
the plan for `select bitnot(cast(power(-2,127) as largeint)+1);` was:

```
~ CAST(power(-2.0, 127.0) AS LARGEINT) + 1
```

but after that commit, the plan was:

```
~ CAST(CAST(power(-2.0, 127.0) AS LARGEINT) + 1 AS BIGINT)
```
**The reason is  we shouldn't handle bitnot by ArithmeticExpr when Analyze.**

### CODE REVIEW

**Review by silverbullet233 — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by packy92** [comment]
I see the `bitnot` function was regarded as `ArithmeticExpr` in ScalarOperatorToExpr#439. Is this bug caused by casting 
 the partamer to a wrong type in `bitnot` function?

**Comment by packy92** [comment]
> ArithmeticExpr



> > I see the `bitnot` function was regarded as `ArithmeticExpr` in ScalarOperatorToExpr#439. Is this bug caused by casting the partamer to a wrong type in `bitnot` function?
> 
> ```
>             } else if (node.getOp().getPos() == ArithmeticExpr.OperatorPosition.UNARY_PREFIX) {
> 
>                 Function fn = Expr.getBuiltinFunction(
>                         node.getOp().getName(), new Type[] {Type.BIGINT}, Function.CompareMode.IS_SUPERTYPE_OF);
> 
>                 node.setType(Type.BIGINT);
>                 node.setFn(fn);
> ```
> 
> bug is here, if we handle the bitnot as ArithmeticExpr, the arg type will be BIGINT.

So we just regard the `bitnot` as a normal function call in FE and regard it as `ArithmeticExpr` in BE?

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by packy92 — APPROVED** [review]

**Review by Youngwb — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by satanson — APPROVED** [review]

**Pull request merged**
