### PR TITLE
[BugFix] fix create table crash, define hash func for TTaskType

### LINKED ISSUE #18883: [Bug] ASAN BE crash when create table
### Steps to reproduce the behavior (Required)
1. Build BE with ASAN:
```
BUILD_TYPE=ASAN ./build.sh --be
```
2. Create table.
```
CREATE TABLE IF NOT EXISTS detail_demo (
    id            BIGINT         COMMENT "range [-2^63 + 1 ~ 2^63 - 1]",
    pass      LARGEINT       COMMENT "range [-2^127 + 1 ~ 2^127 - 1]",
    info      LARGEINT       COMMENT "range [-2^127 + 1 ~ 2^127 - 1]"
) ENGINE=OLAP
PRIMARY KEY(id)
DISTRIBUTED BY HASH(id) BUCKETS 1
properties (
"replication_num" = “1”,
);
```

### Expected behavior (Required)
Create table success.

### Real behavior (Required)
BE crash at:
```
*** Aborted at 1677773278 (unix time) try "date -d @1677773278" if you are using GNU date ***
PC: @     0x7efc9359d387 __GI_raise
*** SIGABRT (@0x43b0000f3fd) received by PID 62461 (TID 0x7ef6eae5c700) from PID 62461; stack trace: ***
    @         0x16612de2 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7efc93944630 (unknown)
    @     0x7efc9359d387 __GI_raise
    @     0x7efc9359ea78 __GI_abort
    @     0x7efc935961a6 __assert_fail_base
    @     0x7efc93596252 __GI___assert_fail
    @          0xd093032 phmap::priv::raw_hash_set<>::emplace_at<>()
    @          0xd08cebe phmap::priv::raw_hash_map<>::try_emplace_impl<>()
    @          0xd087660 phmap::priv::raw_hash_map<>::try_emplace<>()
    @          0xd080174 _ZN5phmap4priv12raw_hash_mapINS0_17FlatHashMapPolicyIN9starrocks9TTaskType4typeESt6vectorIPKNS3_17TAgentTaskRequestESaIS9_EEEENS_4HashIS5_EENS_7EqualToIS5_EESaISt4pairIKS5_SB_EEEixIS5_SC_LPS5_0EEEDTclsrT0_5valuecl9addressofcl7declvalIRSJ_EEEEEOS5_
    @          0xd05cd39 starrocks::AgentServer::Impl::submit_tasks()
    @          0xd06ea62 starrocks::AgentServer::submit_tasks()
    @         0x14d672fa starrocks::BackendService::submit_tasks()
    @         0x151dcbfc starrocks::BackendServiceProcessor::process_submit_tasks()
    @         0x151d7d85 starrocks::BackendServiceProcessor::dispatchCall()
    @          0xd0cd9c0 apache::thrift::TDispatchProcessor::process()
    @         0x165eb678 apache::thrift::server::TConnectedClient::run()
    @         0x165f0144 apache::thrift::server::TThreadedServer::TConnectedClientRunner::run()
    @         0x165f29fd apache::thrift::concurrency::Thread::threadMain()
    @         0x165ceda6 std::thread::_State_impl<>::_M_run()
    @         0x1879a7a0 execute_native_thread_routine
    @     0x7efc9393cea5 start_thread
    @     0x7efc93665b0d __clone
    @                0x0 (unknown)
```

### StarRocks version (Required)
 - UNKNOWN ASAN (build 8fd961c38)

### PR DESCRIPTION
**Pull request by luohaha**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #18883

## Problem Summary(Required) ：
Be crash because `phmap` check out that the key it just insert can't be found later, so assert failed.
```
    void emplace_at(size_t i, Args&&... args) {
        PolicyTraits::construct(&alloc_ref(), slots_ + i, std::forward<Args>(args)...);

        assert(PolicyTraits::apply(FindElement{*this}, *iterator_at(i)) == iterator_at(i) &&
               "constructed value does not match the lookup key");
    }
```
It is because we don't define the hash func for TTaskType, and it's hash func choose by `phmap` isn't stable.

Using `std::hash<std::underlying_type<TTaskType::type>::type>` as it's hash func, follow the standard: https://en.cppreference.com/w/cpp/utility/hash

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 3.0
  - [x] 2.5
  - [x] 2.4
  - [x] 2.3

### CODE REVIEW

**Review by imay — APPROVED** [review]

**Comment by luohaha** [comment]
run starrocks_fe_unittest
run starrocks_clang-format
run starrocks_be_unittest

**Comment by wangruin** [comment]
run all

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.4

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.3

**Pull request merged**
