### PR TITLE
[Refactor] rename work group to resource group

### PR DESCRIPTION
**Pull request by murphyatwork**
## What type of PR is this：
- [ ] bug
- [ ] feature
- [ ] enhancement
- [x] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #

### CODE REVIEW

**Review by imay — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by mofeiatwork** [comment]
@Mergifyio rebase

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 166 / 251 (66.14%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/StmtExecutor.java|0|7|00.00%|[216, 217, 964, 965, 966, 967, 1031]|
|:large_blue_circle:|com/starrocks/journal/JournalEntity.java|0|1|00.00%|[509]|
|:large_blue_circle:|com/starrocks/qe/ShowExecutor.java|1|5|20.00%|[281, 1612, 1613, 1614]|
|:large_blue_circle:|com/starrocks/qe/Coordinator.java|5|17|29.41%|[505, 509, 510, 511, 512, 516, 518, 522, 523, 524, 527, 2724]|
|:large_blue_circle:|com/starrocks/qe/QueryDetail.java|1|3|33.33%|[224, 228]|
|:large_blue_circle:|com/starrocks/persist/EditLog.java|1|3|33.33%|[695, 696]|
|:large_blue_circle:|com/starrocks/master/ReportHandler.java|2|5|40.00%|[204, 207, 453]|
|:large_blue_circle:|com/starrocks/qe/SessionVariable.java|1|2|50.00%|[918]|
|:large_blue_circle:|com/starrocks/persist/ResourceGroupOpEntry.java|3|6|50.00%|[31, 35, 39]|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|2|4|50.00%|[1133, 1383]|
|:large_blue_circle:|com/starrocks/qe/ConnectProcessor.java|1|2|50.00%|[229]|
|:large_blue_circle:|com/starrocks/sql/ast/ShowResourceGroupStmt.java|2|3|66.67%|[32]|
|:large_blue_circle:|com/starrocks/catalog/ResourceGroupMgr.java|67|101|66.34%|[180, 182, 191, 192, 193, 194, 202, 204, 215, 216, 217, 223, 224, 282, 340, 344, 347, 350, 351, 354, 369, 370, 371, 379, 380, 381, 382, 385, 386, 391, 392, 393, 396, 413]|
|:large_blue_circle:|com/starrocks/catalog/ResourceGroup.java|7|10|70.00%|[77, 250, 251]|
|:large_blue_circle:|com/starrocks/catalog/ResourceGroupClassifier.java|3|4|75.00%|[49]|
|:large_blue_circle:|com/starrocks/sql/analyzer/ResourceGroupAnalyzer.java|26|32|81.25%|[29, 53, 60, 71, 87, 103]|
|:large_blue_circle:|com/starrocks/sql/ast/AlterResourceGroupStmt.java|8|9|88.89%|[60]|
|:large_blue_circle:|com/starrocks/sql/ast/CreateResourceGroupStmt.java|12|13|92.31%|[69]|
|:large_blue_circle:|com/starrocks/analysis/SetVar.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|8|8|100.00%|[]|
|:large_blue_circle:|com/starrocks/metric/ResourceGroupMetricMgr.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/DropResourceGroupStmt.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/execution/DropResourceGroupExecutor.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/qe/ConnectContext.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/execution/CreateResourceGroupExecutor.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/execution/AlterResourceGroupExecutor.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/execution/DataDefinitionExecutorFactory.java|3|3|100.00%|[]|

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 169 / 253 (66.80%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/StmtExecutor.java|0|7|00.00%|[216, 217, 964, 965, 966, 967, 1031]|
|:large_blue_circle:|com/starrocks/journal/JournalEntity.java|0|1|00.00%|[510]|
|:large_blue_circle:|com/starrocks/qe/ShowExecutor.java|1|5|20.00%|[283, 1619, 1620, 1621]|
|:large_blue_circle:|com/starrocks/qe/Coordinator.java|5|17|29.41%|[502, 506, 507, 508, 509, 513, 515, 519, 520, 521, 524, 2720]|
|:large_blue_circle:|com/starrocks/qe/QueryDetail.java|1|3|33.33%|[224, 228]|
|:large_blue_circle:|com/starrocks/persist/EditLog.java|1|3|33.33%|[696, 697]|
|:large_blue_circle:|com/starrocks/master/ReportHandler.java|2|5|40.00%|[204, 207, 453]|
|:large_blue_circle:|com/starrocks/qe/SessionVariable.java|1|2|50.00%|[918]|
|:large_blue_circle:|com/starrocks/persist/ResourceGroupOpEntry.java|3|6|50.00%|[31, 35, 39]|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|2|4|50.00%|[1143, 1401]|
|:large_blue_circle:|com/starrocks/qe/ConnectProcessor.java|1|2|50.00%|[229]|
|:large_blue_circle:|com/starrocks/catalog/ResourceGroupMgr.java|67|102|65.69%|[180, 182, 191, 192, 193, 194, 202, 204, 215, 216, 217, 223, 224, 282, 340, 344, 347, 350, 351, 354, 369, 370, 371, 379, 380, 381, 382, 385, 386, 391, 392, 393, 394, 397, 414]|
|:large_blue_circle:|com/starrocks/sql/ast/ShowResourceGroupStmt.java|2|3|66.67%|[32]|
|:large_blue_circle:|com/starrocks/catalog/ResourceGroup.java|7|10|70.00%|[77, 250, 251]|
|:large_blue_circle:|com/starrocks/catalog/ResourceGroupClassifier.java|3|4|75.00%|[49]|
|:large_blue_circle:|com/starrocks/sql/analyzer/ResourceGroupAnalyzer.java|26|30|86.67%|[28, 52, 59, 70]|
|:large_blue_circle:|com/starrocks/sql/ast/AlterResourceGroupStmt.java|8|9|88.89%|[60]|
|:large_blue_circle:|com/starrocks/sql/ast/CreateResourceGroupStmt.java|12|13|92.31%|[69]|
|:large_blue_circle:|com/starrocks/analysis/SetVar.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|8|8|100.00%|[]|
|:large_blue_circle:|com/starrocks/metric/ResourceGroupMetricMgr.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/DropResourceGroupStmt.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/execution/DropResourceGroupExecutor.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/qe/ConnectContext.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/Column.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/execution/CreateResourceGroupExecutor.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/execution/AlterResourceGroupExecutor.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/execution/DataDefinitionExecutorFactory.java|3|3|100.00%|[]|

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 166 / 250 (66.40%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/StmtExecutor.java|0|7|00.00%|[216, 217, 964, 965, 966, 967, 1031]|
|:large_blue_circle:|com/starrocks/journal/JournalEntity.java|0|1|00.00%|[510]|
|:large_blue_circle:|com/starrocks/qe/ShowExecutor.java|1|5|20.00%|[283, 1619, 1620, 1621]|
|:large_blue_circle:|com/starrocks/qe/Coordinator.java|5|17|29.41%|[503, 507, 508, 509, 510, 514, 516, 520, 521, 522, 525, 2721]|
|:large_blue_circle:|com/starrocks/qe/QueryDetail.java|1|3|33.33%|[224, 228]|
|:large_blue_circle:|com/starrocks/persist/EditLog.java|1|3|33.33%|[696, 697]|
|:large_blue_circle:|com/starrocks/master/ReportHandler.java|2|5|40.00%|[204, 207, 453]|
|:large_blue_circle:|com/starrocks/qe/SessionVariable.java|1|2|50.00%|[918]|
|:large_blue_circle:|com/starrocks/persist/ResourceGroupOpEntry.java|3|6|50.00%|[31, 35, 39]|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|2|4|50.00%|[1141, 1399]|
|:large_blue_circle:|com/starrocks/qe/ConnectProcessor.java|1|2|50.00%|[229]|
|:large_blue_circle:|com/starrocks/catalog/ResourceGroupMgr.java|67|102|65.69%|[180, 182, 191, 192, 193, 194, 202, 204, 215, 216, 217, 223, 224, 282, 340, 344, 347, 350, 351, 354, 369, 370, 371, 379, 380, 381, 382, 385, 386, 391, 392, 393, 394, 397, 414]|
|:large_blue_circle:|com/starrocks/sql/ast/ShowResourceGroupStmt.java|2|3|66.67%|[32]|
|:large_blue_circle:|com/starrocks/catalog/ResourceGroup.java|7|10|70.00%|[77, 250, 251]|
|:large_blue_circle:|com/starrocks/catalog/ResourceGroupClassifier.java|3|4|75.00%|[49]|
|:large_blue_circle:|com/starrocks/sql/analyzer/ResourceGroupAnalyzer.java|26|30|86.67%|[28, 52, 59, 70]|
|:large_blue_circle:|com/starrocks/sql/ast/AlterResourceGroupStmt.java|8|9|88.89%|[60]|
|:large_blue_circle:|com/starrocks/sql/ast/CreateResourceGroupStmt.java|12|13|92.31%|[69]|
|:large_blue_circle:|com/starrocks/analysis/SetVar.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|8|8|100.00%|[]|
|:large_blue_circle:|com/starrocks/metric/ResourceGroupMetricMgr.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/DropResourceGroupStmt.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/execution/DropResourceGroupExecutor.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/qe/ConnectContext.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/execution/CreateResourceGroupExecutor.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/execution/AlterResourceGroupExecutor.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/execution/DataDefinitionExecutorFactory.java|3|3|100.00%|[]|

**Review by kangkaisen — APPROVED** [review]

**Pull request merged**
