### PR TITLE
[Refactor][meta-format-change] Change all bdb log serialize/deserialize format to json

### PR DESCRIPTION
**Pull request by gengjun-git**
Fixes #issue

## What type of PR is this:
- [ ] BugFix
- [x] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 62 / 132 (46.97%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/journal/JournalEntity.java|0|57|00.00%|[241, 242, 243, 266, 267, 268, 308, 309, 310, 328, 329, 330, 348, 349, 350, 400, 401, 402, 448, 449, 450, 463, 464, 465, 490, 491, 492, 529, 530, 531, 540, 541, 542, 569, 570, 571, 597, 598, 599, 651, 652, 653, 661, 662, 663, 671, 672, 673, 784, 785, 786, 794, 795, 796, 804, 805, 806]|
|:large_blue_circle:|com/starrocks/persist/EditLog.java|23|36|63.89%|[1172, 1180, 1272, 1292, 1304, 1348, 1456, 1476, 1508, 1655, 1667, 1746, 1765]|
|:large_blue_circle:|com/starrocks/persist/BackendTabletsInfo.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/load/PartitionUtils.java|15|15|100.00%|[]|
|:large_blue_circle:|com/starrocks/persist/DropInfo.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|19|19|100.00%|[]|
|:large_blue_circle:|com/starrocks/persist/ReplicaPersistInfo.java|3|3|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 62 / 132 (46.97%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/journal/JournalEntity.java|0|57|00.00%|[241, 242, 243, 266, 267, 268, 308, 309, 310, 328, 329, 330, 348, 349, 350, 400, 401, 402, 448, 449, 450, 463, 464, 465, 490, 491, 492, 529, 530, 531, 540, 541, 542, 569, 570, 571, 597, 598, 599, 651, 652, 653, 661, 662, 663, 671, 672, 673, 784, 785, 786, 794, 795, 796, 804, 805, 806]|
|:large_blue_circle:|com/starrocks/persist/EditLog.java|23|36|63.89%|[1172, 1180, 1272, 1292, 1304, 1348, 1456, 1476, 1508, 1651, 1663, 1742, 1761]|
|:large_blue_circle:|com/starrocks/persist/BackendTabletsInfo.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/load/PartitionUtils.java|15|15|100.00%|[]|
|:large_blue_circle:|com/starrocks/persist/DropInfo.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|19|19|100.00%|[]|
|:large_blue_circle:|com/starrocks/persist/ReplicaPersistInfo.java|3|3|100.00%|[]|

**Review by HangyuanLiu — DISMISSED** [review]

**Review by nshangyiming — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 78 / 159 (49.06%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/load/streamload/StreamLoadTask.java|0|5|00.00%|[1401, 1402, 1406, 1407, 1408]|
|:large_blue_circle:|com/starrocks/journal/JournalEntity.java|0|63|00.00%|[241, 242, 243, 267, 268, 269, 309, 310, 311, 329, 330, 331, 349, 350, 351, 401, 402, 403, 449, 450, 451, 464, 465, 466, 491, 492, 493, 530, 531, 532, 541, 542, 543, 570, 571, 572, 598, 599, 600, 652, 653, 654, 662, 663, 664, 672, 673, 674, 703, 704, 705, 795, 796, 797, 805, 806, 807, 975, 976, 977, 985, 986, 987]|
|:large_blue_circle:|com/starrocks/persist/EditLog.java|24|37|64.86%|[1175, 1183, 1279, 1299, 1311, 1355, 1463, 1483, 1515, 1658, 1670, 1694, 1762]|
|:large_blue_circle:|com/starrocks/persist/BackendTabletsInfo.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/load/PartitionUtils.java|15|15|100.00%|[]|
|:large_blue_circle:|com/starrocks/persist/DropInfo.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/system/SystemInfoService.java|6|6|100.00%|[]|
|:large_blue_circle:|com/starrocks/scheduler/mv/MVMaintenanceJob.java|6|6|100.00%|[]|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|19|19|100.00%|[]|
|:large_blue_circle:|com/starrocks/persist/gson/GsonUtils.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/persist/ReplicaPersistInfo.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/authentication/UserPropertyInfo.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 137 / 224 (61.16%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/load/streamload/StreamLoadTask.java|0|5|00.00%|[1401, 1402, 1406, 1407, 1408]|
|:large_blue_circle:|com/starrocks/journal/JournalEntity.java|0|63|00.00%|[241, 242, 243, 267, 268, 269, 309, 310, 311, 329, 330, 331, 349, 350, 351, 401, 402, 403, 449, 450, 451, 464, 465, 466, 491, 492, 493, 530, 531, 532, 541, 542, 543, 570, 571, 572, 598, 599, 600, 652, 653, 654, 662, 663, 664, 672, 673, 674, 703, 704, 705, 795, 796, 797, 805, 806, 807, 975, 976, 977, 985, 986, 987]|
|:large_blue_circle:|com/starrocks/persist/EditLog.java|24|37|64.86%|[1175, 1183, 1279, 1299, 1311, 1355, 1463, 1483, 1515, 1658, 1670, 1694, 1762]|
|:large_blue_circle:|com/starrocks/clone/TabletScheduler.java|32|38|84.21%|[741, 748, 749, 753, 1023, 1050]|
|:large_blue_circle:|com/starrocks/clone/TabletChecker.java|12|12|100.00%|[]|
|:large_blue_circle:|com/starrocks/persist/BackendTabletsInfo.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/clone/DiskAndTabletLoadReBalancer.java|27|27|100.00%|[]|
|:large_blue_circle:|com/starrocks/load/PartitionUtils.java|15|15|100.00%|[]|
|:large_blue_circle:|com/starrocks/persist/DropInfo.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/scheduler/mv/MVMaintenanceJob.java|6|6|100.00%|[]|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|11|11|100.00%|[]|
|:large_blue_circle:|com/starrocks/persist/gson/GsonUtils.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/persist/ReplicaPersistInfo.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/authentication/UserPropertyInfo.java|1|1|100.00%|[]|

**Review by nshangyiming — APPROVED** [review]

**Review by HangyuanLiu — APPROVED** [review]

**Comment by gengjun-git** [comment]
@mergifyio backport barnch-3.1

**Comment by gengjun-git** [comment]
@mergifyio backport branch-3.1

**Pull request merged**
