### PR TITLE
[Feature] Support query fe metrics from information_schea.fe_metris table

### PR DESCRIPTION
**Pull request by meegoo**
Fixes #issue

## What type of PR is this:

- [ ] BugFix
- [x] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.2
  - [x] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 8 / 9 (88.89%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/system/information/FeMetricsSystemTable.java|7|8|87.50%|[26]|
|:large_blue_circle:|com/starrocks/catalog/system/information/InfoSchemaDb.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 0 / 2 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/exec/schema_scanner.cpp|0|2|00.00%|[143, 144]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 8 / 9 (88.89%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/system/information/FeMetricsSystemTable.java|7|8|87.50%|[26]|
|:large_blue_circle:|com/starrocks/catalog/system/information/InfoSchemaDb.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 0 / 71 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|be/src/exec/schema_scanner.cpp|0|2|00.00%|[143, 144]|
|:large_blue_circle:|be/src/exec/schema_scanner/schema_fe_metrics_scanner.cpp|0|69|00.00%|[38, 39, 41, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 69, 72, 73, 74, 75, 76, 79, 80, 81, 82, 83, 84, 85, 86, 88, 89, 90, 92, 93, 95, 97, 98, 99, 101, 103, 104, 105, 107, 109, 110, 112, 113, 117, 120, 121, 122, 124, 125, 126, 128, 129, 131, 132]|

**Review by Astralidea — DISMISSED** [review]

**Review by gengjun-git — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:disappointed: **fail** : 12 / 28 (42.86%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/planner/SchemaScanNode.java|3|17|17.65%|[254, 311, 312, 313, 315, 316, 318, 319, 320, 321, 323, 325, 326, 327]|
|:large_blue_circle:|com/starrocks/sql/plan/PlanFragmentBuilder.java|1|2|50.00%|[1333]|
|:large_blue_circle:|com/starrocks/catalog/system/information/FeMetricsSystemTable.java|7|8|87.50%|[26]|
|:large_blue_circle:|com/starrocks/catalog/system/information/InfoSchemaDb.java|1|1|100.00%|[]|

**Review by Astralidea — APPROVED** [review]

**Review by gengjun-git — APPROVED** [review]

**Comment by meegoo** [comment]
mergify backport branch-3.2 branch-3.1 branch-3.0 branch-2.5

**Pull request merged**
