### PR TITLE
Update SHOW BACKUP doc

### PR DESCRIPTION
**Pull request by fieldsfarmer**
Add missing field `Progress`.

## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [x] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [x] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Comment by imay** [comment]
@fieldsfarmer thank you for contribution. Could you sign off by “git commit -s ”

**Comment by fieldsfarmer** [comment]
> @fieldsfarmer thank you for contribution. Could you sign off by “git commit -s ”

thanks for reply. but how to do that given I have committed the change through the web page.

**Comment by imay** [comment]
You can do it by leave a message for each of your PR like "Signed-off-by: [Your Name] <[Your Email]>"

**Comment by fieldsfarmer** [comment]
Thanks!

Signed-off-by: Kaiwei Wang <fieldsfarmer@gmail.com>

**Comment by EsoragotoSpirit** [comment]
Thank you for your contribution @fieldsfarmer . Your effort is much appreciated. However, your previous PR has been relocated from the Chinese doc repo and merged. Closing this one for duplication

**Pull request closed without merging**
