### PR TITLE
[Enhancement] support now with parameter in FE

### LINKED ISSUE #19273: Metabase needs to support the now function with parameters
https://dev.mysql.com/doc/refman/8.0/en/date-and-time-functions.html#function_now
### Steps to reproduce the behavior (Required)
1. select now(0);

### Expected behavior (Required)
+---------------------+
| now(0)              |
+---------------------+
| 2023-03-09 16:48:10 |
+---------------------+
### Real behavior (Required)
No matching function with signature: now(tinyint(4)).
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
3.0

### PR DESCRIPTION
**Pull request by Astralidea**
## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #19273

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 3.0
  - [x] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Comment by Astralidea** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 29 / 34 (85.29%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rewrite/ScalarOperatorFunctions.java|8|11|72.73%|[358, 362, 365]|
|:large_blue_circle:|com/starrocks/analysis/DateLiteral.java|14|16|87.50%|[342, 343]|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/scalar/ConstantOperator.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/ScalarType.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/plan/ScalarOperatorToExpr.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/Type.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Pull request closed without merging**
