### PR TITLE
[BugFix] Insert plan required gather when select limit

### PR DESCRIPTION
**Pull request by Seaven**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：
<!--
Usage: `Fixes #<issue number>`, or `Fixes (paste link of issue)`.
_If PR is about `failing-tests or flakes`, please post the related issues/tests in a comment and do not use `Fixes`_*
-->
Fixes #

## Problem Summary(Required) ：
<!-- (Please describe the changes you have made. In which scenarios will this bug be triggered and what measures have you taken to fix the bug?) -->

Insert data sink is shuffle, not gather, will insert too much data

```
MySQL n2> explain insert into dm_health1  select * from dm_health1 limit 1;
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Explain String                                                                                                                                                                                                                                                                                                                                                                               |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| PLAN FRAGMENT 0                                                                                                                                                                                                                                                                                                                                                                              |
|  OUTPUT EXPRS:1: month | 2: platform_id | 3: id | 4: title | 5: content | 6: content_type | 7: post_id | 8: user_id | 9: user_name | 10: created_at | 11: access_time | 12: source_type | 13: busi_field | 14: rule_flag | 15: is_host | 16: access_date | 17: inc_flag | 18: etl_load_dt | 19: xuqiu | 20: changjing | 21: fangan | 22: driver | 23: barrier | 24: question | 25: cognition |
|   PARTITION: HASH_PARTITIONED: 1: month, 2: platform_id, 3: id                                                                                                                                                                                                                                                                                                                               |
|                                                                                                                                                                                                                                                                                                                                                                                              |
|   OLAP TABLE SINK                                                                                                                                                                                                                                                                                                                                                                            |
|     TUPLE ID: 1                                                                                                                                                                                                                                                                                                                                                                              |
|     RANDOM                                                                                                                                                                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                                                                                                                                                                                                              |
|   1:EXCHANGE                                                                                                                                                                                                                                                                                                                                                                                 |
|      limit: 1                                                                                                                                                                                                                                                                                                                                                                                |
|                                                                                                                                                                                                                                                                                                                                                                                              |
| PLAN FRAGMENT 1                                                                                                                                                                                                                                                                                                                                                                              |
|  OUTPUT EXPRS:                                                                                                                                                                                                                                                                                                                                                                               |
|   PARTITION: RANDOM                                                                                                                                                                                                                                                                                                                                                                          |
|                                                                                                                                                                                                                                                                                                                                                                                              |
|   STREAM DATA SINK                                                                                                                                                                                                                                                                                                                                                                           |
|     EXCHANGE ID: 01                                                                                                                                                                                                                                                                                                                                                                          |
|     HASH_PARTITIONED: 1: month, 2: platform_id, 3: id                                                                                                                                                                                                                                                                                                                                        |
|                                                                                                                                                                                                                                                                                                                                                                                              |
|   0:OlapScanNode                                                                                                                                                                                                                                                                                                                                                                             |
|      TABLE: dm_health1                                                                                                                                                                                                                                                                                                                                                                       |
|      PREAGGREGATION: OFF. Reason: None aggregate function                                                                                                                                                                                                                                                                                                                                    |
|      partitions=0/47                                                                                                                                                                                                                                                                                                                                                                         |
|      rollup: dm_health1                                                                                                                                                                                                                                                                                                                                                                      |
|      tabletRatio=0/0                                                                                                                                                                                                                                                                                                                                                                         |
|      tabletList=                                                                                                                                                                                                                                                                                                                                                                             |
|      cardinality=1                                                                                                                                                                                                                                                                                                                                                                           |
|      avgRowSize=25.0                                                                                                                                                                                                                                                                                                                                                                         |
|      numNodes=0                                                                                                                                                                                                                                                                                                                                                                              |
|      limit: 1                                                                                                                                                                                                                                                                                                                                                                                |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```

except:
```
MySQL n2> explain insert into dm_health1  select * from dm_health1 limit 1;
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Explain String                                                                                                                                                                                                                                                                                                                                                                               |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| PLAN FRAGMENT 0                                                                                                                                                                                                                                                                                                                                                                              |
|  OUTPUT EXPRS:1: month | 2: platform_id | 3: id | 4: title | 5: content | 6: content_type | 7: post_id | 8: user_id | 9: user_name | 10: created_at | 11: access_time | 12: source_type | 13: busi_field | 14: rule_flag | 15: is_host | 16: access_date | 17: inc_flag | 18: etl_load_dt | 19: xuqiu | 20: changjing | 21: fangan | 22: driver | 23: barrier | 24: question | 25: cognition |
|   PARTITION: UNPARTITIONED                                                                                                                                                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                                                                                                                                                                                                              |
|   OLAP TABLE SINK                                                                                                                                                                                                                                                                                                                                                                            |
|     TUPLE ID: 1                                                                                                                                                                                                                                                                                                                                                                              |
|     RANDOM                                                                                                                                                                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                                                                                                                                                                                                              |
|   1:EXCHANGE                                                                                                                                                                                                                                                                                                                                                                                 |
|      limit: 1                                                                                                                                                                                                                                                                                                                                                                                |
|                                                                                                                                                                                                                                                                                                                                                                                              |
| PLAN FRAGMENT 1                                                                                                                                                                                                                                                                                                                                                                              |
|  OUTPUT EXPRS:                                                                                                                                                                                                                                                                                                                                                                               |
|   PARTITION: RANDOM                                                                                                                                                                                                                                                                                                                                                                          |
|                                                                                                                                                                                                                                                                                                                                                                                              |
|   STREAM DATA SINK                                                                                                                                                                                                                                                                                                                                                                           |
|     EXCHANGE ID: 01                                                                                                                                                                                                                                                                                                                                                                          |
|     UNPARTITIONED                                                                                                                                                                                                                                                                                                                                                                            |
|                                                                                                                                                                                                                                                                                                                                                                                              |
|   0:OlapScanNode                                                                                                                                                                                                                                                                                                                                                                             |
|      TABLE: dm_health1                                                                                                                                                                                                                                                                                                                                                                       |
|      PREAGGREGATION: OFF. Reason: None aggregate function                                                                                                                                                                                                                                                                                                                                    |
|      partitions=0/47                                                                                                                                                                                                                                                                                                                                                                         |
|      rollup: dm_health1                                                                                                                                                                                                                                                                                                                                                                      |
|      tabletRatio=0/0                                                                                                                                                                                                                                                                                                                                                                         |
|      tabletList=                                                                                                                                                                                                                                                                                                                                                                             |
|      cardinality=1                                                                                                                                                                                                                                                                                                                                                                           |
|      avgRowSize=25.0                                                                                                                                                                                                                                                                                                                                                                         |
|      numNodes=0                                                                                                                                                                                                                                                                                                                                                                              |
|      limit: 1                                                                                                                                                                                                                                                                                                                                                                                |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```


## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Review by kangkaisen — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 5 / 5 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/InsertPlanner.java|5|5|100.00%|[]|

**Review by kangkaisen — APPROVED** [review]

**Comment by ZiheLiu** [comment]
run starrocks_admit_test

**Review by ZiheLiu — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wangruin** [comment]
run starrocks_admit_test

**Review by HangyuanLiu — APPROVED** [review]

**Review by Youngwb — APPROVED** [review]

**Comment by Seaven** [comment]
@mergfiyio backport branch-2.2

**Comment by Seaven** [comment]
@Mergeifyio backport branch-2.2

**Comment by Seaven** [comment]
@Mergifyio backport branch-2.2

**Pull request merged**
