### PR TITLE
[BugFix] column names must be associated with slotIds when normalizing OlapScanNode accessing unpartitioned table

### PR DESCRIPTION
**Pull request by satanson**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：

For aggregation queres on unpartitioned or multicolumn-partitioned table, when generating digest components of cache key,  the same digest is produced for different queries. for an exanmple:
```
-- create unpartitioned table
CREATE TABLE if not exists t9(
REGION_CODE VARCHAR NOT NULL,
REGION_NAME VARCHAR NOT NULL,
v1 INT NOT NULL,
v2 DECIMAL(7,2) NOT NULL
) ENGINE=OLAP
PRIMARY KEY(`REGION_CODE`, `REGION_NAME`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`REGION_CODE`, `REGION_NAME`) BUCKETS 10
PROPERTIES(
"replication_num" = "1",
"in_memory" = "false",
"storage_format" = "default"
);

-- Q1
select REGION_CODE, percentile_cont(v1, 0.5) from t9 group by 1;
-- Q2
select REGION_NAME, percentile_cont(v1, 0.5) from t9 group by 1;
```
Q1 and Q2 use different columns as group-by columns, so they should generated different digest, but when normalizing OlapScanNode during calculating digests, the slotIds of columns  are not associated with its column names mistakenly. different columns can have the same slotId in the structural-similar queries (like Q1 and Q2), if we only use slotIds and ignored the column names underlying these slotIds, the semantic-inequivalent queries will generated the same digest unexpectedly.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 18 / 18 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/planner/OlapScanNode.java|18|18|100.00%|[]|

**Review by ZiheLiu — APPROVED** [review]

**Review by kangkaisen — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by satanson** [comment]
run starrocks_admit_test

**Comment by satanson** [comment]
run starrocks_admit_test

**Comment by satanson** [comment]
run starrocks_admit_test

**Comment by zuyu** [comment]
Branch 2.5 backport PR #16755

**Pull request merged**
