### PR TITLE
[Refactor] Remove query and insert statement parser / analyzer deprecated code

### PR DESCRIPTION
**Pull request by HangyuanLiu**
## What type of PR is this：
- [ ] bug
- [ ] feature
- [ ] enhancement
- [x] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #

## Problem Summary(Required) ：
[]

starrocks_pr_regression
http://39.101.206.100:8090/view/regression/job/starrocks_pr_regression/774/#showFailuresLink

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by HangyuanLiu** [comment]
run starrocks_be_unittest

**Comment by HangyuanLiu** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
run starrocks_clang-format

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 76 / 99 (76.77%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/service/FrontendServiceImpl.java|0|4|00.00%|[315, 316, 317, 318]|
|:large_blue_circle:|com/starrocks/analysis/Analyzer.java|0|1|00.00%|[290]|
|:large_blue_circle:|com/starrocks/qe/ConnectProcessor.java|1|2|50.00%|[243]|
|:large_blue_circle:|com/starrocks/analysis/Subquery.java|5|8|62.50%|[75, 83, 102]|
|:large_blue_circle:|com/starrocks/qe/StmtExecutor.java|7|10|70.00%|[249, 605, 606]|
|:large_blue_circle:|com/starrocks/sql/ast/InsertStmt.java|50|61|81.97%|[102, 103, 128, 145, 179, 180, 181, 182, 183, 184, 189]|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/CreateMaterializedViewStmt.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/parser/SqlParser.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/SetQualifier.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/ValueList.java|4|4|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 0 / 99 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|0|2|00.00%|[1546, 2355]|
|:large_blue_circle:|com/starrocks/analysis/CreateMaterializedViewStmt.java|0|3|00.00%|[174, 175, 176]|
|:large_blue_circle:|com/starrocks/service/FrontendServiceImpl.java|0|4|00.00%|[315, 316, 317, 318]|
|:large_blue_circle:|com/starrocks/sql/ast/InsertStmt.java|0|61|00.00%|[45, 48, 52, 54, 58, 60, 65, 68, 69, 70, 71, 72, 73, 74, 75, 78, 79, 80, 81, 82, 83, 86, 90, 91, 94, 98, 102, 103, 106, 107, 110, 114, 118, 119, 123, 128, 132, 136, 140, 141, 145, 150, 154, 158, 162, 163, 166, 167, 170, 174, 175, 179, 180, 181, 182, 183, 184, 188, 189, 191, 196]|
|:large_blue_circle:|com/starrocks/analysis/Subquery.java|0|8|00.00%|[60, 74, 75, 77, 83, 97, 102, 106]|
|:large_blue_circle:|com/starrocks/sql/parser/SqlParser.java|0|1|00.00%|[39]|
|:large_blue_circle:|com/starrocks/sql/ast/SetQualifier.java|0|3|00.00%|[4, 5, 6]|
|:large_blue_circle:|com/starrocks/qe/StmtExecutor.java|0|10|00.00%|[249, 304, 375, 604, 605, 606, 607, 608, 609, 707]|
|:large_blue_circle:|com/starrocks/analysis/Analyzer.java|0|1|00.00%|[290]|
|:large_blue_circle:|com/starrocks/qe/ConnectProcessor.java|0|2|00.00%|[194, 243]|
|:large_blue_circle:|com/starrocks/sql/ast/ValueList.java|0|4|00.00%|[13, 14, 15, 18]|

**Review by kangkaisen — APPROVED** [review]

**Review by Seaven — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wangruin** [comment]
run starrocks_fe_unittest

**Comment by wangruin** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 0 / 99 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|0|2|00.00%|[1546, 2355]|
|:large_blue_circle:|com/starrocks/analysis/CreateMaterializedViewStmt.java|0|3|00.00%|[174, 175, 176]|
|:large_blue_circle:|com/starrocks/service/FrontendServiceImpl.java|0|4|00.00%|[315, 316, 317, 318]|
|:large_blue_circle:|com/starrocks/sql/ast/InsertStmt.java|0|61|00.00%|[45, 48, 52, 54, 58, 60, 65, 68, 69, 70, 71, 72, 73, 74, 75, 78, 79, 80, 81, 82, 83, 86, 90, 91, 94, 98, 102, 103, 106, 107, 110, 114, 118, 119, 123, 128, 132, 136, 140, 141, 145, 150, 154, 158, 162, 163, 166, 167, 170, 174, 175, 179, 180, 181, 182, 183, 184, 188, 189, 191, 196]|
|:large_blue_circle:|com/starrocks/analysis/Subquery.java|0|8|00.00%|[60, 74, 75, 77, 83, 97, 102, 106]|
|:large_blue_circle:|com/starrocks/sql/parser/SqlParser.java|0|1|00.00%|[39]|
|:large_blue_circle:|com/starrocks/sql/ast/SetQualifier.java|0|3|00.00%|[4, 5, 6]|
|:large_blue_circle:|com/starrocks/qe/StmtExecutor.java|0|10|00.00%|[249, 304, 375, 604, 605, 606, 607, 608, 609, 707]|
|:large_blue_circle:|com/starrocks/analysis/Analyzer.java|0|1|00.00%|[290]|
|:large_blue_circle:|com/starrocks/qe/ConnectProcessor.java|0|2|00.00%|[194, 243]|
|:large_blue_circle:|com/starrocks/sql/ast/ValueList.java|0|4|00.00%|[13, 14, 15, 18]|

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 75 / 99 (75.76%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/service/FrontendServiceImpl.java|0|4|00.00%|[315, 316, 317, 318]|
|:large_blue_circle:|com/starrocks/analysis/Analyzer.java|0|1|00.00%|[290]|
|:large_blue_circle:|com/starrocks/qe/ConnectProcessor.java|0|2|00.00%|[194, 243]|
|:large_blue_circle:|com/starrocks/analysis/Subquery.java|5|8|62.50%|[75, 83, 102]|
|:large_blue_circle:|com/starrocks/qe/StmtExecutor.java|7|10|70.00%|[249, 605, 606]|
|:large_blue_circle:|com/starrocks/sql/ast/InsertStmt.java|50|61|81.97%|[102, 103, 128, 145, 179, 180, 181, 182, 183, 184, 189]|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/CreateMaterializedViewStmt.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/parser/SqlParser.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/SetQualifier.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/ValueList.java|4|4|100.00%|[]|

**Pull request merged**
